//! Defines every typed payload that can be persisted in the system database.

#[derive(Clone, Debug, PartialEq)]
pub(crate) enum SystemRow {
    TaxonomyRegistry {
        id: String,
        domain: String,
        purpose: String,
    },
    TaxonomyTerm {
        taxonomy_id: String,
        term_key: String,
        parent_term_key: Option<String>,
        label: String,
        normalized_label: String,
        aliases_json: String,
        sort_order: usize,
    },
    GeoPlace {
        id: String,
        place_type: String,
        parent_place_id: Option<String>,
        country_codes_json: String,
        latitude: Option<f64>,
        longitude: Option<f64>,
        name: String,
        normalized_name: String,
        aliases_json: String,
    },
    Life {
        id: String,
        domain_id: String,
        kingdom_id: Option<String>,
        phylum_id: Option<String>,
        class_id: Option<String>,
        order_id: Option<String>,
        family_id: Option<String>,
        genus_id: Option<String>,
        species_id: Option<String>,
        breed_id: Option<String>,
        variety_id: Option<String>,
        size_term_key: Option<String>,
        name: String,
        normalized_name: String,
        aliases_json: String,
        stage_metrics_json: Option<String>,
        content_json: String,
    },
    LifeOrigin {
        life_id: String,
        place_id: String,
        sort_order: usize,
    },
    Manufacturer {
        id: String,
        name: String,
        normalized_name: String,
        aliases_json: String,
        regions_json: String,
        website: Option<String>,
        content_json: String,
    },
    ActiveIngredient {
        id: String,
        name: String,
        normalized_name: String,
        aliases_json: String,
        regions_json: String,
        nomenclature_json: String,
        atc_vet_code: Option<String>,
        atc_vet_system: Option<String>,
        denominations_json: String,
        content_json: String,
    },
    Condition {
        id: String,
        name: String,
        normalized_name: String,
        aliases_json: String,
        regions_json: String,
        content_json: String,
    },
    Product {
        id: String,
        name: String,
        normalized_name: String,
        applicable_taxon_ids_json: String,
        applicable_life_stages_json: String,
        therapeutic_spectrum: Option<String>,
        aliases_json: String,
        manufacturer_id: String,
        regions_json: String,
        regulatory_identifiers_json: String,
        commercial_line: Option<String>,
        presentation_dosage: Option<String>,
        target_species_warnings_json: String,
        content_json: String,
    },
    EntityTaxonomy {
        entity_type: String,
        entity_id: String,
        taxonomy_id: String,
        term_key: String,
        sort_order: usize,
    },
    ProductActiveIngredient {
        product_id: String,
        active_ingredient_id: String,
        sort_order: usize,
    },
    TreatmentProtocol {
        id: String,
        kind: String,
        name: String,
        normalized_name: String,
        applicable_taxon_ids_json: String,
        observation: Option<String>,
    },
    TreatmentProtocolItem {
        protocol_id: String,
        product_id: String,
        sort_order: usize,
    },
    TreatmentProtocolDose {
        protocol_id: String,
        dose_id: String,
        label: String,
        validity_value: u32,
        validity_unit: String,
        sort_order: usize,
    },
    SearchTerm {
        entity_type: String,
        entity_id: String,
        value: String,
        normalized_value: String,
        provenance: String,
        sort_order: usize,
    },
    MediaReference {
        entity_type: String,
        entity_id: String,
        role: String,
        media_key: String,
        sort_order: usize,
    },
}
