import type { TranslationKey } from '$lib/i18n/index.js';

const knownPetSpeciesIds = ['canine', 'feline'] as const;

export type KnownPetSpecies = (typeof knownPetSpeciesIds)[number];
export type PetSpecies = KnownPetSpecies | (string & {});

export interface PetSpeciesOption {
	id: KnownPetSpecies;
	labelKey: TranslationKey;
	imagePath: string;
	fallbackImagePath: string;
}

interface PetBreedOptionBase {
	id: string;
	species: KnownPetSpecies;
	labelKey: TranslationKey;
	imagePath: string;
	fallbackImagePath: string;
}

const canineBreedFallback = '/images/pet-taxonomy/breeds/canine-placeholder.svg';
const felineBreedFallback = '/images/pet-taxonomy/breeds/feline-placeholder.svg';

function breedImage(id: string): string {
	return `/images/pet-taxonomy/breeds/${id}.webp`;
}

export const petSpeciesOptions = [
	{
		id: 'canine',
		labelKey: 'pet.speciesCanine',
		imagePath: '/images/pet-taxonomy/species/canine.webp',
		fallbackImagePath: '/images/pet-taxonomy/species/canine.svg'
	},
	{
		id: 'feline',
		labelKey: 'pet.speciesFeline',
		imagePath: '/images/pet-taxonomy/species/feline.webp',
		fallbackImagePath: '/images/pet-taxonomy/species/feline.svg'
	}
] as const satisfies readonly PetSpeciesOption[];

export const petBreedOptions = [
	{ id: 'mixed-breed', species: 'canine', labelKey: 'pet.breed.mixedBreed', imagePath: breedImage('mixed-breed'), fallbackImagePath: canineBreedFallback },
	{ id: 'shih-tzu', species: 'canine', labelKey: 'pet.breed.shihTzu', imagePath: breedImage('shih-tzu'), fallbackImagePath: canineBreedFallback },
	{ id: 'poodle', species: 'canine', labelKey: 'pet.breed.poodle', imagePath: breedImage('poodle'), fallbackImagePath: canineBreedFallback },
	{ id: 'pinscher', species: 'canine', labelKey: 'pet.breed.pinscher', imagePath: breedImage('pinscher'), fallbackImagePath: canineBreedFallback },
	{ id: 'pit-bull', species: 'canine', labelKey: 'pet.breed.pitBull', imagePath: breedImage('pit-bull'), fallbackImagePath: canineBreedFallback },
	{ id: 'lhasa-apso', species: 'canine', labelKey: 'pet.breed.lhasaApso', imagePath: breedImage('lhasa-apso'), fallbackImagePath: canineBreedFallback },
	{ id: 'dachshund', species: 'canine', labelKey: 'pet.breed.dachshund', imagePath: breedImage('dachshund'), fallbackImagePath: canineBreedFallback },
	{ id: 'rottweiler', species: 'canine', labelKey: 'pet.breed.rottweiler', imagePath: breedImage('rottweiler'), fallbackImagePath: canineBreedFallback },
	{ id: 'labrador-retriever', species: 'canine', labelKey: 'pet.breed.labradorRetriever', imagePath: breedImage('labrador-retriever'), fallbackImagePath: canineBreedFallback },
	{ id: 'yorkshire-terrier', species: 'canine', labelKey: 'pet.breed.yorkshireTerrier', imagePath: breedImage('yorkshire-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'german-shepherd', species: 'canine', labelKey: 'pet.breed.germanShepherd', imagePath: breedImage('german-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'chow-chow', species: 'canine', labelKey: 'pet.breed.chowChow', imagePath: breedImage('chow-chow'), fallbackImagePath: canineBreedFallback },
	{ id: 'pug', species: 'canine', labelKey: 'pet.breed.pug', imagePath: breedImage('pug'), fallbackImagePath: canineBreedFallback },
	{ id: 'maltese', species: 'canine', labelKey: 'pet.breed.maltese', imagePath: breedImage('maltese'), fallbackImagePath: canineBreedFallback },
	{ id: 'border-collie', species: 'canine', labelKey: 'pet.breed.borderCollie', imagePath: breedImage('border-collie'), fallbackImagePath: canineBreedFallback },
	{ id: 'golden-retriever', species: 'canine', labelKey: 'pet.breed.goldenRetriever', imagePath: breedImage('golden-retriever'), fallbackImagePath: canineBreedFallback },
	{ id: 'australian-cattle-dog', species: 'canine', labelKey: 'pet.breed.australianCattleDog', imagePath: breedImage('australian-cattle-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'australian-stumpy-tail-cattle-dog', species: 'canine', labelKey: 'pet.breed.australianStumpyTailCattleDog', imagePath: breedImage('australian-stumpy-tail-cattle-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'boxer', species: 'canine', labelKey: 'pet.breed.boxer', imagePath: breedImage('boxer'), fallbackImagePath: canineBreedFallback },
	{ id: 'brazilian-terrier', species: 'canine', labelKey: 'pet.breed.brazilianTerrier', imagePath: breedImage('brazilian-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'cocker-spaniel', species: 'canine', labelKey: 'pet.breed.cockerSpaniel', imagePath: breedImage('cocker-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'german-spitz', species: 'canine', labelKey: 'pet.breed.germanSpitz', imagePath: breedImage('german-spitz'), fallbackImagePath: canineBreedFallback },
	{ id: 'pekingese', species: 'canine', labelKey: 'pet.breed.pekingese', imagePath: breedImage('pekingese'), fallbackImagePath: canineBreedFallback },
	{ id: 'fila-brasileiro', species: 'canine', labelKey: 'pet.breed.filaBrasileiro', imagePath: breedImage('fila-brasileiro'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-bully', species: 'canine', labelKey: 'pet.breed.americanBully', imagePath: breedImage('american-bully'), fallbackImagePath: canineBreedFallback },
	{ id: 'french-bulldog', species: 'canine', labelKey: 'pet.breed.frenchBulldog', imagePath: breedImage('french-bulldog'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-foxhound', species: 'canine', labelKey: 'pet.breed.americanFoxhound', imagePath: breedImage('american-foxhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'siberian-husky', species: 'canine', labelKey: 'pet.breed.siberianHusky', imagePath: breedImage('siberian-husky'), fallbackImagePath: canineBreedFallback },
	{ id: 'shar-pei', species: 'canine', labelKey: 'pet.breed.sharPei', imagePath: breedImage('shar-pei'), fallbackImagePath: canineBreedFallback },
	{ id: 'beagle', species: 'canine', labelKey: 'pet.breed.beagle', imagePath: breedImage('beagle'), fallbackImagePath: canineBreedFallback },
	{ id: 'dalmatian', species: 'canine', labelKey: 'pet.breed.dalmatian', imagePath: breedImage('dalmatian'), fallbackImagePath: canineBreedFallback },
	{ id: 'schnauzer', species: 'canine', labelKey: 'pet.breed.schnauzer', imagePath: breedImage('schnauzer'), fallbackImagePath: canineBreedFallback },
	{ id: 'belgian-shepherd', species: 'canine', labelKey: 'pet.breed.belgianShepherd', imagePath: breedImage('belgian-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'english-bulldog', species: 'canine', labelKey: 'pet.breed.englishBulldog', imagePath: breedImage('english-bulldog'), fallbackImagePath: canineBreedFallback },
	{ id: 'akita', species: 'canine', labelKey: 'pet.breed.akita', imagePath: breedImage('akita'), fallbackImagePath: canineBreedFallback },
	{ id: 'australian-shepherd', species: 'canine', labelKey: 'pet.breed.australianShepherd', imagePath: breedImage('australian-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'basset-hound', species: 'canine', labelKey: 'pet.breed.bassetHound', imagePath: breedImage('basset-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'bernese-mountain-dog', species: 'canine', labelKey: 'pet.breed.berneseMountainDog', imagePath: breedImage('bernese-mountain-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'boston-terrier', species: 'canine', labelKey: 'pet.breed.bostonTerrier', imagePath: breedImage('boston-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'cane-corso', species: 'canine', labelKey: 'pet.breed.caneCorso', imagePath: breedImage('cane-corso'), fallbackImagePath: canineBreedFallback },
	{ id: 'chihuahua', species: 'canine', labelKey: 'pet.breed.chihuahua', imagePath: breedImage('chihuahua'), fallbackImagePath: canineBreedFallback },
	{ id: 'doberman', species: 'canine', labelKey: 'pet.breed.doberman', imagePath: breedImage('doberman'), fallbackImagePath: canineBreedFallback },
	{ id: 'great-dane', species: 'canine', labelKey: 'pet.breed.greatDane', imagePath: breedImage('great-dane'), fallbackImagePath: canineBreedFallback },
	{ id: 'jack-russell-terrier', species: 'canine', labelKey: 'pet.breed.jackRussellTerrier', imagePath: breedImage('jack-russell-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'samoyed', species: 'canine', labelKey: 'pet.breed.samoyed', imagePath: breedImage('samoyed'), fallbackImagePath: canineBreedFallback },
	{ id: 'weimaraner', species: 'canine', labelKey: 'pet.breed.weimaraner', imagePath: breedImage('weimaraner'), fallbackImagePath: canineBreedFallback },
	{ id: 'affenpinscher', species: 'canine', labelKey: 'pet.breed.affenpinscher', imagePath: breedImage('affenpinscher'), fallbackImagePath: canineBreedFallback },
	{ id: 'afghan-hound', species: 'canine', labelKey: 'pet.breed.afghanHound', imagePath: breedImage('afghan-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'africanis', species: 'canine', labelKey: 'pet.breed.africanis', imagePath: breedImage('africanis'), fallbackImagePath: canineBreedFallback },
	{ id: 'aidi', species: 'canine', labelKey: 'pet.breed.aidi', imagePath: breedImage('aidi'), fallbackImagePath: canineBreedFallback },
	{ id: 'airedale-terrier', species: 'canine', labelKey: 'pet.breed.airedaleTerrier', imagePath: breedImage('airedale-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'basenji', species: 'canine', labelKey: 'pet.breed.basenji', imagePath: breedImage('basenji'), fallbackImagePath: canineBreedFallback },
	{ id: 'bichon-frise', species: 'canine', labelKey: 'pet.breed.bichonFrise', imagePath: breedImage('bichon-frise'), fallbackImagePath: canineBreedFallback },
	{ id: 'bloodhound', species: 'canine', labelKey: 'pet.breed.bloodhound', imagePath: breedImage('bloodhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'borzoi', species: 'canine', labelKey: 'pet.breed.borzoi', imagePath: breedImage('borzoi'), fallbackImagePath: canineBreedFallback },
	{ id: 'bull-terrier', species: 'canine', labelKey: 'pet.breed.bullTerrier', imagePath: breedImage('bull-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'bullmastiff', species: 'canine', labelKey: 'pet.breed.bullmastiff', imagePath: breedImage('bullmastiff'), fallbackImagePath: canineBreedFallback },
	{ id: 'cavalier-king-charles-spaniel', species: 'canine', labelKey: 'pet.breed.cavalierKingCharlesSpaniel', imagePath: breedImage('cavalier-king-charles-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'collie', species: 'canine', labelKey: 'pet.breed.collie', imagePath: breedImage('collie'), fallbackImagePath: canineBreedFallback },
	{ id: 'coton-de-tulear', species: 'canine', labelKey: 'pet.breed.cotonDeTulear', imagePath: breedImage('coton-de-tulear'), fallbackImagePath: canineBreedFallback },
	{ id: 'dogo-argentino', species: 'canine', labelKey: 'pet.breed.dogoArgentino', imagePath: breedImage('dogo-argentino'), fallbackImagePath: canineBreedFallback },
	{ id: 'dogue-de-bordeaux', species: 'canine', labelKey: 'pet.breed.dogueDeBordeaux', imagePath: breedImage('dogue-de-bordeaux'), fallbackImagePath: canineBreedFallback },
	{ id: 'english-setter', species: 'canine', labelKey: 'pet.breed.englishSetter', imagePath: breedImage('english-setter'), fallbackImagePath: canineBreedFallback },
	{ id: 'fox-terrier', species: 'canine', labelKey: 'pet.breed.foxTerrier', imagePath: breedImage('fox-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'greyhound', species: 'canine', labelKey: 'pet.breed.greyhound', imagePath: breedImage('greyhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'havanese', species: 'canine', labelKey: 'pet.breed.havanese', imagePath: breedImage('havanese'), fallbackImagePath: canineBreedFallback },
	{ id: 'irish-setter', species: 'canine', labelKey: 'pet.breed.irishSetter', imagePath: breedImage('irish-setter'), fallbackImagePath: canineBreedFallback },
	{ id: 'italian-greyhound', species: 'canine', labelKey: 'pet.breed.italianGreyhound', imagePath: breedImage('italian-greyhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'japanese-spitz', species: 'canine', labelKey: 'pet.breed.japaneseSpitz', imagePath: breedImage('japanese-spitz'), fallbackImagePath: canineBreedFallback },
	{ id: 'hokkaido', species: 'canine', labelKey: 'pet.breed.hokkaido', imagePath: breedImage('hokkaido'), fallbackImagePath: canineBreedFallback },
	{ id: 'kai-ken', species: 'canine', labelKey: 'pet.breed.kaiKen', imagePath: breedImage('kai-ken'), fallbackImagePath: canineBreedFallback },
	{ id: 'kishu', species: 'canine', labelKey: 'pet.breed.kishu', imagePath: breedImage('kishu'), fallbackImagePath: canineBreedFallback },
	{ id: 'shikoku', species: 'canine', labelKey: 'pet.breed.shikoku', imagePath: breedImage('shikoku'), fallbackImagePath: canineBreedFallback },
	{ id: 'tosa', species: 'canine', labelKey: 'pet.breed.tosa', imagePath: breedImage('tosa'), fallbackImagePath: canineBreedFallback },
	{ id: 'japanese-terrier', species: 'canine', labelKey: 'pet.breed.japaneseTerrier', imagePath: breedImage('japanese-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'mastiff', species: 'canine', labelKey: 'pet.breed.mastiff', imagePath: breedImage('mastiff'), fallbackImagePath: canineBreedFallback },
	{ id: 'papillon', species: 'canine', labelKey: 'pet.breed.papillon', imagePath: breedImage('papillon'), fallbackImagePath: canineBreedFallback },
	{ id: 'pembroke-welsh-corgi', species: 'canine', labelKey: 'pet.breed.pembrokeWelshCorgi', imagePath: breedImage('pembroke-welsh-corgi'), fallbackImagePath: canineBreedFallback },
	{ id: 'pointer', species: 'canine', labelKey: 'pet.breed.pointer', imagePath: breedImage('pointer'), fallbackImagePath: canineBreedFallback },
	{ id: 'portuguese-water-dog', species: 'canine', labelKey: 'pet.breed.portugueseWaterDog', imagePath: breedImage('portuguese-water-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'saint-bernard', species: 'canine', labelKey: 'pet.breed.saintBernard', imagePath: breedImage('saint-bernard'), fallbackImagePath: canineBreedFallback },
	{ id: 'shetland-sheepdog', species: 'canine', labelKey: 'pet.breed.shetlandSheepdog', imagePath: breedImage('shetland-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'shiba-inu', species: 'canine', labelKey: 'pet.breed.shibaInu', imagePath: breedImage('shiba-inu'), fallbackImagePath: canineBreedFallback },
	{ id: 'whippet', species: 'canine', labelKey: 'pet.breed.whippet', imagePath: breedImage('whippet'), fallbackImagePath: canineBreedFallback },
	{ id: 'alaskan-malamute', species: 'canine', labelKey: 'pet.breed.alaskanMalamute', imagePath: breedImage('alaskan-malamute'), fallbackImagePath: canineBreedFallback },
	{ id: 'anatolian-shepherd-dog', species: 'canine', labelKey: 'pet.breed.anatolianShepherdDog', imagePath: breedImage('anatolian-shepherd-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'armant', species: 'canine', labelKey: 'pet.breed.armant', imagePath: breedImage('armant'), fallbackImagePath: canineBreedFallback },
	{ id: 'azawakh', species: 'canine', labelKey: 'pet.breed.azawakh', imagePath: breedImage('azawakh'), fallbackImagePath: canineBreedFallback },
	{ id: 'barbet', species: 'canine', labelKey: 'pet.breed.barbet', imagePath: breedImage('barbet'), fallbackImagePath: canineBreedFallback },
	{ id: 'beauceron', species: 'canine', labelKey: 'pet.breed.beauceron', imagePath: breedImage('beauceron'), fallbackImagePath: canineBreedFallback },
	{ id: 'belgian-malinois', species: 'canine', labelKey: 'pet.breed.belgianMalinois', imagePath: breedImage('belgian-malinois'), fallbackImagePath: canineBreedFallback },
	{ id: 'biewer-terrier', species: 'canine', labelKey: 'pet.breed.biewerTerrier', imagePath: breedImage('biewer-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'black-russian-terrier', species: 'canine', labelKey: 'pet.breed.blackRussianTerrier', imagePath: breedImage('black-russian-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'boerboel', species: 'canine', labelKey: 'pet.breed.boerboel', imagePath: breedImage('boerboel'), fallbackImagePath: canineBreedFallback },
	{ id: 'briard', species: 'canine', labelKey: 'pet.breed.briard', imagePath: breedImage('briard'), fallbackImagePath: canineBreedFallback },
	{ id: 'brussels-griffon', species: 'canine', labelKey: 'pet.breed.brusselsGriffon', imagePath: breedImage('brussels-griffon'), fallbackImagePath: canineBreedFallback },
	{ id: 'cardigan-welsh-corgi', species: 'canine', labelKey: 'pet.breed.cardiganWelshCorgi', imagePath: breedImage('cardigan-welsh-corgi'), fallbackImagePath: canineBreedFallback },
	{ id: 'chesapeake-bay-retriever', species: 'canine', labelKey: 'pet.breed.chesapeakeBayRetriever', imagePath: breedImage('chesapeake-bay-retriever'), fallbackImagePath: canineBreedFallback },
	{ id: 'chinese-crested', species: 'canine', labelKey: 'pet.breed.chineseCrested', imagePath: breedImage('chinese-crested'), fallbackImagePath: canineBreedFallback },
	{ id: 'clumber-spaniel', species: 'canine', labelKey: 'pet.breed.clumberSpaniel', imagePath: breedImage('clumber-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'curly-coated-retriever', species: 'canine', labelKey: 'pet.breed.curlyCoatedRetriever', imagePath: breedImage('curly-coated-retriever'), fallbackImagePath: canineBreedFallback },
	{ id: 'english-cocker-spaniel', species: 'canine', labelKey: 'pet.breed.englishCockerSpaniel', imagePath: breedImage('english-cocker-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'english-springer-spaniel', species: 'canine', labelKey: 'pet.breed.englishSpringerSpaniel', imagePath: breedImage('english-springer-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'flat-coated-retriever', species: 'canine', labelKey: 'pet.breed.flatCoatedRetriever', imagePath: breedImage('flat-coated-retriever'), fallbackImagePath: canineBreedFallback },
	{ id: 'gordon-setter', species: 'canine', labelKey: 'pet.breed.gordonSetter', imagePath: breedImage('gordon-setter'), fallbackImagePath: canineBreedFallback },
	{ id: 'irish-wolfhound', species: 'canine', labelKey: 'pet.breed.irishWolfhound', imagePath: breedImage('irish-wolfhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'keeshond', species: 'canine', labelKey: 'pet.breed.keeshond', imagePath: breedImage('keeshond'), fallbackImagePath: canineBreedFallback },
	{ id: 'komondor', species: 'canine', labelKey: 'pet.breed.komondor', imagePath: breedImage('komondor'), fallbackImagePath: canineBreedFallback },
	{ id: 'kuvasz', species: 'canine', labelKey: 'pet.breed.kuvasz', imagePath: breedImage('kuvasz'), fallbackImagePath: canineBreedFallback },
	{ id: 'leonberger', species: 'canine', labelKey: 'pet.breed.leonberger', imagePath: breedImage('leonberger'), fallbackImagePath: canineBreedFallback },
	{ id: 'miniature-pinscher', species: 'canine', labelKey: 'pet.breed.miniaturePinscher', imagePath: breedImage('miniature-pinscher'), fallbackImagePath: canineBreedFallback },
	{ id: 'newfoundland', species: 'canine', labelKey: 'pet.breed.newfoundland', imagePath: breedImage('newfoundland'), fallbackImagePath: canineBreedFallback },
	{ id: 'norfolk-terrier', species: 'canine', labelKey: 'pet.breed.norfolkTerrier', imagePath: breedImage('norfolk-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'norwich-terrier', species: 'canine', labelKey: 'pet.breed.norwichTerrier', imagePath: breedImage('norwich-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'old-english-sheepdog', species: 'canine', labelKey: 'pet.breed.oldEnglishSheepdog', imagePath: breedImage('old-english-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'pomeranian', species: 'canine', labelKey: 'pet.breed.pomeranian', imagePath: breedImage('pomeranian'), fallbackImagePath: canineBreedFallback },
	{ id: 'rhodesian-ridgeback', species: 'canine', labelKey: 'pet.breed.rhodesianRidgeback', imagePath: breedImage('rhodesian-ridgeback'), fallbackImagePath: canineBreedFallback },
	{ id: 'saluki', species: 'canine', labelKey: 'pet.breed.saluki', imagePath: breedImage('saluki'), fallbackImagePath: canineBreedFallback },
	{ id: 'sloughi', species: 'canine', labelKey: 'pet.breed.sloughi', imagePath: breedImage('sloughi'), fallbackImagePath: canineBreedFallback },
	{ id: 'scottish-terrier', species: 'canine', labelKey: 'pet.breed.scottishTerrier', imagePath: breedImage('scottish-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'staffordshire-bull-terrier', species: 'canine', labelKey: 'pet.breed.staffordshireBullTerrier', imagePath: breedImage('staffordshire-bull-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'west-highland-white-terrier', species: 'canine', labelKey: 'pet.breed.westHighlandWhiteTerrier', imagePath: breedImage('west-highland-white-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'brazilian-pit-monster', species: 'canine', labelKey: 'pet.breed.brazilianPitMonster', imagePath: breedImage('brazilian-pit-monster'), fallbackImagePath: canineBreedFallback },
	{ id: 'gaucho-sheepdog', species: 'canine', labelKey: 'pet.breed.gauchoSheepdog', imagePath: breedImage('gaucho-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'dogo-brasileiro', species: 'canine', labelKey: 'pet.breed.dogoBrasileiro', imagePath: breedImage('dogo-brasileiro'), fallbackImagePath: canineBreedFallback },
	{ id: 'campeiro-bulldog', species: 'canine', labelKey: 'pet.breed.campeiroBulldog', imagePath: breedImage('campeiro-bulldog'), fallbackImagePath: canineBreedFallback },
	{ id: 'rastreador-brasileiro', species: 'canine', labelKey: 'pet.breed.rastreadorBrasileiro', imagePath: breedImage('rastreador-brasileiro'), fallbackImagePath: canineBreedFallback },
	{ id: 'veadeiro-pampeano', species: 'canine', labelKey: 'pet.breed.veadeiroPampeano', imagePath: breedImage('veadeiro-pampeano'), fallbackImagePath: canineBreedFallback },
	{ id: 'pastor-da-mantiqueira', species: 'canine', labelKey: 'pet.breed.pastorDaMantiqueira', imagePath: breedImage('pastor-da-mantiqueira'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-staffordshire-terrier', species: 'canine', labelKey: 'pet.breed.americanStaffordshireTerrier', imagePath: breedImage('american-staffordshire-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-bulldog', species: 'canine', labelKey: 'pet.breed.americanBulldog', imagePath: breedImage('american-bulldog'), fallbackImagePath: canineBreedFallback },
	{ id: 'olde-english-bulldogge', species: 'canine', labelKey: 'pet.breed.oldeEnglishBulldogge', imagePath: breedImage('olde-english-bulldogge'), fallbackImagePath: canineBreedFallback },
	{ id: 'presa-canario', species: 'canine', labelKey: 'pet.breed.presaCanario', imagePath: breedImage('presa-canario'), fallbackImagePath: canineBreedFallback },
	{ id: 'catahoula-leopard-dog', species: 'canine', labelKey: 'pet.breed.catahoulaLeopardDog', imagePath: breedImage('catahoula-leopard-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'carolina-dog', species: 'canine', labelKey: 'pet.breed.carolinaDog', imagePath: breedImage('carolina-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'rat-terrier', species: 'canine', labelKey: 'pet.breed.ratTerrier', imagePath: breedImage('rat-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'toy-fox-terrier', species: 'canine', labelKey: 'pet.breed.toyFoxTerrier', imagePath: breedImage('toy-fox-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-eskimo-dog', species: 'canine', labelKey: 'pet.breed.americanEskimoDog', imagePath: breedImage('american-eskimo-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'miniature-american-shepherd', species: 'canine', labelKey: 'pet.breed.miniatureAmericanShepherd', imagePath: breedImage('miniature-american-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'boykin-spaniel', species: 'canine', labelKey: 'pet.breed.boykinSpaniel', imagePath: breedImage('boykin-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-water-spaniel', species: 'canine', labelKey: 'pet.breed.americanWaterSpaniel', imagePath: breedImage('american-water-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-english-coonhound', species: 'canine', labelKey: 'pet.breed.americanEnglishCoonhound', imagePath: breedImage('american-english-coonhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-hairless-terrier', species: 'canine', labelKey: 'pet.breed.americanHairlessTerrier', imagePath: breedImage('american-hairless-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-leopard-hound', species: 'canine', labelKey: 'pet.breed.americanLeopardHound', imagePath: breedImage('american-leopard-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'black-mouth-cur', species: 'canine', labelKey: 'pet.breed.blackMouthCur', imagePath: breedImage('black-mouth-cur'), fallbackImagePath: canineBreedFallback },
	{ id: 'blue-lacy', species: 'canine', labelKey: 'pet.breed.blueLacy', imagePath: breedImage('blue-lacy'), fallbackImagePath: canineBreedFallback },
	{ id: 'mountain-cur', species: 'canine', labelKey: 'pet.breed.mountainCur', imagePath: breedImage('mountain-cur'), fallbackImagePath: canineBreedFallback },
	{ id: 'mcnab', species: 'canine', labelKey: 'pet.breed.mcnab', imagePath: breedImage('mcnab'), fallbackImagePath: canineBreedFallback },
	{ id: 'silken-windhound', species: 'canine', labelKey: 'pet.breed.silkenWindhound', imagePath: breedImage('silken-windhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'teddy-roosevelt-terrier', species: 'canine', labelKey: 'pet.breed.teddyRooseveltTerrier', imagePath: breedImage('teddy-roosevelt-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'treeing-tennessee-brindle', species: 'canine', labelKey: 'pet.breed.treeingTennesseeBrindle', imagePath: breedImage('treeing-tennessee-brindle'), fallbackImagePath: canineBreedFallback },
	{ id: 'black-and-tan-coonhound', species: 'canine', labelKey: 'pet.breed.blackAndTanCoonhound', imagePath: breedImage('black-and-tan-coonhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'bluetick-coonhound', species: 'canine', labelKey: 'pet.breed.bluetickCoonhound', imagePath: breedImage('bluetick-coonhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'redbone-coonhound', species: 'canine', labelKey: 'pet.breed.redboneCoonhound', imagePath: breedImage('redbone-coonhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'treeing-walker-coonhound', species: 'canine', labelKey: 'pet.breed.treeingWalkerCoonhound', imagePath: breedImage('treeing-walker-coonhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'plott-hound', species: 'canine', labelKey: 'pet.breed.plottHound', imagePath: breedImage('plott-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'nova-scotia-duck-tolling-retriever', species: 'canine', labelKey: 'pet.breed.novaScotiaDuckTollingRetriever', imagePath: breedImage('nova-scotia-duck-tolling-retriever'), fallbackImagePath: canineBreedFallback },
	{ id: 'canadian-eskimo-dog', species: 'canine', labelKey: 'pet.breed.canadianEskimoDog', imagePath: breedImage('canadian-eskimo-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'greenland-dog', species: 'canine', labelKey: 'pet.breed.greenlandDog', imagePath: breedImage('greenland-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'chinook', species: 'canine', labelKey: 'pet.breed.chinook', imagePath: breedImage('chinook'), fallbackImagePath: canineBreedFallback },
	{ id: 'xoloitzcuintli', species: 'canine', labelKey: 'pet.breed.xoloitzcuintli', imagePath: breedImage('xoloitzcuintli'), fallbackImagePath: canineBreedFallback },
	{ id: 'calupoh', species: 'canine', labelKey: 'pet.breed.calupoh', imagePath: breedImage('calupoh'), fallbackImagePath: canineBreedFallback },
	{ id: 'peruvian-inca-orchid', species: 'canine', labelKey: 'pet.breed.peruvianIncaOrchid', imagePath: breedImage('peruvian-inca-orchid'), fallbackImagePath: canineBreedFallback },
	{ id: 'chilean-terrier', species: 'canine', labelKey: 'pet.breed.chileanTerrier', imagePath: breedImage('chilean-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'cimarron-uruguayo', species: 'canine', labelKey: 'pet.breed.cimarronUruguayo', imagePath: breedImage('cimarron-uruguayo'), fallbackImagePath: canineBreedFallback },
	{ id: 'mucuchies', species: 'canine', labelKey: 'pet.breed.mucuchies', imagePath: breedImage('mucuchies'), fallbackImagePath: canineBreedFallback },
	{ id: 'gran-mastin-de-borinquen', species: 'canine', labelKey: 'pet.breed.granMastinDeBorinquen', imagePath: breedImage('gran-mastin-de-borinquen'), fallbackImagePath: canineBreedFallback },
	{ id: 'argentine-pila-dog', species: 'canine', labelKey: 'pet.breed.argentinePilaDog', imagePath: breedImage('argentine-pila-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'boca-preta-sertanejo', species: 'canine', labelKey: 'pet.breed.bocaPretaSertanejo', imagePath: breedImage('boca-preta-sertanejo'), fallbackImagePath: canineBreedFallback },
	{ id: 'caramelo', species: 'canine', labelKey: 'pet.breed.caramelo', imagePath: breedImage('caramelo'), fallbackImagePath: canineBreedFallback },
	{ id: 'original-fila-brasileiro', species: 'canine', labelKey: 'pet.breed.originalFilaBrasileiro', imagePath: breedImage('original-fila-brasileiro'), fallbackImagePath: canineBreedFallback },
	{ id: 'serrano-bulldog', species: 'canine', labelKey: 'pet.breed.serranoBulldog', imagePath: breedImage('serrano-bulldog'), fallbackImagePath: canineBreedFallback },
	{ id: 'boiadeiro-pantaneiro', species: 'canine', labelKey: 'pet.breed.boiadeiroPantaneiro', imagePath: breedImage('boiadeiro-pantaneiro'), fallbackImagePath: canineBreedFallback },
	{ id: 'argentine-polar-dog', species: 'canine', labelKey: 'pet.breed.argentinePolarDog', imagePath: breedImage('argentine-polar-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'fuegian-dog', species: 'canine', labelKey: 'pet.breed.fuegianDog', imagePath: breedImage('fuegian-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'patagonian-sheepdog', species: 'canine', labelKey: 'pet.breed.patagonianSheepdog', imagePath: breedImage('patagonian-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'chiribaya-dog', species: 'canine', labelKey: 'pet.breed.chiribayaDog', imagePath: breedImage('chiribaya-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'colombian-fino-hound', species: 'canine', labelKey: 'pet.breed.colombianFinoHound', imagePath: breedImage('colombian-fino-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'ecuadorian-hairless-dog', species: 'canine', labelKey: 'pet.breed.ecuadorianHairlessDog', imagePath: breedImage('ecuadorian-hairless-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'khala', species: 'canine', labelKey: 'pet.breed.khala', imagePath: breedImage('khala'), fallbackImagePath: canineBreedFallback },
	{ id: 'perro-pampa-argentino', species: 'canine', labelKey: 'pet.breed.perroPampaArgentino', imagePath: breedImage('perro-pampa-argentino'), fallbackImagePath: canineBreedFallback },
	{ id: 'double-nosed-andean-tiger-hound', species: 'canine', labelKey: 'pet.breed.doubleNosedAndeanTigerHound', imagePath: breedImage('double-nosed-andean-tiger-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'alaskan-klee-kai', species: 'canine', labelKey: 'pet.breed.alaskanKleeKai', imagePath: breedImage('alaskan-klee-kai'), fallbackImagePath: canineBreedFallback },
	{ id: 'dutch-shepherd', species: 'canine', labelKey: 'pet.breed.dutchShepherd', imagePath: breedImage('dutch-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'great-pyrenees', species: 'canine', labelKey: 'pet.breed.greatPyrenees', imagePath: breedImage('great-pyrenees'), fallbackImagePath: canineBreedFallback },
	{ id: 'german-shorthaired-pointer', species: 'canine', labelKey: 'pet.breed.germanShorthairedPointer', imagePath: breedImage('german-shorthaired-pointer'), fallbackImagePath: canineBreedFallback },
	{ id: 'vizsla', species: 'canine', labelKey: 'pet.breed.vizsla', imagePath: breedImage('vizsla'), fallbackImagePath: canineBreedFallback },
	{ id: 'brittany', species: 'canine', labelKey: 'pet.breed.brittany', imagePath: breedImage('brittany'), fallbackImagePath: canineBreedFallback },
	{ id: 'german-wirehaired-pointer', species: 'canine', labelKey: 'pet.breed.germanWirehairedPointer', imagePath: breedImage('german-wirehaired-pointer'), fallbackImagePath: canineBreedFallback },
	{ id: 'wirehaired-pointing-griffon', species: 'canine', labelKey: 'pet.breed.wirehairedPointingGriffon', imagePath: breedImage('wirehaired-pointing-griffon'), fallbackImagePath: canineBreedFallback },
	{ id: 'tibetan-mastiff', species: 'canine', labelKey: 'pet.breed.tibetanMastiff', imagePath: breedImage('tibetan-mastiff'), fallbackImagePath: canineBreedFallback },
	{ id: 'maremma-sheepdog', species: 'canine', labelKey: 'pet.breed.maremmaSheepdog', imagePath: breedImage('maremma-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'caucasian-shepherd-dog', species: 'canine', labelKey: 'pet.breed.caucasianShepherdDog', imagePath: breedImage('caucasian-shepherd-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'kangal-shepherd-dog', species: 'canine', labelKey: 'pet.breed.kangalShepherdDog', imagePath: breedImage('kangal-shepherd-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'akbash', species: 'canine', labelKey: 'pet.breed.akbash', imagePath: breedImage('akbash'), fallbackImagePath: canineBreedFallback },
	{ id: 'aksaray-malaklisi', species: 'canine', labelKey: 'pet.breed.aksarayMalaklisi', imagePath: breedImage('aksaray-malaklisi'), fallbackImagePath: canineBreedFallback },
	{ id: 'kars-dog', species: 'canine', labelKey: 'pet.breed.karsDog', imagePath: breedImage('kars-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'armenian-gampr', species: 'canine', labelKey: 'pet.breed.armenianGampr', imagePath: breedImage('armenian-gampr'), fallbackImagePath: canineBreedFallback },
	{ id: 'georgian-shepherd', species: 'canine', labelKey: 'pet.breed.georgianShepherd', imagePath: breedImage('georgian-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'sarabi-dog', species: 'canine', labelKey: 'pet.breed.sarabiDog', imagePath: breedImage('sarabi-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'zerdava', species: 'canine', labelKey: 'pet.breed.zerdava', imagePath: breedImage('zerdava'), fallbackImagePath: canineBreedFallback },
	{ id: 'tarsus-catalburun', species: 'canine', labelKey: 'pet.breed.tarsusCatalburun', imagePath: breedImage('tarsus-catalburun'), fallbackImagePath: canineBreedFallback },
	{ id: 'labradoodle', species: 'canine', labelKey: 'pet.breed.labradoodle', imagePath: breedImage('labradoodle'), fallbackImagePath: canineBreedFallback },
	{ id: 'goldendoodle', species: 'canine', labelKey: 'pet.breed.goldendoodle', imagePath: breedImage('goldendoodle'), fallbackImagePath: canineBreedFallback },
	{ id: 'cockapoo', species: 'canine', labelKey: 'pet.breed.cockapoo', imagePath: breedImage('cockapoo'), fallbackImagePath: canineBreedFallback },
	{ id: 'cavapoo', species: 'canine', labelKey: 'pet.breed.cavapoo', imagePath: breedImage('cavapoo'), fallbackImagePath: canineBreedFallback },
	{ id: 'miniature-schnauzer', species: 'canine', labelKey: 'pet.breed.miniatureSchnauzer', imagePath: breedImage('miniature-schnauzer'), fallbackImagePath: canineBreedFallback },
	{ id: 'giant-schnauzer', species: 'canine', labelKey: 'pet.breed.giantSchnauzer', imagePath: breedImage('giant-schnauzer'), fallbackImagePath: canineBreedFallback },
	{ id: 'english-toy-spaniel', species: 'canine', labelKey: 'pet.breed.englishToySpaniel', imagePath: breedImage('english-toy-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'japanese-chin', species: 'canine', labelKey: 'pet.breed.japaneseChin', imagePath: breedImage('japanese-chin'), fallbackImagePath: canineBreedFallback },
	{ id: 'tibetan-spaniel', species: 'canine', labelKey: 'pet.breed.tibetanSpaniel', imagePath: breedImage('tibetan-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'tibetan-terrier', species: 'canine', labelKey: 'pet.breed.tibetanTerrier', imagePath: breedImage('tibetan-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'border-terrier', species: 'canine', labelKey: 'pet.breed.borderTerrier', imagePath: breedImage('border-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'cairn-terrier', species: 'canine', labelKey: 'pet.breed.cairnTerrier', imagePath: breedImage('cairn-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'australian-terrier', species: 'canine', labelKey: 'pet.breed.australianTerrier', imagePath: breedImage('australian-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'silky-terrier', species: 'canine', labelKey: 'pet.breed.silkyTerrier', imagePath: breedImage('silky-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'tenterfield-terrier', species: 'canine', labelKey: 'pet.breed.tenterfieldTerrier', imagePath: breedImage('tenterfield-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'bedlington-terrier', species: 'canine', labelKey: 'pet.breed.bedlingtonTerrier', imagePath: breedImage('bedlington-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'lakeland-terrier', species: 'canine', labelKey: 'pet.breed.lakelandTerrier', imagePath: breedImage('lakeland-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'welsh-terrier', species: 'canine', labelKey: 'pet.breed.welshTerrier', imagePath: breedImage('welsh-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'dandie-dinmont-terrier', species: 'canine', labelKey: 'pet.breed.dandieDinmontTerrier', imagePath: breedImage('dandie-dinmont-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'skye-terrier', species: 'canine', labelKey: 'pet.breed.skyeTerrier', imagePath: breedImage('skye-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'parson-russell-terrier', species: 'canine', labelKey: 'pet.breed.parsonRussellTerrier', imagePath: breedImage('parson-russell-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'manchester-terrier', species: 'canine', labelKey: 'pet.breed.manchesterTerrier', imagePath: breedImage('manchester-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'irish-terrier', species: 'canine', labelKey: 'pet.breed.irishTerrier', imagePath: breedImage('irish-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'soft-coated-wheaten-terrier', species: 'canine', labelKey: 'pet.breed.softCoatedWheatenTerrier', imagePath: breedImage('soft-coated-wheaten-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'kerry-blue-terrier', species: 'canine', labelKey: 'pet.breed.kerryBlueTerrier', imagePath: breedImage('kerry-blue-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'irish-water-spaniel', species: 'canine', labelKey: 'pet.breed.irishWaterSpaniel', imagePath: breedImage('irish-water-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'welsh-springer-spaniel', species: 'canine', labelKey: 'pet.breed.welshSpringerSpaniel', imagePath: breedImage('welsh-springer-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'field-spaniel', species: 'canine', labelKey: 'pet.breed.fieldSpaniel', imagePath: breedImage('field-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'sussex-spaniel', species: 'canine', labelKey: 'pet.breed.sussexSpaniel', imagePath: breedImage('sussex-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'american-cocker-spaniel', species: 'canine', labelKey: 'pet.breed.americanCockerSpaniel', imagePath: breedImage('american-cocker-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'bouvier-des-flandres', species: 'canine', labelKey: 'pet.breed.bouvierDesFlandres', imagePath: breedImage('bouvier-des-flandres'), fallbackImagePath: canineBreedFallback },
	{ id: 'schipperke', species: 'canine', labelKey: 'pet.breed.schipperke', imagePath: breedImage('schipperke'), fallbackImagePath: canineBreedFallback },
	{ id: 'belgian-tervuren', species: 'canine', labelKey: 'pet.breed.belgianTervuren', imagePath: breedImage('belgian-tervuren'), fallbackImagePath: canineBreedFallback },
	{ id: 'belgian-groenendael', species: 'canine', labelKey: 'pet.breed.belgianGroenendael', imagePath: breedImage('belgian-groenendael'), fallbackImagePath: canineBreedFallback },
	{ id: 'australian-kelpie', species: 'canine', labelKey: 'pet.breed.australianKelpie', imagePath: breedImage('australian-kelpie'), fallbackImagePath: canineBreedFallback },
	{ id: 'huntaway', species: 'canine', labelKey: 'pet.breed.huntaway', imagePath: breedImage('huntaway'), fallbackImagePath: canineBreedFallback },
	{ id: 'english-shepherd', species: 'canine', labelKey: 'pet.breed.englishShepherd', imagePath: breedImage('english-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'puli', species: 'canine', labelKey: 'pet.breed.puli', imagePath: breedImage('puli'), fallbackImagePath: canineBreedFallback },
	{ id: 'pumi', species: 'canine', labelKey: 'pet.breed.pumi', imagePath: breedImage('pumi'), fallbackImagePath: canineBreedFallback },
	{ id: 'spanish-water-dog', species: 'canine', labelKey: 'pet.breed.spanishWaterDog', imagePath: breedImage('spanish-water-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'portuguese-podengo', species: 'canine', labelKey: 'pet.breed.portuguesePodengo', imagePath: breedImage('portuguese-podengo'), fallbackImagePath: canineBreedFallback },
	{ id: 'ibizan-hound', species: 'canine', labelKey: 'pet.breed.ibizanHound', imagePath: breedImage('ibizan-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'pharaoh-hound', species: 'canine', labelKey: 'pet.breed.pharaohHound', imagePath: breedImage('pharaoh-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'lagotto-romagnolo', species: 'canine', labelKey: 'pet.breed.lagottoRomagnolo', imagePath: breedImage('lagotto-romagnolo'), fallbackImagePath: canineBreedFallback },
	{ id: 'bracco-italiano', species: 'canine', labelKey: 'pet.breed.braccoItaliano', imagePath: breedImage('bracco-italiano'), fallbackImagePath: canineBreedFallback },
	{ id: 'spinone-italiano', species: 'canine', labelKey: 'pet.breed.spinoneItaliano', imagePath: breedImage('spinone-italiano'), fallbackImagePath: canineBreedFallback },
	{ id: 'neapolitan-mastiff', species: 'canine', labelKey: 'pet.breed.neapolitanMastiff', imagePath: breedImage('neapolitan-mastiff'), fallbackImagePath: canineBreedFallback },
	{ id: 'bolognese', species: 'canine', labelKey: 'pet.breed.bolognese', imagePath: breedImage('bolognese'), fallbackImagePath: canineBreedFallback },
	{ id: 'jindo', species: 'canine', labelKey: 'pet.breed.jindo', imagePath: breedImage('jindo'), fallbackImagePath: canineBreedFallback },
	{ id: 'thai-ridgeback', species: 'canine', labelKey: 'pet.breed.thaiRidgeback', imagePath: breedImage('thai-ridgeback'), fallbackImagePath: canineBreedFallback },
	{ id: 'canaan-dog', species: 'canine', labelKey: 'pet.breed.canaanDog', imagePath: breedImage('canaan-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'central-asian-shepherd-dog', species: 'canine', labelKey: 'pet.breed.centralAsianShepherdDog', imagePath: breedImage('central-asian-shepherd-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'yakutian-laika', species: 'canine', labelKey: 'pet.breed.yakutianLaika', imagePath: breedImage('yakutian-laika'), fallbackImagePath: canineBreedFallback },
	{ id: 'sapsali', species: 'canine', labelKey: 'pet.breed.sapsali', imagePath: breedImage('sapsali'), fallbackImagePath: canineBreedFallback },
	{ id: 'taiwan-dog', species: 'canine', labelKey: 'pet.breed.taiwanDog', imagePath: breedImage('taiwan-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'thai-bangkaew-dog', species: 'canine', labelKey: 'pet.breed.thaiBangkaewDog', imagePath: breedImage('thai-bangkaew-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'kintamani-bali-dog', species: 'canine', labelKey: 'pet.breed.kintamaniBaliDog', imagePath: breedImage('kintamani-bali-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'phu-quoc-ridgeback', species: 'canine', labelKey: 'pet.breed.phuQuocRidgeback', imagePath: breedImage('phu-quoc-ridgeback'), fallbackImagePath: canineBreedFallback },
	{ id: 'indian-spitz', species: 'canine', labelKey: 'pet.breed.indianSpitz', imagePath: breedImage('indian-spitz'), fallbackImagePath: canineBreedFallback },
	{ id: 'mudhol-hound', species: 'canine', labelKey: 'pet.breed.mudholHound', imagePath: breedImage('mudhol-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'rajapalayam', species: 'canine', labelKey: 'pet.breed.rajapalayam', imagePath: breedImage('rajapalayam'), fallbackImagePath: canineBreedFallback },
	{ id: 'chippiparai', species: 'canine', labelKey: 'pet.breed.chippiparai', imagePath: breedImage('chippiparai'), fallbackImagePath: canineBreedFallback },
	{ id: 'kombai', species: 'canine', labelKey: 'pet.breed.kombai', imagePath: breedImage('kombai'), fallbackImagePath: canineBreedFallback },
	{ id: 'rampur-greyhound', species: 'canine', labelKey: 'pet.breed.rampurGreyhound', imagePath: breedImage('rampur-greyhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'finnish-spitz', species: 'canine', labelKey: 'pet.breed.finnishSpitz', imagePath: breedImage('finnish-spitz'), fallbackImagePath: canineBreedFallback },
	{ id: 'finnish-lapphund', species: 'canine', labelKey: 'pet.breed.finnishLapphund', imagePath: breedImage('finnish-lapphund'), fallbackImagePath: canineBreedFallback },
	{ id: 'norwegian-elkhound', species: 'canine', labelKey: 'pet.breed.norwegianElkhound', imagePath: breedImage('norwegian-elkhound'), fallbackImagePath: canineBreedFallback },
	{ id: 'swedish-vallhund', species: 'canine', labelKey: 'pet.breed.swedishVallhund', imagePath: breedImage('swedish-vallhund'), fallbackImagePath: canineBreedFallback },
	{ id: 'icelandic-sheepdog', species: 'canine', labelKey: 'pet.breed.icelandicSheepdog', imagePath: breedImage('icelandic-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'appenzeller-sennenhund', species: 'canine', labelKey: 'pet.breed.appenzellerSennenhund', imagePath: breedImage('appenzeller-sennenhund'), fallbackImagePath: canineBreedFallback },
	{ id: 'east-siberian-laika', species: 'canine', labelKey: 'pet.breed.eastSiberianLaika', imagePath: breedImage('east-siberian-laika'), fallbackImagePath: canineBreedFallback },
	{ id: 'west-siberian-laika', species: 'canine', labelKey: 'pet.breed.westSiberianLaika', imagePath: breedImage('west-siberian-laika'), fallbackImagePath: canineBreedFallback },
	{ id: 'russo-european-laika', species: 'canine', labelKey: 'pet.breed.russoEuropeanLaika', imagePath: breedImage('russo-european-laika'), fallbackImagePath: canineBreedFallback },
	{ id: 'russian-toy', species: 'canine', labelKey: 'pet.breed.russianToy', imagePath: breedImage('russian-toy'), fallbackImagePath: canineBreedFallback },
	{ id: 'russian-spaniel', species: 'canine', labelKey: 'pet.breed.russianSpaniel', imagePath: breedImage('russian-spaniel'), fallbackImagePath: canineBreedFallback },
	{ id: 'russian-tsvetnaya-bolonka', species: 'canine', labelKey: 'pet.breed.russianTsvetnayaBolonka', imagePath: breedImage('russian-tsvetnaya-bolonka'), fallbackImagePath: canineBreedFallback },
	{ id: 'south-russian-ovcharka', species: 'canine', labelKey: 'pet.breed.southRussianOvcharka', imagePath: breedImage('south-russian-ovcharka'), fallbackImagePath: canineBreedFallback },
	{ id: 'east-european-shepherd', species: 'canine', labelKey: 'pet.breed.eastEuropeanShepherd', imagePath: breedImage('east-european-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'moscow-watchdog', species: 'canine', labelKey: 'pet.breed.moscowWatchdog', imagePath: breedImage('moscow-watchdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'polish-lowland-sheepdog', species: 'canine', labelKey: 'pet.breed.polishLowlandSheepdog', imagePath: breedImage('polish-lowland-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'polish-tatra-sheepdog', species: 'canine', labelKey: 'pet.breed.polishTatraSheepdog', imagePath: breedImage('polish-tatra-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'czechoslovakian-wolfdog', species: 'canine', labelKey: 'pet.breed.czechoslovakianWolfdog', imagePath: breedImage('czechoslovakian-wolfdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'cesky-terrier', species: 'canine', labelKey: 'pet.breed.ceskyTerrier', imagePath: breedImage('cesky-terrier'), fallbackImagePath: canineBreedFallback },
	{ id: 'cesky-fousek', species: 'canine', labelKey: 'pet.breed.ceskyFousek', imagePath: breedImage('cesky-fousek'), fallbackImagePath: canineBreedFallback },
	{ id: 'bohemian-shepherd', species: 'canine', labelKey: 'pet.breed.bohemianShepherd', imagePath: breedImage('bohemian-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'prague-ratter', species: 'canine', labelKey: 'pet.breed.pragueRatter', imagePath: breedImage('prague-ratter'), fallbackImagePath: canineBreedFallback },
	{ id: 'slovak-cuvac', species: 'canine', labelKey: 'pet.breed.slovakCuvac', imagePath: breedImage('slovak-cuvac'), fallbackImagePath: canineBreedFallback },
	{ id: 'slovensky-kopov', species: 'canine', labelKey: 'pet.breed.slovenskyKopov', imagePath: breedImage('slovensky-kopov'), fallbackImagePath: canineBreedFallback },
	{ id: 'romanian-carpathian-shepherd-dog', species: 'canine', labelKey: 'pet.breed.romanianCarpathianShepherdDog', imagePath: breedImage('romanian-carpathian-shepherd-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'romanian-mioritic-shepherd-dog', species: 'canine', labelKey: 'pet.breed.romanianMioriticShepherdDog', imagePath: breedImage('romanian-mioritic-shepherd-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'romanian-raven-shepherd-dog', species: 'canine', labelKey: 'pet.breed.romanianRavenShepherdDog', imagePath: breedImage('romanian-raven-shepherd-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'bucovina-shepherd-dog', species: 'canine', labelKey: 'pet.breed.bucovinaShepherdDog', imagePath: breedImage('bucovina-shepherd-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'mudi', species: 'canine', labelKey: 'pet.breed.mudi', imagePath: breedImage('mudi'), fallbackImagePath: canineBreedFallback },
	{ id: 'transylvanian-hound', species: 'canine', labelKey: 'pet.breed.transylvanianHound', imagePath: breedImage('transylvanian-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'sarplaninac', species: 'canine', labelKey: 'pet.breed.sarplaninac', imagePath: breedImage('sarplaninac'), fallbackImagePath: canineBreedFallback },
	{ id: 'tornjak', species: 'canine', labelKey: 'pet.breed.tornjak', imagePath: breedImage('tornjak'), fallbackImagePath: canineBreedFallback },
	{ id: 'karst-shepherd', species: 'canine', labelKey: 'pet.breed.karstShepherd', imagePath: breedImage('karst-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'croatian-sheepdog', species: 'canine', labelKey: 'pet.breed.croatianSheepdog', imagePath: breedImage('croatian-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'karakachan', species: 'canine', labelKey: 'pet.breed.karakachan', imagePath: breedImage('karakachan'), fallbackImagePath: canineBreedFallback },
	{ id: 'hellenic-hound', species: 'canine', labelKey: 'pet.breed.hellenicHound', imagePath: breedImage('hellenic-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'estonian-hound', species: 'canine', labelKey: 'pet.breed.estonianHound', imagePath: breedImage('estonian-hound'), fallbackImagePath: canineBreedFallback },
	{ id: 'eurasier', species: 'canine', labelKey: 'pet.breed.eurasier', imagePath: breedImage('eurasier'), fallbackImagePath: canineBreedFallback },
	{ id: 'hovawart', species: 'canine', labelKey: 'pet.breed.hovawart', imagePath: breedImage('hovawart'), fallbackImagePath: canineBreedFallback },
	{ id: 'lowchen', species: 'canine', labelKey: 'pet.breed.lowchen', imagePath: breedImage('lowchen'), fallbackImagePath: canineBreedFallback },
	{ id: 'berger-picard', species: 'canine', labelKey: 'pet.breed.bergerPicard', imagePath: breedImage('berger-picard'), fallbackImagePath: canineBreedFallback },
	{ id: 'pyrenean-shepherd', species: 'canine', labelKey: 'pet.breed.pyreneanShepherd', imagePath: breedImage('pyrenean-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'petit-basset-griffon-vendeen', species: 'canine', labelKey: 'pet.breed.petitBassetGriffonVendeen', imagePath: breedImage('petit-basset-griffon-vendeen'), fallbackImagePath: canineBreedFallback },
	{ id: 'greater-swiss-mountain-dog', species: 'canine', labelKey: 'pet.breed.greaterSwissMountainDog', imagePath: breedImage('greater-swiss-mountain-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'entlebucher-mountain-dog', species: 'canine', labelKey: 'pet.breed.entlebucherMountainDog', imagePath: breedImage('entlebucher-mountain-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'spanish-mastiff', species: 'canine', labelKey: 'pet.breed.spanishMastiff', imagePath: breedImage('spanish-mastiff'), fallbackImagePath: canineBreedFallback },
	{ id: 'galgo-espanol', species: 'canine', labelKey: 'pet.breed.galgoEspanol', imagePath: breedImage('galgo-espanol'), fallbackImagePath: canineBreedFallback },
	{ id: 'pyrenean-mastiff', species: 'canine', labelKey: 'pet.breed.pyreneanMastiff', imagePath: breedImage('pyrenean-mastiff'), fallbackImagePath: canineBreedFallback },
	{ id: 'ca-de-bou', species: 'canine', labelKey: 'pet.breed.caDeBou', imagePath: breedImage('ca-de-bou'), fallbackImagePath: canineBreedFallback },
	{ id: 'catalan-sheepdog', species: 'canine', labelKey: 'pet.breed.catalanSheepdog', imagePath: breedImage('catalan-sheepdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'estrela-mountain-dog', species: 'canine', labelKey: 'pet.breed.estrelaMountainDog', imagePath: breedImage('estrela-mountain-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'castro-laboreiro-dog', species: 'canine', labelKey: 'pet.breed.castroLaboreiroDog', imagePath: breedImage('castro-laboreiro-dog'), fallbackImagePath: canineBreedFallback },
	{ id: 'rafeiro-do-alentejo', species: 'canine', labelKey: 'pet.breed.rafeiroDoAlentejo', imagePath: breedImage('rafeiro-do-alentejo'), fallbackImagePath: canineBreedFallback },
	{ id: 'bergamasco-shepherd', species: 'canine', labelKey: 'pet.breed.bergamascoShepherd', imagePath: breedImage('bergamasco-shepherd'), fallbackImagePath: canineBreedFallback },
	{ id: 'cirneco-dell-etna', species: 'canine', labelKey: 'pet.breed.cirnecoDellEtna', imagePath: breedImage('cirneco-dell-etna'), fallbackImagePath: canineBreedFallback },
	{ id: 'volpino-italiano', species: 'canine', labelKey: 'pet.breed.volpinoItaliano', imagePath: breedImage('volpino-italiano'), fallbackImagePath: canineBreedFallback },
	{ id: 'norwegian-buhund', species: 'canine', labelKey: 'pet.breed.norwegianBuhund', imagePath: breedImage('norwegian-buhund'), fallbackImagePath: canineBreedFallback },
	{ id: 'swedish-lapphund', species: 'canine', labelKey: 'pet.breed.swedishLapphund', imagePath: breedImage('swedish-lapphund'), fallbackImagePath: canineBreedFallback },
	{ id: 'danish-swedish-farmdog', species: 'canine', labelKey: 'pet.breed.danishSwedishFarmdog', imagePath: breedImage('danish-swedish-farmdog'), fallbackImagePath: canineBreedFallback },
	{ id: 'kooikerhondje', species: 'canine', labelKey: 'pet.breed.kooikerhondje', imagePath: breedImage('kooikerhondje'), fallbackImagePath: canineBreedFallback },
	{ id: 'stabyhoun', species: 'canine', labelKey: 'pet.breed.stabyhoun', imagePath: breedImage('stabyhoun'), fallbackImagePath: canineBreedFallback },
	{ id: 'belgian-laekenois', species: 'canine', labelKey: 'pet.breed.belgianLaekenois', imagePath: breedImage('belgian-laekenois'), fallbackImagePath: canineBreedFallback },
	{ id: 'feline-mixed-breed', species: 'feline', labelKey: 'pet.breed.felineMixedBreed', imagePath: breedImage('feline-mixed-breed'), fallbackImagePath: felineBreedFallback },
	{ id: 'siamese', species: 'feline', labelKey: 'pet.breed.siamese', imagePath: breedImage('siamese'), fallbackImagePath: felineBreedFallback },
	{ id: 'persian', species: 'feline', labelKey: 'pet.breed.persian', imagePath: breedImage('persian'), fallbackImagePath: felineBreedFallback },
	{ id: 'abyssinian', species: 'feline', labelKey: 'pet.breed.abyssinian', imagePath: breedImage('abyssinian'), fallbackImagePath: felineBreedFallback },
	{ id: 'angora', species: 'feline', labelKey: 'pet.breed.angora', imagePath: breedImage('angora'), fallbackImagePath: felineBreedFallback },
	{ id: 'bengal', species: 'feline', labelKey: 'pet.breed.bengal', imagePath: breedImage('bengal'), fallbackImagePath: felineBreedFallback },
	{ id: 'brazilian-shorthair', species: 'feline', labelKey: 'pet.breed.brazilianShorthair', imagePath: breedImage('brazilian-shorthair'), fallbackImagePath: felineBreedFallback },
	{ id: 'british-shorthair', species: 'feline', labelKey: 'pet.breed.britishShorthair', imagePath: breedImage('british-shorthair'), fallbackImagePath: felineBreedFallback },
	{ id: 'burmese', species: 'feline', labelKey: 'pet.breed.burmese', imagePath: breedImage('burmese'), fallbackImagePath: felineBreedFallback },
	{ id: 'exotic-shorthair', species: 'feline', labelKey: 'pet.breed.exoticShorthair', imagePath: breedImage('exotic-shorthair'), fallbackImagePath: felineBreedFallback },
	{ id: 'himalayan', species: 'feline', labelKey: 'pet.breed.himalayan', imagePath: breedImage('himalayan'), fallbackImagePath: felineBreedFallback },
	{ id: 'maine-coon', species: 'feline', labelKey: 'pet.breed.maineCoon', imagePath: breedImage('maine-coon'), fallbackImagePath: felineBreedFallback },
	{ id: 'ragdoll', species: 'feline', labelKey: 'pet.breed.ragdoll', imagePath: breedImage('ragdoll'), fallbackImagePath: felineBreedFallback },
	{ id: 'russian-blue', species: 'feline', labelKey: 'pet.breed.russianBlue', imagePath: breedImage('russian-blue'), fallbackImagePath: felineBreedFallback },
	{ id: 'russian-white-black-tabby', species: 'feline', labelKey: 'pet.breed.russianWhiteBlackTabby', imagePath: breedImage('russian-white-black-tabby'), fallbackImagePath: felineBreedFallback },
	{ id: 'toybob', species: 'feline', labelKey: 'pet.breed.toybob', imagePath: breedImage('toybob'), fallbackImagePath: felineBreedFallback },
	{ id: 'sacred-birman', species: 'feline', labelKey: 'pet.breed.sacredBirman', imagePath: breedImage('sacred-birman'), fallbackImagePath: felineBreedFallback },
	{ id: 'scottish-fold', species: 'feline', labelKey: 'pet.breed.scottishFold', imagePath: breedImage('scottish-fold'), fallbackImagePath: felineBreedFallback },
	{ id: 'sphynx', species: 'feline', labelKey: 'pet.breed.sphynx', imagePath: breedImage('sphynx'), fallbackImagePath: felineBreedFallback },
	{ id: 'american-shorthair', species: 'feline', labelKey: 'pet.breed.americanShorthair', imagePath: breedImage('american-shorthair'), fallbackImagePath: felineBreedFallback },
	{ id: 'american-bobtail', species: 'feline', labelKey: 'pet.breed.americanBobtail', imagePath: breedImage('american-bobtail'), fallbackImagePath: felineBreedFallback },
	{ id: 'american-curl', species: 'feline', labelKey: 'pet.breed.americanCurl', imagePath: breedImage('american-curl'), fallbackImagePath: felineBreedFallback },
	{ id: 'american-wirehair', species: 'feline', labelKey: 'pet.breed.americanWirehair', imagePath: breedImage('american-wirehair'), fallbackImagePath: felineBreedFallback },
	{ id: 'balinese', species: 'feline', labelKey: 'pet.breed.balinese', imagePath: breedImage('balinese'), fallbackImagePath: felineBreedFallback },
	{ id: 'cornish-rex', species: 'feline', labelKey: 'pet.breed.cornishRex', imagePath: breedImage('cornish-rex'), fallbackImagePath: felineBreedFallback },
	{ id: 'devon-rex', species: 'feline', labelKey: 'pet.breed.devonRex', imagePath: breedImage('devon-rex'), fallbackImagePath: felineBreedFallback },
	{ id: 'egyptian-mau', species: 'feline', labelKey: 'pet.breed.egyptianMau', imagePath: breedImage('egyptian-mau'), fallbackImagePath: felineBreedFallback },
	{ id: 'manx', species: 'feline', labelKey: 'pet.breed.manx', imagePath: breedImage('manx'), fallbackImagePath: felineBreedFallback },
	{ id: 'norwegian-forest-cat', species: 'feline', labelKey: 'pet.breed.norwegianForestCat', imagePath: breedImage('norwegian-forest-cat'), fallbackImagePath: felineBreedFallback },
	{ id: 'oriental-shorthair', species: 'feline', labelKey: 'pet.breed.orientalShorthair', imagePath: breedImage('oriental-shorthair'), fallbackImagePath: felineBreedFallback },
	{ id: 'savannah', species: 'feline', labelKey: 'pet.breed.savannah', imagePath: breedImage('savannah'), fallbackImagePath: felineBreedFallback },
	{ id: 'somali', species: 'feline', labelKey: 'pet.breed.somali', imagePath: breedImage('somali'), fallbackImagePath: felineBreedFallback },
	{ id: 'chartreux', species: 'feline', labelKey: 'pet.breed.chartreux', imagePath: breedImage('chartreux'), fallbackImagePath: felineBreedFallback },
	{ id: 'european-shorthair', species: 'feline', labelKey: 'pet.breed.europeanShorthair', imagePath: breedImage('european-shorthair'), fallbackImagePath: felineBreedFallback },
	{ id: 'japanese-bobtail', species: 'feline', labelKey: 'pet.breed.japaneseBobtail', imagePath: breedImage('japanese-bobtail'), fallbackImagePath: felineBreedFallback },
	{ id: 'korat', species: 'feline', labelKey: 'pet.breed.korat', imagePath: breedImage('korat'), fallbackImagePath: felineBreedFallback },
	{ id: 'laperm', species: 'feline', labelKey: 'pet.breed.laperm', imagePath: breedImage('laperm'), fallbackImagePath: felineBreedFallback },
	{ id: 'munchkin', species: 'feline', labelKey: 'pet.breed.munchkin', imagePath: breedImage('munchkin'), fallbackImagePath: felineBreedFallback },
	{ id: 'nebelung', species: 'feline', labelKey: 'pet.breed.nebelung', imagePath: breedImage('nebelung'), fallbackImagePath: felineBreedFallback },
	{ id: 'ocicat', species: 'feline', labelKey: 'pet.breed.ocicat', imagePath: breedImage('ocicat'), fallbackImagePath: felineBreedFallback },
	{ id: 'peterbald', species: 'feline', labelKey: 'pet.breed.peterbald', imagePath: breedImage('peterbald'), fallbackImagePath: felineBreedFallback },
	{ id: 'pixie-bob', species: 'feline', labelKey: 'pet.breed.pixieBob', imagePath: breedImage('pixie-bob'), fallbackImagePath: felineBreedFallback },
	{ id: 'selkirk-rex', species: 'feline', labelKey: 'pet.breed.selkirkRex', imagePath: breedImage('selkirk-rex'), fallbackImagePath: felineBreedFallback },
	{ id: 'siberian-cat', species: 'feline', labelKey: 'pet.breed.siberianCat', imagePath: breedImage('siberian-cat'), fallbackImagePath: felineBreedFallback },
	{ id: 'singapura', species: 'feline', labelKey: 'pet.breed.singapura', imagePath: breedImage('singapura'), fallbackImagePath: felineBreedFallback },
	{ id: 'snowshoe', species: 'feline', labelKey: 'pet.breed.snowshoe', imagePath: breedImage('snowshoe'), fallbackImagePath: felineBreedFallback },
	{ id: 'tonkinese', species: 'feline', labelKey: 'pet.breed.tonkinese', imagePath: breedImage('tonkinese'), fallbackImagePath: felineBreedFallback },
	{ id: 'bombay', species: 'feline', labelKey: 'pet.breed.bombay', imagePath: breedImage('bombay'), fallbackImagePath: felineBreedFallback },
	{ id: 'burmilla', species: 'feline', labelKey: 'pet.breed.burmilla', imagePath: breedImage('burmilla'), fallbackImagePath: felineBreedFallback },
	{ id: 'ragamuffin', species: 'feline', labelKey: 'pet.breed.ragamuffin', imagePath: breedImage('ragamuffin'), fallbackImagePath: felineBreedFallback },
	{ id: 'turkish-van', species: 'feline', labelKey: 'pet.breed.turkishVan', imagePath: breedImage('turkish-van'), fallbackImagePath: felineBreedFallback },
	{ id: 'khao-manee', species: 'feline', labelKey: 'pet.breed.khaoManee', imagePath: breedImage('khao-manee'), fallbackImagePath: felineBreedFallback },
	{ id: 'havana-brown', species: 'feline', labelKey: 'pet.breed.havanaBrown', imagePath: breedImage('havana-brown'), fallbackImagePath: felineBreedFallback },
	{ id: 'toyger', species: 'feline', labelKey: 'pet.breed.toyger', imagePath: breedImage('toyger'), fallbackImagePath: felineBreedFallback },
	{ id: 'lykoi', species: 'feline', labelKey: 'pet.breed.lykoi', imagePath: breedImage('lykoi'), fallbackImagePath: felineBreedFallback },
	{ id: 'australian-mist', species: 'feline', labelKey: 'pet.breed.australianMist', imagePath: breedImage('australian-mist'), fallbackImagePath: felineBreedFallback },
	{ id: 'arabian-mau', species: 'feline', labelKey: 'pet.breed.arabianMau', imagePath: breedImage('arabian-mau'), fallbackImagePath: felineBreedFallback },
	{ id: 'aphrodite', species: 'feline', labelKey: 'pet.breed.aphrodite', imagePath: breedImage('aphrodite'), fallbackImagePath: felineBreedFallback },
	{ id: 'dragon-li', species: 'feline', labelKey: 'pet.breed.dragonLi', imagePath: breedImage('dragon-li'), fallbackImagePath: felineBreedFallback },
	{ id: 'suphalak', species: 'feline', labelKey: 'pet.breed.suphalak', imagePath: breedImage('suphalak'), fallbackImagePath: felineBreedFallback },
	{ id: 'raas-cat', species: 'feline', labelKey: 'pet.breed.raasCat', imagePath: breedImage('raas-cat'), fallbackImagePath: felineBreedFallback },
	{ id: 'aegean', species: 'feline', labelKey: 'pet.breed.aegean', imagePath: breedImage('aegean'), fallbackImagePath: felineBreedFallback },
	{ id: 'asian-cat', species: 'feline', labelKey: 'pet.breed.asianCat', imagePath: breedImage('asian-cat'), fallbackImagePath: felineBreedFallback },
	{ id: 'german-rex', species: 'feline', labelKey: 'pet.breed.germanRex', imagePath: breedImage('german-rex'), fallbackImagePath: felineBreedFallback },
	{ id: 'donskoy', species: 'feline', labelKey: 'pet.breed.donskoy', imagePath: breedImage('donskoy'), fallbackImagePath: felineBreedFallback },
	{ id: 'ukrainian-levkoy', species: 'feline', labelKey: 'pet.breed.ukrainianLevkoy', imagePath: breedImage('ukrainian-levkoy'), fallbackImagePath: felineBreedFallback },
	{ id: 'kurilian-bobtail', species: 'feline', labelKey: 'pet.breed.kurilianBobtail', imagePath: breedImage('kurilian-bobtail'), fallbackImagePath: felineBreedFallback },
	{ id: 'mekong-bobtail', species: 'feline', labelKey: 'pet.breed.mekongBobtail', imagePath: breedImage('mekong-bobtail'), fallbackImagePath: felineBreedFallback },
	{ id: 'thai-cat', species: 'feline', labelKey: 'pet.breed.thaiCat', imagePath: breedImage('thai-cat'), fallbackImagePath: felineBreedFallback },
	{ id: 'serengeti', species: 'feline', labelKey: 'pet.breed.serengeti', imagePath: breedImage('serengeti'), fallbackImagePath: felineBreedFallback },
	{ id: 'chausie', species: 'feline', labelKey: 'pet.breed.chausie', imagePath: breedImage('chausie'), fallbackImagePath: felineBreedFallback },
	{ id: 'cheetoh', species: 'feline', labelKey: 'pet.breed.cheetoh', imagePath: breedImage('cheetoh'), fallbackImagePath: felineBreedFallback },
	{ id: 'colorpoint-shorthair', species: 'feline', labelKey: 'pet.breed.colorpointShorthair', imagePath: breedImage('colorpoint-shorthair'), fallbackImagePath: felineBreedFallback },
	{ id: 'cymric', species: 'feline', labelKey: 'pet.breed.cymric', imagePath: breedImage('cymric'), fallbackImagePath: felineBreedFallback },
	{ id: 'minuet', species: 'feline', labelKey: 'pet.breed.minuet', imagePath: breedImage('minuet'), fallbackImagePath: felineBreedFallback },
	{ id: 'minskin', species: 'feline', labelKey: 'pet.breed.minskin', imagePath: breedImage('minskin'), fallbackImagePath: felineBreedFallback },
	{ id: 'highlander', species: 'feline', labelKey: 'pet.breed.highlander', imagePath: breedImage('highlander'), fallbackImagePath: felineBreedFallback },
	{ id: 'york-chocolate', species: 'feline', labelKey: 'pet.breed.yorkChocolate', imagePath: breedImage('york-chocolate'), fallbackImagePath: felineBreedFallback },
	{ id: 'foldex', species: 'feline', labelKey: 'pet.breed.foldex', imagePath: breedImage('foldex'), fallbackImagePath: felineBreedFallback },
	{ id: 'sokoke', species: 'feline', labelKey: 'pet.breed.sokoke', imagePath: breedImage('sokoke'), fallbackImagePath: felineBreedFallback }
] as const satisfies readonly PetBreedOptionBase[];

export type KnownPetBreed = (typeof petBreedOptions)[number]['id'];
export type PetBreed = KnownPetBreed | (string & {});
export type PetBreedOption = (typeof petBreedOptions)[number];

const petSpeciesIds = new Set<string>(petSpeciesOptions.map((option) => option.id));
const petBreedIds = new Set<string>(petBreedOptions.map((option) => option.id));

export function isPetSpecies(value: string | null | undefined): value is KnownPetSpecies {
	return petSpeciesIds.has(value ?? '');
}

export function isPetBreed(value: string | null | undefined): value is KnownPetBreed {
	return petBreedIds.has(value ?? '');
}

export function getPetSpeciesOption(species: string | null | undefined): PetSpeciesOption | null {
	return petSpeciesOptions.find((option) => option.id === species) ?? null;
}

export function getPetBreedOption(breed: string | null | undefined): PetBreedOption | null {
	return petBreedOptions.find((option) => option.id === breed) ?? null;
}

export function getPetBreedOptions(species: string | null | undefined): PetBreedOption[] {
	if (!species) return [];
	return petBreedOptions.filter((option) => option.species === species);
}

export function isPetBreedForSpecies(species: string, breed: string): boolean {
	return getPetBreedOptions(species).some((option) => option.id === breed);
}