import type { Country } from './types.js';

export const ALB = {
	"code": "ALB",
	"labels": {
		"pt-BR": "Albânia",
		"pt-PT": "Albânia",
		"qu-PE": "Albania",
		"qu-BO": "Albania",
		"qu-EC": "Albania",
		"chr-US": "ᎠᎵᏇᏂᏯ",
		"hi-IN": "अल्बानिया",
		"bn-IN": "আলবেনিয়া",
		"bn-BD": "আলবেনিয়া",
		"ta-IN": "அல்பேனியா",
		"ta-LK": "அல்பேனியா",
		"ta-SG": "அல்பேனியா",
		"ta-MY": "அல்பேனியா",
		"te-IN": "అల్బేనియా",
		"mr-IN": "अल्बानिया",
		"gu-IN": "અલ્બેનિયા",
		"kn-IN": "ಅಲ್ಬೇನಿಯಾ",
		"ml-IN": "അൽബേനിയ",
		"pa-IN": "ਅਲਬਾਨੀਆ",
		"ur-IN": "البانیہ",
		"ur-PK": "البانیہ",
		"or-IN": "ଆଲବାନିଆ",
		"as-IN": "আলবেনিয়া",
		"ne-IN": "अल्बेनिया",
		"ne-NP": "अल्बेनिया",
		"si-LK": "ඇල්බේනියාව",
		"kok-IN": "अल्बानीया",
		"ks-IN": "البانیا",
		"brx-IN": "आल्बानिया",
		"mai-IN": "अलबानिया",
		"dz-BT": "ཨཱལ་བེ་ནི་ཡ",
		"ja-JP": "アルバニア",
		"ko-KR": "알바니아",
		"ko-KP": "알바니아",
		"zh-CN": "阿尔巴尼亚",
		"zh-Hans-CN": "阿尔巴尼亚",
		"zh-Hant-TW": "阿爾巴尼亞",
		"zh-TW": "阿爾巴尼亞",
		"zh-HK": "阿爾巴尼亞",
		"zh-MO": "阿爾巴尼亞",
		"zh-SG": "阿尔巴尼亚",
		"yue-Hant-HK": "阿爾巴尼亞",
		"yue-Hans-CN": "阿尔巴尼亚",
		"mn-MN": "Албани",
		"ug-CN": "ئالبانىيە",
		"th-TH": "แอลเบเนีย",
		"lo-LA": "ແອວເບເນຍ",
		"km-KH": "អាល់បានី",
		"my-MM": "အယ်လ်ဘေးနီးယား",
		"vi-VN": "Albania",
		"id-ID": "Albania",
		"ms-MY": "Albania",
		"ms-SG": "Albania",
		"ms-BN": "Albania",
		"jv-ID": "Albani",
		"fil-PH": "Albania",
		"ceb-PH": "Albania",
		"ka-GE": "ალბანეთი",
		"hy-AM": "Ալբանիա",
		"az-AZ": "Albaniya",
		"az-Cyrl-AZ": "Албанија",
		"kk-KZ": "Албания",
		"ky-KG": "Албания",
		"uz-UZ": "Albaniya",
		"tg-TJ": "Албания",
		"tk-TM": "Albaniýa",
		"fa-IR": "آلبانی",
		"fa-AF": "البانیا",
		"ps-AF": "البانیه",
		"ps-PK": "البانیه",
		"he-IL": "אלבניה",
		"ar-SA": "ألبانيا",
		"ar-AE": "ألبانيا",
		"ar-QA": "ألبانيا",
		"ar-BH": "ألبانيا",
		"ar-KW": "ألبانيا",
		"ar-OM": "ألبانيا",
		"ar-YE": "ألبانيا",
		"ar-IQ": "ألبانيا",
		"ar-JO": "ألبانيا",
		"ar-LB": "ألبانيا",
		"ar-SY": "ألبانيا",
		"ar-PS": "ألبانيا",
		"en-US": "Albania",
		"en-GB": "Albania",
		"en-IE": "Albania",
		"en-MT": "Albania",
		"en-GI": "Albania",
		"en-CY": "Albania",
		"en-JE": "Albania",
		"en-GG": "Albania",
		"en-IM": "Albania",
		"en-CA": "Albania",
		"en-AU": "Albania",
		"en-NZ": "Albania",
		"en-ZA": "Albania",
		"en-IN": "Albania",
		"en-SG": "Albania",
		"pt-AO": "Albânia",
		"pt-MZ": "Albânia",
		"pt-CV": "Albânia",
		"pt-GW": "Albânia",
		"pt-ST": "Albânia",
		"pt-TL": "Albânia",
		"pt-MO": "Albânia",
		"es-ES": "Albania",
		"es-419": "Albania",
		"es-AD": "Albania",
		"es-GI": "Albania",
		"es-AR": "Albania",
		"es-BO": "Albania",
		"es-BR": "Albania",
		"es-BZ": "Albania",
		"es-CL": "Albania",
		"es-CO": "Albania",
		"es-CR": "Albania",
		"es-CU": "Albania",
		"es-DO": "Albania",
		"es-EC": "Albania",
		"es-GT": "Albania",
		"es-HN": "Albania",
		"es-MX": "Albania",
		"es-NI": "Albania",
		"es-PA": "Albania",
		"es-PE": "Albania",
		"es-PR": "Albania",
		"es-PY": "Albania",
		"es-SV": "Albania",
		"es-US": "Albania",
		"es-UY": "Albania",
		"es-VE": "Albania",
		"fr-FR": "Albanie",
		"fr-BE": "Albanie",
		"fr-CH": "Albanie",
		"fr-LU": "Albanie",
		"fr-MC": "Albanie",
		"fr-AD": "Albanie",
		"fr-CA": "Albanie",
		"it-IT": "Albania",
		"it-CH": "Albania",
		"it-SM": "Albania",
		"it-VA": "Albania",
		"de-DE": "Albanien",
		"de-AT": "Albanien",
		"de-CH": "Albanien",
		"de-BE": "Albanien",
		"de-LI": "Albanien",
		"de-LU": "Albanien",
		"nl-NL": "Albanië",
		"nl-BE": "Albanië",
		"sv-SE": "Albanien",
		"sv-FI": "Albanien",
		"da-DK": "Albanien",
		"nb-NO": "Albania",
		"nn-NO": "Albania",
		"fi-FI": "Albania",
		"is-IS": "Albanía",
		"fo-FO": "Albania",
		"et-EE": "Albaania",
		"lv-LV": "Albānija",
		"lt-LT": "Albanija",
		"pl-PL": "Albania",
		"cs-CZ": "Albánie",
		"sk-SK": "Albánsko",
		"sl-SI": "Albanija",
		"hr-HR": "Albanija",
		"bs-BA": "Albanija",
		"sr-RS": "Албанија",
		"sr-BA": "Албанија",
		"sr-ME": "Albanija",
		"mk-MK": "Албанија",
		"bg-BG": "Албания",
		"be-BY": "Албанія",
		"uk-UA": "Албанія",
		"ru-RU": "Албания",
		"el-GR": "Αλβανία",
		"el-CY": "Αλβανία",
		"ro-RO": "Albania",
		"ro-MD": "Albania",
		"hu-HU": "Albánia",
		"sq-AL": "Shqipëri",
		"sq-XK": "Shqipëri",
		"mt-MT": "l-Albanija",
		"ga-IE": "an Albáin",
		"cy-GB": "Albania",
		"gd-GB": "Albàinia",
		"lb-LU": "Albanien",
		"ca-ES": "Albània",
		"ca-AD": "Albània",
		"ca-FR": "Albània",
		"ca-IT": "Albània",
		"eu-ES": "Albania",
		"eu-FR": "Albania",
		"gl-ES": "Albania",
		"tr-TR": "Arnavutluk",
		"tr-CY": "Arnavutluk"
	},
	"callingCode": "355",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"80|9"
			]
		},
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"4[2-6]"
			]
		},
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[2358][2-5]|4"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[23578]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"6"
			]
		}
	]
} satisfies Country;
