import type { Country } from './types.js';

export const ARM = {
	"code": "ARM",
	"labels": {
		"pt-BR": "Armênia",
		"pt-PT": "Arménia",
		"qu-PE": "Armenia",
		"qu-BO": "Armenia",
		"qu-EC": "Armenia",
		"chr-US": "ᎠᎵᎻᏂᎠ",
		"hi-IN": "आर्मेनिया",
		"bn-IN": "আর্মেনিয়া",
		"bn-BD": "আর্মেনিয়া",
		"ta-IN": "அர்மேனியா",
		"ta-LK": "அர்மேனியா",
		"ta-SG": "அர்மேனியா",
		"ta-MY": "அர்மேனியா",
		"te-IN": "ఆర్మేనియా",
		"mr-IN": "अर्मेनिया",
		"gu-IN": "આર્મેનિયા",
		"kn-IN": "ಆರ್ಮೇನಿಯ",
		"ml-IN": "അർമേനിയ",
		"pa-IN": "ਅਰਮੀਨੀਆ",
		"ur-IN": "آرمینیا",
		"ur-PK": "آرمینیا",
		"or-IN": "ଆର୍ମେନିଆ",
		"as-IN": "আৰ্মেনিয়া",
		"ne-IN": "आर्मेनिया",
		"ne-NP": "आर्मेनिया",
		"si-LK": "ආර්මේනියාව",
		"kok-IN": "आर्मीनीया",
		"ks-IN": "اَرمانِیا",
		"brx-IN": "आर्मेनिया",
		"mai-IN": "आरमेनिया",
		"dz-BT": "ཨར་མི་ནི་ཡ",
		"ja-JP": "アルメニア",
		"ko-KR": "아르메니아",
		"ko-KP": "아르메니아",
		"zh-CN": "亚美尼亚",
		"zh-Hans-CN": "亚美尼亚",
		"zh-Hant-TW": "亞美尼亞",
		"zh-TW": "亞美尼亞",
		"zh-HK": "亞美尼亞",
		"zh-MO": "亞美尼亞",
		"zh-SG": "亚美尼亚",
		"yue-Hant-HK": "亞美尼亞",
		"yue-Hans-CN": "亚美尼亚",
		"mn-MN": "Армени",
		"ug-CN": "ئەرمېنىيە",
		"th-TH": "อาร์เมเนีย",
		"lo-LA": "ອາເມເນຍ",
		"km-KH": "អាមេនី",
		"my-MM": "အာမေးနီးယား",
		"vi-VN": "Armenia",
		"id-ID": "Armenia",
		"ms-MY": "Armenia",
		"ms-SG": "Armenia",
		"ms-BN": "Armenia",
		"jv-ID": "Arménia",
		"fil-PH": "Armenia",
		"ceb-PH": "Armenia",
		"ka-GE": "სომხეთი",
		"hy-AM": "Հայաստան",
		"az-AZ": "Ermənistan",
		"az-Cyrl-AZ": "Ермәнистан",
		"kk-KZ": "Армения",
		"ky-KG": "Армения",
		"uz-UZ": "Armaniston",
		"tg-TJ": "Арманистон",
		"tk-TM": "Ermenistan",
		"fa-IR": "ارمنستان",
		"fa-AF": "ارمنستان",
		"ps-AF": "ارمنستان",
		"ps-PK": "ارمنستان",
		"he-IL": "ארמניה",
		"ar-SA": "أرمينيا",
		"ar-AE": "أرمينيا",
		"ar-QA": "أرمينيا",
		"ar-BH": "أرمينيا",
		"ar-KW": "أرمينيا",
		"ar-OM": "أرمينيا",
		"ar-YE": "أرمينيا",
		"ar-IQ": "أرمينيا",
		"ar-JO": "أرمينيا",
		"ar-LB": "أرمينيا",
		"ar-SY": "أرمينيا",
		"ar-PS": "أرمينيا",
		"en-US": "Armenia",
		"en-GB": "Armenia",
		"en-IE": "Armenia",
		"en-MT": "Armenia",
		"en-GI": "Armenia",
		"en-CY": "Armenia",
		"en-JE": "Armenia",
		"en-GG": "Armenia",
		"en-IM": "Armenia",
		"en-CA": "Armenia",
		"en-AU": "Armenia",
		"en-NZ": "Armenia",
		"en-ZA": "Armenia",
		"en-IN": "Armenia",
		"en-SG": "Armenia",
		"pt-AO": "Arménia",
		"pt-MZ": "Arménia",
		"pt-CV": "Arménia",
		"pt-GW": "Arménia",
		"pt-ST": "Arménia",
		"pt-TL": "Arménia",
		"pt-MO": "Arménia",
		"es-ES": "Armenia",
		"es-419": "Armenia",
		"es-AD": "Armenia",
		"es-GI": "Armenia",
		"es-AR": "Armenia",
		"es-BO": "Armenia",
		"es-BR": "Armenia",
		"es-BZ": "Armenia",
		"es-CL": "Armenia",
		"es-CO": "Armenia",
		"es-CR": "Armenia",
		"es-CU": "Armenia",
		"es-DO": "Armenia",
		"es-EC": "Armenia",
		"es-GT": "Armenia",
		"es-HN": "Armenia",
		"es-MX": "Armenia",
		"es-NI": "Armenia",
		"es-PA": "Armenia",
		"es-PE": "Armenia",
		"es-PR": "Armenia",
		"es-PY": "Armenia",
		"es-SV": "Armenia",
		"es-US": "Armenia",
		"es-UY": "Armenia",
		"es-VE": "Armenia",
		"fr-FR": "Arménie",
		"fr-BE": "Arménie",
		"fr-CH": "Arménie",
		"fr-LU": "Arménie",
		"fr-MC": "Arménie",
		"fr-AD": "Arménie",
		"fr-CA": "Arménie",
		"it-IT": "Armenia",
		"it-CH": "Armenia",
		"it-SM": "Armenia",
		"it-VA": "Armenia",
		"de-DE": "Armenien",
		"de-AT": "Armenien",
		"de-CH": "Armenien",
		"de-BE": "Armenien",
		"de-LI": "Armenien",
		"de-LU": "Armenien",
		"nl-NL": "Armenië",
		"nl-BE": "Armenië",
		"sv-SE": "Armenien",
		"sv-FI": "Armenien",
		"da-DK": "Armenien",
		"nb-NO": "Armenia",
		"nn-NO": "Armenia",
		"fi-FI": "Armenia",
		"is-IS": "Armenía",
		"fo-FO": "Armenia",
		"et-EE": "Armeenia",
		"lv-LV": "Armēnija",
		"lt-LT": "Armėnija",
		"pl-PL": "Armenia",
		"cs-CZ": "Arménie",
		"sk-SK": "Arménsko",
		"sl-SI": "Armenija",
		"hr-HR": "Armenija",
		"bs-BA": "Armenija",
		"sr-RS": "Јерменија",
		"sr-BA": "Јерменија",
		"sr-ME": "Jermenija",
		"mk-MK": "Ерменија",
		"bg-BG": "Армения",
		"be-BY": "Арменія",
		"uk-UA": "Вірменія",
		"ru-RU": "Армения",
		"el-GR": "Αρμενία",
		"el-CY": "Αρμενία",
		"ro-RO": "Armenia",
		"ro-MD": "Armenia",
		"hu-HU": "Örményország",
		"sq-AL": "Armeni",
		"sq-XK": "Armeni",
		"mt-MT": "l-Armenja",
		"ga-IE": "an Airméin",
		"cy-GB": "Armenia",
		"gd-GB": "Airmeinea",
		"lb-LU": "Armenien",
		"ca-ES": "Armènia",
		"ca-AD": "Armènia",
		"ca-FR": "Armènia",
		"ca-IT": "Armènia",
		"eu-ES": "Armenia",
		"eu-FR": "Armenia",
		"gl-ES": "Armenia",
		"tr-TR": "Ermenistan",
		"tr-CY": "Ermenistan"
	},
	"callingCode": "374",
	"phoneMasks": [
		{
			"mask": "## ######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"1|47"
			]
		},
		{
			"mask": "## ######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[3-9]"
			]
		},
		{
			"mask": "### ## ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[89]0"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2|3[12]"
			]
		}
	]
} satisfies Country;
