import type { Country } from './types.js';

export const ATF = {
	"code": "ATF",
	"labels": {
		"pt-BR": "Territórios Franceses do Sul",
		"pt-PT": "Territórios Austrais Franceses",
		"qu-PE": "Territorios Australes Franceses",
		"qu-BO": "Territorios Australes Franceses",
		"qu-EC": "Territorios Australes Franceses",
		"chr-US": "ᎠᏂᎦᎸᏥ ᏧᎦᎾᏮ ᎦᏙᎯ ᎤᎵᏍᏛᎢ",
		"hi-IN": "फ़्रांसीसी दक्षिणी क्षेत्र",
		"bn-IN": "ফরাসী দক্ষিণাঞ্চল",
		"bn-BD": "ফরাসী দক্ষিণাঞ্চল",
		"ta-IN": "பிரெஞ்சு தெற்கு பிரதேசங்கள்",
		"ta-LK": "பிரெஞ்சு தெற்கு பிரதேசங்கள்",
		"ta-SG": "பிரெஞ்சு தெற்கு பிரதேசங்கள்",
		"ta-MY": "பிரெஞ்சு தெற்கு பிரதேசங்கள்",
		"te-IN": "ఫ్రెంచ్ దక్షిణ ప్రాంతాలు",
		"mr-IN": "फ्रेंच दाक्षिणात्य प्रदेश",
		"gu-IN": "ફ્રેંચ સધર્ન ટેરિટરીઝ",
		"kn-IN": "ಫ್ರೆಂಚ್ ದಕ್ಷಿಣ ಪ್ರದೇಶಗಳು",
		"ml-IN": "ഫ്രഞ്ച് ദക്ഷിണ ഭൂപ്രദേശം",
		"pa-IN": "ਫਰੈਂਚ ਦੱਖਣੀ ਪ੍ਰਦੇਸ਼",
		"ur-IN": "فرانسیسی جنوبی خطے",
		"ur-PK": "فرانسیسی جنوبی خطے",
		"or-IN": "ଫରାସୀ ଦକ୍ଷିଣ କ୍ଷେତ୍ର",
		"as-IN": "দক্ষিণ ফ্ৰান্সৰ অঞ্চল",
		"ne-IN": "फ्रेन्च दक्षिणी राज्यहरू",
		"ne-NP": "फ्रेन्च दक्षिणी राज्यहरू",
		"si-LK": "දකුණු ප්‍රංශ දූපත් සමූහය",
		"kok-IN": "फ्रेंच दक्षिणी प्रांत",
		"ks-IN": "فرانسِسی جَنوٗبی عَلاقہٕ",
		"brx-IN": "फ्रान्सनि खोलायारि बाहागोफोर",
		"mai-IN": "फ्रांसीसी दक्षिणी क्षेत्र",
		"dz-BT": "ཕྲནཅ་གི་ལྷོ་ཕྱོགས་མངའ་ཁོངས",
		"ja-JP": "仏領極南諸島",
		"ko-KR": "프랑스령 남방 지역",
		"ko-KP": "프랑스령 남방 지역",
		"zh-CN": "法属南部领地",
		"zh-Hans-CN": "法属南部领地",
		"zh-Hant-TW": "法屬南部屬地",
		"zh-TW": "法屬南部屬地",
		"zh-HK": "法屬南部領地",
		"zh-MO": "法屬南部領地",
		"zh-SG": "法属南部领地",
		"yue-Hant-HK": "法屬南方屬地",
		"yue-Hans-CN": "法属南方属地",
		"mn-MN": "Францын өмнөд газар нутаг",
		"ug-CN": "فىرانسىيەنىڭ جەنۇبىي زېمىنى",
		"th-TH": "เฟรนช์เซาเทิร์นเทร์ริทอรีส์",
		"lo-LA": "ເຂດແດນທາງໃຕ້ຂອງຝຮັ່ງ",
		"km-KH": "ដែនដី​បារាំង​នៅ​ភាគខាងត្បូង",
		"my-MM": "ပြင်သစ် တောင်ပိုင်း ပိုင်နက်များ",
		"vi-VN": "Lãnh thổ phía Nam Thuộc Pháp",
		"id-ID": "Wilayah Selatan Prancis",
		"ms-MY": "Wilayah Selatan Perancis",
		"ms-SG": "Wilayah Selatan Perancis",
		"ms-BN": "Wilayah Selatan Perancis",
		"jv-ID": "Wilayah Prancis nang Kutub Kidul",
		"fil-PH": "French Southern Territories",
		"ceb-PH": "French Southern Territories",
		"ka-GE": "ფრანგული სამხრეთის ტერიტორიები",
		"hy-AM": "Ֆրանսիական Հարավային Տարածքներ",
		"az-AZ": "Fransanın Cənub Əraziləri",
		"az-Cyrl-AZ": "Франсанын Ҹәнуб Әразиләри",
		"kk-KZ": "Францияның оңтүстік аймақтары",
		"ky-KG": "Франциянын Түштүктөгү аймактары",
		"uz-UZ": "Fransuz Janubiy hududlari",
		"tg-TJ": "Минтақаҳои Ҷанубии Фаронса",
		"tk-TM": "Fransuz günorta territoriýalary",
		"fa-IR": "سرزمین‌های جنوبی فرانسه",
		"fa-AF": "سرزمین‌های جنوبی فرانسه",
		"ps-AF": "د فرانسې جنوبي سیمې",
		"ps-PK": "د فرانسے جنوبي سیمے",
		"he-IL": "הטריטוריות הדרומיות של צרפת",
		"ar-SA": "الأقاليم الجنوبية الفرنسية",
		"ar-AE": "الأقاليم الجنوبية الفرنسية",
		"ar-QA": "الأقاليم الجنوبية الفرنسية",
		"ar-BH": "الأقاليم الجنوبية الفرنسية",
		"ar-KW": "الأقاليم الجنوبية الفرنسية",
		"ar-OM": "الأقاليم الجنوبية الفرنسية",
		"ar-YE": "الأقاليم الجنوبية الفرنسية",
		"ar-IQ": "الأقاليم الجنوبية الفرنسية",
		"ar-JO": "الأقاليم الجنوبية الفرنسية",
		"ar-LB": "الأقاليم الجنوبية الفرنسية",
		"ar-SY": "الأقاليم الجنوبية الفرنسية",
		"ar-PS": "الأقاليم الجنوبية الفرنسية",
		"en-US": "French Southern Territories",
		"en-GB": "French Southern Territories",
		"en-IE": "French Southern Territories",
		"en-MT": "French Southern Territories",
		"en-GI": "French Southern Territories",
		"en-CY": "French Southern Territories",
		"en-JE": "French Southern Territories",
		"en-GG": "French Southern Territories",
		"en-IM": "French Southern Territories",
		"en-CA": "French Southern Territories",
		"en-AU": "French Southern Territories",
		"en-NZ": "French Southern Territories",
		"en-ZA": "French Southern Territories",
		"en-IN": "French Southern Territories",
		"en-SG": "French Southern Territories",
		"pt-AO": "Territórios Austrais Franceses",
		"pt-MZ": "Territórios Austrais Franceses",
		"pt-CV": "Territórios Austrais Franceses",
		"pt-GW": "Territórios Austrais Franceses",
		"pt-ST": "Territórios Austrais Franceses",
		"pt-TL": "Territórios Austrais Franceses",
		"pt-MO": "Territórios Austrais Franceses",
		"es-ES": "Territorios Australes Franceses",
		"es-419": "Territorios Australes Franceses",
		"es-AD": "Territorios Australes Franceses",
		"es-GI": "Territorios Australes Franceses",
		"es-AR": "Territorios Australes Franceses",
		"es-BO": "Territorios Australes Franceses",
		"es-BR": "Territorios Australes Franceses",
		"es-BZ": "Territorios Australes Franceses",
		"es-CL": "Territorios Australes Franceses",
		"es-CO": "Territorios Australes Franceses",
		"es-CR": "Territorios Australes Franceses",
		"es-CU": "Territorios Australes Franceses",
		"es-DO": "Territorios Australes Franceses",
		"es-EC": "Territorios Australes Franceses",
		"es-GT": "Territorios Australes Franceses",
		"es-HN": "Territorios Australes Franceses",
		"es-MX": "Territorios Australes Franceses",
		"es-NI": "Territorios Australes Franceses",
		"es-PA": "Territorios Australes Franceses",
		"es-PE": "Territorios Australes Franceses",
		"es-PR": "Territorios Australes Franceses",
		"es-PY": "Territorios Australes Franceses",
		"es-SV": "Territorios Australes Franceses",
		"es-US": "Territorios Australes Franceses",
		"es-UY": "Territorios Australes Franceses",
		"es-VE": "Territorios Australes Franceses",
		"fr-FR": "Terres australes françaises",
		"fr-BE": "Terres australes françaises",
		"fr-CH": "Terres australes françaises",
		"fr-LU": "Terres australes françaises",
		"fr-MC": "Terres australes françaises",
		"fr-AD": "Terres australes françaises",
		"fr-CA": "Terres australes françaises",
		"it-IT": "Terre Australi Francesi",
		"it-CH": "Terre Australi Francesi",
		"it-SM": "Terre Australi Francesi",
		"it-VA": "Terre Australi Francesi",
		"de-DE": "Französische Süd- und Antarktisgebiete",
		"de-AT": "Französische Süd- und Antarktisgebiete",
		"de-CH": "Französische Süd- und Antarktisgebiete",
		"de-BE": "Französische Süd- und Antarktisgebiete",
		"de-LI": "Französische Süd- und Antarktisgebiete",
		"de-LU": "Französische Süd- und Antarktisgebiete",
		"nl-NL": "Franse Gebieden in de zuidelijke Indische Oceaan",
		"nl-BE": "Franse Gebieden in de zuidelijke Indische Oceaan",
		"sv-SE": "Franska sydterritorierna",
		"sv-FI": "Franska sydterritorierna",
		"da-DK": "De Franske Besiddelser i Det Sydlige Indiske Ocean og Antarktis",
		"nb-NO": "De franske sørterritorier",
		"nn-NO": "Dei franske sørterritoria",
		"fi-FI": "Ranskan eteläiset ja antarktiset alueet",
		"is-IS": "Frönsku suðlægu landsvæðin",
		"fo-FO": "Fronsku sunnaru landaøki",
		"et-EE": "Prantsuse Lõunaalad",
		"lv-LV": "Francijas Dienvidjūru teritorija",
		"lt-LT": "Prancūzijos Pietų sritys",
		"pl-PL": "Francuskie Terytoria Południowe i Antarktyczne",
		"cs-CZ": "Francouzská jižní území",
		"sk-SK": "Francúzske južné a antarktické územia",
		"sl-SI": "Francosko južno ozemlje",
		"hr-HR": "Francuski Južni Teritoriji",
		"bs-BA": "Francuske Južne Teritorije",
		"sr-RS": "Француске Јужне Територије",
		"sr-BA": "Француске јужне територије",
		"sr-ME": "Francuske Južne Teritorije",
		"mk-MK": "Француски Јужни Територии",
		"bg-BG": "Френски южни територии",
		"be-BY": "Французскія паўднёвыя тэрыторыі",
		"uk-UA": "Французькі Південні Території",
		"ru-RU": "Французские Южные территории",
		"el-GR": "Γαλλικά Νότια Εδάφη",
		"el-CY": "Γαλλικά Νότια Εδάφη",
		"ro-RO": "Teritoriile Australe și Antarctice Franceze",
		"ro-MD": "Teritoriile Australe și Antarctice Franceze",
		"hu-HU": "Francia Déli Területek",
		"sq-AL": "Territoret Jugore Franceze",
		"sq-XK": "Territoret Jugore Franceze",
		"mt-MT": "It-Territorji Franċiżi tan-Nofsinhar",
		"ga-IE": "Críocha Francacha Dheisceart an Domhain",
		"cy-GB": "Tiroedd Deheuol ac Antarctig Ffrainc",
		"gd-GB": "Ranntairean a Deas na Frainge",
		"lb-LU": "Franséisch Süd- an Antarktisgebidder",
		"ca-ES": "Terres Australs Antàrtiques Franceses",
		"ca-AD": "Terres Australs Antàrtiques Franceses",
		"ca-FR": "Terres Australs Antàrtiques Franceses",
		"ca-IT": "Terres Australs Antàrtiques Franceses",
		"eu-ES": "Hegoaldeko lurralde frantsesak",
		"eu-FR": "Hegoaldeko lurralde frantsesak",
		"gl-ES": "Territorios Austrais Franceses",
		"tr-TR": "Fransız Güney Toprakları",
		"tr-CY": "Fransız Güney Toprakları"
	},
	"callingCode": "262"
} satisfies Country;
