import type { Country } from './types.js';

export const BFA = {
	"code": "BFA",
	"labels": {
		"pt-BR": "Burquina Faso",
		"pt-PT": "Burquina Faso",
		"qu-PE": "Burkina Faso",
		"qu-BO": "Burkina Faso",
		"qu-EC": "Burkina Faso",
		"chr-US": "ᏋᎩᎾ ᏩᏐ",
		"hi-IN": "बुर्किना फ़ासो",
		"bn-IN": "বুরকিনা ফাসো",
		"bn-BD": "বুরকিনা ফাসো",
		"ta-IN": "புர்கினா ஃபாஸோ",
		"ta-LK": "புர்கினா ஃபாஸோ",
		"ta-SG": "புர்கினா ஃபாஸோ",
		"ta-MY": "புர்கினா ஃபாஸோ",
		"te-IN": "బుర్కినా ఫాసో",
		"mr-IN": "बुर्किना फासो",
		"gu-IN": "બુર્કિના ફાસો",
		"kn-IN": "ಬುರ್ಕಿನಾ ಫಾಸೊ",
		"ml-IN": "ബർക്കിന ഫാസോ",
		"pa-IN": "ਬੁਰਕੀਨਾ ਫ਼ਾਸੋ",
		"ur-IN": "برکینا فاسو",
		"ur-PK": "برکینا فاسو",
		"or-IN": "ବୁର୍କିନା ଫାସୋ",
		"as-IN": "বুৰকিনা ফাচো",
		"ne-IN": "बुर्किना फासो",
		"ne-NP": "बुर्किना फासो",
		"si-LK": "බර්කිනා ෆාසෝ",
		"kok-IN": "बुर्किना फॅसो",
		"ks-IN": "بُرکِنا فیسو",
		"brx-IN": "बुर्किना फास’",
		"mai-IN": "बुरकिना फासो",
		"dz-BT": "བྷར་ཀི་ན་ ཕེ་སོ",
		"ja-JP": "ブルキナファソ",
		"ko-KR": "부르키나파소",
		"ko-KP": "부르키나파소",
		"zh-CN": "布基纳法索",
		"zh-Hans-CN": "布基纳法索",
		"zh-Hant-TW": "布吉納法索",
		"zh-TW": "布吉納法索",
		"zh-HK": "布基納法索",
		"zh-MO": "布基納法索",
		"zh-SG": "布基纳法索",
		"yue-Hant-HK": "布吉納法索",
		"yue-Hans-CN": "布吉纳法索",
		"mn-MN": "Буркина Фасо",
		"ug-CN": "بۇركىنا فاسو",
		"th-TH": "บูร์กินาฟาโซ",
		"lo-LA": "ເບີກິນາ ຟາໂຊ",
		"km-KH": "បួគីណាហ្វាសូ",
		"my-MM": "ဘာကီးနား ဖားဆို",
		"vi-VN": "Burkina Faso",
		"id-ID": "Burkina Faso",
		"ms-MY": "Burkina Faso",
		"ms-SG": "Burkina Faso",
		"ms-BN": "Burkina Faso",
		"jv-ID": "Burkina Faso",
		"fil-PH": "Burkina Faso",
		"ceb-PH": "Burkina Faso",
		"ka-GE": "ბურკინა-ფასო",
		"hy-AM": "Բուրկինա Ֆասո",
		"az-AZ": "Burkina Faso",
		"az-Cyrl-AZ": "Буркина Фасо",
		"kk-KZ": "Буркина-Фасо",
		"ky-KG": "Буркина-Фасо",
		"uz-UZ": "Burkina-Faso",
		"tg-TJ": "Буркина-Фасо",
		"tk-TM": "Burkina-Faso",
		"fa-IR": "بورکینافاسو",
		"fa-AF": "بورکینافاسو",
		"ps-AF": "بورکینا فاسو",
		"ps-PK": "بورکینا فاسو",
		"he-IL": "בורקינה פאסו",
		"ar-SA": "بوركينا فاسو",
		"ar-AE": "بوركينا فاسو",
		"ar-QA": "بوركينا فاسو",
		"ar-BH": "بوركينا فاسو",
		"ar-KW": "بوركينا فاسو",
		"ar-OM": "بوركينا فاسو",
		"ar-YE": "بوركينا فاسو",
		"ar-IQ": "بوركينا فاسو",
		"ar-JO": "بوركينا فاسو",
		"ar-LB": "بوركينا فاسو",
		"ar-SY": "بوركينا فاسو",
		"ar-PS": "بوركينا فاسو",
		"en-US": "Burkina Faso",
		"en-GB": "Burkina Faso",
		"en-IE": "Burkina Faso",
		"en-MT": "Burkina Faso",
		"en-GI": "Burkina Faso",
		"en-CY": "Burkina Faso",
		"en-JE": "Burkina Faso",
		"en-GG": "Burkina Faso",
		"en-IM": "Burkina Faso",
		"en-CA": "Burkina Faso",
		"en-AU": "Burkina Faso",
		"en-NZ": "Burkina Faso",
		"en-ZA": "Burkina Faso",
		"en-IN": "Burkina Faso",
		"en-SG": "Burkina Faso",
		"pt-AO": "Burquina Faso",
		"pt-MZ": "Burquina Faso",
		"pt-CV": "Burquina Faso",
		"pt-GW": "Burquina Faso",
		"pt-ST": "Burquina Faso",
		"pt-TL": "Burquina Faso",
		"pt-MO": "Burquina Faso",
		"es-ES": "Burkina Faso",
		"es-419": "Burkina Faso",
		"es-AD": "Burkina Faso",
		"es-GI": "Burkina Faso",
		"es-AR": "Burkina Faso",
		"es-BO": "Burkina Faso",
		"es-BR": "Burkina Faso",
		"es-BZ": "Burkina Faso",
		"es-CL": "Burkina Faso",
		"es-CO": "Burkina Faso",
		"es-CR": "Burkina Faso",
		"es-CU": "Burkina Faso",
		"es-DO": "Burkina Faso",
		"es-EC": "Burkina Faso",
		"es-GT": "Burkina Faso",
		"es-HN": "Burkina Faso",
		"es-MX": "Burkina Faso",
		"es-NI": "Burkina Faso",
		"es-PA": "Burkina Faso",
		"es-PE": "Burkina Faso",
		"es-PR": "Burkina Faso",
		"es-PY": "Burkina Faso",
		"es-SV": "Burkina Faso",
		"es-US": "Burkina Faso",
		"es-UY": "Burkina Faso",
		"es-VE": "Burkina Faso",
		"fr-FR": "Burkina Faso",
		"fr-BE": "Burkina Faso",
		"fr-CH": "Burkina Faso",
		"fr-LU": "Burkina Faso",
		"fr-MC": "Burkina Faso",
		"fr-AD": "Burkina Faso",
		"fr-CA": "Burkina Faso",
		"it-IT": "Burkina Faso",
		"it-CH": "Burkina Faso",
		"it-SM": "Burkina Faso",
		"it-VA": "Burkina Faso",
		"de-DE": "Burkina Faso",
		"de-AT": "Burkina Faso",
		"de-CH": "Burkina Faso",
		"de-BE": "Burkina Faso",
		"de-LI": "Burkina Faso",
		"de-LU": "Burkina Faso",
		"nl-NL": "Burkina Faso",
		"nl-BE": "Burkina Faso",
		"sv-SE": "Burkina Faso",
		"sv-FI": "Burkina Faso",
		"da-DK": "Burkina Faso",
		"nb-NO": "Burkina Faso",
		"nn-NO": "Burkina Faso",
		"fi-FI": "Burkina Faso",
		"is-IS": "Búrkína Fasó",
		"fo-FO": "Burkina Faso",
		"et-EE": "Burkina Faso",
		"lv-LV": "Burkinafaso",
		"lt-LT": "Burkina Fasas",
		"pl-PL": "Burkina Faso",
		"cs-CZ": "Burkina Faso",
		"sk-SK": "Burkina Faso",
		"sl-SI": "Burkina Faso",
		"hr-HR": "Burkina Faso",
		"bs-BA": "Burkina Faso",
		"sr-RS": "Буркина Фасо",
		"sr-BA": "Буркина Фасо",
		"sr-ME": "Burkina Faso",
		"mk-MK": "Буркина Фасо",
		"bg-BG": "Буркина Фасо",
		"be-BY": "Буркіна-Фасо",
		"uk-UA": "Буркіна-Фасо",
		"ru-RU": "Буркина-Фасо",
		"el-GR": "Μπουρκίνα Φάσο",
		"el-CY": "Μπουρκίνα Φάσο",
		"ro-RO": "Burkina Faso",
		"ro-MD": "Burkina Faso",
		"hu-HU": "Burkina Faso",
		"sq-AL": "Burkina-Faso",
		"sq-XK": "Burkina-Faso",
		"mt-MT": "il-Burkina Faso",
		"ga-IE": "Buircíne Fasó",
		"cy-GB": "Burkina Faso",
		"gd-GB": "Buirciona Faso",
		"lb-LU": "Burkina Faso",
		"ca-ES": "Burkina Faso",
		"ca-AD": "Burkina Faso",
		"ca-FR": "Burkina Faso",
		"ca-IT": "Burkina Faso",
		"eu-ES": "Burkina Faso",
		"eu-FR": "Burkina Faso",
		"gl-ES": "Burkina Faso",
		"tr-TR": "Burkina Faso",
		"tr-CY": "Burkina Faso"
	},
	"callingCode": "226",
	"phoneMasks": [
		{
			"mask": "## ## ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[025-7]"
			]
		}
	]
} satisfies Country;
