import type { Country } from './types.js';

export const BGD = {
	"code": "BGD",
	"labels": {
		"pt-BR": "Bangladesh",
		"pt-PT": "Bangladeche",
		"qu-PE": "Bangladesh",
		"qu-BO": "Bangladesh",
		"qu-EC": "Bangladesh",
		"chr-US": "ᏆᏂᎦᎵᏕᏍ",
		"hi-IN": "बांग्लादेश",
		"bn-IN": "বাংলাদেশ",
		"bn-BD": "বাংলাদেশ",
		"ta-IN": "பங்களாதேஷ்",
		"ta-LK": "பங்களாதேஷ்",
		"ta-SG": "பங்களாதேஷ்",
		"ta-MY": "பங்களாதேஷ்",
		"te-IN": "బంగ్లాదేశ్",
		"mr-IN": "बांगलादेश",
		"gu-IN": "બાંગ્લાદેશ",
		"kn-IN": "ಬಾಂಗ್ಲಾದೇಶ",
		"ml-IN": "ബംഗ്ലാദേശ്",
		"pa-IN": "ਬੰਗਲਾਦੇਸ਼",
		"ur-IN": "بنگلہ دیش",
		"ur-PK": "بنگلہ دیش",
		"or-IN": "ବାଂଲାଦେଶ",
		"as-IN": "বাংলাদেশ",
		"ne-IN": "बङ्गलादेश",
		"ne-NP": "बङ्गलादेश",
		"si-LK": "බංග්ලාදේශය",
		"kok-IN": "बांगलादेश",
		"ks-IN": "بَنگلادیش",
		"brx-IN": "बांलादेश",
		"mai-IN": "बंगलादेश",
		"dz-BT": "བངྒ་ལ་དེཤ",
		"ja-JP": "バングラデシュ",
		"ko-KR": "방글라데시",
		"ko-KP": "방글라데시",
		"zh-CN": "孟加拉国",
		"zh-Hans-CN": "孟加拉国",
		"zh-Hant-TW": "孟加拉",
		"zh-TW": "孟加拉",
		"zh-HK": "孟加拉",
		"zh-MO": "孟加拉",
		"zh-SG": "孟加拉国",
		"yue-Hant-HK": "孟加拉",
		"yue-Hans-CN": "孟加拉",
		"mn-MN": "Бангладеш",
		"ug-CN": "بېنگال",
		"th-TH": "บังกลาเทศ",
		"lo-LA": "ບັງກະລາເທດ",
		"km-KH": "បង់ក្លាដែស",
		"my-MM": "ဘင်္ဂလားဒေ့ရှ်",
		"vi-VN": "Bangladesh",
		"id-ID": "Bangladesh",
		"ms-MY": "Bangladesh",
		"ms-SG": "Bangladesh",
		"ms-BN": "Bangladesh",
		"jv-ID": "Banggaladésa",
		"fil-PH": "Bangladesh",
		"ceb-PH": "Bangladesh",
		"ka-GE": "ბანგლადეში",
		"hy-AM": "Բանգլադեշ",
		"az-AZ": "Banqladeş",
		"az-Cyrl-AZ": "Бангладеш",
		"kk-KZ": "Бангладеш",
		"ky-KG": "Бангладеш",
		"uz-UZ": "Bangladesh",
		"tg-TJ": "Бангладеш",
		"tk-TM": "Bangladeş",
		"fa-IR": "بنگلادش",
		"fa-AF": "بنگله‌دیش",
		"ps-AF": "بنگله دېش",
		"ps-PK": "بنگله دېش",
		"he-IL": "בנגלדש",
		"ar-SA": "بنغلاديش",
		"ar-AE": "بنغلاديش",
		"ar-QA": "بنغلاديش",
		"ar-BH": "بنغلاديش",
		"ar-KW": "بنغلاديش",
		"ar-OM": "بنغلاديش",
		"ar-YE": "بنغلاديش",
		"ar-IQ": "بنغلاديش",
		"ar-JO": "بنغلاديش",
		"ar-LB": "بنغلاديش",
		"ar-SY": "بنغلاديش",
		"ar-PS": "بنغلاديش",
		"en-US": "Bangladesh",
		"en-GB": "Bangladesh",
		"en-IE": "Bangladesh",
		"en-MT": "Bangladesh",
		"en-GI": "Bangladesh",
		"en-CY": "Bangladesh",
		"en-JE": "Bangladesh",
		"en-GG": "Bangladesh",
		"en-IM": "Bangladesh",
		"en-CA": "Bangladesh",
		"en-AU": "Bangladesh",
		"en-NZ": "Bangladesh",
		"en-ZA": "Bangladesh",
		"en-IN": "Bangladesh",
		"en-SG": "Bangladesh",
		"pt-AO": "Bangladeche",
		"pt-MZ": "Bangladeche",
		"pt-CV": "Bangladeche",
		"pt-GW": "Bangladeche",
		"pt-ST": "Bangladeche",
		"pt-TL": "Bangladeche",
		"pt-MO": "Bangladeche",
		"es-ES": "Bangladés",
		"es-419": "Bangladés",
		"es-AD": "Bangladés",
		"es-GI": "Bangladés",
		"es-AR": "Bangladés",
		"es-BO": "Bangladés",
		"es-BR": "Bangladés",
		"es-BZ": "Bangladés",
		"es-CL": "Bangladés",
		"es-CO": "Bangladés",
		"es-CR": "Bangladés",
		"es-CU": "Bangladés",
		"es-DO": "Bangladés",
		"es-EC": "Bangladés",
		"es-GT": "Bangladés",
		"es-HN": "Bangladés",
		"es-MX": "Bangladés",
		"es-NI": "Bangladés",
		"es-PA": "Bangladés",
		"es-PE": "Bangladés",
		"es-PR": "Bangladés",
		"es-PY": "Bangladés",
		"es-SV": "Bangladés",
		"es-US": "Bangladés",
		"es-UY": "Bangladés",
		"es-VE": "Bangladés",
		"fr-FR": "Bangladesh",
		"fr-BE": "Bangladesh",
		"fr-CH": "Bangladesh",
		"fr-LU": "Bangladesh",
		"fr-MC": "Bangladesh",
		"fr-AD": "Bangladesh",
		"fr-CA": "Bangladesh",
		"it-IT": "Bangladesh",
		"it-CH": "Bangladesh",
		"it-SM": "Bangladesh",
		"it-VA": "Bangladesh",
		"de-DE": "Bangladesch",
		"de-AT": "Bangladesch",
		"de-CH": "Bangladesch",
		"de-BE": "Bangladesch",
		"de-LI": "Bangladesch",
		"de-LU": "Bangladesch",
		"nl-NL": "Bangladesh",
		"nl-BE": "Bangladesh",
		"sv-SE": "Bangladesh",
		"sv-FI": "Bangladesh",
		"da-DK": "Bangladesh",
		"nb-NO": "Bangladesh",
		"nn-NO": "Bangladesh",
		"fi-FI": "Bangladesh",
		"is-IS": "Bangladess",
		"fo-FO": "Bangladesj",
		"et-EE": "Bangladesh",
		"lv-LV": "Bangladeša",
		"lt-LT": "Bangladešas",
		"pl-PL": "Bangladesz",
		"cs-CZ": "Bangladéš",
		"sk-SK": "Bangladéš",
		"sl-SI": "Bangladeš",
		"hr-HR": "Bangladeš",
		"bs-BA": "Bangladeš",
		"sr-RS": "Бангладеш",
		"sr-BA": "Бангладеш",
		"sr-ME": "Bangladeš",
		"mk-MK": "Бангладеш",
		"bg-BG": "Бангладеш",
		"be-BY": "Бангладэш",
		"uk-UA": "Бангладеш",
		"ru-RU": "Бангладеш",
		"el-GR": "Μπανγκλαντές",
		"el-CY": "Μπανγκλαντές",
		"ro-RO": "Bangladesh",
		"ro-MD": "Bangladesh",
		"hu-HU": "Banglades",
		"sq-AL": "Bangladesh",
		"sq-XK": "Bangladesh",
		"mt-MT": "il-Bangladesh",
		"ga-IE": "an Bhanglaidéis",
		"cy-GB": "Bangladesh",
		"gd-GB": "Bangladais",
		"lb-LU": "Bangladesch",
		"ca-ES": "Bangladesh",
		"ca-AD": "Bangladesh",
		"ca-FR": "Bangladesh",
		"ca-IT": "Bangladesh",
		"eu-ES": "Bangladesh",
		"eu-FR": "Bangladesh",
		"gl-ES": "Bangladesh",
		"tr-TR": "Bangladeş",
		"tr-CY": "Bangladeş"
	},
	"callingCode": "880",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "##-######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"31[5-8]|[459]1"
			]
		},
		{
			"mask": "#-########",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "###-#######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"3(?:[67]|8[013-9])|4(?:6[168]|7|[89][18])|5(?:6[128]|9)|6(?:[15]|28|4[14])|7[2-589]|8(?:0[014-9]|[12])|9[358]|(?:3[2-5]|4[235]|5[2-578]|6[0389]|76|8[3-7]|9[24])1|(?:44|66)[01346-9]"
			]
		},
		{
			"mask": "####-######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[13-9]|2[23]"
			]
		}
	]
} satisfies Country;
