import type { Country } from './types.js';

export const BIH = {
	"code": "BIH",
	"labels": {
		"pt-BR": "Bósnia e Herzegovina",
		"pt-PT": "Bósnia e Herzegovina",
		"qu-PE": "Bosnia y Herzegovina",
		"qu-BO": "Bosnia y Herzegovina",
		"qu-EC": "Bosnia y Herzegovina",
		"chr-US": "ᏉᏏᏂᎠ & ᎲᏤᎪᏫᎾ",
		"hi-IN": "बोस्निया और हर्ज़ेगोविना",
		"bn-IN": "বসনিয়া ও হার্জেগোভিনা",
		"bn-BD": "বসনিয়া ও হার্জেগোভিনা",
		"ta-IN": "போஸ்னியா & ஹெர்ஸகோவினா",
		"ta-LK": "போஸ்னியா & ஹெர்ஸகோவினா",
		"ta-SG": "போஸ்னியா & ஹெர்ஸகோவினா",
		"ta-MY": "போஸ்னியா & ஹெர்ஸகோவினா",
		"te-IN": "బోస్నియా మరియు హెర్జిగోవినా",
		"mr-IN": "बोस्निया अणि हर्जेगोविना",
		"gu-IN": "બોસ્નિયા અને હર્ઝેગોવિના",
		"kn-IN": "ಬೋಸ್ನಿಯಾ ಮತ್ತು ಹರ್ಜೆಗೋವಿನಾ",
		"ml-IN": "ബോസ്നിയയും ഹെർസഗോവിനയും",
		"pa-IN": "ਬੋਸਨੀਆ ਅਤੇ ਹਰਜ਼ੇਗੋਵੀਨਾ",
		"ur-IN": "بوسنیا اور ہرزیگووینا",
		"ur-PK": "بوسنیا اور ہرزیگووینا",
		"or-IN": "ବୋସନିଆ ଏବଂ ହର୍ଜଗୋଭିନା",
		"as-IN": "ব’ছনিয়া আৰু হাৰ্জেগ’ভিনা",
		"ne-IN": "बोस्निया एण्ड हर्जगोभिनिया",
		"ne-NP": "बोस्निया एण्ड हर्जगोभिनिया",
		"si-LK": "බොස්නියාව සහ හර්සගොවීනාව",
		"kok-IN": "बोस्निया आनी हेर्जेगोविना",
		"ks-IN": "بوسنِیا تہٕ ہَرزِگووِنا",
		"brx-IN": "बसनिया आरो होर्जेगभिना",
		"mai-IN": "बोस्निया आ हर्जेगोबिना",
		"dz-BT": "བྷོས་ནི་ཡ་ ཨེནཌ་ ཧར་ཛི་གྷོ་བི་ན",
		"ja-JP": "ボスニア・ヘルツェゴビナ",
		"ko-KR": "보스니아 헤르체고비나",
		"ko-KP": "보스니아 헤르체고비나",
		"zh-CN": "波斯尼亚和黑塞哥维那",
		"zh-Hans-CN": "波斯尼亚和黑塞哥维那",
		"zh-Hant-TW": "波士尼亞與赫塞哥維納",
		"zh-TW": "波士尼亞與赫塞哥維納",
		"zh-HK": "波斯尼亞和黑塞哥維那",
		"zh-MO": "波斯尼亞和黑塞哥維那",
		"zh-SG": "波斯尼亚和黑塞哥维那",
		"yue-Hant-HK": "波斯尼亞同黑塞哥維那",
		"yue-Hans-CN": "波斯尼亚同黑塞哥维那",
		"mn-MN": "Босни-Херцеговин",
		"ug-CN": "بوسىنىيە ۋە گېرتسېگوۋىنا",
		"th-TH": "บอสเนียและเฮอร์เซโกวีนา",
		"lo-LA": "ບອດສະເນຍ ແລະ ແຮສໂກວີນາ",
		"km-KH": "បូស្ន៊ី និងហឺហ្ស៊ីហ្គូវីណា",
		"my-MM": "ဘော့စနီးယားနှင့် ဟာဇီဂိုဗီနား",
		"vi-VN": "Bosnia và Herzegovina",
		"id-ID": "Bosnia dan Herzegovina",
		"ms-MY": "Bosnia dan Herzegovina",
		"ms-SG": "Bosnia dan Herzegovina",
		"ms-BN": "Bosnia dan Herzegovina",
		"jv-ID": "Bosnia lan Hèrségovina",
		"fil-PH": "Bosnia and Herzegovina",
		"ceb-PH": "Bosnia & Herzegovina",
		"ka-GE": "ბოსნია და ჰერცეგოვინა",
		"hy-AM": "Բոսնիա և Հերցեգովինա",
		"az-AZ": "Bosniya və Herseqovina",
		"az-Cyrl-AZ": "Боснија вә Һерсеговина",
		"kk-KZ": "Босния және Герцеговина",
		"ky-KG": "Босния жана Герцеговина",
		"uz-UZ": "Bosniya va Gertsegovina",
		"tg-TJ": "Босния ва Ҳерсеговина",
		"tk-TM": "Bosniýa we Gersegowina",
		"fa-IR": "بوسنی و هرزگوین",
		"fa-AF": "بوسنیا و هرزه‌گوینا",
		"ps-AF": "بوسنيا او هېرزګوينا",
		"ps-PK": "بوسنيا او هېرزګوينا",
		"he-IL": "בוסניה והרצגובינה",
		"ar-SA": "البوسنة والهرسك",
		"ar-AE": "البوسنة والهرسك",
		"ar-QA": "البوسنة والهرسك",
		"ar-BH": "البوسنة والهرسك",
		"ar-KW": "البوسنة والهرسك",
		"ar-OM": "البوسنة والهرسك",
		"ar-YE": "البوسنة والهرسك",
		"ar-IQ": "البوسنة والهرسك",
		"ar-JO": "البوسنة والهرسك",
		"ar-LB": "البوسنة والهرسك",
		"ar-SY": "البوسنة والهرسك",
		"ar-PS": "البوسنة والهرسك",
		"en-US": "Bosnia & Herzegovina",
		"en-GB": "Bosnia & Herzegovina",
		"en-IE": "Bosnia & Herzegovina",
		"en-MT": "Bosnia & Herzegovina",
		"en-GI": "Bosnia & Herzegovina",
		"en-CY": "Bosnia & Herzegovina",
		"en-JE": "Bosnia & Herzegovina",
		"en-GG": "Bosnia & Herzegovina",
		"en-IM": "Bosnia & Herzegovina",
		"en-CA": "Bosnia and Herzegovina",
		"en-AU": "Bosnia & Herzegovina",
		"en-NZ": "Bosnia & Herzegovina",
		"en-ZA": "Bosnia & Herzegovina",
		"en-IN": "Bosnia & Herzegovina",
		"en-SG": "Bosnia & Herzegovina",
		"pt-AO": "Bósnia e Herzegovina",
		"pt-MZ": "Bósnia e Herzegovina",
		"pt-CV": "Bósnia e Herzegovina",
		"pt-GW": "Bósnia e Herzegovina",
		"pt-ST": "Bósnia e Herzegovina",
		"pt-TL": "Bósnia e Herzegovina",
		"pt-MO": "Bósnia e Herzegovina",
		"es-ES": "Bosnia y Herzegovina",
		"es-419": "Bosnia-Herzegovina",
		"es-AD": "Bosnia y Herzegovina",
		"es-GI": "Bosnia y Herzegovina",
		"es-AR": "Bosnia y Herzegovina",
		"es-BO": "Bosnia y Herzegovina",
		"es-BR": "Bosnia-Herzegovina",
		"es-BZ": "Bosnia-Herzegovina",
		"es-CL": "Bosnia y Herzegovina",
		"es-CO": "Bosnia y Herzegovina",
		"es-CR": "Bosnia y Herzegovina",
		"es-CU": "Bosnia-Herzegovina",
		"es-DO": "Bosnia y Herzegovina",
		"es-EC": "Bosnia y Herzegovina",
		"es-GT": "Bosnia y Herzegovina",
		"es-HN": "Bosnia y Herzegovina",
		"es-MX": "Bosnia y Herzegovina",
		"es-NI": "Bosnia y Herzegovina",
		"es-PA": "Bosnia y Herzegovina",
		"es-PE": "Bosnia y Herzegovina",
		"es-PR": "Bosnia-Herzegovina",
		"es-PY": "Bosnia y Herzegovina",
		"es-SV": "Bosnia-Herzegovina",
		"es-US": "Bosnia y Herzegovina",
		"es-UY": "Bosnia-Herzegovina",
		"es-VE": "Bosnia y Herzegovina",
		"fr-FR": "Bosnie-Herzégovine",
		"fr-BE": "Bosnie-Herzégovine",
		"fr-CH": "Bosnie-Herzégovine",
		"fr-LU": "Bosnie-Herzégovine",
		"fr-MC": "Bosnie-Herzégovine",
		"fr-AD": "Bosnie-Herzégovine",
		"fr-CA": "Bosnie-Herzégovine",
		"it-IT": "Bosnia ed Erzegovina",
		"it-CH": "Bosnia ed Erzegovina",
		"it-SM": "Bosnia ed Erzegovina",
		"it-VA": "Bosnia ed Erzegovina",
		"de-DE": "Bosnien und Herzegowina",
		"de-AT": "Bosnien und Herzegowina",
		"de-CH": "Bosnien und Herzegowina",
		"de-BE": "Bosnien und Herzegowina",
		"de-LI": "Bosnien und Herzegowina",
		"de-LU": "Bosnien und Herzegowina",
		"nl-NL": "Bosnië en Herzegovina",
		"nl-BE": "Bosnië en Herzegovina",
		"sv-SE": "Bosnien och Hercegovina",
		"sv-FI": "Bosnien och Hercegovina",
		"da-DK": "Bosnien-Hercegovina",
		"nb-NO": "Bosnia-Hercegovina",
		"nn-NO": "Bosnia-Hercegovina",
		"fi-FI": "Bosnia ja Hertsegovina",
		"is-IS": "Bosnía og Hersegóvína",
		"fo-FO": "Bosnia-Hersegovina",
		"et-EE": "Bosnia ja Hertsegoviina",
		"lv-LV": "Bosnija un Hercegovina",
		"lt-LT": "Bosnija ir Hercegovina",
		"pl-PL": "Bośnia i Hercegowina",
		"cs-CZ": "Bosna a Hercegovina",
		"sk-SK": "Bosna a Hercegovina",
		"sl-SI": "Bosna in Hercegovina",
		"hr-HR": "Bosna i Hercegovina",
		"bs-BA": "Bosna i Hercegovina",
		"sr-RS": "Босна и Херцеговина",
		"sr-BA": "Босна и Херцеговина",
		"sr-ME": "Bosna i Hercegovina",
		"mk-MK": "Босна и Херцеговина",
		"bg-BG": "Босна и Херцеговина",
		"be-BY": "Боснія і Герцагавіна",
		"uk-UA": "Боснія і Герцеговина",
		"ru-RU": "Босния и Герцеговина",
		"el-GR": "Βοσνία - Ερζεγοβίνη",
		"el-CY": "Βοσνία - Ερζεγοβίνη",
		"ro-RO": "Bosnia și Herțegovina",
		"ro-MD": "Bosnia și Herțegovina",
		"hu-HU": "Bosznia-Hercegovina",
		"sq-AL": "Bosnjë-Hercegovinë",
		"sq-XK": "Bosnjë-Hercegovinë",
		"mt-MT": "il-Bożnija-Ħerzegovina",
		"ga-IE": "an Bhoisnia agus an Heirseagaivéin",
		"cy-GB": "Bosnia a Herzegovina",
		"gd-GB": "Bosna is Hearsagobhana",
		"lb-LU": "Bosnien an Herzegowina",
		"ca-ES": "Bòsnia i Hercegovina",
		"ca-AD": "Bòsnia i Hercegovina",
		"ca-FR": "Bòsnia i Hercegovina",
		"ca-IT": "Bòsnia i Hercegovina",
		"eu-ES": "Bosnia-Herzegovina",
		"eu-FR": "Bosnia-Herzegovina",
		"gl-ES": "Bosnia e Hercegovina",
		"tr-TR": "Bosna-Hersek",
		"tr-CY": "Bosna-Hersek"
	},
	"callingCode": "387",
	"phoneMasks": [
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"6[1-3]|[7-9]"
			]
		},
		{
			"mask": "## ###-###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[3-5]|6[56]"
			]
		},
		{
			"mask": "## ## ## ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"6"
			]
		}
	]
} satisfies Country;
