import type { Country } from './types.js';

export const BLM = {
	"code": "BLM",
	"labels": {
		"pt-BR": "São Bartolomeu",
		"pt-PT": "São Bartolomeu",
		"qu-PE": "San Bartolomé",
		"qu-BO": "San Bartolomé",
		"qu-EC": "San Bartolomé",
		"chr-US": "ᎤᏓᏅᏘ ᏆᏕᎳᎻ",
		"hi-IN": "सेंट बार्थेलेमी",
		"bn-IN": "সেন্ট বার্থেলেমি",
		"bn-BD": "সেন্ট বার্থেলেমি",
		"ta-IN": "செயின்ட் பார்தேலெமி",
		"ta-LK": "செயின்ட் பார்தேலெமி",
		"ta-SG": "செயின்ட் பார்தேலெமி",
		"ta-MY": "செயின்ட் பார்தேலெமி",
		"te-IN": "సెయింట్ బర్థెలిమి",
		"mr-IN": "सेंट बार्थेलेमी",
		"gu-IN": "સેંટ બાર્થેલેમી",
		"kn-IN": "ಸೇಂಟ್ ಬಾರ್ಥೆಲೆಮಿ",
		"ml-IN": "സെന്റ് ബാർത്തലമി",
		"pa-IN": "ਸੇਂਟ ਬਾਰਥੇਲੇਮੀ",
		"ur-IN": "سینٹ برتھلیمی",
		"ur-PK": "سینٹ برتھلیمی",
		"or-IN": "ସେଣ୍ଟ ବାର୍ଥେଲେମି",
		"as-IN": "ছেইণ্ট বাৰ্থলেমে",
		"ne-IN": "सेन्ट बार्थेलेमी",
		"ne-NP": "सेन्ट बार्थेलेमी",
		"si-LK": "ශාන්ත බර්තලෙමි",
		"kok-IN": "सॅंट बार्थेल्मी",
		"ks-IN": "سینٹ بارتَھیلمی",
		"brx-IN": "सैन्ट बार्थेलेमी",
		"mai-IN": "सेंट बार्थेलेमी",
		"dz-BT": "སེནཊ་ བར་ཐོ་ལོམ་མིའུ",
		"ja-JP": "サン・バルテルミー",
		"ko-KR": "생바르텔레미",
		"ko-KP": "생바르텔레미",
		"zh-CN": "圣巴泰勒米",
		"zh-Hans-CN": "圣巴泰勒米",
		"zh-Hant-TW": "聖巴瑟米",
		"zh-TW": "聖巴瑟米",
		"zh-HK": "聖巴泰勒米",
		"zh-MO": "聖巴泰勒米",
		"zh-SG": "圣巴泰勒米",
		"yue-Hant-HK": "聖巴瑟米",
		"yue-Hans-CN": "圣巴瑟米",
		"mn-MN": "Сент-Бартельми",
		"ug-CN": "ساينت بارتېلېمى",
		"th-TH": "เซนต์บาร์เธเลมี",
		"lo-LA": "ເຊນ ບາເທເລມີ",
		"km-KH": "សាំង​បាថេឡេមី",
		"my-MM": "စိန့်ဘာသယ်လ်မီ",
		"vi-VN": "St. Barthélemy",
		"id-ID": "Saint Barthélemy",
		"ms-MY": "St. Barthelemy",
		"ms-SG": "St. Barthelemy",
		"ms-BN": "St. Barthelemy",
		"jv-ID": "Saint Barthélémi",
		"fil-PH": "St. Barthélemy",
		"ceb-PH": "St. Barthelemy",
		"ka-GE": "სენ-ბართელმი",
		"hy-AM": "Սուրբ Բարդուղիմեոս",
		"az-AZ": "Sent-Bartelemi",
		"az-Cyrl-AZ": "Сент-Бартелеми",
		"kk-KZ": "Сен-Бартелеми",
		"ky-KG": "Сент Бартелеми",
		"uz-UZ": "Sen-Bartelemi",
		"tg-TJ": "Сент-Бартелми",
		"tk-TM": "Sen-Bartelemi",
		"fa-IR": "سن بارتلمی",
		"fa-AF": "سن بارتلمی",
		"ps-AF": "سينټ بارتيلمي",
		"ps-PK": "سينټ بارتيلمي",
		"he-IL": "סנט ברתולומיאו",
		"ar-SA": "سان بارتليمي",
		"ar-AE": "سان بارتليمي",
		"ar-QA": "سان بارتليمي",
		"ar-BH": "سان بارتليمي",
		"ar-KW": "سان بارتليمي",
		"ar-OM": "سان بارتليمي",
		"ar-YE": "سان بارتليمي",
		"ar-IQ": "سان بارتليمي",
		"ar-JO": "سان بارتليمي",
		"ar-LB": "سان بارتليمي",
		"ar-SY": "سان بارتليمي",
		"ar-PS": "سان بارتليمي",
		"en-US": "St. Barthélemy",
		"en-GB": "St Barthélemy",
		"en-IE": "St Barthélemy",
		"en-MT": "St Barthélemy",
		"en-GI": "St Barthélemy",
		"en-CY": "St Barthélemy",
		"en-JE": "St Barthélemy",
		"en-GG": "St Barthélemy",
		"en-IM": "St Barthélemy",
		"en-CA": "Saint-Barthélemy",
		"en-AU": "St. Barthélemy",
		"en-NZ": "St Barthélemy",
		"en-ZA": "St Barthélemy",
		"en-IN": "St Barthélemy",
		"en-SG": "St Barthélemy",
		"pt-AO": "São Bartolomeu",
		"pt-MZ": "São Bartolomeu",
		"pt-CV": "São Bartolomeu",
		"pt-GW": "São Bartolomeu",
		"pt-ST": "São Bartolomeu",
		"pt-TL": "São Bartolomeu",
		"pt-MO": "São Bartolomeu",
		"es-ES": "San Bartolomé",
		"es-419": "San Bartolomé",
		"es-AD": "San Bartolomé",
		"es-GI": "San Bartolomé",
		"es-AR": "San Bartolomé",
		"es-BO": "San Bartolomé",
		"es-BR": "San Bartolomé",
		"es-BZ": "San Bartolomé",
		"es-CL": "San Bartolomé",
		"es-CO": "San Bartolomé",
		"es-CR": "San Bartolomé",
		"es-CU": "San Bartolomé",
		"es-DO": "San Bartolomé",
		"es-EC": "San Bartolomé",
		"es-GT": "San Bartolomé",
		"es-HN": "San Bartolomé",
		"es-MX": "San Bartolomé",
		"es-NI": "San Bartolomé",
		"es-PA": "San Bartolomé",
		"es-PE": "San Bartolomé",
		"es-PR": "San Bartolomé",
		"es-PY": "San Bartolomé",
		"es-SV": "San Bartolomé",
		"es-US": "San Bartolomé",
		"es-UY": "San Bartolomé",
		"es-VE": "San Bartolomé",
		"fr-FR": "Saint-Barthélemy",
		"fr-BE": "Saint-Barthélemy",
		"fr-CH": "Saint-Barthélemy",
		"fr-LU": "Saint-Barthélemy",
		"fr-MC": "Saint-Barthélemy",
		"fr-AD": "Saint-Barthélemy",
		"fr-CA": "Saint-Barthélemy",
		"it-IT": "Saint-Barthélemy",
		"it-CH": "Saint-Barthélemy",
		"it-SM": "Saint-Barthélemy",
		"it-VA": "Saint-Barthélemy",
		"de-DE": "St. Barthélemy",
		"de-AT": "St. Barthélemy",
		"de-CH": "St. Barthélemy",
		"de-BE": "St. Barthélemy",
		"de-LI": "St. Barthélemy",
		"de-LU": "St. Barthélemy",
		"nl-NL": "Saint-Barthélemy",
		"nl-BE": "Saint-Barthélemy",
		"sv-SE": "S:t Barthélemy",
		"sv-FI": "S:t Barthélemy",
		"da-DK": "Saint Barthélemy",
		"nb-NO": "Saint-Barthélemy",
		"nn-NO": "Saint-Barthélemy",
		"fi-FI": "Saint-Barthélemy",
		"is-IS": "Sankti Bartólómeusareyjar",
		"fo-FO": "St. Barthélemy",
		"et-EE": "Saint-Barthélemy",
		"lv-LV": "Senbartelmī",
		"lt-LT": "Sen Bartelemi",
		"pl-PL": "Saint-Barthélemy",
		"cs-CZ": "Svatý Bartoloměj",
		"sk-SK": "Svätý Bartolomej",
		"sl-SI": "Saint Barthélemy",
		"hr-HR": "Saint Barthélemy",
		"bs-BA": "Sveti Bartolomej",
		"sr-RS": "Свети Бартоломеј",
		"sr-BA": "Сен Бартелеми",
		"sr-ME": "Sveti Bartolomej",
		"mk-MK": "Свети Вартоломеј",
		"bg-BG": "Сен Бартелеми",
		"be-BY": "Сен-Бартэльмі",
		"uk-UA": "Сен-Бартелемі",
		"ru-RU": "Сен-Бартелеми",
		"el-GR": "Άγιος Βαρθολομαίος",
		"el-CY": "Άγιος Βαρθολομαίος",
		"ro-RO": "Saint-Barthélemy",
		"ro-MD": "Saint-Barthélemy",
		"hu-HU": "Saint-Barthélemy",
		"sq-AL": "Sen-Bartelemi",
		"sq-XK": "Sen-Bartelemi",
		"mt-MT": "Saint Barthélemy",
		"ga-IE": "Saint Barthélemy",
		"cy-GB": "Saint Barthélemy",
		"gd-GB": "Saint Barthélemy",
		"lb-LU": "Saint-Barthélemy",
		"ca-ES": "Saint-Barthélemy",
		"ca-AD": "Saint-Barthélemy",
		"ca-FR": "Saint-Barthélemy",
		"ca-IT": "Saint-Barthélemy",
		"eu-ES": "Saint Barthélemy",
		"eu-FR": "Saint Barthélemy",
		"gl-ES": "Saint Barthélemy",
		"tr-TR": "Saint Barthelemy",
		"tr-CY": "Saint Barthelemy"
	},
	"callingCode": "590",
	"phoneMasks": [
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		}
	]
} satisfies Country;
