import type { Country } from './types.js';

export const BMU = {
	"code": "BMU",
	"labels": {
		"pt-BR": "Bermudas",
		"pt-PT": "Bermudas",
		"qu-PE": "Bermudas",
		"qu-BO": "Bermudas",
		"qu-EC": "Bermudas",
		"chr-US": "ᏆᏊᏓ",
		"hi-IN": "बरमूडा",
		"bn-IN": "বারমুডা",
		"bn-BD": "বারমুডা",
		"ta-IN": "பெர்முடா",
		"ta-LK": "பெர்முடா",
		"ta-SG": "பெர்முடா",
		"ta-MY": "பெர்முடா",
		"te-IN": "బెర్ముడా",
		"mr-IN": "बर्मुडा",
		"gu-IN": "બર્મુડા",
		"kn-IN": "ಬರ್ಮುಡಾ",
		"ml-IN": "ബർമുഡ",
		"pa-IN": "ਬਰਮੂਡਾ",
		"ur-IN": "برمودا",
		"ur-PK": "برمودا",
		"or-IN": "ବର୍ମୁଡା",
		"as-IN": "বাৰ্মুডা",
		"ne-IN": "बर्मुडा",
		"ne-NP": "बर्मुडा",
		"si-LK": "බර්මියුඩා",
		"kok-IN": "बर्मुडा",
		"ks-IN": "برمودا",
		"brx-IN": "बारमूडा",
		"mai-IN": "बरमुडा",
		"dz-BT": "བར་མུ་ཌ",
		"ja-JP": "バミューダ",
		"ko-KR": "버뮤다",
		"ko-KP": "버뮤다",
		"zh-CN": "百慕大",
		"zh-Hans-CN": "百慕大",
		"zh-Hant-TW": "百慕達",
		"zh-TW": "百慕達",
		"zh-HK": "百慕達",
		"zh-MO": "百慕達",
		"zh-SG": "百慕大",
		"yue-Hant-HK": "百慕達",
		"yue-Hans-CN": "百慕达",
		"mn-MN": "Бермуда",
		"ug-CN": "بېرمۇدا",
		"th-TH": "เบอร์มิวดา",
		"lo-LA": "ເບີມິວດາ",
		"km-KH": "ប៊ឺមុយដា",
		"my-MM": "ဘာမြူဒါ",
		"vi-VN": "Bermuda",
		"id-ID": "Bermuda",
		"ms-MY": "Bermuda",
		"ms-SG": "Bermuda",
		"ms-BN": "Bermuda",
		"jv-ID": "Bermuda",
		"fil-PH": "Bermuda",
		"ceb-PH": "Bermuda",
		"ka-GE": "ბერმუდა",
		"hy-AM": "Բերմուդներ",
		"az-AZ": "Bermud adaları",
		"az-Cyrl-AZ": "Бермуд адалары",
		"kk-KZ": "Бермуд аралдары",
		"ky-KG": "Бермуд аралдары",
		"uz-UZ": "Bermuda orollari",
		"tg-TJ": "Бермуда",
		"tk-TM": "Bermuda",
		"fa-IR": "برمودا",
		"fa-AF": "برمودا",
		"ps-AF": "برمودا",
		"ps-PK": "برمودا",
		"he-IL": "ברמודה",
		"ar-SA": "برمودا",
		"ar-AE": "برمودا",
		"ar-QA": "برمودا",
		"ar-BH": "برمودا",
		"ar-KW": "برمودا",
		"ar-OM": "برمودا",
		"ar-YE": "برمودا",
		"ar-IQ": "برمودا",
		"ar-JO": "برمودا",
		"ar-LB": "برمودا",
		"ar-SY": "برمودا",
		"ar-PS": "برمودا",
		"en-US": "Bermuda",
		"en-GB": "Bermuda",
		"en-IE": "Bermuda",
		"en-MT": "Bermuda",
		"en-GI": "Bermuda",
		"en-CY": "Bermuda",
		"en-JE": "Bermuda",
		"en-GG": "Bermuda",
		"en-IM": "Bermuda",
		"en-CA": "Bermuda",
		"en-AU": "Bermuda",
		"en-NZ": "Bermuda",
		"en-ZA": "Bermuda",
		"en-IN": "Bermuda",
		"en-SG": "Bermuda",
		"pt-AO": "Bermudas",
		"pt-MZ": "Bermudas",
		"pt-CV": "Bermudas",
		"pt-GW": "Bermudas",
		"pt-ST": "Bermudas",
		"pt-TL": "Bermudas",
		"pt-MO": "Bermudas",
		"es-ES": "Bermudas",
		"es-419": "Bermudas",
		"es-AD": "Bermudas",
		"es-GI": "Bermudas",
		"es-AR": "Bermudas",
		"es-BO": "Bermudas",
		"es-BR": "Bermudas",
		"es-BZ": "Bermudas",
		"es-CL": "Bermudas",
		"es-CO": "Bermudas",
		"es-CR": "Bermudas",
		"es-CU": "Bermudas",
		"es-DO": "Bermudas",
		"es-EC": "Bermudas",
		"es-GT": "Bermudas",
		"es-HN": "Bermudas",
		"es-MX": "Bermudas",
		"es-NI": "Bermudas",
		"es-PA": "Bermudas",
		"es-PE": "Bermudas",
		"es-PR": "Bermudas",
		"es-PY": "Bermudas",
		"es-SV": "Bermudas",
		"es-US": "Bermudas",
		"es-UY": "Bermudas",
		"es-VE": "Bermudas",
		"fr-FR": "Bermudes",
		"fr-BE": "Bermudes",
		"fr-CH": "Bermudes",
		"fr-LU": "Bermudes",
		"fr-MC": "Bermudes",
		"fr-AD": "Bermudes",
		"fr-CA": "Bermudes",
		"it-IT": "Bermuda",
		"it-CH": "Bermuda",
		"it-SM": "Bermuda",
		"it-VA": "Bermuda",
		"de-DE": "Bermuda",
		"de-AT": "Bermuda",
		"de-CH": "Bermuda",
		"de-BE": "Bermuda",
		"de-LI": "Bermuda",
		"de-LU": "Bermuda",
		"nl-NL": "Bermuda",
		"nl-BE": "Bermuda",
		"sv-SE": "Bermuda",
		"sv-FI": "Bermuda",
		"da-DK": "Bermuda",
		"nb-NO": "Bermuda",
		"nn-NO": "Bermuda",
		"fi-FI": "Bermuda",
		"is-IS": "Bermúdaeyjar",
		"fo-FO": "Bermuda",
		"et-EE": "Bermuda",
		"lv-LV": "Bermudu salas",
		"lt-LT": "Bermuda",
		"pl-PL": "Bermudy",
		"cs-CZ": "Bermudy",
		"sk-SK": "Bermudy",
		"sl-SI": "Bermudi",
		"hr-HR": "Bermudi",
		"bs-BA": "Bermuda",
		"sr-RS": "Бермуди",
		"sr-BA": "Бермуди",
		"sr-ME": "Bermudi",
		"mk-MK": "Бермуди",
		"bg-BG": "Бермудски острови",
		"be-BY": "Бермудскія астравы",
		"uk-UA": "Бермудські Острови",
		"ru-RU": "Бермудские о-ва",
		"el-GR": "Βερμούδες",
		"el-CY": "Βερμούδες",
		"ro-RO": "Bermuda",
		"ro-MD": "Bermuda",
		"hu-HU": "Bermuda",
		"sq-AL": "Bermude",
		"sq-XK": "Bermude",
		"mt-MT": "Bermuda",
		"ga-IE": "Beirmiúda",
		"cy-GB": "Bermuda",
		"gd-GB": "Bearmùda",
		"lb-LU": "Bermuda",
		"ca-ES": "Bermudes",
		"ca-AD": "Bermudes",
		"ca-FR": "Bermudes",
		"ca-IT": "Bermudes",
		"eu-ES": "Bermuda",
		"eu-FR": "Bermuda",
		"gl-ES": "Illas Bermudas",
		"tr-TR": "Bermuda",
		"tr-CY": "Bermuda"
	},
	"callingCode": "1441",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
