import type { Country } from './types.js';

export const BWA = {
	"code": "BWA",
	"labels": {
		"pt-BR": "Botsuana",
		"pt-PT": "Botsuana",
		"qu-PE": "Botsuana",
		"qu-BO": "Botsuana",
		"qu-EC": "Botsuana",
		"chr-US": "ᏆᏣᏩᎾ",
		"hi-IN": "बोत्स्वाना",
		"bn-IN": "বতসোয়ানা",
		"bn-BD": "বতসোয়ানা",
		"ta-IN": "போட்ஸ்வானா",
		"ta-LK": "போட்ஸ்வானா",
		"ta-SG": "போட்ஸ்வானா",
		"ta-MY": "போட்ஸ்வானா",
		"te-IN": "బోట్స్వానా",
		"mr-IN": "बोट्सवाना",
		"gu-IN": "બોત્સ્વાના",
		"kn-IN": "ಬೋಟ್ಸ್‌ವಾನಾ",
		"ml-IN": "ബോട്സ്വാന",
		"pa-IN": "ਬੋਤਸਵਾਨਾ",
		"ur-IN": "بوتسوانا",
		"ur-PK": "بوتسوانا",
		"or-IN": "ବୋଟସ୍ୱାନା",
		"as-IN": "ব’টচোৱানা",
		"ne-IN": "बोट्स्वाना",
		"ne-NP": "बोट्स्वाना",
		"si-LK": "බොට්ස්වානා",
		"kok-IN": "बोत्सवाना",
		"ks-IN": "بوتَسوانا",
		"brx-IN": "बत्स्वाना",
		"mai-IN": "बोत्सबाना",
		"dz-BT": "བྷོཙ་ཝ་ན",
		"ja-JP": "ボツワナ",
		"ko-KR": "보츠와나",
		"ko-KP": "보츠와나",
		"zh-CN": "博茨瓦纳",
		"zh-Hans-CN": "博茨瓦纳",
		"zh-Hant-TW": "波札那",
		"zh-TW": "波札那",
		"zh-HK": "博茨瓦納",
		"zh-MO": "博茨瓦納",
		"zh-SG": "博茨瓦纳",
		"yue-Hant-HK": "波札那",
		"yue-Hans-CN": "波札那",
		"mn-MN": "Ботсван",
		"ug-CN": "بوتسۋانا",
		"th-TH": "บอตสวานา",
		"lo-LA": "ບອດສະວານາ",
		"km-KH": "បុតស្វាណា",
		"my-MM": "ဘော့ဆွာနာ",
		"vi-VN": "Botswana",
		"id-ID": "Botswana",
		"ms-MY": "Botswana",
		"ms-SG": "Botswana",
		"ms-BN": "Botswana",
		"jv-ID": "Botswana",
		"fil-PH": "Botswana",
		"ceb-PH": "Botswana",
		"ka-GE": "ბოტსვანა",
		"hy-AM": "Բոտսվանա",
		"az-AZ": "Botsvana",
		"az-Cyrl-AZ": "Ботсвана",
		"kk-KZ": "Ботсвана",
		"ky-KG": "Ботсвана",
		"uz-UZ": "Botsvana",
		"tg-TJ": "Ботсвана",
		"tk-TM": "Botswana",
		"fa-IR": "بوتسوانا",
		"fa-AF": "بوتسوانا",
		"ps-AF": "بوتسوانه",
		"ps-PK": "بوتسوانه",
		"he-IL": "בוטסואנה",
		"ar-SA": "بوتسوانا",
		"ar-AE": "بوتسوانا",
		"ar-QA": "بوتسوانا",
		"ar-BH": "بوتسوانا",
		"ar-KW": "بوتسوانا",
		"ar-OM": "بوتسوانا",
		"ar-YE": "بوتسوانا",
		"ar-IQ": "بوتسوانا",
		"ar-JO": "بوتسوانا",
		"ar-LB": "بوتسوانا",
		"ar-SY": "بوتسوانا",
		"ar-PS": "بوتسوانا",
		"en-US": "Botswana",
		"en-GB": "Botswana",
		"en-IE": "Botswana",
		"en-MT": "Botswana",
		"en-GI": "Botswana",
		"en-CY": "Botswana",
		"en-JE": "Botswana",
		"en-GG": "Botswana",
		"en-IM": "Botswana",
		"en-CA": "Botswana",
		"en-AU": "Botswana",
		"en-NZ": "Botswana",
		"en-ZA": "Botswana",
		"en-IN": "Botswana",
		"en-SG": "Botswana",
		"pt-AO": "Botsuana",
		"pt-MZ": "Botsuana",
		"pt-CV": "Botsuana",
		"pt-GW": "Botsuana",
		"pt-ST": "Botsuana",
		"pt-TL": "Botsuana",
		"pt-MO": "Botsuana",
		"es-ES": "Botsuana",
		"es-419": "Botsuana",
		"es-AD": "Botsuana",
		"es-GI": "Botsuana",
		"es-AR": "Botsuana",
		"es-BO": "Botsuana",
		"es-BR": "Botsuana",
		"es-BZ": "Botsuana",
		"es-CL": "Botsuana",
		"es-CO": "Botsuana",
		"es-CR": "Botsuana",
		"es-CU": "Botsuana",
		"es-DO": "Botsuana",
		"es-EC": "Botsuana",
		"es-GT": "Botsuana",
		"es-HN": "Botsuana",
		"es-MX": "Botsuana",
		"es-NI": "Botsuana",
		"es-PA": "Botsuana",
		"es-PE": "Botsuana",
		"es-PR": "Botsuana",
		"es-PY": "Botsuana",
		"es-SV": "Botsuana",
		"es-US": "Botsuana",
		"es-UY": "Botsuana",
		"es-VE": "Botsuana",
		"fr-FR": "Botswana",
		"fr-BE": "Botswana",
		"fr-CH": "Botswana",
		"fr-LU": "Botswana",
		"fr-MC": "Botswana",
		"fr-AD": "Botswana",
		"fr-CA": "Botswana",
		"it-IT": "Botswana",
		"it-CH": "Botswana",
		"it-SM": "Botswana",
		"it-VA": "Botswana",
		"de-DE": "Botsuana",
		"de-AT": "Botsuana",
		"de-CH": "Botswana",
		"de-BE": "Botsuana",
		"de-LI": "Botsuana",
		"de-LU": "Botsuana",
		"nl-NL": "Botswana",
		"nl-BE": "Botswana",
		"sv-SE": "Botswana",
		"sv-FI": "Botswana",
		"da-DK": "Botswana",
		"nb-NO": "Botswana",
		"nn-NO": "Botswana",
		"fi-FI": "Botswana",
		"is-IS": "Botsvana",
		"fo-FO": "Botsvana",
		"et-EE": "Botswana",
		"lv-LV": "Botsvāna",
		"lt-LT": "Botsvana",
		"pl-PL": "Botswana",
		"cs-CZ": "Botswana",
		"sk-SK": "Botswana",
		"sl-SI": "Bocvana",
		"hr-HR": "Bocvana",
		"bs-BA": "Bocvana",
		"sr-RS": "Боцвана",
		"sr-BA": "Боцвана",
		"sr-ME": "Bocvana",
		"mk-MK": "Боцвана",
		"bg-BG": "Ботсвана",
		"be-BY": "Батсвана",
		"uk-UA": "Ботсвана",
		"ru-RU": "Ботсвана",
		"el-GR": "Μποτσουάνα",
		"el-CY": "Μποτσουάνα",
		"ro-RO": "Botswana",
		"ro-MD": "Botswana",
		"hu-HU": "Botswana",
		"sq-AL": "Botsvanë",
		"sq-XK": "Botsvanë",
		"mt-MT": "il-Botswana",
		"ga-IE": "an Bhotsuáin",
		"cy-GB": "Botswana",
		"gd-GB": "Botsuana",
		"lb-LU": "Botsuana",
		"ca-ES": "Botswana",
		"ca-AD": "Botswana",
		"ca-FR": "Botswana",
		"ca-IT": "Botswana",
		"eu-ES": "Botswana",
		"eu-FR": "Botswana",
		"gl-ES": "Botswana",
		"tr-TR": "Botsvana",
		"tr-CY": "Botsvana"
	},
	"callingCode": "267",
	"phoneMasks": [
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"90"
			]
		},
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[24-6]|3[15-9]"
			]
		},
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[37]"
			]
		},
		{
			"mask": "### #### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "#### ### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"0"
			]
		}
	]
} satisfies Country;
