import type { Country } from './types.js';

export const CHE = {
	"code": "CHE",
	"labels": {
		"pt-BR": "Suíça",
		"pt-PT": "Suíça",
		"qu-PE": "Suiza",
		"qu-BO": "Suiza",
		"qu-EC": "Suiza",
		"chr-US": "ᏍᏫᏍ",
		"hi-IN": "स्विट्ज़रलैंड",
		"bn-IN": "সুইজারল্যান্ড",
		"bn-BD": "সুইজারল্যান্ড",
		"ta-IN": "ஸ்விட்சர்லாந்து",
		"ta-LK": "ஸ்விட்சர்லாந்து",
		"ta-SG": "ஸ்விட்சர்லாந்து",
		"ta-MY": "ஸ்விட்சர்லாந்து",
		"te-IN": "స్విట్జర్లాండ్",
		"mr-IN": "स्वित्झर्लंड",
		"gu-IN": "સ્વિટ્ઝર્લૅન્ડ",
		"kn-IN": "ಸ್ವಿಟ್ಜರ್ಲ್ಯಾಂಡ್",
		"ml-IN": "സ്വിറ്റ്സർലാൻഡ്",
		"pa-IN": "ਸਵਿਟਜ਼ਰਲੈਂਡ",
		"ur-IN": "سوئٹزر لینڈ",
		"ur-PK": "سوئٹزر لینڈ",
		"or-IN": "ସ୍ୱିଜରଲ୍ୟାଣ୍ଡ",
		"as-IN": "চুইজাৰলেণ্ড",
		"ne-IN": "स्विजरल्याण्ड",
		"ne-NP": "स्विजरल्याण्ड",
		"si-LK": "ස්විස්ටර්ලන්තය",
		"kok-IN": "स्विट्ज़रलैंड",
		"ks-IN": "سُوِزَرلینڑ",
		"brx-IN": "सुईजारलेण्ड",
		"mai-IN": "स्विट्जरलैंड",
		"dz-BT": "སུ་ཝིཊ་ཛར་ལེནཌ",
		"ja-JP": "スイス",
		"ko-KR": "스위스",
		"ko-KP": "스위스",
		"zh-CN": "瑞士",
		"zh-Hans-CN": "瑞士",
		"zh-Hant-TW": "瑞士",
		"zh-TW": "瑞士",
		"zh-HK": "瑞士",
		"zh-MO": "瑞士",
		"zh-SG": "瑞士",
		"yue-Hant-HK": "瑞士",
		"yue-Hans-CN": "瑞士",
		"mn-MN": "Швейцар",
		"ug-CN": "شىۋېتسارىيە",
		"th-TH": "สวิตเซอร์แลนด์",
		"lo-LA": "ສະວິດເຊີແລນ",
		"km-KH": "ស្វ៊ីស",
		"my-MM": "ဆွစ်ဇာလန်",
		"vi-VN": "Thụy Sĩ",
		"id-ID": "Swiss",
		"ms-MY": "Switzerland",
		"ms-SG": "Switzerland",
		"ms-BN": "Switzerland",
		"jv-ID": "Switserlan",
		"fil-PH": "Switzerland",
		"ceb-PH": "Switzerland",
		"ka-GE": "შვეიცარია",
		"hy-AM": "Շվեյցարիա",
		"az-AZ": "İsveçrə",
		"az-Cyrl-AZ": "Исвечрә",
		"kk-KZ": "Швейцария",
		"ky-KG": "Швейцария",
		"uz-UZ": "Shveytsariya",
		"tg-TJ": "Швейтсария",
		"tk-TM": "Şweýsariýa",
		"fa-IR": "سوئیس",
		"fa-AF": "سویس",
		"ps-AF": "سویس",
		"ps-PK": "سویس",
		"he-IL": "שווייץ",
		"ar-SA": "سويسرا",
		"ar-AE": "سويسرا",
		"ar-QA": "سويسرا",
		"ar-BH": "سويسرا",
		"ar-KW": "سويسرا",
		"ar-OM": "سويسرا",
		"ar-YE": "سويسرا",
		"ar-IQ": "سويسرا",
		"ar-JO": "سويسرا",
		"ar-LB": "سويسرا",
		"ar-SY": "سويسرا",
		"ar-PS": "سويسرا",
		"en-US": "Switzerland",
		"en-GB": "Switzerland",
		"en-IE": "Switzerland",
		"en-MT": "Switzerland",
		"en-GI": "Switzerland",
		"en-CY": "Switzerland",
		"en-JE": "Switzerland",
		"en-GG": "Switzerland",
		"en-IM": "Switzerland",
		"en-CA": "Switzerland",
		"en-AU": "Switzerland",
		"en-NZ": "Switzerland",
		"en-ZA": "Switzerland",
		"en-IN": "Switzerland",
		"en-SG": "Switzerland",
		"pt-AO": "Suíça",
		"pt-MZ": "Suíça",
		"pt-CV": "Suíça",
		"pt-GW": "Suíça",
		"pt-ST": "Suíça",
		"pt-TL": "Suíça",
		"pt-MO": "Suíça",
		"es-ES": "Suiza",
		"es-419": "Suiza",
		"es-AD": "Suiza",
		"es-GI": "Suiza",
		"es-AR": "Suiza",
		"es-BO": "Suiza",
		"es-BR": "Suiza",
		"es-BZ": "Suiza",
		"es-CL": "Suiza",
		"es-CO": "Suiza",
		"es-CR": "Suiza",
		"es-CU": "Suiza",
		"es-DO": "Suiza",
		"es-EC": "Suiza",
		"es-GT": "Suiza",
		"es-HN": "Suiza",
		"es-MX": "Suiza",
		"es-NI": "Suiza",
		"es-PA": "Suiza",
		"es-PE": "Suiza",
		"es-PR": "Suiza",
		"es-PY": "Suiza",
		"es-SV": "Suiza",
		"es-US": "Suiza",
		"es-UY": "Suiza",
		"es-VE": "Suiza",
		"fr-FR": "Suisse",
		"fr-BE": "Suisse",
		"fr-CH": "Suisse",
		"fr-LU": "Suisse",
		"fr-MC": "Suisse",
		"fr-AD": "Suisse",
		"fr-CA": "Suisse",
		"it-IT": "Svizzera",
		"it-CH": "Svizzera",
		"it-SM": "Svizzera",
		"it-VA": "Svizzera",
		"de-DE": "Schweiz",
		"de-AT": "Schweiz",
		"de-CH": "Schweiz",
		"de-BE": "Schweiz",
		"de-LI": "Schweiz",
		"de-LU": "Schweiz",
		"nl-NL": "Zwitserland",
		"nl-BE": "Zwitserland",
		"sv-SE": "Schweiz",
		"sv-FI": "Schweiz",
		"da-DK": "Schweiz",
		"nb-NO": "Sveits",
		"nn-NO": "Sveits",
		"fi-FI": "Sveitsi",
		"is-IS": "Sviss",
		"fo-FO": "Sveis",
		"et-EE": "Šveits",
		"lv-LV": "Šveice",
		"lt-LT": "Šveicarija",
		"pl-PL": "Szwajcaria",
		"cs-CZ": "Švýcarsko",
		"sk-SK": "Švajčiarsko",
		"sl-SI": "Švica",
		"hr-HR": "Švicarska",
		"bs-BA": "Švicarska",
		"sr-RS": "Швајцарска",
		"sr-BA": "Швајцарска",
		"sr-ME": "Švajcarska",
		"mk-MK": "Швајцарија",
		"bg-BG": "Швейцария",
		"be-BY": "Швейцарыя",
		"uk-UA": "Швейцарія",
		"ru-RU": "Швейцария",
		"el-GR": "Ελβετία",
		"el-CY": "Ελβετία",
		"ro-RO": "Elveția",
		"ro-MD": "Elveția",
		"hu-HU": "Svájc",
		"sq-AL": "Zvicër",
		"sq-XK": "Zvicër",
		"mt-MT": "l-Iżvizzera",
		"ga-IE": "an Eilvéis",
		"cy-GB": "Y Swistir",
		"gd-GB": "An Eilbheis",
		"lb-LU": "Schwäiz",
		"ca-ES": "Suïssa",
		"ca-AD": "Suïssa",
		"ca-FR": "Suïssa",
		"ca-IT": "Suïssa",
		"eu-ES": "Suitza",
		"eu-FR": "Suitza",
		"gl-ES": "Suíza",
		"tr-TR": "İsviçre",
		"tr-CY": "İsviçre"
	},
	"callingCode": "41",
	"phoneMasks": [
		{
			"mask": "## ### ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[2-79]|81"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8[047]|90"
			]
		},
		{
			"mask": "### ## ### ## ##",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
