import type { Country } from './types.js';

export const CHL = {
	"code": "CHL",
	"labels": {
		"pt-BR": "Chile",
		"pt-PT": "Chile",
		"qu-PE": "Chile",
		"qu-BO": "Chile",
		"qu-EC": "Chile",
		"chr-US": "ᏥᎵ",
		"hi-IN": "चिली",
		"bn-IN": "চিলি",
		"bn-BD": "চিলি",
		"ta-IN": "சிலி",
		"ta-LK": "சிலி",
		"ta-SG": "சிலி",
		"ta-MY": "சிலி",
		"te-IN": "చిలీ",
		"mr-IN": "चिली",
		"gu-IN": "ચિલી",
		"kn-IN": "ಚಿಲಿ",
		"ml-IN": "ചിലി",
		"pa-IN": "ਚਿਲੀ",
		"ur-IN": "چلی",
		"ur-PK": "چلی",
		"or-IN": "ଚିଲି",
		"as-IN": "চিলি",
		"ne-IN": "चिली",
		"ne-NP": "चिली",
		"si-LK": "චිලී",
		"kok-IN": "चिली",
		"ks-IN": "چِلی",
		"brx-IN": "चिले",
		"mai-IN": "चिली",
		"dz-BT": "ཅི་ལི",
		"ja-JP": "チリ",
		"ko-KR": "칠레",
		"ko-KP": "칠레",
		"zh-CN": "智利",
		"zh-Hans-CN": "智利",
		"zh-Hant-TW": "智利",
		"zh-TW": "智利",
		"zh-HK": "智利",
		"zh-MO": "智利",
		"zh-SG": "智利",
		"yue-Hant-HK": "智利",
		"yue-Hans-CN": "智利",
		"mn-MN": "Чили",
		"ug-CN": "چىلى",
		"th-TH": "ชิลี",
		"lo-LA": "ຊິລີ",
		"km-KH": "ស៊ីលី",
		"my-MM": "ချီလီ",
		"vi-VN": "Chile",
		"id-ID": "Cile",
		"ms-MY": "Chile",
		"ms-SG": "Chile",
		"ms-BN": "Chile",
		"jv-ID": "Cilé",
		"fil-PH": "Chile",
		"ceb-PH": "Chile",
		"ka-GE": "ჩილე",
		"hy-AM": "Չիլի",
		"az-AZ": "Çili",
		"az-Cyrl-AZ": "Чили",
		"kk-KZ": "Чили",
		"ky-KG": "Чили",
		"uz-UZ": "Chili",
		"tg-TJ": "Чили",
		"tk-TM": "Çili",
		"fa-IR": "شیلی",
		"fa-AF": "چلی",
		"ps-AF": "چیلي",
		"ps-PK": "چیلي",
		"he-IL": "צ׳ילה",
		"ar-SA": "تشيلي",
		"ar-AE": "تشيلي",
		"ar-QA": "تشيلي",
		"ar-BH": "تشيلي",
		"ar-KW": "تشيلي",
		"ar-OM": "تشيلي",
		"ar-YE": "تشيلي",
		"ar-IQ": "تشيلي",
		"ar-JO": "تشيلي",
		"ar-LB": "تشيلي",
		"ar-SY": "تشيلي",
		"ar-PS": "تشيلي",
		"en-US": "Chile",
		"en-GB": "Chile",
		"en-IE": "Chile",
		"en-MT": "Chile",
		"en-GI": "Chile",
		"en-CY": "Chile",
		"en-JE": "Chile",
		"en-GG": "Chile",
		"en-IM": "Chile",
		"en-CA": "Chile",
		"en-AU": "Chile",
		"en-NZ": "Chile",
		"en-ZA": "Chile",
		"en-IN": "Chile",
		"en-SG": "Chile",
		"pt-AO": "Chile",
		"pt-MZ": "Chile",
		"pt-CV": "Chile",
		"pt-GW": "Chile",
		"pt-ST": "Chile",
		"pt-TL": "Chile",
		"pt-MO": "Chile",
		"es-ES": "Chile",
		"es-419": "Chile",
		"es-AD": "Chile",
		"es-GI": "Chile",
		"es-AR": "Chile",
		"es-BO": "Chile",
		"es-BR": "Chile",
		"es-BZ": "Chile",
		"es-CL": "Chile",
		"es-CO": "Chile",
		"es-CR": "Chile",
		"es-CU": "Chile",
		"es-DO": "Chile",
		"es-EC": "Chile",
		"es-GT": "Chile",
		"es-HN": "Chile",
		"es-MX": "Chile",
		"es-NI": "Chile",
		"es-PA": "Chile",
		"es-PE": "Chile",
		"es-PR": "Chile",
		"es-PY": "Chile",
		"es-SV": "Chile",
		"es-US": "Chile",
		"es-UY": "Chile",
		"es-VE": "Chile",
		"fr-FR": "Chili",
		"fr-BE": "Chili",
		"fr-CH": "Chili",
		"fr-LU": "Chili",
		"fr-MC": "Chili",
		"fr-AD": "Chili",
		"fr-CA": "Chili",
		"it-IT": "Cile",
		"it-CH": "Cile",
		"it-SM": "Cile",
		"it-VA": "Cile",
		"de-DE": "Chile",
		"de-AT": "Chile",
		"de-CH": "Chile",
		"de-BE": "Chile",
		"de-LI": "Chile",
		"de-LU": "Chile",
		"nl-NL": "Chili",
		"nl-BE": "Chili",
		"sv-SE": "Chile",
		"sv-FI": "Chile",
		"da-DK": "Chile",
		"nb-NO": "Chile",
		"nn-NO": "Chile",
		"fi-FI": "Chile",
		"is-IS": "Síle",
		"fo-FO": "Kili",
		"et-EE": "Tšiili",
		"lv-LV": "Čīle",
		"lt-LT": "Čilė",
		"pl-PL": "Chile",
		"cs-CZ": "Chile",
		"sk-SK": "Čile",
		"sl-SI": "Čile",
		"hr-HR": "Čile",
		"bs-BA": "Čile",
		"sr-RS": "Чиле",
		"sr-BA": "Чиле",
		"sr-ME": "Čile",
		"mk-MK": "Чиле",
		"bg-BG": "Чили",
		"be-BY": "Чылі",
		"uk-UA": "Чилі",
		"ru-RU": "Чили",
		"el-GR": "Χιλή",
		"el-CY": "Χιλή",
		"ro-RO": "Chile",
		"ro-MD": "Chile",
		"hu-HU": "Chile",
		"sq-AL": "Kili",
		"sq-XK": "Kili",
		"mt-MT": "iċ-Ċili",
		"ga-IE": "an tSile",
		"cy-GB": "Chile",
		"gd-GB": "An t-Sile",
		"lb-LU": "Chile",
		"ca-ES": "Xile",
		"ca-AD": "Xile",
		"ca-FR": "Xile",
		"ca-IT": "Xile",
		"eu-ES": "Txile",
		"eu-FR": "Txile",
		"gl-ES": "Chile",
		"tr-TR": "Şili",
		"tr-CY": "Şili"
	},
	"callingCode": "56",
	"phoneMasks": [
		{
			"mask": "(#) #### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"2[1-36]"
			]
		},
		{
			"mask": "(##) ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"3[2-5]|[47]|5[1-3578]|6[13-57]|8(?:0[1-9]|[1-9])"
			]
		},
		{
			"mask": "(#####) ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"219",
				"2196"
			]
		},
		{
			"mask": "# #### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"9[2-9]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"44"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"60|8"
			]
		},
		{
			"mask": "### ### ## ###",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"60"
			]
		},
		{
			"mask": "#### ### ####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"1"
			]
		}
	]
} satisfies Country;
