import type { Country } from './types.js';

export const COD = {
	"code": "COD",
	"labels": {
		"pt-BR": "Congo - Kinshasa",
		"pt-PT": "Congo-Kinshasa",
		"qu-PE": "Congo (RDC)",
		"qu-BO": "Congo (RDC)",
		"qu-EC": "Congo (RDC)",
		"chr-US": "ᎧᏂᎪ - ᎨᏂᏝᏌ",
		"hi-IN": "कांगो - किंशासा",
		"bn-IN": "কঙ্গো-কিনশাসা",
		"bn-BD": "কঙ্গো-কিনশাসা",
		"ta-IN": "காங்கோ - கின்ஷாசா",
		"ta-LK": "காங்கோ - கின்ஷாசா",
		"ta-SG": "காங்கோ - கின்ஷாசா",
		"ta-MY": "காங்கோ - கின்ஷாசா",
		"te-IN": "కాంగో- కిన్షాసా",
		"mr-IN": "काँगो - किंशासा",
		"gu-IN": "કોંગો - કિંશાસા",
		"kn-IN": "ಕಾಂಗೋ - ಕಿನ್ಶಾಸಾ",
		"ml-IN": "കോംഗോ - കിൻഷാസ",
		"pa-IN": "ਕਾਂਗੋ - ਕਿੰਸ਼ਾਸਾ",
		"ur-IN": "کانگو - کنشاسا",
		"ur-PK": "کانگو - کنشاسا",
		"or-IN": "କଙ୍ଗୋ (ଡିଆରସି)",
		"as-IN": "কঙ্গো - কিনচাছা",
		"ne-IN": "कङ्गो - किन्शासा",
		"ne-NP": "कङ्गो - किन्शासा",
		"si-LK": "කොංගෝව (ඩීආර්සී)",
		"kok-IN": "कोंगो - किंशासा",
		"ks-IN": "کونگو کِنشاسا",
		"brx-IN": "कंग’-किनशासा",
		"mai-IN": "कांगो-किंशासा",
		"dz-BT": "ཀོང་གྷོ ཀིན་ཤ་ས",
		"ja-JP": "コンゴ民主共和国(キンシャサ)",
		"ko-KR": "콩고-킨샤사",
		"ko-KP": "콩고-킨샤사",
		"zh-CN": "刚果（金）",
		"zh-Hans-CN": "刚果（金）",
		"zh-Hant-TW": "剛果（金夏沙）",
		"zh-TW": "剛果（金夏沙）",
		"zh-HK": "剛果（金夏沙）",
		"zh-MO": "剛果（金夏沙）",
		"zh-SG": "刚果（金）",
		"yue-Hant-HK": "剛果（金夏沙）",
		"yue-Hans-CN": "刚果（金夏沙）",
		"mn-MN": "Конго-Киншаса",
		"ug-CN": "كونگو - كىنشاسا",
		"th-TH": "คองโก - กินชาซา",
		"lo-LA": "ຄອງໂກ - ຄິນຊາຊາ",
		"km-KH": "កុងហ្គោ- គីនស្ហាសា",
		"my-MM": "ကွန်ဂို",
		"vi-VN": "Congo - Kinshasa",
		"id-ID": "Kongo - Kinshasa",
		"ms-MY": "Congo - Kinshasa",
		"ms-SG": "Congo - Kinshasa",
		"ms-BN": "Congo - Kinshasa",
		"jv-ID": "Kongo - Kinshasa",
		"fil-PH": "Congo - Kinshasa",
		"ceb-PH": "Congo - Kinshasa",
		"ka-GE": "კონგო - კინშასა",
		"hy-AM": "Կոնգո - Կինշասա",
		"az-AZ": "Konqo - Kinşasa",
		"az-Cyrl-AZ": "Конго-Киншаса",
		"kk-KZ": "Конго",
		"ky-KG": "Конго-Киншаса",
		"uz-UZ": "Kongo – Kinshasa",
		"tg-TJ": "Конго - Киншаса",
		"tk-TM": "Kongo - Kinşasa",
		"fa-IR": "کنگو - کینشاسا",
		"fa-AF": "کانگو - کینشاسا",
		"ps-AF": "کانګو - کینشاسا",
		"ps-PK": "کانګو - کینشاسا",
		"he-IL": "קונגו - קינשאסה",
		"ar-SA": "الكونغو - كينشاسا",
		"ar-AE": "الكونغو - كينشاسا",
		"ar-QA": "الكونغو - كينشاسا",
		"ar-BH": "الكونغو - كينشاسا",
		"ar-KW": "الكونغو - كينشاسا",
		"ar-OM": "الكونغو - كينشاسا",
		"ar-YE": "الكونغو - كينشاسا",
		"ar-IQ": "الكونغو - كينشاسا",
		"ar-JO": "الكونغو - كينشاسا",
		"ar-LB": "الكونغو - كينشاسا",
		"ar-SY": "الكونغو - كينشاسا",
		"ar-PS": "الكونغو - كينشاسا",
		"en-US": "Congo - Kinshasa",
		"en-GB": "Congo - Kinshasa",
		"en-IE": "Congo - Kinshasa",
		"en-MT": "Congo - Kinshasa",
		"en-GI": "Congo - Kinshasa",
		"en-CY": "Congo - Kinshasa",
		"en-JE": "Congo - Kinshasa",
		"en-GG": "Congo - Kinshasa",
		"en-IM": "Congo - Kinshasa",
		"en-CA": "Congo - Kinshasa",
		"en-AU": "Congo - Kinshasa",
		"en-NZ": "Congo - Kinshasa",
		"en-ZA": "Congo - Kinshasa",
		"en-IN": "Congo - Kinshasa",
		"en-SG": "Congo - Kinshasa",
		"pt-AO": "Congo-Kinshasa",
		"pt-MZ": "Congo-Kinshasa",
		"pt-CV": "Congo-Kinshasa",
		"pt-GW": "Congo-Kinshasa",
		"pt-ST": "Congo-Kinshasa",
		"pt-TL": "Congo-Kinshasa",
		"pt-MO": "Congo-Kinshasa",
		"es-ES": "República Democrática del Congo",
		"es-419": "República Democrática del Congo",
		"es-AD": "República Democrática del Congo",
		"es-GI": "República Democrática del Congo",
		"es-AR": "República Democrática del Congo",
		"es-BO": "República Democrática del Congo",
		"es-BR": "República Democrática del Congo",
		"es-BZ": "República Democrática del Congo",
		"es-CL": "República Democrática del Congo",
		"es-CO": "República Democrática del Congo",
		"es-CR": "República Democrática del Congo",
		"es-CU": "República Democrática del Congo",
		"es-DO": "República Democrática del Congo",
		"es-EC": "República Democrática del Congo",
		"es-GT": "República Democrática del Congo",
		"es-HN": "República Democrática del Congo",
		"es-MX": "República Democrática del Congo",
		"es-NI": "República Democrática del Congo",
		"es-PA": "República Democrática del Congo",
		"es-PE": "República Democrática del Congo",
		"es-PR": "República Democrática del Congo",
		"es-PY": "República Democrática del Congo",
		"es-SV": "República Democrática del Congo",
		"es-US": "República Democrática del Congo",
		"es-UY": "República Democrática del Congo",
		"es-VE": "República Democrática del Congo",
		"fr-FR": "Congo-Kinshasa",
		"fr-BE": "Congo-Kinshasa",
		"fr-CH": "Congo-Kinshasa",
		"fr-LU": "Congo-Kinshasa",
		"fr-MC": "Congo-Kinshasa",
		"fr-AD": "Congo-Kinshasa",
		"fr-CA": "Congo-Kinshasa",
		"it-IT": "Congo - Kinshasa",
		"it-CH": "Congo - Kinshasa",
		"it-SM": "Congo - Kinshasa",
		"it-VA": "Congo - Kinshasa",
		"de-DE": "Kongo-Kinshasa",
		"de-AT": "Kongo-Kinshasa",
		"de-CH": "Kongo-Kinshasa",
		"de-BE": "Kongo-Kinshasa",
		"de-LI": "Kongo-Kinshasa",
		"de-LU": "Kongo-Kinshasa",
		"nl-NL": "Congo-Kinshasa",
		"nl-BE": "Congo-Kinshasa",
		"sv-SE": "Kongo-Kinshasa",
		"sv-FI": "Kongo-Kinshasa",
		"da-DK": "Congo-Kinshasa",
		"nb-NO": "Kongo",
		"nn-NO": "Kongo-Kinshasa",
		"fi-FI": "Kongon demokraattinen tasavalta",
		"is-IS": "Kongó-Kinshasa",
		"fo-FO": "Kongo, Dem. Lýðveldið",
		"et-EE": "Kongo DV",
		"lv-LV": "Kongo (Kinšasa)",
		"lt-LT": "Kongas-Kinšasa",
		"pl-PL": "Demokratyczna Republika Konga",
		"cs-CZ": "Kongo – Kinshasa",
		"sk-SK": "Konžská demokratická republika",
		"sl-SI": "Demokratična republika Kongo",
		"hr-HR": "Kongo - Kinshasa",
		"bs-BA": "Demokratska Republika Kongo",
		"sr-RS": "Конго - Киншаса",
		"sr-BA": "Конго - Киншаса",
		"sr-ME": "Kongo - Kinšasa",
		"mk-MK": "Конго - Киншаса",
		"bg-BG": "Конго (Киншаса)",
		"be-BY": "Конга (Кіншаса)",
		"uk-UA": "Конго – Кіншаса",
		"ru-RU": "Конго - Киншаса",
		"el-GR": "Κονγκό - Κινσάσα",
		"el-CY": "Κονγκό - Κινσάσα",
		"ro-RO": "Congo - Kinshasa",
		"ro-MD": "Congo - Kinshasa",
		"hu-HU": "Kongó – Kinshasa",
		"sq-AL": "Kongo-Kinshasa",
		"sq-XK": "Kongo-Kinshasa",
		"mt-MT": "ir-Repubblika Demokratika tal-Kongo",
		"ga-IE": "Poblacht Dhaonlathach an Chongó",
		"cy-GB": "Y Congo - Kinshasa",
		"gd-GB": "Congo - Kinshasa",
		"lb-LU": "Kongo-Kinshasa",
		"ca-ES": "Congo - Kinshasa",
		"ca-AD": "Congo - Kinshasa",
		"ca-FR": "Congo - Kinshasa",
		"ca-IT": "Congo - Kinshasa",
		"eu-ES": "Kongoko Errepublika Demokratikoa",
		"eu-FR": "Kongoko Errepublika Demokratikoa",
		"gl-ES": "República Democrática do Congo",
		"tr-TR": "Kongo - Kinşasa",
		"tr-CY": "Kongo - Kinşasa"
	},
	"callingCode": "243",
	"phoneMasks": [
		{
			"mask": "## ## ###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"88"
			]
		},
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[1-6]"
			]
		},
		{
			"mask": "## ## ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[89]"
			]
		},
		{
			"mask": "## ## ### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"5"
			]
		}
	]
} satisfies Country;
