import type { Country } from './types.js';

export const COG = {
	"code": "COG",
	"labels": {
		"pt-BR": "República do Congo",
		"pt-PT": "Congo-Brazzaville",
		"qu-PE": "Congo",
		"qu-BO": "Congo",
		"qu-EC": "Congo",
		"chr-US": "ᎧᏂᎪ - ᏆᏌᏩᎵ",
		"hi-IN": "कांगो – ब्राज़ाविल",
		"bn-IN": "কঙ্গো - ব্রাজাভিল",
		"bn-BD": "কঙ্গো - ব্রাজাভিল",
		"ta-IN": "காங்கோ - ப்ராஸாவில்லே",
		"ta-LK": "காங்கோ - ப்ராஸாவில்லே",
		"ta-SG": "காங்கோ - ப்ராஸாவில்லே",
		"ta-MY": "காங்கோ - ப்ராஸாவில்லே",
		"te-IN": "కాంగో- బ్రాజావిల్లి",
		"mr-IN": "काँगो - ब्राझाविले",
		"gu-IN": "કોંગો - બ્રાઝાવિલે",
		"kn-IN": "ಕಾಂಗೋ - ಬ್ರಾಜಾವಿಲ್ಲೇ",
		"ml-IN": "കോംഗോ - ബ്രാസവില്ലി",
		"pa-IN": "ਕਾਂਗੋ - ਬ੍ਰਾਜ਼ਾਵਿਲੇ",
		"ur-IN": "کانگو - برازاویلے",
		"ur-PK": "کانگو - برازاویلے",
		"or-IN": "କଙ୍ଗୋ-ବ୍ରାଜିଭିଲ୍ଲେ",
		"as-IN": "কঙ্গো - ব্রাজাভিল",
		"ne-IN": "कङ्गो ब्राजाभिल",
		"ne-NP": "कङ्गो ब्राजाभिल",
		"si-LK": "කොංගො - බ්‍රසාවිල්",
		"kok-IN": "कोंगो - ब्राझाविला",
		"ks-IN": "کونگو بٔرزاوِلی",
		"brx-IN": "कंग’- ब्राज्जाभील",
		"mai-IN": "कांगो-ब्राजाबिले",
		"dz-BT": "ཀོང་གྷོ བྷྲ་ཛ་བིལ",
		"ja-JP": "コンゴ共和国(ブラザビル)",
		"ko-KR": "콩고-브라자빌",
		"ko-KP": "콩고-브라자빌",
		"zh-CN": "刚果（布）",
		"zh-Hans-CN": "刚果（布）",
		"zh-Hant-TW": "剛果（布拉薩）",
		"zh-TW": "剛果（布拉薩）",
		"zh-HK": "剛果（布拉薩）",
		"zh-MO": "剛果（布拉薩）",
		"zh-SG": "刚果（布）",
		"yue-Hant-HK": "剛果（布拉薩）",
		"yue-Hans-CN": "刚果（布拉萨）",
		"mn-MN": "Конго-Браззавиль",
		"ug-CN": "كونگو - بىراززاۋىل",
		"th-TH": "คองโก - บราซซาวิล",
		"lo-LA": "ຄອງໂກ - ບຣາຊາວິວ",
		"km-KH": "កុងហ្គោ - ប្រាហ្សាវីល",
		"my-MM": "ကွန်ဂို-ဘရာဇာဗီးလ်",
		"vi-VN": "Congo - Brazzaville",
		"id-ID": "Kongo - Brazzaville",
		"ms-MY": "Congo - Brazzaville",
		"ms-SG": "Congo - Brazzaville",
		"ms-BN": "Congo - Brazzaville",
		"jv-ID": "Kongo - Brassaville",
		"fil-PH": "Congo - Brazzaville",
		"ceb-PH": "Congo - Brazzaville",
		"ka-GE": "კონგო - ბრაზავილი",
		"hy-AM": "Կոնգո - Բրազավիլ",
		"az-AZ": "Konqo - Brazzavil",
		"az-Cyrl-AZ": "Конго-Браззавил",
		"kk-KZ": "Конго-Браззавиль Республикасы",
		"ky-KG": "Конго-Браззавил",
		"uz-UZ": "Kongo – Brazzavil",
		"tg-TJ": "Конго - Браззавил",
		"tk-TM": "Kongo - Brazzawil",
		"fa-IR": "کنگو - برازویل",
		"fa-AF": "کانگو - برازویل",
		"ps-AF": "کانګو - بروزوییل",
		"ps-PK": "کانګو - بروزوییل",
		"he-IL": "קונגו - ברזאויל",
		"ar-SA": "الكونغو - برازافيل",
		"ar-AE": "الكونغو - برازافيل",
		"ar-QA": "الكونغو - برازافيل",
		"ar-BH": "الكونغو - برازافيل",
		"ar-KW": "الكونغو - برازافيل",
		"ar-OM": "الكونغو - برازافيل",
		"ar-YE": "الكونغو - برازافيل",
		"ar-IQ": "الكونغو - برازافيل",
		"ar-JO": "الكونغو - برازافيل",
		"ar-LB": "الكونغو - برازافيل",
		"ar-SY": "الكونغو - برازافيل",
		"ar-PS": "الكونغو - برازافيل",
		"en-US": "Congo - Brazzaville",
		"en-GB": "Congo - Brazzaville",
		"en-IE": "Congo - Brazzaville",
		"en-MT": "Congo - Brazzaville",
		"en-GI": "Congo - Brazzaville",
		"en-CY": "Congo - Brazzaville",
		"en-JE": "Congo - Brazzaville",
		"en-GG": "Congo - Brazzaville",
		"en-IM": "Congo - Brazzaville",
		"en-CA": "Congo - Brazzaville",
		"en-AU": "Congo - Brazzaville",
		"en-NZ": "Congo - Brazzaville",
		"en-ZA": "Congo - Brazzaville",
		"en-IN": "Congo - Brazzaville",
		"en-SG": "Congo - Brazzaville",
		"pt-AO": "Congo-Brazzaville",
		"pt-MZ": "Congo-Brazzaville",
		"pt-CV": "Congo-Brazzaville",
		"pt-GW": "Congo-Brazzaville",
		"pt-ST": "Congo-Brazzaville",
		"pt-TL": "Congo-Brazzaville",
		"pt-MO": "Congo-Brazzaville",
		"es-ES": "Congo",
		"es-419": "República del Congo",
		"es-AD": "Congo",
		"es-GI": "Congo",
		"es-AR": "República del Congo",
		"es-BO": "República del Congo",
		"es-BR": "República del Congo",
		"es-BZ": "República del Congo",
		"es-CL": "República del Congo",
		"es-CO": "República del Congo",
		"es-CR": "República del Congo",
		"es-CU": "República del Congo",
		"es-DO": "República del Congo",
		"es-EC": "República del Congo",
		"es-GT": "República del Congo",
		"es-HN": "República del Congo",
		"es-MX": "República del Congo",
		"es-NI": "República del Congo",
		"es-PA": "República del Congo",
		"es-PE": "República del Congo",
		"es-PR": "República del Congo",
		"es-PY": "República del Congo",
		"es-SV": "República del Congo",
		"es-US": "República del Congo",
		"es-UY": "República del Congo",
		"es-VE": "República del Congo",
		"fr-FR": "Congo-Brazzaville",
		"fr-BE": "Congo-Brazzaville",
		"fr-CH": "Congo-Brazzaville",
		"fr-LU": "Congo-Brazzaville",
		"fr-MC": "Congo-Brazzaville",
		"fr-AD": "Congo-Brazzaville",
		"fr-CA": "Congo-Brazzaville",
		"it-IT": "Congo-Brazzaville",
		"it-CH": "Congo-Brazzaville",
		"it-SM": "Congo-Brazzaville",
		"it-VA": "Congo-Brazzaville",
		"de-DE": "Kongo-Brazzaville",
		"de-AT": "Kongo-Brazzaville",
		"de-CH": "Kongo-Brazzaville",
		"de-BE": "Kongo-Brazzaville",
		"de-LI": "Kongo-Brazzaville",
		"de-LU": "Kongo-Brazzaville",
		"nl-NL": "Congo-Brazzaville",
		"nl-BE": "Congo-Brazzaville",
		"sv-SE": "Kongo-Brazzaville",
		"sv-FI": "Kongo-Brazzaville",
		"da-DK": "Congo-Brazzaville",
		"nb-NO": "Kongo-Brazzaville",
		"nn-NO": "Kongo-Brazzaville",
		"fi-FI": "Kongon tasavalta",
		"is-IS": "Kongó-Brazzaville",
		"fo-FO": "Kongo",
		"et-EE": "Kongo Vabariik",
		"lv-LV": "Kongo (Brazavila)",
		"lt-LT": "Kongas-Brazavilis",
		"pl-PL": "Kongo",
		"cs-CZ": "Kongo – Brazzaville",
		"sk-SK": "Konžská republika",
		"sl-SI": "Kongo - Brazzaville",
		"hr-HR": "Kongo - Brazzaville",
		"bs-BA": "Kongo",
		"sr-RS": "Конго - Бразавил",
		"sr-BA": "Конго - Бразавил",
		"sr-ME": "Kongo",
		"mk-MK": "Конго - Бразавил",
		"bg-BG": "Конго (Бразавил)",
		"be-BY": "Конга - Бразавіль",
		"uk-UA": "Конго – Браззавіль",
		"ru-RU": "Конго - Браззавиль",
		"el-GR": "Κονγκό - Μπραζαβίλ",
		"el-CY": "Κονγκό - Μπραζαβίλ",
		"ro-RO": "Congo - Brazzaville",
		"ro-MD": "Congo - Brazzaville",
		"hu-HU": "Kongó – Brazzaville",
		"sq-AL": "Kongo-Brazavilë",
		"sq-XK": "Kongo-Brazavilë",
		"mt-MT": "il-Kongo - Brazzaville",
		"ga-IE": "Congó-Brazzaville",
		"cy-GB": "Y Congo - Brazzaville",
		"gd-GB": "A’ Chongo - Brazzaville",
		"lb-LU": "Kongo-Brazzaville",
		"ca-ES": "Congo - Brazzaville",
		"ca-AD": "Congo - Brazzaville",
		"ca-FR": "Congo - Brazzaville",
		"ca-IT": "Congo - Brazzaville",
		"eu-ES": "Kongo",
		"eu-FR": "Kongo",
		"gl-ES": "República do Congo",
		"tr-TR": "Kongo - Brazavil",
		"tr-CY": "Kongo - Brazavil"
	},
	"callingCode": "242",
	"phoneMasks": [
		{
			"mask": "# #### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[02]"
			]
		}
	]
} satisfies Country;
