import type { Country } from './types.js';

export const COM = {
	"code": "COM",
	"labels": {
		"pt-BR": "Comores",
		"pt-PT": "Comores",
		"qu-PE": "Comoras",
		"qu-BO": "Comoras",
		"qu-EC": "Comoras",
		"chr-US": "ᎪᎼᎳᏍ",
		"hi-IN": "कोमोरोस",
		"bn-IN": "কমোরোস",
		"bn-BD": "কমোরোস",
		"ta-IN": "கோமரோஸ்",
		"ta-LK": "கோமரோஸ்",
		"ta-SG": "கோமரோஸ்",
		"ta-MY": "கோமரோஸ்",
		"te-IN": "కొమొరోస్",
		"mr-IN": "कोमोरोज",
		"gu-IN": "કોમોરસ",
		"kn-IN": "ಕೊಮೊರೊಸ್",
		"ml-IN": "കോമൊറോസ്",
		"pa-IN": "ਕੋਮੋਰੋਸ",
		"ur-IN": "کوموروس",
		"ur-PK": "کوموروس",
		"or-IN": "କୋମୋରସ୍",
		"as-IN": "কোমোৰোজ",
		"ne-IN": "कोमोरोस",
		"ne-NP": "कोमोरोस",
		"si-LK": "කොමොරෝස්",
		"kok-IN": "कोमोरोस",
		"ks-IN": "کَمورَس",
		"brx-IN": "कम’र’ज",
		"mai-IN": "कोमोरोस",
		"dz-BT": "ཀོ་མོ་རོས",
		"ja-JP": "コモロ",
		"ko-KR": "코모로",
		"ko-KP": "코모로",
		"zh-CN": "科摩罗",
		"zh-Hans-CN": "科摩罗",
		"zh-Hant-TW": "葛摩",
		"zh-TW": "葛摩",
		"zh-HK": "科摩羅",
		"zh-MO": "科摩羅",
		"zh-SG": "科摩罗",
		"yue-Hant-HK": "葛摩",
		"yue-Hans-CN": "葛摩",
		"mn-MN": "Коморын арлууд",
		"ug-CN": "كومورو",
		"th-TH": "คอโมโรส",
		"lo-LA": "ໂຄໂມໂຣສ",
		"km-KH": "កូម័រ",
		"my-MM": "ကိုမိုရိုစ်",
		"vi-VN": "Comoros",
		"id-ID": "Komoro",
		"ms-MY": "Comoros",
		"ms-SG": "Comoros",
		"ms-BN": "Comoros",
		"jv-ID": "Komoro",
		"fil-PH": "Comoros",
		"ceb-PH": "Comoros",
		"ka-GE": "კომორის კუნძულები",
		"hy-AM": "Կոմորյան կղզիներ",
		"az-AZ": "Komor adaları",
		"az-Cyrl-AZ": "Комор адалары",
		"kk-KZ": "Комор аралдары",
		"ky-KG": "Коморос",
		"uz-UZ": "Komor orollari",
		"tg-TJ": "Комор",
		"tk-TM": "Komor adalary",
		"fa-IR": "کومور",
		"fa-AF": "کومور",
		"ps-AF": "کوموروس",
		"ps-PK": "کوموروس",
		"he-IL": "קומורו",
		"ar-SA": "جزر القمر",
		"ar-AE": "جزر القمر",
		"ar-QA": "جزر القمر",
		"ar-BH": "جزر القمر",
		"ar-KW": "جزر القمر",
		"ar-OM": "جزر القمر",
		"ar-YE": "جزر القمر",
		"ar-IQ": "جزر القمر",
		"ar-JO": "جزر القمر",
		"ar-LB": "جزر القمر",
		"ar-SY": "جزر القمر",
		"ar-PS": "جزر القمر",
		"en-US": "Comoros",
		"en-GB": "Comoros",
		"en-IE": "Comoros",
		"en-MT": "Comoros",
		"en-GI": "Comoros",
		"en-CY": "Comoros",
		"en-JE": "Comoros",
		"en-GG": "Comoros",
		"en-IM": "Comoros",
		"en-CA": "Comoros",
		"en-AU": "Comoros",
		"en-NZ": "Comoros",
		"en-ZA": "Comoros",
		"en-IN": "Comoros",
		"en-SG": "Comoros",
		"pt-AO": "Comores",
		"pt-MZ": "Comores",
		"pt-CV": "Comores",
		"pt-GW": "Comores",
		"pt-ST": "Comores",
		"pt-TL": "Comores",
		"pt-MO": "Comores",
		"es-ES": "Comoras",
		"es-419": "Comoras",
		"es-AD": "Comoras",
		"es-GI": "Comoras",
		"es-AR": "Comoras",
		"es-BO": "Comoras",
		"es-BR": "Comoras",
		"es-BZ": "Comoras",
		"es-CL": "Comoras",
		"es-CO": "Comoras",
		"es-CR": "Comoras",
		"es-CU": "Comoras",
		"es-DO": "Comoras",
		"es-EC": "Comoras",
		"es-GT": "Comoras",
		"es-HN": "Comoras",
		"es-MX": "Comoras",
		"es-NI": "Comoras",
		"es-PA": "Comoras",
		"es-PE": "Comoras",
		"es-PR": "Comoras",
		"es-PY": "Comoras",
		"es-SV": "Comoras",
		"es-US": "Comoras",
		"es-UY": "Comoras",
		"es-VE": "Comoras",
		"fr-FR": "Comores",
		"fr-BE": "Comores",
		"fr-CH": "Comores",
		"fr-LU": "Comores",
		"fr-MC": "Comores",
		"fr-AD": "Comores",
		"fr-CA": "Comores",
		"it-IT": "Comore",
		"it-CH": "Comore",
		"it-SM": "Comore",
		"it-VA": "Comore",
		"de-DE": "Komoren",
		"de-AT": "Komoren",
		"de-CH": "Komoren",
		"de-BE": "Komoren",
		"de-LI": "Komoren",
		"de-LU": "Komoren",
		"nl-NL": "Comoren",
		"nl-BE": "Comoren",
		"sv-SE": "Komorerna",
		"sv-FI": "Komorerna",
		"da-DK": "Comorerne",
		"nb-NO": "Komorene",
		"nn-NO": "Komorane",
		"fi-FI": "Komorit",
		"is-IS": "Kómoreyjar",
		"fo-FO": "Komoroyggjar",
		"et-EE": "Komoorid",
		"lv-LV": "Komoru salas",
		"lt-LT": "Komorai",
		"pl-PL": "Komory",
		"cs-CZ": "Komory",
		"sk-SK": "Komory",
		"sl-SI": "Komori",
		"hr-HR": "Komori",
		"bs-BA": "Komori",
		"sr-RS": "Коморска Острва",
		"sr-BA": "Комори",
		"sr-ME": "Komorska Ostrva",
		"mk-MK": "Коморски Острови",
		"bg-BG": "Коморски острови",
		"be-BY": "Каморскія астравы",
		"uk-UA": "Комори",
		"ru-RU": "Коморы",
		"el-GR": "Κομόρες",
		"el-CY": "Κομόρες",
		"ro-RO": "Comore",
		"ro-MD": "Comore",
		"hu-HU": "Comore-szigetek",
		"sq-AL": "Komore",
		"sq-XK": "Komore",
		"mt-MT": "Comoros",
		"ga-IE": "Oileáin Chomóra",
		"cy-GB": "Comoros",
		"gd-GB": "Comoros",
		"lb-LU": "Komoren",
		"ca-ES": "Comores",
		"ca-AD": "Comores",
		"ca-FR": "Comores",
		"ca-IT": "Comores",
		"eu-ES": "Komoreak",
		"eu-FR": "Komoreak",
		"gl-ES": "Comores",
		"tr-TR": "Komorlar",
		"tr-CY": "Komorlar"
	},
	"callingCode": "269",
	"phoneMasks": [
		{
			"mask": "### ## ##",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[3478]"
			]
		}
	]
} satisfies Country;
