import type { Country } from './types.js';

export const CPV = {
	"code": "CPV",
	"labels": {
		"pt-BR": "Cabo Verde",
		"pt-PT": "Cabo Verde",
		"qu-PE": "Cabo Verde",
		"qu-BO": "Cabo Verde",
		"qu-EC": "Cabo Verde",
		"chr-US": "ᎢᎬᎾᏕᎾ ᎢᏤᏳᏍᏗ",
		"hi-IN": "केप वर्ड",
		"bn-IN": "কেপ ভার্দে",
		"bn-BD": "কেপ ভার্দে",
		"ta-IN": "கேப் வெர்டே",
		"ta-LK": "கேப் வெர்டே",
		"ta-SG": "கேப் வெர்டே",
		"ta-MY": "கேப் வெர்டே",
		"te-IN": "కేప్ వెర్డె",
		"mr-IN": "केप व्हर्डे",
		"gu-IN": "કૅપ વર્ડે",
		"kn-IN": "ಕೇಪ್ ವರ್ಡೆ",
		"ml-IN": "കേപ്പ് വേർഡ്",
		"pa-IN": "ਕੇਪ ਵਰਡੇ",
		"ur-IN": "کیپ ورڈی",
		"ur-PK": "کیپ ورڈی",
		"or-IN": "କେପ୍ ଭର୍ଦେ",
		"as-IN": "কেপ ভার্দে",
		"ne-IN": "केप भर्डे",
		"ne-NP": "केप भर्डे",
		"si-LK": "කේප් වර්ඩ්",
		"kok-IN": "केप वर्दी",
		"ks-IN": "کیپ ؤرڑی",
		"brx-IN": "केप भेर्दे",
		"mai-IN": "कैप बर्डे",
		"dz-BT": "ཀེཔ་བཱཌ",
		"ja-JP": "カーボベルデ",
		"ko-KR": "카보베르데",
		"ko-KP": "카보베르데",
		"zh-CN": "佛得角",
		"zh-Hans-CN": "佛得角",
		"zh-Hant-TW": "維德角",
		"zh-TW": "維德角",
		"zh-HK": "佛得角",
		"zh-MO": "佛得角",
		"zh-SG": "佛得角",
		"yue-Hant-HK": "維德角",
		"yue-Hans-CN": "维德角",
		"mn-MN": "Кабо-Верде",
		"ug-CN": "يېشىل تۇمشۇق",
		"th-TH": "เคปเวิร์ด",
		"lo-LA": "ເຄບ ເວີດ",
		"km-KH": "កាប់វែរ",
		"my-MM": "ကိတ်ဗာဒီ",
		"vi-VN": "Cape Verde",
		"id-ID": "Tanjung Verde",
		"ms-MY": "Cape Verde",
		"ms-SG": "Cape Verde",
		"ms-BN": "Cape Verde",
		"jv-ID": "Pongol Verdé",
		"fil-PH": "Cape Verde",
		"ceb-PH": "Cape Verde",
		"ka-GE": "კაბო-ვერდე",
		"hy-AM": "Կաբո Վերդե",
		"az-AZ": "Kabo-Verde",
		"az-Cyrl-AZ": "Кабо-Верде",
		"kk-KZ": "Кабо-Верде",
		"ky-KG": "Кабо-Верде",
		"uz-UZ": "Kabo-Verde",
		"tg-TJ": "Кабо-Верде",
		"tk-TM": "Kabo-Werde",
		"fa-IR": "کیپ‌ورد",
		"fa-AF": "کیپ‌ورد",
		"ps-AF": "کیپ ورد",
		"ps-PK": "کیپ ورد",
		"he-IL": "כף ורדה",
		"ar-SA": "الرأس الأخضر",
		"ar-AE": "الرأس الأخضر",
		"ar-QA": "الرأس الأخضر",
		"ar-BH": "الرأس الأخضر",
		"ar-KW": "الرأس الأخضر",
		"ar-OM": "الرأس الأخضر",
		"ar-YE": "الرأس الأخضر",
		"ar-IQ": "الرأس الأخضر",
		"ar-JO": "الرأس الأخضر",
		"ar-LB": "الرأس الأخضر",
		"ar-SY": "الرأس الأخضر",
		"ar-PS": "الرأس الأخضر",
		"en-US": "Cape Verde",
		"en-GB": "Cape Verde",
		"en-IE": "Cape Verde",
		"en-MT": "Cape Verde",
		"en-GI": "Cape Verde",
		"en-CY": "Cape Verde",
		"en-JE": "Cape Verde",
		"en-GG": "Cape Verde",
		"en-IM": "Cape Verde",
		"en-CA": "Cape Verde",
		"en-AU": "Cape Verde",
		"en-NZ": "Cape Verde",
		"en-ZA": "Cape Verde",
		"en-IN": "Cape Verde",
		"en-SG": "Cape Verde",
		"pt-AO": "Cabo Verde",
		"pt-MZ": "Cabo Verde",
		"pt-CV": "Cabo Verde",
		"pt-GW": "Cabo Verde",
		"pt-ST": "Cabo Verde",
		"pt-TL": "Cabo Verde",
		"pt-MO": "Cabo Verde",
		"es-ES": "Cabo Verde",
		"es-419": "Cabo Verde",
		"es-AD": "Cabo Verde",
		"es-GI": "Cabo Verde",
		"es-AR": "Cabo Verde",
		"es-BO": "Cabo Verde",
		"es-BR": "Cabo Verde",
		"es-BZ": "Cabo Verde",
		"es-CL": "Cabo Verde",
		"es-CO": "Cabo Verde",
		"es-CR": "Cabo Verde",
		"es-CU": "Cabo Verde",
		"es-DO": "Cabo Verde",
		"es-EC": "Cabo Verde",
		"es-GT": "Cabo Verde",
		"es-HN": "Cabo Verde",
		"es-MX": "Cabo Verde",
		"es-NI": "Cabo Verde",
		"es-PA": "Cabo Verde",
		"es-PE": "Cabo Verde",
		"es-PR": "Cabo Verde",
		"es-PY": "Cabo Verde",
		"es-SV": "Cabo Verde",
		"es-US": "Cabo Verde",
		"es-UY": "Cabo Verde",
		"es-VE": "Cabo Verde",
		"fr-FR": "Cap-Vert",
		"fr-BE": "Cap-Vert",
		"fr-CH": "Cap-Vert",
		"fr-LU": "Cap-Vert",
		"fr-MC": "Cap-Vert",
		"fr-AD": "Cap-Vert",
		"fr-CA": "Cap-Vert",
		"it-IT": "Capo Verde",
		"it-CH": "Capo Verde",
		"it-SM": "Capo Verde",
		"it-VA": "Capo Verde",
		"de-DE": "Cabo Verde",
		"de-AT": "Cabo Verde",
		"de-CH": "Kapverden",
		"de-BE": "Cabo Verde",
		"de-LI": "Cabo Verde",
		"de-LU": "Cabo Verde",
		"nl-NL": "Kaapverdië",
		"nl-BE": "Kaapverdië",
		"sv-SE": "Kap Verde",
		"sv-FI": "Kap Verde",
		"da-DK": "Kap Verde",
		"nb-NO": "Kapp Verde",
		"nn-NO": "Kapp Verde",
		"fi-FI": "Kap Verde",
		"is-IS": "Grænhöfðaeyjar",
		"fo-FO": "Grønhøvdaoyggjar",
		"et-EE": "Roheneemesaared",
		"lv-LV": "Kaboverde",
		"lt-LT": "Žaliasis Kyšulys",
		"pl-PL": "Republika Zielonego Przylądka",
		"cs-CZ": "Kapverdy",
		"sk-SK": "Kapverdy",
		"sl-SI": "Zelenortski otoki",
		"hr-HR": "Zelenortska Republika",
		"bs-BA": "Zelenortska Ostrva",
		"sr-RS": "Зеленортска Острва",
		"sr-BA": "Зеленортска Острва",
		"sr-ME": "Zelenortska Ostrva",
		"mk-MK": "Кабо Верде",
		"bg-BG": "Кабо Верде",
		"be-BY": "Каба-Вердэ",
		"uk-UA": "Кабо-Верде",
		"ru-RU": "Кабо-Верде",
		"el-GR": "Πράσινο Ακρωτήριο",
		"el-CY": "Πράσινο Ακρωτήριο",
		"ro-RO": "Capul Verde",
		"ro-MD": "Capul Verde",
		"hu-HU": "Zöld-foki Köztársaság",
		"sq-AL": "Kepi i Gjelbër",
		"sq-XK": "Kepi i Gjelbër",
		"mt-MT": "Cape Verde",
		"ga-IE": "Rinn Verde",
		"cy-GB": "Cabo Verde",
		"gd-GB": "An Ceap Uaine",
		"lb-LU": "Kap Verde",
		"ca-ES": "Cap Verd",
		"ca-AD": "Cap Verd",
		"ca-FR": "Cap Verd",
		"ca-IT": "Cap Verd",
		"eu-ES": "Cabo Verde",
		"eu-FR": "Cabo Verde",
		"gl-ES": "Cabo Verde",
		"tr-TR": "Cabo Verde",
		"tr-CY": "Cabo Verde"
	},
	"callingCode": "238",
	"phoneMasks": [
		{
			"mask": "### ## ##",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-589]"
			]
		}
	]
} satisfies Country;
