import type { Country } from './types.js';

export const CRI = {
	"code": "CRI",
	"labels": {
		"pt-BR": "Costa Rica",
		"pt-PT": "Costa Rica",
		"qu-PE": "Costa Rica",
		"qu-BO": "Costa Rica",
		"qu-EC": "Costa Rica",
		"chr-US": "ᎪᏍᏓ ᎵᎧ",
		"hi-IN": "कोस्टारिका",
		"bn-IN": "কোস্টারিকা",
		"bn-BD": "কোস্টারিকা",
		"ta-IN": "கோஸ்டாரிகா",
		"ta-LK": "கோஸ்டாரிகா",
		"ta-SG": "கோஸ்டாரிகா",
		"ta-MY": "கோஸ்டாரிகா",
		"te-IN": "కోస్టా రికా",
		"mr-IN": "कोस्टा रिका",
		"gu-IN": "કોસ્ટા રિકા",
		"kn-IN": "ಕೊಸ್ಟಾ ರಿಕಾ",
		"ml-IN": "കോസ്റ്ററിക്ക",
		"pa-IN": "ਕੋਸਟਾ ਰੀਕਾ",
		"ur-IN": "کوسٹا ریکا",
		"ur-PK": "کوسٹا ریکا",
		"or-IN": "କୋଷ୍ଟା ରିକା",
		"as-IN": "কোষ্টা ৰিকা",
		"ne-IN": "कोष्टारिका",
		"ne-NP": "कोष्टारिका",
		"si-LK": "කොස්ටරිකාව",
		"kok-IN": "कोस्ता रिका",
		"ks-IN": "کوسٹا ریکا",
		"brx-IN": "कस्टा रिका",
		"mai-IN": "कोस्टारिका",
		"dz-BT": "ཀོས་ཊ་རི་ཀ",
		"ja-JP": "コスタリカ",
		"ko-KR": "코스타리카",
		"ko-KP": "코스타리카",
		"zh-CN": "哥斯达黎加",
		"zh-Hans-CN": "哥斯达黎加",
		"zh-Hant-TW": "哥斯大黎加",
		"zh-TW": "哥斯大黎加",
		"zh-HK": "哥斯達黎加",
		"zh-MO": "哥斯達黎加",
		"zh-SG": "哥斯达黎加",
		"yue-Hant-HK": "哥斯大黎加",
		"yue-Hans-CN": "哥斯大黎加",
		"mn-MN": "Коста-Рика",
		"ug-CN": "كوستارىكا",
		"th-TH": "คอสตาริกา",
		"lo-LA": "ໂຄສຕາ ຣິກາ",
		"km-KH": "កូស្តារីកា",
		"my-MM": "ကို့စ်တာရီကာ",
		"vi-VN": "Costa Rica",
		"id-ID": "Kosta Rika",
		"ms-MY": "Costa Rica",
		"ms-SG": "Costa Rica",
		"ms-BN": "Costa Rica",
		"jv-ID": "Kosta Rika",
		"fil-PH": "Costa Rica",
		"ceb-PH": "Costa Rica",
		"ka-GE": "კოსტა-რიკა",
		"hy-AM": "Կոստա Ռիկա",
		"az-AZ": "Kosta Rika",
		"az-Cyrl-AZ": "Коста Рика",
		"kk-KZ": "Коста-Рика",
		"ky-KG": "Коста-Рика",
		"uz-UZ": "Kosta-Rika",
		"tg-TJ": "Коста-Рика",
		"tk-TM": "Kosta-Rika",
		"fa-IR": "کاستاریکا",
		"fa-AF": "کاستریکا",
		"ps-AF": "کوستاریکا",
		"ps-PK": "کوستاریکا",
		"he-IL": "קוסטה ריקה",
		"ar-SA": "كوستاريكا",
		"ar-AE": "كوستاريكا",
		"ar-QA": "كوستاريكا",
		"ar-BH": "كوستاريكا",
		"ar-KW": "كوستاريكا",
		"ar-OM": "كوستاريكا",
		"ar-YE": "كوستاريكا",
		"ar-IQ": "كوستاريكا",
		"ar-JO": "كوستاريكا",
		"ar-LB": "كوستاريكا",
		"ar-SY": "كوستاريكا",
		"ar-PS": "كوستاريكا",
		"en-US": "Costa Rica",
		"en-GB": "Costa Rica",
		"en-IE": "Costa Rica",
		"en-MT": "Costa Rica",
		"en-GI": "Costa Rica",
		"en-CY": "Costa Rica",
		"en-JE": "Costa Rica",
		"en-GG": "Costa Rica",
		"en-IM": "Costa Rica",
		"en-CA": "Costa Rica",
		"en-AU": "Costa Rica",
		"en-NZ": "Costa Rica",
		"en-ZA": "Costa Rica",
		"en-IN": "Costa Rica",
		"en-SG": "Costa Rica",
		"pt-AO": "Costa Rica",
		"pt-MZ": "Costa Rica",
		"pt-CV": "Costa Rica",
		"pt-GW": "Costa Rica",
		"pt-ST": "Costa Rica",
		"pt-TL": "Costa Rica",
		"pt-MO": "Costa Rica",
		"es-ES": "Costa Rica",
		"es-419": "Costa Rica",
		"es-AD": "Costa Rica",
		"es-GI": "Costa Rica",
		"es-AR": "Costa Rica",
		"es-BO": "Costa Rica",
		"es-BR": "Costa Rica",
		"es-BZ": "Costa Rica",
		"es-CL": "Costa Rica",
		"es-CO": "Costa Rica",
		"es-CR": "Costa Rica",
		"es-CU": "Costa Rica",
		"es-DO": "Costa Rica",
		"es-EC": "Costa Rica",
		"es-GT": "Costa Rica",
		"es-HN": "Costa Rica",
		"es-MX": "Costa Rica",
		"es-NI": "Costa Rica",
		"es-PA": "Costa Rica",
		"es-PE": "Costa Rica",
		"es-PR": "Costa Rica",
		"es-PY": "Costa Rica",
		"es-SV": "Costa Rica",
		"es-US": "Costa Rica",
		"es-UY": "Costa Rica",
		"es-VE": "Costa Rica",
		"fr-FR": "Costa Rica",
		"fr-BE": "Costa Rica",
		"fr-CH": "Costa Rica",
		"fr-LU": "Costa Rica",
		"fr-MC": "Costa Rica",
		"fr-AD": "Costa Rica",
		"fr-CA": "Costa Rica",
		"it-IT": "Costa Rica",
		"it-CH": "Costa Rica",
		"it-SM": "Costa Rica",
		"it-VA": "Costa Rica",
		"de-DE": "Costa Rica",
		"de-AT": "Costa Rica",
		"de-CH": "Costa Rica",
		"de-BE": "Costa Rica",
		"de-LI": "Costa Rica",
		"de-LU": "Costa Rica",
		"nl-NL": "Costa Rica",
		"nl-BE": "Costa Rica",
		"sv-SE": "Costa Rica",
		"sv-FI": "Costa Rica",
		"da-DK": "Costa Rica",
		"nb-NO": "Costa Rica",
		"nn-NO": "Costa Rica",
		"fi-FI": "Costa Rica",
		"is-IS": "Kostaríka",
		"fo-FO": "Kosta Rika",
		"et-EE": "Costa Rica",
		"lv-LV": "Kostarika",
		"lt-LT": "Kosta Rika",
		"pl-PL": "Kostaryka",
		"cs-CZ": "Kostarika",
		"sk-SK": "Kostarika",
		"sl-SI": "Kostarika",
		"hr-HR": "Kostarika",
		"bs-BA": "Kostarika",
		"sr-RS": "Костарика",
		"sr-BA": "Костарика",
		"sr-ME": "Kostarika",
		"mk-MK": "Костарика",
		"bg-BG": "Коста Рика",
		"be-BY": "Коста-Рыка",
		"uk-UA": "Коста-Рика",
		"ru-RU": "Коста-Рика",
		"el-GR": "Κόστα Ρίκα",
		"el-CY": "Κόστα Ρίκα",
		"ro-RO": "Costa Rica",
		"ro-MD": "Costa Rica",
		"hu-HU": "Costa Rica",
		"sq-AL": "Kosta-Rikë",
		"sq-XK": "Kosta-Rikë",
		"mt-MT": "il-Costa Rica",
		"ga-IE": "Cósta Ríce",
		"cy-GB": "Costa Rica",
		"gd-GB": "Costa Rìcea",
		"lb-LU": "Costa Rica",
		"ca-ES": "Costa Rica",
		"ca-AD": "Costa Rica",
		"ca-FR": "Costa Rica",
		"ca-IT": "Costa Rica",
		"eu-ES": "Costa Rica",
		"eu-FR": "Costa Rica",
		"gl-ES": "Costa Rica",
		"tr-TR": "Kosta Rika",
		"tr-CY": "Kosta Rika"
	},
	"callingCode": "506",
	"phoneMasks": [
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[2-7]|8[3-9]"
			]
		},
		{
			"mask": "###-###-####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
