import type { Country } from './types.js';

export const CYM = {
	"code": "CYM",
	"labels": {
		"pt-BR": "Ilhas Cayman",
		"pt-PT": "Ilhas Caimão",
		"qu-PE": "Islas Caimán",
		"qu-BO": "Islas Caimán",
		"qu-EC": "Islas Caimán",
		"chr-US": "ᎨᎢᎹᏂ ᏚᎦᏚᏛᎢ",
		"hi-IN": "कैमेन द्वीपसमूह",
		"bn-IN": "কেম্যান দ্বীপপুঞ্জ",
		"bn-BD": "কেম্যান দ্বীপপুঞ্জ",
		"ta-IN": "கெய்மென் தீவுகள்",
		"ta-LK": "கெய்மென் தீவுகள்",
		"ta-SG": "கெய்மென் தீவுகள்",
		"ta-MY": "கெய்மென் தீவுகள்",
		"te-IN": "కేమాన్ దీవులు",
		"mr-IN": "केमन बेटे",
		"gu-IN": "કેમેન આઇલેન્ડ્સ",
		"kn-IN": "ಕೇಮನ್ ದ್ವೀಪಗಳು",
		"ml-IN": "കേയ്മാൻ ദ്വീപുകൾ",
		"pa-IN": "ਕੇਮੈਨ ਟਾਪੂ",
		"ur-IN": "کیمین آئلینڈز",
		"ur-PK": "کیمین آئلینڈز",
		"or-IN": "କେମ୍ୟାନ୍‌ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "কেইমেন দ্বীপপুঞ্জ",
		"ne-IN": "केयमान टापु",
		"ne-NP": "केयमान टापु",
		"si-LK": "කේමන් දූපත්",
		"kok-IN": "कैमेन आइलैंड्स",
		"ks-IN": "کیمَن جٔزیٖرٕ",
		"brx-IN": "कैमेन द्वीपफोर",
		"mai-IN": "कैमेन द्वीपसमूह",
		"dz-BT": "ཁེ་མེན་གླིང་ཚོམ",
		"ja-JP": "ケイマン諸島",
		"ko-KR": "케이맨 제도",
		"ko-KP": "케이맨 제도",
		"zh-CN": "开曼群岛",
		"zh-Hans-CN": "开曼群岛",
		"zh-Hant-TW": "開曼群島",
		"zh-TW": "開曼群島",
		"zh-HK": "開曼群島",
		"zh-MO": "開曼群島",
		"zh-SG": "开曼群岛",
		"yue-Hant-HK": "開曼群島",
		"yue-Hans-CN": "开曼群岛",
		"mn-MN": "Кайманы арлууд",
		"ug-CN": "كايمان ئاراللىرى",
		"th-TH": "หมู่เกาะเคย์แมน",
		"lo-LA": "ໝູ່ເກາະ ເຄແມນ",
		"km-KH": "កោះ​កៃម៉ង់",
		"my-MM": "ကေမန် ကျွန်းစု",
		"vi-VN": "Quần đảo Cayman",
		"id-ID": "Kepulauan Cayman",
		"ms-MY": "Kepulauan Cayman",
		"ms-SG": "Kepulauan Cayman",
		"ms-BN": "Kepulauan Cayman",
		"jv-ID": "Kapuloan Kéman",
		"fil-PH": "Cayman Islands",
		"ceb-PH": "Cayman Islands",
		"ka-GE": "კაიმანის კუნძულები",
		"hy-AM": "Կայմանյան կղզիներ",
		"az-AZ": "Kayman adaları",
		"az-Cyrl-AZ": "Кајман адалары",
		"kk-KZ": "Кайман аралдары",
		"ky-KG": "Кайман аралдары",
		"uz-UZ": "Kayman orollari",
		"tg-TJ": "Ҷазираҳои Кайман",
		"tk-TM": "Kaýman adalary",
		"fa-IR": "جزایر کِیمن",
		"fa-AF": "جزایر کِیمن",
		"ps-AF": "کیمان ټاپوګان",
		"ps-PK": "کیمان ټاپوګان",
		"he-IL": "איי קיימן",
		"ar-SA": "جزر كايمان",
		"ar-AE": "جزر كايمان",
		"ar-QA": "جزر كايمان",
		"ar-BH": "جزر كايمان",
		"ar-KW": "جزر كايمان",
		"ar-OM": "جزر كايمان",
		"ar-YE": "جزر كايمان",
		"ar-IQ": "جزر كايمان",
		"ar-JO": "جزر كايمان",
		"ar-LB": "جزر كايمان",
		"ar-SY": "جزر كايمان",
		"ar-PS": "جزر كايمان",
		"en-US": "Cayman Islands",
		"en-GB": "Cayman Islands",
		"en-IE": "Cayman Islands",
		"en-MT": "Cayman Islands",
		"en-GI": "Cayman Islands",
		"en-CY": "Cayman Islands",
		"en-JE": "Cayman Islands",
		"en-GG": "Cayman Islands",
		"en-IM": "Cayman Islands",
		"en-CA": "Cayman Islands",
		"en-AU": "Cayman Islands",
		"en-NZ": "Cayman Islands",
		"en-ZA": "Cayman Islands",
		"en-IN": "Cayman Islands",
		"en-SG": "Cayman Islands",
		"pt-AO": "Ilhas Caimão",
		"pt-MZ": "Ilhas Caimão",
		"pt-CV": "Ilhas Caimão",
		"pt-GW": "Ilhas Caimão",
		"pt-ST": "Ilhas Caimão",
		"pt-TL": "Ilhas Caimão",
		"pt-MO": "Ilhas Caimão",
		"es-ES": "Islas Caimán",
		"es-419": "Islas Caimán",
		"es-AD": "Islas Caimán",
		"es-GI": "Islas Caimán",
		"es-AR": "Islas Caimán",
		"es-BO": "Islas Caimán",
		"es-BR": "Islas Caimán",
		"es-BZ": "Islas Caimán",
		"es-CL": "Islas Caimán",
		"es-CO": "Islas Caimán",
		"es-CR": "Islas Caimán",
		"es-CU": "Islas Caimán",
		"es-DO": "Islas Caimán",
		"es-EC": "Islas Caimán",
		"es-GT": "Islas Caimán",
		"es-HN": "Islas Caimán",
		"es-MX": "Islas Caimán",
		"es-NI": "Islas Caimán",
		"es-PA": "Islas Caimán",
		"es-PE": "Islas Caimán",
		"es-PR": "Islas Caimán",
		"es-PY": "Islas Caimán",
		"es-SV": "Islas Caimán",
		"es-US": "Islas Caimán",
		"es-UY": "Islas Caimán",
		"es-VE": "Islas Caimán",
		"fr-FR": "Îles Caïmans",
		"fr-BE": "Îles Caïmans",
		"fr-CH": "Îles Caïmans",
		"fr-LU": "Îles Caïmans",
		"fr-MC": "Îles Caïmans",
		"fr-AD": "Îles Caïmans",
		"fr-CA": "Îles Caïmans",
		"it-IT": "Isole Cayman",
		"it-CH": "Isole Cayman",
		"it-SM": "Isole Cayman",
		"it-VA": "Isole Cayman",
		"de-DE": "Kaimaninseln",
		"de-AT": "Kaimaninseln",
		"de-CH": "Kaimaninseln",
		"de-BE": "Kaimaninseln",
		"de-LI": "Kaimaninseln",
		"de-LU": "Kaimaninseln",
		"nl-NL": "Kaaimaneilanden",
		"nl-BE": "Kaaimaneilanden",
		"sv-SE": "Caymanöarna",
		"sv-FI": "Caymanöarna",
		"da-DK": "Caymanøerne",
		"nb-NO": "Caymanøyene",
		"nn-NO": "Caymanøyane",
		"fi-FI": "Caymansaaret",
		"is-IS": "Caymaneyjar",
		"fo-FO": "Caymanoyggjar",
		"et-EE": "Kaimanisaared",
		"lv-LV": "Kaimanu salas",
		"lt-LT": "Kaimanų Salos",
		"pl-PL": "Kajmany",
		"cs-CZ": "Kajmanské ostrovy",
		"sk-SK": "Kajmanie ostrovy",
		"sl-SI": "Kajmanski otoki",
		"hr-HR": "Kajmanski Otoci",
		"bs-BA": "Kajmanska ostrva",
		"sr-RS": "Кајманска Острва",
		"sr-BA": "Кајманска Острва",
		"sr-ME": "Kajmanska Ostrva",
		"mk-MK": "Кајмански Острови",
		"bg-BG": "Кайманови острови",
		"be-BY": "Кайманавы астравы",
		"uk-UA": "Кайманові Острови",
		"ru-RU": "о-ва Кайман",
		"el-GR": "Νήσοι Κέιμαν",
		"el-CY": "Νήσοι Κέιμαν",
		"ro-RO": "Insulele Cayman",
		"ro-MD": "Insulele Cayman",
		"hu-HU": "Kajmán-szigetek",
		"sq-AL": "Ishujt Kajman",
		"sq-XK": "Ishujt Kajman",
		"mt-MT": "il-Gżejjer Cayman",
		"ga-IE": "Oileáin Cayman",
		"cy-GB": "Ynysoedd Cayman",
		"gd-GB": "Na h-Eileanan Caimean",
		"lb-LU": "Kaimaninselen",
		"ca-ES": "Illes Caiman",
		"ca-AD": "Illes Caiman",
		"ca-FR": "Illes Caiman",
		"ca-IT": "Illes Caiman",
		"eu-ES": "Kaiman uharteak",
		"eu-FR": "Kaiman uharteak",
		"gl-ES": "Illas Caimán",
		"tr-TR": "Cayman Adaları",
		"tr-CY": "Cayman Adaları"
	},
	"callingCode": "1345",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
