import type { Country } from './types.js';

export const DOM = {
	"code": "DOM",
	"labels": {
		"pt-BR": "República Dominicana",
		"pt-PT": "República Dominicana",
		"qu-PE": "República Dominicana",
		"qu-BO": "República Dominicana",
		"qu-EC": "República Dominicana",
		"chr-US": "ᏙᎻᏂᎧᏂ ᏍᎦᏚᎩ",
		"hi-IN": "डोमिनिकन गणराज्य",
		"bn-IN": "ডোমেনিকান প্রজাতন্ত্র",
		"bn-BD": "ডোমেনিকান প্রজাতন্ত্র",
		"ta-IN": "டொமினிகன் குடியரசு",
		"ta-LK": "டொமினிகன் குடியரசு",
		"ta-SG": "டொமினிகன் குடியரசு",
		"ta-MY": "டொமினிகன் குடியரசு",
		"te-IN": "డొమినికన్ రిపబ్లిక్",
		"mr-IN": "डोमिनिकन प्रजासत्ताक",
		"gu-IN": "ડોમિનિકન રિપબ્લિક",
		"kn-IN": "ಡೊಮೆನಿಕನ್ ರಿಪಬ್ಲಿಕ್",
		"ml-IN": "ഡൊമിനിക്കൻ റിപ്പബ്ലിക്ക്",
		"pa-IN": "ਡੋਮੀਨਿਕਾਈ ਗਣਰਾਜ",
		"ur-IN": "جمہوریہ ڈومينيکن",
		"ur-PK": "جمہوریہ ڈومينيکن",
		"or-IN": "ଡୋମିନିକାନ୍‌ ସାଧାରଣତନ୍ତ୍ର",
		"as-IN": "ড’মিনিকান ৰিপাব্লিক",
		"ne-IN": "डोमिनिकन गणतन्त्र",
		"ne-NP": "डोमिनिकन गणतन्त्र",
		"si-LK": "ඩොමිනිකා ජනරජය",
		"kok-IN": "डोमिनिकन प्रजासत्ताक",
		"ks-IN": "ڈومِنِکَن جموٗرِیَت",
		"brx-IN": "दमिनिकान सुबुंखुंथाय",
		"mai-IN": "डोमिनिकन रिपब्लिक",
		"dz-BT": "ཌོ་མི་ནི་ཀཱན་ རི་པབ་ལིཀ",
		"ja-JP": "ドミニカ共和国",
		"ko-KR": "도미니카 공화국",
		"ko-KP": "도미니카 공화국",
		"zh-CN": "多米尼加共和国",
		"zh-Hans-CN": "多米尼加共和国",
		"zh-Hant-TW": "多明尼加共和國",
		"zh-TW": "多明尼加共和國",
		"zh-HK": "多米尼加共和國",
		"zh-MO": "多米尼加共和國",
		"zh-SG": "多米尼加共和国",
		"yue-Hant-HK": "多明尼加共和國",
		"yue-Hans-CN": "多明尼加共和国",
		"mn-MN": "Бүгд Найрамдах Доминикан Улс",
		"ug-CN": "دومىنىكا جۇمھۇرىيىتى",
		"th-TH": "สาธารณรัฐโดมินิกัน",
		"lo-LA": "ສາທາລະນະລັດ ໂດມິນິກັນ",
		"km-KH": "សាធារណរដ្ឋ​ដូមីនីក",
		"my-MM": "ဒိုမီနီကန်",
		"vi-VN": "Cộng hòa Dominica",
		"id-ID": "Republik Dominika",
		"ms-MY": "Republik Dominica",
		"ms-SG": "Republik Dominica",
		"ms-BN": "Republik Dominica",
		"jv-ID": "Républik Dominika",
		"fil-PH": "Dominican Republic",
		"ceb-PH": "Dominican Republic",
		"ka-GE": "დომინიკელთა რესპუბლიკა",
		"hy-AM": "Դոմինիկյան Հանրապետություն",
		"az-AZ": "Dominikan Respublikası",
		"az-Cyrl-AZ": "Доминикан Республикасы",
		"kk-KZ": "Доминикан Республикасы",
		"ky-KG": "Доминика Республикасы",
		"uz-UZ": "Dominikan Respublikasi",
		"tg-TJ": "Ҷумҳурии Доминикан",
		"tk-TM": "Dominikan Respublikasy",
		"fa-IR": "جمهوری دومینیکن",
		"fa-AF": "جمهوری دومینیکن",
		"ps-AF": "جمهوريه ډومينيکن",
		"ps-PK": "جمهوريه ډومينيکن",
		"he-IL": "הרפובליקה הדומיניקנית",
		"ar-SA": "جمهورية الدومينيكان",
		"ar-AE": "جمهورية الدومينيكان",
		"ar-QA": "جمهورية الدومينيكان",
		"ar-BH": "جمهورية الدومينيكان",
		"ar-KW": "جمهورية الدومينيكان",
		"ar-OM": "جمهورية الدومينيكان",
		"ar-YE": "جمهورية الدومينيكان",
		"ar-IQ": "جمهورية الدومينيكان",
		"ar-JO": "جمهورية الدومينيكان",
		"ar-LB": "جمهورية الدومينيكان",
		"ar-SY": "جمهورية الدومينيكان",
		"ar-PS": "جمهورية الدومينيكان",
		"en-US": "Dominican Republic",
		"en-GB": "Dominican Republic",
		"en-IE": "Dominican Republic",
		"en-MT": "Dominican Republic",
		"en-GI": "Dominican Republic",
		"en-CY": "Dominican Republic",
		"en-JE": "Dominican Republic",
		"en-GG": "Dominican Republic",
		"en-IM": "Dominican Republic",
		"en-CA": "Dominican Republic",
		"en-AU": "Dominican Republic",
		"en-NZ": "Dominican Republic",
		"en-ZA": "Dominican Republic",
		"en-IN": "Dominican Republic",
		"en-SG": "Dominican Republic",
		"pt-AO": "República Dominicana",
		"pt-MZ": "República Dominicana",
		"pt-CV": "República Dominicana",
		"pt-GW": "República Dominicana",
		"pt-ST": "República Dominicana",
		"pt-TL": "República Dominicana",
		"pt-MO": "República Dominicana",
		"es-ES": "República Dominicana",
		"es-419": "República Dominicana",
		"es-AD": "República Dominicana",
		"es-GI": "República Dominicana",
		"es-AR": "República Dominicana",
		"es-BO": "República Dominicana",
		"es-BR": "República Dominicana",
		"es-BZ": "República Dominicana",
		"es-CL": "República Dominicana",
		"es-CO": "República Dominicana",
		"es-CR": "República Dominicana",
		"es-CU": "República Dominicana",
		"es-DO": "República Dominicana",
		"es-EC": "República Dominicana",
		"es-GT": "República Dominicana",
		"es-HN": "República Dominicana",
		"es-MX": "República Dominicana",
		"es-NI": "República Dominicana",
		"es-PA": "República Dominicana",
		"es-PE": "República Dominicana",
		"es-PR": "República Dominicana",
		"es-PY": "República Dominicana",
		"es-SV": "República Dominicana",
		"es-US": "República Dominicana",
		"es-UY": "República Dominicana",
		"es-VE": "República Dominicana",
		"fr-FR": "République dominicaine",
		"fr-BE": "République dominicaine",
		"fr-CH": "République dominicaine",
		"fr-LU": "République dominicaine",
		"fr-MC": "République dominicaine",
		"fr-AD": "République dominicaine",
		"fr-CA": "République dominicaine",
		"it-IT": "Repubblica Dominicana",
		"it-CH": "Repubblica Dominicana",
		"it-SM": "Repubblica Dominicana",
		"it-VA": "Repubblica Dominicana",
		"de-DE": "Dominikanische Republik",
		"de-AT": "Dominikanische Republik",
		"de-CH": "Dominikanische Republik",
		"de-BE": "Dominikanische Republik",
		"de-LI": "Dominikanische Republik",
		"de-LU": "Dominikanische Republik",
		"nl-NL": "Dominicaanse Republiek",
		"nl-BE": "Dominicaanse Republiek",
		"sv-SE": "Dominikanska republiken",
		"sv-FI": "Dominikanska republiken",
		"da-DK": "Den Dominikanske Republik",
		"nb-NO": "Den dominikanske republikk",
		"nn-NO": "Den dominikanske republikken",
		"fi-FI": "Dominikaaninen tasavalta",
		"is-IS": "Dóminíska lýðveldið",
		"fo-FO": "Dominikalýðveldið",
		"et-EE": "Dominikaani Vabariik",
		"lv-LV": "Dominikāna",
		"lt-LT": "Dominikos Respublika",
		"pl-PL": "Dominikana",
		"cs-CZ": "Dominikánská republika",
		"sk-SK": "Dominikánska republika",
		"sl-SI": "Dominikanska republika",
		"hr-HR": "Dominikanska Republika",
		"bs-BA": "Dominikanska Republika",
		"sr-RS": "Доминиканска Република",
		"sr-BA": "Доминиканска Република",
		"sr-ME": "Dominikanska Republika",
		"mk-MK": "Доминиканска Република",
		"bg-BG": "Доминиканска република",
		"be-BY": "Дамініканская Рэспубліка",
		"uk-UA": "Домініканська Республіка",
		"ru-RU": "Доминиканская Республика",
		"el-GR": "Δομινικανή Δημοκρατία",
		"el-CY": "Δομινικανή Δημοκρατία",
		"ro-RO": "Republica Dominicană",
		"ro-MD": "Republica Dominicană",
		"hu-HU": "Dominikai Köztársaság",
		"sq-AL": "Republika Dominikane",
		"sq-XK": "Republika Dominikane",
		"mt-MT": "ir-Repubblika Dominicana",
		"ga-IE": "an Phoblacht Dhoiminiceach",
		"cy-GB": "Gweriniaeth Dominica",
		"gd-GB": "A’ Phoblachd Dhoiminiceach",
		"lb-LU": "Dominikanesch Republik",
		"ca-ES": "República Dominicana",
		"ca-AD": "República Dominicana",
		"ca-FR": "República Dominicana",
		"ca-IT": "República Dominicana",
		"eu-ES": "Dominikar Errepublika",
		"eu-FR": "Dominikar Errepublika",
		"gl-ES": "República Dominicana",
		"tr-TR": "Dominik Cumhuriyeti",
		"tr-CY": "Dominik Cumhuriyeti"
	},
	"callingCode": "1",
	"phoneMasks": [
		{
			"mask": "(###) ###-####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
