import type { Country } from './types.js';

export const ECU = {
	"code": "ECU",
	"labels": {
		"pt-BR": "Equador",
		"pt-PT": "Equador",
		"qu-PE": "Ecuador",
		"qu-BO": "Ecuador",
		"qu-EC": "Ecuador",
		"chr-US": "ᎡᏆᏙᎵ",
		"hi-IN": "इक्वाडोर",
		"bn-IN": "ইকুয়েডর",
		"bn-BD": "ইকুয়েডর",
		"ta-IN": "ஈக்வடார்",
		"ta-LK": "ஈக்வடார்",
		"ta-SG": "ஈக்வடார்",
		"ta-MY": "ஈக்வடார்",
		"te-IN": "ఈక్వడార్",
		"mr-IN": "इक्वाडोर",
		"gu-IN": "એક્વાડોર",
		"kn-IN": "ಈಕ್ವೆಡಾರ್",
		"ml-IN": "ഇക്വഡോർ",
		"pa-IN": "ਇਕਵੇਡੋਰ",
		"ur-IN": "ایکواڈور",
		"ur-PK": "ایکواڈور",
		"or-IN": "ଇକ୍ୱେଡର୍‌",
		"as-IN": "ইকুৱেডৰ",
		"ne-IN": "इक्वेडोर",
		"ne-NP": "इक्वेडोर",
		"si-LK": "ඉක්වදෝරය",
		"kok-IN": "इक्वाडोर",
		"ks-IN": "اِکواڑور",
		"brx-IN": "एक्वाड’र",
		"mai-IN": "इक्वाडोर",
		"dz-BT": "ཨེ་ཁྭ་ཌོར",
		"ja-JP": "エクアドル",
		"ko-KR": "에콰도르",
		"ko-KP": "에콰도르",
		"zh-CN": "厄瓜多尔",
		"zh-Hans-CN": "厄瓜多尔",
		"zh-Hant-TW": "厄瓜多",
		"zh-TW": "厄瓜多",
		"zh-HK": "厄瓜多爾",
		"zh-MO": "厄瓜多爾",
		"zh-SG": "厄瓜多尔",
		"yue-Hant-HK": "厄瓜多",
		"yue-Hans-CN": "厄瓜多",
		"mn-MN": "Эквадор",
		"ug-CN": "ئېكۋاتور",
		"th-TH": "เอกวาดอร์",
		"lo-LA": "ເອກວາດໍ",
		"km-KH": "អេក្វាទ័រ",
		"my-MM": "အီကွေဒေါ",
		"vi-VN": "Ecuador",
		"id-ID": "Ekuador",
		"ms-MY": "Ecuador",
		"ms-SG": "Ecuador",
		"ms-BN": "Ecuador",
		"jv-ID": "Ékuadhor",
		"fil-PH": "Ecuador",
		"ceb-PH": "Ecuador",
		"ka-GE": "ეკვადორი",
		"hy-AM": "Էկվադոր",
		"az-AZ": "Ekvador",
		"az-Cyrl-AZ": "Еквадор",
		"kk-KZ": "Эквадор",
		"ky-KG": "Эквадор",
		"uz-UZ": "Ekvador",
		"tg-TJ": "Эквадор",
		"tk-TM": "Ekwador",
		"fa-IR": "اکوادور",
		"fa-AF": "اکوادور",
		"ps-AF": "اکوادور",
		"ps-PK": "اکوادور",
		"he-IL": "אקוודור",
		"ar-SA": "الإكوادور",
		"ar-AE": "الإكوادور",
		"ar-QA": "الإكوادور",
		"ar-BH": "الإكوادور",
		"ar-KW": "الإكوادور",
		"ar-OM": "الإكوادور",
		"ar-YE": "الإكوادور",
		"ar-IQ": "الإكوادور",
		"ar-JO": "الإكوادور",
		"ar-LB": "الإكوادور",
		"ar-SY": "الإكوادور",
		"ar-PS": "الإكوادور",
		"en-US": "Ecuador",
		"en-GB": "Ecuador",
		"en-IE": "Ecuador",
		"en-MT": "Ecuador",
		"en-GI": "Ecuador",
		"en-CY": "Ecuador",
		"en-JE": "Ecuador",
		"en-GG": "Ecuador",
		"en-IM": "Ecuador",
		"en-CA": "Ecuador",
		"en-AU": "Ecuador",
		"en-NZ": "Ecuador",
		"en-ZA": "Ecuador",
		"en-IN": "Ecuador",
		"en-SG": "Ecuador",
		"pt-AO": "Equador",
		"pt-MZ": "Equador",
		"pt-CV": "Equador",
		"pt-GW": "Equador",
		"pt-ST": "Equador",
		"pt-TL": "Equador",
		"pt-MO": "Equador",
		"es-ES": "Ecuador",
		"es-419": "Ecuador",
		"es-AD": "Ecuador",
		"es-GI": "Ecuador",
		"es-AR": "Ecuador",
		"es-BO": "Ecuador",
		"es-BR": "Ecuador",
		"es-BZ": "Ecuador",
		"es-CL": "Ecuador",
		"es-CO": "Ecuador",
		"es-CR": "Ecuador",
		"es-CU": "Ecuador",
		"es-DO": "Ecuador",
		"es-EC": "Ecuador",
		"es-GT": "Ecuador",
		"es-HN": "Ecuador",
		"es-MX": "Ecuador",
		"es-NI": "Ecuador",
		"es-PA": "Ecuador",
		"es-PE": "Ecuador",
		"es-PR": "Ecuador",
		"es-PY": "Ecuador",
		"es-SV": "Ecuador",
		"es-US": "Ecuador",
		"es-UY": "Ecuador",
		"es-VE": "Ecuador",
		"fr-FR": "Équateur",
		"fr-BE": "Équateur",
		"fr-CH": "Équateur",
		"fr-LU": "Équateur",
		"fr-MC": "Équateur",
		"fr-AD": "Équateur",
		"fr-CA": "Équateur",
		"it-IT": "Ecuador",
		"it-CH": "Ecuador",
		"it-SM": "Ecuador",
		"it-VA": "Ecuador",
		"de-DE": "Ecuador",
		"de-AT": "Ecuador",
		"de-CH": "Ecuador",
		"de-BE": "Ecuador",
		"de-LI": "Ecuador",
		"de-LU": "Ecuador",
		"nl-NL": "Ecuador",
		"nl-BE": "Ecuador",
		"sv-SE": "Ecuador",
		"sv-FI": "Ecuador",
		"da-DK": "Ecuador",
		"nb-NO": "Ecuador",
		"nn-NO": "Ecuador",
		"fi-FI": "Ecuador",
		"is-IS": "Ekvador",
		"fo-FO": "Ekvador",
		"et-EE": "Ecuador",
		"lv-LV": "Ekvadora",
		"lt-LT": "Ekvadoras",
		"pl-PL": "Ekwador",
		"cs-CZ": "Ekvádor",
		"sk-SK": "Ekvádor",
		"sl-SI": "Ekvador",
		"hr-HR": "Ekvador",
		"bs-BA": "Ekvador",
		"sr-RS": "Еквадор",
		"sr-BA": "Еквадор",
		"sr-ME": "Ekvador",
		"mk-MK": "Еквадор",
		"bg-BG": "Еквадор",
		"be-BY": "Эквадор",
		"uk-UA": "Еквадор",
		"ru-RU": "Эквадор",
		"el-GR": "Ισημερινός",
		"el-CY": "Ισημερινός",
		"ro-RO": "Ecuador",
		"ro-MD": "Ecuador",
		"hu-HU": "Ecuador",
		"sq-AL": "Ekuador",
		"sq-XK": "Ekuador",
		"mt-MT": "l-Ekwador",
		"ga-IE": "Eacuadór",
		"cy-GB": "Ecuador",
		"gd-GB": "Eacuador",
		"lb-LU": "Ecuador",
		"ca-ES": "Equador",
		"ca-AD": "Equador",
		"ca-FR": "Equador",
		"ca-IT": "Equador",
		"eu-ES": "Ekuador",
		"eu-FR": "Ekuador",
		"gl-ES": "Ecuador",
		"tr-TR": "Ekvador",
		"tr-CY": "Ekvador"
	},
	"callingCode": "593",
	"phoneMasks": [
		{
			"mask": "# ###-####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[2-7]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"9"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "#### ### ####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"1"
			]
		}
	]
} satisfies Country;
