import type { Country } from './types.js';

export const EGY = {
	"code": "EGY",
	"labels": {
		"pt-BR": "Egito",
		"pt-PT": "Egito",
		"qu-PE": "Egipto",
		"qu-BO": "Egipto",
		"qu-EC": "Egipto",
		"chr-US": "ᎢᏥᏈᎢ",
		"hi-IN": "मिस्र",
		"bn-IN": "মিশর",
		"bn-BD": "মিশর",
		"ta-IN": "எகிப்து",
		"ta-LK": "எகிப்து",
		"ta-SG": "எகிப்து",
		"ta-MY": "எகிப்து",
		"te-IN": "ఈజిప్ట్",
		"mr-IN": "इजिप्त",
		"gu-IN": "ઇજિપ્ત",
		"kn-IN": "ಈಜಿಪ್ಟ್",
		"ml-IN": "ഈജിപ്ത്",
		"pa-IN": "ਮਿਸਰ",
		"ur-IN": "مصر",
		"ur-PK": "مصر",
		"or-IN": "ଇଜିପ୍ଟ",
		"as-IN": "ইজিপ্ত",
		"ne-IN": "इजिप्ट",
		"ne-NP": "इजिप्ट",
		"si-LK": "ඊජිප්තුව",
		"kok-IN": "ईजिप्त",
		"ks-IN": "مصر",
		"brx-IN": "ईजिप्त",
		"mai-IN": "मिस्र",
		"dz-BT": "ཨི་ཇིབཊ",
		"ja-JP": "エジプト",
		"ko-KR": "이집트",
		"ko-KP": "이집트",
		"zh-CN": "埃及",
		"zh-Hans-CN": "埃及",
		"zh-Hant-TW": "埃及",
		"zh-TW": "埃及",
		"zh-HK": "埃及",
		"zh-MO": "埃及",
		"zh-SG": "埃及",
		"yue-Hant-HK": "埃及",
		"yue-Hans-CN": "埃及",
		"mn-MN": "Египет",
		"ug-CN": "مىسىر",
		"th-TH": "อียิปต์",
		"lo-LA": "ອີຢິບ",
		"km-KH": "អេហ្ស៊ីប",
		"my-MM": "အီဂျစ်",
		"vi-VN": "Ai Cập",
		"id-ID": "Mesir",
		"ms-MY": "Mesir",
		"ms-SG": "Mesir",
		"ms-BN": "Mesir",
		"jv-ID": "Mesir",
		"fil-PH": "Egypt",
		"ceb-PH": "Egypt",
		"ka-GE": "ეგვიპტე",
		"hy-AM": "Եգիպտոս",
		"az-AZ": "Misir",
		"az-Cyrl-AZ": "Мисир",
		"kk-KZ": "Мысыр",
		"ky-KG": "Египет",
		"uz-UZ": "Misr",
		"tg-TJ": "Миср",
		"tk-TM": "Müsür",
		"fa-IR": "مصر",
		"fa-AF": "مصر",
		"ps-AF": "مصر",
		"ps-PK": "مصر",
		"he-IL": "מצרים",
		"ar-SA": "مصر",
		"ar-AE": "مصر",
		"ar-QA": "مصر",
		"ar-BH": "مصر",
		"ar-KW": "مصر",
		"ar-OM": "مصر",
		"ar-YE": "مصر",
		"ar-IQ": "مصر",
		"ar-JO": "مصر",
		"ar-LB": "مصر",
		"ar-SY": "مصر",
		"ar-PS": "مصر",
		"en-US": "Egypt",
		"en-GB": "Egypt",
		"en-IE": "Egypt",
		"en-MT": "Egypt",
		"en-GI": "Egypt",
		"en-CY": "Egypt",
		"en-JE": "Egypt",
		"en-GG": "Egypt",
		"en-IM": "Egypt",
		"en-CA": "Egypt",
		"en-AU": "Egypt",
		"en-NZ": "Egypt",
		"en-ZA": "Egypt",
		"en-IN": "Egypt",
		"en-SG": "Egypt",
		"pt-AO": "Egito",
		"pt-MZ": "Egito",
		"pt-CV": "Egito",
		"pt-GW": "Egito",
		"pt-ST": "Egito",
		"pt-TL": "Egito",
		"pt-MO": "Egito",
		"es-ES": "Egipto",
		"es-419": "Egipto",
		"es-AD": "Egipto",
		"es-GI": "Egipto",
		"es-AR": "Egipto",
		"es-BO": "Egipto",
		"es-BR": "Egipto",
		"es-BZ": "Egipto",
		"es-CL": "Egipto",
		"es-CO": "Egipto",
		"es-CR": "Egipto",
		"es-CU": "Egipto",
		"es-DO": "Egipto",
		"es-EC": "Egipto",
		"es-GT": "Egipto",
		"es-HN": "Egipto",
		"es-MX": "Egipto",
		"es-NI": "Egipto",
		"es-PA": "Egipto",
		"es-PE": "Egipto",
		"es-PR": "Egipto",
		"es-PY": "Egipto",
		"es-SV": "Egipto",
		"es-US": "Egipto",
		"es-UY": "Egipto",
		"es-VE": "Egipto",
		"fr-FR": "Égypte",
		"fr-BE": "Égypte",
		"fr-CH": "Égypte",
		"fr-LU": "Égypte",
		"fr-MC": "Égypte",
		"fr-AD": "Égypte",
		"fr-CA": "Égypte",
		"it-IT": "Egitto",
		"it-CH": "Egitto",
		"it-SM": "Egitto",
		"it-VA": "Egitto",
		"de-DE": "Ägypten",
		"de-AT": "Ägypten",
		"de-CH": "Ägypten",
		"de-BE": "Ägypten",
		"de-LI": "Ägypten",
		"de-LU": "Ägypten",
		"nl-NL": "Egypte",
		"nl-BE": "Egypte",
		"sv-SE": "Egypten",
		"sv-FI": "Egypten",
		"da-DK": "Egypten",
		"nb-NO": "Egypt",
		"nn-NO": "Egypt",
		"fi-FI": "Egypti",
		"is-IS": "Egyptaland",
		"fo-FO": "Egyptaland",
		"et-EE": "Egiptus",
		"lv-LV": "Ēģipte",
		"lt-LT": "Egiptas",
		"pl-PL": "Egipt",
		"cs-CZ": "Egypt",
		"sk-SK": "Egypt",
		"sl-SI": "Egipt",
		"hr-HR": "Egipat",
		"bs-BA": "Egipat",
		"sr-RS": "Египат",
		"sr-BA": "Египат",
		"sr-ME": "Egipat",
		"mk-MK": "Египет",
		"bg-BG": "Египет",
		"be-BY": "Егіпет",
		"uk-UA": "Єгипет",
		"ru-RU": "Египет",
		"el-GR": "Αίγυπτος",
		"el-CY": "Αίγυπτος",
		"ro-RO": "Egipt",
		"ro-MD": "Egipt",
		"hu-HU": "Egyiptom",
		"sq-AL": "Egjipt",
		"sq-XK": "Egjipt",
		"mt-MT": "l-Eġittu",
		"ga-IE": "An Éigipt",
		"cy-GB": "Yr Aifft",
		"gd-GB": "An Èipheit",
		"lb-LU": "Egypten",
		"ca-ES": "Egipte",
		"ca-AD": "Egipte",
		"ca-FR": "Egipte",
		"ca-IT": "Egipte",
		"eu-ES": "Egipto",
		"eu-FR": "Egipto",
		"gl-ES": "Exipto",
		"tr-TR": "Mısır",
		"tr-CY": "Mısır"
	},
	"callingCode": "20",
	"phoneMasks": [
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "# ########",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[23]"
			]
		},
		{
			"mask": "## #######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1[35]|[4-6]|8[2468]|9[235-7]"
			]
		},
		{
			"mask": "## ########",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
