import type { Country } from './types.js';

export const FIN = {
	"code": "FIN",
	"labels": {
		"pt-BR": "Finlândia",
		"pt-PT": "Finlândia",
		"qu-PE": "Finlandia",
		"qu-BO": "Finlandia",
		"qu-EC": "Finlandia",
		"chr-US": "ᏫᏂᎦᏙᎯ",
		"hi-IN": "फ़िनलैंड",
		"bn-IN": "ফিনল্যান্ড",
		"bn-BD": "ফিনল্যান্ড",
		"ta-IN": "பின்லாந்து",
		"ta-LK": "பின்லாந்து",
		"ta-SG": "பின்லாந்து",
		"ta-MY": "பின்லாந்து",
		"te-IN": "ఫిన్లాండ్",
		"mr-IN": "फिनलंड",
		"gu-IN": "ફિનલેન્ડ",
		"kn-IN": "ಫಿನ್‌ಲ್ಯಾಂಡ್",
		"ml-IN": "ഫിൻലാൻഡ്",
		"pa-IN": "ਫਿਨਲੈਂਡ",
		"ur-IN": "فن لینڈ",
		"ur-PK": "فن لینڈ",
		"or-IN": "ଫିନଲ୍ୟାଣ୍ଡ",
		"as-IN": "ফিনলেণ্ড",
		"ne-IN": "फिनल्याण्ड",
		"ne-NP": "फिनल्याण्ड",
		"si-LK": "ෆින්ලන්තය",
		"kok-IN": "फिनलँड",
		"ks-IN": "فِن لینڈ",
		"brx-IN": "फिनलेण्ड",
		"mai-IN": "फिनलैंड",
		"dz-BT": "ཕིན་ལེནཌ",
		"ja-JP": "フィンランド",
		"ko-KR": "핀란드",
		"ko-KP": "핀란드",
		"zh-CN": "芬兰",
		"zh-Hans-CN": "芬兰",
		"zh-Hant-TW": "芬蘭",
		"zh-TW": "芬蘭",
		"zh-HK": "芬蘭",
		"zh-MO": "芬蘭",
		"zh-SG": "芬兰",
		"yue-Hant-HK": "芬蘭",
		"yue-Hans-CN": "芬兰",
		"mn-MN": "Финланд",
		"ug-CN": "فىنلاندىيە",
		"th-TH": "ฟินแลนด์",
		"lo-LA": "ຟິນແລນ",
		"km-KH": "ហ្វាំងឡង់",
		"my-MM": "ဖင်လန်",
		"vi-VN": "Phần Lan",
		"id-ID": "Finlandia",
		"ms-MY": "Finland",
		"ms-SG": "Finland",
		"ms-BN": "Finland",
		"jv-ID": "Finlan",
		"fil-PH": "Finland",
		"ceb-PH": "Finland",
		"ka-GE": "ფინეთი",
		"hy-AM": "Ֆինլանդիա",
		"az-AZ": "Finlandiya",
		"az-Cyrl-AZ": "Финландија",
		"kk-KZ": "Финляндия",
		"ky-KG": "Финляндия",
		"uz-UZ": "Finlandiya",
		"tg-TJ": "Финляндия",
		"tk-TM": "Finlýandiýa",
		"fa-IR": "فنلاند",
		"fa-AF": "فنلند",
		"ps-AF": "فنلینډ",
		"ps-PK": "فنلینډ",
		"he-IL": "פינלנד",
		"ar-SA": "فنلندا",
		"ar-AE": "فنلندا",
		"ar-QA": "فنلندا",
		"ar-BH": "فنلندا",
		"ar-KW": "فنلندا",
		"ar-OM": "فنلندا",
		"ar-YE": "فنلندا",
		"ar-IQ": "فنلندا",
		"ar-JO": "فنلندا",
		"ar-LB": "فنلندا",
		"ar-SY": "فنلندا",
		"ar-PS": "فنلندا",
		"en-US": "Finland",
		"en-GB": "Finland",
		"en-IE": "Finland",
		"en-MT": "Finland",
		"en-GI": "Finland",
		"en-CY": "Finland",
		"en-JE": "Finland",
		"en-GG": "Finland",
		"en-IM": "Finland",
		"en-CA": "Finland",
		"en-AU": "Finland",
		"en-NZ": "Finland",
		"en-ZA": "Finland",
		"en-IN": "Finland",
		"en-SG": "Finland",
		"pt-AO": "Finlândia",
		"pt-MZ": "Finlândia",
		"pt-CV": "Finlândia",
		"pt-GW": "Finlândia",
		"pt-ST": "Finlândia",
		"pt-TL": "Finlândia",
		"pt-MO": "Finlândia",
		"es-ES": "Finlandia",
		"es-419": "Finlandia",
		"es-AD": "Finlandia",
		"es-GI": "Finlandia",
		"es-AR": "Finlandia",
		"es-BO": "Finlandia",
		"es-BR": "Finlandia",
		"es-BZ": "Finlandia",
		"es-CL": "Finlandia",
		"es-CO": "Finlandia",
		"es-CR": "Finlandia",
		"es-CU": "Finlandia",
		"es-DO": "Finlandia",
		"es-EC": "Finlandia",
		"es-GT": "Finlandia",
		"es-HN": "Finlandia",
		"es-MX": "Finlandia",
		"es-NI": "Finlandia",
		"es-PA": "Finlandia",
		"es-PE": "Finlandia",
		"es-PR": "Finlandia",
		"es-PY": "Finlandia",
		"es-SV": "Finlandia",
		"es-US": "Finlandia",
		"es-UY": "Finlandia",
		"es-VE": "Finlandia",
		"fr-FR": "Finlande",
		"fr-BE": "Finlande",
		"fr-CH": "Finlande",
		"fr-LU": "Finlande",
		"fr-MC": "Finlande",
		"fr-AD": "Finlande",
		"fr-CA": "Finlande",
		"it-IT": "Finlandia",
		"it-CH": "Finlandia",
		"it-SM": "Finlandia",
		"it-VA": "Finlandia",
		"de-DE": "Finnland",
		"de-AT": "Finnland",
		"de-CH": "Finnland",
		"de-BE": "Finnland",
		"de-LI": "Finnland",
		"de-LU": "Finnland",
		"nl-NL": "Finland",
		"nl-BE": "Finland",
		"sv-SE": "Finland",
		"sv-FI": "Finland",
		"da-DK": "Finland",
		"nb-NO": "Finland",
		"nn-NO": "Finland",
		"fi-FI": "Suomi",
		"is-IS": "Finnland",
		"fo-FO": "Finnland",
		"et-EE": "Soome",
		"lv-LV": "Somija",
		"lt-LT": "Suomija",
		"pl-PL": "Finlandia",
		"cs-CZ": "Finsko",
		"sk-SK": "Fínsko",
		"sl-SI": "Finska",
		"hr-HR": "Finska",
		"bs-BA": "Finska",
		"sr-RS": "Финска",
		"sr-BA": "Финска",
		"sr-ME": "Finska",
		"mk-MK": "Финска",
		"bg-BG": "Финландия",
		"be-BY": "Фінляндыя",
		"uk-UA": "Фінляндія",
		"ru-RU": "Финляндия",
		"el-GR": "Φινλανδία",
		"el-CY": "Φινλανδία",
		"ro-RO": "Finlanda",
		"ro-MD": "Finlanda",
		"hu-HU": "Finnország",
		"sq-AL": "Finlandë",
		"sq-XK": "Finlandë",
		"mt-MT": "il-Finlandja",
		"ga-IE": "an Fhionlainn",
		"cy-GB": "Y Ffindir",
		"gd-GB": "An Fhionnlann",
		"lb-LU": "Finnland",
		"ca-ES": "Finlàndia",
		"ca-AD": "Finlàndia",
		"ca-FR": "Finlàndia",
		"ca-IT": "Finlàndia",
		"eu-ES": "Finlandia",
		"eu-FR": "Finlandia",
		"gl-ES": "Finlandia",
		"tr-TR": "Finlandiya",
		"tr-CY": "Finlandiya"
	},
	"callingCode": "358",
	"phoneMasks": [
		{
			"mask": "#####",
			"minLength": 5,
			"maxLength": 5,
			"leadingDigits": [
				"20[2-59]"
			]
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		},
		{
			"mask": "# #########",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"(?:19|[2568])[1-8]|3(?:0[1-9]|[1-9])|9"
			]
		},
		{
			"mask": "## ########",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[14]|2[09]|50|7[135]"
			]
		},
		{
			"mask": "### #######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"(?:[1-3]0|[68])0|70[07-9]"
			]
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11
		},
		{
			"mask": "## ##########",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"7"
			]
		}
	]
} satisfies Country;
