import type { Country } from './types.js';

export const FLK = {
	"code": "FLK",
	"labels": {
		"pt-BR": "Ilhas Malvinas",
		"pt-PT": "Ilhas Falkland",
		"qu-PE": "Islas Malvinas",
		"qu-BO": "Islas Malvinas",
		"qu-EC": "Islas Malvinas",
		"chr-US": "ᏩᎩ ᏚᎦᏚᏛᎢ",
		"hi-IN": "फ़ॉकलैंड द्वीपसमूह",
		"bn-IN": "ফকল্যান্ড দ্বীপপুঞ্জ",
		"bn-BD": "ফকল্যান্ড দ্বীপপুঞ্জ",
		"ta-IN": "ஃபாக்லாந்து தீவுகள்",
		"ta-LK": "ஃபாக்லாந்து தீவுகள்",
		"ta-SG": "ஃபாக்லாந்து தீவுகள்",
		"ta-MY": "ஃபாக்லாந்து தீவுகள்",
		"te-IN": "ఫాక్‌ల్యాండ్ దీవులు",
		"mr-IN": "फॉकलंड बेटे",
		"gu-IN": "ફૉકલેન્ડ આઇલેન્ડ્સ",
		"kn-IN": "ಫಾಕ್‌ಲ್ಯಾಂಡ್ ದ್ವೀಪಗಳು",
		"ml-IN": "ഫാക്ക്‌ലാന്റ് ദ്വീപുകൾ",
		"pa-IN": "ਫ਼ਾਕਲੈਂਡ ਟਾਪੂ",
		"ur-IN": "جزائر فاکلینڈ",
		"ur-PK": "فاکلینڈ جزائر",
		"or-IN": "ଫକ୍‌ଲ୍ୟାଣ୍ଡ ଦ୍ଵୀପପୁଞ୍ଜ",
		"as-IN": "ফকলেণ্ড দ্বীপপুঞ্জ",
		"ne-IN": "फकल्याण्ड टापुहरु",
		"ne-NP": "फकल्याण्ड टापुहरु",
		"si-LK": "ෆෝක්ලන්ත දූපත්",
		"kok-IN": "फ़ॉकलैंड आइलैंड्स",
		"ks-IN": "فٕلاکلینڑ جٔزیٖرٕ",
		"brx-IN": "फकलेण्ड द्वीपफोर",
		"mai-IN": "फाकलैंड द्वीपसमूह",
		"dz-BT": "ཕལྐ་ལནྜ་གླིང་ཚོམ",
		"ja-JP": "フォークランド諸島",
		"ko-KR": "포클랜드 제도",
		"ko-KP": "포클랜드 제도",
		"zh-CN": "福克兰群岛",
		"zh-Hans-CN": "福克兰群岛",
		"zh-Hant-TW": "福克蘭群島",
		"zh-TW": "福克蘭群島",
		"zh-HK": "福克蘭群島",
		"zh-MO": "福克蘭群島",
		"zh-SG": "福克兰群岛",
		"yue-Hant-HK": "福克蘭群島",
		"yue-Hans-CN": "福克兰群岛",
		"mn-MN": "Фолклендийн арлууд",
		"ug-CN": "فالكلاند ئاراللىرى",
		"th-TH": "หมู่เกาะฟอล์กแลนด์",
		"lo-LA": "ຫມູ່ເກາະຟອກແລນ",
		"km-KH": "កោះ​ហ្វក់ឡែន",
		"my-MM": "ဖော့ကလန် ကျွန်းစု",
		"vi-VN": "Quần đảo Falkland",
		"id-ID": "Kepulauan Falkland",
		"ms-MY": "Kepulauan Falkland",
		"ms-SG": "Kepulauan Falkland",
		"ms-BN": "Kepulauan Falkland",
		"jv-ID": "Kapuloan Falkland",
		"fil-PH": "Falkland Islands",
		"ceb-PH": "Falkland Islands",
		"ka-GE": "ფოლკლენდის კუნძულები",
		"hy-AM": "Ֆոլքլենդյան կղզիներ",
		"az-AZ": "Folklend adaları",
		"az-Cyrl-AZ": "Фолкленд адалары",
		"kk-KZ": "Фолкленд аралдары",
		"ky-KG": "Фолкленд аралдары",
		"uz-UZ": "Folklend orollari",
		"tg-TJ": "Ҷазираҳои Фолкленд",
		"tk-TM": "Folklend adalary",
		"fa-IR": "جزایر فالکلند",
		"fa-AF": "جزایر فالکلند",
		"ps-AF": "فاکلينډ ټاپوګان",
		"ps-PK": "فاکلينډ ټاپوګان",
		"he-IL": "איי פוקלנד",
		"ar-SA": "جزر فوكلاند",
		"ar-AE": "جزر فوكلاند",
		"ar-QA": "جزر فوكلاند",
		"ar-BH": "جزر فوكلاند",
		"ar-KW": "جزر فوكلاند",
		"ar-OM": "جزر فوكلاند",
		"ar-YE": "جزر فوكلاند",
		"ar-IQ": "جزر فوكلاند",
		"ar-JO": "جزر فوكلاند",
		"ar-LB": "جزر فوكلاند",
		"ar-SY": "جزر فوكلاند",
		"ar-PS": "جزر فوكلاند",
		"en-US": "Falkland Islands",
		"en-GB": "Falkland Islands",
		"en-IE": "Falkland Islands",
		"en-MT": "Falkland Islands",
		"en-GI": "Falkland Islands",
		"en-CY": "Falkland Islands",
		"en-JE": "Falkland Islands",
		"en-GG": "Falkland Islands",
		"en-IM": "Falkland Islands",
		"en-CA": "Falkland Islands",
		"en-AU": "Falkland Islands",
		"en-NZ": "Falkland Islands",
		"en-ZA": "Falkland Islands",
		"en-IN": "Falkland Islands",
		"en-SG": "Falkland Islands",
		"pt-AO": "Ilhas Falkland",
		"pt-MZ": "Ilhas Falkland",
		"pt-CV": "Ilhas Falkland",
		"pt-GW": "Ilhas Falkland",
		"pt-ST": "Ilhas Falkland",
		"pt-TL": "Ilhas Falkland",
		"pt-MO": "Ilhas Falkland",
		"es-ES": "Islas Malvinas",
		"es-419": "Islas Malvinas",
		"es-AD": "Islas Malvinas",
		"es-GI": "Islas Malvinas",
		"es-AR": "Islas Malvinas",
		"es-BO": "Islas Malvinas",
		"es-BR": "Islas Malvinas",
		"es-BZ": "Islas Malvinas",
		"es-CL": "Islas Malvinas",
		"es-CO": "Islas Malvinas",
		"es-CR": "Islas Malvinas",
		"es-CU": "Islas Malvinas",
		"es-DO": "Islas Malvinas",
		"es-EC": "Islas Malvinas",
		"es-GT": "Islas Malvinas",
		"es-HN": "Islas Malvinas",
		"es-MX": "Islas Malvinas",
		"es-NI": "Islas Malvinas",
		"es-PA": "Islas Malvinas",
		"es-PE": "Islas Malvinas",
		"es-PR": "Islas Malvinas",
		"es-PY": "Islas Malvinas",
		"es-SV": "Islas Malvinas",
		"es-US": "Islas Malvinas",
		"es-UY": "Islas Malvinas",
		"es-VE": "Islas Malvinas",
		"fr-FR": "Îles Malouines",
		"fr-BE": "Îles Malouines",
		"fr-CH": "Îles Malouines",
		"fr-LU": "Îles Malouines",
		"fr-MC": "Îles Malouines",
		"fr-AD": "Îles Malouines",
		"fr-CA": "îles Malouines",
		"it-IT": "Isole Falkland",
		"it-CH": "Isole Falkland",
		"it-SM": "Isole Falkland",
		"it-VA": "Isole Falkland",
		"de-DE": "Falklandinseln",
		"de-AT": "Falklandinseln",
		"de-CH": "Falklandinseln",
		"de-BE": "Falklandinseln",
		"de-LI": "Falklandinseln",
		"de-LU": "Falklandinseln",
		"nl-NL": "Falklandeilanden",
		"nl-BE": "Falklandeilanden",
		"sv-SE": "Falklandsöarna",
		"sv-FI": "Falklandsöarna",
		"da-DK": "Falklandsøerne",
		"nb-NO": "Falklandsøyene",
		"nn-NO": "Falklandsøyane",
		"fi-FI": "Falklandinsaaret",
		"is-IS": "Falklandseyjar",
		"fo-FO": "Falklandsoyggjar",
		"et-EE": "Falklandi saared",
		"lv-LV": "Folklenda salas",
		"lt-LT": "Folklando Salos",
		"pl-PL": "Falklandy",
		"cs-CZ": "Falklandské ostrovy",
		"sk-SK": "Falklandy",
		"sl-SI": "Falklandski otoki",
		"hr-HR": "Falklandski Otoci",
		"bs-BA": "Folklandska ostrva",
		"sr-RS": "Фокландска Острва",
		"sr-BA": "Фокландска острва",
		"sr-ME": "Foklandska Ostrva",
		"mk-MK": "Фолкландски Острови",
		"bg-BG": "Фолкландски острови",
		"be-BY": "Фалклендскія астравы",
		"uk-UA": "Фолклендські Острови",
		"ru-RU": "Фолклендские о-ва",
		"el-GR": "Νήσοι Φόκλαντ",
		"el-CY": "Νήσοι Φόκλαντ",
		"ro-RO": "Insulele Falkland",
		"ro-MD": "Insulele Falkland",
		"hu-HU": "Falkland-szigetek",
		"sq-AL": "Ishujt Falkland",
		"sq-XK": "Ishujt Falkland",
		"mt-MT": "il-Gżejjer Falkland",
		"ga-IE": "Oileáin Fháclainne",
		"cy-GB": "Ynysoedd y Falkland/Malvinas",
		"gd-GB": "Na h-Eileanan Fàclannach",
		"lb-LU": "Falklandinselen",
		"ca-ES": "Illes Falkland",
		"ca-AD": "Illes Falkland",
		"ca-FR": "Illes Falkland",
		"ca-IT": "Illes Falkland",
		"eu-ES": "Falklandak",
		"eu-FR": "Falklandak",
		"gl-ES": "Illas Malvinas",
		"tr-TR": "Falkland Adaları",
		"tr-CY": "Falkland Adaları"
	},
	"callingCode": "500",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		}
	]
} satisfies Country;
