import type { Country } from './types.js';

export const FRO = {
	"code": "FRO",
	"labels": {
		"pt-BR": "Ilhas Faroé",
		"pt-PT": "Ilhas Faroé",
		"qu-PE": "Islas Feroe",
		"qu-BO": "Islas Feroe",
		"qu-EC": "Islas Feroe",
		"chr-US": "ᏪᎶ ᏚᎦᏚᏛᎢ",
		"hi-IN": "फ़ेरो द्वीपसमूह",
		"bn-IN": "ফ্যারো দ্বীপপুঞ্জ",
		"bn-BD": "ফ্যারো দ্বীপপুঞ্জ",
		"ta-IN": "ஃபாரோ தீவுகள்",
		"ta-LK": "ஃபாரோ தீவுகள்",
		"ta-SG": "ஃபாரோ தீவுகள்",
		"ta-MY": "ஃபாரோ தீவுகள்",
		"te-IN": "ఫారో దీవులు",
		"mr-IN": "फेरो बेटे",
		"gu-IN": "ફેરો આઇલેન્ડ્સ",
		"kn-IN": "ಫರೋ ದ್ವೀಪಗಳು",
		"ml-IN": "ഫറോ ദ്വീപുകൾ",
		"pa-IN": "ਫੈਰੋ ਟਾਪੂ",
		"ur-IN": "جزائر فیرو",
		"ur-PK": "جزائر فارو",
		"or-IN": "ଫାରୋଇ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "ফাৰো দ্বীপপুঞ্জ",
		"ne-IN": "फारो टापुहरू",
		"ne-NP": "फारो टापुहरू",
		"si-LK": "ෆැරෝ දූපත්",
		"kok-IN": "फैरो आयलँड्स",
		"ks-IN": "فارو جزیرہ",
		"brx-IN": "फेर’ द्वीपफोर",
		"mai-IN": "फेरो द्वीपसमूह",
		"dz-BT": "ཕཱའེ་རོ་གླིང་ཚོམ",
		"ja-JP": "フェロー諸島",
		"ko-KR": "페로 제도",
		"ko-KP": "페로 제도",
		"zh-CN": "法罗群岛",
		"zh-Hans-CN": "法罗群岛",
		"zh-Hant-TW": "法羅群島",
		"zh-TW": "法羅群島",
		"zh-HK": "法羅群島",
		"zh-MO": "法羅群島",
		"zh-SG": "法罗群岛",
		"yue-Hant-HK": "法羅群島",
		"yue-Hans-CN": "法罗群岛",
		"mn-MN": "Фарерын арлууд",
		"ug-CN": "فارو ئاراللىرى",
		"th-TH": "หมู่เกาะแฟโร",
		"lo-LA": "ຫມູ່ເກາະແຟໂຣ",
		"km-KH": "កោះ​ហ្វារ៉ូ",
		"my-MM": "ဖာရိုး ကျွန်းစုများ",
		"vi-VN": "Quần đảo Faroe",
		"id-ID": "Kepulauan Faroe",
		"ms-MY": "Kepulauan Faroe",
		"ms-SG": "Kepulauan Faroe",
		"ms-BN": "Kepulauan Faroe",
		"jv-ID": "Kapuloan Faro",
		"fil-PH": "Faroe Islands",
		"ceb-PH": "Faroe Islands",
		"ka-GE": "ფარერის კუნძულები",
		"hy-AM": "Ֆարերյան կղզիներ",
		"az-AZ": "Farer adaları",
		"az-Cyrl-AZ": "Фарер адалары",
		"kk-KZ": "Фарер аралдары",
		"ky-KG": "Фарер аралдары",
		"uz-UZ": "Farer orollari",
		"tg-TJ": "Ҷазираҳои Фарер",
		"tk-TM": "Farer adalary",
		"fa-IR": "جزایر فارو",
		"fa-AF": "جزایر فارو",
		"ps-AF": "فارو ټاپو",
		"ps-PK": "فارو ټاپو",
		"he-IL": "איי פארו",
		"ar-SA": "جزر فارو",
		"ar-AE": "جزر فارو",
		"ar-QA": "جزر فارو",
		"ar-BH": "جزر فارو",
		"ar-KW": "جزر فارو",
		"ar-OM": "جزر فارو",
		"ar-YE": "جزر فارو",
		"ar-IQ": "جزر فارو",
		"ar-JO": "جزر فارو",
		"ar-LB": "جزر فارو",
		"ar-SY": "جزر فارو",
		"ar-PS": "جزر فارو",
		"en-US": "Faroe Islands",
		"en-GB": "Faroe Islands",
		"en-IE": "Faroe Islands",
		"en-MT": "Faroe Islands",
		"en-GI": "Faroe Islands",
		"en-CY": "Faroe Islands",
		"en-JE": "Faroe Islands",
		"en-GG": "Faroe Islands",
		"en-IM": "Faroe Islands",
		"en-CA": "Faroe Islands",
		"en-AU": "Faroe Islands",
		"en-NZ": "Faroe Islands",
		"en-ZA": "Faroe Islands",
		"en-IN": "Faroe Islands",
		"en-SG": "Faroe Islands",
		"pt-AO": "Ilhas Faroé",
		"pt-MZ": "Ilhas Faroé",
		"pt-CV": "Ilhas Faroé",
		"pt-GW": "Ilhas Faroé",
		"pt-ST": "Ilhas Faroé",
		"pt-TL": "Ilhas Faroé",
		"pt-MO": "Ilhas Faroé",
		"es-ES": "Islas Feroe",
		"es-419": "Islas Feroe",
		"es-AD": "Islas Feroe",
		"es-GI": "Islas Feroe",
		"es-AR": "Islas Feroe",
		"es-BO": "Islas Feroe",
		"es-BR": "Islas Feroe",
		"es-BZ": "Islas Feroe",
		"es-CL": "Islas Feroe",
		"es-CO": "Islas Feroe",
		"es-CR": "Islas Feroe",
		"es-CU": "Islas Feroe",
		"es-DO": "Islas Feroe",
		"es-EC": "Islas Feroe",
		"es-GT": "Islas Feroe",
		"es-HN": "Islas Feroe",
		"es-MX": "Islas Feroe",
		"es-NI": "Islas Feroe",
		"es-PA": "Islas Feroe",
		"es-PE": "Islas Feroe",
		"es-PR": "Islas Feroe",
		"es-PY": "Islas Feroe",
		"es-SV": "Islas Feroe",
		"es-US": "Islas Feroe",
		"es-UY": "Islas Feroe",
		"es-VE": "Islas Feroe",
		"fr-FR": "Îles Féroé",
		"fr-BE": "Îles Féroé",
		"fr-CH": "Îles Féroé",
		"fr-LU": "Îles Féroé",
		"fr-MC": "Îles Féroé",
		"fr-AD": "Îles Féroé",
		"fr-CA": "îles Féroé",
		"it-IT": "Isole Fær Øer",
		"it-CH": "Isole Fær Øer",
		"it-SM": "Isole Fær Øer",
		"it-VA": "Isole Fær Øer",
		"de-DE": "Färöer",
		"de-AT": "Färöer",
		"de-CH": "Färöer",
		"de-BE": "Färöer",
		"de-LI": "Färöer",
		"de-LU": "Färöer",
		"nl-NL": "Faeröer",
		"nl-BE": "Faeröer",
		"sv-SE": "Färöarna",
		"sv-FI": "Färöarna",
		"da-DK": "Færøerne",
		"nb-NO": "Færøyene",
		"nn-NO": "Færøyane",
		"fi-FI": "Färsaaret",
		"is-IS": "Færeyjar",
		"fo-FO": "Føroyar",
		"et-EE": "Fääri saared",
		"lv-LV": "Fēru salas",
		"lt-LT": "Farerų Salos",
		"pl-PL": "Wyspy Owcze",
		"cs-CZ": "Faerské ostrovy",
		"sk-SK": "Faerské ostrovy",
		"sl-SI": "Ferski otoki",
		"hr-HR": "Ovčji Otoci",
		"bs-BA": "Farska ostrva",
		"sr-RS": "Фарска Острва",
		"sr-BA": "Фарска острва",
		"sr-ME": "Farska Ostrva",
		"mk-MK": "Фарски Острови",
		"bg-BG": "Фарьорски острови",
		"be-BY": "Фарэрскія астравы",
		"uk-UA": "Фарерські Острови",
		"ru-RU": "Фарерские о-ва",
		"el-GR": "Νήσοι Φερόες",
		"el-CY": "Νήσοι Φερόες",
		"ro-RO": "Insulele Feroe",
		"ro-MD": "Insulele Feroe",
		"hu-HU": "Feröer szigetek",
		"sq-AL": "Ishujt Faroe",
		"sq-XK": "Ishujt Faroe",
		"mt-MT": "il-Gżejjer Faeroe",
		"ga-IE": "Oileáin Fharó",
		"cy-GB": "Ynysoedd Ffaro",
		"gd-GB": "Na h-Eileanan Fàro",
		"lb-LU": "Färöer",
		"ca-ES": "Illes Fèroe",
		"ca-AD": "Illes Fèroe",
		"ca-FR": "Illes Fèroe",
		"ca-IT": "Illes Fèroe",
		"eu-ES": "Faroe uharteak",
		"eu-FR": "Faroe uharteak",
		"gl-ES": "Illas Feroe",
		"tr-TR": "Faroe Adaları",
		"tr-CY": "Faroe Adaları"
	},
	"callingCode": "298",
	"phoneMasks": [
		{
			"mask": "######",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
