import type { Country } from './types.js';

export const GEO = {
	"code": "GEO",
	"labels": {
		"pt-BR": "Geórgia",
		"pt-PT": "Geórgia",
		"qu-PE": "Georgia",
		"qu-BO": "Georgia",
		"qu-EC": "Georgia",
		"chr-US": "ᏣᎠᏥᎢ",
		"hi-IN": "जॉर्जिया",
		"bn-IN": "জর্জিয়া",
		"bn-BD": "জর্জিয়া",
		"ta-IN": "ஜார்ஜியா",
		"ta-LK": "ஜார்ஜியா",
		"ta-SG": "ஜார்ஜியா",
		"ta-MY": "ஜார்ஜியா",
		"te-IN": "జార్జియా",
		"mr-IN": "जॉर्जिया",
		"gu-IN": "જ્યોર્જિયા",
		"kn-IN": "ಜಾರ್ಜಿಯಾ",
		"ml-IN": "ജോർജ്ജിയ",
		"pa-IN": "ਜਾਰਜੀਆ",
		"ur-IN": "جارجیا",
		"ur-PK": "جارجیا",
		"or-IN": "ଜର୍ଜିଆ",
		"as-IN": "জৰ্জিয়া",
		"ne-IN": "जर्जिया",
		"ne-NP": "जर्जिया",
		"si-LK": "ජෝර්ජියාව",
		"kok-IN": "जॉर्जिया",
		"ks-IN": "جارجِیا",
		"brx-IN": "जर्जिया",
		"mai-IN": "जार्जिया",
		"dz-BT": "ཇཽར་ཇཱ",
		"ja-JP": "ジョージア",
		"ko-KR": "조지아",
		"ko-KP": "조지아",
		"zh-CN": "格鲁吉亚",
		"zh-Hans-CN": "格鲁吉亚",
		"zh-Hant-TW": "喬治亞",
		"zh-TW": "喬治亞",
		"zh-HK": "格魯吉亞",
		"zh-MO": "格魯吉亞",
		"zh-SG": "格鲁吉亚",
		"yue-Hant-HK": "格魯吉亞",
		"yue-Hans-CN": "乔治亚共和国",
		"mn-MN": "Гүрж",
		"ug-CN": "گىرۇزىيە",
		"th-TH": "จอร์เจีย",
		"lo-LA": "ຈໍເຈຍ",
		"km-KH": "ហ្សកហ្ស៊ី",
		"my-MM": "ဂျော်ဂျီယာ",
		"vi-VN": "Georgia",
		"id-ID": "Georgia",
		"ms-MY": "Georgia",
		"ms-SG": "Georgia",
		"ms-BN": "Georgia",
		"jv-ID": "Géorgia",
		"fil-PH": "Georgia",
		"ceb-PH": "Georgia",
		"ka-GE": "საქართველო",
		"hy-AM": "Վրաստան",
		"az-AZ": "Gürcüstan",
		"az-Cyrl-AZ": "Ҝүрҹүстан",
		"kk-KZ": "Грузия",
		"ky-KG": "Грузия",
		"uz-UZ": "Gruziya",
		"tg-TJ": "Гурҷистон",
		"tk-TM": "Gruziýa",
		"fa-IR": "گرجستان",
		"fa-AF": "گرجستان",
		"ps-AF": "گورجستان",
		"ps-PK": "گورجستان",
		"he-IL": "גאורגיה",
		"ar-SA": "جورجيا",
		"ar-AE": "جورجيا",
		"ar-QA": "جورجيا",
		"ar-BH": "جورجيا",
		"ar-KW": "جورجيا",
		"ar-OM": "جورجيا",
		"ar-YE": "جورجيا",
		"ar-IQ": "جورجيا",
		"ar-JO": "جورجيا",
		"ar-LB": "جورجيا",
		"ar-SY": "جورجيا",
		"ar-PS": "جورجيا",
		"en-US": "Georgia",
		"en-GB": "Georgia",
		"en-IE": "Georgia",
		"en-MT": "Georgia",
		"en-GI": "Georgia",
		"en-CY": "Georgia",
		"en-JE": "Georgia",
		"en-GG": "Georgia",
		"en-IM": "Georgia",
		"en-CA": "Georgia",
		"en-AU": "Georgia",
		"en-NZ": "Georgia",
		"en-ZA": "Georgia",
		"en-IN": "Georgia",
		"en-SG": "Georgia",
		"pt-AO": "Geórgia",
		"pt-MZ": "Geórgia",
		"pt-CV": "Geórgia",
		"pt-GW": "Geórgia",
		"pt-ST": "Geórgia",
		"pt-TL": "Geórgia",
		"pt-MO": "Geórgia",
		"es-ES": "Georgia",
		"es-419": "Georgia",
		"es-AD": "Georgia",
		"es-GI": "Georgia",
		"es-AR": "Georgia",
		"es-BO": "Georgia",
		"es-BR": "Georgia",
		"es-BZ": "Georgia",
		"es-CL": "Georgia",
		"es-CO": "Georgia",
		"es-CR": "Georgia",
		"es-CU": "Georgia",
		"es-DO": "Georgia",
		"es-EC": "Georgia",
		"es-GT": "Georgia",
		"es-HN": "Georgia",
		"es-MX": "Georgia",
		"es-NI": "Georgia",
		"es-PA": "Georgia",
		"es-PE": "Georgia",
		"es-PR": "Georgia",
		"es-PY": "Georgia",
		"es-SV": "Georgia",
		"es-US": "Georgia",
		"es-UY": "Georgia",
		"es-VE": "Georgia",
		"fr-FR": "Géorgie",
		"fr-BE": "Géorgie",
		"fr-CH": "Géorgie",
		"fr-LU": "Géorgie",
		"fr-MC": "Géorgie",
		"fr-AD": "Géorgie",
		"fr-CA": "Géorgie",
		"it-IT": "Georgia",
		"it-CH": "Georgia",
		"it-SM": "Georgia",
		"it-VA": "Georgia",
		"de-DE": "Georgien",
		"de-AT": "Georgien",
		"de-CH": "Georgien",
		"de-BE": "Georgien",
		"de-LI": "Georgien",
		"de-LU": "Georgien",
		"nl-NL": "Georgië",
		"nl-BE": "Georgië",
		"sv-SE": "Georgien",
		"sv-FI": "Georgien",
		"da-DK": "Georgien",
		"nb-NO": "Georgia",
		"nn-NO": "Georgia",
		"fi-FI": "Georgia",
		"is-IS": "Georgía",
		"fo-FO": "Georgia",
		"et-EE": "Gruusia",
		"lv-LV": "Gruzija",
		"lt-LT": "Gruzija",
		"pl-PL": "Gruzja",
		"cs-CZ": "Gruzie",
		"sk-SK": "Gruzínsko",
		"sl-SI": "Gruzija",
		"hr-HR": "Gruzija",
		"bs-BA": "Gruzija",
		"sr-RS": "Грузија",
		"sr-BA": "Грузија",
		"sr-ME": "Gruzija",
		"mk-MK": "Грузија",
		"bg-BG": "Грузия",
		"be-BY": "Грузія",
		"uk-UA": "Грузія",
		"ru-RU": "Грузия",
		"el-GR": "Γεωργία",
		"el-CY": "Γεωργία",
		"ro-RO": "Georgia",
		"ro-MD": "Georgia",
		"hu-HU": "Grúzia",
		"sq-AL": "Gjeorgji",
		"sq-XK": "Gjeorgji",
		"mt-MT": "il-Georgia",
		"ga-IE": "an tSeoirsia",
		"cy-GB": "Georgia",
		"gd-GB": "A’ Chairtbheil",
		"lb-LU": "Georgien",
		"ca-ES": "Geòrgia",
		"ca-AD": "Geòrgia",
		"ca-FR": "Geòrgia",
		"ca-IT": "Geòrgia",
		"eu-ES": "Georgia",
		"eu-FR": "Georgia",
		"gl-ES": "Xeorxia",
		"tr-TR": "Gürcistan",
		"tr-CY": "Gürcistan"
	},
	"callingCode": "995",
	"phoneMasks": [
		{
			"mask": "## ### ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"32"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[57]"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[348]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"70"
			]
		}
	]
} satisfies Country;
