import type { Country } from './types.js';

export const GNQ = {
	"code": "GNQ",
	"labels": {
		"pt-BR": "Guiné Equatorial",
		"pt-PT": "Guiné Equatorial",
		"qu-PE": "Guinea Ecuatorial",
		"qu-BO": "Guinea Ecuatorial",
		"qu-EC": "Guinea Ecuatorial",
		"chr-US": "ᎡᏆᏙᎵᎠᎵ ᎩᎢᏂ",
		"hi-IN": "इक्वेटोरियल गिनी",
		"bn-IN": "নিরক্ষীয় গিনি",
		"bn-BD": "নিরক্ষীয় গিনি",
		"ta-IN": "ஈக்வடோரியல் கினியா",
		"ta-LK": "ஈக்வடோரியல் கினியா",
		"ta-SG": "ஈக்வடோரியல் கினியா",
		"ta-MY": "ஈக்வடோரியல் கினியா",
		"te-IN": "ఈక్వటోరియల్ గినియా",
		"mr-IN": "इक्वेटोरियल गिनी",
		"gu-IN": "ઇક્વેટોરિયલ ગિની",
		"kn-IN": "ಈಕ್ವೆಟೋರಿಯಲ್ ಗಿನಿ",
		"ml-IN": "ഇക്വറ്റോറിയൽ ഗിനിയ",
		"pa-IN": "ਭੂ-ਖੰਡੀ ਗਿਨੀ",
		"ur-IN": "استوائی گیانا",
		"ur-PK": "استوائی گیانا",
		"or-IN": "ଇକ୍ବାଟୋରିଆଲ୍ ଗୁଇନିଆ",
		"as-IN": "ইকুৱেটৰিয়েল গিনি",
		"ne-IN": "भू-मध्यीय गिनी",
		"ne-NP": "भू-मध्यीय गिनी",
		"si-LK": "සමක ගිනියාව",
		"kok-IN": "इक्वेटोरियल गुएनिया",
		"ks-IN": "اِکوِٹورِیَل گِنی",
		"brx-IN": "बिसुबारि गिनीया",
		"mai-IN": "इक्वेटोरियल गिनी",
		"dz-BT": "ཨེ་ཀུ་ཊོ་རེལ་ གི་ནི",
		"ja-JP": "赤道ギニア",
		"ko-KR": "적도 기니",
		"ko-KP": "적도 기니",
		"zh-CN": "赤道几内亚",
		"zh-Hans-CN": "赤道几内亚",
		"zh-Hant-TW": "赤道幾內亞",
		"zh-TW": "赤道幾內亞",
		"zh-HK": "赤道幾內亞",
		"zh-MO": "赤道幾內亞",
		"zh-SG": "赤道几内亚",
		"yue-Hant-HK": "赤道幾內亞",
		"yue-Hans-CN": "赤道几内亚",
		"mn-MN": "Экваторын Гвиней",
		"ug-CN": "ئېكۋاتور گىۋىنىيەسى",
		"th-TH": "อิเควทอเรียลกินี",
		"lo-LA": "ເອຄົວໂທຣຽວ ກີນີ",
		"km-KH": "ហ្គីណេអេក្វាទ័រ",
		"my-MM": "အီကွေတာ ဂီနီ",
		"vi-VN": "Guinea Xích Đạo",
		"id-ID": "Guinea Ekuatorial",
		"ms-MY": "Guinea Khatulistiwa",
		"ms-SG": "Guinea Khatulistiwa",
		"ms-BN": "Guinea Khatulistiwa",
		"jv-ID": "Guinéa Katulistiwa",
		"fil-PH": "Equatorial Guinea",
		"ceb-PH": "Equatorial Guinea",
		"ka-GE": "ეკვატორული გვინეა",
		"hy-AM": "Հասարակածային Գվինեա",
		"az-AZ": "Ekvatorial Qvineya",
		"az-Cyrl-AZ": "Екваториал Гвинеја",
		"kk-KZ": "Экваторлық Гвинея",
		"ky-KG": "Экватордук Гвинея",
		"uz-UZ": "Ekvatorial Gvineya",
		"tg-TJ": "Гвинеяи Экваторӣ",
		"tk-TM": "Ekwatorial Gwineýa",
		"fa-IR": "گینهٔ استوایی",
		"fa-AF": "گینیا استوایی",
		"ps-AF": "استوایی ګیني",
		"ps-PK": "استوایی ګیني",
		"he-IL": "גינאה המשוונית",
		"ar-SA": "غينيا الاستوائية",
		"ar-AE": "غينيا الاستوائية",
		"ar-QA": "غينيا الاستوائية",
		"ar-BH": "غينيا الاستوائية",
		"ar-KW": "غينيا الاستوائية",
		"ar-OM": "غينيا الاستوائية",
		"ar-YE": "غينيا الاستوائية",
		"ar-IQ": "غينيا الاستوائية",
		"ar-JO": "غينيا الاستوائية",
		"ar-LB": "غينيا الاستوائية",
		"ar-SY": "غينيا الاستوائية",
		"ar-PS": "غينيا الاستوائية",
		"en-US": "Equatorial Guinea",
		"en-GB": "Equatorial Guinea",
		"en-IE": "Equatorial Guinea",
		"en-MT": "Equatorial Guinea",
		"en-GI": "Equatorial Guinea",
		"en-CY": "Equatorial Guinea",
		"en-JE": "Equatorial Guinea",
		"en-GG": "Equatorial Guinea",
		"en-IM": "Equatorial Guinea",
		"en-CA": "Equatorial Guinea",
		"en-AU": "Equatorial Guinea",
		"en-NZ": "Equatorial Guinea",
		"en-ZA": "Equatorial Guinea",
		"en-IN": "Equatorial Guinea",
		"en-SG": "Equatorial Guinea",
		"pt-AO": "Guiné Equatorial",
		"pt-MZ": "Guiné Equatorial",
		"pt-CV": "Guiné Equatorial",
		"pt-GW": "Guiné Equatorial",
		"pt-ST": "Guiné Equatorial",
		"pt-TL": "Guiné Equatorial",
		"pt-MO": "Guiné Equatorial",
		"es-ES": "Guinea Ecuatorial",
		"es-419": "Guinea Ecuatorial",
		"es-AD": "Guinea Ecuatorial",
		"es-GI": "Guinea Ecuatorial",
		"es-AR": "Guinea Ecuatorial",
		"es-BO": "Guinea Ecuatorial",
		"es-BR": "Guinea Ecuatorial",
		"es-BZ": "Guinea Ecuatorial",
		"es-CL": "Guinea Ecuatorial",
		"es-CO": "Guinea Ecuatorial",
		"es-CR": "Guinea Ecuatorial",
		"es-CU": "Guinea Ecuatorial",
		"es-DO": "Guinea Ecuatorial",
		"es-EC": "Guinea Ecuatorial",
		"es-GT": "Guinea Ecuatorial",
		"es-HN": "Guinea Ecuatorial",
		"es-MX": "Guinea Ecuatorial",
		"es-NI": "Guinea Ecuatorial",
		"es-PA": "Guinea Ecuatorial",
		"es-PE": "Guinea Ecuatorial",
		"es-PR": "Guinea Ecuatorial",
		"es-PY": "Guinea Ecuatorial",
		"es-SV": "Guinea Ecuatorial",
		"es-US": "Guinea Ecuatorial",
		"es-UY": "Guinea Ecuatorial",
		"es-VE": "Guinea Ecuatorial",
		"fr-FR": "Guinée équatoriale",
		"fr-BE": "Guinée équatoriale",
		"fr-CH": "Guinée équatoriale",
		"fr-LU": "Guinée équatoriale",
		"fr-MC": "Guinée équatoriale",
		"fr-AD": "Guinée équatoriale",
		"fr-CA": "Guinée équatoriale",
		"it-IT": "Guinea Equatoriale",
		"it-CH": "Guinea Equatoriale",
		"it-SM": "Guinea Equatoriale",
		"it-VA": "Guinea Equatoriale",
		"de-DE": "Äquatorialguinea",
		"de-AT": "Äquatorialguinea",
		"de-CH": "Äquatorialguinea",
		"de-BE": "Äquatorialguinea",
		"de-LI": "Äquatorialguinea",
		"de-LU": "Äquatorialguinea",
		"nl-NL": "Equatoriaal-Guinea",
		"nl-BE": "Equatoriaal-Guinea",
		"sv-SE": "Ekvatorialguinea",
		"sv-FI": "Ekvatorialguinea",
		"da-DK": "Ækvatorialguinea",
		"nb-NO": "Ekvatorial-Guinea",
		"nn-NO": "Ekvatorial-Guinea",
		"fi-FI": "Päiväntasaajan Guinea",
		"is-IS": "Miðbaugs-Gínea",
		"fo-FO": "Ekvatorguinea",
		"et-EE": "Ekvatoriaal-Guinea",
		"lv-LV": "Ekvatoriālā Gvineja",
		"lt-LT": "Pusiaujo Gvinėja",
		"pl-PL": "Gwinea Równikowa",
		"cs-CZ": "Rovníková Guinea",
		"sk-SK": "Rovníková Guinea",
		"sl-SI": "Ekvatorialna Gvineja",
		"hr-HR": "Ekvatorska Gvineja",
		"bs-BA": "Ekvatorijalna Gvineja",
		"sr-RS": "Екваторијална Гвинеја",
		"sr-BA": "Екваторијална Гвинеја",
		"sr-ME": "Ekvatorijalna Gvineja",
		"mk-MK": "Екваторска Гвинеја",
		"bg-BG": "Екваториална Гвинея",
		"be-BY": "Экватарыяльная Гвінея",
		"uk-UA": "Екваторіальна Гвінея",
		"ru-RU": "Экваториальная Гвинея",
		"el-GR": "Ισημερινή Γουινέα",
		"el-CY": "Ισημερινή Γουινέα",
		"ro-RO": "Guineea Ecuatorială",
		"ro-MD": "Guineea Ecuatorială",
		"hu-HU": "Egyenlítői-Guinea",
		"sq-AL": "Guineja Ekuatoriale",
		"sq-XK": "Guineja Ekuatoriale",
		"mt-MT": "il-Guinea Ekwatorjali",
		"ga-IE": "an Ghuine Mheánchiorclach",
		"cy-GB": "Gini Gyhydeddol",
		"gd-GB": "Gini Mheadhan-Chriosach",
		"lb-LU": "Equatorialguinea",
		"ca-ES": "Guinea Equatorial",
		"ca-AD": "Guinea Equatorial",
		"ca-FR": "Guinea Equatorial",
		"ca-IT": "Guinea Equatorial",
		"eu-ES": "Ekuatore Ginea",
		"eu-FR": "Ekuatore Ginea",
		"gl-ES": "Guinea Ecuatorial",
		"tr-TR": "Ekvator Ginesi",
		"tr-CY": "Ekvator Ginesi"
	},
	"callingCode": "240",
	"phoneMasks": [
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[235]"
			]
		},
		{
			"mask": "### ######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
