import type { Country } from './types.js';

export const GRC = {
	"code": "GRC",
	"labels": {
		"pt-BR": "Grécia",
		"pt-PT": "Grécia",
		"qu-PE": "Grecia",
		"qu-BO": "Grecia",
		"qu-EC": "Grecia",
		"chr-US": "ᎪᎢᎯ",
		"hi-IN": "यूनान",
		"bn-IN": "গ্রীস",
		"bn-BD": "গ্রীস",
		"ta-IN": "கிரீஸ்",
		"ta-LK": "கிரீஸ்",
		"ta-SG": "கிரீஸ்",
		"ta-MY": "கிரீஸ்",
		"te-IN": "గ్రీస్",
		"mr-IN": "ग्रीस",
		"gu-IN": "ગ્રીસ",
		"kn-IN": "ಗ್ರೀಸ್",
		"ml-IN": "ഗ്രീസ്",
		"pa-IN": "ਗ੍ਰੀਸ",
		"ur-IN": "یونان",
		"ur-PK": "یونان",
		"or-IN": "ଗ୍ରୀସ୍",
		"as-IN": "গ্ৰীচ",
		"ne-IN": "ग्रीस",
		"ne-NP": "ग्रीस",
		"si-LK": "ග්‍රීසිය",
		"kok-IN": "ग्रीस",
		"ks-IN": "گریٖس",
		"brx-IN": "ग्रीस",
		"mai-IN": "यूनान",
		"dz-BT": "གིརིས྄",
		"ja-JP": "ギリシャ",
		"ko-KR": "그리스",
		"ko-KP": "그리스",
		"zh-CN": "希腊",
		"zh-Hans-CN": "希腊",
		"zh-Hant-TW": "希臘",
		"zh-TW": "希臘",
		"zh-HK": "希臘",
		"zh-MO": "希臘",
		"zh-SG": "希腊",
		"yue-Hant-HK": "希臘",
		"yue-Hans-CN": "希腊",
		"mn-MN": "Грек",
		"ug-CN": "گىرېتسىيە",
		"th-TH": "กรีซ",
		"lo-LA": "ກຣີຊ",
		"km-KH": "ក្រិក",
		"my-MM": "ဂရိ",
		"vi-VN": "Hy Lạp",
		"id-ID": "Yunani",
		"ms-MY": "Greece",
		"ms-SG": "Greece",
		"ms-BN": "Greece",
		"jv-ID": "Grikenlan",
		"fil-PH": "Greece",
		"ceb-PH": "Greece",
		"ka-GE": "საბერძნეთი",
		"hy-AM": "Հունաստան",
		"az-AZ": "Yunanıstan",
		"az-Cyrl-AZ": "Јунаныстан",
		"kk-KZ": "Грекия",
		"ky-KG": "Греция",
		"uz-UZ": "Gretsiya",
		"tg-TJ": "Юнон",
		"tk-TM": "Gresiýa",
		"fa-IR": "یونان",
		"fa-AF": "یونان",
		"ps-AF": "یونان",
		"ps-PK": "یونان",
		"he-IL": "יוון",
		"ar-SA": "اليونان",
		"ar-AE": "اليونان",
		"ar-QA": "اليونان",
		"ar-BH": "اليونان",
		"ar-KW": "اليونان",
		"ar-OM": "اليونان",
		"ar-YE": "اليونان",
		"ar-IQ": "اليونان",
		"ar-JO": "اليونان",
		"ar-LB": "اليونان",
		"ar-SY": "اليونان",
		"ar-PS": "اليونان",
		"en-US": "Greece",
		"en-GB": "Greece",
		"en-IE": "Greece",
		"en-MT": "Greece",
		"en-GI": "Greece",
		"en-CY": "Greece",
		"en-JE": "Greece",
		"en-GG": "Greece",
		"en-IM": "Greece",
		"en-CA": "Greece",
		"en-AU": "Greece",
		"en-NZ": "Greece",
		"en-ZA": "Greece",
		"en-IN": "Greece",
		"en-SG": "Greece",
		"pt-AO": "Grécia",
		"pt-MZ": "Grécia",
		"pt-CV": "Grécia",
		"pt-GW": "Grécia",
		"pt-ST": "Grécia",
		"pt-TL": "Grécia",
		"pt-MO": "Grécia",
		"es-ES": "Grecia",
		"es-419": "Grecia",
		"es-AD": "Grecia",
		"es-GI": "Grecia",
		"es-AR": "Grecia",
		"es-BO": "Grecia",
		"es-BR": "Grecia",
		"es-BZ": "Grecia",
		"es-CL": "Grecia",
		"es-CO": "Grecia",
		"es-CR": "Grecia",
		"es-CU": "Grecia",
		"es-DO": "Grecia",
		"es-EC": "Grecia",
		"es-GT": "Grecia",
		"es-HN": "Grecia",
		"es-MX": "Grecia",
		"es-NI": "Grecia",
		"es-PA": "Grecia",
		"es-PE": "Grecia",
		"es-PR": "Grecia",
		"es-PY": "Grecia",
		"es-SV": "Grecia",
		"es-US": "Grecia",
		"es-UY": "Grecia",
		"es-VE": "Grecia",
		"fr-FR": "Grèce",
		"fr-BE": "Grèce",
		"fr-CH": "Grèce",
		"fr-LU": "Grèce",
		"fr-MC": "Grèce",
		"fr-AD": "Grèce",
		"fr-CA": "Grèce",
		"it-IT": "Grecia",
		"it-CH": "Grecia",
		"it-SM": "Grecia",
		"it-VA": "Grecia",
		"de-DE": "Griechenland",
		"de-AT": "Griechenland",
		"de-CH": "Griechenland",
		"de-BE": "Griechenland",
		"de-LI": "Griechenland",
		"de-LU": "Griechenland",
		"nl-NL": "Griekenland",
		"nl-BE": "Griekenland",
		"sv-SE": "Grekland",
		"sv-FI": "Grekland",
		"da-DK": "Grækenland",
		"nb-NO": "Hellas",
		"nn-NO": "Hellas",
		"fi-FI": "Kreikka",
		"is-IS": "Grikkland",
		"fo-FO": "Grikkaland",
		"et-EE": "Kreeka",
		"lv-LV": "Grieķija",
		"lt-LT": "Graikija",
		"pl-PL": "Grecja",
		"cs-CZ": "Řecko",
		"sk-SK": "Grécko",
		"sl-SI": "Grčija",
		"hr-HR": "Grčka",
		"bs-BA": "Grčka",
		"sr-RS": "Грчка",
		"sr-BA": "Грчка",
		"sr-ME": "Grčka",
		"mk-MK": "Грција",
		"bg-BG": "Гърция",
		"be-BY": "Грэцыя",
		"uk-UA": "Греція",
		"ru-RU": "Греция",
		"el-GR": "Ελλάδα",
		"el-CY": "Ελλάδα",
		"ro-RO": "Grecia",
		"ro-MD": "Grecia",
		"hu-HU": "Görögország",
		"sq-AL": "Greqi",
		"sq-XK": "Greqi",
		"mt-MT": "il-Greċja",
		"ga-IE": "an Ghréig",
		"cy-GB": "Gwlad Groeg",
		"gd-GB": "A’ Ghreug",
		"lb-LU": "Griicheland",
		"ca-ES": "Grècia",
		"ca-AD": "Grècia",
		"ca-FR": "Grècia",
		"ca-IT": "Grècia",
		"eu-ES": "Grezia",
		"eu-FR": "Grezia",
		"gl-ES": "Grecia",
		"tr-TR": "Yunanistan",
		"tr-CY": "Yunanistan"
	},
	"callingCode": "30",
	"phoneMasks": [
		{
			"mask": "## #### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"21|7"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[2689]"
			]
		},
		{
			"mask": "#### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2(?:2|3[2-57-9]|4[2-469]|5[2-59]|6[2-9]|7[2-69]|8[2-49])|5"
			]
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11
		},
		{
			"mask": "### #### #####",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
