import type { Country } from './types.js';

export const HKG = {
	"code": "HKG",
	"labels": {
		"pt-BR": "Hong Kong, RAE da China",
		"pt-PT": "Hong Kong, RAE da China",
		"qu-PE": "Hong Kong RAE China",
		"qu-BO": "Hong Kong RAE China",
		"qu-EC": "Hong Kong RAE China",
		"chr-US": "ᎰᏂᎩ ᎪᏂᎩ ᎤᏓᏤᎵᏓ ᏧᏂᎸᏫᏍᏓᏁᏗ ᎢᎬᎾᏕᎾ ᏓᎶᏂᎨᏍᏛ",
		"hi-IN": "हाँग काँग (चीन विशेष प्रशासनिक क्षेत्र)",
		"bn-IN": "হংকং এসএআর চীনা",
		"bn-BD": "হংকং এসএআর চীনা",
		"ta-IN": "ஹாங்காங் எஸ்ஏஆர் சீனா",
		"ta-LK": "ஹாங்காங் எஸ்ஏஆர் சீனா",
		"ta-SG": "ஹாங்காங் எஸ்ஏஆர் சீனா",
		"ta-MY": "ஹாங்காங் எஸ்ஏஆர் சீனா",
		"te-IN": "హాంకాంగ్ ఎస్ఏఆర్ చైనా",
		"mr-IN": "हाँगकाँग एसएआर चीन",
		"gu-IN": "હોંગકોંગ SAR ચીન",
		"kn-IN": "ಹಾಂಗ್ ಕಾಂಗ್ ಎಸ್ಎಆರ್ ಚೈನಾ",
		"ml-IN": "ഹോങ്കോങ് (SAR) ചൈന",
		"pa-IN": "ਹਾਂਗ ਕਾਂਗ ਐਸਏਆਰ ਚੀਨ",
		"ur-IN": "ہانگ کانگ SAR چین",
		"ur-PK": "ہانگ کانگ SAR چین",
		"or-IN": "ହଂ କଂ ଏସଏଆର୍‌ ଚାଇନା",
		"as-IN": "হং কং এছ. এ. আৰ. চীন",
		"ne-IN": "हङकङ चिनियाँ विशेष प्रशासनिक क्षेत्र",
		"ne-NP": "हङकङ चिनियाँ विशेष प्रशासनिक क्षेत्र",
		"si-LK": "හොංකොං විශේෂ පරිපාලන කලාපය චීනය",
		"kok-IN": "हाँग काँग एसएआर चीन",
		"ks-IN": "ہانگ کانگ ایس اے آر چیٖن",
		"brx-IN": "हंकं एस.ए.आर चाइना",
		"mai-IN": "हांग कांग (विशेष प्रशासनिक क्षेत्र चीन)",
		"dz-BT": "ཧོང་ཀོང་ཅཱའི་ན",
		"ja-JP": "中華人民共和国香港特別行政区",
		"ko-KR": "홍콩(중국 특별행정구)",
		"ko-KP": "홍콩(중국 특별행정구)",
		"zh-CN": "中国香港特别行政区",
		"zh-Hans-CN": "中国香港特别行政区",
		"zh-Hant-TW": "中國香港特別行政區",
		"zh-TW": "中國香港特別行政區",
		"zh-HK": "中國香港特別行政區",
		"zh-MO": "中國香港特別行政區",
		"zh-SG": "中国香港特别行政区",
		"yue-Hant-HK": "中國香港特別行政區",
		"yue-Hans-CN": "中华人民共和国香港特别行政区",
		"mn-MN": "БНХАУ-ын Тусгай захиргааны бүс Хонг-Конг",
		"ug-CN": "شياڭگاڭ ئالاھىدە مەمۇرىي رايونى (جۇڭگو)",
		"th-TH": "เขตปกครองพิเศษฮ่องกงแห่งสาธารณรัฐประชาชนจีน",
		"lo-LA": "ຮົງກົງ ເຂດປົກຄອງພິເສດ ຈີນ",
		"km-KH": "ហុងកុង តំបន់រដ្ឋបាលពិសេសចិន",
		"my-MM": "ဟောင်ကောင် (တရုတ်ပြည်)",
		"vi-VN": "Đặc khu Hành chính Hồng Kông, Trung Quốc",
		"id-ID": "Hong Kong DAK Tiongkok",
		"ms-MY": "Hong Kong SAR China",
		"ms-SG": "Hong Kong SAR China",
		"ms-BN": "Hong Kong SAR China",
		"jv-ID": "Laladan Administratif Astamiwa Hong Kong",
		"fil-PH": "Hong Kong SAR China",
		"ceb-PH": "Hong Kong SAR China",
		"ka-GE": "ჰონკონგის სპეციალური ადმინისტრაციული რეგიონი, ჩინეთი",
		"hy-AM": "Հոնկոնգի ՀՎՇ",
		"az-AZ": "Honq Konq Xüsusi İnzibati Rayonu Çin",
		"az-Cyrl-AZ": "Һонк Конг Хүсуси Инзибати Әрази Чин",
		"kk-KZ": "Сянган АӘА",
		"ky-KG": "Гонконг Кытай ААА",
		"uz-UZ": "Gonkong (Xitoy MMH)",
		"tg-TJ": "Ҳонконг (МММ)",
		"tk-TM": "Gonkong AAS Hytaý",
		"fa-IR": "هنگ‌کنگ، منطقهٔ ویژهٔ اداری چین",
		"fa-AF": "هانگ کانگ، ناحیهٔ ویژهٔ حکومتی چین",
		"ps-AF": "هانګ کانګ SAR چین",
		"ps-PK": "هانګ کانګ SAR چین",
		"he-IL": "הונג קונג (אזור מנהלי מיוחד של סין)",
		"ar-SA": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-AE": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-QA": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-BH": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-KW": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-OM": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-YE": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-IQ": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-JO": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-LB": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-SY": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"ar-PS": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
		"en-US": "Hong Kong SAR China",
		"en-GB": "Hong Kong SAR China",
		"en-IE": "Hong Kong SAR China",
		"en-MT": "Hong Kong SAR China",
		"en-GI": "Hong Kong SAR China",
		"en-CY": "Hong Kong SAR China",
		"en-JE": "Hong Kong SAR China",
		"en-GG": "Hong Kong SAR China",
		"en-IM": "Hong Kong SAR China",
		"en-CA": "Hong Kong SAR China",
		"en-AU": "Hong Kong SAR China",
		"en-NZ": "Hong Kong SAR China",
		"en-ZA": "Hong Kong SAR China",
		"en-IN": "Hong Kong SAR China",
		"en-SG": "Hong Kong SAR China",
		"pt-AO": "Hong Kong, RAE da China",
		"pt-MZ": "Hong Kong, RAE da China",
		"pt-CV": "Hong Kong, RAE da China",
		"pt-GW": "Hong Kong, RAE da China",
		"pt-ST": "Hong Kong, RAE da China",
		"pt-TL": "Hong Kong, RAE da China",
		"pt-MO": "Hong Kong, RAE da China",
		"es-ES": "RAE de Hong Kong (China)",
		"es-419": "RAE de Hong Kong (China)",
		"es-AD": "RAE de Hong Kong (China)",
		"es-GI": "RAE de Hong Kong (China)",
		"es-AR": "RAE de Hong Kong (China)",
		"es-BO": "RAE de Hong Kong (China)",
		"es-BR": "RAE de Hong Kong (China)",
		"es-BZ": "RAE de Hong Kong (China)",
		"es-CL": "RAE de Hong Kong (China)",
		"es-CO": "RAE de Hong Kong (China)",
		"es-CR": "RAE de Hong Kong (China)",
		"es-CU": "RAE de Hong Kong (China)",
		"es-DO": "RAE de Hong Kong (China)",
		"es-EC": "RAE de Hong Kong (China)",
		"es-GT": "RAE de Hong Kong (China)",
		"es-HN": "RAE de Hong Kong (China)",
		"es-MX": "RAE de Hong Kong (China)",
		"es-NI": "RAE de Hong Kong (China)",
		"es-PA": "RAE de Hong Kong (China)",
		"es-PE": "RAE de Hong Kong (China)",
		"es-PR": "RAE de Hong Kong (China)",
		"es-PY": "RAE de Hong Kong (China)",
		"es-SV": "RAE de Hong Kong (China)",
		"es-US": "RAE de Hong Kong (China)",
		"es-UY": "RAE de Hong Kong (China)",
		"es-VE": "RAE de Hong Kong (China)",
		"fr-FR": "R.A.S. chinoise de Hong Kong",
		"fr-BE": "R.A.S. chinoise de Hong Kong",
		"fr-CH": "R.A.S. chinoise de Hong Kong",
		"fr-LU": "R.A.S. chinoise de Hong Kong",
		"fr-MC": "R.A.S. chinoise de Hong Kong",
		"fr-AD": "R.A.S. chinoise de Hong Kong",
		"fr-CA": "R.A.S. chinoise de Hong Kong",
		"it-IT": "RAS di Hong Kong",
		"it-CH": "RAS di Hong Kong",
		"it-SM": "RAS di Hong Kong",
		"it-VA": "RAS di Hong Kong",
		"de-DE": "Sonderverwaltungsregion Hongkong",
		"de-AT": "Sonderverwaltungsregion Hongkong",
		"de-CH": "Sonderverwaltungsregion Hongkong",
		"de-BE": "Sonderverwaltungsregion Hongkong",
		"de-LI": "Sonderverwaltungsregion Hongkong",
		"de-LU": "Sonderverwaltungsregion Hongkong",
		"nl-NL": "Hongkong SAR van China",
		"nl-BE": "Hongkong SAR van China",
		"sv-SE": "Hongkong SAR",
		"sv-FI": "Hongkong SAR",
		"da-DK": "SAR Hongkong",
		"nb-NO": "Hongkong SAR Kina",
		"nn-NO": "Hongkong SAR Kina",
		"fi-FI": "Hongkong – Kiinan erityishallintoalue",
		"is-IS": "sérstjórnarsvæðið Hong Kong",
		"fo-FO": "Hong Kong SAR Kina",
		"et-EE": "Hongkongi erihalduspiirkond",
		"lv-LV": "Ķīnas īpašās pārvaldes apgabals Honkonga",
		"lt-LT": "Ypatingasis Administracinis Kinijos Regionas Honkongas",
		"pl-PL": "SRA Hongkong (Chiny)",
		"cs-CZ": "Hongkong – ZAO Číny",
		"sk-SK": "Hongkong – OAO Číny",
		"sl-SI": "Posebno upravno območje Ljudske republike Kitajske Hongkong",
		"hr-HR": "PUP Hong Kong Kina",
		"bs-BA": "Hong Kong (SAR Kina)",
		"sr-RS": "САР Хонгконг (Кина)",
		"sr-BA": "Хонгконг (САО Кине)",
		"sr-ME": "SAR Hongkong (Kina)",
		"mk-MK": "Хонгконг САР Кина",
		"bg-BG": "Хонконг, САР на Китай",
		"be-BY": "Ганконг, САР (Кітай)",
		"uk-UA": "Гонконг, ОАР Китаю",
		"ru-RU": "Гонконг (САР)",
		"el-GR": "Χονγκ Κονγκ ΕΔΠ Κίνας",
		"el-CY": "Χονγκ Κονγκ ΕΔΠ Κίνας",
		"ro-RO": "R.A.S. Hong Kong, China",
		"ro-MD": "R.A.S. Hong Kong, China",
		"hu-HU": "Hongkong KKT",
		"sq-AL": "RPA i Hong-Kongut",
		"sq-XK": "RPA i Hong-Kongut",
		"mt-MT": "ir-Reġjun Amministrattiv Speċjali ta’ Hong Kong tar-Repubblika tal-Poplu taċ-Ċina",
		"ga-IE": "Sainréigiún Riaracháin Hong Cong, Daonphoblacht na Síne",
		"cy-GB": "Hong Kong SAR Tsieina",
		"gd-GB": "Hong Kong SAR na Sìne",
		"lb-LU": "Spezialverwaltungszon Hong Kong",
		"ca-ES": "Hong Kong (RAE Xina)",
		"ca-AD": "Hong Kong (RAE Xina)",
		"ca-FR": "Hong Kong (RAE Xina)",
		"ca-IT": "Hong Kong (RAE Xina)",
		"eu-ES": "Hong Kong Txinako AEB",
		"eu-FR": "Hong Kong Txinako AEB",
		"gl-ES": "Hong Kong RAE da China",
		"tr-TR": "Çin Hong Kong ÖİB",
		"tr-CY": "Çin Hong Kong ÖİB"
	},
	"callingCode": "852",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"900",
				"9003"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[2-7]|8[1-4]|9(?:0[1-9]|[1-8])"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "### ## ### ###",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"9"
			]
		}
	]
} satisfies Country;
