import type { Country } from './types.js';

export const HRV = {
	"code": "HRV",
	"labels": {
		"pt-BR": "Croácia",
		"pt-PT": "Croácia",
		"qu-PE": "Croacia",
		"qu-BO": "Croacia",
		"qu-EC": "Croacia",
		"chr-US": "ᎧᎶᎡᏏᎠ",
		"hi-IN": "क्रोएशिया",
		"bn-IN": "ক্রোয়েশিয়া",
		"bn-BD": "ক্রোয়েশিয়া",
		"ta-IN": "குரோஷியா",
		"ta-LK": "குரோஷியா",
		"ta-SG": "குரோஷியா",
		"ta-MY": "குரோஷியா",
		"te-IN": "క్రొయేషియా",
		"mr-IN": "क्रोएशिया",
		"gu-IN": "ક્રોએશિયા",
		"kn-IN": "ಕ್ರೊಯೇಷಿಯಾ",
		"ml-IN": "ക്രൊയേഷ്യ",
		"pa-IN": "ਕਰੋਏਸ਼ੀਆ",
		"ur-IN": "کروشیا",
		"ur-PK": "کروشیا",
		"or-IN": "କ୍ରୋଏସିଆ",
		"as-IN": "ক্ৰোৱেছিয়া",
		"ne-IN": "क्रोएशिया",
		"ne-NP": "क्रोएशिया",
		"si-LK": "ක්‍රොඒෂියාව",
		"kok-IN": "क्रोयेशीया",
		"ks-IN": "کروشِیا",
		"brx-IN": "क्रवेशिया",
		"mai-IN": "क्रोएशिया",
		"dz-BT": "ཀྲོ་ཨེ་ཤ",
		"ja-JP": "クロアチア",
		"ko-KR": "크로아티아",
		"ko-KP": "크로아티아",
		"zh-CN": "克罗地亚",
		"zh-Hans-CN": "克罗地亚",
		"zh-Hant-TW": "克羅埃西亞",
		"zh-TW": "克羅埃西亞",
		"zh-HK": "克羅地亞",
		"zh-MO": "克羅地亞",
		"zh-SG": "克罗地亚",
		"yue-Hant-HK": "克羅埃西亞",
		"yue-Hans-CN": "克罗埃西亚",
		"mn-MN": "Хорват",
		"ug-CN": "كىرودىيە",
		"th-TH": "โครเอเชีย",
		"lo-LA": "ໂຄຣເອເທຍ",
		"km-KH": "ក្រូអាស៊ី",
		"my-MM": "ခရိုအေးရှား",
		"vi-VN": "Croatia",
		"id-ID": "Kroasia",
		"ms-MY": "Croatia",
		"ms-SG": "Croatia",
		"ms-BN": "Croatia",
		"jv-ID": "Kroasia",
		"fil-PH": "Croatia",
		"ceb-PH": "Croatia",
		"ka-GE": "ხორვატია",
		"hy-AM": "Խորվաթիա",
		"az-AZ": "Xorvatiya",
		"az-Cyrl-AZ": "Хорватија",
		"kk-KZ": "Хорватия",
		"ky-KG": "Хорватия",
		"uz-UZ": "Xorvatiya",
		"tg-TJ": "Хорватия",
		"tk-TM": "Horwatiýa",
		"fa-IR": "کرواسی",
		"fa-AF": "کروشیا",
		"ps-AF": "کرواشيا",
		"ps-PK": "کرواشيا",
		"he-IL": "קרואטיה",
		"ar-SA": "كرواتيا",
		"ar-AE": "كرواتيا",
		"ar-QA": "كرواتيا",
		"ar-BH": "كرواتيا",
		"ar-KW": "كرواتيا",
		"ar-OM": "كرواتيا",
		"ar-YE": "كرواتيا",
		"ar-IQ": "كرواتيا",
		"ar-JO": "كرواتيا",
		"ar-LB": "كرواتيا",
		"ar-SY": "كرواتيا",
		"ar-PS": "كرواتيا",
		"en-US": "Croatia",
		"en-GB": "Croatia",
		"en-IE": "Croatia",
		"en-MT": "Croatia",
		"en-GI": "Croatia",
		"en-CY": "Croatia",
		"en-JE": "Croatia",
		"en-GG": "Croatia",
		"en-IM": "Croatia",
		"en-CA": "Croatia",
		"en-AU": "Croatia",
		"en-NZ": "Croatia",
		"en-ZA": "Croatia",
		"en-IN": "Croatia",
		"en-SG": "Croatia",
		"pt-AO": "Croácia",
		"pt-MZ": "Croácia",
		"pt-CV": "Croácia",
		"pt-GW": "Croácia",
		"pt-ST": "Croácia",
		"pt-TL": "Croácia",
		"pt-MO": "Croácia",
		"es-ES": "Croacia",
		"es-419": "Croacia",
		"es-AD": "Croacia",
		"es-GI": "Croacia",
		"es-AR": "Croacia",
		"es-BO": "Croacia",
		"es-BR": "Croacia",
		"es-BZ": "Croacia",
		"es-CL": "Croacia",
		"es-CO": "Croacia",
		"es-CR": "Croacia",
		"es-CU": "Croacia",
		"es-DO": "Croacia",
		"es-EC": "Croacia",
		"es-GT": "Croacia",
		"es-HN": "Croacia",
		"es-MX": "Croacia",
		"es-NI": "Croacia",
		"es-PA": "Croacia",
		"es-PE": "Croacia",
		"es-PR": "Croacia",
		"es-PY": "Croacia",
		"es-SV": "Croacia",
		"es-US": "Croacia",
		"es-UY": "Croacia",
		"es-VE": "Croacia",
		"fr-FR": "Croatie",
		"fr-BE": "Croatie",
		"fr-CH": "Croatie",
		"fr-LU": "Croatie",
		"fr-MC": "Croatie",
		"fr-AD": "Croatie",
		"fr-CA": "Croatie",
		"it-IT": "Croazia",
		"it-CH": "Croazia",
		"it-SM": "Croazia",
		"it-VA": "Croazia",
		"de-DE": "Kroatien",
		"de-AT": "Kroatien",
		"de-CH": "Kroatien",
		"de-BE": "Kroatien",
		"de-LI": "Kroatien",
		"de-LU": "Kroatien",
		"nl-NL": "Kroatië",
		"nl-BE": "Kroatië",
		"sv-SE": "Kroatien",
		"sv-FI": "Kroatien",
		"da-DK": "Kroatien",
		"nb-NO": "Kroatia",
		"nn-NO": "Kroatia",
		"fi-FI": "Kroatia",
		"is-IS": "Króatía",
		"fo-FO": "Kroatia",
		"et-EE": "Horvaatia",
		"lv-LV": "Horvātija",
		"lt-LT": "Kroatija",
		"pl-PL": "Chorwacja",
		"cs-CZ": "Chorvatsko",
		"sk-SK": "Chorvátsko",
		"sl-SI": "Hrvaška",
		"hr-HR": "Hrvatska",
		"bs-BA": "Hrvatska",
		"sr-RS": "Хрватска",
		"sr-BA": "Хрватска",
		"sr-ME": "Hrvatska",
		"mk-MK": "Хрватска",
		"bg-BG": "Хърватия",
		"be-BY": "Харватыя",
		"uk-UA": "Хорватія",
		"ru-RU": "Хорватия",
		"el-GR": "Κροατία",
		"el-CY": "Κροατία",
		"ro-RO": "Croația",
		"ro-MD": "Croația",
		"hu-HU": "Horvátország",
		"sq-AL": "Kroaci",
		"sq-XK": "Kroaci",
		"mt-MT": "il-Kroazja",
		"ga-IE": "an Chróit",
		"cy-GB": "Croatia",
		"gd-GB": "A’ Chròthais",
		"lb-LU": "Kroatien",
		"ca-ES": "Croàcia",
		"ca-AD": "Croàcia",
		"ca-FR": "Croàcia",
		"ca-IT": "Croàcia",
		"eu-ES": "Kroazia",
		"eu-FR": "Kroazia",
		"gl-ES": "Croacia",
		"tr-TR": "Hırvatistan",
		"tr-CY": "Hırvatistan"
	},
	"callingCode": "385",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "## ## ###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"6[01]"
			]
		},
		{
			"mask": "# #### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "### ## ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"6|7[245]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"9"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[2-57]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
