import type { Country } from './types.js';

export const HUN = {
	"code": "HUN",
	"labels": {
		"pt-BR": "Hungria",
		"pt-PT": "Hungria",
		"qu-PE": "Hungría",
		"qu-BO": "Hungría",
		"qu-EC": "Hungría",
		"chr-US": "ᎲᏂᎦᎵ",
		"hi-IN": "हंगरी",
		"bn-IN": "হাঙ্গেরি",
		"bn-BD": "হাঙ্গেরি",
		"ta-IN": "ஹங்கேரி",
		"ta-LK": "ஹங்கேரி",
		"ta-SG": "ஹங்கேரி",
		"ta-MY": "ஹங்கேரி",
		"te-IN": "హంగేరీ",
		"mr-IN": "हंगेरी",
		"gu-IN": "હંગેરી",
		"kn-IN": "ಹಂಗೇರಿ",
		"ml-IN": "ഹംഗറി",
		"pa-IN": "ਹੰਗਰੀ",
		"ur-IN": "ہنگری",
		"ur-PK": "ہنگری",
		"or-IN": "ହଙ୍ଗେରୀ",
		"as-IN": "হাংগেৰী",
		"ne-IN": "हङ्गेरी",
		"ne-NP": "हङ्गेरी",
		"si-LK": "හන්ගේරියාව",
		"kok-IN": "हंगेरी",
		"ks-IN": "ہَنگری",
		"brx-IN": "हांगारी",
		"mai-IN": "हंगरी",
		"dz-BT": "ཧཱང་གྷ་རི",
		"ja-JP": "ハンガリー",
		"ko-KR": "헝가리",
		"ko-KP": "헝가리",
		"zh-CN": "匈牙利",
		"zh-Hans-CN": "匈牙利",
		"zh-Hant-TW": "匈牙利",
		"zh-TW": "匈牙利",
		"zh-HK": "匈牙利",
		"zh-MO": "匈牙利",
		"zh-SG": "匈牙利",
		"yue-Hant-HK": "匈牙利",
		"yue-Hans-CN": "匈牙利",
		"mn-MN": "Унгар",
		"ug-CN": "ۋېنگىرىيە",
		"th-TH": "ฮังการี",
		"lo-LA": "ຮັງກາຣີ",
		"km-KH": "ហុងគ្រី",
		"my-MM": "ဟန်ဂေရီ",
		"vi-VN": "Hungary",
		"id-ID": "Hungaria",
		"ms-MY": "Hungary",
		"ms-SG": "Hungary",
		"ms-BN": "Hungary",
		"jv-ID": "Honggari",
		"fil-PH": "Hungary",
		"ceb-PH": "Hungary",
		"ka-GE": "უნგრეთი",
		"hy-AM": "Հունգարիա",
		"az-AZ": "Macarıstan",
		"az-Cyrl-AZ": "Маҹарыстан",
		"kk-KZ": "Венгрия",
		"ky-KG": "Венгрия",
		"uz-UZ": "Vengriya",
		"tg-TJ": "Маҷористон",
		"tk-TM": "Wengriýa",
		"fa-IR": "مجارستان",
		"fa-AF": "مجارستان",
		"ps-AF": "مجارستان",
		"ps-PK": "مجارستان",
		"he-IL": "הונגריה",
		"ar-SA": "هنغاريا",
		"ar-AE": "هنغاريا",
		"ar-QA": "هنغاريا",
		"ar-BH": "هنغاريا",
		"ar-KW": "هنغاريا",
		"ar-OM": "هنغاريا",
		"ar-YE": "هنغاريا",
		"ar-IQ": "هنغاريا",
		"ar-JO": "هنغاريا",
		"ar-LB": "هنغاريا",
		"ar-SY": "هنغاريا",
		"ar-PS": "هنغاريا",
		"en-US": "Hungary",
		"en-GB": "Hungary",
		"en-IE": "Hungary",
		"en-MT": "Hungary",
		"en-GI": "Hungary",
		"en-CY": "Hungary",
		"en-JE": "Hungary",
		"en-GG": "Hungary",
		"en-IM": "Hungary",
		"en-CA": "Hungary",
		"en-AU": "Hungary",
		"en-NZ": "Hungary",
		"en-ZA": "Hungary",
		"en-IN": "Hungary",
		"en-SG": "Hungary",
		"pt-AO": "Hungria",
		"pt-MZ": "Hungria",
		"pt-CV": "Hungria",
		"pt-GW": "Hungria",
		"pt-ST": "Hungria",
		"pt-TL": "Hungria",
		"pt-MO": "Hungria",
		"es-ES": "Hungría",
		"es-419": "Hungría",
		"es-AD": "Hungría",
		"es-GI": "Hungría",
		"es-AR": "Hungría",
		"es-BO": "Hungría",
		"es-BR": "Hungría",
		"es-BZ": "Hungría",
		"es-CL": "Hungría",
		"es-CO": "Hungría",
		"es-CR": "Hungría",
		"es-CU": "Hungría",
		"es-DO": "Hungría",
		"es-EC": "Hungría",
		"es-GT": "Hungría",
		"es-HN": "Hungría",
		"es-MX": "Hungría",
		"es-NI": "Hungría",
		"es-PA": "Hungría",
		"es-PE": "Hungría",
		"es-PR": "Hungría",
		"es-PY": "Hungría",
		"es-SV": "Hungría",
		"es-US": "Hungría",
		"es-UY": "Hungría",
		"es-VE": "Hungría",
		"fr-FR": "Hongrie",
		"fr-BE": "Hongrie",
		"fr-CH": "Hongrie",
		"fr-LU": "Hongrie",
		"fr-MC": "Hongrie",
		"fr-AD": "Hongrie",
		"fr-CA": "Hongrie",
		"it-IT": "Ungheria",
		"it-CH": "Ungheria",
		"it-SM": "Ungheria",
		"it-VA": "Ungheria",
		"de-DE": "Ungarn",
		"de-AT": "Ungarn",
		"de-CH": "Ungarn",
		"de-BE": "Ungarn",
		"de-LI": "Ungarn",
		"de-LU": "Ungarn",
		"nl-NL": "Hongarije",
		"nl-BE": "Hongarije",
		"sv-SE": "Ungern",
		"sv-FI": "Ungern",
		"da-DK": "Ungarn",
		"nb-NO": "Ungarn",
		"nn-NO": "Ungarn",
		"fi-FI": "Unkari",
		"is-IS": "Ungverjaland",
		"fo-FO": "Ungarn",
		"et-EE": "Ungari",
		"lv-LV": "Ungārija",
		"lt-LT": "Vengrija",
		"pl-PL": "Węgry",
		"cs-CZ": "Maďarsko",
		"sk-SK": "Maďarsko",
		"sl-SI": "Madžarska",
		"hr-HR": "Mađarska",
		"bs-BA": "Mađarska",
		"sr-RS": "Мађарска",
		"sr-BA": "Мађарска",
		"sr-ME": "Mađarska",
		"mk-MK": "Унгарија",
		"bg-BG": "Унгария",
		"be-BY": "Венгрыя",
		"uk-UA": "Угорщина",
		"ru-RU": "Венгрия",
		"el-GR": "Ουγγαρία",
		"el-CY": "Ουγγαρία",
		"ro-RO": "Ungaria",
		"ro-MD": "Ungaria",
		"hu-HU": "Magyarország",
		"sq-AL": "Hungari",
		"sq-XK": "Hungari",
		"mt-MT": "l-Ungerija",
		"ga-IE": "an Ungáir",
		"cy-GB": "Hwngari",
		"gd-GB": "An Ungair",
		"lb-LU": "Ungarn",
		"ca-ES": "Hongria",
		"ca-AD": "Hongria",
		"ca-FR": "Hongria",
		"ca-IT": "Hongria",
		"eu-ES": "Hungaria",
		"eu-FR": "Hungaria",
		"gl-ES": "Hungría",
		"tr-TR": "Macaristan",
		"tr-CY": "Macaristan"
	},
	"callingCode": "36",
	"phoneMasks": [
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[27][2-9]|3[2-7]|4[24-9]|5[2-79]|6|8[2-57-9]|9[2-69]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
