import type { Country } from './types.js';

export const IOT = {
	"code": "IOT",
	"labels": {
		"pt-BR": "Território Britânico do Oceano Índico",
		"pt-PT": "Território Britânico do Oceano Índico",
		"qu-PE": "Territorio Británico del Océano Índico",
		"qu-BO": "Territorio Británico del Océano Índico",
		"qu-EC": "Territorio Británico del Océano Índico",
		"chr-US": "ᏈᏗᏏ ᏴᏫᏯ ᎠᎺᏉ ᎢᎬᎾᏕᏅ",
		"hi-IN": "ब्रिटिश हिंद महासागरीय क्षेत्र",
		"bn-IN": "ব্রিটিশ ভারত মহাসাগরীয় অঞ্চল",
		"bn-BD": "ব্রিটিশ ভারত মহাসাগরীয় অঞ্চল",
		"ta-IN": "பிரிட்டிஷ் இந்தியப் பெருங்கடல் பிரதேசம்",
		"ta-LK": "பிரிட்டிஷ் இந்தியப் பெருங்கடல் பிரதேசம்",
		"ta-SG": "பிரிட்டிஷ் இந்தியப் பெருங்கடல் பிரதேசம்",
		"ta-MY": "பிரிட்டிஷ் இந்தியப் பெருங்கடல் பிரதேசம்",
		"te-IN": "బ్రిటిష్ హిందూ మహాసముద్ర ప్రాంతం",
		"mr-IN": "ब्रिटिश हिंद महासागर प्रदेश",
		"gu-IN": "બ્રિટિશ ઇન્ડિયન ઓશન ટેરિટરી",
		"kn-IN": "ಬ್ರಿಟೀಷ್ ಹಿಂದೂ ಮಹಾಸಾಗರದ ಪ್ರದೇಶ",
		"ml-IN": "ബ്രിട്ടീഷ് ഇന്ത്യൻ ഓഷ്യൻ ടെറിട്ടറി",
		"pa-IN": "ਬਰਤਾਨਵੀ ਹਿੰਦ ਮਹਾਂਸਾਗਰ ਖਿੱਤਾ",
		"ur-IN": "برطانوی بحر ہند کا علاقہ",
		"ur-PK": "برطانوی بحر ہند کا علاقہ",
		"or-IN": "ବ୍ରିଟିଶ୍‌ ଭାରତୀୟ ମହାସାଗର କ୍ଷେତ୍ର",
		"as-IN": "ব্ৰিটিছ ইণ্ডিয়ান অ’চন টেৰিট’ৰি",
		"ne-IN": "बेलायती हिन्द महासागर क्षेत्र",
		"ne-NP": "बेलायती हिन्द महासागर क्षेत्र",
		"si-LK": "බ්‍රිතාන්‍ය ඉන්දීය සාගර බල ප්‍රදේශය",
		"kok-IN": "ब्रिटिश हिंद महासागरीय क्षेत्र",
		"brx-IN": "ब्रिटिशनि भारतारि लैथो बाहागो",
		"mai-IN": "ब्रिटिश हिंद महासागरीय क्षेत्र",
		"ja-JP": "英領インド洋地域",
		"ko-KR": "영국령 인도양 지역",
		"ko-KP": "영국령 인도양 지역",
		"zh-CN": "英属印度洋领地",
		"zh-Hans-CN": "英属印度洋领地",
		"zh-Hant-TW": "英屬印度洋領地",
		"zh-TW": "英屬印度洋領地",
		"zh-HK": "英屬印度洋領地",
		"zh-MO": "英屬印度洋領地",
		"zh-SG": "英属印度洋领地",
		"yue-Hant-HK": "英屬印度洋領地",
		"yue-Hans-CN": "英属印度洋领地",
		"mn-MN": "Британийн харьяа Энэтхэгийн далай дахь нутаг дэвсгэр",
		"th-TH": "บริติชอินเดียนโอเชียนเทร์ริทอรี",
		"lo-LA": "ເຂດແດນອັງກິດໃນມະຫາສະໝຸດອິນເດຍ",
		"km-KH": "ដែនដី​អង់គ្លេស​នៅ​មហា​សមុទ្រ​ឥណ្ឌា",
		"my-MM": "ဗြိတိသျှပိုင် အိန္ဒိယသမုဒ္ဒရာကျွန်းများ",
		"vi-VN": "Lãnh thổ Ấn Độ Dương thuộc Anh",
		"id-ID": "Wilayah Inggris di Samudra Hindia",
		"ms-MY": "Wilayah Lautan Hindi British",
		"ms-SG": "Wilayah Lautan Hindi British",
		"ms-BN": "Wilayah Lautan Hindi British",
		"jv-ID": "Wilayah Inggris ing Segara Hindia",
		"fil-PH": "British Indian Ocean Territory",
		"ceb-PH": "Teritoryo sa British Indian Ocean",
		"ka-GE": "ბრიტანეთის ტერიტორია ინდოეთის ოკეანეში",
		"hy-AM": "Բրիտանական տարածք Հնդկական Օվկիանոսում",
		"az-AZ": "Britaniyanın Hind Okeanı Ərazisi",
		"kk-KZ": "Үнді мұхитындағы Британ аймағы",
		"ky-KG": "Инди океанындагы Британ территориясы",
		"uz-UZ": "Britaniyaning Hind okeanidagi hududi",
		"tg-TJ": "Қаламрави Британия дар уқёнуси Ҳинд",
		"tk-TM": "Britaniýanyň Hindi okeanyndaky territoriýalary",
		"fa-IR": "قلمرو بریتانیا در اقیانوس هند",
		"fa-AF": "قلمرو بریتانیا در اقیانوس هند",
		"ps-AF": "د برتانوي هند سمندري سيمه",
		"ps-PK": "د برتانوي هند سمندري سيمه",
		"he-IL": "הטריטוריה הבריטית באוקיינוס ההודי",
		"ar-SA": "الإقليم البريطاني في المحيط الهندي",
		"ar-AE": "الإقليم البريطاني في المحيط الهندي",
		"ar-QA": "الإقليم البريطاني في المحيط الهندي",
		"ar-BH": "الإقليم البريطاني في المحيط الهندي",
		"ar-KW": "الإقليم البريطاني في المحيط الهندي",
		"ar-OM": "الإقليم البريطاني في المحيط الهندي",
		"ar-YE": "الإقليم البريطاني في المحيط الهندي",
		"ar-IQ": "الإقليم البريطاني في المحيط الهندي",
		"ar-JO": "الإقليم البريطاني في المحيط الهندي",
		"ar-LB": "الإقليم البريطاني في المحيط الهندي",
		"ar-SY": "الإقليم البريطاني في المحيط الهندي",
		"ar-PS": "الإقليم البريطاني في المحيط الهندي",
		"en-US": "British Indian Ocean Territory",
		"en-GB": "British Indian Ocean Territory",
		"en-IE": "British Indian Ocean Territory",
		"en-MT": "British Indian Ocean Territory",
		"en-GI": "British Indian Ocean Territory",
		"en-CY": "British Indian Ocean Territory",
		"en-JE": "British Indian Ocean Territory",
		"en-GG": "British Indian Ocean Territory",
		"en-IM": "British Indian Ocean Territory",
		"en-CA": "British Indian Ocean Territory",
		"en-AU": "British Indian Ocean Territory",
		"en-NZ": "British Indian Ocean Territory",
		"en-ZA": "British Indian Ocean Territory",
		"en-IN": "British Indian Ocean Territory",
		"en-SG": "British Indian Ocean Territory",
		"pt-AO": "Território Britânico do Oceano Índico",
		"pt-MZ": "Território Britânico do Oceano Índico",
		"pt-CV": "Território Britânico do Oceano Índico",
		"pt-GW": "Território Britânico do Oceano Índico",
		"pt-ST": "Território Britânico do Oceano Índico",
		"pt-TL": "Território Britânico do Oceano Índico",
		"pt-MO": "Território Britânico do Oceano Índico",
		"es-ES": "Territorio Británico del Océano Índico",
		"es-419": "Territorio Británico del Océano Índico",
		"es-AD": "Territorio Británico del Océano Índico",
		"es-GI": "Territorio Británico del Océano Índico",
		"es-AR": "Territorio Británico del Océano Índico",
		"es-BO": "Territorio Británico del Océano Índico",
		"es-BR": "Territorio Británico del Océano Índico",
		"es-BZ": "Territorio Británico del Océano Índico",
		"es-CL": "Territorio Británico del Océano Índico",
		"es-CO": "Territorio Británico del Océano Índico",
		"es-CR": "Territorio Británico del Océano Índico",
		"es-CU": "Territorio Británico del Océano Índico",
		"es-DO": "Territorio Británico del Océano Índico",
		"es-EC": "Territorio Británico del Océano Índico",
		"es-GT": "Territorio Británico del Océano Índico",
		"es-HN": "Territorio Británico del Océano Índico",
		"es-MX": "Territorio Británico del Océano Índico",
		"es-NI": "Territorio Británico del Océano Índico",
		"es-PA": "Territorio Británico del Océano Índico",
		"es-PE": "Territorio Británico del Océano Índico",
		"es-PR": "Territorio Británico del Océano Índico",
		"es-PY": "Territorio Británico del Océano Índico",
		"es-SV": "Territorio Británico del Océano Índico",
		"es-US": "Territorio Británico del Océano Índico",
		"es-UY": "Territorio Británico del Océano Índico",
		"es-VE": "Territorio Británico del Océano Índico",
		"fr-FR": "Territoire britannique de l’océan Indien",
		"fr-BE": "Territoire britannique de l’océan Indien",
		"fr-CH": "Territoire britannique de l’océan Indien",
		"fr-LU": "Territoire britannique de l’océan Indien",
		"fr-MC": "Territoire britannique de l’océan Indien",
		"fr-AD": "Territoire britannique de l’océan Indien",
		"fr-CA": "Territoire britannique de l’océan Indien",
		"it-IT": "Territorio Britannico dell’Oceano Indiano",
		"it-CH": "Territorio Britannico dell’Oceano Indiano",
		"it-SM": "Territorio Britannico dell’Oceano Indiano",
		"it-VA": "Territorio Britannico dell’Oceano Indiano",
		"de-DE": "Britisches Territorium im Indischen Ozean",
		"de-AT": "Britisches Territorium im Indischen Ozean",
		"de-CH": "Britisches Territorium im Indischen Ozean",
		"de-BE": "Britisches Territorium im Indischen Ozean",
		"de-LI": "Britisches Territorium im Indischen Ozean",
		"de-LU": "Britisches Territorium im Indischen Ozean",
		"nl-NL": "Brits Indische Oceaanterritorium",
		"nl-BE": "Brits Indische Oceaanterritorium",
		"sv-SE": "Brittiska territoriet i Indiska oceanen",
		"sv-FI": "Brittiska territoriet i Indiska oceanen",
		"da-DK": "Det Britiske Territorium i Det Indiske Ocean",
		"nb-NO": "Det britiske territoriet i Indiahavet",
		"nn-NO": "Det britiske territoriet i Indiahavet",
		"fi-FI": "Brittiläinen Intian valtameren alue",
		"is-IS": "Bresku Indlandshafseyjar",
		"fo-FO": "Stóra Bretlands Indiahavoyggjar",
		"et-EE": "Briti India ookeani ala",
		"lv-LV": "Indijas okeāna Britu teritorija",
		"lt-LT": "Indijos Vandenyno Britų Sritis",
		"pl-PL": "Brytyjskie Terytorium Oceanu Indyjskiego",
		"cs-CZ": "Britské indickooceánské území",
		"sk-SK": "Britské indickooceánske územie",
		"sl-SI": "Britansko ozemlje v Indijskem oceanu",
		"hr-HR": "Britanski Indijskooceanski Teritorij",
		"bs-BA": "Britanska Teritorija u Indijskom Okeanu",
		"sr-RS": "Британска територија Индијског океана",
		"sr-BA": "Британска територија Индијског океана",
		"sr-ME": "Britanska teritorija Indijskog okeana",
		"mk-MK": "Британска Индоокеанска Територија",
		"bg-BG": "Британска територия в Индийския океан",
		"be-BY": "Брытанская тэрыторыя ў Індыйскім акіяне",
		"uk-UA": "Британська територія в Індійському океані",
		"ru-RU": "Британская территория в Индийском океане",
		"el-GR": "Βρετανικά Εδάφη Ινδικού Ωκεανού",
		"el-CY": "Βρετανικά Εδάφη Ινδικού Ωκεανού",
		"ro-RO": "Teritoriul Britanic din Oceanul Indian",
		"ro-MD": "Teritoriul Britanic din Oceanul Indian",
		"hu-HU": "Brit Indiai-óceáni Terület",
		"sq-AL": "Territori Britanik i Oqeanit Indian",
		"sq-XK": "Territori Britanik i Oqeanit Indian",
		"ga-IE": "Críoch Aigéan Indiach na Breataine",
		"cy-GB": "Tiriogaeth Brydeinig Cefnfor India",
		"gd-GB": "Ranntair Breatannach Cuan nan Innseachan",
		"ca-ES": "Territori Britànic de l’Oceà Índic",
		"ca-AD": "Territori Britànic de l’Oceà Índic",
		"ca-FR": "Territori Britànic de l’Oceà Índic",
		"ca-IT": "Territori Britànic de l’Oceà Índic",
		"eu-ES": "Indiako Ozeanoko lurralde britainiarra",
		"eu-FR": "Indiako Ozeanoko lurralde britainiarra",
		"gl-ES": "Territorio Británico do Océano Índico",
		"tr-TR": "Britanya Hint Okyanusu Toprakları",
		"tr-CY": "Britanya Hint Okyanusu Toprakları"
	},
	"callingCode": "246",
	"phoneMasks": [
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"3"
			]
		}
	]
} satisfies Country;
