import type { Country } from './types.js';

export const IRN = {
	"code": "IRN",
	"labels": {
		"pt-BR": "Irã",
		"pt-PT": "Irão",
		"qu-PE": "Irán",
		"qu-BO": "Irán",
		"qu-EC": "Irán",
		"chr-US": "ᎢᎴᏂ",
		"hi-IN": "ईरान",
		"bn-IN": "ইরান",
		"bn-BD": "ইরান",
		"ta-IN": "ஈரான்",
		"ta-LK": "ஈரான்",
		"ta-SG": "ஈரான்",
		"ta-MY": "ஈரான்",
		"te-IN": "ఇరాన్",
		"mr-IN": "इराण",
		"gu-IN": "ઈરાન",
		"kn-IN": "ಇರಾನ್",
		"ml-IN": "ഇറാൻ",
		"pa-IN": "ਈਰਾਨ",
		"ur-IN": "ایران",
		"ur-PK": "ایران",
		"or-IN": "ଇରାନ",
		"as-IN": "ইৰান",
		"ne-IN": "इरान",
		"ne-NP": "इरान",
		"si-LK": "ඉරානය",
		"kok-IN": "इरान",
		"ks-IN": "ایٖران",
		"brx-IN": "ईरान",
		"mai-IN": "ईरान",
		"dz-BT": "ཨི་རཱན",
		"ja-JP": "イラン",
		"ko-KR": "이란",
		"ko-KP": "이란",
		"zh-CN": "伊朗",
		"zh-Hans-CN": "伊朗",
		"zh-Hant-TW": "伊朗",
		"zh-TW": "伊朗",
		"zh-HK": "伊朗",
		"zh-MO": "伊朗",
		"zh-SG": "伊朗",
		"yue-Hant-HK": "伊朗",
		"yue-Hans-CN": "伊朗",
		"mn-MN": "Иран",
		"ug-CN": "ئىران",
		"th-TH": "อิหร่าน",
		"lo-LA": "ອີຣານ",
		"km-KH": "អ៊ីរ៉ង់",
		"my-MM": "အီရန်",
		"vi-VN": "Iran",
		"id-ID": "Iran",
		"ms-MY": "Iran",
		"ms-SG": "Iran",
		"ms-BN": "Iran",
		"jv-ID": "Iran",
		"fil-PH": "Iran",
		"ceb-PH": "Iran",
		"ka-GE": "ირანი",
		"hy-AM": "Իրան",
		"az-AZ": "İran",
		"az-Cyrl-AZ": "Иран",
		"kk-KZ": "Иран",
		"ky-KG": "Иран",
		"uz-UZ": "Eron",
		"tg-TJ": "Эрон",
		"tk-TM": "Eýran",
		"fa-IR": "ایران",
		"fa-AF": "ایران",
		"ps-AF": "ايران",
		"ps-PK": "ايران",
		"he-IL": "איראן",
		"ar-SA": "إيران",
		"ar-AE": "إيران",
		"ar-QA": "إيران",
		"ar-BH": "إيران",
		"ar-KW": "إيران",
		"ar-OM": "إيران",
		"ar-YE": "إيران",
		"ar-IQ": "إيران",
		"ar-JO": "إيران",
		"ar-LB": "إيران",
		"ar-SY": "إيران",
		"ar-PS": "إيران",
		"en-US": "Iran",
		"en-GB": "Iran",
		"en-IE": "Iran",
		"en-MT": "Iran",
		"en-GI": "Iran",
		"en-CY": "Iran",
		"en-JE": "Iran",
		"en-GG": "Iran",
		"en-IM": "Iran",
		"en-CA": "Iran",
		"en-AU": "Iran",
		"en-NZ": "Iran",
		"en-ZA": "Iran",
		"en-IN": "Iran",
		"en-SG": "Iran",
		"pt-AO": "Irão",
		"pt-MZ": "Irão",
		"pt-CV": "Irão",
		"pt-GW": "Irão",
		"pt-ST": "Irão",
		"pt-TL": "Irão",
		"pt-MO": "Irão",
		"es-ES": "Irán",
		"es-419": "Irán",
		"es-AD": "Irán",
		"es-GI": "Irán",
		"es-AR": "Irán",
		"es-BO": "Irán",
		"es-BR": "Irán",
		"es-BZ": "Irán",
		"es-CL": "Irán",
		"es-CO": "Irán",
		"es-CR": "Irán",
		"es-CU": "Irán",
		"es-DO": "Irán",
		"es-EC": "Irán",
		"es-GT": "Irán",
		"es-HN": "Irán",
		"es-MX": "Irán",
		"es-NI": "Irán",
		"es-PA": "Irán",
		"es-PE": "Irán",
		"es-PR": "Irán",
		"es-PY": "Irán",
		"es-SV": "Irán",
		"es-US": "Irán",
		"es-UY": "Irán",
		"es-VE": "Irán",
		"fr-FR": "Iran",
		"fr-BE": "Iran",
		"fr-CH": "Iran",
		"fr-LU": "Iran",
		"fr-MC": "Iran",
		"fr-AD": "Iran",
		"fr-CA": "Iran",
		"it-IT": "Iran",
		"it-CH": "Iran",
		"it-SM": "Iran",
		"it-VA": "Iran",
		"de-DE": "Iran",
		"de-AT": "Iran",
		"de-CH": "Iran",
		"de-BE": "Iran",
		"de-LI": "Iran",
		"de-LU": "Iran",
		"nl-NL": "Iran",
		"nl-BE": "Iran",
		"sv-SE": "Iran",
		"sv-FI": "Iran",
		"da-DK": "Iran",
		"nb-NO": "Iran",
		"nn-NO": "Iran",
		"fi-FI": "Iran",
		"is-IS": "Íran",
		"fo-FO": "Iran",
		"et-EE": "Iraan",
		"lv-LV": "Irāna",
		"lt-LT": "Iranas",
		"pl-PL": "Iran",
		"cs-CZ": "Írán",
		"sk-SK": "Irán",
		"sl-SI": "Iran",
		"hr-HR": "Iran",
		"bs-BA": "Iran",
		"sr-RS": "Иран",
		"sr-BA": "Иран",
		"sr-ME": "Iran",
		"mk-MK": "Иран",
		"bg-BG": "Иран",
		"be-BY": "Іран",
		"uk-UA": "Іран",
		"ru-RU": "Иран",
		"el-GR": "Ιράν",
		"el-CY": "Ιράν",
		"ro-RO": "Iran",
		"ro-MD": "Iran",
		"hu-HU": "Irán",
		"sq-AL": "Iran",
		"sq-XK": "Iran",
		"mt-MT": "l-Iran",
		"ga-IE": "an Iaráin",
		"cy-GB": "Iran",
		"gd-GB": "Ioràn",
		"lb-LU": "Iran",
		"ca-ES": "Iran",
		"ca-AD": "Iran",
		"ca-FR": "Iran",
		"ca-IT": "Iran",
		"eu-ES": "Iran",
		"eu-FR": "Iran",
		"gl-ES": "Irán",
		"tr-TR": "İran",
		"tr-CY": "İran"
	},
	"callingCode": "98",
	"phoneMasks": [
		{
			"mask": "####",
			"minLength": 4,
			"maxLength": 4
		},
		{
			"mask": "#####",
			"minLength": 5,
			"maxLength": 5,
			"leadingDigits": [
				"96"
			]
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"(?:1[137]|2[13-68]|3[1458]|4[145]|5[1468]|6[16]|7[1467]|8[13467])[12689]"
			]
		},
		{
			"mask": "## #### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[1-8]"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"9"
			]
		}
	]
} satisfies Country;
