import type { Country } from './types.js';

export const ITA = {
	"code": "ITA",
	"labels": {
		"pt-BR": "Itália",
		"pt-PT": "Itália",
		"qu-PE": "Italia",
		"qu-BO": "Italia",
		"qu-EC": "Italia",
		"chr-US": "ᎢᏔᎵ",
		"hi-IN": "इटली",
		"bn-IN": "ইতালি",
		"bn-BD": "ইতালি",
		"ta-IN": "இத்தாலி",
		"ta-LK": "இத்தாலி",
		"ta-SG": "இத்தாலி",
		"ta-MY": "இத்தாலி",
		"te-IN": "ఇటలీ",
		"mr-IN": "इटली",
		"gu-IN": "ઇટાલી",
		"kn-IN": "ಇಟಲಿ",
		"ml-IN": "ഇറ്റലി",
		"pa-IN": "ਇਟਲੀ",
		"ur-IN": "اٹلی",
		"ur-PK": "اٹلی",
		"or-IN": "ଇଟାଲୀ",
		"as-IN": "ইটালি",
		"ne-IN": "इटली",
		"ne-NP": "इटली",
		"si-LK": "ඉතාලිය",
		"kok-IN": "इटली",
		"sd-IN": "इटली",
		"ks-IN": "اِٹلی",
		"doi-IN": "इटली",
		"mni-IN": "ইটালি",
		"brx-IN": "इटाली",
		"sat-IN": "ᱤᱴᱞᱤ",
		"mai-IN": "इटली",
		"sa-IN": "इटली:",
		"dz-BT": "ཨི་ཊ་ལི",
		"ja-JP": "イタリア",
		"ko-KR": "이탈리아",
		"ko-KP": "이탈리아",
		"zh-CN": "意大利",
		"zh-Hans-CN": "意大利",
		"zh-Hant-TW": "義大利",
		"zh-TW": "義大利",
		"zh-HK": "意大利",
		"zh-MO": "意大利",
		"zh-SG": "意大利",
		"yue-Hant-HK": "意大利",
		"yue-Hans-CN": "义大利",
		"mn-MN": "Итали",
		"bo-CN": "ཨི་ཀྲར་ལི་",
		"bo-IN": "ཨི་ཀྲར་ལི་",
		"ug-CN": "ئىتالىيە",
		"ii-CN": "ꑴꄊꆺ",
		"th-TH": "อิตาลี",
		"lo-LA": "ອິຕາລີ",
		"km-KH": "អ៊ីតាលី",
		"my-MM": "အီတလီ",
		"vi-VN": "Italy",
		"id-ID": "Italia",
		"ms-MY": "Itali",
		"ms-SG": "Itali",
		"ms-BN": "Itali",
		"jv-ID": "Itali",
		"su-ID": "Italia",
		"fil-PH": "Italy",
		"ceb-PH": "Italya",
		"ka-GE": "იტალია",
		"hy-AM": "Իտալիա",
		"az-AZ": "İtaliya",
		"az-Cyrl-AZ": "Италија",
		"kk-KZ": "Италия",
		"ky-KG": "Италия",
		"uz-UZ": "Italiya",
		"tg-TJ": "Италия",
		"tk-TM": "Italiýa",
		"fa-IR": "ایتالیا",
		"fa-AF": "ایتالیا",
		"ps-AF": "ایټالیه",
		"ps-PK": "ایټالیه",
		"he-IL": "איטליה",
		"ar-SA": "إيطاليا",
		"ar-AE": "إيطاليا",
		"ar-QA": "إيطاليا",
		"ar-BH": "إيطاليا",
		"ar-KW": "إيطاليا",
		"ar-OM": "إيطاليا",
		"ar-YE": "إيطاليا",
		"ar-IQ": "إيطاليا",
		"ar-JO": "إيطاليا",
		"ar-LB": "إيطاليا",
		"ar-SY": "إيطاليا",
		"ar-PS": "إيطاليا",
		"en-US": "Italy",
		"en-GB": "Italy",
		"en-IE": "Italy",
		"en-MT": "Italy",
		"en-GI": "Italy",
		"en-CY": "Italy",
		"en-JE": "Italy",
		"en-GG": "Italy",
		"en-IM": "Italy",
		"en-CA": "Italy",
		"en-AU": "Italy",
		"en-NZ": "Italy",
		"en-ZA": "Italy",
		"en-IN": "Italy",
		"en-SG": "Italy",
		"pt-AO": "Itália",
		"pt-MZ": "Itália",
		"pt-CV": "Itália",
		"pt-GW": "Itália",
		"pt-ST": "Itália",
		"pt-TL": "Itália",
		"pt-MO": "Itália",
		"es-ES": "Italia",
		"es-419": "Italia",
		"es-AD": "Italia",
		"es-GI": "Italia",
		"es-AR": "Italia",
		"es-BO": "Italia",
		"es-BR": "Italia",
		"es-BZ": "Italia",
		"es-CL": "Italia",
		"es-CO": "Italia",
		"es-CR": "Italia",
		"es-CU": "Italia",
		"es-DO": "Italia",
		"es-EC": "Italia",
		"es-GT": "Italia",
		"es-HN": "Italia",
		"es-MX": "Italia",
		"es-NI": "Italia",
		"es-PA": "Italia",
		"es-PE": "Italia",
		"es-PR": "Italia",
		"es-PY": "Italia",
		"es-SV": "Italia",
		"es-US": "Italia",
		"es-UY": "Italia",
		"es-VE": "Italia",
		"fr-FR": "Italie",
		"fr-BE": "Italie",
		"fr-CH": "Italie",
		"fr-LU": "Italie",
		"fr-MC": "Italie",
		"fr-AD": "Italie",
		"fr-CA": "Italie",
		"it-IT": "Italia",
		"it-CH": "Italia",
		"it-SM": "Italia",
		"it-VA": "Italia",
		"de-DE": "Italien",
		"de-AT": "Italien",
		"de-CH": "Italien",
		"de-BE": "Italien",
		"de-LI": "Italien",
		"de-LU": "Italien",
		"nl-NL": "Italië",
		"nl-BE": "Italië",
		"sv-SE": "Italien",
		"sv-FI": "Italien",
		"da-DK": "Italien",
		"nb-NO": "Italia",
		"nn-NO": "Italia",
		"fi-FI": "Italia",
		"is-IS": "Ítalía",
		"fo-FO": "Italia",
		"et-EE": "Itaalia",
		"lv-LV": "Itālija",
		"lt-LT": "Italija",
		"pl-PL": "Włochy",
		"cs-CZ": "Itálie",
		"sk-SK": "Taliansko",
		"sl-SI": "Italija",
		"hr-HR": "Italija",
		"bs-BA": "Italija",
		"sr-RS": "Италија",
		"sr-BA": "Италија",
		"sr-ME": "Italija",
		"mk-MK": "Италија",
		"bg-BG": "Италия",
		"be-BY": "Італія",
		"uk-UA": "Італія",
		"ru-RU": "Италия",
		"el-GR": "Ιταλία",
		"el-CY": "Ιταλία",
		"ro-RO": "Italia",
		"ro-MD": "Italia",
		"hu-HU": "Olaszország",
		"sq-AL": "Itali",
		"sq-XK": "Itali",
		"mt-MT": "l-Italja",
		"ga-IE": "an Iodáil",
		"cy-GB": "Yr Eidal",
		"gd-GB": "An Eadailt",
		"lb-LU": "Italien",
		"ca-ES": "Itàlia",
		"ca-AD": "Itàlia",
		"ca-FR": "Itàlia",
		"ca-IT": "Itàlia",
		"eu-ES": "Italia",
		"eu-FR": "Italia",
		"gl-ES": "Italia",
		"tr-TR": "İtalya",
		"tr-CY": "İtalya"
	},
	"callingCode": "39",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "## ######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"0[26]"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"894"
			]
		},
		{
			"mask": "### ######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"0[13-57-9][0159]|8(?:03|4[17]|9[2-5])",
				"0[13-57-9][0159]|8(?:03|4[17]|9(?:2|3[04]|[45][0-4]))"
			]
		},
		{
			"mask": "## #### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"0[26]|5"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1(?:44|[679])|[378]|43"
			]
		},
		{
			"mask": "#### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"0(?:[13-579][2-46-8]|8[236-8])"
			]
		},
		{
			"mask": "## #### #####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"0[26]"
			]
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"0[13-57-9][0159]|14"
			]
		},
		{
			"mask": "#### ### ####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"0"
			]
		},
		{
			"mask": "### #### #####",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"3"
			]
		}
	]
} satisfies Country;
