import type { Country } from './types.js';

export const KEN = {
	"code": "KEN",
	"labels": {
		"pt-BR": "Quênia",
		"pt-PT": "Quénia",
		"qu-PE": "Kenia",
		"qu-BO": "Kenia",
		"qu-EC": "Kenia",
		"chr-US": "ᎨᏂᏯ",
		"hi-IN": "केन्या",
		"bn-IN": "কেনিয়া",
		"bn-BD": "কেনিয়া",
		"ta-IN": "கென்யா",
		"ta-LK": "கென்யா",
		"ta-SG": "கென்யா",
		"ta-MY": "கென்யா",
		"te-IN": "కెన్యా",
		"mr-IN": "केनिया",
		"gu-IN": "કેન્યા",
		"kn-IN": "ಕೀನ್ಯಾ",
		"ml-IN": "കെനിയ",
		"pa-IN": "ਕੀਨੀਆ",
		"ur-IN": "کینیا",
		"ur-PK": "کینیا",
		"or-IN": "କେନିୟା",
		"as-IN": "কেনিয়া",
		"ne-IN": "केन्या",
		"ne-NP": "केन्या",
		"si-LK": "කෙන්යාව",
		"kok-IN": "केनया",
		"ks-IN": "کِنیا",
		"brx-IN": "केनिया",
		"mai-IN": "केन्या",
		"dz-BT": "ཀེན་ཡ",
		"ja-JP": "ケニア",
		"ko-KR": "케냐",
		"ko-KP": "케냐",
		"zh-CN": "肯尼亚",
		"zh-Hans-CN": "肯尼亚",
		"zh-Hant-TW": "肯亞",
		"zh-TW": "肯亞",
		"zh-HK": "肯尼亞",
		"zh-MO": "肯尼亞",
		"zh-SG": "肯尼亚",
		"yue-Hant-HK": "肯亞",
		"yue-Hans-CN": "肯亚",
		"mn-MN": "Кени",
		"ug-CN": "كېنىيە",
		"th-TH": "เคนยา",
		"lo-LA": "ເຄນຢາ",
		"km-KH": "កេនយ៉ា",
		"my-MM": "ကင်ညာ",
		"vi-VN": "Kenya",
		"id-ID": "Kenya",
		"ms-MY": "Kenya",
		"ms-SG": "Kenya",
		"ms-BN": "Kenya",
		"jv-ID": "Kénya",
		"fil-PH": "Kenya",
		"ceb-PH": "Kenya",
		"ka-GE": "კენია",
		"hy-AM": "Քենիա",
		"az-AZ": "Keniya",
		"az-Cyrl-AZ": "Кенија",
		"kk-KZ": "Кения",
		"ky-KG": "Кения",
		"uz-UZ": "Keniya",
		"tg-TJ": "Кения",
		"tk-TM": "Keniýa",
		"fa-IR": "کنیا",
		"fa-AF": "کینیا",
		"ps-AF": "کینیا",
		"ps-PK": "کینیا",
		"he-IL": "קניה",
		"ar-SA": "كينيا",
		"ar-AE": "كينيا",
		"ar-QA": "كينيا",
		"ar-BH": "كينيا",
		"ar-KW": "كينيا",
		"ar-OM": "كينيا",
		"ar-YE": "كينيا",
		"ar-IQ": "كينيا",
		"ar-JO": "كينيا",
		"ar-LB": "كينيا",
		"ar-SY": "كينيا",
		"ar-PS": "كينيا",
		"en-US": "Kenya",
		"en-GB": "Kenya",
		"en-IE": "Kenya",
		"en-MT": "Kenya",
		"en-GI": "Kenya",
		"en-CY": "Kenya",
		"en-JE": "Kenya",
		"en-GG": "Kenya",
		"en-IM": "Kenya",
		"en-CA": "Kenya",
		"en-AU": "Kenya",
		"en-NZ": "Kenya",
		"en-ZA": "Kenya",
		"en-IN": "Kenya",
		"en-SG": "Kenya",
		"pt-AO": "Quénia",
		"pt-MZ": "Quénia",
		"pt-CV": "Quénia",
		"pt-GW": "Quénia",
		"pt-ST": "Quénia",
		"pt-TL": "Quénia",
		"pt-MO": "Quénia",
		"es-ES": "Kenia",
		"es-419": "Kenia",
		"es-AD": "Kenia",
		"es-GI": "Kenia",
		"es-AR": "Kenia",
		"es-BO": "Kenia",
		"es-BR": "Kenia",
		"es-BZ": "Kenia",
		"es-CL": "Kenia",
		"es-CO": "Kenia",
		"es-CR": "Kenia",
		"es-CU": "Kenia",
		"es-DO": "Kenia",
		"es-EC": "Kenia",
		"es-GT": "Kenia",
		"es-HN": "Kenia",
		"es-MX": "Kenia",
		"es-NI": "Kenia",
		"es-PA": "Kenia",
		"es-PE": "Kenia",
		"es-PR": "Kenia",
		"es-PY": "Kenia",
		"es-SV": "Kenia",
		"es-US": "Kenia",
		"es-UY": "Kenia",
		"es-VE": "Kenia",
		"fr-FR": "Kenya",
		"fr-BE": "Kenya",
		"fr-CH": "Kenya",
		"fr-LU": "Kenya",
		"fr-MC": "Kenya",
		"fr-AD": "Kenya",
		"fr-CA": "Kenya",
		"it-IT": "Kenya",
		"it-CH": "Kenya",
		"it-SM": "Kenya",
		"it-VA": "Kenya",
		"de-DE": "Kenia",
		"de-AT": "Kenia",
		"de-CH": "Kenia",
		"de-BE": "Kenia",
		"de-LI": "Kenia",
		"de-LU": "Kenia",
		"nl-NL": "Kenia",
		"nl-BE": "Kenia",
		"sv-SE": "Kenya",
		"sv-FI": "Kenya",
		"da-DK": "Kenya",
		"nb-NO": "Kenya",
		"nn-NO": "Kenya",
		"fi-FI": "Kenia",
		"is-IS": "Kenía",
		"fo-FO": "Kenja",
		"et-EE": "Keenia",
		"lv-LV": "Kenija",
		"lt-LT": "Kenija",
		"pl-PL": "Kenia",
		"cs-CZ": "Keňa",
		"sk-SK": "Keňa",
		"sl-SI": "Kenija",
		"hr-HR": "Kenija",
		"bs-BA": "Kenija",
		"sr-RS": "Кенија",
		"sr-BA": "Кенија",
		"sr-ME": "Kenija",
		"mk-MK": "Кенија",
		"bg-BG": "Кения",
		"be-BY": "Кенія",
		"uk-UA": "Кенія",
		"ru-RU": "Кения",
		"el-GR": "Κένυα",
		"el-CY": "Κένυα",
		"ro-RO": "Kenya",
		"ro-MD": "Kenya",
		"hu-HU": "Kenya",
		"sq-AL": "Kenia",
		"sq-XK": "Kenia",
		"mt-MT": "il-Kenja",
		"ga-IE": "an Chéinia",
		"cy-GB": "Kenya",
		"gd-GB": "Ceinia",
		"lb-LU": "Kenia",
		"ca-ES": "Kenya",
		"ca-AD": "Kenya",
		"ca-FR": "Kenya",
		"ca-IT": "Kenya",
		"eu-ES": "Kenya",
		"eu-FR": "Kenya",
		"gl-ES": "Kenya",
		"tr-TR": "Kenya",
		"tr-CY": "Kenya"
	},
	"callingCode": "254",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "## #######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[24-6]"
			]
		},
		{
			"mask": "### ######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[17]"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
