import type { Country } from './types.js';

export const LUX = {
	"code": "LUX",
	"labels": {
		"pt-BR": "Luxemburgo",
		"pt-PT": "Luxemburgo",
		"qu-PE": "Luxemburgo",
		"qu-BO": "Luxemburgo",
		"qu-EC": "Luxemburgo",
		"chr-US": "ᎸᎧᏎᏋᎩ",
		"hi-IN": "लग्ज़मबर्ग",
		"bn-IN": "লাক্সেমবার্গ",
		"bn-BD": "লাক্সেমবার্গ",
		"ta-IN": "லக்ஸ்சம்பர்க்",
		"ta-LK": "லக்ஸ்சம்பர்க்",
		"ta-SG": "லக்ஸ்சம்பர்க்",
		"ta-MY": "லக்ஸ்சம்பர்க்",
		"te-IN": "లక్సెంబర్గ్",
		"mr-IN": "लक्झेंबर्ग",
		"gu-IN": "લક્ઝમબર્ગ",
		"kn-IN": "ಲಕ್ಸೆಂಬರ್ಗ್",
		"ml-IN": "ലക്സംബർഗ്",
		"pa-IN": "ਲਕਜ਼ਮਬਰਗ",
		"ur-IN": "لکسمبرگ",
		"ur-PK": "لکسمبرگ",
		"or-IN": "ଲକ୍ସେମବର୍ଗ",
		"as-IN": "লাক্সেমবাৰ্গ",
		"ne-IN": "लक्जेमबर्ग",
		"ne-NP": "लक्जेमबर्ग",
		"si-LK": "ලක්ශම්බර්ග්",
		"kok-IN": "लक्सेमबर्ग",
		"ks-IN": "لَکسَمبٔرٕگ",
		"brx-IN": "लाक्जेमबुर्ग",
		"mai-IN": "लग्जमबर्ग",
		"dz-BT": "ལག་ཛམ་བོརྒ",
		"ja-JP": "ルクセンブルク",
		"ko-KR": "룩셈부르크",
		"ko-KP": "룩셈부르크",
		"zh-CN": "卢森堡",
		"zh-Hans-CN": "卢森堡",
		"zh-Hant-TW": "盧森堡",
		"zh-TW": "盧森堡",
		"zh-HK": "盧森堡",
		"zh-MO": "盧森堡",
		"zh-SG": "卢森堡",
		"yue-Hant-HK": "盧森堡",
		"yue-Hans-CN": "卢森堡",
		"mn-MN": "Люксембург",
		"ug-CN": "لىيۇكسېمبۇرگ",
		"th-TH": "ลักเซมเบิร์ก",
		"lo-LA": "ລຸກແຊມເບີກ",
		"km-KH": "លុចសំបួ",
		"my-MM": "လူဇင်ဘတ်",
		"vi-VN": "Luxembourg",
		"id-ID": "Luksemburg",
		"ms-MY": "Luxembourg",
		"ms-SG": "Luxembourg",
		"ms-BN": "Luxembourg",
		"jv-ID": "Luksemburg",
		"fil-PH": "Luxembourg",
		"ceb-PH": "Luxembourg",
		"ka-GE": "ლუქსემბურგი",
		"hy-AM": "Լյուքսեմբուրգ",
		"az-AZ": "Lüksemburq",
		"az-Cyrl-AZ": "Лүксембург",
		"kk-KZ": "Люксембург",
		"ky-KG": "Люксембург",
		"uz-UZ": "Lyuksemburg",
		"tg-TJ": "Люксембург",
		"tk-TM": "Lýuksemburg",
		"fa-IR": "لوکزامبورگ",
		"fa-AF": "لوکزامبورگ",
		"ps-AF": "لوګزامبورګ",
		"ps-PK": "لوګزامبورګ",
		"he-IL": "לוקסמבורג",
		"ar-SA": "لوكسمبورغ",
		"ar-AE": "لوكسمبورغ",
		"ar-QA": "لوكسمبورغ",
		"ar-BH": "لوكسمبورغ",
		"ar-KW": "لوكسمبورغ",
		"ar-OM": "لوكسمبورغ",
		"ar-YE": "لوكسمبورغ",
		"ar-IQ": "لوكسمبورغ",
		"ar-JO": "لوكسمبورغ",
		"ar-LB": "لوكسمبورغ",
		"ar-SY": "لوكسمبورغ",
		"ar-PS": "لوكسمبورغ",
		"en-US": "Luxembourg",
		"en-GB": "Luxembourg",
		"en-IE": "Luxembourg",
		"en-MT": "Luxembourg",
		"en-GI": "Luxembourg",
		"en-CY": "Luxembourg",
		"en-JE": "Luxembourg",
		"en-GG": "Luxembourg",
		"en-IM": "Luxembourg",
		"en-CA": "Luxembourg",
		"en-AU": "Luxembourg",
		"en-NZ": "Luxembourg",
		"en-ZA": "Luxembourg",
		"en-IN": "Luxembourg",
		"en-SG": "Luxembourg",
		"pt-AO": "Luxemburgo",
		"pt-MZ": "Luxemburgo",
		"pt-CV": "Luxemburgo",
		"pt-GW": "Luxemburgo",
		"pt-ST": "Luxemburgo",
		"pt-TL": "Luxemburgo",
		"pt-MO": "Luxemburgo",
		"es-ES": "Luxemburgo",
		"es-419": "Luxemburgo",
		"es-AD": "Luxemburgo",
		"es-GI": "Luxemburgo",
		"es-AR": "Luxemburgo",
		"es-BO": "Luxemburgo",
		"es-BR": "Luxemburgo",
		"es-BZ": "Luxemburgo",
		"es-CL": "Luxemburgo",
		"es-CO": "Luxemburgo",
		"es-CR": "Luxemburgo",
		"es-CU": "Luxemburgo",
		"es-DO": "Luxemburgo",
		"es-EC": "Luxemburgo",
		"es-GT": "Luxemburgo",
		"es-HN": "Luxemburgo",
		"es-MX": "Luxemburgo",
		"es-NI": "Luxemburgo",
		"es-PA": "Luxemburgo",
		"es-PE": "Luxemburgo",
		"es-PR": "Luxemburgo",
		"es-PY": "Luxemburgo",
		"es-SV": "Luxemburgo",
		"es-US": "Luxemburgo",
		"es-UY": "Luxemburgo",
		"es-VE": "Luxemburgo",
		"fr-FR": "Luxembourg",
		"fr-BE": "Luxembourg",
		"fr-CH": "Luxembourg",
		"fr-LU": "Luxembourg",
		"fr-MC": "Luxembourg",
		"fr-AD": "Luxembourg",
		"fr-CA": "Luxembourg",
		"it-IT": "Lussemburgo",
		"it-CH": "Lussemburgo",
		"it-SM": "Lussemburgo",
		"it-VA": "Lussemburgo",
		"de-DE": "Luxemburg",
		"de-AT": "Luxemburg",
		"de-CH": "Luxemburg",
		"de-BE": "Luxemburg",
		"de-LI": "Luxemburg",
		"de-LU": "Luxemburg",
		"nl-NL": "Luxemburg",
		"nl-BE": "Luxemburg",
		"sv-SE": "Luxemburg",
		"sv-FI": "Luxemburg",
		"da-DK": "Luxembourg",
		"nb-NO": "Luxemburg",
		"nn-NO": "Luxembourg",
		"fi-FI": "Luxemburg",
		"is-IS": "Lúxemborg",
		"fo-FO": "Luksemborg",
		"et-EE": "Luksemburg",
		"lv-LV": "Luksemburga",
		"lt-LT": "Liuksemburgas",
		"pl-PL": "Luksemburg",
		"cs-CZ": "Lucembursko",
		"sk-SK": "Luxembursko",
		"sl-SI": "Luksemburg",
		"hr-HR": "Luksemburg",
		"bs-BA": "Luksemburg",
		"sr-RS": "Луксембург",
		"sr-BA": "Луксембург",
		"sr-ME": "Luksemburg",
		"mk-MK": "Луксембург",
		"bg-BG": "Люксембург",
		"be-BY": "Люксембург",
		"uk-UA": "Люксембург",
		"ru-RU": "Люксембург",
		"el-GR": "Λουξεμβούργο",
		"el-CY": "Λουξεμβούργο",
		"ro-RO": "Luxemburg",
		"ro-MD": "Luxemburg",
		"hu-HU": "Luxemburg",
		"sq-AL": "Luksemburg",
		"sq-XK": "Luksemburg",
		"mt-MT": "il-Lussemburgu",
		"ga-IE": "Lucsamburg",
		"cy-GB": "Lwcsembwrg",
		"gd-GB": "Lugsamburg",
		"lb-LU": "Lëtzebuerg",
		"ca-ES": "Luxemburg",
		"ca-AD": "Luxemburg",
		"ca-FR": "Luxemburg",
		"ca-IT": "Luxemburg",
		"eu-ES": "Luxenburgo",
		"eu-FR": "Luxenburgo",
		"gl-ES": "Luxemburgo",
		"tr-TR": "Lüksemburg",
		"tr-CY": "Lüksemburg"
	},
	"callingCode": "352",
	"phoneMasks": [
		{
			"mask": "####",
			"minLength": 4,
			"maxLength": 4
		},
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5,
			"leadingDigits": [
				"2(?:0[2-689]|[2-9])|[3-57]|8(?:0[2-9]|[13-9])|9(?:0[89]|[2-579])"
			]
		},
		{
			"mask": "## ## ##",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"2(?:0[2-689]|[2-9])|[3-57]|8(?:0[2-9]|[13-9])|9(?:0[89]|[2-579])"
			]
		},
		{
			"mask": "## ## ###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"20[2-689]"
			]
		},
		{
			"mask": "## ## ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2(?:[0367]|4[3-8])"
			]
		},
		{
			"mask": "### ## ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"80[01]|90[015]"
			]
		},
		{
			"mask": "## ## ## ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"20"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"6"
			]
		},
		{
			"mask": "## ## ## ## ##",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2(?:[0367]|4[3-8])"
			]
		},
		{
			"mask": "## ## ## #####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"[3-57]|8[13-9]|9(?:0[89]|[2-579])|(?:2|80)[2-9]"
			]
		}
	]
} satisfies Country;
