import type { Country } from './types.js';

export const MAF = {
	"code": "MAF",
	"labels": {
		"pt-BR": "São Martinho",
		"pt-PT": "São Martinho (Saint-Martin)",
		"qu-PE": "San Martín",
		"qu-BO": "San Martín",
		"qu-EC": "San Martín",
		"chr-US": "ᎤᏓᏅᏘ ᏡᏡ",
		"hi-IN": "सेंट मार्टिन",
		"bn-IN": "সেন্ট মার্টিন",
		"bn-BD": "সেন্ট মার্টিন",
		"ta-IN": "செயின்ட் மார்ட்டீன்",
		"ta-LK": "செயின்ட் மார்ட்டீன்",
		"ta-SG": "செயின்ட் மார்ட்டீன்",
		"ta-MY": "செயின்ட் மார்ட்டீன்",
		"te-IN": "సెయింట్ మార్టిన్",
		"mr-IN": "सेंट मार्टिन",
		"gu-IN": "સેંટ માર્ટિન",
		"kn-IN": "ಸೇಂಟ್ ಮಾರ್ಟಿನ್",
		"ml-IN": "സെന്റ് മാർട്ടിൻ",
		"pa-IN": "ਸੇਂਟ ਮਾਰਟਿਨ",
		"ur-IN": "سینٹ مارٹن",
		"ur-PK": "سینٹ مارٹن",
		"or-IN": "ସେଣ୍ଟ ମାର୍ଟିନ୍",
		"as-IN": "ছেইণ্ট মাৰ্টিন",
		"ne-IN": "सेन्ट मार्टिन",
		"ne-NP": "सेन्ट मार्टिन",
		"si-LK": "ශාන්ත මාර්ටින්",
		"kok-IN": "सॅंट मार्टिन",
		"ks-IN": "سینٹ مارٹِن",
		"brx-IN": "सैन्ट मार्तिन",
		"mai-IN": "सेंट मार्टिन",
		"dz-BT": "སེནཊ་ མཱར་ཊིན",
		"ja-JP": "サン・マルタン",
		"ko-KR": "생마르탱",
		"ko-KP": "생마르탱",
		"zh-CN": "法属圣马丁",
		"zh-Hans-CN": "法属圣马丁",
		"zh-Hant-TW": "法屬聖馬丁",
		"zh-TW": "法屬聖馬丁",
		"zh-HK": "法屬聖馬丁",
		"zh-MO": "法屬聖馬丁",
		"zh-SG": "法属圣马丁",
		"yue-Hant-HK": "法屬聖馬丁",
		"yue-Hans-CN": "法属圣马丁",
		"mn-MN": "Сент-Мартин",
		"ug-CN": "ساينت مارتىن",
		"th-TH": "เซนต์มาร์ติน",
		"lo-LA": "ເຊນ ມາທິນ",
		"km-KH": "សាំង​ម៉ាទីន",
		"my-MM": "စိန့်မာတင်",
		"vi-VN": "St. Martin",
		"id-ID": "Saint Martin",
		"ms-MY": "Saint Martin",
		"ms-SG": "Saint Martin",
		"ms-BN": "Saint Martin",
		"jv-ID": "Santa Martin",
		"fil-PH": "Saint Martin",
		"ceb-PH": "St. Martin",
		"ka-GE": "სენ-მარტენი",
		"hy-AM": "Սեն Մարտեն",
		"az-AZ": "Sent Martin",
		"az-Cyrl-AZ": "Сент Мартин",
		"kk-KZ": "Сен-Мартен",
		"ky-KG": "Сент-Мартин",
		"uz-UZ": "Sent-Martin",
		"tg-TJ": "Ҷазираи Сент-Мартин",
		"tk-TM": "Sen-Marten",
		"fa-IR": "سنت مارتین",
		"fa-AF": "سنت مارتین",
		"ps-AF": "سینټ مارټن",
		"ps-PK": "سینټ مارټن",
		"he-IL": "סן מרטן",
		"ar-SA": "سان مارتن",
		"ar-AE": "سان مارتن",
		"ar-QA": "سان مارتن",
		"ar-BH": "سان مارتن",
		"ar-KW": "سان مارتن",
		"ar-OM": "سان مارتن",
		"ar-YE": "سان مارتن",
		"ar-IQ": "سان مارتن",
		"ar-JO": "سان مارتن",
		"ar-LB": "سان مارتن",
		"ar-SY": "سان مارتن",
		"ar-PS": "سان مارتن",
		"en-US": "St. Martin",
		"en-GB": "St Martin",
		"en-IE": "St Martin",
		"en-MT": "St Martin",
		"en-GI": "St Martin",
		"en-CY": "St Martin",
		"en-JE": "St Martin",
		"en-GG": "St Martin",
		"en-IM": "St Martin",
		"en-CA": "Saint Martin",
		"en-AU": "St. Martin",
		"en-NZ": "St Martin",
		"en-ZA": "St Martin",
		"en-IN": "St Martin",
		"en-SG": "St Martin",
		"pt-AO": "São Martinho (Saint-Martin)",
		"pt-MZ": "São Martinho (Saint-Martin)",
		"pt-CV": "São Martinho (Saint-Martin)",
		"pt-GW": "São Martinho (Saint-Martin)",
		"pt-ST": "São Martinho (Saint-Martin)",
		"pt-TL": "São Martinho (Saint-Martin)",
		"pt-MO": "São Martinho (Saint-Martin)",
		"es-ES": "San Martín",
		"es-419": "San Martín",
		"es-AD": "San Martín",
		"es-GI": "San Martín",
		"es-AR": "San Martín",
		"es-BO": "San Martín",
		"es-BR": "San Martín",
		"es-BZ": "San Martín",
		"es-CL": "San Martín",
		"es-CO": "San Martín",
		"es-CR": "San Martín",
		"es-CU": "San Martín",
		"es-DO": "San Martín",
		"es-EC": "San Martín",
		"es-GT": "San Martín",
		"es-HN": "San Martín",
		"es-MX": "San Martín",
		"es-NI": "San Martín",
		"es-PA": "San Martín",
		"es-PE": "San Martín",
		"es-PR": "San Martín",
		"es-PY": "San Martín",
		"es-SV": "San Martín",
		"es-US": "San Martín",
		"es-UY": "San Martín",
		"es-VE": "San Martín",
		"fr-FR": "Saint-Martin",
		"fr-BE": "Saint-Martin",
		"fr-CH": "Saint-Martin",
		"fr-LU": "Saint-Martin",
		"fr-MC": "Saint-Martin",
		"fr-AD": "Saint-Martin",
		"fr-CA": "Saint-Martin (France)",
		"it-IT": "Saint Martin",
		"it-CH": "Saint Martin",
		"it-SM": "Saint Martin",
		"it-VA": "Saint Martin",
		"de-DE": "St. Martin",
		"de-AT": "St. Martin",
		"de-CH": "St. Martin",
		"de-BE": "St. Martin",
		"de-LI": "St. Martin",
		"de-LU": "St. Martin",
		"nl-NL": "Saint-Martin",
		"nl-BE": "Saint-Martin",
		"sv-SE": "Saint-Martin",
		"sv-FI": "Saint-Martin",
		"da-DK": "Saint Martin",
		"nb-NO": "Saint-Martin",
		"nn-NO": "Saint-Martin",
		"fi-FI": "Saint-Martin",
		"is-IS": "Saint-Martin",
		"fo-FO": "St-Martin",
		"et-EE": "Saint-Martin",
		"lv-LV": "Senmartēna",
		"lt-LT": "Sen Martenas",
		"pl-PL": "Saint-Martin",
		"cs-CZ": "Svatý Martin (Francie)",
		"sk-SK": "Svätý Martin (fr.)",
		"sl-SI": "Saint Martin",
		"hr-HR": "Saint Martin",
		"bs-BA": "Sveti Martin",
		"sr-RS": "Свети Мартин (Француска)",
		"sr-BA": "Свети Мартин (Француска)",
		"sr-ME": "Sveti Martin (Francuska)",
		"mk-MK": "Сент Мартин",
		"bg-BG": "Сен Мартен",
		"be-BY": "Сен-Мартэн",
		"uk-UA": "Сен-Мартен",
		"ru-RU": "Сен-Мартен",
		"el-GR": "Άγιος Μαρτίνος (Γαλλικό τμήμα)",
		"el-CY": "Άγιος Μαρτίνος (Γαλλικό τμήμα)",
		"ro-RO": "Sfântul Martin",
		"ro-MD": "Sfântul Martin",
		"hu-HU": "Saint Martin",
		"sq-AL": "Sen-Marten",
		"sq-XK": "Sen-Marten",
		"mt-MT": "Saint Martin",
		"ga-IE": "Saint-Martin",
		"cy-GB": "Saint Martin",
		"gd-GB": "Naomh Màrtainn",
		"lb-LU": "St. Martin",
		"ca-ES": "Saint Martin",
		"ca-AD": "Saint Martin",
		"ca-FR": "Saint Martin",
		"ca-IT": "Saint Martin",
		"eu-ES": "San Martin",
		"eu-FR": "San Martin",
		"gl-ES": "Saint Martin",
		"tr-TR": "Saint Martin",
		"tr-CY": "Saint Martin"
	},
	"callingCode": "590",
	"phoneMasks": [
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		}
	]
} satisfies Country;
