import type { Country } from './types.js';

export const MDV = {
	"code": "MDV",
	"labels": {
		"pt-BR": "Maldivas",
		"pt-PT": "Maldivas",
		"qu-PE": "Maldivas",
		"qu-BO": "Maldivas",
		"qu-EC": "Maldivas",
		"chr-US": "ᎹᎵᏗᏫᏍ",
		"hi-IN": "मालदीव",
		"bn-IN": "মালদ্বীপ",
		"bn-BD": "মালদ্বীপ",
		"ta-IN": "மாலத்தீவு",
		"ta-LK": "மாலத்தீவு",
		"ta-SG": "மாலத்தீவு",
		"ta-MY": "மாலத்தீவு",
		"te-IN": "మాల్దీవులు",
		"mr-IN": "मालदीव",
		"gu-IN": "માલદિવ્સ",
		"kn-IN": "ಮಾಲ್ಡೀವ್ಸ್",
		"ml-IN": "മാലിദ്വീപ്",
		"pa-IN": "ਮਾਲਦੀਵ",
		"ur-IN": "مالدیپ",
		"ur-PK": "مالدیپ",
		"or-IN": "ମାଲଦିଭସ୍‌",
		"as-IN": "মালদ্বীপ",
		"ne-IN": "माल्दिभ्स",
		"ne-NP": "माल्दिभ्स",
		"si-LK": "මාල දිවයින",
		"kok-IN": "मालदीव",
		"ks-IN": "مالدیٖو",
		"brx-IN": "मालदीव",
		"mai-IN": "मालदीब",
		"dz-BT": "མཱལ་དིབས",
		"ja-JP": "モルディブ",
		"ko-KR": "몰디브",
		"ko-KP": "몰디브",
		"zh-CN": "马尔代夫",
		"zh-Hans-CN": "马尔代夫",
		"zh-Hant-TW": "馬爾地夫",
		"zh-TW": "馬爾地夫",
		"zh-HK": "馬爾代夫",
		"zh-MO": "馬爾代夫",
		"zh-SG": "马尔代夫",
		"yue-Hant-HK": "馬爾地夫",
		"yue-Hans-CN": "马尔地夫",
		"mn-MN": "Мальдив",
		"ug-CN": "مالدىۋې",
		"th-TH": "มัลดีฟส์",
		"lo-LA": "ມັນດິຟ",
		"km-KH": "ម៉ាល់ឌីវ",
		"my-MM": "မော်လ်ဒိုက်",
		"vi-VN": "Maldives",
		"id-ID": "Maladewa",
		"ms-MY": "Maldives",
		"ms-SG": "Maldives",
		"ms-BN": "Maldives",
		"jv-ID": "Maladéwa",
		"fil-PH": "Maldives",
		"ceb-PH": "Maldives",
		"ka-GE": "მალდივები",
		"hy-AM": "Մալդիվներ",
		"az-AZ": "Maldiv adaları",
		"az-Cyrl-AZ": "Малдив адалары",
		"kk-KZ": "Мальдив аралдары",
		"ky-KG": "Мальдив",
		"uz-UZ": "Maldiv orollari",
		"tg-TJ": "Малдив",
		"tk-TM": "Maldiwler",
		"fa-IR": "مالدیو",
		"fa-AF": "مالدیو",
		"ps-AF": "مالديپ",
		"ps-PK": "مالديپ",
		"he-IL": "האיים המלדיביים",
		"ar-SA": "جزر المالديف",
		"ar-AE": "جزر المالديف",
		"ar-QA": "جزر المالديف",
		"ar-BH": "جزر المالديف",
		"ar-KW": "جزر المالديف",
		"ar-OM": "جزر المالديف",
		"ar-YE": "جزر المالديف",
		"ar-IQ": "جزر المالديف",
		"ar-JO": "جزر المالديف",
		"ar-LB": "جزر المالديف",
		"ar-SY": "جزر المالديف",
		"ar-PS": "جزر المالديف",
		"en-US": "Maldives",
		"en-GB": "Maldives",
		"en-IE": "Maldives",
		"en-MT": "Maldives",
		"en-GI": "Maldives",
		"en-CY": "Maldives",
		"en-JE": "Maldives",
		"en-GG": "Maldives",
		"en-IM": "Maldives",
		"en-CA": "Maldives",
		"en-AU": "Maldives",
		"en-NZ": "Maldives",
		"en-ZA": "Maldives",
		"en-IN": "Maldives",
		"en-SG": "Maldives",
		"pt-AO": "Maldivas",
		"pt-MZ": "Maldivas",
		"pt-CV": "Maldivas",
		"pt-GW": "Maldivas",
		"pt-ST": "Maldivas",
		"pt-TL": "Maldivas",
		"pt-MO": "Maldivas",
		"es-ES": "Maldivas",
		"es-419": "Maldivas",
		"es-AD": "Maldivas",
		"es-GI": "Maldivas",
		"es-AR": "Maldivas",
		"es-BO": "Maldivas",
		"es-BR": "Maldivas",
		"es-BZ": "Maldivas",
		"es-CL": "Maldivas",
		"es-CO": "Maldivas",
		"es-CR": "Maldivas",
		"es-CU": "Maldivas",
		"es-DO": "Maldivas",
		"es-EC": "Maldivas",
		"es-GT": "Maldivas",
		"es-HN": "Maldivas",
		"es-MX": "Maldivas",
		"es-NI": "Maldivas",
		"es-PA": "Maldivas",
		"es-PE": "Maldivas",
		"es-PR": "Maldivas",
		"es-PY": "Maldivas",
		"es-SV": "Maldivas",
		"es-US": "Maldivas",
		"es-UY": "Maldivas",
		"es-VE": "Maldivas",
		"fr-FR": "Maldives",
		"fr-BE": "Maldives",
		"fr-CH": "Maldives",
		"fr-LU": "Maldives",
		"fr-MC": "Maldives",
		"fr-AD": "Maldives",
		"fr-CA": "Maldives",
		"it-IT": "Maldive",
		"it-CH": "Maldive",
		"it-SM": "Maldive",
		"it-VA": "Maldive",
		"de-DE": "Malediven",
		"de-AT": "Malediven",
		"de-CH": "Malediven",
		"de-BE": "Malediven",
		"de-LI": "Malediven",
		"de-LU": "Malediven",
		"nl-NL": "Maldiven",
		"nl-BE": "Maldiven",
		"sv-SE": "Maldiverna",
		"sv-FI": "Maldiverna",
		"da-DK": "Maldiverne",
		"nb-NO": "Maldivene",
		"nn-NO": "Maldivane",
		"fi-FI": "Malediivit",
		"is-IS": "Maldíveyjar",
		"fo-FO": "Maldivoyggjar",
		"et-EE": "Maldiivid",
		"lv-LV": "Maldīvija",
		"lt-LT": "Maldyvai",
		"pl-PL": "Malediwy",
		"cs-CZ": "Maledivy",
		"sk-SK": "Maldivy",
		"sl-SI": "Maldivi",
		"hr-HR": "Maldivi",
		"bs-BA": "Maldivi",
		"sr-RS": "Малдиви",
		"sr-BA": "Малдиви",
		"sr-ME": "Maldivi",
		"mk-MK": "Малдиви",
		"bg-BG": "Малдиви",
		"be-BY": "Мальдывы",
		"uk-UA": "Мальдіви",
		"ru-RU": "Мальдивы",
		"el-GR": "Μαλδίβες",
		"el-CY": "Μαλδίβες",
		"ro-RO": "Maldive",
		"ro-MD": "Maldive",
		"hu-HU": "Maldív-szigetek",
		"sq-AL": "Maldive",
		"sq-XK": "Maldive",
		"mt-MT": "il-Maldivi",
		"ga-IE": "Oileáin Mhaildíve",
		"cy-GB": "Y Maldives",
		"gd-GB": "Na h-Eileanan Mhaladaibh",
		"lb-LU": "Maldiven",
		"ca-ES": "Maldives",
		"ca-AD": "Maldives",
		"ca-FR": "Maldives",
		"ca-IT": "Maldives",
		"eu-ES": "Maldivak",
		"eu-FR": "Maldivak",
		"gl-ES": "Maldivas",
		"tr-TR": "Maldivler",
		"tr-CY": "Maldivler"
	},
	"callingCode": "960",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[34679]"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
