import type { Country } from './types.js';

export const MHL = {
	"code": "MHL",
	"labels": {
		"pt-BR": "Ilhas Marshall",
		"pt-PT": "Ilhas Marshall",
		"qu-PE": "Islas Marshall",
		"qu-BO": "Islas Marshall",
		"qu-EC": "Islas Marshall",
		"chr-US": "ᎹᏌᎵ ᏚᎦᏚᏛᎢ",
		"hi-IN": "मार्शल द्वीपसमूह",
		"bn-IN": "মার্শাল দ্বীপপুঞ্জ",
		"bn-BD": "মার্শাল দ্বীপপুঞ্জ",
		"ta-IN": "மார்ஷல் தீவுகள்",
		"ta-LK": "மார்ஷல் தீவுகள்",
		"ta-SG": "மார்ஷல் தீவுகள்",
		"ta-MY": "மார்ஷல் தீவுகள்",
		"te-IN": "మార్షల్ దీవులు",
		"mr-IN": "मार्शल बेटे",
		"gu-IN": "માર્શલ આઇલેન્ડ્સ",
		"kn-IN": "ಮಾರ್ಷಲ್ ದ್ವೀಪಗಳು",
		"ml-IN": "മാർഷൽ ദ്വീപുകൾ",
		"pa-IN": "ਮਾਰਸ਼ਲ ਟਾਪੂ",
		"ur-IN": "جزائر مارشل",
		"ur-PK": "مارشل آئلینڈز",
		"or-IN": "ମାର୍ଶାଲ୍ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "মাৰ্শ্বাল দ্বীপপুঞ্জ",
		"ne-IN": "मार्शल टापुहरु",
		"ne-NP": "मार्शल टापुहरु",
		"si-LK": "මාෂල් දූපත්",
		"kok-IN": "मार्शल आयलँड्स",
		"ks-IN": "مارشَل جٔزیٖرٕ",
		"brx-IN": "मार्शेल द्वीप",
		"mai-IN": "मार्शल द्वीपसमूह",
		"dz-BT": "མར་ཤེལ་གླིང་ཚོམ",
		"ja-JP": "マーシャル諸島",
		"ko-KR": "마셜 제도",
		"ko-KP": "마셜 제도",
		"zh-CN": "马绍尔群岛",
		"zh-Hans-CN": "马绍尔群岛",
		"zh-Hant-TW": "馬紹爾群島",
		"zh-TW": "馬紹爾群島",
		"zh-HK": "馬紹爾群島",
		"zh-MO": "馬紹爾群島",
		"zh-SG": "马绍尔群岛",
		"yue-Hant-HK": "馬紹爾群島",
		"yue-Hans-CN": "马绍尔群岛",
		"mn-MN": "Маршаллын арлууд",
		"ug-CN": "مارشال ئاراللىرى",
		"th-TH": "หมู่เกาะมาร์แชลล์",
		"lo-LA": "ຫມູ່ເກາະມາແຊວ",
		"km-KH": "កោះ​ម៉ាស់សល",
		"my-MM": "မာရှယ် ကျွန်းစု",
		"vi-VN": "Quần đảo Marshall",
		"id-ID": "Kepulauan Marshall",
		"ms-MY": "Kepulauan Marshall",
		"ms-SG": "Kepulauan Marshall",
		"ms-BN": "Kepulauan Marshall",
		"jv-ID": "Kapuloan Marshall",
		"fil-PH": "Marshall Islands",
		"ceb-PH": "Marshall Islands",
		"ka-GE": "მარშალის კუნძულები",
		"hy-AM": "Մարշալյան կղզիներ",
		"az-AZ": "Marşal adaları",
		"az-Cyrl-AZ": "Маршал адалары",
		"kk-KZ": "Маршалл аралдары",
		"ky-KG": "Маршалл аралдары",
		"uz-UZ": "Marshall orollari",
		"tg-TJ": "Ҷазираҳои Маршалл",
		"tk-TM": "Marşall adalary",
		"fa-IR": "جزایر مارشال",
		"fa-AF": "جزایر مارشال",
		"ps-AF": "مارشل ټاپوګان",
		"ps-PK": "مارشل ټاپوګان",
		"he-IL": "איי מרשל",
		"ar-SA": "جزر مارشال",
		"ar-AE": "جزر مارشال",
		"ar-QA": "جزر مارشال",
		"ar-BH": "جزر مارشال",
		"ar-KW": "جزر مارشال",
		"ar-OM": "جزر مارشال",
		"ar-YE": "جزر مارشال",
		"ar-IQ": "جزر مارشال",
		"ar-JO": "جزر مارشال",
		"ar-LB": "جزر مارشال",
		"ar-SY": "جزر مارشال",
		"ar-PS": "جزر مارشال",
		"en-US": "Marshall Islands",
		"en-GB": "Marshall Islands",
		"en-IE": "Marshall Islands",
		"en-MT": "Marshall Islands",
		"en-GI": "Marshall Islands",
		"en-CY": "Marshall Islands",
		"en-JE": "Marshall Islands",
		"en-GG": "Marshall Islands",
		"en-IM": "Marshall Islands",
		"en-CA": "Marshall Islands",
		"en-AU": "Marshall Islands",
		"en-NZ": "Marshall Islands",
		"en-ZA": "Marshall Islands",
		"en-IN": "Marshall Islands",
		"en-SG": "Marshall Islands",
		"pt-AO": "Ilhas Marshall",
		"pt-MZ": "Ilhas Marshall",
		"pt-CV": "Ilhas Marshall",
		"pt-GW": "Ilhas Marshall",
		"pt-ST": "Ilhas Marshall",
		"pt-TL": "Ilhas Marshall",
		"pt-MO": "Ilhas Marshall",
		"es-ES": "Islas Marshall",
		"es-419": "Islas Marshall",
		"es-AD": "Islas Marshall",
		"es-GI": "Islas Marshall",
		"es-AR": "Islas Marshall",
		"es-BO": "Islas Marshall",
		"es-BR": "Islas Marshall",
		"es-BZ": "Islas Marshall",
		"es-CL": "Islas Marshall",
		"es-CO": "Islas Marshall",
		"es-CR": "Islas Marshall",
		"es-CU": "Islas Marshall",
		"es-DO": "Islas Marshall",
		"es-EC": "Islas Marshall",
		"es-GT": "Islas Marshall",
		"es-HN": "Islas Marshall",
		"es-MX": "Islas Marshall",
		"es-NI": "Islas Marshall",
		"es-PA": "Islas Marshall",
		"es-PE": "Islas Marshall",
		"es-PR": "Islas Marshall",
		"es-PY": "Islas Marshall",
		"es-SV": "Islas Marshall",
		"es-US": "Islas Marshall",
		"es-UY": "Islas Marshall",
		"es-VE": "Islas Marshall",
		"fr-FR": "Îles Marshall",
		"fr-BE": "Îles Marshall",
		"fr-CH": "Îles Marshall",
		"fr-LU": "Îles Marshall",
		"fr-MC": "Îles Marshall",
		"fr-AD": "Îles Marshall",
		"fr-CA": "Îles Marshall",
		"it-IT": "Isole Marshall",
		"it-CH": "Isole Marshall",
		"it-SM": "Isole Marshall",
		"it-VA": "Isole Marshall",
		"de-DE": "Marshallinseln",
		"de-AT": "Marshallinseln",
		"de-CH": "Marshallinseln",
		"de-BE": "Marshallinseln",
		"de-LI": "Marshallinseln",
		"de-LU": "Marshallinseln",
		"nl-NL": "Marshalleilanden",
		"nl-BE": "Marshalleilanden",
		"sv-SE": "Marshallöarna",
		"sv-FI": "Marshallöarna",
		"da-DK": "Marshalløerne",
		"nb-NO": "Marshalløyene",
		"nn-NO": "Marshalløyane",
		"fi-FI": "Marshallinsaaret",
		"is-IS": "Marshalleyjar",
		"fo-FO": "Marshalloyggjar",
		"et-EE": "Marshalli Saared",
		"lv-LV": "Māršala salas",
		"lt-LT": "Maršalo Salos",
		"pl-PL": "Wyspy Marshalla",
		"cs-CZ": "Marshallovy ostrovy",
		"sk-SK": "Marshallove ostrovy",
		"sl-SI": "Marshallovi otoki",
		"hr-HR": "Maršalovi Otoci",
		"bs-BA": "Maršalova ostrva",
		"sr-RS": "Маршалска Острва",
		"sr-BA": "Маршалска Острва",
		"sr-ME": "Maršalska Ostrva",
		"mk-MK": "Маршалски Острови",
		"bg-BG": "Маршалови острови",
		"be-BY": "Маршалавы астравы",
		"uk-UA": "Маршаллові Острови",
		"ru-RU": "Маршалловы о-ва",
		"el-GR": "Νήσοι Μάρσαλ",
		"el-CY": "Νήσοι Μάρσαλ",
		"ro-RO": "Insulele Marshall",
		"ro-MD": "Insulele Marshall",
		"hu-HU": "Marshall-szigetek",
		"sq-AL": "Ishujt Marshall",
		"sq-XK": "Ishujt Marshall",
		"mt-MT": "Gżejjer Marshall",
		"ga-IE": "Oileáin Marshall",
		"cy-GB": "Ynysoedd Marshall",
		"gd-GB": "Eileanan Mharshall",
		"lb-LU": "Marshallinselen",
		"ca-ES": "Illes Marshall",
		"ca-AD": "Illes Marshall",
		"ca-FR": "Illes Marshall",
		"ca-IT": "Illes Marshall",
		"eu-ES": "Marshall Uharteak",
		"eu-FR": "Marshall Uharteak",
		"gl-ES": "Illas Marshall",
		"tr-TR": "Marshall Adaları",
		"tr-CY": "Marshall Adaları"
	},
	"callingCode": "692",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-6]"
			]
		}
	]
} satisfies Country;
