import type { Country } from './types.js';

export const MKD = {
	"code": "MKD",
	"labels": {
		"pt-BR": "Macedônia do Norte",
		"pt-PT": "Macedónia do Norte",
		"qu-PE": "Macedonia del Norte",
		"qu-BO": "Macedonia del Norte",
		"qu-EC": "Macedonia del Norte",
		"chr-US": "ᏧᏴᏜ ᎹᏎᏙᏂᏯ",
		"hi-IN": "उत्तरी मकदूनिया",
		"bn-IN": "উত্তর ম্যাসেডোনিয়া",
		"bn-BD": "উত্তর ম্যাসেডোনিয়া",
		"ta-IN": "வடக்கு மாசிடோனியா",
		"ta-LK": "வடக்கு மாசிடோனியா",
		"ta-SG": "வடக்கு மாசிடோனியா",
		"ta-MY": "வடக்கு மாசிடோனியா",
		"te-IN": "ఉత్తర మాసిడోనియా",
		"mr-IN": "उत्तर मॅसेडोनिया",
		"gu-IN": "ઉત્તર મેસેડોનિયા",
		"kn-IN": "ಉತ್ತರ ಮ್ಯಾಸಿಡೋನಿಯಾ",
		"ml-IN": "നോർത്ത് മാസിഡോണിയ",
		"pa-IN": "ਉੱਤਰੀ ਮੈਕਡੋਨੀਆ",
		"ur-IN": "شمالی مقدونیہ",
		"ur-PK": "شمالی مقدونیہ",
		"or-IN": "ଉତ୍ତର ମାସେଡୋନିଆ",
		"as-IN": "উত্তৰ মেচিডোনীয়া",
		"ne-IN": "उत्तर म्यासेडोनिया",
		"ne-NP": "उत्तर म्यासेडोनिया",
		"si-LK": "උතුරු මැසිඩෝනියාව",
		"kok-IN": "उत्तर मॅसिडोनिया",
		"ks-IN": "شُمالی میسڈونیا",
		"brx-IN": "साहा मेसेड’निया",
		"mai-IN": "उत्तरी मकदूनिया",
		"ja-JP": "北マケドニア",
		"ko-KR": "북마케도니아",
		"ko-KP": "북마케도니아",
		"zh-CN": "北马其顿",
		"zh-Hans-CN": "北马其顿",
		"zh-Hant-TW": "北馬其頓",
		"zh-TW": "北馬其頓",
		"zh-HK": "北馬其頓",
		"zh-MO": "北馬其頓",
		"zh-SG": "北马其顿",
		"yue-Hant-HK": "北馬其頓",
		"yue-Hans-CN": "马其顿",
		"mn-MN": "Хойд Македон",
		"ug-CN": "شىمالىي ماكېدونىيە",
		"th-TH": "มาซิโดเนียเหนือ",
		"lo-LA": "ແມຊິໂດເນຍເໜືອ",
		"km-KH": "ម៉ាសេដ្វានខាងជើង",
		"my-MM": "မြောက် မက်ဆီဒိုးနီးယား",
		"vi-VN": "Bắc Macedonia",
		"id-ID": "Makedonia Utara",
		"ms-MY": "Macedonia Utara",
		"ms-SG": "Macedonia Utara",
		"ms-BN": "Macedonia Utara",
		"jv-ID": "Républik Makédonia Lor",
		"fil-PH": "North Macedonia",
		"ceb-PH": "North Macedonia",
		"ka-GE": "ჩრდილოეთ მაკედონია",
		"hy-AM": "Հյուսիսային Մակեդոնիա",
		"az-AZ": "Şimali Makedoniya",
		"kk-KZ": "Солтүстік Македония",
		"ky-KG": "Түндүк Македония",
		"uz-UZ": "Shimoliy Makedoniya",
		"tg-TJ": "Македонияи Шимолӣ",
		"tk-TM": "Demirgazyk Makedoniýa",
		"fa-IR": "مقدونیهٔ شمالی",
		"fa-AF": "مقدونیهٔ شمالی",
		"ps-AF": "شمالي مقدونيه",
		"ps-PK": "شمالي مقدونيه",
		"he-IL": "מקדוניה הצפונית",
		"ar-SA": "مقدونيا الشمالية",
		"ar-AE": "مقدونيا الشمالية",
		"ar-QA": "مقدونيا الشمالية",
		"ar-BH": "مقدونيا الشمالية",
		"ar-KW": "مقدونيا الشمالية",
		"ar-OM": "مقدونيا الشمالية",
		"ar-YE": "مقدونيا الشمالية",
		"ar-IQ": "مقدونيا الشمالية",
		"ar-JO": "مقدونيا الشمالية",
		"ar-LB": "مقدونيا الشمالية",
		"ar-SY": "مقدونيا الشمالية",
		"ar-PS": "مقدونيا الشمالية",
		"en-US": "North Macedonia",
		"en-GB": "North Macedonia",
		"en-IE": "North Macedonia",
		"en-MT": "North Macedonia",
		"en-GI": "North Macedonia",
		"en-CY": "North Macedonia",
		"en-JE": "North Macedonia",
		"en-GG": "North Macedonia",
		"en-IM": "North Macedonia",
		"en-CA": "North Macedonia",
		"en-AU": "North Macedonia",
		"en-NZ": "North Macedonia",
		"en-ZA": "North Macedonia",
		"en-IN": "North Macedonia",
		"en-SG": "North Macedonia",
		"pt-AO": "Macedónia do Norte",
		"pt-MZ": "Macedónia do Norte",
		"pt-CV": "Macedónia do Norte",
		"pt-GW": "Macedónia do Norte",
		"pt-ST": "Macedónia do Norte",
		"pt-TL": "Macedónia do Norte",
		"pt-MO": "Macedónia do Norte",
		"es-ES": "Macedonia del Norte",
		"es-419": "Macedonia del Norte",
		"es-AD": "Macedonia del Norte",
		"es-GI": "Macedonia del Norte",
		"es-AR": "Macedonia del Norte",
		"es-BO": "Macedonia del Norte",
		"es-BR": "Macedonia del Norte",
		"es-BZ": "Macedonia del Norte",
		"es-CL": "Macedonia del Norte",
		"es-CO": "Macedonia del Norte",
		"es-CR": "Macedonia del Norte",
		"es-CU": "Macedonia del Norte",
		"es-DO": "Macedonia del Norte",
		"es-EC": "Macedonia del Norte",
		"es-GT": "Macedonia del Norte",
		"es-HN": "Macedonia del Norte",
		"es-MX": "Macedonia del Norte",
		"es-NI": "Macedonia del Norte",
		"es-PA": "Macedonia del Norte",
		"es-PE": "Macedonia del Norte",
		"es-PR": "Macedonia del Norte",
		"es-PY": "Macedonia del Norte",
		"es-SV": "Macedonia del Norte",
		"es-US": "Macedonia del Norte",
		"es-UY": "Macedonia del Norte",
		"es-VE": "Macedonia del Norte",
		"fr-FR": "Macédoine du Nord",
		"fr-BE": "Macédoine du Nord",
		"fr-CH": "Macédoine du Nord",
		"fr-LU": "Macédoine du Nord",
		"fr-MC": "Macédoine du Nord",
		"fr-AD": "Macédoine du Nord",
		"fr-CA": "Macédoine du Nord",
		"it-IT": "Macedonia del Nord",
		"it-CH": "Macedonia del Nord",
		"it-SM": "Macedonia del Nord",
		"it-VA": "Macedonia del Nord",
		"de-DE": "Nordmazedonien",
		"de-AT": "Nordmazedonien",
		"de-CH": "Nordmazedonien",
		"de-BE": "Nordmazedonien",
		"de-LI": "Nordmazedonien",
		"de-LU": "Nordmazedonien",
		"nl-NL": "Noord-Macedonië",
		"nl-BE": "Noord-Macedonië",
		"sv-SE": "Nordmakedonien",
		"sv-FI": "Nordmakedonien",
		"da-DK": "Nordmakedonien",
		"nb-NO": "Nord-Makedonia",
		"nn-NO": "Nord-Makedonia",
		"fi-FI": "Pohjois-Makedonia",
		"is-IS": "Norður-Makedónía",
		"fo-FO": "Norður Makedónia",
		"et-EE": "Põhja-Makedoonia",
		"lv-LV": "Ziemeļmaķedonija",
		"lt-LT": "Šiaurės Makedonija",
		"pl-PL": "Macedonia Północna",
		"cs-CZ": "Severní Makedonie",
		"sk-SK": "Severné Macedónsko",
		"sl-SI": "Severna Makedonija",
		"hr-HR": "Sjeverna Makedonija",
		"bs-BA": "Sjeverna Makedonija",
		"sr-RS": "Северна Македонија",
		"sr-BA": "Сјеверна Македонија",
		"sr-ME": "Severna Makedonija",
		"mk-MK": "Северна Македонија",
		"bg-BG": "Северна Македония",
		"be-BY": "Паўночная Македонія",
		"uk-UA": "Північна Македонія",
		"ru-RU": "Северная Македония",
		"el-GR": "Βόρεια Μακεδονία",
		"el-CY": "Βόρεια Μακεδονία",
		"ro-RO": "Macedonia de Nord",
		"ro-MD": "Macedonia de Nord",
		"hu-HU": "Észak-Macedónia",
		"sq-AL": "Maqedonia e Veriut",
		"sq-XK": "Maqedonia e Veriut",
		"mt-MT": "il-Maċedonja ta’ Fuq",
		"ga-IE": "an Mhacadóin Thuaidh",
		"cy-GB": "Gogledd Macedonia",
		"gd-GB": "A’ Mhasadon a Tuath",
		"lb-LU": "Nordmazedonien",
		"ca-ES": "Macedònia del Nord",
		"ca-AD": "Macedònia del Nord",
		"ca-FR": "Macedònia del Nord",
		"ca-IT": "Macedònia del Nord",
		"eu-ES": "Ipar Mazedonia",
		"eu-FR": "Ipar Mazedonia",
		"gl-ES": "Macedonia do Norte",
		"tr-TR": "Kuzey Makedonya",
		"tr-CY": "Kuzey Makedonya"
	},
	"callingCode": "389",
	"phoneMasks": [
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2|34[47]|4(?:[37]7|5[47]|64)"
			]
		},
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[347]"
			]
		},
		{
			"mask": "### # ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[58]"
			]
		}
	]
} satisfies Country;
