import type { Country } from './types.js';

export const MNP = {
	"code": "MNP",
	"labels": {
		"pt-BR": "Ilhas Marianas do Norte",
		"pt-PT": "Ilhas Marianas do Norte",
		"qu-PE": "Islas Marianas del Norte",
		"qu-BO": "Islas Marianas del Norte",
		"qu-EC": "Islas Marianas del Norte",
		"chr-US": "ᏧᏴᏢ ᏗᏜ ᎹᎵᎠᎾ ᏚᎦᏚᏛᎢ",
		"hi-IN": "उत्तरी मारियाना द्वीपसमूह",
		"bn-IN": "উত্তরাঞ্চলীয় মারিয়ানা দ্বীপপুঞ্জ",
		"bn-BD": "উত্তরাঞ্চলীয় মারিয়ানা দ্বীপপুঞ্জ",
		"ta-IN": "வடக்கு மரியானா தீவுகள்",
		"ta-LK": "வடக்கு மரியானா தீவுகள்",
		"ta-SG": "வடக்கு மரியானா தீவுகள்",
		"ta-MY": "வடக்கு மரியானா தீவுகள்",
		"te-IN": "ఉత్తర మరియానా దీవులు",
		"mr-IN": "उत्तरी मारियाना बेटे",
		"gu-IN": "ઉત્તરી મારિયાના આઇલેન્ડ્સ",
		"kn-IN": "ಉತ್ತರ ಮರಿಯಾನಾ ದ್ವೀಪಗಳು",
		"ml-IN": "ഉത്തര മറിയാനാ ദ്വീപുകൾ",
		"pa-IN": "ਉੱਤਰੀ ਮਾਰੀਆਨਾ ਟਾਪੂ",
		"ur-IN": "جزائر شمالی ماریانا",
		"ur-PK": "شمالی ماریانا آئلینڈز",
		"or-IN": "ଉତ୍ତର ମାରିଆନା ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "উত্তৰ মাৰিয়ানা দ্বীপপুঞ্জ",
		"ne-IN": "उत्तरी मारिआना टापु",
		"ne-NP": "उत्तरी मारिआना टापु",
		"si-LK": "උතුරු මරියානා දූපත්",
		"kok-IN": "उत्तरी मरिना आयसलैण्ड",
		"ks-IN": "شُمٲلی مارِیانا جٔزیٖرٕ",
		"brx-IN": "साहायारि मारियाना द्वीप",
		"mai-IN": "उत्तर मरीना द्वीपसमूह",
		"dz-BT": "བྱང་ཕྱོགས་ཀྱི་མ་ར་ཡ་ན་གླིང་ཚོམ",
		"ja-JP": "北マリアナ諸島",
		"ko-KR": "북마리아나제도",
		"ko-KP": "북마리아나제도",
		"zh-CN": "北马里亚纳群岛",
		"zh-Hans-CN": "北马里亚纳群岛",
		"zh-Hant-TW": "北馬利安納群島",
		"zh-TW": "北馬利安納群島",
		"zh-HK": "北馬利安納群島",
		"zh-MO": "北馬利安納群島",
		"zh-SG": "北马里亚纳群岛",
		"yue-Hant-HK": "北馬里亞納群島",
		"yue-Hans-CN": "北马里亚纳群岛",
		"mn-MN": "Хойд Марианы арлууд",
		"ug-CN": "شىمالىي مارىيانا ئاراللىرى",
		"th-TH": "หมู่เกาะนอร์เทิร์นมาเรียนา",
		"lo-LA": "ໝູ່ເກາະມາເຣຍນາຕອນເໜືອ",
		"km-KH": "កោះ​ម៉ារីណា​ខាង​ជើង",
		"my-MM": "မြောက်ပိုင်းမာရီအာနာကျွန်းစု",
		"vi-VN": "Quần đảo Bắc Mariana",
		"id-ID": "Kepulauan Mariana Utara",
		"ms-MY": "Kepulauan Mariana Utara",
		"ms-SG": "Kepulauan Mariana Utara",
		"ms-BN": "Kepulauan Mariana Utara",
		"jv-ID": "Kapuloan Mariana Lor",
		"fil-PH": "Northern Mariana Islands",
		"ceb-PH": "Northern Mariana Islands",
		"ka-GE": "ჩრდილოეთ მარიანას კუნძულები",
		"hy-AM": "Հյուսիսային Մարիանյան կղզիներ",
		"az-AZ": "Şimali Marian adaları",
		"az-Cyrl-AZ": "Шимали Мариан адалары",
		"kk-KZ": "Солтүстік Мариана аралдары",
		"ky-KG": "Түндүк Мариана аралдары",
		"uz-UZ": "Shimoliy Mariana orollari",
		"tg-TJ": "Ҷазираҳои Марианаи Шимолӣ",
		"tk-TM": "Demirgazyk Mariana adalary",
		"fa-IR": "جزایر ماریانای شمالی",
		"fa-AF": "جزایر ماریانای شمالی",
		"ps-AF": "شمالي ماريانا ټاپوګان",
		"ps-PK": "شمالي ماريانا ټاپوګان",
		"he-IL": "איי מריאנה הצפוניים",
		"ar-SA": "جزر ماريانا الشمالية",
		"ar-AE": "جزر ماريانا الشمالية",
		"ar-QA": "جزر ماريانا الشمالية",
		"ar-BH": "جزر ماريانا الشمالية",
		"ar-KW": "جزر ماريانا الشمالية",
		"ar-OM": "جزر ماريانا الشمالية",
		"ar-YE": "جزر ماريانا الشمالية",
		"ar-IQ": "جزر ماريانا الشمالية",
		"ar-JO": "جزر ماريانا الشمالية",
		"ar-LB": "جزر ماريانا الشمالية",
		"ar-SY": "جزر ماريانا الشمالية",
		"ar-PS": "جزر ماريانا الشمالية",
		"en-US": "Northern Mariana Islands",
		"en-GB": "Northern Mariana Islands",
		"en-IE": "Northern Mariana Islands",
		"en-MT": "Northern Mariana Islands",
		"en-GI": "Northern Mariana Islands",
		"en-CY": "Northern Mariana Islands",
		"en-JE": "Northern Mariana Islands",
		"en-GG": "Northern Mariana Islands",
		"en-IM": "Northern Mariana Islands",
		"en-CA": "Northern Mariana Islands",
		"en-AU": "Northern Mariana Islands",
		"en-NZ": "Northern Mariana Islands",
		"en-ZA": "Northern Mariana Islands",
		"en-IN": "Northern Mariana Islands",
		"en-SG": "Northern Mariana Islands",
		"pt-AO": "Ilhas Marianas do Norte",
		"pt-MZ": "Ilhas Marianas do Norte",
		"pt-CV": "Ilhas Marianas do Norte",
		"pt-GW": "Ilhas Marianas do Norte",
		"pt-ST": "Ilhas Marianas do Norte",
		"pt-TL": "Ilhas Marianas do Norte",
		"pt-MO": "Ilhas Marianas do Norte",
		"es-ES": "Islas Marianas del Norte",
		"es-419": "Islas Marianas del Norte",
		"es-AD": "Islas Marianas del Norte",
		"es-GI": "Islas Marianas del Norte",
		"es-AR": "Islas Marianas del Norte",
		"es-BO": "Islas Marianas del Norte",
		"es-BR": "Islas Marianas del Norte",
		"es-BZ": "Islas Marianas del Norte",
		"es-CL": "Islas Marianas del Norte",
		"es-CO": "Islas Marianas del Norte",
		"es-CR": "Islas Marianas del Norte",
		"es-CU": "Islas Marianas del Norte",
		"es-DO": "Islas Marianas del Norte",
		"es-EC": "Islas Marianas del Norte",
		"es-GT": "Islas Marianas del Norte",
		"es-HN": "Islas Marianas del Norte",
		"es-MX": "Islas Marianas del Norte",
		"es-NI": "Islas Marianas del Norte",
		"es-PA": "Islas Marianas del Norte",
		"es-PE": "Islas Marianas del Norte",
		"es-PR": "Islas Marianas del Norte",
		"es-PY": "Islas Marianas del Norte",
		"es-SV": "Islas Marianas del Norte",
		"es-US": "Islas Marianas del Norte",
		"es-UY": "Islas Marianas del Norte",
		"es-VE": "Islas Marianas del Norte",
		"fr-FR": "Îles Mariannes du Nord",
		"fr-BE": "Îles Mariannes du Nord",
		"fr-CH": "Îles Mariannes du Nord",
		"fr-LU": "Îles Mariannes du Nord",
		"fr-MC": "Îles Mariannes du Nord",
		"fr-AD": "Îles Mariannes du Nord",
		"fr-CA": "Mariannes du Nord",
		"it-IT": "Isole Marianne Settentrionali",
		"it-CH": "Isole Marianne Settentrionali",
		"it-SM": "Isole Marianne Settentrionali",
		"it-VA": "Isole Marianne Settentrionali",
		"de-DE": "Nördliche Marianen",
		"de-AT": "Nördliche Marianen",
		"de-CH": "Nördliche Marianen",
		"de-BE": "Nördliche Marianen",
		"de-LI": "Nördliche Marianen",
		"de-LU": "Nördliche Marianen",
		"nl-NL": "Noordelijke Marianen",
		"nl-BE": "Noordelijke Marianen",
		"sv-SE": "Nordmarianerna",
		"sv-FI": "Nordmarianerna",
		"da-DK": "Nordmarianerne",
		"nb-NO": "Nord-Marianene",
		"nn-NO": "Nord-Marianane",
		"fi-FI": "Pohjois-Mariaanit",
		"is-IS": "Norður-Maríanaeyjar",
		"fo-FO": "Norðaru Mariuoyggjar",
		"et-EE": "Põhja-Mariaanid",
		"lv-LV": "Ziemeļu Marianas salas",
		"lt-LT": "Marianos Šiaurinės Salos",
		"pl-PL": "Mariany Północne",
		"cs-CZ": "Severní Mariany",
		"sk-SK": "Severné Mariány",
		"sl-SI": "Severni Marianski otoki",
		"hr-HR": "Sjevernomarijanski Otoci",
		"bs-BA": "Sjeverna Marijanska ostrva",
		"sr-RS": "Северна Маријанска Острва",
		"sr-BA": "Сјеверна Маријанска острва",
		"sr-ME": "Severna Marijanska Ostrva",
		"mk-MK": "Северни Маријански Острови",
		"bg-BG": "Северни Мариански острови",
		"be-BY": "Паўночныя Марыянскія астравы",
		"uk-UA": "Північні Маріанські Острови",
		"ru-RU": "Северные Марианские о-ва",
		"el-GR": "Νήσοι Βόρειες Μαριάνες",
		"el-CY": "Νήσοι Βόρειες Μαριάνες",
		"ro-RO": "Insulele Mariane de Nord",
		"ro-MD": "Insulele Mariane de Nord",
		"hu-HU": "Északi Mariana-szigetek",
		"sq-AL": "Ishujt e Marianës Veriore",
		"sq-XK": "Ishujt e Marianës Veriore",
		"mt-MT": "Ġżejjer Mariana tat-Tramuntana",
		"ga-IE": "Na hOileáin Mháirianacha Thuaidh",
		"cy-GB": "Ynysoedd Gogledd Mariana",
		"gd-GB": "Na h-Eileanan Mairianach a Tuath",
		"lb-LU": "Nërdlech Marianen",
		"ca-ES": "Illes Marianes del Nord",
		"ca-AD": "Illes Marianes del Nord",
		"ca-FR": "Illes Marianes del Nord",
		"ca-IT": "Illes Marianes del Nord",
		"eu-ES": "Ipar Mariana uharteak",
		"eu-FR": "Ipar Mariana uharteak",
		"gl-ES": "Illas Marianas do Norte",
		"tr-TR": "Kuzey Mariana Adaları",
		"tr-CY": "Kuzey Mariana Adaları"
	},
	"callingCode": "1670",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
