import type { Country } from './types.js';

export const MTQ = {
	"code": "MTQ",
	"labels": {
		"pt-BR": "Martinica",
		"pt-PT": "Martinica",
		"qu-PE": "Martinica",
		"qu-BO": "Martinica",
		"qu-EC": "Martinica",
		"chr-US": "ᎹᏘᏂᎨ",
		"hi-IN": "मार्टीनिक",
		"bn-IN": "মার্টিনিক",
		"bn-BD": "মার্টিনিক",
		"ta-IN": "மார்டினிக்",
		"ta-LK": "மார்டினிக்",
		"ta-SG": "மார்டினிக்",
		"ta-MY": "மார்டினிக்",
		"te-IN": "మార్టినీక్",
		"mr-IN": "मार्टिनिक",
		"gu-IN": "માર્ટીનીક",
		"kn-IN": "ಮಾರ್ಟಿನಿಕ್",
		"ml-IN": "മാർട്ടിനിക്ക്",
		"pa-IN": "ਮਾਰਟੀਨਿਕ",
		"ur-IN": "مارٹینک",
		"ur-PK": "مارٹینک",
		"or-IN": "ମାର୍ଟିନିକ୍ୟୁ",
		"as-IN": "মাৰ্টিনিক",
		"ne-IN": "मार्टिनिक",
		"ne-NP": "मार्टिनिक",
		"si-LK": "මර්ටිනික්",
		"kok-IN": "मार्टीनिक",
		"ks-IN": "مارٹِنِک",
		"brx-IN": "मार्तिनिक",
		"mai-IN": "मार्टिनिक",
		"dz-BT": "མཱར་ཊི་ནིཀ",
		"ja-JP": "マルティニーク",
		"ko-KR": "마르티니크",
		"ko-KP": "마르티니크",
		"zh-CN": "马提尼克",
		"zh-Hans-CN": "马提尼克",
		"zh-Hant-TW": "馬丁尼克",
		"zh-TW": "馬丁尼克",
		"zh-HK": "馬丁尼克",
		"zh-MO": "馬丁尼克",
		"zh-SG": "马提尼克",
		"yue-Hant-HK": "馬丁尼克島",
		"yue-Hans-CN": "马丁尼克岛",
		"mn-MN": "Мартиник",
		"ug-CN": "مارتىنىكا",
		"th-TH": "มาร์ตินีก",
		"lo-LA": "ມາຕິນີກ",
		"km-KH": "ម៉ាទីនីក",
		"my-MM": "မာတီနိခ်",
		"vi-VN": "Martinique",
		"id-ID": "Martinik",
		"ms-MY": "Martinique",
		"ms-SG": "Martinique",
		"ms-BN": "Martinique",
		"jv-ID": "Martinik",
		"fil-PH": "Martinique",
		"ceb-PH": "Martinique",
		"ka-GE": "მარტინიკა",
		"hy-AM": "Մարտինիկա",
		"az-AZ": "Martinik",
		"az-Cyrl-AZ": "Мартиник",
		"kk-KZ": "Мартиника",
		"ky-KG": "Мартиника",
		"uz-UZ": "Martinika",
		"tg-TJ": "Мартиника",
		"tk-TM": "Martinika",
		"fa-IR": "مارتینیک",
		"fa-AF": "مارتینیک",
		"ps-AF": "مارټینیک",
		"ps-PK": "مارټینیک",
		"he-IL": "מרטיניק",
		"ar-SA": "جزر المارتينيك",
		"ar-AE": "جزر المارتينيك",
		"ar-QA": "جزر المارتينيك",
		"ar-BH": "جزر المارتينيك",
		"ar-KW": "جزر المارتينيك",
		"ar-OM": "جزر المارتينيك",
		"ar-YE": "جزر المارتينيك",
		"ar-IQ": "جزر المارتينيك",
		"ar-JO": "جزر المارتينيك",
		"ar-LB": "جزر المارتينيك",
		"ar-SY": "جزر المارتينيك",
		"ar-PS": "جزر المارتينيك",
		"en-US": "Martinique",
		"en-GB": "Martinique",
		"en-IE": "Martinique",
		"en-MT": "Martinique",
		"en-GI": "Martinique",
		"en-CY": "Martinique",
		"en-JE": "Martinique",
		"en-GG": "Martinique",
		"en-IM": "Martinique",
		"en-CA": "Martinique",
		"en-AU": "Martinique",
		"en-NZ": "Martinique",
		"en-ZA": "Martinique",
		"en-IN": "Martinique",
		"en-SG": "Martinique",
		"pt-AO": "Martinica",
		"pt-MZ": "Martinica",
		"pt-CV": "Martinica",
		"pt-GW": "Martinica",
		"pt-ST": "Martinica",
		"pt-TL": "Martinica",
		"pt-MO": "Martinica",
		"es-ES": "Martinica",
		"es-419": "Martinica",
		"es-AD": "Martinica",
		"es-GI": "Martinica",
		"es-AR": "Martinica",
		"es-BO": "Martinica",
		"es-BR": "Martinica",
		"es-BZ": "Martinica",
		"es-CL": "Martinica",
		"es-CO": "Martinica",
		"es-CR": "Martinica",
		"es-CU": "Martinica",
		"es-DO": "Martinica",
		"es-EC": "Martinica",
		"es-GT": "Martinica",
		"es-HN": "Martinica",
		"es-MX": "Martinica",
		"es-NI": "Martinica",
		"es-PA": "Martinica",
		"es-PE": "Martinica",
		"es-PR": "Martinica",
		"es-PY": "Martinica",
		"es-SV": "Martinica",
		"es-US": "Martinica",
		"es-UY": "Martinica",
		"es-VE": "Martinica",
		"fr-FR": "Martinique",
		"fr-BE": "Martinique",
		"fr-CH": "Martinique",
		"fr-LU": "Martinique",
		"fr-MC": "Martinique",
		"fr-AD": "Martinique",
		"fr-CA": "Martinique",
		"it-IT": "Martinica",
		"it-CH": "Martinica",
		"it-SM": "Martinica",
		"it-VA": "Martinica",
		"de-DE": "Martinique",
		"de-AT": "Martinique",
		"de-CH": "Martinique",
		"de-BE": "Martinique",
		"de-LI": "Martinique",
		"de-LU": "Martinique",
		"nl-NL": "Martinique",
		"nl-BE": "Martinique",
		"sv-SE": "Martinique",
		"sv-FI": "Martinique",
		"da-DK": "Martinique",
		"nb-NO": "Martinique",
		"nn-NO": "Martinique",
		"fi-FI": "Martinique",
		"is-IS": "Martiník",
		"fo-FO": "Martinique",
		"et-EE": "Martinique",
		"lv-LV": "Martinika",
		"lt-LT": "Martinika",
		"pl-PL": "Martynika",
		"cs-CZ": "Martinik",
		"sk-SK": "Martinik",
		"sl-SI": "Martinik",
		"hr-HR": "Martinik",
		"bs-BA": "Martinik",
		"sr-RS": "Мартиник",
		"sr-BA": "Мартиник",
		"sr-ME": "Martinik",
		"mk-MK": "Мартиник",
		"bg-BG": "Мартиника",
		"be-BY": "Марцініка",
		"uk-UA": "Мартиніка",
		"ru-RU": "Мартиника",
		"el-GR": "Μαρτινίκα",
		"el-CY": "Μαρτινίκα",
		"ro-RO": "Martinica",
		"ro-MD": "Martinica",
		"hu-HU": "Martinique",
		"sq-AL": "Martinikë",
		"sq-XK": "Martinikë",
		"mt-MT": "Martinique",
		"ga-IE": "Martinique",
		"cy-GB": "Martinique",
		"gd-GB": "Mairtinic",
		"lb-LU": "Martinique",
		"ca-ES": "Martinica",
		"ca-AD": "Martinica",
		"ca-FR": "Martinica",
		"ca-IT": "Martinica",
		"eu-ES": "Martinika",
		"eu-FR": "Martinika",
		"gl-ES": "Martinica",
		"tr-TR": "Martinik",
		"tr-CY": "Martinik"
	},
	"callingCode": "596",
	"phoneMasks": [
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[5-79]|8(?:0[6-9]|[36])"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
