import type { Country } from './types.js';

export const NCL = {
	"code": "NCL",
	"labels": {
		"pt-BR": "Nova Caledônia",
		"pt-PT": "Nova Caledónia",
		"qu-PE": "Nueva Caledonia",
		"qu-BO": "Nueva Caledonia",
		"qu-EC": "Nueva Caledonia",
		"chr-US": "ᎢᏤ ᎧᎵᏙᏂᎠᏂ",
		"hi-IN": "न्यू कैलेडोनिया",
		"bn-IN": "নিউ ক্যালেডোনিয়া",
		"bn-BD": "নিউ ক্যালেডোনিয়া",
		"ta-IN": "நியூ கேலிடோனியா",
		"ta-LK": "நியூ கேலிடோனியா",
		"ta-SG": "நியூ கேலிடோனியா",
		"ta-MY": "நியூ கேலிடோனியா",
		"te-IN": "క్రొత్త కాలెడోనియా",
		"mr-IN": "न्यू कॅलेडोनिया",
		"gu-IN": "ન્યુ સેલેડોનિયા",
		"kn-IN": "ನ್ಯೂ ಕ್ಯಾಲಿಡೋನಿಯಾ",
		"ml-IN": "ന്യൂ കാലിഡോണിയ",
		"pa-IN": "ਨਿਊ ਕੈਲੇਡੋਨੀਆ",
		"ur-IN": "نیو کلیڈونیا",
		"ur-PK": "نیو کلیڈونیا",
		"or-IN": "ନୂତନ କାଲେଡୋନିଆ",
		"as-IN": "নিউ কেলিডোনিয়া",
		"ne-IN": "न्यु क्यालेडोनिया",
		"ne-NP": "न्यु क्यालेडोनिया",
		"si-LK": "නව කැලිඩෝනියාව",
		"kok-IN": "न्यू कॅलिडोनिया",
		"ks-IN": "نِو کیلِڑونِیا",
		"brx-IN": "निउ केलेडनिया",
		"mai-IN": "न्यू कैलेडोनिया",
		"dz-BT": "ནིའུ་ཀ་ལི་དོ་ནི་ཡ",
		"ja-JP": "ニューカレドニア",
		"ko-KR": "뉴칼레도니아",
		"ko-KP": "뉴칼레도니아",
		"zh-CN": "新喀里多尼亚",
		"zh-Hans-CN": "新喀里多尼亚",
		"zh-Hant-TW": "新喀里多尼亞",
		"zh-TW": "新喀里多尼亞",
		"zh-HK": "新喀里多尼亞",
		"zh-MO": "新喀里多尼亞",
		"zh-SG": "新喀里多尼亚",
		"yue-Hant-HK": "新喀里多尼亞",
		"yue-Hans-CN": "新喀里多尼亚",
		"mn-MN": "Шинэ Каледони",
		"ug-CN": "يېڭى كالېدونىيە",
		"th-TH": "นิวแคลิโดเนีย",
		"lo-LA": "ນິວ ຄາເລໂດເນຍ",
		"km-KH": "នូវែល​កាឡេដូនី",
		"my-MM": "နယူး ကယ်လီဒိုနီးယား",
		"vi-VN": "New Caledonia",
		"id-ID": "Kaledonia Baru",
		"ms-MY": "New Caledonia",
		"ms-SG": "New Caledonia",
		"ms-BN": "New Caledonia",
		"jv-ID": "Kalédonia Anyar",
		"fil-PH": "New Caledonia",
		"ceb-PH": "New Caledonia",
		"ka-GE": "ახალი კალედონია",
		"hy-AM": "Նոր Կալեդոնիա",
		"az-AZ": "Yeni Kaledoniya",
		"az-Cyrl-AZ": "Јени Каледонија",
		"kk-KZ": "Жаңа Каледония",
		"ky-KG": "Жаңы Каледония",
		"uz-UZ": "Yangi Kaledoniya",
		"tg-TJ": "Каледонияи Нав",
		"tk-TM": "Täze Kaledoniýa",
		"fa-IR": "کالدونیای جدید",
		"fa-AF": "کالدونیای جدید",
		"ps-AF": "نوی کالیډونیا",
		"ps-PK": "نوی کالیډونیا",
		"he-IL": "קלדוניה החדשה",
		"ar-SA": "كاليدونيا الجديدة",
		"ar-AE": "كاليدونيا الجديدة",
		"ar-QA": "كاليدونيا الجديدة",
		"ar-BH": "كاليدونيا الجديدة",
		"ar-KW": "كاليدونيا الجديدة",
		"ar-OM": "كاليدونيا الجديدة",
		"ar-YE": "كاليدونيا الجديدة",
		"ar-IQ": "كاليدونيا الجديدة",
		"ar-JO": "كاليدونيا الجديدة",
		"ar-LB": "كاليدونيا الجديدة",
		"ar-SY": "كاليدونيا الجديدة",
		"ar-PS": "كاليدونيا الجديدة",
		"en-US": "New Caledonia",
		"en-GB": "New Caledonia",
		"en-IE": "New Caledonia",
		"en-MT": "New Caledonia",
		"en-GI": "New Caledonia",
		"en-CY": "New Caledonia",
		"en-JE": "New Caledonia",
		"en-GG": "New Caledonia",
		"en-IM": "New Caledonia",
		"en-CA": "New Caledonia",
		"en-AU": "New Caledonia",
		"en-NZ": "New Caledonia",
		"en-ZA": "New Caledonia",
		"en-IN": "New Caledonia",
		"en-SG": "New Caledonia",
		"pt-AO": "Nova Caledónia",
		"pt-MZ": "Nova Caledónia",
		"pt-CV": "Nova Caledónia",
		"pt-GW": "Nova Caledónia",
		"pt-ST": "Nova Caledónia",
		"pt-TL": "Nova Caledónia",
		"pt-MO": "Nova Caledónia",
		"es-ES": "Nueva Caledonia",
		"es-419": "Nueva Caledonia",
		"es-AD": "Nueva Caledonia",
		"es-GI": "Nueva Caledonia",
		"es-AR": "Nueva Caledonia",
		"es-BO": "Nueva Caledonia",
		"es-BR": "Nueva Caledonia",
		"es-BZ": "Nueva Caledonia",
		"es-CL": "Nueva Caledonia",
		"es-CO": "Nueva Caledonia",
		"es-CR": "Nueva Caledonia",
		"es-CU": "Nueva Caledonia",
		"es-DO": "Nueva Caledonia",
		"es-EC": "Nueva Caledonia",
		"es-GT": "Nueva Caledonia",
		"es-HN": "Nueva Caledonia",
		"es-MX": "Nueva Caledonia",
		"es-NI": "Nueva Caledonia",
		"es-PA": "Nueva Caledonia",
		"es-PE": "Nueva Caledonia",
		"es-PR": "Nueva Caledonia",
		"es-PY": "Nueva Caledonia",
		"es-SV": "Nueva Caledonia",
		"es-US": "Nueva Caledonia",
		"es-UY": "Nueva Caledonia",
		"es-VE": "Nueva Caledonia",
		"fr-FR": "Nouvelle-Calédonie",
		"fr-BE": "Nouvelle-Calédonie",
		"fr-CH": "Nouvelle-Calédonie",
		"fr-LU": "Nouvelle-Calédonie",
		"fr-MC": "Nouvelle-Calédonie",
		"fr-AD": "Nouvelle-Calédonie",
		"fr-CA": "Nouvelle-Calédonie",
		"it-IT": "Nuova Caledonia",
		"it-CH": "Nuova Caledonia",
		"it-SM": "Nuova Caledonia",
		"it-VA": "Nuova Caledonia",
		"de-DE": "Neukaledonien",
		"de-AT": "Neukaledonien",
		"de-CH": "Neukaledonien",
		"de-BE": "Neukaledonien",
		"de-LI": "Neukaledonien",
		"de-LU": "Neukaledonien",
		"nl-NL": "Nieuw-Caledonië",
		"nl-BE": "Nieuw-Caledonië",
		"sv-SE": "Nya Kaledonien",
		"sv-FI": "Nya Kaledonien",
		"da-DK": "Ny Kaledonien",
		"nb-NO": "Ny-Caledonia",
		"nn-NO": "Ny-Caledonia",
		"fi-FI": "Uusi-Kaledonia",
		"is-IS": "Nýja-Kaledónía",
		"fo-FO": "Nýkaledónia",
		"et-EE": "Uus-Kaledoonia",
		"lv-LV": "Jaunkaledonija",
		"lt-LT": "Naujoji Kaledonija",
		"pl-PL": "Nowa Kaledonia",
		"cs-CZ": "Nová Kaledonie",
		"sk-SK": "Nová Kaledónia",
		"sl-SI": "Nova Kaledonija",
		"hr-HR": "Nova Kaledonija",
		"bs-BA": "Nova Kaledonija",
		"sr-RS": "Нова Каледонија",
		"sr-BA": "Нова Каледонија",
		"sr-ME": "Nova Kaledonija",
		"mk-MK": "Нова Каледонија",
		"bg-BG": "Нова Каледония",
		"be-BY": "Новая Каледонія",
		"uk-UA": "Нова Каледонія",
		"ru-RU": "Новая Каледония",
		"el-GR": "Νέα Καληδονία",
		"el-CY": "Νέα Καληδονία",
		"ro-RO": "Noua Caledonie",
		"ro-MD": "Noua Caledonie",
		"hu-HU": "Új-Kaledónia",
		"sq-AL": "Kaledoni e Re",
		"sq-XK": "Kaledoni e Re",
		"mt-MT": "New Caledonia",
		"ga-IE": "an Nua-Chaladóin",
		"cy-GB": "Caledonia Newydd",
		"gd-GB": "Cailleann Nuadh",
		"lb-LU": "Neikaledonien",
		"ca-ES": "Nova Caledònia",
		"ca-AD": "Nova Caledònia",
		"ca-FR": "Nova Caledònia",
		"ca-IT": "Nova Caledònia",
		"eu-ES": "Kaledonia Berria",
		"eu-FR": "Kaledonia Berria",
		"gl-ES": "Nova Caledonia",
		"tr-TR": "Yeni Kaledonya",
		"tr-CY": "Yeni Kaledonya"
	},
	"callingCode": "687",
	"phoneMasks": [
		{
			"mask": "##.##.##",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"[02-57-9]"
			]
		}
	]
} satisfies Country;
