import type { Country } from './types.js';

export const NFK = {
	"code": "NFK",
	"labels": {
		"pt-BR": "Ilha Norfolk",
		"pt-PT": "Ilha Norfolk",
		"qu-PE": "Isla Norfolk",
		"qu-BO": "Isla Norfolk",
		"qu-EC": "Isla Norfolk",
		"chr-US": "ᏃᎵᏬᎵᎩ ᎤᎦᏚᏛᎢ",
		"hi-IN": "नॉरफ़ॉक द्वीप",
		"bn-IN": "নরফোক দ্বীপ",
		"bn-BD": "নরফোক দ্বীপ",
		"ta-IN": "நார்ஃபோக் தீவு",
		"ta-LK": "நார்ஃபோக் தீவு",
		"ta-SG": "நார்ஃபோக் தீவு",
		"ta-MY": "நார்ஃபோக் தீவு",
		"te-IN": "నార్ఫోక్ దీవి",
		"mr-IN": "नॉरफॉक बेट",
		"gu-IN": "નોરફોક આઇલેન્ડ્સ",
		"kn-IN": "ನಾರ್ಫೋಕ್ ದ್ವೀಪ",
		"ml-IN": "നോർഫോക് ദ്വീപ്",
		"pa-IN": "ਨੋਰਫੌਕ ਟਾਪੂ",
		"ur-IN": "جزیرہ نارفوک",
		"ur-PK": "نارفوک آئلینڈ",
		"or-IN": "ନର୍ଫକ୍ ଦ୍ଵୀପ",
		"as-IN": "ন’ৰফ’ক দ্বীপ",
		"ne-IN": "नोरफोल्क टापु",
		"ne-NP": "नोरफोल्क टापु",
		"si-LK": "නෝෆෝක් දූපත",
		"kok-IN": "नॉरफॉक आयलँड",
		"ks-IN": "نارفاک جٔزیٖرٕ",
		"brx-IN": "नर्फ’क द्वीप",
		"mai-IN": "नौरफोक द्वीप",
		"dz-BT": "ནོར་ཕོལཀ་མཚོ་གླིང༌",
		"ja-JP": "ノーフォーク島",
		"ko-KR": "노퍽섬",
		"ko-KP": "노퍽섬",
		"zh-CN": "诺福克岛",
		"zh-Hans-CN": "诺福克岛",
		"zh-Hant-TW": "諾福克島",
		"zh-TW": "諾福克島",
		"zh-HK": "諾福克島",
		"zh-MO": "諾福克島",
		"zh-SG": "诺福克岛",
		"yue-Hant-HK": "諾福克島",
		"yue-Hans-CN": "诺福克岛",
		"mn-MN": "Норфолк арал",
		"ug-CN": "نورفولك ئارىلى",
		"th-TH": "เกาะนอร์ฟอล์ก",
		"lo-LA": "ເກາະນໍໂຟກ",
		"km-KH": "កោះ​ណ័រហ្វក់",
		"my-MM": "နောဖုတ်ကျွန်း",
		"vi-VN": "Đảo Norfolk",
		"id-ID": "Kepulauan Norfolk",
		"ms-MY": "Pulau Norfolk",
		"ms-SG": "Pulau Norfolk",
		"ms-BN": "Pulau Norfolk",
		"jv-ID": "Pulo Norfolk",
		"fil-PH": "Norfolk Island",
		"ceb-PH": "Norfolk Island",
		"ka-GE": "ნორფოლკის კუნძული",
		"hy-AM": "Նորֆոլկ կղզի",
		"az-AZ": "Norfolk adası",
		"az-Cyrl-AZ": "Норфолк адасы",
		"kk-KZ": "Норфолк аралы",
		"ky-KG": "Норфолк аралы",
		"uz-UZ": "Norfolk oroli",
		"tg-TJ": "Ҷазираи Норфолк",
		"tk-TM": "Norfolk adasy",
		"fa-IR": "جزیرهٔ نورفولک",
		"fa-AF": "جزیرهٔ نورفولک",
		"ps-AF": "نارفولک ټاپوګان",
		"ps-PK": "نارفولک ټاپوګان",
		"he-IL": "האי נורפוק",
		"ar-SA": "جزيرة نورفولك",
		"ar-AE": "جزيرة نورفولك",
		"ar-QA": "جزيرة نورفولك",
		"ar-BH": "جزيرة نورفولك",
		"ar-KW": "جزيرة نورفولك",
		"ar-OM": "جزيرة نورفولك",
		"ar-YE": "جزيرة نورفولك",
		"ar-IQ": "جزيرة نورفولك",
		"ar-JO": "جزيرة نورفولك",
		"ar-LB": "جزيرة نورفولك",
		"ar-SY": "جزيرة نورفولك",
		"ar-PS": "جزيرة نورفولك",
		"en-US": "Norfolk Island",
		"en-GB": "Norfolk Island",
		"en-IE": "Norfolk Island",
		"en-MT": "Norfolk Island",
		"en-GI": "Norfolk Island",
		"en-CY": "Norfolk Island",
		"en-JE": "Norfolk Island",
		"en-GG": "Norfolk Island",
		"en-IM": "Norfolk Island",
		"en-CA": "Norfolk Island",
		"en-AU": "Norfolk Island",
		"en-NZ": "Norfolk Island",
		"en-ZA": "Norfolk Island",
		"en-IN": "Norfolk Island",
		"en-SG": "Norfolk Island",
		"pt-AO": "Ilha Norfolk",
		"pt-MZ": "Ilha Norfolk",
		"pt-CV": "Ilha Norfolk",
		"pt-GW": "Ilha Norfolk",
		"pt-ST": "Ilha Norfolk",
		"pt-TL": "Ilha Norfolk",
		"pt-MO": "Ilha Norfolk",
		"es-ES": "Isla Norfolk",
		"es-419": "Isla Norfolk",
		"es-AD": "Isla Norfolk",
		"es-GI": "Isla Norfolk",
		"es-AR": "Isla Norfolk",
		"es-BO": "Isla Norfolk",
		"es-BR": "Isla Norfolk",
		"es-BZ": "Isla Norfolk",
		"es-CL": "Isla Norfolk",
		"es-CO": "Isla Norfolk",
		"es-CR": "Isla Norfolk",
		"es-CU": "Isla Norfolk",
		"es-DO": "Isla Norfolk",
		"es-EC": "Isla Norfolk",
		"es-GT": "Isla Norfolk",
		"es-HN": "Isla Norfolk",
		"es-MX": "Isla Norfolk",
		"es-NI": "Isla Norfolk",
		"es-PA": "Isla Norfolk",
		"es-PE": "Isla Norfolk",
		"es-PR": "Isla Norfolk",
		"es-PY": "Isla Norfolk",
		"es-SV": "Isla Norfolk",
		"es-US": "Isla Norfolk",
		"es-UY": "Isla Norfolk",
		"es-VE": "Isla Norfolk",
		"fr-FR": "Île Norfolk",
		"fr-BE": "Île Norfolk",
		"fr-CH": "Île Norfolk",
		"fr-LU": "Île Norfolk",
		"fr-MC": "Île Norfolk",
		"fr-AD": "Île Norfolk",
		"fr-CA": "île Norfolk",
		"it-IT": "Isola Norfolk",
		"it-CH": "Isola Norfolk",
		"it-SM": "Isola Norfolk",
		"it-VA": "Isola Norfolk",
		"de-DE": "Norfolkinsel",
		"de-AT": "Norfolkinsel",
		"de-CH": "Norfolkinsel",
		"de-BE": "Norfolkinsel",
		"de-LI": "Norfolkinsel",
		"de-LU": "Norfolkinsel",
		"nl-NL": "Norfolk",
		"nl-BE": "Norfolk",
		"sv-SE": "Norfolkön",
		"sv-FI": "Norfolkön",
		"da-DK": "Norfolk Island",
		"nb-NO": "Norfolkøya",
		"nn-NO": "Norfolkøya",
		"fi-FI": "Norfolkinsaari",
		"is-IS": "Norfolkeyja",
		"fo-FO": "Norfolksoyggj",
		"et-EE": "Norfolk",
		"lv-LV": "Norfolkas sala",
		"lt-LT": "Norfolko sala",
		"pl-PL": "Norfolk",
		"cs-CZ": "Norfolk",
		"sk-SK": "Norfolk",
		"sl-SI": "Norfolški otok",
		"hr-HR": "Otok Norfolk",
		"bs-BA": "Ostrvo Norfolk",
		"sr-RS": "Острво Норфок",
		"sr-BA": "острво Норфок",
		"sr-ME": "Ostrvo Norfok",
		"mk-MK": "Норфолшки Остров",
		"bg-BG": "остров Норфолк",
		"be-BY": "Востраў Норфалк",
		"uk-UA": "Острів Норфолк",
		"ru-RU": "о-в Норфолк",
		"el-GR": "Νήσος Νόρφολκ",
		"el-CY": "Νήσος Νόρφολκ",
		"ro-RO": "Insula Norfolk",
		"ro-MD": "Insula Norfolk",
		"hu-HU": "Norfolk-sziget",
		"sq-AL": "Ishulli Norfolk",
		"sq-XK": "Ishulli Norfolk",
		"mt-MT": "Gżira Norfolk",
		"ga-IE": "Oileán Norfolk",
		"cy-GB": "Ynys Norfolk",
		"gd-GB": "Eilean Norfolk",
		"lb-LU": "Norfolkinsel",
		"ca-ES": "Illa Norfolk",
		"ca-AD": "Illa Norfolk",
		"ca-FR": "Illa Norfolk",
		"ca-IT": "Illa Norfolk",
		"eu-ES": "Norfolk uhartea",
		"eu-FR": "Norfolk uhartea",
		"gl-ES": "Illa Norfolk",
		"tr-TR": "Norfolk Adası",
		"tr-CY": "Norfolk Adası"
	},
	"callingCode": "672",
	"phoneMasks": [
		{
			"mask": "# #####",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"[13]"
			]
		},
		{
			"mask": "## ####",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"1[0-3]"
			]
		}
	]
} satisfies Country;
