import type { Country } from './types.js';

export const NGA = {
	"code": "NGA",
	"labels": {
		"pt-BR": "Nigéria",
		"pt-PT": "Nigéria",
		"qu-PE": "Nigeria",
		"qu-BO": "Nigeria",
		"qu-EC": "Nigeria",
		"chr-US": "ᏂᏥᎵᏯ",
		"hi-IN": "नाइजीरिया",
		"bn-IN": "নাইজেরিয়া",
		"bn-BD": "নাইজেরিয়া",
		"ta-IN": "நைஜீரியா",
		"ta-LK": "நைஜீரியா",
		"ta-SG": "நைஜீரியா",
		"ta-MY": "நைஜீரியா",
		"te-IN": "నైజీరియా",
		"mr-IN": "नायजेरिया",
		"gu-IN": "નાઇજેરિયા",
		"kn-IN": "ನೈಜೀರಿಯಾ",
		"ml-IN": "നൈജീരിയ",
		"pa-IN": "ਨਾਈਜੀਰੀਆ",
		"ur-IN": "نائجیریا",
		"ur-PK": "نائجیریا",
		"or-IN": "ନାଇଜେରିଆ",
		"as-IN": "নাইজেৰিয়া",
		"ne-IN": "नाइजेरिया",
		"ne-NP": "नाइजेरिया",
		"si-LK": "නයිජීරියාව",
		"kok-IN": "नायजेरिया",
		"ks-IN": "نایجیرِیا",
		"brx-IN": "नाइजेरिया",
		"mai-IN": "नाइजीरिया",
		"dz-BT": "ནཱའི་ཇི་རི་ཡ",
		"ja-JP": "ナイジェリア",
		"ko-KR": "나이지리아",
		"ko-KP": "나이지리아",
		"zh-CN": "尼日利亚",
		"zh-Hans-CN": "尼日利亚",
		"zh-Hant-TW": "奈及利亞",
		"zh-TW": "奈及利亞",
		"zh-HK": "尼日利亞",
		"zh-MO": "尼日利亞",
		"zh-SG": "尼日利亚",
		"yue-Hant-HK": "奈及利亞",
		"yue-Hans-CN": "奈及利亚",
		"mn-MN": "Нигери",
		"ug-CN": "نىگېرىيە",
		"th-TH": "ไนจีเรีย",
		"lo-LA": "ໄນຈີເຣຍ",
		"km-KH": "នីហ្សេរីយ៉ា",
		"my-MM": "နိုင်ဂျီးရီးယား",
		"vi-VN": "Nigeria",
		"id-ID": "Nigeria",
		"ms-MY": "Nigeria",
		"ms-SG": "Nigeria",
		"ms-BN": "Nigeria",
		"jv-ID": "Nigéria",
		"fil-PH": "Nigeria",
		"ceb-PH": "Nigeria",
		"ka-GE": "ნიგერია",
		"hy-AM": "Նիգերիա",
		"az-AZ": "Nigeriya",
		"az-Cyrl-AZ": "Ниҝерија",
		"kk-KZ": "Нигерия",
		"ky-KG": "Нигерия",
		"uz-UZ": "Nigeriya",
		"tg-TJ": "Нигерия",
		"tk-TM": "Nigeriýa",
		"fa-IR": "نیجریه",
		"fa-AF": "نیجریا",
		"ps-AF": "نایجیریا",
		"ps-PK": "نایجیریا",
		"he-IL": "ניגריה",
		"ar-SA": "نيجيريا",
		"ar-AE": "نيجيريا",
		"ar-QA": "نيجيريا",
		"ar-BH": "نيجيريا",
		"ar-KW": "نيجيريا",
		"ar-OM": "نيجيريا",
		"ar-YE": "نيجيريا",
		"ar-IQ": "نيجيريا",
		"ar-JO": "نيجيريا",
		"ar-LB": "نيجيريا",
		"ar-SY": "نيجيريا",
		"ar-PS": "نيجيريا",
		"en-US": "Nigeria",
		"en-GB": "Nigeria",
		"en-IE": "Nigeria",
		"en-MT": "Nigeria",
		"en-GI": "Nigeria",
		"en-CY": "Nigeria",
		"en-JE": "Nigeria",
		"en-GG": "Nigeria",
		"en-IM": "Nigeria",
		"en-CA": "Nigeria",
		"en-AU": "Nigeria",
		"en-NZ": "Nigeria",
		"en-ZA": "Nigeria",
		"en-IN": "Nigeria",
		"en-SG": "Nigeria",
		"pt-AO": "Nigéria",
		"pt-MZ": "Nigéria",
		"pt-CV": "Nigéria",
		"pt-GW": "Nigéria",
		"pt-ST": "Nigéria",
		"pt-TL": "Nigéria",
		"pt-MO": "Nigéria",
		"es-ES": "Nigeria",
		"es-419": "Nigeria",
		"es-AD": "Nigeria",
		"es-GI": "Nigeria",
		"es-AR": "Nigeria",
		"es-BO": "Nigeria",
		"es-BR": "Nigeria",
		"es-BZ": "Nigeria",
		"es-CL": "Nigeria",
		"es-CO": "Nigeria",
		"es-CR": "Nigeria",
		"es-CU": "Nigeria",
		"es-DO": "Nigeria",
		"es-EC": "Nigeria",
		"es-GT": "Nigeria",
		"es-HN": "Nigeria",
		"es-MX": "Nigeria",
		"es-NI": "Nigeria",
		"es-PA": "Nigeria",
		"es-PE": "Nigeria",
		"es-PR": "Nigeria",
		"es-PY": "Nigeria",
		"es-SV": "Nigeria",
		"es-US": "Nigeria",
		"es-UY": "Nigeria",
		"es-VE": "Nigeria",
		"fr-FR": "Nigeria",
		"fr-BE": "Nigeria",
		"fr-CH": "Nigeria",
		"fr-LU": "Nigeria",
		"fr-MC": "Nigeria",
		"fr-AD": "Nigeria",
		"fr-CA": "Nigéria",
		"it-IT": "Nigeria",
		"it-CH": "Nigeria",
		"it-SM": "Nigeria",
		"it-VA": "Nigeria",
		"de-DE": "Nigeria",
		"de-AT": "Nigeria",
		"de-CH": "Nigeria",
		"de-BE": "Nigeria",
		"de-LI": "Nigeria",
		"de-LU": "Nigeria",
		"nl-NL": "Nigeria",
		"nl-BE": "Nigeria",
		"sv-SE": "Nigeria",
		"sv-FI": "Nigeria",
		"da-DK": "Nigeria",
		"nb-NO": "Nigeria",
		"nn-NO": "Nigeria",
		"fi-FI": "Nigeria",
		"is-IS": "Nígería",
		"fo-FO": "Nigeria",
		"et-EE": "Nigeeria",
		"lv-LV": "Nigērija",
		"lt-LT": "Nigerija",
		"pl-PL": "Nigeria",
		"cs-CZ": "Nigérie",
		"sk-SK": "Nigéria",
		"sl-SI": "Nigerija",
		"hr-HR": "Nigerija",
		"bs-BA": "Nigerija",
		"sr-RS": "Нигерија",
		"sr-BA": "Нигерија",
		"sr-ME": "Nigerija",
		"mk-MK": "Нигерија",
		"bg-BG": "Нигерия",
		"be-BY": "Нігерыя",
		"uk-UA": "Нігерія",
		"ru-RU": "Нигерия",
		"el-GR": "Νιγηρία",
		"el-CY": "Νιγηρία",
		"ro-RO": "Nigeria",
		"ro-MD": "Nigeria",
		"hu-HU": "Nigéria",
		"sq-AL": "Nigeri",
		"sq-XK": "Nigeri",
		"mt-MT": "in-Niġerja",
		"ga-IE": "An Nigéir",
		"cy-GB": "Nigeria",
		"gd-GB": "Nigèiria",
		"lb-LU": "Nigeria",
		"ca-ES": "Nigèria",
		"ca-AD": "Nigèria",
		"ca-FR": "Nigèria",
		"ca-IT": "Nigèria",
		"eu-ES": "Nigeria",
		"eu-FR": "Nigeria",
		"gl-ES": "Nixeria",
		"tr-TR": "Nijerya",
		"tr-CY": "Nijerya"
	},
	"callingCode": "234",
	"phoneMasks": [
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"3"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[7-9]"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"20[129]"
			]
		},
		{
			"mask": "#### ## ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11
		},
		{
			"mask": "### #### #####",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"[78]"
			]
		},
		{
			"mask": "# ### ### ### ###",
			"minLength": 13,
			"maxLength": 13
		},
		{
			"mask": "### ##### ######",
			"minLength": 14,
			"maxLength": 14,
			"leadingDigits": [
				"[78]"
			]
		}
	]
} satisfies Country;
