import type { Country } from './types.js';

export const NZL = {
	"code": "NZL",
	"labels": {
		"pt-BR": "Nova Zelândia",
		"pt-PT": "Nova Zelândia",
		"qu-PE": "Nueva Zelanda",
		"qu-BO": "Nueva Zelanda",
		"qu-EC": "Nueva Zelanda",
		"chr-US": "ᎢᏤ ᏏᎢᎴᏂᏗ",
		"hi-IN": "न्यूज़ीलैंड",
		"bn-IN": "নিউজিল্যান্ড",
		"bn-BD": "নিউজিল্যান্ড",
		"ta-IN": "நியூசிலாந்து",
		"ta-LK": "நியூசிலாந்து",
		"ta-SG": "நியூசிலாந்து",
		"ta-MY": "நியூசிலாந்து",
		"te-IN": "న్యూజిలాండ్",
		"mr-IN": "न्यूझीलंड",
		"gu-IN": "ન્યુઝીલેન્ડ",
		"kn-IN": "ನ್ಯೂಜಿಲೆಂಡ್",
		"ml-IN": "ന്യൂസിലൻഡ്",
		"pa-IN": "ਨਿਊਜ਼ੀਲੈਂਡ",
		"ur-IN": "نیوزی لینڈ",
		"ur-PK": "نیوزی لینڈ",
		"or-IN": "ନ୍ୟୁଜିଲାଣ୍ଡ",
		"as-IN": "নিউজিলেণ্ড",
		"ne-IN": "न्युजिल्याण्ड",
		"ne-NP": "न्युजिल्याण्ड",
		"si-LK": "නවසීලන්තය",
		"kok-IN": "न्युझीलॅन्ड",
		"ks-IN": "نیوزی لینڈ",
		"brx-IN": "न्यूजीलेण्ड",
		"mai-IN": "न्यूजीलैंड",
		"dz-BT": "ནིའུ་ཛི་ལེནཌ",
		"ja-JP": "ニュージーランド",
		"ko-KR": "뉴질랜드",
		"ko-KP": "뉴질랜드",
		"zh-CN": "新西兰",
		"zh-Hans-CN": "新西兰",
		"zh-Hant-TW": "紐西蘭",
		"zh-TW": "紐西蘭",
		"zh-HK": "紐西蘭",
		"zh-MO": "紐西蘭",
		"zh-SG": "新西兰",
		"yue-Hant-HK": "新西蘭",
		"yue-Hans-CN": "纽西兰",
		"mn-MN": "Шинэ Зеланд",
		"ug-CN": "يېڭى زېلاندىيە",
		"th-TH": "นิวซีแลนด์",
		"lo-LA": "ນິວຊີແລນ",
		"km-KH": "នូវែល​សេឡង់",
		"my-MM": "နယူးဇီလန်",
		"vi-VN": "New Zealand",
		"id-ID": "Selandia Baru",
		"ms-MY": "New Zealand",
		"ms-SG": "New Zealand",
		"ms-BN": "New Zealand",
		"jv-ID": "Selandia Anyar",
		"fil-PH": "New Zealand",
		"ceb-PH": "New Zealand",
		"ka-GE": "ახალი ზელანდია",
		"hy-AM": "Նոր Զելանդիա",
		"az-AZ": "Yeni Zelandiya",
		"az-Cyrl-AZ": "Јени Зеландија",
		"kk-KZ": "Жаңа Зеландия",
		"ky-KG": "Жаңы Зеландия",
		"uz-UZ": "Yangi Zelandiya",
		"tg-TJ": "Зеландияи Нав",
		"tk-TM": "Täze Zelandiýa",
		"fa-IR": "نیوزیلند",
		"fa-AF": "زیلاند جدید",
		"ps-AF": "نیوزیلنډ",
		"ps-PK": "نیوزیلنډ",
		"he-IL": "ניו זילנד",
		"ar-SA": "نيوزيلندا",
		"ar-AE": "نيوزيلندا",
		"ar-QA": "نيوزيلندا",
		"ar-BH": "نيوزيلندا",
		"ar-KW": "نيوزيلندا",
		"ar-OM": "نيوزيلندا",
		"ar-YE": "نيوزيلندا",
		"ar-IQ": "نيوزيلندا",
		"ar-JO": "نيوزيلندا",
		"ar-LB": "نيوزيلندا",
		"ar-SY": "نيوزيلندا",
		"ar-PS": "نيوزيلندا",
		"en-US": "New Zealand",
		"en-GB": "New Zealand",
		"en-IE": "New Zealand",
		"en-MT": "New Zealand",
		"en-GI": "New Zealand",
		"en-CY": "New Zealand",
		"en-JE": "New Zealand",
		"en-GG": "New Zealand",
		"en-IM": "New Zealand",
		"en-CA": "New Zealand",
		"en-AU": "New Zealand",
		"en-NZ": "New Zealand",
		"en-ZA": "New Zealand",
		"en-IN": "New Zealand",
		"en-SG": "New Zealand",
		"pt-AO": "Nova Zelândia",
		"pt-MZ": "Nova Zelândia",
		"pt-CV": "Nova Zelândia",
		"pt-GW": "Nova Zelândia",
		"pt-ST": "Nova Zelândia",
		"pt-TL": "Nova Zelândia",
		"pt-MO": "Nova Zelândia",
		"es-ES": "Nueva Zelanda",
		"es-419": "Nueva Zelanda",
		"es-AD": "Nueva Zelanda",
		"es-GI": "Nueva Zelanda",
		"es-AR": "Nueva Zelanda",
		"es-BO": "Nueva Zelanda",
		"es-BR": "Nueva Zelanda",
		"es-BZ": "Nueva Zelanda",
		"es-CL": "Nueva Zelanda",
		"es-CO": "Nueva Zelanda",
		"es-CR": "Nueva Zelanda",
		"es-CU": "Nueva Zelanda",
		"es-DO": "Nueva Zelanda",
		"es-EC": "Nueva Zelanda",
		"es-GT": "Nueva Zelanda",
		"es-HN": "Nueva Zelanda",
		"es-MX": "Nueva Zelanda",
		"es-NI": "Nueva Zelanda",
		"es-PA": "Nueva Zelanda",
		"es-PE": "Nueva Zelanda",
		"es-PR": "Nueva Zelanda",
		"es-PY": "Nueva Zelanda",
		"es-SV": "Nueva Zelanda",
		"es-US": "Nueva Zelanda",
		"es-UY": "Nueva Zelanda",
		"es-VE": "Nueva Zelanda",
		"fr-FR": "Nouvelle-Zélande",
		"fr-BE": "Nouvelle-Zélande",
		"fr-CH": "Nouvelle-Zélande",
		"fr-LU": "Nouvelle-Zélande",
		"fr-MC": "Nouvelle-Zélande",
		"fr-AD": "Nouvelle-Zélande",
		"fr-CA": "Nouvelle-Zélande",
		"it-IT": "Nuova Zelanda",
		"it-CH": "Nuova Zelanda",
		"it-SM": "Nuova Zelanda",
		"it-VA": "Nuova Zelanda",
		"de-DE": "Neuseeland",
		"de-AT": "Neuseeland",
		"de-CH": "Neuseeland",
		"de-BE": "Neuseeland",
		"de-LI": "Neuseeland",
		"de-LU": "Neuseeland",
		"nl-NL": "Nieuw-Zeeland",
		"nl-BE": "Nieuw-Zeeland",
		"sv-SE": "Nya Zeeland",
		"sv-FI": "Nya Zeeland",
		"da-DK": "New Zealand",
		"nb-NO": "New Zealand",
		"nn-NO": "New Zealand",
		"fi-FI": "Uusi-Seelanti",
		"is-IS": "Nýja-Sjáland",
		"fo-FO": "Nýsæland",
		"et-EE": "Uus-Meremaa",
		"lv-LV": "Jaunzēlande",
		"lt-LT": "Naujoji Zelandija",
		"pl-PL": "Nowa Zelandia",
		"cs-CZ": "Nový Zéland",
		"sk-SK": "Nový Zéland",
		"sl-SI": "Nova Zelandija",
		"hr-HR": "Novi Zeland",
		"bs-BA": "Novi Zeland",
		"sr-RS": "Нови Зеланд",
		"sr-BA": "Нови Зеланд",
		"sr-ME": "Novi Zeland",
		"mk-MK": "Нов Зеланд",
		"bg-BG": "Нова Зеландия",
		"be-BY": "Новая Зеландыя",
		"uk-UA": "Нова Зеландія",
		"ru-RU": "Новая Зеландия",
		"el-GR": "Νέα Ζηλανδία",
		"el-CY": "Νέα Ζηλανδία",
		"ro-RO": "Noua Zeelandă",
		"ro-MD": "Noua Zeelandă",
		"hu-HU": "Új-Zéland",
		"sq-AL": "Zelandë e Re",
		"sq-XK": "Zelandë e Re",
		"mt-MT": "New Zealand",
		"ga-IE": "an Nua-Shéalainn",
		"cy-GB": "Seland Newydd",
		"gd-GB": "Sealainn Nuadh",
		"lb-LU": "Neiséiland",
		"ca-ES": "Nova Zelanda",
		"ca-AD": "Nova Zelanda",
		"ca-FR": "Nova Zelanda",
		"ca-IT": "Nova Zelanda",
		"eu-ES": "Zeelanda Berria",
		"eu-FR": "Zeelanda Berria",
		"gl-ES": "Nova Zelandia",
		"tr-TR": "Yeni Zelanda",
		"tr-CY": "Yeni Zelanda"
	},
	"callingCode": "64",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"24|[346]|7[2-57-9]|9[2-9]"
			]
		},
		{
			"mask": "### ## ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"50[036-8]|8|90",
				"50(?:[0367]|88)|8|90"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		},
		{
			"mask": "## ### #####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2(?:[169]|7[0-35-9])|7"
			]
		},
		{
			"mask": "## #### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1|2[028]"
			]
		},
		{
			"mask": "## ########",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8[1-79]"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2(?:10|74)|[589]"
			]
		}
	]
} satisfies Country;
