import type { Country } from './types.js';

export const OMN = {
	"code": "OMN",
	"labels": {
		"pt-BR": "Omã",
		"pt-PT": "Omã",
		"qu-PE": "Omán",
		"qu-BO": "Omán",
		"qu-EC": "Omán",
		"chr-US": "ᎣᎺᏂ",
		"hi-IN": "ओमान",
		"bn-IN": "ওমান",
		"bn-BD": "ওমান",
		"ta-IN": "ஓமன்",
		"ta-LK": "ஓமன்",
		"ta-SG": "ஓமன்",
		"ta-MY": "ஓமன்",
		"te-IN": "ఓమన్",
		"mr-IN": "ओमान",
		"gu-IN": "ઓમાન",
		"kn-IN": "ಓಮನ್",
		"ml-IN": "ഒമാൻ",
		"pa-IN": "ਓਮਾਨ",
		"ur-IN": "عمان",
		"ur-PK": "عمان",
		"or-IN": "ଓମାନ୍",
		"as-IN": "ওমান",
		"ne-IN": "ओमन",
		"ne-NP": "ओमन",
		"si-LK": "ඕමානය",
		"kok-IN": "ओमान",
		"ks-IN": "اومان",
		"brx-IN": "ओमान",
		"mai-IN": "ओमान",
		"dz-BT": "ཨོ་མཱན",
		"ja-JP": "オマーン",
		"ko-KR": "오만",
		"ko-KP": "오만",
		"zh-CN": "阿曼",
		"zh-Hans-CN": "阿曼",
		"zh-Hant-TW": "阿曼",
		"zh-TW": "阿曼",
		"zh-HK": "阿曼",
		"zh-MO": "阿曼",
		"zh-SG": "阿曼",
		"yue-Hant-HK": "阿曼王國",
		"yue-Hans-CN": "阿曼王国",
		"mn-MN": "Оман",
		"ug-CN": "ئومان",
		"th-TH": "โอมาน",
		"lo-LA": "ໂອມານ",
		"km-KH": "អូម៉ង់",
		"my-MM": "အိုမန်",
		"vi-VN": "Oman",
		"id-ID": "Oman",
		"ms-MY": "Oman",
		"ms-SG": "Oman",
		"ms-BN": "Oman",
		"jv-ID": "Oman",
		"fil-PH": "Oman",
		"ceb-PH": "Oman",
		"ka-GE": "ომანი",
		"hy-AM": "Օման",
		"az-AZ": "Oman",
		"az-Cyrl-AZ": "Оман",
		"kk-KZ": "Оман",
		"ky-KG": "Оман",
		"uz-UZ": "Ummon",
		"tg-TJ": "Умон",
		"tk-TM": "Oman",
		"fa-IR": "عمان",
		"fa-AF": "عمان",
		"ps-AF": "عمان",
		"ps-PK": "عمان",
		"he-IL": "עומאן",
		"ar-SA": "عُمان",
		"ar-AE": "عُمان",
		"ar-QA": "عُمان",
		"ar-BH": "عُمان",
		"ar-KW": "عُمان",
		"ar-OM": "عُمان",
		"ar-YE": "عُمان",
		"ar-IQ": "عُمان",
		"ar-JO": "عُمان",
		"ar-LB": "عُمان",
		"ar-SY": "عُمان",
		"ar-PS": "عُمان",
		"en-US": "Oman",
		"en-GB": "Oman",
		"en-IE": "Oman",
		"en-MT": "Oman",
		"en-GI": "Oman",
		"en-CY": "Oman",
		"en-JE": "Oman",
		"en-GG": "Oman",
		"en-IM": "Oman",
		"en-CA": "Oman",
		"en-AU": "Oman",
		"en-NZ": "Oman",
		"en-ZA": "Oman",
		"en-IN": "Oman",
		"en-SG": "Oman",
		"pt-AO": "Omã",
		"pt-MZ": "Omã",
		"pt-CV": "Omã",
		"pt-GW": "Omã",
		"pt-ST": "Omã",
		"pt-TL": "Omã",
		"pt-MO": "Omã",
		"es-ES": "Omán",
		"es-419": "Omán",
		"es-AD": "Omán",
		"es-GI": "Omán",
		"es-AR": "Omán",
		"es-BO": "Omán",
		"es-BR": "Omán",
		"es-BZ": "Omán",
		"es-CL": "Omán",
		"es-CO": "Omán",
		"es-CR": "Omán",
		"es-CU": "Omán",
		"es-DO": "Omán",
		"es-EC": "Omán",
		"es-GT": "Omán",
		"es-HN": "Omán",
		"es-MX": "Omán",
		"es-NI": "Omán",
		"es-PA": "Omán",
		"es-PE": "Omán",
		"es-PR": "Omán",
		"es-PY": "Omán",
		"es-SV": "Omán",
		"es-US": "Omán",
		"es-UY": "Omán",
		"es-VE": "Omán",
		"fr-FR": "Oman",
		"fr-BE": "Oman",
		"fr-CH": "Oman",
		"fr-LU": "Oman",
		"fr-MC": "Oman",
		"fr-AD": "Oman",
		"fr-CA": "Oman",
		"it-IT": "Oman",
		"it-CH": "Oman",
		"it-SM": "Oman",
		"it-VA": "Oman",
		"de-DE": "Oman",
		"de-AT": "Oman",
		"de-CH": "Oman",
		"de-BE": "Oman",
		"de-LI": "Oman",
		"de-LU": "Oman",
		"nl-NL": "Oman",
		"nl-BE": "Oman",
		"sv-SE": "Oman",
		"sv-FI": "Oman",
		"da-DK": "Oman",
		"nb-NO": "Oman",
		"nn-NO": "Oman",
		"fi-FI": "Oman",
		"is-IS": "Óman",
		"fo-FO": "Oman",
		"et-EE": "Omaan",
		"lv-LV": "Omāna",
		"lt-LT": "Omanas",
		"pl-PL": "Oman",
		"cs-CZ": "Omán",
		"sk-SK": "Omán",
		"sl-SI": "Oman",
		"hr-HR": "Oman",
		"bs-BA": "Oman",
		"sr-RS": "Оман",
		"sr-BA": "Оман",
		"sr-ME": "Oman",
		"mk-MK": "Оман",
		"bg-BG": "Оман",
		"be-BY": "Аман",
		"uk-UA": "Оман",
		"ru-RU": "Оман",
		"el-GR": "Ομάν",
		"el-CY": "Ομάν",
		"ro-RO": "Oman",
		"ro-MD": "Oman",
		"hu-HU": "Omán",
		"sq-AL": "Oman",
		"sq-XK": "Oman",
		"mt-MT": "l-Oman",
		"ga-IE": "Óman",
		"cy-GB": "Oman",
		"gd-GB": "Omàn",
		"lb-LU": "Oman",
		"ca-ES": "Oman",
		"ca-AD": "Oman",
		"ca-FR": "Oman",
		"ca-IT": "Oman",
		"eu-ES": "Oman",
		"eu-FR": "Oman",
		"gl-ES": "Omán",
		"tr-TR": "Umman",
		"tr-CY": "Umman"
	},
	"callingCode": "968",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "## ######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[179]"
			]
		},
		{
			"mask": "### ######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[58]"
			]
		}
	]
} satisfies Country;
