import type { Country } from './types.js';

export const PAK = {
	"code": "PAK",
	"labels": {
		"pt-BR": "Paquistão",
		"pt-PT": "Paquistão",
		"qu-PE": "Pakistán",
		"qu-BO": "Pakistán",
		"qu-EC": "Pakistán",
		"chr-US": "ᏆᎩᏍᏖᏂ",
		"hi-IN": "पाकिस्तान",
		"bn-IN": "পাকিস্তান",
		"bn-BD": "পাকিস্তান",
		"ta-IN": "பாகிஸ்தான்",
		"ta-LK": "பாகிஸ்தான்",
		"ta-SG": "பாகிஸ்தான்",
		"ta-MY": "பாகிஸ்தான்",
		"te-IN": "పాకిస్తాన్",
		"mr-IN": "पाकिस्तान",
		"gu-IN": "પાકિસ્તાન",
		"kn-IN": "ಪಾಕಿಸ್ತಾನ",
		"ml-IN": "പാക്കിസ്ഥാൻ",
		"pa-IN": "ਪਾਕਿਸਤਾਨ",
		"ur-IN": "پاکستان",
		"ur-PK": "پاکستان",
		"or-IN": "ପାକିସ୍ତାନ",
		"as-IN": "পাকিস্তান",
		"ne-IN": "पाकिस्तान",
		"ne-NP": "पाकिस्तान",
		"si-LK": "පාකිස්තානය",
		"kok-IN": "पाकिस्तान",
		"sd-IN": "पाकिस्तान",
		"ks-IN": "پاکِستان",
		"brx-IN": "पाकिस्तान",
		"mai-IN": "पाकिस्तान",
		"dz-BT": "པ་ཀི་སཏཱན",
		"ja-JP": "パキスタン",
		"ko-KR": "파키스탄",
		"ko-KP": "파키스탄",
		"zh-CN": "巴基斯坦",
		"zh-Hans-CN": "巴基斯坦",
		"zh-Hant-TW": "巴基斯坦",
		"zh-TW": "巴基斯坦",
		"zh-HK": "巴基斯坦",
		"zh-MO": "巴基斯坦",
		"zh-SG": "巴基斯坦",
		"yue-Hant-HK": "巴基斯坦",
		"yue-Hans-CN": "巴基斯坦",
		"mn-MN": "Пакистан",
		"ug-CN": "پاكىستان",
		"th-TH": "ปากีสถาน",
		"lo-LA": "ປາກິດສະຖານ",
		"km-KH": "ប៉ាគីស្ថាន",
		"my-MM": "ပါကစ္စတန်",
		"vi-VN": "Pakistan",
		"id-ID": "Pakistan",
		"ms-MY": "Pakistan",
		"ms-SG": "Pakistan",
		"ms-BN": "Pakistan",
		"jv-ID": "Pakistan",
		"fil-PH": "Pakistan",
		"ceb-PH": "Pakistan",
		"ka-GE": "პაკისტანი",
		"hy-AM": "Պակիստան",
		"az-AZ": "Pakistan",
		"az-Cyrl-AZ": "Пакистан",
		"kk-KZ": "Пәкістан",
		"ky-KG": "Пакистан",
		"uz-UZ": "Pokiston",
		"tg-TJ": "Покистон",
		"tk-TM": "Pakistan",
		"fa-IR": "پاکستان",
		"fa-AF": "پاکستان",
		"ps-AF": "پاکستان",
		"ps-PK": "پاکستان",
		"he-IL": "פקיסטן",
		"ar-SA": "باكستان",
		"ar-AE": "باكستان",
		"ar-QA": "باكستان",
		"ar-BH": "باكستان",
		"ar-KW": "باكستان",
		"ar-OM": "باكستان",
		"ar-YE": "باكستان",
		"ar-IQ": "باكستان",
		"ar-JO": "باكستان",
		"ar-LB": "باكستان",
		"ar-SY": "باكستان",
		"ar-PS": "باكستان",
		"en-US": "Pakistan",
		"en-GB": "Pakistan",
		"en-IE": "Pakistan",
		"en-MT": "Pakistan",
		"en-GI": "Pakistan",
		"en-CY": "Pakistan",
		"en-JE": "Pakistan",
		"en-GG": "Pakistan",
		"en-IM": "Pakistan",
		"en-CA": "Pakistan",
		"en-AU": "Pakistan",
		"en-NZ": "Pakistan",
		"en-ZA": "Pakistan",
		"en-IN": "Pakistan",
		"en-SG": "Pakistan",
		"pt-AO": "Paquistão",
		"pt-MZ": "Paquistão",
		"pt-CV": "Paquistão",
		"pt-GW": "Paquistão",
		"pt-ST": "Paquistão",
		"pt-TL": "Paquistão",
		"pt-MO": "Paquistão",
		"es-ES": "Pakistán",
		"es-419": "Pakistán",
		"es-AD": "Pakistán",
		"es-GI": "Pakistán",
		"es-AR": "Pakistán",
		"es-BO": "Pakistán",
		"es-BR": "Pakistán",
		"es-BZ": "Pakistán",
		"es-CL": "Pakistán",
		"es-CO": "Pakistán",
		"es-CR": "Pakistán",
		"es-CU": "Pakistán",
		"es-DO": "Pakistán",
		"es-EC": "Pakistán",
		"es-GT": "Pakistán",
		"es-HN": "Pakistán",
		"es-MX": "Pakistán",
		"es-NI": "Pakistán",
		"es-PA": "Pakistán",
		"es-PE": "Pakistán",
		"es-PR": "Pakistán",
		"es-PY": "Pakistán",
		"es-SV": "Pakistán",
		"es-US": "Pakistán",
		"es-UY": "Pakistán",
		"es-VE": "Pakistán",
		"fr-FR": "Pakistan",
		"fr-BE": "Pakistan",
		"fr-CH": "Pakistan",
		"fr-LU": "Pakistan",
		"fr-MC": "Pakistan",
		"fr-AD": "Pakistan",
		"fr-CA": "Pakistan",
		"it-IT": "Pakistan",
		"it-CH": "Pakistan",
		"it-SM": "Pakistan",
		"it-VA": "Pakistan",
		"de-DE": "Pakistan",
		"de-AT": "Pakistan",
		"de-CH": "Pakistan",
		"de-BE": "Pakistan",
		"de-LI": "Pakistan",
		"de-LU": "Pakistan",
		"nl-NL": "Pakistan",
		"nl-BE": "Pakistan",
		"sv-SE": "Pakistan",
		"sv-FI": "Pakistan",
		"da-DK": "Pakistan",
		"nb-NO": "Pakistan",
		"nn-NO": "Pakistan",
		"fi-FI": "Pakistan",
		"is-IS": "Pakistan",
		"fo-FO": "Pakistan",
		"et-EE": "Pakistan",
		"lv-LV": "Pakistāna",
		"lt-LT": "Pakistanas",
		"pl-PL": "Pakistan",
		"cs-CZ": "Pákistán",
		"sk-SK": "Pakistan",
		"sl-SI": "Pakistan",
		"hr-HR": "Pakistan",
		"bs-BA": "Pakistan",
		"sr-RS": "Пакистан",
		"sr-BA": "Пакистан",
		"sr-ME": "Pakistan",
		"mk-MK": "Пакистан",
		"bg-BG": "Пакистан",
		"be-BY": "Пакістан",
		"uk-UA": "Пакистан",
		"ru-RU": "Пакистан",
		"el-GR": "Πακιστάν",
		"el-CY": "Πακιστάν",
		"ro-RO": "Pakistan",
		"ro-MD": "Pakistan",
		"hu-HU": "Pakisztán",
		"sq-AL": "Pakistan",
		"sq-XK": "Pakistan",
		"mt-MT": "il-Pakistan",
		"ga-IE": "an Phacastáin",
		"cy-GB": "Pakistan",
		"gd-GB": "Pagastàn",
		"lb-LU": "Pakistan",
		"ca-ES": "Pakistan",
		"ca-AD": "Pakistan",
		"ca-FR": "Pakistan",
		"ca-IT": "Pakistan",
		"eu-ES": "Pakistan",
		"eu-FR": "Pakistan",
		"gl-ES": "Paquistán",
		"tr-TR": "Pakistan",
		"tr-CY": "Pakistan"
	},
	"callingCode": "92",
	"phoneMasks": [
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "#### #####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "## ########",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"(?:2[125]|4[0-246-9]|5[1-35-7]|6[1-8]|7[14]|8[16]|91)[2-9]"
			]
		},
		{
			"mask": "### #######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2(?:3[2358]|4[2-4]|9[2-8])|45[3479]|54[2-467]|60[468]|72[236]|8(?:2[2-689]|3[23578]|4[3478]|5[2356])|9(?:2[2-8]|3[27-9]|4[2-6]|6[3569]|9[25-8])",
				"9(?:2[3-8]|98)|(?:2(?:3[2358]|4[2-4]|9[2-8])|45[3479]|54[2-467]|60[468]|72[236]|8(?:2[2-689]|3[23578]|4[3478]|5[2356])|9(?:22|3[27-9]|4[2-6]|6[3569]|9[25-7]))[2-9]"
			]
		},
		{
			"mask": "### #######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"3"
			]
		},
		{
			"mask": "##### #####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"58"
			]
		},
		{
			"mask": "## ### ### ###",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"2[125]|4[0-246-9]|5[1-35-7]|6[1-8]|7[14]|8[16]|91"
			]
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"[24-9]"
			]
		},
		{
			"mask": "### ### #######",
			"minLength": 13,
			"maxLength": 13,
			"leadingDigits": [
				"[89]0"
			]
		}
	]
} satisfies Country;
