import type { Country } from './types.js';

export const PCN = {
	"code": "PCN",
	"labels": {
		"pt-BR": "Ilhas Pitcairn",
		"pt-PT": "Ilhas Pitcairn",
		"qu-PE": "Islas Pitcairn",
		"qu-BO": "Islas Pitcairn",
		"qu-EC": "Islas Pitcairn",
		"chr-US": "ᏈᎧᎵᏂ ᏚᎦᏚᏛᎢ",
		"hi-IN": "पिटकैर्न द्वीपसमूह",
		"bn-IN": "পিটকেয়ার্ন দ্বীপপুঞ্জ",
		"bn-BD": "পিটকেয়ার্ন দ্বীপপুঞ্জ",
		"ta-IN": "பிட்கெய்ர்ன் தீவுகள்",
		"ta-LK": "பிட்கெய்ர்ன் தீவுகள்",
		"ta-SG": "பிட்கெய்ர்ன் தீவுகள்",
		"ta-MY": "பிட்கெய்ர்ன் தீவுகள்",
		"te-IN": "పిట్‌కెయిర్న్ దీవులు",
		"mr-IN": "पिटकैर्न बेटे",
		"gu-IN": "પીટકૈર્ન આઇલેન્ડ્સ",
		"kn-IN": "ಪಿಟ್‌ಕೈರ್ನ್ ದ್ವೀಪಗಳು",
		"ml-IN": "പിറ്റ്‌കെയ്‌ൻ ദ്വീപുകൾ",
		"pa-IN": "ਪਿਟਕੇਰਨ ਟਾਪੂ",
		"ur-IN": "جزائر پٹکیرن",
		"ur-PK": "پٹکائرن جزائر",
		"or-IN": "ପିଟକାଇରିନ୍‌ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "পিটকেইৰ্ণ দ্বীপপুঞ্জ",
		"ne-IN": "पिटकाइर्न टापुहरु",
		"ne-NP": "पिटकाइर्न टापुहरु",
		"si-LK": "පිට්කෙය්න් දූපත්",
		"kok-IN": "पिटकॅरन आयलँड्स",
		"ks-IN": "پِٹکیرٕنؠ جٔزیٖرٕ",
		"brx-IN": "पिटकाईर्न द्वीप",
		"mai-IN": "पिटकेयर्न द्वीपसमूह",
		"dz-BT": "པིཊ་ཀེ་ཡེརན་གླིང་ཚོམ",
		"ja-JP": "ピトケアン諸島",
		"ko-KR": "핏케언 제도",
		"ko-KP": "핏케언 제도",
		"zh-CN": "皮特凯恩群岛",
		"zh-Hans-CN": "皮特凯恩群岛",
		"zh-Hant-TW": "皮特肯群島",
		"zh-TW": "皮特肯群島",
		"zh-HK": "皮特凱恩島",
		"zh-MO": "皮特凱恩島",
		"zh-SG": "皮特凯恩群岛",
		"yue-Hant-HK": "皮特肯群島",
		"yue-Hans-CN": "皮特肯群岛",
		"mn-MN": "Питкэрн арлууд",
		"ug-CN": "پىتكايرن ئاراللىرى",
		"th-TH": "หมู่เกาะพิตแคร์น",
		"lo-LA": "ໝູ່ເກາະພິດແຄນ",
		"km-KH": "កោះ​ភីតកាន",
		"my-MM": "ပစ်တ်ကိန်းကျွန်းစု",
		"vi-VN": "Quần đảo Pitcairn",
		"id-ID": "Kepulauan Pitcairn",
		"ms-MY": "Kepulauan Pitcairn",
		"ms-SG": "Kepulauan Pitcairn",
		"ms-BN": "Kepulauan Pitcairn",
		"jv-ID": "Kapuloan Pitcairn",
		"fil-PH": "Pitcairn Islands",
		"ceb-PH": "Pitcairn Islands",
		"ka-GE": "პიტკერნის კუნძულები",
		"hy-AM": "Պիտկեռն կղզիներ",
		"az-AZ": "Pitkern adaları",
		"az-Cyrl-AZ": "Питкерн адалары",
		"kk-KZ": "Питкэрн аралдары",
		"ky-KG": "Питкэрн аралдары",
		"uz-UZ": "Pitkern orollari",
		"tg-TJ": "Ҷазираҳои Питкейрн",
		"tk-TM": "Pitkern adalary",
		"fa-IR": "جزایر پیت‌کرن",
		"fa-AF": "جزایر پیت‌کرن",
		"ps-AF": "پيټکيرن ټاپوګان",
		"ps-PK": "پيټکيرن ټاپوګان",
		"he-IL": "איי פיטקרן",
		"ar-SA": "جزر بيتكيرن",
		"ar-AE": "جزر بيتكيرن",
		"ar-QA": "جزر بيتكيرن",
		"ar-BH": "جزر بيتكيرن",
		"ar-KW": "جزر بيتكيرن",
		"ar-OM": "جزر بيتكيرن",
		"ar-YE": "جزر بيتكيرن",
		"ar-IQ": "جزر بيتكيرن",
		"ar-JO": "جزر بيتكيرن",
		"ar-LB": "جزر بيتكيرن",
		"ar-SY": "جزر بيتكيرن",
		"ar-PS": "جزر بيتكيرن",
		"en-US": "Pitcairn Islands",
		"en-GB": "Pitcairn Islands",
		"en-IE": "Pitcairn Islands",
		"en-MT": "Pitcairn Islands",
		"en-GI": "Pitcairn Islands",
		"en-CY": "Pitcairn Islands",
		"en-JE": "Pitcairn Islands",
		"en-GG": "Pitcairn Islands",
		"en-IM": "Pitcairn Islands",
		"en-CA": "Pitcairn Islands",
		"en-AU": "Pitcairn Islands",
		"en-NZ": "Pitcairn Islands",
		"en-ZA": "Pitcairn Islands",
		"en-IN": "Pitcairn Islands",
		"en-SG": "Pitcairn Islands",
		"pt-AO": "Ilhas Pitcairn",
		"pt-MZ": "Ilhas Pitcairn",
		"pt-CV": "Ilhas Pitcairn",
		"pt-GW": "Ilhas Pitcairn",
		"pt-ST": "Ilhas Pitcairn",
		"pt-TL": "Ilhas Pitcairn",
		"pt-MO": "Ilhas Pitcairn",
		"es-ES": "Islas Pitcairn",
		"es-419": "Islas Pitcairn",
		"es-AD": "Islas Pitcairn",
		"es-GI": "Islas Pitcairn",
		"es-AR": "Islas Pitcairn",
		"es-BO": "Islas Pitcairn",
		"es-BR": "Islas Pitcairn",
		"es-BZ": "Islas Pitcairn",
		"es-CL": "Islas Pitcairn",
		"es-CO": "Islas Pitcairn",
		"es-CR": "Islas Pitcairn",
		"es-CU": "Islas Pitcairn",
		"es-DO": "Islas Pitcairn",
		"es-EC": "Islas Pitcairn",
		"es-GT": "Islas Pitcairn",
		"es-HN": "Islas Pitcairn",
		"es-MX": "Islas Pitcairn",
		"es-NI": "Islas Pitcairn",
		"es-PA": "Islas Pitcairn",
		"es-PE": "Islas Pitcairn",
		"es-PR": "Islas Pitcairn",
		"es-PY": "Islas Pitcairn",
		"es-SV": "Islas Pitcairn",
		"es-US": "Islas Pitcairn",
		"es-UY": "Islas Pitcairn",
		"es-VE": "Islas Pitcairn",
		"fr-FR": "Îles Pitcairn",
		"fr-BE": "Îles Pitcairn",
		"fr-CH": "Îles Pitcairn",
		"fr-LU": "Îles Pitcairn",
		"fr-MC": "Îles Pitcairn",
		"fr-AD": "Îles Pitcairn",
		"fr-CA": "îles Pitcairn",
		"it-IT": "Isole Pitcairn",
		"it-CH": "Isole Pitcairn",
		"it-SM": "Isole Pitcairn",
		"it-VA": "Isole Pitcairn",
		"de-DE": "Pitcairninseln",
		"de-AT": "Pitcairninseln",
		"de-CH": "Pitcairninseln",
		"de-BE": "Pitcairninseln",
		"de-LI": "Pitcairninseln",
		"de-LU": "Pitcairninseln",
		"nl-NL": "Pitcairneilanden",
		"nl-BE": "Pitcairneilanden",
		"sv-SE": "Pitcairnöarna",
		"sv-FI": "Pitcairnöarna",
		"da-DK": "Pitcairn",
		"nb-NO": "Pitcairnøyene",
		"nn-NO": "Pitcairn",
		"fi-FI": "Pitcairn",
		"is-IS": "Pitcairn-eyjar",
		"fo-FO": "Pitcairnoyggjar",
		"et-EE": "Pitcairni saared",
		"lv-LV": "Pitkērnas salas",
		"lt-LT": "Pitkerno salos",
		"pl-PL": "Pitcairn",
		"cs-CZ": "Pitcairnovy ostrovy",
		"sk-SK": "Pitcairnove ostrovy",
		"sl-SI": "Pitcairn",
		"hr-HR": "Pitcairnovi Otoci",
		"bs-BA": "Pitkernska Ostrva",
		"sr-RS": "Питкерн",
		"sr-BA": "Питкерн",
		"sr-ME": "Pitkern",
		"mk-MK": "Питкернски Острови",
		"bg-BG": "Острови Питкерн",
		"be-BY": "Астравы Піткэрн",
		"uk-UA": "Острови Піткерн",
		"ru-RU": "о-ва Питкэрн",
		"el-GR": "Νήσοι Πίτκερν",
		"el-CY": "Νήσοι Πίτκερν",
		"ro-RO": "Insulele Pitcairn",
		"ro-MD": "Insulele Pitcairn",
		"hu-HU": "Pitcairn-szigetek",
		"sq-AL": "Ishujt Pitkern",
		"sq-XK": "Ishujt Pitkern",
		"mt-MT": "Gżejjer Pitcairn",
		"ga-IE": "Oileáin Pitcairn",
		"cy-GB": "Ynysoedd Pitcairn",
		"gd-GB": "Eileanan Pheit a’ Chàirn",
		"lb-LU": "Pitcairninselen",
		"ca-ES": "Illes Pitcairn",
		"ca-AD": "Illes Pitcairn",
		"ca-FR": "Illes Pitcairn",
		"ca-IT": "Illes Pitcairn",
		"eu-ES": "Pitcairn uharteak",
		"eu-FR": "Pitcairn uharteak",
		"gl-ES": "Illas Pitcairn",
		"tr-TR": "Pitcairn Adaları",
		"tr-CY": "Pitcairn Adaları"
	},
	"callingCode": "64"
} satisfies Country;
