import type { Country } from './types.js';

export const PER = {
	"code": "PER",
	"labels": {
		"pt-BR": "Peru",
		"pt-PT": "Peru",
		"ay-BO": "Piruw",
		"ay-PE": "Piruw",
		"ay-CL": "Piruw",
		"qu-PE": "Piruw",
		"qu-BO": "Piruw",
		"qu-EC": "Piruw",
		"chr-US": "ᏇᎷ",
		"hi-IN": "पेरू",
		"bn-IN": "পেরু",
		"bn-BD": "পেরু",
		"ta-IN": "பெரு",
		"ta-LK": "பெரு",
		"ta-SG": "பெரு",
		"ta-MY": "பெரு",
		"te-IN": "పెరూ",
		"mr-IN": "पेरू",
		"gu-IN": "પેરુ",
		"kn-IN": "ಪೆರು",
		"ml-IN": "പെറു",
		"pa-IN": "ਪੇਰੂ",
		"ur-IN": "پیرو",
		"ur-PK": "پیرو",
		"or-IN": "ପେରୁ",
		"as-IN": "পেৰু",
		"ne-IN": "पेरू",
		"ne-NP": "पेरू",
		"si-LK": "පේරු",
		"kok-IN": "पेरू",
		"ks-IN": "پیٖروٗ",
		"brx-IN": "पेरू",
		"mai-IN": "पेरू",
		"dz-BT": "པེ་རུ",
		"ja-JP": "ペルー",
		"ko-KR": "페루",
		"ko-KP": "페루",
		"zh-CN": "秘鲁",
		"zh-Hans-CN": "秘鲁",
		"zh-Hant-TW": "秘魯",
		"zh-TW": "秘魯",
		"zh-HK": "秘魯",
		"zh-MO": "秘魯",
		"zh-SG": "秘鲁",
		"yue-Hant-HK": "秘魯",
		"yue-Hans-CN": "秘鲁",
		"mn-MN": "Перу",
		"ug-CN": "پېرۇ",
		"th-TH": "เปรู",
		"lo-LA": "ເປຣູ",
		"km-KH": "ប៉េរូ",
		"my-MM": "ပီရူး",
		"vi-VN": "Peru",
		"id-ID": "Peru",
		"ms-MY": "Peru",
		"ms-SG": "Peru",
		"ms-BN": "Peru",
		"jv-ID": "Peru",
		"fil-PH": "Peru",
		"ceb-PH": "Peru",
		"ka-GE": "პერუ",
		"hy-AM": "Պերու",
		"az-AZ": "Peru",
		"az-Cyrl-AZ": "Перу",
		"kk-KZ": "Перу",
		"ky-KG": "Перу",
		"uz-UZ": "Peru",
		"tg-TJ": "Перу",
		"tk-TM": "Peru",
		"fa-IR": "پرو",
		"fa-AF": "پیرو",
		"ps-AF": "پیرو",
		"ps-PK": "پیرو",
		"he-IL": "פרו",
		"ar-SA": "بيرو",
		"ar-AE": "بيرو",
		"ar-QA": "بيرو",
		"ar-BH": "بيرو",
		"ar-KW": "بيرو",
		"ar-OM": "بيرو",
		"ar-YE": "بيرو",
		"ar-IQ": "بيرو",
		"ar-JO": "بيرو",
		"ar-LB": "بيرو",
		"ar-SY": "بيرو",
		"ar-PS": "بيرو",
		"en-US": "Peru",
		"en-GB": "Peru",
		"en-IE": "Peru",
		"en-MT": "Peru",
		"en-GI": "Peru",
		"en-CY": "Peru",
		"en-JE": "Peru",
		"en-GG": "Peru",
		"en-IM": "Peru",
		"en-CA": "Peru",
		"en-AU": "Peru",
		"en-NZ": "Peru",
		"en-ZA": "Peru",
		"en-IN": "Peru",
		"en-SG": "Peru",
		"pt-AO": "Peru",
		"pt-MZ": "Peru",
		"pt-CV": "Peru",
		"pt-GW": "Peru",
		"pt-ST": "Peru",
		"pt-TL": "Peru",
		"pt-MO": "Peru",
		"es-ES": "Perú",
		"es-419": "Perú",
		"es-AD": "Perú",
		"es-GI": "Perú",
		"es-AR": "Perú",
		"es-BO": "Perú",
		"es-BR": "Perú",
		"es-BZ": "Perú",
		"es-CL": "Perú",
		"es-CO": "Perú",
		"es-CR": "Perú",
		"es-CU": "Perú",
		"es-DO": "Perú",
		"es-EC": "Perú",
		"es-GT": "Perú",
		"es-HN": "Perú",
		"es-MX": "Perú",
		"es-NI": "Perú",
		"es-PA": "Perú",
		"es-PE": "Perú",
		"es-PR": "Perú",
		"es-PY": "Perú",
		"es-SV": "Perú",
		"es-US": "Perú",
		"es-UY": "Perú",
		"es-VE": "Perú",
		"fr-FR": "Pérou",
		"fr-BE": "Pérou",
		"fr-CH": "Pérou",
		"fr-LU": "Pérou",
		"fr-MC": "Pérou",
		"fr-AD": "Pérou",
		"fr-CA": "Pérou",
		"it-IT": "Perù",
		"it-CH": "Perù",
		"it-SM": "Perù",
		"it-VA": "Perù",
		"de-DE": "Peru",
		"de-AT": "Peru",
		"de-CH": "Peru",
		"de-BE": "Peru",
		"de-LI": "Peru",
		"de-LU": "Peru",
		"nl-NL": "Peru",
		"nl-BE": "Peru",
		"sv-SE": "Peru",
		"sv-FI": "Peru",
		"da-DK": "Peru",
		"nb-NO": "Peru",
		"nn-NO": "Peru",
		"fi-FI": "Peru",
		"is-IS": "Perú",
		"fo-FO": "Peru",
		"et-EE": "Peruu",
		"lv-LV": "Peru",
		"lt-LT": "Peru",
		"pl-PL": "Peru",
		"cs-CZ": "Peru",
		"sk-SK": "Peru",
		"sl-SI": "Peru",
		"hr-HR": "Peru",
		"bs-BA": "Peru",
		"sr-RS": "Перу",
		"sr-BA": "Перу",
		"sr-ME": "Peru",
		"mk-MK": "Перу",
		"bg-BG": "Перу",
		"be-BY": "Перу",
		"uk-UA": "Перу",
		"ru-RU": "Перу",
		"el-GR": "Περού",
		"el-CY": "Περού",
		"ro-RO": "Peru",
		"ro-MD": "Peru",
		"hu-HU": "Peru",
		"sq-AL": "Peru",
		"sq-XK": "Peru",
		"mt-MT": "il-Perù",
		"ga-IE": "Peiriú",
		"cy-GB": "Periw",
		"gd-GB": "Pearù",
		"lb-LU": "Peru",
		"ca-ES": "Perú",
		"ca-AD": "Perú",
		"ca-FR": "Perú",
		"ca-IT": "Perú",
		"eu-ES": "Peru",
		"eu-FR": "Peru",
		"gl-ES": "Perú",
		"tr-TR": "Peru",
		"tr-CY": "Peru"
	},
	"callingCode": "51",
	"phoneMasks": [
		{
			"mask": "# #######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "## ######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[4-8]"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"80"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"9"
			]
		}
	]
} satisfies Country;
