import type { Country } from './types.js';

export const PNG = {
	"code": "PNG",
	"labels": {
		"pt-BR": "Papua-Nova Guiné",
		"pt-PT": "Papua-Nova Guiné",
		"qu-PE": "Papúa Nueva Guinea",
		"qu-BO": "Papúa Nueva Guinea",
		"qu-EC": "Papúa Nueva Guinea",
		"chr-US": "ᏆᏇ ᎢᏤ ᎩᎢᏂ",
		"hi-IN": "पापुआ न्यू गिनी",
		"bn-IN": "পাপুয়া নিউ গিনি",
		"bn-BD": "পাপুয়া নিউ গিনি",
		"ta-IN": "பப்புவா நியூ கினியா",
		"ta-LK": "பப்புவா நியூ கினியா",
		"ta-SG": "பப்புவா நியூ கினியா",
		"ta-MY": "பப்புவா நியூ கினியா",
		"te-IN": "పాపువా న్యూ గినియా",
		"mr-IN": "पापुआ न्यू गिनी",
		"gu-IN": "પાપુઆ ન્યૂ ગિની",
		"kn-IN": "ಪಪುವಾ ನ್ಯೂಗಿನಿಯಾ",
		"ml-IN": "പാപ്പുവ ന്യൂ ഗിനിയ",
		"pa-IN": "ਪਾਪੂਆ ਨਿਊ ਗਿਨੀ",
		"ur-IN": "پاپوآ نیو گنی",
		"ur-PK": "پاپوآ نیو گنی",
		"or-IN": "ପପୁଆ ନ୍ୟୁ ଗିନି",
		"as-IN": "পাপুৱা নিউ গিনি",
		"ne-IN": "पपुआ न्यू गाइनिया",
		"ne-NP": "पपुआ न्यू गाइनिया",
		"si-LK": "පැපුවා නිව් ගිනියාව",
		"kok-IN": "पापुआ न्यु गिनी",
		"ks-IN": "پاپُوا نیوٗ گیٖنی",
		"brx-IN": "पापुआ निउ गिनी",
		"mai-IN": "पापुआ न्यू गिनी",
		"dz-BT": "པ་པུ་ ནིའུ་གི་ནི",
		"ja-JP": "パプアニューギニア",
		"ko-KR": "파푸아뉴기니",
		"ko-KP": "파푸아뉴기니",
		"zh-CN": "巴布亚新几内亚",
		"zh-Hans-CN": "巴布亚新几内亚",
		"zh-Hant-TW": "巴布亞紐幾內亞",
		"zh-TW": "巴布亞紐幾內亞",
		"zh-HK": "巴布亞新畿內亞",
		"zh-MO": "巴布亞新畿內亞",
		"zh-SG": "巴布亚新几内亚",
		"yue-Hant-HK": "巴布亞紐幾內亞",
		"yue-Hans-CN": "巴布亚纽几内亚",
		"mn-MN": "Папуа Шинэ Гвиней",
		"ug-CN": "پاپۇئا يېڭى گىۋىنىيەسى",
		"th-TH": "ปาปัวนิวกินี",
		"lo-LA": "ປາປົວນິວກີນີ",
		"km-KH": "ប៉ាពូអាស៊ី​នូវែលហ្គីណេ",
		"my-MM": "ပါပူအာ နယူးဂီနီ",
		"vi-VN": "Papua New Guinea",
		"id-ID": "Papua Nugini",
		"ms-MY": "Papua New Guinea",
		"ms-SG": "Papua New Guinea",
		"ms-BN": "Papua New Guinea",
		"jv-ID": "Papua Nugini",
		"fil-PH": "Papua New Guinea",
		"ceb-PH": "Papua New Guinea",
		"ka-GE": "პაპუა-ახალი გვინეა",
		"hy-AM": "Պապուա Նոր Գվինեա",
		"az-AZ": "Papua-Yeni Qvineya",
		"az-Cyrl-AZ": "Папуа-Јени Гвинеја",
		"kk-KZ": "Папуа — Жаңа Гвинея",
		"ky-KG": "Папуа-Жаңы Гвинея",
		"uz-UZ": "Papua – Yangi Gvineya",
		"tg-TJ": "Папуа Гвинеяи Нав",
		"tk-TM": "Papua - Täze Gwineýa",
		"fa-IR": "پاپوا گینهٔ نو",
		"fa-AF": "پاپوا نیو گینیا",
		"ps-AF": "پاپوا نيو ګيني",
		"ps-PK": "پاپوا نيو ګيني",
		"he-IL": "פפואה גינאה החדשה",
		"ar-SA": "بابوا غينيا الجديدة",
		"ar-AE": "بابوا غينيا الجديدة",
		"ar-QA": "بابوا غينيا الجديدة",
		"ar-BH": "بابوا غينيا الجديدة",
		"ar-KW": "بابوا غينيا الجديدة",
		"ar-OM": "بابوا غينيا الجديدة",
		"ar-YE": "بابوا غينيا الجديدة",
		"ar-IQ": "بابوا غينيا الجديدة",
		"ar-JO": "بابوا غينيا الجديدة",
		"ar-LB": "بابوا غينيا الجديدة",
		"ar-SY": "بابوا غينيا الجديدة",
		"ar-PS": "بابوا غينيا الجديدة",
		"en-US": "Papua New Guinea",
		"en-GB": "Papua New Guinea",
		"en-IE": "Papua New Guinea",
		"en-MT": "Papua New Guinea",
		"en-GI": "Papua New Guinea",
		"en-CY": "Papua New Guinea",
		"en-JE": "Papua New Guinea",
		"en-GG": "Papua New Guinea",
		"en-IM": "Papua New Guinea",
		"en-CA": "Papua New Guinea",
		"en-AU": "Papua New Guinea",
		"en-NZ": "Papua New Guinea",
		"en-ZA": "Papua New Guinea",
		"en-IN": "Papua New Guinea",
		"en-SG": "Papua New Guinea",
		"pt-AO": "Papua-Nova Guiné",
		"pt-MZ": "Papua-Nova Guiné",
		"pt-CV": "Papua-Nova Guiné",
		"pt-GW": "Papua-Nova Guiné",
		"pt-ST": "Papua-Nova Guiné",
		"pt-TL": "Papua-Nova Guiné",
		"pt-MO": "Papua-Nova Guiné",
		"es-ES": "Papúa Nueva Guinea",
		"es-419": "Papúa Nueva Guinea",
		"es-AD": "Papúa Nueva Guinea",
		"es-GI": "Papúa Nueva Guinea",
		"es-AR": "Papúa Nueva Guinea",
		"es-BO": "Papúa Nueva Guinea",
		"es-BR": "Papúa Nueva Guinea",
		"es-BZ": "Papúa Nueva Guinea",
		"es-CL": "Papúa Nueva Guinea",
		"es-CO": "Papúa Nueva Guinea",
		"es-CR": "Papúa Nueva Guinea",
		"es-CU": "Papúa Nueva Guinea",
		"es-DO": "Papúa Nueva Guinea",
		"es-EC": "Papúa Nueva Guinea",
		"es-GT": "Papúa Nueva Guinea",
		"es-HN": "Papúa Nueva Guinea",
		"es-MX": "Papúa Nueva Guinea",
		"es-NI": "Papúa Nueva Guinea",
		"es-PA": "Papúa Nueva Guinea",
		"es-PE": "Papúa Nueva Guinea",
		"es-PR": "Papúa Nueva Guinea",
		"es-PY": "Papúa Nueva Guinea",
		"es-SV": "Papúa Nueva Guinea",
		"es-US": "Papúa Nueva Guinea",
		"es-UY": "Papúa Nueva Guinea",
		"es-VE": "Papúa Nueva Guinea",
		"fr-FR": "Papouasie-Nouvelle-Guinée",
		"fr-BE": "Papouasie-Nouvelle-Guinée",
		"fr-CH": "Papouasie-Nouvelle-Guinée",
		"fr-LU": "Papouasie-Nouvelle-Guinée",
		"fr-MC": "Papouasie-Nouvelle-Guinée",
		"fr-AD": "Papouasie-Nouvelle-Guinée",
		"fr-CA": "Papouasie-Nouvelle-Guinée",
		"it-IT": "Papua Nuova Guinea",
		"it-CH": "Papua Nuova Guinea",
		"it-SM": "Papua Nuova Guinea",
		"it-VA": "Papua Nuova Guinea",
		"de-DE": "Papua-Neuguinea",
		"de-AT": "Papua-Neuguinea",
		"de-CH": "Papua-Neuguinea",
		"de-BE": "Papua-Neuguinea",
		"de-LI": "Papua-Neuguinea",
		"de-LU": "Papua-Neuguinea",
		"nl-NL": "Papoea-Nieuw-Guinea",
		"nl-BE": "Papoea-Nieuw-Guinea",
		"sv-SE": "Papua Nya Guinea",
		"sv-FI": "Papua Nya Guinea",
		"da-DK": "Papua Ny Guinea",
		"nb-NO": "Papua Ny-Guinea",
		"nn-NO": "Papua Ny-Guinea",
		"fi-FI": "Papua-Uusi-Guinea",
		"is-IS": "Papúa Nýja-Gínea",
		"fo-FO": "Papua Nýguinea",
		"et-EE": "Paapua Uus-Guinea",
		"lv-LV": "Papua-Jaungvineja",
		"lt-LT": "Papua Naujoji Gvinėja",
		"pl-PL": "Papua-Nowa Gwinea",
		"cs-CZ": "Papua-Nová Guinea",
		"sk-SK": "Papua-Nová Guinea",
		"sl-SI": "Papua Nova Gvineja",
		"hr-HR": "Papua Nova Gvineja",
		"bs-BA": "Papua Nova Gvineja",
		"sr-RS": "Папуа Нова Гвинеја",
		"sr-BA": "Папуа Нова Гвинеја",
		"sr-ME": "Papua Nova Gvineja",
		"mk-MK": "Папуа Нова Гвинеја",
		"bg-BG": "Папуа-Нова Гвинея",
		"be-BY": "Папуа-Новая Гвінея",
		"uk-UA": "Папуа-Нова Гвінея",
		"ru-RU": "Папуа — Новая Гвинея",
		"el-GR": "Παπούα Νέα Γουινέα",
		"el-CY": "Παπούα Νέα Γουινέα",
		"ro-RO": "Papua-Noua Guinee",
		"ro-MD": "Papua-Noua Guinee",
		"hu-HU": "Pápua Új-Guinea",
		"sq-AL": "Guineja e Re-Papua",
		"sq-XK": "Guineja e Re-Papua",
		"mt-MT": "Papua New Guinea",
		"ga-IE": "Nua-Ghuine Phapua",
		"cy-GB": "Papua Guinea Newydd",
		"gd-GB": "Gini Nuadh Phaputhach",
		"lb-LU": "Papua-Neiguinea",
		"ca-ES": "Papua Nova Guinea",
		"ca-AD": "Papua Nova Guinea",
		"ca-FR": "Papua Nova Guinea",
		"ca-IT": "Papua Nova Guinea",
		"eu-ES": "Papua Ginea Berria",
		"eu-FR": "Papua Ginea Berria",
		"gl-ES": "Papúa-Nova Guinea",
		"tr-TR": "Papua Yeni Gine",
		"tr-CY": "Papua Yeni Gine"
	},
	"callingCode": "675",
	"phoneMasks": [
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"18|[2-69]|85"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[78]"
			]
		}
	]
} satisfies Country;
