import type { Country } from './types.js';

export const POL = {
	"code": "POL",
	"labels": {
		"pt-BR": "Polônia",
		"pt-PT": "Polónia",
		"qu-PE": "Polonia",
		"qu-BO": "Polonia",
		"qu-EC": "Polonia",
		"chr-US": "ᏉᎳᏂ",
		"hi-IN": "पोलैंड",
		"bn-IN": "পোল্যান্ড",
		"bn-BD": "পোল্যান্ড",
		"ta-IN": "போலந்து",
		"ta-LK": "போலந்து",
		"ta-SG": "போலந்து",
		"ta-MY": "போலந்து",
		"te-IN": "పోలాండ్",
		"mr-IN": "पोलंड",
		"gu-IN": "પોલેંડ",
		"kn-IN": "ಪೋಲ್ಯಾಂಡ್",
		"ml-IN": "പോളണ്ട്",
		"pa-IN": "ਪੋਲੈਂਡ",
		"ur-IN": "پولینڈ",
		"ur-PK": "پولینڈ",
		"or-IN": "ପୋଲାଣ୍ଡ",
		"as-IN": "পোলেণ্ড",
		"ne-IN": "पोल्याण्ड",
		"ne-NP": "पोल्याण्ड",
		"si-LK": "පෝලන්තය",
		"kok-IN": "पोलंड",
		"ks-IN": "پولینڈ",
		"brx-IN": "पलेण्ड",
		"mai-IN": "पोलैंड",
		"dz-BT": "པོ་ལེནཌ",
		"ja-JP": "ポーランド",
		"ko-KR": "폴란드",
		"ko-KP": "폴란드",
		"zh-CN": "波兰",
		"zh-Hans-CN": "波兰",
		"zh-Hant-TW": "波蘭",
		"zh-TW": "波蘭",
		"zh-HK": "波蘭",
		"zh-MO": "波蘭",
		"zh-SG": "波兰",
		"yue-Hant-HK": "波蘭",
		"yue-Hans-CN": "波兰",
		"mn-MN": "Польш",
		"ug-CN": "پولشا",
		"th-TH": "โปแลนด์",
		"lo-LA": "ໂປແລນ",
		"km-KH": "ប៉ូឡូញ",
		"my-MM": "ပိုလန်",
		"vi-VN": "Ba Lan",
		"id-ID": "Polandia",
		"ms-MY": "Poland",
		"ms-SG": "Poland",
		"ms-BN": "Poland",
		"jv-ID": "Polen",
		"fil-PH": "Poland",
		"ceb-PH": "Poland",
		"ka-GE": "პოლონეთი",
		"hy-AM": "Լեհաստան",
		"az-AZ": "Polşa",
		"az-Cyrl-AZ": "Полша",
		"kk-KZ": "Польша",
		"ky-KG": "Польша",
		"uz-UZ": "Polsha",
		"tg-TJ": "Лаҳистон",
		"tk-TM": "Polşa",
		"fa-IR": "لهستان",
		"fa-AF": "پولند",
		"ps-AF": "پولنډ",
		"ps-PK": "پولنډ",
		"he-IL": "פולין",
		"ar-SA": "بولندا",
		"ar-AE": "بولندا",
		"ar-QA": "بولندا",
		"ar-BH": "بولندا",
		"ar-KW": "بولندا",
		"ar-OM": "بولندا",
		"ar-YE": "بولندا",
		"ar-IQ": "بولندا",
		"ar-JO": "بولندا",
		"ar-LB": "بولندا",
		"ar-SY": "بولندا",
		"ar-PS": "بولندا",
		"en-US": "Poland",
		"en-GB": "Poland",
		"en-IE": "Poland",
		"en-MT": "Poland",
		"en-GI": "Poland",
		"en-CY": "Poland",
		"en-JE": "Poland",
		"en-GG": "Poland",
		"en-IM": "Poland",
		"en-CA": "Poland",
		"en-AU": "Poland",
		"en-NZ": "Poland",
		"en-ZA": "Poland",
		"en-IN": "Poland",
		"en-SG": "Poland",
		"pt-AO": "Polónia",
		"pt-MZ": "Polónia",
		"pt-CV": "Polónia",
		"pt-GW": "Polónia",
		"pt-ST": "Polónia",
		"pt-TL": "Polónia",
		"pt-MO": "Polónia",
		"es-ES": "Polonia",
		"es-419": "Polonia",
		"es-AD": "Polonia",
		"es-GI": "Polonia",
		"es-AR": "Polonia",
		"es-BO": "Polonia",
		"es-BR": "Polonia",
		"es-BZ": "Polonia",
		"es-CL": "Polonia",
		"es-CO": "Polonia",
		"es-CR": "Polonia",
		"es-CU": "Polonia",
		"es-DO": "Polonia",
		"es-EC": "Polonia",
		"es-GT": "Polonia",
		"es-HN": "Polonia",
		"es-MX": "Polonia",
		"es-NI": "Polonia",
		"es-PA": "Polonia",
		"es-PE": "Polonia",
		"es-PR": "Polonia",
		"es-PY": "Polonia",
		"es-SV": "Polonia",
		"es-US": "Polonia",
		"es-UY": "Polonia",
		"es-VE": "Polonia",
		"fr-FR": "Pologne",
		"fr-BE": "Pologne",
		"fr-CH": "Pologne",
		"fr-LU": "Pologne",
		"fr-MC": "Pologne",
		"fr-AD": "Pologne",
		"fr-CA": "Pologne",
		"it-IT": "Polonia",
		"it-CH": "Polonia",
		"it-SM": "Polonia",
		"it-VA": "Polonia",
		"de-DE": "Polen",
		"de-AT": "Polen",
		"de-CH": "Polen",
		"de-BE": "Polen",
		"de-LI": "Polen",
		"de-LU": "Polen",
		"nl-NL": "Polen",
		"nl-BE": "Polen",
		"sv-SE": "Polen",
		"sv-FI": "Polen",
		"da-DK": "Polen",
		"nb-NO": "Polen",
		"nn-NO": "Polen",
		"fi-FI": "Puola",
		"is-IS": "Pólland",
		"fo-FO": "Pólland",
		"et-EE": "Poola",
		"lv-LV": "Polija",
		"lt-LT": "Lenkija",
		"pl-PL": "Polska",
		"cs-CZ": "Polsko",
		"sk-SK": "Poľsko",
		"sl-SI": "Poljska",
		"hr-HR": "Poljska",
		"bs-BA": "Poljska",
		"sr-RS": "Пољска",
		"sr-BA": "Пољска",
		"sr-ME": "Poljska",
		"mk-MK": "Полска",
		"bg-BG": "Полша",
		"be-BY": "Польшча",
		"uk-UA": "Польща",
		"ru-RU": "Польша",
		"el-GR": "Πολωνία",
		"el-CY": "Πολωνία",
		"ro-RO": "Polonia",
		"ro-MD": "Polonia",
		"hu-HU": "Lengyelország",
		"sq-AL": "Poloni",
		"sq-XK": "Poloni",
		"mt-MT": "il-Polonja",
		"ga-IE": "an Pholainn",
		"cy-GB": "Gwlad Pwyl",
		"gd-GB": "A’ Phòlainn",
		"lb-LU": "Polen",
		"ca-ES": "Polònia",
		"ca-AD": "Polònia",
		"ca-FR": "Polònia",
		"ca-IT": "Polònia",
		"eu-ES": "Polonia",
		"eu-FR": "Polonia",
		"gl-ES": "Polonia",
		"tr-TR": "Polonya",
		"tr-CY": "Polonya"
	},
	"callingCode": "48",
	"phoneMasks": [
		{
			"mask": "#####",
			"minLength": 5,
			"maxLength": 5,
			"leadingDigits": [
				"19"
			]
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"11|20|64"
			]
		},
		{
			"mask": "## ## ###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"(?:1[2-8]|2[2-69]|3[2-4]|4[1-468]|5[24-689]|6[1-3578]|7[14-7]|8[1-79]|9[145])1",
				"(?:1[2-8]|2[2-69]|3[2-4]|4[1-468]|5[24-689]|6[1-3578]|7[14-7]|8[1-79]|9[145])19"
			]
		},
		{
			"mask": "### ## ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"64"
			]
		},
		{
			"mask": "## ### ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1[2-8]|[2-7]|8[1-79]|9[145]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"21|39|45|5[0137]|6[0469]|7[02389]|8(?:0[14]|8)"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
