import type { Country } from './types.js';

export const PRK = {
	"code": "PRK",
	"labels": {
		"pt-BR": "Coreia do Norte",
		"pt-PT": "Coreia do Norte",
		"qu-PE": "Corea del Norte",
		"qu-BO": "Corea del Norte",
		"qu-EC": "Corea del Norte",
		"chr-US": "ᏧᏴᏢ ᎪᎵᎠ",
		"hi-IN": "उत्तर कोरिया",
		"bn-IN": "উত্তর কোরিয়া",
		"bn-BD": "উত্তর কোরিয়া",
		"ta-IN": "வட கொரியா",
		"ta-LK": "வட கொரியா",
		"ta-SG": "வட கொரியா",
		"ta-MY": "வட கொரியா",
		"te-IN": "ఉత్తర కొరియా",
		"mr-IN": "उत्तर कोरिया",
		"gu-IN": "ઉત્તર કોરિયા",
		"kn-IN": "ಉತ್ತರ ಕೊರಿಯಾ",
		"ml-IN": "ഉത്തരകൊറിയ",
		"pa-IN": "ਉੱਤਰ ਕੋਰੀਆ",
		"ur-IN": "شمالی کوریا",
		"ur-PK": "شمالی کوریا",
		"or-IN": "ଉତ୍ତର କୋରିଆ",
		"as-IN": "উত্তৰ কোৰিয়া",
		"ne-IN": "उत्तर कोरिया",
		"ne-NP": "उत्तर कोरिया",
		"si-LK": "උතුරු කොරියාව",
		"kok-IN": "उत्तर कोरिया",
		"ks-IN": "شُمٲلی کورِیا",
		"brx-IN": "साहा करिया",
		"mai-IN": "उत्तर कोरिया",
		"dz-BT": "བྱང་ ཀོ་རི་ཡ",
		"ja-JP": "北朝鮮",
		"ko-KR": "북한",
		"ko-KP": "조선민주주의인민공화국",
		"zh-CN": "朝鲜",
		"zh-Hans-CN": "朝鲜",
		"zh-Hant-TW": "北韓",
		"zh-TW": "北韓",
		"zh-HK": "北韓",
		"zh-MO": "北韓",
		"zh-SG": "朝鲜",
		"yue-Hant-HK": "北韓",
		"yue-Hans-CN": "北韩",
		"mn-MN": "Хойд Солонгос",
		"ug-CN": "چاۋشيەن",
		"th-TH": "เกาหลีเหนือ",
		"lo-LA": "ເກົາຫລີເໜືອ",
		"km-KH": "កូរ៉េ​ខាង​ជើង",
		"my-MM": "မြောက်ကိုရီးယား",
		"vi-VN": "Triều Tiên",
		"id-ID": "Korea Utara",
		"ms-MY": "Korea Utara",
		"ms-SG": "Korea Utara",
		"ms-BN": "Korea Utara",
		"jv-ID": "Korea Lor",
		"fil-PH": "Hilagang Korea",
		"ceb-PH": "North Korea",
		"ka-GE": "ჩრდილოეთ კორეა",
		"hy-AM": "Հյուսիսային Կորեա",
		"az-AZ": "Şimali Koreya",
		"az-Cyrl-AZ": "Шимали Кореја",
		"kk-KZ": "Солтүстік Корея",
		"ky-KG": "Түндүк Корея",
		"uz-UZ": "Shimoliy Koreya",
		"tg-TJ": "Кореяи Шимолӣ",
		"tk-TM": "Demirgazyk Koreýa",
		"fa-IR": "کرهٔ شمالی",
		"fa-AF": "کوریای شمالی",
		"ps-AF": "شمالی کوریا",
		"ps-PK": "شمالی کوریا",
		"he-IL": "קוריאה הצפונית",
		"ar-SA": "كوريا الشمالية",
		"ar-AE": "كوريا الشمالية",
		"ar-QA": "كوريا الشمالية",
		"ar-BH": "كوريا الشمالية",
		"ar-KW": "كوريا الشمالية",
		"ar-OM": "كوريا الشمالية",
		"ar-YE": "كوريا الشمالية",
		"ar-IQ": "كوريا الشمالية",
		"ar-JO": "كوريا الشمالية",
		"ar-LB": "كوريا الشمالية",
		"ar-SY": "كوريا الشمالية",
		"ar-PS": "كوريا الشمالية",
		"en-US": "North Korea",
		"en-GB": "North Korea",
		"en-IE": "North Korea",
		"en-MT": "North Korea",
		"en-GI": "North Korea",
		"en-CY": "North Korea",
		"en-JE": "North Korea",
		"en-GG": "North Korea",
		"en-IM": "North Korea",
		"en-CA": "North Korea",
		"en-AU": "North Korea",
		"en-NZ": "North Korea",
		"en-ZA": "North Korea",
		"en-IN": "North Korea",
		"en-SG": "North Korea",
		"pt-AO": "Coreia do Norte",
		"pt-MZ": "Coreia do Norte",
		"pt-CV": "Coreia do Norte",
		"pt-GW": "Coreia do Norte",
		"pt-ST": "Coreia do Norte",
		"pt-TL": "Coreia do Norte",
		"pt-MO": "Coreia do Norte",
		"es-ES": "Corea del Norte",
		"es-419": "Corea del Norte",
		"es-AD": "Corea del Norte",
		"es-GI": "Corea del Norte",
		"es-AR": "Corea del Norte",
		"es-BO": "Corea del Norte",
		"es-BR": "Corea del Norte",
		"es-BZ": "Corea del Norte",
		"es-CL": "Corea del Norte",
		"es-CO": "Corea del Norte",
		"es-CR": "Corea del Norte",
		"es-CU": "Corea del Norte",
		"es-DO": "Corea del Norte",
		"es-EC": "Corea del Norte",
		"es-GT": "Corea del Norte",
		"es-HN": "Corea del Norte",
		"es-MX": "Corea del Norte",
		"es-NI": "Corea del Norte",
		"es-PA": "Corea del Norte",
		"es-PE": "Corea del Norte",
		"es-PR": "Corea del Norte",
		"es-PY": "Corea del Norte",
		"es-SV": "Corea del Norte",
		"es-US": "Corea del Norte",
		"es-UY": "Corea del Norte",
		"es-VE": "Corea del Norte",
		"fr-FR": "Corée du Nord",
		"fr-BE": "Corée du Nord",
		"fr-CH": "Corée du Nord",
		"fr-LU": "Corée du Nord",
		"fr-MC": "Corée du Nord",
		"fr-AD": "Corée du Nord",
		"fr-CA": "Corée du Nord",
		"it-IT": "Corea del Nord",
		"it-CH": "Corea del Nord",
		"it-SM": "Corea del Nord",
		"it-VA": "Corea del Nord",
		"de-DE": "Nordkorea",
		"de-AT": "Nordkorea",
		"de-CH": "Nordkorea",
		"de-BE": "Nordkorea",
		"de-LI": "Nordkorea",
		"de-LU": "Nordkorea",
		"nl-NL": "Noord-Korea",
		"nl-BE": "Noord-Korea",
		"sv-SE": "Nordkorea",
		"sv-FI": "Nordkorea",
		"da-DK": "Nordkorea",
		"nb-NO": "Nord-Korea",
		"nn-NO": "Nord-Korea",
		"fi-FI": "Pohjois-Korea",
		"is-IS": "Norður-Kórea",
		"fo-FO": "Norðurkorea",
		"et-EE": "Põhja-Korea",
		"lv-LV": "Ziemeļkoreja",
		"lt-LT": "Šiaurės Korėja",
		"pl-PL": "Korea Północna",
		"cs-CZ": "Severní Korea",
		"sk-SK": "Severná Kórea",
		"sl-SI": "Severna Koreja",
		"hr-HR": "Sjeverna Koreja",
		"bs-BA": "Sjeverna Koreja",
		"sr-RS": "Северна Кореја",
		"sr-BA": "Сјеверна Кореја",
		"sr-ME": "Severna Koreja",
		"mk-MK": "Северна Кореја",
		"bg-BG": "Северна Корея",
		"be-BY": "Паўночная Карэя",
		"uk-UA": "Північна Корея",
		"ru-RU": "КНДР",
		"el-GR": "Βόρεια Κορέα",
		"el-CY": "Βόρεια Κορέα",
		"ro-RO": "Coreea de Nord",
		"ro-MD": "Coreea de Nord",
		"hu-HU": "Észak-Korea",
		"sq-AL": "Kore e Veriut",
		"sq-XK": "Kore e Veriut",
		"mt-MT": "il-Korea ta’ Fuq",
		"ga-IE": "an Chóiré Thuaidh",
		"cy-GB": "Gogledd Corea",
		"gd-GB": "Coirèa a Tuath",
		"lb-LU": "Nordkorea",
		"ca-ES": "Corea del Nord",
		"ca-AD": "Corea del Nord",
		"ca-FR": "Corea del Nord",
		"ca-IT": "Corea del Nord",
		"eu-ES": "Ipar Korea",
		"eu-FR": "Ipar Korea",
		"gl-ES": "Corea do Norte",
		"tr-TR": "Kuzey Kore",
		"tr-CY": "Kuzey Kore"
	},
	"callingCode": "850",
	"phoneMasks": [
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[2-7]"
			]
		},
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1"
			]
		}
	]
} satisfies Country;
