import type { Country } from './types.js';

export const REU = {
	"code": "REU",
	"labels": {
		"pt-BR": "Reunião",
		"pt-PT": "Reunião",
		"qu-PE": "Reunión",
		"qu-BO": "Reunión",
		"qu-EC": "Reunión",
		"chr-US": "ᎴᏳᏂᎠᏂ",
		"hi-IN": "रियूनियन",
		"bn-IN": "রিইউনিয়ন",
		"bn-BD": "রিইউনিয়ন",
		"ta-IN": "ரீயூனியன்",
		"ta-LK": "ரீயூனியன்",
		"ta-SG": "ரீயூனியன்",
		"ta-MY": "ரீயூனியன்",
		"te-IN": "రీయూనియన్",
		"mr-IN": "रियुनियन",
		"gu-IN": "રીયુનિયન",
		"kn-IN": "ರಿಯೂನಿಯನ್",
		"ml-IN": "റീയൂണിയൻ",
		"pa-IN": "ਰਿਯੂਨੀਅਨ",
		"ur-IN": "ری یونین",
		"ur-PK": "ری یونین",
		"or-IN": "ରିୟୁନିଅନ୍",
		"as-IN": "ৰিইউনিয়ন",
		"ne-IN": "रियुनियन",
		"ne-NP": "रियुनियन",
		"si-LK": "රීයුනියන්",
		"kok-IN": "रीयूनियन",
		"ks-IN": "رِیوٗنِیَن",
		"brx-IN": "रेयूनियन",
		"mai-IN": "रियूनियन",
		"dz-BT": "རེ་ཡུ་ནི་ཡོན",
		"ja-JP": "レユニオン",
		"ko-KR": "레위니옹",
		"ko-KP": "레위니옹",
		"zh-CN": "留尼汪",
		"zh-Hans-CN": "留尼汪",
		"zh-Hant-TW": "留尼旺",
		"zh-TW": "留尼旺",
		"zh-HK": "留尼旺",
		"zh-MO": "留尼旺",
		"zh-SG": "留尼汪",
		"yue-Hant-HK": "留尼旺",
		"yue-Hans-CN": "留尼旺",
		"mn-MN": "Реюнион",
		"ug-CN": "رېيۇنىيون",
		"th-TH": "เรอูนียง",
		"lo-LA": "ເຣອູນິຍົງ",
		"km-KH": "រេអុយញ៉ុង",
		"my-MM": "ရီယူနီယန်",
		"vi-VN": "Réunion",
		"id-ID": "Réunion",
		"ms-MY": "Reunion",
		"ms-SG": "Reunion",
		"ms-BN": "Reunion",
		"jv-ID": "Réunion",
		"fil-PH": "Réunion",
		"ceb-PH": "Reunion",
		"ka-GE": "რეუნიონი",
		"hy-AM": "Ռեյունիոն",
		"az-AZ": "Reyunyon",
		"az-Cyrl-AZ": "Рејунјон",
		"kk-KZ": "Реюньон",
		"ky-KG": "Реюньон",
		"uz-UZ": "Reyunion",
		"tg-TJ": "Реюнион",
		"tk-TM": "Reýunýon",
		"fa-IR": "رئونیون",
		"fa-AF": "رئونیون",
		"ps-AF": "ریونین",
		"ps-PK": "ریونین",
		"he-IL": "ראוניון",
		"ar-SA": "روينيون",
		"ar-AE": "روينيون",
		"ar-QA": "روينيون",
		"ar-BH": "روينيون",
		"ar-KW": "روينيون",
		"ar-OM": "روينيون",
		"ar-YE": "روينيون",
		"ar-IQ": "روينيون",
		"ar-JO": "روينيون",
		"ar-LB": "روينيون",
		"ar-SY": "روينيون",
		"ar-PS": "روينيون",
		"en-US": "Réunion",
		"en-GB": "Réunion",
		"en-IE": "Réunion",
		"en-MT": "Réunion",
		"en-GI": "Réunion",
		"en-CY": "Réunion",
		"en-JE": "Réunion",
		"en-GG": "Réunion",
		"en-IM": "Réunion",
		"en-CA": "Réunion",
		"en-AU": "Réunion",
		"en-NZ": "Réunion",
		"en-ZA": "Réunion",
		"en-IN": "Réunion",
		"en-SG": "Réunion",
		"pt-AO": "Reunião",
		"pt-MZ": "Reunião",
		"pt-CV": "Reunião",
		"pt-GW": "Reunião",
		"pt-ST": "Reunião",
		"pt-TL": "Reunião",
		"pt-MO": "Reunião",
		"es-ES": "Reunión",
		"es-419": "Reunión",
		"es-AD": "Reunión",
		"es-GI": "Reunión",
		"es-AR": "Reunión",
		"es-BO": "Reunión",
		"es-BR": "Reunión",
		"es-BZ": "Reunión",
		"es-CL": "Reunión",
		"es-CO": "Reunión",
		"es-CR": "Reunión",
		"es-CU": "Reunión",
		"es-DO": "Reunión",
		"es-EC": "Reunión",
		"es-GT": "Reunión",
		"es-HN": "Reunión",
		"es-MX": "Reunión",
		"es-NI": "Reunión",
		"es-PA": "Reunión",
		"es-PE": "Reunión",
		"es-PR": "Reunión",
		"es-PY": "Reunión",
		"es-SV": "Reunión",
		"es-US": "Reunión",
		"es-UY": "Reunión",
		"es-VE": "Reunión",
		"fr-FR": "La Réunion",
		"fr-BE": "La Réunion",
		"fr-CH": "La Réunion",
		"fr-LU": "La Réunion",
		"fr-MC": "La Réunion",
		"fr-AD": "La Réunion",
		"fr-CA": "la Réunion",
		"it-IT": "Riunione",
		"it-CH": "Riunione",
		"it-SM": "Riunione",
		"it-VA": "Riunione",
		"de-DE": "Réunion",
		"de-AT": "Réunion",
		"de-CH": "Réunion",
		"de-BE": "Réunion",
		"de-LI": "Réunion",
		"de-LU": "Réunion",
		"nl-NL": "Réunion",
		"nl-BE": "Réunion",
		"sv-SE": "Réunion",
		"sv-FI": "Réunion",
		"da-DK": "Réunion",
		"nb-NO": "Réunion",
		"nn-NO": "Réunion",
		"fi-FI": "Réunion",
		"is-IS": "Réunion",
		"fo-FO": "Réunion",
		"et-EE": "Réunion",
		"lv-LV": "Reinjona",
		"lt-LT": "Reunjonas",
		"pl-PL": "Reunion",
		"cs-CZ": "Réunion",
		"sk-SK": "Réunion",
		"sl-SI": "Reunion",
		"hr-HR": "Réunion",
		"bs-BA": "Reunion",
		"sr-RS": "Реинион",
		"sr-BA": "Реунион",
		"sr-ME": "Reunion",
		"mk-MK": "Рејунион",
		"bg-BG": "Реюнион",
		"be-BY": "Рэюньён",
		"uk-UA": "Реюньйон",
		"ru-RU": "Реюньон",
		"el-GR": "Ρεϊνιόν",
		"el-CY": "Ρεϊνιόν",
		"ro-RO": "Réunion",
		"ro-MD": "Réunion",
		"hu-HU": "Réunion",
		"sq-AL": "Reunion",
		"sq-XK": "Reunion",
		"mt-MT": "Réunion",
		"ga-IE": "La Réunion",
		"cy-GB": "Réunion",
		"gd-GB": "Réunion",
		"lb-LU": "Réunion",
		"ca-ES": "Illa de la Reunió",
		"ca-AD": "Illa de la Reunió",
		"ca-FR": "Illa de la Reunió",
		"ca-IT": "Illa de la Reunió",
		"eu-ES": "Reunion",
		"eu-FR": "Reunion",
		"gl-ES": "Reunión",
		"tr-TR": "Reunion",
		"tr-CY": "Reunion"
	},
	"callingCode": "262",
	"phoneMasks": [
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[26-9]"
			]
		}
	]
} satisfies Country;
