import type { Country } from './types.js';

export const ROU = {
	"code": "ROU",
	"labels": {
		"pt-BR": "Romênia",
		"pt-PT": "Roménia",
		"qu-PE": "Rumania",
		"qu-BO": "Rumania",
		"qu-EC": "Rumania",
		"chr-US": "ᎶᎹᏂᏯ",
		"hi-IN": "रोमानिया",
		"bn-IN": "রোমানিয়া",
		"bn-BD": "রোমানিয়া",
		"ta-IN": "ருமேனியா",
		"ta-LK": "ருமேனியா",
		"ta-SG": "ருமேனியா",
		"ta-MY": "ருமேனியா",
		"te-IN": "రోమేనియా",
		"mr-IN": "रोमानिया",
		"gu-IN": "રોમાનિયા",
		"kn-IN": "ರೊಮೇನಿಯಾ",
		"ml-IN": "റൊമാനിയ",
		"pa-IN": "ਰੋਮਾਨੀਆ",
		"ur-IN": "رومانیہ",
		"ur-PK": "رومانیہ",
		"or-IN": "ରୋମାନିଆ",
		"as-IN": "ৰোমানিয়া",
		"ne-IN": "रोमेनिया",
		"ne-NP": "रोमेनिया",
		"si-LK": "රුමේනියාව",
		"kok-IN": "रोमानीया",
		"ks-IN": "رومانِیا",
		"brx-IN": "रमानिया",
		"mai-IN": "रोमानिया",
		"dz-BT": "རོ་མེ་ནི་ཡ",
		"ja-JP": "ルーマニア",
		"ko-KR": "루마니아",
		"ko-KP": "루마니아",
		"zh-CN": "罗马尼亚",
		"zh-Hans-CN": "罗马尼亚",
		"zh-Hant-TW": "羅馬尼亞",
		"zh-TW": "羅馬尼亞",
		"zh-HK": "羅馬尼亞",
		"zh-MO": "羅馬尼亞",
		"zh-SG": "罗马尼亚",
		"yue-Hant-HK": "羅馬尼亞",
		"yue-Hans-CN": "罗马尼亚",
		"mn-MN": "Румын",
		"ug-CN": "رومىنىيە",
		"th-TH": "โรมาเนีย",
		"lo-LA": "ໂຣແມເນຍ",
		"km-KH": "រូម៉ានី",
		"my-MM": "ရိုမေးနီးယား",
		"vi-VN": "Romania",
		"id-ID": "Rumania",
		"ms-MY": "Romania",
		"ms-SG": "Romania",
		"ms-BN": "Romania",
		"jv-ID": "Ruméni",
		"fil-PH": "Romania",
		"ceb-PH": "Romania",
		"ka-GE": "რუმინეთი",
		"hy-AM": "Ռումինիա",
		"az-AZ": "Rumıniya",
		"az-Cyrl-AZ": "Румынија",
		"kk-KZ": "Румыния",
		"ky-KG": "Румыния",
		"uz-UZ": "Ruminiya",
		"tg-TJ": "Руминия",
		"tk-TM": "Rumyniýa",
		"fa-IR": "رومانی",
		"fa-AF": "رومانیا",
		"ps-AF": "رومانیا",
		"ps-PK": "رومانیا",
		"he-IL": "רומניה",
		"ar-SA": "رومانيا",
		"ar-AE": "رومانيا",
		"ar-QA": "رومانيا",
		"ar-BH": "رومانيا",
		"ar-KW": "رومانيا",
		"ar-OM": "رومانيا",
		"ar-YE": "رومانيا",
		"ar-IQ": "رومانيا",
		"ar-JO": "رومانيا",
		"ar-LB": "رومانيا",
		"ar-SY": "رومانيا",
		"ar-PS": "رومانيا",
		"en-US": "Romania",
		"en-GB": "Romania",
		"en-IE": "Romania",
		"en-MT": "Romania",
		"en-GI": "Romania",
		"en-CY": "Romania",
		"en-JE": "Romania",
		"en-GG": "Romania",
		"en-IM": "Romania",
		"en-CA": "Romania",
		"en-AU": "Romania",
		"en-NZ": "Romania",
		"en-ZA": "Romania",
		"en-IN": "Romania",
		"en-SG": "Romania",
		"pt-AO": "Roménia",
		"pt-MZ": "Roménia",
		"pt-CV": "Roménia",
		"pt-GW": "Roménia",
		"pt-ST": "Roménia",
		"pt-TL": "Roménia",
		"pt-MO": "Roménia",
		"es-ES": "Rumanía",
		"es-419": "Rumania",
		"es-AD": "Rumanía",
		"es-GI": "Rumanía",
		"es-AR": "Rumania",
		"es-BO": "Rumania",
		"es-BR": "Rumania",
		"es-BZ": "Rumania",
		"es-CL": "Rumania",
		"es-CO": "Rumania",
		"es-CR": "Rumania",
		"es-CU": "Rumania",
		"es-DO": "Rumania",
		"es-EC": "Rumania",
		"es-GT": "Rumania",
		"es-HN": "Rumania",
		"es-MX": "Rumania",
		"es-NI": "Rumania",
		"es-PA": "Rumania",
		"es-PE": "Rumania",
		"es-PR": "Rumania",
		"es-PY": "Rumania",
		"es-SV": "Rumania",
		"es-US": "Rumania",
		"es-UY": "Rumania",
		"es-VE": "Rumania",
		"fr-FR": "Roumanie",
		"fr-BE": "Roumanie",
		"fr-CH": "Roumanie",
		"fr-LU": "Roumanie",
		"fr-MC": "Roumanie",
		"fr-AD": "Roumanie",
		"fr-CA": "Roumanie",
		"it-IT": "Romania",
		"it-CH": "Romania",
		"it-SM": "Romania",
		"it-VA": "Romania",
		"de-DE": "Rumänien",
		"de-AT": "Rumänien",
		"de-CH": "Rumänien",
		"de-BE": "Rumänien",
		"de-LI": "Rumänien",
		"de-LU": "Rumänien",
		"nl-NL": "Roemenië",
		"nl-BE": "Roemenië",
		"sv-SE": "Rumänien",
		"sv-FI": "Rumänien",
		"da-DK": "Rumænien",
		"nb-NO": "Romania",
		"nn-NO": "Romania",
		"fi-FI": "Romania",
		"is-IS": "Rúmenía",
		"fo-FO": "Rumenia",
		"et-EE": "Rumeenia",
		"lv-LV": "Rumānija",
		"lt-LT": "Rumunija",
		"pl-PL": "Rumunia",
		"cs-CZ": "Rumunsko",
		"sk-SK": "Rumunsko",
		"sl-SI": "Romunija",
		"hr-HR": "Rumunjska",
		"bs-BA": "Rumunija",
		"sr-RS": "Румунија",
		"sr-BA": "Румунија",
		"sr-ME": "Rumunija",
		"mk-MK": "Романија",
		"bg-BG": "Румъния",
		"be-BY": "Румынія",
		"uk-UA": "Румунія",
		"ru-RU": "Румыния",
		"el-GR": "Ρουμανία",
		"el-CY": "Ρουμανία",
		"ro-RO": "România",
		"ro-MD": "România",
		"hu-HU": "Románia",
		"sq-AL": "Rumani",
		"sq-XK": "Rumani",
		"mt-MT": "ir-Rumanija",
		"ga-IE": "an Rómáin",
		"cy-GB": "Rwmania",
		"gd-GB": "Romàinia",
		"lb-LU": "Rumänien",
		"ca-ES": "Romania",
		"ca-AD": "Romania",
		"ca-FR": "Romania",
		"ca-IT": "Romania",
		"eu-ES": "Errumania",
		"eu-FR": "Errumania",
		"gl-ES": "Romanía",
		"tr-TR": "Romanya",
		"tr-CY": "Romanya"
	},
	"callingCode": "40",
	"phoneMasks": [
		{
			"mask": "## ####",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"219|31"
			]
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"2[3-6]",
				"2[3-6]\\d9"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[23]1"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[236-9]"
			]
		}
	]
} satisfies Country;
