import type { Country } from './types.js';

export const SAU = {
	"code": "SAU",
	"labels": {
		"pt-BR": "Arábia Saudita",
		"pt-PT": "Arábia Saudita",
		"qu-PE": "Arabia Saudí",
		"qu-BO": "Arabia Saudí",
		"qu-EC": "Arabia Saudí",
		"chr-US": "ᏌᎤᏗ ᎡᎴᏈᎠ",
		"hi-IN": "सऊदी अरब",
		"bn-IN": "সৌদি আরব",
		"bn-BD": "সৌদি আরব",
		"ta-IN": "சவுதி அரேபியா",
		"ta-LK": "சவுதி அரேபியா",
		"ta-SG": "சவுதி அரேபியா",
		"ta-MY": "சவுதி அரேபியா",
		"te-IN": "సౌదీ అరేబియా",
		"mr-IN": "सौदी अरब",
		"gu-IN": "સાઉદી અરેબિયા",
		"kn-IN": "ಸೌದಿ ಅರೇಬಿಯಾ",
		"ml-IN": "സൗദി അറേബ്യ",
		"pa-IN": "ਸਾਊਦੀ ਅਰਬ",
		"ur-IN": "سعودی عرب",
		"ur-PK": "سعودی عرب",
		"or-IN": "ସାଉଦି ଆରବିଆ",
		"as-IN": "চৌডি আৰবিয়া",
		"ne-IN": "साउदी अरब",
		"ne-NP": "साउदी अरब",
		"si-LK": "සෞදි අරාබිය",
		"kok-IN": "सऊदी अरेबिया",
		"ks-IN": "سعودی عرب",
		"brx-IN": "साउदि आराबिया",
		"mai-IN": "सऊदी अरब",
		"dz-BT": "སཱཝ་དི་ ཨ་རེ་བྷི་ཡ",
		"ja-JP": "サウジアラビア",
		"ko-KR": "사우디아라비아",
		"ko-KP": "사우디아라비아",
		"zh-CN": "沙特阿拉伯",
		"zh-Hans-CN": "沙特阿拉伯",
		"zh-Hant-TW": "沙烏地阿拉伯",
		"zh-TW": "沙烏地阿拉伯",
		"zh-HK": "沙地阿拉伯",
		"zh-MO": "沙地阿拉伯",
		"zh-SG": "沙特阿拉伯",
		"yue-Hant-HK": "沙特阿拉伯",
		"yue-Hans-CN": "沙乌地阿拉伯",
		"mn-MN": "Саудын Араб",
		"ug-CN": "سەئۇدىي ئەرەبىستان",
		"th-TH": "ซาอุดีอาระเบีย",
		"lo-LA": "ຊາອຸດິ ອາຣາເບຍ",
		"km-KH": "អារ៉ាប៊ីសាអូឌីត",
		"my-MM": "ဆော်ဒီအာရေးဘီးယား",
		"vi-VN": "Ả Rập Xê-út",
		"id-ID": "Arab Saudi",
		"ms-MY": "Arab Saudi",
		"ms-SG": "Arab Saudi",
		"ms-BN": "Arab Saudi",
		"jv-ID": "Arab Saudi",
		"fil-PH": "Saudi Arabia",
		"ceb-PH": "Saudi Arabia",
		"ka-GE": "საუდის არაბეთი",
		"hy-AM": "Սաուդյան Արաբիա",
		"az-AZ": "Səudiyyə Ərəbistanı",
		"az-Cyrl-AZ": "Сәудијјә Әрәбистаны",
		"kk-KZ": "Сауд Арабиясы",
		"ky-KG": "Сауд Арабиясы",
		"uz-UZ": "Saudiya Arabistoni",
		"tg-TJ": "Арабистони Саудӣ",
		"tk-TM": "Saud Arabystany",
		"fa-IR": "عربستان سعودی",
		"fa-AF": "عربستان سعودی",
		"ps-AF": "سعودي عربستان",
		"ps-PK": "سعودي عربستان",
		"he-IL": "ערב הסעודית",
		"ar-SA": "المملكة العربية السعودية",
		"ar-AE": "المملكة العربية السعودية",
		"ar-QA": "المملكة العربية السعودية",
		"ar-BH": "المملكة العربية السعودية",
		"ar-KW": "المملكة العربية السعودية",
		"ar-OM": "المملكة العربية السعودية",
		"ar-YE": "المملكة العربية السعودية",
		"ar-IQ": "المملكة العربية السعودية",
		"ar-JO": "المملكة العربية السعودية",
		"ar-LB": "المملكة العربية السعودية",
		"ar-SY": "المملكة العربية السعودية",
		"ar-PS": "المملكة العربية السعودية",
		"en-US": "Saudi Arabia",
		"en-GB": "Saudi Arabia",
		"en-IE": "Saudi Arabia",
		"en-MT": "Saudi Arabia",
		"en-GI": "Saudi Arabia",
		"en-CY": "Saudi Arabia",
		"en-JE": "Saudi Arabia",
		"en-GG": "Saudi Arabia",
		"en-IM": "Saudi Arabia",
		"en-CA": "Saudi Arabia",
		"en-AU": "Saudi Arabia",
		"en-NZ": "Saudi Arabia",
		"en-ZA": "Saudi Arabia",
		"en-IN": "Saudi Arabia",
		"en-SG": "Saudi Arabia",
		"pt-AO": "Arábia Saudita",
		"pt-MZ": "Arábia Saudita",
		"pt-CV": "Arábia Saudita",
		"pt-GW": "Arábia Saudita",
		"pt-ST": "Arábia Saudita",
		"pt-TL": "Arábia Saudita",
		"pt-MO": "Arábia Saudita",
		"es-ES": "Arabia Saudí",
		"es-419": "Arabia Saudita",
		"es-AD": "Arabia Saudí",
		"es-GI": "Arabia Saudí",
		"es-AR": "Arabia Saudita",
		"es-BO": "Arabia Saudita",
		"es-BR": "Arabia Saudita",
		"es-BZ": "Arabia Saudita",
		"es-CL": "Arabia Saudita",
		"es-CO": "Arabia Saudita",
		"es-CR": "Arabia Saudita",
		"es-CU": "Arabia Saudita",
		"es-DO": "Arabia Saudita",
		"es-EC": "Arabia Saudita",
		"es-GT": "Arabia Saudita",
		"es-HN": "Arabia Saudita",
		"es-MX": "Arabia Saudita",
		"es-NI": "Arabia Saudita",
		"es-PA": "Arabia Saudita",
		"es-PE": "Arabia Saudita",
		"es-PR": "Arabia Saudita",
		"es-PY": "Arabia Saudita",
		"es-SV": "Arabia Saudita",
		"es-US": "Arabia Saudita",
		"es-UY": "Arabia Saudita",
		"es-VE": "Arabia Saudita",
		"fr-FR": "Arabie saoudite",
		"fr-BE": "Arabie saoudite",
		"fr-CH": "Arabie saoudite",
		"fr-LU": "Arabie saoudite",
		"fr-MC": "Arabie saoudite",
		"fr-AD": "Arabie saoudite",
		"fr-CA": "Arabie saoudite",
		"it-IT": "Arabia Saudita",
		"it-CH": "Arabia Saudita",
		"it-SM": "Arabia Saudita",
		"it-VA": "Arabia Saudita",
		"de-DE": "Saudi-Arabien",
		"de-AT": "Saudi-Arabien",
		"de-CH": "Saudi-Arabien",
		"de-BE": "Saudi-Arabien",
		"de-LI": "Saudi-Arabien",
		"de-LU": "Saudi-Arabien",
		"nl-NL": "Saoedi-Arabië",
		"nl-BE": "Saoedi-Arabië",
		"sv-SE": "Saudiarabien",
		"sv-FI": "Saudiarabien",
		"da-DK": "Saudi-Arabien",
		"nb-NO": "Saudi-Arabia",
		"nn-NO": "Saudi-Arabia",
		"fi-FI": "Saudi-Arabia",
		"is-IS": "Sádi-Arabía",
		"fo-FO": "Saudiarabia",
		"et-EE": "Saudi Araabia",
		"lv-LV": "Saūda Arābija",
		"lt-LT": "Saudo Arabija",
		"pl-PL": "Arabia Saudyjska",
		"cs-CZ": "Saúdská Arábie",
		"sk-SK": "Saudská Arábia",
		"sl-SI": "Saudova Arabija",
		"hr-HR": "Saudijska Arabija",
		"bs-BA": "Saudijska Arabija",
		"sr-RS": "Саудијска Арабија",
		"sr-BA": "Саудијска Арабија",
		"sr-ME": "Saudijska Arabija",
		"mk-MK": "Саудиска Арабија",
		"bg-BG": "Саудитска Арабия",
		"be-BY": "Саудаўская Аравія",
		"uk-UA": "Саудівська Аравія",
		"ru-RU": "Саудовская Аравия",
		"el-GR": "Σαουδική Αραβία",
		"el-CY": "Σαουδική Αραβία",
		"ro-RO": "Arabia Saudită",
		"ro-MD": "Arabia Saudită",
		"hu-HU": "Szaúd-Arábia",
		"sq-AL": "Arabi Saudite",
		"sq-XK": "Arabi Saudite",
		"mt-MT": "l-Arabja Sawdija",
		"ga-IE": "an Araib Shádach",
		"cy-GB": "Saudi Arabia",
		"gd-GB": "Aràibia nan Sabhd",
		"lb-LU": "Saudi-Arabien",
		"ca-ES": "Aràbia Saudí",
		"ca-AD": "Aràbia Saudí",
		"ca-FR": "Aràbia Saudí",
		"ca-IT": "Aràbia Saudí",
		"eu-ES": "Saudi Arabia",
		"eu-FR": "Saudi Arabia",
		"gl-ES": "Arabia Saudita",
		"tr-TR": "Suudi Arabistan",
		"tr-CY": "Suudi Arabistan"
	},
	"callingCode": "966",
	"phoneMasks": [
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"5"
			]
		},
		{
			"mask": "#### #####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"9"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"81"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
