import type { Country } from './types.js';

export const SJM = {
	"code": "SJM",
	"labels": {
		"pt-BR": "Svalbard e Jan Mayen",
		"pt-PT": "Svalbard e Jan Mayen",
		"qu-PE": "Svalbard y Jan Mayen",
		"qu-BO": "Svalbard y Jan Mayen",
		"qu-EC": "Svalbard y Jan Mayen",
		"chr-US": "ᏍᏩᎵᏆᎵᏗ ᎠᎴ ᏤᏂ ᎹᏰᏂ",
		"hi-IN": "स्वालबार्ड और जान मायेन",
		"bn-IN": "স্বালবার্ড ও জান মেয়েন",
		"bn-BD": "স্বালবার্ড ও জান মেয়েন",
		"ta-IN": "ஸ்வல்பார்டு & ஜான் மேயன்",
		"ta-LK": "ஸ்வல்பார்டு & ஜான் மேயன்",
		"ta-SG": "ஸ்வல்பார்டு & ஜான் மேயன்",
		"ta-MY": "ஸ்வல்பார்டு & ஜான் மேயன்",
		"te-IN": "స్వాల్‌బార్డ్ మరియు జాన్ మాయెన్",
		"mr-IN": "स्वालबर्ड आणि जान मायेन",
		"gu-IN": "સ્વાલબર્ડ અને જેન મેયન",
		"kn-IN": "ಸ್ವಾಲ್ಬಾರ್ಡ್ ಮತ್ತು ಜಾನ್ ಮೆಯನ್",
		"ml-IN": "സ്വാൽബാഡും ജാൻ മായേനും",
		"pa-IN": "ਸਵਾਲਬਰਡ ਅਤੇ ਜਾਨ ਮਾਯੇਨ",
		"ur-IN": "سوالبرڈ اور جان ماین",
		"ur-PK": "سوالبرڈ اور جان ماین",
		"or-IN": "ସାଲବାର୍ଡ ଏବଂ ଜାନ୍‌ ମାୟେନ୍‌",
		"as-IN": "চাভালবাৰ্ড আৰু জন মেয়ন",
		"ne-IN": "सभाल्बार्ड र जान मायेन",
		"ne-NP": "सभाल्बार्ड र जान मायेन",
		"si-LK": "ස්වෙල්බර්ඩ් සහ ජේන් මයේන්",
		"kok-IN": "स्वालबार्ड आनी जान मेयन",
		"ks-IN": "سَوالبریڑ تہٕ جان ماییڑ",
		"brx-IN": "स्भालबार्ड आरो जान मायेन",
		"mai-IN": "स्वालबार्ड आ जान मायेन",
		"dz-BT": "སྭཱལ་བྷརྡ་ ཨེནཌ་ ཇཱན་མ་ཡེན",
		"ja-JP": "スバールバル諸島・ヤンマイエン島",
		"ko-KR": "스발바르제도-얀마웬섬",
		"ko-KP": "스발바르제도-얀마웬섬",
		"zh-CN": "斯瓦尔巴和扬马延",
		"zh-Hans-CN": "斯瓦尔巴和扬马延",
		"zh-Hant-TW": "挪威屬斯瓦巴及尖棉",
		"zh-TW": "挪威屬斯瓦巴及尖棉",
		"zh-HK": "斯瓦爾巴特群島及揚馬延島",
		"zh-MO": "斯瓦爾巴特群島及揚馬延島",
		"zh-SG": "斯瓦尔巴和扬马延",
		"yue-Hant-HK": "斯瓦爾巴特群島同揚馬延島",
		"yue-Hans-CN": "斯瓦尔巴特群岛同扬马延岛",
		"mn-MN": "Свалбард ба Ян Майен",
		"ug-CN": "سىۋالبارد ۋە يان مايېن",
		"th-TH": "สฟาลบาร์และยานไมเอน",
		"lo-LA": "ສະວາບາ ແລະ ແຢນ ມາເຢນ",
		"km-KH": "ស្វាលបាដ និង ហ្សង់ម៉ាយេន",
		"my-MM": "စဗိုလ်ဘတ်နှင့်ဂျန်မေရန်",
		"vi-VN": "Svalbard và Jan Mayen",
		"id-ID": "Kepulauan Svalbard dan Jan Mayen",
		"ms-MY": "Svalbard dan Jan Mayen",
		"ms-SG": "Svalbard dan Jan Mayen",
		"ms-BN": "Svalbard dan Jan Mayen",
		"jv-ID": "Svalbard lan Jan Mayen",
		"fil-PH": "Svalbard & Jan Mayen",
		"ceb-PH": "Svalbard & Jan Mayen",
		"ka-GE": "შპიცბერგენი და იან-მაიენი",
		"hy-AM": "Սվալբարդ և Յան Մայեն",
		"az-AZ": "Svalbard və Yan-Mayen",
		"az-Cyrl-AZ": "Свалбард вә Јан-Мајен",
		"kk-KZ": "Шпицберген және Ян-Майен",
		"ky-KG": "Шпицберген жана Ян-Майен",
		"uz-UZ": "Shpitsbergen va Yan-Mayen",
		"tg-TJ": "Шпитсберген ва Ян Майен",
		"tk-TM": "Şpisbergen we Ýan-Maýen",
		"fa-IR": "سوالبارد و یان ماین",
		"fa-AF": "اسوالبارد و جان ماین",
		"ps-AF": "سوالبارد او جان ميين",
		"ps-PK": "سوالبارد او جان ميين",
		"he-IL": "סבאלברד ויאן מאיין",
		"ar-SA": "سفالبارد وجان ماين",
		"ar-AE": "سفالبارد وجان ماين",
		"ar-QA": "سفالبارد وجان ماين",
		"ar-BH": "سفالبارد وجان ماين",
		"ar-KW": "سفالبارد وجان ماين",
		"ar-OM": "سفالبارد وجان ماين",
		"ar-YE": "سفالبارد وجان ماين",
		"ar-IQ": "سفالبارد وجان ماين",
		"ar-JO": "سفالبارد وجان ماين",
		"ar-LB": "سفالبارد وجان ماين",
		"ar-SY": "سفالبارد وجان ماين",
		"ar-PS": "سفالبارد وجان ماين",
		"en-US": "Svalbard & Jan Mayen",
		"en-GB": "Svalbard & Jan Mayen",
		"en-IE": "Svalbard & Jan Mayen",
		"en-MT": "Svalbard & Jan Mayen",
		"en-GI": "Svalbard & Jan Mayen",
		"en-CY": "Svalbard & Jan Mayen",
		"en-JE": "Svalbard & Jan Mayen",
		"en-GG": "Svalbard & Jan Mayen",
		"en-IM": "Svalbard & Jan Mayen",
		"en-CA": "Svalbard and Jan Mayen",
		"en-AU": "Svalbard & Jan Mayen",
		"en-NZ": "Svalbard & Jan Mayen",
		"en-ZA": "Svalbard & Jan Mayen",
		"en-IN": "Svalbard & Jan Mayen",
		"en-SG": "Svalbard & Jan Mayen",
		"pt-AO": "Svalbard e Jan Mayen",
		"pt-MZ": "Svalbard e Jan Mayen",
		"pt-CV": "Svalbard e Jan Mayen",
		"pt-GW": "Svalbard e Jan Mayen",
		"pt-ST": "Svalbard e Jan Mayen",
		"pt-TL": "Svalbard e Jan Mayen",
		"pt-MO": "Svalbard e Jan Mayen",
		"es-ES": "Svalbard y Jan Mayen",
		"es-419": "Svalbard y Jan Mayen",
		"es-AD": "Svalbard y Jan Mayen",
		"es-GI": "Svalbard y Jan Mayen",
		"es-AR": "Svalbard y Jan Mayen",
		"es-BO": "Svalbard y Jan Mayen",
		"es-BR": "Svalbard y Jan Mayen",
		"es-BZ": "Svalbard y Jan Mayen",
		"es-CL": "Svalbard y Jan Mayen",
		"es-CO": "Svalbard y Jan Mayen",
		"es-CR": "Svalbard y Jan Mayen",
		"es-CU": "Svalbard y Jan Mayen",
		"es-DO": "Svalbard y Jan Mayen",
		"es-EC": "Svalbard y Jan Mayen",
		"es-GT": "Svalbard y Jan Mayen",
		"es-HN": "Svalbard y Jan Mayen",
		"es-MX": "Svalbard y Jan Mayen",
		"es-NI": "Svalbard y Jan Mayen",
		"es-PA": "Svalbard y Jan Mayen",
		"es-PE": "Svalbard y Jan Mayen",
		"es-PR": "Svalbard y Jan Mayen",
		"es-PY": "Svalbard y Jan Mayen",
		"es-SV": "Svalbard y Jan Mayen",
		"es-US": "Svalbard y Jan Mayen",
		"es-UY": "Svalbard y Jan Mayen",
		"es-VE": "Svalbard y Jan Mayen",
		"fr-FR": "Svalbard et Jan Mayen",
		"fr-BE": "Svalbard et Jan Mayen",
		"fr-CH": "Svalbard et Jan Mayen",
		"fr-LU": "Svalbard et Jan Mayen",
		"fr-MC": "Svalbard et Jan Mayen",
		"fr-AD": "Svalbard et Jan Mayen",
		"fr-CA": "Svalbard et Jan Mayen",
		"it-IT": "Svalbard e Jan Mayen",
		"it-CH": "Svalbard e Jan Mayen",
		"it-SM": "Svalbard e Jan Mayen",
		"it-VA": "Svalbard e Jan Mayen",
		"de-DE": "Spitzbergen und Jan Mayen",
		"de-AT": "Svalbard und Jan Mayen",
		"de-CH": "Spitzbergen und Jan Mayen",
		"de-BE": "Spitzbergen und Jan Mayen",
		"de-LI": "Spitzbergen und Jan Mayen",
		"de-LU": "Spitzbergen und Jan Mayen",
		"nl-NL": "Spitsbergen en Jan Mayen",
		"nl-BE": "Spitsbergen en Jan Mayen",
		"sv-SE": "Svalbard och Jan Mayen",
		"sv-FI": "Svalbard och Jan Mayen",
		"da-DK": "Svalbard og Jan Mayen",
		"nb-NO": "Svalbard og Jan Mayen",
		"nn-NO": "Svalbard og Jan Mayen",
		"fi-FI": "Huippuvuoret ja Jan Mayen",
		"is-IS": "Svalbarði og Jan Mayen",
		"fo-FO": "Svalbard & Jan Mayen",
		"et-EE": "Svalbard ja Jan Mayen",
		"lv-LV": "Svalbāra un Jana Majena sala",
		"lt-LT": "Svalbardas ir Janas Majenas",
		"pl-PL": "Svalbard i Jan Mayen",
		"cs-CZ": "Špicberky a Jan Mayen",
		"sk-SK": "Svalbard a Jan Mayen",
		"sl-SI": "Svalbard in Jan Mayen",
		"hr-HR": "Svalbard i Jan Mayen",
		"bs-BA": "Svalbard i Jan Mayen",
		"sr-RS": "Свалбард и Јан Мајен",
		"sr-BA": "Свалбард и Јан Мајен",
		"sr-ME": "Svalbard i Jan Majen",
		"mk-MK": "Свалбард и Јан Мајен",
		"bg-BG": "Свалбард и Ян Майен",
		"be-BY": "Шпіцберген і Ян-Маен",
		"uk-UA": "Шпіцберген та Ян-Маєн",
		"ru-RU": "Шпицберген и Ян-Майен",
		"el-GR": "Σβάλμπαρντ και Γιαν Μαγιέν",
		"el-CY": "Σβάλμπαρντ και Γιαν Μαγιέν",
		"ro-RO": "Svalbard și Jan Mayen",
		"ro-MD": "Svalbard și Jan Mayen",
		"hu-HU": "Svalbard és Jan Mayen",
		"sq-AL": "Svalbard e Jan-Majen",
		"sq-XK": "Svalbard e Jan-Majen",
		"mt-MT": "Svalbard u Jan Mayen",
		"ga-IE": "Svalbard agus Jan Mayen",
		"cy-GB": "Svalbard a Jan Mayen",
		"gd-GB": "Svalbard is Jan Mayen",
		"lb-LU": "Svalbard a Jan Mayen",
		"ca-ES": "Svalbard i Jan Mayen",
		"ca-AD": "Svalbard i Jan Mayen",
		"ca-FR": "Svalbard i Jan Mayen",
		"ca-IT": "Svalbard i Jan Mayen",
		"eu-ES": "Svalbard eta Jan Mayen uharteak",
		"eu-FR": "Svalbard eta Jan Mayen uharteak",
		"gl-ES": "Svalbard e Jan Mayen",
		"tr-TR": "Svalbard ve Jan Mayen",
		"tr-CY": "Svalbard ve Jan Mayen"
	},
	"callingCode": "4779",
	"phoneMasks": [
		{
			"mask": "###",
			"minLength": 3,
			"maxLength": 3
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		}
	]
} satisfies Country;
