import type { Country } from './types.js';

export const SLE = {
	"code": "SLE",
	"labels": {
		"pt-BR": "Serra Leoa",
		"pt-PT": "Serra Leoa",
		"qu-PE": "Sierra Leona",
		"qu-BO": "Sierra Leona",
		"qu-EC": "Sierra Leona",
		"chr-US": "ᏏᎡᎳ ᎴᎣᏂ",
		"hi-IN": "सिएरा लियोन",
		"bn-IN": "সিয়েরা লিওন",
		"bn-BD": "সিয়েরা লিওন",
		"ta-IN": "சியாரா லியோன்",
		"ta-LK": "சியாரா லியோன்",
		"ta-SG": "சியாரா லியோன்",
		"ta-MY": "சியாரா லியோன்",
		"te-IN": "సియెర్రా లియాన్",
		"mr-IN": "सिएरा लिओन",
		"gu-IN": "સીએરા લેઓન",
		"kn-IN": "ಸಿಯೆರ್ರಾ ಲಿಯೋನ್",
		"ml-IN": "സിയെറ ലിയോൺ",
		"pa-IN": "ਸਿਏਰਾ ਲਿਓਨ",
		"ur-IN": "سیرالیون",
		"ur-PK": "سیرالیون",
		"or-IN": "ସିଏରା ଲିଓନ",
		"as-IN": "চিয়েৰা লিঅ’ন",
		"ne-IN": "सिएर्रा लिओन",
		"ne-NP": "सिएर्रा लिओन",
		"si-LK": "සියරාලියෝන්",
		"kok-IN": "सिएरा लियॉन",
		"ks-IN": "سیرا لیون",
		"brx-IN": "सियेरा लेओन",
		"mai-IN": "सियरा लियोन",
		"dz-BT": "སི་ར་ ལི་འོན",
		"ja-JP": "シエラレオネ",
		"ko-KR": "시에라리온",
		"ko-KP": "시에라리온",
		"zh-CN": "塞拉利昂",
		"zh-Hans-CN": "塞拉利昂",
		"zh-Hant-TW": "獅子山",
		"zh-TW": "獅子山",
		"zh-HK": "塞拉利昂",
		"zh-MO": "塞拉利昂",
		"zh-SG": "塞拉利昂",
		"yue-Hant-HK": "獅子山",
		"yue-Hans-CN": "狮子山",
		"mn-MN": "Сьерра-Леоне",
		"ug-CN": "سېررالېئون",
		"th-TH": "เซียร์ราลีโอน",
		"lo-LA": "ເຊຍຣາ ລີໂອນ",
		"km-KH": "សៀរ៉ាឡេអូន",
		"my-MM": "ဆီယာရာ လီယွန်း",
		"vi-VN": "Sierra Leone",
		"id-ID": "Sierra Leone",
		"ms-MY": "Sierra Leone",
		"ms-SG": "Sierra Leone",
		"ms-BN": "Sierra Leone",
		"jv-ID": "Siéra Léoné",
		"fil-PH": "Sierra Leone",
		"ceb-PH": "Sierra Leone",
		"ka-GE": "სიერა-ლეონე",
		"hy-AM": "Սիեռա Լեոնե",
		"az-AZ": "Syerra-Leone",
		"az-Cyrl-AZ": "Сјерра-Леоне",
		"kk-KZ": "Сьерра-Леоне",
		"ky-KG": "Сьерра-Леоне",
		"uz-UZ": "Syerra-Leone",
		"tg-TJ": "Сиерра-Леоне",
		"tk-TM": "Sýerra-Leone",
		"fa-IR": "سیرالئون",
		"fa-AF": "سیرالیون",
		"ps-AF": "سییرا لیون",
		"ps-PK": "سییرا لیون",
		"he-IL": "סיירה לאון",
		"ar-SA": "سيراليون",
		"ar-AE": "سيراليون",
		"ar-QA": "سيراليون",
		"ar-BH": "سيراليون",
		"ar-KW": "سيراليون",
		"ar-OM": "سيراليون",
		"ar-YE": "سيراليون",
		"ar-IQ": "سيراليون",
		"ar-JO": "سيراليون",
		"ar-LB": "سيراليون",
		"ar-SY": "سيراليون",
		"ar-PS": "سيراليون",
		"en-US": "Sierra Leone",
		"en-GB": "Sierra Leone",
		"en-IE": "Sierra Leone",
		"en-MT": "Sierra Leone",
		"en-GI": "Sierra Leone",
		"en-CY": "Sierra Leone",
		"en-JE": "Sierra Leone",
		"en-GG": "Sierra Leone",
		"en-IM": "Sierra Leone",
		"en-CA": "Sierra Leone",
		"en-AU": "Sierra Leone",
		"en-NZ": "Sierra Leone",
		"en-ZA": "Sierra Leone",
		"en-IN": "Sierra Leone",
		"en-SG": "Sierra Leone",
		"pt-AO": "Serra Leoa",
		"pt-MZ": "Serra Leoa",
		"pt-CV": "Serra Leoa",
		"pt-GW": "Serra Leoa",
		"pt-ST": "Serra Leoa",
		"pt-TL": "Serra Leoa",
		"pt-MO": "Serra Leoa",
		"es-ES": "Sierra Leona",
		"es-419": "Sierra Leona",
		"es-AD": "Sierra Leona",
		"es-GI": "Sierra Leona",
		"es-AR": "Sierra Leona",
		"es-BO": "Sierra Leona",
		"es-BR": "Sierra Leona",
		"es-BZ": "Sierra Leona",
		"es-CL": "Sierra Leona",
		"es-CO": "Sierra Leona",
		"es-CR": "Sierra Leona",
		"es-CU": "Sierra Leona",
		"es-DO": "Sierra Leona",
		"es-EC": "Sierra Leona",
		"es-GT": "Sierra Leona",
		"es-HN": "Sierra Leona",
		"es-MX": "Sierra Leona",
		"es-NI": "Sierra Leona",
		"es-PA": "Sierra Leona",
		"es-PE": "Sierra Leona",
		"es-PR": "Sierra Leona",
		"es-PY": "Sierra Leona",
		"es-SV": "Sierra Leona",
		"es-US": "Sierra Leona",
		"es-UY": "Sierra Leona",
		"es-VE": "Sierra Leona",
		"fr-FR": "Sierra Leone",
		"fr-BE": "Sierra Leone",
		"fr-CH": "Sierra Leone",
		"fr-LU": "Sierra Leone",
		"fr-MC": "Sierra Leone",
		"fr-AD": "Sierra Leone",
		"fr-CA": "Sierra Leone",
		"it-IT": "Sierra Leone",
		"it-CH": "Sierra Leone",
		"it-SM": "Sierra Leone",
		"it-VA": "Sierra Leone",
		"de-DE": "Sierra Leone",
		"de-AT": "Sierra Leone",
		"de-CH": "Sierra Leone",
		"de-BE": "Sierra Leone",
		"de-LI": "Sierra Leone",
		"de-LU": "Sierra Leone",
		"nl-NL": "Sierra Leone",
		"nl-BE": "Sierra Leone",
		"sv-SE": "Sierra Leone",
		"sv-FI": "Sierra Leone",
		"da-DK": "Sierra Leone",
		"nb-NO": "Sierra Leone",
		"nn-NO": "Sierra Leone",
		"fi-FI": "Sierra Leone",
		"is-IS": "Síerra Leóne",
		"fo-FO": "Sierra Leona",
		"et-EE": "Sierra Leone",
		"lv-LV": "Sjerraleone",
		"lt-LT": "Siera Leonė",
		"pl-PL": "Sierra Leone",
		"cs-CZ": "Sierra Leone",
		"sk-SK": "Sierra Leone",
		"sl-SI": "Sierra Leone",
		"hr-HR": "Sijera Leone",
		"bs-BA": "Sijera Leone",
		"sr-RS": "Сијера Леоне",
		"sr-BA": "Сијера Леоне",
		"sr-ME": "Sijera Leone",
		"mk-MK": "Сиера Леоне",
		"bg-BG": "Сиера Леоне",
		"be-BY": "Сьера-Леонэ",
		"uk-UA": "Сьєрра-Леоне",
		"ru-RU": "Сьерра-Леоне",
		"el-GR": "Σιέρα Λεόνε",
		"el-CY": "Σιέρα Λεόνε",
		"ro-RO": "Sierra Leone",
		"ro-MD": "Sierra Leone",
		"hu-HU": "Sierra Leone",
		"sq-AL": "Sierra-Leone",
		"sq-XK": "Sierra-Leone",
		"mt-MT": "Sierra Leone",
		"ga-IE": "Siarra Leon",
		"cy-GB": "Sierra Leone",
		"gd-GB": "Siarra Leòmhann",
		"lb-LU": "Sierra Leone",
		"ca-ES": "Sierra Leone",
		"ca-AD": "Sierra Leone",
		"ca-FR": "Sierra Leone",
		"ca-IT": "Sierra Leone",
		"eu-ES": "Sierra Leona",
		"eu-FR": "Sierra Leona",
		"gl-ES": "Serra Leoa",
		"tr-TR": "Sierra Leone",
		"tr-CY": "Sierra Leone"
	},
	"callingCode": "232",
	"phoneMasks": [
		{
			"mask": "## ######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[236-9]"
			]
		}
	]
} satisfies Country;
