import type { Country } from './types.js';

export const SLV = {
	"code": "SLV",
	"labels": {
		"pt-BR": "El Salvador",
		"pt-PT": "Salvador",
		"qu-PE": "El Salvador",
		"qu-BO": "El Salvador",
		"qu-EC": "El Salvador",
		"chr-US": "ᎡᎵᏌᎵᏆᏙᎵ",
		"hi-IN": "अल सल्वाडोर",
		"bn-IN": "এল সালভেদর",
		"bn-BD": "এল সালভেদর",
		"ta-IN": "எல் சால்வடார்",
		"ta-LK": "எல் சால்வடார்",
		"ta-SG": "எல் சால்வடார்",
		"ta-MY": "எல் சால்வடார்",
		"te-IN": "ఎల్ సాల్వడోర్",
		"mr-IN": "अल साल्वाडोर",
		"gu-IN": "એલ સેલ્વાડોર",
		"kn-IN": "ಎಲ್ ಸಾಲ್ವೇಡಾರ್",
		"ml-IN": "എൽ സാൽവദോർ",
		"pa-IN": "ਅਲ ਸਲਵਾਡੋਰ",
		"ur-IN": "ال سلواڈور",
		"ur-PK": "ال سلواڈور",
		"or-IN": "ଏଲ୍ ସାଲଭାଡୋର୍",
		"as-IN": "এল ছেলভেড’ৰ",
		"ne-IN": "एल् साल्भाडोर",
		"ne-NP": "एल् साल्भाडोर",
		"si-LK": "එල් සැල්වදෝරය",
		"kok-IN": "एल साल्वाडोर",
		"ks-IN": "ایل سلویڈر",
		"brx-IN": "एल साल्भाड’र",
		"mai-IN": "अल सल्वाडोर",
		"dz-BT": "ཨེལ་སལ་བ་ཌོར",
		"ja-JP": "エルサルバドル",
		"ko-KR": "엘살바도르",
		"ko-KP": "엘살바도르",
		"zh-CN": "萨尔瓦多",
		"zh-Hans-CN": "萨尔瓦多",
		"zh-Hant-TW": "薩爾瓦多",
		"zh-TW": "薩爾瓦多",
		"zh-HK": "薩爾瓦多",
		"zh-MO": "薩爾瓦多",
		"zh-SG": "萨尔瓦多",
		"yue-Hant-HK": "薩爾瓦多",
		"yue-Hans-CN": "萨尔瓦多",
		"mn-MN": "Эль Сальвадор",
		"ug-CN": "سالۋادور",
		"th-TH": "เอลซัลวาดอร์",
		"lo-LA": "ເອວ ຊໍວາດໍ",
		"km-KH": "អែលសាល់វ៉ាឌ័រ",
		"my-MM": "အယ်လ်ဆာဗေးဒိုး",
		"vi-VN": "El Salvador",
		"id-ID": "El Salvador",
		"ms-MY": "El Salvador",
		"ms-SG": "El Salvador",
		"ms-BN": "El Salvador",
		"jv-ID": "Èl Salvador",
		"fil-PH": "El Salvador",
		"ceb-PH": "El Salvador",
		"ka-GE": "სალვადორი",
		"hy-AM": "Սալվադոր",
		"az-AZ": "Salvador",
		"az-Cyrl-AZ": "Салвадор",
		"kk-KZ": "Сальвадор",
		"ky-KG": "Эль-Сальвадор",
		"uz-UZ": "Salvador",
		"tg-TJ": "Эл-Салвадор",
		"tk-TM": "Salwador",
		"fa-IR": "السالوادور",
		"fa-AF": "السلوادور",
		"ps-AF": "سالوېډور",
		"ps-PK": "سالوېډور",
		"he-IL": "אל סלבדור",
		"ar-SA": "السلفادور",
		"ar-AE": "السلفادور",
		"ar-QA": "السلفادور",
		"ar-BH": "السلفادور",
		"ar-KW": "السلفادور",
		"ar-OM": "السلفادور",
		"ar-YE": "السلفادور",
		"ar-IQ": "السلفادور",
		"ar-JO": "السلفادور",
		"ar-LB": "السلفادور",
		"ar-SY": "السلفادور",
		"ar-PS": "السلفادور",
		"en-US": "El Salvador",
		"en-GB": "El Salvador",
		"en-IE": "El Salvador",
		"en-MT": "El Salvador",
		"en-GI": "El Salvador",
		"en-CY": "El Salvador",
		"en-JE": "El Salvador",
		"en-GG": "El Salvador",
		"en-IM": "El Salvador",
		"en-CA": "El Salvador",
		"en-AU": "El Salvador",
		"en-NZ": "El Salvador",
		"en-ZA": "El Salvador",
		"en-IN": "El Salvador",
		"en-SG": "El Salvador",
		"pt-AO": "Salvador",
		"pt-MZ": "Salvador",
		"pt-CV": "Salvador",
		"pt-GW": "Salvador",
		"pt-ST": "Salvador",
		"pt-TL": "Salvador",
		"pt-MO": "Salvador",
		"es-ES": "El Salvador",
		"es-419": "El Salvador",
		"es-AD": "El Salvador",
		"es-GI": "El Salvador",
		"es-AR": "El Salvador",
		"es-BO": "El Salvador",
		"es-BR": "El Salvador",
		"es-BZ": "El Salvador",
		"es-CL": "El Salvador",
		"es-CO": "El Salvador",
		"es-CR": "El Salvador",
		"es-CU": "El Salvador",
		"es-DO": "El Salvador",
		"es-EC": "El Salvador",
		"es-GT": "El Salvador",
		"es-HN": "El Salvador",
		"es-MX": "El Salvador",
		"es-NI": "El Salvador",
		"es-PA": "El Salvador",
		"es-PE": "El Salvador",
		"es-PR": "El Salvador",
		"es-PY": "El Salvador",
		"es-SV": "El Salvador",
		"es-US": "El Salvador",
		"es-UY": "El Salvador",
		"es-VE": "El Salvador",
		"fr-FR": "Salvador",
		"fr-BE": "Salvador",
		"fr-CH": "Salvador",
		"fr-LU": "Salvador",
		"fr-MC": "Salvador",
		"fr-AD": "Salvador",
		"fr-CA": "Salvador",
		"it-IT": "El Salvador",
		"it-CH": "El Salvador",
		"it-SM": "El Salvador",
		"it-VA": "El Salvador",
		"de-DE": "El Salvador",
		"de-AT": "El Salvador",
		"de-CH": "El Salvador",
		"de-BE": "El Salvador",
		"de-LI": "El Salvador",
		"de-LU": "El Salvador",
		"nl-NL": "El Salvador",
		"nl-BE": "El Salvador",
		"sv-SE": "El Salvador",
		"sv-FI": "El Salvador",
		"da-DK": "El Salvador",
		"nb-NO": "El Salvador",
		"nn-NO": "El Salvador",
		"fi-FI": "El Salvador",
		"is-IS": "El Salvador",
		"fo-FO": "El Salvador",
		"et-EE": "El Salvador",
		"lv-LV": "Salvadora",
		"lt-LT": "Salvadoras",
		"pl-PL": "Salwador",
		"cs-CZ": "Salvador",
		"sk-SK": "Salvádor",
		"sl-SI": "Salvador",
		"hr-HR": "Salvador",
		"bs-BA": "Salvador",
		"sr-RS": "Салвадор",
		"sr-BA": "Салвадор",
		"sr-ME": "Salvador",
		"mk-MK": "Ел Салвадор",
		"bg-BG": "Салвадор",
		"be-BY": "Сальвадор",
		"uk-UA": "Сальвадор",
		"ru-RU": "Сальвадор",
		"el-GR": "Ελ Σαλβαδόρ",
		"el-CY": "Ελ Σαλβαδόρ",
		"ro-RO": "El Salvador",
		"ro-MD": "El Salvador",
		"hu-HU": "Salvador",
		"sq-AL": "Salvador",
		"sq-XK": "Salvador",
		"mt-MT": "El Salvador",
		"ga-IE": "An tSalvadóir",
		"cy-GB": "El Salvador",
		"gd-GB": "An Salbhador",
		"lb-LU": "El Salvador",
		"ca-ES": "El Salvador",
		"ca-AD": "El Salvador",
		"ca-FR": "El Salvador",
		"ca-IT": "El Salvador",
		"eu-ES": "El Salvador",
		"eu-FR": "El Salvador",
		"gl-ES": "O Salvador",
		"tr-TR": "El Salvador",
		"tr-CY": "El Salvador"
	},
	"callingCode": "503",
	"phoneMasks": [
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[89]"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[267]"
			]
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
