import type { Country } from './types.js';

export const SOM = {
	"code": "SOM",
	"labels": {
		"pt-BR": "Somália",
		"pt-PT": "Somália",
		"qu-PE": "Somalia",
		"qu-BO": "Somalia",
		"qu-EC": "Somalia",
		"chr-US": "ᏐᎹᎵ",
		"hi-IN": "सोमालिया",
		"bn-IN": "সোমালিয়া",
		"bn-BD": "সোমালিয়া",
		"ta-IN": "சோமாலியா",
		"ta-LK": "சோமாலியா",
		"ta-SG": "சோமாலியா",
		"ta-MY": "சோமாலியா",
		"te-IN": "సోమాలియా",
		"mr-IN": "सोमालिया",
		"gu-IN": "સોમાલિયા",
		"kn-IN": "ಸೊಮಾಲಿಯಾ",
		"ml-IN": "സോമാലിയ",
		"pa-IN": "ਸੋਮਾਲੀਆ",
		"ur-IN": "صومالیہ",
		"ur-PK": "صومالیہ",
		"or-IN": "ସୋମାଲିଆ",
		"as-IN": "চোমালিয়া",
		"ne-IN": "सोमालिया",
		"ne-NP": "सोमालिया",
		"si-LK": "සෝමාලියාව",
		"kok-IN": "सोमालिया",
		"ks-IN": "سومالِیا",
		"brx-IN": "समालिया",
		"mai-IN": "सोमालिया",
		"dz-BT": "སོ་མ་ལི་ཡ",
		"ja-JP": "ソマリア",
		"ko-KR": "소말리아",
		"ko-KP": "소말리아",
		"zh-CN": "索马里",
		"zh-Hans-CN": "索马里",
		"zh-Hant-TW": "索馬利亞",
		"zh-TW": "索馬利亞",
		"zh-HK": "索馬里",
		"zh-MO": "索馬里",
		"zh-SG": "索马里",
		"yue-Hant-HK": "索馬利亞",
		"yue-Hans-CN": "索马利亚",
		"mn-MN": "Сомали",
		"ug-CN": "سومالى",
		"th-TH": "โซมาเลีย",
		"lo-LA": "ໂຊມາເລຍ",
		"km-KH": "សូម៉ាលី",
		"my-MM": "ဆိုမာလီယာ",
		"vi-VN": "Somalia",
		"id-ID": "Somalia",
		"ms-MY": "Somalia",
		"ms-SG": "Somalia",
		"ms-BN": "Somalia",
		"jv-ID": "Somalia",
		"fil-PH": "Somalia",
		"ceb-PH": "Somalia",
		"ka-GE": "სომალი",
		"hy-AM": "Սոմալի",
		"az-AZ": "Somali",
		"az-Cyrl-AZ": "Сомали",
		"kk-KZ": "Сомали",
		"ky-KG": "Сомали",
		"uz-UZ": "Somali",
		"tg-TJ": "Сомалӣ",
		"tk-TM": "Somali",
		"fa-IR": "سومالی",
		"fa-AF": "سومالیه",
		"ps-AF": "سومالیا",
		"ps-PK": "سومالیا",
		"he-IL": "סומליה",
		"ar-SA": "الصومال",
		"ar-AE": "الصومال",
		"ar-QA": "الصومال",
		"ar-BH": "الصومال",
		"ar-KW": "الصومال",
		"ar-OM": "الصومال",
		"ar-YE": "الصومال",
		"ar-IQ": "الصومال",
		"ar-JO": "الصومال",
		"ar-LB": "الصومال",
		"ar-SY": "الصومال",
		"ar-PS": "الصومال",
		"en-US": "Somalia",
		"en-GB": "Somalia",
		"en-IE": "Somalia",
		"en-MT": "Somalia",
		"en-GI": "Somalia",
		"en-CY": "Somalia",
		"en-JE": "Somalia",
		"en-GG": "Somalia",
		"en-IM": "Somalia",
		"en-CA": "Somalia",
		"en-AU": "Somalia",
		"en-NZ": "Somalia",
		"en-ZA": "Somalia",
		"en-IN": "Somalia",
		"en-SG": "Somalia",
		"pt-AO": "Somália",
		"pt-MZ": "Somália",
		"pt-CV": "Somália",
		"pt-GW": "Somália",
		"pt-ST": "Somália",
		"pt-TL": "Somália",
		"pt-MO": "Somália",
		"es-ES": "Somalia",
		"es-419": "Somalia",
		"es-AD": "Somalia",
		"es-GI": "Somalia",
		"es-AR": "Somalia",
		"es-BO": "Somalia",
		"es-BR": "Somalia",
		"es-BZ": "Somalia",
		"es-CL": "Somalia",
		"es-CO": "Somalia",
		"es-CR": "Somalia",
		"es-CU": "Somalia",
		"es-DO": "Somalia",
		"es-EC": "Somalia",
		"es-GT": "Somalia",
		"es-HN": "Somalia",
		"es-MX": "Somalia",
		"es-NI": "Somalia",
		"es-PA": "Somalia",
		"es-PE": "Somalia",
		"es-PR": "Somalia",
		"es-PY": "Somalia",
		"es-SV": "Somalia",
		"es-US": "Somalia",
		"es-UY": "Somalia",
		"es-VE": "Somalia",
		"fr-FR": "Somalie",
		"fr-BE": "Somalie",
		"fr-CH": "Somalie",
		"fr-LU": "Somalie",
		"fr-MC": "Somalie",
		"fr-AD": "Somalie",
		"fr-CA": "Somalie",
		"it-IT": "Somalia",
		"it-CH": "Somalia",
		"it-SM": "Somalia",
		"it-VA": "Somalia",
		"de-DE": "Somalia",
		"de-AT": "Somalia",
		"de-CH": "Somalia",
		"de-BE": "Somalia",
		"de-LI": "Somalia",
		"de-LU": "Somalia",
		"nl-NL": "Somalië",
		"nl-BE": "Somalië",
		"sv-SE": "Somalia",
		"sv-FI": "Somalia",
		"da-DK": "Somalia",
		"nb-NO": "Somalia",
		"nn-NO": "Somalia",
		"fi-FI": "Somalia",
		"is-IS": "Sómalía",
		"fo-FO": "Somalia",
		"et-EE": "Somaalia",
		"lv-LV": "Somālija",
		"lt-LT": "Somalis",
		"pl-PL": "Somalia",
		"cs-CZ": "Somálsko",
		"sk-SK": "Somálsko",
		"sl-SI": "Somalija",
		"hr-HR": "Somalija",
		"bs-BA": "Somalija",
		"sr-RS": "Сомалија",
		"sr-BA": "Сомалија",
		"sr-ME": "Somalija",
		"mk-MK": "Сомалија",
		"bg-BG": "Сомалия",
		"be-BY": "Самалі",
		"uk-UA": "Сомалі",
		"ru-RU": "Сомали",
		"el-GR": "Σομαλία",
		"el-CY": "Σομαλία",
		"ro-RO": "Somalia",
		"ro-MD": "Somalia",
		"hu-HU": "Szomália",
		"sq-AL": "Somali",
		"sq-XK": "Somali",
		"mt-MT": "is-Somalja",
		"ga-IE": "an tSomáil",
		"cy-GB": "Somalia",
		"gd-GB": "Somàilia",
		"lb-LU": "Somalia",
		"ca-ES": "Somàlia",
		"ca-AD": "Somàlia",
		"ca-FR": "Somàlia",
		"ca-IT": "Somàlia",
		"eu-ES": "Somalia",
		"eu-FR": "Somalia",
		"gl-ES": "Somalia",
		"tr-TR": "Somali",
		"tr-CY": "Somali"
	},
	"callingCode": "252",
	"phoneMasks": [
		{
			"mask": "## ####",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"8[125]"
			]
		},
		{
			"mask": "######",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"[134]"
			]
		},
		{
			"mask": "# ######",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[15]|2[0-79]|3[0-46-8]|4[0-7]"
			]
		},
		{
			"mask": "# #######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"(?:2|90)4|[67]"
			]
		},
		{
			"mask": "## #######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1|28|6[0-35-9]|7[67]|9[2-9]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[348]|64|79|90"
			]
		}
	]
} satisfies Country;
