import type { Country } from './types.js';

export const SRB = {
	"code": "SRB",
	"labels": {
		"pt-BR": "Sérvia",
		"pt-PT": "Sérvia",
		"qu-PE": "Serbia",
		"qu-BO": "Serbia",
		"qu-EC": "Serbia",
		"chr-US": "ᏒᏈᏯ",
		"hi-IN": "सर्बिया",
		"bn-IN": "সার্বিয়া",
		"bn-BD": "সার্বিয়া",
		"ta-IN": "செர்பியா",
		"ta-LK": "செர்பியா",
		"ta-SG": "செர்பியா",
		"ta-MY": "செர்பியா",
		"te-IN": "సెర్బియా",
		"mr-IN": "सर्बिया",
		"gu-IN": "સર્બિયા",
		"kn-IN": "ಸೆರ್ಬಿಯಾ",
		"ml-IN": "സെർബിയ",
		"pa-IN": "ਸਰਬੀਆ",
		"ur-IN": "سربیا",
		"ur-PK": "سربیا",
		"or-IN": "ସର୍ବିଆ",
		"as-IN": "ছাৰ্বিয়া",
		"ne-IN": "सर्बिया",
		"ne-NP": "सर्बिया",
		"si-LK": "සර්බියාව",
		"kok-IN": "सर्बिया",
		"ks-IN": "سَربِیا",
		"brx-IN": "सार्बिया",
		"mai-IN": "सर्बिया",
		"dz-BT": "སཱར་བྷི་ཡ",
		"ja-JP": "セルビア",
		"ko-KR": "세르비아",
		"ko-KP": "세르비아",
		"zh-CN": "塞尔维亚",
		"zh-Hans-CN": "塞尔维亚",
		"zh-Hant-TW": "塞爾維亞",
		"zh-TW": "塞爾維亞",
		"zh-HK": "塞爾維亞",
		"zh-MO": "塞爾維亞",
		"zh-SG": "塞尔维亚",
		"yue-Hant-HK": "塞爾維亞",
		"yue-Hans-CN": "塞尔维亚",
		"mn-MN": "Серби",
		"ug-CN": "سېربىيە",
		"th-TH": "เซอร์เบีย",
		"lo-LA": "ເຊີເບຍ",
		"km-KH": "សែប៊ី",
		"my-MM": "ဆားဘီးယား",
		"vi-VN": "Serbia",
		"id-ID": "Serbia",
		"ms-MY": "Serbia",
		"ms-SG": "Serbia",
		"ms-BN": "Serbia",
		"jv-ID": "Sèrbi",
		"fil-PH": "Serbia",
		"ceb-PH": "Serbia",
		"ka-GE": "სერბეთი",
		"hy-AM": "Սերբիա",
		"az-AZ": "Serbiya",
		"az-Cyrl-AZ": "Сербија",
		"kk-KZ": "Сербия",
		"ky-KG": "Сербия",
		"uz-UZ": "Serbiya",
		"tg-TJ": "Сербия",
		"tk-TM": "Serbiýa",
		"fa-IR": "صربستان",
		"fa-AF": "صربستان",
		"ps-AF": "سربيا",
		"ps-PK": "سربيا",
		"he-IL": "סרביה",
		"ar-SA": "صربيا",
		"ar-AE": "صربيا",
		"ar-QA": "صربيا",
		"ar-BH": "صربيا",
		"ar-KW": "صربيا",
		"ar-OM": "صربيا",
		"ar-YE": "صربيا",
		"ar-IQ": "صربيا",
		"ar-JO": "صربيا",
		"ar-LB": "صربيا",
		"ar-SY": "صربيا",
		"ar-PS": "صربيا",
		"en-US": "Serbia",
		"en-GB": "Serbia",
		"en-IE": "Serbia",
		"en-MT": "Serbia",
		"en-GI": "Serbia",
		"en-CY": "Serbia",
		"en-JE": "Serbia",
		"en-GG": "Serbia",
		"en-IM": "Serbia",
		"en-CA": "Serbia",
		"en-AU": "Serbia",
		"en-NZ": "Serbia",
		"en-ZA": "Serbia",
		"en-IN": "Serbia",
		"en-SG": "Serbia",
		"pt-AO": "Sérvia",
		"pt-MZ": "Sérvia",
		"pt-CV": "Sérvia",
		"pt-GW": "Sérvia",
		"pt-ST": "Sérvia",
		"pt-TL": "Sérvia",
		"pt-MO": "Sérvia",
		"es-ES": "Serbia",
		"es-419": "Serbia",
		"es-AD": "Serbia",
		"es-GI": "Serbia",
		"es-AR": "Serbia",
		"es-BO": "Serbia",
		"es-BR": "Serbia",
		"es-BZ": "Serbia",
		"es-CL": "Serbia",
		"es-CO": "Serbia",
		"es-CR": "Serbia",
		"es-CU": "Serbia",
		"es-DO": "Serbia",
		"es-EC": "Serbia",
		"es-GT": "Serbia",
		"es-HN": "Serbia",
		"es-MX": "Serbia",
		"es-NI": "Serbia",
		"es-PA": "Serbia",
		"es-PE": "Serbia",
		"es-PR": "Serbia",
		"es-PY": "Serbia",
		"es-SV": "Serbia",
		"es-US": "Serbia",
		"es-UY": "Serbia",
		"es-VE": "Serbia",
		"fr-FR": "Serbie",
		"fr-BE": "Serbie",
		"fr-CH": "Serbie",
		"fr-LU": "Serbie",
		"fr-MC": "Serbie",
		"fr-AD": "Serbie",
		"fr-CA": "Serbie",
		"it-IT": "Serbia",
		"it-CH": "Serbia",
		"it-SM": "Serbia",
		"it-VA": "Serbia",
		"de-DE": "Serbien",
		"de-AT": "Serbien",
		"de-CH": "Serbien",
		"de-BE": "Serbien",
		"de-LI": "Serbien",
		"de-LU": "Serbien",
		"nl-NL": "Servië",
		"nl-BE": "Servië",
		"sv-SE": "Serbien",
		"sv-FI": "Serbien",
		"da-DK": "Serbien",
		"nb-NO": "Serbia",
		"nn-NO": "Serbia",
		"fi-FI": "Serbia",
		"is-IS": "Serbía",
		"fo-FO": "Serbia",
		"et-EE": "Serbia",
		"lv-LV": "Serbija",
		"lt-LT": "Serbija",
		"pl-PL": "Serbia",
		"cs-CZ": "Srbsko",
		"sk-SK": "Srbsko",
		"sl-SI": "Srbija",
		"hr-HR": "Srbija",
		"bs-BA": "Srbija",
		"sr-RS": "Србија",
		"sr-BA": "Србија",
		"sr-ME": "Srbija",
		"mk-MK": "Србија",
		"bg-BG": "Сърбия",
		"be-BY": "Сербія",
		"uk-UA": "Сербія",
		"ru-RU": "Сербия",
		"el-GR": "Σερβία",
		"el-CY": "Σερβία",
		"ro-RO": "Serbia",
		"ro-MD": "Serbia",
		"hu-HU": "Szerbia",
		"sq-AL": "Serbi",
		"sq-XK": "Serbi",
		"mt-MT": "is-Serbja",
		"ga-IE": "an tSeirbia",
		"cy-GB": "Serbia",
		"gd-GB": "An t-Sèirb",
		"lb-LU": "Serbien",
		"ca-ES": "Sèrbia",
		"ca-AD": "Sèrbia",
		"ca-FR": "Sèrbia",
		"ca-IT": "Sèrbia",
		"eu-ES": "Serbia",
		"eu-FR": "Serbia",
		"gl-ES": "Serbia",
		"tr-TR": "Sırbistan",
		"tr-CY": "Sırbistan"
	},
	"callingCode": "381",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11
		},
		{
			"mask": "## ##########",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"[1-36]"
			]
		},
		{
			"mask": "### #########",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"(?:2[389]|39)0|[7-9]"
			]
		}
	]
} satisfies Country;
