import type { Country } from './types.js';

export const SYC = {
	"code": "SYC",
	"labels": {
		"pt-BR": "Seicheles",
		"pt-PT": "Seicheles",
		"qu-PE": "Seychelles",
		"qu-BO": "Seychelles",
		"qu-EC": "Seychelles",
		"chr-US": "ᏏᎡᏥᎵᏍ",
		"hi-IN": "सेशेल्स",
		"bn-IN": "সিসিলি",
		"bn-BD": "সিসিলি",
		"ta-IN": "சீஷெல்ஸ்",
		"ta-LK": "சீஷெல்ஸ்",
		"ta-SG": "சீஷெல்ஸ்",
		"ta-MY": "சீஷெல்ஸ்",
		"te-IN": "సీషెల్స్",
		"mr-IN": "सेशेल्स",
		"gu-IN": "સેશેલ્સ",
		"kn-IN": "ಸೀಶೆಲ್ಲೆಸ್",
		"ml-IN": "സീഷെൽസ്",
		"pa-IN": "ਸੇਸ਼ਲਸ",
		"ur-IN": "سشلیز",
		"ur-PK": "سشلیز",
		"or-IN": "ସେଚେଲସ୍",
		"as-IN": "ছিচিলিছ",
		"ne-IN": "सेचेलेस",
		"ne-NP": "सेचेलेस",
		"si-LK": "සීශෙල්ස්",
		"kok-IN": "सेशेल्स",
		"ks-IN": "سیشَلِس",
		"brx-IN": "सैशेल्लेस",
		"mai-IN": "सेशेल्स",
		"dz-BT": "སེ་ཤཱལས",
		"ja-JP": "セーシェル",
		"ko-KR": "세이셸",
		"ko-KP": "세이셸",
		"zh-CN": "塞舌尔",
		"zh-Hans-CN": "塞舌尔",
		"zh-Hant-TW": "塞席爾",
		"zh-TW": "塞席爾",
		"zh-HK": "塞舌爾",
		"zh-MO": "塞舌爾",
		"zh-SG": "塞舌尔",
		"yue-Hant-HK": "塞席爾",
		"yue-Hans-CN": "塞席尔",
		"mn-MN": "Сейшелийн арлууд",
		"ug-CN": "سېيشېل",
		"th-TH": "เซเชลส์",
		"lo-LA": "ເຊເຊວເລສ",
		"km-KH": "សីស្ហែល",
		"my-MM": "ဆေးရှဲ",
		"vi-VN": "Seychelles",
		"id-ID": "Seychelles",
		"ms-MY": "Seychelles",
		"ms-SG": "Seychelles",
		"ms-BN": "Seychelles",
		"jv-ID": "Sésèl",
		"fil-PH": "Seychelles",
		"ceb-PH": "Seychelles",
		"ka-GE": "სეიშელის კუნძულები",
		"hy-AM": "Սեյշելներ",
		"az-AZ": "Seyşel adaları",
		"az-Cyrl-AZ": "Сејшел адалары",
		"kk-KZ": "Сейшель аралдары",
		"ky-KG": "Сейшел аралдары",
		"uz-UZ": "Seyshel orollari",
		"tg-TJ": "Сейшел",
		"tk-TM": "Seýşel adalary",
		"fa-IR": "سیشل",
		"fa-AF": "سیشل",
		"ps-AF": "سیچیلیس",
		"ps-PK": "سیچیلیس",
		"he-IL": "איי סיישל",
		"ar-SA": "سيشل",
		"ar-AE": "سيشل",
		"ar-QA": "سيشل",
		"ar-BH": "سيشل",
		"ar-KW": "سيشل",
		"ar-OM": "سيشل",
		"ar-YE": "سيشل",
		"ar-IQ": "سيشل",
		"ar-JO": "سيشل",
		"ar-LB": "سيشل",
		"ar-SY": "سيشل",
		"ar-PS": "سيشل",
		"en-US": "Seychelles",
		"en-GB": "Seychelles",
		"en-IE": "Seychelles",
		"en-MT": "Seychelles",
		"en-GI": "Seychelles",
		"en-CY": "Seychelles",
		"en-JE": "Seychelles",
		"en-GG": "Seychelles",
		"en-IM": "Seychelles",
		"en-CA": "Seychelles",
		"en-AU": "Seychelles",
		"en-NZ": "Seychelles",
		"en-ZA": "Seychelles",
		"en-IN": "Seychelles",
		"en-SG": "Seychelles",
		"pt-AO": "Seicheles",
		"pt-MZ": "Seicheles",
		"pt-CV": "Seicheles",
		"pt-GW": "Seicheles",
		"pt-ST": "Seicheles",
		"pt-TL": "Seicheles",
		"pt-MO": "Seicheles",
		"es-ES": "Seychelles",
		"es-419": "Seychelles",
		"es-AD": "Seychelles",
		"es-GI": "Seychelles",
		"es-AR": "Seychelles",
		"es-BO": "Seychelles",
		"es-BR": "Seychelles",
		"es-BZ": "Seychelles",
		"es-CL": "Seychelles",
		"es-CO": "Seychelles",
		"es-CR": "Seychelles",
		"es-CU": "Seychelles",
		"es-DO": "Seychelles",
		"es-EC": "Seychelles",
		"es-GT": "Seychelles",
		"es-HN": "Seychelles",
		"es-MX": "Seychelles",
		"es-NI": "Seychelles",
		"es-PA": "Seychelles",
		"es-PE": "Seychelles",
		"es-PR": "Seychelles",
		"es-PY": "Seychelles",
		"es-SV": "Seychelles",
		"es-US": "Seychelles",
		"es-UY": "Seychelles",
		"es-VE": "Seychelles",
		"fr-FR": "Seychelles",
		"fr-BE": "Seychelles",
		"fr-CH": "Seychelles",
		"fr-LU": "Seychelles",
		"fr-MC": "Seychelles",
		"fr-AD": "Seychelles",
		"fr-CA": "Seychelles",
		"it-IT": "Seychelles",
		"it-CH": "Seychelles",
		"it-SM": "Seychelles",
		"it-VA": "Seychelles",
		"de-DE": "Seychellen",
		"de-AT": "Seychellen",
		"de-CH": "Seychellen",
		"de-BE": "Seychellen",
		"de-LI": "Seychellen",
		"de-LU": "Seychellen",
		"nl-NL": "Seychellen",
		"nl-BE": "Seychellen",
		"sv-SE": "Seychellerna",
		"sv-FI": "Seychellerna",
		"da-DK": "Seychellerne",
		"nb-NO": "Seychellene",
		"nn-NO": "Seychellane",
		"fi-FI": "Seychellit",
		"is-IS": "Seychelles-eyjar",
		"fo-FO": "Seyskelloyggjar",
		"et-EE": "Seišellid",
		"lv-LV": "Seišelu salas",
		"lt-LT": "Seišeliai",
		"pl-PL": "Seszele",
		"cs-CZ": "Seychely",
		"sk-SK": "Seychely",
		"sl-SI": "Sejšeli",
		"hr-HR": "Sejšeli",
		"bs-BA": "Sejšeli",
		"sr-RS": "Сејшели",
		"sr-BA": "Сејшели",
		"sr-ME": "Sejšeli",
		"mk-MK": "Сејшели",
		"bg-BG": "Сейшели",
		"be-BY": "Сейшэльскія астравы",
		"uk-UA": "Сейшельські Острови",
		"ru-RU": "Сейшельские о-ва",
		"el-GR": "Σεϋχέλλες",
		"el-CY": "Σεϋχέλλες",
		"ro-RO": "Seychelles",
		"ro-MD": "Seychelles",
		"hu-HU": "Seychelle-szigetek",
		"sq-AL": "Sejshelle",
		"sq-XK": "Sejshelle",
		"mt-MT": "is-Seychelles",
		"ga-IE": "na Séiséil",
		"cy-GB": "Seychelles",
		"gd-GB": "Na h-Eileanan Sheiseall",
		"lb-LU": "Seychellen",
		"ca-ES": "Seychelles",
		"ca-AD": "Seychelles",
		"ca-FR": "Seychelles",
		"ca-IT": "Seychelles",
		"eu-ES": "Seychelleak",
		"eu-FR": "Seychelleak",
		"gl-ES": "Seychelles",
		"tr-TR": "Seyşeller",
		"tr-CY": "Seyşeller"
	},
	"callingCode": "248",
	"phoneMasks": [
		{
			"mask": "# ### ###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[246]|9[57]"
			]
		}
	]
} satisfies Country;
