import type { Country } from './types.js';

export const THA = {
	"code": "THA",
	"labels": {
		"pt-BR": "Tailândia",
		"pt-PT": "Tailândia",
		"qu-PE": "Tailandia",
		"qu-BO": "Tailandia",
		"qu-EC": "Tailandia",
		"chr-US": "ᏔᏯᎴᏂ",
		"hi-IN": "थाईलैंड",
		"bn-IN": "থাইল্যান্ড",
		"bn-BD": "থাইল্যান্ড",
		"ta-IN": "தாய்லாந்து",
		"ta-LK": "தாய்லாந்து",
		"ta-SG": "தாய்லாந்து",
		"ta-MY": "தாய்லாந்து",
		"te-IN": "థాయిలాండ్",
		"mr-IN": "थायलंड",
		"gu-IN": "થાઇલેંડ",
		"kn-IN": "ಥೈಲ್ಯಾಂಡ್",
		"ml-IN": "തായ്‌ലാൻഡ്",
		"pa-IN": "ਥਾਈਲੈਂਡ",
		"ur-IN": "تھائی لینڈ",
		"ur-PK": "تھائی لینڈ",
		"or-IN": "ଥାଇଲ୍ୟାଣ୍ଡ",
		"as-IN": "থাইলেণ্ড",
		"ne-IN": "थाइल्याण्ड",
		"ne-NP": "थाइल्याण्ड",
		"si-LK": "තායිලන්තය",
		"kok-IN": "थायलँड",
		"ks-IN": "تھائی لینڈ",
		"brx-IN": "थाइलेण्ड",
		"mai-IN": "थाईलैंड",
		"dz-BT": "ཐཱའི་ལེནཌ",
		"ja-JP": "タイ",
		"ko-KR": "태국",
		"ko-KP": "태국",
		"zh-CN": "泰国",
		"zh-Hans-CN": "泰国",
		"zh-Hant-TW": "泰國",
		"zh-TW": "泰國",
		"zh-HK": "泰國",
		"zh-MO": "泰國",
		"zh-SG": "泰国",
		"yue-Hant-HK": "泰國",
		"yue-Hans-CN": "泰国",
		"mn-MN": "Тайланд",
		"ug-CN": "تايلاند",
		"th-TH": "ไทย",
		"lo-LA": "ໄທ",
		"km-KH": "ថៃ",
		"my-MM": "ထိုင်း",
		"vi-VN": "Thái Lan",
		"id-ID": "Thailand",
		"ms-MY": "Thailand",
		"ms-SG": "Thailand",
		"ms-BN": "Thailand",
		"jv-ID": "Tanah Thai",
		"fil-PH": "Thailand",
		"ceb-PH": "Thailand",
		"ka-GE": "ტაილანდი",
		"hy-AM": "Թաիլանդ",
		"az-AZ": "Tailand",
		"az-Cyrl-AZ": "Таиланд",
		"kk-KZ": "Таиланд",
		"ky-KG": "Тайланд",
		"uz-UZ": "Tailand",
		"tg-TJ": "Таиланд",
		"tk-TM": "Taýland",
		"fa-IR": "تایلند",
		"fa-AF": "تایلند",
		"ps-AF": "تهايلنډ",
		"ps-PK": "تهايلنډ",
		"he-IL": "תאילנד",
		"ar-SA": "تايلاند",
		"ar-AE": "تايلاند",
		"ar-QA": "تايلاند",
		"ar-BH": "تايلاند",
		"ar-KW": "تايلاند",
		"ar-OM": "تايلاند",
		"ar-YE": "تايلاند",
		"ar-IQ": "تايلاند",
		"ar-JO": "تايلاند",
		"ar-LB": "تايلاند",
		"ar-SY": "تايلاند",
		"ar-PS": "تايلاند",
		"en-US": "Thailand",
		"en-GB": "Thailand",
		"en-IE": "Thailand",
		"en-MT": "Thailand",
		"en-GI": "Thailand",
		"en-CY": "Thailand",
		"en-JE": "Thailand",
		"en-GG": "Thailand",
		"en-IM": "Thailand",
		"en-CA": "Thailand",
		"en-AU": "Thailand",
		"en-NZ": "Thailand",
		"en-ZA": "Thailand",
		"en-IN": "Thailand",
		"en-SG": "Thailand",
		"pt-AO": "Tailândia",
		"pt-MZ": "Tailândia",
		"pt-CV": "Tailândia",
		"pt-GW": "Tailândia",
		"pt-ST": "Tailândia",
		"pt-TL": "Tailândia",
		"pt-MO": "Tailândia",
		"es-ES": "Tailandia",
		"es-419": "Tailandia",
		"es-AD": "Tailandia",
		"es-GI": "Tailandia",
		"es-AR": "Tailandia",
		"es-BO": "Tailandia",
		"es-BR": "Tailandia",
		"es-BZ": "Tailandia",
		"es-CL": "Tailandia",
		"es-CO": "Tailandia",
		"es-CR": "Tailandia",
		"es-CU": "Tailandia",
		"es-DO": "Tailandia",
		"es-EC": "Tailandia",
		"es-GT": "Tailandia",
		"es-HN": "Tailandia",
		"es-MX": "Tailandia",
		"es-NI": "Tailandia",
		"es-PA": "Tailandia",
		"es-PE": "Tailandia",
		"es-PR": "Tailandia",
		"es-PY": "Tailandia",
		"es-SV": "Tailandia",
		"es-US": "Tailandia",
		"es-UY": "Tailandia",
		"es-VE": "Tailandia",
		"fr-FR": "Thaïlande",
		"fr-BE": "Thaïlande",
		"fr-CH": "Thaïlande",
		"fr-LU": "Thaïlande",
		"fr-MC": "Thaïlande",
		"fr-AD": "Thaïlande",
		"fr-CA": "Thaïlande",
		"it-IT": "Thailandia",
		"it-CH": "Thailandia",
		"it-SM": "Thailandia",
		"it-VA": "Thailandia",
		"de-DE": "Thailand",
		"de-AT": "Thailand",
		"de-CH": "Thailand",
		"de-BE": "Thailand",
		"de-LI": "Thailand",
		"de-LU": "Thailand",
		"nl-NL": "Thailand",
		"nl-BE": "Thailand",
		"sv-SE": "Thailand",
		"sv-FI": "Thailand",
		"da-DK": "Thailand",
		"nb-NO": "Thailand",
		"nn-NO": "Thailand",
		"fi-FI": "Thaimaa",
		"is-IS": "Taíland",
		"fo-FO": "Tailand",
		"et-EE": "Tai",
		"lv-LV": "Taizeme",
		"lt-LT": "Tailandas",
		"pl-PL": "Tajlandia",
		"cs-CZ": "Thajsko",
		"sk-SK": "Thajsko",
		"sl-SI": "Tajska",
		"hr-HR": "Tajland",
		"bs-BA": "Tajland",
		"sr-RS": "Тајланд",
		"sr-BA": "Тајланд",
		"sr-ME": "Tajland",
		"mk-MK": "Тајланд",
		"bg-BG": "Тайланд",
		"be-BY": "Тайланд",
		"uk-UA": "Таїланд",
		"ru-RU": "Таиланд",
		"el-GR": "Ταϊλάνδη",
		"el-CY": "Ταϊλάνδη",
		"ro-RO": "Thailanda",
		"ro-MD": "Thailanda",
		"hu-HU": "Thaiföld",
		"sq-AL": "Tajlandë",
		"sq-XK": "Tajlandë",
		"mt-MT": "it-Tajlandja",
		"ga-IE": "an Téalainn",
		"cy-GB": "Gwlad Thai",
		"gd-GB": "Dùthaich nan Tàidh",
		"lb-LU": "Thailand",
		"ca-ES": "Tailàndia",
		"ca-AD": "Tailàndia",
		"ca-FR": "Tailàndia",
		"ca-IT": "Tailàndia",
		"eu-ES": "Thailandia",
		"eu-FR": "Thailandia",
		"gl-ES": "Tailandia",
		"tr-TR": "Tayland",
		"tr-CY": "Tayland"
	},
	"callingCode": "66",
	"phoneMasks": [
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[13-9]"
			]
		},
		{
			"mask": "#### ### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "# ### ### ### ###",
			"minLength": 13,
			"maxLength": 13
		}
	]
} satisfies Country;
