import type { Country } from './types.js';

export const TLS = {
	"code": "TLS",
	"labels": {
		"pt-BR": "Timor-Leste",
		"pt-PT": "Timor-Leste",
		"qu-PE": "Timor-Leste",
		"qu-BO": "Timor-Leste",
		"qu-EC": "Timor-Leste",
		"chr-US": "ᏘᎼᎵ-ᎴᏍᏖ",
		"hi-IN": "तिमोर-लेस्त",
		"bn-IN": "তিমুর-লেস্তে",
		"bn-BD": "তিমুর-লেস্তে",
		"ta-IN": "திமோர்-லெஸ்தே",
		"ta-LK": "திமோர்-லெஸ்தே",
		"ta-SG": "திமோர்-லெஸ்தே",
		"ta-MY": "திமோர்-லெஸ்தே",
		"te-IN": "టిమోర్-లెస్టె",
		"mr-IN": "तिमोर-लेस्ते",
		"gu-IN": "તિમોર-લેસ્તે",
		"kn-IN": "ಟಿಮೋರ್ ಲೆಸ್ಟೆ",
		"ml-IN": "തിമോർ-ലെസ്റ്റെ",
		"pa-IN": "ਤਿਮੋਰ-ਲੇਸਤੇ",
		"ur-IN": "تیمور لیسٹ",
		"ur-PK": "تیمور لیسٹ",
		"or-IN": "ତିମୋର୍-ଲେଷ୍ଟେ",
		"as-IN": "টিমোৰ-লেচটে",
		"ne-IN": "टिमोर-लेस्टे",
		"ne-NP": "टिमोर-लेस्टे",
		"si-LK": "ටිමෝර් - ලෙස්ත්",
		"kok-IN": "तिमोर-लेस्ते",
		"ks-IN": "تیمور-لیسٹ",
		"brx-IN": "तिमर-लेस्ते",
		"mai-IN": "तिमोर-लेस्त",
		"dz-BT": "ཏི་་མོར་ལེ་ཨེསཊ",
		"ja-JP": "東ティモール",
		"ko-KR": "동티모르",
		"ko-KP": "동티모르",
		"zh-CN": "东帝汶",
		"zh-Hans-CN": "东帝汶",
		"zh-Hant-TW": "東帝汶",
		"zh-TW": "東帝汶",
		"zh-HK": "東帝汶",
		"zh-MO": "東帝汶",
		"zh-SG": "东帝汶",
		"yue-Hant-HK": "東帝汶",
		"yue-Hans-CN": "东帝汶",
		"mn-MN": "Тимор-Лесте",
		"ug-CN": "شەرقىي تىمور",
		"th-TH": "ติมอร์-เลสเต",
		"lo-LA": "ທິມໍ-ເລສເຕ",
		"km-KH": "ទីម័រលេស្តេ",
		"my-MM": "အရှေ့တီမော",
		"vi-VN": "Timor-Leste",
		"id-ID": "Timor Leste",
		"ms-MY": "Timor-Leste",
		"ms-SG": "Timor-Leste",
		"ms-BN": "Timor-Leste",
		"jv-ID": "Timor Leste",
		"fil-PH": "Timor-Leste",
		"ceb-PH": "Timor-Leste",
		"ka-GE": "ტიმორ-ლესტე",
		"hy-AM": "Թիմոր Լեշտի",
		"az-AZ": "Şərqi Timor",
		"az-Cyrl-AZ": "Шәрги Тимор",
		"kk-KZ": "Тимор-Лесте",
		"ky-KG": "Тимор-Лесте",
		"uz-UZ": "Timor-Leste",
		"tg-TJ": "Тимор-Лесте",
		"tk-TM": "Timor-Leste",
		"fa-IR": "تیمور-لسته",
		"fa-AF": "تیمور-لسته",
		"ps-AF": "تيمور-ليسټ",
		"ps-PK": "تيمور-ليسټ",
		"he-IL": "טימור-לסטה",
		"ar-SA": "تيمور - ليشتي",
		"ar-AE": "تيمور - ليشتي",
		"ar-QA": "تيمور - ليشتي",
		"ar-BH": "تيمور - ليشتي",
		"ar-KW": "تيمور - ليشتي",
		"ar-OM": "تيمور - ليشتي",
		"ar-YE": "تيمور - ليشتي",
		"ar-IQ": "تيمور - ليشتي",
		"ar-JO": "تيمور - ليشتي",
		"ar-LB": "تيمور - ليشتي",
		"ar-SY": "تيمور - ليشتي",
		"ar-PS": "تيمور - ليشتي",
		"en-US": "Timor-Leste",
		"en-GB": "Timor-Leste",
		"en-IE": "Timor-Leste",
		"en-MT": "Timor-Leste",
		"en-GI": "Timor-Leste",
		"en-CY": "Timor-Leste",
		"en-JE": "Timor-Leste",
		"en-GG": "Timor-Leste",
		"en-IM": "Timor-Leste",
		"en-CA": "Timor-Leste",
		"en-AU": "Timor-Leste",
		"en-NZ": "Timor-Leste",
		"en-ZA": "Timor-Leste",
		"en-IN": "Timor-Leste",
		"en-SG": "Timor-Leste",
		"pt-AO": "Timor-Leste",
		"pt-MZ": "Timor-Leste",
		"pt-CV": "Timor-Leste",
		"pt-GW": "Timor-Leste",
		"pt-ST": "Timor-Leste",
		"pt-TL": "Timor-Leste",
		"pt-MO": "Timor-Leste",
		"es-ES": "Timor-Leste",
		"es-419": "Timor Oriental",
		"es-AD": "Timor-Leste",
		"es-GI": "Timor-Leste",
		"es-AR": "Timor-Leste",
		"es-BO": "Timor-Leste",
		"es-BR": "Timor Oriental",
		"es-BZ": "Timor Oriental",
		"es-CL": "Timor-Leste",
		"es-CO": "Timor-Leste",
		"es-CR": "Timor-Leste",
		"es-CU": "Timor Oriental",
		"es-DO": "Timor-Leste",
		"es-EC": "Timor-Leste",
		"es-GT": "Timor-Leste",
		"es-HN": "Timor-Leste",
		"es-MX": "Timor Oriental",
		"es-NI": "Timor-Leste",
		"es-PA": "Timor-Leste",
		"es-PE": "Timor-Leste",
		"es-PR": "Timor Oriental",
		"es-PY": "Timor-Leste",
		"es-SV": "Timor Oriental",
		"es-US": "Timor Oriental",
		"es-UY": "Timor Oriental",
		"es-VE": "Timor-Leste",
		"fr-FR": "Timor oriental",
		"fr-BE": "Timor oriental",
		"fr-CH": "Timor oriental",
		"fr-LU": "Timor oriental",
		"fr-MC": "Timor oriental",
		"fr-AD": "Timor oriental",
		"fr-CA": "Timor-Leste",
		"it-IT": "Timor Est",
		"it-CH": "Timor Est",
		"it-SM": "Timor Est",
		"it-VA": "Timor Est",
		"de-DE": "Timor-Leste",
		"de-AT": "Timor-Leste",
		"de-CH": "Osttimor",
		"de-BE": "Timor-Leste",
		"de-LI": "Timor-Leste",
		"de-LU": "Timor-Leste",
		"nl-NL": "Oost-Timor",
		"nl-BE": "Oost-Timor",
		"sv-SE": "Östtimor",
		"sv-FI": "Östtimor",
		"da-DK": "Timor-Leste",
		"nb-NO": "Øst-Timor",
		"nn-NO": "Aust-Timor",
		"fi-FI": "Itä-Timor",
		"is-IS": "Tímor-Leste",
		"fo-FO": "Eysturtimor",
		"et-EE": "Ida-Timor",
		"lv-LV": "Austrumtimora",
		"lt-LT": "Rytų Timoras",
		"pl-PL": "Timor Wschodni",
		"cs-CZ": "Východní Timor",
		"sk-SK": "Východný Timor",
		"sl-SI": "Timor-Leste",
		"hr-HR": "Timor-Leste",
		"bs-BA": "Istočni Timor",
		"sr-RS": "Тимор-Лесте (Источни Тимор)",
		"sr-BA": "Тимор-Лесте (Источни Тимор)",
		"sr-ME": "Timor-Leste (Istočni Timor)",
		"mk-MK": "Тимор Лесте",
		"bg-BG": "Тимор Лесте",
		"be-BY": "Тымор-Лешці",
		"uk-UA": "Тимор-Лешті",
		"ru-RU": "Восточный Тимор",
		"el-GR": "Τιμόρ-Λέστε",
		"el-CY": "Τιμόρ-Λέστε",
		"ro-RO": "Timor-Leste",
		"ro-MD": "Timor-Leste",
		"hu-HU": "Kelet-Timor",
		"sq-AL": "Timor-Leste",
		"sq-XK": "Timor-Leste",
		"mt-MT": "Timor Leste",
		"ga-IE": "Tíomór Thoir",
		"cy-GB": "Timor-Leste",
		"gd-GB": "Timor-Leste",
		"lb-LU": "Osttimor",
		"ca-ES": "Timor-Leste",
		"ca-AD": "Timor-Leste",
		"ca-FR": "Timor-Leste",
		"ca-IT": "Timor-Leste",
		"eu-ES": "Ekialdeko Timor",
		"eu-FR": "Ekialdeko Timor",
		"gl-ES": "Timor Leste",
		"tr-TR": "Timor-Leste",
		"tr-CY": "Timor-Leste"
	},
	"callingCode": "670",
	"phoneMasks": [
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-489]|70"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"7"
			]
		}
	]
} satisfies Country;
