import type { Country } from './types.js';

export const TTO = {
	"code": "TTO",
	"labels": {
		"pt-BR": "Trinidad e Tobago",
		"pt-PT": "Trindade e Tobago",
		"qu-PE": "Trinidad y Tobago",
		"qu-BO": "Trinidad y Tobago",
		"qu-EC": "Trinidad y Tobago",
		"chr-US": "ᏟᏂᏕᏗ ᎠᎴ ᏙᏆᎪ",
		"hi-IN": "त्रिनिदाद और टोबैगो",
		"bn-IN": "ত্রিনিনাদ ও টোব্যাগো",
		"bn-BD": "ত্রিনিনাদ ও টোব্যাগো",
		"ta-IN": "டிரினிடாட் & டொபாகோ",
		"ta-LK": "டிரினிடாட் & டொபாகோ",
		"ta-SG": "டிரினிடாட் & டொபாகோ",
		"ta-MY": "டிரினிடாட் & டொபாகோ",
		"te-IN": "ట్రినిడాడ్ మరియు టొబాగో",
		"mr-IN": "त्रिनिदाद आणि टोबॅगो",
		"gu-IN": "ટ્રિનીદાદ અને ટોબેગો",
		"kn-IN": "ಟ್ರಿನಿಡಾಡ್ ಮತ್ತು ಟೊಬಾಗೊ",
		"ml-IN": "ട്രിനിഡാഡും ടുബാഗോയും",
		"pa-IN": "ਟ੍ਰਿਨੀਡਾਡ ਅਤੇ ਟੋਬਾਗੋ",
		"ur-IN": "ترینیداد اور ٹوباگو",
		"ur-PK": "ترینیداد اور ٹوباگو",
		"or-IN": "ତ୍ରିନିଦାଦ୍ ଏବଂ ଟୋବାଗୋ",
		"as-IN": "ট্ৰিনিডাড আৰু টোবাগো",
		"ne-IN": "त्रिनिडाड एण्ड टोबागो",
		"ne-NP": "त्रिनिडाड एण्ड टोबागो",
		"si-LK": "ට්‍රිනිඩෑඩ් සහ ටොබැගෝ",
		"kok-IN": "ट्रिनीदाद आनी टोबॅगो",
		"ks-IN": "ٹرنِنداد تہٕ ٹوبیگو",
		"brx-IN": "त्रिनिडाड आरो तबेग’",
		"mai-IN": "ट्रिनिदाद आ टोबैगो",
		"dz-BT": "ཊི་ནི་ཌཱཌ་ ཨེནཌ་ ཊོ་བྷེ་གྷོ",
		"ja-JP": "トリニダード・トバゴ",
		"ko-KR": "트리니다드 토바고",
		"ko-KP": "트리니다드 토바고",
		"zh-CN": "特立尼达和多巴哥",
		"zh-Hans-CN": "特立尼达和多巴哥",
		"zh-Hant-TW": "千里達及托巴哥",
		"zh-TW": "千里達及托巴哥",
		"zh-HK": "千里達和多巴哥",
		"zh-MO": "千里達和多巴哥",
		"zh-SG": "特立尼达和多巴哥",
		"yue-Hant-HK": "千里達同多巴哥",
		"yue-Hans-CN": "千里达同多巴哥",
		"mn-MN": "Тринидад ба Тобаго",
		"ug-CN": "تىرىنىداد ۋە توباگو",
		"th-TH": "ตรินิแดดและโตเบโก",
		"lo-LA": "ທຣິນິແດດ ແລະ ໂທແບໂກ",
		"km-KH": "ទ្រីនីដាត និង​តូបាហ្គោ",
		"my-MM": "ထရီနီဒတ်နှင့် တိုဘက်ဂို",
		"vi-VN": "Trinidad và Tobago",
		"id-ID": "Trinidad dan Tobago",
		"ms-MY": "Trinidad dan Tobago",
		"ms-SG": "Trinidad dan Tobago",
		"ms-BN": "Trinidad dan Tobago",
		"jv-ID": "Trinidad lan Tobago",
		"fil-PH": "Trinidad & Tobago",
		"ceb-PH": "Trinidad & Tobago",
		"ka-GE": "ტრინიდადი და ტობაგო",
		"hy-AM": "Տրինիդադ և Տոբագո",
		"az-AZ": "Trinidad və Tobaqo",
		"az-Cyrl-AZ": "Тринидад вә Тобаго",
		"kk-KZ": "Тринидад және Тобаго",
		"ky-KG": "Тринидад жана Тобаго",
		"uz-UZ": "Trinidad va Tobago",
		"tg-TJ": "Тринидад ва Тобаго",
		"tk-TM": "Trinidad we Tobago",
		"fa-IR": "ترینیداد و توباگو",
		"fa-AF": "ترینیداد و توباگو",
		"ps-AF": "ټرينيډاډ او ټوباګو",
		"ps-PK": "ټرينيډاډ او ټوباګو",
		"he-IL": "טרינידד וטובגו",
		"ar-SA": "ترينيداد وتوباغو",
		"ar-AE": "ترينيداد وتوباغو",
		"ar-QA": "ترينيداد وتوباغو",
		"ar-BH": "ترينيداد وتوباغو",
		"ar-KW": "ترينيداد وتوباغو",
		"ar-OM": "ترينيداد وتوباغو",
		"ar-YE": "ترينيداد وتوباغو",
		"ar-IQ": "ترينيداد وتوباغو",
		"ar-JO": "ترينيداد وتوباغو",
		"ar-LB": "ترينيداد وتوباغو",
		"ar-SY": "ترينيداد وتوباغو",
		"ar-PS": "ترينيداد وتوباغو",
		"en-US": "Trinidad & Tobago",
		"en-GB": "Trinidad & Tobago",
		"en-IE": "Trinidad & Tobago",
		"en-MT": "Trinidad & Tobago",
		"en-GI": "Trinidad & Tobago",
		"en-CY": "Trinidad & Tobago",
		"en-JE": "Trinidad & Tobago",
		"en-GG": "Trinidad & Tobago",
		"en-IM": "Trinidad & Tobago",
		"en-CA": "Trinidad and Tobago",
		"en-AU": "Trinidad & Tobago",
		"en-NZ": "Trinidad & Tobago",
		"en-ZA": "Trinidad & Tobago",
		"en-IN": "Trinidad & Tobago",
		"en-SG": "Trinidad & Tobago",
		"pt-AO": "Trindade e Tobago",
		"pt-MZ": "Trindade e Tobago",
		"pt-CV": "Trindade e Tobago",
		"pt-GW": "Trindade e Tobago",
		"pt-ST": "Trindade e Tobago",
		"pt-TL": "Trindade e Tobago",
		"pt-MO": "Trindade e Tobago",
		"es-ES": "Trinidad y Tobago",
		"es-419": "Trinidad y Tobago",
		"es-AD": "Trinidad y Tobago",
		"es-GI": "Trinidad y Tobago",
		"es-AR": "Trinidad y Tobago",
		"es-BO": "Trinidad y Tobago",
		"es-BR": "Trinidad y Tobago",
		"es-BZ": "Trinidad y Tobago",
		"es-CL": "Trinidad y Tobago",
		"es-CO": "Trinidad y Tobago",
		"es-CR": "Trinidad y Tobago",
		"es-CU": "Trinidad y Tobago",
		"es-DO": "Trinidad y Tobago",
		"es-EC": "Trinidad y Tobago",
		"es-GT": "Trinidad y Tobago",
		"es-HN": "Trinidad y Tobago",
		"es-MX": "Trinidad y Tobago",
		"es-NI": "Trinidad y Tobago",
		"es-PA": "Trinidad y Tobago",
		"es-PE": "Trinidad y Tobago",
		"es-PR": "Trinidad y Tobago",
		"es-PY": "Trinidad y Tobago",
		"es-SV": "Trinidad y Tobago",
		"es-US": "Trinidad y Tobago",
		"es-UY": "Trinidad y Tobago",
		"es-VE": "Trinidad y Tobago",
		"fr-FR": "Trinité-et-Tobago",
		"fr-BE": "Trinité-et-Tobago",
		"fr-CH": "Trinité-et-Tobago",
		"fr-LU": "Trinité-et-Tobago",
		"fr-MC": "Trinité-et-Tobago",
		"fr-AD": "Trinité-et-Tobago",
		"fr-CA": "Trinité-et-Tobago",
		"it-IT": "Trinidad e Tobago",
		"it-CH": "Trinidad e Tobago",
		"it-SM": "Trinidad e Tobago",
		"it-VA": "Trinidad e Tobago",
		"de-DE": "Trinidad und Tobago",
		"de-AT": "Trinidad und Tobago",
		"de-CH": "Trinidad und Tobago",
		"de-BE": "Trinidad und Tobago",
		"de-LI": "Trinidad und Tobago",
		"de-LU": "Trinidad und Tobago",
		"nl-NL": "Trinidad en Tobago",
		"nl-BE": "Trinidad en Tobago",
		"sv-SE": "Trinidad och Tobago",
		"sv-FI": "Trinidad och Tobago",
		"da-DK": "Trinidad og Tobago",
		"nb-NO": "Trinidad og Tobago",
		"nn-NO": "Trinidad og Tobago",
		"fi-FI": "Trinidad ja Tobago",
		"is-IS": "Trínidad og Tóbagó",
		"fo-FO": "Trinidad & Tobago",
		"et-EE": "Trinidad ja Tobago",
		"lv-LV": "Trinidāda un Tobāgo",
		"lt-LT": "Trinidadas ir Tobagas",
		"pl-PL": "Trynidad i Tobago",
		"cs-CZ": "Trinidad a Tobago",
		"sk-SK": "Trinidad a Tobago",
		"sl-SI": "Trinidad in Tobago",
		"hr-HR": "Trinidad i Tobago",
		"bs-BA": "Trinidad i Tobago",
		"sr-RS": "Тринидад и Тобаго",
		"sr-BA": "Тринидад и Тобаго",
		"sr-ME": "Trinidad i Tobago",
		"mk-MK": "Тринидад и Тобаго",
		"bg-BG": "Тринидад и Тобаго",
		"be-BY": "Трынідад і Табага",
		"uk-UA": "Тринідад і Тобаго",
		"ru-RU": "Тринидад и Тобаго",
		"el-GR": "Τρινιντάντ και Τομπάγκο",
		"el-CY": "Τρινιντάντ και Τομπάγκο",
		"ro-RO": "Trinidad și Tobago",
		"ro-MD": "Trinidad și Tobago",
		"hu-HU": "Trinidad és Tobago",
		"sq-AL": "Trinidad e Tobago",
		"sq-XK": "Trinidad e Tobago",
		"mt-MT": "Trinidad u Tobago",
		"ga-IE": "Oileán na Tríonóide agus Tobága",
		"cy-GB": "Trinidad a Tobago",
		"gd-GB": "Trianaid agus Tobago",
		"lb-LU": "Trinidad an Tobago",
		"ca-ES": "Trinidad i Tobago",
		"ca-AD": "Trinidad i Tobago",
		"ca-FR": "Trinidad i Tobago",
		"ca-IT": "Trinidad i Tobago",
		"eu-ES": "Trinidad eta Tobago",
		"eu-FR": "Trinidad eta Tobago",
		"gl-ES": "Trinidad e Tobago",
		"tr-TR": "Trinidad ve Tobago",
		"tr-CY": "Trinidad ve Tobago"
	},
	"callingCode": "1868",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
