import type { Country } from './types.js';

export const TWN = {
	"code": "TWN",
	"labels": {
		"pt-BR": "Taiwan",
		"pt-PT": "Taiwan",
		"qu-PE": "Taiwán",
		"qu-BO": "Taiwán",
		"qu-EC": "Taiwán",
		"chr-US": "ᏔᎢᏩᏂ",
		"hi-IN": "ताइवान",
		"bn-IN": "তাইওয়ান",
		"bn-BD": "তাইওয়ান",
		"ta-IN": "தைவான்",
		"ta-LK": "தைவான்",
		"ta-SG": "தைவான்",
		"ta-MY": "தைவான்",
		"te-IN": "తైవాన్",
		"mr-IN": "तैवान",
		"gu-IN": "તાઇવાન",
		"kn-IN": "ತೈವಾನ್",
		"ml-IN": "തായ്‌വാൻ",
		"pa-IN": "ਤਾਇਵਾਨ",
		"ur-IN": "تائیوان",
		"ur-PK": "تائیوان",
		"or-IN": "ତାଇୱାନ",
		"as-IN": "টাইৱান",
		"ne-IN": "ताइवान",
		"ne-NP": "ताइवान",
		"si-LK": "තායිවානය",
		"kok-IN": "तायवान",
		"ks-IN": "تایوان",
		"brx-IN": "ताइवान",
		"mai-IN": "ताइबान",
		"dz-BT": "ཊཱའི་ཝཱན",
		"ja-JP": "台湾",
		"ko-KR": "대만",
		"ko-KP": "대만",
		"zh-CN": "台湾",
		"zh-Hans-CN": "台湾",
		"zh-Hant-TW": "台灣",
		"zh-TW": "台灣",
		"zh-HK": "台灣",
		"zh-MO": "台灣",
		"zh-SG": "台湾",
		"yue-Hant-HK": "台灣",
		"yue-Hans-CN": "台湾",
		"mn-MN": "Тайвань",
		"ug-CN": "تەيۋەن",
		"th-TH": "ไต้หวัน",
		"lo-LA": "ໄຕ້ຫວັນ",
		"km-KH": "តៃវ៉ាន់",
		"my-MM": "ထိုင်ဝမ်",
		"vi-VN": "Đài Loan",
		"id-ID": "Taiwan",
		"ms-MY": "Taiwan",
		"ms-SG": "Taiwan",
		"ms-BN": "Taiwan",
		"jv-ID": "Taiwan",
		"fil-PH": "Taiwan",
		"ceb-PH": "Taiwan",
		"ka-GE": "ტაივანი",
		"hy-AM": "Թայվան",
		"az-AZ": "Tayvan",
		"az-Cyrl-AZ": "Тајван",
		"kk-KZ": "Тайвань",
		"ky-KG": "Тайвань",
		"uz-UZ": "Tayvan",
		"tg-TJ": "Тайван",
		"tk-TM": "Taýwan",
		"fa-IR": "تایوان",
		"fa-AF": "تایوان",
		"ps-AF": "تائيوان",
		"ps-PK": "تائيوان",
		"he-IL": "טייוואן",
		"ar-SA": "تايوان",
		"ar-AE": "تايوان",
		"ar-QA": "تايوان",
		"ar-BH": "تايوان",
		"ar-KW": "تايوان",
		"ar-OM": "تايوان",
		"ar-YE": "تايوان",
		"ar-IQ": "تايوان",
		"ar-JO": "تايوان",
		"ar-LB": "تايوان",
		"ar-SY": "تايوان",
		"ar-PS": "تايوان",
		"en-US": "Taiwan",
		"en-GB": "Taiwan",
		"en-IE": "Taiwan",
		"en-MT": "Taiwan",
		"en-GI": "Taiwan",
		"en-CY": "Taiwan",
		"en-JE": "Taiwan",
		"en-GG": "Taiwan",
		"en-IM": "Taiwan",
		"en-CA": "Taiwan",
		"en-AU": "Taiwan",
		"en-NZ": "Taiwan",
		"en-ZA": "Taiwan",
		"en-IN": "Taiwan",
		"en-SG": "Taiwan",
		"pt-AO": "Taiwan",
		"pt-MZ": "Taiwan",
		"pt-CV": "Taiwan",
		"pt-GW": "Taiwan",
		"pt-ST": "Taiwan",
		"pt-TL": "Taiwan",
		"pt-MO": "Taiwan",
		"es-ES": "Taiwán",
		"es-419": "Taiwán",
		"es-AD": "Taiwán",
		"es-GI": "Taiwán",
		"es-AR": "Taiwán",
		"es-BO": "Taiwán",
		"es-BR": "Taiwán",
		"es-BZ": "Taiwán",
		"es-CL": "Taiwán",
		"es-CO": "Taiwán",
		"es-CR": "Taiwán",
		"es-CU": "Taiwán",
		"es-DO": "Taiwán",
		"es-EC": "Taiwán",
		"es-GT": "Taiwán",
		"es-HN": "Taiwán",
		"es-MX": "Taiwán",
		"es-NI": "Taiwán",
		"es-PA": "Taiwán",
		"es-PE": "Taiwán",
		"es-PR": "Taiwán",
		"es-PY": "Taiwán",
		"es-SV": "Taiwán",
		"es-US": "Taiwán",
		"es-UY": "Taiwán",
		"es-VE": "Taiwán",
		"fr-FR": "Taïwan",
		"fr-BE": "Taïwan",
		"fr-CH": "Taïwan",
		"fr-LU": "Taïwan",
		"fr-MC": "Taïwan",
		"fr-AD": "Taïwan",
		"fr-CA": "Taïwan",
		"it-IT": "Taiwan",
		"it-CH": "Taiwan",
		"it-SM": "Taiwan",
		"it-VA": "Taiwan",
		"de-DE": "Taiwan",
		"de-AT": "Taiwan",
		"de-CH": "Taiwan",
		"de-BE": "Taiwan",
		"de-LI": "Taiwan",
		"de-LU": "Taiwan",
		"nl-NL": "Taiwan",
		"nl-BE": "Taiwan",
		"sv-SE": "Taiwan",
		"sv-FI": "Taiwan",
		"da-DK": "Taiwan",
		"nb-NO": "Taiwan",
		"nn-NO": "Taiwan",
		"fi-FI": "Taiwan",
		"is-IS": "Taívan",
		"fo-FO": "Taivan",
		"et-EE": "Taiwan",
		"lv-LV": "Taivāna",
		"lt-LT": "Taivanas",
		"pl-PL": "Tajwan",
		"cs-CZ": "Tchaj-wan",
		"sk-SK": "Taiwan",
		"sl-SI": "Tajvan",
		"hr-HR": "Tajvan",
		"bs-BA": "Tajvan",
		"sr-RS": "Тајван",
		"sr-BA": "Тајван",
		"sr-ME": "Tajvan",
		"mk-MK": "Тајван",
		"bg-BG": "Тайван",
		"be-BY": "Тайвань",
		"uk-UA": "Тайвань",
		"ru-RU": "Тайвань",
		"el-GR": "Ταϊβάν",
		"el-CY": "Ταϊβάν",
		"ro-RO": "Taiwan",
		"ro-MD": "Taiwan",
		"hu-HU": "Tajvan",
		"sq-AL": "Tajvan",
		"sq-XK": "Tajvan",
		"mt-MT": "it-Tajwan",
		"ga-IE": "an Téaváin",
		"cy-GB": "Taiwan",
		"gd-GB": "Taidh-Bhàn",
		"lb-LU": "Taiwan",
		"ca-ES": "Taiwan",
		"ca-AD": "Taiwan",
		"ca-FR": "Taiwan",
		"ca-IT": "Taiwan",
		"eu-ES": "Taiwan",
		"eu-FR": "Taiwan",
		"gl-ES": "Taiwán",
		"tr-TR": "Tayvan",
		"tr-CY": "Tayvan"
	},
	"callingCode": "886",
	"phoneMasks": [
		{
			"mask": "## # ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"202"
			]
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "# #### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[23568]|4(?:0[02-48]|[1-47-9])|7[1-9]",
				"[23568]|4(?:0[2-48]|[1-47-9])|(?:400|7)[1-9]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[258]0"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[49]"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "## #### #####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"7"
			]
		}
	]
} satisfies Country;
