import type { Country } from './types.js';

export const VAT = {
	"code": "VAT",
	"labels": {
		"pt-BR": "Cidade do Vaticano",
		"pt-PT": "Cidade do Vaticano",
		"qu-PE": "Santa Sede (Ciudad del Vaticano)",
		"qu-BO": "Santa Sede (Ciudad del Vaticano)",
		"qu-EC": "Santa Sede (Ciudad del Vaticano)",
		"chr-US": "ᎠᏥᎳᏁᏠ ᎦᏚᎲ",
		"hi-IN": "वेटिकन सिटी",
		"bn-IN": "ভ্যাটিকান সিটি",
		"bn-BD": "ভ্যাটিকান সিটি",
		"ta-IN": "வாடிகன் நகரம்",
		"ta-LK": "வாடிகன் நகரம்",
		"ta-SG": "வாடிகன் நகரம்",
		"ta-MY": "வாடிகன் நகரம்",
		"te-IN": "వాటికన్ నగరం",
		"mr-IN": "व्हॅटिकन सिटी",
		"gu-IN": "વેટિકન સિટી",
		"kn-IN": "ವ್ಯಾಟಿಕನ್ ಸಿಟಿ",
		"ml-IN": "വത്തിക്കാൻ",
		"pa-IN": "ਵੈਟੀਕਨ ਸਿਟੀ",
		"ur-IN": "ویٹیکن سٹی",
		"ur-PK": "ویٹیکن سٹی",
		"or-IN": "ଭାଟିକାନ୍ ସିଟି",
		"as-IN": "ভেটিকান চিটি",
		"ne-IN": "भेटिकन सिटी",
		"ne-NP": "भेटिकन सिटी",
		"si-LK": "වතිකානු නගරය",
		"kok-IN": "वॅटिकन सिटी",
		"ks-IN": "ویٹِکَن سِٹی",
		"brx-IN": "भेटिकान नोगोर",
		"mai-IN": "वेटिकन सिटी",
		"dz-BT": "བ་ཊི་ཀཱན་ སི་ཊི",
		"ja-JP": "バチカン市国",
		"ko-KR": "바티칸 시국",
		"ko-KP": "바티칸 시국",
		"zh-CN": "梵蒂冈",
		"zh-Hans-CN": "梵蒂冈",
		"zh-Hant-TW": "梵蒂岡",
		"zh-TW": "梵蒂岡",
		"zh-HK": "梵蒂岡",
		"zh-MO": "梵蒂岡",
		"zh-SG": "梵蒂冈",
		"yue-Hant-HK": "梵蒂岡",
		"yue-Hans-CN": "梵蒂冈",
		"mn-MN": "Ватикан хот улс",
		"ug-CN": "ۋاتىكان",
		"th-TH": "นครวาติกัน",
		"lo-LA": "ນະຄອນ ວາຕິກັນ",
		"km-KH": "បុរី​វ៉ាទីកង់",
		"my-MM": "ဗာတီကန်စီးတီး",
		"vi-VN": "Thành Vatican",
		"id-ID": "Vatikan",
		"ms-MY": "Kota Vatican",
		"ms-SG": "Kota Vatican",
		"ms-BN": "Kota Vatican",
		"jv-ID": "Kutha Vatikan",
		"fil-PH": "Vatican City",
		"ceb-PH": "Vatican City",
		"ka-GE": "ქალაქი ვატიკანი",
		"hy-AM": "Վատիկան",
		"az-AZ": "Vatikan",
		"az-Cyrl-AZ": "Ватикан",
		"kk-KZ": "Ватикан",
		"ky-KG": "Ватикан",
		"uz-UZ": "Vatikan",
		"tg-TJ": "Шаҳри Вотикон",
		"tk-TM": "Watikan",
		"fa-IR": "واتیکان",
		"fa-AF": "واتیکان",
		"ps-AF": "واتیکان ښار",
		"ps-PK": "واتیکان ښار",
		"he-IL": "הוותיקן",
		"ar-SA": "الفاتيكان",
		"ar-AE": "الفاتيكان",
		"ar-QA": "الفاتيكان",
		"ar-BH": "الفاتيكان",
		"ar-KW": "الفاتيكان",
		"ar-OM": "الفاتيكان",
		"ar-YE": "الفاتيكان",
		"ar-IQ": "الفاتيكان",
		"ar-JO": "الفاتيكان",
		"ar-LB": "الفاتيكان",
		"ar-SY": "الفاتيكان",
		"ar-PS": "الفاتيكان",
		"en-US": "Vatican City",
		"en-GB": "Vatican City",
		"en-IE": "Vatican City",
		"en-MT": "Vatican City",
		"en-GI": "Vatican City",
		"en-CY": "Vatican City",
		"en-JE": "Vatican City",
		"en-GG": "Vatican City",
		"en-IM": "Vatican City",
		"en-CA": "Vatican City",
		"en-AU": "Vatican City",
		"en-NZ": "Vatican City",
		"en-ZA": "Vatican City",
		"en-IN": "Vatican City",
		"en-SG": "Vatican City",
		"pt-AO": "Cidade do Vaticano",
		"pt-MZ": "Cidade do Vaticano",
		"pt-CV": "Cidade do Vaticano",
		"pt-GW": "Cidade do Vaticano",
		"pt-ST": "Cidade do Vaticano",
		"pt-TL": "Cidade do Vaticano",
		"pt-MO": "Cidade do Vaticano",
		"es-ES": "Ciudad del Vaticano",
		"es-419": "Ciudad del Vaticano",
		"es-AD": "Ciudad del Vaticano",
		"es-GI": "Ciudad del Vaticano",
		"es-AR": "Ciudad del Vaticano",
		"es-BO": "Ciudad del Vaticano",
		"es-BR": "Ciudad del Vaticano",
		"es-BZ": "Ciudad del Vaticano",
		"es-CL": "Ciudad del Vaticano",
		"es-CO": "Ciudad del Vaticano",
		"es-CR": "Ciudad del Vaticano",
		"es-CU": "Ciudad del Vaticano",
		"es-DO": "Ciudad del Vaticano",
		"es-EC": "Ciudad del Vaticano",
		"es-GT": "Ciudad del Vaticano",
		"es-HN": "Ciudad del Vaticano",
		"es-MX": "Ciudad del Vaticano",
		"es-NI": "Ciudad del Vaticano",
		"es-PA": "Ciudad del Vaticano",
		"es-PE": "Ciudad del Vaticano",
		"es-PR": "Ciudad del Vaticano",
		"es-PY": "Ciudad del Vaticano",
		"es-SV": "Ciudad del Vaticano",
		"es-US": "Ciudad del Vaticano",
		"es-UY": "Ciudad del Vaticano",
		"es-VE": "Ciudad del Vaticano",
		"fr-FR": "État de la Cité du Vatican",
		"fr-BE": "État de la Cité du Vatican",
		"fr-CH": "État de la Cité du Vatican",
		"fr-LU": "État de la Cité du Vatican",
		"fr-MC": "État de la Cité du Vatican",
		"fr-AD": "État de la Cité du Vatican",
		"fr-CA": "Cité du Vatican",
		"it-IT": "Città del Vaticano",
		"it-CH": "Città del Vaticano",
		"it-SM": "Città del Vaticano",
		"it-VA": "Città del Vaticano",
		"de-DE": "Vatikanstadt",
		"de-AT": "Vatikanstadt",
		"de-CH": "Vatikanstadt",
		"de-BE": "Vatikanstadt",
		"de-LI": "Vatikanstadt",
		"de-LU": "Vatikanstadt",
		"nl-NL": "Vaticaanstad",
		"nl-BE": "Vaticaanstad",
		"sv-SE": "Vatikanstaten",
		"sv-FI": "Vatikanstaten",
		"da-DK": "Vatikanstaten",
		"nb-NO": "Vatikanstaten",
		"nn-NO": "Vatikanstaten",
		"fi-FI": "Vatikaani",
		"is-IS": "Vatíkanið",
		"fo-FO": "Vatikanbýur",
		"et-EE": "Vatikan",
		"lv-LV": "Vatikāns",
		"lt-LT": "Vatikano Miesto Valstybė",
		"pl-PL": "Watykan",
		"cs-CZ": "Vatikán",
		"sk-SK": "Vatikán",
		"sl-SI": "Vatikan",
		"hr-HR": "Vatikan",
		"bs-BA": "Vatikan",
		"sr-RS": "Ватикан",
		"sr-BA": "Ватикан",
		"sr-ME": "Vatikan",
		"mk-MK": "Ватикан",
		"bg-BG": "Ватикан",
		"be-BY": "Ватыкан",
		"uk-UA": "Ватикан",
		"ru-RU": "Ватикан",
		"el-GR": "Βατικανό",
		"el-CY": "Βατικανό",
		"ro-RO": "Statul Cetății Vaticanului",
		"ro-MD": "Statul Cetății Vaticanului",
		"hu-HU": "Vatikán",
		"sq-AL": "Vatikan",
		"sq-XK": "Vatikan",
		"mt-MT": "l-Istat tal-Belt tal-Vatikan",
		"ga-IE": "Cathair na Vatacáine",
		"cy-GB": "Y Fatican",
		"gd-GB": "Cathair na Bhatacain",
		"lb-LU": "Vatikanstad",
		"ca-ES": "Ciutat del Vaticà",
		"ca-AD": "Ciutat del Vaticà",
		"ca-FR": "Ciutat del Vaticà",
		"ca-IT": "Ciutat del Vaticà",
		"eu-ES": "Vatikano Hiria",
		"eu-FR": "Vatikano Hiria",
		"gl-ES": "Cidade do Vaticano",
		"tr-TR": "Vatikan",
		"tr-CY": "Vatikan"
	},
	"callingCode": "3906698",
	"phoneMasks": [
		{
			"mask": "#",
			"minLength": 1,
			"maxLength": 1
		},
		{
			"mask": "##",
			"minLength": 2,
			"maxLength": 2
		},
		{
			"mask": "###",
			"minLength": 3,
			"maxLength": 3
		},
		{
			"mask": "####",
			"minLength": 4,
			"maxLength": 4
		},
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		}
	]
} satisfies Country;
