import type { Country } from './types.js';

export const VNM = {
	"code": "VNM",
	"labels": {
		"pt-BR": "Vietnã",
		"pt-PT": "Vietname",
		"qu-PE": "Vietnam",
		"qu-BO": "Vietnam",
		"qu-EC": "Vietnam",
		"chr-US": "ᏫᎡᏘᎾᎻ",
		"hi-IN": "वियतनाम",
		"bn-IN": "ভিয়েতনাম",
		"bn-BD": "ভিয়েতনাম",
		"ta-IN": "வியட்நாம்",
		"ta-LK": "வியட்நாம்",
		"ta-SG": "வியட்நாம்",
		"ta-MY": "வியட்நாம்",
		"te-IN": "వియత్నాం",
		"mr-IN": "व्हिएतनाम",
		"gu-IN": "વિયેતનામ",
		"kn-IN": "ವಿಯೆಟ್ನಾಮ್",
		"ml-IN": "വിയറ്റ്നാം",
		"pa-IN": "ਵੀਅਤਨਾਮ",
		"ur-IN": "ویتنام",
		"ur-PK": "ویتنام",
		"or-IN": "ଭିଏତନାମ୍",
		"as-IN": "ভিয়েটনাম",
		"ne-IN": "भिएतनाम",
		"ne-NP": "भिएतनाम",
		"si-LK": "වියට්නාමය",
		"kok-IN": "व्हिएतनाम",
		"ks-IN": "ویتنام",
		"brx-IN": "भियेतनाम",
		"mai-IN": "बियतनाम",
		"dz-BT": "བེཊ་ནཱམ",
		"ja-JP": "ベトナム",
		"ko-KR": "베트남",
		"ko-KP": "베트남",
		"zh-CN": "越南",
		"zh-Hans-CN": "越南",
		"zh-Hant-TW": "越南",
		"zh-TW": "越南",
		"zh-HK": "越南",
		"zh-MO": "越南",
		"zh-SG": "越南",
		"yue-Hant-HK": "越南",
		"yue-Hans-CN": "越南",
		"mn-MN": "Вьетнам",
		"ug-CN": "ۋىيېتنام",
		"th-TH": "เวียดนาม",
		"lo-LA": "ຫວຽດນາມ",
		"km-KH": "វៀតណាម",
		"my-MM": "ဗီယက်နမ်",
		"vi-VN": "Việt Nam",
		"id-ID": "Vietnam",
		"ms-MY": "Vietnam",
		"ms-SG": "Vietnam",
		"ms-BN": "Vietnam",
		"jv-ID": "Viètnam",
		"fil-PH": "Vietnam",
		"ceb-PH": "Vietnam",
		"ka-GE": "ვიეტნამი",
		"hy-AM": "Վիետնամ",
		"az-AZ": "Vyetnam",
		"az-Cyrl-AZ": "Вјетнам",
		"kk-KZ": "Вьетнам",
		"ky-KG": "Вьетнам",
		"uz-UZ": "Vyetnam",
		"tg-TJ": "Ветнам",
		"tk-TM": "Wýetnam",
		"fa-IR": "ویتنام",
		"fa-AF": "ویتنام",
		"ps-AF": "وېتنام",
		"ps-PK": "وېتنام",
		"he-IL": "וייטנאם",
		"ar-SA": "فيتنام",
		"ar-AE": "فيتنام",
		"ar-QA": "فيتنام",
		"ar-BH": "فيتنام",
		"ar-KW": "فيتنام",
		"ar-OM": "فيتنام",
		"ar-YE": "فيتنام",
		"ar-IQ": "فيتنام",
		"ar-JO": "فيتنام",
		"ar-LB": "فيتنام",
		"ar-SY": "فيتنام",
		"ar-PS": "فيتنام",
		"en-US": "Vietnam",
		"en-GB": "Vietnam",
		"en-IE": "Vietnam",
		"en-MT": "Vietnam",
		"en-GI": "Vietnam",
		"en-CY": "Vietnam",
		"en-JE": "Vietnam",
		"en-GG": "Vietnam",
		"en-IM": "Vietnam",
		"en-CA": "Vietnam",
		"en-AU": "Vietnam",
		"en-NZ": "Vietnam",
		"en-ZA": "Vietnam",
		"en-IN": "Vietnam",
		"en-SG": "Vietnam",
		"pt-AO": "Vietname",
		"pt-MZ": "Vietname",
		"pt-CV": "Vietname",
		"pt-GW": "Vietname",
		"pt-ST": "Vietname",
		"pt-TL": "Vietname",
		"pt-MO": "Vietname",
		"es-ES": "Vietnam",
		"es-419": "Vietnam",
		"es-AD": "Vietnam",
		"es-GI": "Vietnam",
		"es-AR": "Vietnam",
		"es-BO": "Vietnam",
		"es-BR": "Vietnam",
		"es-BZ": "Vietnam",
		"es-CL": "Vietnam",
		"es-CO": "Vietnam",
		"es-CR": "Vietnam",
		"es-CU": "Vietnam",
		"es-DO": "Vietnam",
		"es-EC": "Vietnam",
		"es-GT": "Vietnam",
		"es-HN": "Vietnam",
		"es-MX": "Vietnam",
		"es-NI": "Vietnam",
		"es-PA": "Vietnam",
		"es-PE": "Vietnam",
		"es-PR": "Vietnam",
		"es-PY": "Vietnam",
		"es-SV": "Vietnam",
		"es-US": "Vietnam",
		"es-UY": "Vietnam",
		"es-VE": "Vietnam",
		"fr-FR": "Viêt Nam",
		"fr-BE": "Viêt Nam",
		"fr-CH": "Viêt Nam",
		"fr-LU": "Viêt Nam",
		"fr-MC": "Viêt Nam",
		"fr-AD": "Viêt Nam",
		"fr-CA": "Vietnam",
		"it-IT": "Vietnam",
		"it-CH": "Vietnam",
		"it-SM": "Vietnam",
		"it-VA": "Vietnam",
		"de-DE": "Vietnam",
		"de-AT": "Vietnam",
		"de-CH": "Vietnam",
		"de-BE": "Vietnam",
		"de-LI": "Vietnam",
		"de-LU": "Vietnam",
		"nl-NL": "Vietnam",
		"nl-BE": "Vietnam",
		"sv-SE": "Vietnam",
		"sv-FI": "Vietnam",
		"da-DK": "Vietnam",
		"nb-NO": "Vietnam",
		"nn-NO": "Vietnam",
		"fi-FI": "Vietnam",
		"is-IS": "Víetnam",
		"fo-FO": "Vjetnam",
		"et-EE": "Vietnam",
		"lv-LV": "Vjetnama",
		"lt-LT": "Vietnamas",
		"pl-PL": "Wietnam",
		"cs-CZ": "Vietnam",
		"sk-SK": "Vietnam",
		"sl-SI": "Vietnam",
		"hr-HR": "Vijetnam",
		"bs-BA": "Vijetnam",
		"sr-RS": "Вијетнам",
		"sr-BA": "Вијетнам",
		"sr-ME": "Vijetnam",
		"mk-MK": "Виетнам",
		"bg-BG": "Виетнам",
		"be-BY": "В’етнам",
		"uk-UA": "Вʼєтнам",
		"ru-RU": "Вьетнам",
		"el-GR": "Βιετνάμ",
		"el-CY": "Βιετνάμ",
		"ro-RO": "Vietnam",
		"ro-MD": "Vietnam",
		"hu-HU": "Vietnám",
		"sq-AL": "Vietnam",
		"sq-XK": "Vietnam",
		"mt-MT": "il-Vjetnam",
		"ga-IE": "Vítneam",
		"cy-GB": "Fietnam",
		"gd-GB": "Bhiet-Nam",
		"lb-LU": "Vietnam",
		"ca-ES": "Vietnam",
		"ca-AD": "Vietnam",
		"ca-FR": "Vietnam",
		"ca-IT": "Vietnam",
		"eu-ES": "Vietnam",
		"eu-FR": "Vietnam",
		"gl-ES": "Vietnam",
		"tr-TR": "Vietnam",
		"tr-CY": "Vietnam"
	},
	"callingCode": "84",
	"phoneMasks": [
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"80"
			]
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "## ### ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"6"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[357-9]"
			]
		},
		{
			"mask": "## #### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2[48]"
			]
		},
		{
			"mask": "### #### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "#### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1"
			]
		}
	]
} satisfies Country;
