import type { Country } from './types.js';

export const WLF = {
	"code": "WLF",
	"labels": {
		"pt-BR": "Wallis e Futuna",
		"pt-PT": "Wallis e Futuna",
		"qu-PE": "Wallis y Futuna",
		"qu-BO": "Wallis y Futuna",
		"qu-EC": "Wallis y Futuna",
		"chr-US": "ᏩᎵᏍ ᎠᎴ ᏊᏚᎾ",
		"hi-IN": "वालिस और फ़्यूचूना",
		"bn-IN": "ওয়ালিস ও ফুটুনা",
		"bn-BD": "ওয়ালিস ও ফুটুনা",
		"ta-IN": "வாலிஸ் மற்றும் ஃபுடுனா",
		"ta-LK": "வாலிஸ் மற்றும் ஃபுடுனா",
		"ta-SG": "வாலிஸ் மற்றும் ஃபுடுனா",
		"ta-MY": "வாலிஸ் மற்றும் ஃபுடுனா",
		"te-IN": "వాల్లిస్ మరియు ఫుటునా",
		"mr-IN": "वालिस आणि फ्यूचूना",
		"gu-IN": "વૉલિસ અને ફ્યુચુના",
		"kn-IN": "ವಾಲಿಸ್ ಮತ್ತು ಫುಟುನಾ",
		"ml-IN": "വാലിസ് ആന്റ് ഫ്യൂച്യുന",
		"pa-IN": "ਵਾਲਿਸ ਅਤੇ ਫੂਟੂਨਾ",
		"ur-IN": "ویلیز اور فیوٹیونا",
		"ur-PK": "ویلیز اور فیوٹیونا",
		"or-IN": "ୱାଲିସ୍ ଏବଂ ଫୁତୁନା",
		"as-IN": "ৱালিছ আৰু ফুটুনা",
		"ne-IN": "वालिस र फुटुना",
		"ne-NP": "वालिस र फुटुना",
		"si-LK": "වැලිස් සහ ෆුටුනා",
		"kok-IN": "वालिस आनी फ्यूचूना",
		"ks-IN": "والِس تہٕ فیوٗچوٗنا",
		"brx-IN": "वालिस आरो फ्युचुना",
		"mai-IN": "बालिस आ फुटुना",
		"dz-BT": "ཝལ་ལིས྄་ ཨེནཌ་ ཕུ་ཏུ་ན་",
		"ja-JP": "ウォリス・フツナ",
		"ko-KR": "왈리스-푸투나 제도",
		"ko-KP": "왈리스-푸투나 제도",
		"zh-CN": "瓦利斯和富图纳",
		"zh-Hans-CN": "瓦利斯和富图纳",
		"zh-Hant-TW": "瓦利斯群島和富圖那群島",
		"zh-TW": "瓦利斯群島和富圖那群島",
		"zh-HK": "瓦利斯群島和富圖那群島",
		"zh-MO": "瓦利斯群島和富圖那群島",
		"zh-SG": "瓦利斯和富图纳",
		"yue-Hant-HK": "瓦利斯同富圖納群島",
		"yue-Hans-CN": "瓦利斯同富图纳群岛",
		"mn-MN": "Уоллис ба Футуна",
		"ug-CN": "ۋاللىس ۋە فۇتۇنا",
		"th-TH": "วาลลิสและฟุตูนา",
		"lo-LA": "ວາລລິສ ແລະ ຟູຕູນາ",
		"km-KH": "វ៉ាលីស និង​ហ្វូទូណា",
		"my-MM": "ဝေါလစ်နှင့် ဖူကျူးနား",
		"vi-VN": "Wallis và Futuna",
		"id-ID": "Kepulauan Wallis dan Futuna",
		"ms-MY": "Wallis dan Futuna",
		"ms-SG": "Wallis dan Futuna",
		"ms-BN": "Wallis dan Futuna",
		"jv-ID": "Wallis lan Futuna",
		"fil-PH": "Wallis & Futuna",
		"ceb-PH": "Wallis & Futuna",
		"ka-GE": "უოლისი და ფუტუნა",
		"hy-AM": "Ուոլիս և Ֆուտունա",
		"az-AZ": "Uollis və Futuna",
		"az-Cyrl-AZ": "Уоллис вә Футуна",
		"kk-KZ": "Уоллис және Футуна",
		"ky-KG": "Уоллис жана Футуна",
		"uz-UZ": "Uollis va Futuna",
		"tg-TJ": "Уоллис ва Футуна",
		"tk-TM": "Uollis we Futuna",
		"fa-IR": "والیس و فوتونا",
		"fa-AF": "والیس و فوتونا",
		"ps-AF": "والیس او فوتونا",
		"ps-PK": "والیس او فوتونا",
		"he-IL": "איי ווליס ופוטונה",
		"ar-SA": "جزر والس وفوتونا",
		"ar-AE": "جزر والس وفوتونا",
		"ar-QA": "جزر والس وفوتونا",
		"ar-BH": "جزر والس وفوتونا",
		"ar-KW": "جزر والس وفوتونا",
		"ar-OM": "جزر والس وفوتونا",
		"ar-YE": "جزر والس وفوتونا",
		"ar-IQ": "جزر والس وفوتونا",
		"ar-JO": "جزر والس وفوتونا",
		"ar-LB": "جزر والس وفوتونا",
		"ar-SY": "جزر والس وفوتونا",
		"ar-PS": "جزر والس وفوتونا",
		"en-US": "Wallis & Futuna",
		"en-GB": "Wallis & Futuna",
		"en-IE": "Wallis & Futuna",
		"en-MT": "Wallis & Futuna",
		"en-GI": "Wallis & Futuna",
		"en-CY": "Wallis & Futuna",
		"en-JE": "Wallis & Futuna",
		"en-GG": "Wallis & Futuna",
		"en-IM": "Wallis & Futuna",
		"en-CA": "Wallis and Futuna",
		"en-AU": "Wallis & Futuna",
		"en-NZ": "Wallis & Futuna",
		"en-ZA": "Wallis & Futuna",
		"en-IN": "Wallis & Futuna",
		"en-SG": "Wallis & Futuna",
		"pt-AO": "Wallis e Futuna",
		"pt-MZ": "Wallis e Futuna",
		"pt-CV": "Wallis e Futuna",
		"pt-GW": "Wallis e Futuna",
		"pt-ST": "Wallis e Futuna",
		"pt-TL": "Wallis e Futuna",
		"pt-MO": "Wallis e Futuna",
		"es-ES": "Wallis y Futuna",
		"es-419": "Wallis y Futuna",
		"es-AD": "Wallis y Futuna",
		"es-GI": "Wallis y Futuna",
		"es-AR": "Wallis y Futuna",
		"es-BO": "Wallis y Futuna",
		"es-BR": "Wallis y Futuna",
		"es-BZ": "Wallis y Futuna",
		"es-CL": "Wallis y Futuna",
		"es-CO": "Wallis y Futuna",
		"es-CR": "Wallis y Futuna",
		"es-CU": "Wallis y Futuna",
		"es-DO": "Wallis y Futuna",
		"es-EC": "Wallis y Futuna",
		"es-GT": "Wallis y Futuna",
		"es-HN": "Wallis y Futuna",
		"es-MX": "Wallis y Futuna",
		"es-NI": "Wallis y Futuna",
		"es-PA": "Wallis y Futuna",
		"es-PE": "Wallis y Futuna",
		"es-PR": "Wallis y Futuna",
		"es-PY": "Wallis y Futuna",
		"es-SV": "Wallis y Futuna",
		"es-US": "Wallis y Futuna",
		"es-UY": "Wallis y Futuna",
		"es-VE": "Wallis y Futuna",
		"fr-FR": "Wallis-et-Futuna",
		"fr-BE": "Wallis-et-Futuna",
		"fr-CH": "Wallis-et-Futuna",
		"fr-LU": "Wallis-et-Futuna",
		"fr-MC": "Wallis-et-Futuna",
		"fr-AD": "Wallis-et-Futuna",
		"fr-CA": "Wallis-et-Futuna",
		"it-IT": "Wallis e Futuna",
		"it-CH": "Wallis e Futuna",
		"it-SM": "Wallis e Futuna",
		"it-VA": "Wallis e Futuna",
		"de-DE": "Wallis und Futuna",
		"de-AT": "Wallis und Futuna",
		"de-CH": "Wallis und Futuna",
		"de-BE": "Wallis und Futuna",
		"de-LI": "Wallis und Futuna",
		"de-LU": "Wallis und Futuna",
		"nl-NL": "Wallis en Futuna",
		"nl-BE": "Wallis en Futuna",
		"sv-SE": "Wallis- och Futunaöarna",
		"sv-FI": "Wallis- och Futunaöarna",
		"da-DK": "Wallis og Futuna",
		"nb-NO": "Wallis og Futuna",
		"nn-NO": "Wallis og Futuna",
		"fi-FI": "Wallis ja Futuna",
		"is-IS": "Wallis- og Fútúnaeyjar",
		"fo-FO": "Wallis- og Futunaoyggjar",
		"et-EE": "Wallis ja Futuna",
		"lv-LV": "Volisa un Futunas salas",
		"lt-LT": "Volisas ir Futūna",
		"pl-PL": "Wallis i Futuna",
		"cs-CZ": "Wallis a Futuna",
		"sk-SK": "Wallis a Futuna",
		"sl-SI": "Wallis in Futuna",
		"hr-HR": "Wallis i Futuna",
		"bs-BA": "Ostrva Valis i Futuna",
		"sr-RS": "Валис и Футуна",
		"sr-BA": "Валис и Футуна",
		"sr-ME": "Valis i Futuna",
		"mk-MK": "Валис и Футуна",
		"bg-BG": "Уолис и Футуна",
		"be-BY": "Уоліс і Футуна",
		"uk-UA": "Уолліс і Футуна",
		"ru-RU": "Уоллис и Футуна",
		"el-GR": "Γουάλις και Φουτούνα",
		"el-CY": "Γουάλις και Φουτούνα",
		"ro-RO": "Wallis și Futuna",
		"ro-MD": "Wallis și Futuna",
		"hu-HU": "Wallis és Futuna",
		"sq-AL": "Uollis e Futuna",
		"sq-XK": "Uollis e Futuna",
		"mt-MT": "Wallis u Futuna",
		"ga-IE": "Vailís agus Futúna",
		"cy-GB": "Wallis a Futuna",
		"gd-GB": "Uallas agus Futuna",
		"lb-LU": "Wallis a Futuna",
		"ca-ES": "Wallis i Futuna",
		"ca-AD": "Wallis i Futuna",
		"ca-FR": "Wallis i Futuna",
		"ca-IT": "Wallis i Futuna",
		"eu-ES": "Wallis eta Futuna",
		"eu-FR": "Wallis eta Futuna",
		"gl-ES": "Wallis e Futuna",
		"tr-TR": "Wallis ve Futuna",
		"tr-CY": "Wallis ve Futuna"
	},
	"callingCode": "681",
	"phoneMasks": [
		{
			"mask": "## ## ##",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"[47-9]"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
