import type { Country } from './types.js';

export const ZAF = {
	"code": "ZAF",
	"labels": {
		"pt-BR": "África do Sul",
		"pt-PT": "África do Sul",
		"qu-PE": "Sudáfrica",
		"qu-BO": "Sudáfrica",
		"qu-EC": "Sudáfrica",
		"chr-US": "ᏧᎦᎾᏮ ᎬᎿᎨᏍᏛ",
		"hi-IN": "दक्षिण अफ़्रीका",
		"bn-IN": "দক্ষিণ আফ্রিকা",
		"bn-BD": "দক্ষিণ আফ্রিকা",
		"ta-IN": "தென் ஆப்பிரிக்கா",
		"ta-LK": "தென் ஆப்பிரிக்கா",
		"ta-SG": "தென் ஆப்பிரிக்கா",
		"ta-MY": "தென் ஆப்பிரிக்கா",
		"te-IN": "దక్షిణ ఆఫ్రికా",
		"mr-IN": "दक्षिण आफ्रिका",
		"gu-IN": "દક્ષિણ આફ્રિકા",
		"kn-IN": "ದಕ್ಷಿಣ ಆಫ್ರಿಕಾ",
		"ml-IN": "ദക്ഷിണാഫ്രിക്ക",
		"pa-IN": "ਦੱਖਣੀ ਅਫਰੀਕਾ",
		"ur-IN": "جنوبی افریقہ",
		"ur-PK": "جنوبی افریقہ",
		"or-IN": "ଦକ୍ଷିଣ ଆଫ୍ରିକା",
		"as-IN": "দক্ষিণ আফ্রিকা",
		"ne-IN": "दक्षिण अफ्रिका",
		"ne-NP": "दक्षिण अफ्रिका",
		"si-LK": "දකුණු අප්‍රිකාව",
		"kok-IN": "दक्षिण आफ्रीका",
		"ks-IN": "جنوبی افریقہ",
		"brx-IN": "खोला आफ्रिका",
		"mai-IN": "दक्षिण अफ्रीका",
		"dz-BT": "སཱའུཐ་ ཨཕ་རི་ཀ",
		"ja-JP": "南アフリカ",
		"ko-KR": "남아프리카",
		"ko-KP": "남아프리카",
		"zh-CN": "南非",
		"zh-Hans-CN": "南非",
		"zh-Hant-TW": "南非",
		"zh-TW": "南非",
		"zh-HK": "南非",
		"zh-MO": "南非",
		"zh-SG": "南非",
		"yue-Hant-HK": "南非",
		"yue-Hans-CN": "南非",
		"mn-MN": "Өмнөд Африк",
		"ug-CN": "جەنۇبىي ئافرىقا",
		"th-TH": "แอฟริกาใต้",
		"lo-LA": "ອາຟຣິກາໃຕ້",
		"km-KH": "អាហ្វ្រិកខាងត្បូង",
		"my-MM": "တောင်အာဖရိက",
		"vi-VN": "Nam Phi",
		"id-ID": "Afrika Selatan",
		"ms-MY": "Afrika Selatan",
		"ms-SG": "Afrika Selatan",
		"ms-BN": "Afrika Selatan",
		"jv-ID": "Afrika Kidul",
		"fil-PH": "South Africa",
		"ceb-PH": "South Africa",
		"ka-GE": "სამხრეთ აფრიკის რესპუბლიკა",
		"hy-AM": "Հարավաֆրիկյան Հանրապետություն",
		"az-AZ": "Cənub Afrika",
		"az-Cyrl-AZ": "Ҹәнуб Африка",
		"kk-KZ": "Оңтүстік Африка",
		"ky-KG": "Түштүк-Африка Республикасы",
		"uz-UZ": "Janubiy Afrika Respublikasi",
		"tg-TJ": "Африкаи Ҷанубӣ",
		"tk-TM": "Günorta Afrika",
		"fa-IR": "افریقای جنوبی",
		"fa-AF": "افریقای جنوبی",
		"ps-AF": "سویلي افریقا",
		"ps-PK": "سویلي افریقا",
		"he-IL": "דרום אפריקה",
		"ar-SA": "جنوب أفريقيا",
		"ar-AE": "جنوب أفريقيا",
		"ar-QA": "جنوب أفريقيا",
		"ar-BH": "جنوب أفريقيا",
		"ar-KW": "جنوب أفريقيا",
		"ar-OM": "جنوب أفريقيا",
		"ar-YE": "جنوب أفريقيا",
		"ar-IQ": "جنوب أفريقيا",
		"ar-JO": "جنوب أفريقيا",
		"ar-LB": "جنوب أفريقيا",
		"ar-SY": "جنوب أفريقيا",
		"ar-PS": "جنوب أفريقيا",
		"en-US": "South Africa",
		"en-GB": "South Africa",
		"en-IE": "South Africa",
		"en-MT": "South Africa",
		"en-GI": "South Africa",
		"en-CY": "South Africa",
		"en-JE": "South Africa",
		"en-GG": "South Africa",
		"en-IM": "South Africa",
		"en-CA": "South Africa",
		"en-AU": "South Africa",
		"en-NZ": "South Africa",
		"en-ZA": "South Africa",
		"en-IN": "South Africa",
		"en-SG": "South Africa",
		"pt-AO": "África do Sul",
		"pt-MZ": "África do Sul",
		"pt-CV": "África do Sul",
		"pt-GW": "África do Sul",
		"pt-ST": "África do Sul",
		"pt-TL": "África do Sul",
		"pt-MO": "África do Sul",
		"es-ES": "Sudáfrica",
		"es-419": "Sudáfrica",
		"es-AD": "Sudáfrica",
		"es-GI": "Sudáfrica",
		"es-AR": "Sudáfrica",
		"es-BO": "Sudáfrica",
		"es-BR": "Sudáfrica",
		"es-BZ": "Sudáfrica",
		"es-CL": "Sudáfrica",
		"es-CO": "Sudáfrica",
		"es-CR": "Sudáfrica",
		"es-CU": "Sudáfrica",
		"es-DO": "Sudáfrica",
		"es-EC": "Sudáfrica",
		"es-GT": "Sudáfrica",
		"es-HN": "Sudáfrica",
		"es-MX": "Sudáfrica",
		"es-NI": "Sudáfrica",
		"es-PA": "Sudáfrica",
		"es-PE": "Sudáfrica",
		"es-PR": "Sudáfrica",
		"es-PY": "Sudáfrica",
		"es-SV": "Sudáfrica",
		"es-US": "Sudáfrica",
		"es-UY": "Sudáfrica",
		"es-VE": "Sudáfrica",
		"fr-FR": "Afrique du Sud",
		"fr-BE": "Afrique du Sud",
		"fr-CH": "Afrique du Sud",
		"fr-LU": "Afrique du Sud",
		"fr-MC": "Afrique du Sud",
		"fr-AD": "Afrique du Sud",
		"fr-CA": "Afrique du Sud",
		"it-IT": "Sudafrica",
		"it-CH": "Sudafrica",
		"it-SM": "Sudafrica",
		"it-VA": "Sudafrica",
		"de-DE": "Südafrika",
		"de-AT": "Südafrika",
		"de-CH": "Südafrika",
		"de-BE": "Südafrika",
		"de-LI": "Südafrika",
		"de-LU": "Südafrika",
		"nl-NL": "Zuid-Afrika",
		"nl-BE": "Zuid-Afrika",
		"sv-SE": "Sydafrika",
		"sv-FI": "Sydafrika",
		"da-DK": "Sydafrika",
		"nb-NO": "Sør-Afrika",
		"nn-NO": "Sør-Afrika",
		"fi-FI": "Etelä-Afrikka",
		"is-IS": "Suður-Afríka",
		"fo-FO": "Suðurafrika",
		"et-EE": "Lõuna-Aafrika Vabariik",
		"lv-LV": "Dienvidāfrikas Republika",
		"lt-LT": "Pietų Afrika",
		"pl-PL": "Republika Południowej Afryki",
		"cs-CZ": "Jihoafrická republika",
		"sk-SK": "Južná Afrika",
		"sl-SI": "Južnoafriška republika",
		"hr-HR": "Južnoafrička Republika",
		"bs-BA": "Južnoafrička Republika",
		"sr-RS": "Јужноафричка Република",
		"sr-BA": "Јужноафричка Република",
		"sr-ME": "Južnoafrička Republika",
		"mk-MK": "Јужноафриканска Република",
		"bg-BG": "Южна Африка",
		"be-BY": "Паўднёва-Афрыканская Рэспубліка",
		"uk-UA": "Південно-Африканська Республіка",
		"ru-RU": "Южно-Африканская Республика",
		"el-GR": "Νότια Αφρική",
		"el-CY": "Νότια Αφρική",
		"ro-RO": "Africa de Sud",
		"ro-MD": "Africa de Sud",
		"hu-HU": "Dél-afrikai Köztársaság",
		"sq-AL": "Afrika e Jugut",
		"sq-XK": "Afrika e Jugut",
		"mt-MT": "l-Afrika t’Isfel",
		"ga-IE": "an Afraic Theas",
		"cy-GB": "De Affrica",
		"gd-GB": "Afraga a Deas",
		"lb-LU": "Südafrika",
		"ca-ES": "Sud-àfrica",
		"ca-AD": "Sud-àfrica",
		"ca-FR": "Sud-àfrica",
		"ca-IT": "Sud-àfrica",
		"eu-ES": "Hegoafrika",
		"eu-FR": "Hegoafrika",
		"gl-ES": "Suráfrica",
		"tr-TR": "Güney Afrika",
		"tr-CY": "Güney Afrika"
	},
	"callingCode": "27",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "## ####",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"8[1-4]"
			]
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"8[1-4]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[1-9]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"860"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
