import type { Country } from './types.js';

export const ZWE = {
	"code": "ZWE",
	"labels": {
		"pt-BR": "Zimbábue",
		"pt-PT": "Zimbabué",
		"qu-PE": "Zimbabue",
		"qu-BO": "Zimbabue",
		"qu-EC": "Zimbabue",
		"chr-US": "ᏏᎻᏆᏇ",
		"hi-IN": "ज़िम्बाब्वे",
		"bn-IN": "জিম্বাবোয়ে",
		"bn-BD": "জিম্বাবোয়ে",
		"ta-IN": "ஜிம்பாப்வே",
		"ta-LK": "ஜிம்பாப்வே",
		"ta-SG": "ஜிம்பாப்வே",
		"ta-MY": "ஜிம்பாப்வே",
		"te-IN": "జింబాబ్వే",
		"mr-IN": "झिम्बाब्वे",
		"gu-IN": "ઝિમ્બાબ્વે",
		"kn-IN": "ಜಿಂಬಾಬ್ವೆ",
		"ml-IN": "സിംബാബ്‌വേ",
		"pa-IN": "ਜ਼ਿੰਬਾਬਵੇ",
		"ur-IN": "زمبابوے",
		"ur-PK": "زمبابوے",
		"or-IN": "ଜିମ୍ବାୱେ",
		"as-IN": "জিম্বাবৱে",
		"ne-IN": "जिम्बाबवे",
		"ne-NP": "जिम्बाबवे",
		"si-LK": "සිම්බාබ්වේ",
		"kok-IN": "जिम्बाब्वे",
		"ks-IN": "زِمبابے",
		"brx-IN": "जिम्बाब्वे",
		"mai-IN": "जिम्बाब्बे",
		"dz-BT": "ཛིམ་བྷབ་ཝེ",
		"ja-JP": "ジンバブエ",
		"ko-KR": "짐바브웨",
		"ko-KP": "짐바브웨",
		"zh-CN": "津巴布韦",
		"zh-Hans-CN": "津巴布韦",
		"zh-Hant-TW": "辛巴威",
		"zh-TW": "辛巴威",
		"zh-HK": "津巴布韋",
		"zh-MO": "津巴布韋",
		"zh-SG": "津巴布韦",
		"yue-Hant-HK": "辛巴威",
		"yue-Hans-CN": "辛巴威",
		"mn-MN": "Зимбабве",
		"ug-CN": "زىمبابۋې",
		"th-TH": "ซิมบับเว",
		"lo-LA": "ຊິມບັບເວ",
		"km-KH": "ស៊ីមបាវ៉េ",
		"my-MM": "ဇင်ဘာဘွေ",
		"vi-VN": "Zimbabwe",
		"id-ID": "Zimbabwe",
		"ms-MY": "Zimbabwe",
		"ms-SG": "Zimbabwe",
		"ms-BN": "Zimbabwe",
		"jv-ID": "Simbabwe",
		"fil-PH": "Zimbabwe",
		"ceb-PH": "Zimbabwe",
		"ka-GE": "ზიმბაბვე",
		"hy-AM": "Զիմբաբվե",
		"az-AZ": "Zimbabve",
		"az-Cyrl-AZ": "Зимбабве",
		"kk-KZ": "Зимбабве",
		"ky-KG": "Зимбабве",
		"uz-UZ": "Zimbabve",
		"tg-TJ": "Зимбабве",
		"tk-TM": "Zimbabwe",
		"fa-IR": "زیمبابوه",
		"fa-AF": "زیمبابوی",
		"ps-AF": "زیمبابوی",
		"ps-PK": "زیمبابوی",
		"he-IL": "זימבבואה",
		"ar-SA": "زيمبابوي",
		"ar-AE": "زيمبابوي",
		"ar-QA": "زيمبابوي",
		"ar-BH": "زيمبابوي",
		"ar-KW": "زيمبابوي",
		"ar-OM": "زيمبابوي",
		"ar-YE": "زيمبابوي",
		"ar-IQ": "زيمبابوي",
		"ar-JO": "زيمبابوي",
		"ar-LB": "زيمبابوي",
		"ar-SY": "زيمبابوي",
		"ar-PS": "زيمبابوي",
		"en-US": "Zimbabwe",
		"en-GB": "Zimbabwe",
		"en-IE": "Zimbabwe",
		"en-MT": "Zimbabwe",
		"en-GI": "Zimbabwe",
		"en-CY": "Zimbabwe",
		"en-JE": "Zimbabwe",
		"en-GG": "Zimbabwe",
		"en-IM": "Zimbabwe",
		"en-CA": "Zimbabwe",
		"en-AU": "Zimbabwe",
		"en-NZ": "Zimbabwe",
		"en-ZA": "Zimbabwe",
		"en-IN": "Zimbabwe",
		"en-SG": "Zimbabwe",
		"pt-AO": "Zimbabué",
		"pt-MZ": "Zimbabué",
		"pt-CV": "Zimbabué",
		"pt-GW": "Zimbabué",
		"pt-ST": "Zimbabué",
		"pt-TL": "Zimbabué",
		"pt-MO": "Zimbabué",
		"es-ES": "Zimbabue",
		"es-419": "Zimbabue",
		"es-AD": "Zimbabue",
		"es-GI": "Zimbabue",
		"es-AR": "Zimbabue",
		"es-BO": "Zimbabue",
		"es-BR": "Zimbabue",
		"es-BZ": "Zimbabue",
		"es-CL": "Zimbabue",
		"es-CO": "Zimbabue",
		"es-CR": "Zimbabue",
		"es-CU": "Zimbabue",
		"es-DO": "Zimbabue",
		"es-EC": "Zimbabue",
		"es-GT": "Zimbabue",
		"es-HN": "Zimbabue",
		"es-MX": "Zimbabue",
		"es-NI": "Zimbabue",
		"es-PA": "Zimbabue",
		"es-PE": "Zimbabue",
		"es-PR": "Zimbabue",
		"es-PY": "Zimbabue",
		"es-SV": "Zimbabue",
		"es-US": "Zimbabue",
		"es-UY": "Zimbabue",
		"es-VE": "Zimbabue",
		"fr-FR": "Zimbabwe",
		"fr-BE": "Zimbabwe",
		"fr-CH": "Zimbabwe",
		"fr-LU": "Zimbabwe",
		"fr-MC": "Zimbabwe",
		"fr-AD": "Zimbabwe",
		"fr-CA": "Zimbabwe",
		"it-IT": "Zimbabwe",
		"it-CH": "Zimbabwe",
		"it-SM": "Zimbabwe",
		"it-VA": "Zimbabwe",
		"de-DE": "Simbabwe",
		"de-AT": "Simbabwe",
		"de-CH": "Zimbabwe",
		"de-BE": "Simbabwe",
		"de-LI": "Simbabwe",
		"de-LU": "Simbabwe",
		"nl-NL": "Zimbabwe",
		"nl-BE": "Zimbabwe",
		"sv-SE": "Zimbabwe",
		"sv-FI": "Zimbabwe",
		"da-DK": "Zimbabwe",
		"nb-NO": "Zimbabwe",
		"nn-NO": "Zimbabwe",
		"fi-FI": "Zimbabwe",
		"is-IS": "Simbabve",
		"fo-FO": "Simbabvi",
		"et-EE": "Zimbabwe",
		"lv-LV": "Zimbabve",
		"lt-LT": "Zimbabvė",
		"pl-PL": "Zimbabwe",
		"cs-CZ": "Zimbabwe",
		"sk-SK": "Zimbabwe",
		"sl-SI": "Zimbabve",
		"hr-HR": "Zimbabve",
		"bs-BA": "Zimbabve",
		"sr-RS": "Зимбабве",
		"sr-BA": "Зимбабве",
		"sr-ME": "Zimbabve",
		"mk-MK": "Зимбабве",
		"bg-BG": "Зимбабве",
		"be-BY": "Зімбабвэ",
		"uk-UA": "Зімбабве",
		"ru-RU": "Зимбабве",
		"el-GR": "Ζιμπάμπουε",
		"el-CY": "Ζιμπάμπουε",
		"ro-RO": "Zimbabwe",
		"ro-MD": "Zimbabwe",
		"hu-HU": "Zimbabwe",
		"sq-AL": "Zimbabve",
		"sq-XK": "Zimbabve",
		"mt-MT": "iż-Żimbabwe",
		"ga-IE": "an tSiombáib",
		"cy-GB": "Zimbabwe",
		"gd-GB": "An t-Sìombab",
		"lb-LU": "Simbabwe",
		"ca-ES": "Zimbàbue",
		"ca-AD": "Zimbàbue",
		"ca-FR": "Zimbàbue",
		"ca-IT": "Zimbàbue",
		"eu-ES": "Zimbabwe",
		"eu-FR": "Zimbabwe",
		"gl-ES": "Zimbabwe",
		"tr-TR": "Zimbabve",
		"tr-CY": "Zimbabve"
	},
	"callingCode": "263",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"1|2(?:0[0-36-9]|12|29|[56])|3(?:1[0-689]|[24-6])|5(?:[0236-9]|1[2-4])|6(?:[013-59]|7[0-46-9])|(?:33|55|6[68])[0-69]|(?:29|3[09]|62)[0-79]"
			]
		},
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"80"
			]
		},
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[49]"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2(?:0[45]|2[278]|[49]8)|3(?:[09]8|17)|6(?:[29]8|37|75)|[23][78]|(?:33|5[15]|6[68])[78]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"7"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"29[013-9]|39|54"
			]
		},
		{
			"mask": "## #######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"24|8[13-59]|(?:2[05-79]|39|5[45]|6[15-8])2",
				"2(?:02[014]|4|[56]20|[79]2)|392|5(?:42|525)|6(?:[16-8]21|52[013])|8[13-59]"
			]
		},
		{
			"mask": "#### #####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"(?:25|54)8",
				"258|5483"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2(?:1[39]|2[0157]|[378]|[56][14])|3(?:12|29)",
				"2(?:1[39]|2[0157]|[378]|[56][14])|3(?:123|29)"
			]
		},
		{
			"mask": "#### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
