// Declarative list of user-owned tables exported to CSV. Keeping it apart from
// the parser/importer makes schema updates less noisy and easier to review.
pub(crate) const MEDIA_CSV_TABLE: CsvTable = CsvTable {
    name: "blobs",
    folder: "media_csv",
    columns: &[
        "hash",
        "thumbnail",
        "mime_type",
        "size_bytes",
        "width",
        "height",
        "sync_status",
        "created_at",
        "uploaded_at",
        "removed_at",
    ],
    order_by: "created_at, hash",
    blob_columns: &["hash", "thumbnail"],
};

pub(crate) const USER_CSV_TABLES: &[CsvTable] = &[
    CsvTable {
        name: "owners",
        folder: "data_csv",
        columns: &[
            "id",
            "name",
            "avatar_hash",
            "additional_information",
            "created_at",
            "updated_at",
            "deleted_at",
            "purge_after",
        ],
        order_by: "id",
        blob_columns: &["avatar_hash"],
    },
    CsvTable {
        name: "addresses",
        folder: "data_csv",
        columns: &[
            "id",
            "owner_id",
            "workplace_id",
            "street",
            "street_number",
            "address_complement",
            "neighborhood",
            "city",
            "state",
            "country",
            "postal_code",
            "created_at",
            "updated_at",
        ],
        order_by: "owner_id, workplace_id, id",
        blob_columns: &[],
    },
    CsvTable {
        name: "veterinarian_profiles",
        folder: "data_csv",
        columns: &[
            "id",
            "name",
            "professional_registration",
            "avatar_hash",
            "created_at",
            "updated_at",
        ],
        order_by: "id",
        blob_columns: &["avatar_hash"],
    },
    CsvTable {
        name: "workplaces",
        folder: "data_csv",
        columns: &[
            "id",
            "name",
            "services_description",
            "created_at",
            "updated_at",
        ],
        order_by: "id",
        blob_columns: &[],
    },
    CsvTable {
        name: "image_collections",
        folder: "data_csv",
        columns: &[
            "id",
            "entity_type",
            "entity_id",
            "primary_required",
            "max_items",
            "created_at",
            "updated_at",
        ],
        order_by: "entity_type, entity_id, id",
        blob_columns: &[],
    },
    CsvTable {
        name: "image_collection_items",
        folder: "data_csv",
        columns: &[
            "id",
            "collection_id",
            "image_hash",
            "original_image_hash",
            "description",
            "is_primary",
            "sort_order",
            "created_at",
            "updated_at",
        ],
        order_by: "collection_id, sort_order, id",
        blob_columns: &["image_hash", "original_image_hash"],
    },
    CsvTable {
        name: "owner_additional_responsibles",
        folder: "data_csv",
        columns: &[
            "id",
            "owner_id",
            "name",
            "avatar_hash",
            "sort_order",
            "created_at",
            "updated_at",
        ],
        order_by: "owner_id, sort_order, id",
        blob_columns: &["avatar_hash"],
    },
    CsvTable {
        name: "contacts",
        folder: "data_csv",
        columns: &[
            "id",
            "owner_id",
            "responsible_id",
            "veterinarian_profile_id",
            "workplace_id",
            "kind",
            "label",
            "value",
            "sort_order",
            "created_at",
            "updated_at",
        ],
        order_by: "owner_id, responsible_id, veterinarian_profile_id, workplace_id, sort_order, id",
        blob_columns: &[],
    },
    CsvTable {
        name: "pets",
        folder: "data_csv",
        columns: &[
            "id",
            "name",
            "birth_date",
            "species",
            "breed",
            "sex",
            "avatar_hash",
            "updated_at",
            "deleted_at",
            "purge_after",
        ],
        order_by: "id",
        blob_columns: &["avatar_hash"],
    },
    CsvTable {
        name: "pet_owners",
        folder: "data_csv",
        columns: &[
            "id",
            "pet_id",
            "owner_id",
            "sort_order",
            "created_at",
            "updated_at",
        ],
        order_by: "pet_id, sort_order, id",
        blob_columns: &[],
    },
    CsvTable {
        name: "medical_records",
        folder: "data_csv",
        columns: &[
            "id",
            "pet_id",
            "title",
            "description",
            "admitted_at",
            "discharged_at",
            "updated_at",
            "deleted_at",
            "purge_after",
        ],
        order_by: "pet_id, admitted_at, id",
        blob_columns: &[],
    },
    CsvTable {
        name: "app_settings",
        folder: "data_csv",
        columns: &["key", "value", "updated_at"],
        order_by: "key",
        blob_columns: &[],
    },
    CsvTable {
        name: "backup_history",
        folder: "data_csv",
        columns: &["id", "path", "kind", "created_at"],
        order_by: "id",
        blob_columns: &[],
    },
    CsvTable {
        name: "user_product_catalog_items",
        folder: "data_csv",
        columns: &[
            "id",
            "type",
            "name",
            "normalized_name",
            "species",
            "aliases",
            "manufacturer_id",
            "manufacturer_name",
            "regions",
            "extension",
            "hidden_at",
            "created_at",
            "updated_at",
        ],
        order_by: "type, name, id",
        blob_columns: &[],
    },
    CsvTable {
        name: "treatment_protocols",
        folder: "data_csv",
        columns: &[
            "id",
            "kind",
            "origin",
            "name",
            "normalized_name",
            "species",
            "observation",
            "sort_order",
            "hidden_at",
            "created_at",
            "updated_at",
            "deleted_at",
            "purge_after",
        ],
        order_by: "kind, sort_order, name, id",
        blob_columns: &[],
    },
    CsvTable {
        name: "treatment_protocol_items",
        folder: "data_csv",
        columns: &[
            "id",
            "protocol_id",
            "catalog_item_id",
            "sort_order",
            "created_at",
            "updated_at",
        ],
        order_by: "protocol_id, sort_order, id",
        blob_columns: &[],
    },
    CsvTable {
        name: "treatment_protocol_doses",
        folder: "data_csv",
        columns: &[
            "id",
            "protocol_id",
            "dose",
            "validity_value",
            "validity_unit",
            "sort_order",
            "created_at",
            "updated_at",
        ],
        order_by: "protocol_id, sort_order, id",
        blob_columns: &[],
    },
    CsvTable {
        name: "pet_treatments",
        folder: "data_csv",
        columns: &[
            "id",
            "pet_id",
            "kind",
            "applied_at",
            "name",
            "normalized_name",
            "dose",
            "validity_value",
            "validity_unit",
            "observation",
            "created_at",
            "validity_ignored_at",
            "updated_at",
            "deleted_at",
            "purge_after",
        ],
        order_by: "kind, pet_id, applied_at, id",
        blob_columns: &[],
    },
];

#[derive(Clone, Copy)]
pub(crate) struct CsvTable {
    pub(crate) name: &'static str,
    pub(crate) folder: &'static str,
    pub(crate) columns: &'static [&'static str],
    pub(crate) order_by: &'static str,
    pub(crate) blob_columns: &'static [&'static str],
}
