export const CURRENT_USER_MAIN_SCHEMA_VERSION = 1;
export const CURRENT_USER_MEDIA_SCHEMA_VERSION = 1;
export const CURRENT_USER_LOGS_SCHEMA_VERSION = 1;
export const CURRENT_SYSTEM_MAIN_SCHEMA_VERSION = 1;
export const CURRENT_SYSTEM_MEDIA_SCHEMA_VERSION = 1;
