import type { Country } from './types.js';

export const AFG = {
	"code": "AFG",
	"labels": {
		"pt-BR": "Afeganistão",
		"pt-PT": "Afeganistão",
		"es-ES": "Afganistán",
		"es-419": "Afganistán",
		"es-AR": "Afganistán",
		"es-BO": "Afganistán",
		"es-BR": "Afganistán",
		"es-BZ": "Afganistán",
		"es-CL": "Afganistán",
		"es-CO": "Afganistán",
		"es-CR": "Afganistán",
		"es-CU": "Afganistán",
		"es-DO": "Afganistán",
		"es-EC": "Afganistán",
		"es-GT": "Afganistán",
		"es-HN": "Afganistán",
		"es-MX": "Afganistán",
		"es-NI": "Afganistán",
		"es-PA": "Afganistán",
		"es-PE": "Afganistán",
		"es-PR": "Afganistán",
		"es-PY": "Afganistán",
		"es-SV": "Afganistán",
		"es-US": "Afganistán",
		"es-UY": "Afganistán",
		"es-VE": "Afganistán",
		"en-US": "Afghanistan",
		"fr-FR": "Afghanistan",
		"fr-BE": "Afghanistan",
		"fr-CA": "Afghanistan",
		"fr-CH": "Afghanistan",
		"fr-LU": "Afghanistan",
		"fr-MC": "Afghanistan",
		"it-IT": "Afghanistan",
		"it-CH": "Afghanistan",
		"it-SM": "Afghanistan",
		"it-VA": "Afghanistan",
		"de-DE": "Afghanistan",
		"de-AT": "Afghanistan",
		"de-CH": "Afghanistan",
		"de-BE": "Afghanistan",
		"de-LI": "Afghanistan",
		"de-LU": "Afghanistan"
	},
	"callingCode": "93"
} satisfies Country;
