import type { Country } from './types.js';

export const AGO = {
	"code": "AGO",
	"labels": {
		"pt-BR": "Angola",
		"pt-PT": "Angola",
		"es-ES": "Angola",
		"es-419": "Angola",
		"es-AR": "Angola",
		"es-BO": "Angola",
		"es-BR": "Angola",
		"es-BZ": "Angola",
		"es-CL": "Angola",
		"es-CO": "Angola",
		"es-CR": "Angola",
		"es-CU": "Angola",
		"es-DO": "Angola",
		"es-EC": "Angola",
		"es-GT": "Angola",
		"es-HN": "Angola",
		"es-MX": "Angola",
		"es-NI": "Angola",
		"es-PA": "Angola",
		"es-PE": "Angola",
		"es-PR": "Angola",
		"es-PY": "Angola",
		"es-SV": "Angola",
		"es-US": "Angola",
		"es-UY": "Angola",
		"es-VE": "Angola",
		"en-US": "Angola",
		"fr-FR": "Angola",
		"fr-BE": "Angola",
		"fr-CA": "Angola",
		"fr-CH": "Angola",
		"fr-LU": "Angola",
		"fr-MC": "Angola",
		"it-IT": "Angola",
		"it-CH": "Angola",
		"it-SM": "Angola",
		"it-VA": "Angola",
		"de-DE": "Angola",
		"de-AT": "Angola",
		"de-CH": "Angola",
		"de-BE": "Angola",
		"de-LI": "Angola",
		"de-LU": "Angola"
	},
	"callingCode": "244"
} satisfies Country;
