import type { Country } from './types.js';

export const AIA = {
	"code": "AIA",
	"labels": {
		"pt-BR": "Anguila",
		"pt-PT": "Anguila",
		"es-ES": "Anguila",
		"es-419": "Anguila",
		"es-AR": "Anguila",
		"es-BO": "Anguila",
		"es-BR": "Anguila",
		"es-BZ": "Anguila",
		"es-CL": "Anguila",
		"es-CO": "Anguila",
		"es-CR": "Anguila",
		"es-CU": "Anguila",
		"es-DO": "Anguila",
		"es-EC": "Anguila",
		"es-GT": "Anguila",
		"es-HN": "Anguila",
		"es-MX": "Anguila",
		"es-NI": "Anguila",
		"es-PA": "Anguila",
		"es-PE": "Anguila",
		"es-PR": "Anguila",
		"es-PY": "Anguila",
		"es-SV": "Anguila",
		"es-US": "Anguila",
		"es-UY": "Anguila",
		"es-VE": "Anguila",
		"en-US": "Anguilla",
		"fr-FR": "Anguilla",
		"fr-BE": "Anguilla",
		"fr-CA": "Anguilla",
		"fr-CH": "Anguilla",
		"fr-LU": "Anguilla",
		"fr-MC": "Anguilla",
		"it-IT": "Anguilla",
		"it-CH": "Anguilla",
		"it-SM": "Anguilla",
		"it-VA": "Anguilla",
		"de-DE": "Anguilla",
		"de-AT": "Anguilla",
		"de-CH": "Anguilla",
		"de-BE": "Anguilla",
		"de-LI": "Anguilla",
		"de-LU": "Anguilla"
	},
	"callingCode": "1264"
} satisfies Country;
