import type { Country } from './types.js';

export const ALA = {
	"code": "ALA",
	"labels": {
		"pt-BR": "Ilhas Aland",
		"pt-PT": "Alanda",
		"es-ES": "Islas Aland",
		"es-419": "Islas Åland",
		"es-AR": "Islas Åland",
		"es-BO": "Islas Åland",
		"es-BR": "Islas Åland",
		"es-BZ": "Islas Åland",
		"es-CL": "Islas Åland",
		"es-CO": "Islas Åland",
		"es-CR": "Islas Åland",
		"es-CU": "Islas Åland",
		"es-DO": "Islas Åland",
		"es-EC": "Islas Åland",
		"es-GT": "Islas Åland",
		"es-HN": "Islas Åland",
		"es-MX": "Islas Åland",
		"es-NI": "Islas Åland",
		"es-PA": "Islas Åland",
		"es-PE": "Islas Åland",
		"es-PR": "Islas Åland",
		"es-PY": "Islas Åland",
		"es-SV": "Islas Åland",
		"es-US": "Islas Åland",
		"es-UY": "Islas Åland",
		"es-VE": "Islas Åland",
		"en-US": "Åland Islands",
		"fr-FR": "Îles Åland",
		"fr-BE": "Îles Åland",
		"fr-CA": "îles d’Åland",
		"fr-CH": "Îles Åland",
		"fr-LU": "Îles Åland",
		"fr-MC": "Îles Åland",
		"it-IT": "Isole Åland",
		"it-CH": "Isole Åland",
		"it-SM": "Isole Åland",
		"it-VA": "Isole Åland",
		"de-DE": "Ålandinseln",
		"de-AT": "Ålandinseln",
		"de-CH": "Ålandinseln",
		"de-BE": "Ålandinseln",
		"de-LI": "Ålandinseln",
		"de-LU": "Ålandinseln"
	},
	"callingCode": "35818"
} satisfies Country;
