import type { Country } from './types.js';

export const ALA = {
	"code": "ALA",
	"labels": {
		"pt-BR": "Ilhas Aland",
		"pt-PT": "Alanda",
		"qu-PE": "Islas Åland",
		"qu-BO": "Islas Åland",
		"qu-EC": "Islas Åland",
		"chr-US": "ᎣᎴᏅᏓ ᏚᎦᏚᏛᎢ",
		"hi-IN": "एलैंड द्वीपसमूह",
		"bn-IN": "অলান্ড দ্বীপপুঞ্জ",
		"bn-BD": "অলান্ড দ্বীপপুঞ্জ",
		"ta-IN": "ஆலந்து தீவுகள்",
		"ta-LK": "ஆலந்து தீவுகள்",
		"ta-SG": "ஆலந்து தீவுகள்",
		"ta-MY": "ஆலந்து தீவுகள்",
		"te-IN": "ఆలాండ్ దీవులు",
		"mr-IN": "अ‍ॅलँड बेटे",
		"gu-IN": "ઑલેન્ડ આઇલેન્ડ્સ",
		"kn-IN": "ಆಲ್ಯಾಂಡ್ ದ್ವೀಪಗಳು",
		"ml-IN": "അലൻഡ് ദ്വീപുകൾ",
		"pa-IN": "ਅਲੈਂਡ ਟਾਪੂ",
		"ur-IN": "جزائر آلینڈ",
		"ur-PK": "آلینڈ آئلینڈز",
		"or-IN": "ଅଲାଣ୍ଡ ଦ୍ଵୀପପୁଞ୍ଜ",
		"as-IN": "আলণ্ড দ্বীপপুঞ্জ",
		"ne-IN": "अलान्ड टापुहरु",
		"ne-NP": "अलान्ड टापुहरु",
		"si-LK": "ඕලන්ඩ් දූපත්",
		"kok-IN": "अलांड जुवे",
		"ks-IN": "ایلینڑ جٔزیٖرٕ",
		"brx-IN": "आलाण्ड द्वीपफोर",
		"mai-IN": "अलैंड द्वीपसमूह",
		"dz-BT": "ཨ་ལནཌ་གླིང་ཚོམ",
		"ja-JP": "オーランド諸島",
		"ko-KR": "올란드 제도",
		"ko-KP": "올란드 제도",
		"zh-CN": "奥兰群岛",
		"zh-Hans-CN": "奥兰群岛",
		"zh-Hant-TW": "奧蘭群島",
		"zh-TW": "奧蘭群島",
		"zh-HK": "奧蘭群島",
		"zh-MO": "奧蘭群島",
		"zh-SG": "奥兰群岛",
		"yue-Hant-HK": "奧蘭群島",
		"yue-Hans-CN": "奥兰群岛",
		"mn-MN": "Аландын арлууд",
		"ug-CN": "ئالاند ئاراللىرى",
		"th-TH": "หมู่เกาะโอลันด์",
		"lo-LA": "ຫມູ່ເກາະໂອລັນ",
		"km-KH": "កោះ​អាឡង់",
		"my-MM": "အာလန်ကျွန်း",
		"vi-VN": "Quần đảo Åland",
		"id-ID": "Kepulauan Aland",
		"ms-MY": "Kepulauan Aland",
		"ms-SG": "Kepulauan Aland",
		"ms-BN": "Kepulauan Aland",
		"jv-ID": "Kapuloan Alan",
		"fil-PH": "Åland Islands",
		"ceb-PH": "Aland Islands",
		"ka-GE": "ალანდის კუნძულები",
		"hy-AM": "Ալանդյան կղզիներ",
		"az-AZ": "Aland adaları",
		"az-Cyrl-AZ": "Аланд адалары",
		"kk-KZ": "Аланд аралдары",
		"ky-KG": "Аланд аралдары",
		"uz-UZ": "Aland orollari",
		"tg-TJ": "Ҷазираҳои Аланд",
		"tk-TM": "Aland adalary",
		"fa-IR": "جزایر آلاند",
		"fa-AF": "جزایر آلاند",
		"ps-AF": "الاند ټاپوان",
		"ps-PK": "الاند ټاپوان",
		"he-IL": "איי אולנד",
		"ar-SA": "جزر آلاند",
		"ar-AE": "جزر آلاند",
		"ar-QA": "جزر آلاند",
		"ar-BH": "جزر آلاند",
		"ar-KW": "جزر آلاند",
		"ar-OM": "جزر آلاند",
		"ar-YE": "جزر آلاند",
		"ar-IQ": "جزر آلاند",
		"ar-JO": "جزر آلاند",
		"ar-LB": "جزر آلاند",
		"ar-SY": "جزر آلاند",
		"ar-PS": "جزر آلاند",
		"en-US": "Åland Islands",
		"en-GB": "Åland Islands",
		"en-IE": "Åland Islands",
		"en-MT": "Åland Islands",
		"en-GI": "Åland Islands",
		"en-CY": "Åland Islands",
		"en-JE": "Åland Islands",
		"en-GG": "Åland Islands",
		"en-IM": "Åland Islands",
		"en-CA": "Åland Islands",
		"en-AU": "Åland Islands",
		"en-NZ": "Åland Islands",
		"en-ZA": "Åland Islands",
		"en-IN": "Åland Islands",
		"en-SG": "Åland Islands",
		"pt-AO": "Alanda",
		"pt-MZ": "Alanda",
		"pt-CV": "Alanda",
		"pt-GW": "Alanda",
		"pt-ST": "Alanda",
		"pt-TL": "Alanda",
		"pt-MO": "Alanda",
		"es-ES": "Islas Aland",
		"es-419": "Islas Åland",
		"es-AD": "Islas Aland",
		"es-GI": "Islas Aland",
		"es-AR": "Islas Åland",
		"es-BO": "Islas Åland",
		"es-BR": "Islas Åland",
		"es-BZ": "Islas Åland",
		"es-CL": "Islas Åland",
		"es-CO": "Islas Åland",
		"es-CR": "Islas Åland",
		"es-CU": "Islas Åland",
		"es-DO": "Islas Åland",
		"es-EC": "Islas Åland",
		"es-GT": "Islas Åland",
		"es-HN": "Islas Åland",
		"es-MX": "Islas Åland",
		"es-NI": "Islas Åland",
		"es-PA": "Islas Åland",
		"es-PE": "Islas Åland",
		"es-PR": "Islas Åland",
		"es-PY": "Islas Åland",
		"es-SV": "Islas Åland",
		"es-US": "Islas Åland",
		"es-UY": "Islas Åland",
		"es-VE": "Islas Åland",
		"fr-FR": "Îles Åland",
		"fr-BE": "Îles Åland",
		"fr-CH": "Îles Åland",
		"fr-LU": "Îles Åland",
		"fr-MC": "Îles Åland",
		"fr-AD": "Îles Åland",
		"fr-CA": "îles d’Åland",
		"it-IT": "Isole Åland",
		"it-CH": "Isole Åland",
		"it-SM": "Isole Åland",
		"it-VA": "Isole Åland",
		"de-DE": "Ålandinseln",
		"de-AT": "Ålandinseln",
		"de-CH": "Ålandinseln",
		"de-BE": "Ålandinseln",
		"de-LI": "Ålandinseln",
		"de-LU": "Ålandinseln",
		"nl-NL": "Åland",
		"nl-BE": "Åland",
		"sv-SE": "Åland",
		"sv-FI": "Åland",
		"da-DK": "Åland",
		"nb-NO": "Åland",
		"nn-NO": "Åland",
		"fi-FI": "Ahvenanmaa",
		"is-IS": "Álandseyjar",
		"fo-FO": "Áland",
		"et-EE": "Ahvenamaa",
		"lv-LV": "Olandes salas",
		"lt-LT": "Alandų Salos",
		"pl-PL": "Wyspy Alandzkie",
		"cs-CZ": "Ålandy",
		"sk-SK": "Alandy",
		"sl-SI": "Ålandski otoki",
		"hr-HR": "Ålandski otoci",
		"bs-BA": "Olandska ostrva",
		"sr-RS": "Оландска Острва",
		"sr-BA": "Оландска острва",
		"sr-ME": "Olandska Ostrva",
		"mk-MK": "Оландски Острови",
		"bg-BG": "Оландски острови",
		"be-BY": "Аландскія астравы",
		"uk-UA": "Аландські Острови",
		"ru-RU": "Аландские о-ва",
		"el-GR": "Νήσοι Όλαντ",
		"el-CY": "Νήσοι Όλαντ",
		"ro-RO": "Insulele Åland",
		"ro-MD": "Insulele Åland",
		"hu-HU": "Åland-szigetek",
		"sq-AL": "Ishujt Alandë",
		"sq-XK": "Ishujt Alandë",
		"mt-MT": "il-Gżejjer Aland",
		"ga-IE": "Oileáin Åland",
		"cy-GB": "Ynysoedd Åland",
		"gd-GB": "Na h-Eileanan Åland",
		"lb-LU": "Ålandinselen",
		"ca-ES": "Illes Åland",
		"ca-AD": "Illes Åland",
		"ca-FR": "Illes Åland",
		"ca-IT": "Illes Åland",
		"eu-ES": "Åland",
		"eu-FR": "Åland",
		"gl-ES": "Illas Åland",
		"tr-TR": "Åland Adaları",
		"tr-CY": "Åland Adaları"
	},
	"callingCode": "35818",
	"phoneMasks": [
		{
			"mask": "###",
			"minLength": 3,
			"maxLength": 3
		},
		{
			"mask": "####",
			"minLength": 4,
			"maxLength": 4
		},
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		}
	]
} satisfies Country;
