import type { Country } from './types.js';

export const ALB = {
	"code": "ALB",
	"labels": {
		"pt-BR": "Albânia",
		"pt-PT": "Albânia",
		"es-ES": "Albania",
		"es-419": "Albania",
		"es-AR": "Albania",
		"es-BO": "Albania",
		"es-BR": "Albania",
		"es-BZ": "Albania",
		"es-CL": "Albania",
		"es-CO": "Albania",
		"es-CR": "Albania",
		"es-CU": "Albania",
		"es-DO": "Albania",
		"es-EC": "Albania",
		"es-GT": "Albania",
		"es-HN": "Albania",
		"es-MX": "Albania",
		"es-NI": "Albania",
		"es-PA": "Albania",
		"es-PE": "Albania",
		"es-PR": "Albania",
		"es-PY": "Albania",
		"es-SV": "Albania",
		"es-US": "Albania",
		"es-UY": "Albania",
		"es-VE": "Albania",
		"en-US": "Albania",
		"fr-FR": "Albanie",
		"fr-BE": "Albanie",
		"fr-CA": "Albanie",
		"fr-CH": "Albanie",
		"fr-LU": "Albanie",
		"fr-MC": "Albanie",
		"it-IT": "Albania",
		"it-CH": "Albania",
		"it-SM": "Albania",
		"it-VA": "Albania",
		"de-DE": "Albanien",
		"de-AT": "Albanien",
		"de-CH": "Albanien",
		"de-BE": "Albanien",
		"de-LI": "Albanien",
		"de-LU": "Albanien"
	},
	"callingCode": "355"
} satisfies Country;
