import type { Country } from './types.js';

export const AND = {
	"code": "AND",
	"labels": {
		"pt-BR": "Andorra",
		"pt-PT": "Andorra",
		"es-ES": "Andorra",
		"es-419": "Andorra",
		"es-AR": "Andorra",
		"es-BO": "Andorra",
		"es-BR": "Andorra",
		"es-BZ": "Andorra",
		"es-CL": "Andorra",
		"es-CO": "Andorra",
		"es-CR": "Andorra",
		"es-CU": "Andorra",
		"es-DO": "Andorra",
		"es-EC": "Andorra",
		"es-GT": "Andorra",
		"es-HN": "Andorra",
		"es-MX": "Andorra",
		"es-NI": "Andorra",
		"es-PA": "Andorra",
		"es-PE": "Andorra",
		"es-PR": "Andorra",
		"es-PY": "Andorra",
		"es-SV": "Andorra",
		"es-US": "Andorra",
		"es-UY": "Andorra",
		"es-VE": "Andorra",
		"en-US": "Andorra",
		"fr-FR": "Andorre",
		"fr-BE": "Andorre",
		"fr-CA": "Andorre",
		"fr-CH": "Andorre",
		"fr-LU": "Andorre",
		"fr-MC": "Andorre",
		"it-IT": "Andorra",
		"it-CH": "Andorra",
		"it-SM": "Andorra",
		"it-VA": "Andorra",
		"de-DE": "Andorra",
		"de-AT": "Andorra",
		"de-CH": "Andorra",
		"de-BE": "Andorra",
		"de-LI": "Andorra",
		"de-LU": "Andorra"
	},
	"callingCode": "376"
} satisfies Country;
