import type { Country } from './types.js';

export const ARE = {
	"code": "ARE",
	"labels": {
		"pt-BR": "Emirados Árabes Unidos",
		"pt-PT": "Emirados Árabes Unidos",
		"qu-PE": "Emiratos Árabes Unidos",
		"qu-BO": "Emiratos Árabes Unidos",
		"qu-EC": "Emiratos Árabes Unidos",
		"chr-US": "ᏌᏊ ᎢᏳᎾᎵᏍᏔᏅ ᎡᎳᏈ ᎢᎹᎵᏘᏏ",
		"hi-IN": "संयुक्त अरब अमीरात",
		"bn-IN": "সংযুক্ত আরব আমিরাত",
		"bn-BD": "সংযুক্ত আরব আমিরাত",
		"ta-IN": "ஐக்கிய அரபு எமிரேட்ஸ்",
		"ta-LK": "ஐக்கிய அரபு எமிரேட்ஸ்",
		"ta-SG": "ஐக்கிய அரபு எமிரேட்ஸ்",
		"ta-MY": "ஐக்கிய அரபு எமிரேட்ஸ்",
		"te-IN": "యునైటెడ్ అరబ్ ఎమిరేట్స్",
		"mr-IN": "संयुक्त अरब अमीरात",
		"gu-IN": "યુનાઇટેડ આરબ અમીરાત",
		"kn-IN": "ಯುನೈಟೆಡ್ ಅರಬ್ ಎಮಿರೇಟ್ಸ್",
		"ml-IN": "യുണൈറ്റഡ് അറബ് എമിറൈറ്റ്‌സ്",
		"pa-IN": "ਸੰਯੁਕਤ ਅਰਬ ਅਮੀਰਾਤ",
		"ur-IN": "متحدہ عرب امارات",
		"ur-PK": "متحدہ عرب امارات",
		"or-IN": "ସଂଯୁକ୍ତ ଆରବ ଏମିରେଟସ୍",
		"as-IN": "সংযুক্ত আৰব আমিৰাত",
		"ne-IN": "संयुक्त अरब इमिराट्स",
		"ne-NP": "संयुक्त अरब इमिराट्स",
		"si-LK": "එක්සත් අරාබි එමිර් රාජ්‍යය",
		"kok-IN": "युनाइटेड अरब इमीरात",
		"ks-IN": "مُتحدہ عرَب امارات",
		"brx-IN": "जथाय आराब एमिरेत",
		"mai-IN": "संयुक्त अरब अमीरात",
		"dz-BT": "ཡུ་ནཱའི་ཊེཌ་ ཨ་རབ་ ཨེ་མེ་རེཊས",
		"ja-JP": "アラブ首長国連邦",
		"ko-KR": "아랍에미리트",
		"ko-KP": "아랍에미리트",
		"zh-CN": "阿拉伯联合酋长国",
		"zh-Hans-CN": "阿拉伯联合酋长国",
		"zh-Hant-TW": "阿拉伯聯合大公國",
		"zh-TW": "阿拉伯聯合大公國",
		"zh-HK": "阿拉伯聯合酋長國",
		"zh-MO": "阿拉伯聯合酋長國",
		"zh-SG": "阿拉伯联合酋长国",
		"yue-Hant-HK": "阿拉伯聯合大公國",
		"yue-Hans-CN": "阿拉伯联合大公国",
		"mn-MN": "Арабын Нэгдсэн Эмират Улс",
		"ug-CN": "ئەرەب بىرلەشمە خەلىپىلىكى",
		"th-TH": "สหรัฐอาหรับเอมิเรตส์",
		"lo-LA": "ສະຫະລັດອາຣັບເອມິເຣດ",
		"km-KH": "អេមីរ៉ាត​អារ៉ាប់​រួម",
		"my-MM": "ယူအေအီး",
		"vi-VN": "Các Tiểu Vương quốc Ả Rập Thống nhất",
		"id-ID": "Uni Emirat Arab",
		"ms-MY": "Emiriah Arab Bersatu",
		"ms-SG": "Emiriah Arab Bersatu",
		"ms-BN": "Emiriah Arab Bersatu",
		"jv-ID": "Uni Émirat Arab",
		"fil-PH": "United Arab Emirates",
		"ceb-PH": "United Arab Emirates",
		"ka-GE": "არაბთა გაერთიანებული საამიროები",
		"hy-AM": "Արաբական Միացյալ Էմիրություններ",
		"az-AZ": "Birləşmiş Ərəb Əmirlikləri",
		"az-Cyrl-AZ": "Бирләшмиш Әрәб Әмирликләри",
		"kk-KZ": "Біріккен Араб Әмірліктері",
		"ky-KG": "Бириккен Араб Эмираттары",
		"uz-UZ": "Birlashgan Arab Amirliklari",
		"tg-TJ": "Аморатҳои Муттаҳидаи Араб",
		"tk-TM": "Birleşen Arap Emirlikleri",
		"fa-IR": "امارات متحدهٔ عربی",
		"fa-AF": "امارات متحدهٔ عربی",
		"ps-AF": "متحده عرب امارات",
		"ps-PK": "متحده عرب امارات",
		"he-IL": "איחוד האמירויות הערביות",
		"ar-SA": "الإمارات العربية المتحدة",
		"ar-AE": "الإمارات العربية المتحدة",
		"ar-QA": "الإمارات العربية المتحدة",
		"ar-BH": "الإمارات العربية المتحدة",
		"ar-KW": "الإمارات العربية المتحدة",
		"ar-OM": "الإمارات العربية المتحدة",
		"ar-YE": "الإمارات العربية المتحدة",
		"ar-IQ": "الإمارات العربية المتحدة",
		"ar-JO": "الإمارات العربية المتحدة",
		"ar-LB": "الإمارات العربية المتحدة",
		"ar-SY": "الإمارات العربية المتحدة",
		"ar-PS": "الإمارات العربية المتحدة",
		"en-US": "United Arab Emirates",
		"en-GB": "United Arab Emirates",
		"en-IE": "United Arab Emirates",
		"en-MT": "United Arab Emirates",
		"en-GI": "United Arab Emirates",
		"en-CY": "United Arab Emirates",
		"en-JE": "United Arab Emirates",
		"en-GG": "United Arab Emirates",
		"en-IM": "United Arab Emirates",
		"en-CA": "United Arab Emirates",
		"en-AU": "United Arab Emirates",
		"en-NZ": "United Arab Emirates",
		"en-ZA": "United Arab Emirates",
		"en-IN": "United Arab Emirates",
		"en-SG": "United Arab Emirates",
		"pt-AO": "Emirados Árabes Unidos",
		"pt-MZ": "Emirados Árabes Unidos",
		"pt-CV": "Emirados Árabes Unidos",
		"pt-GW": "Emirados Árabes Unidos",
		"pt-ST": "Emirados Árabes Unidos",
		"pt-TL": "Emirados Árabes Unidos",
		"pt-MO": "Emirados Árabes Unidos",
		"es-ES": "Emiratos Árabes Unidos",
		"es-419": "Emiratos Árabes Unidos",
		"es-AD": "Emiratos Árabes Unidos",
		"es-GI": "Emiratos Árabes Unidos",
		"es-AR": "Emiratos Árabes Unidos",
		"es-BO": "Emiratos Árabes Unidos",
		"es-BR": "Emiratos Árabes Unidos",
		"es-BZ": "Emiratos Árabes Unidos",
		"es-CL": "Emiratos Árabes Unidos",
		"es-CO": "Emiratos Árabes Unidos",
		"es-CR": "Emiratos Árabes Unidos",
		"es-CU": "Emiratos Árabes Unidos",
		"es-DO": "Emiratos Árabes Unidos",
		"es-EC": "Emiratos Árabes Unidos",
		"es-GT": "Emiratos Árabes Unidos",
		"es-HN": "Emiratos Árabes Unidos",
		"es-MX": "Emiratos Árabes Unidos",
		"es-NI": "Emiratos Árabes Unidos",
		"es-PA": "Emiratos Árabes Unidos",
		"es-PE": "Emiratos Árabes Unidos",
		"es-PR": "Emiratos Árabes Unidos",
		"es-PY": "Emiratos Árabes Unidos",
		"es-SV": "Emiratos Árabes Unidos",
		"es-US": "Emiratos Árabes Unidos",
		"es-UY": "Emiratos Árabes Unidos",
		"es-VE": "Emiratos Árabes Unidos",
		"fr-FR": "Émirats arabes unis",
		"fr-BE": "Émirats arabes unis",
		"fr-CH": "Émirats arabes unis",
		"fr-LU": "Émirats arabes unis",
		"fr-MC": "Émirats arabes unis",
		"fr-AD": "Émirats arabes unis",
		"fr-CA": "Émirats arabes unis",
		"it-IT": "Emirati Arabi Uniti",
		"it-CH": "Emirati Arabi Uniti",
		"it-SM": "Emirati Arabi Uniti",
		"it-VA": "Emirati Arabi Uniti",
		"de-DE": "Vereinigte Arabische Emirate",
		"de-AT": "Vereinigte Arabische Emirate",
		"de-CH": "Vereinigte Arabische Emirate",
		"de-BE": "Vereinigte Arabische Emirate",
		"de-LI": "Vereinigte Arabische Emirate",
		"de-LU": "Vereinigte Arabische Emirate",
		"nl-NL": "Verenigde Arabische Emiraten",
		"nl-BE": "Verenigde Arabische Emiraten",
		"sv-SE": "Förenade Arabemiraten",
		"sv-FI": "Förenade Arabemiraten",
		"da-DK": "De Forenede Arabiske Emirater",
		"nb-NO": "De forente arabiske emirater",
		"nn-NO": "Dei sameinte arabiske emirata",
		"fi-FI": "Arabiemiirikunnat",
		"is-IS": "Sameinuðu arabísku furstadæmin",
		"fo-FO": "Sameindu Emirríkini",
		"et-EE": "Araabia Ühendemiraadid",
		"lv-LV": "Apvienotie Arābu Emirāti",
		"lt-LT": "Jungtiniai Arabų Emyratai",
		"pl-PL": "Zjednoczone Emiraty Arabskie",
		"cs-CZ": "Spojené arabské emiráty",
		"sk-SK": "Spojené arabské emiráty",
		"sl-SI": "Združeni arabski emirati",
		"hr-HR": "Ujedinjeni Arapski Emirati",
		"bs-BA": "Ujedinjeni Arapski Emirati",
		"sr-RS": "Уједињени Арапски Емирати",
		"sr-BA": "Уједињени Арапски Емирати",
		"sr-ME": "Ujedinjeni Arapski Emirati",
		"mk-MK": "Обединети Арапски Емирати",
		"bg-BG": "Обединени арабски емирства",
		"be-BY": "Аб’яднаныя Арабскія Эміраты",
		"uk-UA": "Обʼєднані Арабські Емірати",
		"ru-RU": "ОАЭ",
		"el-GR": "Ηνωμένα Αραβικά Εμιράτα",
		"el-CY": "Ηνωμένα Αραβικά Εμιράτα",
		"ro-RO": "Emiratele Arabe Unite",
		"ro-MD": "Emiratele Arabe Unite",
		"hu-HU": "Egyesült Arab Emírségek",
		"sq-AL": "Emiratet e Bashkuara Arabe",
		"sq-XK": "Emiratet e Bashkuara Arabe",
		"mt-MT": "l-Emirati Għarab Magħquda",
		"ga-IE": "Aontas na nÉimíríochtaí Arabacha",
		"cy-GB": "Emiradau Arabaidd Unedig",
		"gd-GB": "Na h-Iomaratan Arabach Aonaichte",
		"lb-LU": "Vereenegt Arabesch Emirater",
		"ca-ES": "Emirats Àrabs Units",
		"ca-AD": "Emirats Àrabs Units",
		"ca-FR": "Emirats Àrabs Units",
		"ca-IT": "Emirats Àrabs Units",
		"eu-ES": "Arabiar Emirerri Batuak",
		"eu-FR": "Arabiar Emirerri Batuak",
		"gl-ES": "Emiratos Árabes Unidos",
		"tr-TR": "Birleşik Arap Emirlikleri",
		"tr-CY": "Birleşik Arap Emirlikleri"
	},
	"callingCode": "971",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[236]|[479][2-8]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"5"
			]
		},
		{
			"mask": "### # #####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[479]"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11
		},
		{
			"mask": "### #########",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"60|8"
			]
		}
	]
} satisfies Country;
