import type { Country } from './types.js';

export const ARG = {
	"code": "ARG",
	"labels": {
		"pt-BR": "Argentina",
		"pt-PT": "Argentina",
		"gn-PY": "Argentina",
		"es-ES": "Argentina",
		"es-419": "Argentina",
		"es-AR": "Argentina",
		"es-BO": "Argentina",
		"es-BR": "Argentina",
		"es-BZ": "Argentina",
		"es-CL": "Argentina",
		"es-CO": "Argentina",
		"es-CR": "Argentina",
		"es-CU": "Argentina",
		"es-DO": "Argentina",
		"es-EC": "Argentina",
		"es-GT": "Argentina",
		"es-HN": "Argentina",
		"es-MX": "Argentina",
		"es-NI": "Argentina",
		"es-PA": "Argentina",
		"es-PE": "Argentina",
		"es-PR": "Argentina",
		"es-PY": "Argentina",
		"es-SV": "Argentina",
		"es-US": "Argentina",
		"es-UY": "Argentina",
		"es-VE": "Argentina",
		"en-US": "Argentina",
		"fr-FR": "Argentine",
		"fr-BE": "Argentine",
		"fr-CA": "Argentine",
		"fr-CH": "Argentine",
		"fr-LU": "Argentine",
		"fr-MC": "Argentine",
		"it-IT": "Argentina",
		"it-CH": "Argentina",
		"it-SM": "Argentina",
		"it-VA": "Argentina",
		"de-DE": "Argentinien",
		"de-AT": "Argentinien",
		"de-CH": "Argentinien",
		"de-BE": "Argentinien",
		"de-LI": "Argentinien",
		"de-LU": "Argentinien"
	}
} satisfies Country;
