import type { Country } from './types.js';

export const ARM = {
	"code": "ARM",
	"labels": {
		"pt-BR": "Armênia",
		"pt-PT": "Arménia",
		"es-ES": "Armenia",
		"es-419": "Armenia",
		"es-AR": "Armenia",
		"es-BO": "Armenia",
		"es-BR": "Armenia",
		"es-BZ": "Armenia",
		"es-CL": "Armenia",
		"es-CO": "Armenia",
		"es-CR": "Armenia",
		"es-CU": "Armenia",
		"es-DO": "Armenia",
		"es-EC": "Armenia",
		"es-GT": "Armenia",
		"es-HN": "Armenia",
		"es-MX": "Armenia",
		"es-NI": "Armenia",
		"es-PA": "Armenia",
		"es-PE": "Armenia",
		"es-PR": "Armenia",
		"es-PY": "Armenia",
		"es-SV": "Armenia",
		"es-US": "Armenia",
		"es-UY": "Armenia",
		"es-VE": "Armenia",
		"en-US": "Armenia",
		"fr-FR": "Arménie",
		"fr-BE": "Arménie",
		"fr-CA": "Arménie",
		"fr-CH": "Arménie",
		"fr-LU": "Arménie",
		"fr-MC": "Arménie",
		"it-IT": "Armenia",
		"it-CH": "Armenia",
		"it-SM": "Armenia",
		"it-VA": "Armenia",
		"de-DE": "Armenien",
		"de-AT": "Armenien",
		"de-CH": "Armenien",
		"de-BE": "Armenien",
		"de-LI": "Armenien",
		"de-LU": "Armenien"
	},
	"callingCode": "374"
} satisfies Country;
