import type { Country } from './types.js';

export const ASM = {
	"code": "ASM",
	"labels": {
		"pt-BR": "Samoa Americana",
		"pt-PT": "Samoa Americana",
		"es-ES": "Samoa Americana",
		"es-419": "Samoa Americana",
		"es-AR": "Samoa Americana",
		"es-BO": "Samoa Americana",
		"es-BR": "Samoa Americana",
		"es-BZ": "Samoa Americana",
		"es-CL": "Samoa Americana",
		"es-CO": "Samoa Americana",
		"es-CR": "Samoa Americana",
		"es-CU": "Samoa Americana",
		"es-DO": "Samoa Americana",
		"es-EC": "Samoa Americana",
		"es-GT": "Samoa Americana",
		"es-HN": "Samoa Americana",
		"es-MX": "Samoa Americana",
		"es-NI": "Samoa Americana",
		"es-PA": "Samoa Americana",
		"es-PE": "Samoa Americana",
		"es-PR": "Samoa Americana",
		"es-PY": "Samoa Americana",
		"es-SV": "Samoa Americana",
		"es-US": "Samoa Americana",
		"es-UY": "Samoa Americana",
		"es-VE": "Samoa Americana",
		"en-US": "American Samoa",
		"fr-FR": "Samoa américaines",
		"fr-BE": "Samoa américaines",
		"fr-CA": "Samoa américaines",
		"fr-CH": "Samoa américaines",
		"fr-LU": "Samoa américaines",
		"fr-MC": "Samoa américaines",
		"it-IT": "Samoa Americane",
		"it-CH": "Samoa Americane",
		"it-SM": "Samoa Americane",
		"it-VA": "Samoa Americane",
		"de-DE": "Amerikanisch-Samoa",
		"de-AT": "Amerikanisch-Samoa",
		"de-CH": "Amerikanisch-Samoa",
		"de-BE": "Amerikanisch-Samoa",
		"de-LI": "Amerikanisch-Samoa",
		"de-LU": "Amerikanisch-Samoa"
	}
} satisfies Country;
