import type { Country } from './types.js';

export const ASM = {
	"code": "ASM",
	"labels": {
		"pt-BR": "Samoa Americana",
		"pt-PT": "Samoa Americana",
		"qu-PE": "Samoa Americana",
		"qu-BO": "Samoa Americana",
		"qu-EC": "Samoa Americana",
		"chr-US": "ᎠᎺᎵᎧ ᏌᎼᎠ",
		"hi-IN": "अमेरिकी समोआ",
		"bn-IN": "আমেরিকান সামোয়া",
		"bn-BD": "আমেরিকান সামোয়া",
		"ta-IN": "அமெரிக்க சமோவா",
		"ta-LK": "அமெரிக்க சமோவா",
		"ta-SG": "அமெரிக்க சமோவா",
		"ta-MY": "அமெரிக்க சமோவா",
		"te-IN": "అమెరికన్ సమోవా",
		"mr-IN": "अमेरिकन सामोआ",
		"gu-IN": "અમેરિકન સમોઆ",
		"kn-IN": "ಅಮೇರಿಕನ್ ಸಮೋವಾ",
		"ml-IN": "അമേരിക്കൻ സമോവ",
		"pa-IN": "ਅਮੈਰੀਕਨ ਸਮੋਆ",
		"ur-IN": "امریکی ساموآ",
		"ur-PK": "امریکی ساموآ",
		"or-IN": "ଆମେରିକାନ୍ ସାମୋଆ",
		"as-IN": "আমেৰিকান চামোৱা",
		"ne-IN": "अमेरिकी समोआ",
		"ne-NP": "अमेरिकी समोआ",
		"si-LK": "ඇමරිකානු සැමෝවා",
		"kok-IN": "अमेरिकी सामोआ",
		"ks-IN": "اَمریٖکَن سَموا",
		"brx-IN": "आमेरिकान सामआ",
		"mai-IN": "अमेरिकी समोआ",
		"dz-BT": "ས་མོ་ཨ་ཡུ་ཨེས་ཨེ་མངའ་ཁོངས",
		"ja-JP": "米領サモア",
		"ko-KR": "아메리칸 사모아",
		"ko-KP": "아메리칸 사모아",
		"zh-CN": "美属萨摩亚",
		"zh-Hans-CN": "美属萨摩亚",
		"zh-Hant-TW": "美屬薩摩亞",
		"zh-TW": "美屬薩摩亞",
		"zh-HK": "美屬薩摩亞",
		"zh-MO": "美屬薩摩亞",
		"zh-SG": "美属萨摩亚",
		"yue-Hant-HK": "美屬薩摩亞",
		"yue-Hans-CN": "美属萨摩亚",
		"mn-MN": "Америкийн Самоа",
		"ug-CN": "ئامېرىكا ساموئا",
		"th-TH": "อเมริกันซามัว",
		"lo-LA": "ອາເມຣິກາ ຊາມົວ",
		"km-KH": "សាម័រ អាមេរិកាំង",
		"my-MM": "အမေရိကန် ဆမိုးအား",
		"vi-VN": "Samoa thuộc Mỹ",
		"id-ID": "Samoa Amerika",
		"ms-MY": "Samoa Amerika",
		"ms-SG": "Samoa Amerika",
		"ms-BN": "Samoa Amerika",
		"jv-ID": "Samoa Amerika",
		"fil-PH": "American Samoa",
		"ceb-PH": "American Samoa",
		"ka-GE": "ამერიკის სამოა",
		"hy-AM": "Ամերիկյան Սամոա",
		"az-AZ": "Amerika Samoası",
		"az-Cyrl-AZ": "Америка Самоасы",
		"kk-KZ": "Америкалық Самоа",
		"ky-KG": "Америкалык Самоа",
		"uz-UZ": "Amerika Samoasi",
		"tg-TJ": "Самоаи Америка",
		"tk-TM": "Amerikan Samoasy",
		"fa-IR": "ساموآی امریکا",
		"fa-AF": "ساموآی امریکا",
		"ps-AF": "امریکایی ساماوا",
		"ps-PK": "امریکایی ساماوا",
		"he-IL": "סמואה האמריקנית",
		"ar-SA": "ساموا الأمريكية",
		"ar-AE": "ساموا الأمريكية",
		"ar-QA": "ساموا الأمريكية",
		"ar-BH": "ساموا الأمريكية",
		"ar-KW": "ساموا الأمريكية",
		"ar-OM": "ساموا الأمريكية",
		"ar-YE": "ساموا الأمريكية",
		"ar-IQ": "ساموا الأمريكية",
		"ar-JO": "ساموا الأمريكية",
		"ar-LB": "ساموا الأمريكية",
		"ar-SY": "ساموا الأمريكية",
		"ar-PS": "ساموا الأمريكية",
		"en-US": "American Samoa",
		"en-GB": "American Samoa",
		"en-IE": "American Samoa",
		"en-MT": "American Samoa",
		"en-GI": "American Samoa",
		"en-CY": "American Samoa",
		"en-JE": "American Samoa",
		"en-GG": "American Samoa",
		"en-IM": "American Samoa",
		"en-CA": "American Samoa",
		"en-AU": "American Samoa",
		"en-NZ": "American Samoa",
		"en-ZA": "American Samoa",
		"en-IN": "American Samoa",
		"en-SG": "American Samoa",
		"pt-AO": "Samoa Americana",
		"pt-MZ": "Samoa Americana",
		"pt-CV": "Samoa Americana",
		"pt-GW": "Samoa Americana",
		"pt-ST": "Samoa Americana",
		"pt-TL": "Samoa Americana",
		"pt-MO": "Samoa Americana",
		"es-ES": "Samoa Americana",
		"es-419": "Samoa Americana",
		"es-AD": "Samoa Americana",
		"es-GI": "Samoa Americana",
		"es-AR": "Samoa Americana",
		"es-BO": "Samoa Americana",
		"es-BR": "Samoa Americana",
		"es-BZ": "Samoa Americana",
		"es-CL": "Samoa Americana",
		"es-CO": "Samoa Americana",
		"es-CR": "Samoa Americana",
		"es-CU": "Samoa Americana",
		"es-DO": "Samoa Americana",
		"es-EC": "Samoa Americana",
		"es-GT": "Samoa Americana",
		"es-HN": "Samoa Americana",
		"es-MX": "Samoa Americana",
		"es-NI": "Samoa Americana",
		"es-PA": "Samoa Americana",
		"es-PE": "Samoa Americana",
		"es-PR": "Samoa Americana",
		"es-PY": "Samoa Americana",
		"es-SV": "Samoa Americana",
		"es-US": "Samoa Americana",
		"es-UY": "Samoa Americana",
		"es-VE": "Samoa Americana",
		"fr-FR": "Samoa américaines",
		"fr-BE": "Samoa américaines",
		"fr-CH": "Samoa américaines",
		"fr-LU": "Samoa américaines",
		"fr-MC": "Samoa américaines",
		"fr-AD": "Samoa américaines",
		"fr-CA": "Samoa américaines",
		"it-IT": "Samoa Americane",
		"it-CH": "Samoa Americane",
		"it-SM": "Samoa Americane",
		"it-VA": "Samoa Americane",
		"de-DE": "Amerikanisch-Samoa",
		"de-AT": "Amerikanisch-Samoa",
		"de-CH": "Amerikanisch-Samoa",
		"de-BE": "Amerikanisch-Samoa",
		"de-LI": "Amerikanisch-Samoa",
		"de-LU": "Amerikanisch-Samoa",
		"nl-NL": "Amerikaans-Samoa",
		"nl-BE": "Amerikaans-Samoa",
		"sv-SE": "Amerikanska Samoa",
		"sv-FI": "Amerikanska Samoa",
		"da-DK": "Amerikansk Samoa",
		"nb-NO": "Amerikansk Samoa",
		"nn-NO": "Amerikansk Samoa",
		"fi-FI": "Amerikan Samoa",
		"is-IS": "Bandaríska Samóa",
		"fo-FO": "Amerikanska Samoa",
		"et-EE": "Ameerika Samoa",
		"lv-LV": "ASV Samoa",
		"lt-LT": "Amerikos Samoa",
		"pl-PL": "Samoa Amerykańskie",
		"cs-CZ": "Americká Samoa",
		"sk-SK": "Americká Samoa",
		"sl-SI": "Ameriška Samoa",
		"hr-HR": "Američka Samoa",
		"bs-BA": "Američka Samoa",
		"sr-RS": "Америчка Самоа",
		"sr-BA": "Америчка Самоа",
		"sr-ME": "Američka Samoa",
		"mk-MK": "Американска Самоа",
		"bg-BG": "Американска Самоа",
		"be-BY": "Амерыканскае Самоа",
		"uk-UA": "Американське Самоа",
		"ru-RU": "Американское Самоа",
		"el-GR": "Αμερικανική Σαμόα",
		"el-CY": "Αμερικανική Σαμόα",
		"ro-RO": "Samoa Americană",
		"ro-MD": "Samoa Americană",
		"hu-HU": "Amerikai Szamoa",
		"sq-AL": "Samoa Amerikane",
		"sq-XK": "Samoa Amerikane",
		"mt-MT": "is-Samoa Amerikana",
		"ga-IE": "Samó Mheiriceá",
		"cy-GB": "Samoa America",
		"gd-GB": "Samotha na h-Aimeireaga",
		"lb-LU": "Amerikanesch-Samoa",
		"ca-ES": "Samoa Americana",
		"ca-AD": "Samoa Americana",
		"ca-FR": "Samoa Americana",
		"ca-IT": "Samoa Americana",
		"eu-ES": "Samoa Estatubatuarra",
		"eu-FR": "Samoa Estatubatuarra",
		"gl-ES": "Samoa Americana",
		"tr-TR": "Amerikan Samoası",
		"tr-CY": "Amerikan Samoası"
	},
	"callingCode": "1684",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
