import type { Country } from './types.js';

export const ATA = {
	"code": "ATA",
	"labels": {
		"pt-BR": "Antártida",
		"pt-PT": "Antártida",
		"es-ES": "Antártida",
		"es-419": "Antártida",
		"es-AR": "Antártida",
		"es-BO": "Antártida",
		"es-BR": "Antártida",
		"es-BZ": "Antártida",
		"es-CL": "Antártida",
		"es-CO": "Antártida",
		"es-CR": "Antártida",
		"es-CU": "Antártida",
		"es-DO": "Antártida",
		"es-EC": "Antártida",
		"es-GT": "Antártida",
		"es-HN": "Antártida",
		"es-MX": "Antártida",
		"es-NI": "Antártida",
		"es-PA": "Antártida",
		"es-PE": "Antártida",
		"es-PR": "Antártida",
		"es-PY": "Antártida",
		"es-SV": "Antártida",
		"es-US": "Antártida",
		"es-UY": "Antártida",
		"es-VE": "Antártida",
		"en-US": "Antarctica",
		"fr-FR": "Antarctique",
		"fr-BE": "Antarctique",
		"fr-CA": "Antarctique",
		"fr-CH": "Antarctique",
		"fr-LU": "Antarctique",
		"fr-MC": "Antarctique",
		"it-IT": "Antartide",
		"it-CH": "Antartide",
		"it-SM": "Antartide",
		"it-VA": "Antartide",
		"de-DE": "Antarktis",
		"de-AT": "Antarktis",
		"de-CH": "Antarktis",
		"de-BE": "Antarktis",
		"de-LI": "Antarktis",
		"de-LU": "Antarktis"
	}
} satisfies Country;
