import type { Country } from './types.js';

export const ATF = {
	"code": "ATF",
	"labels": {
		"pt-BR": "Territórios Franceses do Sul",
		"pt-PT": "Territórios Austrais Franceses",
		"es-ES": "Territorios Australes Franceses",
		"es-419": "Territorios Australes Franceses",
		"es-AR": "Territorios Australes Franceses",
		"es-BO": "Territorios Australes Franceses",
		"es-BR": "Territorios Australes Franceses",
		"es-BZ": "Territorios Australes Franceses",
		"es-CL": "Territorios Australes Franceses",
		"es-CO": "Territorios Australes Franceses",
		"es-CR": "Territorios Australes Franceses",
		"es-CU": "Territorios Australes Franceses",
		"es-DO": "Territorios Australes Franceses",
		"es-EC": "Territorios Australes Franceses",
		"es-GT": "Territorios Australes Franceses",
		"es-HN": "Territorios Australes Franceses",
		"es-MX": "Territorios Australes Franceses",
		"es-NI": "Territorios Australes Franceses",
		"es-PA": "Territorios Australes Franceses",
		"es-PE": "Territorios Australes Franceses",
		"es-PR": "Territorios Australes Franceses",
		"es-PY": "Territorios Australes Franceses",
		"es-SV": "Territorios Australes Franceses",
		"es-US": "Territorios Australes Franceses",
		"es-UY": "Territorios Australes Franceses",
		"es-VE": "Territorios Australes Franceses",
		"en-US": "French Southern Territories",
		"fr-FR": "Terres australes françaises",
		"fr-BE": "Terres australes françaises",
		"fr-CA": "Terres australes françaises",
		"fr-CH": "Terres australes françaises",
		"fr-LU": "Terres australes françaises",
		"fr-MC": "Terres australes françaises",
		"it-IT": "Terre Australi Francesi",
		"it-CH": "Terre Australi Francesi",
		"it-SM": "Terre Australi Francesi",
		"it-VA": "Terre Australi Francesi",
		"de-DE": "Französische Süd- und Antarktisgebiete",
		"de-AT": "Französische Süd- und Antarktisgebiete",
		"de-CH": "Französische Süd- und Antarktisgebiete",
		"de-BE": "Französische Süd- und Antarktisgebiete",
		"de-LI": "Französische Süd- und Antarktisgebiete",
		"de-LU": "Französische Süd- und Antarktisgebiete"
	}
} satisfies Country;
