import type { Country } from './types.js';

export const ATG = {
	"code": "ATG",
	"labels": {
		"pt-BR": "Antígua e Barbuda",
		"pt-PT": "Antígua e Barbuda",
		"qu-PE": "Antigua y Barbuda",
		"qu-BO": "Antigua y Barbuda",
		"qu-EC": "Antigua y Barbuda",
		"chr-US": "ᎤᏪᏘ & ᏆᏊᏓ",
		"hi-IN": "एंटिगुआ और बरबुडा",
		"bn-IN": "অ্যান্টিগুয়া ও বারবুডা",
		"bn-BD": "অ্যান্টিগুয়া ও বারবুডা",
		"ta-IN": "ஆண்டிகுவா மற்றும் பார்புடா",
		"ta-LK": "ஆண்டிகுவா மற்றும் பார்புடா",
		"ta-SG": "ஆண்டிகுவா மற்றும் பார்புடா",
		"ta-MY": "ஆண்டிகுவா மற்றும் பார்புடா",
		"te-IN": "ఆంటిగ్వా మరియు బార్బుడా",
		"mr-IN": "अँटिग्वा आणि बर्बुडा",
		"gu-IN": "ઍન્ટિગુઆ અને બર્મુડા",
		"kn-IN": "ಆಂಟಿಗುವಾ ಮತ್ತು ಬರ್ಬುಡಾ",
		"ml-IN": "ആൻറിഗ്വയും ബർബുഡയും",
		"pa-IN": "ਐਂਟੀਗੁਆ ਅਤੇ ਬਾਰਬੁਡਾ",
		"ur-IN": "انٹیگوا اور باربودا",
		"ur-PK": "انٹیگوا اور باربودا",
		"or-IN": "ଆଣ୍ଟିଗୁଆ ଏବଂ ବାରବୁଦା",
		"as-IN": "এণ্টিগুৱা আৰু বাৰ্বুডা",
		"ne-IN": "एन्टिगुआ र बारबुडा",
		"ne-NP": "एन्टिगुआ र बारबुडा",
		"si-LK": "ඇන්ටිගුවා සහ බාබියුඩාව",
		"kok-IN": "एँटिगुआ आनी बारबुडा",
		"ks-IN": "اؠنٹِگُوا تہٕ باربوڑا",
		"brx-IN": "एन्टिगुआ आरो बारबुडा",
		"mai-IN": "एंटिगुआ आ बारबुडा",
		"dz-BT": "ཨན་ཊི་གུ་ཝ་ ཨེནཌ་ བྷར་བྷུ་ཌ",
		"ja-JP": "アンティグア・バーブーダ",
		"ko-KR": "앤티가 바부다",
		"ko-KP": "앤티가 바부다",
		"zh-CN": "安提瓜和巴布达",
		"zh-Hans-CN": "安提瓜和巴布达",
		"zh-Hant-TW": "安地卡及巴布達",
		"zh-TW": "安地卡及巴布達",
		"zh-HK": "安提瓜和巴布達",
		"zh-MO": "安提瓜和巴布達",
		"zh-SG": "安提瓜和巴布达",
		"yue-Hant-HK": "安提瓜同巴布達",
		"yue-Hans-CN": "安提瓜同巴布达",
		"mn-MN": "Антигуа ба Барбуда",
		"ug-CN": "ئانتىگۇئا ۋە باربۇدا",
		"th-TH": "แอนติกาและบาร์บูดา",
		"lo-LA": "ແອນທິກົວ ແລະ ບາບູດາ",
		"km-KH": "អង់ទីហ្គា និង បាប៊ុយដា",
		"my-MM": "အန်တီဂွါနှင့် ဘာဘူဒါ",
		"vi-VN": "Antigua và Barbuda",
		"id-ID": "Antigua dan Barbuda",
		"ms-MY": "Antigua dan Barbuda",
		"ms-SG": "Antigua dan Barbuda",
		"ms-BN": "Antigua dan Barbuda",
		"jv-ID": "Antigua lan Barbuda",
		"fil-PH": "Antigua & Barbuda",
		"ceb-PH": "Antigua & Barbuda",
		"ka-GE": "ანტიგუა და ბარბუდა",
		"hy-AM": "Անտիգուա և Բարբուդա",
		"az-AZ": "Antiqua və Barbuda",
		"az-Cyrl-AZ": "Антигуа вә Барбуда",
		"kk-KZ": "Антигуа және Барбуда",
		"ky-KG": "Антигуа жана Барбуда",
		"uz-UZ": "Antigua va Barbuda",
		"tg-TJ": "Антигуа ва Барбуда",
		"tk-TM": "Antigua we Barbuda",
		"fa-IR": "آنتیگوا و باربودا",
		"fa-AF": "انتیگوا و باربودا",
		"ps-AF": "انټيګوا او باربودا",
		"ps-PK": "انټيګوا او باربودا",
		"he-IL": "אנטיגואה וברבודה",
		"ar-SA": "أنتيغوا وبربودا",
		"ar-AE": "أنتيغوا وبربودا",
		"ar-QA": "أنتيغوا وبربودا",
		"ar-BH": "أنتيغوا وبربودا",
		"ar-KW": "أنتيغوا وبربودا",
		"ar-OM": "أنتيغوا وبربودا",
		"ar-YE": "أنتيغوا وبربودا",
		"ar-IQ": "أنتيغوا وبربودا",
		"ar-JO": "أنتيغوا وبربودا",
		"ar-LB": "أنتيغوا وبربودا",
		"ar-SY": "أنتيغوا وبربودا",
		"ar-PS": "أنتيغوا وبربودا",
		"en-US": "Antigua & Barbuda",
		"en-GB": "Antigua & Barbuda",
		"en-IE": "Antigua & Barbuda",
		"en-MT": "Antigua & Barbuda",
		"en-GI": "Antigua & Barbuda",
		"en-CY": "Antigua & Barbuda",
		"en-JE": "Antigua & Barbuda",
		"en-GG": "Antigua & Barbuda",
		"en-IM": "Antigua & Barbuda",
		"en-CA": "Antigua and Barbuda",
		"en-AU": "Antigua & Barbuda",
		"en-NZ": "Antigua & Barbuda",
		"en-ZA": "Antigua & Barbuda",
		"en-IN": "Antigua & Barbuda",
		"en-SG": "Antigua & Barbuda",
		"pt-AO": "Antígua e Barbuda",
		"pt-MZ": "Antígua e Barbuda",
		"pt-CV": "Antígua e Barbuda",
		"pt-GW": "Antígua e Barbuda",
		"pt-ST": "Antígua e Barbuda",
		"pt-TL": "Antígua e Barbuda",
		"pt-MO": "Antígua e Barbuda",
		"es-ES": "Antigua y Barbuda",
		"es-419": "Antigua y Barbuda",
		"es-AD": "Antigua y Barbuda",
		"es-GI": "Antigua y Barbuda",
		"es-AR": "Antigua y Barbuda",
		"es-BO": "Antigua y Barbuda",
		"es-BR": "Antigua y Barbuda",
		"es-BZ": "Antigua y Barbuda",
		"es-CL": "Antigua y Barbuda",
		"es-CO": "Antigua y Barbuda",
		"es-CR": "Antigua y Barbuda",
		"es-CU": "Antigua y Barbuda",
		"es-DO": "Antigua y Barbuda",
		"es-EC": "Antigua y Barbuda",
		"es-GT": "Antigua y Barbuda",
		"es-HN": "Antigua y Barbuda",
		"es-MX": "Antigua y Barbuda",
		"es-NI": "Antigua y Barbuda",
		"es-PA": "Antigua y Barbuda",
		"es-PE": "Antigua y Barbuda",
		"es-PR": "Antigua y Barbuda",
		"es-PY": "Antigua y Barbuda",
		"es-SV": "Antigua y Barbuda",
		"es-US": "Antigua y Barbuda",
		"es-UY": "Antigua y Barbuda",
		"es-VE": "Antigua y Barbuda",
		"fr-FR": "Antigua-et-Barbuda",
		"fr-BE": "Antigua-et-Barbuda",
		"fr-CH": "Antigua-et-Barbuda",
		"fr-LU": "Antigua-et-Barbuda",
		"fr-MC": "Antigua-et-Barbuda",
		"fr-AD": "Antigua-et-Barbuda",
		"fr-CA": "Antigua-et-Barbuda",
		"it-IT": "Antigua e Barbuda",
		"it-CH": "Antigua e Barbuda",
		"it-SM": "Antigua e Barbuda",
		"it-VA": "Antigua e Barbuda",
		"de-DE": "Antigua und Barbuda",
		"de-AT": "Antigua und Barbuda",
		"de-CH": "Antigua und Barbuda",
		"de-BE": "Antigua und Barbuda",
		"de-LI": "Antigua und Barbuda",
		"de-LU": "Antigua und Barbuda",
		"nl-NL": "Antigua en Barbuda",
		"nl-BE": "Antigua en Barbuda",
		"sv-SE": "Antigua och Barbuda",
		"sv-FI": "Antigua och Barbuda",
		"da-DK": "Antigua og Barbuda",
		"nb-NO": "Antigua og Barbuda",
		"nn-NO": "Antigua og Barbuda",
		"fi-FI": "Antigua ja Barbuda",
		"is-IS": "Antígva og Barbúda",
		"fo-FO": "Antigua & Barbuda",
		"et-EE": "Antigua ja Barbuda",
		"lv-LV": "Antigva un Barbuda",
		"lt-LT": "Antigva ir Barbuda",
		"pl-PL": "Antigua i Barbuda",
		"cs-CZ": "Antigua a Barbuda",
		"sk-SK": "Antigua a Barbuda",
		"sl-SI": "Antigva in Barbuda",
		"hr-HR": "Antigva i Barbuda",
		"bs-BA": "Antigva i Barbuda",
		"sr-RS": "Антигва и Барбуда",
		"sr-BA": "Антигва и Барбуда",
		"sr-ME": "Antigva i Barbuda",
		"mk-MK": "Антига и Барбуда",
		"bg-BG": "Антигуа и Барбуда",
		"be-BY": "Антыгуа і Барбуда",
		"uk-UA": "Антигуа і Барбуда",
		"ru-RU": "Антигуа и Барбуда",
		"el-GR": "Αντίγκουα και Μπαρμπούντα",
		"el-CY": "Αντίγκουα και Μπαρμπούντα",
		"ro-RO": "Antigua și Barbuda",
		"ro-MD": "Antigua și Barbuda",
		"hu-HU": "Antigua és Barbuda",
		"sq-AL": "Antigua e Barbuda",
		"sq-XK": "Antigua e Barbuda",
		"mt-MT": "Antigua u Barbuda",
		"ga-IE": "Antigua agus Barbúda",
		"cy-GB": "Antigua a Barbuda",
		"gd-GB": "Aintìoga is Barbuda",
		"lb-LU": "Antigua a Barbuda",
		"ca-ES": "Antigua i Barbuda",
		"ca-AD": "Antigua i Barbuda",
		"ca-FR": "Antigua i Barbuda",
		"ca-IT": "Antigua i Barbuda",
		"eu-ES": "Antigua eta Barbuda",
		"eu-FR": "Antigua eta Barbuda",
		"gl-ES": "Antigua e Barbuda",
		"tr-TR": "Antigua ve Barbuda",
		"tr-CY": "Antigua ve Barbuda"
	},
	"callingCode": "1268",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
