import type { Country } from './types.js';

export const ATG = {
	"code": "ATG",
	"labels": {
		"pt-BR": "Antígua e Barbuda",
		"pt-PT": "Antígua e Barbuda",
		"es-ES": "Antigua y Barbuda",
		"es-419": "Antigua y Barbuda",
		"es-AR": "Antigua y Barbuda",
		"es-BO": "Antigua y Barbuda",
		"es-BR": "Antigua y Barbuda",
		"es-BZ": "Antigua y Barbuda",
		"es-CL": "Antigua y Barbuda",
		"es-CO": "Antigua y Barbuda",
		"es-CR": "Antigua y Barbuda",
		"es-CU": "Antigua y Barbuda",
		"es-DO": "Antigua y Barbuda",
		"es-EC": "Antigua y Barbuda",
		"es-GT": "Antigua y Barbuda",
		"es-HN": "Antigua y Barbuda",
		"es-MX": "Antigua y Barbuda",
		"es-NI": "Antigua y Barbuda",
		"es-PA": "Antigua y Barbuda",
		"es-PE": "Antigua y Barbuda",
		"es-PR": "Antigua y Barbuda",
		"es-PY": "Antigua y Barbuda",
		"es-SV": "Antigua y Barbuda",
		"es-US": "Antigua y Barbuda",
		"es-UY": "Antigua y Barbuda",
		"es-VE": "Antigua y Barbuda",
		"en-US": "Antigua & Barbuda",
		"fr-FR": "Antigua-et-Barbuda",
		"fr-BE": "Antigua-et-Barbuda",
		"fr-CA": "Antigua-et-Barbuda",
		"fr-CH": "Antigua-et-Barbuda",
		"fr-LU": "Antigua-et-Barbuda",
		"fr-MC": "Antigua-et-Barbuda",
		"it-IT": "Antigua e Barbuda",
		"it-CH": "Antigua e Barbuda",
		"it-SM": "Antigua e Barbuda",
		"it-VA": "Antigua e Barbuda",
		"de-DE": "Antigua und Barbuda",
		"de-AT": "Antigua und Barbuda",
		"de-CH": "Antigua und Barbuda",
		"de-BE": "Antigua und Barbuda",
		"de-LI": "Antigua und Barbuda",
		"de-LU": "Antigua und Barbuda"
	}
} satisfies Country;
