import type { Country } from './types.js';

export const AUS = {
	"code": "AUS",
	"labels": {
		"pt-BR": "Austrália",
		"pt-PT": "Austrália",
		"qu-PE": "Australia",
		"qu-BO": "Australia",
		"qu-EC": "Australia",
		"chr-US": "ᎡᎳᏗᏜ",
		"hi-IN": "ऑस्ट्रेलिया",
		"bn-IN": "অস্ট্রেলিয়া",
		"bn-BD": "অস্ট্রেলিয়া",
		"ta-IN": "ஆஸ்திரேலியா",
		"ta-LK": "ஆஸ்திரேலியா",
		"ta-SG": "ஆஸ்திரேலியா",
		"ta-MY": "ஆஸ்திரேலியா",
		"te-IN": "ఆస్ట్రేలియా",
		"mr-IN": "ऑस्ट्रेलिया",
		"gu-IN": "ઑસ્ટ્રેલિયા",
		"kn-IN": "ಆಸ್ಟ್ರೇಲಿಯಾ",
		"ml-IN": "ഓസ്‌ട്രേലിയ",
		"pa-IN": "ਆਸਟ੍ਰੇਲੀਆ",
		"ur-IN": "آسٹریلیا",
		"ur-PK": "آسٹریلیا",
		"or-IN": "ଅଷ୍ଟ୍ରେଲିଆ",
		"as-IN": "অষ্ট্ৰেলিয়া",
		"ne-IN": "अस्ट्रेलिया",
		"ne-NP": "अस्ट्रेलिया",
		"si-LK": "ඕස්ට්‍රේලියාව",
		"kok-IN": "ऑस्ट्रेलीया",
		"ks-IN": "آسٹریلِیا",
		"brx-IN": "अस्ट्रेलिया",
		"mai-IN": "आस्ट्रेलिया",
		"dz-BT": "ཨཱོས་ཊྲེལ་ལི་ཡ",
		"ja-JP": "オーストラリア",
		"ko-KR": "오스트레일리아",
		"ko-KP": "오스트레일리아",
		"zh-CN": "澳大利亚",
		"zh-Hans-CN": "澳大利亚",
		"zh-Hant-TW": "澳洲",
		"zh-TW": "澳洲",
		"zh-HK": "澳洲",
		"zh-MO": "澳洲",
		"zh-SG": "澳大利亚",
		"yue-Hant-HK": "澳洲",
		"yue-Hans-CN": "澳洲",
		"mn-MN": "Австрали",
		"ug-CN": "ئاۋسترالىيە",
		"th-TH": "ออสเตรเลีย",
		"lo-LA": "ອອສເຕຣເລຍ",
		"km-KH": "អូស្ត្រាលី",
		"my-MM": "ဩစတြေးလျ",
		"vi-VN": "Australia",
		"id-ID": "Australia",
		"ms-MY": "Australia",
		"ms-SG": "Australia",
		"ms-BN": "Australia",
		"jv-ID": "Ostrali",
		"fil-PH": "Australia",
		"ceb-PH": "Australia",
		"ka-GE": "ავსტრალია",
		"hy-AM": "Ավստրալիա",
		"az-AZ": "Avstraliya",
		"az-Cyrl-AZ": "Австралија",
		"kk-KZ": "Аустралия",
		"ky-KG": "Австралия",
		"uz-UZ": "Avstraliya",
		"tg-TJ": "Австралия",
		"tk-TM": "Awstraliýa",
		"fa-IR": "استرالیا",
		"fa-AF": "استرالیا",
		"ps-AF": "آسټرالیا",
		"ps-PK": "آسټرالیا",
		"he-IL": "אוסטרליה",
		"ar-SA": "أستراليا",
		"ar-AE": "أستراليا",
		"ar-QA": "أستراليا",
		"ar-BH": "أستراليا",
		"ar-KW": "أستراليا",
		"ar-OM": "أستراليا",
		"ar-YE": "أستراليا",
		"ar-IQ": "أستراليا",
		"ar-JO": "أستراليا",
		"ar-LB": "أستراليا",
		"ar-SY": "أستراليا",
		"ar-PS": "أستراليا",
		"en-US": "Australia",
		"en-GB": "Australia",
		"en-IE": "Australia",
		"en-MT": "Australia",
		"en-GI": "Australia",
		"en-CY": "Australia",
		"en-JE": "Australia",
		"en-GG": "Australia",
		"en-IM": "Australia",
		"en-CA": "Australia",
		"en-AU": "Australia",
		"en-NZ": "Australia",
		"en-ZA": "Australia",
		"en-IN": "Australia",
		"en-SG": "Australia",
		"pt-AO": "Austrália",
		"pt-MZ": "Austrália",
		"pt-CV": "Austrália",
		"pt-GW": "Austrália",
		"pt-ST": "Austrália",
		"pt-TL": "Austrália",
		"pt-MO": "Austrália",
		"es-ES": "Australia",
		"es-419": "Australia",
		"es-AD": "Australia",
		"es-GI": "Australia",
		"es-AR": "Australia",
		"es-BO": "Australia",
		"es-BR": "Australia",
		"es-BZ": "Australia",
		"es-CL": "Australia",
		"es-CO": "Australia",
		"es-CR": "Australia",
		"es-CU": "Australia",
		"es-DO": "Australia",
		"es-EC": "Australia",
		"es-GT": "Australia",
		"es-HN": "Australia",
		"es-MX": "Australia",
		"es-NI": "Australia",
		"es-PA": "Australia",
		"es-PE": "Australia",
		"es-PR": "Australia",
		"es-PY": "Australia",
		"es-SV": "Australia",
		"es-US": "Australia",
		"es-UY": "Australia",
		"es-VE": "Australia",
		"fr-FR": "Australie",
		"fr-BE": "Australie",
		"fr-CH": "Australie",
		"fr-LU": "Australie",
		"fr-MC": "Australie",
		"fr-AD": "Australie",
		"fr-CA": "Australie",
		"it-IT": "Australia",
		"it-CH": "Australia",
		"it-SM": "Australia",
		"it-VA": "Australia",
		"de-DE": "Australien",
		"de-AT": "Australien",
		"de-CH": "Australien",
		"de-BE": "Australien",
		"de-LI": "Australien",
		"de-LU": "Australien",
		"nl-NL": "Australië",
		"nl-BE": "Australië",
		"sv-SE": "Australien",
		"sv-FI": "Australien",
		"da-DK": "Australien",
		"nb-NO": "Australia",
		"nn-NO": "Australia",
		"fi-FI": "Australia",
		"is-IS": "Ástralía",
		"fo-FO": "Avstralia",
		"et-EE": "Austraalia",
		"lv-LV": "Austrālija",
		"lt-LT": "Australija",
		"pl-PL": "Australia",
		"cs-CZ": "Austrálie",
		"sk-SK": "Austrália",
		"sl-SI": "Avstralija",
		"hr-HR": "Australija",
		"bs-BA": "Australija",
		"sr-RS": "Аустралија",
		"sr-BA": "Аустралија",
		"sr-ME": "Australija",
		"mk-MK": "Австралија",
		"bg-BG": "Австралия",
		"be-BY": "Аўстралія",
		"uk-UA": "Австралія",
		"ru-RU": "Австралия",
		"el-GR": "Αυστραλία",
		"el-CY": "Αυστραλία",
		"ro-RO": "Australia",
		"ro-MD": "Australia",
		"hu-HU": "Ausztrália",
		"sq-AL": "Australi",
		"sq-XK": "Australi",
		"mt-MT": "l-Awstralja",
		"ga-IE": "an Astráil",
		"cy-GB": "Awstralia",
		"gd-GB": "Astràilia",
		"lb-LU": "Australien",
		"ca-ES": "Austràlia",
		"ca-AD": "Austràlia",
		"ca-FR": "Austràlia",
		"ca-IT": "Austràlia",
		"eu-ES": "Australia",
		"eu-FR": "Australia",
		"gl-ES": "Australia",
		"tr-TR": "Avustralya",
		"tr-CY": "Avustralya"
	},
	"callingCode": "61",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "## ####",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"16"
			]
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "# #### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[2378]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"16"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"14|4"
			]
		},
		{
			"mask": "#### ### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1(?:30|[89])"
			]
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12
		}
	]
} satisfies Country;
