import type { Country } from './types.js';

export const AUT = {
	"code": "AUT",
	"labels": {
		"pt-BR": "Áustria",
		"pt-PT": "Áustria",
		"es-ES": "Austria",
		"es-419": "Austria",
		"es-AR": "Austria",
		"es-BO": "Austria",
		"es-BR": "Austria",
		"es-BZ": "Austria",
		"es-CL": "Austria",
		"es-CO": "Austria",
		"es-CR": "Austria",
		"es-CU": "Austria",
		"es-DO": "Austria",
		"es-EC": "Austria",
		"es-GT": "Austria",
		"es-HN": "Austria",
		"es-MX": "Austria",
		"es-NI": "Austria",
		"es-PA": "Austria",
		"es-PE": "Austria",
		"es-PR": "Austria",
		"es-PY": "Austria",
		"es-SV": "Austria",
		"es-US": "Austria",
		"es-UY": "Austria",
		"es-VE": "Austria",
		"en-US": "Austria",
		"fr-FR": "Autriche",
		"fr-BE": "Autriche",
		"fr-CA": "Autriche",
		"fr-CH": "Autriche",
		"fr-LU": "Autriche",
		"fr-MC": "Autriche",
		"it-IT": "Austria",
		"it-CH": "Austria",
		"it-SM": "Austria",
		"it-VA": "Austria",
		"de-DE": "Österreich",
		"de-AT": "Österreich",
		"de-CH": "Österreich",
		"de-BE": "Österreich",
		"de-LI": "Österreich",
		"de-LU": "Österreich"
	},
	"callingCode": "43"
} satisfies Country;
