import type { Country } from './types.js';

export const AUT = {
	"code": "AUT",
	"labels": {
		"pt-BR": "Áustria",
		"pt-PT": "Áustria",
		"qu-PE": "Austria",
		"qu-BO": "Austria",
		"qu-EC": "Austria",
		"chr-US": "ᎠᏍᏟᏯ",
		"hi-IN": "ऑस्ट्रिया",
		"bn-IN": "অস্ট্রিয়া",
		"bn-BD": "অস্ট্রিয়া",
		"ta-IN": "ஆஸ்திரியா",
		"ta-LK": "ஆஸ்திரியா",
		"ta-SG": "ஆஸ்திரியா",
		"ta-MY": "ஆஸ்திரியா",
		"te-IN": "ఆస్ట్రియా",
		"mr-IN": "ऑस्ट्रिया",
		"gu-IN": "ઑસ્ટ્રિયા",
		"kn-IN": "ಆಸ್ಟ್ರಿಯಾ",
		"ml-IN": "ഓസ്ട്രിയ",
		"pa-IN": "ਆਸਟਰੀਆ",
		"ur-IN": "آسٹریا",
		"ur-PK": "آسٹریا",
		"or-IN": "ଅଷ୍ଟ୍ରିଆ",
		"as-IN": "অষ্ট্ৰিয়া",
		"ne-IN": "अष्ट्रिया",
		"ne-NP": "अष्ट्रिया",
		"si-LK": "ඔස්ට්‍රියාව",
		"kok-IN": "ऑस्ट्रिया",
		"ks-IN": "آسٹریا",
		"brx-IN": "अस्ट्रिया",
		"mai-IN": "आस्ट्रिया",
		"dz-BT": "ཨཱོས་ཊྲི་ཡ",
		"ja-JP": "オーストリア",
		"ko-KR": "오스트리아",
		"ko-KP": "오스트리아",
		"zh-CN": "奥地利",
		"zh-Hans-CN": "奥地利",
		"zh-Hant-TW": "奧地利",
		"zh-TW": "奧地利",
		"zh-HK": "奧地利",
		"zh-MO": "奧地利",
		"zh-SG": "奥地利",
		"yue-Hant-HK": "奧地利",
		"yue-Hans-CN": "奥地利",
		"mn-MN": "Австри",
		"ug-CN": "ئاۋىستىرىيە",
		"th-TH": "ออสเตรีย",
		"lo-LA": "ອອສເທຣຍ",
		"km-KH": "អូទ្រីស",
		"my-MM": "ဩစတြီးယား",
		"vi-VN": "Áo",
		"id-ID": "Austria",
		"ms-MY": "Austria",
		"ms-SG": "Austria",
		"ms-BN": "Austria",
		"jv-ID": "Ostenrik",
		"fil-PH": "Austria",
		"ceb-PH": "Austria",
		"ka-GE": "ავსტრია",
		"hy-AM": "Ավստրիա",
		"az-AZ": "Avstriya",
		"az-Cyrl-AZ": "Австрија",
		"kk-KZ": "Аустрия",
		"ky-KG": "Австрия",
		"uz-UZ": "Avstriya",
		"tg-TJ": "Австрия",
		"tk-TM": "Awstriýa",
		"fa-IR": "اتریش",
		"fa-AF": "اتریش",
		"ps-AF": "اتریش",
		"ps-PK": "اتریش",
		"he-IL": "אוסטריה",
		"ar-SA": "النمسا",
		"ar-AE": "النمسا",
		"ar-QA": "النمسا",
		"ar-BH": "النمسا",
		"ar-KW": "النمسا",
		"ar-OM": "النمسا",
		"ar-YE": "النمسا",
		"ar-IQ": "النمسا",
		"ar-JO": "النمسا",
		"ar-LB": "النمسا",
		"ar-SY": "النمسا",
		"ar-PS": "النمسا",
		"en-US": "Austria",
		"en-GB": "Austria",
		"en-IE": "Austria",
		"en-MT": "Austria",
		"en-GI": "Austria",
		"en-CY": "Austria",
		"en-JE": "Austria",
		"en-GG": "Austria",
		"en-IM": "Austria",
		"en-CA": "Austria",
		"en-AU": "Austria",
		"en-NZ": "Austria",
		"en-ZA": "Austria",
		"en-IN": "Austria",
		"en-SG": "Austria",
		"pt-AO": "Áustria",
		"pt-MZ": "Áustria",
		"pt-CV": "Áustria",
		"pt-GW": "Áustria",
		"pt-ST": "Áustria",
		"pt-TL": "Áustria",
		"pt-MO": "Áustria",
		"es-ES": "Austria",
		"es-419": "Austria",
		"es-AD": "Austria",
		"es-GI": "Austria",
		"es-AR": "Austria",
		"es-BO": "Austria",
		"es-BR": "Austria",
		"es-BZ": "Austria",
		"es-CL": "Austria",
		"es-CO": "Austria",
		"es-CR": "Austria",
		"es-CU": "Austria",
		"es-DO": "Austria",
		"es-EC": "Austria",
		"es-GT": "Austria",
		"es-HN": "Austria",
		"es-MX": "Austria",
		"es-NI": "Austria",
		"es-PA": "Austria",
		"es-PE": "Austria",
		"es-PR": "Austria",
		"es-PY": "Austria",
		"es-SV": "Austria",
		"es-US": "Austria",
		"es-UY": "Austria",
		"es-VE": "Austria",
		"fr-FR": "Autriche",
		"fr-BE": "Autriche",
		"fr-CH": "Autriche",
		"fr-LU": "Autriche",
		"fr-MC": "Autriche",
		"fr-AD": "Autriche",
		"fr-CA": "Autriche",
		"it-IT": "Austria",
		"it-CH": "Austria",
		"it-SM": "Austria",
		"it-VA": "Austria",
		"de-DE": "Österreich",
		"de-AT": "Österreich",
		"de-CH": "Österreich",
		"de-BE": "Österreich",
		"de-LI": "Österreich",
		"de-LU": "Österreich",
		"nl-NL": "Oostenrijk",
		"nl-BE": "Oostenrijk",
		"sv-SE": "Österrike",
		"sv-FI": "Österrike",
		"da-DK": "Østrig",
		"nb-NO": "Østerrike",
		"nn-NO": "Austerrike",
		"fi-FI": "Itävalta",
		"is-IS": "Austurríki",
		"fo-FO": "Eysturríki",
		"et-EE": "Austria",
		"lv-LV": "Austrija",
		"lt-LT": "Austrija",
		"pl-PL": "Austria",
		"cs-CZ": "Rakousko",
		"sk-SK": "Rakúsko",
		"sl-SI": "Avstrija",
		"hr-HR": "Austrija",
		"bs-BA": "Austrija",
		"sr-RS": "Аустрија",
		"sr-BA": "Аустрија",
		"sr-ME": "Austrija",
		"mk-MK": "Австрија",
		"bg-BG": "Австрия",
		"be-BY": "Аўстрыя",
		"uk-UA": "Австрія",
		"ru-RU": "Австрия",
		"el-GR": "Αυστρία",
		"el-CY": "Αυστρία",
		"ro-RO": "Austria",
		"ro-MD": "Austria",
		"hu-HU": "Ausztria",
		"sq-AL": "Austri",
		"sq-XK": "Austri",
		"mt-MT": "l-Awstrija",
		"ga-IE": "an Ostair",
		"cy-GB": "Awstria",
		"gd-GB": "An Ostair",
		"lb-LU": "Éisträich",
		"ca-ES": "Àustria",
		"ca-AD": "Àustria",
		"ca-FR": "Àustria",
		"ca-IT": "Àustria",
		"eu-ES": "Austria",
		"eu-FR": "Austria",
		"gl-ES": "Austria",
		"tr-TR": "Avusturya",
		"tr-CY": "Avusturya"
	},
	"callingCode": "43",
	"phoneMasks": [
		{
			"mask": "####",
			"minLength": 4,
			"maxLength": 4
		},
		{
			"mask": "### ##",
			"minLength": 5,
			"maxLength": 5,
			"leadingDigits": [
				"517"
			]
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"5[079]"
			]
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"5"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12
		},
		{
			"mask": "# ############",
			"minLength": 13,
			"maxLength": 13,
			"leadingDigits": [
				"1(?:11|[2-9])"
			]
		},
		{
			"mask": "## #### #######",
			"minLength": 13,
			"maxLength": 13,
			"leadingDigits": [
				"5"
			]
		},
		{
			"mask": "### ##########",
			"minLength": 13,
			"maxLength": 13,
			"leadingDigits": [
				"(?:31|4)6|51|6(?:5[0-3579]|[6-9])|7(?:20|32|8)|[89]"
			]
		},
		{
			"mask": "#### #########",
			"minLength": 13,
			"maxLength": 13,
			"leadingDigits": [
				"[2-467]|5[2-6]"
			]
		}
	]
} satisfies Country;
