import type { Country } from './types.js';

export const AZE = {
	"code": "AZE",
	"labels": {
		"pt-BR": "Azerbaijão",
		"pt-PT": "Azerbaijão",
		"qu-PE": "Azerbaiyán",
		"qu-BO": "Azerbaiyán",
		"qu-EC": "Azerbaiyán",
		"chr-US": "ᎠᏎᏆᏣᏂ",
		"hi-IN": "अज़रबैजान",
		"bn-IN": "আজারবাইজান",
		"bn-BD": "আজারবাইজান",
		"ta-IN": "அசர்பைஜான்",
		"ta-LK": "அசர்பைஜான்",
		"ta-SG": "அசர்பைஜான்",
		"ta-MY": "அசர்பைஜான்",
		"te-IN": "అజర్బైజాన్",
		"mr-IN": "अझरबैजान",
		"gu-IN": "અઝરબૈજાન",
		"kn-IN": "ಅಜರ್ಬೈಜಾನ್",
		"ml-IN": "അസർബൈജാൻ",
		"pa-IN": "ਅਜ਼ਰਬਾਈਜਾਨ",
		"ur-IN": "آذربائیجان",
		"ur-PK": "آذربائیجان",
		"or-IN": "ଆଜେରବାଇଜାନ୍",
		"as-IN": "আজাৰবেইজান",
		"ne-IN": "अजरबैजान",
		"ne-NP": "अजरबैजान",
		"si-LK": "අසර්බයිජානය",
		"kok-IN": "अजरबैजान",
		"ks-IN": "آذربائیجان",
		"brx-IN": "आजेरबाईजान",
		"mai-IN": "अजरबैजान",
		"dz-BT": "ཨ་ཛར་བྷའི་ཇཱན",
		"ja-JP": "アゼルバイジャン",
		"ko-KR": "아제르바이잔",
		"ko-KP": "아제르바이잔",
		"zh-CN": "阿塞拜疆",
		"zh-Hans-CN": "阿塞拜疆",
		"zh-Hant-TW": "亞塞拜然",
		"zh-TW": "亞塞拜然",
		"zh-HK": "亞塞拜疆",
		"zh-MO": "亞塞拜疆",
		"zh-SG": "阿塞拜疆",
		"yue-Hant-HK": "阿塞拜疆",
		"yue-Hans-CN": "亚塞拜然",
		"mn-MN": "Азербайжан",
		"ug-CN": "ئەزەربەيجان",
		"th-TH": "อาเซอร์ไบจาน",
		"lo-LA": "ອາເຊີໄບຈານ",
		"km-KH": "អាស៊ែបៃហ្សង់",
		"my-MM": "အဇာဘိုင်ဂျန်",
		"vi-VN": "Azerbaijan",
		"id-ID": "Azerbaijan",
		"ms-MY": "Azerbaijan",
		"ms-SG": "Azerbaijan",
		"ms-BN": "Azerbaijan",
		"jv-ID": "Azerbaijan",
		"fil-PH": "Azerbaijan",
		"ceb-PH": "Azerbaijan",
		"ka-GE": "აზერბაიჯანი",
		"hy-AM": "Ադրբեջան",
		"az-AZ": "Azərbaycan",
		"az-Cyrl-AZ": "Азәрбајҹан",
		"kk-KZ": "Әзірбайжан",
		"ky-KG": "Азербайжан",
		"uz-UZ": "Ozarbayjon",
		"tg-TJ": "Озарбойҷон",
		"tk-TM": "Azerbaýjan",
		"fa-IR": "جمهوری آذربایجان",
		"fa-AF": "جمهوری آذربایجان",
		"ps-AF": "اذربايجان",
		"ps-PK": "اذربايجان",
		"he-IL": "אזרבייג׳ן",
		"ar-SA": "أذربيجان",
		"ar-AE": "أذربيجان",
		"ar-QA": "أذربيجان",
		"ar-BH": "أذربيجان",
		"ar-KW": "أذربيجان",
		"ar-OM": "أذربيجان",
		"ar-YE": "أذربيجان",
		"ar-IQ": "أذربيجان",
		"ar-JO": "أذربيجان",
		"ar-LB": "أذربيجان",
		"ar-SY": "أذربيجان",
		"ar-PS": "أذربيجان",
		"en-US": "Azerbaijan",
		"en-GB": "Azerbaijan",
		"en-IE": "Azerbaijan",
		"en-MT": "Azerbaijan",
		"en-GI": "Azerbaijan",
		"en-CY": "Azerbaijan",
		"en-JE": "Azerbaijan",
		"en-GG": "Azerbaijan",
		"en-IM": "Azerbaijan",
		"en-CA": "Azerbaijan",
		"en-AU": "Azerbaijan",
		"en-NZ": "Azerbaijan",
		"en-ZA": "Azerbaijan",
		"en-IN": "Azerbaijan",
		"en-SG": "Azerbaijan",
		"pt-AO": "Azerbaijão",
		"pt-MZ": "Azerbaijão",
		"pt-CV": "Azerbaijão",
		"pt-GW": "Azerbaijão",
		"pt-ST": "Azerbaijão",
		"pt-TL": "Azerbaijão",
		"pt-MO": "Azerbaijão",
		"es-ES": "Azerbaiyán",
		"es-419": "Azerbaiyán",
		"es-AD": "Azerbaiyán",
		"es-GI": "Azerbaiyán",
		"es-AR": "Azerbaiyán",
		"es-BO": "Azerbaiyán",
		"es-BR": "Azerbaiyán",
		"es-BZ": "Azerbaiyán",
		"es-CL": "Azerbaiyán",
		"es-CO": "Azerbaiyán",
		"es-CR": "Azerbaiyán",
		"es-CU": "Azerbaiyán",
		"es-DO": "Azerbaiyán",
		"es-EC": "Azerbaiyán",
		"es-GT": "Azerbaiyán",
		"es-HN": "Azerbaiyán",
		"es-MX": "Azerbaiyán",
		"es-NI": "Azerbaiyán",
		"es-PA": "Azerbaiyán",
		"es-PE": "Azerbaiyán",
		"es-PR": "Azerbaiyán",
		"es-PY": "Azerbaiyán",
		"es-SV": "Azerbaiyán",
		"es-US": "Azerbaiyán",
		"es-UY": "Azerbaiyán",
		"es-VE": "Azerbaiyán",
		"fr-FR": "Azerbaïdjan",
		"fr-BE": "Azerbaïdjan",
		"fr-CH": "Azerbaïdjan",
		"fr-LU": "Azerbaïdjan",
		"fr-MC": "Azerbaïdjan",
		"fr-AD": "Azerbaïdjan",
		"fr-CA": "Azerbaïdjan",
		"it-IT": "Azerbaigian",
		"it-CH": "Azerbaigian",
		"it-SM": "Azerbaigian",
		"it-VA": "Azerbaigian",
		"de-DE": "Aserbaidschan",
		"de-AT": "Aserbaidschan",
		"de-CH": "Aserbaidschan",
		"de-BE": "Aserbaidschan",
		"de-LI": "Aserbaidschan",
		"de-LU": "Aserbaidschan",
		"nl-NL": "Azerbeidzjan",
		"nl-BE": "Azerbeidzjan",
		"sv-SE": "Azerbajdzjan",
		"sv-FI": "Azerbajdzjan",
		"da-DK": "Aserbajdsjan",
		"nb-NO": "Aserbajdsjan",
		"nn-NO": "Aserbajdsjan",
		"fi-FI": "Azerbaidžan",
		"is-IS": "Aserbaídsjan",
		"fo-FO": "Aserbadjan",
		"et-EE": "Aserbaidžaan",
		"lv-LV": "Azerbaidžāna",
		"lt-LT": "Azerbaidžanas",
		"pl-PL": "Azerbejdżan",
		"cs-CZ": "Ázerbájdžán",
		"sk-SK": "Azerbajdžan",
		"sl-SI": "Azerbajdžan",
		"hr-HR": "Azerbajdžan",
		"bs-BA": "Azerbejdžan",
		"sr-RS": "Азербејџан",
		"sr-BA": "Азербејџан",
		"sr-ME": "Azerbejdžan",
		"mk-MK": "Азербејџан",
		"bg-BG": "Азербайджан",
		"be-BY": "Азербайджан",
		"uk-UA": "Азербайджан",
		"ru-RU": "Азербайджан",
		"el-GR": "Αζερμπαϊτζάν",
		"el-CY": "Αζερμπαϊτζάν",
		"ro-RO": "Azerbaidjan",
		"ro-MD": "Azerbaidjan",
		"hu-HU": "Azerbajdzsán",
		"sq-AL": "Azerbajxhan",
		"sq-XK": "Azerbajxhan",
		"mt-MT": "l-Ażerbajġan",
		"ga-IE": "an Asarbaiseáin",
		"cy-GB": "Aserbaijan",
		"gd-GB": "Asarbaideàn",
		"lb-LU": "Aserbaidschan",
		"ca-ES": "Azerbaidjan",
		"ca-AD": "Azerbaidjan",
		"ca-FR": "Azerbaidjan",
		"ca-IT": "Azerbaidjan",
		"eu-ES": "Azerbaijan",
		"eu-FR": "Azerbaijan",
		"gl-ES": "Acerbaixán",
		"tr-TR": "Azerbaycan",
		"tr-CY": "Azerbaycan"
	},
	"callingCode": "994",
	"phoneMasks": [
		{
			"mask": "## ### ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1[28]|2|365|46",
				"1[28]|2|365[45]|46",
				"1[28]|2|365(?:4|5[02])|46"
			]
		},
		{
			"mask": "## ### ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[13-9]"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"90"
			]
		}
	]
} satisfies Country;
