import type { Country } from './types.js';

export const BDI = {
	"code": "BDI",
	"labels": {
		"pt-BR": "Burundi",
		"pt-PT": "Burundi",
		"es-ES": "Burundi",
		"es-419": "Burundi",
		"es-AR": "Burundi",
		"es-BO": "Burundi",
		"es-BR": "Burundi",
		"es-BZ": "Burundi",
		"es-CL": "Burundi",
		"es-CO": "Burundi",
		"es-CR": "Burundi",
		"es-CU": "Burundi",
		"es-DO": "Burundi",
		"es-EC": "Burundi",
		"es-GT": "Burundi",
		"es-HN": "Burundi",
		"es-MX": "Burundi",
		"es-NI": "Burundi",
		"es-PA": "Burundi",
		"es-PE": "Burundi",
		"es-PR": "Burundi",
		"es-PY": "Burundi",
		"es-SV": "Burundi",
		"es-US": "Burundi",
		"es-UY": "Burundi",
		"es-VE": "Burundi",
		"en-US": "Burundi",
		"fr-FR": "Burundi",
		"fr-BE": "Burundi",
		"fr-CA": "Burundi",
		"fr-CH": "Burundi",
		"fr-LU": "Burundi",
		"fr-MC": "Burundi",
		"it-IT": "Burundi",
		"it-CH": "Burundi",
		"it-SM": "Burundi",
		"it-VA": "Burundi",
		"de-DE": "Burundi",
		"de-AT": "Burundi",
		"de-CH": "Burundi",
		"de-BE": "Burundi",
		"de-LI": "Burundi",
		"de-LU": "Burundi"
	}
} satisfies Country;
