import type { Country } from './types.js';

export const BEL = {
	"code": "BEL",
	"labels": {
		"pt-BR": "Bélgica",
		"pt-PT": "Bélgica",
		"qu-PE": "Bélgica",
		"qu-BO": "Bélgica",
		"qu-EC": "Bélgica",
		"chr-US": "ᏇᎵᏥᎥᎻ",
		"hi-IN": "बेल्जियम",
		"bn-IN": "বেলজিয়াম",
		"bn-BD": "বেলজিয়াম",
		"ta-IN": "பெல்ஜியம்",
		"ta-LK": "பெல்ஜியம்",
		"ta-SG": "பெல்ஜியம்",
		"ta-MY": "பெல்ஜியம்",
		"te-IN": "బెల్జియం",
		"mr-IN": "बेल्जियम",
		"gu-IN": "બેલ્જીયમ",
		"kn-IN": "ಬೆಲ್ಜಿಯಮ್",
		"ml-IN": "ബെൽജിയം",
		"pa-IN": "ਬੈਲਜੀਅਮ",
		"ur-IN": "بیلجیم",
		"ur-PK": "بیلجیم",
		"or-IN": "ବେଲଜିୟମ୍",
		"as-IN": "বেলজিয়াম",
		"ne-IN": "बेल्जियम",
		"ne-NP": "बेल्जियम",
		"si-LK": "බෙල්ජියම",
		"kok-IN": "बेल्जियम",
		"ks-IN": "بیلجِیَم",
		"brx-IN": "बेलजियाम",
		"mai-IN": "बेल्जियम",
		"dz-BT": "བྷེལ་ཇམ",
		"ja-JP": "ベルギー",
		"ko-KR": "벨기에",
		"ko-KP": "벨기에",
		"zh-CN": "比利时",
		"zh-Hans-CN": "比利时",
		"zh-Hant-TW": "比利時",
		"zh-TW": "比利時",
		"zh-HK": "比利時",
		"zh-MO": "比利時",
		"zh-SG": "比利时",
		"yue-Hant-HK": "比利時",
		"yue-Hans-CN": "比利时",
		"mn-MN": "Бельги",
		"ug-CN": "بېلگىيە",
		"ii-CN": "ꀘꆹꏃ",
		"th-TH": "เบลเยียม",
		"lo-LA": "ເບວຢຽມ",
		"km-KH": "បែលហ្ស៊ិក",
		"my-MM": "ဘယ်လ်ဂျီယမ်",
		"vi-VN": "Bỉ",
		"id-ID": "Belgia",
		"ms-MY": "Belgium",
		"ms-SG": "Belgium",
		"ms-BN": "Belgium",
		"jv-ID": "Bèlgi",
		"fil-PH": "Belgium",
		"ceb-PH": "Belgium",
		"ka-GE": "ბელგია",
		"hy-AM": "Բելգիա",
		"az-AZ": "Belçika",
		"az-Cyrl-AZ": "Белчика",
		"kk-KZ": "Бельгия",
		"ky-KG": "Бельгия",
		"uz-UZ": "Belgiya",
		"tg-TJ": "Белгия",
		"tk-TM": "Belgiýa",
		"fa-IR": "بلژیک",
		"fa-AF": "بلجیم",
		"ps-AF": "بیلجیم",
		"ps-PK": "بیلجیم",
		"he-IL": "בלגיה",
		"ar-SA": "بلجيكا",
		"ar-AE": "بلجيكا",
		"ar-QA": "بلجيكا",
		"ar-BH": "بلجيكا",
		"ar-KW": "بلجيكا",
		"ar-OM": "بلجيكا",
		"ar-YE": "بلجيكا",
		"ar-IQ": "بلجيكا",
		"ar-JO": "بلجيكا",
		"ar-LB": "بلجيكا",
		"ar-SY": "بلجيكا",
		"ar-PS": "بلجيكا",
		"en-US": "Belgium",
		"en-GB": "Belgium",
		"en-IE": "Belgium",
		"en-MT": "Belgium",
		"en-GI": "Belgium",
		"en-CY": "Belgium",
		"en-JE": "Belgium",
		"en-GG": "Belgium",
		"en-IM": "Belgium",
		"en-CA": "Belgium",
		"en-AU": "Belgium",
		"en-NZ": "Belgium",
		"en-ZA": "Belgium",
		"en-IN": "Belgium",
		"en-SG": "Belgium",
		"pt-AO": "Bélgica",
		"pt-MZ": "Bélgica",
		"pt-CV": "Bélgica",
		"pt-GW": "Bélgica",
		"pt-ST": "Bélgica",
		"pt-TL": "Bélgica",
		"pt-MO": "Bélgica",
		"es-ES": "Bélgica",
		"es-419": "Bélgica",
		"es-AD": "Bélgica",
		"es-GI": "Bélgica",
		"es-AR": "Bélgica",
		"es-BO": "Bélgica",
		"es-BR": "Bélgica",
		"es-BZ": "Bélgica",
		"es-CL": "Bélgica",
		"es-CO": "Bélgica",
		"es-CR": "Bélgica",
		"es-CU": "Bélgica",
		"es-DO": "Bélgica",
		"es-EC": "Bélgica",
		"es-GT": "Bélgica",
		"es-HN": "Bélgica",
		"es-MX": "Bélgica",
		"es-NI": "Bélgica",
		"es-PA": "Bélgica",
		"es-PE": "Bélgica",
		"es-PR": "Bélgica",
		"es-PY": "Bélgica",
		"es-SV": "Bélgica",
		"es-US": "Bélgica",
		"es-UY": "Bélgica",
		"es-VE": "Bélgica",
		"fr-FR": "Belgique",
		"fr-BE": "Belgique",
		"fr-CH": "Belgique",
		"fr-LU": "Belgique",
		"fr-MC": "Belgique",
		"fr-AD": "Belgique",
		"fr-CA": "Belgique",
		"it-IT": "Belgio",
		"it-CH": "Belgio",
		"it-SM": "Belgio",
		"it-VA": "Belgio",
		"de-DE": "Belgien",
		"de-AT": "Belgien",
		"de-CH": "Belgien",
		"de-BE": "Belgien",
		"de-LI": "Belgien",
		"de-LU": "Belgien",
		"nl-NL": "België",
		"nl-BE": "België",
		"sv-SE": "Belgien",
		"sv-FI": "Belgien",
		"da-DK": "Belgien",
		"nb-NO": "Belgia",
		"nn-NO": "Belgia",
		"fi-FI": "Belgia",
		"is-IS": "Belgía",
		"fo-FO": "Belgia",
		"et-EE": "Belgia",
		"lv-LV": "Beļģija",
		"lt-LT": "Belgija",
		"pl-PL": "Belgia",
		"cs-CZ": "Belgie",
		"sk-SK": "Belgicko",
		"sl-SI": "Belgija",
		"hr-HR": "Belgija",
		"bs-BA": "Belgija",
		"sr-RS": "Белгија",
		"sr-BA": "Белгија",
		"sr-ME": "Belgija",
		"mk-MK": "Белгија",
		"bg-BG": "Белгия",
		"be-BY": "Бельгія",
		"uk-UA": "Бельгія",
		"ru-RU": "Бельгия",
		"el-GR": "Βέλγιο",
		"el-CY": "Βέλγιο",
		"ro-RO": "Belgia",
		"ro-MD": "Belgia",
		"hu-HU": "Belgium",
		"sq-AL": "Belgjikë",
		"sq-XK": "Belgjikë",
		"mt-MT": "il-Belġju",
		"ga-IE": "an Bheilg",
		"cy-GB": "Gwlad Belg",
		"gd-GB": "A’ Bheilg",
		"lb-LU": "Belsch",
		"ca-ES": "Bèlgica",
		"ca-AD": "Bèlgica",
		"ca-FR": "Bèlgica",
		"ca-IT": "Bèlgica",
		"eu-ES": "Belgika",
		"eu-FR": "Belgika",
		"gl-ES": "Bélxica",
		"tr-TR": "Belçika",
		"tr-CY": "Belçika"
	},
	"callingCode": "32",
	"phoneMasks": [
		{
			"mask": "# ### ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[239]|4[23]"
			]
		},
		{
			"mask": "## ## ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[15-8]"
			]
		},
		{
			"mask": "### ## ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"(?:80|9)0"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"4"
			]
		}
	]
} satisfies Country;
