import type { Country } from './types.js';

export const BEL = {
	"code": "BEL",
	"labels": {
		"pt-BR": "Bélgica",
		"pt-PT": "Bélgica",
		"es-ES": "Bélgica",
		"es-419": "Bélgica",
		"es-AR": "Bélgica",
		"es-BO": "Bélgica",
		"es-BR": "Bélgica",
		"es-BZ": "Bélgica",
		"es-CL": "Bélgica",
		"es-CO": "Bélgica",
		"es-CR": "Bélgica",
		"es-CU": "Bélgica",
		"es-DO": "Bélgica",
		"es-EC": "Bélgica",
		"es-GT": "Bélgica",
		"es-HN": "Bélgica",
		"es-MX": "Bélgica",
		"es-NI": "Bélgica",
		"es-PA": "Bélgica",
		"es-PE": "Bélgica",
		"es-PR": "Bélgica",
		"es-PY": "Bélgica",
		"es-SV": "Bélgica",
		"es-US": "Bélgica",
		"es-UY": "Bélgica",
		"es-VE": "Bélgica",
		"en-US": "Belgium",
		"fr-FR": "Belgique",
		"fr-BE": "Belgique",
		"fr-CA": "Belgique",
		"fr-CH": "Belgique",
		"fr-LU": "Belgique",
		"fr-MC": "Belgique",
		"it-IT": "Belgio",
		"it-CH": "Belgio",
		"it-SM": "Belgio",
		"it-VA": "Belgio",
		"de-DE": "Belgien",
		"de-AT": "Belgien",
		"de-CH": "Belgien",
		"de-BE": "Belgien",
		"de-LI": "Belgien",
		"de-LU": "Belgien"
	}
} satisfies Country;
