import type { Country } from './types.js';

export const BEN = {
	"code": "BEN",
	"labels": {
		"pt-BR": "Benin",
		"pt-PT": "Benim",
		"es-ES": "Benín",
		"es-419": "Benín",
		"es-AR": "Benín",
		"es-BO": "Benín",
		"es-BR": "Benín",
		"es-BZ": "Benín",
		"es-CL": "Benín",
		"es-CO": "Benín",
		"es-CR": "Benín",
		"es-CU": "Benín",
		"es-DO": "Benín",
		"es-EC": "Benín",
		"es-GT": "Benín",
		"es-HN": "Benín",
		"es-MX": "Benín",
		"es-NI": "Benín",
		"es-PA": "Benín",
		"es-PE": "Benín",
		"es-PR": "Benín",
		"es-PY": "Benín",
		"es-SV": "Benín",
		"es-US": "Benín",
		"es-UY": "Benín",
		"es-VE": "Benín",
		"en-US": "Benin",
		"fr-FR": "Bénin",
		"fr-BE": "Bénin",
		"fr-CA": "Bénin",
		"fr-CH": "Bénin",
		"fr-LU": "Bénin",
		"fr-MC": "Bénin",
		"it-IT": "Benin",
		"it-CH": "Benin",
		"it-SM": "Benin",
		"it-VA": "Benin",
		"de-DE": "Benin",
		"de-AT": "Benin",
		"de-CH": "Benin",
		"de-BE": "Benin",
		"de-LI": "Benin",
		"de-LU": "Benin"
	},
	"callingCode": "229"
} satisfies Country;
