import type { Country } from './types.js';

export const BES = {
	"code": "BES",
	"labels": {
		"pt-BR": "Países Baixos Caribenhos",
		"pt-PT": "Países Baixos Caribenhos",
		"qu-PE": "Bonaire",
		"qu-BO": "Bonaire",
		"qu-EC": "Bonaire",
		"chr-US": "ᎧᎵᏈᎢᏂᎯ ᎾᏍᎩᏁᏛᎳᏂ",
		"hi-IN": "कैरिबियन नीदरलैंड",
		"bn-IN": "ক্যারিবিয়ান নেদারল্যান্ডস",
		"bn-BD": "ক্যারিবিয়ান নেদারল্যান্ডস",
		"ta-IN": "கரீபியன் நெதர்லாந்து",
		"ta-LK": "கரீபியன் நெதர்லாந்து",
		"ta-SG": "கரீபியன் நெதர்லாந்து",
		"ta-MY": "கரீபியன் நெதர்லாந்து",
		"te-IN": "కరీబియన్ నెదర్లాండ్స్",
		"mr-IN": "कॅरिबियन नेदरलँड्स",
		"gu-IN": "કેરેબિયન નેધરલેન્ડ્ઝ",
		"kn-IN": "ಕೆರೀಬಿಯನ್ ನೆದರ್‌ಲ್ಯಾಂಡ್ಸ್",
		"ml-IN": "കരീബിയൻ നെതർലാൻഡ്സ്",
		"pa-IN": "ਕੈਰੇਬੀਆਈ ਨੀਦਰਲੈਂਡ",
		"ur-IN": "کریبیائی نیدرلینڈز",
		"ur-PK": "کریبیائی نیدرلینڈز",
		"or-IN": "କାରବିୟନ୍‌ ନେଦରଲ୍ୟାଣ୍ଡ",
		"as-IN": "কেৰিবিয়ান নেদাৰলেণ্ডছ",
		"ne-IN": "क्यारिवियन नेदरल्याण्ड्स",
		"ne-NP": "क्यारिवियन नेदरल्याण्ड्स",
		"si-LK": "කැරිබියානු නෙදර්ලන්තය",
		"kok-IN": "कॅरिबियन निदरलँड",
		"ks-IN": "کیریبین نیدرلینڈس",
		"brx-IN": "केरिबियान नेदारलेण्डस",
		"mai-IN": "कैरिबियाई नीदरलैंड",
		"dz-BT": "ཀེ་རི་བི་ཡེན་ནེ་དར་ལནཌས྄",
		"ja-JP": "オランダ領カリブ",
		"ko-KR": "네덜란드령 카리브",
		"ko-KP": "네덜란드령 카리브",
		"zh-CN": "荷属加勒比区",
		"zh-Hans-CN": "荷属加勒比区",
		"zh-Hant-TW": "荷蘭加勒比區",
		"zh-TW": "荷蘭加勒比區",
		"zh-HK": "荷蘭加勒比區",
		"zh-MO": "荷蘭加勒比區",
		"zh-SG": "荷属加勒比区",
		"yue-Hant-HK": "荷蘭加勒比區",
		"yue-Hans-CN": "荷兰加勒比区",
		"mn-MN": "Карибын Нидерланд",
		"ug-CN": "كارىب دېڭىزى گوللاندىيە",
		"th-TH": "เนเธอร์แลนด์แคริบเบียน",
		"lo-LA": "ຄາຣິບບຽນ ເນເທີແລນ",
		"km-KH": "ហូឡង់ ការ៉ាប៊ីន",
		"my-MM": "ကာရစ်ဘီယံ နယ်သာလန်",
		"vi-VN": "Ca-ri-bê Hà Lan",
		"id-ID": "Belanda Karibia",
		"ms-MY": "Belanda Caribbean",
		"ms-SG": "Belanda Caribbean",
		"ms-BN": "Belanda Caribbean",
		"jv-ID": "Karibia Walanda",
		"fil-PH": "Caribbean Netherlands",
		"ceb-PH": "Caribbean Netherlands",
		"ka-GE": "კარიბის ნიდერლანდები",
		"hy-AM": "Կարիբյան Նիդեռլանդներ",
		"az-AZ": "Karib Niderlandı",
		"kk-KZ": "Бонэйр, Синт-Эстатиус және Саба",
		"ky-KG": "Кариб Нидерланддары",
		"uz-UZ": "Boneyr, Sint-Estatius va Saba",
		"tg-TJ": "Кариби Нидерланд",
		"tk-TM": "Karib Niderlandlary",
		"fa-IR": "جزایر کارائیب هلند",
		"fa-AF": "جزایر کارائیب هلند",
		"ps-AF": "کیریبین هالینډ",
		"ps-PK": "کیریبین هالینډ",
		"he-IL": "האיים הקריביים ההולנדיים",
		"ar-SA": "هولندا الكاريبية",
		"ar-AE": "هولندا الكاريبية",
		"ar-QA": "هولندا الكاريبية",
		"ar-BH": "هولندا الكاريبية",
		"ar-KW": "هولندا الكاريبية",
		"ar-OM": "هولندا الكاريبية",
		"ar-YE": "هولندا الكاريبية",
		"ar-IQ": "هولندا الكاريبية",
		"ar-JO": "هولندا الكاريبية",
		"ar-LB": "هولندا الكاريبية",
		"ar-SY": "هولندا الكاريبية",
		"ar-PS": "هولندا الكاريبية",
		"en-US": "Caribbean Netherlands",
		"en-GB": "Caribbean Netherlands",
		"en-IE": "Caribbean Netherlands",
		"en-MT": "Caribbean Netherlands",
		"en-GI": "Caribbean Netherlands",
		"en-CY": "Caribbean Netherlands",
		"en-JE": "Caribbean Netherlands",
		"en-GG": "Caribbean Netherlands",
		"en-IM": "Caribbean Netherlands",
		"en-CA": "Caribbean Netherlands",
		"en-AU": "Caribbean Netherlands",
		"en-NZ": "Caribbean Netherlands",
		"en-ZA": "Caribbean Netherlands",
		"en-IN": "Caribbean Netherlands",
		"en-SG": "Caribbean Netherlands",
		"pt-AO": "Países Baixos Caribenhos",
		"pt-MZ": "Países Baixos Caribenhos",
		"pt-CV": "Países Baixos Caribenhos",
		"pt-GW": "Países Baixos Caribenhos",
		"pt-ST": "Países Baixos Caribenhos",
		"pt-TL": "Países Baixos Caribenhos",
		"pt-MO": "Países Baixos Caribenhos",
		"es-ES": "Caribe neerlandés",
		"es-419": "Caribe neerlandés",
		"es-AD": "Caribe neerlandés",
		"es-GI": "Caribe neerlandés",
		"es-AR": "Caribe neerlandés",
		"es-BO": "Caribe neerlandés",
		"es-BR": "Caribe neerlandés",
		"es-BZ": "Caribe neerlandés",
		"es-CL": "Caribe neerlandés",
		"es-CO": "Caribe neerlandés",
		"es-CR": "Caribe neerlandés",
		"es-CU": "Caribe neerlandés",
		"es-DO": "Caribe neerlandés",
		"es-EC": "Caribe neerlandés",
		"es-GT": "Caribe neerlandés",
		"es-HN": "Caribe neerlandés",
		"es-MX": "Caribe neerlandés",
		"es-NI": "Caribe neerlandés",
		"es-PA": "Caribe neerlandés",
		"es-PE": "Caribe neerlandés",
		"es-PR": "Caribe neerlandés",
		"es-PY": "Caribe neerlandés",
		"es-SV": "Caribe neerlandés",
		"es-US": "Caribe neerlandés",
		"es-UY": "Caribe neerlandés",
		"es-VE": "Caribe neerlandés",
		"fr-FR": "Pays-Bas caribéens",
		"fr-BE": "Pays-Bas caribéens",
		"fr-CH": "Pays-Bas caribéens",
		"fr-LU": "Pays-Bas caribéens",
		"fr-MC": "Pays-Bas caribéens",
		"fr-AD": "Pays-Bas caribéens",
		"fr-CA": "Pays-Bas caribéens",
		"it-IT": "Caraibi Olandesi",
		"it-CH": "Caraibi Olandesi",
		"it-SM": "Caraibi Olandesi",
		"it-VA": "Caraibi Olandesi",
		"de-DE": "Karibische Niederlande",
		"de-AT": "Karibische Niederlande",
		"de-CH": "Karibische Niederlande",
		"de-BE": "Karibische Niederlande",
		"de-LI": "Karibische Niederlande",
		"de-LU": "Karibische Niederlande",
		"nl-NL": "Caribisch Nederland",
		"nl-BE": "Caribisch Nederland",
		"sv-SE": "Karibiska Nederländerna",
		"sv-FI": "Karibiska Nederländerna",
		"da-DK": "De tidligere Nederlandske Antiller",
		"nb-NO": "Karibisk Nederland",
		"nn-NO": "Karibisk Nederland",
		"fi-FI": "Karibian Alankomaat",
		"is-IS": "Karíbahafshluti Hollands",
		"fo-FO": "Niðurlonds Karibia",
		"et-EE": "Kariibi Madalmaad",
		"lv-LV": "Nīderlandes Karību salas",
		"lt-LT": "Karibų Nyderlandai",
		"pl-PL": "Niderlandy Karaibskie",
		"cs-CZ": "Karibské Nizozemsko",
		"sk-SK": "Karibské Holandsko",
		"sl-SI": "Nizozemski Karibi",
		"hr-HR": "Karipski otoci Nizozemske",
		"bs-BA": "Karipska Holandija",
		"sr-RS": "Карипска Холандија",
		"sr-BA": "Карипска Холандија",
		"sr-ME": "Karipska Holandija",
		"mk-MK": "Карипска Холандија",
		"bg-BG": "Карибска Нидерландия",
		"be-BY": "Карыбскія Нідэрланды",
		"uk-UA": "Карибські Нідерланди",
		"ru-RU": "Бонэйр, Синт-Эстатиус и Саба",
		"el-GR": "Ολλανδία Καραϊβικής",
		"el-CY": "Ολλανδία Καραϊβικής",
		"ro-RO": "Insulele Caraibe Olandeze",
		"ro-MD": "Insulele Caraibe Olandeze",
		"hu-HU": "Holland Karib-térség",
		"sq-AL": "Karaibet holandeze",
		"sq-XK": "Karaibet holandeze",
		"mt-MT": "in-Netherlands tal-Karibew",
		"ga-IE": "an Ísiltír Chairibeach",
		"cy-GB": "Antilles yr Iseldiroedd",
		"gd-GB": "Na Tìrean Ìsle Caraibeach",
		"lb-LU": "Karibescht Holland",
		"ca-ES": "Carib Neerlandès",
		"ca-AD": "Carib Neerlandès",
		"ca-FR": "Carib Neerlandès",
		"ca-IT": "Carib Neerlandès",
		"eu-ES": "Karibeko Herbehereak",
		"eu-FR": "Karibeko Herbehereak",
		"gl-ES": "Caribe Neerlandés",
		"tr-TR": "Karayip Hollandası",
		"tr-CY": "Karayip Hollandası"
	},
	"callingCode": "599",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		}
	]
} satisfies Country;
