import type { Country } from './types.js';

export const BFA = {
	"code": "BFA",
	"labels": {
		"pt-BR": "Burquina Faso",
		"pt-PT": "Burquina Faso",
		"es-ES": "Burkina Faso",
		"es-419": "Burkina Faso",
		"es-AR": "Burkina Faso",
		"es-BO": "Burkina Faso",
		"es-BR": "Burkina Faso",
		"es-BZ": "Burkina Faso",
		"es-CL": "Burkina Faso",
		"es-CO": "Burkina Faso",
		"es-CR": "Burkina Faso",
		"es-CU": "Burkina Faso",
		"es-DO": "Burkina Faso",
		"es-EC": "Burkina Faso",
		"es-GT": "Burkina Faso",
		"es-HN": "Burkina Faso",
		"es-MX": "Burkina Faso",
		"es-NI": "Burkina Faso",
		"es-PA": "Burkina Faso",
		"es-PE": "Burkina Faso",
		"es-PR": "Burkina Faso",
		"es-PY": "Burkina Faso",
		"es-SV": "Burkina Faso",
		"es-US": "Burkina Faso",
		"es-UY": "Burkina Faso",
		"es-VE": "Burkina Faso",
		"en-US": "Burkina Faso",
		"fr-FR": "Burkina Faso",
		"fr-BE": "Burkina Faso",
		"fr-CA": "Burkina Faso",
		"fr-CH": "Burkina Faso",
		"fr-LU": "Burkina Faso",
		"fr-MC": "Burkina Faso",
		"it-IT": "Burkina Faso",
		"it-CH": "Burkina Faso",
		"it-SM": "Burkina Faso",
		"it-VA": "Burkina Faso",
		"de-DE": "Burkina Faso",
		"de-AT": "Burkina Faso",
		"de-CH": "Burkina Faso",
		"de-BE": "Burkina Faso",
		"de-LI": "Burkina Faso",
		"de-LU": "Burkina Faso"
	},
	"callingCode": "226"
} satisfies Country;
