import type { Country } from './types.js';

export const BGD = {
	"code": "BGD",
	"labels": {
		"pt-BR": "Bangladesh",
		"pt-PT": "Bangladeche",
		"es-ES": "Bangladés",
		"es-419": "Bangladés",
		"es-AR": "Bangladés",
		"es-BO": "Bangladés",
		"es-BR": "Bangladés",
		"es-BZ": "Bangladés",
		"es-CL": "Bangladés",
		"es-CO": "Bangladés",
		"es-CR": "Bangladés",
		"es-CU": "Bangladés",
		"es-DO": "Bangladés",
		"es-EC": "Bangladés",
		"es-GT": "Bangladés",
		"es-HN": "Bangladés",
		"es-MX": "Bangladés",
		"es-NI": "Bangladés",
		"es-PA": "Bangladés",
		"es-PE": "Bangladés",
		"es-PR": "Bangladés",
		"es-PY": "Bangladés",
		"es-SV": "Bangladés",
		"es-US": "Bangladés",
		"es-UY": "Bangladés",
		"es-VE": "Bangladés",
		"en-US": "Bangladesh",
		"fr-FR": "Bangladesh",
		"fr-BE": "Bangladesh",
		"fr-CA": "Bangladesh",
		"fr-CH": "Bangladesh",
		"fr-LU": "Bangladesh",
		"fr-MC": "Bangladesh",
		"it-IT": "Bangladesh",
		"it-CH": "Bangladesh",
		"it-SM": "Bangladesh",
		"it-VA": "Bangladesh",
		"de-DE": "Bangladesch",
		"de-AT": "Bangladesch",
		"de-CH": "Bangladesch",
		"de-BE": "Bangladesch",
		"de-LI": "Bangladesch",
		"de-LU": "Bangladesch"
	},
	"callingCode": "880"
} satisfies Country;
