import type { Country } from './types.js';

export const BGR = {
	"code": "BGR",
	"labels": {
		"pt-BR": "Bulgária",
		"pt-PT": "Bulgária",
		"qu-PE": "Bulgaria",
		"qu-BO": "Bulgaria",
		"qu-EC": "Bulgaria",
		"chr-US": "ᏊᎵᎨᎵᎠ",
		"hi-IN": "बुल्गारिया",
		"bn-IN": "বুলগেরিয়া",
		"bn-BD": "বুলগেরিয়া",
		"ta-IN": "பல்கேரியா",
		"ta-LK": "பல்கேரியா",
		"ta-SG": "பல்கேரியா",
		"ta-MY": "பல்கேரியா",
		"te-IN": "బల్గేరియా",
		"mr-IN": "बल्गेरिया",
		"gu-IN": "બલ્ગેરિયા",
		"kn-IN": "ಬಲ್ಗೇರಿಯಾ",
		"ml-IN": "ബൾഗേറിയ",
		"pa-IN": "ਬੁਲਗਾਰੀਆ",
		"ur-IN": "بلغاریہ",
		"ur-PK": "بلغاریہ",
		"or-IN": "ବୁଲଗେରିଆ",
		"as-IN": "বুলগেৰিয়া",
		"ne-IN": "बुल्गेरिया",
		"ne-NP": "बुल्गेरिया",
		"si-LK": "බල්ගේරියාව",
		"kok-IN": "बल्गेरीया",
		"ks-IN": "بَلجیرِیا",
		"brx-IN": "बुल्गारिया",
		"mai-IN": "बुल्गारिया",
		"dz-BT": "བུལ་ག་རི་ཡ",
		"ja-JP": "ブルガリア",
		"ko-KR": "불가리아",
		"ko-KP": "불가리아",
		"zh-CN": "保加利亚",
		"zh-Hans-CN": "保加利亚",
		"zh-Hant-TW": "保加利亞",
		"zh-TW": "保加利亞",
		"zh-HK": "保加利亞",
		"zh-MO": "保加利亞",
		"zh-SG": "保加利亚",
		"yue-Hant-HK": "保加利亞",
		"yue-Hans-CN": "保加利亚",
		"mn-MN": "Болгар",
		"ug-CN": "بۇلغارىيە",
		"th-TH": "บัลแกเรีย",
		"lo-LA": "ບັງກາເຣຍ",
		"km-KH": "ប៊ុលហ្ការី",
		"my-MM": "ဘူလ်ဂေးရီးယား",
		"vi-VN": "Bulgaria",
		"id-ID": "Bulgaria",
		"ms-MY": "Bulgaria",
		"ms-SG": "Bulgaria",
		"ms-BN": "Bulgaria",
		"jv-ID": "Bulgari",
		"fil-PH": "Bulgaria",
		"ceb-PH": "Bulgaria",
		"ka-GE": "ბულგარეთი",
		"hy-AM": "Բուլղարիա",
		"az-AZ": "Bolqarıstan",
		"az-Cyrl-AZ": "Болгарыстан",
		"kk-KZ": "Болгария",
		"ky-KG": "Болгария",
		"uz-UZ": "Bolgariya",
		"tg-TJ": "Булғория",
		"tk-TM": "Bolgariýa",
		"fa-IR": "بلغارستان",
		"fa-AF": "بلغاریا",
		"ps-AF": "بلغاریه",
		"ps-PK": "بلغاریه",
		"he-IL": "בולגריה",
		"ar-SA": "بلغاريا",
		"ar-AE": "بلغاريا",
		"ar-QA": "بلغاريا",
		"ar-BH": "بلغاريا",
		"ar-KW": "بلغاريا",
		"ar-OM": "بلغاريا",
		"ar-YE": "بلغاريا",
		"ar-IQ": "بلغاريا",
		"ar-JO": "بلغاريا",
		"ar-LB": "بلغاريا",
		"ar-SY": "بلغاريا",
		"ar-PS": "بلغاريا",
		"en-US": "Bulgaria",
		"en-GB": "Bulgaria",
		"en-IE": "Bulgaria",
		"en-MT": "Bulgaria",
		"en-GI": "Bulgaria",
		"en-CY": "Bulgaria",
		"en-JE": "Bulgaria",
		"en-GG": "Bulgaria",
		"en-IM": "Bulgaria",
		"en-CA": "Bulgaria",
		"en-AU": "Bulgaria",
		"en-NZ": "Bulgaria",
		"en-ZA": "Bulgaria",
		"en-IN": "Bulgaria",
		"en-SG": "Bulgaria",
		"pt-AO": "Bulgária",
		"pt-MZ": "Bulgária",
		"pt-CV": "Bulgária",
		"pt-GW": "Bulgária",
		"pt-ST": "Bulgária",
		"pt-TL": "Bulgária",
		"pt-MO": "Bulgária",
		"es-ES": "Bulgaria",
		"es-419": "Bulgaria",
		"es-AD": "Bulgaria",
		"es-GI": "Bulgaria",
		"es-AR": "Bulgaria",
		"es-BO": "Bulgaria",
		"es-BR": "Bulgaria",
		"es-BZ": "Bulgaria",
		"es-CL": "Bulgaria",
		"es-CO": "Bulgaria",
		"es-CR": "Bulgaria",
		"es-CU": "Bulgaria",
		"es-DO": "Bulgaria",
		"es-EC": "Bulgaria",
		"es-GT": "Bulgaria",
		"es-HN": "Bulgaria",
		"es-MX": "Bulgaria",
		"es-NI": "Bulgaria",
		"es-PA": "Bulgaria",
		"es-PE": "Bulgaria",
		"es-PR": "Bulgaria",
		"es-PY": "Bulgaria",
		"es-SV": "Bulgaria",
		"es-US": "Bulgaria",
		"es-UY": "Bulgaria",
		"es-VE": "Bulgaria",
		"fr-FR": "Bulgarie",
		"fr-BE": "Bulgarie",
		"fr-CH": "Bulgarie",
		"fr-LU": "Bulgarie",
		"fr-MC": "Bulgarie",
		"fr-AD": "Bulgarie",
		"fr-CA": "Bulgarie",
		"it-IT": "Bulgaria",
		"it-CH": "Bulgaria",
		"it-SM": "Bulgaria",
		"it-VA": "Bulgaria",
		"de-DE": "Bulgarien",
		"de-AT": "Bulgarien",
		"de-CH": "Bulgarien",
		"de-BE": "Bulgarien",
		"de-LI": "Bulgarien",
		"de-LU": "Bulgarien",
		"nl-NL": "Bulgarije",
		"nl-BE": "Bulgarije",
		"sv-SE": "Bulgarien",
		"sv-FI": "Bulgarien",
		"da-DK": "Bulgarien",
		"nb-NO": "Bulgaria",
		"nn-NO": "Bulgaria",
		"fi-FI": "Bulgaria",
		"is-IS": "Búlgaría",
		"fo-FO": "Bulgaria",
		"et-EE": "Bulgaaria",
		"lv-LV": "Bulgārija",
		"lt-LT": "Bulgarija",
		"pl-PL": "Bułgaria",
		"cs-CZ": "Bulharsko",
		"sk-SK": "Bulharsko",
		"sl-SI": "Bolgarija",
		"hr-HR": "Bugarska",
		"bs-BA": "Bugarska",
		"sr-RS": "Бугарска",
		"sr-BA": "Бугарска",
		"sr-ME": "Bugarska",
		"mk-MK": "Бугарија",
		"bg-BG": "България",
		"be-BY": "Балгарыя",
		"uk-UA": "Болгарія",
		"ru-RU": "Болгария",
		"el-GR": "Βουλγαρία",
		"el-CY": "Βουλγαρία",
		"ro-RO": "Bulgaria",
		"ro-MD": "Bulgaria",
		"hu-HU": "Bulgária",
		"sq-AL": "Bullgari",
		"sq-XK": "Bullgari",
		"mt-MT": "il-Bulgarija",
		"ga-IE": "an Bhulgáir",
		"cy-GB": "Bwlgaria",
		"gd-GB": "A’ Bhulgair",
		"lb-LU": "Bulgarien",
		"ca-ES": "Bulgària",
		"ca-AD": "Bulgària",
		"ca-FR": "Bulgària",
		"ca-IT": "Bulgària",
		"eu-ES": "Bulgaria",
		"eu-FR": "Bulgaria",
		"gl-ES": "Bulgaria",
		"tr-TR": "Bulgaristan",
		"tr-CY": "Bulgaristan"
	},
	"callingCode": "359",
	"phoneMasks": [
		{
			"mask": "# # ## ##",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"43[1-6]|70[1-9]"
			]
		},
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[356]|4[124-7]|7[1-9]|8[1-6]|9[1-7]"
			]
		},
		{
			"mask": "### ## ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"(?:70|8)0"
			]
		},
		{
			"mask": "### ### ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"43[1-7]|7"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[48]|9[08]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"9"
			]
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12
		}
	]
} satisfies Country;
