import type { Country } from './types.js';

export const BHR = {
	"code": "BHR",
	"labels": {
		"pt-BR": "Barein",
		"pt-PT": "Barém",
		"es-ES": "Baréin",
		"es-419": "Baréin",
		"es-AR": "Baréin",
		"es-BO": "Baréin",
		"es-BR": "Baréin",
		"es-BZ": "Baréin",
		"es-CL": "Baréin",
		"es-CO": "Baréin",
		"es-CR": "Baréin",
		"es-CU": "Baréin",
		"es-DO": "Baréin",
		"es-EC": "Baréin",
		"es-GT": "Baréin",
		"es-HN": "Baréin",
		"es-MX": "Baréin",
		"es-NI": "Baréin",
		"es-PA": "Baréin",
		"es-PE": "Baréin",
		"es-PR": "Baréin",
		"es-PY": "Baréin",
		"es-SV": "Baréin",
		"es-US": "Baréin",
		"es-UY": "Baréin",
		"es-VE": "Baréin",
		"en-US": "Bahrain",
		"fr-FR": "Bahreïn",
		"fr-BE": "Bahreïn",
		"fr-CA": "Bahreïn",
		"fr-CH": "Bahreïn",
		"fr-LU": "Bahreïn",
		"fr-MC": "Bahreïn",
		"it-IT": "Bahrein",
		"it-CH": "Bahrein",
		"it-SM": "Bahrein",
		"it-VA": "Bahrein",
		"de-DE": "Bahrain",
		"de-AT": "Bahrain",
		"de-CH": "Bahrain",
		"de-BE": "Bahrain",
		"de-LI": "Bahrain",
		"de-LU": "Bahrain"
	},
	"callingCode": "973"
} satisfies Country;
