import type { Country } from './types.js';

export const BHS = {
	"code": "BHS",
	"labels": {
		"pt-BR": "Bahamas",
		"pt-PT": "Baamas",
		"qu-PE": "Bahamas",
		"qu-BO": "Bahamas",
		"qu-EC": "Bahamas",
		"chr-US": "ᎾᏍᎩ ᏆᎭᎹᏍ",
		"hi-IN": "बहामास",
		"bn-IN": "বাহামা দ্বীপপুঞ্জ",
		"bn-BD": "বাহামা দ্বীপপুঞ্জ",
		"ta-IN": "பஹாமாஸ்",
		"ta-LK": "பஹாமாஸ்",
		"ta-SG": "பஹாமாஸ்",
		"ta-MY": "பஹாமாஸ்",
		"te-IN": "బహామాస్",
		"mr-IN": "बहामाज",
		"gu-IN": "બહામાસ",
		"kn-IN": "ಬಹಾಮಾಸ್",
		"ml-IN": "ബഹാമാസ്",
		"pa-IN": "ਬਹਾਮਾਸ",
		"ur-IN": "بہاماس",
		"ur-PK": "بہاماس",
		"or-IN": "ବାହାମାସ୍",
		"as-IN": "বাহামাছ",
		"ne-IN": "बहामास",
		"ne-NP": "बहामास",
		"si-LK": "බහමාස්",
		"kok-IN": "बहामास",
		"ks-IN": "بَہامَس",
		"brx-IN": "बाहामास",
		"mai-IN": "बहामास",
		"dz-BT": "བྷ་ཧ་མས྄",
		"ja-JP": "バハマ",
		"ko-KR": "바하마",
		"ko-KP": "바하마",
		"zh-CN": "巴哈马",
		"zh-Hans-CN": "巴哈马",
		"zh-Hant-TW": "巴哈馬",
		"zh-TW": "巴哈馬",
		"zh-HK": "巴哈馬",
		"zh-MO": "巴哈馬",
		"zh-SG": "巴哈马",
		"yue-Hant-HK": "巴哈馬",
		"yue-Hans-CN": "巴哈马",
		"mn-MN": "Багамын арлууд",
		"ug-CN": "باھاما",
		"th-TH": "บาฮามาส",
		"lo-LA": "ບາຮາມາສ",
		"km-KH": "បាហាម៉ា",
		"my-MM": "ဘဟားမား",
		"vi-VN": "Bahamas",
		"id-ID": "Bahama",
		"ms-MY": "Bahamas",
		"ms-SG": "Bahamas",
		"ms-BN": "Bahamas",
		"jv-ID": "Bahama",
		"fil-PH": "Bahamas",
		"ceb-PH": "Bahamas",
		"ka-GE": "ბაჰამის კუნძულები",
		"hy-AM": "Բահամյան կղզիներ",
		"az-AZ": "Baham adaları",
		"az-Cyrl-AZ": "Баһам адалары",
		"kk-KZ": "Багам аралдары",
		"ky-KG": "Багама аралдары",
		"uz-UZ": "Bagama orollari",
		"tg-TJ": "Багам",
		"tk-TM": "Bagama adalary",
		"fa-IR": "باهاما",
		"fa-AF": "بهاماس",
		"ps-AF": "باهماس",
		"ps-PK": "باهماس",
		"he-IL": "איי בהאמה",
		"ar-SA": "جزر البهاما",
		"ar-AE": "جزر البهاما",
		"ar-QA": "جزر البهاما",
		"ar-BH": "جزر البهاما",
		"ar-KW": "جزر البهاما",
		"ar-OM": "جزر البهاما",
		"ar-YE": "جزر البهاما",
		"ar-IQ": "جزر البهاما",
		"ar-JO": "جزر البهاما",
		"ar-LB": "جزر البهاما",
		"ar-SY": "جزر البهاما",
		"ar-PS": "جزر البهاما",
		"en-US": "Bahamas",
		"en-GB": "Bahamas",
		"en-IE": "Bahamas",
		"en-MT": "Bahamas",
		"en-GI": "Bahamas",
		"en-CY": "Bahamas",
		"en-JE": "Bahamas",
		"en-GG": "Bahamas",
		"en-IM": "Bahamas",
		"en-CA": "Bahamas",
		"en-AU": "Bahamas",
		"en-NZ": "Bahamas",
		"en-ZA": "Bahamas",
		"en-IN": "Bahamas",
		"en-SG": "Bahamas",
		"pt-AO": "Baamas",
		"pt-MZ": "Baamas",
		"pt-CV": "Baamas",
		"pt-GW": "Baamas",
		"pt-ST": "Baamas",
		"pt-TL": "Baamas",
		"pt-MO": "Baamas",
		"es-ES": "Bahamas",
		"es-419": "Bahamas",
		"es-AD": "Bahamas",
		"es-GI": "Bahamas",
		"es-AR": "Bahamas",
		"es-BO": "Bahamas",
		"es-BR": "Bahamas",
		"es-BZ": "Bahamas",
		"es-CL": "Bahamas",
		"es-CO": "Bahamas",
		"es-CR": "Bahamas",
		"es-CU": "Bahamas",
		"es-DO": "Bahamas",
		"es-EC": "Bahamas",
		"es-GT": "Bahamas",
		"es-HN": "Bahamas",
		"es-MX": "Bahamas",
		"es-NI": "Bahamas",
		"es-PA": "Bahamas",
		"es-PE": "Bahamas",
		"es-PR": "Bahamas",
		"es-PY": "Bahamas",
		"es-SV": "Bahamas",
		"es-US": "Bahamas",
		"es-UY": "Bahamas",
		"es-VE": "Bahamas",
		"fr-FR": "Bahamas",
		"fr-BE": "Bahamas",
		"fr-CH": "Bahamas",
		"fr-LU": "Bahamas",
		"fr-MC": "Bahamas",
		"fr-AD": "Bahamas",
		"fr-CA": "Bahamas",
		"it-IT": "Bahamas",
		"it-CH": "Bahamas",
		"it-SM": "Bahamas",
		"it-VA": "Bahamas",
		"de-DE": "Bahamas",
		"de-AT": "Bahamas",
		"de-CH": "Bahamas",
		"de-BE": "Bahamas",
		"de-LI": "Bahamas",
		"de-LU": "Bahamas",
		"nl-NL": "Bahama’s",
		"nl-BE": "Bahama’s",
		"sv-SE": "Bahamas",
		"sv-FI": "Bahamas",
		"da-DK": "Bahamas",
		"nb-NO": "Bahamas",
		"nn-NO": "Bahamas",
		"fi-FI": "Bahama",
		"is-IS": "Bahamaeyjar",
		"fo-FO": "Bahamaoyggjar",
		"et-EE": "Bahama",
		"lv-LV": "Bahamu salas",
		"lt-LT": "Bahamos",
		"pl-PL": "Bahamy",
		"cs-CZ": "Bahamy",
		"sk-SK": "Bahamy",
		"sl-SI": "Bahami",
		"hr-HR": "Bahami",
		"bs-BA": "Bahami",
		"sr-RS": "Бахами",
		"sr-BA": "Бахами",
		"sr-ME": "Bahami",
		"mk-MK": "Бахами",
		"bg-BG": "Бахамски острови",
		"be-BY": "Багамскія астравы",
		"uk-UA": "Багамські Острови",
		"ru-RU": "Багамы",
		"el-GR": "Μπαχάμες",
		"el-CY": "Μπαχάμες",
		"ro-RO": "Bahamas",
		"ro-MD": "Bahamas",
		"hu-HU": "Bahama-szigetek",
		"sq-AL": "Bahama",
		"sq-XK": "Bahama",
		"mt-MT": "il-Bahamas",
		"ga-IE": "na Bahámaí",
		"cy-GB": "Y Bahamas",
		"gd-GB": "Na h-Eileanan Bhathama",
		"lb-LU": "Bahamas",
		"ca-ES": "Bahames",
		"ca-AD": "Bahames",
		"ca-FR": "Bahames",
		"ca-IT": "Bahames",
		"eu-ES": "Bahamak",
		"eu-FR": "Bahamak",
		"gl-ES": "Bahamas",
		"tr-TR": "Bahamalar",
		"tr-CY": "Bahamalar"
	},
	"callingCode": "1242",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
