import type { Country } from './types.js';

export const BHS = {
	"code": "BHS",
	"labels": {
		"pt-BR": "Bahamas",
		"pt-PT": "Baamas",
		"es-ES": "Bahamas",
		"es-419": "Bahamas",
		"es-AR": "Bahamas",
		"es-BO": "Bahamas",
		"es-BR": "Bahamas",
		"es-BZ": "Bahamas",
		"es-CL": "Bahamas",
		"es-CO": "Bahamas",
		"es-CR": "Bahamas",
		"es-CU": "Bahamas",
		"es-DO": "Bahamas",
		"es-EC": "Bahamas",
		"es-GT": "Bahamas",
		"es-HN": "Bahamas",
		"es-MX": "Bahamas",
		"es-NI": "Bahamas",
		"es-PA": "Bahamas",
		"es-PE": "Bahamas",
		"es-PR": "Bahamas",
		"es-PY": "Bahamas",
		"es-SV": "Bahamas",
		"es-US": "Bahamas",
		"es-UY": "Bahamas",
		"es-VE": "Bahamas",
		"en-US": "Bahamas",
		"fr-FR": "Bahamas",
		"fr-BE": "Bahamas",
		"fr-CA": "Bahamas",
		"fr-CH": "Bahamas",
		"fr-LU": "Bahamas",
		"fr-MC": "Bahamas",
		"it-IT": "Bahamas",
		"it-CH": "Bahamas",
		"it-SM": "Bahamas",
		"it-VA": "Bahamas",
		"de-DE": "Bahamas",
		"de-AT": "Bahamas",
		"de-CH": "Bahamas",
		"de-BE": "Bahamas",
		"de-LI": "Bahamas",
		"de-LU": "Bahamas"
	},
	"callingCode": "1242"
} satisfies Country;
