import type { Country } from './types.js';

export const BLM = {
	"code": "BLM",
	"labels": {
		"pt-BR": "São Bartolomeu",
		"pt-PT": "São Bartolomeu",
		"es-ES": "San Bartolomé",
		"es-419": "San Bartolomé",
		"es-AR": "San Bartolomé",
		"es-BO": "San Bartolomé",
		"es-BR": "San Bartolomé",
		"es-BZ": "San Bartolomé",
		"es-CL": "San Bartolomé",
		"es-CO": "San Bartolomé",
		"es-CR": "San Bartolomé",
		"es-CU": "San Bartolomé",
		"es-DO": "San Bartolomé",
		"es-EC": "San Bartolomé",
		"es-GT": "San Bartolomé",
		"es-HN": "San Bartolomé",
		"es-MX": "San Bartolomé",
		"es-NI": "San Bartolomé",
		"es-PA": "San Bartolomé",
		"es-PE": "San Bartolomé",
		"es-PR": "San Bartolomé",
		"es-PY": "San Bartolomé",
		"es-SV": "San Bartolomé",
		"es-US": "San Bartolomé",
		"es-UY": "San Bartolomé",
		"es-VE": "San Bartolomé",
		"en-US": "St. Barthélemy",
		"fr-FR": "Saint-Barthélemy",
		"fr-BE": "Saint-Barthélemy",
		"fr-CA": "Saint-Barthélemy",
		"fr-CH": "Saint-Barthélemy",
		"fr-LU": "Saint-Barthélemy",
		"fr-MC": "Saint-Barthélemy",
		"it-IT": "Saint-Barthélemy",
		"it-CH": "Saint-Barthélemy",
		"it-SM": "Saint-Barthélemy",
		"it-VA": "Saint-Barthélemy",
		"de-DE": "St. Barthélemy",
		"de-AT": "St. Barthélemy",
		"de-CH": "St. Barthélemy",
		"de-BE": "St. Barthélemy",
		"de-LI": "St. Barthélemy",
		"de-LU": "St. Barthélemy"
	}
} satisfies Country;
