import type { Country } from './types.js';

export const BLR = {
	"code": "BLR",
	"labels": {
		"pt-BR": "Bielorrússia",
		"pt-PT": "Bielorrússia",
		"es-ES": "Bielorrusia",
		"es-419": "Bielorrusia",
		"es-AR": "Bielorrusia",
		"es-BO": "Bielorrusia",
		"es-BR": "Bielorrusia",
		"es-BZ": "Bielorrusia",
		"es-CL": "Bielorrusia",
		"es-CO": "Bielorrusia",
		"es-CR": "Bielorrusia",
		"es-CU": "Bielorrusia",
		"es-DO": "Bielorrusia",
		"es-EC": "Bielorrusia",
		"es-GT": "Bielorrusia",
		"es-HN": "Bielorrusia",
		"es-MX": "Bielorrusia",
		"es-NI": "Bielorrusia",
		"es-PA": "Bielorrusia",
		"es-PE": "Bielorrusia",
		"es-PR": "Bielorrusia",
		"es-PY": "Bielorrusia",
		"es-SV": "Bielorrusia",
		"es-US": "Bielorrusia",
		"es-UY": "Bielorrusia",
		"es-VE": "Bielorrusia",
		"en-US": "Belarus",
		"fr-FR": "Biélorussie",
		"fr-BE": "Biélorussie",
		"fr-CA": "Bélarus",
		"fr-CH": "Biélorussie",
		"fr-LU": "Biélorussie",
		"fr-MC": "Biélorussie",
		"it-IT": "Bielorussia",
		"it-CH": "Bielorussia",
		"it-SM": "Bielorussia",
		"it-VA": "Bielorussia",
		"de-DE": "Belarus",
		"de-AT": "Belarus",
		"de-CH": "Belarus",
		"de-BE": "Belarus",
		"de-LI": "Belarus",
		"de-LU": "Belarus"
	}
} satisfies Country;
