import type { Country } from './types.js';

export const BLR = {
	"code": "BLR",
	"labels": {
		"pt-BR": "Bielorrússia",
		"pt-PT": "Bielorrússia",
		"qu-PE": "Belarús",
		"qu-BO": "Belarús",
		"qu-EC": "Belarús",
		"chr-US": "ᏇᎳᎷᏍ",
		"hi-IN": "बेलारूस",
		"bn-IN": "বেলারুশ",
		"bn-BD": "বেলারুশ",
		"ta-IN": "பெலாரஸ்",
		"ta-LK": "பெலாரஸ்",
		"ta-SG": "பெலாரஸ்",
		"ta-MY": "பெலாரஸ்",
		"te-IN": "బెలారస్",
		"mr-IN": "बेलारूस",
		"gu-IN": "બેલારુસ",
		"kn-IN": "ಬೆಲಾರಸ್",
		"ml-IN": "ബെലറൂസ്",
		"pa-IN": "ਬੇਲਾਰੂਸ",
		"ur-IN": "بیلاروس",
		"ur-PK": "بیلاروس",
		"or-IN": "ବେଲାରୁଷ୍",
		"as-IN": "বেলাৰুছ",
		"ne-IN": "बेलारूस",
		"ne-NP": "बेलारूस",
		"si-LK": "බෙලරුස්",
		"kok-IN": "बेलारूस",
		"ks-IN": "بیلاروٗس",
		"brx-IN": "बेलारूस",
		"mai-IN": "बेलारूस",
		"dz-BT": "བེལ་ཨ་རུ་སུ",
		"ja-JP": "ベラルーシ",
		"ko-KR": "벨라루스",
		"ko-KP": "벨라루스",
		"zh-CN": "白俄罗斯",
		"zh-Hans-CN": "白俄罗斯",
		"zh-Hant-TW": "白俄羅斯",
		"zh-TW": "白俄羅斯",
		"zh-HK": "白俄羅斯",
		"zh-MO": "白俄羅斯",
		"zh-SG": "白俄罗斯",
		"yue-Hant-HK": "白俄羅斯",
		"yue-Hans-CN": "白俄罗斯",
		"mn-MN": "Беларусь",
		"ug-CN": "بېلارۇسىيە",
		"th-TH": "เบลารุส",
		"lo-LA": "ເບລາຣຸສ",
		"km-KH": "បេឡារុស",
		"my-MM": "ဘီလာရုစ်",
		"vi-VN": "Belarus",
		"id-ID": "Belarus",
		"ms-MY": "Belarus",
		"ms-SG": "Belarus",
		"ms-BN": "Belarus",
		"jv-ID": "Bélarus",
		"fil-PH": "Belarus",
		"ceb-PH": "Belarus",
		"ka-GE": "ბელარუსი",
		"hy-AM": "Բելառուս",
		"az-AZ": "Belarus",
		"az-Cyrl-AZ": "Беларус",
		"kk-KZ": "Беларусь",
		"ky-KG": "Беларусь",
		"uz-UZ": "Belarus",
		"tg-TJ": "Белорус",
		"tk-TM": "Belarus",
		"fa-IR": "بلاروس",
		"fa-AF": "بلاروس",
		"ps-AF": "بیلاروس",
		"ps-PK": "بیلاروس",
		"he-IL": "בלארוס",
		"ar-SA": "بيلاروس",
		"ar-AE": "بيلاروس",
		"ar-QA": "بيلاروس",
		"ar-BH": "بيلاروس",
		"ar-KW": "بيلاروس",
		"ar-OM": "بيلاروس",
		"ar-YE": "بيلاروس",
		"ar-IQ": "بيلاروس",
		"ar-JO": "بيلاروس",
		"ar-LB": "بيلاروس",
		"ar-SY": "بيلاروس",
		"ar-PS": "بيلاروس",
		"en-US": "Belarus",
		"en-GB": "Belarus",
		"en-IE": "Belarus",
		"en-MT": "Belarus",
		"en-GI": "Belarus",
		"en-CY": "Belarus",
		"en-JE": "Belarus",
		"en-GG": "Belarus",
		"en-IM": "Belarus",
		"en-CA": "Belarus",
		"en-AU": "Belarus",
		"en-NZ": "Belarus",
		"en-ZA": "Belarus",
		"en-IN": "Belarus",
		"en-SG": "Belarus",
		"pt-AO": "Bielorrússia",
		"pt-MZ": "Bielorrússia",
		"pt-CV": "Bielorrússia",
		"pt-GW": "Bielorrússia",
		"pt-ST": "Bielorrússia",
		"pt-TL": "Bielorrússia",
		"pt-MO": "Bielorrússia",
		"es-ES": "Bielorrusia",
		"es-419": "Bielorrusia",
		"es-AD": "Bielorrusia",
		"es-GI": "Bielorrusia",
		"es-AR": "Bielorrusia",
		"es-BO": "Bielorrusia",
		"es-BR": "Bielorrusia",
		"es-BZ": "Bielorrusia",
		"es-CL": "Bielorrusia",
		"es-CO": "Bielorrusia",
		"es-CR": "Bielorrusia",
		"es-CU": "Bielorrusia",
		"es-DO": "Bielorrusia",
		"es-EC": "Bielorrusia",
		"es-GT": "Bielorrusia",
		"es-HN": "Bielorrusia",
		"es-MX": "Bielorrusia",
		"es-NI": "Bielorrusia",
		"es-PA": "Bielorrusia",
		"es-PE": "Bielorrusia",
		"es-PR": "Bielorrusia",
		"es-PY": "Bielorrusia",
		"es-SV": "Bielorrusia",
		"es-US": "Bielorrusia",
		"es-UY": "Bielorrusia",
		"es-VE": "Bielorrusia",
		"fr-FR": "Biélorussie",
		"fr-BE": "Biélorussie",
		"fr-CH": "Biélorussie",
		"fr-LU": "Biélorussie",
		"fr-MC": "Biélorussie",
		"fr-AD": "Biélorussie",
		"fr-CA": "Bélarus",
		"it-IT": "Bielorussia",
		"it-CH": "Bielorussia",
		"it-SM": "Bielorussia",
		"it-VA": "Bielorussia",
		"de-DE": "Belarus",
		"de-AT": "Belarus",
		"de-CH": "Belarus",
		"de-BE": "Belarus",
		"de-LI": "Belarus",
		"de-LU": "Belarus",
		"nl-NL": "Belarus",
		"nl-BE": "Belarus",
		"sv-SE": "Belarus",
		"sv-FI": "Belarus",
		"da-DK": "Belarus",
		"nb-NO": "Belarus",
		"nn-NO": "Belarus",
		"fi-FI": "Valko-Venäjä",
		"is-IS": "Hvíta-Rússland",
		"fo-FO": "Hvítarussland",
		"et-EE": "Valgevene",
		"lv-LV": "Baltkrievija",
		"lt-LT": "Baltarusija",
		"pl-PL": "Białoruś",
		"cs-CZ": "Bělorusko",
		"sk-SK": "Bielorusko",
		"sl-SI": "Belorusija",
		"hr-HR": "Bjelorusija",
		"bs-BA": "Bjelorusija",
		"sr-RS": "Белорусија",
		"sr-BA": "Бјелорусија",
		"sr-ME": "Bjelorusija",
		"mk-MK": "Белорусија",
		"bg-BG": "Беларус",
		"be-BY": "Беларусь",
		"uk-UA": "Білорусь",
		"ru-RU": "Беларусь",
		"el-GR": "Λευκορωσία",
		"el-CY": "Λευκορωσία",
		"ro-RO": "Belarus",
		"ro-MD": "Belarus",
		"hu-HU": "Belarusz",
		"sq-AL": "Bjellorusi",
		"sq-XK": "Bjellorusi",
		"mt-MT": "il-Belarussja",
		"ga-IE": "an Bhealarúis",
		"cy-GB": "Belarws",
		"gd-GB": "A’ Bhealaruis",
		"lb-LU": "Wäissrussland",
		"ca-ES": "Belarús",
		"ca-AD": "Belarús",
		"ca-FR": "Belarús",
		"ca-IT": "Belarús",
		"eu-ES": "Bielorrusia",
		"eu-FR": "Bielorrusia",
		"gl-ES": "Belarús",
		"tr-TR": "Belarus",
		"tr-CY": "Belarus"
	},
	"callingCode": "375",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"800"
			]
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "## ###-##-##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[1-4]"
			]
		},
		{
			"mask": "### ## ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"800"
			]
		},
		{
			"mask": "### ##-##-##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1(?:[56]|7[467])|2[1-3]"
			]
		},
		{
			"mask": "#### ##-###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1(?:5[169]|6[3-5]|7[179])|2(?:1[35]|2[34]|3[3-5])",
				"1(?:5[169]|6(?:3[1-3]|4|5[125])|7(?:1[3-9]|7[0-24-6]|9[2-7]))|2(?:1[35]|2[34]|3[3-5])"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
