import type { Country } from './types.js';

export const BLZ = {
	"code": "BLZ",
	"labels": {
		"pt-BR": "Belize",
		"pt-PT": "Belize",
		"es-ES": "Belice",
		"es-419": "Belice",
		"es-AR": "Belice",
		"es-BO": "Belice",
		"es-BR": "Belice",
		"es-BZ": "Belice",
		"es-CL": "Belice",
		"es-CO": "Belice",
		"es-CR": "Belice",
		"es-CU": "Belice",
		"es-DO": "Belice",
		"es-EC": "Belice",
		"es-GT": "Belice",
		"es-HN": "Belice",
		"es-MX": "Belice",
		"es-NI": "Belice",
		"es-PA": "Belice",
		"es-PE": "Belice",
		"es-PR": "Belice",
		"es-PY": "Belice",
		"es-SV": "Belice",
		"es-US": "Belice",
		"es-UY": "Belice",
		"es-VE": "Belice",
		"en-US": "Belize",
		"fr-FR": "Belize",
		"fr-BE": "Belize",
		"fr-CA": "Bélize",
		"fr-CH": "Belize",
		"fr-LU": "Belize",
		"fr-MC": "Belize",
		"it-IT": "Belize",
		"it-CH": "Belize",
		"it-SM": "Belize",
		"it-VA": "Belize",
		"de-DE": "Belize",
		"de-AT": "Belize",
		"de-CH": "Belize",
		"de-BE": "Belize",
		"de-LI": "Belize",
		"de-LU": "Belize"
	},
	"callingCode": "501"
} satisfies Country;
