import type { Country } from './types.js';

export const BMU = {
	"code": "BMU",
	"labels": {
		"pt-BR": "Bermudas",
		"pt-PT": "Bermudas",
		"es-ES": "Bermudas",
		"es-419": "Bermudas",
		"es-AR": "Bermudas",
		"es-BO": "Bermudas",
		"es-BR": "Bermudas",
		"es-BZ": "Bermudas",
		"es-CL": "Bermudas",
		"es-CO": "Bermudas",
		"es-CR": "Bermudas",
		"es-CU": "Bermudas",
		"es-DO": "Bermudas",
		"es-EC": "Bermudas",
		"es-GT": "Bermudas",
		"es-HN": "Bermudas",
		"es-MX": "Bermudas",
		"es-NI": "Bermudas",
		"es-PA": "Bermudas",
		"es-PE": "Bermudas",
		"es-PR": "Bermudas",
		"es-PY": "Bermudas",
		"es-SV": "Bermudas",
		"es-US": "Bermudas",
		"es-UY": "Bermudas",
		"es-VE": "Bermudas",
		"en-US": "Bermuda",
		"fr-FR": "Bermudes",
		"fr-BE": "Bermudes",
		"fr-CA": "Bermudes",
		"fr-CH": "Bermudes",
		"fr-LU": "Bermudes",
		"fr-MC": "Bermudes",
		"it-IT": "Bermuda",
		"it-CH": "Bermuda",
		"it-SM": "Bermuda",
		"it-VA": "Bermuda",
		"de-DE": "Bermuda",
		"de-AT": "Bermuda",
		"de-CH": "Bermuda",
		"de-BE": "Bermuda",
		"de-LI": "Bermuda",
		"de-LU": "Bermuda"
	},
	"callingCode": "1441"
} satisfies Country;
