import type { Country } from './types.js';

export const BRA = {
	"code": "BRA",
	"labels": {
		"pt-BR": "Brasil",
		"pt-PT": "Brasil",
		"es-ES": "Brasil",
		"es-419": "Brasil",
		"es-AR": "Brasil",
		"es-BO": "Brasil",
		"es-BR": "Brasil",
		"es-BZ": "Brasil",
		"es-CL": "Brasil",
		"es-CO": "Brasil",
		"es-CR": "Brasil",
		"es-CU": "Brasil",
		"es-DO": "Brasil",
		"es-EC": "Brasil",
		"es-GT": "Brasil",
		"es-HN": "Brasil",
		"es-MX": "Brasil",
		"es-NI": "Brasil",
		"es-PA": "Brasil",
		"es-PE": "Brasil",
		"es-PR": "Brasil",
		"es-PY": "Brasil",
		"es-SV": "Brasil",
		"es-US": "Brasil",
		"es-UY": "Brasil",
		"es-VE": "Brasil",
		"en-US": "Brazil",
		"fr-FR": "Brésil",
		"fr-BE": "Brésil",
		"fr-CA": "Brésil",
		"fr-CH": "Brésil",
		"fr-LU": "Brésil",
		"fr-MC": "Brésil",
		"it-IT": "Brasile",
		"it-CH": "Brasile",
		"it-SM": "Brasile",
		"it-VA": "Brasile",
		"de-DE": "Brasilien",
		"de-AT": "Brasilien",
		"de-CH": "Brasilien",
		"de-BE": "Brasilien",
		"de-LI": "Brasilien",
		"de-LU": "Brasilien"
	}
} satisfies Country;
