import type { Country } from './types.js';

export const BRA = {
	"code": "BRA",
	"labels": {
		"pt-BR": "Brasil",
		"pt-PT": "Brasil",
		"qu-PE": "Brasil",
		"qu-BO": "Brasil",
		"qu-EC": "Brasil",
		"chr-US": "ᏆᏏᎵ",
		"hi-IN": "ब्राज़ील",
		"bn-IN": "ব্রাজিল",
		"bn-BD": "ব্রাজিল",
		"ta-IN": "பிரேசில்",
		"ta-LK": "பிரேசில்",
		"ta-SG": "பிரேசில்",
		"ta-MY": "பிரேசில்",
		"te-IN": "బ్రెజిల్",
		"mr-IN": "ब्राझिल",
		"gu-IN": "બ્રાઝિલ",
		"kn-IN": "ಬ್ರೆಜಿಲ್",
		"ml-IN": "ബ്രസീൽ",
		"pa-IN": "ਬ੍ਰਾਜ਼ੀਲ",
		"ur-IN": "برازیل",
		"ur-PK": "برازیل",
		"or-IN": "ବ୍ରାଜିଲ୍",
		"as-IN": "ব্ৰাজিল",
		"ne-IN": "ब्राजिल",
		"ne-NP": "ब्राजिल",
		"si-LK": "බ්‍රසීලය",
		"kok-IN": "ब्राझील",
		"sd-IN": "ब्राज़ील",
		"ks-IN": "برازِل",
		"doi-IN": "ब्राजील",
		"mni-IN": "ব্রাজিল",
		"brx-IN": "ब्राजील",
		"sat-IN": "ᱵᱨᱟᱡᱤᱞ",
		"mai-IN": "ब्राज़ील",
		"sa-IN": "ब्राजील",
		"dz-BT": "བྲ་ཛིལ",
		"ja-JP": "ブラジル",
		"ko-KR": "브라질",
		"ko-KP": "브라질",
		"zh-CN": "巴西",
		"zh-Hans-CN": "巴西",
		"zh-Hant-TW": "巴西",
		"zh-TW": "巴西",
		"zh-HK": "巴西",
		"zh-MO": "巴西",
		"zh-SG": "巴西",
		"yue-Hant-HK": "巴西",
		"yue-Hans-CN": "巴西",
		"mn-MN": "Бразил",
		"ug-CN": "بىرازىلىيە",
		"ii-CN": "ꀠꑭ",
		"th-TH": "บราซิล",
		"lo-LA": "ບຣາຊິວ",
		"km-KH": "ប្រេស៊ីល",
		"my-MM": "ဘရာဇီး",
		"vi-VN": "Brazil",
		"id-ID": "Brasil",
		"ms-MY": "Brazil",
		"ms-SG": "Brazil",
		"ms-BN": "Brazil",
		"jv-ID": "Brasil",
		"su-ID": "Brasil",
		"fil-PH": "Brazil",
		"ceb-PH": "Brazil",
		"ka-GE": "ბრაზილია",
		"hy-AM": "Բրազիլիա",
		"az-AZ": "Braziliya",
		"az-Cyrl-AZ": "Бразилија",
		"kk-KZ": "Бразилия",
		"ky-KG": "Бразилия",
		"uz-UZ": "Braziliya",
		"tg-TJ": "Бразилия",
		"tk-TM": "Braziliýa",
		"fa-IR": "برزیل",
		"fa-AF": "برازیل",
		"ps-AF": "برازیل",
		"ps-PK": "برازیل",
		"he-IL": "ברזיל",
		"ar-SA": "البرازيل",
		"ar-AE": "البرازيل",
		"ar-QA": "البرازيل",
		"ar-BH": "البرازيل",
		"ar-KW": "البرازيل",
		"ar-OM": "البرازيل",
		"ar-YE": "البرازيل",
		"ar-IQ": "البرازيل",
		"ar-JO": "البرازيل",
		"ar-LB": "البرازيل",
		"ar-SY": "البرازيل",
		"ar-PS": "البرازيل",
		"en-US": "Brazil",
		"en-GB": "Brazil",
		"en-IE": "Brazil",
		"en-MT": "Brazil",
		"en-GI": "Brazil",
		"en-CY": "Brazil",
		"en-JE": "Brazil",
		"en-GG": "Brazil",
		"en-IM": "Brazil",
		"en-CA": "Brazil",
		"en-AU": "Brazil",
		"en-NZ": "Brazil",
		"en-ZA": "Brazil",
		"en-IN": "Brazil",
		"en-SG": "Brazil",
		"pt-AO": "Brasil",
		"pt-MZ": "Brasil",
		"pt-CV": "Brasil",
		"pt-GW": "Brasil",
		"pt-ST": "Brasil",
		"pt-TL": "Brasil",
		"pt-MO": "Brasil",
		"es-ES": "Brasil",
		"es-419": "Brasil",
		"es-AD": "Brasil",
		"es-GI": "Brasil",
		"es-AR": "Brasil",
		"es-BO": "Brasil",
		"es-BR": "Brasil",
		"es-BZ": "Brasil",
		"es-CL": "Brasil",
		"es-CO": "Brasil",
		"es-CR": "Brasil",
		"es-CU": "Brasil",
		"es-DO": "Brasil",
		"es-EC": "Brasil",
		"es-GT": "Brasil",
		"es-HN": "Brasil",
		"es-MX": "Brasil",
		"es-NI": "Brasil",
		"es-PA": "Brasil",
		"es-PE": "Brasil",
		"es-PR": "Brasil",
		"es-PY": "Brasil",
		"es-SV": "Brasil",
		"es-US": "Brasil",
		"es-UY": "Brasil",
		"es-VE": "Brasil",
		"fr-FR": "Brésil",
		"fr-BE": "Brésil",
		"fr-CH": "Brésil",
		"fr-LU": "Brésil",
		"fr-MC": "Brésil",
		"fr-AD": "Brésil",
		"fr-CA": "Brésil",
		"it-IT": "Brasile",
		"it-CH": "Brasile",
		"it-SM": "Brasile",
		"it-VA": "Brasile",
		"de-DE": "Brasilien",
		"de-AT": "Brasilien",
		"de-CH": "Brasilien",
		"de-BE": "Brasilien",
		"de-LI": "Brasilien",
		"de-LU": "Brasilien",
		"nl-NL": "Brazilië",
		"nl-BE": "Brazilië",
		"sv-SE": "Brasilien",
		"sv-FI": "Brasilien",
		"da-DK": "Brasilien",
		"nb-NO": "Brasil",
		"nn-NO": "Brasil",
		"fi-FI": "Brasilia",
		"is-IS": "Brasilía",
		"fo-FO": "Brasil",
		"et-EE": "Brasiilia",
		"lv-LV": "Brazīlija",
		"lt-LT": "Brazilija",
		"pl-PL": "Brazylia",
		"cs-CZ": "Brazílie",
		"sk-SK": "Brazília",
		"sl-SI": "Brazilija",
		"hr-HR": "Brazil",
		"bs-BA": "Brazil",
		"sr-RS": "Бразил",
		"sr-BA": "Бразил",
		"sr-ME": "Brazil",
		"mk-MK": "Бразил",
		"bg-BG": "Бразилия",
		"be-BY": "Бразілія",
		"uk-UA": "Бразилія",
		"ru-RU": "Бразилия",
		"el-GR": "Βραζιλία",
		"el-CY": "Βραζιλία",
		"ro-RO": "Brazilia",
		"ro-MD": "Brazilia",
		"hu-HU": "Brazília",
		"sq-AL": "Brazil",
		"sq-XK": "Brazil",
		"mt-MT": "Il-Brażil",
		"ga-IE": "an Bhrasaíl",
		"cy-GB": "Brasil",
		"gd-GB": "Braisil",
		"lb-LU": "Brasilien",
		"ca-ES": "Brasil",
		"ca-AD": "Brasil",
		"ca-FR": "Brasil",
		"ca-IT": "Brasil",
		"eu-ES": "Brasil",
		"eu-FR": "Brasil",
		"gl-ES": "Brasil",
		"tr-TR": "Brezilya",
		"tr-CY": "Brezilya"
	},
	"callingCode": "55",
	"phoneMasks": [
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"300|4(?:0[02]|37)",
				"4(?:02|37)0|[34]00"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		},
		{
			"mask": "(##) ####-####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"(?:[14689][1-9]|2[12478]|3[1-578]|5[13-5]|7[13-579])[2-57]"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"(?:[358]|90)0"
			]
		},
		{
			"mask": "(##) #####-####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"[16][1-9]|[2-57-9]"
			]
		}
	]
} satisfies Country;
