import type { Country } from './types.js';

export const BRB = {
	"code": "BRB",
	"labels": {
		"pt-BR": "Barbados",
		"pt-PT": "Barbados",
		"es-ES": "Barbados",
		"es-419": "Barbados",
		"es-AR": "Barbados",
		"es-BO": "Barbados",
		"es-BR": "Barbados",
		"es-BZ": "Barbados",
		"es-CL": "Barbados",
		"es-CO": "Barbados",
		"es-CR": "Barbados",
		"es-CU": "Barbados",
		"es-DO": "Barbados",
		"es-EC": "Barbados",
		"es-GT": "Barbados",
		"es-HN": "Barbados",
		"es-MX": "Barbados",
		"es-NI": "Barbados",
		"es-PA": "Barbados",
		"es-PE": "Barbados",
		"es-PR": "Barbados",
		"es-PY": "Barbados",
		"es-SV": "Barbados",
		"es-US": "Barbados",
		"es-UY": "Barbados",
		"es-VE": "Barbados",
		"en-US": "Barbados",
		"fr-FR": "Barbade",
		"fr-BE": "Barbade",
		"fr-CA": "Barbade",
		"fr-CH": "Barbade",
		"fr-LU": "Barbade",
		"fr-MC": "Barbade",
		"it-IT": "Barbados",
		"it-CH": "Barbados",
		"it-SM": "Barbados",
		"it-VA": "Barbados",
		"de-DE": "Barbados",
		"de-AT": "Barbados",
		"de-CH": "Barbados",
		"de-BE": "Barbados",
		"de-LI": "Barbados",
		"de-LU": "Barbados"
	}
} satisfies Country;
