import type { Country } from './types.js';

export const BVT = {
	"code": "BVT",
	"labels": {
		"pt-BR": "Ilha Bouvet",
		"pt-PT": "Ilha Bouvet",
		"qu-PE": "Isla Bouvet",
		"qu-BO": "Isla Bouvet",
		"qu-EC": "Isla Bouvet",
		"chr-US": "ᏊᏪ ᎤᎦᏚᏛᎢ",
		"hi-IN": "बोवेत द्वीप",
		"bn-IN": "বোভেট দ্বীপ",
		"bn-BD": "বোভেট দ্বীপ",
		"ta-IN": "பொவேட் தீவு",
		"ta-LK": "பொவேட் தீவு",
		"ta-SG": "பொவேட் தீவு",
		"ta-MY": "பொவேட் தீவு",
		"te-IN": "బువై దీవి",
		"mr-IN": "बोउवेट बेट",
		"gu-IN": "બૌવેત આઇલેન્ડ",
		"kn-IN": "ಬೋವೆಟ್ ದ್ವೀಪ",
		"ml-IN": "ബൗവെട്ട് ദ്വീപ്",
		"pa-IN": "ਬੌਵੇਟ ਟਾਪੂ",
		"ur-IN": "جزیرہ بوویت",
		"ur-PK": "بؤویٹ آئلینڈ",
		"or-IN": "ବୌଭେଟ୍‌ ଦ୍ୱୀପ",
		"as-IN": "বুভে দ্বীপ",
		"ne-IN": "बुभेट टापु",
		"ne-NP": "बुभेट टापु",
		"si-LK": "බුවට් දුපත්",
		"kok-IN": "बोवट आयलँड",
		"ks-IN": "بووَٹ جٔزیٖرٕ",
		"brx-IN": "बूभेट द्वीप",
		"mai-IN": "बोबेत द्वीप",
		"dz-BT": "བོའུ་ཝེཊ་མཚོ་གླིང",
		"ja-JP": "ブーベ島",
		"ko-KR": "부베섬",
		"ko-KP": "부베섬",
		"zh-CN": "布韦岛",
		"zh-Hans-CN": "布韦岛",
		"zh-Hant-TW": "布威島",
		"zh-TW": "布威島",
		"zh-HK": "鮑威特島",
		"zh-MO": "鮑威特島",
		"zh-SG": "布韦岛",
		"yue-Hant-HK": "布威島",
		"yue-Hans-CN": "布威岛",
		"mn-MN": "Буве арал",
		"ug-CN": "بوۋېت ئارىلى",
		"th-TH": "เกาะบูเว",
		"lo-LA": "ເກາະບູເວດ",
		"km-KH": "កោះ​ប៊ូវ៉េត",
		"my-MM": "ဘူဗက်ကျွန်း",
		"vi-VN": "Đảo Bouvet",
		"id-ID": "Pulau Bouvet",
		"ms-MY": "Pulau Bouvet",
		"ms-SG": "Pulau Bouvet",
		"ms-BN": "Pulau Bouvet",
		"jv-ID": "Pulo Bovèt",
		"fil-PH": "Bouvet Island",
		"ceb-PH": "Bouvet Island",
		"ka-GE": "ბუვე",
		"hy-AM": "Բուվե կղզի",
		"az-AZ": "Buve adası",
		"az-Cyrl-AZ": "Буве адасы",
		"kk-KZ": "Буве аралы",
		"ky-KG": "Буве аралы",
		"uz-UZ": "Buve oroli",
		"tg-TJ": "Ҷазираи Буве",
		"tk-TM": "Buwe adasy",
		"fa-IR": "جزیرهٔ بووه",
		"fa-AF": "جزیرهٔ بووه",
		"ps-AF": "بوویټ ټاپو",
		"ps-PK": "بوویټ ټاپو",
		"he-IL": "האי בובה",
		"ar-SA": "جزيرة بوفيه",
		"ar-AE": "جزيرة بوفيه",
		"ar-QA": "جزيرة بوفيه",
		"ar-BH": "جزيرة بوفيه",
		"ar-KW": "جزيرة بوفيه",
		"ar-OM": "جزيرة بوفيه",
		"ar-YE": "جزيرة بوفيه",
		"ar-IQ": "جزيرة بوفيه",
		"ar-JO": "جزيرة بوفيه",
		"ar-LB": "جزيرة بوفيه",
		"ar-SY": "جزيرة بوفيه",
		"ar-PS": "جزيرة بوفيه",
		"en-US": "Bouvet Island",
		"en-GB": "Bouvet Island",
		"en-IE": "Bouvet Island",
		"en-MT": "Bouvet Island",
		"en-GI": "Bouvet Island",
		"en-CY": "Bouvet Island",
		"en-JE": "Bouvet Island",
		"en-GG": "Bouvet Island",
		"en-IM": "Bouvet Island",
		"en-CA": "Bouvet Island",
		"en-AU": "Bouvet Island",
		"en-NZ": "Bouvet Island",
		"en-ZA": "Bouvet Island",
		"en-IN": "Bouvet Island",
		"en-SG": "Bouvet Island",
		"pt-AO": "Ilha Bouvet",
		"pt-MZ": "Ilha Bouvet",
		"pt-CV": "Ilha Bouvet",
		"pt-GW": "Ilha Bouvet",
		"pt-ST": "Ilha Bouvet",
		"pt-TL": "Ilha Bouvet",
		"pt-MO": "Ilha Bouvet",
		"es-ES": "Isla Bouvet",
		"es-419": "Isla Bouvet",
		"es-AD": "Isla Bouvet",
		"es-GI": "Isla Bouvet",
		"es-AR": "Isla Bouvet",
		"es-BO": "Isla Bouvet",
		"es-BR": "Isla Bouvet",
		"es-BZ": "Isla Bouvet",
		"es-CL": "Isla Bouvet",
		"es-CO": "Isla Bouvet",
		"es-CR": "Isla Bouvet",
		"es-CU": "Isla Bouvet",
		"es-DO": "Isla Bouvet",
		"es-EC": "Isla Bouvet",
		"es-GT": "Isla Bouvet",
		"es-HN": "Isla Bouvet",
		"es-MX": "Isla Bouvet",
		"es-NI": "Isla Bouvet",
		"es-PA": "Isla Bouvet",
		"es-PE": "Isla Bouvet",
		"es-PR": "Isla Bouvet",
		"es-PY": "Isla Bouvet",
		"es-SV": "Isla Bouvet",
		"es-US": "Isla Bouvet",
		"es-UY": "Isla Bouvet",
		"es-VE": "Isla Bouvet",
		"fr-FR": "Île Bouvet",
		"fr-BE": "Île Bouvet",
		"fr-CH": "Île Bouvet",
		"fr-LU": "Île Bouvet",
		"fr-MC": "Île Bouvet",
		"fr-AD": "Île Bouvet",
		"fr-CA": "île Bouvet",
		"it-IT": "Isola Bouvet",
		"it-CH": "Isola Bouvet",
		"it-SM": "Isola Bouvet",
		"it-VA": "Isola Bouvet",
		"de-DE": "Bouvetinsel",
		"de-AT": "Bouvetinsel",
		"de-CH": "Bouvetinsel",
		"de-BE": "Bouvetinsel",
		"de-LI": "Bouvetinsel",
		"de-LU": "Bouvetinsel",
		"nl-NL": "Bouveteiland",
		"nl-BE": "Bouveteiland",
		"sv-SE": "Bouvetön",
		"sv-FI": "Bouvetön",
		"da-DK": "Bouvetøen",
		"nb-NO": "Bouvetøya",
		"nn-NO": "Bouvetøya",
		"fi-FI": "Bouvet’nsaari",
		"is-IS": "Bouveteyja",
		"fo-FO": "Bouvetoyggj",
		"et-EE": "Bouvet’ saar",
		"lv-LV": "Buvē sala",
		"lt-LT": "Buvė Sala",
		"pl-PL": "Wyspa Bouveta",
		"cs-CZ": "Bouvetův ostrov",
		"sk-SK": "Bouvetov ostrov",
		"sl-SI": "Bouvetov otok",
		"hr-HR": "Otok Bouvet",
		"bs-BA": "Ostrvo Buve",
		"sr-RS": "Острво Буве",
		"sr-BA": "острво Буве",
		"sr-ME": "Ostrvo Buve",
		"mk-MK": "Остров Буве",
		"bg-BG": "остров Буве",
		"be-BY": "Востраў Бувэ",
		"uk-UA": "Острів Буве",
		"ru-RU": "о-в Буве",
		"el-GR": "Νήσος Μπουβέ",
		"el-CY": "Νήσος Μπουβέ",
		"ro-RO": "Insula Bouvet",
		"ro-MD": "Insula Bouvet",
		"hu-HU": "Bouvet-sziget",
		"sq-AL": "Ishulli Bove",
		"sq-XK": "Ishulli Bove",
		"mt-MT": "Gżira Bouvet",
		"ga-IE": "Oileán Bouvet",
		"cy-GB": "Ynys Bouvet",
		"gd-GB": "Eilean Bouvet",
		"lb-LU": "Bouvetinsel",
		"ca-ES": "Illa Bouvet",
		"ca-AD": "Illa Bouvet",
		"ca-FR": "Illa Bouvet",
		"ca-IT": "Illa Bouvet",
		"eu-ES": "Bouvet uhartea",
		"eu-FR": "Bouvet uhartea",
		"gl-ES": "Illa Bouvet",
		"tr-TR": "Bouvet Adası",
		"tr-CY": "Bouvet Adası"
	},
	"callingCode": "47"
} satisfies Country;
