import type { Country } from './types.js';

export const BVT = {
	"code": "BVT",
	"labels": {
		"pt-BR": "Ilha Bouvet",
		"pt-PT": "Ilha Bouvet",
		"es-ES": "Isla Bouvet",
		"es-419": "Isla Bouvet",
		"es-AR": "Isla Bouvet",
		"es-BO": "Isla Bouvet",
		"es-BR": "Isla Bouvet",
		"es-BZ": "Isla Bouvet",
		"es-CL": "Isla Bouvet",
		"es-CO": "Isla Bouvet",
		"es-CR": "Isla Bouvet",
		"es-CU": "Isla Bouvet",
		"es-DO": "Isla Bouvet",
		"es-EC": "Isla Bouvet",
		"es-GT": "Isla Bouvet",
		"es-HN": "Isla Bouvet",
		"es-MX": "Isla Bouvet",
		"es-NI": "Isla Bouvet",
		"es-PA": "Isla Bouvet",
		"es-PE": "Isla Bouvet",
		"es-PR": "Isla Bouvet",
		"es-PY": "Isla Bouvet",
		"es-SV": "Isla Bouvet",
		"es-US": "Isla Bouvet",
		"es-UY": "Isla Bouvet",
		"es-VE": "Isla Bouvet",
		"en-US": "Bouvet Island",
		"fr-FR": "Île Bouvet",
		"fr-BE": "Île Bouvet",
		"fr-CA": "île Bouvet",
		"fr-CH": "Île Bouvet",
		"fr-LU": "Île Bouvet",
		"fr-MC": "Île Bouvet",
		"it-IT": "Isola Bouvet",
		"it-CH": "Isola Bouvet",
		"it-SM": "Isola Bouvet",
		"it-VA": "Isola Bouvet",
		"de-DE": "Bouvetinsel",
		"de-AT": "Bouvetinsel",
		"de-CH": "Bouvetinsel",
		"de-BE": "Bouvetinsel",
		"de-LI": "Bouvetinsel",
		"de-LU": "Bouvetinsel"
	},
	"callingCode": "47"
} satisfies Country;
