import type { Country } from './types.js';

export const CAF = {
	"code": "CAF",
	"labels": {
		"pt-BR": "República Centro-Africana",
		"pt-PT": "República Centro-Africana",
		"qu-PE": "República Centroafricana",
		"qu-BO": "República Centroafricana",
		"qu-EC": "República Centroafricana",
		"chr-US": "ᎬᎿᎨᏍᏛ ᎠᏰᏟ ᏍᎦᏚᎩ",
		"hi-IN": "मध्य अफ़्रीकी गणराज्य",
		"bn-IN": "মধ্য আফ্রিকার প্রজাতন্ত্র",
		"bn-BD": "মধ্য আফ্রিকার প্রজাতন্ত্র",
		"ta-IN": "மத்திய ஆப்ரிக்கக் குடியரசு",
		"ta-LK": "மத்திய ஆப்ரிக்கக் குடியரசு",
		"ta-SG": "மத்திய ஆப்ரிக்கக் குடியரசு",
		"ta-MY": "மத்திய ஆப்ரிக்கக் குடியரசு",
		"te-IN": "సెంట్రల్ ఆఫ్రికన్ రిపబ్లిక్",
		"mr-IN": "केंद्रीय अफ्रिकी प्रजासत्ताक",
		"gu-IN": "સેન્ટ્રલ આફ્રિકન રિપબ્લિક",
		"kn-IN": "ಮಧ್ಯ ಆಫ್ರಿಕಾ ಗಣರಾಜ್ಯ",
		"ml-IN": "സെൻട്രൽ ആഫ്രിക്കൻ റിപ്പബ്ലിക്ക്",
		"pa-IN": "ਕੇਂਦਰੀ ਅਫ਼ਰੀਕੀ ਗਣਰਾਜ",
		"ur-IN": "وسط افریقی جمہوریہ",
		"ur-PK": "وسط افریقی جمہوریہ",
		"or-IN": "ମଧ୍ୟ ଆଫ୍ରିକୀୟ ସାଧାରଣତନ୍ତ୍ର",
		"as-IN": "মধ্য আফ্রিকান প্রজাতন্ত্র",
		"ne-IN": "मध्य अफ्रिकी गणतन्त्र",
		"ne-NP": "मध्य अफ्रिकी गणतन्त्र",
		"si-LK": "මධ්‍යම අප්‍රිකානු ජනරජය",
		"kok-IN": "मध्य अफ्रीकी लोकसत्तकराज्य",
		"ks-IN": "مرکٔزی اَفریٖکی جموٗریَت",
		"brx-IN": "मिरु आफ्रिका सुबुंखुंथाय",
		"mai-IN": "मध्य अफ्रीकी रिपब्लिक",
		"dz-BT": "སེན་ཊལ་ ཨཕ་རི་ཀཱན་ རི་པབ་ལིཀ",
		"ja-JP": "中央アフリカ共和国",
		"ko-KR": "중앙 아프리카 공화국",
		"ko-KP": "중앙 아프리카 공화국",
		"zh-CN": "中非共和国",
		"zh-Hans-CN": "中非共和国",
		"zh-Hant-TW": "中非共和國",
		"zh-TW": "中非共和國",
		"zh-HK": "中非共和國",
		"zh-MO": "中非共和國",
		"zh-SG": "中非共和国",
		"yue-Hant-HK": "中非共和國",
		"yue-Hans-CN": "中非共和国",
		"mn-MN": "Төв Африкийн Бүгд Найрамдах Улс",
		"ug-CN": "ئوتتۇرا ئافرىقا جۇمھۇرىيىتى",
		"th-TH": "สาธารณรัฐแอฟริกากลาง",
		"lo-LA": "ສາທາລະນະລັດອາຟຣິກາກາງ",
		"km-KH": "សាធារណរដ្ឋអាហ្វ្រិកកណ្ដាល",
		"my-MM": "ဗဟို အာဖရိက ပြည်ထောင်စု",
		"vi-VN": "Cộng hòa Trung Phi",
		"id-ID": "Republik Afrika Tengah",
		"ms-MY": "Republik Afrika Tengah",
		"ms-SG": "Republik Afrika Tengah",
		"ms-BN": "Republik Afrika Tengah",
		"jv-ID": "Républik Afrika Tengah",
		"fil-PH": "Central African Republic",
		"ceb-PH": "Central African Republic",
		"ka-GE": "ცენტრალური აფრიკის რესპუბლიკა",
		"hy-AM": "Կենտրոնական Աֆրիկյան Հանրապետություն",
		"az-AZ": "Mərkəzi Afrika Respublikası",
		"az-Cyrl-AZ": "Мәркәзи Африка Республикасы",
		"kk-KZ": "Орталық Африка Республикасы",
		"ky-KG": "Борбордук Африка Республикасы",
		"uz-UZ": "Markaziy Afrika Respublikasi",
		"tg-TJ": "Ҷумҳурии Африқои Марказӣ",
		"tk-TM": "Merkezi Afrika Respublikasy",
		"fa-IR": "جمهوری افریقای مرکزی",
		"fa-AF": "جمهوری افریقای مرکزی",
		"ps-AF": "وسطي افريقا جمهور",
		"ps-PK": "وسطي افريقا جمهور",
		"he-IL": "הרפובליקה המרכז-אפריקאית",
		"ar-SA": "جمهورية أفريقيا الوسطى",
		"ar-AE": "جمهورية أفريقيا الوسطى",
		"ar-QA": "جمهورية أفريقيا الوسطى",
		"ar-BH": "جمهورية أفريقيا الوسطى",
		"ar-KW": "جمهورية أفريقيا الوسطى",
		"ar-OM": "جمهورية أفريقيا الوسطى",
		"ar-YE": "جمهورية أفريقيا الوسطى",
		"ar-IQ": "جمهورية أفريقيا الوسطى",
		"ar-JO": "جمهورية أفريقيا الوسطى",
		"ar-LB": "جمهورية أفريقيا الوسطى",
		"ar-SY": "جمهورية أفريقيا الوسطى",
		"ar-PS": "جمهورية أفريقيا الوسطى",
		"en-US": "Central African Republic",
		"en-GB": "Central African Republic",
		"en-IE": "Central African Republic",
		"en-MT": "Central African Republic",
		"en-GI": "Central African Republic",
		"en-CY": "Central African Republic",
		"en-JE": "Central African Republic",
		"en-GG": "Central African Republic",
		"en-IM": "Central African Republic",
		"en-CA": "Central African Republic",
		"en-AU": "Central African Republic",
		"en-NZ": "Central African Republic",
		"en-ZA": "Central African Republic",
		"en-IN": "Central African Republic",
		"en-SG": "Central African Republic",
		"pt-AO": "República Centro-Africana",
		"pt-MZ": "República Centro-Africana",
		"pt-CV": "República Centro-Africana",
		"pt-GW": "República Centro-Africana",
		"pt-ST": "República Centro-Africana",
		"pt-TL": "República Centro-Africana",
		"pt-MO": "República Centro-Africana",
		"es-ES": "República Centroafricana",
		"es-419": "República Centroafricana",
		"es-AD": "República Centroafricana",
		"es-GI": "República Centroafricana",
		"es-AR": "República Centroafricana",
		"es-BO": "República Centroafricana",
		"es-BR": "República Centroafricana",
		"es-BZ": "República Centroafricana",
		"es-CL": "República Centroafricana",
		"es-CO": "República Centroafricana",
		"es-CR": "República Centroafricana",
		"es-CU": "República Centroafricana",
		"es-DO": "República Centroafricana",
		"es-EC": "República Centroafricana",
		"es-GT": "República Centroafricana",
		"es-HN": "República Centroafricana",
		"es-MX": "República Centroafricana",
		"es-NI": "República Centroafricana",
		"es-PA": "República Centroafricana",
		"es-PE": "República Centroafricana",
		"es-PR": "República Centroafricana",
		"es-PY": "República Centroafricana",
		"es-SV": "República Centroafricana",
		"es-US": "República Centroafricana",
		"es-UY": "República Centroafricana",
		"es-VE": "República Centroafricana",
		"fr-FR": "République centrafricaine",
		"fr-BE": "République centrafricaine",
		"fr-CH": "République centrafricaine",
		"fr-LU": "République centrafricaine",
		"fr-MC": "République centrafricaine",
		"fr-AD": "République centrafricaine",
		"fr-CA": "République centrafricaine",
		"it-IT": "Repubblica Centrafricana",
		"it-CH": "Repubblica Centrafricana",
		"it-SM": "Repubblica Centrafricana",
		"it-VA": "Repubblica Centrafricana",
		"de-DE": "Zentralafrikanische Republik",
		"de-AT": "Zentralafrikanische Republik",
		"de-CH": "Zentralafrikanische Republik",
		"de-BE": "Zentralafrikanische Republik",
		"de-LI": "Zentralafrikanische Republik",
		"de-LU": "Zentralafrikanische Republik",
		"nl-NL": "Centraal-Afrikaanse Republiek",
		"nl-BE": "Centraal-Afrikaanse Republiek",
		"sv-SE": "Centralafrikanska republiken",
		"sv-FI": "Centralafrikanska republiken",
		"da-DK": "Den Centralafrikanske Republik",
		"nb-NO": "Den sentralafrikanske republikk",
		"nn-NO": "Den sentralafrikanske republikken",
		"fi-FI": "Keski-Afrikan tasavalta",
		"is-IS": "Mið-Afríkulýðveldið",
		"fo-FO": "Miðafrikalýðveldið",
		"et-EE": "Kesk-Aafrika Vabariik",
		"lv-LV": "Centrālāfrikas Republika",
		"lt-LT": "Centrinės Afrikos Respublika",
		"pl-PL": "Republika Środkowoafrykańska",
		"cs-CZ": "Středoafrická republika",
		"sk-SK": "Stredoafrická republika",
		"sl-SI": "Srednjeafriška republika",
		"hr-HR": "Srednjoafrička Republika",
		"bs-BA": "Centralnoafrička Republika",
		"sr-RS": "Централноафричка Република",
		"sr-BA": "Централноафричка Република",
		"sr-ME": "Centralnoafrička Republika",
		"mk-MK": "Централноафриканска Република",
		"bg-BG": "Централноафриканска република",
		"be-BY": "Цэнтральна-Афрыканская Рэспубліка",
		"uk-UA": "Центральноафриканська Республіка",
		"ru-RU": "Центрально-Африканская Республика",
		"el-GR": "Κεντροαφρικανική Δημοκρατία",
		"el-CY": "Κεντροαφρικανική Δημοκρατία",
		"ro-RO": "Republica Centrafricană",
		"ro-MD": "Republica Centrafricană",
		"hu-HU": "Közép-afrikai Köztársaság",
		"sq-AL": "Republika e Afrikës Qendrore",
		"sq-XK": "Republika e Afrikës Qendrore",
		"mt-MT": "ir-Repubblika Ċentru-Afrikana",
		"ga-IE": "Poblacht na hAfraice Láir",
		"cy-GB": "Gweriniaeth Canolbarth Affrica",
		"gd-GB": "Poblachd Meadhan Afraga",
		"lb-LU": "Zentralafrikanesch Republik",
		"ca-ES": "República Centreafricana",
		"ca-AD": "República Centreafricana",
		"ca-FR": "República Centreafricana",
		"ca-IT": "República Centreafricana",
		"eu-ES": "Afrika Erdiko Errepublika",
		"eu-FR": "Afrika Erdiko Errepublika",
		"gl-ES": "República Centroafricana",
		"tr-TR": "Orta Afrika Cumhuriyeti",
		"tr-CY": "Orta Afrika Cumhuriyeti"
	},
	"callingCode": "236",
	"phoneMasks": [
		{
			"mask": "## ## ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[278]"
			]
		}
	]
} satisfies Country;
