import type { Country } from './types.js';

export const CAN = {
	"code": "CAN",
	"labels": {
		"pt-BR": "Canadá",
		"pt-PT": "Canadá",
		"es-ES": "Canadá",
		"es-419": "Canadá",
		"es-AR": "Canadá",
		"es-BO": "Canadá",
		"es-BR": "Canadá",
		"es-BZ": "Canadá",
		"es-CL": "Canadá",
		"es-CO": "Canadá",
		"es-CR": "Canadá",
		"es-CU": "Canadá",
		"es-DO": "Canadá",
		"es-EC": "Canadá",
		"es-GT": "Canadá",
		"es-HN": "Canadá",
		"es-MX": "Canadá",
		"es-NI": "Canadá",
		"es-PA": "Canadá",
		"es-PE": "Canadá",
		"es-PR": "Canadá",
		"es-PY": "Canadá",
		"es-SV": "Canadá",
		"es-US": "Canadá",
		"es-UY": "Canadá",
		"es-VE": "Canadá",
		"en-US": "Canada",
		"fr-FR": "Canada",
		"fr-BE": "Canada",
		"fr-CA": "Canada",
		"fr-CH": "Canada",
		"fr-LU": "Canada",
		"fr-MC": "Canada",
		"it-IT": "Canada",
		"it-CH": "Canada",
		"it-SM": "Canada",
		"it-VA": "Canada",
		"de-DE": "Kanada",
		"de-AT": "Kanada",
		"de-CH": "Kanada",
		"de-BE": "Kanada",
		"de-LI": "Kanada",
		"de-LU": "Kanada"
	}
} satisfies Country;
