import type { Country } from './types.js';

export const CCK = {
	"code": "CCK",
	"labels": {
		"pt-BR": "Ilhas Cocos (Keeling)",
		"pt-PT": "Ilhas dos Cocos (Keeling)",
		"qu-PE": "Islas Cocos",
		"qu-BO": "Islas Cocos",
		"qu-EC": "Islas Cocos",
		"chr-US": "ᎪᎪᏍ (ᎩᎵᏂ) ᏚᎦᏚᏛᎢ",
		"hi-IN": "कोकोस (कीलिंग) द्वीपसमूह",
		"bn-IN": "কোকোস (কিলিং) দ্বীপপুঞ্জ",
		"bn-BD": "কোকোস (কিলিং) দ্বীপপুঞ্জ",
		"ta-IN": "கோகோஸ் (கீலிங்) தீவுகள்",
		"ta-LK": "கோகோஸ் (கீலிங்) தீவுகள்",
		"ta-SG": "கோகோஸ் (கீலிங்) தீவுகள்",
		"ta-MY": "கோகோஸ் (கீலிங்) தீவுகள்",
		"te-IN": "కోకోస్ (కీలింగ్) దీవులు",
		"mr-IN": "कोकोस (कीलिंग) बेटे",
		"gu-IN": "કોકોઝ (કીલીંગ) આઇલેન્ડ્સ",
		"kn-IN": "ಕೊಕೊಸ್ (ಕೀಲಿಂಗ್) ದ್ವೀಪಗಳು",
		"ml-IN": "കോക്കസ് (കീലിംഗ്) ദ്വീപുകൾ",
		"pa-IN": "ਕੋਕੋਸ (ਕੀਲਿੰਗ) ਟਾਪੂ",
		"ur-IN": "جزائر (کیلنگ) کوکوس",
		"ur-PK": "کوکوس (کیلنگ) جزائر",
		"or-IN": "କୋକୋସ୍ (କୀଲିଂ) ଦ୍ଵୀପପୁଞ୍ଜ",
		"as-IN": "কোকোচ (কীলিং) দ্বীপপুঞ্জ",
		"ne-IN": "कोकोस (किलिंग) टापुहरु",
		"ne-NP": "कोकोस (किलिंग) टापुहरु",
		"si-LK": "කොකෝස් දූපත්",
		"kok-IN": "कोकोस (कीलिंग) आयलँड",
		"ks-IN": "کوکَس (کیٖلِنگ) جٔزیٖرٕ",
		"brx-IN": "कक’स द्वीपफोर",
		"mai-IN": "कोकेज (कीलिंग) द्वीपसमूह",
		"dz-BT": "ཀོ་ཀོས་གླིང་ཚོམ",
		"ja-JP": "ココス(キーリング)諸島",
		"ko-KR": "코코스 제도",
		"ko-KP": "코코스 제도",
		"zh-CN": "科科斯（基林）群岛",
		"zh-Hans-CN": "科科斯（基林）群岛",
		"zh-Hant-TW": "科克斯（基靈）群島",
		"zh-TW": "科克斯（基靈）群島",
		"zh-HK": "科科斯 (基林) 群島",
		"zh-MO": "科科斯 (基林) 群島",
		"zh-SG": "科科斯（基林）群岛",
		"yue-Hant-HK": "科科斯（基林）群島",
		"yue-Hans-CN": "科科斯（基林）群岛",
		"mn-MN": "Кокос (Кийлинг) арлууд",
		"ug-CN": "كوكوس (كىلىڭ) ئاراللىرى",
		"th-TH": "หมู่เกาะโคโคส (คีลิง)",
		"lo-LA": "ຫມູ່ເກາະໂກໂກສ",
		"km-KH": "កោះ​កូកូស (គីលីង)",
		"my-MM": "ကိုကိုးကျွန်း",
		"vi-VN": "Quần đảo Cocos (Keeling)",
		"id-ID": "Kepulauan Cocos (Keeling)",
		"ms-MY": "Kepulauan Cocos (Keeling)",
		"ms-SG": "Kepulauan Cocos (Keeling)",
		"ms-BN": "Kepulauan Cocos (Keeling)",
		"jv-ID": "Kapuloan Cocos (Keeling)",
		"fil-PH": "Cocos (Keeling) Islands",
		"ceb-PH": "Cocos (Keeling) Islands",
		"ka-GE": "ქოქოსის (კილინგის) კუნძულები",
		"hy-AM": "Կոկոսյան (Քիլինգ) կղզիներ",
		"az-AZ": "Kokos (Kilinq) adaları",
		"az-Cyrl-AZ": "Кокос (Килинг) адалары",
		"kk-KZ": "Кокос (Килинг) аралдары",
		"ky-KG": "Кокос (Килинг) аралдары",
		"uz-UZ": "Kokos (Kiling) orollari",
		"tg-TJ": "Ҷазираҳои Кокос (Килинг)",
		"tk-TM": "Kokos (Kiling) adalary",
		"fa-IR": "جزایر کوکوس",
		"fa-AF": "جزایر کوکوس",
		"ps-AF": "کوکوز (کيلنګ) ټاپوګان",
		"ps-PK": "کوکوز (کيلنګ) ټاپوګان",
		"he-IL": "איי קוקוס (קילינג)",
		"ar-SA": "جزر كوكوس (كيلينغ)",
		"ar-AE": "جزر كوكوس (كيلينغ)",
		"ar-QA": "جزر كوكوس (كيلينغ)",
		"ar-BH": "جزر كوكوس (كيلينغ)",
		"ar-KW": "جزر كوكوس (كيلينغ)",
		"ar-OM": "جزر كوكوس (كيلينغ)",
		"ar-YE": "جزر كوكوس (كيلينغ)",
		"ar-IQ": "جزر كوكوس (كيلينغ)",
		"ar-JO": "جزر كوكوس (كيلينغ)",
		"ar-LB": "جزر كوكوس (كيلينغ)",
		"ar-SY": "جزر كوكوس (كيلينغ)",
		"ar-PS": "جزر كوكوس (كيلينغ)",
		"en-US": "Cocos (Keeling) Islands",
		"en-GB": "Cocos (Keeling) Islands",
		"en-IE": "Cocos (Keeling) Islands",
		"en-MT": "Cocos (Keeling) Islands",
		"en-GI": "Cocos (Keeling) Islands",
		"en-CY": "Cocos (Keeling) Islands",
		"en-JE": "Cocos (Keeling) Islands",
		"en-GG": "Cocos (Keeling) Islands",
		"en-IM": "Cocos (Keeling) Islands",
		"en-CA": "Cocos (Keeling) Islands",
		"en-AU": "Cocos (Keeling) Islands",
		"en-NZ": "Cocos (Keeling) Islands",
		"en-ZA": "Cocos (Keeling) Islands",
		"en-IN": "Cocos (Keeling) Islands",
		"en-SG": "Cocos (Keeling) Islands",
		"pt-AO": "Ilhas dos Cocos (Keeling)",
		"pt-MZ": "Ilhas dos Cocos (Keeling)",
		"pt-CV": "Ilhas dos Cocos (Keeling)",
		"pt-GW": "Ilhas dos Cocos (Keeling)",
		"pt-ST": "Ilhas dos Cocos (Keeling)",
		"pt-TL": "Ilhas dos Cocos (Keeling)",
		"pt-MO": "Ilhas dos Cocos (Keeling)",
		"es-ES": "Islas Cocos",
		"es-419": "Islas Cocos",
		"es-AD": "Islas Cocos",
		"es-GI": "Islas Cocos",
		"es-AR": "Islas Cocos",
		"es-BO": "Islas Cocos",
		"es-BR": "Islas Cocos",
		"es-BZ": "Islas Cocos",
		"es-CL": "Islas Cocos",
		"es-CO": "Islas Cocos",
		"es-CR": "Islas Cocos",
		"es-CU": "Islas Cocos",
		"es-DO": "Islas Cocos",
		"es-EC": "Islas Cocos",
		"es-GT": "Islas Cocos",
		"es-HN": "Islas Cocos",
		"es-MX": "Islas Cocos",
		"es-NI": "Islas Cocos",
		"es-PA": "Islas Cocos",
		"es-PE": "Islas Cocos",
		"es-PR": "Islas Cocos",
		"es-PY": "Islas Cocos",
		"es-SV": "Islas Cocos",
		"es-US": "Islas Cocos",
		"es-UY": "Islas Cocos",
		"es-VE": "Islas Cocos",
		"fr-FR": "Îles Cocos",
		"fr-BE": "Îles Cocos",
		"fr-CH": "Îles Cocos",
		"fr-LU": "Îles Cocos",
		"fr-MC": "Îles Cocos",
		"fr-AD": "Îles Cocos",
		"fr-CA": "îles Cocos (Keeling)",
		"it-IT": "Isole Cocos (Keeling)",
		"it-CH": "Isole Cocos (Keeling)",
		"it-SM": "Isole Cocos (Keeling)",
		"it-VA": "Isole Cocos (Keeling)",
		"de-DE": "Kokosinseln",
		"de-AT": "Kokosinseln",
		"de-CH": "Kokosinseln",
		"de-BE": "Kokosinseln",
		"de-LI": "Kokosinseln",
		"de-LU": "Kokosinseln",
		"nl-NL": "Cocoseilanden",
		"nl-BE": "Cocoseilanden",
		"sv-SE": "Kokosöarna",
		"sv-FI": "Kokosöarna",
		"da-DK": "Cocosøerne",
		"nb-NO": "Kokosøyene",
		"nn-NO": "Kokosøyane",
		"fi-FI": "Kookossaaret (Keelingsaaret)",
		"is-IS": "Kókoseyjar (Keeling)",
		"fo-FO": "Kokosoyggjar",
		"et-EE": "Kookossaared",
		"lv-LV": "Kokosu (Kīlinga) salas",
		"lt-LT": "Kokosų (Kilingo) Salos",
		"pl-PL": "Wyspy Kokosowe",
		"cs-CZ": "Kokosové ostrovy",
		"sk-SK": "Kokosové ostrovy",
		"sl-SI": "Kokosovi otoki",
		"hr-HR": "Kokosovi (Keelingovi) Otoci",
		"bs-BA": "Kokosova (Keelingova) ostrva",
		"sr-RS": "Кокосова (Килингова) Острва",
		"sr-BA": "Кокосова (Килинг) острва",
		"sr-ME": "Kokosova (Kilingova) Ostrva",
		"mk-MK": "Кокосови (Килиншки) Острови",
		"bg-BG": "Кокосови острови (острови Кийлинг)",
		"be-BY": "Какосавыя (Кілінг) астравы",
		"uk-UA": "Кокосові (Кілінг) Острови",
		"ru-RU": "Кокосовые о-ва",
		"el-GR": "Νήσοι Κόκος (Κίλινγκ)",
		"el-CY": "Νήσοι Κόκος (Κίλινγκ)",
		"ro-RO": "Insulele Cocos (Keeling)",
		"ro-MD": "Insulele Cocos (Keeling)",
		"hu-HU": "Kókusz (Keeling)-szigetek",
		"sq-AL": "Ishujt Kokos",
		"sq-XK": "Ishujt Kokos",
		"mt-MT": "Gżejjer Cocos (Keeling)",
		"ga-IE": "Oileáin Cocos (Keeling)",
		"cy-GB": "Ynysoedd Cocos (Keeling)",
		"gd-GB": "Na h-Eileanan Chocos (Keeling)",
		"lb-LU": "Kokosinselen",
		"ca-ES": "Illes Cocos (Keeling)",
		"ca-AD": "Illes Cocos (Keeling)",
		"ca-FR": "Illes Cocos (Keeling)",
		"ca-IT": "Illes Cocos (Keeling)",
		"eu-ES": "Cocos (Keeling) uharteak",
		"eu-FR": "Cocos (Keeling) uharteak",
		"gl-ES": "Illas Cocos (Keeling)",
		"tr-TR": "Cocos (Keeling) Adaları",
		"tr-CY": "Cocos (Keeling) Adaları"
	},
	"callingCode": "61",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12
		}
	]
} satisfies Country;
