import type { Country } from './types.js';

export const CHE = {
	"code": "CHE",
	"labels": {
		"pt-BR": "Suíça",
		"pt-PT": "Suíça",
		"es-ES": "Suiza",
		"es-419": "Suiza",
		"es-AR": "Suiza",
		"es-BO": "Suiza",
		"es-BR": "Suiza",
		"es-BZ": "Suiza",
		"es-CL": "Suiza",
		"es-CO": "Suiza",
		"es-CR": "Suiza",
		"es-CU": "Suiza",
		"es-DO": "Suiza",
		"es-EC": "Suiza",
		"es-GT": "Suiza",
		"es-HN": "Suiza",
		"es-MX": "Suiza",
		"es-NI": "Suiza",
		"es-PA": "Suiza",
		"es-PE": "Suiza",
		"es-PR": "Suiza",
		"es-PY": "Suiza",
		"es-SV": "Suiza",
		"es-US": "Suiza",
		"es-UY": "Suiza",
		"es-VE": "Suiza",
		"en-US": "Switzerland",
		"fr-FR": "Suisse",
		"fr-BE": "Suisse",
		"fr-CA": "Suisse",
		"fr-CH": "Suisse",
		"fr-LU": "Suisse",
		"fr-MC": "Suisse",
		"it-IT": "Svizzera",
		"it-CH": "Svizzera",
		"it-SM": "Svizzera",
		"it-VA": "Svizzera",
		"de-DE": "Schweiz",
		"de-AT": "Schweiz",
		"de-CH": "Schweiz",
		"de-BE": "Schweiz",
		"de-LI": "Schweiz",
		"de-LU": "Schweiz"
	},
	"callingCode": "41"
} satisfies Country;
