import type { Country } from './types.js';

export const CHN = {
	"code": "CHN",
	"labels": {
		"pt-BR": "China",
		"pt-PT": "China",
		"es-ES": "China",
		"es-419": "China",
		"es-AR": "China",
		"es-BO": "China",
		"es-BR": "China",
		"es-BZ": "China",
		"es-CL": "China",
		"es-CO": "China",
		"es-CR": "China",
		"es-CU": "China",
		"es-DO": "China",
		"es-EC": "China",
		"es-GT": "China",
		"es-HN": "China",
		"es-MX": "China",
		"es-NI": "China",
		"es-PA": "China",
		"es-PE": "China",
		"es-PR": "China",
		"es-PY": "China",
		"es-SV": "China",
		"es-US": "China",
		"es-UY": "China",
		"es-VE": "China",
		"en-US": "China",
		"fr-FR": "Chine",
		"fr-BE": "Chine",
		"fr-CA": "Chine",
		"fr-CH": "Chine",
		"fr-LU": "Chine",
		"fr-MC": "Chine",
		"it-IT": "Cina",
		"it-CH": "Cina",
		"it-SM": "Cina",
		"it-VA": "Cina",
		"de-DE": "China",
		"de-AT": "China",
		"de-CH": "China",
		"de-BE": "China",
		"de-LI": "China",
		"de-LU": "China"
	},
	"callingCode": "86"
} satisfies Country;
