import type { Country } from './types.js';

export const CIV = {
	"code": "CIV",
	"labels": {
		"pt-BR": "Costa do Marfim",
		"pt-PT": "Côte d’Ivoire (Costa do Marfim)",
		"qu-PE": "Côte d’Ivoire",
		"qu-BO": "Côte d’Ivoire",
		"qu-EC": "Côte d’Ivoire",
		"chr-US": "ᎢᏬᎵ ᎾᎿ ᎠᎹᏳᎶᏗ",
		"hi-IN": "कोत दिवुआर",
		"bn-IN": "কোট ডি‘আইভোর",
		"bn-BD": "কোট ডি‘আইভোর",
		"ta-IN": "கோட் தி’வாயர்",
		"ta-LK": "கோட் தி’வாயர்",
		"ta-SG": "கோட் தி’வாயர்",
		"ta-MY": "கோட் தி’வாயர்",
		"te-IN": "కోట్ డి ఐవోర్",
		"mr-IN": "कोत द’ईवोआर",
		"gu-IN": "કોટ ડીઆઇવરી",
		"kn-IN": "ಕೋತ್ ದ್‘ಇವಾರ್",
		"ml-IN": "കോട്ട് ഡി വാർ",
		"pa-IN": "ਕੋਟ ਡੀਵੋਆਰ",
		"ur-IN": "کوٹ ڈی آئیوری",
		"ur-PK": "کوٹ ڈی آئیوری",
		"or-IN": "କୋତ୍ ଡି ଭ୍ଵାର୍",
		"as-IN": "কোটে ডি আইভৰ",
		"ne-IN": "कोट दिभोर",
		"ne-NP": "कोट दिभोर",
		"si-LK": "කෝට් දි අයිවරි",
		"kok-IN": "कोत द’ईवोआर",
		"ks-IN": "کوٹ ڈلوائر",
		"brx-IN": "कट दिभवेर",
		"mai-IN": "कोट डी आइवर",
		"dz-BT": "ཀོ་ཊེ་ ཌི་ཨི་ཝོ་རེ",
		"ja-JP": "コートジボワール",
		"ko-KR": "코트디부아르",
		"ko-KP": "코트디부아르",
		"zh-CN": "科特迪瓦",
		"zh-Hans-CN": "科特迪瓦",
		"zh-Hant-TW": "象牙海岸",
		"zh-TW": "象牙海岸",
		"zh-HK": "科特迪瓦",
		"zh-MO": "科特迪瓦",
		"zh-SG": "科特迪瓦",
		"yue-Hant-HK": "象牙海岸",
		"yue-Hans-CN": "象牙海岸",
		"mn-MN": "Кот-д’Ивуар",
		"ug-CN": "كوتې دې ئىۋوئىر",
		"th-TH": "โกตดิวัวร์",
		"lo-LA": "ໂຄຕີ ວົວ",
		"km-KH": "កូតឌីវ័រ",
		"my-MM": "ကို့တ် ဒီဗွာ",
		"vi-VN": "Côte d’Ivoire",
		"id-ID": "Côte d’Ivoire",
		"ms-MY": "Cote d’Ivoire",
		"ms-SG": "Cote d’Ivoire",
		"ms-BN": "Cote d’Ivoire",
		"jv-ID": "Pasisir Gadhing",
		"fil-PH": "Côte d’Ivoire",
		"ceb-PH": "Cote d’Ivoire",
		"ka-GE": "კოტ-დივუარი",
		"hy-AM": "Կոտ դ՚Իվուար",
		"az-AZ": "Kotd’ivuar",
		"az-Cyrl-AZ": "Котд’ивуар",
		"kk-KZ": "Кот-д’Ивуар",
		"ky-KG": "Кот-д’Ивуар",
		"uz-UZ": "Kot-d’Ivuar",
		"tg-TJ": "Кот-д’Ивуар",
		"tk-TM": "Kot-d’Iwuar",
		"fa-IR": "ساحل عاج",
		"fa-AF": "ساحل عاج",
		"ps-AF": "د عاج ساحل",
		"ps-PK": "د عاج ساحل",
		"he-IL": "חוף השנהב",
		"ar-SA": "ساحل العاج",
		"ar-AE": "ساحل العاج",
		"ar-QA": "ساحل العاج",
		"ar-BH": "ساحل العاج",
		"ar-KW": "ساحل العاج",
		"ar-OM": "ساحل العاج",
		"ar-YE": "ساحل العاج",
		"ar-IQ": "ساحل العاج",
		"ar-JO": "ساحل العاج",
		"ar-LB": "ساحل العاج",
		"ar-SY": "ساحل العاج",
		"ar-PS": "ساحل العاج",
		"en-US": "Côte d’Ivoire",
		"en-GB": "Côte d’Ivoire",
		"en-IE": "Côte d’Ivoire",
		"en-MT": "Côte d’Ivoire",
		"en-GI": "Côte d’Ivoire",
		"en-CY": "Côte d’Ivoire",
		"en-JE": "Côte d’Ivoire",
		"en-GG": "Côte d’Ivoire",
		"en-IM": "Côte d’Ivoire",
		"en-CA": "Côte d’Ivoire",
		"en-AU": "Côte d’Ivoire",
		"en-NZ": "Côte d’Ivoire",
		"en-ZA": "Côte d’Ivoire",
		"en-IN": "Côte d’Ivoire",
		"en-SG": "Côte d’Ivoire",
		"pt-AO": "Côte d’Ivoire (Costa do Marfim)",
		"pt-MZ": "Côte d’Ivoire (Costa do Marfim)",
		"pt-CV": "Côte d’Ivoire (Costa do Marfim)",
		"pt-GW": "Côte d’Ivoire (Costa do Marfim)",
		"pt-ST": "Côte d’Ivoire (Costa do Marfim)",
		"pt-TL": "Côte d’Ivoire (Costa do Marfim)",
		"pt-MO": "Côte d’Ivoire (Costa do Marfim)",
		"es-ES": "Côte d’Ivoire",
		"es-419": "Costa de Marfil",
		"es-AD": "Côte d’Ivoire",
		"es-GI": "Côte d’Ivoire",
		"es-AR": "Costa de Marfil",
		"es-BO": "Costa de Marfil",
		"es-BR": "Costa de Marfil",
		"es-BZ": "Costa de Marfil",
		"es-CL": "Costa de Marfil",
		"es-CO": "Costa de Marfil",
		"es-CR": "Costa de Marfil",
		"es-CU": "Costa de Marfil",
		"es-DO": "Costa de Marfil",
		"es-EC": "Costa de Marfil",
		"es-GT": "Costa de Marfil",
		"es-HN": "Costa de Marfil",
		"es-MX": "Côte d’Ivoire",
		"es-NI": "Costa de Marfil",
		"es-PA": "Costa de Marfil",
		"es-PE": "Costa de Marfil",
		"es-PR": "Costa de Marfil",
		"es-PY": "Costa de Marfil",
		"es-SV": "Costa de Marfil",
		"es-US": "Costa de Marfil",
		"es-UY": "Costa de Marfil",
		"es-VE": "Costa de Marfil",
		"fr-FR": "Côte d’Ivoire",
		"fr-BE": "Côte d’Ivoire",
		"fr-CH": "Côte d’Ivoire",
		"fr-LU": "Côte d’Ivoire",
		"fr-MC": "Côte d’Ivoire",
		"fr-AD": "Côte d’Ivoire",
		"fr-CA": "Côte d’Ivoire",
		"it-IT": "Costa d’Avorio",
		"it-CH": "Costa d’Avorio",
		"it-SM": "Costa d’Avorio",
		"it-VA": "Costa d’Avorio",
		"de-DE": "Côte d’Ivoire",
		"de-AT": "Côte d’Ivoire",
		"de-CH": "Côte d’Ivoire",
		"de-BE": "Côte d’Ivoire",
		"de-LI": "Côte d’Ivoire",
		"de-LU": "Côte d’Ivoire",
		"nl-NL": "Ivoorkust",
		"nl-BE": "Ivoorkust",
		"sv-SE": "Elfenbenskusten",
		"sv-FI": "Elfenbenskusten",
		"da-DK": "Elfenbenskysten",
		"nb-NO": "Elfenbenskysten",
		"nn-NO": "Elfenbeinskysten",
		"fi-FI": "Norsunluurannikko",
		"is-IS": "Fílabeinsströndin",
		"fo-FO": "Fílabeinsstrondin",
		"et-EE": "Elevandiluurannik",
		"lv-LV": "Kotdivuāra",
		"lt-LT": "Dramblio Kaulo Krantas",
		"pl-PL": "Côte d’Ivoire",
		"cs-CZ": "Pobřeží slonoviny",
		"sk-SK": "Pobrežie Slonoviny",
		"sl-SI": "Slonokoščena obala",
		"hr-HR": "Obala Bjelokosti",
		"bs-BA": "Obala Slonovače",
		"sr-RS": "Обала Слоноваче (Кот д’Ивоар)",
		"sr-BA": "Обала Слоноваче (Кот д’Ивоар)",
		"sr-ME": "Obala Slonovače (Kot d’Ivoar)",
		"mk-MK": "Брегот на Слоновата Коска",
		"bg-BG": "Кот д’Ивоар",
		"be-BY": "Кот-д’Івуар",
		"uk-UA": "Кот-дʼІвуар",
		"ru-RU": "Кот-д’Ивуар",
		"el-GR": "Ακτή Ελεφαντοστού",
		"el-CY": "Ακτή Ελεφαντοστού",
		"ro-RO": "Côte d’Ivoire",
		"ro-MD": "Côte d’Ivoire",
		"hu-HU": "Elefántcsontpart",
		"sq-AL": "Côte d’Ivoire",
		"sq-XK": "Côte d’Ivoire",
		"mt-MT": "il-Kosta tal-Avorju",
		"ga-IE": "An Cósta Eabhair",
		"cy-GB": "Côte d’Ivoire",
		"gd-GB": "Côte d’Ivoire",
		"lb-LU": "Côte d’Ivoire",
		"ca-ES": "Côte d’Ivoire",
		"ca-AD": "Côte d’Ivoire",
		"ca-FR": "Côte d’Ivoire",
		"ca-IT": "Côte d’Ivoire",
		"eu-ES": "Boli Kosta",
		"eu-FR": "Boli Kosta",
		"gl-ES": "Côte d’Ivoire",
		"tr-TR": "Côte d’Ivoire",
		"tr-CY": "Côte d’Ivoire"
	},
	"callingCode": "225",
	"phoneMasks": [
		{
			"mask": "## ## # #####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "## ## ## ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"0"
			]
		}
	]
} satisfies Country;
