import type { Country } from './types.js';

export const CMR = {
	"code": "CMR",
	"labels": {
		"pt-BR": "Camarões",
		"pt-PT": "Camarões",
		"es-ES": "Camerún",
		"es-419": "Camerún",
		"es-AR": "Camerún",
		"es-BO": "Camerún",
		"es-BR": "Camerún",
		"es-BZ": "Camerún",
		"es-CL": "Camerún",
		"es-CO": "Camerún",
		"es-CR": "Camerún",
		"es-CU": "Camerún",
		"es-DO": "Camerún",
		"es-EC": "Camerún",
		"es-GT": "Camerún",
		"es-HN": "Camerún",
		"es-MX": "Camerún",
		"es-NI": "Camerún",
		"es-PA": "Camerún",
		"es-PE": "Camerún",
		"es-PR": "Camerún",
		"es-PY": "Camerún",
		"es-SV": "Camerún",
		"es-US": "Camerún",
		"es-UY": "Camerún",
		"es-VE": "Camerún",
		"en-US": "Cameroon",
		"fr-FR": "Cameroun",
		"fr-BE": "Cameroun",
		"fr-CA": "Cameroun",
		"fr-CH": "Cameroun",
		"fr-LU": "Cameroun",
		"fr-MC": "Cameroun",
		"it-IT": "Camerun",
		"it-CH": "Camerun",
		"it-SM": "Camerun",
		"it-VA": "Camerun",
		"de-DE": "Kamerun",
		"de-AT": "Kamerun",
		"de-CH": "Kamerun",
		"de-BE": "Kamerun",
		"de-LI": "Kamerun",
		"de-LU": "Kamerun"
	}
} satisfies Country;
