import type { Country } from './types.js';

export const COG = {
	"code": "COG",
	"labels": {
		"pt-BR": "República do Congo",
		"pt-PT": "Congo-Brazzaville",
		"es-ES": "Congo",
		"es-419": "República del Congo",
		"es-AR": "República del Congo",
		"es-BO": "República del Congo",
		"es-BR": "República del Congo",
		"es-BZ": "República del Congo",
		"es-CL": "República del Congo",
		"es-CO": "República del Congo",
		"es-CR": "República del Congo",
		"es-CU": "República del Congo",
		"es-DO": "República del Congo",
		"es-EC": "República del Congo",
		"es-GT": "República del Congo",
		"es-HN": "República del Congo",
		"es-MX": "República del Congo",
		"es-NI": "República del Congo",
		"es-PA": "República del Congo",
		"es-PE": "República del Congo",
		"es-PR": "República del Congo",
		"es-PY": "República del Congo",
		"es-SV": "República del Congo",
		"es-US": "República del Congo",
		"es-UY": "República del Congo",
		"es-VE": "República del Congo",
		"en-US": "Congo - Brazzaville",
		"fr-FR": "Congo-Brazzaville",
		"fr-BE": "Congo-Brazzaville",
		"fr-CA": "Congo-Brazzaville",
		"fr-CH": "Congo-Brazzaville",
		"fr-LU": "Congo-Brazzaville",
		"fr-MC": "Congo-Brazzaville",
		"it-IT": "Congo-Brazzaville",
		"it-CH": "Congo-Brazzaville",
		"it-SM": "Congo-Brazzaville",
		"it-VA": "Congo-Brazzaville",
		"de-DE": "Kongo-Brazzaville",
		"de-AT": "Kongo-Brazzaville",
		"de-CH": "Kongo-Brazzaville",
		"de-BE": "Kongo-Brazzaville",
		"de-LI": "Kongo-Brazzaville",
		"de-LU": "Kongo-Brazzaville"
	}
} satisfies Country;
