import type { Country } from './types.js';

export const COK = {
	"code": "COK",
	"labels": {
		"pt-BR": "Ilhas Cook",
		"pt-PT": "Ilhas Cook",
		"qu-PE": "Islas Cook",
		"qu-BO": "Islas Cook",
		"qu-EC": "Islas Cook",
		"chr-US": "ᎠᏓᏍᏓᏴᎲᏍᎩ ᏚᎦᏚᏛᎢ",
		"hi-IN": "कुक द्वीपसमूह",
		"bn-IN": "কুক দ্বীপপুঞ্জ",
		"bn-BD": "কুক দ্বীপপুঞ্জ",
		"ta-IN": "குக் தீவுகள்",
		"ta-LK": "குக் தீவுகள்",
		"ta-SG": "குக் தீவுகள்",
		"ta-MY": "குக் தீவுகள்",
		"te-IN": "కుక్ దీవులు",
		"mr-IN": "कुक बेटे",
		"gu-IN": "કુક આઇલેન્ડ્સ",
		"kn-IN": "ಕುಕ್ ದ್ವೀಪಗಳು",
		"ml-IN": "കുക്ക് ദ്വീപുകൾ",
		"pa-IN": "ਕੁੱਕ ਟਾਪੂ",
		"ur-IN": "جزائر کک",
		"ur-PK": "کک آئلینڈز",
		"or-IN": "କୁକ୍‌ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "কুক দ্বীপপুঞ্জ",
		"ne-IN": "कुक टापुहरु",
		"ne-NP": "कुक टापुहरु",
		"si-LK": "කුක් දූපත්",
		"kok-IN": "कुक आयलँड्स",
		"ks-IN": "کُک جٔزیٖرٕ",
		"brx-IN": "कुक द्वीप",
		"mai-IN": "कुक द्वीपसमूह",
		"dz-BT": "ཀུག་གླིང་ཚོམ",
		"ja-JP": "クック諸島",
		"ko-KR": "쿡 제도",
		"ko-KP": "쿡 제도",
		"zh-CN": "库克群岛",
		"zh-Hans-CN": "库克群岛",
		"zh-Hant-TW": "庫克群島",
		"zh-TW": "庫克群島",
		"zh-HK": "庫克群島",
		"zh-MO": "庫克群島",
		"zh-SG": "库克群岛",
		"yue-Hant-HK": "庫克群島",
		"yue-Hans-CN": "库克群岛",
		"mn-MN": "Күүкийн арлууд",
		"ug-CN": "كۇك ئاراللىرى",
		"th-TH": "หมู่เกาะคุก",
		"lo-LA": "ໝູ່ເກາະຄຸກ",
		"km-KH": "កោះ​ខូក",
		"my-MM": "ကွတ် ကျွန်းစု",
		"vi-VN": "Quần đảo Cook",
		"id-ID": "Kepulauan Cook",
		"ms-MY": "Kepulauan Cook",
		"ms-SG": "Kepulauan Cook",
		"ms-BN": "Kepulauan Cook",
		"jv-ID": "Kapuloan Cook",
		"fil-PH": "Cook Islands",
		"ceb-PH": "Cook Islands",
		"ka-GE": "კუკის კუნძულები",
		"hy-AM": "Կուկի կղզիներ",
		"az-AZ": "Kuk adaları",
		"az-Cyrl-AZ": "Кук адалары",
		"kk-KZ": "Кук аралдары",
		"ky-KG": "Кук аралдары",
		"uz-UZ": "Kuk orollari",
		"tg-TJ": "Ҷазираҳои Кук",
		"tk-TM": "Kuk adalary",
		"fa-IR": "جزایر کوک",
		"fa-AF": "جزایر کوک",
		"ps-AF": "کوک ټاپوګان",
		"ps-PK": "کوک ټاپوګان",
		"he-IL": "איי קוק",
		"ar-SA": "جزر كوك",
		"ar-AE": "جزر كوك",
		"ar-QA": "جزر كوك",
		"ar-BH": "جزر كوك",
		"ar-KW": "جزر كوك",
		"ar-OM": "جزر كوك",
		"ar-YE": "جزر كوك",
		"ar-IQ": "جزر كوك",
		"ar-JO": "جزر كوك",
		"ar-LB": "جزر كوك",
		"ar-SY": "جزر كوك",
		"ar-PS": "جزر كوك",
		"en-US": "Cook Islands",
		"en-GB": "Cook Islands",
		"en-IE": "Cook Islands",
		"en-MT": "Cook Islands",
		"en-GI": "Cook Islands",
		"en-CY": "Cook Islands",
		"en-JE": "Cook Islands",
		"en-GG": "Cook Islands",
		"en-IM": "Cook Islands",
		"en-CA": "Cook Islands",
		"en-AU": "Cook Islands",
		"en-NZ": "Cook Islands",
		"en-ZA": "Cook Islands",
		"en-IN": "Cook Islands",
		"en-SG": "Cook Islands",
		"pt-AO": "Ilhas Cook",
		"pt-MZ": "Ilhas Cook",
		"pt-CV": "Ilhas Cook",
		"pt-GW": "Ilhas Cook",
		"pt-ST": "Ilhas Cook",
		"pt-TL": "Ilhas Cook",
		"pt-MO": "Ilhas Cook",
		"es-ES": "Islas Cook",
		"es-419": "Islas Cook",
		"es-AD": "Islas Cook",
		"es-GI": "Islas Cook",
		"es-AR": "Islas Cook",
		"es-BO": "Islas Cook",
		"es-BR": "Islas Cook",
		"es-BZ": "Islas Cook",
		"es-CL": "Islas Cook",
		"es-CO": "Islas Cook",
		"es-CR": "Islas Cook",
		"es-CU": "Islas Cook",
		"es-DO": "Islas Cook",
		"es-EC": "Islas Cook",
		"es-GT": "Islas Cook",
		"es-HN": "Islas Cook",
		"es-MX": "Islas Cook",
		"es-NI": "Islas Cook",
		"es-PA": "Islas Cook",
		"es-PE": "Islas Cook",
		"es-PR": "Islas Cook",
		"es-PY": "Islas Cook",
		"es-SV": "Islas Cook",
		"es-US": "Islas Cook",
		"es-UY": "Islas Cook",
		"es-VE": "Islas Cook",
		"fr-FR": "Îles Cook",
		"fr-BE": "Îles Cook",
		"fr-CH": "Îles Cook",
		"fr-LU": "Îles Cook",
		"fr-MC": "Îles Cook",
		"fr-AD": "Îles Cook",
		"fr-CA": "îles Cook",
		"it-IT": "Isole Cook",
		"it-CH": "Isole Cook",
		"it-SM": "Isole Cook",
		"it-VA": "Isole Cook",
		"de-DE": "Cookinseln",
		"de-AT": "Cookinseln",
		"de-CH": "Cookinseln",
		"de-BE": "Cookinseln",
		"de-LI": "Cookinseln",
		"de-LU": "Cookinseln",
		"nl-NL": "Cookeilanden",
		"nl-BE": "Cookeilanden",
		"sv-SE": "Cooköarna",
		"sv-FI": "Cooköarna",
		"da-DK": "Cookøerne",
		"nb-NO": "Cookøyene",
		"nn-NO": "Cookøyane",
		"fi-FI": "Cookinsaaret",
		"is-IS": "Cooks-eyjar",
		"fo-FO": "Cooksoyggjar",
		"et-EE": "Cooki saared",
		"lv-LV": "Kuka salas",
		"lt-LT": "Kuko Salos",
		"pl-PL": "Wyspy Cooka",
		"cs-CZ": "Cookovy ostrovy",
		"sk-SK": "Cookove ostrovy",
		"sl-SI": "Cookovi otoki",
		"hr-HR": "Cookovi Otoci",
		"bs-BA": "Kukova ostrva",
		"sr-RS": "Кукова Острва",
		"sr-BA": "Кукова Острва",
		"sr-ME": "Kukova Ostrva",
		"mk-MK": "Кукови Острови",
		"bg-BG": "острови Кук",
		"be-BY": "Астравы Кука",
		"uk-UA": "Острови Кука",
		"ru-RU": "о-ва Кука",
		"el-GR": "Νήσοι Κουκ",
		"el-CY": "Νήσοι Κουκ",
		"ro-RO": "Insulele Cook",
		"ro-MD": "Insulele Cook",
		"hu-HU": "Cook-szigetek",
		"sq-AL": "Ishujt Kuk",
		"sq-XK": "Ishujt Kuk",
		"mt-MT": "Gżejjer Cook",
		"ga-IE": "Oileáin Cook",
		"cy-GB": "Ynysoedd Cook",
		"gd-GB": "Eileanan Cook",
		"lb-LU": "Cookinselen",
		"ca-ES": "Illes Cook",
		"ca-AD": "Illes Cook",
		"ca-FR": "Illes Cook",
		"ca-IT": "Illes Cook",
		"eu-ES": "Cook uharteak",
		"eu-FR": "Cook uharteak",
		"gl-ES": "Illas Cook",
		"tr-TR": "Cook Adaları",
		"tr-CY": "Cook Adaları"
	},
	"callingCode": "682",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5,
			"leadingDigits": [
				"[2-578]"
			]
		}
	]
} satisfies Country;
