import type { Country } from './types.js';

export const COK = {
	"code": "COK",
	"labels": {
		"pt-BR": "Ilhas Cook",
		"pt-PT": "Ilhas Cook",
		"es-ES": "Islas Cook",
		"es-419": "Islas Cook",
		"es-AR": "Islas Cook",
		"es-BO": "Islas Cook",
		"es-BR": "Islas Cook",
		"es-BZ": "Islas Cook",
		"es-CL": "Islas Cook",
		"es-CO": "Islas Cook",
		"es-CR": "Islas Cook",
		"es-CU": "Islas Cook",
		"es-DO": "Islas Cook",
		"es-EC": "Islas Cook",
		"es-GT": "Islas Cook",
		"es-HN": "Islas Cook",
		"es-MX": "Islas Cook",
		"es-NI": "Islas Cook",
		"es-PA": "Islas Cook",
		"es-PE": "Islas Cook",
		"es-PR": "Islas Cook",
		"es-PY": "Islas Cook",
		"es-SV": "Islas Cook",
		"es-US": "Islas Cook",
		"es-UY": "Islas Cook",
		"es-VE": "Islas Cook",
		"en-US": "Cook Islands",
		"fr-FR": "Îles Cook",
		"fr-BE": "Îles Cook",
		"fr-CA": "îles Cook",
		"fr-CH": "Îles Cook",
		"fr-LU": "Îles Cook",
		"fr-MC": "Îles Cook",
		"it-IT": "Isole Cook",
		"it-CH": "Isole Cook",
		"it-SM": "Isole Cook",
		"it-VA": "Isole Cook",
		"de-DE": "Cookinseln",
		"de-AT": "Cookinseln",
		"de-CH": "Cookinseln",
		"de-BE": "Cookinseln",
		"de-LI": "Cookinseln",
		"de-LU": "Cookinseln"
	}
} satisfies Country;
