import type { Country } from './types.js';

export const COL = {
	"code": "COL",
	"labels": {
		"pt-BR": "Colômbia",
		"pt-PT": "Colômbia",
		"qu-PE": "Colombia",
		"qu-BO": "Colombia",
		"qu-EC": "Colombia",
		"chr-US": "ᎪᎸᎻᏈᎢᎠ",
		"hi-IN": "कोलंबिया",
		"bn-IN": "কলম্বিয়া",
		"bn-BD": "কলম্বিয়া",
		"ta-IN": "கொலம்பியா",
		"ta-LK": "கொலம்பியா",
		"ta-SG": "கொலம்பியா",
		"ta-MY": "கொலம்பியா",
		"te-IN": "కొలంబియా",
		"mr-IN": "कोलम्बिया",
		"gu-IN": "કોલમ્બિયા",
		"kn-IN": "ಕೊಲಂಬಿಯಾ",
		"ml-IN": "കൊളംബിയ",
		"pa-IN": "ਕੋਲੰਬੀਆ",
		"ur-IN": "کولمبیا",
		"ur-PK": "کولمبیا",
		"or-IN": "କଲମ୍ବିଆ",
		"as-IN": "কলম্বিয়া",
		"ne-IN": "कोलोम्बिया",
		"ne-NP": "कोलोम्बिया",
		"si-LK": "කොළොම්බියාව",
		"kok-IN": "कोलंबिया",
		"ks-IN": "کولَمبِیا",
		"brx-IN": "कलम्बिया",
		"mai-IN": "कोलंबिया",
		"dz-BT": "ཀོ་ལོམ་བྷི་ཡ",
		"ja-JP": "コロンビア",
		"ko-KR": "콜롬비아",
		"ko-KP": "콜롬비아",
		"zh-CN": "哥伦比亚",
		"zh-Hans-CN": "哥伦比亚",
		"zh-Hant-TW": "哥倫比亞",
		"zh-TW": "哥倫比亞",
		"zh-HK": "哥倫比亞",
		"zh-MO": "哥倫比亞",
		"zh-SG": "哥伦比亚",
		"yue-Hant-HK": "哥倫比亞",
		"yue-Hans-CN": "哥伦比亚",
		"mn-MN": "Колумби",
		"ug-CN": "كولومبىيە",
		"th-TH": "โคลอมเบีย",
		"lo-LA": "ໂຄລົມເບຍ",
		"km-KH": "កូឡុំប៊ី",
		"my-MM": "ကိုလံဘီယာ",
		"vi-VN": "Colombia",
		"id-ID": "Kolombia",
		"ms-MY": "Colombia",
		"ms-SG": "Colombia",
		"ms-BN": "Colombia",
		"jv-ID": "Kolombia",
		"fil-PH": "Colombia",
		"ceb-PH": "Colombia",
		"ka-GE": "კოლუმბია",
		"hy-AM": "Կոլումբիա",
		"az-AZ": "Kolumbiya",
		"az-Cyrl-AZ": "Колумбија",
		"kk-KZ": "Колумбия",
		"ky-KG": "Колумбия",
		"uz-UZ": "Kolumbiya",
		"tg-TJ": "Колумбия",
		"tk-TM": "Kolumbiýa",
		"fa-IR": "کلمبیا",
		"fa-AF": "کولمبیا",
		"ps-AF": "کولمبیا",
		"ps-PK": "کولمبیا",
		"he-IL": "קולומביה",
		"ar-SA": "كولومبيا",
		"ar-AE": "كولومبيا",
		"ar-QA": "كولومبيا",
		"ar-BH": "كولومبيا",
		"ar-KW": "كولومبيا",
		"ar-OM": "كولومبيا",
		"ar-YE": "كولومبيا",
		"ar-IQ": "كولومبيا",
		"ar-JO": "كولومبيا",
		"ar-LB": "كولومبيا",
		"ar-SY": "كولومبيا",
		"ar-PS": "كولومبيا",
		"en-US": "Colombia",
		"en-GB": "Colombia",
		"en-IE": "Colombia",
		"en-MT": "Colombia",
		"en-GI": "Colombia",
		"en-CY": "Colombia",
		"en-JE": "Colombia",
		"en-GG": "Colombia",
		"en-IM": "Colombia",
		"en-CA": "Colombia",
		"en-AU": "Colombia",
		"en-NZ": "Colombia",
		"en-ZA": "Colombia",
		"en-IN": "Colombia",
		"en-SG": "Colombia",
		"pt-AO": "Colômbia",
		"pt-MZ": "Colômbia",
		"pt-CV": "Colômbia",
		"pt-GW": "Colômbia",
		"pt-ST": "Colômbia",
		"pt-TL": "Colômbia",
		"pt-MO": "Colômbia",
		"es-ES": "Colombia",
		"es-419": "Colombia",
		"es-AD": "Colombia",
		"es-GI": "Colombia",
		"es-AR": "Colombia",
		"es-BO": "Colombia",
		"es-BR": "Colombia",
		"es-BZ": "Colombia",
		"es-CL": "Colombia",
		"es-CO": "Colombia",
		"es-CR": "Colombia",
		"es-CU": "Colombia",
		"es-DO": "Colombia",
		"es-EC": "Colombia",
		"es-GT": "Colombia",
		"es-HN": "Colombia",
		"es-MX": "Colombia",
		"es-NI": "Colombia",
		"es-PA": "Colombia",
		"es-PE": "Colombia",
		"es-PR": "Colombia",
		"es-PY": "Colombia",
		"es-SV": "Colombia",
		"es-US": "Colombia",
		"es-UY": "Colombia",
		"es-VE": "Colombia",
		"fr-FR": "Colombie",
		"fr-BE": "Colombie",
		"fr-CH": "Colombie",
		"fr-LU": "Colombie",
		"fr-MC": "Colombie",
		"fr-AD": "Colombie",
		"fr-CA": "Colombie",
		"it-IT": "Colombia",
		"it-CH": "Colombia",
		"it-SM": "Colombia",
		"it-VA": "Colombia",
		"de-DE": "Kolumbien",
		"de-AT": "Kolumbien",
		"de-CH": "Kolumbien",
		"de-BE": "Kolumbien",
		"de-LI": "Kolumbien",
		"de-LU": "Kolumbien",
		"nl-NL": "Colombia",
		"nl-BE": "Colombia",
		"sv-SE": "Colombia",
		"sv-FI": "Colombia",
		"da-DK": "Colombia",
		"nb-NO": "Colombia",
		"nn-NO": "Colombia",
		"fi-FI": "Kolumbia",
		"is-IS": "Kólumbía",
		"fo-FO": "Kolombia",
		"et-EE": "Colombia",
		"lv-LV": "Kolumbija",
		"lt-LT": "Kolumbija",
		"pl-PL": "Kolumbia",
		"cs-CZ": "Kolumbie",
		"sk-SK": "Kolumbia",
		"sl-SI": "Kolumbija",
		"hr-HR": "Kolumbija",
		"bs-BA": "Kolumbija",
		"sr-RS": "Колумбија",
		"sr-BA": "Колумбија",
		"sr-ME": "Kolumbija",
		"mk-MK": "Колумбија",
		"bg-BG": "Колумбия",
		"be-BY": "Калумбія",
		"uk-UA": "Колумбія",
		"ru-RU": "Колумбия",
		"el-GR": "Κολομβία",
		"el-CY": "Κολομβία",
		"ro-RO": "Columbia",
		"ro-MD": "Columbia",
		"hu-HU": "Kolumbia",
		"sq-AL": "Kolumbi",
		"sq-XK": "Kolumbi",
		"mt-MT": "il-Kolombja",
		"ga-IE": "an Cholóim",
		"cy-GB": "Colombia",
		"gd-GB": "Coloimbia",
		"lb-LU": "Kolumbien",
		"ca-ES": "Colòmbia",
		"ca-AD": "Colòmbia",
		"ca-FR": "Colòmbia",
		"ca-IT": "Colòmbia",
		"eu-ES": "Kolonbia",
		"eu-FR": "Kolonbia",
		"gl-ES": "Colombia",
		"tr-TR": "Kolombiya",
		"tr-CY": "Kolombiya"
	},
	"callingCode": "57",
	"phoneMasks": [
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"46"
			]
		},
		{
			"mask": "(###) #######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"6|90"
			]
		},
		{
			"mask": "### #######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"3[0-357]|91"
			]
		},
		{
			"mask": "#-###-#######",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"1"
			]
		}
	]
} satisfies Country;
