import type { Country } from './types.js';

export const COM = {
	"code": "COM",
	"labels": {
		"pt-BR": "Comores",
		"pt-PT": "Comores",
		"es-ES": "Comoras",
		"es-419": "Comoras",
		"es-AR": "Comoras",
		"es-BO": "Comoras",
		"es-BR": "Comoras",
		"es-BZ": "Comoras",
		"es-CL": "Comoras",
		"es-CO": "Comoras",
		"es-CR": "Comoras",
		"es-CU": "Comoras",
		"es-DO": "Comoras",
		"es-EC": "Comoras",
		"es-GT": "Comoras",
		"es-HN": "Comoras",
		"es-MX": "Comoras",
		"es-NI": "Comoras",
		"es-PA": "Comoras",
		"es-PE": "Comoras",
		"es-PR": "Comoras",
		"es-PY": "Comoras",
		"es-SV": "Comoras",
		"es-US": "Comoras",
		"es-UY": "Comoras",
		"es-VE": "Comoras",
		"en-US": "Comoros",
		"fr-FR": "Comores",
		"fr-BE": "Comores",
		"fr-CA": "Comores",
		"fr-CH": "Comores",
		"fr-LU": "Comores",
		"fr-MC": "Comores",
		"it-IT": "Comore",
		"it-CH": "Comore",
		"it-SM": "Comore",
		"it-VA": "Comore",
		"de-DE": "Komoren",
		"de-AT": "Komoren",
		"de-CH": "Komoren",
		"de-BE": "Komoren",
		"de-LI": "Komoren",
		"de-LU": "Komoren"
	}
} satisfies Country;
