import type { Country } from './types.js';

export const CRI = {
	"code": "CRI",
	"labels": {
		"pt-BR": "Costa Rica",
		"pt-PT": "Costa Rica",
		"es-ES": "Costa Rica",
		"es-419": "Costa Rica",
		"es-AR": "Costa Rica",
		"es-BO": "Costa Rica",
		"es-BR": "Costa Rica",
		"es-BZ": "Costa Rica",
		"es-CL": "Costa Rica",
		"es-CO": "Costa Rica",
		"es-CR": "Costa Rica",
		"es-CU": "Costa Rica",
		"es-DO": "Costa Rica",
		"es-EC": "Costa Rica",
		"es-GT": "Costa Rica",
		"es-HN": "Costa Rica",
		"es-MX": "Costa Rica",
		"es-NI": "Costa Rica",
		"es-PA": "Costa Rica",
		"es-PE": "Costa Rica",
		"es-PR": "Costa Rica",
		"es-PY": "Costa Rica",
		"es-SV": "Costa Rica",
		"es-US": "Costa Rica",
		"es-UY": "Costa Rica",
		"es-VE": "Costa Rica",
		"en-US": "Costa Rica",
		"fr-FR": "Costa Rica",
		"fr-BE": "Costa Rica",
		"fr-CA": "Costa Rica",
		"fr-CH": "Costa Rica",
		"fr-LU": "Costa Rica",
		"fr-MC": "Costa Rica",
		"it-IT": "Costa Rica",
		"it-CH": "Costa Rica",
		"it-SM": "Costa Rica",
		"it-VA": "Costa Rica",
		"de-DE": "Costa Rica",
		"de-AT": "Costa Rica",
		"de-CH": "Costa Rica",
		"de-BE": "Costa Rica",
		"de-LI": "Costa Rica",
		"de-LU": "Costa Rica"
	}
} satisfies Country;
