import type { Country } from './types.js';

export const CUB = {
	"code": "CUB",
	"labels": {
		"pt-BR": "Cuba",
		"pt-PT": "Cuba",
		"qu-PE": "Cuba",
		"qu-BO": "Cuba",
		"qu-EC": "Cuba",
		"chr-US": "ᎫᏆ",
		"hi-IN": "क्यूबा",
		"bn-IN": "কিউবা",
		"bn-BD": "কিউবা",
		"ta-IN": "கியூபா",
		"ta-LK": "கியூபா",
		"ta-SG": "கியூபா",
		"ta-MY": "கியூபா",
		"te-IN": "క్యూబా",
		"mr-IN": "क्यूबा",
		"gu-IN": "ક્યુબા",
		"kn-IN": "ಕ್ಯೂಬಾ",
		"ml-IN": "ക്യൂബ",
		"pa-IN": "ਕਿਊਬਾ",
		"ur-IN": "کیوبا",
		"ur-PK": "کیوبا",
		"or-IN": "କ‍୍ୟୁବା",
		"as-IN": "কিউবা",
		"ne-IN": "क्युबा",
		"ne-NP": "क्युबा",
		"si-LK": "කියුබාව",
		"kok-IN": "क्युबा",
		"ks-IN": "کیوٗبا",
		"brx-IN": "क्यूबा",
		"mai-IN": "क्यूबा",
		"dz-BT": "ཀིའུ་བྷ",
		"ja-JP": "キューバ",
		"ko-KR": "쿠바",
		"ko-KP": "쿠바",
		"zh-CN": "古巴",
		"zh-Hans-CN": "古巴",
		"zh-Hant-TW": "古巴",
		"zh-TW": "古巴",
		"zh-HK": "古巴",
		"zh-MO": "古巴",
		"zh-SG": "古巴",
		"yue-Hant-HK": "古巴",
		"yue-Hans-CN": "古巴",
		"mn-MN": "Куба",
		"ug-CN": "كۇبا",
		"th-TH": "คิวบา",
		"lo-LA": "ຄິວບາ",
		"km-KH": "គុយបា",
		"my-MM": "ကျူးဘား",
		"vi-VN": "Cuba",
		"id-ID": "Kuba",
		"ms-MY": "Cuba",
		"ms-SG": "Cuba",
		"ms-BN": "Cuba",
		"jv-ID": "Kuba",
		"fil-PH": "Cuba",
		"ceb-PH": "Cuba",
		"ka-GE": "კუბა",
		"hy-AM": "Կուբա",
		"az-AZ": "Kuba",
		"az-Cyrl-AZ": "Куба",
		"kk-KZ": "Куба",
		"ky-KG": "Куба",
		"uz-UZ": "Kuba",
		"tg-TJ": "Куба",
		"tk-TM": "Kuba",
		"fa-IR": "کوبا",
		"fa-AF": "کیوبا",
		"ps-AF": "کیوبا",
		"ps-PK": "کیوبا",
		"he-IL": "קובה",
		"ar-SA": "كوبا",
		"ar-AE": "كوبا",
		"ar-QA": "كوبا",
		"ar-BH": "كوبا",
		"ar-KW": "كوبا",
		"ar-OM": "كوبا",
		"ar-YE": "كوبا",
		"ar-IQ": "كوبا",
		"ar-JO": "كوبا",
		"ar-LB": "كوبا",
		"ar-SY": "كوبا",
		"ar-PS": "كوبا",
		"en-US": "Cuba",
		"en-GB": "Cuba",
		"en-IE": "Cuba",
		"en-MT": "Cuba",
		"en-GI": "Cuba",
		"en-CY": "Cuba",
		"en-JE": "Cuba",
		"en-GG": "Cuba",
		"en-IM": "Cuba",
		"en-CA": "Cuba",
		"en-AU": "Cuba",
		"en-NZ": "Cuba",
		"en-ZA": "Cuba",
		"en-IN": "Cuba",
		"en-SG": "Cuba",
		"pt-AO": "Cuba",
		"pt-MZ": "Cuba",
		"pt-CV": "Cuba",
		"pt-GW": "Cuba",
		"pt-ST": "Cuba",
		"pt-TL": "Cuba",
		"pt-MO": "Cuba",
		"es-ES": "Cuba",
		"es-419": "Cuba",
		"es-AD": "Cuba",
		"es-GI": "Cuba",
		"es-AR": "Cuba",
		"es-BO": "Cuba",
		"es-BR": "Cuba",
		"es-BZ": "Cuba",
		"es-CL": "Cuba",
		"es-CO": "Cuba",
		"es-CR": "Cuba",
		"es-CU": "Cuba",
		"es-DO": "Cuba",
		"es-EC": "Cuba",
		"es-GT": "Cuba",
		"es-HN": "Cuba",
		"es-MX": "Cuba",
		"es-NI": "Cuba",
		"es-PA": "Cuba",
		"es-PE": "Cuba",
		"es-PR": "Cuba",
		"es-PY": "Cuba",
		"es-SV": "Cuba",
		"es-US": "Cuba",
		"es-UY": "Cuba",
		"es-VE": "Cuba",
		"fr-FR": "Cuba",
		"fr-BE": "Cuba",
		"fr-CH": "Cuba",
		"fr-LU": "Cuba",
		"fr-MC": "Cuba",
		"fr-AD": "Cuba",
		"fr-CA": "Cuba",
		"it-IT": "Cuba",
		"it-CH": "Cuba",
		"it-SM": "Cuba",
		"it-VA": "Cuba",
		"de-DE": "Kuba",
		"de-AT": "Kuba",
		"de-CH": "Kuba",
		"de-BE": "Kuba",
		"de-LI": "Kuba",
		"de-LU": "Kuba",
		"nl-NL": "Cuba",
		"nl-BE": "Cuba",
		"sv-SE": "Kuba",
		"sv-FI": "Kuba",
		"da-DK": "Cuba",
		"nb-NO": "Cuba",
		"nn-NO": "Cuba",
		"fi-FI": "Kuuba",
		"is-IS": "Kúba",
		"fo-FO": "Kuba",
		"et-EE": "Kuuba",
		"lv-LV": "Kuba",
		"lt-LT": "Kuba",
		"pl-PL": "Kuba",
		"cs-CZ": "Kuba",
		"sk-SK": "Kuba",
		"sl-SI": "Kuba",
		"hr-HR": "Kuba",
		"bs-BA": "Kuba",
		"sr-RS": "Куба",
		"sr-BA": "Куба",
		"sr-ME": "Kuba",
		"mk-MK": "Куба",
		"bg-BG": "Куба",
		"be-BY": "Куба",
		"uk-UA": "Куба",
		"ru-RU": "Куба",
		"el-GR": "Κούβα",
		"el-CY": "Κούβα",
		"ro-RO": "Cuba",
		"ro-MD": "Cuba",
		"hu-HU": "Kuba",
		"sq-AL": "Kubë",
		"sq-XK": "Kubë",
		"mt-MT": "Kuba",
		"ga-IE": "Cúba",
		"cy-GB": "Ciwba",
		"gd-GB": "Cùba",
		"lb-LU": "Kuba",
		"ca-ES": "Cuba",
		"ca-AD": "Cuba",
		"ca-FR": "Cuba",
		"ca-IT": "Cuba",
		"eu-ES": "Kuba",
		"eu-FR": "Kuba",
		"gl-ES": "Cuba",
		"tr-TR": "Küba",
		"tr-CY": "Küba"
	},
	"callingCode": "53",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "# #######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"7"
			]
		},
		{
			"mask": "# #######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[56]"
			]
		},
		{
			"mask": "## ######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2[1-4]|[34]"
			]
		},
		{
			"mask": "### #######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
