import type { Country } from './types.js';

export const CUB = {
	"code": "CUB",
	"labels": {
		"pt-BR": "Cuba",
		"pt-PT": "Cuba",
		"es-ES": "Cuba",
		"es-419": "Cuba",
		"es-AR": "Cuba",
		"es-BO": "Cuba",
		"es-BR": "Cuba",
		"es-BZ": "Cuba",
		"es-CL": "Cuba",
		"es-CO": "Cuba",
		"es-CR": "Cuba",
		"es-CU": "Cuba",
		"es-DO": "Cuba",
		"es-EC": "Cuba",
		"es-GT": "Cuba",
		"es-HN": "Cuba",
		"es-MX": "Cuba",
		"es-NI": "Cuba",
		"es-PA": "Cuba",
		"es-PE": "Cuba",
		"es-PR": "Cuba",
		"es-PY": "Cuba",
		"es-SV": "Cuba",
		"es-US": "Cuba",
		"es-UY": "Cuba",
		"es-VE": "Cuba",
		"en-US": "Cuba",
		"fr-FR": "Cuba",
		"fr-BE": "Cuba",
		"fr-CA": "Cuba",
		"fr-CH": "Cuba",
		"fr-LU": "Cuba",
		"fr-MC": "Cuba",
		"it-IT": "Cuba",
		"it-CH": "Cuba",
		"it-SM": "Cuba",
		"it-VA": "Cuba",
		"de-DE": "Kuba",
		"de-AT": "Kuba",
		"de-CH": "Kuba",
		"de-BE": "Kuba",
		"de-LI": "Kuba",
		"de-LU": "Kuba"
	}
} satisfies Country;
