import type { Country } from './types.js';

export const CUW = {
	"code": "CUW",
	"labels": {
		"pt-BR": "Curaçao",
		"pt-PT": "Curaçau",
		"es-ES": "Curazao",
		"es-419": "Curazao",
		"es-AR": "Curazao",
		"es-BO": "Curazao",
		"es-BR": "Curazao",
		"es-BZ": "Curazao",
		"es-CL": "Curazao",
		"es-CO": "Curazao",
		"es-CR": "Curazao",
		"es-CU": "Curazao",
		"es-DO": "Curazao",
		"es-EC": "Curazao",
		"es-GT": "Curazao",
		"es-HN": "Curazao",
		"es-MX": "Curazao",
		"es-NI": "Curazao",
		"es-PA": "Curazao",
		"es-PE": "Curazao",
		"es-PR": "Curazao",
		"es-PY": "Curazao",
		"es-SV": "Curazao",
		"es-US": "Curazao",
		"es-UY": "Curazao",
		"es-VE": "Curazao",
		"en-US": "Curaçao",
		"fr-FR": "Curaçao",
		"fr-BE": "Curaçao",
		"fr-CA": "Curaçao",
		"fr-CH": "Curaçao",
		"fr-LU": "Curaçao",
		"fr-MC": "Curaçao",
		"it-IT": "Curaçao",
		"it-CH": "Curaçao",
		"it-SM": "Curaçao",
		"it-VA": "Curaçao",
		"de-DE": "Curaçao",
		"de-AT": "Curaçao",
		"de-CH": "Curaçao",
		"de-BE": "Curaçao",
		"de-LI": "Curaçao",
		"de-LU": "Curaçao"
	}
} satisfies Country;
