import type { Country } from './types.js';

export const CXR = {
	"code": "CXR",
	"labels": {
		"pt-BR": "Ilha Christmas",
		"pt-PT": "Ilha do Natal",
		"qu-PE": "Isla Christmas",
		"qu-BO": "Isla Christmas",
		"qu-EC": "Isla Christmas",
		"chr-US": "ᏓᏂᏍᏓᏲᎯᎲ ᎤᎦᏚᏛᎢ",
		"hi-IN": "क्रिसमस द्वीप",
		"bn-IN": "ক্রিসমাস দ্বীপ",
		"bn-BD": "ক্রিসমাস দ্বীপ",
		"ta-IN": "கிறிஸ்துமஸ் தீவு",
		"ta-LK": "கிறிஸ்துமஸ் தீவு",
		"ta-SG": "கிறிஸ்துமஸ் தீவு",
		"ta-MY": "கிறிஸ்துமஸ் தீவு",
		"te-IN": "క్రిస్మస్ దీవి",
		"mr-IN": "ख्रिसमस बेट",
		"gu-IN": "ક્રિસમસ આઇલેન્ડ",
		"kn-IN": "ಕ್ರಿಸ್ಮಸ್ ದ್ವೀಪ",
		"ml-IN": "ക്രിസ്മസ് ദ്വീപ്",
		"pa-IN": "ਕ੍ਰਿਸਮਿਸ ਟਾਪੂ",
		"ur-IN": "جزیرہ کرسمس",
		"ur-PK": "جزیرہ کرسمس",
		"or-IN": "ଖ୍ରୀଷ୍ଟମାସ ଦ୍ୱୀପ",
		"as-IN": "খ্ৰীষ্টমাছ দ্বীপ",
		"ne-IN": "क्रिष्टमस टापु",
		"ne-NP": "क्रिष्टमस टापु",
		"si-LK": "ක්‍රිස්මස් දූපත",
		"kok-IN": "क्रिसमस आयलँड",
		"ks-IN": "کرِسمَس جٔزیٖرٕ",
		"brx-IN": "ख्रिसमास द्वीपफोर",
		"mai-IN": "क्रिसमस द्वीप",
		"dz-BT": "ཁི་རིསྟ་མེས་མཚོ་གླིང",
		"ja-JP": "クリスマス島",
		"ko-KR": "크리스마스섬",
		"ko-KP": "크리스마스섬",
		"zh-CN": "圣诞岛",
		"zh-Hans-CN": "圣诞岛",
		"zh-Hant-TW": "聖誕島",
		"zh-TW": "聖誕島",
		"zh-HK": "聖誕島",
		"zh-MO": "聖誕島",
		"zh-SG": "圣诞岛",
		"yue-Hant-HK": "聖誕島",
		"yue-Hans-CN": "圣诞岛",
		"mn-MN": "Зул сарын арал",
		"ug-CN": "مىلاد ئارىلى",
		"th-TH": "เกาะคริสต์มาส",
		"lo-LA": "ເກາະຄຣິສມາດ",
		"km-KH": "កោះ​គ្រីស្មាស",
		"my-MM": "ခရစ်စမတ် ကျွန်း",
		"vi-VN": "Đảo Giáng Sinh",
		"id-ID": "Pulau Natal",
		"ms-MY": "Pulau Krismas",
		"ms-SG": "Pulau Krismas",
		"ms-BN": "Pulau Krismas",
		"jv-ID": "Pulo Natal",
		"fil-PH": "Christmas Island",
		"ceb-PH": "Christmas Island",
		"ka-GE": "შობის კუნძული",
		"hy-AM": "Սուրբ Ծննդյան կղզի",
		"az-AZ": "Milad adası",
		"az-Cyrl-AZ": "Милад адасы",
		"kk-KZ": "Рождество аралы",
		"ky-KG": "Рождество аралы",
		"uz-UZ": "Rojdestvo oroli",
		"tg-TJ": "Ҷазираи Крисмас",
		"tk-TM": "Roždestwo adasy",
		"fa-IR": "جزیرهٔ کریسمس",
		"fa-AF": "جزیرهٔ کریسمس",
		"ps-AF": "د کريسمس ټاپو",
		"ps-PK": "د کريسمس ټاپو",
		"he-IL": "אי חג המולד",
		"ar-SA": "جزيرة كريسماس",
		"ar-AE": "جزيرة كريسماس",
		"ar-QA": "جزيرة كريسماس",
		"ar-BH": "جزيرة كريسماس",
		"ar-KW": "جزيرة كريسماس",
		"ar-OM": "جزيرة كريسماس",
		"ar-YE": "جزيرة كريسماس",
		"ar-IQ": "جزيرة كريسماس",
		"ar-JO": "جزيرة كريسماس",
		"ar-LB": "جزيرة كريسماس",
		"ar-SY": "جزيرة كريسماس",
		"ar-PS": "جزيرة كريسماس",
		"en-US": "Christmas Island",
		"en-GB": "Christmas Island",
		"en-IE": "Christmas Island",
		"en-MT": "Christmas Island",
		"en-GI": "Christmas Island",
		"en-CY": "Christmas Island",
		"en-JE": "Christmas Island",
		"en-GG": "Christmas Island",
		"en-IM": "Christmas Island",
		"en-CA": "Christmas Island",
		"en-AU": "Christmas Island",
		"en-NZ": "Christmas Island",
		"en-ZA": "Christmas Island",
		"en-IN": "Christmas Island",
		"en-SG": "Christmas Island",
		"pt-AO": "Ilha do Natal",
		"pt-MZ": "Ilha do Natal",
		"pt-CV": "Ilha do Natal",
		"pt-GW": "Ilha do Natal",
		"pt-ST": "Ilha do Natal",
		"pt-TL": "Ilha do Natal",
		"pt-MO": "Ilha do Natal",
		"es-ES": "Isla de Navidad",
		"es-419": "Isla de Navidad",
		"es-AD": "Isla de Navidad",
		"es-GI": "Isla de Navidad",
		"es-AR": "Isla de Navidad",
		"es-BO": "Isla de Navidad",
		"es-BR": "Isla de Navidad",
		"es-BZ": "Isla de Navidad",
		"es-CL": "Isla de Navidad",
		"es-CO": "Isla de Navidad",
		"es-CR": "Isla de Navidad",
		"es-CU": "Isla de Navidad",
		"es-DO": "Isla de Navidad",
		"es-EC": "Isla de Navidad",
		"es-GT": "Isla de Navidad",
		"es-HN": "Isla de Navidad",
		"es-MX": "Isla de Navidad",
		"es-NI": "Isla de Navidad",
		"es-PA": "Isla de Navidad",
		"es-PE": "Isla de Navidad",
		"es-PR": "Isla de Navidad",
		"es-PY": "Isla de Navidad",
		"es-SV": "Isla de Navidad",
		"es-US": "Isla de Navidad",
		"es-UY": "Isla de Navidad",
		"es-VE": "Isla de Navidad",
		"fr-FR": "Île Christmas",
		"fr-BE": "Île Christmas",
		"fr-CH": "Île Christmas",
		"fr-LU": "Île Christmas",
		"fr-MC": "Île Christmas",
		"fr-AD": "Île Christmas",
		"fr-CA": "île Christmas",
		"it-IT": "Isola Christmas",
		"it-CH": "Isola Christmas",
		"it-SM": "Isola Christmas",
		"it-VA": "Isola Christmas",
		"de-DE": "Weihnachtsinsel",
		"de-AT": "Weihnachtsinsel",
		"de-CH": "Weihnachtsinsel",
		"de-BE": "Weihnachtsinsel",
		"de-LI": "Weihnachtsinsel",
		"de-LU": "Weihnachtsinsel",
		"nl-NL": "Christmaseiland",
		"nl-BE": "Christmaseiland",
		"sv-SE": "Julön",
		"sv-FI": "Julön",
		"da-DK": "Juleøen",
		"nb-NO": "Christmasøya",
		"nn-NO": "Christmasøya",
		"fi-FI": "Joulusaari",
		"is-IS": "Jólaey",
		"fo-FO": "Jólaoyggjin",
		"et-EE": "Jõulusaar",
		"lv-LV": "Ziemsvētku sala",
		"lt-LT": "Kalėdų Sala",
		"pl-PL": "Wyspa Bożego Narodzenia",
		"cs-CZ": "Vánoční ostrov",
		"sk-SK": "Vianočný ostrov",
		"sl-SI": "Božični otok",
		"hr-HR": "Božićni Otok",
		"bs-BA": "Božićno ostrvo",
		"sr-RS": "Божићно Острво",
		"sr-BA": "Божићно Острво",
		"sr-ME": "Božićno Ostrvo",
		"mk-MK": "Божиќен Остров",
		"bg-BG": "остров Рождество",
		"be-BY": "Востраў Каляд",
		"uk-UA": "Острів Різдва",
		"ru-RU": "о-в Рождества",
		"el-GR": "Νήσος των Χριστουγέννων",
		"el-CY": "Νήσος των Χριστουγέννων",
		"ro-RO": "Insula Christmas",
		"ro-MD": "Insula Christmas",
		"hu-HU": "Karácsony-sziget",
		"sq-AL": "Ishulli i Krishtlindjes",
		"sq-XK": "Ishulli i Krishtlindjes",
		"mt-MT": "il-Gżira Christmas",
		"ga-IE": "Oileán na Nollag",
		"cy-GB": "Ynys y Nadolig",
		"gd-GB": "Eilean na Nollaig",
		"lb-LU": "Chrëschtdagsinsel",
		"ca-ES": "Illa Christmas",
		"ca-AD": "Illa Christmas",
		"ca-FR": "Illa Christmas",
		"ca-IT": "Illa Christmas",
		"eu-ES": "Christmas uhartea",
		"eu-FR": "Christmas uhartea",
		"gl-ES": "Illa Christmas",
		"tr-TR": "Christmas Adası",
		"tr-CY": "Christmas Adası"
	},
	"callingCode": "61",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12
		}
	]
} satisfies Country;
