import type { Country } from './types.js';

export const CYM = {
	"code": "CYM",
	"labels": {
		"pt-BR": "Ilhas Cayman",
		"pt-PT": "Ilhas Caimão",
		"es-ES": "Islas Caimán",
		"es-419": "Islas Caimán",
		"es-AR": "Islas Caimán",
		"es-BO": "Islas Caimán",
		"es-BR": "Islas Caimán",
		"es-BZ": "Islas Caimán",
		"es-CL": "Islas Caimán",
		"es-CO": "Islas Caimán",
		"es-CR": "Islas Caimán",
		"es-CU": "Islas Caimán",
		"es-DO": "Islas Caimán",
		"es-EC": "Islas Caimán",
		"es-GT": "Islas Caimán",
		"es-HN": "Islas Caimán",
		"es-MX": "Islas Caimán",
		"es-NI": "Islas Caimán",
		"es-PA": "Islas Caimán",
		"es-PE": "Islas Caimán",
		"es-PR": "Islas Caimán",
		"es-PY": "Islas Caimán",
		"es-SV": "Islas Caimán",
		"es-US": "Islas Caimán",
		"es-UY": "Islas Caimán",
		"es-VE": "Islas Caimán",
		"en-US": "Cayman Islands",
		"fr-FR": "Îles Caïmans",
		"fr-BE": "Îles Caïmans",
		"fr-CA": "Îles Caïmans",
		"fr-CH": "Îles Caïmans",
		"fr-LU": "Îles Caïmans",
		"fr-MC": "Îles Caïmans",
		"it-IT": "Isole Cayman",
		"it-CH": "Isole Cayman",
		"it-SM": "Isole Cayman",
		"it-VA": "Isole Cayman",
		"de-DE": "Kaimaninseln",
		"de-AT": "Kaimaninseln",
		"de-CH": "Kaimaninseln",
		"de-BE": "Kaimaninseln",
		"de-LI": "Kaimaninseln",
		"de-LU": "Kaimaninseln"
	}
} satisfies Country;
