import type { Country } from './types.js';

export const CYP = {
	"code": "CYP",
	"labels": {
		"pt-BR": "Chipre",
		"pt-PT": "Chipre",
		"es-ES": "Chipre",
		"es-419": "Chipre",
		"es-AR": "Chipre",
		"es-BO": "Chipre",
		"es-BR": "Chipre",
		"es-BZ": "Chipre",
		"es-CL": "Chipre",
		"es-CO": "Chipre",
		"es-CR": "Chipre",
		"es-CU": "Chipre",
		"es-DO": "Chipre",
		"es-EC": "Chipre",
		"es-GT": "Chipre",
		"es-HN": "Chipre",
		"es-MX": "Chipre",
		"es-NI": "Chipre",
		"es-PA": "Chipre",
		"es-PE": "Chipre",
		"es-PR": "Chipre",
		"es-PY": "Chipre",
		"es-SV": "Chipre",
		"es-US": "Chipre",
		"es-UY": "Chipre",
		"es-VE": "Chipre",
		"en-US": "Cyprus",
		"fr-FR": "Chypre",
		"fr-BE": "Chypre",
		"fr-CA": "Chypre",
		"fr-CH": "Chypre",
		"fr-LU": "Chypre",
		"fr-MC": "Chypre",
		"it-IT": "Cipro",
		"it-CH": "Cipro",
		"it-SM": "Cipro",
		"it-VA": "Cipro",
		"de-DE": "Zypern",
		"de-AT": "Zypern",
		"de-CH": "Zypern",
		"de-BE": "Zypern",
		"de-LI": "Zypern",
		"de-LU": "Zypern"
	},
	"callingCode": "357"
} satisfies Country;
