import type { Country } from './types.js';

export const CZE = {
	"code": "CZE",
	"labels": {
		"pt-BR": "Tchéquia",
		"pt-PT": "Chéquia",
		"es-ES": "Chequia",
		"es-419": "Chequia",
		"es-AR": "Chequia",
		"es-BO": "Chequia",
		"es-BR": "Chequia",
		"es-BZ": "Chequia",
		"es-CL": "Chequia",
		"es-CO": "Chequia",
		"es-CR": "Chequia",
		"es-CU": "Chequia",
		"es-DO": "Chequia",
		"es-EC": "Chequia",
		"es-GT": "Chequia",
		"es-HN": "Chequia",
		"es-MX": "Chequia",
		"es-NI": "Chequia",
		"es-PA": "Chequia",
		"es-PE": "Chequia",
		"es-PR": "Chequia",
		"es-PY": "Chequia",
		"es-SV": "Chequia",
		"es-US": "Chequia",
		"es-UY": "Chequia",
		"es-VE": "Chequia",
		"en-US": "Czechia",
		"fr-FR": "Tchéquie",
		"fr-BE": "Tchéquie",
		"fr-CA": "Tchéquie",
		"fr-CH": "Tchéquie",
		"fr-LU": "Tchéquie",
		"fr-MC": "Tchéquie",
		"it-IT": "Cechia",
		"it-CH": "Cechia",
		"it-SM": "Cechia",
		"it-VA": "Cechia",
		"de-DE": "Tschechien",
		"de-AT": "Tschechien",
		"de-CH": "Tschechien",
		"de-BE": "Tschechien",
		"de-LI": "Tschechien",
		"de-LU": "Tschechien"
	},
	"callingCode": "420"
} satisfies Country;
