import type { Country } from './types.js';

export const CZE = {
	"code": "CZE",
	"labels": {
		"pt-BR": "Tchéquia",
		"pt-PT": "Chéquia",
		"qu-PE": "Chequia",
		"qu-BO": "Chequia",
		"qu-EC": "Chequia",
		"chr-US": "ᏤᎩᎠ",
		"hi-IN": "चेकिया",
		"bn-IN": "চেকিয়া",
		"bn-BD": "চেকিয়া",
		"ta-IN": "செசியா",
		"ta-LK": "செசியா",
		"ta-SG": "செசியா",
		"ta-MY": "செசியா",
		"te-IN": "చెకియా",
		"mr-IN": "झेकिया",
		"gu-IN": "ચેકીયા",
		"kn-IN": "ಝೆಕಿಯಾ",
		"ml-IN": "ചെക്കിയ",
		"pa-IN": "ਚੈਕੀਆ",
		"ur-IN": "چیکیا",
		"ur-PK": "چیکیا",
		"or-IN": "ଚେଚିଆ",
		"as-IN": "চিজেচিয়া",
		"ne-IN": "चेकिया",
		"ne-NP": "चेकिया",
		"si-LK": "චෙචියාව",
		"kok-IN": "चेकिया",
		"ks-IN": "چیکیا",
		"brx-IN": "चेखिया",
		"mai-IN": "चेकिया",
		"dz-BT": "ཅེཀ་ རི་པབ་ལིཀ",
		"ja-JP": "チェコ",
		"ko-KR": "체코",
		"ko-KP": "체코",
		"zh-CN": "捷克",
		"zh-Hans-CN": "捷克",
		"zh-Hant-TW": "捷克",
		"zh-TW": "捷克",
		"zh-HK": "捷克",
		"zh-MO": "捷克",
		"zh-SG": "捷克",
		"yue-Hant-HK": "捷克",
		"yue-Hans-CN": "捷克",
		"mn-MN": "Чех",
		"ug-CN": "چېخ جۇمھۇرىيىتى",
		"th-TH": "เช็ก",
		"lo-LA": "ເຊັກເຊຍ",
		"km-KH": "ឆែក",
		"my-MM": "ချက်ကီယား",
		"vi-VN": "Séc",
		"id-ID": "Ceko",
		"ms-MY": "Czechia",
		"ms-SG": "Czechia",
		"ms-BN": "Czechia",
		"jv-ID": "Céko",
		"fil-PH": "Czechia",
		"ceb-PH": "Czechia",
		"ka-GE": "ჩეხეთი",
		"hy-AM": "Չեխիա",
		"az-AZ": "Çexiya",
		"az-Cyrl-AZ": "Чехија",
		"kk-KZ": "Чехия",
		"ky-KG": "Чехия",
		"uz-UZ": "Chexiya",
		"tg-TJ": "Ҷумҳурии Чех",
		"tk-TM": "Çehiýa",
		"fa-IR": "چک",
		"fa-AF": "چک",
		"ps-AF": "چکیا",
		"ps-PK": "چکیا",
		"he-IL": "צ׳כיה",
		"ar-SA": "التشيك",
		"ar-AE": "التشيك",
		"ar-QA": "التشيك",
		"ar-BH": "التشيك",
		"ar-KW": "التشيك",
		"ar-OM": "التشيك",
		"ar-YE": "التشيك",
		"ar-IQ": "التشيك",
		"ar-JO": "التشيك",
		"ar-LB": "التشيك",
		"ar-SY": "التشيك",
		"ar-PS": "التشيك",
		"en-US": "Czechia",
		"en-GB": "Czechia",
		"en-IE": "Czechia",
		"en-MT": "Czechia",
		"en-GI": "Czechia",
		"en-CY": "Czechia",
		"en-JE": "Czechia",
		"en-GG": "Czechia",
		"en-IM": "Czechia",
		"en-CA": "Czechia",
		"en-AU": "Czechia",
		"en-NZ": "Czechia",
		"en-ZA": "Czechia",
		"en-IN": "Czechia",
		"en-SG": "Czechia",
		"pt-AO": "Chéquia",
		"pt-MZ": "Chéquia",
		"pt-CV": "Chéquia",
		"pt-GW": "Chéquia",
		"pt-ST": "Chéquia",
		"pt-TL": "Chéquia",
		"pt-MO": "Chéquia",
		"es-ES": "Chequia",
		"es-419": "Chequia",
		"es-AD": "Chequia",
		"es-GI": "Chequia",
		"es-AR": "Chequia",
		"es-BO": "Chequia",
		"es-BR": "Chequia",
		"es-BZ": "Chequia",
		"es-CL": "Chequia",
		"es-CO": "Chequia",
		"es-CR": "Chequia",
		"es-CU": "Chequia",
		"es-DO": "Chequia",
		"es-EC": "Chequia",
		"es-GT": "Chequia",
		"es-HN": "Chequia",
		"es-MX": "Chequia",
		"es-NI": "Chequia",
		"es-PA": "Chequia",
		"es-PE": "Chequia",
		"es-PR": "Chequia",
		"es-PY": "Chequia",
		"es-SV": "Chequia",
		"es-US": "Chequia",
		"es-UY": "Chequia",
		"es-VE": "Chequia",
		"fr-FR": "Tchéquie",
		"fr-BE": "Tchéquie",
		"fr-CH": "Tchéquie",
		"fr-LU": "Tchéquie",
		"fr-MC": "Tchéquie",
		"fr-AD": "Tchéquie",
		"fr-CA": "Tchéquie",
		"it-IT": "Cechia",
		"it-CH": "Cechia",
		"it-SM": "Cechia",
		"it-VA": "Cechia",
		"de-DE": "Tschechien",
		"de-AT": "Tschechien",
		"de-CH": "Tschechien",
		"de-BE": "Tschechien",
		"de-LI": "Tschechien",
		"de-LU": "Tschechien",
		"nl-NL": "Tsjechië",
		"nl-BE": "Tsjechië",
		"sv-SE": "Tjeckien",
		"sv-FI": "Tjeckien",
		"da-DK": "Tjekkiet",
		"nb-NO": "Tsjekkia",
		"nn-NO": "Tsjekkia",
		"fi-FI": "Tšekki",
		"is-IS": "Tékkland",
		"fo-FO": "Kekkia",
		"et-EE": "Tšehhi",
		"lv-LV": "Čehija",
		"lt-LT": "Čekija",
		"pl-PL": "Czechy",
		"cs-CZ": "Česko",
		"sk-SK": "Česko",
		"sl-SI": "Češka",
		"hr-HR": "Češka",
		"bs-BA": "Češka",
		"sr-RS": "Чешка",
		"sr-BA": "Чешка Република",
		"sr-ME": "Češka Republika",
		"mk-MK": "Чешка",
		"bg-BG": "Чехия",
		"be-BY": "Чэхія",
		"uk-UA": "Чехія",
		"ru-RU": "Чехия",
		"el-GR": "Τσεχία",
		"el-CY": "Τσεχία",
		"ro-RO": "Cehia",
		"ro-MD": "Cehia",
		"hu-HU": "Csehország",
		"sq-AL": "Çeki",
		"sq-XK": "Çeki",
		"mt-MT": "ir-Repubblika Ċeka",
		"ga-IE": "an tSeicia",
		"cy-GB": "Tsiecia",
		"gd-GB": "An t-Seic",
		"lb-LU": "Tschechien",
		"ca-ES": "Txèquia",
		"ca-AD": "Txèquia",
		"ca-FR": "Txèquia",
		"ca-IT": "Txèquia",
		"eu-ES": "Txekia",
		"eu-FR": "Txekia",
		"gl-ES": "Chequia",
		"tr-TR": "Çekya",
		"tr-CY": "Çekya"
	},
	"callingCode": "420",
	"phoneMasks": [
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[2-8]|9[015-7]"
			]
		},
		{
			"mask": "## ### ### ##",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"96"
			]
		},
		{
			"mask": "## ### ### ###",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"9"
			]
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"9"
			]
		}
	]
} satisfies Country;
