import type { Country } from './types.js';

export const DEU = {
	"code": "DEU",
	"labels": {
		"pt-BR": "Alemanha",
		"pt-PT": "Alemanha",
		"es-ES": "Alemania",
		"es-419": "Alemania",
		"es-AR": "Alemania",
		"es-BO": "Alemania",
		"es-BR": "Alemania",
		"es-BZ": "Alemania",
		"es-CL": "Alemania",
		"es-CO": "Alemania",
		"es-CR": "Alemania",
		"es-CU": "Alemania",
		"es-DO": "Alemania",
		"es-EC": "Alemania",
		"es-GT": "Alemania",
		"es-HN": "Alemania",
		"es-MX": "Alemania",
		"es-NI": "Alemania",
		"es-PA": "Alemania",
		"es-PE": "Alemania",
		"es-PR": "Alemania",
		"es-PY": "Alemania",
		"es-SV": "Alemania",
		"es-US": "Alemania",
		"es-UY": "Alemania",
		"es-VE": "Alemania",
		"en-US": "Germany",
		"fr-FR": "Allemagne",
		"fr-BE": "Allemagne",
		"fr-CA": "Allemagne",
		"fr-CH": "Allemagne",
		"fr-LU": "Allemagne",
		"fr-MC": "Allemagne",
		"it-IT": "Germania",
		"it-CH": "Germania",
		"it-SM": "Germania",
		"it-VA": "Germania",
		"de-DE": "Deutschland",
		"de-AT": "Deutschland",
		"de-CH": "Deutschland",
		"de-BE": "Deutschland",
		"de-LI": "Deutschland",
		"de-LU": "Deutschland"
	},
	"callingCode": "49"
} satisfies Country;
