import type { Country } from './types.js';

export const DMA = {
	"code": "DMA",
	"labels": {
		"pt-BR": "Dominica",
		"pt-PT": "Domínica",
		"es-ES": "Dominica",
		"es-419": "Dominica",
		"es-AR": "Dominica",
		"es-BO": "Dominica",
		"es-BR": "Dominica",
		"es-BZ": "Dominica",
		"es-CL": "Dominica",
		"es-CO": "Dominica",
		"es-CR": "Dominica",
		"es-CU": "Dominica",
		"es-DO": "Dominica",
		"es-EC": "Dominica",
		"es-GT": "Dominica",
		"es-HN": "Dominica",
		"es-MX": "Dominica",
		"es-NI": "Dominica",
		"es-PA": "Dominica",
		"es-PE": "Dominica",
		"es-PR": "Dominica",
		"es-PY": "Dominica",
		"es-SV": "Dominica",
		"es-US": "Dominica",
		"es-UY": "Dominica",
		"es-VE": "Dominica",
		"en-US": "Dominica",
		"fr-FR": "Dominique",
		"fr-BE": "Dominique",
		"fr-CA": "Dominique",
		"fr-CH": "Dominique",
		"fr-LU": "Dominique",
		"fr-MC": "Dominique",
		"it-IT": "Dominica",
		"it-CH": "Dominica",
		"it-SM": "Dominica",
		"it-VA": "Dominica",
		"de-DE": "Dominica",
		"de-AT": "Dominica",
		"de-CH": "Dominica",
		"de-BE": "Dominica",
		"de-LI": "Dominica",
		"de-LU": "Dominica"
	}
} satisfies Country;
