import type { Country } from './types.js';

export const DOM = {
	"code": "DOM",
	"labels": {
		"pt-BR": "República Dominicana",
		"pt-PT": "República Dominicana",
		"es-ES": "República Dominicana",
		"es-419": "República Dominicana",
		"es-AR": "República Dominicana",
		"es-BO": "República Dominicana",
		"es-BR": "República Dominicana",
		"es-BZ": "República Dominicana",
		"es-CL": "República Dominicana",
		"es-CO": "República Dominicana",
		"es-CR": "República Dominicana",
		"es-CU": "República Dominicana",
		"es-DO": "República Dominicana",
		"es-EC": "República Dominicana",
		"es-GT": "República Dominicana",
		"es-HN": "República Dominicana",
		"es-MX": "República Dominicana",
		"es-NI": "República Dominicana",
		"es-PA": "República Dominicana",
		"es-PE": "República Dominicana",
		"es-PR": "República Dominicana",
		"es-PY": "República Dominicana",
		"es-SV": "República Dominicana",
		"es-US": "República Dominicana",
		"es-UY": "República Dominicana",
		"es-VE": "República Dominicana",
		"en-US": "Dominican Republic",
		"fr-FR": "République dominicaine",
		"fr-BE": "République dominicaine",
		"fr-CA": "République dominicaine",
		"fr-CH": "République dominicaine",
		"fr-LU": "République dominicaine",
		"fr-MC": "République dominicaine",
		"it-IT": "Repubblica Dominicana",
		"it-CH": "Repubblica Dominicana",
		"it-SM": "Repubblica Dominicana",
		"it-VA": "Repubblica Dominicana",
		"de-DE": "Dominikanische Republik",
		"de-AT": "Dominikanische Republik",
		"de-CH": "Dominikanische Republik",
		"de-BE": "Dominikanische Republik",
		"de-LI": "Dominikanische Republik",
		"de-LU": "Dominikanische Republik"
	},
	"callingCode": "1"
} satisfies Country;
