import type { Country } from './types.js';

export const ERI = {
	"code": "ERI",
	"labels": {
		"pt-BR": "Eritreia",
		"pt-PT": "Eritreia",
		"es-ES": "Eritrea",
		"es-419": "Eritrea",
		"es-AR": "Eritrea",
		"es-BO": "Eritrea",
		"es-BR": "Eritrea",
		"es-BZ": "Eritrea",
		"es-CL": "Eritrea",
		"es-CO": "Eritrea",
		"es-CR": "Eritrea",
		"es-CU": "Eritrea",
		"es-DO": "Eritrea",
		"es-EC": "Eritrea",
		"es-GT": "Eritrea",
		"es-HN": "Eritrea",
		"es-MX": "Eritrea",
		"es-NI": "Eritrea",
		"es-PA": "Eritrea",
		"es-PE": "Eritrea",
		"es-PR": "Eritrea",
		"es-PY": "Eritrea",
		"es-SV": "Eritrea",
		"es-US": "Eritrea",
		"es-UY": "Eritrea",
		"es-VE": "Eritrea",
		"en-US": "Eritrea",
		"fr-FR": "Érythrée",
		"fr-BE": "Érythrée",
		"fr-CA": "Érythrée",
		"fr-CH": "Érythrée",
		"fr-LU": "Érythrée",
		"fr-MC": "Érythrée",
		"it-IT": "Eritrea",
		"it-CH": "Eritrea",
		"it-SM": "Eritrea",
		"it-VA": "Eritrea",
		"de-DE": "Eritrea",
		"de-AT": "Eritrea",
		"de-CH": "Eritrea",
		"de-BE": "Eritrea",
		"de-LI": "Eritrea",
		"de-LU": "Eritrea"
	}
} satisfies Country;
