import type { Country } from './types.js';

export const ESH = {
	"code": "ESH",
	"labels": {
		"pt-BR": "Saara Ocidental",
		"pt-PT": "Sara Ocidental",
		"qu-PE": "Sahara Occidental",
		"qu-BO": "Sahara Occidental",
		"qu-EC": "Sahara Occidental",
		"chr-US": "ᏭᏕᎵᎬ ᏗᏜ ᏌᎮᎳ",
		"hi-IN": "पश्चिमी सहारा",
		"bn-IN": "পশ্চিম সাহারা",
		"bn-BD": "পশ্চিম সাহারা",
		"ta-IN": "மேற்கு சஹாரா",
		"ta-LK": "மேற்கு சஹாரா",
		"ta-SG": "மேற்கு சஹாரா",
		"ta-MY": "மேற்கு சஹாரா",
		"te-IN": "పడమటి సహారా",
		"mr-IN": "पश्चिम सहारा",
		"gu-IN": "પશ્ચિમી સહારા",
		"kn-IN": "ಪಶ್ಚಿಮ ಸಹಾರಾ",
		"ml-IN": "പശ്ചിമ സഹാറ",
		"pa-IN": "ਪੱਛਮੀ ਸਹਾਰਾ",
		"ur-IN": "مغربی صحارا",
		"ur-PK": "مغربی صحارا",
		"or-IN": "ପଶ୍ଚିମ ସାହାରା",
		"as-IN": "পশ্চিমীয় ছাহাৰা",
		"ne-IN": "पश्चिमी साहारा",
		"ne-NP": "पश्चिमी साहारा",
		"si-LK": "බටහිර සහරාව",
		"kok-IN": "अस्तंत सहारा",
		"ks-IN": "مشرِقی سَہارا",
		"brx-IN": "सोनाबारि साहारा",
		"mai-IN": "पश्चिमी सहारा",
		"dz-BT": "ནུབ་ཕྱོགས་ ས་ཧཱ་ར",
		"ja-JP": "西サハラ",
		"ko-KR": "서사하라",
		"ko-KP": "서사하라",
		"zh-CN": "西撒哈拉",
		"zh-Hans-CN": "西撒哈拉",
		"zh-Hant-TW": "西撒哈拉",
		"zh-TW": "西撒哈拉",
		"zh-HK": "西撒哈拉",
		"zh-MO": "西撒哈拉",
		"zh-SG": "西撒哈拉",
		"yue-Hant-HK": "西撒哈拉",
		"yue-Hans-CN": "西撒哈拉",
		"mn-MN": "Баруун Сахар",
		"ug-CN": "غەربىي ساخارا",
		"th-TH": "ซาฮาราตะวันตก",
		"lo-LA": "ຊາຮາຣາຕາເວັນຕົກ",
		"km-KH": "សាហារ៉ាខាងលិច",
		"my-MM": "အနောက် ဆာဟာရ",
		"vi-VN": "Tây Sahara",
		"id-ID": "Sahara Barat",
		"ms-MY": "Sahara Barat",
		"ms-SG": "Sahara Barat",
		"ms-BN": "Sahara Barat",
		"jv-ID": "Sahara Kulon",
		"fil-PH": "Kanlurang Sahara",
		"ceb-PH": "Western Sahara",
		"ka-GE": "დასავლეთ საჰარა",
		"hy-AM": "Արևմտյան Սահարա",
		"az-AZ": "Qərbi Saxara",
		"kk-KZ": "Батыс Сахара",
		"ky-KG": "Батыш Сахара",
		"uz-UZ": "G‘arbiy Sahroi Kabir",
		"tg-TJ": "Сахараи Ғарбӣ",
		"tk-TM": "Günbatar Sahara",
		"fa-IR": "صحرای غربی",
		"fa-AF": "صحرای غربی",
		"ps-AF": "لويديځ صحارا",
		"ps-PK": "لويديځ صحارا",
		"he-IL": "סהרה המערבית",
		"ar-SA": "الصحراء الغربية",
		"ar-AE": "الصحراء الغربية",
		"ar-QA": "الصحراء الغربية",
		"ar-BH": "الصحراء الغربية",
		"ar-KW": "الصحراء الغربية",
		"ar-OM": "الصحراء الغربية",
		"ar-YE": "الصحراء الغربية",
		"ar-IQ": "الصحراء الغربية",
		"ar-JO": "الصحراء الغربية",
		"ar-LB": "الصحراء الغربية",
		"ar-SY": "الصحراء الغربية",
		"ar-PS": "الصحراء الغربية",
		"en-US": "Western Sahara",
		"en-GB": "Western Sahara",
		"en-IE": "Western Sahara",
		"en-MT": "Western Sahara",
		"en-GI": "Western Sahara",
		"en-CY": "Western Sahara",
		"en-JE": "Western Sahara",
		"en-GG": "Western Sahara",
		"en-IM": "Western Sahara",
		"en-CA": "Western Sahara",
		"en-AU": "Western Sahara",
		"en-NZ": "Western Sahara",
		"en-ZA": "Western Sahara",
		"en-IN": "Western Sahara",
		"en-SG": "Western Sahara",
		"pt-AO": "Sara Ocidental",
		"pt-MZ": "Sara Ocidental",
		"pt-CV": "Sara Ocidental",
		"pt-GW": "Sara Ocidental",
		"pt-ST": "Sara Ocidental",
		"pt-TL": "Sara Ocidental",
		"pt-MO": "Sara Ocidental",
		"es-ES": "Sáhara Occidental",
		"es-419": "Sáhara Occidental",
		"es-AD": "Sáhara Occidental",
		"es-GI": "Sáhara Occidental",
		"es-AR": "Sáhara Occidental",
		"es-BO": "Sáhara Occidental",
		"es-BR": "Sáhara Occidental",
		"es-BZ": "Sáhara Occidental",
		"es-CL": "Sahara Occidental",
		"es-CO": "Sáhara Occidental",
		"es-CR": "Sáhara Occidental",
		"es-CU": "Sáhara Occidental",
		"es-DO": "Sáhara Occidental",
		"es-EC": "Sáhara Occidental",
		"es-GT": "Sáhara Occidental",
		"es-HN": "Sáhara Occidental",
		"es-MX": "Sáhara Occidental",
		"es-NI": "Sáhara Occidental",
		"es-PA": "Sáhara Occidental",
		"es-PE": "Sáhara Occidental",
		"es-PR": "Sáhara Occidental",
		"es-PY": "Sáhara Occidental",
		"es-SV": "Sáhara Occidental",
		"es-US": "Sahara Occidental",
		"es-UY": "Sáhara Occidental",
		"es-VE": "Sáhara Occidental",
		"fr-FR": "Sahara occidental",
		"fr-BE": "Sahara occidental",
		"fr-CH": "Sahara occidental",
		"fr-LU": "Sahara occidental",
		"fr-MC": "Sahara occidental",
		"fr-AD": "Sahara occidental",
		"fr-CA": "Sahara occidental",
		"it-IT": "Sahara Occidentale",
		"it-CH": "Sahara Occidentale",
		"it-SM": "Sahara Occidentale",
		"it-VA": "Sahara Occidentale",
		"de-DE": "Westsahara",
		"de-AT": "Westsahara",
		"de-CH": "Westsahara",
		"de-BE": "Westsahara",
		"de-LI": "Westsahara",
		"de-LU": "Westsahara",
		"nl-NL": "Westelijke Sahara",
		"nl-BE": "Westelijke Sahara",
		"sv-SE": "Västsahara",
		"sv-FI": "Västsahara",
		"da-DK": "Vestsahara",
		"nb-NO": "Vest-Sahara",
		"nn-NO": "Vest-Sahara",
		"fi-FI": "Länsi-Sahara",
		"is-IS": "Vestur-Sahara",
		"fo-FO": "Vestursahara",
		"et-EE": "Lääne-Sahara",
		"lv-LV": "Rietumsahāra",
		"lt-LT": "Vakarų Sachara",
		"pl-PL": "Sahara Zachodnia",
		"cs-CZ": "Západní Sahara",
		"sk-SK": "Západná Sahara",
		"sl-SI": "Zahodna Sahara",
		"hr-HR": "Zapadna Sahara",
		"bs-BA": "Zapadna Sahara",
		"sr-RS": "Западна Сахара",
		"sr-BA": "Западна Сахара",
		"sr-ME": "Zapadna Sahara",
		"mk-MK": "Западна Сахара",
		"bg-BG": "Западна Сахара",
		"be-BY": "Заходняя Сахара",
		"uk-UA": "Західна Сахара",
		"ru-RU": "Западная Сахара",
		"el-GR": "Δυτική Σαχάρα",
		"el-CY": "Δυτική Σαχάρα",
		"ro-RO": "Sahara Occidentală",
		"ro-MD": "Sahara Occidentală",
		"hu-HU": "Nyugat-Szahara",
		"sq-AL": "Saharaja Perëndimore",
		"sq-XK": "Saharaja Perëndimore",
		"mt-MT": "is-Saħara tal-Punent",
		"ga-IE": "An Sahára Thiar",
		"cy-GB": "Gorllewin Sahara",
		"gd-GB": "Sathara an Iar",
		"lb-LU": "Westsahara",
		"ca-ES": "Sàhara Occidental",
		"ca-AD": "Sàhara Occidental",
		"ca-FR": "Sàhara Occidental",
		"ca-IT": "Sàhara Occidental",
		"eu-ES": "Mendebaldeko Sahara",
		"eu-FR": "Mendebaldeko Sahara",
		"gl-ES": "Sáhara Occidental",
		"tr-TR": "Batı Sahra",
		"tr-CY": "Batı Sahra"
	},
	"callingCode": "2125288",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		}
	]
} satisfies Country;
