import type { Country } from './types.js';

export const ESH = {
	"code": "ESH",
	"labels": {
		"pt-BR": "Saara Ocidental",
		"pt-PT": "Sara Ocidental",
		"es-ES": "Sáhara Occidental",
		"es-419": "Sáhara Occidental",
		"es-AR": "Sáhara Occidental",
		"es-BO": "Sáhara Occidental",
		"es-BR": "Sáhara Occidental",
		"es-BZ": "Sáhara Occidental",
		"es-CL": "Sahara Occidental",
		"es-CO": "Sáhara Occidental",
		"es-CR": "Sáhara Occidental",
		"es-CU": "Sáhara Occidental",
		"es-DO": "Sáhara Occidental",
		"es-EC": "Sáhara Occidental",
		"es-GT": "Sáhara Occidental",
		"es-HN": "Sáhara Occidental",
		"es-MX": "Sáhara Occidental",
		"es-NI": "Sáhara Occidental",
		"es-PA": "Sáhara Occidental",
		"es-PE": "Sáhara Occidental",
		"es-PR": "Sáhara Occidental",
		"es-PY": "Sáhara Occidental",
		"es-SV": "Sáhara Occidental",
		"es-US": "Sahara Occidental",
		"es-UY": "Sáhara Occidental",
		"es-VE": "Sáhara Occidental",
		"en-US": "Western Sahara",
		"fr-FR": "Sahara occidental",
		"fr-BE": "Sahara occidental",
		"fr-CA": "Sahara occidental",
		"fr-CH": "Sahara occidental",
		"fr-LU": "Sahara occidental",
		"fr-MC": "Sahara occidental",
		"it-IT": "Sahara Occidentale",
		"it-CH": "Sahara Occidentale",
		"it-SM": "Sahara Occidentale",
		"it-VA": "Sahara Occidentale",
		"de-DE": "Westsahara",
		"de-AT": "Westsahara",
		"de-CH": "Westsahara",
		"de-BE": "Westsahara",
		"de-LI": "Westsahara",
		"de-LU": "Westsahara"
	},
	"callingCode": "2125288"
} satisfies Country;
