import type { Country } from './types.js';

export const EST = {
	"code": "EST",
	"labels": {
		"pt-BR": "Estônia",
		"pt-PT": "Estónia",
		"qu-PE": "Estonia",
		"qu-BO": "Estonia",
		"qu-EC": "Estonia",
		"chr-US": "ᎡᏍᏙᏂᏯ",
		"hi-IN": "एस्टोनिया",
		"bn-IN": "এস্তোনিয়া",
		"bn-BD": "এস্তোনিয়া",
		"ta-IN": "எஸ்டோனியா",
		"ta-LK": "எஸ்டோனியா",
		"ta-SG": "எஸ்டோனியா",
		"ta-MY": "எஸ்டோனியா",
		"te-IN": "ఎస్టోనియా",
		"mr-IN": "एस्टोनिया",
		"gu-IN": "એસ્ટોનિયા",
		"kn-IN": "ಎಸ್ಟೋನಿಯಾ",
		"ml-IN": "എസ്റ്റോണിയ‍",
		"pa-IN": "ਇਸਟੋਨੀਆ",
		"ur-IN": "اسٹونیا",
		"ur-PK": "اسٹونیا",
		"or-IN": "ଏସ୍ତୋନିଆ",
		"as-IN": "ইষ্টোনিয়া",
		"ne-IN": "इस्टोनिया",
		"ne-NP": "इस्टोनिया",
		"si-LK": "එස්තෝනියාව",
		"kok-IN": "एस्टोनिया",
		"ks-IN": "ایسٹونِیا",
		"brx-IN": "एस्ट’निया",
		"mai-IN": "एस्टोनिया",
		"dz-BT": "ཨེས་ཊོ་ནི་ཡ",
		"ja-JP": "エストニア",
		"ko-KR": "에스토니아",
		"ko-KP": "에스토니아",
		"zh-CN": "爱沙尼亚",
		"zh-Hans-CN": "爱沙尼亚",
		"zh-Hant-TW": "愛沙尼亞",
		"zh-TW": "愛沙尼亞",
		"zh-HK": "愛沙尼亞",
		"zh-MO": "愛沙尼亞",
		"zh-SG": "爱沙尼亚",
		"yue-Hant-HK": "愛沙尼亞",
		"yue-Hans-CN": "爱沙尼亚",
		"mn-MN": "Эстони",
		"ug-CN": "ئېستونىيە",
		"th-TH": "เอสโตเนีย",
		"lo-LA": "ເອສໂຕເນຍ",
		"km-KH": "អេស្តូនី",
		"my-MM": "အက်စတိုးနီးယား",
		"vi-VN": "Estonia",
		"id-ID": "Estonia",
		"ms-MY": "Estonia",
		"ms-SG": "Estonia",
		"ms-BN": "Estonia",
		"jv-ID": "Éstonia",
		"fil-PH": "Estonia",
		"ceb-PH": "Estonia",
		"ka-GE": "ესტონეთი",
		"hy-AM": "Էստոնիա",
		"az-AZ": "Estoniya",
		"az-Cyrl-AZ": "Естонија",
		"kk-KZ": "Эстония",
		"ky-KG": "Эстония",
		"uz-UZ": "Estoniya",
		"tg-TJ": "Эстония",
		"tk-TM": "Estoniýa",
		"fa-IR": "استونی",
		"fa-AF": "استونیا",
		"ps-AF": "استونیا",
		"ps-PK": "استونیا",
		"he-IL": "אסטוניה",
		"ar-SA": "إستونيا",
		"ar-AE": "إستونيا",
		"ar-QA": "إستونيا",
		"ar-BH": "إستونيا",
		"ar-KW": "إستونيا",
		"ar-OM": "إستونيا",
		"ar-YE": "إستونيا",
		"ar-IQ": "إستونيا",
		"ar-JO": "إستونيا",
		"ar-LB": "إستونيا",
		"ar-SY": "إستونيا",
		"ar-PS": "إستونيا",
		"en-US": "Estonia",
		"en-GB": "Estonia",
		"en-IE": "Estonia",
		"en-MT": "Estonia",
		"en-GI": "Estonia",
		"en-CY": "Estonia",
		"en-JE": "Estonia",
		"en-GG": "Estonia",
		"en-IM": "Estonia",
		"en-CA": "Estonia",
		"en-AU": "Estonia",
		"en-NZ": "Estonia",
		"en-ZA": "Estonia",
		"en-IN": "Estonia",
		"en-SG": "Estonia",
		"pt-AO": "Estónia",
		"pt-MZ": "Estónia",
		"pt-CV": "Estónia",
		"pt-GW": "Estónia",
		"pt-ST": "Estónia",
		"pt-TL": "Estónia",
		"pt-MO": "Estónia",
		"es-ES": "Estonia",
		"es-419": "Estonia",
		"es-AD": "Estonia",
		"es-GI": "Estonia",
		"es-AR": "Estonia",
		"es-BO": "Estonia",
		"es-BR": "Estonia",
		"es-BZ": "Estonia",
		"es-CL": "Estonia",
		"es-CO": "Estonia",
		"es-CR": "Estonia",
		"es-CU": "Estonia",
		"es-DO": "Estonia",
		"es-EC": "Estonia",
		"es-GT": "Estonia",
		"es-HN": "Estonia",
		"es-MX": "Estonia",
		"es-NI": "Estonia",
		"es-PA": "Estonia",
		"es-PE": "Estonia",
		"es-PR": "Estonia",
		"es-PY": "Estonia",
		"es-SV": "Estonia",
		"es-US": "Estonia",
		"es-UY": "Estonia",
		"es-VE": "Estonia",
		"fr-FR": "Estonie",
		"fr-BE": "Estonie",
		"fr-CH": "Estonie",
		"fr-LU": "Estonie",
		"fr-MC": "Estonie",
		"fr-AD": "Estonie",
		"fr-CA": "Estonie",
		"it-IT": "Estonia",
		"it-CH": "Estonia",
		"it-SM": "Estonia",
		"it-VA": "Estonia",
		"de-DE": "Estland",
		"de-AT": "Estland",
		"de-CH": "Estland",
		"de-BE": "Estland",
		"de-LI": "Estland",
		"de-LU": "Estland",
		"nl-NL": "Estland",
		"nl-BE": "Estland",
		"sv-SE": "Estland",
		"sv-FI": "Estland",
		"da-DK": "Estland",
		"nb-NO": "Estland",
		"nn-NO": "Estland",
		"fi-FI": "Viro",
		"is-IS": "Eistland",
		"fo-FO": "Estland",
		"et-EE": "Eesti",
		"lv-LV": "Igaunija",
		"lt-LT": "Estija",
		"pl-PL": "Estonia",
		"cs-CZ": "Estonsko",
		"sk-SK": "Estónsko",
		"sl-SI": "Estonija",
		"hr-HR": "Estonija",
		"bs-BA": "Estonija",
		"sr-RS": "Естонија",
		"sr-BA": "Естонија",
		"sr-ME": "Estonija",
		"mk-MK": "Естонија",
		"bg-BG": "Естония",
		"be-BY": "Эстонія",
		"uk-UA": "Естонія",
		"ru-RU": "Эстония",
		"el-GR": "Εσθονία",
		"el-CY": "Εσθονία",
		"ro-RO": "Estonia",
		"ro-MD": "Estonia",
		"hu-HU": "Észtország",
		"sq-AL": "Estoni",
		"sq-XK": "Estoni",
		"mt-MT": "l-Estonja",
		"ga-IE": "an Eastóin",
		"cy-GB": "Estonia",
		"gd-GB": "An Eastoin",
		"lb-LU": "Estland",
		"ca-ES": "Estònia",
		"ca-AD": "Estònia",
		"ca-FR": "Estònia",
		"ca-IT": "Estònia",
		"eu-ES": "Estonia",
		"eu-FR": "Estonia",
		"gl-ES": "Estonia",
		"tr-TR": "Estonya",
		"tr-CY": "Estonya"
	},
	"callingCode": "372",
	"phoneMasks": [
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[369]|4[3-8]|5(?:[0-2]|5[0-478]|6[45])|7[1-9]|88",
				"[369]|4[3-8]|5(?:[02]|1(?:[0-8]|95)|5[0-478]|6(?:4[0-4]|5[1-589]))|7[1-9]|88"
			]
		},
		{
			"mask": "## ## ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"7"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[45]|8(?:00|[1-49])",
				"[45]|8(?:00[1-9]|[1-49])"
			]
		},
		{
			"mask": "#### ### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
