import type { Country } from './types.js';

export const ETH = {
	"code": "ETH",
	"labels": {
		"pt-BR": "Etiópia",
		"pt-PT": "Etiópia",
		"es-ES": "Etiopía",
		"es-419": "Etiopía",
		"es-AR": "Etiopía",
		"es-BO": "Etiopía",
		"es-BR": "Etiopía",
		"es-BZ": "Etiopía",
		"es-CL": "Etiopía",
		"es-CO": "Etiopía",
		"es-CR": "Etiopía",
		"es-CU": "Etiopía",
		"es-DO": "Etiopía",
		"es-EC": "Etiopía",
		"es-GT": "Etiopía",
		"es-HN": "Etiopía",
		"es-MX": "Etiopía",
		"es-NI": "Etiopía",
		"es-PA": "Etiopía",
		"es-PE": "Etiopía",
		"es-PR": "Etiopía",
		"es-PY": "Etiopía",
		"es-SV": "Etiopía",
		"es-US": "Etiopía",
		"es-UY": "Etiopía",
		"es-VE": "Etiopía",
		"en-US": "Ethiopia",
		"fr-FR": "Éthiopie",
		"fr-BE": "Éthiopie",
		"fr-CA": "Éthiopie",
		"fr-CH": "Éthiopie",
		"fr-LU": "Éthiopie",
		"fr-MC": "Éthiopie",
		"it-IT": "Etiopia",
		"it-CH": "Etiopia",
		"it-SM": "Etiopia",
		"it-VA": "Etiopia",
		"de-DE": "Äthiopien",
		"de-AT": "Äthiopien",
		"de-CH": "Äthiopien",
		"de-BE": "Äthiopien",
		"de-LI": "Äthiopien",
		"de-LU": "Äthiopien"
	}
} satisfies Country;
