import type { Country } from './types.js';

export const FIN = {
	"code": "FIN",
	"labels": {
		"pt-BR": "Finlândia",
		"pt-PT": "Finlândia",
		"es-ES": "Finlandia",
		"es-419": "Finlandia",
		"es-AR": "Finlandia",
		"es-BO": "Finlandia",
		"es-BR": "Finlandia",
		"es-BZ": "Finlandia",
		"es-CL": "Finlandia",
		"es-CO": "Finlandia",
		"es-CR": "Finlandia",
		"es-CU": "Finlandia",
		"es-DO": "Finlandia",
		"es-EC": "Finlandia",
		"es-GT": "Finlandia",
		"es-HN": "Finlandia",
		"es-MX": "Finlandia",
		"es-NI": "Finlandia",
		"es-PA": "Finlandia",
		"es-PE": "Finlandia",
		"es-PR": "Finlandia",
		"es-PY": "Finlandia",
		"es-SV": "Finlandia",
		"es-US": "Finlandia",
		"es-UY": "Finlandia",
		"es-VE": "Finlandia",
		"en-US": "Finland",
		"fr-FR": "Finlande",
		"fr-BE": "Finlande",
		"fr-CA": "Finlande",
		"fr-CH": "Finlande",
		"fr-LU": "Finlande",
		"fr-MC": "Finlande",
		"it-IT": "Finlandia",
		"it-CH": "Finlandia",
		"it-SM": "Finlandia",
		"it-VA": "Finlandia",
		"de-DE": "Finnland",
		"de-AT": "Finnland",
		"de-CH": "Finnland",
		"de-BE": "Finnland",
		"de-LI": "Finnland",
		"de-LU": "Finnland"
	}
} satisfies Country;
