import type { Country } from './types.js';

export const FJI = {
	"code": "FJI",
	"labels": {
		"pt-BR": "Fiji",
		"pt-PT": "Fiji",
		"es-ES": "Fiyi",
		"es-419": "Fiyi",
		"es-AR": "Fiyi",
		"es-BO": "Fiyi",
		"es-BR": "Fiyi",
		"es-BZ": "Fiyi",
		"es-CL": "Fiyi",
		"es-CO": "Fiyi",
		"es-CR": "Fiyi",
		"es-CU": "Fiyi",
		"es-DO": "Fiyi",
		"es-EC": "Fiyi",
		"es-GT": "Fiyi",
		"es-HN": "Fiyi",
		"es-MX": "Fiyi",
		"es-NI": "Fiyi",
		"es-PA": "Fiyi",
		"es-PE": "Fiyi",
		"es-PR": "Fiyi",
		"es-PY": "Fiyi",
		"es-SV": "Fiyi",
		"es-US": "Fiyi",
		"es-UY": "Fiyi",
		"es-VE": "Fiyi",
		"en-US": "Fiji",
		"fr-FR": "Fidji",
		"fr-BE": "Fidji",
		"fr-CA": "Fidji",
		"fr-CH": "Fidji",
		"fr-LU": "Fidji",
		"fr-MC": "Fidji",
		"it-IT": "Figi",
		"it-CH": "Figi",
		"it-SM": "Figi",
		"it-VA": "Figi",
		"de-DE": "Fidschi",
		"de-AT": "Fidschi",
		"de-CH": "Fidschi",
		"de-BE": "Fidschi",
		"de-LI": "Fidschi",
		"de-LU": "Fidschi"
	},
	"callingCode": "679"
} satisfies Country;
