import type { Country } from './types.js';

export const FRA = {
	"code": "FRA",
	"labels": {
		"pt-BR": "França",
		"pt-PT": "França",
		"es-ES": "Francia",
		"es-419": "Francia",
		"es-AR": "Francia",
		"es-BO": "Francia",
		"es-BR": "Francia",
		"es-BZ": "Francia",
		"es-CL": "Francia",
		"es-CO": "Francia",
		"es-CR": "Francia",
		"es-CU": "Francia",
		"es-DO": "Francia",
		"es-EC": "Francia",
		"es-GT": "Francia",
		"es-HN": "Francia",
		"es-MX": "Francia",
		"es-NI": "Francia",
		"es-PA": "Francia",
		"es-PE": "Francia",
		"es-PR": "Francia",
		"es-PY": "Francia",
		"es-SV": "Francia",
		"es-US": "Francia",
		"es-UY": "Francia",
		"es-VE": "Francia",
		"en-US": "France",
		"fr-FR": "France",
		"fr-BE": "France",
		"fr-CA": "France",
		"fr-CH": "France",
		"fr-LU": "France",
		"fr-MC": "France",
		"it-IT": "Francia",
		"it-CH": "Francia",
		"it-SM": "Francia",
		"it-VA": "Francia",
		"de-DE": "Frankreich",
		"de-AT": "Frankreich",
		"de-CH": "Frankreich",
		"de-BE": "Frankreich",
		"de-LI": "Frankreich",
		"de-LU": "Frankreich"
	}
} satisfies Country;
