import type { Country } from './types.js';

export const FRO = {
	"code": "FRO",
	"labels": {
		"pt-BR": "Ilhas Faroé",
		"pt-PT": "Ilhas Faroé",
		"es-ES": "Islas Feroe",
		"es-419": "Islas Feroe",
		"es-AR": "Islas Feroe",
		"es-BO": "Islas Feroe",
		"es-BR": "Islas Feroe",
		"es-BZ": "Islas Feroe",
		"es-CL": "Islas Feroe",
		"es-CO": "Islas Feroe",
		"es-CR": "Islas Feroe",
		"es-CU": "Islas Feroe",
		"es-DO": "Islas Feroe",
		"es-EC": "Islas Feroe",
		"es-GT": "Islas Feroe",
		"es-HN": "Islas Feroe",
		"es-MX": "Islas Feroe",
		"es-NI": "Islas Feroe",
		"es-PA": "Islas Feroe",
		"es-PE": "Islas Feroe",
		"es-PR": "Islas Feroe",
		"es-PY": "Islas Feroe",
		"es-SV": "Islas Feroe",
		"es-US": "Islas Feroe",
		"es-UY": "Islas Feroe",
		"es-VE": "Islas Feroe",
		"en-US": "Faroe Islands",
		"fr-FR": "Îles Féroé",
		"fr-BE": "Îles Féroé",
		"fr-CA": "îles Féroé",
		"fr-CH": "Îles Féroé",
		"fr-LU": "Îles Féroé",
		"fr-MC": "Îles Féroé",
		"it-IT": "Isole Fær Øer",
		"it-CH": "Isole Fær Øer",
		"it-SM": "Isole Fær Øer",
		"it-VA": "Isole Fær Øer",
		"de-DE": "Färöer",
		"de-AT": "Färöer",
		"de-CH": "Färöer",
		"de-BE": "Färöer",
		"de-LI": "Färöer",
		"de-LU": "Färöer"
	},
	"callingCode": "298"
} satisfies Country;
