import type { Country } from './types.js';

export const FSM = {
	"code": "FSM",
	"labels": {
		"pt-BR": "Micronésia",
		"pt-PT": "Micronésia",
		"es-ES": "Micronesia",
		"es-419": "Micronesia",
		"es-AR": "Micronesia",
		"es-BO": "Micronesia",
		"es-BR": "Micronesia",
		"es-BZ": "Micronesia",
		"es-CL": "Micronesia",
		"es-CO": "Micronesia",
		"es-CR": "Micronesia",
		"es-CU": "Micronesia",
		"es-DO": "Micronesia",
		"es-EC": "Micronesia",
		"es-GT": "Micronesia",
		"es-HN": "Micronesia",
		"es-MX": "Micronesia",
		"es-NI": "Micronesia",
		"es-PA": "Micronesia",
		"es-PE": "Micronesia",
		"es-PR": "Micronesia",
		"es-PY": "Micronesia",
		"es-SV": "Micronesia",
		"es-US": "Micronesia",
		"es-UY": "Micronesia",
		"es-VE": "Micronesia",
		"en-US": "Micronesia",
		"fr-FR": "Micronésie",
		"fr-BE": "Micronésie",
		"fr-CA": "Micronésie",
		"fr-CH": "Micronésie",
		"fr-LU": "Micronésie",
		"fr-MC": "Micronésie",
		"it-IT": "Micronesia",
		"it-CH": "Micronesia",
		"it-SM": "Micronesia",
		"it-VA": "Micronesia",
		"de-DE": "Mikronesien",
		"de-AT": "Mikronesien",
		"de-CH": "Mikronesien",
		"de-BE": "Mikronesien",
		"de-LI": "Mikronesien",
		"de-LU": "Mikronesien"
	}
} satisfies Country;
