import type { Country } from './types.js';

export const GAB = {
	"code": "GAB",
	"labels": {
		"pt-BR": "Gabão",
		"pt-PT": "Gabão",
		"es-ES": "Gabón",
		"es-419": "Gabón",
		"es-AR": "Gabón",
		"es-BO": "Gabón",
		"es-BR": "Gabón",
		"es-BZ": "Gabón",
		"es-CL": "Gabón",
		"es-CO": "Gabón",
		"es-CR": "Gabón",
		"es-CU": "Gabón",
		"es-DO": "Gabón",
		"es-EC": "Gabón",
		"es-GT": "Gabón",
		"es-HN": "Gabón",
		"es-MX": "Gabón",
		"es-NI": "Gabón",
		"es-PA": "Gabón",
		"es-PE": "Gabón",
		"es-PR": "Gabón",
		"es-PY": "Gabón",
		"es-SV": "Gabón",
		"es-US": "Gabón",
		"es-UY": "Gabón",
		"es-VE": "Gabón",
		"en-US": "Gabon",
		"fr-FR": "Gabon",
		"fr-BE": "Gabon",
		"fr-CA": "Gabon",
		"fr-CH": "Gabon",
		"fr-LU": "Gabon",
		"fr-MC": "Gabon",
		"it-IT": "Gabon",
		"it-CH": "Gabon",
		"it-SM": "Gabon",
		"it-VA": "Gabon",
		"de-DE": "Gabun",
		"de-AT": "Gabun",
		"de-CH": "Gabun",
		"de-BE": "Gabun",
		"de-LI": "Gabun",
		"de-LU": "Gabun"
	},
	"callingCode": "241"
} satisfies Country;
