import type { Country } from './types.js';

export const GBR = {
	"code": "GBR",
	"labels": {
		"pt-BR": "Reino Unido",
		"pt-PT": "Reino Unido",
		"qu-PE": "Reino Unido",
		"qu-BO": "Reino Unido",
		"qu-EC": "Reino Unido",
		"chr-US": "ᎩᎵᏏᏲ",
		"hi-IN": "यूनाइटेड किंगडम",
		"bn-IN": "যুক্তরাজ্য",
		"bn-BD": "যুক্তরাজ্য",
		"ta-IN": "யுனைடெட் கிங்டம்",
		"ta-LK": "யுனைடெட் கிங்டம்",
		"ta-SG": "யுனைடெட் கிங்டம்",
		"ta-MY": "யுனைடெட் கிங்டம்",
		"te-IN": "యునైటెడ్ కింగ్‌డమ్",
		"mr-IN": "युनायटेड किंगडम",
		"gu-IN": "યુનાઇટેડ કિંગડમ",
		"kn-IN": "ಯುನೈಟೆಡ್ ಕಿಂಗ್‌ಡಮ್",
		"ml-IN": "യുണൈറ്റഡ് കിംഗ്ഡം",
		"pa-IN": "ਯੂਨਾਈਟਡ ਕਿੰਗਡਮ",
		"ur-IN": "سلطنت متحدہ",
		"ur-PK": "سلطنت متحدہ",
		"or-IN": "ଯୁକ୍ତରାଜ୍ୟ",
		"as-IN": "সংযুক্ত ৰাজ্য",
		"ne-IN": "संयुक्त अधिराज्य",
		"ne-NP": "संयुक्त अधिराज्य",
		"si-LK": "එක්සත් රාජධානිය",
		"kok-IN": "युनायटेड किंगडम",
		"sd-IN": "बरतानी",
		"ks-IN": "متحدہ مملِکت",
		"doi-IN": "यूनाइटेड किंगडम",
		"mni-IN": "য়ুনাইটেদ কিংদম",
		"brx-IN": "जथाय ब्रिटिश हादोर",
		"sat-IN": "ᱭᱩᱱᱤᱭᱴᱮᱰ ᱠᱤᱝᱰᱚᱢ",
		"mai-IN": "यूनाइटेड किंगडम",
		"sa-IN": "संयुक्त राष्ट्र:",
		"dz-BT": "ཡུ་ནཱའི་ཊེཌ་ ཀིང་ཌམ",
		"ja-JP": "イギリス",
		"ko-KR": "영국",
		"ko-KP": "영국",
		"zh-CN": "英国",
		"zh-Hans-CN": "英国",
		"zh-Hant-TW": "英國",
		"zh-TW": "英國",
		"zh-HK": "英國",
		"zh-MO": "英國",
		"zh-SG": "英国",
		"yue-Hant-HK": "英國",
		"yue-Hans-CN": "英国",
		"mn-MN": "Их Британи",
		"bo-CN": "དབྱིན་ཇི་",
		"bo-IN": "དབྱིན་ཇི་",
		"ug-CN": "بىرلەشمە پادىشاھلىق",
		"ii-CN": "ꑱꇩ",
		"th-TH": "สหราชอาณาจักร",
		"lo-LA": "ສະຫະລາດຊະອະນາຈັກ",
		"km-KH": "ចក្រភព​អង់គ្លេស",
		"my-MM": "ယူနိုက်တက်ကင်းဒမ်း",
		"vi-VN": "Vương quốc Anh",
		"id-ID": "Inggris Raya",
		"ms-MY": "United Kingdom",
		"ms-SG": "United Kingdom",
		"ms-BN": "United Kingdom",
		"jv-ID": "Karajan Manunggal",
		"su-ID": "Britania Raya",
		"fil-PH": "United Kingdom",
		"ceb-PH": "United Kingdom",
		"ka-GE": "გაერთიანებული სამეფო",
		"hy-AM": "Միացյալ Թագավորություն",
		"az-AZ": "Birləşmiş Krallıq",
		"az-Cyrl-AZ": "Бирләшмиш Краллыг",
		"kk-KZ": "Ұлыбритания",
		"ky-KG": "Улуу Британия",
		"uz-UZ": "Buyuk Britaniya",
		"tg-TJ": "Шоҳигарии Муттаҳида",
		"tk-TM": "Birleşen Patyşalyk",
		"fa-IR": "بریتانیا",
		"fa-AF": "بریتانیا",
		"ps-AF": "برتانیه",
		"ps-PK": "برتانیه",
		"he-IL": "בריטניה",
		"ar-SA": "المملكة المتحدة",
		"ar-AE": "المملكة المتحدة",
		"ar-QA": "المملكة المتحدة",
		"ar-BH": "المملكة المتحدة",
		"ar-KW": "المملكة المتحدة",
		"ar-OM": "المملكة المتحدة",
		"ar-YE": "المملكة المتحدة",
		"ar-IQ": "المملكة المتحدة",
		"ar-JO": "المملكة المتحدة",
		"ar-LB": "المملكة المتحدة",
		"ar-SY": "المملكة المتحدة",
		"ar-PS": "المملكة المتحدة",
		"en-US": "United Kingdom",
		"en-GB": "United Kingdom",
		"en-IE": "United Kingdom",
		"en-MT": "United Kingdom",
		"en-GI": "United Kingdom",
		"en-CY": "United Kingdom",
		"en-JE": "United Kingdom",
		"en-GG": "United Kingdom",
		"en-IM": "United Kingdom",
		"en-CA": "United Kingdom",
		"en-AU": "United Kingdom",
		"en-NZ": "United Kingdom",
		"en-ZA": "United Kingdom",
		"en-IN": "United Kingdom",
		"en-SG": "United Kingdom",
		"pt-AO": "Reino Unido",
		"pt-MZ": "Reino Unido",
		"pt-CV": "Reino Unido",
		"pt-GW": "Reino Unido",
		"pt-ST": "Reino Unido",
		"pt-TL": "Reino Unido",
		"pt-MO": "Reino Unido",
		"es-ES": "Reino Unido",
		"es-419": "Reino Unido",
		"es-AD": "Reino Unido",
		"es-GI": "Reino Unido",
		"es-AR": "Reino Unido",
		"es-BO": "Reino Unido",
		"es-BR": "Reino Unido",
		"es-BZ": "Reino Unido",
		"es-CL": "Reino Unido",
		"es-CO": "Reino Unido",
		"es-CR": "Reino Unido",
		"es-CU": "Reino Unido",
		"es-DO": "Reino Unido",
		"es-EC": "Reino Unido",
		"es-GT": "Reino Unido",
		"es-HN": "Reino Unido",
		"es-MX": "Reino Unido",
		"es-NI": "Reino Unido",
		"es-PA": "Reino Unido",
		"es-PE": "Reino Unido",
		"es-PR": "Reino Unido",
		"es-PY": "Reino Unido",
		"es-SV": "Reino Unido",
		"es-US": "Reino Unido",
		"es-UY": "Reino Unido",
		"es-VE": "Reino Unido",
		"fr-FR": "Royaume-Uni",
		"fr-BE": "Royaume-Uni",
		"fr-CH": "Royaume-Uni",
		"fr-LU": "Royaume-Uni",
		"fr-MC": "Royaume-Uni",
		"fr-AD": "Royaume-Uni",
		"fr-CA": "Royaume-Uni",
		"it-IT": "Regno Unito",
		"it-CH": "Regno Unito",
		"it-SM": "Regno Unito",
		"it-VA": "Regno Unito",
		"de-DE": "Vereinigtes Königreich",
		"de-AT": "Vereinigtes Königreich",
		"de-CH": "Vereinigtes Königreich",
		"de-BE": "Vereinigtes Königreich",
		"de-LI": "Vereinigtes Königreich",
		"de-LU": "Vereinigtes Königreich",
		"nl-NL": "Verenigd Koninkrijk",
		"nl-BE": "Verenigd Koninkrijk",
		"sv-SE": "Storbritannien",
		"sv-FI": "Storbritannien",
		"da-DK": "Storbritannien",
		"nb-NO": "Storbritannia",
		"nn-NO": "Storbritannia",
		"fi-FI": "Iso-Britannia",
		"is-IS": "Bretland",
		"fo-FO": "Stórabretland",
		"et-EE": "Ühendkuningriik",
		"lv-LV": "Apvienotā Karaliste",
		"lt-LT": "Jungtinė Karalystė",
		"pl-PL": "Wielka Brytania",
		"cs-CZ": "Spojené království",
		"sk-SK": "Spojené kráľovstvo",
		"sl-SI": "Združeno kraljestvo",
		"hr-HR": "Ujedinjeno Kraljevstvo",
		"bs-BA": "Ujedinjeno Kraljevstvo",
		"sr-RS": "Уједињено Краљевство",
		"sr-BA": "Уједињено Краљевство",
		"sr-ME": "Ujedinjeno Kraljevstvo",
		"mk-MK": "Обединето Кралство",
		"bg-BG": "Обединеното кралство",
		"be-BY": "Вялікабрытанія",
		"uk-UA": "Велика Британія",
		"ru-RU": "Великобритания",
		"el-GR": "Ηνωμένο Βασίλειο",
		"el-CY": "Ηνωμένο Βασίλειο",
		"ro-RO": "Regatul Unit",
		"ro-MD": "Regatul Unit",
		"hu-HU": "Egyesült Királyság",
		"sq-AL": "Mbretëria e Bashkuar",
		"sq-XK": "Mbretëria e Bashkuar",
		"mt-MT": "ir-Renju Unit",
		"ga-IE": "an Ríocht Aontaithe",
		"cy-GB": "Y Deyrnas Unedig",
		"gd-GB": "An Rìoghachd Aonaichte",
		"lb-LU": "Groussbritannien",
		"ca-ES": "Regne Unit",
		"ca-AD": "Regne Unit",
		"ca-FR": "Regne Unit",
		"ca-IT": "Regne Unit",
		"eu-ES": "Erresuma Batua",
		"eu-FR": "Erresuma Batua",
		"gl-ES": "Reino Unido",
		"tr-TR": "Birleşik Krallık",
		"tr-CY": "Birleşik Krallık"
	},
	"callingCode": "44",
	"phoneMasks": [
		{
			"mask": "### ## ##",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"845",
				"8454",
				"84546",
				"845464"
			]
		},
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"800",
				"8001",
				"80011",
				"800111",
				"8001111"
			]
		},
		{
			"mask": "### ######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"800"
			]
		},
		{
			"mask": "## #### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[25]|7(?:0|6[02-9])",
				"[25]|7(?:0|6(?:[03-9]|2[356]))"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[1389]"
			]
		},
		{
			"mask": "#### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1(?:[2-69][02-9]|[78])"
			]
		},
		{
			"mask": "#### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"7"
			]
		},
		{
			"mask": "##### #####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1(?:38|5[23]|69|76|94)",
				"1(?:(?:38|69)7|5(?:24|39)|768|946)",
				"1(?:3873|5(?:242|39[4-6])|(?:697|768)[347]|9467)"
			]
		}
	]
} satisfies Country;
