import type { Country } from './types.js';

export const GGY = {
	"code": "GGY",
	"labels": {
		"pt-BR": "Guernsey",
		"pt-PT": "Guernesey",
		"es-ES": "Guernesey",
		"es-419": "Guernesey",
		"es-AR": "Guernesey",
		"es-BO": "Guernesey",
		"es-BR": "Guernesey",
		"es-BZ": "Guernesey",
		"es-CL": "Guernesey",
		"es-CO": "Guernesey",
		"es-CR": "Guernesey",
		"es-CU": "Guernesey",
		"es-DO": "Guernesey",
		"es-EC": "Guernesey",
		"es-GT": "Guernesey",
		"es-HN": "Guernesey",
		"es-MX": "Guernsey",
		"es-NI": "Guernesey",
		"es-PA": "Guernesey",
		"es-PE": "Guernesey",
		"es-PR": "Guernesey",
		"es-PY": "Guernesey",
		"es-SV": "Guernesey",
		"es-US": "Guernsey",
		"es-UY": "Guernesey",
		"es-VE": "Guernesey",
		"en-US": "Guernsey",
		"fr-FR": "Guernesey",
		"fr-BE": "Guernesey",
		"fr-CA": "Guernesey",
		"fr-CH": "Guernesey",
		"fr-LU": "Guernesey",
		"fr-MC": "Guernesey",
		"it-IT": "Guernsey",
		"it-CH": "Guernsey",
		"it-SM": "Guernsey",
		"it-VA": "Guernsey",
		"de-DE": "Guernsey",
		"de-AT": "Guernsey",
		"de-CH": "Guernsey",
		"de-BE": "Guernsey",
		"de-LI": "Guernsey",
		"de-LU": "Guernsey"
	}
} satisfies Country;
