import type { Country } from './types.js';

export const GHA = {
	"code": "GHA",
	"labels": {
		"pt-BR": "Gana",
		"pt-PT": "Gana",
		"es-ES": "Ghana",
		"es-419": "Ghana",
		"es-AR": "Ghana",
		"es-BO": "Ghana",
		"es-BR": "Ghana",
		"es-BZ": "Ghana",
		"es-CL": "Ghana",
		"es-CO": "Ghana",
		"es-CR": "Ghana",
		"es-CU": "Ghana",
		"es-DO": "Ghana",
		"es-EC": "Ghana",
		"es-GT": "Ghana",
		"es-HN": "Ghana",
		"es-MX": "Ghana",
		"es-NI": "Ghana",
		"es-PA": "Ghana",
		"es-PE": "Ghana",
		"es-PR": "Ghana",
		"es-PY": "Ghana",
		"es-SV": "Ghana",
		"es-US": "Ghana",
		"es-UY": "Ghana",
		"es-VE": "Ghana",
		"en-US": "Ghana",
		"fr-FR": "Ghana",
		"fr-BE": "Ghana",
		"fr-CA": "Ghana",
		"fr-CH": "Ghana",
		"fr-LU": "Ghana",
		"fr-MC": "Ghana",
		"it-IT": "Ghana",
		"it-CH": "Ghana",
		"it-SM": "Ghana",
		"it-VA": "Ghana",
		"de-DE": "Ghana",
		"de-AT": "Ghana",
		"de-CH": "Ghana",
		"de-BE": "Ghana",
		"de-LI": "Ghana",
		"de-LU": "Ghana"
	},
	"callingCode": "233"
} satisfies Country;
