import type { Country } from './types.js';

export const GIB = {
	"code": "GIB",
	"labels": {
		"pt-BR": "Gibraltar",
		"pt-PT": "Gibraltar",
		"qu-PE": "Gibraltar",
		"qu-BO": "Gibraltar",
		"qu-EC": "Gibraltar",
		"chr-US": "ᏥᏆᎵᏓ",
		"hi-IN": "जिब्राल्टर",
		"bn-IN": "জিব্রাল্টার",
		"bn-BD": "জিব্রাল্টার",
		"ta-IN": "ஜிப்ரால்டர்",
		"ta-LK": "ஜிப்ரால்டர்",
		"ta-SG": "ஜிப்ரால்டர்",
		"ta-MY": "ஜிப்ரால்டர்",
		"te-IN": "జిబ్రాల్టర్",
		"mr-IN": "जिब्राल्टर",
		"gu-IN": "જીબ્રાલ્ટર",
		"kn-IN": "ಗಿಬ್ರಾಲ್ಟರ್",
		"ml-IN": "ജിബ്രാൾട്ടർ",
		"pa-IN": "ਜਿਬਰਾਲਟਰ",
		"ur-IN": "جبل الطارق",
		"ur-PK": "جبل الطارق",
		"or-IN": "ଜିବ୍ରାଲ୍ଟର୍",
		"as-IN": "জিব্ৰাল্টৰ",
		"ne-IN": "जिब्राल्टार",
		"ne-NP": "जिब्राल्टार",
		"si-LK": "ජිබ්‍රෝල්ටාව",
		"kok-IN": "जिब्राल्टर",
		"ks-IN": "جِبرالٹَر",
		"brx-IN": "जिब्राल्टार",
		"mai-IN": "जिब्राल्टर",
		"dz-BT": "ཇིབ་རཱལ་ཊར",
		"ja-JP": "ジブラルタル",
		"ko-KR": "지브롤터",
		"ko-KP": "지브롤터",
		"zh-CN": "直布罗陀",
		"zh-Hans-CN": "直布罗陀",
		"zh-Hant-TW": "直布羅陀",
		"zh-TW": "直布羅陀",
		"zh-HK": "直布羅陀",
		"zh-MO": "直布羅陀",
		"zh-SG": "直布罗陀",
		"yue-Hant-HK": "直布羅陀",
		"yue-Hans-CN": "直布罗陀",
		"mn-MN": "Гибралтар",
		"ug-CN": "جەبىلتارىق",
		"th-TH": "ยิบรอลตาร์",
		"lo-LA": "ຈິບບຣອນທາ",
		"km-KH": "ហ្ស៊ីប្រាល់តា",
		"my-MM": "ဂျီဘရော်လ်တာ",
		"vi-VN": "Gibraltar",
		"id-ID": "Gibraltar",
		"ms-MY": "Gibraltar",
		"ms-SG": "Gibraltar",
		"ms-BN": "Gibraltar",
		"jv-ID": "Gibraltar",
		"fil-PH": "Gibraltar",
		"ceb-PH": "Gibraltar",
		"ka-GE": "გიბრალტარი",
		"hy-AM": "Ջիբրալթար",
		"az-AZ": "Cəbəllütariq",
		"az-Cyrl-AZ": "Ҹәбәллүтариг",
		"kk-KZ": "Гибралтар",
		"ky-KG": "Гибралтар",
		"uz-UZ": "Gibraltar",
		"tg-TJ": "Гибралтар",
		"tk-TM": "Gibraltar",
		"fa-IR": "جبل‌الطارق",
		"fa-AF": "جبل‌الطارق",
		"ps-AF": "جبل الطارق",
		"ps-PK": "جبل الطارق",
		"he-IL": "גיברלטר",
		"ar-SA": "جبل طارق",
		"ar-AE": "جبل طارق",
		"ar-QA": "جبل طارق",
		"ar-BH": "جبل طارق",
		"ar-KW": "جبل طارق",
		"ar-OM": "جبل طارق",
		"ar-YE": "جبل طارق",
		"ar-IQ": "جبل طارق",
		"ar-JO": "جبل طارق",
		"ar-LB": "جبل طارق",
		"ar-SY": "جبل طارق",
		"ar-PS": "جبل طارق",
		"en-US": "Gibraltar",
		"en-GB": "Gibraltar",
		"en-IE": "Gibraltar",
		"en-MT": "Gibraltar",
		"en-GI": "Gibraltar",
		"en-CY": "Gibraltar",
		"en-JE": "Gibraltar",
		"en-GG": "Gibraltar",
		"en-IM": "Gibraltar",
		"en-CA": "Gibraltar",
		"en-AU": "Gibraltar",
		"en-NZ": "Gibraltar",
		"en-ZA": "Gibraltar",
		"en-IN": "Gibraltar",
		"en-SG": "Gibraltar",
		"pt-AO": "Gibraltar",
		"pt-MZ": "Gibraltar",
		"pt-CV": "Gibraltar",
		"pt-GW": "Gibraltar",
		"pt-ST": "Gibraltar",
		"pt-TL": "Gibraltar",
		"pt-MO": "Gibraltar",
		"es-ES": "Gibraltar",
		"es-419": "Gibraltar",
		"es-AD": "Gibraltar",
		"es-GI": "Gibraltar",
		"es-AR": "Gibraltar",
		"es-BO": "Gibraltar",
		"es-BR": "Gibraltar",
		"es-BZ": "Gibraltar",
		"es-CL": "Gibraltar",
		"es-CO": "Gibraltar",
		"es-CR": "Gibraltar",
		"es-CU": "Gibraltar",
		"es-DO": "Gibraltar",
		"es-EC": "Gibraltar",
		"es-GT": "Gibraltar",
		"es-HN": "Gibraltar",
		"es-MX": "Gibraltar",
		"es-NI": "Gibraltar",
		"es-PA": "Gibraltar",
		"es-PE": "Gibraltar",
		"es-PR": "Gibraltar",
		"es-PY": "Gibraltar",
		"es-SV": "Gibraltar",
		"es-US": "Gibraltar",
		"es-UY": "Gibraltar",
		"es-VE": "Gibraltar",
		"fr-FR": "Gibraltar",
		"fr-BE": "Gibraltar",
		"fr-CH": "Gibraltar",
		"fr-LU": "Gibraltar",
		"fr-MC": "Gibraltar",
		"fr-AD": "Gibraltar",
		"fr-CA": "Gibraltar",
		"it-IT": "Gibilterra",
		"it-CH": "Gibilterra",
		"it-SM": "Gibilterra",
		"it-VA": "Gibilterra",
		"de-DE": "Gibraltar",
		"de-AT": "Gibraltar",
		"de-CH": "Gibraltar",
		"de-BE": "Gibraltar",
		"de-LI": "Gibraltar",
		"de-LU": "Gibraltar",
		"nl-NL": "Gibraltar",
		"nl-BE": "Gibraltar",
		"sv-SE": "Gibraltar",
		"sv-FI": "Gibraltar",
		"da-DK": "Gibraltar",
		"nb-NO": "Gibraltar",
		"nn-NO": "Gibraltar",
		"fi-FI": "Gibraltar",
		"is-IS": "Gíbraltar",
		"fo-FO": "Gibraltar",
		"et-EE": "Gibraltar",
		"lv-LV": "Gibraltārs",
		"lt-LT": "Gibraltaras",
		"pl-PL": "Gibraltar",
		"cs-CZ": "Gibraltar",
		"sk-SK": "Gibraltár",
		"sl-SI": "Gibraltar",
		"hr-HR": "Gibraltar",
		"bs-BA": "Gibraltar",
		"sr-RS": "Гибралтар",
		"sr-BA": "Гибралтар",
		"sr-ME": "Gibraltar",
		"mk-MK": "Гибралтар",
		"bg-BG": "Гибралтар",
		"be-BY": "Гібралтар",
		"uk-UA": "Гібралтар",
		"ru-RU": "Гибралтар",
		"el-GR": "Γιβραλτάρ",
		"el-CY": "Γιβραλτάρ",
		"ro-RO": "Gibraltar",
		"ro-MD": "Gibraltar",
		"hu-HU": "Gibraltár",
		"sq-AL": "Gjibraltar",
		"sq-XK": "Gjibraltar",
		"mt-MT": "Ġibiltà",
		"ga-IE": "Giobráltar",
		"cy-GB": "Gibraltar",
		"gd-GB": "Diobraltar",
		"lb-LU": "Gibraltar",
		"ca-ES": "Gibraltar",
		"ca-AD": "Gibraltar",
		"ca-FR": "Gibraltar",
		"ca-IT": "Gibraltar",
		"eu-ES": "Gibraltar",
		"eu-FR": "Gibraltar",
		"gl-ES": "Xibraltar",
		"tr-TR": "Cebelitarık",
		"tr-CY": "Cebelitarık"
	},
	"callingCode": "350",
	"phoneMasks": [
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2"
			]
		}
	]
} satisfies Country;
