import type { Country } from './types.js';

export const GLP = {
	"code": "GLP",
	"labels": {
		"pt-BR": "Guadalupe",
		"pt-PT": "Guadalupe",
		"es-ES": "Guadalupe",
		"es-419": "Guadalupe",
		"es-AR": "Guadalupe",
		"es-BO": "Guadalupe",
		"es-BR": "Guadalupe",
		"es-BZ": "Guadalupe",
		"es-CL": "Guadalupe",
		"es-CO": "Guadalupe",
		"es-CR": "Guadalupe",
		"es-CU": "Guadalupe",
		"es-DO": "Guadalupe",
		"es-EC": "Guadalupe",
		"es-GT": "Guadalupe",
		"es-HN": "Guadalupe",
		"es-MX": "Guadalupe",
		"es-NI": "Guadalupe",
		"es-PA": "Guadalupe",
		"es-PE": "Guadalupe",
		"es-PR": "Guadalupe",
		"es-PY": "Guadalupe",
		"es-SV": "Guadalupe",
		"es-US": "Guadalupe",
		"es-UY": "Guadalupe",
		"es-VE": "Guadalupe",
		"en-US": "Guadeloupe",
		"fr-FR": "Guadeloupe",
		"fr-BE": "Guadeloupe",
		"fr-CA": "Guadeloupe",
		"fr-CH": "Guadeloupe",
		"fr-LU": "Guadeloupe",
		"fr-MC": "Guadeloupe",
		"it-IT": "Guadalupa",
		"it-CH": "Guadalupa",
		"it-SM": "Guadalupa",
		"it-VA": "Guadalupa",
		"de-DE": "Guadeloupe",
		"de-AT": "Guadeloupe",
		"de-CH": "Guadeloupe",
		"de-BE": "Guadeloupe",
		"de-LI": "Guadeloupe",
		"de-LU": "Guadeloupe"
	},
	"callingCode": "590"
} satisfies Country;
