import type { Country } from './types.js';

export const GMB = {
	"code": "GMB",
	"labels": {
		"pt-BR": "Gâmbia",
		"pt-PT": "Gâmbia",
		"es-ES": "Gambia",
		"es-419": "Gambia",
		"es-AR": "Gambia",
		"es-BO": "Gambia",
		"es-BR": "Gambia",
		"es-BZ": "Gambia",
		"es-CL": "Gambia",
		"es-CO": "Gambia",
		"es-CR": "Gambia",
		"es-CU": "Gambia",
		"es-DO": "Gambia",
		"es-EC": "Gambia",
		"es-GT": "Gambia",
		"es-HN": "Gambia",
		"es-MX": "Gambia",
		"es-NI": "Gambia",
		"es-PA": "Gambia",
		"es-PE": "Gambia",
		"es-PR": "Gambia",
		"es-PY": "Gambia",
		"es-SV": "Gambia",
		"es-US": "Gambia",
		"es-UY": "Gambia",
		"es-VE": "Gambia",
		"en-US": "Gambia",
		"fr-FR": "Gambie",
		"fr-BE": "Gambie",
		"fr-CA": "Gambie",
		"fr-CH": "Gambie",
		"fr-LU": "Gambie",
		"fr-MC": "Gambie",
		"it-IT": "Gambia",
		"it-CH": "Gambia",
		"it-SM": "Gambia",
		"it-VA": "Gambia",
		"de-DE": "Gambia",
		"de-AT": "Gambia",
		"de-CH": "Gambia",
		"de-BE": "Gambia",
		"de-LI": "Gambia",
		"de-LU": "Gambia"
	}
} satisfies Country;
