import type { Country } from './types.js';

export const GNB = {
	"code": "GNB",
	"labels": {
		"pt-BR": "Guiné-Bissau",
		"pt-PT": "Guiné-Bissau",
		"qu-PE": "Guinea-Bisáu",
		"qu-BO": "Guinea-Bisáu",
		"qu-EC": "Guinea-Bisáu",
		"chr-US": "ᎩᎢᏂ-ᏈᏌᎤᏫ",
		"hi-IN": "गिनी-बिसाउ",
		"bn-IN": "গিনি-বিসাউ",
		"bn-BD": "গিনি-বিসাউ",
		"ta-IN": "கினியா-பிஸ்ஸாவ்",
		"ta-LK": "கினியா-பிஸ்ஸாவ்",
		"ta-SG": "கினியா-பிஸ்ஸாவ்",
		"ta-MY": "கினியா-பிஸ்ஸாவ்",
		"te-IN": "గినియా-బిస్సావ్",
		"mr-IN": "गिनी-बिसाउ",
		"gu-IN": "ગિની-બિસાઉ",
		"kn-IN": "ಗಿನಿ-ಬಿಸ್ಸಾವ್",
		"ml-IN": "ഗിനിയ-ബിസൗ",
		"pa-IN": "ਗਿਨੀ-ਬਿਸਾਉ",
		"ur-IN": "گنی بساؤ",
		"ur-PK": "گنی بساؤ",
		"or-IN": "ଗୁଇନିଆ-ବିସାଉ",
		"as-IN": "গিনি-বিছাও",
		"ne-IN": "गिनी-बिसाउ",
		"ne-NP": "गिनी-बिसाउ",
		"si-LK": "ගිනි බිසව්",
		"kok-IN": "गुअनिया-बिसाउ",
		"ks-IN": "گیٖنی بِساو",
		"brx-IN": "गिनीया- बिसाऊ",
		"mai-IN": "गिनी-बिसाऊ",
		"dz-BT": "གྷི་ནི་ བྷི་སཱའུ",
		"ja-JP": "ギニアビサウ",
		"ko-KR": "기니비사우",
		"ko-KP": "기니비사우",
		"zh-CN": "几内亚比绍",
		"zh-Hans-CN": "几内亚比绍",
		"zh-Hant-TW": "幾內亞比索",
		"zh-TW": "幾內亞比索",
		"zh-HK": "幾內亞比紹",
		"zh-MO": "幾內亞比紹",
		"zh-SG": "几内亚比绍",
		"yue-Hant-HK": "幾內亞比索",
		"yue-Hans-CN": "几内亚比索",
		"mn-MN": "Гвиней-Бисау",
		"ug-CN": "گىۋىنىيە بىسسائۇ",
		"th-TH": "กินี-บิสเซา",
		"lo-LA": "ກິນີ-ບິສເຊົາ",
		"km-KH": "ហ្គីណេប៊ីស្សូ",
		"my-MM": "ဂီနီ-ဘီစော",
		"vi-VN": "Guinea-Bissau",
		"id-ID": "Guinea-Bissau",
		"ms-MY": "Guinea Bissau",
		"ms-SG": "Guinea Bissau",
		"ms-BN": "Guinea Bissau",
		"jv-ID": "Guinea-Bissau",
		"fil-PH": "Guinea-Bissau",
		"ceb-PH": "Guinea-Bissau",
		"ka-GE": "გვინეა-ბისაუ",
		"hy-AM": "Գվինեա-Բիսաու",
		"az-AZ": "Qvineya-Bisau",
		"az-Cyrl-AZ": "Гвинеја-Бисау",
		"kk-KZ": "Гвинея-Бисау",
		"ky-KG": "Гвинея-Бисау",
		"uz-UZ": "Gvineya-Bisau",
		"tg-TJ": "Гвинея-Бисау",
		"tk-TM": "Gwineýa-Bisau",
		"fa-IR": "گینهٔ بیسائو",
		"fa-AF": "گینیا بیسائو",
		"ps-AF": "ګینه بیسو",
		"ps-PK": "ګینه بیسو",
		"he-IL": "גינאה-ביסאו",
		"ar-SA": "غينيا بيساو",
		"ar-AE": "غينيا بيساو",
		"ar-QA": "غينيا بيساو",
		"ar-BH": "غينيا بيساو",
		"ar-KW": "غينيا بيساو",
		"ar-OM": "غينيا بيساو",
		"ar-YE": "غينيا بيساو",
		"ar-IQ": "غينيا بيساو",
		"ar-JO": "غينيا بيساو",
		"ar-LB": "غينيا بيساو",
		"ar-SY": "غينيا بيساو",
		"ar-PS": "غينيا بيساو",
		"en-US": "Guinea-Bissau",
		"en-GB": "Guinea-Bissau",
		"en-IE": "Guinea-Bissau",
		"en-MT": "Guinea-Bissau",
		"en-GI": "Guinea-Bissau",
		"en-CY": "Guinea-Bissau",
		"en-JE": "Guinea-Bissau",
		"en-GG": "Guinea-Bissau",
		"en-IM": "Guinea-Bissau",
		"en-CA": "Guinea-Bissau",
		"en-AU": "Guinea-Bissau",
		"en-NZ": "Guinea-Bissau",
		"en-ZA": "Guinea-Bissau",
		"en-IN": "Guinea-Bissau",
		"en-SG": "Guinea-Bissau",
		"pt-AO": "Guiné-Bissau",
		"pt-MZ": "Guiné-Bissau",
		"pt-CV": "Guiné-Bissau",
		"pt-GW": "Guiné-Bissau",
		"pt-ST": "Guiné-Bissau",
		"pt-TL": "Guiné-Bissau",
		"pt-MO": "Guiné-Bissau",
		"es-ES": "Guinea-Bisáu",
		"es-419": "Guinea-Bisáu",
		"es-AD": "Guinea-Bisáu",
		"es-GI": "Guinea-Bisáu",
		"es-AR": "Guinea-Bisáu",
		"es-BO": "Guinea-Bisáu",
		"es-BR": "Guinea-Bisáu",
		"es-BZ": "Guinea-Bisáu",
		"es-CL": "Guinea-Bisáu",
		"es-CO": "Guinea-Bisáu",
		"es-CR": "Guinea-Bisáu",
		"es-CU": "Guinea-Bisáu",
		"es-DO": "Guinea-Bisáu",
		"es-EC": "Guinea-Bisáu",
		"es-GT": "Guinea-Bisáu",
		"es-HN": "Guinea-Bisáu",
		"es-MX": "Guinea-Bisáu",
		"es-NI": "Guinea-Bisáu",
		"es-PA": "Guinea-Bisáu",
		"es-PE": "Guinea-Bisáu",
		"es-PR": "Guinea-Bisáu",
		"es-PY": "Guinea-Bisáu",
		"es-SV": "Guinea-Bisáu",
		"es-US": "Guinea-Bisáu",
		"es-UY": "Guinea-Bisáu",
		"es-VE": "Guinea-Bisáu",
		"fr-FR": "Guinée-Bissau",
		"fr-BE": "Guinée-Bissau",
		"fr-CH": "Guinée-Bissau",
		"fr-LU": "Guinée-Bissau",
		"fr-MC": "Guinée-Bissau",
		"fr-AD": "Guinée-Bissau",
		"fr-CA": "Guinée-Bissau",
		"it-IT": "Guinea-Bissau",
		"it-CH": "Guinea-Bissau",
		"it-SM": "Guinea-Bissau",
		"it-VA": "Guinea-Bissau",
		"de-DE": "Guinea-Bissau",
		"de-AT": "Guinea-Bissau",
		"de-CH": "Guinea-Bissau",
		"de-BE": "Guinea-Bissau",
		"de-LI": "Guinea-Bissau",
		"de-LU": "Guinea-Bissau",
		"nl-NL": "Guinee-Bissau",
		"nl-BE": "Guinee-Bissau",
		"sv-SE": "Guinea-Bissau",
		"sv-FI": "Guinea-Bissau",
		"da-DK": "Guinea-Bissau",
		"nb-NO": "Guinea-Bissau",
		"nn-NO": "Guinea-Bissau",
		"fi-FI": "Guinea-Bissau",
		"is-IS": "Gínea-Bissá",
		"fo-FO": "Guinea-Bissau",
		"et-EE": "Guinea-Bissau",
		"lv-LV": "Gvineja-Bisava",
		"lt-LT": "Bisau Gvinėja",
		"pl-PL": "Gwinea Bissau",
		"cs-CZ": "Guinea-Bissau",
		"sk-SK": "Guinea-Bissau",
		"sl-SI": "Gvineja Bissau",
		"hr-HR": "Gvineja Bisau",
		"bs-BA": "Gvineja-Bisao",
		"sr-RS": "Гвинеја-Бисао",
		"sr-BA": "Гвинеја Бисао",
		"sr-ME": "Gvineja-Bisao",
		"mk-MK": "Гвинеја Бисао",
		"bg-BG": "Гвинея-Бисау",
		"be-BY": "Гвінея-Бісау",
		"uk-UA": "Гвінея-Бісау",
		"ru-RU": "Гвинея-Бисау",
		"el-GR": "Γουινέα Μπισάου",
		"el-CY": "Γουινέα Μπισάου",
		"ro-RO": "Guineea-Bissau",
		"ro-MD": "Guineea-Bissau",
		"hu-HU": "Bissau-Guinea",
		"sq-AL": "Guine-Bisau",
		"sq-XK": "Guine-Bisau",
		"mt-MT": "il-Guinea-Bissau",
		"ga-IE": "Guine Bissau",
		"cy-GB": "Guiné-Bissau",
		"gd-GB": "Gini-Bioso",
		"lb-LU": "Guinea-Bissau",
		"ca-ES": "Guinea Bissau",
		"ca-AD": "Guinea Bissau",
		"ca-FR": "Guinea Bissau",
		"ca-IT": "Guinea Bissau",
		"eu-ES": "Ginea Bissau",
		"eu-FR": "Ginea Bissau",
		"gl-ES": "Guinea Bissau",
		"tr-TR": "Gine-Bissau",
		"tr-CY": "Gine-Bissau"
	},
	"callingCode": "245",
	"phoneMasks": [
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"40"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[49]"
			]
		}
	]
} satisfies Country;
