import type { Country } from './types.js';

export const GRC = {
	"code": "GRC",
	"labels": {
		"pt-BR": "Grécia",
		"pt-PT": "Grécia",
		"es-ES": "Grecia",
		"es-419": "Grecia",
		"es-AR": "Grecia",
		"es-BO": "Grecia",
		"es-BR": "Grecia",
		"es-BZ": "Grecia",
		"es-CL": "Grecia",
		"es-CO": "Grecia",
		"es-CR": "Grecia",
		"es-CU": "Grecia",
		"es-DO": "Grecia",
		"es-EC": "Grecia",
		"es-GT": "Grecia",
		"es-HN": "Grecia",
		"es-MX": "Grecia",
		"es-NI": "Grecia",
		"es-PA": "Grecia",
		"es-PE": "Grecia",
		"es-PR": "Grecia",
		"es-PY": "Grecia",
		"es-SV": "Grecia",
		"es-US": "Grecia",
		"es-UY": "Grecia",
		"es-VE": "Grecia",
		"en-US": "Greece",
		"fr-FR": "Grèce",
		"fr-BE": "Grèce",
		"fr-CA": "Grèce",
		"fr-CH": "Grèce",
		"fr-LU": "Grèce",
		"fr-MC": "Grèce",
		"it-IT": "Grecia",
		"it-CH": "Grecia",
		"it-SM": "Grecia",
		"it-VA": "Grecia",
		"de-DE": "Griechenland",
		"de-AT": "Griechenland",
		"de-CH": "Griechenland",
		"de-BE": "Griechenland",
		"de-LI": "Griechenland",
		"de-LU": "Griechenland"
	}
} satisfies Country;
