import type { Country } from './types.js';

export const GTM = {
	"code": "GTM",
	"labels": {
		"pt-BR": "Guatemala",
		"pt-PT": "Guatemala",
		"es-ES": "Guatemala",
		"es-419": "Guatemala",
		"es-AR": "Guatemala",
		"es-BO": "Guatemala",
		"es-BR": "Guatemala",
		"es-BZ": "Guatemala",
		"es-CL": "Guatemala",
		"es-CO": "Guatemala",
		"es-CR": "Guatemala",
		"es-CU": "Guatemala",
		"es-DO": "Guatemala",
		"es-EC": "Guatemala",
		"es-GT": "Guatemala",
		"es-HN": "Guatemala",
		"es-MX": "Guatemala",
		"es-NI": "Guatemala",
		"es-PA": "Guatemala",
		"es-PE": "Guatemala",
		"es-PR": "Guatemala",
		"es-PY": "Guatemala",
		"es-SV": "Guatemala",
		"es-US": "Guatemala",
		"es-UY": "Guatemala",
		"es-VE": "Guatemala",
		"en-US": "Guatemala",
		"fr-FR": "Guatemala",
		"fr-BE": "Guatemala",
		"fr-CA": "Guatemala",
		"fr-CH": "Guatemala",
		"fr-LU": "Guatemala",
		"fr-MC": "Guatemala",
		"it-IT": "Guatemala",
		"it-CH": "Guatemala",
		"it-SM": "Guatemala",
		"it-VA": "Guatemala",
		"de-DE": "Guatemala",
		"de-AT": "Guatemala",
		"de-CH": "Guatemala",
		"de-BE": "Guatemala",
		"de-LI": "Guatemala",
		"de-LU": "Guatemala"
	},
	"callingCode": "502"
} satisfies Country;
