import type { Country } from './types.js';

export const GUF = {
	"code": "GUF",
	"labels": {
		"pt-BR": "Guiana Francesa",
		"pt-PT": "Guiana Francesa",
		"qu-PE": "Guayana Francesa",
		"qu-BO": "Guayana Francesa",
		"qu-EC": "Guayana Francesa",
		"chr-US": "ᎠᏂᎦᎸᏥ ᎩᎠ",
		"hi-IN": "फ़्रेंच गुयाना",
		"bn-IN": "ফরাসী গায়ানা",
		"bn-BD": "ফরাসী গায়ানা",
		"ta-IN": "பிரெஞ்சு கயானா",
		"ta-LK": "பிரெஞ்சு கயானா",
		"ta-SG": "பிரெஞ்சு கயானா",
		"ta-MY": "பிரெஞ்சு கயானா",
		"te-IN": "ఫ్రెంచ్ గియానా",
		"mr-IN": "फ्रेंच गयाना",
		"gu-IN": "ફ્રેંચ ગયાના",
		"kn-IN": "ಫ್ರೆಂಚ್ ಗಯಾನಾ",
		"ml-IN": "ഫ്രഞ്ച് ഗയാന",
		"pa-IN": "ਫਰੈਂਚ ਗੁਇਆਨਾ",
		"ur-IN": "فرانسیسی گیانا",
		"ur-PK": "فرینچ گیانا",
		"or-IN": "ଫ୍ରେଞ୍ଚ ଗୁଇନା",
		"as-IN": "ফ্ৰান্স গয়ানা",
		"ne-IN": "फ्रान्सेली गायना",
		"ne-NP": "फ्रान्सेली गायना",
		"si-LK": "ප්‍රංශ ගයනාව",
		"kok-IN": "फ्रेन्च गयाना",
		"ks-IN": "فرانسِسی گِانا",
		"brx-IN": "फ्रेन्च गिआना",
		"mai-IN": "फ्रेंच गुयाना",
		"dz-BT": "གུའི་ཡ་ན་ ཕྲནས྄་མངའ་ཁོངས",
		"ja-JP": "仏領ギアナ",
		"ko-KR": "프랑스령 기아나",
		"ko-KP": "프랑스령 기아나",
		"zh-CN": "法属圭亚那",
		"zh-Hans-CN": "法属圭亚那",
		"zh-Hant-TW": "法屬圭亞那",
		"zh-TW": "法屬圭亞那",
		"zh-HK": "法屬圭亞那",
		"zh-MO": "法屬圭亞那",
		"zh-SG": "法属圭亚那",
		"yue-Hant-HK": "法屬圭亞那",
		"yue-Hans-CN": "法属圭亚那",
		"mn-MN": "Францын Гвиана",
		"ug-CN": "فىرانسىيەگە قاراشلىق گىۋىيانا",
		"th-TH": "เฟรนช์เกียนา",
		"lo-LA": "ເຟຣນຊ໌ ກຸຍອານາ",
		"km-KH": "ហ្គីអាណា បារាំង",
		"my-MM": "ပြင်သစ် ဂီယာနာ",
		"vi-VN": "Guiana thuộc Pháp",
		"id-ID": "Guyana Prancis",
		"ms-MY": "Guiana Perancis",
		"ms-SG": "Guiana Perancis",
		"ms-BN": "Guiana Perancis",
		"jv-ID": "Guyana Prancis",
		"fil-PH": "French Guiana",
		"ceb-PH": "French Guiana",
		"ka-GE": "საფრანგეთის გვიანა",
		"hy-AM": "Ֆրանսիական Գվիանա",
		"az-AZ": "Fransa Qvianası",
		"az-Cyrl-AZ": "Франса Гвианасы",
		"kk-KZ": "Француз Гвианасы",
		"ky-KG": "Франция Гвианасы",
		"uz-UZ": "Fransuz Gvianasi",
		"tg-TJ": "Гвианаи Фаронса",
		"tk-TM": "Fransuz Gwianasy",
		"fa-IR": "گویان فرانسه",
		"fa-AF": "گویان فرانسه",
		"ps-AF": "فرانسوي ګانا",
		"ps-PK": "فرانسوي ګانا",
		"he-IL": "גיאנה הצרפתית",
		"ar-SA": "غويانا الفرنسية",
		"ar-AE": "غويانا الفرنسية",
		"ar-QA": "غويانا الفرنسية",
		"ar-BH": "غويانا الفرنسية",
		"ar-KW": "غويانا الفرنسية",
		"ar-OM": "غويانا الفرنسية",
		"ar-YE": "غويانا الفرنسية",
		"ar-IQ": "غويانا الفرنسية",
		"ar-JO": "غويانا الفرنسية",
		"ar-LB": "غويانا الفرنسية",
		"ar-SY": "غويانا الفرنسية",
		"ar-PS": "غويانا الفرنسية",
		"en-US": "French Guiana",
		"en-GB": "French Guiana",
		"en-IE": "French Guiana",
		"en-MT": "French Guiana",
		"en-GI": "French Guiana",
		"en-CY": "French Guiana",
		"en-JE": "French Guiana",
		"en-GG": "French Guiana",
		"en-IM": "French Guiana",
		"en-CA": "French Guiana",
		"en-AU": "French Guiana",
		"en-NZ": "French Guiana",
		"en-ZA": "French Guiana",
		"en-IN": "French Guiana",
		"en-SG": "French Guiana",
		"pt-AO": "Guiana Francesa",
		"pt-MZ": "Guiana Francesa",
		"pt-CV": "Guiana Francesa",
		"pt-GW": "Guiana Francesa",
		"pt-ST": "Guiana Francesa",
		"pt-TL": "Guiana Francesa",
		"pt-MO": "Guiana Francesa",
		"es-ES": "Guayana Francesa",
		"es-419": "Guayana Francesa",
		"es-AD": "Guayana Francesa",
		"es-GI": "Guayana Francesa",
		"es-AR": "Guayana Francesa",
		"es-BO": "Guayana Francesa",
		"es-BR": "Guayana Francesa",
		"es-BZ": "Guayana Francesa",
		"es-CL": "Guayana Francesa",
		"es-CO": "Guayana Francesa",
		"es-CR": "Guayana Francesa",
		"es-CU": "Guayana Francesa",
		"es-DO": "Guayana Francesa",
		"es-EC": "Guayana Francesa",
		"es-GT": "Guayana Francesa",
		"es-HN": "Guayana Francesa",
		"es-MX": "Guayana Francesa",
		"es-NI": "Guayana Francesa",
		"es-PA": "Guayana Francesa",
		"es-PE": "Guayana Francesa",
		"es-PR": "Guayana Francesa",
		"es-PY": "Guayana Francesa",
		"es-SV": "Guayana Francesa",
		"es-US": "Guayana Francesa",
		"es-UY": "Guayana Francesa",
		"es-VE": "Guayana Francesa",
		"fr-FR": "Guyane française",
		"fr-BE": "Guyane française",
		"fr-CH": "Guyane française",
		"fr-LU": "Guyane française",
		"fr-MC": "Guyane française",
		"fr-AD": "Guyane française",
		"fr-CA": "Guyane française",
		"it-IT": "Guyana Francese",
		"it-CH": "Guyana Francese",
		"it-SM": "Guyana Francese",
		"it-VA": "Guyana Francese",
		"de-DE": "Französisch-Guayana",
		"de-AT": "Französisch-Guayana",
		"de-CH": "Französisch-Guayana",
		"de-BE": "Französisch-Guayana",
		"de-LI": "Französisch-Guayana",
		"de-LU": "Französisch-Guayana",
		"nl-NL": "Frans-Guyana",
		"nl-BE": "Frans-Guyana",
		"sv-SE": "Franska Guyana",
		"sv-FI": "Franska Guyana",
		"da-DK": "Fransk Guyana",
		"nb-NO": "Fransk Guyana",
		"nn-NO": "Fransk Guyana",
		"fi-FI": "Ranskan Guayana",
		"is-IS": "Franska Gvæjana",
		"fo-FO": "Franska Gujana",
		"et-EE": "Prantsuse Guajaana",
		"lv-LV": "Francijas Gviāna",
		"lt-LT": "Prancūzijos Gviana",
		"pl-PL": "Gujana Francuska",
		"cs-CZ": "Francouzská Guyana",
		"sk-SK": "Francúzska Guyana",
		"sl-SI": "Francoska Gvajana",
		"hr-HR": "Francuska Gijana",
		"bs-BA": "Francuska Gvajana",
		"sr-RS": "Француска Гвајана",
		"sr-BA": "Француска Гвајана",
		"sr-ME": "Francuska Gvajana",
		"mk-MK": "Француска Гвајана",
		"bg-BG": "Френска Гвиана",
		"be-BY": "Французская Гвіяна",
		"uk-UA": "Французька Гвіана",
		"ru-RU": "Французская Гвиана",
		"el-GR": "Γαλλική Γουιάνα",
		"el-CY": "Γαλλική Γουιάνα",
		"ro-RO": "Guyana Franceză",
		"ro-MD": "Guyana Franceză",
		"hu-HU": "Francia Guyana",
		"sq-AL": "Guajana Franceze",
		"sq-XK": "Guajana Franceze",
		"mt-MT": "il-Guyana Franċiża",
		"ga-IE": "Guáin na Fraince",
		"cy-GB": "Guyane Ffrengig",
		"gd-GB": "Guidheàna na Frainge",
		"lb-LU": "Guayane",
		"ca-ES": "Guaiana Francesa",
		"ca-AD": "Guaiana Francesa",
		"ca-FR": "Guaiana Francesa",
		"ca-IT": "Guaiana Francesa",
		"eu-ES": "Guyana Frantsesa",
		"eu-FR": "Guyana Frantsesa",
		"gl-ES": "Güiana Francesa",
		"tr-TR": "Fransız Guyanası",
		"tr-CY": "Fransız Guyanası"
	},
	"callingCode": "594",
	"phoneMasks": [
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[5-7]|9[47]"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
