import type { Country } from './types.js';

export const GUF = {
	"code": "GUF",
	"labels": {
		"pt-BR": "Guiana Francesa",
		"pt-PT": "Guiana Francesa",
		"es-ES": "Guayana Francesa",
		"es-419": "Guayana Francesa",
		"es-AR": "Guayana Francesa",
		"es-BO": "Guayana Francesa",
		"es-BR": "Guayana Francesa",
		"es-BZ": "Guayana Francesa",
		"es-CL": "Guayana Francesa",
		"es-CO": "Guayana Francesa",
		"es-CR": "Guayana Francesa",
		"es-CU": "Guayana Francesa",
		"es-DO": "Guayana Francesa",
		"es-EC": "Guayana Francesa",
		"es-GT": "Guayana Francesa",
		"es-HN": "Guayana Francesa",
		"es-MX": "Guayana Francesa",
		"es-NI": "Guayana Francesa",
		"es-PA": "Guayana Francesa",
		"es-PE": "Guayana Francesa",
		"es-PR": "Guayana Francesa",
		"es-PY": "Guayana Francesa",
		"es-SV": "Guayana Francesa",
		"es-US": "Guayana Francesa",
		"es-UY": "Guayana Francesa",
		"es-VE": "Guayana Francesa",
		"en-US": "French Guiana",
		"fr-FR": "Guyane française",
		"fr-BE": "Guyane française",
		"fr-CA": "Guyane française",
		"fr-CH": "Guyane française",
		"fr-LU": "Guyane française",
		"fr-MC": "Guyane française",
		"it-IT": "Guyana Francese",
		"it-CH": "Guyana Francese",
		"it-SM": "Guyana Francese",
		"it-VA": "Guyana Francese",
		"de-DE": "Französisch-Guayana",
		"de-AT": "Französisch-Guayana",
		"de-CH": "Französisch-Guayana",
		"de-BE": "Französisch-Guayana",
		"de-LI": "Französisch-Guayana",
		"de-LU": "Französisch-Guayana"
	},
	"callingCode": "594"
} satisfies Country;
