import type { Country } from './types.js';

export const HMD = {
	"code": "HMD",
	"labels": {
		"pt-BR": "Ilhas Heard e McDonald",
		"pt-PT": "Ilhas Heard e McDonald",
		"qu-PE": "Islas Heard y McDonald",
		"qu-BO": "Islas Heard y McDonald",
		"qu-EC": "Islas Heard y McDonald",
		"chr-US": "ᎲᏗ ᎤᎦᏚᏛᎢ ᎠᎴ ᎺᎩᏓᎾᎵᏗ ᏚᎦᏚᏛᎢ",
		"hi-IN": "हर्ड द्वीप और मैकडोनॉल्ड द्वीपसमूह",
		"bn-IN": "হার্ড এবং ম্যাকডোনাল্ড দ্বীপপুঞ্জ",
		"bn-BD": "হার্ড এবং ম্যাকডোনাল্ড দ্বীপপুঞ্জ",
		"ta-IN": "ஹேர்ட் மற்றும் மெக்டொனால்டு தீவுகள்",
		"ta-LK": "ஹேர்ட் மற்றும் மெக்டொனால்டு தீவுகள்",
		"ta-SG": "ஹேர்ட் மற்றும் மெக்டொனால்டு தீவுகள்",
		"ta-MY": "ஹேர்ட் மற்றும் மெக்டொனால்டு தீவுகள்",
		"te-IN": "హెర్డ్ దీవి మరియు మెక్‌డొనాల్డ్ దీవులు",
		"mr-IN": "हर्ड आणि मॅक्डोनाल्ड बेटे",
		"gu-IN": "હર્ડ અને મેકડોનાલ્ડ આઇલેન્ડ્સ",
		"kn-IN": "ಹರ್ಡ್ ಮತ್ತು ಮ್ಯಾಕ್‌ಡೋನಾಲ್ಡ್ ದ್ವೀಪಗಳು",
		"ml-IN": "ഹേർഡ്, മക്ഡോണൾഡ് ദ്വീപുകൾ",
		"pa-IN": "ਹਰਡ ਤੇ ਮੈਕਡੋਨਾਲਡ ਟਾਪੂ",
		"ur-IN": "جزائر ہرڈ و مکڈونلڈ",
		"ur-PK": "ہیرڈ جزیرہ و میکڈولینڈ جزائر",
		"or-IN": "ହାର୍ଡ୍‌ ଏବଂ ମ୍ୟାକଡୋନାଲ୍ଡ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "হাৰ্ড দ্বীপ আৰু মেকডোনাল্ড দ্বীপপুঞ্জ",
		"ne-IN": "हर्ड टापु र म्याकडोनाल्ड टापुहरु",
		"ne-NP": "हर्ड टापु र म्याकडोनाल्ड टापुहरु",
		"si-LK": "හර්ඩ් දූපත සහ මැක්ඩොනල්ඩ් දූපත්",
		"kok-IN": "हर्ड ऍंड मॅक्डोनाल्ड आयलँड्स",
		"ks-IN": "ہَرٕڑ تہٕ مؠکڈونالڑٕ جٔزیٖرٕ",
		"brx-IN": "होर्द आरो मेकद’नाल्ड द्वीपफोर",
		"mai-IN": "हर्ड आ मैकडोनल्ड द्वीपसमूह",
		"dz-BT": "ཧཱརཌ་མཚོ་གླིང་ དང་ མེཀ་ཌོ་ནལཌ྄་གླིང་ཚོམ",
		"ja-JP": "ハード島・マクドナルド諸島",
		"ko-KR": "허드 맥도널드 제도",
		"ko-KP": "허드 맥도널드 제도",
		"zh-CN": "赫德岛和麦克唐纳群岛",
		"zh-Hans-CN": "赫德岛和麦克唐纳群岛",
		"zh-Hant-TW": "赫德島及麥唐納群島",
		"zh-TW": "赫德島及麥唐納群島",
		"zh-HK": "赫德島及麥唐納群島",
		"zh-MO": "赫德島及麥唐納群島",
		"zh-SG": "赫德岛和麦克唐纳群岛",
		"yue-Hant-HK": "赫德島同麥克唐納群島",
		"yue-Hans-CN": "赫德岛同麦克唐纳群岛",
		"mn-MN": "Херд ба Макдональдийн арлууд",
		"ug-CN": "ھېرد ئارىلى ۋە ماكدونالد ئاراللىرى",
		"th-TH": "เกาะเฮิร์ดและหมู่เกาะแมกดอนัลด์",
		"lo-LA": "ໝູ່ເກາະເຮີດ & ແມັກໂດນອລ",
		"km-KH": "កោះ​ហឺដនិង​ម៉ាក់ដូណាល់",
		"my-MM": "ဟတ်ကျွန်းနှင့်မက်ဒေါနယ်ကျွန်းစု",
		"vi-VN": "Quần đảo Heard và McDonald",
		"id-ID": "Pulau Heard dan Kepulauan McDonald",
		"ms-MY": "Kepulauan Heard & McDonald",
		"ms-SG": "Kepulauan Heard & McDonald",
		"ms-BN": "Kepulauan Heard & McDonald",
		"jv-ID": "Kapuloan Heard lan McDonald",
		"fil-PH": "Heard & McDonald Islands",
		"ceb-PH": "Heard & McDonald Islands",
		"ka-GE": "ჰერდი და მაკდონალდის კუნძულები",
		"hy-AM": "Հերդ կղզի և ՄակԴոնալդի կղզիներ",
		"az-AZ": "Herd və Makdonald adaları",
		"az-Cyrl-AZ": "Һерд вә Макдоналд адалары",
		"kk-KZ": "Херд аралы және Макдональд аралдары",
		"ky-KG": "Херд жана Макдональд аралдары",
		"uz-UZ": "Xerd va Makdonald orollari",
		"tg-TJ": "Ҷазираи Ҳерд ва Ҷазираҳои Макдоналд",
		"tk-TM": "Herd we Makdonald adalary",
		"fa-IR": "هرد و جزایر مک‌دونالد",
		"fa-AF": "هرد و جزایر مک‌دونالد",
		"ps-AF": "هارډ او ميکډانلډ ټاپوګان",
		"ps-PK": "هارډ او ميکډانلډ ټاپوګان",
		"he-IL": "איי הרד ומקדונלד",
		"ar-SA": "جزيرة هيرد وجزر ماكدونالد",
		"ar-AE": "جزيرة هيرد وجزر ماكدونالد",
		"ar-QA": "جزيرة هيرد وجزر ماكدونالد",
		"ar-BH": "جزيرة هيرد وجزر ماكدونالد",
		"ar-KW": "جزيرة هيرد وجزر ماكدونالد",
		"ar-OM": "جزيرة هيرد وجزر ماكدونالد",
		"ar-YE": "جزيرة هيرد وجزر ماكدونالد",
		"ar-IQ": "جزيرة هيرد وجزر ماكدونالد",
		"ar-JO": "جزيرة هيرد وجزر ماكدونالد",
		"ar-LB": "جزيرة هيرد وجزر ماكدونالد",
		"ar-SY": "جزيرة هيرد وجزر ماكدونالد",
		"ar-PS": "جزيرة هيرد وجزر ماكدونالد",
		"en-US": "Heard & McDonald Islands",
		"en-GB": "Heard & McDonald Islands",
		"en-IE": "Heard & McDonald Islands",
		"en-MT": "Heard & McDonald Islands",
		"en-GI": "Heard & McDonald Islands",
		"en-CY": "Heard & McDonald Islands",
		"en-JE": "Heard & McDonald Islands",
		"en-GG": "Heard & McDonald Islands",
		"en-IM": "Heard & McDonald Islands",
		"en-CA": "Heard and McDonald Islands",
		"en-AU": "Heard & McDonald Islands",
		"en-NZ": "Heard & McDonald Islands",
		"en-ZA": "Heard & McDonald Islands",
		"en-IN": "Heard & McDonald Islands",
		"en-SG": "Heard & McDonald Islands",
		"pt-AO": "Ilhas Heard e McDonald",
		"pt-MZ": "Ilhas Heard e McDonald",
		"pt-CV": "Ilhas Heard e McDonald",
		"pt-GW": "Ilhas Heard e McDonald",
		"pt-ST": "Ilhas Heard e McDonald",
		"pt-TL": "Ilhas Heard e McDonald",
		"pt-MO": "Ilhas Heard e McDonald",
		"es-ES": "Islas Heard y McDonald",
		"es-419": "Islas Heard y McDonald",
		"es-AD": "Islas Heard y McDonald",
		"es-GI": "Islas Heard y McDonald",
		"es-AR": "Islas Heard y McDonald",
		"es-BO": "Islas Heard y McDonald",
		"es-BR": "Islas Heard y McDonald",
		"es-BZ": "Islas Heard y McDonald",
		"es-CL": "Islas Heard y McDonald",
		"es-CO": "Islas Heard y McDonald",
		"es-CR": "Islas Heard y McDonald",
		"es-CU": "Islas Heard y McDonald",
		"es-DO": "Islas Heard y McDonald",
		"es-EC": "Islas Heard y McDonald",
		"es-GT": "Islas Heard y McDonald",
		"es-HN": "Islas Heard y McDonald",
		"es-MX": "Islas Heard y McDonald",
		"es-NI": "Islas Heard y McDonald",
		"es-PA": "Islas Heard y McDonald",
		"es-PE": "Islas Heard y McDonald",
		"es-PR": "Islas Heard y McDonald",
		"es-PY": "Islas Heard y McDonald",
		"es-SV": "Islas Heard y McDonald",
		"es-US": "Islas Heard y McDonald",
		"es-UY": "Islas Heard y McDonald",
		"es-VE": "Islas Heard y McDonald",
		"fr-FR": "Îles Heard-et-MacDonald",
		"fr-BE": "Îles Heard-et-MacDonald",
		"fr-CH": "Îles Heard-et-MacDonald",
		"fr-LU": "Îles Heard-et-MacDonald",
		"fr-MC": "Îles Heard-et-MacDonald",
		"fr-AD": "Îles Heard-et-MacDonald",
		"fr-CA": "îles Heard et McDonald",
		"it-IT": "Isole Heard e McDonald",
		"it-CH": "Isole Heard e McDonald",
		"it-SM": "Isole Heard e McDonald",
		"it-VA": "Isole Heard e McDonald",
		"de-DE": "Heard und McDonaldinseln",
		"de-AT": "Heard und McDonaldinseln",
		"de-CH": "Heard und McDonaldinseln",
		"de-BE": "Heard und McDonaldinseln",
		"de-LI": "Heard und McDonaldinseln",
		"de-LU": "Heard und McDonaldinseln",
		"nl-NL": "Heard en McDonaldeilanden",
		"nl-BE": "Heard en McDonaldeilanden",
		"sv-SE": "Heardön och McDonaldöarna",
		"sv-FI": "Heardön och McDonaldöarna",
		"da-DK": "Heard Island og McDonald Islands",
		"nb-NO": "Heard- og McDonaldøyene",
		"nn-NO": "Heardøya og McDonaldøyane",
		"fi-FI": "Heard ja McDonaldinsaaret",
		"is-IS": "Heard og McDonaldseyjar",
		"fo-FO": "Heard og McDonaldoyggjar",
		"et-EE": "Heardi ja McDonaldi saared",
		"lv-LV": "Hērda sala un Makdonalda salas",
		"lt-LT": "Herdo ir Makdonaldo Salos",
		"pl-PL": "Wyspy Heard i McDonalda",
		"cs-CZ": "Heardův ostrov a McDonaldovy ostrovy",
		"sk-SK": "Heardov ostrov a Macdonaldove ostrovy",
		"sl-SI": "Heardov otok in McDonaldovi otoki",
		"hr-HR": "Otoci Heard i McDonald",
		"bs-BA": "Ostrvo Heard i arhipelag McDonald",
		"sr-RS": "Острво Херд и Мекдоналдова острва",
		"sr-BA": "острво Херд и острва Макдоналд",
		"sr-ME": "Ostrvo Herd i Mekdonaldova ostrva",
		"mk-MK": "Остров Херд и Острови Мекдоналд",
		"bg-BG": "острови Хърд и Макдоналд",
		"be-BY": "Астравы Херд і Макдональд",
		"uk-UA": "Острови Герд і Макдоналд",
		"ru-RU": "о-ва Херд и Макдональд",
		"el-GR": "Νήσοι Χερντ και Μακντόναλντ",
		"el-CY": "Νήσοι Χερντ και Μακντόναλντ",
		"ro-RO": "Insula Heard și Insulele McDonald",
		"ro-MD": "Insula Heard și Insulele McDonald",
		"hu-HU": "Heard-sziget és McDonald-szigetek",
		"sq-AL": "Ishujt Hërd e Mekdonald",
		"sq-XK": "Ishujt Hërd e Mekdonald",
		"mt-MT": "il-Gżejjer Heard u l-Gżejjer McDonald",
		"ga-IE": "Oileán Heard agus Oileáin McDonald",
		"cy-GB": "Ynys Heard ac Ynysoedd McDonald",
		"gd-GB": "Eilean Heard is Eileanan MhicDhòmhnaill",
		"lb-LU": "Heard- a McDonald-Inselen",
		"ca-ES": "Illes Heard i McDonald",
		"ca-AD": "Illes Heard i McDonald",
		"ca-FR": "Illes Heard i McDonald",
		"ca-IT": "Illes Heard i McDonald",
		"eu-ES": "Heard eta McDonald uharteak",
		"eu-FR": "Heard eta McDonald uharteak",
		"gl-ES": "Illa Heard e Illas McDonald",
		"tr-TR": "Heard Adası ve McDonald Adaları",
		"tr-CY": "Heard Adası ve McDonald Adaları"
	}
} satisfies Country;
