import type { Country } from './types.js';

export const HMD = {
	"code": "HMD",
	"labels": {
		"pt-BR": "Ilhas Heard e McDonald",
		"pt-PT": "Ilhas Heard e McDonald",
		"es-ES": "Islas Heard y McDonald",
		"es-419": "Islas Heard y McDonald",
		"es-AR": "Islas Heard y McDonald",
		"es-BO": "Islas Heard y McDonald",
		"es-BR": "Islas Heard y McDonald",
		"es-BZ": "Islas Heard y McDonald",
		"es-CL": "Islas Heard y McDonald",
		"es-CO": "Islas Heard y McDonald",
		"es-CR": "Islas Heard y McDonald",
		"es-CU": "Islas Heard y McDonald",
		"es-DO": "Islas Heard y McDonald",
		"es-EC": "Islas Heard y McDonald",
		"es-GT": "Islas Heard y McDonald",
		"es-HN": "Islas Heard y McDonald",
		"es-MX": "Islas Heard y McDonald",
		"es-NI": "Islas Heard y McDonald",
		"es-PA": "Islas Heard y McDonald",
		"es-PE": "Islas Heard y McDonald",
		"es-PR": "Islas Heard y McDonald",
		"es-PY": "Islas Heard y McDonald",
		"es-SV": "Islas Heard y McDonald",
		"es-US": "Islas Heard y McDonald",
		"es-UY": "Islas Heard y McDonald",
		"es-VE": "Islas Heard y McDonald",
		"en-US": "Heard & McDonald Islands",
		"fr-FR": "Îles Heard-et-MacDonald",
		"fr-BE": "Îles Heard-et-MacDonald",
		"fr-CA": "îles Heard et McDonald",
		"fr-CH": "Îles Heard-et-MacDonald",
		"fr-LU": "Îles Heard-et-MacDonald",
		"fr-MC": "Îles Heard-et-MacDonald",
		"it-IT": "Isole Heard e McDonald",
		"it-CH": "Isole Heard e McDonald",
		"it-SM": "Isole Heard e McDonald",
		"it-VA": "Isole Heard e McDonald",
		"de-DE": "Heard und McDonaldinseln",
		"de-AT": "Heard und McDonaldinseln",
		"de-CH": "Heard und McDonaldinseln",
		"de-BE": "Heard und McDonaldinseln",
		"de-LI": "Heard und McDonaldinseln",
		"de-LU": "Heard und McDonaldinseln"
	}
} satisfies Country;
