import type { Country } from './types.js';

export const HND = {
	"code": "HND",
	"labels": {
		"pt-BR": "Honduras",
		"pt-PT": "Honduras",
		"es-ES": "Honduras",
		"es-419": "Honduras",
		"es-AR": "Honduras",
		"es-BO": "Honduras",
		"es-BR": "Honduras",
		"es-BZ": "Honduras",
		"es-CL": "Honduras",
		"es-CO": "Honduras",
		"es-CR": "Honduras",
		"es-CU": "Honduras",
		"es-DO": "Honduras",
		"es-EC": "Honduras",
		"es-GT": "Honduras",
		"es-HN": "Honduras",
		"es-MX": "Honduras",
		"es-NI": "Honduras",
		"es-PA": "Honduras",
		"es-PE": "Honduras",
		"es-PR": "Honduras",
		"es-PY": "Honduras",
		"es-SV": "Honduras",
		"es-US": "Honduras",
		"es-UY": "Honduras",
		"es-VE": "Honduras",
		"en-US": "Honduras",
		"fr-FR": "Honduras",
		"fr-BE": "Honduras",
		"fr-CA": "Honduras",
		"fr-CH": "Honduras",
		"fr-LU": "Honduras",
		"fr-MC": "Honduras",
		"it-IT": "Honduras",
		"it-CH": "Honduras",
		"it-SM": "Honduras",
		"it-VA": "Honduras",
		"de-DE": "Honduras",
		"de-AT": "Honduras",
		"de-CH": "Honduras",
		"de-BE": "Honduras",
		"de-LI": "Honduras",
		"de-LU": "Honduras"
	},
	"callingCode": "504"
} satisfies Country;
