import type { Country } from './types.js';

export const HRV = {
	"code": "HRV",
	"labels": {
		"pt-BR": "Croácia",
		"pt-PT": "Croácia",
		"es-ES": "Croacia",
		"es-419": "Croacia",
		"es-AR": "Croacia",
		"es-BO": "Croacia",
		"es-BR": "Croacia",
		"es-BZ": "Croacia",
		"es-CL": "Croacia",
		"es-CO": "Croacia",
		"es-CR": "Croacia",
		"es-CU": "Croacia",
		"es-DO": "Croacia",
		"es-EC": "Croacia",
		"es-GT": "Croacia",
		"es-HN": "Croacia",
		"es-MX": "Croacia",
		"es-NI": "Croacia",
		"es-PA": "Croacia",
		"es-PE": "Croacia",
		"es-PR": "Croacia",
		"es-PY": "Croacia",
		"es-SV": "Croacia",
		"es-US": "Croacia",
		"es-UY": "Croacia",
		"es-VE": "Croacia",
		"en-US": "Croatia",
		"fr-FR": "Croatie",
		"fr-BE": "Croatie",
		"fr-CA": "Croatie",
		"fr-CH": "Croatie",
		"fr-LU": "Croatie",
		"fr-MC": "Croatie",
		"it-IT": "Croazia",
		"it-CH": "Croazia",
		"it-SM": "Croazia",
		"it-VA": "Croazia",
		"de-DE": "Kroatien",
		"de-AT": "Kroatien",
		"de-CH": "Kroatien",
		"de-BE": "Kroatien",
		"de-LI": "Kroatien",
		"de-LU": "Kroatien"
	}
} satisfies Country;
