import type { Country } from './types.js';

export const HTI = {
	"code": "HTI",
	"labels": {
		"pt-BR": "Haiti",
		"pt-PT": "Haiti",
		"es-ES": "Haití",
		"es-419": "Haití",
		"es-AR": "Haití",
		"es-BO": "Haití",
		"es-BR": "Haití",
		"es-BZ": "Haití",
		"es-CL": "Haití",
		"es-CO": "Haití",
		"es-CR": "Haití",
		"es-CU": "Haití",
		"es-DO": "Haití",
		"es-EC": "Haití",
		"es-GT": "Haití",
		"es-HN": "Haití",
		"es-MX": "Haití",
		"es-NI": "Haití",
		"es-PA": "Haití",
		"es-PE": "Haití",
		"es-PR": "Haití",
		"es-PY": "Haití",
		"es-SV": "Haití",
		"es-US": "Haití",
		"es-UY": "Haití",
		"es-VE": "Haití",
		"en-US": "Haiti",
		"fr-FR": "Haïti",
		"fr-BE": "Haïti",
		"fr-CA": "Haïti",
		"fr-CH": "Haïti",
		"fr-LU": "Haïti",
		"fr-MC": "Haïti",
		"it-IT": "Haiti",
		"it-CH": "Haiti",
		"it-SM": "Haiti",
		"it-VA": "Haiti",
		"de-DE": "Haiti",
		"de-AT": "Haiti",
		"de-CH": "Haiti",
		"de-BE": "Haiti",
		"de-LI": "Haiti",
		"de-LU": "Haiti"
	},
	"callingCode": "509"
} satisfies Country;
