import type { Country } from './types.js';

export const IDN = {
	"code": "IDN",
	"labels": {
		"pt-BR": "Indonésia",
		"pt-PT": "Indonésia",
		"es-ES": "Indonesia",
		"es-419": "Indonesia",
		"es-AR": "Indonesia",
		"es-BO": "Indonesia",
		"es-BR": "Indonesia",
		"es-BZ": "Indonesia",
		"es-CL": "Indonesia",
		"es-CO": "Indonesia",
		"es-CR": "Indonesia",
		"es-CU": "Indonesia",
		"es-DO": "Indonesia",
		"es-EC": "Indonesia",
		"es-GT": "Indonesia",
		"es-HN": "Indonesia",
		"es-MX": "Indonesia",
		"es-NI": "Indonesia",
		"es-PA": "Indonesia",
		"es-PE": "Indonesia",
		"es-PR": "Indonesia",
		"es-PY": "Indonesia",
		"es-SV": "Indonesia",
		"es-US": "Indonesia",
		"es-UY": "Indonesia",
		"es-VE": "Indonesia",
		"en-US": "Indonesia",
		"fr-FR": "Indonésie",
		"fr-BE": "Indonésie",
		"fr-CA": "Indonésie",
		"fr-CH": "Indonésie",
		"fr-LU": "Indonésie",
		"fr-MC": "Indonésie",
		"it-IT": "Indonesia",
		"it-CH": "Indonesia",
		"it-SM": "Indonesia",
		"it-VA": "Indonesia",
		"de-DE": "Indonesien",
		"de-AT": "Indonesien",
		"de-CH": "Indonesien",
		"de-BE": "Indonesien",
		"de-LI": "Indonesien",
		"de-LU": "Indonesien"
	},
	"callingCode": "62"
} satisfies Country;
