import type { Country } from './types.js';

export const IDN = {
	"code": "IDN",
	"labels": {
		"pt-BR": "Indonésia",
		"pt-PT": "Indonésia",
		"qu-PE": "Indonesia",
		"qu-BO": "Indonesia",
		"qu-EC": "Indonesia",
		"chr-US": "ᎢᏂᏙᏂᏍᏯ",
		"hi-IN": "इंडोनेशिया",
		"bn-IN": "ইন্দোনেশিয়া",
		"bn-BD": "ইন্দোনেশিয়া",
		"ta-IN": "இந்தோனேசியா",
		"ta-LK": "இந்தோனேசியா",
		"ta-SG": "இந்தோனேசியா",
		"ta-MY": "இந்தோனேசியா",
		"te-IN": "ఇండోనేషియా",
		"mr-IN": "इंडोनेशिया",
		"gu-IN": "ઇન્ડોનેશિયા",
		"kn-IN": "ಇಂಡೋನೇಶಿಯಾ",
		"ml-IN": "ഇന്തോനേഷ്യ",
		"pa-IN": "ਇੰਡੋਨੇਸ਼ੀਆ",
		"ur-IN": "انڈونیشیا",
		"ur-PK": "انڈونیشیا",
		"or-IN": "ଇଣ୍ଡୋନେସିଆ",
		"as-IN": "ইণ্ডোনেচিয়া",
		"ne-IN": "इन्डोनेशिया",
		"ne-NP": "इन्डोनेशिया",
		"si-LK": "ඉන්දුනීසියාව",
		"kok-IN": "इंडोनेशीया",
		"ks-IN": "انڈونیشیا",
		"brx-IN": "इण्ड’नेशिया",
		"mai-IN": "इंडोनेशिया",
		"dz-BT": "ཨིན་ཌོ་ནེ་ཤི་ཡ",
		"ja-JP": "インドネシア",
		"ko-KR": "인도네시아",
		"ko-KP": "인도네시아",
		"zh-CN": "印度尼西亚",
		"zh-Hans-CN": "印度尼西亚",
		"zh-Hant-TW": "印尼",
		"zh-TW": "印尼",
		"zh-HK": "印尼",
		"zh-MO": "印尼",
		"zh-SG": "印度尼西亚",
		"yue-Hant-HK": "印尼",
		"yue-Hans-CN": "印尼",
		"mn-MN": "Индонез",
		"ug-CN": "ھىندونېزىيە",
		"th-TH": "อินโดนีเซีย",
		"lo-LA": "ອິນໂດເນເຊຍ",
		"km-KH": "ឥណ្ឌូណេស៊ី",
		"my-MM": "အင်ဒိုနီးရှား",
		"vi-VN": "Indonesia",
		"id-ID": "Indonesia",
		"ms-MY": "Indonesia",
		"ms-SG": "Indonesia",
		"ms-BN": "Indonesia",
		"jv-ID": "Indonésia",
		"su-ID": "Indonesia",
		"fil-PH": "Indonesia",
		"ceb-PH": "Indonesia",
		"ka-GE": "ინდონეზია",
		"hy-AM": "Ինդոնեզիա",
		"az-AZ": "İndoneziya",
		"az-Cyrl-AZ": "Индонезија",
		"kk-KZ": "Индонезия",
		"ky-KG": "Индонезия",
		"uz-UZ": "Indoneziya",
		"tg-TJ": "Индонезия",
		"tk-TM": "Indoneziýa",
		"fa-IR": "اندونزی",
		"fa-AF": "اندونیزیا",
		"ps-AF": "اندونیزیا",
		"ps-PK": "اندونیزیا",
		"he-IL": "אינדונזיה",
		"ar-SA": "إندونيسيا",
		"ar-AE": "إندونيسيا",
		"ar-QA": "إندونيسيا",
		"ar-BH": "إندونيسيا",
		"ar-KW": "إندونيسيا",
		"ar-OM": "إندونيسيا",
		"ar-YE": "إندونيسيا",
		"ar-IQ": "إندونيسيا",
		"ar-JO": "إندونيسيا",
		"ar-LB": "إندونيسيا",
		"ar-SY": "إندونيسيا",
		"ar-PS": "إندونيسيا",
		"en-US": "Indonesia",
		"en-GB": "Indonesia",
		"en-IE": "Indonesia",
		"en-MT": "Indonesia",
		"en-GI": "Indonesia",
		"en-CY": "Indonesia",
		"en-JE": "Indonesia",
		"en-GG": "Indonesia",
		"en-IM": "Indonesia",
		"en-CA": "Indonesia",
		"en-AU": "Indonesia",
		"en-NZ": "Indonesia",
		"en-ZA": "Indonesia",
		"en-IN": "Indonesia",
		"en-SG": "Indonesia",
		"pt-AO": "Indonésia",
		"pt-MZ": "Indonésia",
		"pt-CV": "Indonésia",
		"pt-GW": "Indonésia",
		"pt-ST": "Indonésia",
		"pt-TL": "Indonésia",
		"pt-MO": "Indonésia",
		"es-ES": "Indonesia",
		"es-419": "Indonesia",
		"es-AD": "Indonesia",
		"es-GI": "Indonesia",
		"es-AR": "Indonesia",
		"es-BO": "Indonesia",
		"es-BR": "Indonesia",
		"es-BZ": "Indonesia",
		"es-CL": "Indonesia",
		"es-CO": "Indonesia",
		"es-CR": "Indonesia",
		"es-CU": "Indonesia",
		"es-DO": "Indonesia",
		"es-EC": "Indonesia",
		"es-GT": "Indonesia",
		"es-HN": "Indonesia",
		"es-MX": "Indonesia",
		"es-NI": "Indonesia",
		"es-PA": "Indonesia",
		"es-PE": "Indonesia",
		"es-PR": "Indonesia",
		"es-PY": "Indonesia",
		"es-SV": "Indonesia",
		"es-US": "Indonesia",
		"es-UY": "Indonesia",
		"es-VE": "Indonesia",
		"fr-FR": "Indonésie",
		"fr-BE": "Indonésie",
		"fr-CH": "Indonésie",
		"fr-LU": "Indonésie",
		"fr-MC": "Indonésie",
		"fr-AD": "Indonésie",
		"fr-CA": "Indonésie",
		"it-IT": "Indonesia",
		"it-CH": "Indonesia",
		"it-SM": "Indonesia",
		"it-VA": "Indonesia",
		"de-DE": "Indonesien",
		"de-AT": "Indonesien",
		"de-CH": "Indonesien",
		"de-BE": "Indonesien",
		"de-LI": "Indonesien",
		"de-LU": "Indonesien",
		"nl-NL": "Indonesië",
		"nl-BE": "Indonesië",
		"sv-SE": "Indonesien",
		"sv-FI": "Indonesien",
		"da-DK": "Indonesien",
		"nb-NO": "Indonesia",
		"nn-NO": "Indonesia",
		"fi-FI": "Indonesia",
		"is-IS": "Indónesía",
		"fo-FO": "Indonesia",
		"et-EE": "Indoneesia",
		"lv-LV": "Indonēzija",
		"lt-LT": "Indonezija",
		"pl-PL": "Indonezja",
		"cs-CZ": "Indonésie",
		"sk-SK": "Indonézia",
		"sl-SI": "Indonezija",
		"hr-HR": "Indonezija",
		"bs-BA": "Indonezija",
		"sr-RS": "Индонезија",
		"sr-BA": "Индонезија",
		"sr-ME": "Indonezija",
		"mk-MK": "Индонезија",
		"bg-BG": "Индонезия",
		"be-BY": "Інданезія",
		"uk-UA": "Індонезія",
		"ru-RU": "Индонезия",
		"el-GR": "Ινδονησία",
		"el-CY": "Ινδονησία",
		"ro-RO": "Indonezia",
		"ro-MD": "Indonezia",
		"hu-HU": "Indonézia",
		"sq-AL": "Indonezi",
		"sq-XK": "Indonezi",
		"mt-MT": "l-Indoneżja",
		"ga-IE": "an Indinéis",
		"cy-GB": "Indonesia",
		"gd-GB": "Na h-Innd-innse",
		"lb-LU": "Indonesien",
		"ca-ES": "Indonèsia",
		"ca-AD": "Indonèsia",
		"ca-FR": "Indonèsia",
		"ca-IT": "Indonèsia",
		"eu-ES": "Indonesia",
		"eu-FR": "Indonesia",
		"gl-ES": "Indonesia",
		"tr-TR": "Endonezya",
		"tr-CY": "Endonezya"
	},
	"callingCode": "62",
	"phoneMasks": [
		{
			"mask": "# ### ###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"15"
			]
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		},
		{
			"mask": "### # ### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"80"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"804"
			]
		},
		{
			"mask": "### #######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"800"
			]
		},
		{
			"mask": "###-####-###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8[1-35-9]"
			]
		},
		{
			"mask": "## #########",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"2[124]|[36]1"
			]
		},
		{
			"mask": "### ########",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"[2-79]"
			]
		},
		{
			"mask": "### ########",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "###-####-#####",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "# ### ### ### ###",
			"minLength": 13,
			"maxLength": 13
		},
		{
			"mask": "## ### ### ### ###",
			"minLength": 14,
			"maxLength": 14
		},
		{
			"mask": "### ### ### ### ###",
			"minLength": 15,
			"maxLength": 15
		},
		{
			"mask": "# ### ### ### ### ###",
			"minLength": 16,
			"maxLength": 16
		},
		{
			"mask": "## ### ### ### ### ###",
			"minLength": 17,
			"maxLength": 17
		}
	]
} satisfies Country;
