import type { Country } from './types.js';

export const IMN = {
	"code": "IMN",
	"labels": {
		"pt-BR": "Ilha de Man",
		"pt-PT": "Ilha de Man",
		"qu-PE": "Isla de Man",
		"qu-BO": "Isla de Man",
		"qu-EC": "Isla de Man",
		"chr-US": "ᎤᏍᏗ ᎤᎦᏚᏛᎢ ᎾᎿ ᎠᏍᎦᏯ",
		"hi-IN": "आइल ऑफ़ मैन",
		"bn-IN": "আইল অফ ম্যান",
		"bn-BD": "আইল অফ ম্যান",
		"ta-IN": "ஐல் ஆஃப் மேன்",
		"ta-LK": "ஐல் ஆஃப் மேன்",
		"ta-SG": "ஐல் ஆஃப் மேன்",
		"ta-MY": "ஐல் ஆஃப் மேன்",
		"te-IN": "ఐల్ ఆఫ్ మాన్",
		"mr-IN": "आयल ऑफ मॅन",
		"gu-IN": "આઇલ ઑફ મેન",
		"kn-IN": "ಐಲ್ ಆಫ್ ಮ್ಯಾನ್",
		"ml-IN": "ഐൽ ഓഫ് മാൻ",
		"pa-IN": "ਆਇਲ ਆਫ ਮੈਨ",
		"ur-IN": "آئل آف مین",
		"ur-PK": "آئل آف مین",
		"or-IN": "ଆଇଲ୍‌ ଅଫ୍‌ ମ୍ୟାନ୍‌",
		"as-IN": "আইল অফ মেন",
		"ne-IN": "आइल अफ म्यान",
		"ne-NP": "आइल अफ म्यान",
		"si-LK": "අයිල් ඔෆ් මෑන්",
		"kok-IN": "इसले ऑफ मॅन",
		"ks-IN": "آیِل آف مین",
		"brx-IN": "आयोल अफ मेन",
		"mai-IN": "आइल ऑफ मैन",
		"dz-BT": "ཨ་ཡུལ་ ཨོཕ་ མཱན",
		"ja-JP": "マン島",
		"ko-KR": "맨섬",
		"ko-KP": "맨섬",
		"zh-CN": "马恩岛",
		"zh-Hans-CN": "马恩岛",
		"zh-Hant-TW": "曼島",
		"zh-TW": "曼島",
		"zh-HK": "馬恩島",
		"zh-MO": "馬恩島",
		"zh-SG": "马恩岛",
		"yue-Hant-HK": "曼島",
		"yue-Hans-CN": "曼岛",
		"mn-MN": "Мэн Арал",
		"ug-CN": "مان ئارىلى",
		"th-TH": "เกาะแมน",
		"lo-LA": "ເອວ ອອບ ແມນ",
		"km-KH": "អែលអុហ្វមែន",
		"my-MM": "မန်ကျွန်း",
		"vi-VN": "Đảo Man",
		"id-ID": "Pulau Man",
		"ms-MY": "Isle of Man",
		"ms-SG": "Isle of Man",
		"ms-BN": "Isle of Man",
		"jv-ID": "Pulo Man",
		"fil-PH": "Isle of Man",
		"ceb-PH": "Isle of Man",
		"ka-GE": "მენის კუნძული",
		"hy-AM": "Մեն կղզի",
		"az-AZ": "Men adası",
		"az-Cyrl-AZ": "Мен адасы",
		"kk-KZ": "Мэн аралы",
		"ky-KG": "Мэн аралы",
		"uz-UZ": "Men oroli",
		"tg-TJ": "Ҷазираи Мэн",
		"tk-TM": "Men adasy",
		"fa-IR": "جزیرهٔ من",
		"fa-AF": "جزیرهٔ من",
		"ps-AF": "د آئل آف مین",
		"ps-PK": "د آئل آف مین",
		"he-IL": "האי מאן",
		"ar-SA": "جزيرة مان",
		"ar-AE": "جزيرة مان",
		"ar-QA": "جزيرة مان",
		"ar-BH": "جزيرة مان",
		"ar-KW": "جزيرة مان",
		"ar-OM": "جزيرة مان",
		"ar-YE": "جزيرة مان",
		"ar-IQ": "جزيرة مان",
		"ar-JO": "جزيرة مان",
		"ar-LB": "جزيرة مان",
		"ar-SY": "جزيرة مان",
		"ar-PS": "جزيرة مان",
		"en-US": "Isle of Man",
		"en-GB": "Isle of Man",
		"en-IE": "Isle of Man",
		"en-MT": "Isle of Man",
		"en-GI": "Isle of Man",
		"en-CY": "Isle of Man",
		"en-JE": "Isle of Man",
		"en-GG": "Isle of Man",
		"en-IM": "Isle of Man",
		"en-CA": "Isle of Man",
		"en-AU": "Isle of Man",
		"en-NZ": "Isle of Man",
		"en-ZA": "Isle of Man",
		"en-IN": "Isle of Man",
		"en-SG": "Isle of Man",
		"pt-AO": "Ilha de Man",
		"pt-MZ": "Ilha de Man",
		"pt-CV": "Ilha de Man",
		"pt-GW": "Ilha de Man",
		"pt-ST": "Ilha de Man",
		"pt-TL": "Ilha de Man",
		"pt-MO": "Ilha de Man",
		"es-ES": "Isla de Man",
		"es-419": "Isla de Man",
		"es-AD": "Isla de Man",
		"es-GI": "Isla de Man",
		"es-AR": "Isla de Man",
		"es-BO": "Isla de Man",
		"es-BR": "Isla de Man",
		"es-BZ": "Isla de Man",
		"es-CL": "Isla de Man",
		"es-CO": "Isla de Man",
		"es-CR": "Isla de Man",
		"es-CU": "Isla de Man",
		"es-DO": "Isla de Man",
		"es-EC": "Isla de Man",
		"es-GT": "Isla de Man",
		"es-HN": "Isla de Man",
		"es-MX": "Isla de Man",
		"es-NI": "Isla de Man",
		"es-PA": "Isla de Man",
		"es-PE": "Isla de Man",
		"es-PR": "Isla de Man",
		"es-PY": "Isla de Man",
		"es-SV": "Isla de Man",
		"es-US": "Isla de Man",
		"es-UY": "Isla de Man",
		"es-VE": "Isla de Man",
		"fr-FR": "Île de Man",
		"fr-BE": "Île de Man",
		"fr-CH": "Île de Man",
		"fr-LU": "Île de Man",
		"fr-MC": "Île de Man",
		"fr-AD": "Île de Man",
		"fr-CA": "île de Man",
		"it-IT": "Isola di Man",
		"it-CH": "Isola di Man",
		"it-SM": "Isola di Man",
		"it-VA": "Isola di Man",
		"de-DE": "Isle of Man",
		"de-AT": "Isle of Man",
		"de-CH": "Isle of Man",
		"de-BE": "Isle of Man",
		"de-LI": "Isle of Man",
		"de-LU": "Isle of Man",
		"nl-NL": "Isle of Man",
		"nl-BE": "Isle of Man",
		"sv-SE": "Isle of Man",
		"sv-FI": "Isle of Man",
		"da-DK": "Isle of Man",
		"nb-NO": "Man",
		"nn-NO": "Man",
		"fi-FI": "Mansaari",
		"is-IS": "Mön",
		"fo-FO": "Isle of Man",
		"et-EE": "Mani saar",
		"lv-LV": "Menas sala",
		"lt-LT": "Meno Sala",
		"pl-PL": "Wyspa Man",
		"cs-CZ": "Ostrov Man",
		"sk-SK": "Ostrov Man",
		"sl-SI": "Otok Man",
		"hr-HR": "Otok Man",
		"bs-BA": "Ostrvo Man",
		"sr-RS": "Острво Ман",
		"sr-BA": "Острво Ман",
		"sr-ME": "Ostrvo Man",
		"mk-MK": "Остров Ман",
		"bg-BG": "остров Ман",
		"be-BY": "Востраў Мэн",
		"uk-UA": "Острів Мен",
		"ru-RU": "о-в Мэн",
		"el-GR": "Νήσος του Μαν",
		"el-CY": "Νήσος του Μαν",
		"ro-RO": "Insula Man",
		"ro-MD": "Insula Man",
		"hu-HU": "Man-sziget",
		"sq-AL": "Ishulli i Manit",
		"sq-XK": "Ishulli i Manit",
		"mt-MT": "Isle of Man",
		"ga-IE": "Oileán Mhanann",
		"cy-GB": "Ynys Manaw",
		"gd-GB": "Eilean Mhanainn",
		"lb-LU": "Isle of Man",
		"ca-ES": "Illa de Man",
		"ca-AD": "Illa de Man",
		"ca-FR": "Illa de Man",
		"ca-IT": "Illa de Man",
		"eu-ES": "Man uhartea",
		"eu-FR": "Man uhartea",
		"gl-ES": "Illa de Man",
		"tr-TR": "Man Adası",
		"tr-CY": "Man Adası"
	},
	"callingCode": "44",
	"phoneMasks": [
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		}
	]
} satisfies Country;
