import type { Country } from './types.js';

export const IND = {
	"code": "IND",
	"labels": {
		"pt-BR": "Índia",
		"pt-PT": "Índia",
		"es-ES": "India",
		"es-419": "India",
		"es-AR": "India",
		"es-BO": "India",
		"es-BR": "India",
		"es-BZ": "India",
		"es-CL": "India",
		"es-CO": "India",
		"es-CR": "India",
		"es-CU": "India",
		"es-DO": "India",
		"es-EC": "India",
		"es-GT": "India",
		"es-HN": "India",
		"es-MX": "India",
		"es-NI": "India",
		"es-PA": "India",
		"es-PE": "India",
		"es-PR": "India",
		"es-PY": "India",
		"es-SV": "India",
		"es-US": "India",
		"es-UY": "India",
		"es-VE": "India",
		"en-US": "India",
		"fr-FR": "Inde",
		"fr-BE": "Inde",
		"fr-CA": "Inde",
		"fr-CH": "Inde",
		"fr-LU": "Inde",
		"fr-MC": "Inde",
		"it-IT": "India",
		"it-CH": "India",
		"it-SM": "India",
		"it-VA": "India",
		"de-DE": "Indien",
		"de-AT": "Indien",
		"de-CH": "Indien",
		"de-BE": "Indien",
		"de-LI": "Indien",
		"de-LU": "Indien"
	}
} satisfies Country;
