import type { Country } from './types.js';

export const IOT = {
	"code": "IOT",
	"labels": {
		"pt-BR": "Território Britânico do Oceano Índico",
		"pt-PT": "Território Britânico do Oceano Índico",
		"es-ES": "Territorio Británico del Océano Índico",
		"es-419": "Territorio Británico del Océano Índico",
		"es-AR": "Territorio Británico del Océano Índico",
		"es-BO": "Territorio Británico del Océano Índico",
		"es-BR": "Territorio Británico del Océano Índico",
		"es-BZ": "Territorio Británico del Océano Índico",
		"es-CL": "Territorio Británico del Océano Índico",
		"es-CO": "Territorio Británico del Océano Índico",
		"es-CR": "Territorio Británico del Océano Índico",
		"es-CU": "Territorio Británico del Océano Índico",
		"es-DO": "Territorio Británico del Océano Índico",
		"es-EC": "Territorio Británico del Océano Índico",
		"es-GT": "Territorio Británico del Océano Índico",
		"es-HN": "Territorio Británico del Océano Índico",
		"es-MX": "Territorio Británico del Océano Índico",
		"es-NI": "Territorio Británico del Océano Índico",
		"es-PA": "Territorio Británico del Océano Índico",
		"es-PE": "Territorio Británico del Océano Índico",
		"es-PR": "Territorio Británico del Océano Índico",
		"es-PY": "Territorio Británico del Océano Índico",
		"es-SV": "Territorio Británico del Océano Índico",
		"es-US": "Territorio Británico del Océano Índico",
		"es-UY": "Territorio Británico del Océano Índico",
		"es-VE": "Territorio Británico del Océano Índico",
		"en-US": "British Indian Ocean Territory",
		"fr-FR": "Territoire britannique de l’océan Indien",
		"fr-BE": "Territoire britannique de l’océan Indien",
		"fr-CA": "Territoire britannique de l’océan Indien",
		"fr-CH": "Territoire britannique de l’océan Indien",
		"fr-LU": "Territoire britannique de l’océan Indien",
		"fr-MC": "Territoire britannique de l’océan Indien",
		"it-IT": "Territorio Britannico dell’Oceano Indiano",
		"it-CH": "Territorio Britannico dell’Oceano Indiano",
		"it-SM": "Territorio Britannico dell’Oceano Indiano",
		"it-VA": "Territorio Britannico dell’Oceano Indiano",
		"de-DE": "Britisches Territorium im Indischen Ozean",
		"de-AT": "Britisches Territorium im Indischen Ozean",
		"de-CH": "Britisches Territorium im Indischen Ozean",
		"de-BE": "Britisches Territorium im Indischen Ozean",
		"de-LI": "Britisches Territorium im Indischen Ozean",
		"de-LU": "Britisches Territorium im Indischen Ozean"
	}
} satisfies Country;
