import type { Country } from './types.js';

export const IRL = {
	"code": "IRL",
	"labels": {
		"pt-BR": "Irlanda",
		"pt-PT": "Irlanda",
		"qu-PE": "Irlanda",
		"qu-BO": "Irlanda",
		"qu-EC": "Irlanda",
		"chr-US": "ᎠᏲᎳᏂ",
		"hi-IN": "आयरलैंड",
		"bn-IN": "আয়ারল্যান্ড",
		"bn-BD": "আয়ারল্যান্ড",
		"ta-IN": "அயர்லாந்து",
		"ta-LK": "அயர்லாந்து",
		"ta-SG": "அயர்லாந்து",
		"ta-MY": "அயர்லாந்து",
		"te-IN": "ఐర్లాండ్",
		"mr-IN": "आयर्लंड",
		"gu-IN": "આયર્લેન્ડ",
		"kn-IN": "ಐರ್ಲೆಂಡ್",
		"ml-IN": "അയർലൻഡ്",
		"pa-IN": "ਆਇਰਲੈਂਡ",
		"ur-IN": "آئرلینڈ",
		"ur-PK": "آئرلینڈ",
		"or-IN": "ଆୟରଲ୍ୟାଣ୍ଡ",
		"as-IN": "আয়াৰলেণ্ড",
		"ne-IN": "आयरल्याण्ड",
		"ne-NP": "आयरल्याण्ड",
		"si-LK": "අයර්ලන්තය",
		"kok-IN": "आयरलँड",
		"ks-IN": "اَیَرلینڑ",
		"brx-IN": "आयारलेण्ड",
		"mai-IN": "आयरलैंड",
		"dz-BT": "ཨཱ་ཡ་ལེནཌ",
		"ja-JP": "アイルランド",
		"ko-KR": "아일랜드",
		"ko-KP": "아일랜드",
		"zh-CN": "爱尔兰",
		"zh-Hans-CN": "爱尔兰",
		"zh-Hant-TW": "愛爾蘭",
		"zh-TW": "愛爾蘭",
		"zh-HK": "愛爾蘭",
		"zh-MO": "愛爾蘭",
		"zh-SG": "爱尔兰",
		"yue-Hant-HK": "愛爾蘭",
		"yue-Hans-CN": "爱尔兰",
		"mn-MN": "Ирланд",
		"ug-CN": "ئىرېلاندىيە",
		"th-TH": "ไอร์แลนด์",
		"lo-LA": "ໄອແລນ",
		"km-KH": "អៀរឡង់",
		"my-MM": "အိုင်ယာလန်",
		"vi-VN": "Ireland",
		"id-ID": "Irlandia",
		"ms-MY": "Ireland",
		"ms-SG": "Ireland",
		"ms-BN": "Ireland",
		"jv-ID": "Républik Irlan",
		"fil-PH": "Ireland",
		"ceb-PH": "Ireland",
		"ka-GE": "ირლანდია",
		"hy-AM": "Իռլանդիա",
		"az-AZ": "İrlandiya",
		"az-Cyrl-AZ": "Ирландија",
		"kk-KZ": "Ирландия",
		"ky-KG": "Ирландия",
		"uz-UZ": "Irlandiya",
		"tg-TJ": "Ирландия",
		"tk-TM": "Irlandiýa",
		"fa-IR": "ایرلند",
		"fa-AF": "آیرلند",
		"ps-AF": "آيرلېنډ",
		"ps-PK": "آيرلېنډ",
		"he-IL": "אירלנד",
		"ar-SA": "أيرلندا",
		"ar-AE": "أيرلندا",
		"ar-QA": "أيرلندا",
		"ar-BH": "أيرلندا",
		"ar-KW": "أيرلندا",
		"ar-OM": "أيرلندا",
		"ar-YE": "أيرلندا",
		"ar-IQ": "أيرلندا",
		"ar-JO": "أيرلندا",
		"ar-LB": "أيرلندا",
		"ar-SY": "أيرلندا",
		"ar-PS": "أيرلندا",
		"en-US": "Ireland",
		"en-GB": "Ireland",
		"en-IE": "Ireland",
		"en-MT": "Ireland",
		"en-GI": "Ireland",
		"en-CY": "Ireland",
		"en-JE": "Ireland",
		"en-GG": "Ireland",
		"en-IM": "Ireland",
		"en-CA": "Ireland",
		"en-AU": "Ireland",
		"en-NZ": "Ireland",
		"en-ZA": "Ireland",
		"en-IN": "Ireland",
		"en-SG": "Ireland",
		"pt-AO": "Irlanda",
		"pt-MZ": "Irlanda",
		"pt-CV": "Irlanda",
		"pt-GW": "Irlanda",
		"pt-ST": "Irlanda",
		"pt-TL": "Irlanda",
		"pt-MO": "Irlanda",
		"es-ES": "Irlanda",
		"es-419": "Irlanda",
		"es-AD": "Irlanda",
		"es-GI": "Irlanda",
		"es-AR": "Irlanda",
		"es-BO": "Irlanda",
		"es-BR": "Irlanda",
		"es-BZ": "Irlanda",
		"es-CL": "Irlanda",
		"es-CO": "Irlanda",
		"es-CR": "Irlanda",
		"es-CU": "Irlanda",
		"es-DO": "Irlanda",
		"es-EC": "Irlanda",
		"es-GT": "Irlanda",
		"es-HN": "Irlanda",
		"es-MX": "Irlanda",
		"es-NI": "Irlanda",
		"es-PA": "Irlanda",
		"es-PE": "Irlanda",
		"es-PR": "Irlanda",
		"es-PY": "Irlanda",
		"es-SV": "Irlanda",
		"es-US": "Irlanda",
		"es-UY": "Irlanda",
		"es-VE": "Irlanda",
		"fr-FR": "Irlande",
		"fr-BE": "Irlande",
		"fr-CH": "Irlande",
		"fr-LU": "Irlande",
		"fr-MC": "Irlande",
		"fr-AD": "Irlande",
		"fr-CA": "Irlande",
		"it-IT": "Irlanda",
		"it-CH": "Irlanda",
		"it-SM": "Irlanda",
		"it-VA": "Irlanda",
		"de-DE": "Irland",
		"de-AT": "Irland",
		"de-CH": "Irland",
		"de-BE": "Irland",
		"de-LI": "Irland",
		"de-LU": "Irland",
		"nl-NL": "Ierland",
		"nl-BE": "Ierland",
		"sv-SE": "Irland",
		"sv-FI": "Irland",
		"da-DK": "Irland",
		"nb-NO": "Irland",
		"nn-NO": "Irland",
		"fi-FI": "Irlanti",
		"is-IS": "Írland",
		"fo-FO": "Írland",
		"et-EE": "Iirimaa",
		"lv-LV": "Īrija",
		"lt-LT": "Airija",
		"pl-PL": "Irlandia",
		"cs-CZ": "Irsko",
		"sk-SK": "Írsko",
		"sl-SI": "Irska",
		"hr-HR": "Irska",
		"bs-BA": "Irska",
		"sr-RS": "Ирска",
		"sr-BA": "Ирска",
		"sr-ME": "Irska",
		"mk-MK": "Ирска",
		"bg-BG": "Ирландия",
		"be-BY": "Ірландыя",
		"uk-UA": "Ірландія",
		"ru-RU": "Ирландия",
		"el-GR": "Ιρλανδία",
		"el-CY": "Ιρλανδία",
		"ro-RO": "Irlanda",
		"ro-MD": "Irlanda",
		"hu-HU": "Írország",
		"sq-AL": "Irlandë",
		"sq-XK": "Irlandë",
		"mt-MT": "l-Irlanda",
		"ga-IE": "Éire",
		"cy-GB": "Iwerddon",
		"gd-GB": "Èirinn",
		"lb-LU": "Irland",
		"ca-ES": "Irlanda",
		"ca-AD": "Irlanda",
		"ca-FR": "Irlanda",
		"ca-IT": "Irlanda",
		"eu-ES": "Irlanda",
		"eu-FR": "Irlanda",
		"gl-ES": "Irlanda",
		"tr-TR": "İrlanda",
		"tr-CY": "İrlanda"
	},
	"callingCode": "353",
	"phoneMasks": [
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"2[24-9]|47|58|6[237-9]|9[35-9]"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[45]0"
			]
		},
		{
			"mask": "# #### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[2569]|4[1-69]|7[14]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[78]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"70"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"81"
			]
		},
		{
			"mask": "## # ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "## #### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"4"
			]
		},
		{
			"mask": "#### ### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1"
			]
		}
	]
} satisfies Country;
