import type { Country } from './types.js';

export const ISL = {
	"code": "ISL",
	"labels": {
		"pt-BR": "Islândia",
		"pt-PT": "Islândia",
		"es-ES": "Islandia",
		"es-419": "Islandia",
		"es-AR": "Islandia",
		"es-BO": "Islandia",
		"es-BR": "Islandia",
		"es-BZ": "Islandia",
		"es-CL": "Islandia",
		"es-CO": "Islandia",
		"es-CR": "Islandia",
		"es-CU": "Islandia",
		"es-DO": "Islandia",
		"es-EC": "Islandia",
		"es-GT": "Islandia",
		"es-HN": "Islandia",
		"es-MX": "Islandia",
		"es-NI": "Islandia",
		"es-PA": "Islandia",
		"es-PE": "Islandia",
		"es-PR": "Islandia",
		"es-PY": "Islandia",
		"es-SV": "Islandia",
		"es-US": "Islandia",
		"es-UY": "Islandia",
		"es-VE": "Islandia",
		"en-US": "Iceland",
		"fr-FR": "Islande",
		"fr-BE": "Islande",
		"fr-CA": "Islande",
		"fr-CH": "Islande",
		"fr-LU": "Islande",
		"fr-MC": "Islande",
		"it-IT": "Islanda",
		"it-CH": "Islanda",
		"it-SM": "Islanda",
		"it-VA": "Islanda",
		"de-DE": "Island",
		"de-AT": "Island",
		"de-CH": "Island",
		"de-BE": "Island",
		"de-LI": "Island",
		"de-LU": "Island"
	}
} satisfies Country;
