import type { Country } from './types.js';

export const ISR = {
	"code": "ISR",
	"labels": {
		"pt-BR": "Israel",
		"pt-PT": "Israel",
		"qu-PE": "Israel",
		"qu-BO": "Israel",
		"qu-EC": "Israel",
		"chr-US": "ᎢᏏᎵᏱ",
		"hi-IN": "इज़राइल",
		"bn-IN": "ইজরায়েল",
		"bn-BD": "ইজরায়েল",
		"ta-IN": "இஸ்ரேல்",
		"ta-LK": "இஸ்ரேல்",
		"ta-SG": "இஸ்ரேல்",
		"ta-MY": "இஸ்ரேல்",
		"te-IN": "ఇజ్రాయెల్",
		"mr-IN": "इस्त्राइल",
		"gu-IN": "ઇઝરાઇલ",
		"kn-IN": "ಇಸ್ರೇಲ್",
		"ml-IN": "ഇസ്രായേൽ",
		"pa-IN": "ਇਜ਼ਰਾਈਲ",
		"ur-IN": "اسرائیل",
		"ur-PK": "اسرائیل",
		"or-IN": "ଇସ୍ରାଏଲ୍",
		"as-IN": "ইজৰাইল",
		"ne-IN": "इजरायल",
		"ne-NP": "इजरायल",
		"si-LK": "ඊශ්‍රායලය",
		"kok-IN": "इस्त्राइल",
		"ks-IN": "اسرا ییل",
		"brx-IN": "इज्राईल",
		"mai-IN": "इजरायल",
		"dz-BT": "ཨིས་ར་ཡེལ",
		"ja-JP": "イスラエル",
		"ko-KR": "이스라엘",
		"ko-KP": "이스라엘",
		"zh-CN": "以色列",
		"zh-Hans-CN": "以色列",
		"zh-Hant-TW": "以色列",
		"zh-TW": "以色列",
		"zh-HK": "以色列",
		"zh-MO": "以色列",
		"zh-SG": "以色列",
		"yue-Hant-HK": "以色列",
		"yue-Hans-CN": "以色列",
		"mn-MN": "Израил",
		"ug-CN": "ئىسرائىلىيە",
		"th-TH": "อิสราเอล",
		"lo-LA": "ອິສຣາເອວ",
		"km-KH": "អ៊ីស្រាអែល",
		"my-MM": "အစ္စရေး",
		"vi-VN": "Israel",
		"id-ID": "Israel",
		"ms-MY": "Israel",
		"ms-SG": "Israel",
		"ms-BN": "Israel",
		"jv-ID": "Israèl",
		"fil-PH": "Israel",
		"ceb-PH": "Israel",
		"ka-GE": "ისრაელი",
		"hy-AM": "Իսրայել",
		"az-AZ": "İsrail",
		"az-Cyrl-AZ": "Исраил",
		"kk-KZ": "Израиль",
		"ky-KG": "Израиль",
		"uz-UZ": "Isroil",
		"tg-TJ": "Исроил",
		"tk-TM": "Ysraýyl",
		"fa-IR": "اسرائیل",
		"fa-AF": "اسرائیل",
		"ps-AF": "اسراييل",
		"ps-PK": "اسراييل",
		"he-IL": "ישראל",
		"ar-SA": "إسرائيل",
		"ar-AE": "إسرائيل",
		"ar-QA": "إسرائيل",
		"ar-BH": "إسرائيل",
		"ar-KW": "إسرائيل",
		"ar-OM": "إسرائيل",
		"ar-YE": "إسرائيل",
		"ar-IQ": "إسرائيل",
		"ar-JO": "إسرائيل",
		"ar-LB": "إسرائيل",
		"ar-SY": "إسرائيل",
		"ar-PS": "إسرائيل",
		"en-US": "Israel",
		"en-GB": "Israel",
		"en-IE": "Israel",
		"en-MT": "Israel",
		"en-GI": "Israel",
		"en-CY": "Israel",
		"en-JE": "Israel",
		"en-GG": "Israel",
		"en-IM": "Israel",
		"en-CA": "Israel",
		"en-AU": "Israel",
		"en-NZ": "Israel",
		"en-ZA": "Israel",
		"en-IN": "Israel",
		"en-SG": "Israel",
		"pt-AO": "Israel",
		"pt-MZ": "Israel",
		"pt-CV": "Israel",
		"pt-GW": "Israel",
		"pt-ST": "Israel",
		"pt-TL": "Israel",
		"pt-MO": "Israel",
		"es-ES": "Israel",
		"es-419": "Israel",
		"es-AD": "Israel",
		"es-GI": "Israel",
		"es-AR": "Israel",
		"es-BO": "Israel",
		"es-BR": "Israel",
		"es-BZ": "Israel",
		"es-CL": "Israel",
		"es-CO": "Israel",
		"es-CR": "Israel",
		"es-CU": "Israel",
		"es-DO": "Israel",
		"es-EC": "Israel",
		"es-GT": "Israel",
		"es-HN": "Israel",
		"es-MX": "Israel",
		"es-NI": "Israel",
		"es-PA": "Israel",
		"es-PE": "Israel",
		"es-PR": "Israel",
		"es-PY": "Israel",
		"es-SV": "Israel",
		"es-US": "Israel",
		"es-UY": "Israel",
		"es-VE": "Israel",
		"fr-FR": "Israël",
		"fr-BE": "Israël",
		"fr-CH": "Israël",
		"fr-LU": "Israël",
		"fr-MC": "Israël",
		"fr-AD": "Israël",
		"fr-CA": "Israël",
		"it-IT": "Israele",
		"it-CH": "Israele",
		"it-SM": "Israele",
		"it-VA": "Israele",
		"de-DE": "Israel",
		"de-AT": "Israel",
		"de-CH": "Israel",
		"de-BE": "Israel",
		"de-LI": "Israel",
		"de-LU": "Israel",
		"nl-NL": "Israël",
		"nl-BE": "Israël",
		"sv-SE": "Israel",
		"sv-FI": "Israel",
		"da-DK": "Israel",
		"nb-NO": "Israel",
		"nn-NO": "Israel",
		"fi-FI": "Israel",
		"is-IS": "Ísrael",
		"fo-FO": "Ísrael",
		"et-EE": "Iisrael",
		"lv-LV": "Izraēla",
		"lt-LT": "Izraelis",
		"pl-PL": "Izrael",
		"cs-CZ": "Izrael",
		"sk-SK": "Izrael",
		"sl-SI": "Izrael",
		"hr-HR": "Izrael",
		"bs-BA": "Izrael",
		"sr-RS": "Израел",
		"sr-BA": "Израел",
		"sr-ME": "Izrael",
		"mk-MK": "Израел",
		"bg-BG": "Израел",
		"be-BY": "Ізраіль",
		"uk-UA": "Ізраїль",
		"ru-RU": "Израиль",
		"el-GR": "Ισραήλ",
		"el-CY": "Ισραήλ",
		"ro-RO": "Israel",
		"ro-MD": "Israel",
		"hu-HU": "Izrael",
		"sq-AL": "Izrael",
		"sq-XK": "Izrael",
		"mt-MT": "Iżrael",
		"ga-IE": "Iosrael",
		"cy-GB": "Israel",
		"gd-GB": "Iosrael",
		"lb-LU": "Israel",
		"ca-ES": "Israel",
		"ca-AD": "Israel",
		"ca-FR": "Israel",
		"ca-IT": "Israel",
		"eu-ES": "Israel",
		"eu-FR": "Israel",
		"gl-ES": "Israel",
		"tr-TR": "İsrail",
		"tr-CY": "İsrail"
	},
	"callingCode": "972",
	"phoneMasks": [
		{
			"mask": "####-###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"125"
			]
		},
		{
			"mask": "#-###-####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[2-489]"
			]
		},
		{
			"mask": "####-##-##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"121"
			]
		},
		{
			"mask": "##-###-####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[57]"
			]
		},
		{
			"mask": "#-###-###-###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1[7-9]"
			]
		},
		{
			"mask": "####-###-###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"12"
			]
		},
		{
			"mask": "####-######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"159"
			]
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11
		},
		{
			"mask": "###-## ###-####",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"15"
			]
		}
	]
} satisfies Country;
