import type { Country } from './types.js';

export const ITA = {
	"code": "ITA",
	"labels": {
		"pt-BR": "Itália",
		"pt-PT": "Itália",
		"es-ES": "Italia",
		"es-419": "Italia",
		"es-AR": "Italia",
		"es-BO": "Italia",
		"es-BR": "Italia",
		"es-BZ": "Italia",
		"es-CL": "Italia",
		"es-CO": "Italia",
		"es-CR": "Italia",
		"es-CU": "Italia",
		"es-DO": "Italia",
		"es-EC": "Italia",
		"es-GT": "Italia",
		"es-HN": "Italia",
		"es-MX": "Italia",
		"es-NI": "Italia",
		"es-PA": "Italia",
		"es-PE": "Italia",
		"es-PR": "Italia",
		"es-PY": "Italia",
		"es-SV": "Italia",
		"es-US": "Italia",
		"es-UY": "Italia",
		"es-VE": "Italia",
		"en-US": "Italy",
		"fr-FR": "Italie",
		"fr-BE": "Italie",
		"fr-CA": "Italie",
		"fr-CH": "Italie",
		"fr-LU": "Italie",
		"fr-MC": "Italie",
		"it-IT": "Italia",
		"it-CH": "Italia",
		"it-SM": "Italia",
		"it-VA": "Italia",
		"de-DE": "Italien",
		"de-AT": "Italien",
		"de-CH": "Italien",
		"de-BE": "Italien",
		"de-LI": "Italien",
		"de-LU": "Italien"
	},
	"callingCode": "39"
} satisfies Country;
