import type { Country } from './types.js';

export const JAM = {
	"code": "JAM",
	"labels": {
		"pt-BR": "Jamaica",
		"pt-PT": "Jamaica",
		"es-ES": "Jamaica",
		"es-419": "Jamaica",
		"es-AR": "Jamaica",
		"es-BO": "Jamaica",
		"es-BR": "Jamaica",
		"es-BZ": "Jamaica",
		"es-CL": "Jamaica",
		"es-CO": "Jamaica",
		"es-CR": "Jamaica",
		"es-CU": "Jamaica",
		"es-DO": "Jamaica",
		"es-EC": "Jamaica",
		"es-GT": "Jamaica",
		"es-HN": "Jamaica",
		"es-MX": "Jamaica",
		"es-NI": "Jamaica",
		"es-PA": "Jamaica",
		"es-PE": "Jamaica",
		"es-PR": "Jamaica",
		"es-PY": "Jamaica",
		"es-SV": "Jamaica",
		"es-US": "Jamaica",
		"es-UY": "Jamaica",
		"es-VE": "Jamaica",
		"en-US": "Jamaica",
		"fr-FR": "Jamaïque",
		"fr-BE": "Jamaïque",
		"fr-CA": "Jamaïque",
		"fr-CH": "Jamaïque",
		"fr-LU": "Jamaïque",
		"fr-MC": "Jamaïque",
		"it-IT": "Giamaica",
		"it-CH": "Giamaica",
		"it-SM": "Giamaica",
		"it-VA": "Giamaica",
		"de-DE": "Jamaika",
		"de-AT": "Jamaika",
		"de-CH": "Jamaika",
		"de-BE": "Jamaika",
		"de-LI": "Jamaika",
		"de-LU": "Jamaika"
	}
} satisfies Country;
