import type { Country } from './types.js';

export const JEY = {
	"code": "JEY",
	"labels": {
		"pt-BR": "Jersey",
		"pt-PT": "Jersey",
		"es-ES": "Jersey",
		"es-419": "Jersey",
		"es-AR": "Jersey",
		"es-BO": "Jersey",
		"es-BR": "Jersey",
		"es-BZ": "Jersey",
		"es-CL": "Jersey",
		"es-CO": "Jersey",
		"es-CR": "Jersey",
		"es-CU": "Jersey",
		"es-DO": "Jersey",
		"es-EC": "Jersey",
		"es-GT": "Jersey",
		"es-HN": "Jersey",
		"es-MX": "Jersey",
		"es-NI": "Jersey",
		"es-PA": "Jersey",
		"es-PE": "Jersey",
		"es-PR": "Jersey",
		"es-PY": "Jersey",
		"es-SV": "Jersey",
		"es-US": "Jersey",
		"es-UY": "Jersey",
		"es-VE": "Jersey",
		"en-US": "Jersey",
		"fr-FR": "Jersey",
		"fr-BE": "Jersey",
		"fr-CA": "Jersey",
		"fr-CH": "Jersey",
		"fr-LU": "Jersey",
		"fr-MC": "Jersey",
		"it-IT": "Jersey",
		"it-CH": "Jersey",
		"it-SM": "Jersey",
		"it-VA": "Jersey",
		"de-DE": "Jersey",
		"de-AT": "Jersey",
		"de-CH": "Jersey",
		"de-BE": "Jersey",
		"de-LI": "Jersey",
		"de-LU": "Jersey"
	},
	"callingCode": "44"
} satisfies Country;
