import type { Country } from './types.js';

export const JOR = {
	"code": "JOR",
	"labels": {
		"pt-BR": "Jordânia",
		"pt-PT": "Jordânia",
		"es-ES": "Jordania",
		"es-419": "Jordania",
		"es-AR": "Jordania",
		"es-BO": "Jordania",
		"es-BR": "Jordania",
		"es-BZ": "Jordania",
		"es-CL": "Jordania",
		"es-CO": "Jordania",
		"es-CR": "Jordania",
		"es-CU": "Jordania",
		"es-DO": "Jordania",
		"es-EC": "Jordania",
		"es-GT": "Jordania",
		"es-HN": "Jordania",
		"es-MX": "Jordania",
		"es-NI": "Jordania",
		"es-PA": "Jordania",
		"es-PE": "Jordania",
		"es-PR": "Jordania",
		"es-PY": "Jordania",
		"es-SV": "Jordania",
		"es-US": "Jordania",
		"es-UY": "Jordania",
		"es-VE": "Jordania",
		"en-US": "Jordan",
		"fr-FR": "Jordanie",
		"fr-BE": "Jordanie",
		"fr-CA": "Jordanie",
		"fr-CH": "Jordanie",
		"fr-LU": "Jordanie",
		"fr-MC": "Jordanie",
		"it-IT": "Giordania",
		"it-CH": "Giordania",
		"it-SM": "Giordania",
		"it-VA": "Giordania",
		"de-DE": "Jordanien",
		"de-AT": "Jordanien",
		"de-CH": "Jordanien",
		"de-BE": "Jordanien",
		"de-LI": "Jordanien",
		"de-LU": "Jordanien"
	}
} satisfies Country;
