import type { Country } from './types.js';

export const JOR = {
	"code": "JOR",
	"labels": {
		"pt-BR": "Jordânia",
		"pt-PT": "Jordânia",
		"qu-PE": "Jordania",
		"qu-BO": "Jordania",
		"qu-EC": "Jordania",
		"chr-US": "ᏦᏓᏂ",
		"hi-IN": "जॉर्डन",
		"bn-IN": "জর্ডন",
		"bn-BD": "জর্ডন",
		"ta-IN": "ஜோர்டான்",
		"ta-LK": "ஜோர்டான்",
		"ta-SG": "ஜோர்டான்",
		"ta-MY": "ஜோர்டான்",
		"te-IN": "జోర్డాన్",
		"mr-IN": "जॉर्डन",
		"gu-IN": "જોર્ડન",
		"kn-IN": "ಜೋರ್ಡಾನ್",
		"ml-IN": "ജോർദ്ദാൻ",
		"pa-IN": "ਜਾਰਡਨ",
		"ur-IN": "اردن",
		"ur-PK": "اردن",
		"or-IN": "ଜୋର୍ଡାନ୍",
		"as-IN": "জৰ্ডান",
		"ne-IN": "जोर्डन",
		"ne-NP": "जोर्डन",
		"si-LK": "ජෝර්දානය",
		"kok-IN": "जॉर्डन",
		"ks-IN": "جورڈن",
		"brx-IN": "जर्डान",
		"mai-IN": "जार्डन",
		"dz-BT": "ཇོར་ཌན",
		"ja-JP": "ヨルダン",
		"ko-KR": "요르단",
		"ko-KP": "요르단",
		"zh-CN": "约旦",
		"zh-Hans-CN": "约旦",
		"zh-Hant-TW": "約旦",
		"zh-TW": "約旦",
		"zh-HK": "約旦",
		"zh-MO": "約旦",
		"zh-SG": "约旦",
		"yue-Hant-HK": "約旦",
		"yue-Hans-CN": "约旦",
		"mn-MN": "Йордан",
		"ug-CN": "ئىيوردانىيە",
		"th-TH": "จอร์แดน",
		"lo-LA": "ຈໍແດນ",
		"km-KH": "ហ៊្សកដានី",
		"my-MM": "ဂျော်ဒန်",
		"vi-VN": "Jordan",
		"id-ID": "Yordania",
		"ms-MY": "Jordan",
		"ms-SG": "Jordan",
		"ms-BN": "Jordan",
		"jv-ID": "Yordania",
		"fil-PH": "Jordan",
		"ceb-PH": "Jordan",
		"ka-GE": "იორდანია",
		"hy-AM": "Հորդանան",
		"az-AZ": "İordaniya",
		"az-Cyrl-AZ": "Иорданија",
		"kk-KZ": "Иордания",
		"ky-KG": "Иордания",
		"uz-UZ": "Iordaniya",
		"tg-TJ": "Урдун",
		"tk-TM": "Iordaniýa",
		"fa-IR": "اردن",
		"fa-AF": "اردن",
		"ps-AF": "اردن",
		"ps-PK": "اردن",
		"he-IL": "ירדן",
		"ar-SA": "الأردن",
		"ar-AE": "الأردن",
		"ar-QA": "الأردن",
		"ar-BH": "الأردن",
		"ar-KW": "الأردن",
		"ar-OM": "الأردن",
		"ar-YE": "الأردن",
		"ar-IQ": "الأردن",
		"ar-JO": "الأردن",
		"ar-LB": "الأردن",
		"ar-SY": "الأردن",
		"ar-PS": "الأردن",
		"en-US": "Jordan",
		"en-GB": "Jordan",
		"en-IE": "Jordan",
		"en-MT": "Jordan",
		"en-GI": "Jordan",
		"en-CY": "Jordan",
		"en-JE": "Jordan",
		"en-GG": "Jordan",
		"en-IM": "Jordan",
		"en-CA": "Jordan",
		"en-AU": "Jordan",
		"en-NZ": "Jordan",
		"en-ZA": "Jordan",
		"en-IN": "Jordan",
		"en-SG": "Jordan",
		"pt-AO": "Jordânia",
		"pt-MZ": "Jordânia",
		"pt-CV": "Jordânia",
		"pt-GW": "Jordânia",
		"pt-ST": "Jordânia",
		"pt-TL": "Jordânia",
		"pt-MO": "Jordânia",
		"es-ES": "Jordania",
		"es-419": "Jordania",
		"es-AD": "Jordania",
		"es-GI": "Jordania",
		"es-AR": "Jordania",
		"es-BO": "Jordania",
		"es-BR": "Jordania",
		"es-BZ": "Jordania",
		"es-CL": "Jordania",
		"es-CO": "Jordania",
		"es-CR": "Jordania",
		"es-CU": "Jordania",
		"es-DO": "Jordania",
		"es-EC": "Jordania",
		"es-GT": "Jordania",
		"es-HN": "Jordania",
		"es-MX": "Jordania",
		"es-NI": "Jordania",
		"es-PA": "Jordania",
		"es-PE": "Jordania",
		"es-PR": "Jordania",
		"es-PY": "Jordania",
		"es-SV": "Jordania",
		"es-US": "Jordania",
		"es-UY": "Jordania",
		"es-VE": "Jordania",
		"fr-FR": "Jordanie",
		"fr-BE": "Jordanie",
		"fr-CH": "Jordanie",
		"fr-LU": "Jordanie",
		"fr-MC": "Jordanie",
		"fr-AD": "Jordanie",
		"fr-CA": "Jordanie",
		"it-IT": "Giordania",
		"it-CH": "Giordania",
		"it-SM": "Giordania",
		"it-VA": "Giordania",
		"de-DE": "Jordanien",
		"de-AT": "Jordanien",
		"de-CH": "Jordanien",
		"de-BE": "Jordanien",
		"de-LI": "Jordanien",
		"de-LU": "Jordanien",
		"nl-NL": "Jordanië",
		"nl-BE": "Jordanië",
		"sv-SE": "Jordanien",
		"sv-FI": "Jordanien",
		"da-DK": "Jordan",
		"nb-NO": "Jordan",
		"nn-NO": "Jordan",
		"fi-FI": "Jordania",
		"is-IS": "Jórdanía",
		"fo-FO": "Jordan",
		"et-EE": "Jordaania",
		"lv-LV": "Jordānija",
		"lt-LT": "Jordanija",
		"pl-PL": "Jordania",
		"cs-CZ": "Jordánsko",
		"sk-SK": "Jordánsko",
		"sl-SI": "Jordanija",
		"hr-HR": "Jordan",
		"bs-BA": "Jordan",
		"sr-RS": "Јордан",
		"sr-BA": "Јордан",
		"sr-ME": "Jordan",
		"mk-MK": "Јордан",
		"bg-BG": "Йордания",
		"be-BY": "Іарданія",
		"uk-UA": "Йорданія",
		"ru-RU": "Иордания",
		"el-GR": "Ιορδανία",
		"el-CY": "Ιορδανία",
		"ro-RO": "Iordania",
		"ro-MD": "Iordania",
		"hu-HU": "Jordánia",
		"sq-AL": "Jordani",
		"sq-XK": "Jordani",
		"mt-MT": "il-Ġordan",
		"ga-IE": "an Iordáin",
		"cy-GB": "Gwlad Iorddonen",
		"gd-GB": "Iòrdan",
		"lb-LU": "Jordanien",
		"ca-ES": "Jordània",
		"ca-AD": "Jordània",
		"ca-FR": "Jordània",
		"ca-IT": "Jordània",
		"eu-ES": "Jordania",
		"eu-FR": "Jordania",
		"gl-ES": "Xordania",
		"tr-TR": "Ürdün",
		"tr-CY": "Ürdün"
	},
	"callingCode": "962",
	"phoneMasks": [
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[2356]|87"
			]
		},
		{
			"mask": "# #### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"7"
			]
		},
		{
			"mask": "## #######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"70"
			]
		},
		{
			"mask": "### ######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
