import type { Country } from './types.js';

export const JPN = {
	"code": "JPN",
	"labels": {
		"pt-BR": "Japão",
		"pt-PT": "Japão",
		"es-ES": "Japón",
		"es-419": "Japón",
		"es-AR": "Japón",
		"es-BO": "Japón",
		"es-BR": "Japón",
		"es-BZ": "Japón",
		"es-CL": "Japón",
		"es-CO": "Japón",
		"es-CR": "Japón",
		"es-CU": "Japón",
		"es-DO": "Japón",
		"es-EC": "Japón",
		"es-GT": "Japón",
		"es-HN": "Japón",
		"es-MX": "Japón",
		"es-NI": "Japón",
		"es-PA": "Japón",
		"es-PE": "Japón",
		"es-PR": "Japón",
		"es-PY": "Japón",
		"es-SV": "Japón",
		"es-US": "Japón",
		"es-UY": "Japón",
		"es-VE": "Japón",
		"en-US": "Japan",
		"fr-FR": "Japon",
		"fr-BE": "Japon",
		"fr-CA": "Japon",
		"fr-CH": "Japon",
		"fr-LU": "Japon",
		"fr-MC": "Japon",
		"it-IT": "Giappone",
		"it-CH": "Giappone",
		"it-SM": "Giappone",
		"it-VA": "Giappone",
		"de-DE": "Japan",
		"de-AT": "Japan",
		"de-CH": "Japan",
		"de-BE": "Japan",
		"de-LI": "Japan",
		"de-LU": "Japan"
	},
	"callingCode": "81"
} satisfies Country;
