import type { Country } from './types.js';

export const KAZ = {
	"code": "KAZ",
	"labels": {
		"pt-BR": "Cazaquistão",
		"pt-PT": "Cazaquistão",
		"es-ES": "Kazajistán",
		"es-419": "Kazajistán",
		"es-AR": "Kazajistán",
		"es-BO": "Kazajistán",
		"es-BR": "Kazajistán",
		"es-BZ": "Kazajistán",
		"es-CL": "Kazajistán",
		"es-CO": "Kazajistán",
		"es-CR": "Kazajistán",
		"es-CU": "Kazajistán",
		"es-DO": "Kazajistán",
		"es-EC": "Kazajistán",
		"es-GT": "Kazajistán",
		"es-HN": "Kazajistán",
		"es-MX": "Kazajistán",
		"es-NI": "Kazajistán",
		"es-PA": "Kazajistán",
		"es-PE": "Kazajistán",
		"es-PR": "Kazajistán",
		"es-PY": "Kazajistán",
		"es-SV": "Kazajistán",
		"es-US": "Kazajistán",
		"es-UY": "Kazajistán",
		"es-VE": "Kazajistán",
		"en-US": "Kazakhstan",
		"fr-FR": "Kazakhstan",
		"fr-BE": "Kazakhstan",
		"fr-CA": "Kazakhstan",
		"fr-CH": "Kazakhstan",
		"fr-LU": "Kazakhstan",
		"fr-MC": "Kazakhstan",
		"it-IT": "Kazakistan",
		"it-CH": "Kazakistan",
		"it-SM": "Kazakistan",
		"it-VA": "Kazakistan",
		"de-DE": "Kasachstan",
		"de-AT": "Kasachstan",
		"de-CH": "Kasachstan",
		"de-BE": "Kasachstan",
		"de-LI": "Kasachstan",
		"de-LU": "Kasachstan"
	},
	"callingCode": "7"
} satisfies Country;
