import type { Country } from './types.js';

export const KGZ = {
	"code": "KGZ",
	"labels": {
		"pt-BR": "Quirguistão",
		"pt-PT": "Quirguistão",
		"es-ES": "Kirguistán",
		"es-419": "Kirguistán",
		"es-AR": "Kirguistán",
		"es-BO": "Kirguistán",
		"es-BR": "Kirguistán",
		"es-BZ": "Kirguistán",
		"es-CL": "Kirguistán",
		"es-CO": "Kirguistán",
		"es-CR": "Kirguistán",
		"es-CU": "Kirguistán",
		"es-DO": "Kirguistán",
		"es-EC": "Kirguistán",
		"es-GT": "Kirguistán",
		"es-HN": "Kirguistán",
		"es-MX": "Kirguistán",
		"es-NI": "Kirguistán",
		"es-PA": "Kirguistán",
		"es-PE": "Kirguistán",
		"es-PR": "Kirguistán",
		"es-PY": "Kirguistán",
		"es-SV": "Kirguistán",
		"es-US": "Kirguistán",
		"es-UY": "Kirguistán",
		"es-VE": "Kirguistán",
		"en-US": "Kyrgyzstan",
		"fr-FR": "Kirghizstan",
		"fr-BE": "Kirghizstan",
		"fr-CA": "Kirghizistan",
		"fr-CH": "Kirghizstan",
		"fr-LU": "Kirghizstan",
		"fr-MC": "Kirghizstan",
		"it-IT": "Kirghizistan",
		"it-CH": "Kirghizistan",
		"it-SM": "Kirghizistan",
		"it-VA": "Kirghizistan",
		"de-DE": "Kirgisistan",
		"de-AT": "Kirgisistan",
		"de-CH": "Kirgisistan",
		"de-BE": "Kirgisistan",
		"de-LI": "Kirgisistan",
		"de-LU": "Kirgisistan"
	},
	"callingCode": "996"
} satisfies Country;
