import type { Country } from './types.js';

export const KIR = {
	"code": "KIR",
	"labels": {
		"pt-BR": "Quiribati",
		"pt-PT": "Quiribáti",
		"es-ES": "Kiribati",
		"es-419": "Kiribati",
		"es-AR": "Kiribati",
		"es-BO": "Kiribati",
		"es-BR": "Kiribati",
		"es-BZ": "Kiribati",
		"es-CL": "Kiribati",
		"es-CO": "Kiribati",
		"es-CR": "Kiribati",
		"es-CU": "Kiribati",
		"es-DO": "Kiribati",
		"es-EC": "Kiribati",
		"es-GT": "Kiribati",
		"es-HN": "Kiribati",
		"es-MX": "Kiribati",
		"es-NI": "Kiribati",
		"es-PA": "Kiribati",
		"es-PE": "Kiribati",
		"es-PR": "Kiribati",
		"es-PY": "Kiribati",
		"es-SV": "Kiribati",
		"es-US": "Kiribati",
		"es-UY": "Kiribati",
		"es-VE": "Kiribati",
		"en-US": "Kiribati",
		"fr-FR": "Kiribati",
		"fr-BE": "Kiribati",
		"fr-CA": "Kiribati",
		"fr-CH": "Kiribati",
		"fr-LU": "Kiribati",
		"fr-MC": "Kiribati",
		"it-IT": "Kiribati",
		"it-CH": "Kiribati",
		"it-SM": "Kiribati",
		"it-VA": "Kiribati",
		"de-DE": "Kiribati",
		"de-AT": "Kiribati",
		"de-CH": "Kiribati",
		"de-BE": "Kiribati",
		"de-LI": "Kiribati",
		"de-LU": "Kiribati"
	}
} satisfies Country;
