import type { Country } from './types.js';

export const KNA = {
	"code": "KNA",
	"labels": {
		"pt-BR": "São Cristóvão e Névis",
		"pt-PT": "São Cristóvão e Neves",
		"es-ES": "San Cristóbal y Nieves",
		"es-419": "San Cristóbal y Nieves",
		"es-AR": "San Cristóbal y Nieves",
		"es-BO": "San Cristóbal y Nieves",
		"es-BR": "San Cristóbal y Nieves",
		"es-BZ": "San Cristóbal y Nieves",
		"es-CL": "San Cristóbal y Nieves",
		"es-CO": "San Cristóbal y Nieves",
		"es-CR": "San Cristóbal y Nieves",
		"es-CU": "San Cristóbal y Nieves",
		"es-DO": "San Cristóbal y Nieves",
		"es-EC": "San Cristóbal y Nieves",
		"es-GT": "San Cristóbal y Nieves",
		"es-HN": "San Cristóbal y Nieves",
		"es-MX": "San Cristóbal y Nieves",
		"es-NI": "San Cristóbal y Nieves",
		"es-PA": "San Cristóbal y Nieves",
		"es-PE": "San Cristóbal y Nieves",
		"es-PR": "San Cristóbal y Nieves",
		"es-PY": "San Cristóbal y Nieves",
		"es-SV": "San Cristóbal y Nieves",
		"es-US": "San Cristóbal y Nieves",
		"es-UY": "San Cristóbal y Nieves",
		"es-VE": "San Cristóbal y Nieves",
		"en-US": "St. Kitts & Nevis",
		"fr-FR": "Saint-Christophe-et-Niévès",
		"fr-BE": "Saint-Christophe-et-Niévès",
		"fr-CA": "Saint‑Kitts‑et‑Nevis",
		"fr-CH": "Saint-Christophe-et-Niévès",
		"fr-LU": "Saint-Christophe-et-Niévès",
		"fr-MC": "Saint-Christophe-et-Niévès",
		"it-IT": "Saint Kitts e Nevis",
		"it-CH": "Saint Kitts e Nevis",
		"it-SM": "Saint Kitts e Nevis",
		"it-VA": "Saint Kitts e Nevis",
		"de-DE": "St. Kitts und Nevis",
		"de-AT": "St. Kitts und Nevis",
		"de-CH": "St. Kitts und Nevis",
		"de-BE": "St. Kitts und Nevis",
		"de-LI": "St. Kitts und Nevis",
		"de-LU": "St. Kitts und Nevis"
	}
} satisfies Country;
