import type { Country } from './types.js';

export const KNA = {
	"code": "KNA",
	"labels": {
		"pt-BR": "São Cristóvão e Névis",
		"pt-PT": "São Cristóvão e Neves",
		"qu-PE": "San Cristóbal y Nieves",
		"qu-BO": "San Cristóbal y Nieves",
		"qu-EC": "San Cristóbal y Nieves",
		"chr-US": "ᎤᏓᏅᏘ ᎨᏘᏏ ᎠᎴ ᏁᏪᏏ",
		"hi-IN": "सेंट किट्स और नेविस",
		"bn-IN": "সেন্ট কিটস ও নেভিস",
		"bn-BD": "সেন্ট কিটস ও নেভিস",
		"ta-IN": "செயின்ட் கிட்ஸ் & நெவிஸ்",
		"ta-LK": "செயின்ட் கிட்ஸ் & நெவிஸ்",
		"ta-SG": "செயின்ட் கிட்ஸ் & நெவிஸ்",
		"ta-MY": "செயின்ட் கிட்ஸ் & நெவிஸ்",
		"te-IN": "సెయింట్ కిట్స్ మరియు నెవిస్",
		"mr-IN": "सेंट किट्स आणि नेव्हिस",
		"gu-IN": "સેંટ કિટ્સ અને નેવિસ",
		"kn-IN": "ಸೇಂಟ್ ಕಿಟ್ಸ್ ಮತ್ತು ನೆವಿಸ್",
		"ml-IN": "സെന്റ് കിറ്റ്‌സും നെവിസും",
		"pa-IN": "ਸੇਂਟ ਕਿਟਸ ਐਂਡ ਨੇਵਿਸ",
		"ur-IN": "سینٹ کٹس اور نیویس",
		"ur-PK": "سینٹ کٹس اور نیویس",
		"or-IN": "ସେଣ୍ଟ କିଟସ୍‌ ଏବଂ ନେଭିସ୍‌",
		"as-IN": "ছেইণ্ট কিটছ আৰু নেভিছ",
		"ne-IN": "सेन्ट किट्स र नेभिस",
		"ne-NP": "सेन्ट किट्स र नेभिस",
		"si-LK": "ශාන්ත කිට්ස් සහ නේවිස්",
		"kok-IN": "सेंट किट्स आनी नेविस",
		"ks-IN": "سینٹ کِٹَس تہٕ نیوِس",
		"brx-IN": "सैन्ट कीत्स आरो नेभिस",
		"mai-IN": "सेंट किट्स आ नेविस",
		"dz-BT": "སེནཊ་ ཀིཊས་ དང་ ནེ་བིས",
		"ja-JP": "セントクリストファー・ネーヴィス",
		"ko-KR": "세인트키츠 네비스",
		"ko-KP": "세인트키츠 네비스",
		"zh-CN": "圣基茨和尼维斯",
		"zh-Hans-CN": "圣基茨和尼维斯",
		"zh-Hant-TW": "聖克里斯多福及尼維斯",
		"zh-TW": "聖克里斯多福及尼維斯",
		"zh-HK": "聖基茨和尼維斯",
		"zh-MO": "聖基茨和尼維斯",
		"zh-SG": "圣基茨和尼维斯",
		"yue-Hant-HK": "聖基茨同尼維斯",
		"yue-Hans-CN": "圣基茨同尼维斯",
		"mn-MN": "Сент-Киттс ба Невис",
		"ug-CN": "ساينت كىتىس ۋە نېۋىس",
		"th-TH": "เซนต์คิตส์และเนวิส",
		"lo-LA": "ເຊນ ຄິດ ແລະ ເນວິສ",
		"km-KH": "សាំង​គីត និង ណេវីស",
		"my-MM": "စိန့်ကစ်နှင့်နီဗီစ်",
		"vi-VN": "St. Kitts và Nevis",
		"id-ID": "Saint Kitts dan Nevis",
		"ms-MY": "Saint Kitts dan Nevis",
		"ms-SG": "Saint Kitts dan Nevis",
		"ms-BN": "Saint Kitts dan Nevis",
		"jv-ID": "Saint Kits lan Nèvis",
		"fil-PH": "St. Kitts & Nevis",
		"ceb-PH": "St. Kitts & Nevis",
		"ka-GE": "სენტ-კიტსი და ნევისი",
		"hy-AM": "Սենթ Քիտս և Նևիս",
		"az-AZ": "Sent-Kits və Nevis",
		"az-Cyrl-AZ": "Сент-Китс вә Невис",
		"kk-KZ": "Сент-Китс және Невис",
		"ky-KG": "Сент-Китс жана Невис",
		"uz-UZ": "Sent-Kits va Nevis",
		"tg-TJ": "Сент-Китс ва Невис",
		"tk-TM": "Sent-Kits we Newis",
		"fa-IR": "سنت کیتس و نویس",
		"fa-AF": "سنت کیتس و نویس",
		"ps-AF": "سینټ کټس او نیویس",
		"ps-PK": "سینټ کټس او نیویس",
		"he-IL": "סנט קיטס ונוויס",
		"ar-SA": "سانت كيتس ونيفيس",
		"ar-AE": "سانت كيتس ونيفيس",
		"ar-QA": "سانت كيتس ونيفيس",
		"ar-BH": "سانت كيتس ونيفيس",
		"ar-KW": "سانت كيتس ونيفيس",
		"ar-OM": "سانت كيتس ونيفيس",
		"ar-YE": "سانت كيتس ونيفيس",
		"ar-IQ": "سانت كيتس ونيفيس",
		"ar-JO": "سانت كيتس ونيفيس",
		"ar-LB": "سانت كيتس ونيفيس",
		"ar-SY": "سانت كيتس ونيفيس",
		"ar-PS": "سانت كيتس ونيفيس",
		"en-US": "St. Kitts & Nevis",
		"en-GB": "St Kitts & Nevis",
		"en-IE": "St Kitts & Nevis",
		"en-MT": "St Kitts & Nevis",
		"en-GI": "St Kitts & Nevis",
		"en-CY": "St Kitts & Nevis",
		"en-JE": "St Kitts & Nevis",
		"en-GG": "St Kitts & Nevis",
		"en-IM": "St Kitts & Nevis",
		"en-CA": "Saint Kitts and Nevis",
		"en-AU": "St. Kitts & Nevis",
		"en-NZ": "St Kitts & Nevis",
		"en-ZA": "St Kitts & Nevis",
		"en-IN": "St Kitts & Nevis",
		"en-SG": "St Kitts & Nevis",
		"pt-AO": "São Cristóvão e Neves",
		"pt-MZ": "São Cristóvão e Neves",
		"pt-CV": "São Cristóvão e Neves",
		"pt-GW": "São Cristóvão e Neves",
		"pt-ST": "São Cristóvão e Neves",
		"pt-TL": "São Cristóvão e Neves",
		"pt-MO": "São Cristóvão e Neves",
		"es-ES": "San Cristóbal y Nieves",
		"es-419": "San Cristóbal y Nieves",
		"es-AD": "San Cristóbal y Nieves",
		"es-GI": "San Cristóbal y Nieves",
		"es-AR": "San Cristóbal y Nieves",
		"es-BO": "San Cristóbal y Nieves",
		"es-BR": "San Cristóbal y Nieves",
		"es-BZ": "San Cristóbal y Nieves",
		"es-CL": "San Cristóbal y Nieves",
		"es-CO": "San Cristóbal y Nieves",
		"es-CR": "San Cristóbal y Nieves",
		"es-CU": "San Cristóbal y Nieves",
		"es-DO": "San Cristóbal y Nieves",
		"es-EC": "San Cristóbal y Nieves",
		"es-GT": "San Cristóbal y Nieves",
		"es-HN": "San Cristóbal y Nieves",
		"es-MX": "San Cristóbal y Nieves",
		"es-NI": "San Cristóbal y Nieves",
		"es-PA": "San Cristóbal y Nieves",
		"es-PE": "San Cristóbal y Nieves",
		"es-PR": "San Cristóbal y Nieves",
		"es-PY": "San Cristóbal y Nieves",
		"es-SV": "San Cristóbal y Nieves",
		"es-US": "San Cristóbal y Nieves",
		"es-UY": "San Cristóbal y Nieves",
		"es-VE": "San Cristóbal y Nieves",
		"fr-FR": "Saint-Christophe-et-Niévès",
		"fr-BE": "Saint-Christophe-et-Niévès",
		"fr-CH": "Saint-Christophe-et-Niévès",
		"fr-LU": "Saint-Christophe-et-Niévès",
		"fr-MC": "Saint-Christophe-et-Niévès",
		"fr-AD": "Saint-Christophe-et-Niévès",
		"fr-CA": "Saint‑Kitts‑et‑Nevis",
		"it-IT": "Saint Kitts e Nevis",
		"it-CH": "Saint Kitts e Nevis",
		"it-SM": "Saint Kitts e Nevis",
		"it-VA": "Saint Kitts e Nevis",
		"de-DE": "St. Kitts und Nevis",
		"de-AT": "St. Kitts und Nevis",
		"de-CH": "St. Kitts und Nevis",
		"de-BE": "St. Kitts und Nevis",
		"de-LI": "St. Kitts und Nevis",
		"de-LU": "St. Kitts und Nevis",
		"nl-NL": "Saint Kitts en Nevis",
		"nl-BE": "Saint Kitts en Nevis",
		"sv-SE": "S:t Kitts och Nevis",
		"sv-FI": "S:t Kitts och Nevis",
		"da-DK": "Saint Kitts og Nevis",
		"nb-NO": "Saint Kitts og Nevis",
		"nn-NO": "Saint Kitts og Nevis",
		"fi-FI": "Saint Kitts ja Nevis",
		"is-IS": "Sankti Kitts og Nevis",
		"fo-FO": "St. Kitts & Nevis",
		"et-EE": "Saint Kitts ja Nevis",
		"lv-LV": "Sentkitsa un Nevisa",
		"lt-LT": "Sent Kitsas ir Nevis",
		"pl-PL": "Saint Kitts i Nevis",
		"cs-CZ": "Svatý Kryštof a Nevis",
		"sk-SK": "Svätý Krištof a Nevis",
		"sl-SI": "Saint Kitts in Nevis",
		"hr-HR": "Sveti Kristofor i Nevis",
		"bs-BA": "Sveti Kits i Nevis",
		"sr-RS": "Сент Китс и Невис",
		"sr-BA": "Сент Китс и Невис",
		"sr-ME": "Sveti Kits i Nevis",
		"mk-MK": "Свети Китс и Невис",
		"bg-BG": "Сейнт Китс и Невис",
		"be-BY": "Сент-Кітс і Невіс",
		"uk-UA": "Сент-Кітс і Невіс",
		"ru-RU": "Сент-Китс и Невис",
		"el-GR": "Σεν Κιτς και Νέβις",
		"el-CY": "Σεν Κιτς και Νέβις",
		"ro-RO": "Saint Kitts și Nevis",
		"ro-MD": "Saint Kitts și Nevis",
		"hu-HU": "Saint Kitts és Nevis",
		"sq-AL": "Shën-Kits dhe Nevis",
		"sq-XK": "Shën-Kits dhe Nevis",
		"mt-MT": "Saint Kitts u Nevis",
		"ga-IE": "San Críostóir-Nimheas",
		"cy-GB": "Saint Kitts a Nevis",
		"gd-GB": "Naomh Crìstean is Nibheis",
		"lb-LU": "St. Kitts an Nevis",
		"ca-ES": "Saint Kitts i Nevis",
		"ca-AD": "Saint Kitts i Nevis",
		"ca-FR": "Saint Kitts i Nevis",
		"ca-IT": "Saint Kitts i Nevis",
		"eu-ES": "Saint Kitts eta Nevis",
		"eu-FR": "Saint Kitts eta Nevis",
		"gl-ES": "Saint Kitts e Nevis",
		"tr-TR": "Saint Kitts ve Nevis",
		"tr-CY": "Saint Kitts ve Nevis"
	},
	"callingCode": "1869",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
