import type { Country } from './types.js';

export const KOR = {
	"code": "KOR",
	"labels": {
		"pt-BR": "Coreia do Sul",
		"pt-PT": "Coreia do Sul",
		"qu-PE": "Corea del Sur",
		"qu-BO": "Corea del Sur",
		"qu-EC": "Corea del Sur",
		"chr-US": "ᏧᎦᏃᏮ ᎪᎵᎠ",
		"hi-IN": "दक्षिण कोरिया",
		"bn-IN": "দক্ষিণ কোরিয়া",
		"bn-BD": "দক্ষিণ কোরিয়া",
		"ta-IN": "தென் கொரியா",
		"ta-LK": "தென் கொரியா",
		"ta-SG": "தென் கொரியா",
		"ta-MY": "தென் கொரியா",
		"te-IN": "దక్షిణ కొరియా",
		"mr-IN": "दक्षिण कोरिया",
		"gu-IN": "દક્ષિણ કોરિયા",
		"kn-IN": "ದಕ್ಷಿಣ ಕೊರಿಯಾ",
		"ml-IN": "ദക്ഷിണകൊറിയ",
		"pa-IN": "ਦੱਖਣ ਕੋਰੀਆ",
		"ur-IN": "جنوبی کوریا",
		"ur-PK": "جنوبی کوریا",
		"or-IN": "ଦକ୍ଷିଣ କୋରିଆ",
		"as-IN": "দক্ষিণ কোৰিয়া",
		"ne-IN": "दक्षिण कोरिया",
		"ne-NP": "दक्षिण कोरिया",
		"si-LK": "දකුණු කොරියාව",
		"kok-IN": "दक्षिण कोरिया",
		"ks-IN": "جنوٗبی کورِیا",
		"brx-IN": "खोला करिया",
		"mai-IN": "दक्षिण कोरिया",
		"dz-BT": "ལྷོ་ ཀོ་རི་ཡ",
		"ja-JP": "韓国",
		"ko-KR": "대한민국",
		"ko-KP": "대한민국",
		"zh-CN": "韩国",
		"zh-Hans-CN": "韩国",
		"zh-Hant-TW": "南韓",
		"zh-TW": "南韓",
		"zh-HK": "南韓",
		"zh-MO": "南韓",
		"zh-SG": "韩国",
		"yue-Hant-HK": "南韓",
		"yue-Hans-CN": "南韩",
		"mn-MN": "Өмнөд Солонгос",
		"bo-CN": "ལྷོ་ཀོ་རི་ཡ།",
		"bo-IN": "ལྷོ་ཀོ་རི་ཡ།",
		"ug-CN": "كورېيە",
		"th-TH": "เกาหลีใต้",
		"lo-LA": "ເກົາຫລີໃຕ້",
		"km-KH": "កូរ៉េ​ខាង​ត្បូង",
		"my-MM": "တောင်ကိုရီးယား",
		"vi-VN": "Hàn Quốc",
		"id-ID": "Korea Selatan",
		"ms-MY": "Korea Selatan",
		"ms-SG": "Korea Selatan",
		"ms-BN": "Korea Selatan",
		"jv-ID": "Koréa Kidul",
		"fil-PH": "Timog Korea",
		"ceb-PH": "South Korea",
		"ka-GE": "სამხრეთ კორეა",
		"hy-AM": "Հարավային Կորեա",
		"az-AZ": "Cənubi Koreya",
		"az-Cyrl-AZ": "Ҹәнуби Кореја",
		"kk-KZ": "Оңтүстік Корея",
		"ky-KG": "Түштүк Корея",
		"uz-UZ": "Janubiy Koreya",
		"tg-TJ": "Кореяи Ҷанубӣ",
		"tk-TM": "Günorta Koreýa",
		"fa-IR": "کرهٔ جنوبی",
		"fa-AF": "کوریای جنوبی",
		"ps-AF": "سویلي کوریا",
		"ps-PK": "سویلي کوریا",
		"he-IL": "קוריאה הדרומית",
		"ar-SA": "كوريا الجنوبية",
		"ar-AE": "كوريا الجنوبية",
		"ar-QA": "كوريا الجنوبية",
		"ar-BH": "كوريا الجنوبية",
		"ar-KW": "كوريا الجنوبية",
		"ar-OM": "كوريا الجنوبية",
		"ar-YE": "كوريا الجنوبية",
		"ar-IQ": "كوريا الجنوبية",
		"ar-JO": "كوريا الجنوبية",
		"ar-LB": "كوريا الجنوبية",
		"ar-SY": "كوريا الجنوبية",
		"ar-PS": "كوريا الجنوبية",
		"en-US": "South Korea",
		"en-GB": "South Korea",
		"en-IE": "South Korea",
		"en-MT": "South Korea",
		"en-GI": "South Korea",
		"en-CY": "South Korea",
		"en-JE": "South Korea",
		"en-GG": "South Korea",
		"en-IM": "South Korea",
		"en-CA": "South Korea",
		"en-AU": "South Korea",
		"en-NZ": "South Korea",
		"en-ZA": "South Korea",
		"en-IN": "South Korea",
		"en-SG": "South Korea",
		"pt-AO": "Coreia do Sul",
		"pt-MZ": "Coreia do Sul",
		"pt-CV": "Coreia do Sul",
		"pt-GW": "Coreia do Sul",
		"pt-ST": "Coreia do Sul",
		"pt-TL": "Coreia do Sul",
		"pt-MO": "Coreia do Sul",
		"es-ES": "Corea del Sur",
		"es-419": "Corea del Sur",
		"es-AD": "Corea del Sur",
		"es-GI": "Corea del Sur",
		"es-AR": "Corea del Sur",
		"es-BO": "Corea del Sur",
		"es-BR": "Corea del Sur",
		"es-BZ": "Corea del Sur",
		"es-CL": "Corea del Sur",
		"es-CO": "Corea del Sur",
		"es-CR": "Corea del Sur",
		"es-CU": "Corea del Sur",
		"es-DO": "Corea del Sur",
		"es-EC": "Corea del Sur",
		"es-GT": "Corea del Sur",
		"es-HN": "Corea del Sur",
		"es-MX": "Corea del Sur",
		"es-NI": "Corea del Sur",
		"es-PA": "Corea del Sur",
		"es-PE": "Corea del Sur",
		"es-PR": "Corea del Sur",
		"es-PY": "Corea del Sur",
		"es-SV": "Corea del Sur",
		"es-US": "Corea del Sur",
		"es-UY": "Corea del Sur",
		"es-VE": "Corea del Sur",
		"fr-FR": "Corée du Sud",
		"fr-BE": "Corée du Sud",
		"fr-CH": "Corée du Sud",
		"fr-LU": "Corée du Sud",
		"fr-MC": "Corée du Sud",
		"fr-AD": "Corée du Sud",
		"fr-CA": "Corée du Sud",
		"it-IT": "Corea del Sud",
		"it-CH": "Corea del Sud",
		"it-SM": "Corea del Sud",
		"it-VA": "Corea del Sud",
		"de-DE": "Südkorea",
		"de-AT": "Südkorea",
		"de-CH": "Südkorea",
		"de-BE": "Südkorea",
		"de-LI": "Südkorea",
		"de-LU": "Südkorea",
		"nl-NL": "Zuid-Korea",
		"nl-BE": "Zuid-Korea",
		"sv-SE": "Sydkorea",
		"sv-FI": "Sydkorea",
		"da-DK": "Sydkorea",
		"nb-NO": "Sør-Korea",
		"nn-NO": "Sør-Korea",
		"fi-FI": "Etelä-Korea",
		"is-IS": "Suður-Kórea",
		"fo-FO": "Suðurkorea",
		"et-EE": "Lõuna-Korea",
		"lv-LV": "Dienvidkoreja",
		"lt-LT": "Pietų Korėja",
		"pl-PL": "Korea Południowa",
		"cs-CZ": "Jižní Korea",
		"sk-SK": "Južná Kórea",
		"sl-SI": "Južna Koreja",
		"hr-HR": "Južna Koreja",
		"bs-BA": "Južna Koreja",
		"sr-RS": "Јужна Кореја",
		"sr-BA": "Јужна Кореја",
		"sr-ME": "Južna Koreja",
		"mk-MK": "Јужна Кореја",
		"bg-BG": "Южна Корея",
		"be-BY": "Паўднёвая Карэя",
		"uk-UA": "Південна Корея",
		"ru-RU": "Республика Корея",
		"el-GR": "Νότια Κορέα",
		"el-CY": "Νότια Κορέα",
		"ro-RO": "Coreea de Sud",
		"ro-MD": "Coreea de Sud",
		"hu-HU": "Dél-Korea",
		"sq-AL": "Kore e Jugut",
		"sq-XK": "Kore e Jugut",
		"mt-MT": "il-Korea t’Isfel",
		"ga-IE": "an Chóiré Theas",
		"cy-GB": "De Corea",
		"gd-GB": "Coirèa",
		"lb-LU": "Südkorea",
		"ca-ES": "Corea del Sud",
		"ca-AD": "Corea del Sud",
		"ca-FR": "Corea del Sud",
		"ca-IT": "Corea del Sud",
		"eu-ES": "Hego Korea",
		"eu-FR": "Hego Korea",
		"gl-ES": "Corea do Sur",
		"tr-TR": "Güney Kore",
		"tr-CY": "Güney Kore"
	},
	"callingCode": "82",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "##-####",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"(?:3[1-3]|[46][1-4]|5[1-5])1"
			]
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "#-####-####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "##-###-####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[36]0|8"
			]
		},
		{
			"mask": "##-####-####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[1346]|5[1-5]"
			]
		},
		{
			"mask": "##-####-####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[57]"
			]
		},
		{
			"mask": "##-#####-####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"5"
			]
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12
		},
		{
			"mask": "# ### ### ### ###",
			"minLength": 13,
			"maxLength": 13
		},
		{
			"mask": "## ### ### ### ###",
			"minLength": 14,
			"maxLength": 14
		}
	]
} satisfies Country;
