import type { Country } from './types.js';

export const LBN = {
	"code": "LBN",
	"labels": {
		"pt-BR": "Líbano",
		"pt-PT": "Líbano",
		"es-ES": "Líbano",
		"es-419": "Líbano",
		"es-AR": "Líbano",
		"es-BO": "Líbano",
		"es-BR": "Líbano",
		"es-BZ": "Líbano",
		"es-CL": "Líbano",
		"es-CO": "Líbano",
		"es-CR": "Líbano",
		"es-CU": "Líbano",
		"es-DO": "Líbano",
		"es-EC": "Líbano",
		"es-GT": "Líbano",
		"es-HN": "Líbano",
		"es-MX": "Líbano",
		"es-NI": "Líbano",
		"es-PA": "Líbano",
		"es-PE": "Líbano",
		"es-PR": "Líbano",
		"es-PY": "Líbano",
		"es-SV": "Líbano",
		"es-US": "Líbano",
		"es-UY": "Líbano",
		"es-VE": "Líbano",
		"en-US": "Lebanon",
		"fr-FR": "Liban",
		"fr-BE": "Liban",
		"fr-CA": "Liban",
		"fr-CH": "Liban",
		"fr-LU": "Liban",
		"fr-MC": "Liban",
		"it-IT": "Libano",
		"it-CH": "Libano",
		"it-SM": "Libano",
		"it-VA": "Libano",
		"de-DE": "Libanon",
		"de-AT": "Libanon",
		"de-CH": "Libanon",
		"de-BE": "Libanon",
		"de-LI": "Libanon",
		"de-LU": "Libanon"
	}
} satisfies Country;
