import type { Country } from './types.js';

export const LBY = {
	"code": "LBY",
	"labels": {
		"pt-BR": "Líbia",
		"pt-PT": "Líbia",
		"es-ES": "Libia",
		"es-419": "Libia",
		"es-AR": "Libia",
		"es-BO": "Libia",
		"es-BR": "Libia",
		"es-BZ": "Libia",
		"es-CL": "Libia",
		"es-CO": "Libia",
		"es-CR": "Libia",
		"es-CU": "Libia",
		"es-DO": "Libia",
		"es-EC": "Libia",
		"es-GT": "Libia",
		"es-HN": "Libia",
		"es-MX": "Libia",
		"es-NI": "Libia",
		"es-PA": "Libia",
		"es-PE": "Libia",
		"es-PR": "Libia",
		"es-PY": "Libia",
		"es-SV": "Libia",
		"es-US": "Libia",
		"es-UY": "Libia",
		"es-VE": "Libia",
		"en-US": "Libya",
		"fr-FR": "Libye",
		"fr-BE": "Libye",
		"fr-CA": "Libye",
		"fr-CH": "Libye",
		"fr-LU": "Libye",
		"fr-MC": "Libye",
		"it-IT": "Libia",
		"it-CH": "Libia",
		"it-SM": "Libia",
		"it-VA": "Libia",
		"de-DE": "Libyen",
		"de-AT": "Libyen",
		"de-CH": "Libyen",
		"de-BE": "Libyen",
		"de-LI": "Libyen",
		"de-LU": "Libyen"
	}
} satisfies Country;
