import type { Country } from './types.js';

export const LCA = {
	"code": "LCA",
	"labels": {
		"pt-BR": "Santa Lúcia",
		"pt-PT": "Santa Lúcia",
		"qu-PE": "Santa Lucia",
		"qu-BO": "Santa Lucia",
		"qu-EC": "Santa Lucia",
		"chr-US": "ᎤᏓᏅᏘ ᎷᏏᏯ",
		"hi-IN": "सेंट लूसिया",
		"bn-IN": "সেন্ট লুসিয়া",
		"bn-BD": "সেন্ট লুসিয়া",
		"ta-IN": "செயின்ட் லூசியா",
		"ta-LK": "செயின்ட் லூசியா",
		"ta-SG": "செயின்ட் லூசியா",
		"ta-MY": "செயின்ட் லூசியா",
		"te-IN": "సెయింట్ లూసియా",
		"mr-IN": "सेंट ल्यूसिया",
		"gu-IN": "સેંટ લુસિયા",
		"kn-IN": "ಸೇಂಟ್ ಲೂಸಿಯಾ",
		"ml-IN": "സെന്റ് ലൂസിയ",
		"pa-IN": "ਸੇਂਟ ਲੂਸੀਆ",
		"ur-IN": "سینٹ لوسیا",
		"ur-PK": "سینٹ لوسیا",
		"or-IN": "ସେଣ୍ଟ ଲୁସିଆ",
		"as-IN": "ছেইণ্ট লুচিয়া",
		"ne-IN": "सेन्ट लुसिया",
		"ne-NP": "सेन्ट लुसिया",
		"si-LK": "ශාන්ත ලුසියා",
		"kok-IN": "सँट लुसिया",
		"ks-IN": "سینٹ لوٗسِیا",
		"brx-IN": "सैन्ट लुसिया",
		"mai-IN": "सेंट लूसिया",
		"dz-BT": "སེནཊ་ ལུ་སི་ཡ",
		"ja-JP": "セントルシア",
		"ko-KR": "세인트루시아",
		"ko-KP": "세인트루시아",
		"zh-CN": "圣卢西亚",
		"zh-Hans-CN": "圣卢西亚",
		"zh-Hant-TW": "聖露西亞",
		"zh-TW": "聖露西亞",
		"zh-HK": "聖盧西亞",
		"zh-MO": "聖盧西亞",
		"zh-SG": "圣卢西亚",
		"yue-Hant-HK": "聖露西亞",
		"yue-Hans-CN": "圣露西亚",
		"mn-MN": "Сент Люсиа",
		"ug-CN": "ساينت لۇسىيە",
		"th-TH": "เซนต์ลูเซีย",
		"lo-LA": "ເຊນ ລູເຊຍ",
		"km-KH": "សាំងលូស៊ី",
		"my-MM": "စိန့်လူစီယာ",
		"vi-VN": "St. Lucia",
		"id-ID": "Saint Lucia",
		"ms-MY": "Saint Lucia",
		"ms-SG": "Saint Lucia",
		"ms-BN": "Saint Lucia",
		"jv-ID": "Santa Lusia",
		"fil-PH": "Saint Lucia",
		"ceb-PH": "St. Lucia",
		"ka-GE": "სენტ-ლუსია",
		"hy-AM": "Սենթ Լյուսիա",
		"az-AZ": "Sent-Lusiya",
		"az-Cyrl-AZ": "Сент-Лусија",
		"kk-KZ": "Сент-Люсия",
		"ky-KG": "Сент-Люсия",
		"uz-UZ": "Sent-Lyusiya",
		"tg-TJ": "Сент-Люсия",
		"tk-TM": "Sent-Lýusiýa",
		"fa-IR": "سنت لوسیا",
		"fa-AF": "سنت لوسیا",
		"ps-AF": "سینټ لوسیا",
		"ps-PK": "سینټ لوسیا",
		"he-IL": "סנט לוסיה",
		"ar-SA": "سانت لوسيا",
		"ar-AE": "سانت لوسيا",
		"ar-QA": "سانت لوسيا",
		"ar-BH": "سانت لوسيا",
		"ar-KW": "سانت لوسيا",
		"ar-OM": "سانت لوسيا",
		"ar-YE": "سانت لوسيا",
		"ar-IQ": "سانت لوسيا",
		"ar-JO": "سانت لوسيا",
		"ar-LB": "سانت لوسيا",
		"ar-SY": "سانت لوسيا",
		"ar-PS": "سانت لوسيا",
		"en-US": "St. Lucia",
		"en-GB": "St Lucia",
		"en-IE": "St Lucia",
		"en-MT": "St Lucia",
		"en-GI": "St Lucia",
		"en-CY": "St Lucia",
		"en-JE": "St Lucia",
		"en-GG": "St Lucia",
		"en-IM": "St Lucia",
		"en-CA": "Saint Lucia",
		"en-AU": "St. Lucia",
		"en-NZ": "St Lucia",
		"en-ZA": "St Lucia",
		"en-IN": "St Lucia",
		"en-SG": "St Lucia",
		"pt-AO": "Santa Lúcia",
		"pt-MZ": "Santa Lúcia",
		"pt-CV": "Santa Lúcia",
		"pt-GW": "Santa Lúcia",
		"pt-ST": "Santa Lúcia",
		"pt-TL": "Santa Lúcia",
		"pt-MO": "Santa Lúcia",
		"es-ES": "Santa Lucía",
		"es-419": "Santa Lucía",
		"es-AD": "Santa Lucía",
		"es-GI": "Santa Lucía",
		"es-AR": "Santa Lucía",
		"es-BO": "Santa Lucía",
		"es-BR": "Santa Lucía",
		"es-BZ": "Santa Lucía",
		"es-CL": "Santa Lucía",
		"es-CO": "Santa Lucía",
		"es-CR": "Santa Lucía",
		"es-CU": "Santa Lucía",
		"es-DO": "Santa Lucía",
		"es-EC": "Santa Lucía",
		"es-GT": "Santa Lucía",
		"es-HN": "Santa Lucía",
		"es-MX": "Santa Lucía",
		"es-NI": "Santa Lucía",
		"es-PA": "Santa Lucía",
		"es-PE": "Santa Lucía",
		"es-PR": "Santa Lucía",
		"es-PY": "Santa Lucía",
		"es-SV": "Santa Lucía",
		"es-US": "Santa Lucía",
		"es-UY": "Santa Lucía",
		"es-VE": "Santa Lucía",
		"fr-FR": "Sainte-Lucie",
		"fr-BE": "Sainte-Lucie",
		"fr-CH": "Sainte-Lucie",
		"fr-LU": "Sainte-Lucie",
		"fr-MC": "Sainte-Lucie",
		"fr-AD": "Sainte-Lucie",
		"fr-CA": "Sainte-Lucie",
		"it-IT": "Saint Lucia",
		"it-CH": "Saint Lucia",
		"it-SM": "Saint Lucia",
		"it-VA": "Saint Lucia",
		"de-DE": "St. Lucia",
		"de-AT": "St. Lucia",
		"de-CH": "St. Lucia",
		"de-BE": "St. Lucia",
		"de-LI": "St. Lucia",
		"de-LU": "St. Lucia",
		"nl-NL": "Saint Lucia",
		"nl-BE": "Saint Lucia",
		"sv-SE": "S:t Lucia",
		"sv-FI": "S:t Lucia",
		"da-DK": "Saint Lucia",
		"nb-NO": "St. Lucia",
		"nn-NO": "St. Lucia",
		"fi-FI": "Saint Lucia",
		"is-IS": "Sankti Lúsía",
		"fo-FO": "St. Lusia",
		"et-EE": "Saint Lucia",
		"lv-LV": "Sentlūsija",
		"lt-LT": "Sent Lusija",
		"pl-PL": "Saint Lucia",
		"cs-CZ": "Svatá Lucie",
		"sk-SK": "Svätá Lucia",
		"sl-SI": "Saint Lucia",
		"hr-HR": "Sveta Lucija",
		"bs-BA": "Sveta Lucija",
		"sr-RS": "Света Луција",
		"sr-BA": "Света Луција",
		"sr-ME": "Sveta Lucija",
		"mk-MK": "Сент Лусија",
		"bg-BG": "Сейнт Лусия",
		"be-BY": "Сент-Люсія",
		"uk-UA": "Сент-Люсія",
		"ru-RU": "Сент-Люсия",
		"el-GR": "Αγία Λουκία",
		"el-CY": "Αγία Λουκία",
		"ro-RO": "Sfânta Lucia",
		"ro-MD": "Sfânta Lucia",
		"hu-HU": "Saint Lucia",
		"sq-AL": "Shën-Luçia",
		"sq-XK": "Shën-Luçia",
		"mt-MT": "Saint Lucia",
		"ga-IE": "Saint Lucia",
		"cy-GB": "Saint Lucia",
		"gd-GB": "Naomh Lùisea",
		"lb-LU": "St. Lucia",
		"ca-ES": "Saint Lucia",
		"ca-AD": "Saint Lucia",
		"ca-FR": "Saint Lucia",
		"ca-IT": "Saint Lucia",
		"eu-ES": "Santa Luzia",
		"eu-FR": "Santa Luzia",
		"gl-ES": "Santa Lucía",
		"tr-TR": "Saint Lucia",
		"tr-CY": "Saint Lucia"
	},
	"callingCode": "1758",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
