import type { Country } from './types.js';

export const LIE = {
	"code": "LIE",
	"labels": {
		"pt-BR": "Liechtenstein",
		"pt-PT": "Listenstaine",
		"qu-PE": "Liechtenstein",
		"qu-BO": "Liechtenstein",
		"qu-EC": "Liechtenstein",
		"chr-US": "ᎵᎦᏗᏂᏍᏓᏂ",
		"hi-IN": "लिचेंस्टीन",
		"bn-IN": "লিচেনস্টেইন",
		"bn-BD": "লিচেনস্টেইন",
		"ta-IN": "லிச்செண்ஸ்டெய்ன்",
		"ta-LK": "லிச்செண்ஸ்டெய்ன்",
		"ta-SG": "லிச்செண்ஸ்டெய்ன்",
		"ta-MY": "லிச்செண்ஸ்டெய்ன்",
		"te-IN": "లిక్టెన్‌స్టెయిన్",
		"mr-IN": "लिक्टेनस्टाइन",
		"gu-IN": "લૈચટેંસ્ટેઇન",
		"kn-IN": "ಲಿಚೆನ್‌ಸ್ಟೈನ್",
		"ml-IN": "ലിച്ചൺസ്റ്റൈൻ",
		"pa-IN": "ਲਿਚੇਂਸਟਾਇਨ",
		"ur-IN": "لیشٹنسٹائن",
		"ur-PK": "لیشٹنسٹائن",
		"or-IN": "ଲିକ୍ଟନ୍‌ଷ୍ଟାଇନ୍‌",
		"as-IN": "লিচটেনষ্টেইন",
		"ne-IN": "लिकटेन्सटाइन",
		"ne-NP": "लिकटेन्सटाइन",
		"si-LK": "ලික්ටන්ස්ටයින්",
		"kok-IN": "लिचेंस्टीन",
		"ks-IN": "لِکٹیسٹیٖن",
		"brx-IN": "लिक्तोनस्ताईन",
		"mai-IN": "लिख्तेंस्ताइन",
		"dz-BT": "ལིཀ་ཏནས་ཏ་ཡིན",
		"ja-JP": "リヒテンシュタイン",
		"ko-KR": "리히텐슈타인",
		"ko-KP": "리히텐슈타인",
		"zh-CN": "列支敦士登",
		"zh-Hans-CN": "列支敦士登",
		"zh-Hant-TW": "列支敦斯登",
		"zh-TW": "列支敦斯登",
		"zh-HK": "列支敦士登",
		"zh-MO": "列支敦士登",
		"zh-SG": "列支敦士登",
		"yue-Hant-HK": "列支敦斯登",
		"yue-Hans-CN": "列支敦斯登",
		"mn-MN": "Лихтенштайн",
		"ug-CN": "لىكتېنستېين",
		"th-TH": "ลิกเตนสไตน์",
		"lo-LA": "ລິດເທນສະຕາຍ",
		"km-KH": "លិចតិនស្ដាញ",
		"my-MM": "လစ်တန်စတိန်း",
		"vi-VN": "Liechtenstein",
		"id-ID": "Liechtenstein",
		"ms-MY": "Liechtenstein",
		"ms-SG": "Liechtenstein",
		"ms-BN": "Liechtenstein",
		"jv-ID": "Liktenstén",
		"fil-PH": "Liechtenstein",
		"ceb-PH": "Liechtenstein",
		"ka-GE": "ლიხტენშტაინი",
		"hy-AM": "Լիխտենշտեյն",
		"az-AZ": "Lixtenşteyn",
		"az-Cyrl-AZ": "Лихтенштејн",
		"kk-KZ": "Лихтенштейн",
		"ky-KG": "Лихтенштейн",
		"uz-UZ": "Lixtenshteyn",
		"tg-TJ": "Лихтенштейн",
		"tk-TM": "Lihtenşteýn",
		"fa-IR": "لیختن‌اشتاین",
		"fa-AF": "لیختن‌اشتاین",
		"ps-AF": "لیختن اشتاین",
		"ps-PK": "لیختن اشتاین",
		"he-IL": "ליכטנשטיין",
		"ar-SA": "ليختنشتاين",
		"ar-AE": "ليختنشتاين",
		"ar-QA": "ليختنشتاين",
		"ar-BH": "ليختنشتاين",
		"ar-KW": "ليختنشتاين",
		"ar-OM": "ليختنشتاين",
		"ar-YE": "ليختنشتاين",
		"ar-IQ": "ليختنشتاين",
		"ar-JO": "ليختنشتاين",
		"ar-LB": "ليختنشتاين",
		"ar-SY": "ليختنشتاين",
		"ar-PS": "ليختنشتاين",
		"en-US": "Liechtenstein",
		"en-GB": "Liechtenstein",
		"en-IE": "Liechtenstein",
		"en-MT": "Liechtenstein",
		"en-GI": "Liechtenstein",
		"en-CY": "Liechtenstein",
		"en-JE": "Liechtenstein",
		"en-GG": "Liechtenstein",
		"en-IM": "Liechtenstein",
		"en-CA": "Liechtenstein",
		"en-AU": "Liechtenstein",
		"en-NZ": "Liechtenstein",
		"en-ZA": "Liechtenstein",
		"en-IN": "Liechtenstein",
		"en-SG": "Liechtenstein",
		"pt-AO": "Listenstaine",
		"pt-MZ": "Listenstaine",
		"pt-CV": "Listenstaine",
		"pt-GW": "Listenstaine",
		"pt-ST": "Listenstaine",
		"pt-TL": "Listenstaine",
		"pt-MO": "Listenstaine",
		"es-ES": "Liechtenstein",
		"es-419": "Liechtenstein",
		"es-AD": "Liechtenstein",
		"es-GI": "Liechtenstein",
		"es-AR": "Liechtenstein",
		"es-BO": "Liechtenstein",
		"es-BR": "Liechtenstein",
		"es-BZ": "Liechtenstein",
		"es-CL": "Liechtenstein",
		"es-CO": "Liechtenstein",
		"es-CR": "Liechtenstein",
		"es-CU": "Liechtenstein",
		"es-DO": "Liechtenstein",
		"es-EC": "Liechtenstein",
		"es-GT": "Liechtenstein",
		"es-HN": "Liechtenstein",
		"es-MX": "Liechtenstein",
		"es-NI": "Liechtenstein",
		"es-PA": "Liechtenstein",
		"es-PE": "Liechtenstein",
		"es-PR": "Liechtenstein",
		"es-PY": "Liechtenstein",
		"es-SV": "Liechtenstein",
		"es-US": "Liechtenstein",
		"es-UY": "Liechtenstein",
		"es-VE": "Liechtenstein",
		"fr-FR": "Liechtenstein",
		"fr-BE": "Liechtenstein",
		"fr-CH": "Liechtenstein",
		"fr-LU": "Liechtenstein",
		"fr-MC": "Liechtenstein",
		"fr-AD": "Liechtenstein",
		"fr-CA": "Liechtenstein",
		"it-IT": "Liechtenstein",
		"it-CH": "Liechtenstein",
		"it-SM": "Liechtenstein",
		"it-VA": "Liechtenstein",
		"de-DE": "Liechtenstein",
		"de-AT": "Liechtenstein",
		"de-CH": "Liechtenstein",
		"de-BE": "Liechtenstein",
		"de-LI": "Liechtenstein",
		"de-LU": "Liechtenstein",
		"nl-NL": "Liechtenstein",
		"nl-BE": "Liechtenstein",
		"sv-SE": "Liechtenstein",
		"sv-FI": "Liechtenstein",
		"da-DK": "Liechtenstein",
		"nb-NO": "Liechtenstein",
		"nn-NO": "Liechtenstein",
		"fi-FI": "Liechtenstein",
		"is-IS": "Liechtenstein",
		"fo-FO": "Liktinstein",
		"et-EE": "Liechtenstein",
		"lv-LV": "Lihtenšteina",
		"lt-LT": "Lichtenšteinas",
		"pl-PL": "Liechtenstein",
		"cs-CZ": "Lichtenštejnsko",
		"sk-SK": "Lichtenštajnsko",
		"sl-SI": "Lihtenštajn",
		"hr-HR": "Lihtenštajn",
		"bs-BA": "Lihtenštajn",
		"sr-RS": "Лихтенштајн",
		"sr-BA": "Лихтенштајн",
		"sr-ME": "Lihtenštajn",
		"mk-MK": "Лихтенштајн",
		"bg-BG": "Лихтенщайн",
		"be-BY": "Ліхтэнштэйн",
		"uk-UA": "Ліхтенштейн",
		"ru-RU": "Лихтенштейн",
		"el-GR": "Λιχτενστάιν",
		"el-CY": "Λιχτενστάιν",
		"ro-RO": "Liechtenstein",
		"ro-MD": "Liechtenstein",
		"hu-HU": "Liechtenstein",
		"sq-AL": "Lihtenshtajn",
		"sq-XK": "Lihtenshtajn",
		"mt-MT": "il-Liechtenstein",
		"ga-IE": "Lichtinstéin",
		"cy-GB": "Liechtenstein",
		"gd-GB": "Lichtenstein",
		"lb-LU": "Liechtenstein",
		"ca-ES": "Liechtenstein",
		"ca-AD": "Liechtenstein",
		"ca-FR": "Liechtenstein",
		"ca-IT": "Liechtenstein",
		"eu-ES": "Liechtenstein",
		"eu-FR": "Liechtenstein",
		"gl-ES": "Liechtenstein",
		"tr-TR": "Liechtenstein",
		"tr-CY": "Liechtenstein"
	},
	"callingCode": "423",
	"phoneMasks": [
		{
			"mask": "### ## ##",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2379]|8(?:0[09]|7)",
				"[2379]|8(?:0(?:02|9)|7)"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"69"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"6"
			]
		}
	]
} satisfies Country;
