import type { Country } from './types.js';

export const LKA = {
	"code": "LKA",
	"labels": {
		"pt-BR": "Sri Lanka",
		"pt-PT": "Sri Lanca",
		"es-ES": "Sri Lanka",
		"es-419": "Sri Lanka",
		"es-AR": "Sri Lanka",
		"es-BO": "Sri Lanka",
		"es-BR": "Sri Lanka",
		"es-BZ": "Sri Lanka",
		"es-CL": "Sri Lanka",
		"es-CO": "Sri Lanka",
		"es-CR": "Sri Lanka",
		"es-CU": "Sri Lanka",
		"es-DO": "Sri Lanka",
		"es-EC": "Sri Lanka",
		"es-GT": "Sri Lanka",
		"es-HN": "Sri Lanka",
		"es-MX": "Sri Lanka",
		"es-NI": "Sri Lanka",
		"es-PA": "Sri Lanka",
		"es-PE": "Sri Lanka",
		"es-PR": "Sri Lanka",
		"es-PY": "Sri Lanka",
		"es-SV": "Sri Lanka",
		"es-US": "Sri Lanka",
		"es-UY": "Sri Lanka",
		"es-VE": "Sri Lanka",
		"en-US": "Sri Lanka",
		"fr-FR": "Sri Lanka",
		"fr-BE": "Sri Lanka",
		"fr-CA": "Sri Lanka",
		"fr-CH": "Sri Lanka",
		"fr-LU": "Sri Lanka",
		"fr-MC": "Sri Lanka",
		"it-IT": "Sri Lanka",
		"it-CH": "Sri Lanka",
		"it-SM": "Sri Lanka",
		"it-VA": "Sri Lanka",
		"de-DE": "Sri Lanka",
		"de-AT": "Sri Lanka",
		"de-CH": "Sri Lanka",
		"de-BE": "Sri Lanka",
		"de-LI": "Sri Lanka",
		"de-LU": "Sri Lanka"
	},
	"callingCode": "94"
} satisfies Country;
