import type { Country } from './types.js';

export const LKA = {
	"code": "LKA",
	"labels": {
		"pt-BR": "Sri Lanka",
		"pt-PT": "Sri Lanca",
		"qu-PE": "Sri Lanka",
		"qu-BO": "Sri Lanka",
		"qu-EC": "Sri Lanka",
		"chr-US": "ᏍᎵ ᎳᏂᎧ",
		"hi-IN": "श्रीलंका",
		"bn-IN": "শ্রীলঙ্কা",
		"bn-BD": "শ্রীলঙ্কা",
		"ta-IN": "இலங்கை",
		"ta-LK": "இலங்கை",
		"ta-SG": "இலங்கை",
		"ta-MY": "இலங்கை",
		"te-IN": "శ్రీలంక",
		"mr-IN": "श्रीलंका",
		"gu-IN": "શ્રીલંકા",
		"kn-IN": "ಶ್ರೀಲಂಕಾ",
		"ml-IN": "ശ്രീലങ്ക",
		"pa-IN": "ਸ੍ਰੀ ਲੰਕਾ",
		"ur-IN": "سری لنکا",
		"ur-PK": "سری لنکا",
		"or-IN": "ଶ୍ରୀଲଙ୍କା",
		"as-IN": "শ্রীলংকা",
		"ne-IN": "श्रीलङ्का",
		"ne-NP": "श्रीलङ्का",
		"si-LK": "ශ්‍රී ලංකාව",
		"kok-IN": "श्री लंका",
		"ks-IN": "سری لنکا",
		"brx-IN": "श्रीलंका",
		"mai-IN": "श्रीलंका",
		"dz-BT": "ཤྲཱི་ལང་ཀ",
		"ja-JP": "スリランカ",
		"ko-KR": "스리랑카",
		"ko-KP": "스리랑카",
		"zh-CN": "斯里兰卡",
		"zh-Hans-CN": "斯里兰卡",
		"zh-Hant-TW": "斯里蘭卡",
		"zh-TW": "斯里蘭卡",
		"zh-HK": "斯里蘭卡",
		"zh-MO": "斯里蘭卡",
		"zh-SG": "斯里兰卡",
		"yue-Hant-HK": "斯里蘭卡",
		"yue-Hans-CN": "斯里兰卡",
		"mn-MN": "Шри-Ланка",
		"ug-CN": "سىرىلانكا",
		"th-TH": "ศรีลังกา",
		"lo-LA": "ສີລັງກາ",
		"km-KH": "ស្រីលង្កា",
		"my-MM": "သီရိလင်္ကာ",
		"vi-VN": "Sri Lanka",
		"id-ID": "Sri Lanka",
		"ms-MY": "Sri Lanka",
		"ms-SG": "Sri Lanka",
		"ms-BN": "Sri Lanka",
		"jv-ID": "Sri Lanka",
		"fil-PH": "Sri Lanka",
		"ceb-PH": "Sri Lanka",
		"ka-GE": "შრი-ლანკა",
		"hy-AM": "Շրի Լանկա",
		"az-AZ": "Şri-Lanka",
		"az-Cyrl-AZ": "Шри-Ланка",
		"kk-KZ": "Шри-Ланка",
		"ky-KG": "Шри-Ланка",
		"uz-UZ": "Shri-Lanka",
		"tg-TJ": "Шри-Ланка",
		"tk-TM": "Şri-Lanka",
		"fa-IR": "سری‌لانکا",
		"fa-AF": "سریلانکا",
		"ps-AF": "سريلنکا",
		"ps-PK": "سريلنکا",
		"he-IL": "סרי לנקה",
		"ar-SA": "سريلانكا",
		"ar-AE": "سريلانكا",
		"ar-QA": "سريلانكا",
		"ar-BH": "سريلانكا",
		"ar-KW": "سريلانكا",
		"ar-OM": "سريلانكا",
		"ar-YE": "سريلانكا",
		"ar-IQ": "سريلانكا",
		"ar-JO": "سريلانكا",
		"ar-LB": "سريلانكا",
		"ar-SY": "سريلانكا",
		"ar-PS": "سريلانكا",
		"en-US": "Sri Lanka",
		"en-GB": "Sri Lanka",
		"en-IE": "Sri Lanka",
		"en-MT": "Sri Lanka",
		"en-GI": "Sri Lanka",
		"en-CY": "Sri Lanka",
		"en-JE": "Sri Lanka",
		"en-GG": "Sri Lanka",
		"en-IM": "Sri Lanka",
		"en-CA": "Sri Lanka",
		"en-AU": "Sri Lanka",
		"en-NZ": "Sri Lanka",
		"en-ZA": "Sri Lanka",
		"en-IN": "Sri Lanka",
		"en-SG": "Sri Lanka",
		"pt-AO": "Sri Lanca",
		"pt-MZ": "Sri Lanca",
		"pt-CV": "Sri Lanca",
		"pt-GW": "Sri Lanca",
		"pt-ST": "Sri Lanca",
		"pt-TL": "Sri Lanca",
		"pt-MO": "Sri Lanca",
		"es-ES": "Sri Lanka",
		"es-419": "Sri Lanka",
		"es-AD": "Sri Lanka",
		"es-GI": "Sri Lanka",
		"es-AR": "Sri Lanka",
		"es-BO": "Sri Lanka",
		"es-BR": "Sri Lanka",
		"es-BZ": "Sri Lanka",
		"es-CL": "Sri Lanka",
		"es-CO": "Sri Lanka",
		"es-CR": "Sri Lanka",
		"es-CU": "Sri Lanka",
		"es-DO": "Sri Lanka",
		"es-EC": "Sri Lanka",
		"es-GT": "Sri Lanka",
		"es-HN": "Sri Lanka",
		"es-MX": "Sri Lanka",
		"es-NI": "Sri Lanka",
		"es-PA": "Sri Lanka",
		"es-PE": "Sri Lanka",
		"es-PR": "Sri Lanka",
		"es-PY": "Sri Lanka",
		"es-SV": "Sri Lanka",
		"es-US": "Sri Lanka",
		"es-UY": "Sri Lanka",
		"es-VE": "Sri Lanka",
		"fr-FR": "Sri Lanka",
		"fr-BE": "Sri Lanka",
		"fr-CH": "Sri Lanka",
		"fr-LU": "Sri Lanka",
		"fr-MC": "Sri Lanka",
		"fr-AD": "Sri Lanka",
		"fr-CA": "Sri Lanka",
		"it-IT": "Sri Lanka",
		"it-CH": "Sri Lanka",
		"it-SM": "Sri Lanka",
		"it-VA": "Sri Lanka",
		"de-DE": "Sri Lanka",
		"de-AT": "Sri Lanka",
		"de-CH": "Sri Lanka",
		"de-BE": "Sri Lanka",
		"de-LI": "Sri Lanka",
		"de-LU": "Sri Lanka",
		"nl-NL": "Sri Lanka",
		"nl-BE": "Sri Lanka",
		"sv-SE": "Sri Lanka",
		"sv-FI": "Sri Lanka",
		"da-DK": "Sri Lanka",
		"nb-NO": "Sri Lanka",
		"nn-NO": "Sri Lanka",
		"fi-FI": "Sri Lanka",
		"is-IS": "Srí Lanka",
		"fo-FO": "Sri Lanka",
		"et-EE": "Sri Lanka",
		"lv-LV": "Šrilanka",
		"lt-LT": "Šri Lanka",
		"pl-PL": "Sri Lanka",
		"cs-CZ": "Srí Lanka",
		"sk-SK": "Srí Lanka",
		"sl-SI": "Šrilanka",
		"hr-HR": "Šri Lanka",
		"bs-BA": "Šri Lanka",
		"sr-RS": "Шри Ланка",
		"sr-BA": "Шри Ланка",
		"sr-ME": "Šri Lanka",
		"mk-MK": "Шри Ланка",
		"bg-BG": "Шри Ланка",
		"be-BY": "Шры-Ланка",
		"uk-UA": "Шрі-Ланка",
		"ru-RU": "Шри-Ланка",
		"el-GR": "Σρι Λάνκα",
		"el-CY": "Σρι Λάνκα",
		"ro-RO": "Sri Lanka",
		"ro-MD": "Sri Lanka",
		"hu-HU": "Srí Lanka",
		"sq-AL": "Sri-Lankë",
		"sq-XK": "Sri-Lankë",
		"mt-MT": "is-Sri Lanka",
		"ga-IE": "Srí Lanca",
		"cy-GB": "Sri Lanka",
		"gd-GB": "Sri Lanca",
		"lb-LU": "Sri Lanka",
		"ca-ES": "Sri Lanka",
		"ca-AD": "Sri Lanka",
		"ca-FR": "Sri Lanka",
		"ca-IT": "Sri Lanka",
		"eu-ES": "Sri Lanka",
		"eu-FR": "Sri Lanka",
		"gl-ES": "Sri Lanka",
		"tr-TR": "Sri Lanka",
		"tr-CY": "Sri Lanka"
	},
	"callingCode": "94",
	"phoneMasks": [
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"7"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[1-689]"
			]
		}
	]
} satisfies Country;
