import type { Country } from './types.js';

export const LTU = {
	"code": "LTU",
	"labels": {
		"pt-BR": "Lituânia",
		"pt-PT": "Lituânia",
		"es-ES": "Lituania",
		"es-419": "Lituania",
		"es-AR": "Lituania",
		"es-BO": "Lituania",
		"es-BR": "Lituania",
		"es-BZ": "Lituania",
		"es-CL": "Lituania",
		"es-CO": "Lituania",
		"es-CR": "Lituania",
		"es-CU": "Lituania",
		"es-DO": "Lituania",
		"es-EC": "Lituania",
		"es-GT": "Lituania",
		"es-HN": "Lituania",
		"es-MX": "Lituania",
		"es-NI": "Lituania",
		"es-PA": "Lituania",
		"es-PE": "Lituania",
		"es-PR": "Lituania",
		"es-PY": "Lituania",
		"es-SV": "Lituania",
		"es-US": "Lituania",
		"es-UY": "Lituania",
		"es-VE": "Lituania",
		"en-US": "Lithuania",
		"fr-FR": "Lituanie",
		"fr-BE": "Lituanie",
		"fr-CA": "Lituanie",
		"fr-CH": "Lituanie",
		"fr-LU": "Lituanie",
		"fr-MC": "Lituanie",
		"it-IT": "Lituania",
		"it-CH": "Lituania",
		"it-SM": "Lituania",
		"it-VA": "Lituania",
		"de-DE": "Litauen",
		"de-AT": "Litauen",
		"de-CH": "Litauen",
		"de-BE": "Litauen",
		"de-LI": "Litauen",
		"de-LU": "Litauen"
	}
} satisfies Country;
