import type { Country } from './types.js';

export const LTU = {
	"code": "LTU",
	"labels": {
		"pt-BR": "Lituânia",
		"pt-PT": "Lituânia",
		"qu-PE": "Lituania",
		"qu-BO": "Lituania",
		"qu-EC": "Lituania",
		"chr-US": "ᎵᏗᏪᏂᎠ",
		"hi-IN": "लिथुआनिया",
		"bn-IN": "লিথুয়ানিয়া",
		"bn-BD": "লিথুয়ানিয়া",
		"ta-IN": "லிதுவேனியா",
		"ta-LK": "லிதுவேனியா",
		"ta-SG": "லிதுவேனியா",
		"ta-MY": "லிதுவேனியா",
		"te-IN": "లిథువేనియా",
		"mr-IN": "लिथुआनिया",
		"gu-IN": "લિથુઆનિયા",
		"kn-IN": "ಲಿಥುವೇನಿಯಾ",
		"ml-IN": "ലിത്വാനിയ",
		"pa-IN": "ਲਿਥੁਆਨੀਆ",
		"ur-IN": "لیتھونیا",
		"ur-PK": "لیتھونیا",
		"or-IN": "ଲିଥୁଆନିଆ",
		"as-IN": "লিথুৱানিয়া",
		"ne-IN": "लिथुएनिया",
		"ne-NP": "लिथुएनिया",
		"si-LK": "ලිතුවේනියාව",
		"kok-IN": "लिथुआनिया",
		"ks-IN": "لِتھُوانِیا",
		"brx-IN": "लिथुआनिया",
		"mai-IN": "लिथुआनिया",
		"dz-BT": "ལི་ཐུ་ཝེ་ནི་ཡ",
		"ja-JP": "リトアニア",
		"ko-KR": "리투아니아",
		"ko-KP": "리투아니아",
		"zh-CN": "立陶宛",
		"zh-Hans-CN": "立陶宛",
		"zh-Hant-TW": "立陶宛",
		"zh-TW": "立陶宛",
		"zh-HK": "立陶宛",
		"zh-MO": "立陶宛",
		"zh-SG": "立陶宛",
		"yue-Hant-HK": "立陶宛",
		"yue-Hans-CN": "立陶宛",
		"mn-MN": "Литва",
		"ug-CN": "لىتۋانىيە",
		"th-TH": "ลิทัวเนีย",
		"lo-LA": "ລິທົວເນຍ",
		"km-KH": "លីទុយអានី",
		"my-MM": "လစ်သူဝေးနီးယား",
		"vi-VN": "Litva",
		"id-ID": "Lituania",
		"ms-MY": "Lithuania",
		"ms-SG": "Lithuania",
		"ms-BN": "Lithuania",
		"jv-ID": "Litowen",
		"fil-PH": "Lithuania",
		"ceb-PH": "Lithuania",
		"ka-GE": "ლიეტუვა",
		"hy-AM": "Լիտվա",
		"az-AZ": "Litva",
		"az-Cyrl-AZ": "Литва",
		"kk-KZ": "Литва",
		"ky-KG": "Литва",
		"uz-UZ": "Litva",
		"tg-TJ": "Литва",
		"tk-TM": "Litwa",
		"fa-IR": "لیتوانی",
		"fa-AF": "لتوانیا",
		"ps-AF": "لیتوانیا",
		"ps-PK": "لیتوانیا",
		"he-IL": "ליטא",
		"ar-SA": "ليتوانيا",
		"ar-AE": "ليتوانيا",
		"ar-QA": "ليتوانيا",
		"ar-BH": "ليتوانيا",
		"ar-KW": "ليتوانيا",
		"ar-OM": "ليتوانيا",
		"ar-YE": "ليتوانيا",
		"ar-IQ": "ليتوانيا",
		"ar-JO": "ليتوانيا",
		"ar-LB": "ليتوانيا",
		"ar-SY": "ليتوانيا",
		"ar-PS": "ليتوانيا",
		"en-US": "Lithuania",
		"en-GB": "Lithuania",
		"en-IE": "Lithuania",
		"en-MT": "Lithuania",
		"en-GI": "Lithuania",
		"en-CY": "Lithuania",
		"en-JE": "Lithuania",
		"en-GG": "Lithuania",
		"en-IM": "Lithuania",
		"en-CA": "Lithuania",
		"en-AU": "Lithuania",
		"en-NZ": "Lithuania",
		"en-ZA": "Lithuania",
		"en-IN": "Lithuania",
		"en-SG": "Lithuania",
		"pt-AO": "Lituânia",
		"pt-MZ": "Lituânia",
		"pt-CV": "Lituânia",
		"pt-GW": "Lituânia",
		"pt-ST": "Lituânia",
		"pt-TL": "Lituânia",
		"pt-MO": "Lituânia",
		"es-ES": "Lituania",
		"es-419": "Lituania",
		"es-AD": "Lituania",
		"es-GI": "Lituania",
		"es-AR": "Lituania",
		"es-BO": "Lituania",
		"es-BR": "Lituania",
		"es-BZ": "Lituania",
		"es-CL": "Lituania",
		"es-CO": "Lituania",
		"es-CR": "Lituania",
		"es-CU": "Lituania",
		"es-DO": "Lituania",
		"es-EC": "Lituania",
		"es-GT": "Lituania",
		"es-HN": "Lituania",
		"es-MX": "Lituania",
		"es-NI": "Lituania",
		"es-PA": "Lituania",
		"es-PE": "Lituania",
		"es-PR": "Lituania",
		"es-PY": "Lituania",
		"es-SV": "Lituania",
		"es-US": "Lituania",
		"es-UY": "Lituania",
		"es-VE": "Lituania",
		"fr-FR": "Lituanie",
		"fr-BE": "Lituanie",
		"fr-CH": "Lituanie",
		"fr-LU": "Lituanie",
		"fr-MC": "Lituanie",
		"fr-AD": "Lituanie",
		"fr-CA": "Lituanie",
		"it-IT": "Lituania",
		"it-CH": "Lituania",
		"it-SM": "Lituania",
		"it-VA": "Lituania",
		"de-DE": "Litauen",
		"de-AT": "Litauen",
		"de-CH": "Litauen",
		"de-BE": "Litauen",
		"de-LI": "Litauen",
		"de-LU": "Litauen",
		"nl-NL": "Litouwen",
		"nl-BE": "Litouwen",
		"sv-SE": "Litauen",
		"sv-FI": "Litauen",
		"da-DK": "Litauen",
		"nb-NO": "Litauen",
		"nn-NO": "Litauen",
		"fi-FI": "Liettua",
		"is-IS": "Litháen",
		"fo-FO": "Litava",
		"et-EE": "Leedu",
		"lv-LV": "Lietuva",
		"lt-LT": "Lietuva",
		"pl-PL": "Litwa",
		"cs-CZ": "Litva",
		"sk-SK": "Litva",
		"sl-SI": "Litva",
		"hr-HR": "Litva",
		"bs-BA": "Litvanija",
		"sr-RS": "Литванија",
		"sr-BA": "Литванија",
		"sr-ME": "Litvanija",
		"mk-MK": "Литванија",
		"bg-BG": "Литва",
		"be-BY": "Літва",
		"uk-UA": "Литва",
		"ru-RU": "Литва",
		"el-GR": "Λιθουανία",
		"el-CY": "Λιθουανία",
		"ro-RO": "Lituania",
		"ro-MD": "Lituania",
		"hu-HU": "Litvánia",
		"sq-AL": "Lituani",
		"sq-XK": "Lituani",
		"mt-MT": "il-Litwanja",
		"ga-IE": "an Liotuáin",
		"cy-GB": "Lithwania",
		"gd-GB": "An Liotuain",
		"lb-LU": "Litauen",
		"ca-ES": "Lituània",
		"ca-AD": "Lituània",
		"ca-FR": "Lituània",
		"ca-IT": "Lituània",
		"eu-ES": "Lituania",
		"eu-FR": "Lituania",
		"gl-ES": "Lituania",
		"tr-TR": "Litvanya",
		"tr-CY": "Litvanya"
	},
	"callingCode": "370",
	"phoneMasks": [
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"52[0-7]"
			]
		},
		{
			"mask": "## ######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"37|4(?:[15]|6[1-8])"
			]
		},
		{
			"mask": "### ## ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[7-9]"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[3-6]"
			]
		}
	]
} satisfies Country;
