import type { Country } from './types.js';

export const LUX = {
	"code": "LUX",
	"labels": {
		"pt-BR": "Luxemburgo",
		"pt-PT": "Luxemburgo",
		"es-ES": "Luxemburgo",
		"es-419": "Luxemburgo",
		"es-AR": "Luxemburgo",
		"es-BO": "Luxemburgo",
		"es-BR": "Luxemburgo",
		"es-BZ": "Luxemburgo",
		"es-CL": "Luxemburgo",
		"es-CO": "Luxemburgo",
		"es-CR": "Luxemburgo",
		"es-CU": "Luxemburgo",
		"es-DO": "Luxemburgo",
		"es-EC": "Luxemburgo",
		"es-GT": "Luxemburgo",
		"es-HN": "Luxemburgo",
		"es-MX": "Luxemburgo",
		"es-NI": "Luxemburgo",
		"es-PA": "Luxemburgo",
		"es-PE": "Luxemburgo",
		"es-PR": "Luxemburgo",
		"es-PY": "Luxemburgo",
		"es-SV": "Luxemburgo",
		"es-US": "Luxemburgo",
		"es-UY": "Luxemburgo",
		"es-VE": "Luxemburgo",
		"en-US": "Luxembourg",
		"fr-FR": "Luxembourg",
		"fr-BE": "Luxembourg",
		"fr-CA": "Luxembourg",
		"fr-CH": "Luxembourg",
		"fr-LU": "Luxembourg",
		"fr-MC": "Luxembourg",
		"it-IT": "Lussemburgo",
		"it-CH": "Lussemburgo",
		"it-SM": "Lussemburgo",
		"it-VA": "Lussemburgo",
		"de-DE": "Luxemburg",
		"de-AT": "Luxemburg",
		"de-CH": "Luxemburg",
		"de-BE": "Luxemburg",
		"de-LI": "Luxemburg",
		"de-LU": "Luxemburg"
	},
	"callingCode": "352"
} satisfies Country;
