import type { Country } from './types.js';

export const LVA = {
	"code": "LVA",
	"labels": {
		"pt-BR": "Letônia",
		"pt-PT": "Letónia",
		"es-ES": "Letonia",
		"es-419": "Letonia",
		"es-AR": "Letonia",
		"es-BO": "Letonia",
		"es-BR": "Letonia",
		"es-BZ": "Letonia",
		"es-CL": "Letonia",
		"es-CO": "Letonia",
		"es-CR": "Letonia",
		"es-CU": "Letonia",
		"es-DO": "Letonia",
		"es-EC": "Letonia",
		"es-GT": "Letonia",
		"es-HN": "Letonia",
		"es-MX": "Letonia",
		"es-NI": "Letonia",
		"es-PA": "Letonia",
		"es-PE": "Letonia",
		"es-PR": "Letonia",
		"es-PY": "Letonia",
		"es-SV": "Letonia",
		"es-US": "Letonia",
		"es-UY": "Letonia",
		"es-VE": "Letonia",
		"en-US": "Latvia",
		"fr-FR": "Lettonie",
		"fr-BE": "Lettonie",
		"fr-CA": "Lettonie",
		"fr-CH": "Lettonie",
		"fr-LU": "Lettonie",
		"fr-MC": "Lettonie",
		"it-IT": "Lettonia",
		"it-CH": "Lettonia",
		"it-SM": "Lettonia",
		"it-VA": "Lettonia",
		"de-DE": "Lettland",
		"de-AT": "Lettland",
		"de-CH": "Lettland",
		"de-BE": "Lettland",
		"de-LI": "Lettland",
		"de-LU": "Lettland"
	}
} satisfies Country;
