import type { Country } from './types.js';

export const MAC = {
	"code": "MAC",
	"labels": {
		"pt-BR": "Macau, RAE da China",
		"pt-PT": "Macau, RAE da China",
		"es-ES": "RAE de Macao (China)",
		"es-419": "RAE de Macao (China)",
		"es-AR": "RAE de Macao (China)",
		"es-BO": "RAE de Macao (China)",
		"es-BR": "RAE de Macao (China)",
		"es-BZ": "RAE de Macao (China)",
		"es-CL": "RAE de Macao (China)",
		"es-CO": "RAE de Macao (China)",
		"es-CR": "RAE de Macao (China)",
		"es-CU": "RAE de Macao (China)",
		"es-DO": "RAE de Macao (China)",
		"es-EC": "RAE de Macao (China)",
		"es-GT": "RAE de Macao (China)",
		"es-HN": "RAE de Macao (China)",
		"es-MX": "RAE de Macao (China)",
		"es-NI": "RAE de Macao (China)",
		"es-PA": "RAE de Macao (China)",
		"es-PE": "RAE de Macao (China)",
		"es-PR": "RAE de Macao (China)",
		"es-PY": "RAE de Macao (China)",
		"es-SV": "RAE de Macao (China)",
		"es-US": "RAE de Macao (China)",
		"es-UY": "RAE de Macao (China)",
		"es-VE": "RAE de Macao (China)",
		"en-US": "Macao SAR China",
		"fr-FR": "R.A.S. chinoise de Macao",
		"fr-BE": "R.A.S. chinoise de Macao",
		"fr-CA": "R.A.S. chinoise de Macao",
		"fr-CH": "R.A.S. chinoise de Macao",
		"fr-LU": "R.A.S. chinoise de Macao",
		"fr-MC": "R.A.S. chinoise de Macao",
		"it-IT": "RAS di Macao",
		"it-CH": "RAS di Macao",
		"it-SM": "RAS di Macao",
		"it-VA": "RAS di Macao",
		"de-DE": "Sonderverwaltungsregion Macau",
		"de-AT": "Sonderverwaltungsregion Macau",
		"de-CH": "Sonderverwaltungsregion Macau",
		"de-BE": "Sonderverwaltungsregion Macau",
		"de-LI": "Sonderverwaltungsregion Macau",
		"de-LU": "Sonderverwaltungsregion Macau"
	},
	"callingCode": "853"
} satisfies Country;
