import type { Country } from './types.js';

export const MAC = {
	"code": "MAC",
	"labels": {
		"pt-BR": "Macau, RAE da China",
		"pt-PT": "Macau, RAE da China",
		"qu-PE": "Macao RAE China",
		"qu-BO": "Macao RAE China",
		"qu-EC": "Macao RAE China",
		"chr-US": "ᎹᎧᎣ (ᎤᏓᏤᎵᏓ ᏧᏂᎸᏫᏍᏓᏁᏗ ᎢᎬᎾᏕᎾ) ᏣᎢ",
		"hi-IN": "मकाऊ (विशेष प्रशासनिक क्षेत्र चीन)",
		"bn-IN": "ম্যাকাও এসএআর চীন",
		"bn-BD": "ম্যাকাও এসএআর চীন",
		"ta-IN": "மகாவ் எஸ்ஏஆர் சீனா",
		"ta-LK": "மகாவ் எஸ்ஏஆர் சீனா",
		"ta-SG": "மகாவ் எஸ்ஏஆர் சீனா",
		"ta-MY": "மகாவ் எஸ்ஏஆர் சீனா",
		"te-IN": "మకావ్ ఎస్ఏఆర్ చైనా",
		"mr-IN": "मकाओ एसएआर चीन",
		"gu-IN": "મકાઉ SAR ચીન",
		"kn-IN": "ಮಕಾವು ಎಸ್ಎಆರ್ ಚೈನಾ",
		"ml-IN": "മക്കാവു എസ്.എ.ആർ. ചൈന",
		"pa-IN": "ਮਕਾਉ ਐਸਏਆਰ ਚੀਨ",
		"ur-IN": "مکاؤ SAR چین",
		"ur-PK": "مکاؤ SAR چین",
		"or-IN": "ମାକାଉ ଏସଏଆର୍‌ ଚାଇନା",
		"as-IN": "মাকাও এছ. এ. আৰ. চীন",
		"ne-IN": "मकाउ चिनियाँ विशेष प्रशासनिक क्षेत्र",
		"ne-NP": "मकाउ चिनियाँ विशेष प्रशासनिक क्षेत्र",
		"si-LK": "මැකාවු විශේෂ පරිපාලන කලාපය චීනය",
		"kok-IN": "मकाव एसएआर चीन",
		"ks-IN": "مَکاوو ایس اے آر چیٖن",
		"brx-IN": "माकाउ एस.ए.आर चाइना",
		"mai-IN": "मकाउ (विशेष प्रशासनिक क्षेत्र चीन)",
		"dz-BT": "མཀ་ཨའུ་ཅཱའི་ན",
		"ja-JP": "中華人民共和国マカオ特別行政区",
		"ko-KR": "마카오(중국 특별행정구)",
		"ko-KP": "마카오(중국 특별행정구)",
		"zh-CN": "中国澳门特别行政区",
		"zh-Hans-CN": "中国澳门特别行政区",
		"zh-Hant-TW": "中國澳門特別行政區",
		"zh-TW": "中國澳門特別行政區",
		"zh-HK": "中國澳門特別行政區",
		"zh-MO": "中國澳門特別行政區",
		"zh-SG": "中国澳门特别行政区",
		"yue-Hant-HK": "中國澳門特別行政區",
		"yue-Hans-CN": "中华人民共和国澳门特别行政区",
		"mn-MN": "БНХАУ-ын Тусгай захиргааны бүс Макао",
		"ug-CN": "ئاۋمېن ئالاھىدە مەمۇرىي رايونى",
		"th-TH": "เขตปกครองพิเศษมาเก๊าแห่งสาธารณรัฐประชาชนจีน",
		"lo-LA": "ມາກາວ ເຂດປົກຄອງພິເສດ ຈີນ",
		"km-KH": "ម៉ាកាវ តំបន់រដ្ឋបាលពិសេសចិន",
		"my-MM": "မကာအို (တရုတ်ပြည်)",
		"vi-VN": "Đặc khu Hành chính Macao, Trung Quốc",
		"id-ID": "Makau DAK Tiongkok",
		"ms-MY": "Macau SAR China",
		"ms-SG": "Macau SAR China",
		"ms-BN": "Macau SAR China",
		"jv-ID": "Laladan Administratif Astamiwa Makau",
		"fil-PH": "Macau SAR China",
		"ceb-PH": "Macao SAR China",
		"ka-GE": "მაკაოს სპეციალური ადმინისტრაციული რეგიონი, ჩინეთი",
		"hy-AM": "Չինաստանի Մակաո ՀՎՇ",
		"az-AZ": "Makao XİR Çin",
		"az-Cyrl-AZ": "Макао Хүсуси Инзибати Әрази Чин",
		"kk-KZ": "Макао АӘА",
		"ky-KG": "Макао Кытай ААА",
		"uz-UZ": "Makao (Xitoy MMH)",
		"tg-TJ": "Макао (МММ)",
		"tk-TM": "Makao AAS Hytaý",
		"fa-IR": "ماکائو، منطقهٔ ویژهٔ اداری چین",
		"fa-AF": "ماکائو، منطقهٔ ویژهٔ اداری چین",
		"ps-AF": "مکاو SAR چین",
		"ps-PK": "مکاو SAR چین",
		"he-IL": "מקאו (אזור מנהלי מיוחד של סין)",
		"ar-SA": "ماكاو الصينية (منطقة إدارية خاصة)",
		"ar-AE": "منطقة ماكاو الإدارية الخاصة",
		"ar-QA": "منطقة ماكاو الإدارية الخاصة",
		"ar-BH": "منطقة ماكاو الإدارية الخاصة",
		"ar-KW": "منطقة ماكاو الإدارية الخاصة",
		"ar-OM": "منطقة ماكاو الإدارية الخاصة",
		"ar-YE": "منطقة ماكاو الإدارية الخاصة",
		"ar-IQ": "منطقة ماكاو الإدارية الخاصة",
		"ar-JO": "منطقة ماكاو الإدارية الخاصة",
		"ar-LB": "منطقة ماكاو الإدارية الخاصة",
		"ar-SY": "منطقة ماكاو الإدارية الخاصة",
		"ar-PS": "منطقة ماكاو الإدارية الخاصة",
		"en-US": "Macao SAR China",
		"en-GB": "Macao SAR China",
		"en-IE": "Macao SAR China",
		"en-MT": "Macao SAR China",
		"en-GI": "Macao SAR China",
		"en-CY": "Macao SAR China",
		"en-JE": "Macao SAR China",
		"en-GG": "Macao SAR China",
		"en-IM": "Macao SAR China",
		"en-CA": "Macao SAR China",
		"en-AU": "Macao SAR China",
		"en-NZ": "Macao SAR China",
		"en-ZA": "Macao SAR China",
		"en-IN": "Macao SAR China",
		"en-SG": "Macao SAR China",
		"pt-AO": "Macau, RAE da China",
		"pt-MZ": "Macau, RAE da China",
		"pt-CV": "Macau, RAE da China",
		"pt-GW": "Macau, RAE da China",
		"pt-ST": "Macau, RAE da China",
		"pt-TL": "Macau, RAE da China",
		"pt-MO": "Macau, RAE da China",
		"es-ES": "RAE de Macao (China)",
		"es-419": "RAE de Macao (China)",
		"es-AD": "RAE de Macao (China)",
		"es-GI": "RAE de Macao (China)",
		"es-AR": "RAE de Macao (China)",
		"es-BO": "RAE de Macao (China)",
		"es-BR": "RAE de Macao (China)",
		"es-BZ": "RAE de Macao (China)",
		"es-CL": "RAE de Macao (China)",
		"es-CO": "RAE de Macao (China)",
		"es-CR": "RAE de Macao (China)",
		"es-CU": "RAE de Macao (China)",
		"es-DO": "RAE de Macao (China)",
		"es-EC": "RAE de Macao (China)",
		"es-GT": "RAE de Macao (China)",
		"es-HN": "RAE de Macao (China)",
		"es-MX": "RAE de Macao (China)",
		"es-NI": "RAE de Macao (China)",
		"es-PA": "RAE de Macao (China)",
		"es-PE": "RAE de Macao (China)",
		"es-PR": "RAE de Macao (China)",
		"es-PY": "RAE de Macao (China)",
		"es-SV": "RAE de Macao (China)",
		"es-US": "RAE de Macao (China)",
		"es-UY": "RAE de Macao (China)",
		"es-VE": "RAE de Macao (China)",
		"fr-FR": "R.A.S. chinoise de Macao",
		"fr-BE": "R.A.S. chinoise de Macao",
		"fr-CH": "R.A.S. chinoise de Macao",
		"fr-LU": "R.A.S. chinoise de Macao",
		"fr-MC": "R.A.S. chinoise de Macao",
		"fr-AD": "R.A.S. chinoise de Macao",
		"fr-CA": "R.A.S. chinoise de Macao",
		"it-IT": "RAS di Macao",
		"it-CH": "RAS di Macao",
		"it-SM": "RAS di Macao",
		"it-VA": "RAS di Macao",
		"de-DE": "Sonderverwaltungsregion Macau",
		"de-AT": "Sonderverwaltungsregion Macau",
		"de-CH": "Sonderverwaltungsregion Macau",
		"de-BE": "Sonderverwaltungsregion Macau",
		"de-LI": "Sonderverwaltungsregion Macau",
		"de-LU": "Sonderverwaltungsregion Macau",
		"nl-NL": "Macau SAR van China",
		"nl-BE": "Macau SAR van China",
		"sv-SE": "Macao SAR",
		"sv-FI": "Macao SAR",
		"da-DK": "SAR Macao",
		"nb-NO": "Macao SAR Kina",
		"nn-NO": "Macao SAR Kina",
		"fi-FI": "Macao – Kiinan erityishallintoalue",
		"is-IS": "sérstjórnarsvæðið Makaó",
		"fo-FO": "Makao SAR Kina",
		"et-EE": "Macau erihalduspiirkond",
		"lv-LV": "ĶTR īpašais administratīvais reģions Makao",
		"lt-LT": "Ypatingasis Administracinis Kinijos Regionas Makao",
		"pl-PL": "SRA Makau (Chiny)",
		"cs-CZ": "Macao – ZAO Číny",
		"sk-SK": "Macao – OAO Číny",
		"sl-SI": "Posebno upravno območje Ljudske republike Kitajske Macao",
		"hr-HR": "PUP Makao Kina",
		"bs-BA": "Makao (SAR Kina)",
		"sr-RS": "САР Макао (Кина)",
		"sr-BA": "САР Макао (Кина)",
		"sr-ME": "SAR Makao (Kina)",
		"mk-MK": "Макао САР",
		"bg-BG": "Макао, САР на Китай",
		"be-BY": "Макаа, САР (Кітай)",
		"uk-UA": "Макао, ОАР Китаю",
		"ru-RU": "Макао (САР)",
		"el-GR": "Μακάο ΕΔΠ Κίνας",
		"el-CY": "Μακάο ΕΔΠ Κίνας",
		"ro-RO": "R.A.S. Macao, China",
		"ro-MD": "R.A.S. Macao, China",
		"hu-HU": "Makaó KKT",
		"sq-AL": "RPA i Makaos",
		"sq-XK": "RPA i Makaos",
		"mt-MT": "ir-Reġjun Amministrattiv Speċjali tal-Macao tar-Repubblika tal-Poplu taċ-Ċina",
		"ga-IE": "Sainréigiún Riaracháin Macao, Daonphoblacht na Síne",
		"cy-GB": "Macau SAR Tsieina",
		"gd-GB": "Macàthu SAR na Sìne",
		"lb-LU": "Spezialverwaltungszon Macau",
		"ca-ES": "Macau (RAE Xina)",
		"ca-AD": "Macau (RAE Xina)",
		"ca-FR": "Macau (RAE Xina)",
		"ca-IT": "Macau (RAE Xina)",
		"eu-ES": "Macau Txinako AEB",
		"eu-FR": "Macau Txinako AEB",
		"gl-ES": "Macau RAE da China",
		"tr-TR": "Çin Makao ÖİB",
		"tr-CY": "Çin Makao ÖİB"
	},
	"callingCode": "853",
	"phoneMasks": [
		{
			"mask": "#### ###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"0"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[268]"
			]
		}
	]
} satisfies Country;
