import type { Country } from './types.js';

export const MAF = {
	"code": "MAF",
	"labels": {
		"pt-BR": "São Martinho",
		"pt-PT": "São Martinho (Saint-Martin)",
		"es-ES": "San Martín",
		"es-419": "San Martín",
		"es-AR": "San Martín",
		"es-BO": "San Martín",
		"es-BR": "San Martín",
		"es-BZ": "San Martín",
		"es-CL": "San Martín",
		"es-CO": "San Martín",
		"es-CR": "San Martín",
		"es-CU": "San Martín",
		"es-DO": "San Martín",
		"es-EC": "San Martín",
		"es-GT": "San Martín",
		"es-HN": "San Martín",
		"es-MX": "San Martín",
		"es-NI": "San Martín",
		"es-PA": "San Martín",
		"es-PE": "San Martín",
		"es-PR": "San Martín",
		"es-PY": "San Martín",
		"es-SV": "San Martín",
		"es-US": "San Martín",
		"es-UY": "San Martín",
		"es-VE": "San Martín",
		"en-US": "St. Martin",
		"fr-FR": "Saint-Martin",
		"fr-BE": "Saint-Martin",
		"fr-CA": "Saint-Martin (France)",
		"fr-CH": "Saint-Martin",
		"fr-LU": "Saint-Martin",
		"fr-MC": "Saint-Martin",
		"it-IT": "Saint Martin",
		"it-CH": "Saint Martin",
		"it-SM": "Saint Martin",
		"it-VA": "Saint Martin",
		"de-DE": "St. Martin",
		"de-AT": "St. Martin",
		"de-CH": "St. Martin",
		"de-BE": "St. Martin",
		"de-LI": "St. Martin",
		"de-LU": "St. Martin"
	},
	"callingCode": "590"
} satisfies Country;
