import type { Country } from './types.js';

export const MAR = {
	"code": "MAR",
	"labels": {
		"pt-BR": "Marrocos",
		"pt-PT": "Marrocos",
		"qu-PE": "Marruecos",
		"qu-BO": "Marruecos",
		"qu-EC": "Marruecos",
		"chr-US": "ᎼᎶᎪ",
		"hi-IN": "मोरक्को",
		"bn-IN": "মোরক্কো",
		"bn-BD": "মোরক্কো",
		"ta-IN": "மொராக்கோ",
		"ta-LK": "மொராக்கோ",
		"ta-SG": "மொராக்கோ",
		"ta-MY": "மொராக்கோ",
		"te-IN": "మొరాకో",
		"mr-IN": "मोरोक्को",
		"gu-IN": "મોરોક્કો",
		"kn-IN": "ಮೊರಾಕ್ಕೊ",
		"ml-IN": "മൊറോക്കൊ",
		"pa-IN": "ਮੋਰੱਕੋ",
		"ur-IN": "مراکش",
		"ur-PK": "مراکش",
		"or-IN": "ମୋରୋକ୍କୋ",
		"as-IN": "মৰক্কো",
		"ne-IN": "मोरोक्को",
		"ne-NP": "मोरोक्को",
		"si-LK": "මොරොක්කෝව",
		"kok-IN": "मोरोक्को",
		"ks-IN": "موروکو",
		"brx-IN": "मरक्क’",
		"mai-IN": "मोरोक्को",
		"dz-BT": "མོ་རོ་ཀོ",
		"ja-JP": "モロッコ",
		"ko-KR": "모로코",
		"ko-KP": "모로코",
		"zh-CN": "摩洛哥",
		"zh-Hans-CN": "摩洛哥",
		"zh-Hant-TW": "摩洛哥",
		"zh-TW": "摩洛哥",
		"zh-HK": "摩洛哥",
		"zh-MO": "摩洛哥",
		"zh-SG": "摩洛哥",
		"yue-Hant-HK": "摩洛哥",
		"yue-Hans-CN": "摩洛哥",
		"mn-MN": "Морокко",
		"ug-CN": "ماراكەش",
		"th-TH": "โมร็อกโก",
		"lo-LA": "ໂມຣັອກໂຄ",
		"km-KH": "ម៉ារ៉ុក",
		"my-MM": "မော်ရိုကို",
		"vi-VN": "Ma-rốc",
		"id-ID": "Maroko",
		"ms-MY": "Maghribi",
		"ms-SG": "Maghribi",
		"ms-BN": "Maghribi",
		"jv-ID": "Maroko",
		"fil-PH": "Morocco",
		"ceb-PH": "Morocco",
		"ka-GE": "მაროკო",
		"hy-AM": "Մարոկկո",
		"az-AZ": "Mərakeş",
		"az-Cyrl-AZ": "Мәракеш",
		"kk-KZ": "Марокко",
		"ky-KG": "Марокко",
		"uz-UZ": "Marokash",
		"tg-TJ": "Марокаш",
		"tk-TM": "Marokko",
		"fa-IR": "مراکش",
		"fa-AF": "مراکش",
		"ps-AF": "مراکش",
		"ps-PK": "مراکش",
		"he-IL": "מרוקו",
		"ar-SA": "المغرب",
		"ar-AE": "المغرب",
		"ar-QA": "المغرب",
		"ar-BH": "المغرب",
		"ar-KW": "المغرب",
		"ar-OM": "المغرب",
		"ar-YE": "المغرب",
		"ar-IQ": "المغرب",
		"ar-JO": "المغرب",
		"ar-LB": "المغرب",
		"ar-SY": "المغرب",
		"ar-PS": "المغرب",
		"en-US": "Morocco",
		"en-GB": "Morocco",
		"en-IE": "Morocco",
		"en-MT": "Morocco",
		"en-GI": "Morocco",
		"en-CY": "Morocco",
		"en-JE": "Morocco",
		"en-GG": "Morocco",
		"en-IM": "Morocco",
		"en-CA": "Morocco",
		"en-AU": "Morocco",
		"en-NZ": "Morocco",
		"en-ZA": "Morocco",
		"en-IN": "Morocco",
		"en-SG": "Morocco",
		"pt-AO": "Marrocos",
		"pt-MZ": "Marrocos",
		"pt-CV": "Marrocos",
		"pt-GW": "Marrocos",
		"pt-ST": "Marrocos",
		"pt-TL": "Marrocos",
		"pt-MO": "Marrocos",
		"es-ES": "Marruecos",
		"es-419": "Marruecos",
		"es-AD": "Marruecos",
		"es-GI": "Marruecos",
		"es-AR": "Marruecos",
		"es-BO": "Marruecos",
		"es-BR": "Marruecos",
		"es-BZ": "Marruecos",
		"es-CL": "Marruecos",
		"es-CO": "Marruecos",
		"es-CR": "Marruecos",
		"es-CU": "Marruecos",
		"es-DO": "Marruecos",
		"es-EC": "Marruecos",
		"es-GT": "Marruecos",
		"es-HN": "Marruecos",
		"es-MX": "Marruecos",
		"es-NI": "Marruecos",
		"es-PA": "Marruecos",
		"es-PE": "Marruecos",
		"es-PR": "Marruecos",
		"es-PY": "Marruecos",
		"es-SV": "Marruecos",
		"es-US": "Marruecos",
		"es-UY": "Marruecos",
		"es-VE": "Marruecos",
		"fr-FR": "Maroc",
		"fr-BE": "Maroc",
		"fr-CH": "Maroc",
		"fr-LU": "Maroc",
		"fr-MC": "Maroc",
		"fr-AD": "Maroc",
		"fr-CA": "Maroc",
		"it-IT": "Marocco",
		"it-CH": "Marocco",
		"it-SM": "Marocco",
		"it-VA": "Marocco",
		"de-DE": "Marokko",
		"de-AT": "Marokko",
		"de-CH": "Marokko",
		"de-BE": "Marokko",
		"de-LI": "Marokko",
		"de-LU": "Marokko",
		"nl-NL": "Marokko",
		"nl-BE": "Marokko",
		"sv-SE": "Marocko",
		"sv-FI": "Marocko",
		"da-DK": "Marokko",
		"nb-NO": "Marokko",
		"nn-NO": "Marokko",
		"fi-FI": "Marokko",
		"is-IS": "Marokkó",
		"fo-FO": "Marokko",
		"et-EE": "Maroko",
		"lv-LV": "Maroka",
		"lt-LT": "Marokas",
		"pl-PL": "Maroko",
		"cs-CZ": "Maroko",
		"sk-SK": "Maroko",
		"sl-SI": "Maroko",
		"hr-HR": "Maroko",
		"bs-BA": "Maroko",
		"sr-RS": "Мароко",
		"sr-BA": "Мароко",
		"sr-ME": "Maroko",
		"mk-MK": "Мароко",
		"bg-BG": "Мароко",
		"be-BY": "Марока",
		"uk-UA": "Марокко",
		"ru-RU": "Марокко",
		"el-GR": "Μαρόκο",
		"el-CY": "Μαρόκο",
		"ro-RO": "Maroc",
		"ro-MD": "Maroc",
		"hu-HU": "Marokkó",
		"sq-AL": "Marok",
		"sq-XK": "Marok",
		"mt-MT": "il-Marokk",
		"ga-IE": "Maracó",
		"cy-GB": "Moroco",
		"gd-GB": "Moroco",
		"lb-LU": "Marokko",
		"ca-ES": "Marroc",
		"ca-AD": "Marroc",
		"ca-FR": "Marroc",
		"ca-IT": "Marroc",
		"eu-ES": "Maroko",
		"eu-FR": "Maroko",
		"gl-ES": "Marrocos",
		"tr-TR": "Fas",
		"tr-CY": "Fas"
	},
	"callingCode": "212",
	"phoneMasks": [
		{
			"mask": "##-#######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"5[45]"
			]
		},
		{
			"mask": "###-######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[5-7]"
			]
		},
		{
			"mask": "####-#####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"5(?:2[2-46-9]|3[3-9]|9)|8(?:0[89]|92)"
			]
		}
	]
} satisfies Country;
