import type { Country } from './types.js';

export const MAR = {
	"code": "MAR",
	"labels": {
		"pt-BR": "Marrocos",
		"pt-PT": "Marrocos",
		"es-ES": "Marruecos",
		"es-419": "Marruecos",
		"es-AR": "Marruecos",
		"es-BO": "Marruecos",
		"es-BR": "Marruecos",
		"es-BZ": "Marruecos",
		"es-CL": "Marruecos",
		"es-CO": "Marruecos",
		"es-CR": "Marruecos",
		"es-CU": "Marruecos",
		"es-DO": "Marruecos",
		"es-EC": "Marruecos",
		"es-GT": "Marruecos",
		"es-HN": "Marruecos",
		"es-MX": "Marruecos",
		"es-NI": "Marruecos",
		"es-PA": "Marruecos",
		"es-PE": "Marruecos",
		"es-PR": "Marruecos",
		"es-PY": "Marruecos",
		"es-SV": "Marruecos",
		"es-US": "Marruecos",
		"es-UY": "Marruecos",
		"es-VE": "Marruecos",
		"en-US": "Morocco",
		"fr-FR": "Maroc",
		"fr-BE": "Maroc",
		"fr-CA": "Maroc",
		"fr-CH": "Maroc",
		"fr-LU": "Maroc",
		"fr-MC": "Maroc",
		"it-IT": "Marocco",
		"it-CH": "Marocco",
		"it-SM": "Marocco",
		"it-VA": "Marocco",
		"de-DE": "Marokko",
		"de-AT": "Marokko",
		"de-CH": "Marokko",
		"de-BE": "Marokko",
		"de-LI": "Marokko",
		"de-LU": "Marokko"
	}
} satisfies Country;
