import type { Country } from './types.js';

export const MCO = {
	"code": "MCO",
	"labels": {
		"pt-BR": "Mônaco",
		"pt-PT": "Mónaco",
		"es-ES": "Mónaco",
		"es-419": "Mónaco",
		"es-AR": "Mónaco",
		"es-BO": "Mónaco",
		"es-BR": "Mónaco",
		"es-BZ": "Mónaco",
		"es-CL": "Mónaco",
		"es-CO": "Mónaco",
		"es-CR": "Mónaco",
		"es-CU": "Mónaco",
		"es-DO": "Mónaco",
		"es-EC": "Mónaco",
		"es-GT": "Mónaco",
		"es-HN": "Mónaco",
		"es-MX": "Mónaco",
		"es-NI": "Mónaco",
		"es-PA": "Mónaco",
		"es-PE": "Mónaco",
		"es-PR": "Mónaco",
		"es-PY": "Mónaco",
		"es-SV": "Mónaco",
		"es-US": "Mónaco",
		"es-UY": "Mónaco",
		"es-VE": "Mónaco",
		"en-US": "Monaco",
		"fr-FR": "Monaco",
		"fr-BE": "Monaco",
		"fr-CA": "Monaco",
		"fr-CH": "Monaco",
		"fr-LU": "Monaco",
		"fr-MC": "Monaco",
		"it-IT": "Monaco",
		"it-CH": "Monaco",
		"it-SM": "Monaco",
		"it-VA": "Monaco",
		"de-DE": "Monaco",
		"de-AT": "Monaco",
		"de-CH": "Monaco",
		"de-BE": "Monaco",
		"de-LI": "Monaco",
		"de-LU": "Monaco"
	},
	"callingCode": "377"
} satisfies Country;
