import type { Country } from './types.js';

export const MDA = {
	"code": "MDA",
	"labels": {
		"pt-BR": "Moldávia",
		"pt-PT": "Moldávia",
		"qu-PE": "Moldova",
		"qu-BO": "Moldova",
		"qu-EC": "Moldova",
		"chr-US": "ᎹᎵᏙᏫᎠ",
		"hi-IN": "मॉल्डोवा",
		"bn-IN": "মলডোভা",
		"bn-BD": "মলডোভা",
		"ta-IN": "மால்டோவா",
		"ta-LK": "மால்டோவா",
		"ta-SG": "மால்டோவா",
		"ta-MY": "மால்டோவா",
		"te-IN": "మోల్డోవా",
		"mr-IN": "मोल्डोव्हा",
		"gu-IN": "મોલડોવા",
		"kn-IN": "ಮೊಲ್ಡೋವಾ",
		"ml-IN": "മൾഡോവ",
		"pa-IN": "ਮੋਲਡੋਵਾ",
		"ur-IN": "مالدووا",
		"ur-PK": "مالدووا",
		"or-IN": "ମୋଲଡୋଭା",
		"as-IN": "মোলডোভা",
		"ne-IN": "माल्डोभा",
		"ne-NP": "माल्डोभा",
		"si-LK": "මොල්ඩෝවාව",
		"kok-IN": "माल्डोवा",
		"ks-IN": "مولڈووا",
		"brx-IN": "मल्ड’भा",
		"mai-IN": "मोलडोवा",
		"dz-BT": "མོལ་དོ་བཱ",
		"ja-JP": "モルドバ",
		"ko-KR": "몰도바",
		"ko-KP": "몰도바",
		"zh-CN": "摩尔多瓦",
		"zh-Hans-CN": "摩尔多瓦",
		"zh-Hant-TW": "摩爾多瓦",
		"zh-TW": "摩爾多瓦",
		"zh-HK": "摩爾多瓦",
		"zh-MO": "摩爾多瓦",
		"zh-SG": "摩尔多瓦",
		"yue-Hant-HK": "摩爾多瓦",
		"yue-Hans-CN": "摩尔多瓦",
		"mn-MN": "Молдова",
		"ug-CN": "مولدوۋا",
		"th-TH": "มอลโดวา",
		"lo-LA": "ໂມນໂດວາ",
		"km-KH": "ម៉ុលដាវី",
		"my-MM": "မောလ်ဒိုဗာ",
		"vi-VN": "Moldova",
		"id-ID": "Moldova",
		"ms-MY": "Moldova",
		"ms-SG": "Moldova",
		"ms-BN": "Moldova",
		"jv-ID": "Moldova",
		"fil-PH": "Moldova",
		"ceb-PH": "Moldova",
		"ka-GE": "მოლდოვა",
		"hy-AM": "Մոլդովա",
		"az-AZ": "Moldova",
		"az-Cyrl-AZ": "Молдова",
		"kk-KZ": "Молдова",
		"ky-KG": "Молдова",
		"uz-UZ": "Moldova",
		"tg-TJ": "Молдова",
		"tk-TM": "Moldowa",
		"fa-IR": "مولداوی",
		"fa-AF": "مولداوی",
		"ps-AF": "مولدوا",
		"ps-PK": "مولدوا",
		"he-IL": "מולדובה",
		"ar-SA": "مولدوفا",
		"ar-AE": "مولدوفا",
		"ar-QA": "مولدوفا",
		"ar-BH": "مولدوفا",
		"ar-KW": "مولدوفا",
		"ar-OM": "مولدوفا",
		"ar-YE": "مولدوفا",
		"ar-IQ": "مولدوفا",
		"ar-JO": "مولدوفا",
		"ar-LB": "مولدوفا",
		"ar-SY": "مولدوفا",
		"ar-PS": "مولدوفا",
		"en-US": "Moldova",
		"en-GB": "Moldova",
		"en-IE": "Moldova",
		"en-MT": "Moldova",
		"en-GI": "Moldova",
		"en-CY": "Moldova",
		"en-JE": "Moldova",
		"en-GG": "Moldova",
		"en-IM": "Moldova",
		"en-CA": "Moldova",
		"en-AU": "Moldova",
		"en-NZ": "Moldova",
		"en-ZA": "Moldova",
		"en-IN": "Moldova",
		"en-SG": "Moldova",
		"pt-AO": "Moldávia",
		"pt-MZ": "Moldávia",
		"pt-CV": "Moldávia",
		"pt-GW": "Moldávia",
		"pt-ST": "Moldávia",
		"pt-TL": "Moldávia",
		"pt-MO": "Moldávia",
		"es-ES": "Moldavia",
		"es-419": "Moldavia",
		"es-AD": "Moldavia",
		"es-GI": "Moldavia",
		"es-AR": "Moldavia",
		"es-BO": "Moldavia",
		"es-BR": "Moldavia",
		"es-BZ": "Moldavia",
		"es-CL": "Moldavia",
		"es-CO": "Moldavia",
		"es-CR": "Moldavia",
		"es-CU": "Moldavia",
		"es-DO": "Moldavia",
		"es-EC": "Moldavia",
		"es-GT": "Moldavia",
		"es-HN": "Moldavia",
		"es-MX": "Moldavia",
		"es-NI": "Moldavia",
		"es-PA": "Moldavia",
		"es-PE": "Moldavia",
		"es-PR": "Moldavia",
		"es-PY": "Moldavia",
		"es-SV": "Moldavia",
		"es-US": "Moldavia",
		"es-UY": "Moldavia",
		"es-VE": "Moldavia",
		"fr-FR": "Moldavie",
		"fr-BE": "Moldavie",
		"fr-CH": "Moldavie",
		"fr-LU": "Moldavie",
		"fr-MC": "Moldavie",
		"fr-AD": "Moldavie",
		"fr-CA": "Moldavie",
		"it-IT": "Moldavia",
		"it-CH": "Moldavia",
		"it-SM": "Moldavia",
		"it-VA": "Moldavia",
		"de-DE": "Republik Moldau",
		"de-AT": "Republik Moldau",
		"de-CH": "Republik Moldau",
		"de-BE": "Republik Moldau",
		"de-LI": "Republik Moldau",
		"de-LU": "Republik Moldau",
		"nl-NL": "Moldavië",
		"nl-BE": "Moldavië",
		"sv-SE": "Moldavien",
		"sv-FI": "Moldavien",
		"da-DK": "Moldova",
		"nb-NO": "Moldova",
		"nn-NO": "Moldova",
		"fi-FI": "Moldova",
		"is-IS": "Moldóva",
		"fo-FO": "Moldova",
		"et-EE": "Moldova",
		"lv-LV": "Moldova",
		"lt-LT": "Moldova",
		"pl-PL": "Mołdawia",
		"cs-CZ": "Moldavsko",
		"sk-SK": "Moldavsko",
		"sl-SI": "Moldavija",
		"hr-HR": "Moldavija",
		"bs-BA": "Moldavija",
		"sr-RS": "Молдавија",
		"sr-BA": "Молдавија",
		"sr-ME": "Moldavija",
		"mk-MK": "Молдавија",
		"bg-BG": "Молдова",
		"be-BY": "Малдова",
		"uk-UA": "Молдова",
		"ru-RU": "Молдова",
		"el-GR": "Μολδαβία",
		"el-CY": "Μολδαβία",
		"ro-RO": "Republica Moldova",
		"ro-MD": "Republica Moldova",
		"hu-HU": "Moldova",
		"sq-AL": "Moldavi",
		"sq-XK": "Moldavi",
		"mt-MT": "il-Moldova",
		"ga-IE": "an Mholdóiv",
		"cy-GB": "Moldofa",
		"gd-GB": "A’ Mholdobha",
		"lb-LU": "Moldawien",
		"ca-ES": "Moldàvia",
		"ca-AD": "Moldàvia",
		"ca-FR": "Moldàvia",
		"ca-IT": "Moldàvia",
		"eu-ES": "Moldavia",
		"eu-FR": "Moldavia",
		"gl-ES": "República Moldova",
		"tr-TR": "Moldova",
		"tr-CY": "Moldova"
	},
	"callingCode": "373",
	"phoneMasks": [
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"22|3"
			]
		},
		{
			"mask": "### ## ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[25-7]"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
