import type { Country } from './types.js';

export const MDG = {
	"code": "MDG",
	"labels": {
		"pt-BR": "Madagascar",
		"pt-PT": "Madagáscar",
		"es-ES": "Madagascar",
		"es-419": "Madagascar",
		"es-AR": "Madagascar",
		"es-BO": "Madagascar",
		"es-BR": "Madagascar",
		"es-BZ": "Madagascar",
		"es-CL": "Madagascar",
		"es-CO": "Madagascar",
		"es-CR": "Madagascar",
		"es-CU": "Madagascar",
		"es-DO": "Madagascar",
		"es-EC": "Madagascar",
		"es-GT": "Madagascar",
		"es-HN": "Madagascar",
		"es-MX": "Madagascar",
		"es-NI": "Madagascar",
		"es-PA": "Madagascar",
		"es-PE": "Madagascar",
		"es-PR": "Madagascar",
		"es-PY": "Madagascar",
		"es-SV": "Madagascar",
		"es-US": "Madagascar",
		"es-UY": "Madagascar",
		"es-VE": "Madagascar",
		"en-US": "Madagascar",
		"fr-FR": "Madagascar",
		"fr-BE": "Madagascar",
		"fr-CA": "Madagascar",
		"fr-CH": "Madagascar",
		"fr-LU": "Madagascar",
		"fr-MC": "Madagascar",
		"it-IT": "Madagascar",
		"it-CH": "Madagascar",
		"it-SM": "Madagascar",
		"it-VA": "Madagascar",
		"de-DE": "Madagaskar",
		"de-AT": "Madagaskar",
		"de-CH": "Madagaskar",
		"de-BE": "Madagaskar",
		"de-LI": "Madagaskar",
		"de-LU": "Madagaskar"
	},
	"callingCode": "261"
} satisfies Country;
