import type { Country } from './types.js';

export const MEX = {
	"code": "MEX",
	"labels": {
		"pt-BR": "México",
		"pt-PT": "México",
		"es-ES": "México",
		"es-419": "México",
		"es-AR": "México",
		"es-BO": "México",
		"es-BR": "México",
		"es-BZ": "México",
		"es-CL": "México",
		"es-CO": "México",
		"es-CR": "México",
		"es-CU": "México",
		"es-DO": "México",
		"es-EC": "México",
		"es-GT": "México",
		"es-HN": "México",
		"es-MX": "México",
		"es-NI": "México",
		"es-PA": "México",
		"es-PE": "México",
		"es-PR": "México",
		"es-PY": "México",
		"es-SV": "México",
		"es-US": "México",
		"es-UY": "México",
		"es-VE": "México",
		"en-US": "Mexico",
		"fr-FR": "Mexique",
		"fr-BE": "Mexique",
		"fr-CA": "Mexique",
		"fr-CH": "Mexique",
		"fr-LU": "Mexique",
		"fr-MC": "Mexique",
		"it-IT": "Messico",
		"it-CH": "Messico",
		"it-SM": "Messico",
		"it-VA": "Messico",
		"de-DE": "Mexiko",
		"de-AT": "Mexiko",
		"de-CH": "Mexiko",
		"de-BE": "Mexiko",
		"de-LI": "Mexiko",
		"de-LU": "Mexiko"
	}
} satisfies Country;
