import type { Country } from './types.js';

export const MKD = {
	"code": "MKD",
	"labels": {
		"pt-BR": "Macedônia do Norte",
		"pt-PT": "Macedónia do Norte",
		"es-ES": "Macedonia del Norte",
		"es-419": "Macedonia del Norte",
		"es-AR": "Macedonia del Norte",
		"es-BO": "Macedonia del Norte",
		"es-BR": "Macedonia del Norte",
		"es-BZ": "Macedonia del Norte",
		"es-CL": "Macedonia del Norte",
		"es-CO": "Macedonia del Norte",
		"es-CR": "Macedonia del Norte",
		"es-CU": "Macedonia del Norte",
		"es-DO": "Macedonia del Norte",
		"es-EC": "Macedonia del Norte",
		"es-GT": "Macedonia del Norte",
		"es-HN": "Macedonia del Norte",
		"es-MX": "Macedonia del Norte",
		"es-NI": "Macedonia del Norte",
		"es-PA": "Macedonia del Norte",
		"es-PE": "Macedonia del Norte",
		"es-PR": "Macedonia del Norte",
		"es-PY": "Macedonia del Norte",
		"es-SV": "Macedonia del Norte",
		"es-US": "Macedonia del Norte",
		"es-UY": "Macedonia del Norte",
		"es-VE": "Macedonia del Norte",
		"en-US": "North Macedonia",
		"fr-FR": "Macédoine du Nord",
		"fr-BE": "Macédoine du Nord",
		"fr-CA": "Macédoine du Nord",
		"fr-CH": "Macédoine du Nord",
		"fr-LU": "Macédoine du Nord",
		"fr-MC": "Macédoine du Nord",
		"it-IT": "Macedonia del Nord",
		"it-CH": "Macedonia del Nord",
		"it-SM": "Macedonia del Nord",
		"it-VA": "Macedonia del Nord",
		"de-DE": "Nordmazedonien",
		"de-AT": "Nordmazedonien",
		"de-CH": "Nordmazedonien",
		"de-BE": "Nordmazedonien",
		"de-LI": "Nordmazedonien",
		"de-LU": "Nordmazedonien"
	},
	"callingCode": "389"
} satisfies Country;
