import type { Country } from './types.js';

export const MLI = {
	"code": "MLI",
	"labels": {
		"pt-BR": "Mali",
		"pt-PT": "Mali",
		"es-ES": "Mali",
		"es-419": "Mali",
		"es-AR": "Mali",
		"es-BO": "Mali",
		"es-BR": "Mali",
		"es-BZ": "Mali",
		"es-CL": "Mali",
		"es-CO": "Mali",
		"es-CR": "Mali",
		"es-CU": "Mali",
		"es-DO": "Mali",
		"es-EC": "Mali",
		"es-GT": "Mali",
		"es-HN": "Mali",
		"es-MX": "Mali",
		"es-NI": "Mali",
		"es-PA": "Mali",
		"es-PE": "Mali",
		"es-PR": "Mali",
		"es-PY": "Mali",
		"es-SV": "Mali",
		"es-US": "Mali",
		"es-UY": "Mali",
		"es-VE": "Mali",
		"en-US": "Mali",
		"fr-FR": "Mali",
		"fr-BE": "Mali",
		"fr-CA": "Mali",
		"fr-CH": "Mali",
		"fr-LU": "Mali",
		"fr-MC": "Mali",
		"it-IT": "Mali",
		"it-CH": "Mali",
		"it-SM": "Mali",
		"it-VA": "Mali",
		"de-DE": "Mali",
		"de-AT": "Mali",
		"de-CH": "Mali",
		"de-BE": "Mali",
		"de-LI": "Mali",
		"de-LU": "Mali"
	}
} satisfies Country;
