import type { Country } from './types.js';

export const MLT = {
	"code": "MLT",
	"labels": {
		"pt-BR": "Malta",
		"pt-PT": "Malta",
		"es-ES": "Malta",
		"es-419": "Malta",
		"es-AR": "Malta",
		"es-BO": "Malta",
		"es-BR": "Malta",
		"es-BZ": "Malta",
		"es-CL": "Malta",
		"es-CO": "Malta",
		"es-CR": "Malta",
		"es-CU": "Malta",
		"es-DO": "Malta",
		"es-EC": "Malta",
		"es-GT": "Malta",
		"es-HN": "Malta",
		"es-MX": "Malta",
		"es-NI": "Malta",
		"es-PA": "Malta",
		"es-PE": "Malta",
		"es-PR": "Malta",
		"es-PY": "Malta",
		"es-SV": "Malta",
		"es-US": "Malta",
		"es-UY": "Malta",
		"es-VE": "Malta",
		"en-US": "Malta",
		"fr-FR": "Malte",
		"fr-BE": "Malte",
		"fr-CA": "Malte",
		"fr-CH": "Malte",
		"fr-LU": "Malte",
		"fr-MC": "Malte",
		"it-IT": "Malta",
		"it-CH": "Malta",
		"it-SM": "Malta",
		"it-VA": "Malta",
		"de-DE": "Malta",
		"de-AT": "Malta",
		"de-CH": "Malta",
		"de-BE": "Malta",
		"de-LI": "Malta",
		"de-LU": "Malta"
	}
} satisfies Country;
