import type { Country } from './types.js';

export const MMR = {
	"code": "MMR",
	"labels": {
		"pt-BR": "Mianmar (Birmânia)",
		"pt-PT": "Mianmar (Birmânia)",
		"qu-PE": "Myanmar",
		"qu-BO": "Myanmar",
		"qu-EC": "Myanmar",
		"chr-US": "ᎹᏯᎹᎵ (ᏇᎵᎹ)",
		"hi-IN": "म्यांमार (बर्मा)",
		"bn-IN": "মায়ানমার (বার্মা)",
		"bn-BD": "মায়ানমার (বার্মা)",
		"ta-IN": "மியான்மார் (பர்மா)",
		"ta-LK": "மியான்மார் (பர்மா)",
		"ta-SG": "மியான்மார் (பர்மா)",
		"ta-MY": "மியான்மார் (பர்மா)",
		"te-IN": "మయన్మార్",
		"mr-IN": "म्यानमार (बर्मा)",
		"gu-IN": "મ્યાંમાર (બર્મા)",
		"kn-IN": "ಮಯನ್ಮಾರ್ (ಬರ್ಮಾ)",
		"ml-IN": "മ്യാൻമാർ (ബർമ്മ)",
		"pa-IN": "ਮਿਆਂਮਾਰ (ਬਰਮਾ)",
		"ur-IN": "میانمار (برما)",
		"ur-PK": "میانمار (برما)",
		"or-IN": "ମିଆଁମାର",
		"as-IN": "ম্যানমাৰ (বাৰ্মা)",
		"ne-IN": "म्यान्मार (बर्मा)",
		"ne-NP": "म्यान्मार (बर्मा)",
		"si-LK": "මියන්මාරය (බුරුමය)",
		"kok-IN": "म्यानमार (बर्मा)",
		"ks-IN": "میانمار (برما)",
		"brx-IN": "म्यानमार",
		"mai-IN": "मयनमार (बर्मा)",
		"dz-BT": "མི་ཡཱན་མར་ (བྷར་མ)",
		"ja-JP": "ミャンマー (ビルマ)",
		"ko-KR": "미얀마",
		"ko-KP": "미얀마",
		"zh-CN": "缅甸",
		"zh-Hans-CN": "缅甸",
		"zh-Hant-TW": "緬甸",
		"zh-TW": "緬甸",
		"zh-HK": "緬甸",
		"zh-MO": "緬甸",
		"zh-SG": "缅甸",
		"yue-Hant-HK": "緬甸",
		"yue-Hans-CN": "缅甸",
		"mn-MN": "Мьянмар",
		"ug-CN": "بىرما",
		"th-TH": "เมียนมา (พม่า)",
		"lo-LA": "ມຽນມາ (ເບີມາ)",
		"km-KH": "មីយ៉ាន់ម៉ា (ភូមា)",
		"my-MM": "မြန်မာ",
		"vi-VN": "Myanmar (Miến Điện)",
		"id-ID": "Myanmar (Burma)",
		"ms-MY": "Myanmar (Burma)",
		"ms-SG": "Myanmar (Burma)",
		"ms-BN": "Myanmar (Burma)",
		"jv-ID": "Myanmar (Burma)",
		"fil-PH": "Myanmar (Burma)",
		"ceb-PH": "Myanmar (Burma)",
		"ka-GE": "მიანმარი (ბირმა)",
		"hy-AM": "Մյանմա (Բիրմա)",
		"az-AZ": "Myanma",
		"az-Cyrl-AZ": "Мјанма",
		"kk-KZ": "Мьянма (Бирма)",
		"ky-KG": "Мьянма (Бирма)",
		"uz-UZ": "Myanma (Birma)",
		"tg-TJ": "Мянма",
		"tk-TM": "Mýanma (Birma)",
		"fa-IR": "میانمار (برمه)",
		"fa-AF": "میانمار (برمه)",
		"ps-AF": "ميانمار (برما)",
		"ps-PK": "ميانمار (برما)",
		"he-IL": "מיאנמר (בורמה)",
		"ar-SA": "ميانمار (بورما)",
		"ar-AE": "ميانمار (بورما)",
		"ar-QA": "ميانمار (بورما)",
		"ar-BH": "ميانمار (بورما)",
		"ar-KW": "ميانمار (بورما)",
		"ar-OM": "ميانمار (بورما)",
		"ar-YE": "ميانمار (بورما)",
		"ar-IQ": "ميانمار (بورما)",
		"ar-JO": "ميانمار (بورما)",
		"ar-LB": "ميانمار (بورما)",
		"ar-SY": "ميانمار (بورما)",
		"ar-PS": "ميانمار (بورما)",
		"en-US": "Myanmar (Burma)",
		"en-GB": "Myanmar (Burma)",
		"en-IE": "Myanmar (Burma)",
		"en-MT": "Myanmar (Burma)",
		"en-GI": "Myanmar (Burma)",
		"en-CY": "Myanmar (Burma)",
		"en-JE": "Myanmar (Burma)",
		"en-GG": "Myanmar (Burma)",
		"en-IM": "Myanmar (Burma)",
		"en-CA": "Myanmar (Burma)",
		"en-AU": "Myanmar (Burma)",
		"en-NZ": "Myanmar (Burma)",
		"en-ZA": "Myanmar (Burma)",
		"en-IN": "Myanmar (Burma)",
		"en-SG": "Myanmar (Burma)",
		"pt-AO": "Mianmar (Birmânia)",
		"pt-MZ": "Mianmar (Birmânia)",
		"pt-CV": "Mianmar (Birmânia)",
		"pt-GW": "Mianmar (Birmânia)",
		"pt-ST": "Mianmar (Birmânia)",
		"pt-TL": "Mianmar (Birmânia)",
		"pt-MO": "Mianmar (Birmânia)",
		"es-ES": "Myanmar (Birmania)",
		"es-419": "Myanmar (Birmania)",
		"es-AD": "Myanmar (Birmania)",
		"es-GI": "Myanmar (Birmania)",
		"es-AR": "Myanmar (Birmania)",
		"es-BO": "Myanmar (Birmania)",
		"es-BR": "Myanmar (Birmania)",
		"es-BZ": "Myanmar (Birmania)",
		"es-CL": "Myanmar (Birmania)",
		"es-CO": "Myanmar (Birmania)",
		"es-CR": "Myanmar (Birmania)",
		"es-CU": "Myanmar (Birmania)",
		"es-DO": "Myanmar (Birmania)",
		"es-EC": "Myanmar (Birmania)",
		"es-GT": "Myanmar (Birmania)",
		"es-HN": "Myanmar (Birmania)",
		"es-MX": "Myanmar (Birmania)",
		"es-NI": "Myanmar (Birmania)",
		"es-PA": "Myanmar (Birmania)",
		"es-PE": "Myanmar (Birmania)",
		"es-PR": "Myanmar (Birmania)",
		"es-PY": "Myanmar (Birmania)",
		"es-SV": "Myanmar (Birmania)",
		"es-US": "Myanmar (Birmania)",
		"es-UY": "Myanmar (Birmania)",
		"es-VE": "Myanmar (Birmania)",
		"fr-FR": "Myanmar (Birmanie)",
		"fr-BE": "Myanmar (Birmanie)",
		"fr-CH": "Myanmar (Birmanie)",
		"fr-LU": "Myanmar (Birmanie)",
		"fr-MC": "Myanmar (Birmanie)",
		"fr-AD": "Myanmar (Birmanie)",
		"fr-CA": "Myanmar",
		"it-IT": "Myanmar (Birmania)",
		"it-CH": "Myanmar (Birmania)",
		"it-SM": "Myanmar (Birmania)",
		"it-VA": "Myanmar (Birmania)",
		"de-DE": "Myanmar",
		"de-AT": "Myanmar",
		"de-CH": "Myanmar",
		"de-BE": "Myanmar",
		"de-LI": "Myanmar",
		"de-LU": "Myanmar",
		"nl-NL": "Myanmar (Birma)",
		"nl-BE": "Myanmar (Birma)",
		"sv-SE": "Myanmar (Burma)",
		"sv-FI": "Myanmar (Burma)",
		"da-DK": "Myanmar (Burma)",
		"nb-NO": "Myanmar (Burma)",
		"nn-NO": "Myanmar (Burma)",
		"fi-FI": "Myanmar (Burma)",
		"is-IS": "Mjanmar (Búrma)",
		"fo-FO": "Myanmar (Burma)",
		"et-EE": "Myanmar (Birma)",
		"lv-LV": "Mjanma (Birma)",
		"lt-LT": "Mianmaras (Birma)",
		"pl-PL": "Mjanma (Birma)",
		"cs-CZ": "Myanmar (Barma)",
		"sk-SK": "Mjanmarsko",
		"sl-SI": "Mjanmar (Burma)",
		"hr-HR": "Mjanmar (Burma)",
		"bs-BA": "Mijanmar",
		"sr-RS": "Мијанмар (Бурма)",
		"sr-BA": "Мјанмар (Бурма)",
		"sr-ME": "Mijanmar (Burma)",
		"mk-MK": "Мјанмар (Бурма)",
		"bg-BG": "Мианмар (Бирма)",
		"be-BY": "М’янма (Бірма)",
		"uk-UA": "Мʼянма (Бірма)",
		"ru-RU": "Мьянма (Бирма)",
		"el-GR": "Μιανμάρ (Βιρμανία)",
		"el-CY": "Μιανμάρ (Βιρμανία)",
		"ro-RO": "Myanmar (Birmania)",
		"ro-MD": "Myanmar",
		"hu-HU": "Mianmar",
		"sq-AL": "Mianmar (Burmë)",
		"sq-XK": "Mianmar (Burmë)",
		"mt-MT": "il-Myanmar/Burma",
		"ga-IE": "Maenmar (Burma)",
		"cy-GB": "Myanmar (Burma)",
		"gd-GB": "Miànmar",
		"lb-LU": "Myanmar",
		"ca-ES": "Myanmar (Birmània)",
		"ca-AD": "Myanmar (Birmània)",
		"ca-FR": "Myanmar (Birmània)",
		"ca-IT": "Myanmar (Birmània)",
		"eu-ES": "Myanmar (Birmania)",
		"eu-FR": "Myanmar (Birmania)",
		"gl-ES": "Myanmar (Birmania)",
		"tr-TR": "Myanmar (Burma)",
		"tr-CY": "Myanmar (Burma)"
	},
	"callingCode": "95",
	"phoneMasks": [
		{
			"mask": "# ## ###",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"16|2"
			]
		},
		{
			"mask": "## ## ###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"4(?:[2-46]|5[3-5])|5|6(?:[1-689]|7[235-7])|7(?:[0-4]|5[2-7])|8[1-5]|(?:60|86)[23]"
			]
		},
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[12]|452|678|86",
				"[12]|452|6788|86"
			]
		},
		{
			"mask": "# #### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[4-7]|8[1-35]"
			]
		},
		{
			"mask": "# ### ### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"92"
			]
		},
		{
			"mask": "# ### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"9(?:2[0-4]|[35-9]|4[137-9])"
			]
		},
		{
			"mask": "# ##### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"9"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
