import type { Country } from './types.js';

export const MMR = {
	"code": "MMR",
	"labels": {
		"pt-BR": "Mianmar (Birmânia)",
		"pt-PT": "Mianmar (Birmânia)",
		"es-ES": "Myanmar (Birmania)",
		"es-419": "Myanmar (Birmania)",
		"es-AR": "Myanmar (Birmania)",
		"es-BO": "Myanmar (Birmania)",
		"es-BR": "Myanmar (Birmania)",
		"es-BZ": "Myanmar (Birmania)",
		"es-CL": "Myanmar (Birmania)",
		"es-CO": "Myanmar (Birmania)",
		"es-CR": "Myanmar (Birmania)",
		"es-CU": "Myanmar (Birmania)",
		"es-DO": "Myanmar (Birmania)",
		"es-EC": "Myanmar (Birmania)",
		"es-GT": "Myanmar (Birmania)",
		"es-HN": "Myanmar (Birmania)",
		"es-MX": "Myanmar (Birmania)",
		"es-NI": "Myanmar (Birmania)",
		"es-PA": "Myanmar (Birmania)",
		"es-PE": "Myanmar (Birmania)",
		"es-PR": "Myanmar (Birmania)",
		"es-PY": "Myanmar (Birmania)",
		"es-SV": "Myanmar (Birmania)",
		"es-US": "Myanmar (Birmania)",
		"es-UY": "Myanmar (Birmania)",
		"es-VE": "Myanmar (Birmania)",
		"en-US": "Myanmar (Burma)",
		"fr-FR": "Myanmar (Birmanie)",
		"fr-BE": "Myanmar (Birmanie)",
		"fr-CA": "Myanmar",
		"fr-CH": "Myanmar (Birmanie)",
		"fr-LU": "Myanmar (Birmanie)",
		"fr-MC": "Myanmar (Birmanie)",
		"it-IT": "Myanmar (Birmania)",
		"it-CH": "Myanmar (Birmania)",
		"it-SM": "Myanmar (Birmania)",
		"it-VA": "Myanmar (Birmania)",
		"de-DE": "Myanmar",
		"de-AT": "Myanmar",
		"de-CH": "Myanmar",
		"de-BE": "Myanmar",
		"de-LI": "Myanmar",
		"de-LU": "Myanmar"
	},
	"callingCode": "95"
} satisfies Country;
