import type { Country } from './types.js';

export const MNE = {
	"code": "MNE",
	"labels": {
		"pt-BR": "Montenegro",
		"pt-PT": "Montenegro",
		"qu-PE": "Montenegro",
		"qu-BO": "Montenegro",
		"qu-EC": "Montenegro",
		"chr-US": "ᎼᏂᏔᏁᎦᎶ",
		"hi-IN": "मोंटेनेग्रो",
		"bn-IN": "মন্টিনিগ্রো",
		"bn-BD": "মন্টিনিগ্রো",
		"ta-IN": "மான்டேனெக்ரோ",
		"ta-LK": "மான்டேனெக்ரோ",
		"ta-SG": "மான்டேனெக்ரோ",
		"ta-MY": "மான்டேனெக்ரோ",
		"te-IN": "మాంటెనెగ్రో",
		"mr-IN": "मोंटेनेग्रो",
		"gu-IN": "મૉન્ટેનેગ્રો",
		"kn-IN": "ಮೊಂಟೆನೆಗ್ರೋ",
		"ml-IN": "മോണ്ടെനെഗ്രോ",
		"pa-IN": "ਮੋਂਟੇਨੇਗਰੋ",
		"ur-IN": "مونٹے نیگرو",
		"ur-PK": "مونٹے نیگرو",
		"or-IN": "ମଣ୍ଟେନିଗ୍ରୋ",
		"as-IN": "মণ্টেনেগ্ৰু",
		"ne-IN": "मोन्टेनिग्रो",
		"ne-NP": "मोन्टेनिग्रो",
		"si-LK": "මොන්ටෙනීග්‍රෝ",
		"kok-IN": "मॉन्टॅनग्रो",
		"ks-IN": "موٹونیگِریو",
		"brx-IN": "मन्टेनेग्र’",
		"mai-IN": "मोंटेनीग्रो",
		"dz-BT": "མོན་ཊི་ནེག་རོ",
		"ja-JP": "モンテネグロ",
		"ko-KR": "몬테네그로",
		"ko-KP": "몬테네그로",
		"zh-CN": "黑山",
		"zh-Hans-CN": "黑山",
		"zh-Hant-TW": "蒙特內哥羅",
		"zh-TW": "蒙特內哥羅",
		"zh-HK": "黑山",
		"zh-MO": "黑山",
		"zh-SG": "黑山",
		"yue-Hant-HK": "蒙特內哥羅",
		"yue-Hans-CN": "蒙特内哥罗",
		"mn-MN": "Монтенегро",
		"ug-CN": "قارا تاغ",
		"th-TH": "มอนเตเนโกร",
		"lo-LA": "ມອນເຕເນໂກຣ",
		"km-KH": "ម៉ុងតេណេហ្គ្រោ",
		"my-MM": "မွန်တီနိဂရိုး",
		"vi-VN": "Montenegro",
		"id-ID": "Montenegro",
		"ms-MY": "Montenegro",
		"ms-SG": "Montenegro",
		"ms-BN": "Montenegro",
		"jv-ID": "Montenégro",
		"fil-PH": "Montenegro",
		"ceb-PH": "Montenegro",
		"ka-GE": "მონტენეგრო",
		"hy-AM": "Չեռնոգորիա",
		"az-AZ": "Monteneqro",
		"az-Cyrl-AZ": "Монтенегро",
		"kk-KZ": "Черногория",
		"ky-KG": "Черногория",
		"uz-UZ": "Chernogoriya",
		"tg-TJ": "Черногория",
		"tk-TM": "Çernogoriýa",
		"fa-IR": "مونته‌نگرو",
		"fa-AF": "مونته‌نگرو",
		"ps-AF": "مونټینیګرو",
		"ps-PK": "مونټینیګرو",
		"he-IL": "מונטנגרו",
		"ar-SA": "الجبل الأسود",
		"ar-AE": "الجبل الأسود",
		"ar-QA": "الجبل الأسود",
		"ar-BH": "الجبل الأسود",
		"ar-KW": "الجبل الأسود",
		"ar-OM": "الجبل الأسود",
		"ar-YE": "الجبل الأسود",
		"ar-IQ": "الجبل الأسود",
		"ar-JO": "الجبل الأسود",
		"ar-LB": "الجبل الأسود",
		"ar-SY": "الجبل الأسود",
		"ar-PS": "الجبل الأسود",
		"en-US": "Montenegro",
		"en-GB": "Montenegro",
		"en-IE": "Montenegro",
		"en-MT": "Montenegro",
		"en-GI": "Montenegro",
		"en-CY": "Montenegro",
		"en-JE": "Montenegro",
		"en-GG": "Montenegro",
		"en-IM": "Montenegro",
		"en-CA": "Montenegro",
		"en-AU": "Montenegro",
		"en-NZ": "Montenegro",
		"en-ZA": "Montenegro",
		"en-IN": "Montenegro",
		"en-SG": "Montenegro",
		"pt-AO": "Montenegro",
		"pt-MZ": "Montenegro",
		"pt-CV": "Montenegro",
		"pt-GW": "Montenegro",
		"pt-ST": "Montenegro",
		"pt-TL": "Montenegro",
		"pt-MO": "Montenegro",
		"es-ES": "Montenegro",
		"es-419": "Montenegro",
		"es-AD": "Montenegro",
		"es-GI": "Montenegro",
		"es-AR": "Montenegro",
		"es-BO": "Montenegro",
		"es-BR": "Montenegro",
		"es-BZ": "Montenegro",
		"es-CL": "Montenegro",
		"es-CO": "Montenegro",
		"es-CR": "Montenegro",
		"es-CU": "Montenegro",
		"es-DO": "Montenegro",
		"es-EC": "Montenegro",
		"es-GT": "Montenegro",
		"es-HN": "Montenegro",
		"es-MX": "Montenegro",
		"es-NI": "Montenegro",
		"es-PA": "Montenegro",
		"es-PE": "Montenegro",
		"es-PR": "Montenegro",
		"es-PY": "Montenegro",
		"es-SV": "Montenegro",
		"es-US": "Montenegro",
		"es-UY": "Montenegro",
		"es-VE": "Montenegro",
		"fr-FR": "Monténégro",
		"fr-BE": "Monténégro",
		"fr-CH": "Monténégro",
		"fr-LU": "Monténégro",
		"fr-MC": "Monténégro",
		"fr-AD": "Monténégro",
		"fr-CA": "Monténégro",
		"it-IT": "Montenegro",
		"it-CH": "Montenegro",
		"it-SM": "Montenegro",
		"it-VA": "Montenegro",
		"de-DE": "Montenegro",
		"de-AT": "Montenegro",
		"de-CH": "Montenegro",
		"de-BE": "Montenegro",
		"de-LI": "Montenegro",
		"de-LU": "Montenegro",
		"nl-NL": "Montenegro",
		"nl-BE": "Montenegro",
		"sv-SE": "Montenegro",
		"sv-FI": "Montenegro",
		"da-DK": "Montenegro",
		"nb-NO": "Montenegro",
		"nn-NO": "Montenegro",
		"fi-FI": "Montenegro",
		"is-IS": "Svartfjallaland",
		"fo-FO": "Montenegro",
		"et-EE": "Montenegro",
		"lv-LV": "Melnkalne",
		"lt-LT": "Juodkalnija",
		"pl-PL": "Czarnogóra",
		"cs-CZ": "Černá Hora",
		"sk-SK": "Čierna Hora",
		"sl-SI": "Črna gora",
		"hr-HR": "Crna Gora",
		"bs-BA": "Crna Gora",
		"sr-RS": "Црна Гора",
		"sr-BA": "Црна Гора",
		"sr-ME": "Crna Gora",
		"mk-MK": "Црна Гора",
		"bg-BG": "Черна гора",
		"be-BY": "Чарнагорыя",
		"uk-UA": "Чорногорія",
		"ru-RU": "Черногория",
		"el-GR": "Μαυροβούνιο",
		"el-CY": "Μαυροβούνιο",
		"ro-RO": "Muntenegru",
		"ro-MD": "Muntenegru",
		"hu-HU": "Montenegró",
		"sq-AL": "Mal i Zi",
		"sq-XK": "Mal i Zi",
		"mt-MT": "il-Montenegro",
		"ga-IE": "Montainéagró",
		"cy-GB": "Montenegro",
		"gd-GB": "Am Monadh Neagrach",
		"lb-LU": "Montenegro",
		"ca-ES": "Montenegro",
		"ca-AD": "Montenegro",
		"ca-FR": "Montenegro",
		"ca-IT": "Montenegro",
		"eu-ES": "Montenegro",
		"eu-FR": "Montenegro",
		"gl-ES": "Montenegro",
		"tr-TR": "Karadağ",
		"tr-CY": "Karadağ"
	},
	"callingCode": "382",
	"phoneMasks": [
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
