import type { Country } from './types.js';

export const MNG = {
	"code": "MNG",
	"labels": {
		"pt-BR": "Mongólia",
		"pt-PT": "Mongólia",
		"qu-PE": "Mongolia",
		"qu-BO": "Mongolia",
		"qu-EC": "Mongolia",
		"chr-US": "ᎹᏂᎪᎵᎠ",
		"hi-IN": "मंगोलिया",
		"bn-IN": "মঙ্গোলিয়া",
		"bn-BD": "মঙ্গোলিয়া",
		"ta-IN": "மங்கோலியா",
		"ta-LK": "மங்கோலியா",
		"ta-SG": "மங்கோலியா",
		"ta-MY": "மங்கோலியா",
		"te-IN": "మంగోలియా",
		"mr-IN": "मंगोलिया",
		"gu-IN": "મંગોલિયા",
		"kn-IN": "ಮಂಗೋಲಿಯಾ",
		"ml-IN": "മംഗോളിയ",
		"pa-IN": "ਮੰਗੋਲੀਆ",
		"ur-IN": "منگولیا",
		"ur-PK": "منگولیا",
		"or-IN": "ମଙ୍ଗୋଲିଆ",
		"as-IN": "মঙ্গোলিয়া",
		"ne-IN": "मङ्गोलिया",
		"ne-NP": "मङ्गोलिया",
		"si-LK": "මොන්ගෝලියාව",
		"kok-IN": "मंगोलिया",
		"ks-IN": "مَنگولِیا",
		"brx-IN": "मंगलिया",
		"mai-IN": "मंगोलिया",
		"dz-BT": "སོག་པོ་ཡུལ",
		"ja-JP": "モンゴル",
		"ko-KR": "몽골",
		"ko-KP": "몽골",
		"zh-CN": "蒙古",
		"zh-Hans-CN": "蒙古",
		"zh-Hant-TW": "蒙古",
		"zh-TW": "蒙古",
		"zh-HK": "蒙古",
		"zh-MO": "蒙古",
		"zh-SG": "蒙古",
		"yue-Hant-HK": "蒙古",
		"yue-Hans-CN": "蒙古",
		"mn-MN": "Монгол",
		"ug-CN": "موڭغۇلىيە",
		"th-TH": "มองโกเลีย",
		"lo-LA": "ມອງໂກເລຍ",
		"km-KH": "ម៉ុងហ្គោលី",
		"my-MM": "မွန်ဂိုးလီးယား",
		"vi-VN": "Mông Cổ",
		"id-ID": "Mongolia",
		"ms-MY": "Mongolia",
		"ms-SG": "Mongolia",
		"ms-BN": "Mongolia",
		"jv-ID": "Mongolia",
		"fil-PH": "Mongolia",
		"ceb-PH": "Mongolia",
		"ka-GE": "მონღოლეთი",
		"hy-AM": "Մոնղոլիա",
		"az-AZ": "Monqolustan",
		"az-Cyrl-AZ": "Монголустан",
		"kk-KZ": "Моңғолия",
		"ky-KG": "Монголия",
		"uz-UZ": "Mongoliya",
		"tg-TJ": "Муғулистон",
		"tk-TM": "Mongoliýa",
		"fa-IR": "مغولستان",
		"fa-AF": "منگولیا",
		"ps-AF": "منګوليا",
		"ps-PK": "منګوليا",
		"he-IL": "מונגוליה",
		"ar-SA": "منغوليا",
		"ar-AE": "منغوليا",
		"ar-QA": "منغوليا",
		"ar-BH": "منغوليا",
		"ar-KW": "منغوليا",
		"ar-OM": "منغوليا",
		"ar-YE": "منغوليا",
		"ar-IQ": "منغوليا",
		"ar-JO": "منغوليا",
		"ar-LB": "منغوليا",
		"ar-SY": "منغوليا",
		"ar-PS": "منغوليا",
		"en-US": "Mongolia",
		"en-GB": "Mongolia",
		"en-IE": "Mongolia",
		"en-MT": "Mongolia",
		"en-GI": "Mongolia",
		"en-CY": "Mongolia",
		"en-JE": "Mongolia",
		"en-GG": "Mongolia",
		"en-IM": "Mongolia",
		"en-CA": "Mongolia",
		"en-AU": "Mongolia",
		"en-NZ": "Mongolia",
		"en-ZA": "Mongolia",
		"en-IN": "Mongolia",
		"en-SG": "Mongolia",
		"pt-AO": "Mongólia",
		"pt-MZ": "Mongólia",
		"pt-CV": "Mongólia",
		"pt-GW": "Mongólia",
		"pt-ST": "Mongólia",
		"pt-TL": "Mongólia",
		"pt-MO": "Mongólia",
		"es-ES": "Mongolia",
		"es-419": "Mongolia",
		"es-AD": "Mongolia",
		"es-GI": "Mongolia",
		"es-AR": "Mongolia",
		"es-BO": "Mongolia",
		"es-BR": "Mongolia",
		"es-BZ": "Mongolia",
		"es-CL": "Mongolia",
		"es-CO": "Mongolia",
		"es-CR": "Mongolia",
		"es-CU": "Mongolia",
		"es-DO": "Mongolia",
		"es-EC": "Mongolia",
		"es-GT": "Mongolia",
		"es-HN": "Mongolia",
		"es-MX": "Mongolia",
		"es-NI": "Mongolia",
		"es-PA": "Mongolia",
		"es-PE": "Mongolia",
		"es-PR": "Mongolia",
		"es-PY": "Mongolia",
		"es-SV": "Mongolia",
		"es-US": "Mongolia",
		"es-UY": "Mongolia",
		"es-VE": "Mongolia",
		"fr-FR": "Mongolie",
		"fr-BE": "Mongolie",
		"fr-CH": "Mongolie",
		"fr-LU": "Mongolie",
		"fr-MC": "Mongolie",
		"fr-AD": "Mongolie",
		"fr-CA": "Mongolie",
		"it-IT": "Mongolia",
		"it-CH": "Mongolia",
		"it-SM": "Mongolia",
		"it-VA": "Mongolia",
		"de-DE": "Mongolei",
		"de-AT": "Mongolei",
		"de-CH": "Mongolei",
		"de-BE": "Mongolei",
		"de-LI": "Mongolei",
		"de-LU": "Mongolei",
		"nl-NL": "Mongolië",
		"nl-BE": "Mongolië",
		"sv-SE": "Mongoliet",
		"sv-FI": "Mongoliet",
		"da-DK": "Mongoliet",
		"nb-NO": "Mongolia",
		"nn-NO": "Mongolia",
		"fi-FI": "Mongolia",
		"is-IS": "Mongólía",
		"fo-FO": "Mongolia",
		"et-EE": "Mongoolia",
		"lv-LV": "Mongolija",
		"lt-LT": "Mongolija",
		"pl-PL": "Mongolia",
		"cs-CZ": "Mongolsko",
		"sk-SK": "Mongolsko",
		"sl-SI": "Mongolija",
		"hr-HR": "Mongolija",
		"bs-BA": "Mongolija",
		"sr-RS": "Монголија",
		"sr-BA": "Монголија",
		"sr-ME": "Mongolija",
		"mk-MK": "Монголија",
		"bg-BG": "Монголия",
		"be-BY": "Манголія",
		"uk-UA": "Монголія",
		"ru-RU": "Монголия",
		"el-GR": "Μογγολία",
		"el-CY": "Μογγολία",
		"ro-RO": "Mongolia",
		"ro-MD": "Mongolia",
		"hu-HU": "Mongólia",
		"sq-AL": "Mongoli",
		"sq-XK": "Mongoli",
		"mt-MT": "il-Mongolja",
		"ga-IE": "an Mhongóil",
		"cy-GB": "Mongolia",
		"gd-GB": "Dùthaich nam Mongol",
		"lb-LU": "Mongolei",
		"ca-ES": "Mongòlia",
		"ca-AD": "Mongòlia",
		"ca-FR": "Mongòlia",
		"ca-IT": "Mongòlia",
		"eu-ES": "Mongolia",
		"eu-FR": "Mongolia",
		"gl-ES": "Mongolia",
		"tr-TR": "Moğolistan",
		"tr-CY": "Moğolistan"
	},
	"callingCode": "976",
	"phoneMasks": [
		{
			"mask": "## ## ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[12]1"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[5-9]"
			]
		},
		{
			"mask": "### ######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[12]2[1-3]"
			]
		},
		{
			"mask": "#### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[12](?:27|3[2-8]|4[2-68]|5[1-4689])",
				"[12](?:27|3[2-8]|4[2-68]|5[1-4689])[0-3]"
			]
		},
		{
			"mask": "##### #####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[12]"
			]
		}
	]
} satisfies Country;
