import type { Country } from './types.js';

export const MNG = {
	"code": "MNG",
	"labels": {
		"pt-BR": "Mongólia",
		"pt-PT": "Mongólia",
		"es-ES": "Mongolia",
		"es-419": "Mongolia",
		"es-AR": "Mongolia",
		"es-BO": "Mongolia",
		"es-BR": "Mongolia",
		"es-BZ": "Mongolia",
		"es-CL": "Mongolia",
		"es-CO": "Mongolia",
		"es-CR": "Mongolia",
		"es-CU": "Mongolia",
		"es-DO": "Mongolia",
		"es-EC": "Mongolia",
		"es-GT": "Mongolia",
		"es-HN": "Mongolia",
		"es-MX": "Mongolia",
		"es-NI": "Mongolia",
		"es-PA": "Mongolia",
		"es-PE": "Mongolia",
		"es-PR": "Mongolia",
		"es-PY": "Mongolia",
		"es-SV": "Mongolia",
		"es-US": "Mongolia",
		"es-UY": "Mongolia",
		"es-VE": "Mongolia",
		"en-US": "Mongolia",
		"fr-FR": "Mongolie",
		"fr-BE": "Mongolie",
		"fr-CA": "Mongolie",
		"fr-CH": "Mongolie",
		"fr-LU": "Mongolie",
		"fr-MC": "Mongolie",
		"it-IT": "Mongolia",
		"it-CH": "Mongolia",
		"it-SM": "Mongolia",
		"it-VA": "Mongolia",
		"de-DE": "Mongolei",
		"de-AT": "Mongolei",
		"de-CH": "Mongolei",
		"de-BE": "Mongolei",
		"de-LI": "Mongolei",
		"de-LU": "Mongolei"
	}
} satisfies Country;
