import type { Country } from './types.js';

export const MNP = {
	"code": "MNP",
	"labels": {
		"pt-BR": "Ilhas Marianas do Norte",
		"pt-PT": "Ilhas Marianas do Norte",
		"es-ES": "Islas Marianas del Norte",
		"es-419": "Islas Marianas del Norte",
		"es-AR": "Islas Marianas del Norte",
		"es-BO": "Islas Marianas del Norte",
		"es-BR": "Islas Marianas del Norte",
		"es-BZ": "Islas Marianas del Norte",
		"es-CL": "Islas Marianas del Norte",
		"es-CO": "Islas Marianas del Norte",
		"es-CR": "Islas Marianas del Norte",
		"es-CU": "Islas Marianas del Norte",
		"es-DO": "Islas Marianas del Norte",
		"es-EC": "Islas Marianas del Norte",
		"es-GT": "Islas Marianas del Norte",
		"es-HN": "Islas Marianas del Norte",
		"es-MX": "Islas Marianas del Norte",
		"es-NI": "Islas Marianas del Norte",
		"es-PA": "Islas Marianas del Norte",
		"es-PE": "Islas Marianas del Norte",
		"es-PR": "Islas Marianas del Norte",
		"es-PY": "Islas Marianas del Norte",
		"es-SV": "Islas Marianas del Norte",
		"es-US": "Islas Marianas del Norte",
		"es-UY": "Islas Marianas del Norte",
		"es-VE": "Islas Marianas del Norte",
		"en-US": "Northern Mariana Islands",
		"fr-FR": "Îles Mariannes du Nord",
		"fr-BE": "Îles Mariannes du Nord",
		"fr-CA": "Mariannes du Nord",
		"fr-CH": "Îles Mariannes du Nord",
		"fr-LU": "Îles Mariannes du Nord",
		"fr-MC": "Îles Mariannes du Nord",
		"it-IT": "Isole Marianne Settentrionali",
		"it-CH": "Isole Marianne Settentrionali",
		"it-SM": "Isole Marianne Settentrionali",
		"it-VA": "Isole Marianne Settentrionali",
		"de-DE": "Nördliche Marianen",
		"de-AT": "Nördliche Marianen",
		"de-CH": "Nördliche Marianen",
		"de-BE": "Nördliche Marianen",
		"de-LI": "Nördliche Marianen",
		"de-LU": "Nördliche Marianen"
	}
} satisfies Country;
