import type { Country } from './types.js';

export const MOZ = {
	"code": "MOZ",
	"labels": {
		"pt-BR": "Moçambique",
		"pt-PT": "Moçambique",
		"es-ES": "Mozambique",
		"es-419": "Mozambique",
		"es-AR": "Mozambique",
		"es-BO": "Mozambique",
		"es-BR": "Mozambique",
		"es-BZ": "Mozambique",
		"es-CL": "Mozambique",
		"es-CO": "Mozambique",
		"es-CR": "Mozambique",
		"es-CU": "Mozambique",
		"es-DO": "Mozambique",
		"es-EC": "Mozambique",
		"es-GT": "Mozambique",
		"es-HN": "Mozambique",
		"es-MX": "Mozambique",
		"es-NI": "Mozambique",
		"es-PA": "Mozambique",
		"es-PE": "Mozambique",
		"es-PR": "Mozambique",
		"es-PY": "Mozambique",
		"es-SV": "Mozambique",
		"es-US": "Mozambique",
		"es-UY": "Mozambique",
		"es-VE": "Mozambique",
		"en-US": "Mozambique",
		"fr-FR": "Mozambique",
		"fr-BE": "Mozambique",
		"fr-CA": "Mozambique",
		"fr-CH": "Mozambique",
		"fr-LU": "Mozambique",
		"fr-MC": "Mozambique",
		"it-IT": "Mozambico",
		"it-CH": "Mozambico",
		"it-SM": "Mozambico",
		"it-VA": "Mozambico",
		"de-DE": "Mosambik",
		"de-AT": "Mosambik",
		"de-CH": "Mosambik",
		"de-BE": "Mosambik",
		"de-LI": "Mosambik",
		"de-LU": "Mosambik"
	}
} satisfies Country;
