import type { Country } from './types.js';

export const MSR = {
	"code": "MSR",
	"labels": {
		"pt-BR": "Montserrat",
		"pt-PT": "Monserrate",
		"es-ES": "Montserrat",
		"es-419": "Montserrat",
		"es-AR": "Montserrat",
		"es-BO": "Montserrat",
		"es-BR": "Montserrat",
		"es-BZ": "Montserrat",
		"es-CL": "Montserrat",
		"es-CO": "Montserrat",
		"es-CR": "Montserrat",
		"es-CU": "Montserrat",
		"es-DO": "Montserrat",
		"es-EC": "Montserrat",
		"es-GT": "Montserrat",
		"es-HN": "Montserrat",
		"es-MX": "Montserrat",
		"es-NI": "Montserrat",
		"es-PA": "Montserrat",
		"es-PE": "Montserrat",
		"es-PR": "Montserrat",
		"es-PY": "Montserrat",
		"es-SV": "Montserrat",
		"es-US": "Montserrat",
		"es-UY": "Montserrat",
		"es-VE": "Montserrat",
		"en-US": "Montserrat",
		"fr-FR": "Montserrat",
		"fr-BE": "Montserrat",
		"fr-CA": "Montserrat",
		"fr-CH": "Montserrat",
		"fr-LU": "Montserrat",
		"fr-MC": "Montserrat",
		"it-IT": "Montserrat",
		"it-CH": "Montserrat",
		"it-SM": "Montserrat",
		"it-VA": "Montserrat",
		"de-DE": "Montserrat",
		"de-AT": "Montserrat",
		"de-CH": "Montserrat",
		"de-BE": "Montserrat",
		"de-LI": "Montserrat",
		"de-LU": "Montserrat"
	}
} satisfies Country;
