import type { Country } from './types.js';

export const MTQ = {
	"code": "MTQ",
	"labels": {
		"pt-BR": "Martinica",
		"pt-PT": "Martinica",
		"es-ES": "Martinica",
		"es-419": "Martinica",
		"es-AR": "Martinica",
		"es-BO": "Martinica",
		"es-BR": "Martinica",
		"es-BZ": "Martinica",
		"es-CL": "Martinica",
		"es-CO": "Martinica",
		"es-CR": "Martinica",
		"es-CU": "Martinica",
		"es-DO": "Martinica",
		"es-EC": "Martinica",
		"es-GT": "Martinica",
		"es-HN": "Martinica",
		"es-MX": "Martinica",
		"es-NI": "Martinica",
		"es-PA": "Martinica",
		"es-PE": "Martinica",
		"es-PR": "Martinica",
		"es-PY": "Martinica",
		"es-SV": "Martinica",
		"es-US": "Martinica",
		"es-UY": "Martinica",
		"es-VE": "Martinica",
		"en-US": "Martinique",
		"fr-FR": "Martinique",
		"fr-BE": "Martinique",
		"fr-CA": "Martinique",
		"fr-CH": "Martinique",
		"fr-LU": "Martinique",
		"fr-MC": "Martinique",
		"it-IT": "Martinica",
		"it-CH": "Martinica",
		"it-SM": "Martinica",
		"it-VA": "Martinica",
		"de-DE": "Martinique",
		"de-AT": "Martinique",
		"de-CH": "Martinique",
		"de-BE": "Martinique",
		"de-LI": "Martinique",
		"de-LU": "Martinique"
	},
	"callingCode": "596"
} satisfies Country;
