import type { Country } from './types.js';

export const MUS = {
	"code": "MUS",
	"labels": {
		"pt-BR": "Maurício",
		"pt-PT": "Maurícia",
		"qu-PE": "Mauricio",
		"qu-BO": "Mauricio",
		"qu-EC": "Mauricio",
		"chr-US": "ᎼᎵᏏᎥᏍ",
		"hi-IN": "मॉरीशस",
		"bn-IN": "মরিশাস",
		"bn-BD": "মরিশাস",
		"ta-IN": "மொரிசியஸ்",
		"ta-LK": "மொரிசியஸ்",
		"ta-SG": "மொரிசியஸ்",
		"ta-MY": "மொரிசியஸ்",
		"te-IN": "మారిషస్",
		"mr-IN": "मॉरिशस",
		"gu-IN": "મોરિશિયસ",
		"kn-IN": "ಮಾರಿಷಸ್",
		"ml-IN": "മൗറീഷ്യസ്",
		"pa-IN": "ਮੌਰੀਸ਼ਸ",
		"ur-IN": "ماریشس",
		"ur-PK": "ماریشس",
		"or-IN": "ମରିସସ",
		"as-IN": "মৰিছাছ",
		"ne-IN": "मौरिसियस",
		"ne-NP": "मौरिसियस",
		"si-LK": "මුරුසිය",
		"kok-IN": "मॉरिशस",
		"ks-IN": "مورِشَس",
		"brx-IN": "मरिसियास",
		"mai-IN": "मारीशस",
		"dz-BT": "མོ་རི་ཤཱས",
		"ja-JP": "モーリシャス",
		"ko-KR": "모리셔스",
		"ko-KP": "모리셔스",
		"zh-CN": "毛里求斯",
		"zh-Hans-CN": "毛里求斯",
		"zh-Hant-TW": "模里西斯",
		"zh-TW": "模里西斯",
		"zh-HK": "毛里裘斯",
		"zh-MO": "毛里裘斯",
		"zh-SG": "毛里求斯",
		"yue-Hant-HK": "模里西斯",
		"yue-Hans-CN": "模里西斯",
		"mn-MN": "Маврикий",
		"ug-CN": "ماۋرىتىيۇس",
		"th-TH": "มอริเชียส",
		"lo-LA": "ມົວຣິຊຽສ",
		"km-KH": "ម៉ូរីស",
		"my-MM": "မောရစ်ရှ",
		"vi-VN": "Mauritius",
		"id-ID": "Mauritius",
		"ms-MY": "Mauritius",
		"ms-SG": "Mauritius",
		"ms-BN": "Mauritius",
		"jv-ID": "Mauritius",
		"fil-PH": "Mauritius",
		"ceb-PH": "Mauritius",
		"ka-GE": "მავრიკი",
		"hy-AM": "Մավրիկիոս",
		"az-AZ": "Mavriki",
		"az-Cyrl-AZ": "Маврики",
		"kk-KZ": "Маврикий",
		"ky-KG": "Маврикий",
		"uz-UZ": "Mavrikiy",
		"tg-TJ": "Маврикий",
		"tk-TM": "Mawrikiý",
		"fa-IR": "موریس",
		"fa-AF": "موریس",
		"ps-AF": "موریشیس",
		"ps-PK": "موریشیس",
		"he-IL": "מאוריציוס",
		"ar-SA": "موريشيوس",
		"ar-AE": "موريشيوس",
		"ar-QA": "موريشيوس",
		"ar-BH": "موريشيوس",
		"ar-KW": "موريشيوس",
		"ar-OM": "موريشيوس",
		"ar-YE": "موريشيوس",
		"ar-IQ": "موريشيوس",
		"ar-JO": "موريشيوس",
		"ar-LB": "موريشيوس",
		"ar-SY": "موريشيوس",
		"ar-PS": "موريشيوس",
		"en-US": "Mauritius",
		"en-GB": "Mauritius",
		"en-IE": "Mauritius",
		"en-MT": "Mauritius",
		"en-GI": "Mauritius",
		"en-CY": "Mauritius",
		"en-JE": "Mauritius",
		"en-GG": "Mauritius",
		"en-IM": "Mauritius",
		"en-CA": "Mauritius",
		"en-AU": "Mauritius",
		"en-NZ": "Mauritius",
		"en-ZA": "Mauritius",
		"en-IN": "Mauritius",
		"en-SG": "Mauritius",
		"pt-AO": "Maurícia",
		"pt-MZ": "Maurícia",
		"pt-CV": "Maurícia",
		"pt-GW": "Maurícia",
		"pt-ST": "Maurícia",
		"pt-TL": "Maurícia",
		"pt-MO": "Maurícia",
		"es-ES": "Mauricio",
		"es-419": "Mauricio",
		"es-AD": "Mauricio",
		"es-GI": "Mauricio",
		"es-AR": "Mauricio",
		"es-BO": "Mauricio",
		"es-BR": "Mauricio",
		"es-BZ": "Mauricio",
		"es-CL": "Mauricio",
		"es-CO": "Mauricio",
		"es-CR": "Mauricio",
		"es-CU": "Mauricio",
		"es-DO": "Mauricio",
		"es-EC": "Mauricio",
		"es-GT": "Mauricio",
		"es-HN": "Mauricio",
		"es-MX": "Mauricio",
		"es-NI": "Mauricio",
		"es-PA": "Mauricio",
		"es-PE": "Mauricio",
		"es-PR": "Mauricio",
		"es-PY": "Mauricio",
		"es-SV": "Mauricio",
		"es-US": "Mauricio",
		"es-UY": "Mauricio",
		"es-VE": "Mauricio",
		"fr-FR": "Maurice",
		"fr-BE": "Maurice",
		"fr-CH": "Maurice",
		"fr-LU": "Maurice",
		"fr-MC": "Maurice",
		"fr-AD": "Maurice",
		"fr-CA": "Maurice",
		"it-IT": "Mauritius",
		"it-CH": "Mauritius",
		"it-SM": "Mauritius",
		"it-VA": "Mauritius",
		"de-DE": "Mauritius",
		"de-AT": "Mauritius",
		"de-CH": "Mauritius",
		"de-BE": "Mauritius",
		"de-LI": "Mauritius",
		"de-LU": "Mauritius",
		"nl-NL": "Mauritius",
		"nl-BE": "Mauritius",
		"sv-SE": "Mauritius",
		"sv-FI": "Mauritius",
		"da-DK": "Mauritius",
		"nb-NO": "Mauritius",
		"nn-NO": "Mauritius",
		"fi-FI": "Mauritius",
		"is-IS": "Máritíus",
		"fo-FO": "Móritius",
		"et-EE": "Mauritius",
		"lv-LV": "Maurīcija",
		"lt-LT": "Mauricijus",
		"pl-PL": "Mauritius",
		"cs-CZ": "Mauricius",
		"sk-SK": "Maurícius",
		"sl-SI": "Mauritius",
		"hr-HR": "Mauricijus",
		"bs-BA": "Mauricijus",
		"sr-RS": "Маурицијус",
		"sr-BA": "Маурицијус",
		"sr-ME": "Mauricijus",
		"mk-MK": "Маврициус",
		"bg-BG": "Мавриций",
		"be-BY": "Маўрыкій",
		"uk-UA": "Маврикій",
		"ru-RU": "Маврикий",
		"el-GR": "Μαυρίκιος",
		"el-CY": "Μαυρίκιος",
		"ro-RO": "Mauritius",
		"ro-MD": "Mauritius",
		"hu-HU": "Mauritius",
		"sq-AL": "Mauritius",
		"sq-XK": "Mauritius",
		"mt-MT": "Mauritius",
		"ga-IE": "Oileán Mhuirís",
		"cy-GB": "Mauritius",
		"gd-GB": "Na h-Eileanan Mhoiriseas",
		"lb-LU": "Mauritius",
		"ca-ES": "Maurici",
		"ca-AD": "Maurici",
		"ca-FR": "Maurici",
		"ca-IT": "Maurici",
		"eu-ES": "Maurizio",
		"eu-FR": "Maurizio",
		"gl-ES": "Mauricio",
		"tr-TR": "Mauritius",
		"tr-CY": "Mauritius"
	},
	"callingCode": "230",
	"phoneMasks": [
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-46]|8[013]"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[57]"
			]
		},
		{
			"mask": "##### #####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
