import type { Country } from './types.js';

export const MYS = {
	"code": "MYS",
	"labels": {
		"pt-BR": "Malásia",
		"pt-PT": "Malásia",
		"qu-PE": "Malasia",
		"qu-BO": "Malasia",
		"qu-EC": "Malasia",
		"chr-US": "ᎹᎴᏏᎢᎠ",
		"hi-IN": "मलेशिया",
		"bn-IN": "মালয়েশিয়া",
		"bn-BD": "মালয়েশিয়া",
		"ta-IN": "மலேசியா",
		"ta-LK": "மலேசியா",
		"ta-SG": "மலேசியா",
		"ta-MY": "மலேசியா",
		"te-IN": "మలేషియా",
		"mr-IN": "मलेशिया",
		"gu-IN": "મલેશિયા",
		"kn-IN": "ಮಲೇಶಿಯಾ",
		"ml-IN": "മലേഷ്യ",
		"pa-IN": "ਮਲੇਸ਼ੀਆ",
		"ur-IN": "ملائشیا",
		"ur-PK": "ملائشیا",
		"or-IN": "ମାଲେସିଆ",
		"as-IN": "মালয়েচিয়া",
		"ne-IN": "मलेसिया",
		"ne-NP": "मलेसिया",
		"si-LK": "මැලේසියාව",
		"kok-IN": "मलेशिया",
		"ks-IN": "مَلیشِیا",
		"brx-IN": "मालेशिया",
		"mai-IN": "मलेशिया",
		"dz-BT": "མ་ལེ་ཤི་ཡ",
		"ja-JP": "マレーシア",
		"ko-KR": "말레이시아",
		"ko-KP": "말레이시아",
		"zh-CN": "马来西亚",
		"zh-Hans-CN": "马来西亚",
		"zh-Hant-TW": "馬來西亞",
		"zh-TW": "馬來西亞",
		"zh-HK": "馬來西亞",
		"zh-MO": "馬來西亞",
		"zh-SG": "马来西亚",
		"yue-Hant-HK": "馬來西亞",
		"yue-Hans-CN": "马来西亚",
		"mn-MN": "Малайз",
		"ug-CN": "مالايسىيا",
		"th-TH": "มาเลเซีย",
		"lo-LA": "ມາເລເຊຍ",
		"km-KH": "ម៉ាឡេស៊ី",
		"my-MM": "မလေးရှား",
		"vi-VN": "Malaysia",
		"id-ID": "Malaysia",
		"ms-MY": "Malaysia",
		"ms-SG": "Malaysia",
		"ms-BN": "Malaysia",
		"jv-ID": "Malaysia",
		"fil-PH": "Malaysia",
		"ceb-PH": "Malaysia",
		"ka-GE": "მალაიზია",
		"hy-AM": "Մալայզիա",
		"az-AZ": "Malayziya",
		"az-Cyrl-AZ": "Малајзија",
		"kk-KZ": "Малайзия",
		"ky-KG": "Малайзия",
		"uz-UZ": "Malayziya",
		"tg-TJ": "Малайзия",
		"tk-TM": "Malaýziýa",
		"fa-IR": "مالزی",
		"fa-AF": "مالیزیا",
		"ps-AF": "مالیزیا",
		"ps-PK": "مالیزیا",
		"he-IL": "מלזיה",
		"ar-SA": "ماليزيا",
		"ar-AE": "ماليزيا",
		"ar-QA": "ماليزيا",
		"ar-BH": "ماليزيا",
		"ar-KW": "ماليزيا",
		"ar-OM": "ماليزيا",
		"ar-YE": "ماليزيا",
		"ar-IQ": "ماليزيا",
		"ar-JO": "ماليزيا",
		"ar-LB": "ماليزيا",
		"ar-SY": "ماليزيا",
		"ar-PS": "ماليزيا",
		"en-US": "Malaysia",
		"en-GB": "Malaysia",
		"en-IE": "Malaysia",
		"en-MT": "Malaysia",
		"en-GI": "Malaysia",
		"en-CY": "Malaysia",
		"en-JE": "Malaysia",
		"en-GG": "Malaysia",
		"en-IM": "Malaysia",
		"en-CA": "Malaysia",
		"en-AU": "Malaysia",
		"en-NZ": "Malaysia",
		"en-ZA": "Malaysia",
		"en-IN": "Malaysia",
		"en-SG": "Malaysia",
		"pt-AO": "Malásia",
		"pt-MZ": "Malásia",
		"pt-CV": "Malásia",
		"pt-GW": "Malásia",
		"pt-ST": "Malásia",
		"pt-TL": "Malásia",
		"pt-MO": "Malásia",
		"es-ES": "Malasia",
		"es-419": "Malasia",
		"es-AD": "Malasia",
		"es-GI": "Malasia",
		"es-AR": "Malasia",
		"es-BO": "Malasia",
		"es-BR": "Malasia",
		"es-BZ": "Malasia",
		"es-CL": "Malasia",
		"es-CO": "Malasia",
		"es-CR": "Malasia",
		"es-CU": "Malasia",
		"es-DO": "Malasia",
		"es-EC": "Malasia",
		"es-GT": "Malasia",
		"es-HN": "Malasia",
		"es-MX": "Malasia",
		"es-NI": "Malasia",
		"es-PA": "Malasia",
		"es-PE": "Malasia",
		"es-PR": "Malasia",
		"es-PY": "Malasia",
		"es-SV": "Malasia",
		"es-US": "Malasia",
		"es-UY": "Malasia",
		"es-VE": "Malasia",
		"fr-FR": "Malaisie",
		"fr-BE": "Malaisie",
		"fr-CH": "Malaisie",
		"fr-LU": "Malaisie",
		"fr-MC": "Malaisie",
		"fr-AD": "Malaisie",
		"fr-CA": "Malaisie",
		"it-IT": "Malaysia",
		"it-CH": "Malaysia",
		"it-SM": "Malaysia",
		"it-VA": "Malaysia",
		"de-DE": "Malaysia",
		"de-AT": "Malaysia",
		"de-CH": "Malaysia",
		"de-BE": "Malaysia",
		"de-LI": "Malaysia",
		"de-LU": "Malaysia",
		"nl-NL": "Maleisië",
		"nl-BE": "Maleisië",
		"sv-SE": "Malaysia",
		"sv-FI": "Malaysia",
		"da-DK": "Malaysia",
		"nb-NO": "Malaysia",
		"nn-NO": "Malaysia",
		"fi-FI": "Malesia",
		"is-IS": "Malasía",
		"fo-FO": "Malaisia",
		"et-EE": "Malaisia",
		"lv-LV": "Malaizija",
		"lt-LT": "Malaizija",
		"pl-PL": "Malezja",
		"cs-CZ": "Malajsie",
		"sk-SK": "Malajzia",
		"sl-SI": "Malezija",
		"hr-HR": "Malezija",
		"bs-BA": "Malezija",
		"sr-RS": "Малезија",
		"sr-BA": "Малезија",
		"sr-ME": "Malezija",
		"mk-MK": "Малезија",
		"bg-BG": "Малайзия",
		"be-BY": "Малайзія",
		"uk-UA": "Малайзія",
		"ru-RU": "Малайзия",
		"el-GR": "Μαλαισία",
		"el-CY": "Μαλαισία",
		"ro-RO": "Malaysia",
		"ro-MD": "Malaysia",
		"hu-HU": "Malajzia",
		"sq-AL": "Malajzi",
		"sq-XK": "Malajzi",
		"mt-MT": "il-Malasja",
		"ga-IE": "an Mhalaeisia",
		"cy-GB": "Malaysia",
		"gd-GB": "Malaidhsea",
		"lb-LU": "Malaysia",
		"ca-ES": "Malàisia",
		"ca-AD": "Malàisia",
		"ca-FR": "Malàisia",
		"ca-IT": "Malàisia",
		"eu-ES": "Malaysia",
		"eu-FR": "Malaysia",
		"gl-ES": "Malaisia",
		"tr-TR": "Malezya",
		"tr-CY": "Malezya"
	},
	"callingCode": "60",
	"phoneMasks": [
		{
			"mask": "#-### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[4-79]"
			]
		},
		{
			"mask": "#-#### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"3"
			]
		},
		{
			"mask": "##-### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1(?:[02469]|[378][1-9]|53)|8",
				"1(?:[02469]|[37][1-9]|53|8(?:[1-46-9]|5[7-9]))|8"
			]
		},
		{
			"mask": "#-###-##-####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1(?:[367]|80)"
			]
		},
		{
			"mask": "##-#### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "###-### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"15"
			]
		}
	]
} satisfies Country;
