import type { Country } from './types.js';

export const MYT = {
	"code": "MYT",
	"labels": {
		"pt-BR": "Mayotte",
		"pt-PT": "Maiote",
		"es-ES": "Mayotte",
		"es-419": "Mayotte",
		"es-AR": "Mayotte",
		"es-BO": "Mayotte",
		"es-BR": "Mayotte",
		"es-BZ": "Mayotte",
		"es-CL": "Mayotte",
		"es-CO": "Mayotte",
		"es-CR": "Mayotte",
		"es-CU": "Mayotte",
		"es-DO": "Mayotte",
		"es-EC": "Mayotte",
		"es-GT": "Mayotte",
		"es-HN": "Mayotte",
		"es-MX": "Mayotte",
		"es-NI": "Mayotte",
		"es-PA": "Mayotte",
		"es-PE": "Mayotte",
		"es-PR": "Mayotte",
		"es-PY": "Mayotte",
		"es-SV": "Mayotte",
		"es-US": "Mayotte",
		"es-UY": "Mayotte",
		"es-VE": "Mayotte",
		"en-US": "Mayotte",
		"fr-FR": "Mayotte",
		"fr-BE": "Mayotte",
		"fr-CA": "Mayotte",
		"fr-CH": "Mayotte",
		"fr-LU": "Mayotte",
		"fr-MC": "Mayotte",
		"it-IT": "Mayotte",
		"it-CH": "Mayotte",
		"it-SM": "Mayotte",
		"it-VA": "Mayotte",
		"de-DE": "Mayotte",
		"de-AT": "Mayotte",
		"de-CH": "Mayotte",
		"de-BE": "Mayotte",
		"de-LI": "Mayotte",
		"de-LU": "Mayotte"
	},
	"callingCode": "262"
} satisfies Country;
