import type { Country } from './types.js';

export const NAM = {
	"code": "NAM",
	"labels": {
		"pt-BR": "Namíbia",
		"pt-PT": "Namíbia",
		"es-ES": "Namibia",
		"es-419": "Namibia",
		"es-AR": "Namibia",
		"es-BO": "Namibia",
		"es-BR": "Namibia",
		"es-BZ": "Namibia",
		"es-CL": "Namibia",
		"es-CO": "Namibia",
		"es-CR": "Namibia",
		"es-CU": "Namibia",
		"es-DO": "Namibia",
		"es-EC": "Namibia",
		"es-GT": "Namibia",
		"es-HN": "Namibia",
		"es-MX": "Namibia",
		"es-NI": "Namibia",
		"es-PA": "Namibia",
		"es-PE": "Namibia",
		"es-PR": "Namibia",
		"es-PY": "Namibia",
		"es-SV": "Namibia",
		"es-US": "Namibia",
		"es-UY": "Namibia",
		"es-VE": "Namibia",
		"en-US": "Namibia",
		"fr-FR": "Namibie",
		"fr-BE": "Namibie",
		"fr-CA": "Namibie",
		"fr-CH": "Namibie",
		"fr-LU": "Namibie",
		"fr-MC": "Namibie",
		"it-IT": "Namibia",
		"it-CH": "Namibia",
		"it-SM": "Namibia",
		"it-VA": "Namibia",
		"de-DE": "Namibia",
		"de-AT": "Namibia",
		"de-CH": "Namibia",
		"de-BE": "Namibia",
		"de-LI": "Namibia",
		"de-LU": "Namibia"
	}
} satisfies Country;
