import type { Country } from './types.js';

export const NAM = {
	"code": "NAM",
	"labels": {
		"pt-BR": "Namíbia",
		"pt-PT": "Namíbia",
		"qu-PE": "Namibia",
		"qu-BO": "Namibia",
		"qu-EC": "Namibia",
		"chr-US": "ᎾᎻᏈᎢᏯ",
		"hi-IN": "नामीबिया",
		"bn-IN": "নামিবিয়া",
		"bn-BD": "নামিবিয়া",
		"ta-IN": "நமீபியா",
		"ta-LK": "நமீபியா",
		"ta-SG": "நமீபியா",
		"ta-MY": "நமீபியா",
		"te-IN": "నమీబియా",
		"mr-IN": "नामिबिया",
		"gu-IN": "નામિબિયા",
		"kn-IN": "ನಮೀಬಿಯಾ",
		"ml-IN": "നമീബിയ",
		"pa-IN": "ਨਾਮੀਬੀਆ",
		"ur-IN": "نامیبیا",
		"ur-PK": "نامیبیا",
		"or-IN": "ନାମିବିଆ",
		"as-IN": "নামিবিয়া",
		"ne-IN": "नामिबिया",
		"ne-NP": "नामिबिया",
		"si-LK": "නැමීබියාව",
		"kok-IN": "नामीबिया",
		"ks-IN": "نامِبِیا",
		"brx-IN": "नामीबिया",
		"mai-IN": "नामीबिया",
		"dz-BT": "ན་མི་བི་ཡ",
		"ja-JP": "ナミビア",
		"ko-KR": "나미비아",
		"ko-KP": "나미비아",
		"zh-CN": "纳米比亚",
		"zh-Hans-CN": "纳米比亚",
		"zh-Hant-TW": "納米比亞",
		"zh-TW": "納米比亞",
		"zh-HK": "納米比亞",
		"zh-MO": "納米比亞",
		"zh-SG": "纳米比亚",
		"yue-Hant-HK": "納米比亞",
		"yue-Hans-CN": "纳米比亚",
		"mn-MN": "Намиби",
		"ug-CN": "نامىبىيە",
		"th-TH": "นามิเบีย",
		"lo-LA": "ນາມີເບຍ",
		"km-KH": "ណាមីប៊ី",
		"my-MM": "နမီးဘီးယား",
		"vi-VN": "Namibia",
		"id-ID": "Namibia",
		"ms-MY": "Namibia",
		"ms-SG": "Namibia",
		"ms-BN": "Namibia",
		"jv-ID": "Namibia",
		"fil-PH": "Namibia",
		"ceb-PH": "Namibia",
		"ka-GE": "ნამიბია",
		"hy-AM": "Նամիբիա",
		"az-AZ": "Namibiya",
		"az-Cyrl-AZ": "Намибија",
		"kk-KZ": "Намибия",
		"ky-KG": "Намибия",
		"uz-UZ": "Namibiya",
		"tg-TJ": "Намибия",
		"tk-TM": "Namibiýa",
		"fa-IR": "نامیبیا",
		"fa-AF": "نامیبیا",
		"ps-AF": "نیمبیا",
		"ps-PK": "نیمبیا",
		"he-IL": "נמיביה",
		"ar-SA": "ناميبيا",
		"ar-AE": "ناميبيا",
		"ar-QA": "ناميبيا",
		"ar-BH": "ناميبيا",
		"ar-KW": "ناميبيا",
		"ar-OM": "ناميبيا",
		"ar-YE": "ناميبيا",
		"ar-IQ": "ناميبيا",
		"ar-JO": "ناميبيا",
		"ar-LB": "ناميبيا",
		"ar-SY": "ناميبيا",
		"ar-PS": "ناميبيا",
		"en-US": "Namibia",
		"en-GB": "Namibia",
		"en-IE": "Namibia",
		"en-MT": "Namibia",
		"en-GI": "Namibia",
		"en-CY": "Namibia",
		"en-JE": "Namibia",
		"en-GG": "Namibia",
		"en-IM": "Namibia",
		"en-CA": "Namibia",
		"en-AU": "Namibia",
		"en-NZ": "Namibia",
		"en-ZA": "Namibia",
		"en-IN": "Namibia",
		"en-SG": "Namibia",
		"pt-AO": "Namíbia",
		"pt-MZ": "Namíbia",
		"pt-CV": "Namíbia",
		"pt-GW": "Namíbia",
		"pt-ST": "Namíbia",
		"pt-TL": "Namíbia",
		"pt-MO": "Namíbia",
		"es-ES": "Namibia",
		"es-419": "Namibia",
		"es-AD": "Namibia",
		"es-GI": "Namibia",
		"es-AR": "Namibia",
		"es-BO": "Namibia",
		"es-BR": "Namibia",
		"es-BZ": "Namibia",
		"es-CL": "Namibia",
		"es-CO": "Namibia",
		"es-CR": "Namibia",
		"es-CU": "Namibia",
		"es-DO": "Namibia",
		"es-EC": "Namibia",
		"es-GT": "Namibia",
		"es-HN": "Namibia",
		"es-MX": "Namibia",
		"es-NI": "Namibia",
		"es-PA": "Namibia",
		"es-PE": "Namibia",
		"es-PR": "Namibia",
		"es-PY": "Namibia",
		"es-SV": "Namibia",
		"es-US": "Namibia",
		"es-UY": "Namibia",
		"es-VE": "Namibia",
		"fr-FR": "Namibie",
		"fr-BE": "Namibie",
		"fr-CH": "Namibie",
		"fr-LU": "Namibie",
		"fr-MC": "Namibie",
		"fr-AD": "Namibie",
		"fr-CA": "Namibie",
		"it-IT": "Namibia",
		"it-CH": "Namibia",
		"it-SM": "Namibia",
		"it-VA": "Namibia",
		"de-DE": "Namibia",
		"de-AT": "Namibia",
		"de-CH": "Namibia",
		"de-BE": "Namibia",
		"de-LI": "Namibia",
		"de-LU": "Namibia",
		"nl-NL": "Namibië",
		"nl-BE": "Namibië",
		"sv-SE": "Namibia",
		"sv-FI": "Namibia",
		"da-DK": "Namibia",
		"nb-NO": "Namibia",
		"nn-NO": "Namibia",
		"fi-FI": "Namibia",
		"is-IS": "Namibía",
		"fo-FO": "Namibia",
		"et-EE": "Namiibia",
		"lv-LV": "Namībija",
		"lt-LT": "Namibija",
		"pl-PL": "Namibia",
		"cs-CZ": "Namibie",
		"sk-SK": "Namíbia",
		"sl-SI": "Namibija",
		"hr-HR": "Namibija",
		"bs-BA": "Namibija",
		"sr-RS": "Намибија",
		"sr-BA": "Намибија",
		"sr-ME": "Namibija",
		"mk-MK": "Намибија",
		"bg-BG": "Намибия",
		"be-BY": "Намібія",
		"uk-UA": "Намібія",
		"ru-RU": "Намибия",
		"el-GR": "Ναμίμπια",
		"el-CY": "Ναμίμπια",
		"ro-RO": "Namibia",
		"ro-MD": "Namibia",
		"hu-HU": "Namíbia",
		"sq-AL": "Namibi",
		"sq-XK": "Namibi",
		"mt-MT": "in-Namibja",
		"ga-IE": "an Namaib",
		"cy-GB": "Namibia",
		"gd-GB": "An Namaib",
		"lb-LU": "Namibia",
		"ca-ES": "Namíbia",
		"ca-AD": "Namíbia",
		"ca-FR": "Namíbia",
		"ca-IT": "Namíbia",
		"eu-ES": "Namibia",
		"eu-FR": "Namibia",
		"gl-ES": "Namibia",
		"tr-TR": "Namibya",
		"tr-CY": "Namibya"
	},
	"callingCode": "264",
	"phoneMasks": [
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"88"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"6"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"87"
			]
		}
	]
} satisfies Country;
