import type { Country } from './types.js';

export const NCL = {
	"code": "NCL",
	"labels": {
		"pt-BR": "Nova Caledônia",
		"pt-PT": "Nova Caledónia",
		"es-ES": "Nueva Caledonia",
		"es-419": "Nueva Caledonia",
		"es-AR": "Nueva Caledonia",
		"es-BO": "Nueva Caledonia",
		"es-BR": "Nueva Caledonia",
		"es-BZ": "Nueva Caledonia",
		"es-CL": "Nueva Caledonia",
		"es-CO": "Nueva Caledonia",
		"es-CR": "Nueva Caledonia",
		"es-CU": "Nueva Caledonia",
		"es-DO": "Nueva Caledonia",
		"es-EC": "Nueva Caledonia",
		"es-GT": "Nueva Caledonia",
		"es-HN": "Nueva Caledonia",
		"es-MX": "Nueva Caledonia",
		"es-NI": "Nueva Caledonia",
		"es-PA": "Nueva Caledonia",
		"es-PE": "Nueva Caledonia",
		"es-PR": "Nueva Caledonia",
		"es-PY": "Nueva Caledonia",
		"es-SV": "Nueva Caledonia",
		"es-US": "Nueva Caledonia",
		"es-UY": "Nueva Caledonia",
		"es-VE": "Nueva Caledonia",
		"en-US": "New Caledonia",
		"fr-FR": "Nouvelle-Calédonie",
		"fr-BE": "Nouvelle-Calédonie",
		"fr-CA": "Nouvelle-Calédonie",
		"fr-CH": "Nouvelle-Calédonie",
		"fr-LU": "Nouvelle-Calédonie",
		"fr-MC": "Nouvelle-Calédonie",
		"it-IT": "Nuova Caledonia",
		"it-CH": "Nuova Caledonia",
		"it-SM": "Nuova Caledonia",
		"it-VA": "Nuova Caledonia",
		"de-DE": "Neukaledonien",
		"de-AT": "Neukaledonien",
		"de-CH": "Neukaledonien",
		"de-BE": "Neukaledonien",
		"de-LI": "Neukaledonien",
		"de-LU": "Neukaledonien"
	},
	"callingCode": "687"
} satisfies Country;
