import type { Country } from './types.js';

export const NFK = {
	"code": "NFK",
	"labels": {
		"pt-BR": "Ilha Norfolk",
		"pt-PT": "Ilha Norfolk",
		"es-ES": "Isla Norfolk",
		"es-419": "Isla Norfolk",
		"es-AR": "Isla Norfolk",
		"es-BO": "Isla Norfolk",
		"es-BR": "Isla Norfolk",
		"es-BZ": "Isla Norfolk",
		"es-CL": "Isla Norfolk",
		"es-CO": "Isla Norfolk",
		"es-CR": "Isla Norfolk",
		"es-CU": "Isla Norfolk",
		"es-DO": "Isla Norfolk",
		"es-EC": "Isla Norfolk",
		"es-GT": "Isla Norfolk",
		"es-HN": "Isla Norfolk",
		"es-MX": "Isla Norfolk",
		"es-NI": "Isla Norfolk",
		"es-PA": "Isla Norfolk",
		"es-PE": "Isla Norfolk",
		"es-PR": "Isla Norfolk",
		"es-PY": "Isla Norfolk",
		"es-SV": "Isla Norfolk",
		"es-US": "Isla Norfolk",
		"es-UY": "Isla Norfolk",
		"es-VE": "Isla Norfolk",
		"en-US": "Norfolk Island",
		"fr-FR": "Île Norfolk",
		"fr-BE": "Île Norfolk",
		"fr-CA": "île Norfolk",
		"fr-CH": "Île Norfolk",
		"fr-LU": "Île Norfolk",
		"fr-MC": "Île Norfolk",
		"it-IT": "Isola Norfolk",
		"it-CH": "Isola Norfolk",
		"it-SM": "Isola Norfolk",
		"it-VA": "Isola Norfolk",
		"de-DE": "Norfolkinsel",
		"de-AT": "Norfolkinsel",
		"de-CH": "Norfolkinsel",
		"de-BE": "Norfolkinsel",
		"de-LI": "Norfolkinsel",
		"de-LU": "Norfolkinsel"
	}
} satisfies Country;
