import type { Country } from './types.js';

export const NIC = {
	"code": "NIC",
	"labels": {
		"pt-BR": "Nicarágua",
		"pt-PT": "Nicarágua",
		"es-ES": "Nicaragua",
		"es-419": "Nicaragua",
		"es-AR": "Nicaragua",
		"es-BO": "Nicaragua",
		"es-BR": "Nicaragua",
		"es-BZ": "Nicaragua",
		"es-CL": "Nicaragua",
		"es-CO": "Nicaragua",
		"es-CR": "Nicaragua",
		"es-CU": "Nicaragua",
		"es-DO": "Nicaragua",
		"es-EC": "Nicaragua",
		"es-GT": "Nicaragua",
		"es-HN": "Nicaragua",
		"es-MX": "Nicaragua",
		"es-NI": "Nicaragua",
		"es-PA": "Nicaragua",
		"es-PE": "Nicaragua",
		"es-PR": "Nicaragua",
		"es-PY": "Nicaragua",
		"es-SV": "Nicaragua",
		"es-US": "Nicaragua",
		"es-UY": "Nicaragua",
		"es-VE": "Nicaragua",
		"en-US": "Nicaragua",
		"fr-FR": "Nicaragua",
		"fr-BE": "Nicaragua",
		"fr-CA": "Nicaragua",
		"fr-CH": "Nicaragua",
		"fr-LU": "Nicaragua",
		"fr-MC": "Nicaragua",
		"it-IT": "Nicaragua",
		"it-CH": "Nicaragua",
		"it-SM": "Nicaragua",
		"it-VA": "Nicaragua",
		"de-DE": "Nicaragua",
		"de-AT": "Nicaragua",
		"de-CH": "Nicaragua",
		"de-BE": "Nicaragua",
		"de-LI": "Nicaragua",
		"de-LU": "Nicaragua"
	}
} satisfies Country;
