import type { Country } from './types.js';

export const NIU = {
	"code": "NIU",
	"labels": {
		"pt-BR": "Niue",
		"pt-PT": "Niuê",
		"es-ES": "Niue",
		"es-419": "Niue",
		"es-AR": "Niue",
		"es-BO": "Niue",
		"es-BR": "Niue",
		"es-BZ": "Niue",
		"es-CL": "Niue",
		"es-CO": "Niue",
		"es-CR": "Niue",
		"es-CU": "Niue",
		"es-DO": "Niue",
		"es-EC": "Niue",
		"es-GT": "Niue",
		"es-HN": "Niue",
		"es-MX": "Niue",
		"es-NI": "Niue",
		"es-PA": "Niue",
		"es-PE": "Niue",
		"es-PR": "Niue",
		"es-PY": "Niue",
		"es-SV": "Niue",
		"es-US": "Niue",
		"es-UY": "Niue",
		"es-VE": "Niue",
		"en-US": "Niue",
		"fr-FR": "Niue",
		"fr-BE": "Niue",
		"fr-CA": "Niue",
		"fr-CH": "Niue",
		"fr-LU": "Niue",
		"fr-MC": "Niue",
		"it-IT": "Niue",
		"it-CH": "Niue",
		"it-SM": "Niue",
		"it-VA": "Niue",
		"de-DE": "Niue",
		"de-AT": "Niue",
		"de-CH": "Niue",
		"de-BE": "Niue",
		"de-LI": "Niue",
		"de-LU": "Niue"
	},
	"callingCode": "683"
} satisfies Country;
