import type { Country } from './types.js';

export const NLD = {
	"code": "NLD",
	"labels": {
		"pt-BR": "Países Baixos",
		"pt-PT": "Países Baixos",
		"es-ES": "Países Bajos",
		"es-419": "Países Bajos",
		"es-AR": "Países Bajos",
		"es-BO": "Países Bajos",
		"es-BR": "Países Bajos",
		"es-BZ": "Países Bajos",
		"es-CL": "Países Bajos",
		"es-CO": "Países Bajos",
		"es-CR": "Países Bajos",
		"es-CU": "Países Bajos",
		"es-DO": "Países Bajos",
		"es-EC": "Países Bajos",
		"es-GT": "Países Bajos",
		"es-HN": "Países Bajos",
		"es-MX": "Países Bajos",
		"es-NI": "Países Bajos",
		"es-PA": "Países Bajos",
		"es-PE": "Países Bajos",
		"es-PR": "Países Bajos",
		"es-PY": "Países Bajos",
		"es-SV": "Países Bajos",
		"es-US": "Países Bajos",
		"es-UY": "Países Bajos",
		"es-VE": "Países Bajos",
		"en-US": "Netherlands",
		"fr-FR": "Pays-Bas",
		"fr-BE": "Pays-Bas",
		"fr-CA": "Pays-Bas",
		"fr-CH": "Pays-Bas",
		"fr-LU": "Pays-Bas",
		"fr-MC": "Pays-Bas",
		"it-IT": "Paesi Bassi",
		"it-CH": "Paesi Bassi",
		"it-SM": "Paesi Bassi",
		"it-VA": "Paesi Bassi",
		"de-DE": "Niederlande",
		"de-AT": "Niederlande",
		"de-CH": "Niederlande",
		"de-BE": "Niederlande",
		"de-LI": "Niederlande",
		"de-LU": "Niederlande"
	},
	"callingCode": "31"
} satisfies Country;
