import type { Country } from './types.js';

export const NLD = {
	"code": "NLD",
	"labels": {
		"pt-BR": "Países Baixos",
		"pt-PT": "Países Baixos",
		"qu-PE": "Países Bajos",
		"qu-BO": "Países Bajos",
		"qu-EC": "Países Bajos",
		"chr-US": "ᏁᏛᎳᏂ",
		"hi-IN": "नीदरलैंड",
		"bn-IN": "নেদারল্যান্ডস",
		"bn-BD": "নেদারল্যান্ডস",
		"ta-IN": "நெதர்லாந்து",
		"ta-LK": "நெதர்லாந்து",
		"ta-SG": "நெதர்லாந்து",
		"ta-MY": "நெதர்லாந்து",
		"te-IN": "నెదర్లాండ్స్",
		"mr-IN": "नेदरलँड",
		"gu-IN": "નેધરલેન્ડ્સ",
		"kn-IN": "ನೆದರ್‌ಲ್ಯಾಂಡ್ಸ್",
		"ml-IN": "നെതർലാൻഡ്‌സ്",
		"pa-IN": "ਨੀਦਰਲੈਂਡ",
		"ur-IN": "نیدر لینڈز",
		"ur-PK": "نیدر لینڈز",
		"or-IN": "ନେଦରଲ୍ୟାଣ୍ଡ",
		"as-IN": "নেডাৰলেণ্ড",
		"ne-IN": "नेदरल्याण्ड",
		"ne-NP": "नेदरल्याण्ड",
		"si-LK": "නෙදර්ලන්තය",
		"kok-IN": "नॅदरलँड",
		"ks-IN": "نیٖدَرلینڑ",
		"brx-IN": "नेदारलेण्ड",
		"mai-IN": "नीदरलैंड",
		"dz-BT": "ནེ་དར་ལནཌས྄",
		"ja-JP": "オランダ",
		"ko-KR": "네덜란드",
		"ko-KP": "네덜란드",
		"zh-CN": "荷兰",
		"zh-Hans-CN": "荷兰",
		"zh-Hant-TW": "荷蘭",
		"zh-TW": "荷蘭",
		"zh-HK": "荷蘭",
		"zh-MO": "荷蘭",
		"zh-SG": "荷兰",
		"yue-Hant-HK": "荷蘭",
		"yue-Hans-CN": "荷兰",
		"mn-MN": "Нидерланд",
		"ug-CN": "گوللاندىيە",
		"th-TH": "เนเธอร์แลนด์",
		"lo-LA": "ເນເທີແລນ",
		"km-KH": "ហូឡង់",
		"my-MM": "နယ်သာလန်",
		"vi-VN": "Hà Lan",
		"id-ID": "Belanda",
		"ms-MY": "Belanda",
		"ms-SG": "Belanda",
		"ms-BN": "Belanda",
		"jv-ID": "Walanda",
		"fil-PH": "Netherlands",
		"ceb-PH": "Netherlands",
		"ka-GE": "ნიდერლანდები",
		"hy-AM": "Նիդեռլանդներ",
		"az-AZ": "Niderland",
		"az-Cyrl-AZ": "Нидерланд",
		"kk-KZ": "Нидерланд",
		"ky-KG": "Нидерланд",
		"uz-UZ": "Niderlandiya",
		"tg-TJ": "Нидерландия",
		"tk-TM": "Niderlandlar",
		"fa-IR": "هلند",
		"fa-AF": "هالند",
		"ps-AF": "هالېنډ",
		"ps-PK": "هالېنډ",
		"he-IL": "הולנד",
		"ar-SA": "هولندا",
		"ar-AE": "هولندا",
		"ar-QA": "هولندا",
		"ar-BH": "هولندا",
		"ar-KW": "هولندا",
		"ar-OM": "هولندا",
		"ar-YE": "هولندا",
		"ar-IQ": "هولندا",
		"ar-JO": "هولندا",
		"ar-LB": "هولندا",
		"ar-SY": "هولندا",
		"ar-PS": "هولندا",
		"en-US": "Netherlands",
		"en-GB": "Netherlands",
		"en-IE": "Netherlands",
		"en-MT": "Netherlands",
		"en-GI": "Netherlands",
		"en-CY": "Netherlands",
		"en-JE": "Netherlands",
		"en-GG": "Netherlands",
		"en-IM": "Netherlands",
		"en-CA": "Netherlands",
		"en-AU": "Netherlands",
		"en-NZ": "Netherlands",
		"en-ZA": "Netherlands",
		"en-IN": "Netherlands",
		"en-SG": "Netherlands",
		"pt-AO": "Países Baixos",
		"pt-MZ": "Países Baixos",
		"pt-CV": "Países Baixos",
		"pt-GW": "Países Baixos",
		"pt-ST": "Países Baixos",
		"pt-TL": "Países Baixos",
		"pt-MO": "Países Baixos",
		"es-ES": "Países Bajos",
		"es-419": "Países Bajos",
		"es-AD": "Países Bajos",
		"es-GI": "Países Bajos",
		"es-AR": "Países Bajos",
		"es-BO": "Países Bajos",
		"es-BR": "Países Bajos",
		"es-BZ": "Países Bajos",
		"es-CL": "Países Bajos",
		"es-CO": "Países Bajos",
		"es-CR": "Países Bajos",
		"es-CU": "Países Bajos",
		"es-DO": "Países Bajos",
		"es-EC": "Países Bajos",
		"es-GT": "Países Bajos",
		"es-HN": "Países Bajos",
		"es-MX": "Países Bajos",
		"es-NI": "Países Bajos",
		"es-PA": "Países Bajos",
		"es-PE": "Países Bajos",
		"es-PR": "Países Bajos",
		"es-PY": "Países Bajos",
		"es-SV": "Países Bajos",
		"es-US": "Países Bajos",
		"es-UY": "Países Bajos",
		"es-VE": "Países Bajos",
		"fr-FR": "Pays-Bas",
		"fr-BE": "Pays-Bas",
		"fr-CH": "Pays-Bas",
		"fr-LU": "Pays-Bas",
		"fr-MC": "Pays-Bas",
		"fr-AD": "Pays-Bas",
		"fr-CA": "Pays-Bas",
		"it-IT": "Paesi Bassi",
		"it-CH": "Paesi Bassi",
		"it-SM": "Paesi Bassi",
		"it-VA": "Paesi Bassi",
		"de-DE": "Niederlande",
		"de-AT": "Niederlande",
		"de-CH": "Niederlande",
		"de-BE": "Niederlande",
		"de-LI": "Niederlande",
		"de-LU": "Niederlande",
		"nl-NL": "Nederland",
		"nl-BE": "Nederland",
		"sv-SE": "Nederländerna",
		"sv-FI": "Nederländerna",
		"da-DK": "Nederlandene",
		"nb-NO": "Nederland",
		"nn-NO": "Nederland",
		"fi-FI": "Alankomaat",
		"is-IS": "Holland",
		"fo-FO": "Niðurlond",
		"et-EE": "Holland",
		"lv-LV": "Nīderlande",
		"lt-LT": "Nyderlandai",
		"pl-PL": "Holandia",
		"cs-CZ": "Nizozemsko",
		"sk-SK": "Holandsko",
		"sl-SI": "Nizozemska",
		"hr-HR": "Nizozemska",
		"bs-BA": "Nizozemska",
		"sr-RS": "Холандија",
		"sr-BA": "Холандија",
		"sr-ME": "Holandija",
		"mk-MK": "Холандија",
		"bg-BG": "Нидерландия",
		"be-BY": "Нідэрланды",
		"uk-UA": "Нідерланди",
		"ru-RU": "Нидерланды",
		"el-GR": "Κάτω Χώρες",
		"el-CY": "Κάτω Χώρες",
		"ro-RO": "Țările de Jos",
		"ro-MD": "Țările de Jos",
		"hu-HU": "Hollandia",
		"sq-AL": "Holandë",
		"sq-XK": "Holandë",
		"mt-MT": "in-Netherlands",
		"ga-IE": "an Ísiltír",
		"cy-GB": "Yr Iseldiroedd",
		"gd-GB": "Na Tìrean Ìsle",
		"lb-LU": "Holland",
		"ca-ES": "Països Baixos",
		"ca-AD": "Països Baixos",
		"ca-FR": "Països Baixos",
		"ca-IT": "Països Baixos",
		"eu-ES": "Herbehereak",
		"eu-FR": "Herbehereak",
		"gl-ES": "Países Baixos",
		"tr-TR": "Hollanda",
		"tr-CY": "Hollanda"
	},
	"callingCode": "31",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "# ########",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"6"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[1-578]|91"
			]
		},
		{
			"mask": "## #######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"66"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1[16-8]|2[259]|3[124]|4[17-9]|5[124679]"
			]
		},
		{
			"mask": "### #######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[89]0"
			]
		},
		{
			"mask": "### ### #####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"9"
			]
		}
	]
} satisfies Country;
