import type { Country } from './types.js';

export const NOR = {
	"code": "NOR",
	"labels": {
		"pt-BR": "Noruega",
		"pt-PT": "Noruega",
		"es-ES": "Noruega",
		"es-419": "Noruega",
		"es-AR": "Noruega",
		"es-BO": "Noruega",
		"es-BR": "Noruega",
		"es-BZ": "Noruega",
		"es-CL": "Noruega",
		"es-CO": "Noruega",
		"es-CR": "Noruega",
		"es-CU": "Noruega",
		"es-DO": "Noruega",
		"es-EC": "Noruega",
		"es-GT": "Noruega",
		"es-HN": "Noruega",
		"es-MX": "Noruega",
		"es-NI": "Noruega",
		"es-PA": "Noruega",
		"es-PE": "Noruega",
		"es-PR": "Noruega",
		"es-PY": "Noruega",
		"es-SV": "Noruega",
		"es-US": "Noruega",
		"es-UY": "Noruega",
		"es-VE": "Noruega",
		"en-US": "Norway",
		"fr-FR": "Norvège",
		"fr-BE": "Norvège",
		"fr-CA": "Norvège",
		"fr-CH": "Norvège",
		"fr-LU": "Norvège",
		"fr-MC": "Norvège",
		"it-IT": "Norvegia",
		"it-CH": "Norvegia",
		"it-SM": "Norvegia",
		"it-VA": "Norvegia",
		"de-DE": "Norwegen",
		"de-AT": "Norwegen",
		"de-CH": "Norwegen",
		"de-BE": "Norwegen",
		"de-LI": "Norwegen",
		"de-LU": "Norwegen"
	}
} satisfies Country;
