import type { Country } from './types.js';

export const NZL = {
	"code": "NZL",
	"labels": {
		"pt-BR": "Nova Zelândia",
		"pt-PT": "Nova Zelândia",
		"es-ES": "Nueva Zelanda",
		"es-419": "Nueva Zelanda",
		"es-AR": "Nueva Zelanda",
		"es-BO": "Nueva Zelanda",
		"es-BR": "Nueva Zelanda",
		"es-BZ": "Nueva Zelanda",
		"es-CL": "Nueva Zelanda",
		"es-CO": "Nueva Zelanda",
		"es-CR": "Nueva Zelanda",
		"es-CU": "Nueva Zelanda",
		"es-DO": "Nueva Zelanda",
		"es-EC": "Nueva Zelanda",
		"es-GT": "Nueva Zelanda",
		"es-HN": "Nueva Zelanda",
		"es-MX": "Nueva Zelanda",
		"es-NI": "Nueva Zelanda",
		"es-PA": "Nueva Zelanda",
		"es-PE": "Nueva Zelanda",
		"es-PR": "Nueva Zelanda",
		"es-PY": "Nueva Zelanda",
		"es-SV": "Nueva Zelanda",
		"es-US": "Nueva Zelanda",
		"es-UY": "Nueva Zelanda",
		"es-VE": "Nueva Zelanda",
		"en-US": "New Zealand",
		"fr-FR": "Nouvelle-Zélande",
		"fr-BE": "Nouvelle-Zélande",
		"fr-CA": "Nouvelle-Zélande",
		"fr-CH": "Nouvelle-Zélande",
		"fr-LU": "Nouvelle-Zélande",
		"fr-MC": "Nouvelle-Zélande",
		"it-IT": "Nuova Zelanda",
		"it-CH": "Nuova Zelanda",
		"it-SM": "Nuova Zelanda",
		"it-VA": "Nuova Zelanda",
		"de-DE": "Neuseeland",
		"de-AT": "Neuseeland",
		"de-CH": "Neuseeland",
		"de-BE": "Neuseeland",
		"de-LI": "Neuseeland",
		"de-LU": "Neuseeland"
	}
} satisfies Country;
