import type { Country } from './types.js';

export const PAK = {
	"code": "PAK",
	"labels": {
		"pt-BR": "Paquistão",
		"pt-PT": "Paquistão",
		"es-ES": "Pakistán",
		"es-419": "Pakistán",
		"es-AR": "Pakistán",
		"es-BO": "Pakistán",
		"es-BR": "Pakistán",
		"es-BZ": "Pakistán",
		"es-CL": "Pakistán",
		"es-CO": "Pakistán",
		"es-CR": "Pakistán",
		"es-CU": "Pakistán",
		"es-DO": "Pakistán",
		"es-EC": "Pakistán",
		"es-GT": "Pakistán",
		"es-HN": "Pakistán",
		"es-MX": "Pakistán",
		"es-NI": "Pakistán",
		"es-PA": "Pakistán",
		"es-PE": "Pakistán",
		"es-PR": "Pakistán",
		"es-PY": "Pakistán",
		"es-SV": "Pakistán",
		"es-US": "Pakistán",
		"es-UY": "Pakistán",
		"es-VE": "Pakistán",
		"en-US": "Pakistan",
		"fr-FR": "Pakistan",
		"fr-BE": "Pakistan",
		"fr-CA": "Pakistan",
		"fr-CH": "Pakistan",
		"fr-LU": "Pakistan",
		"fr-MC": "Pakistan",
		"it-IT": "Pakistan",
		"it-CH": "Pakistan",
		"it-SM": "Pakistan",
		"it-VA": "Pakistan",
		"de-DE": "Pakistan",
		"de-AT": "Pakistan",
		"de-CH": "Pakistan",
		"de-BE": "Pakistan",
		"de-LI": "Pakistan",
		"de-LU": "Pakistan"
	}
} satisfies Country;
