import type { Country } from './types.js';

export const PCN = {
	"code": "PCN",
	"labels": {
		"pt-BR": "Ilhas Pitcairn",
		"pt-PT": "Ilhas Pitcairn",
		"es-ES": "Islas Pitcairn",
		"es-419": "Islas Pitcairn",
		"es-AR": "Islas Pitcairn",
		"es-BO": "Islas Pitcairn",
		"es-BR": "Islas Pitcairn",
		"es-BZ": "Islas Pitcairn",
		"es-CL": "Islas Pitcairn",
		"es-CO": "Islas Pitcairn",
		"es-CR": "Islas Pitcairn",
		"es-CU": "Islas Pitcairn",
		"es-DO": "Islas Pitcairn",
		"es-EC": "Islas Pitcairn",
		"es-GT": "Islas Pitcairn",
		"es-HN": "Islas Pitcairn",
		"es-MX": "Islas Pitcairn",
		"es-NI": "Islas Pitcairn",
		"es-PA": "Islas Pitcairn",
		"es-PE": "Islas Pitcairn",
		"es-PR": "Islas Pitcairn",
		"es-PY": "Islas Pitcairn",
		"es-SV": "Islas Pitcairn",
		"es-US": "Islas Pitcairn",
		"es-UY": "Islas Pitcairn",
		"es-VE": "Islas Pitcairn",
		"en-US": "Pitcairn Islands",
		"fr-FR": "Îles Pitcairn",
		"fr-BE": "Îles Pitcairn",
		"fr-CA": "îles Pitcairn",
		"fr-CH": "Îles Pitcairn",
		"fr-LU": "Îles Pitcairn",
		"fr-MC": "Îles Pitcairn",
		"it-IT": "Isole Pitcairn",
		"it-CH": "Isole Pitcairn",
		"it-SM": "Isole Pitcairn",
		"it-VA": "Isole Pitcairn",
		"de-DE": "Pitcairninseln",
		"de-AT": "Pitcairninseln",
		"de-CH": "Pitcairninseln",
		"de-BE": "Pitcairninseln",
		"de-LI": "Pitcairninseln",
		"de-LU": "Pitcairninseln"
	},
	"callingCode": "64"
} satisfies Country;
