import type { Country } from './types.js';

export const PER = {
	"code": "PER",
	"labels": {
		"pt-BR": "Peru",
		"pt-PT": "Peru",
		"es-ES": "Perú",
		"es-419": "Perú",
		"es-AR": "Perú",
		"es-BO": "Perú",
		"es-BR": "Perú",
		"es-BZ": "Perú",
		"es-CL": "Perú",
		"es-CO": "Perú",
		"es-CR": "Perú",
		"es-CU": "Perú",
		"es-DO": "Perú",
		"es-EC": "Perú",
		"es-GT": "Perú",
		"es-HN": "Perú",
		"es-MX": "Perú",
		"es-NI": "Perú",
		"es-PA": "Perú",
		"es-PE": "Perú",
		"es-PR": "Perú",
		"es-PY": "Perú",
		"es-SV": "Perú",
		"es-US": "Perú",
		"es-UY": "Perú",
		"es-VE": "Perú",
		"en-US": "Peru",
		"fr-FR": "Pérou",
		"fr-BE": "Pérou",
		"fr-CA": "Pérou",
		"fr-CH": "Pérou",
		"fr-LU": "Pérou",
		"fr-MC": "Pérou",
		"it-IT": "Perù",
		"it-CH": "Perù",
		"it-SM": "Perù",
		"it-VA": "Perù",
		"de-DE": "Peru",
		"de-AT": "Peru",
		"de-CH": "Peru",
		"de-BE": "Peru",
		"de-LI": "Peru",
		"de-LU": "Peru"
	},
	"callingCode": "51"
} satisfies Country;
