import type { Country } from './types.js';

export const PHL = {
	"code": "PHL",
	"labels": {
		"pt-BR": "Filipinas",
		"pt-PT": "Filipinas",
		"es-ES": "Filipinas",
		"es-419": "Filipinas",
		"es-AR": "Filipinas",
		"es-BO": "Filipinas",
		"es-BR": "Filipinas",
		"es-BZ": "Filipinas",
		"es-CL": "Filipinas",
		"es-CO": "Filipinas",
		"es-CR": "Filipinas",
		"es-CU": "Filipinas",
		"es-DO": "Filipinas",
		"es-EC": "Filipinas",
		"es-GT": "Filipinas",
		"es-HN": "Filipinas",
		"es-MX": "Filipinas",
		"es-NI": "Filipinas",
		"es-PA": "Filipinas",
		"es-PE": "Filipinas",
		"es-PR": "Filipinas",
		"es-PY": "Filipinas",
		"es-SV": "Filipinas",
		"es-US": "Filipinas",
		"es-UY": "Filipinas",
		"es-VE": "Filipinas",
		"en-US": "Philippines",
		"fr-FR": "Philippines",
		"fr-BE": "Philippines",
		"fr-CA": "Philippines",
		"fr-CH": "Philippines",
		"fr-LU": "Philippines",
		"fr-MC": "Philippines",
		"it-IT": "Filippine",
		"it-CH": "Filippine",
		"it-SM": "Filippine",
		"it-VA": "Filippine",
		"de-DE": "Philippinen",
		"de-AT": "Philippinen",
		"de-CH": "Philippinen",
		"de-BE": "Philippinen",
		"de-LI": "Philippinen",
		"de-LU": "Philippinen"
	},
	"callingCode": "63"
} satisfies Country;
