import type { Country } from './types.js';

export const PHL = {
	"code": "PHL",
	"labels": {
		"pt-BR": "Filipinas",
		"pt-PT": "Filipinas",
		"qu-PE": "Filipinas",
		"qu-BO": "Filipinas",
		"qu-EC": "Filipinas",
		"chr-US": "ᎠᏂᏈᎵᎩᏃ",
		"hi-IN": "फ़िलिपींस",
		"bn-IN": "ফিলিপাইন",
		"bn-BD": "ফিলিপাইন",
		"ta-IN": "பிலிப்பைன்ஸ்",
		"ta-LK": "பிலிப்பைன்ஸ்",
		"ta-SG": "பிலிப்பைன்ஸ்",
		"ta-MY": "பிலிப்பைன்ஸ்",
		"te-IN": "ఫిలిప్పైన్స్",
		"mr-IN": "फिलिपिन्स",
		"gu-IN": "ફિલિપિન્સ",
		"kn-IN": "ಫಿಲಿಫೈನ್ಸ್",
		"ml-IN": "ഫിലിപ്പീൻസ്",
		"pa-IN": "ਫਿਲੀਪੀਨਜ",
		"ur-IN": "فلپائن",
		"ur-PK": "فلپائن",
		"or-IN": "ଫିଲିପାଇନସ୍",
		"as-IN": "ফিলিপাইনছ",
		"ne-IN": "फिलिपिन्स",
		"ne-NP": "फिलिपिन्स",
		"si-LK": "පිලිපීනය",
		"kok-IN": "फिलीपिन्झ",
		"ks-IN": "فلپائن",
		"brx-IN": "फिलीपिन्स",
		"mai-IN": "फिलिपींस",
		"dz-BT": "ཕི་ལི་པིནས",
		"ja-JP": "フィリピン",
		"ko-KR": "필리핀",
		"ko-KP": "필리핀",
		"zh-CN": "菲律宾",
		"zh-Hans-CN": "菲律宾",
		"zh-Hant-TW": "菲律賓",
		"zh-TW": "菲律賓",
		"zh-HK": "菲律賓",
		"zh-MO": "菲律賓",
		"zh-SG": "菲律宾",
		"yue-Hant-HK": "菲律賓",
		"yue-Hans-CN": "菲律宾",
		"mn-MN": "Филиппин",
		"ug-CN": "فىلىپپىن",
		"th-TH": "ฟิลิปปินส์",
		"lo-LA": "ຟິລິບປິນ",
		"km-KH": "ហ្វ៊ីលីពីន",
		"my-MM": "ဖိလစ်ပိုင်",
		"vi-VN": "Philippines",
		"id-ID": "Filipina",
		"ms-MY": "Filipina",
		"ms-SG": "Filipina",
		"ms-BN": "Filipina",
		"jv-ID": "Pilipina",
		"fil-PH": "Pilipinas",
		"ceb-PH": "Pilipinas",
		"ka-GE": "ფილიპინები",
		"hy-AM": "Ֆիլիպիններ",
		"az-AZ": "Filippin",
		"az-Cyrl-AZ": "Филиппин",
		"kk-KZ": "Филиппин аралдары",
		"ky-KG": "Филиппин",
		"uz-UZ": "Filippin",
		"tg-TJ": "Филиппин",
		"tk-TM": "Filippinler",
		"fa-IR": "فیلیپین",
		"fa-AF": "فیلیپین",
		"ps-AF": "فلپين",
		"ps-PK": "فلپين",
		"he-IL": "הפיליפינים",
		"ar-SA": "الفلبين",
		"ar-AE": "الفلبين",
		"ar-QA": "الفلبين",
		"ar-BH": "الفلبين",
		"ar-KW": "الفلبين",
		"ar-OM": "الفلبين",
		"ar-YE": "الفلبين",
		"ar-IQ": "الفلبين",
		"ar-JO": "الفلبين",
		"ar-LB": "الفلبين",
		"ar-SY": "الفلبين",
		"ar-PS": "الفلبين",
		"en-US": "Philippines",
		"en-GB": "Philippines",
		"en-IE": "Philippines",
		"en-MT": "Philippines",
		"en-GI": "Philippines",
		"en-CY": "Philippines",
		"en-JE": "Philippines",
		"en-GG": "Philippines",
		"en-IM": "Philippines",
		"en-CA": "Philippines",
		"en-AU": "Philippines",
		"en-NZ": "Philippines",
		"en-ZA": "Philippines",
		"en-IN": "Philippines",
		"en-SG": "Philippines",
		"pt-AO": "Filipinas",
		"pt-MZ": "Filipinas",
		"pt-CV": "Filipinas",
		"pt-GW": "Filipinas",
		"pt-ST": "Filipinas",
		"pt-TL": "Filipinas",
		"pt-MO": "Filipinas",
		"es-ES": "Filipinas",
		"es-419": "Filipinas",
		"es-AD": "Filipinas",
		"es-GI": "Filipinas",
		"es-AR": "Filipinas",
		"es-BO": "Filipinas",
		"es-BR": "Filipinas",
		"es-BZ": "Filipinas",
		"es-CL": "Filipinas",
		"es-CO": "Filipinas",
		"es-CR": "Filipinas",
		"es-CU": "Filipinas",
		"es-DO": "Filipinas",
		"es-EC": "Filipinas",
		"es-GT": "Filipinas",
		"es-HN": "Filipinas",
		"es-MX": "Filipinas",
		"es-NI": "Filipinas",
		"es-PA": "Filipinas",
		"es-PE": "Filipinas",
		"es-PR": "Filipinas",
		"es-PY": "Filipinas",
		"es-SV": "Filipinas",
		"es-US": "Filipinas",
		"es-UY": "Filipinas",
		"es-VE": "Filipinas",
		"fr-FR": "Philippines",
		"fr-BE": "Philippines",
		"fr-CH": "Philippines",
		"fr-LU": "Philippines",
		"fr-MC": "Philippines",
		"fr-AD": "Philippines",
		"fr-CA": "Philippines",
		"it-IT": "Filippine",
		"it-CH": "Filippine",
		"it-SM": "Filippine",
		"it-VA": "Filippine",
		"de-DE": "Philippinen",
		"de-AT": "Philippinen",
		"de-CH": "Philippinen",
		"de-BE": "Philippinen",
		"de-LI": "Philippinen",
		"de-LU": "Philippinen",
		"nl-NL": "Filipijnen",
		"nl-BE": "Filipijnen",
		"sv-SE": "Filippinerna",
		"sv-FI": "Filippinerna",
		"da-DK": "Filippinerne",
		"nb-NO": "Filippinene",
		"nn-NO": "Filippinane",
		"fi-FI": "Filippiinit",
		"is-IS": "Filippseyjar",
		"fo-FO": "Filipsoyggjar",
		"et-EE": "Filipiinid",
		"lv-LV": "Filipīnas",
		"lt-LT": "Filipinai",
		"pl-PL": "Filipiny",
		"cs-CZ": "Filipíny",
		"sk-SK": "Filipíny",
		"sl-SI": "Filipini",
		"hr-HR": "Filipini",
		"bs-BA": "Filipini",
		"sr-RS": "Филипини",
		"sr-BA": "Филипини",
		"sr-ME": "Filipini",
		"mk-MK": "Филипини",
		"bg-BG": "Филипини",
		"be-BY": "Філіпіны",
		"uk-UA": "Філіппіни",
		"ru-RU": "Филиппины",
		"el-GR": "Φιλιππίνες",
		"el-CY": "Φιλιππίνες",
		"ro-RO": "Filipine",
		"ro-MD": "Filipine",
		"hu-HU": "Fülöp-szigetek",
		"sq-AL": "Filipine",
		"sq-XK": "Filipine",
		"mt-MT": "il-Filippini",
		"ga-IE": "Na hOileáin Fhilipíneacha",
		"cy-GB": "Y Philipinau",
		"gd-GB": "Na h-Eileanan Filipineach",
		"lb-LU": "Philippinnen",
		"ca-ES": "Filipines",
		"ca-AD": "Filipines",
		"ca-FR": "Filipines",
		"ca-IT": "Filipines",
		"eu-ES": "Filipinak",
		"eu-FR": "Filipinak",
		"gl-ES": "Filipinas",
		"tr-TR": "Filipinler",
		"tr-CY": "Filipinler"
	},
	"callingCode": "63",
	"phoneMasks": [
		{
			"mask": "# #####",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "####-####",
			"minLength": 8,
			"maxLength": 8
		},
		{
			"mask": "# #### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[3-7]|8[2-8]"
			]
		},
		{
			"mask": "##### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"346|4(?:27|9[35])|883",
				"3469|4(?:279|9(?:30|56))|8834"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[89]"
			]
		},
		{
			"mask": "#### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"3(?:23|39|46)|4(?:2[3-6]|[35]9|4[26]|76)|544|88[245]|(?:52|64|86)2",
				"3(?:230|397|461)|4(?:2(?:35|[46]4|51)|396|4(?:22|63)|59[347]|76[15])|5(?:221|446)|642[23]|8(?:622|8(?:[24]2|5[13]))"
			]
		},
		{
			"mask": "#### ### ####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12
		},
		{
			"mask": "#### ## ### ####",
			"minLength": 13,
			"maxLength": 13,
			"leadingDigits": [
				"1"
			]
		}
	]
} satisfies Country;
