import type { Country } from './types.js';

export const PNG = {
	"code": "PNG",
	"labels": {
		"pt-BR": "Papua-Nova Guiné",
		"pt-PT": "Papua-Nova Guiné",
		"es-ES": "Papúa Nueva Guinea",
		"es-419": "Papúa Nueva Guinea",
		"es-AR": "Papúa Nueva Guinea",
		"es-BO": "Papúa Nueva Guinea",
		"es-BR": "Papúa Nueva Guinea",
		"es-BZ": "Papúa Nueva Guinea",
		"es-CL": "Papúa Nueva Guinea",
		"es-CO": "Papúa Nueva Guinea",
		"es-CR": "Papúa Nueva Guinea",
		"es-CU": "Papúa Nueva Guinea",
		"es-DO": "Papúa Nueva Guinea",
		"es-EC": "Papúa Nueva Guinea",
		"es-GT": "Papúa Nueva Guinea",
		"es-HN": "Papúa Nueva Guinea",
		"es-MX": "Papúa Nueva Guinea",
		"es-NI": "Papúa Nueva Guinea",
		"es-PA": "Papúa Nueva Guinea",
		"es-PE": "Papúa Nueva Guinea",
		"es-PR": "Papúa Nueva Guinea",
		"es-PY": "Papúa Nueva Guinea",
		"es-SV": "Papúa Nueva Guinea",
		"es-US": "Papúa Nueva Guinea",
		"es-UY": "Papúa Nueva Guinea",
		"es-VE": "Papúa Nueva Guinea",
		"en-US": "Papua New Guinea",
		"fr-FR": "Papouasie-Nouvelle-Guinée",
		"fr-BE": "Papouasie-Nouvelle-Guinée",
		"fr-CA": "Papouasie-Nouvelle-Guinée",
		"fr-CH": "Papouasie-Nouvelle-Guinée",
		"fr-LU": "Papouasie-Nouvelle-Guinée",
		"fr-MC": "Papouasie-Nouvelle-Guinée",
		"it-IT": "Papua Nuova Guinea",
		"it-CH": "Papua Nuova Guinea",
		"it-SM": "Papua Nuova Guinea",
		"it-VA": "Papua Nuova Guinea",
		"de-DE": "Papua-Neuguinea",
		"de-AT": "Papua-Neuguinea",
		"de-CH": "Papua-Neuguinea",
		"de-BE": "Papua-Neuguinea",
		"de-LI": "Papua-Neuguinea",
		"de-LU": "Papua-Neuguinea"
	},
	"callingCode": "675"
} satisfies Country;
