import type { Country } from './types.js';

export const POL = {
	"code": "POL",
	"labels": {
		"pt-BR": "Polônia",
		"pt-PT": "Polónia",
		"es-ES": "Polonia",
		"es-419": "Polonia",
		"es-AR": "Polonia",
		"es-BO": "Polonia",
		"es-BR": "Polonia",
		"es-BZ": "Polonia",
		"es-CL": "Polonia",
		"es-CO": "Polonia",
		"es-CR": "Polonia",
		"es-CU": "Polonia",
		"es-DO": "Polonia",
		"es-EC": "Polonia",
		"es-GT": "Polonia",
		"es-HN": "Polonia",
		"es-MX": "Polonia",
		"es-NI": "Polonia",
		"es-PA": "Polonia",
		"es-PE": "Polonia",
		"es-PR": "Polonia",
		"es-PY": "Polonia",
		"es-SV": "Polonia",
		"es-US": "Polonia",
		"es-UY": "Polonia",
		"es-VE": "Polonia",
		"en-US": "Poland",
		"fr-FR": "Pologne",
		"fr-BE": "Pologne",
		"fr-CA": "Pologne",
		"fr-CH": "Pologne",
		"fr-LU": "Pologne",
		"fr-MC": "Pologne",
		"it-IT": "Polonia",
		"it-CH": "Polonia",
		"it-SM": "Polonia",
		"it-VA": "Polonia",
		"de-DE": "Polen",
		"de-AT": "Polen",
		"de-CH": "Polen",
		"de-BE": "Polen",
		"de-LI": "Polen",
		"de-LU": "Polen"
	}
} satisfies Country;
