import type { Country } from './types.js';

export const PRI = {
	"code": "PRI",
	"labels": {
		"pt-BR": "Porto Rico",
		"pt-PT": "Porto Rico",
		"qu-PE": "Puerto Rico",
		"qu-BO": "Puerto Rico",
		"qu-EC": "Puerto Rico",
		"chr-US": "ᏇᎡᏙ ᎵᎢᎪ",
		"hi-IN": "पोर्टो रिको",
		"bn-IN": "পুয়ের্তো রিকো",
		"bn-BD": "পুয়ের্তো রিকো",
		"ta-IN": "பியூர்டோ ரிகோ",
		"ta-LK": "பியூர்டோ ரிகோ",
		"ta-SG": "பியூர்டோ ரிகோ",
		"ta-MY": "பியூர்டோ ரிகோ",
		"te-IN": "ప్యూర్టో రికో",
		"mr-IN": "प्युएर्तो रिको",
		"gu-IN": "પ્યુઅર્ટો રિકો",
		"kn-IN": "ಪ್ಯೂರ್ಟೋ ರಿಕೊ",
		"ml-IN": "പോർട്ടോ റിക്കോ",
		"pa-IN": "ਪਿਊਰਟੋ ਰਿਕੋ",
		"ur-IN": "پیورٹو ریکو",
		"ur-PK": "پیورٹو ریکو",
		"or-IN": "ପୁଏର୍ତ୍ତୋ ରିକୋ",
		"as-IN": "পুৱেৰ্টো ৰিকো",
		"ne-IN": "पुएर्टो रिको",
		"ne-NP": "पुएर्टो रिको",
		"si-LK": "පුවර්ටෝ රිකෝ",
		"kok-IN": "प्युएर्तो रिको",
		"ks-IN": "پٔرٹو رِکو",
		"brx-IN": "पुवेर्ट’ रीक’",
		"mai-IN": "प्योर्टो रिको",
		"dz-BT": "པུ་འེར་ཊོ་རི་ཁོ",
		"ja-JP": "プエルトリコ",
		"ko-KR": "푸에르토리코",
		"ko-KP": "푸에르토리코",
		"zh-CN": "波多黎各",
		"zh-Hans-CN": "波多黎各",
		"zh-Hant-TW": "波多黎各",
		"zh-TW": "波多黎各",
		"zh-HK": "波多黎各",
		"zh-MO": "波多黎各",
		"zh-SG": "波多黎各",
		"yue-Hant-HK": "波多黎各",
		"yue-Hans-CN": "波多黎各",
		"mn-MN": "Пуэрто-Рико",
		"ug-CN": "پۇئېرتو رىكو",
		"th-TH": "เปอร์โตริโก",
		"lo-LA": "ເພືອໂຕ ຣິໂກ",
		"km-KH": "ព័រតូរីកូ",
		"my-MM": "ပေါ်တိုရီကို",
		"vi-VN": "Puerto Rico",
		"id-ID": "Puerto Riko",
		"ms-MY": "Puerto Rico",
		"ms-SG": "Puerto Rico",
		"ms-BN": "Puerto Rico",
		"jv-ID": "Puèrto Riko",
		"fil-PH": "Puerto Rico",
		"ceb-PH": "Puerto Rico",
		"ka-GE": "პუერტო-რიკო",
		"hy-AM": "Պուերտո Ռիկո",
		"az-AZ": "Puerto Riko",
		"az-Cyrl-AZ": "Пуерто Рико",
		"kk-KZ": "Пуэрто-Рико",
		"ky-KG": "Пуэрто-Рико",
		"uz-UZ": "Puerto-Riko",
		"tg-TJ": "Пуэрто-Рико",
		"tk-TM": "Puerto-Riko",
		"fa-IR": "پورتوریکو",
		"fa-AF": "پورتوریکو",
		"ps-AF": "پورتو ریکو",
		"ps-PK": "پورتو ریکو",
		"he-IL": "פוארטו ריקו",
		"ar-SA": "بورتوريكو",
		"ar-AE": "بورتوريكو",
		"ar-QA": "بورتوريكو",
		"ar-BH": "بورتوريكو",
		"ar-KW": "بورتوريكو",
		"ar-OM": "بورتوريكو",
		"ar-YE": "بورتوريكو",
		"ar-IQ": "بورتوريكو",
		"ar-JO": "بورتوريكو",
		"ar-LB": "بورتوريكو",
		"ar-SY": "بورتوريكو",
		"ar-PS": "بورتوريكو",
		"en-US": "Puerto Rico",
		"en-GB": "Puerto Rico",
		"en-IE": "Puerto Rico",
		"en-MT": "Puerto Rico",
		"en-GI": "Puerto Rico",
		"en-CY": "Puerto Rico",
		"en-JE": "Puerto Rico",
		"en-GG": "Puerto Rico",
		"en-IM": "Puerto Rico",
		"en-CA": "Puerto Rico",
		"en-AU": "Puerto Rico",
		"en-NZ": "Puerto Rico",
		"en-ZA": "Puerto Rico",
		"en-IN": "Puerto Rico",
		"en-SG": "Puerto Rico",
		"pt-AO": "Porto Rico",
		"pt-MZ": "Porto Rico",
		"pt-CV": "Porto Rico",
		"pt-GW": "Porto Rico",
		"pt-ST": "Porto Rico",
		"pt-TL": "Porto Rico",
		"pt-MO": "Porto Rico",
		"es-ES": "Puerto Rico",
		"es-419": "Puerto Rico",
		"es-AD": "Puerto Rico",
		"es-GI": "Puerto Rico",
		"es-AR": "Puerto Rico",
		"es-BO": "Puerto Rico",
		"es-BR": "Puerto Rico",
		"es-BZ": "Puerto Rico",
		"es-CL": "Puerto Rico",
		"es-CO": "Puerto Rico",
		"es-CR": "Puerto Rico",
		"es-CU": "Puerto Rico",
		"es-DO": "Puerto Rico",
		"es-EC": "Puerto Rico",
		"es-GT": "Puerto Rico",
		"es-HN": "Puerto Rico",
		"es-MX": "Puerto Rico",
		"es-NI": "Puerto Rico",
		"es-PA": "Puerto Rico",
		"es-PE": "Puerto Rico",
		"es-PR": "Puerto Rico",
		"es-PY": "Puerto Rico",
		"es-SV": "Puerto Rico",
		"es-US": "Puerto Rico",
		"es-UY": "Puerto Rico",
		"es-VE": "Puerto Rico",
		"fr-FR": "Porto Rico",
		"fr-BE": "Porto Rico",
		"fr-CH": "Porto Rico",
		"fr-LU": "Porto Rico",
		"fr-MC": "Porto Rico",
		"fr-AD": "Porto Rico",
		"fr-CA": "Porto Rico",
		"it-IT": "Portorico",
		"it-CH": "Portorico",
		"it-SM": "Portorico",
		"it-VA": "Portorico",
		"de-DE": "Puerto Rico",
		"de-AT": "Puerto Rico",
		"de-CH": "Puerto Rico",
		"de-BE": "Puerto Rico",
		"de-LI": "Puerto Rico",
		"de-LU": "Puerto Rico",
		"nl-NL": "Puerto Rico",
		"nl-BE": "Puerto Rico",
		"sv-SE": "Puerto Rico",
		"sv-FI": "Puerto Rico",
		"da-DK": "Puerto Rico",
		"nb-NO": "Puerto Rico",
		"nn-NO": "Puerto Rico",
		"fi-FI": "Puerto Rico",
		"is-IS": "Púertó Ríkó",
		"fo-FO": "Puerto Riko",
		"et-EE": "Puerto Rico",
		"lv-LV": "Puertoriko",
		"lt-LT": "Puerto Rikas",
		"pl-PL": "Portoryko",
		"cs-CZ": "Portoriko",
		"sk-SK": "Portoriko",
		"sl-SI": "Portoriko",
		"hr-HR": "Portoriko",
		"bs-BA": "Porto Riko",
		"sr-RS": "Порторико",
		"sr-BA": "Порторико",
		"sr-ME": "Portoriko",
		"mk-MK": "Порторико",
		"bg-BG": "Пуерто Рико",
		"be-BY": "Пуэрта-Рыка",
		"uk-UA": "Пуерто-Рико",
		"ru-RU": "Пуэрто-Рико",
		"el-GR": "Πουέρτο Ρίκο",
		"el-CY": "Πουέρτο Ρίκο",
		"ro-RO": "Puerto Rico",
		"ro-MD": "Puerto Rico",
		"hu-HU": "Puerto Rico",
		"sq-AL": "Porto-Riko",
		"sq-XK": "Porto-Riko",
		"mt-MT": "Puerto Rico",
		"ga-IE": "Pórtó Ríce",
		"cy-GB": "Puerto Rico",
		"gd-GB": "Porto Rìceo",
		"lb-LU": "Puerto Rico",
		"ca-ES": "Puerto Rico",
		"ca-AD": "Puerto Rico",
		"ca-FR": "Puerto Rico",
		"ca-IT": "Puerto Rico",
		"eu-ES": "Puerto Rico",
		"eu-FR": "Puerto Rico",
		"gl-ES": "Porto Rico",
		"tr-TR": "Porto Riko",
		"tr-CY": "Porto Riko"
	},
	"callingCode": "1",
	"phoneMasks": [
		{
			"mask": "(###) ###-####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
