import type { Country } from './types.js';

export const PRT = {
	"code": "PRT",
	"labels": {
		"pt-BR": "Portugal",
		"pt-PT": "Portugal",
		"es-ES": "Portugal",
		"es-419": "Portugal",
		"es-AR": "Portugal",
		"es-BO": "Portugal",
		"es-BR": "Portugal",
		"es-BZ": "Portugal",
		"es-CL": "Portugal",
		"es-CO": "Portugal",
		"es-CR": "Portugal",
		"es-CU": "Portugal",
		"es-DO": "Portugal",
		"es-EC": "Portugal",
		"es-GT": "Portugal",
		"es-HN": "Portugal",
		"es-MX": "Portugal",
		"es-NI": "Portugal",
		"es-PA": "Portugal",
		"es-PE": "Portugal",
		"es-PR": "Portugal",
		"es-PY": "Portugal",
		"es-SV": "Portugal",
		"es-US": "Portugal",
		"es-UY": "Portugal",
		"es-VE": "Portugal",
		"en-US": "Portugal",
		"fr-FR": "Portugal",
		"fr-BE": "Portugal",
		"fr-CA": "Portugal",
		"fr-CH": "Portugal",
		"fr-LU": "Portugal",
		"fr-MC": "Portugal",
		"it-IT": "Portogallo",
		"it-CH": "Portogallo",
		"it-SM": "Portogallo",
		"it-VA": "Portogallo",
		"de-DE": "Portugal",
		"de-AT": "Portugal",
		"de-CH": "Portugal",
		"de-BE": "Portugal",
		"de-LI": "Portugal",
		"de-LU": "Portugal"
	},
	"callingCode": "351"
} satisfies Country;
