import type { Country } from './types.js';

export const PRY = {
	"code": "PRY",
	"labels": {
		"pt-BR": "Paraguai",
		"pt-PT": "Paraguai",
		"gn-PY": "Paraguái",
		"es-ES": "Paraguay",
		"es-419": "Paraguay",
		"es-AR": "Paraguay",
		"es-BO": "Paraguay",
		"es-BR": "Paraguay",
		"es-BZ": "Paraguay",
		"es-CL": "Paraguay",
		"es-CO": "Paraguay",
		"es-CR": "Paraguay",
		"es-CU": "Paraguay",
		"es-DO": "Paraguay",
		"es-EC": "Paraguay",
		"es-GT": "Paraguay",
		"es-HN": "Paraguay",
		"es-MX": "Paraguay",
		"es-NI": "Paraguay",
		"es-PA": "Paraguay",
		"es-PE": "Paraguay",
		"es-PR": "Paraguay",
		"es-PY": "Paraguay",
		"es-SV": "Paraguay",
		"es-US": "Paraguay",
		"es-UY": "Paraguay",
		"es-VE": "Paraguay",
		"en-US": "Paraguay",
		"fr-FR": "Paraguay",
		"fr-BE": "Paraguay",
		"fr-CA": "Paraguay",
		"fr-CH": "Paraguay",
		"fr-LU": "Paraguay",
		"fr-MC": "Paraguay",
		"it-IT": "Paraguay",
		"it-CH": "Paraguay",
		"it-SM": "Paraguay",
		"it-VA": "Paraguay",
		"de-DE": "Paraguay",
		"de-AT": "Paraguay",
		"de-CH": "Paraguay",
		"de-BE": "Paraguay",
		"de-LI": "Paraguay",
		"de-LU": "Paraguay"
	}
} satisfies Country;
