import type { Country } from './types.js';

export const PRY = {
	"code": "PRY",
	"labels": {
		"pt-BR": "Paraguai",
		"pt-PT": "Paraguai",
		"gn-PY": "Paraguái",
		"qu-PE": "Paraguay",
		"qu-BO": "Paraguay",
		"qu-EC": "Paraguay",
		"chr-US": "ᏆᎳᏇᎢᏯ",
		"hi-IN": "पराग्वे",
		"bn-IN": "প্যারাগুয়ে",
		"bn-BD": "প্যারাগুয়ে",
		"ta-IN": "பராகுவே",
		"ta-LK": "பராகுவே",
		"ta-SG": "பராகுவே",
		"ta-MY": "பராகுவே",
		"te-IN": "పరాగ్వే",
		"mr-IN": "पराग्वे",
		"gu-IN": "પેરાગ્વે",
		"kn-IN": "ಪರಾಗ್ವೇ",
		"ml-IN": "പരാഗ്വേ",
		"pa-IN": "ਪੈਰਾਗਵੇ",
		"ur-IN": "پیراگوئے",
		"ur-PK": "پیراگوئے",
		"or-IN": "ପାରାଗୁଏ",
		"as-IN": "পাৰাগুৱে",
		"ne-IN": "प्याराग्वे",
		"ne-NP": "प्याराग्वे",
		"si-LK": "පැරගුවේ",
		"kok-IN": "पैराग्वे",
		"ks-IN": "پَراگُے",
		"brx-IN": "पारागुए",
		"mai-IN": "पराग्वे",
		"dz-BT": "པ་ར་གུ་ཝའི",
		"ja-JP": "パラグアイ",
		"ko-KR": "파라과이",
		"ko-KP": "파라과이",
		"zh-CN": "巴拉圭",
		"zh-Hans-CN": "巴拉圭",
		"zh-Hant-TW": "巴拉圭",
		"zh-TW": "巴拉圭",
		"zh-HK": "巴拉圭",
		"zh-MO": "巴拉圭",
		"zh-SG": "巴拉圭",
		"yue-Hant-HK": "巴拉圭",
		"yue-Hans-CN": "巴拉圭",
		"mn-MN": "Парагвай",
		"ug-CN": "پاراگۋاي",
		"th-TH": "ปารากวัย",
		"lo-LA": "ພາຣາກວຍ",
		"km-KH": "ប៉ារ៉ាហ្គាយ",
		"my-MM": "ပါရာဂွေး",
		"vi-VN": "Paraguay",
		"id-ID": "Paraguay",
		"ms-MY": "Paraguay",
		"ms-SG": "Paraguay",
		"ms-BN": "Paraguay",
		"jv-ID": "Paraguay",
		"fil-PH": "Paraguay",
		"ceb-PH": "Paraguay",
		"ka-GE": "პარაგვაი",
		"hy-AM": "Պարագվայ",
		"az-AZ": "Paraqvay",
		"az-Cyrl-AZ": "Парагвај",
		"kk-KZ": "Парагвай",
		"ky-KG": "Парагвай",
		"uz-UZ": "Paragvay",
		"tg-TJ": "Парагвай",
		"tk-TM": "Paragwaý",
		"fa-IR": "پاراگوئه",
		"fa-AF": "پاراگوای",
		"ps-AF": "پاراګوی",
		"ps-PK": "پاراګوی",
		"he-IL": "פרגוואי",
		"ar-SA": "باراغواي",
		"ar-AE": "باراغواي",
		"ar-QA": "باراغواي",
		"ar-BH": "باراغواي",
		"ar-KW": "باراغواي",
		"ar-OM": "باراغواي",
		"ar-YE": "باراغواي",
		"ar-IQ": "باراغواي",
		"ar-JO": "باراغواي",
		"ar-LB": "باراغواي",
		"ar-SY": "باراغواي",
		"ar-PS": "باراغواي",
		"en-US": "Paraguay",
		"en-GB": "Paraguay",
		"en-IE": "Paraguay",
		"en-MT": "Paraguay",
		"en-GI": "Paraguay",
		"en-CY": "Paraguay",
		"en-JE": "Paraguay",
		"en-GG": "Paraguay",
		"en-IM": "Paraguay",
		"en-CA": "Paraguay",
		"en-AU": "Paraguay",
		"en-NZ": "Paraguay",
		"en-ZA": "Paraguay",
		"en-IN": "Paraguay",
		"en-SG": "Paraguay",
		"pt-AO": "Paraguai",
		"pt-MZ": "Paraguai",
		"pt-CV": "Paraguai",
		"pt-GW": "Paraguai",
		"pt-ST": "Paraguai",
		"pt-TL": "Paraguai",
		"pt-MO": "Paraguai",
		"es-ES": "Paraguay",
		"es-419": "Paraguay",
		"es-AD": "Paraguay",
		"es-GI": "Paraguay",
		"es-AR": "Paraguay",
		"es-BO": "Paraguay",
		"es-BR": "Paraguay",
		"es-BZ": "Paraguay",
		"es-CL": "Paraguay",
		"es-CO": "Paraguay",
		"es-CR": "Paraguay",
		"es-CU": "Paraguay",
		"es-DO": "Paraguay",
		"es-EC": "Paraguay",
		"es-GT": "Paraguay",
		"es-HN": "Paraguay",
		"es-MX": "Paraguay",
		"es-NI": "Paraguay",
		"es-PA": "Paraguay",
		"es-PE": "Paraguay",
		"es-PR": "Paraguay",
		"es-PY": "Paraguay",
		"es-SV": "Paraguay",
		"es-US": "Paraguay",
		"es-UY": "Paraguay",
		"es-VE": "Paraguay",
		"fr-FR": "Paraguay",
		"fr-BE": "Paraguay",
		"fr-CH": "Paraguay",
		"fr-LU": "Paraguay",
		"fr-MC": "Paraguay",
		"fr-AD": "Paraguay",
		"fr-CA": "Paraguay",
		"it-IT": "Paraguay",
		"it-CH": "Paraguay",
		"it-SM": "Paraguay",
		"it-VA": "Paraguay",
		"de-DE": "Paraguay",
		"de-AT": "Paraguay",
		"de-CH": "Paraguay",
		"de-BE": "Paraguay",
		"de-LI": "Paraguay",
		"de-LU": "Paraguay",
		"nl-NL": "Paraguay",
		"nl-BE": "Paraguay",
		"sv-SE": "Paraguay",
		"sv-FI": "Paraguay",
		"da-DK": "Paraguay",
		"nb-NO": "Paraguay",
		"nn-NO": "Paraguay",
		"fi-FI": "Paraguay",
		"is-IS": "Paragvæ",
		"fo-FO": "Paraguai",
		"et-EE": "Paraguay",
		"lv-LV": "Paragvaja",
		"lt-LT": "Paragvajus",
		"pl-PL": "Paragwaj",
		"cs-CZ": "Paraguay",
		"sk-SK": "Paraguaj",
		"sl-SI": "Paragvaj",
		"hr-HR": "Paragvaj",
		"bs-BA": "Paragvaj",
		"sr-RS": "Парагвај",
		"sr-BA": "Парагвај",
		"sr-ME": "Paragvaj",
		"mk-MK": "Парагвај",
		"bg-BG": "Парагвай",
		"be-BY": "Парагвай",
		"uk-UA": "Парагвай",
		"ru-RU": "Парагвай",
		"el-GR": "Παραγουάη",
		"el-CY": "Παραγουάη",
		"ro-RO": "Paraguay",
		"ro-MD": "Paraguay",
		"hu-HU": "Paraguay",
		"sq-AL": "Paraguai",
		"sq-XK": "Paraguai",
		"mt-MT": "il-Paragwaj",
		"ga-IE": "Paragua",
		"cy-GB": "Paraguay",
		"gd-GB": "Paraguaidh",
		"lb-LU": "Paraguay",
		"ca-ES": "Paraguai",
		"ca-AD": "Paraguai",
		"ca-FR": "Paraguai",
		"ca-IT": "Paraguai",
		"eu-ES": "Paraguai",
		"eu-FR": "Paraguai",
		"gl-ES": "Paraguai",
		"tr-TR": "Paraguay",
		"tr-CY": "Paraguay"
	},
	"callingCode": "595",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[26]1|3[289]|4[1246-8]|7[1-3]|8[1-36]"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"2[279]|3[13-5]|4[359]|5|6(?:[34]|7[1-46-8])|7[46-8]|85"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"2[14-68]|3[26-9]|4[1246-8]|6(?:1|75)|7[1-35]|8[1-36]"
			]
		},
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"87"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[2-8]"
			]
		},
		{
			"mask": "### ######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[2-9]0"
			]
		},
		{
			"mask": "### ######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"9(?:[5-79]|8[1-7])"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "#### ### ####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"9"
			]
		}
	]
} satisfies Country;
