import type { Country } from './types.js';

export const PSE = {
	"code": "PSE",
	"labels": {
		"pt-BR": "Territórios palestinos",
		"pt-PT": "Territórios palestinianos",
		"es-ES": "Territorios Palestinos",
		"es-419": "Territorios Palestinos",
		"es-AR": "Territorios Palestinos",
		"es-BO": "Territorios Palestinos",
		"es-BR": "Territorios Palestinos",
		"es-BZ": "Territorios Palestinos",
		"es-CL": "Territorios Palestinos",
		"es-CO": "Territorios Palestinos",
		"es-CR": "Territorios Palestinos",
		"es-CU": "Territorios Palestinos",
		"es-DO": "Territorios Palestinos",
		"es-EC": "Territorios Palestinos",
		"es-GT": "Territorios Palestinos",
		"es-HN": "Territorios Palestinos",
		"es-MX": "Territorios Palestinos",
		"es-NI": "Territorios Palestinos",
		"es-PA": "Territorios Palestinos",
		"es-PE": "Territorios Palestinos",
		"es-PR": "Territorios Palestinos",
		"es-PY": "Territorios Palestinos",
		"es-SV": "Territorios Palestinos",
		"es-US": "Territorios Palestinos",
		"es-UY": "Territorios Palestinos",
		"es-VE": "Territorios Palestinos",
		"en-US": "Palestinian Territories",
		"fr-FR": "Territoires palestiniens",
		"fr-BE": "Territoires palestiniens",
		"fr-CA": "Territoires palestiniens",
		"fr-CH": "Territoires palestiniens",
		"fr-LU": "Territoires palestiniens",
		"fr-MC": "Territoires palestiniens",
		"it-IT": "Territori Palestinesi",
		"it-CH": "Territori Palestinesi",
		"it-SM": "Territori Palestinesi",
		"it-VA": "Territori Palestinesi",
		"de-DE": "Palästinensische Autonomiegebiete",
		"de-AT": "Palästinensische Autonomiegebiete",
		"de-CH": "Palästinensische Autonomiegebiete",
		"de-BE": "Palästinensische Autonomiegebiete",
		"de-LI": "Palästinensische Autonomiegebiete",
		"de-LU": "Palästinensische Autonomiegebiete"
	}
} satisfies Country;
