import type { Country } from './types.js';

export const PSE = {
	"code": "PSE",
	"labels": {
		"pt-BR": "Territórios palestinos",
		"pt-PT": "Territórios palestinianos",
		"qu-PE": "Palestina Kamachikuq",
		"qu-BO": "Palestina Kamachikuq",
		"qu-EC": "Palestina Kamachikuq",
		"chr-US": "ᏆᎴᏍᏗᏂᎠᏂ ᏄᎬᏫᏳᏌᏕᎩ",
		"hi-IN": "फ़िलिस्तीनी क्षेत्र",
		"bn-IN": "প্যালেস্টাইন ভূখণ্ড",
		"bn-BD": "প্যালেস্টাইন ভূখণ্ড",
		"ta-IN": "பாலஸ்தீனிய பிரதேசங்கள்",
		"ta-LK": "பாலஸ்தீனிய பிரதேசங்கள்",
		"ta-SG": "பாலஸ்தீனிய பிரதேசங்கள்",
		"ta-MY": "பாலஸ்தீனிய பிரதேசங்கள்",
		"te-IN": "పాలస్తీనియన్ ప్రాంతాలు",
		"mr-IN": "पॅलेस्टिनियन प्रदेश",
		"gu-IN": "પેલેસ્ટિનિયન ટેરિટરી",
		"kn-IN": "ಪ್ಯಾಲೇಸ್ಟೇನಿಯನ್ ಪ್ರದೇಶಗಳು",
		"ml-IN": "പാലസ്‌തീൻ പ്രദേശങ്ങൾ",
		"pa-IN": "ਫਿਲੀਸਤੀਨੀ ਇਲਾਕਾ",
		"ur-IN": "فلسطینی خطے",
		"ur-PK": "فلسطینی خطے",
		"or-IN": "ପାଲେଷ୍ଟେନିୟ ଭୂଭାଗ",
		"as-IN": "ফিলিস্তিন অঞ্চল",
		"ne-IN": "प्यालेस्टिनी भू-भागहरू",
		"ne-NP": "प्यालेस्टिनी भू-भागहरू",
		"si-LK": "පලස්තීන රාජ්‍යය",
		"kok-IN": "पेलेस्टीनियन प्रांत",
		"ks-IN": "فلسطینی علاقٕہ",
		"brx-IN": "पेलेस्ताइननि ओनसोलफोर",
		"mai-IN": "फिलिस्तीनी क्षेत्र",
		"dz-BT": "པེ་ལིསི་ཊི་ནི་ཡན་ཊེ་རི་ཐོ་རི",
		"ja-JP": "パレスチナ自治区",
		"ko-KR": "팔레스타인 지구",
		"ko-KP": "팔레스타인 지구",
		"zh-CN": "巴勒斯坦领土",
		"zh-Hans-CN": "巴勒斯坦领土",
		"zh-Hant-TW": "巴勒斯坦自治區",
		"zh-TW": "巴勒斯坦自治區",
		"zh-HK": "巴勒斯坦領土",
		"zh-MO": "巴勒斯坦領土",
		"zh-SG": "巴勒斯坦领土",
		"yue-Hant-HK": "巴勒斯坦自治區",
		"yue-Hans-CN": "巴勒斯坦自治区",
		"mn-MN": "Палестины нутаг дэвсгэр",
		"ug-CN": "پەلەستىن زېمىنى",
		"th-TH": "ดินแดนปาเลสไตน์",
		"lo-LA": "ດິນແດນປາເລດສະຕິນ",
		"km-KH": "ដែនដីប៉ាឡេស្ទីន",
		"my-MM": "ပါလက်စတိုင်း ပိုင်နက်",
		"vi-VN": "Lãnh thổ Palestine",
		"id-ID": "Wilayah Palestina",
		"ms-MY": "Wilayah Palestin",
		"ms-SG": "Wilayah Palestin",
		"ms-BN": "Wilayah Palestin",
		"jv-ID": "Tlatah Palèstina",
		"fil-PH": "Palestinian Territories",
		"ceb-PH": "Palestinian Territories",
		"ka-GE": "პალესტინის ტერიტორიები",
		"hy-AM": "Պաղեստինյան տարածքներ",
		"az-AZ": "Fələstin Əraziləri",
		"kk-KZ": "Палестина аймақтары",
		"ky-KG": "Палестина аймактары",
		"uz-UZ": "Falastin hududlari",
		"tg-TJ": "Қаламравҳои Фаластинӣ",
		"tk-TM": "Palestina territoriýasy",
		"fa-IR": "سرزمین‌های فلسطینی",
		"fa-AF": "سرزمین‌های فلسطینی",
		"ps-AF": "فلسطیني سيمې",
		"ps-PK": "فلسطين سيمے",
		"he-IL": "השטחים הפלסטיניים",
		"ar-SA": "الأراضي الفلسطينية",
		"ar-AE": "الأراضي الفلسطينية",
		"ar-QA": "الأراضي الفلسطينية",
		"ar-BH": "الأراضي الفلسطينية",
		"ar-KW": "الأراضي الفلسطينية",
		"ar-OM": "الأراضي الفلسطينية",
		"ar-YE": "الأراضي الفلسطينية",
		"ar-IQ": "الأراضي الفلسطينية",
		"ar-JO": "الأراضي الفلسطينية",
		"ar-LB": "الأراضي الفلسطينية",
		"ar-SY": "الأراضي الفلسطينية",
		"ar-PS": "الأراضي الفلسطينية",
		"en-US": "Palestinian Territories",
		"en-GB": "Palestinian Territories",
		"en-IE": "Palestinian Territories",
		"en-MT": "Palestinian Territories",
		"en-GI": "Palestinian Territories",
		"en-CY": "Palestinian Territories",
		"en-JE": "Palestinian Territories",
		"en-GG": "Palestinian Territories",
		"en-IM": "Palestinian Territories",
		"en-CA": "Palestinian territories",
		"en-AU": "Palestinian Territories",
		"en-NZ": "Palestinian Territories",
		"en-ZA": "Palestinian Territories",
		"en-IN": "Palestinian Territories",
		"en-SG": "Palestinian Territories",
		"pt-AO": "Territórios palestinianos",
		"pt-MZ": "Territórios palestinianos",
		"pt-CV": "Territórios palestinianos",
		"pt-GW": "Territórios palestinianos",
		"pt-ST": "Territórios palestinianos",
		"pt-TL": "Territórios palestinianos",
		"pt-MO": "Territórios palestinianos",
		"es-ES": "Territorios Palestinos",
		"es-419": "Territorios Palestinos",
		"es-AD": "Territorios Palestinos",
		"es-GI": "Territorios Palestinos",
		"es-AR": "Territorios Palestinos",
		"es-BO": "Territorios Palestinos",
		"es-BR": "Territorios Palestinos",
		"es-BZ": "Territorios Palestinos",
		"es-CL": "Territorios Palestinos",
		"es-CO": "Territorios Palestinos",
		"es-CR": "Territorios Palestinos",
		"es-CU": "Territorios Palestinos",
		"es-DO": "Territorios Palestinos",
		"es-EC": "Territorios Palestinos",
		"es-GT": "Territorios Palestinos",
		"es-HN": "Territorios Palestinos",
		"es-MX": "Territorios Palestinos",
		"es-NI": "Territorios Palestinos",
		"es-PA": "Territorios Palestinos",
		"es-PE": "Territorios Palestinos",
		"es-PR": "Territorios Palestinos",
		"es-PY": "Territorios Palestinos",
		"es-SV": "Territorios Palestinos",
		"es-US": "Territorios Palestinos",
		"es-UY": "Territorios Palestinos",
		"es-VE": "Territorios Palestinos",
		"fr-FR": "Territoires palestiniens",
		"fr-BE": "Territoires palestiniens",
		"fr-CH": "Territoires palestiniens",
		"fr-LU": "Territoires palestiniens",
		"fr-MC": "Territoires palestiniens",
		"fr-AD": "Territoires palestiniens",
		"fr-CA": "Territoires palestiniens",
		"it-IT": "Territori Palestinesi",
		"it-CH": "Territori Palestinesi",
		"it-SM": "Territori Palestinesi",
		"it-VA": "Territori Palestinesi",
		"de-DE": "Palästinensische Autonomiegebiete",
		"de-AT": "Palästinensische Autonomiegebiete",
		"de-CH": "Palästinensische Autonomiegebiete",
		"de-BE": "Palästinensische Autonomiegebiete",
		"de-LI": "Palästinensische Autonomiegebiete",
		"de-LU": "Palästinensische Autonomiegebiete",
		"nl-NL": "Palestijnse gebieden",
		"nl-BE": "Palestijnse gebieden",
		"sv-SE": "Palestinska territorierna",
		"sv-FI": "Palestinska territorierna",
		"da-DK": "De palæstinensiske områder",
		"nb-NO": "Det palestinske området",
		"nn-NO": "Det palestinske området",
		"fi-FI": "Palestiinalaisalue",
		"is-IS": "Heimastjórnarsvæði Palestínumanna",
		"fo-FO": "Palestinskt landøki",
		"et-EE": "Palestiina alad",
		"lv-LV": "Palestīnas teritorijas",
		"lt-LT": "Palestinos teritorija",
		"pl-PL": "Terytoria Palestyńskie",
		"cs-CZ": "Palestinská území",
		"sk-SK": "Palestínske územia",
		"sl-SI": "Palestinsko ozemlje",
		"hr-HR": "Palestinsko područje",
		"bs-BA": "Palestinska Teritorija",
		"sr-RS": "Палестинске територије",
		"sr-BA": "палестинске територије",
		"sr-ME": "Palestinske teritorije",
		"mk-MK": "Палестински Територии",
		"bg-BG": "Палестински територии",
		"be-BY": "Палесцінскія Тэрыторыі",
		"uk-UA": "Палестинські території",
		"ru-RU": "Палестинские территории",
		"el-GR": "Παλαιστινιακά Εδάφη",
		"el-CY": "Παλαιστινιακά Εδάφη",
		"ro-RO": "Teritoriile Palestiniene",
		"ro-MD": "Teritoriile Palestiniene",
		"hu-HU": "Palesztin Autonómia",
		"sq-AL": "Territoret Palestineze",
		"sq-XK": "Territoret Palestineze",
		"mt-MT": "it-Territorji Palestinjani",
		"ga-IE": "na Críocha Palaistíneacha",
		"cy-GB": "Tiriogaethau Palesteinaidd",
		"gd-GB": "Ùghdarras nam Palastaineach",
		"lb-LU": "Palestinensesch Autonomiegebidder",
		"ca-ES": "Territoris palestins",
		"ca-AD": "Territoris palestins",
		"ca-FR": "Territoris palestins",
		"ca-IT": "Territoris palestins",
		"eu-ES": "Palestinar Lurralde Okupatuak",
		"eu-FR": "Palestinar Lurralde Okupatuak",
		"gl-ES": "Territorios Palestinos",
		"tr-TR": "Filistin Bölgeleri",
		"tr-CY": "Filistin Bölgeleri"
	},
	"callingCode": "970",
	"phoneMasks": [
		{
			"mask": "# ### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[2489]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"5"
			]
		},
		{
			"mask": "#### ### ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"1"
			]
		}
	]
} satisfies Country;
