import type { Country } from './types.js';

export const PYF = {
	"code": "PYF",
	"labels": {
		"pt-BR": "Polinésia Francesa",
		"pt-PT": "Polinésia Francesa",
		"qu-PE": "Polinesia Francesa",
		"qu-BO": "Polinesia Francesa",
		"qu-EC": "Polinesia Francesa",
		"chr-US": "ᎠᏂᎦᎸᏥ ᏆᎵᏂᏏᎠ",
		"hi-IN": "फ़्रेंच पोलिनेशिया",
		"bn-IN": "ফরাসী পলিনেশিয়া",
		"bn-BD": "ফরাসী পলিনেশিয়া",
		"ta-IN": "பிரெஞ்சு பாலினேஷியா",
		"ta-LK": "பிரெஞ்சு பாலினேஷியா",
		"ta-SG": "பிரெஞ்சு பாலினேஷியா",
		"ta-MY": "பிரெஞ்சு பாலினேஷியா",
		"te-IN": "ఫ్రెంచ్ పోలినీషియా",
		"mr-IN": "फ्रेंच पॉलिनेशिया",
		"gu-IN": "ફ્રેંચ પોલિનેશિયા",
		"kn-IN": "ಫ್ರೆಂಚ್ ಪಾಲಿನೇಷ್ಯಾ",
		"ml-IN": "ഫ്രഞ്ച് പോളിനേഷ്യ",
		"pa-IN": "ਫਰੈਂਚ ਪੋਲੀਨੇਸ਼ੀਆ",
		"ur-IN": "فرانسیسی پولینیشیا",
		"ur-PK": "فرانسیسی پولینیشیا",
		"or-IN": "ଫ୍ରେଞ୍ଚ ପଲିନେସିଆ",
		"as-IN": "ফ্ৰান্স পোলেনচিয়া",
		"ne-IN": "फ्रान्सेली पोलिनेसिया",
		"ne-NP": "फ्रान्सेली पोलिनेसिया",
		"si-LK": "ප්‍රංශ පොලිනීසියාව",
		"kok-IN": "फ्रेन्च पोलिनेसिया",
		"ks-IN": "فرانسی پولِنیشِیا",
		"brx-IN": "फ्रेन्च पलिनेशिया",
		"mai-IN": "फ्रेंच पोलिनेशिया",
		"dz-BT": "ཕྲཱནས྄་ཀྱི་པོ་ལི་ནི་ཤི་ཡ",
		"ja-JP": "仏領ポリネシア",
		"ko-KR": "프랑스령 폴리네시아",
		"ko-KP": "프랑스령 폴리네시아",
		"zh-CN": "法属波利尼西亚",
		"zh-Hans-CN": "法属波利尼西亚",
		"zh-Hant-TW": "法屬玻里尼西亞",
		"zh-TW": "法屬玻里尼西亞",
		"zh-HK": "法屬波利尼西亞",
		"zh-MO": "法屬波利尼西亞",
		"zh-SG": "法属波利尼西亚",
		"yue-Hant-HK": "法屬玻里尼西亞",
		"yue-Hans-CN": "法属玻里尼西亚",
		"mn-MN": "Францын Полинез",
		"ug-CN": "فىرانسىيەگە قاراشلىق پولىنېزىيە",
		"th-TH": "เฟรนช์โปลินีเซีย",
		"lo-LA": "ເຟຣນຊ໌ ໂພລິນີເຊຍ",
		"km-KH": "ប៉ូលី​ណេស៊ី​បារាំង",
		"my-MM": "ပြင်သစ် ပေါ်လီနီးရှား",
		"vi-VN": "Polynesia thuộc Pháp",
		"id-ID": "Polinesia Prancis",
		"ms-MY": "Polinesia Perancis",
		"ms-SG": "Polinesia Perancis",
		"ms-BN": "Polinesia Perancis",
		"jv-ID": "Polinesia Prancis",
		"fil-PH": "French Polynesia",
		"ceb-PH": "French Polynesia",
		"ka-GE": "საფრანგეთის პოლინეზია",
		"hy-AM": "Ֆրանսիական Պոլինեզիա",
		"az-AZ": "Fransa Polineziyası",
		"az-Cyrl-AZ": "Франса Полинезијасы",
		"kk-KZ": "Француз Полинезиясы",
		"ky-KG": "Полинезия (франциялык)",
		"uz-UZ": "Fransuz Polineziyasi",
		"tg-TJ": "Полинезияи Фаронса",
		"tk-TM": "Fransuz Polineziýasy",
		"fa-IR": "پلی‌نزی فرانسه",
		"fa-AF": "پلی‌نزی فرانسه",
		"ps-AF": "فرانسوي پولينيسيا",
		"ps-PK": "فرانسوي پولينيسيا",
		"he-IL": "פולינזיה הצרפתית",
		"ar-SA": "بولينيزيا الفرنسية",
		"ar-AE": "بولينيزيا الفرنسية",
		"ar-QA": "بولينيزيا الفرنسية",
		"ar-BH": "بولينيزيا الفرنسية",
		"ar-KW": "بولينيزيا الفرنسية",
		"ar-OM": "بولينيزيا الفرنسية",
		"ar-YE": "بولينيزيا الفرنسية",
		"ar-IQ": "بولينيزيا الفرنسية",
		"ar-JO": "بولينيزيا الفرنسية",
		"ar-LB": "بولينيزيا الفرنسية",
		"ar-SY": "بولينيزيا الفرنسية",
		"ar-PS": "بولينيزيا الفرنسية",
		"en-US": "French Polynesia",
		"en-GB": "French Polynesia",
		"en-IE": "French Polynesia",
		"en-MT": "French Polynesia",
		"en-GI": "French Polynesia",
		"en-CY": "French Polynesia",
		"en-JE": "French Polynesia",
		"en-GG": "French Polynesia",
		"en-IM": "French Polynesia",
		"en-CA": "French Polynesia",
		"en-AU": "French Polynesia",
		"en-NZ": "French Polynesia",
		"en-ZA": "French Polynesia",
		"en-IN": "French Polynesia",
		"en-SG": "French Polynesia",
		"pt-AO": "Polinésia Francesa",
		"pt-MZ": "Polinésia Francesa",
		"pt-CV": "Polinésia Francesa",
		"pt-GW": "Polinésia Francesa",
		"pt-ST": "Polinésia Francesa",
		"pt-TL": "Polinésia Francesa",
		"pt-MO": "Polinésia Francesa",
		"es-ES": "Polinesia Francesa",
		"es-419": "Polinesia Francesa",
		"es-AD": "Polinesia Francesa",
		"es-GI": "Polinesia Francesa",
		"es-AR": "Polinesia Francesa",
		"es-BO": "Polinesia Francesa",
		"es-BR": "Polinesia Francesa",
		"es-BZ": "Polinesia Francesa",
		"es-CL": "Polinesia Francesa",
		"es-CO": "Polinesia Francesa",
		"es-CR": "Polinesia Francesa",
		"es-CU": "Polinesia Francesa",
		"es-DO": "Polinesia Francesa",
		"es-EC": "Polinesia Francesa",
		"es-GT": "Polinesia Francesa",
		"es-HN": "Polinesia Francesa",
		"es-MX": "Polinesia Francesa",
		"es-NI": "Polinesia Francesa",
		"es-PA": "Polinesia Francesa",
		"es-PE": "Polinesia Francesa",
		"es-PR": "Polinesia Francesa",
		"es-PY": "Polinesia Francesa",
		"es-SV": "Polinesia Francesa",
		"es-US": "Polinesia Francesa",
		"es-UY": "Polinesia Francesa",
		"es-VE": "Polinesia Francesa",
		"fr-FR": "Polynésie française",
		"fr-BE": "Polynésie française",
		"fr-CH": "Polynésie française",
		"fr-LU": "Polynésie française",
		"fr-MC": "Polynésie française",
		"fr-AD": "Polynésie française",
		"fr-CA": "Polynésie française",
		"it-IT": "Polinesia Francese",
		"it-CH": "Polinesia Francese",
		"it-SM": "Polinesia Francese",
		"it-VA": "Polinesia Francese",
		"de-DE": "Französisch-Polynesien",
		"de-AT": "Französisch-Polynesien",
		"de-CH": "Französisch-Polynesien",
		"de-BE": "Französisch-Polynesien",
		"de-LI": "Französisch-Polynesien",
		"de-LU": "Französisch-Polynesien",
		"nl-NL": "Frans-Polynesië",
		"nl-BE": "Frans-Polynesië",
		"sv-SE": "Franska Polynesien",
		"sv-FI": "Franska Polynesien",
		"da-DK": "Fransk Polynesien",
		"nb-NO": "Fransk Polynesia",
		"nn-NO": "Fransk Polynesia",
		"fi-FI": "Ranskan Polynesia",
		"is-IS": "Franska Pólýnesía",
		"fo-FO": "Franska Polynesia",
		"et-EE": "Prantsuse Polüneesia",
		"lv-LV": "Francijas Polinēzija",
		"lt-LT": "Prancūzijos Polinezija",
		"pl-PL": "Polinezja Francuska",
		"cs-CZ": "Francouzská Polynésie",
		"sk-SK": "Francúzska Polynézia",
		"sl-SI": "Francoska Polinezija",
		"hr-HR": "Francuska Polinezija",
		"bs-BA": "Francuska Polinezija",
		"sr-RS": "Француска Полинезија",
		"sr-BA": "Француска Полинезија",
		"sr-ME": "Francuska Polinezija",
		"mk-MK": "Француска Полинезија",
		"bg-BG": "Френска Полинезия",
		"be-BY": "Французская Палінезія",
		"uk-UA": "Французька Полінезія",
		"ru-RU": "Французская Полинезия",
		"el-GR": "Γαλλική Πολυνησία",
		"el-CY": "Γαλλική Πολυνησία",
		"ro-RO": "Polinezia Franceză",
		"ro-MD": "Polinezia Franceză",
		"hu-HU": "Francia Polinézia",
		"sq-AL": "Polinezia Franceze",
		"sq-XK": "Polinezia Franceze",
		"mt-MT": "Polineżja Franċiża",
		"ga-IE": "Polainéis na Fraince",
		"cy-GB": "Polynesia Ffrengig",
		"gd-GB": "Poilinèis na Frainge",
		"lb-LU": "Franséisch-Polynesien",
		"ca-ES": "Polinèsia Francesa",
		"ca-AD": "Polinèsia Francesa",
		"ca-FR": "Polinèsia Francesa",
		"ca-IT": "Polinèsia Francesa",
		"eu-ES": "Polinesia Frantsesa",
		"eu-FR": "Polinesia Frantsesa",
		"gl-ES": "Polinesia Francesa",
		"tr-TR": "Fransız Polinezyası",
		"tr-CY": "Fransız Polinezyası"
	},
	"callingCode": "689",
	"phoneMasks": [
		{
			"mask": "## ## ##",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"44"
			]
		},
		{
			"mask": "## ## ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"4|8[7-9]"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
