import type { Country } from './types.js';

export const QAT = {
	"code": "QAT",
	"labels": {
		"pt-BR": "Catar",
		"pt-PT": "Catar",
		"es-ES": "Catar",
		"es-419": "Catar",
		"es-AR": "Catar",
		"es-BO": "Catar",
		"es-BR": "Catar",
		"es-BZ": "Catar",
		"es-CL": "Catar",
		"es-CO": "Catar",
		"es-CR": "Catar",
		"es-CU": "Catar",
		"es-DO": "Catar",
		"es-EC": "Catar",
		"es-GT": "Catar",
		"es-HN": "Catar",
		"es-MX": "Catar",
		"es-NI": "Catar",
		"es-PA": "Catar",
		"es-PE": "Catar",
		"es-PR": "Catar",
		"es-PY": "Catar",
		"es-SV": "Catar",
		"es-US": "Catar",
		"es-UY": "Catar",
		"es-VE": "Catar",
		"en-US": "Qatar",
		"fr-FR": "Qatar",
		"fr-BE": "Qatar",
		"fr-CA": "Qatar",
		"fr-CH": "Qatar",
		"fr-LU": "Qatar",
		"fr-MC": "Qatar",
		"it-IT": "Qatar",
		"it-CH": "Qatar",
		"it-SM": "Qatar",
		"it-VA": "Qatar",
		"de-DE": "Katar",
		"de-AT": "Katar",
		"de-CH": "Katar",
		"de-BE": "Katar",
		"de-LI": "Katar",
		"de-LU": "Katar"
	}
} satisfies Country;
