import type { Country } from './types.js';

export const REU = {
	"code": "REU",
	"labels": {
		"pt-BR": "Reunião",
		"pt-PT": "Reunião",
		"es-ES": "Reunión",
		"es-419": "Reunión",
		"es-AR": "Reunión",
		"es-BO": "Reunión",
		"es-BR": "Reunión",
		"es-BZ": "Reunión",
		"es-CL": "Reunión",
		"es-CO": "Reunión",
		"es-CR": "Reunión",
		"es-CU": "Reunión",
		"es-DO": "Reunión",
		"es-EC": "Reunión",
		"es-GT": "Reunión",
		"es-HN": "Reunión",
		"es-MX": "Reunión",
		"es-NI": "Reunión",
		"es-PA": "Reunión",
		"es-PE": "Reunión",
		"es-PR": "Reunión",
		"es-PY": "Reunión",
		"es-SV": "Reunión",
		"es-US": "Reunión",
		"es-UY": "Reunión",
		"es-VE": "Reunión",
		"en-US": "Réunion",
		"fr-FR": "La Réunion",
		"fr-BE": "La Réunion",
		"fr-CA": "la Réunion",
		"fr-CH": "La Réunion",
		"fr-LU": "La Réunion",
		"fr-MC": "La Réunion",
		"it-IT": "Riunione",
		"it-CH": "Riunione",
		"it-SM": "Riunione",
		"it-VA": "Riunione",
		"de-DE": "Réunion",
		"de-AT": "Réunion",
		"de-CH": "Réunion",
		"de-BE": "Réunion",
		"de-LI": "Réunion",
		"de-LU": "Réunion"
	},
	"callingCode": "262"
} satisfies Country;
