import type { Country } from './types.js';

export const RUS = {
	"code": "RUS",
	"labels": {
		"pt-BR": "Rússia",
		"pt-PT": "Rússia",
		"qu-PE": "Rusia",
		"qu-BO": "Rusia",
		"qu-EC": "Rusia",
		"chr-US": "ᏲᏂᎢ",
		"hi-IN": "रूस",
		"bn-IN": "রাশিয়া",
		"bn-BD": "রাশিয়া",
		"ta-IN": "ரஷ்யா",
		"ta-LK": "ரஷ்யா",
		"ta-SG": "ரஷ்யா",
		"ta-MY": "ரஷ்யா",
		"te-IN": "రష్యా",
		"mr-IN": "रशिया",
		"gu-IN": "રશિયા",
		"kn-IN": "ರಷ್ಯಾ",
		"ml-IN": "റഷ്യ",
		"pa-IN": "ਰੂਸ",
		"ur-IN": "روس",
		"ur-PK": "روس",
		"or-IN": "ରୁଷିଆ",
		"as-IN": "ৰাছিয়া",
		"ne-IN": "रूस",
		"ne-NP": "रूस",
		"si-LK": "රුසියාව",
		"kok-IN": "रूस",
		"sd-IN": "रशिया",
		"ks-IN": "روٗس",
		"doi-IN": "रूस",
		"mni-IN": "রুসিয়া",
		"brx-IN": "रासिया",
		"sat-IN": "ᱨᱩᱥ",
		"mai-IN": "रूस",
		"sa-IN": "रष्यदेश:",
		"dz-BT": "ཨུ་རུ་སུ",
		"ja-JP": "ロシア",
		"ko-KR": "러시아",
		"ko-KP": "러시아",
		"zh-CN": "俄罗斯",
		"zh-Hans-CN": "俄罗斯",
		"zh-Hant-TW": "俄羅斯",
		"zh-TW": "俄羅斯",
		"zh-HK": "俄羅斯",
		"zh-MO": "俄羅斯",
		"zh-SG": "俄罗斯",
		"yue-Hant-HK": "俄羅斯",
		"yue-Hans-CN": "俄罗斯",
		"mn-MN": "Орос",
		"bo-CN": "ཨུ་རུ་སུ་",
		"bo-IN": "ཨུ་རུ་སུ་",
		"ug-CN": "رۇسىيە",
		"ii-CN": "ꊉꇆꌦ",
		"th-TH": "รัสเซีย",
		"lo-LA": "ຣັດເຊຍ",
		"km-KH": "រុស្ស៊ី",
		"my-MM": "ရုရှား",
		"vi-VN": "Nga",
		"id-ID": "Rusia",
		"ms-MY": "Rusia",
		"ms-SG": "Rusia",
		"ms-BN": "Rusia",
		"jv-ID": "Rusia",
		"su-ID": "Rusia",
		"fil-PH": "Russia",
		"ceb-PH": "Russia",
		"ka-GE": "რუსეთი",
		"hy-AM": "Ռուսաստան",
		"az-AZ": "Rusiya",
		"az-Cyrl-AZ": "Русија",
		"kk-KZ": "Ресей",
		"ky-KG": "Россия",
		"uz-UZ": "Rossiya",
		"tg-TJ": "Русия",
		"tk-TM": "Russiýa",
		"fa-IR": "روسیه",
		"fa-AF": "روسیه",
		"ps-AF": "روسیه",
		"ps-PK": "روسیه",
		"he-IL": "רוסיה",
		"ar-SA": "روسيا",
		"ar-AE": "روسيا",
		"ar-QA": "روسيا",
		"ar-BH": "روسيا",
		"ar-KW": "روسيا",
		"ar-OM": "روسيا",
		"ar-YE": "روسيا",
		"ar-IQ": "روسيا",
		"ar-JO": "روسيا",
		"ar-LB": "روسيا",
		"ar-SY": "روسيا",
		"ar-PS": "روسيا",
		"en-US": "Russia",
		"en-GB": "Russia",
		"en-IE": "Russia",
		"en-MT": "Russia",
		"en-GI": "Russia",
		"en-CY": "Russia",
		"en-JE": "Russia",
		"en-GG": "Russia",
		"en-IM": "Russia",
		"en-CA": "Russia",
		"en-AU": "Russia",
		"en-NZ": "Russia",
		"en-ZA": "Russia",
		"en-IN": "Russia",
		"en-SG": "Russia",
		"pt-AO": "Rússia",
		"pt-MZ": "Rússia",
		"pt-CV": "Rússia",
		"pt-GW": "Rússia",
		"pt-ST": "Rússia",
		"pt-TL": "Rússia",
		"pt-MO": "Rússia",
		"es-ES": "Rusia",
		"es-419": "Rusia",
		"es-AD": "Rusia",
		"es-GI": "Rusia",
		"es-AR": "Rusia",
		"es-BO": "Rusia",
		"es-BR": "Rusia",
		"es-BZ": "Rusia",
		"es-CL": "Rusia",
		"es-CO": "Rusia",
		"es-CR": "Rusia",
		"es-CU": "Rusia",
		"es-DO": "Rusia",
		"es-EC": "Rusia",
		"es-GT": "Rusia",
		"es-HN": "Rusia",
		"es-MX": "Rusia",
		"es-NI": "Rusia",
		"es-PA": "Rusia",
		"es-PE": "Rusia",
		"es-PR": "Rusia",
		"es-PY": "Rusia",
		"es-SV": "Rusia",
		"es-US": "Rusia",
		"es-UY": "Rusia",
		"es-VE": "Rusia",
		"fr-FR": "Russie",
		"fr-BE": "Russie",
		"fr-CH": "Russie",
		"fr-LU": "Russie",
		"fr-MC": "Russie",
		"fr-AD": "Russie",
		"fr-CA": "Russie",
		"it-IT": "Russia",
		"it-CH": "Russia",
		"it-SM": "Russia",
		"it-VA": "Russia",
		"de-DE": "Russland",
		"de-AT": "Russland",
		"de-CH": "Russland",
		"de-BE": "Russland",
		"de-LI": "Russland",
		"de-LU": "Russland",
		"nl-NL": "Rusland",
		"nl-BE": "Rusland",
		"sv-SE": "Ryssland",
		"sv-FI": "Ryssland",
		"da-DK": "Rusland",
		"nb-NO": "Russland",
		"nn-NO": "Russland",
		"fi-FI": "Venäjä",
		"is-IS": "Rússland",
		"fo-FO": "Russland",
		"et-EE": "Venemaa",
		"lv-LV": "Krievija",
		"lt-LT": "Rusija",
		"pl-PL": "Rosja",
		"cs-CZ": "Rusko",
		"sk-SK": "Rusko",
		"sl-SI": "Rusija",
		"hr-HR": "Rusija",
		"bs-BA": "Rusija",
		"sr-RS": "Русија",
		"sr-BA": "Русија",
		"sr-ME": "Rusija",
		"mk-MK": "Русија",
		"bg-BG": "Русия",
		"be-BY": "Расія",
		"uk-UA": "Росія",
		"ru-RU": "Россия",
		"el-GR": "Ρωσία",
		"el-CY": "Ρωσία",
		"ro-RO": "Rusia",
		"ro-MD": "Rusia",
		"hu-HU": "Oroszország",
		"sq-AL": "Rusi",
		"sq-XK": "Rusi",
		"mt-MT": "ir-Russja",
		"ga-IE": "an Rúis",
		"cy-GB": "Rwsia",
		"gd-GB": "An Ruis",
		"lb-LU": "Russland",
		"ca-ES": "Rússia",
		"ca-AD": "Rússia",
		"ca-FR": "Rússia",
		"ca-IT": "Rússia",
		"eu-ES": "Errusia",
		"eu-FR": "Errusia",
		"gl-ES": "Rusia",
		"tr-TR": "Rusya",
		"tr-CY": "Rusya"
	},
	"callingCode": "7",
	"phoneMasks": [
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"7"
			]
		},
		{
			"mask": "### ###-##-##",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[349]|8(?:[02-7]|1[1-8])"
			]
		},
		{
			"mask": "#### ## ## ##",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"7(?:1[0-8]|2[1-9])",
				"7(?:1(?:[0-356]2|4[29]|7|8[27])|2(?:1[23]|[2-9]2))",
				"7(?:1(?:[0-356]2|4[29]|7|8[27])|2(?:13[03-69]|62[013-9]))|72[1-57-9]2"
			]
		},
		{
			"mask": "##### # ## ##",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"7(?:1[0-68]|2[1-9])",
				"7(?:1(?:[06][3-6]|[18]|2[35]|[3-5][3-5])|2(?:[13][3-5]|[24-689]|7[457]))",
				"7(?:1(?:0(?:[356]|4[023])|[18]|2(?:3[013-9]|5)|3[45]|43[013-79]|5(?:3[1-8]|4[1-7]|5)|6(?:3[0-35-9]|[4-6]))|2(?:1(?:3[178]|[45])|[24-689]|3[35]|7[457]))|7(?:14|23)4[0-8]|71(?:33|45)[1-79]"
			]
		},
		{
			"mask": "#### #### ### ###",
			"minLength": 14,
			"maxLength": 14,
			"leadingDigits": [
				"8"
			]
		}
	]
} satisfies Country;
