import type { Country } from './types.js';

export const RUS = {
	"code": "RUS",
	"labels": {
		"pt-BR": "Rússia",
		"pt-PT": "Rússia",
		"es-ES": "Rusia",
		"es-419": "Rusia",
		"es-AR": "Rusia",
		"es-BO": "Rusia",
		"es-BR": "Rusia",
		"es-BZ": "Rusia",
		"es-CL": "Rusia",
		"es-CO": "Rusia",
		"es-CR": "Rusia",
		"es-CU": "Rusia",
		"es-DO": "Rusia",
		"es-EC": "Rusia",
		"es-GT": "Rusia",
		"es-HN": "Rusia",
		"es-MX": "Rusia",
		"es-NI": "Rusia",
		"es-PA": "Rusia",
		"es-PE": "Rusia",
		"es-PR": "Rusia",
		"es-PY": "Rusia",
		"es-SV": "Rusia",
		"es-US": "Rusia",
		"es-UY": "Rusia",
		"es-VE": "Rusia",
		"en-US": "Russia",
		"fr-FR": "Russie",
		"fr-BE": "Russie",
		"fr-CA": "Russie",
		"fr-CH": "Russie",
		"fr-LU": "Russie",
		"fr-MC": "Russie",
		"it-IT": "Russia",
		"it-CH": "Russia",
		"it-SM": "Russia",
		"it-VA": "Russia",
		"de-DE": "Russland",
		"de-AT": "Russland",
		"de-CH": "Russland",
		"de-BE": "Russland",
		"de-LI": "Russland",
		"de-LU": "Russland"
	}
} satisfies Country;
