import type { Country } from './types.js';

export const RWA = {
	"code": "RWA",
	"labels": {
		"pt-BR": "Ruanda",
		"pt-PT": "Ruanda",
		"es-ES": "Ruanda",
		"es-419": "Ruanda",
		"es-AR": "Ruanda",
		"es-BO": "Ruanda",
		"es-BR": "Ruanda",
		"es-BZ": "Ruanda",
		"es-CL": "Ruanda",
		"es-CO": "Ruanda",
		"es-CR": "Ruanda",
		"es-CU": "Ruanda",
		"es-DO": "Ruanda",
		"es-EC": "Ruanda",
		"es-GT": "Ruanda",
		"es-HN": "Ruanda",
		"es-MX": "Ruanda",
		"es-NI": "Ruanda",
		"es-PA": "Ruanda",
		"es-PE": "Ruanda",
		"es-PR": "Ruanda",
		"es-PY": "Ruanda",
		"es-SV": "Ruanda",
		"es-US": "Ruanda",
		"es-UY": "Ruanda",
		"es-VE": "Ruanda",
		"en-US": "Rwanda",
		"fr-FR": "Rwanda",
		"fr-BE": "Rwanda",
		"fr-CA": "Rwanda",
		"fr-CH": "Rwanda",
		"fr-LU": "Rwanda",
		"fr-MC": "Rwanda",
		"it-IT": "Ruanda",
		"it-CH": "Ruanda",
		"it-SM": "Ruanda",
		"it-VA": "Ruanda",
		"de-DE": "Ruanda",
		"de-AT": "Ruanda",
		"de-CH": "Ruanda",
		"de-BE": "Ruanda",
		"de-LI": "Ruanda",
		"de-LU": "Ruanda"
	},
	"callingCode": "250"
} satisfies Country;
