import type { Country } from './types.js';

export const SAU = {
	"code": "SAU",
	"labels": {
		"pt-BR": "Arábia Saudita",
		"pt-PT": "Arábia Saudita",
		"es-ES": "Arabia Saudí",
		"es-419": "Arabia Saudita",
		"es-AR": "Arabia Saudita",
		"es-BO": "Arabia Saudita",
		"es-BR": "Arabia Saudita",
		"es-BZ": "Arabia Saudita",
		"es-CL": "Arabia Saudita",
		"es-CO": "Arabia Saudita",
		"es-CR": "Arabia Saudita",
		"es-CU": "Arabia Saudita",
		"es-DO": "Arabia Saudita",
		"es-EC": "Arabia Saudita",
		"es-GT": "Arabia Saudita",
		"es-HN": "Arabia Saudita",
		"es-MX": "Arabia Saudita",
		"es-NI": "Arabia Saudita",
		"es-PA": "Arabia Saudita",
		"es-PE": "Arabia Saudita",
		"es-PR": "Arabia Saudita",
		"es-PY": "Arabia Saudita",
		"es-SV": "Arabia Saudita",
		"es-US": "Arabia Saudita",
		"es-UY": "Arabia Saudita",
		"es-VE": "Arabia Saudita",
		"en-US": "Saudi Arabia",
		"fr-FR": "Arabie saoudite",
		"fr-BE": "Arabie saoudite",
		"fr-CA": "Arabie saoudite",
		"fr-CH": "Arabie saoudite",
		"fr-LU": "Arabie saoudite",
		"fr-MC": "Arabie saoudite",
		"it-IT": "Arabia Saudita",
		"it-CH": "Arabia Saudita",
		"it-SM": "Arabia Saudita",
		"it-VA": "Arabia Saudita",
		"de-DE": "Saudi-Arabien",
		"de-AT": "Saudi-Arabien",
		"de-CH": "Saudi-Arabien",
		"de-BE": "Saudi-Arabien",
		"de-LI": "Saudi-Arabien",
		"de-LU": "Saudi-Arabien"
	},
	"callingCode": "966"
} satisfies Country;
