import type { Country } from './types.js';

export const SEN = {
	"code": "SEN",
	"labels": {
		"pt-BR": "Senegal",
		"pt-PT": "Senegal",
		"es-ES": "Senegal",
		"es-419": "Senegal",
		"es-AR": "Senegal",
		"es-BO": "Senegal",
		"es-BR": "Senegal",
		"es-BZ": "Senegal",
		"es-CL": "Senegal",
		"es-CO": "Senegal",
		"es-CR": "Senegal",
		"es-CU": "Senegal",
		"es-DO": "Senegal",
		"es-EC": "Senegal",
		"es-GT": "Senegal",
		"es-HN": "Senegal",
		"es-MX": "Senegal",
		"es-NI": "Senegal",
		"es-PA": "Senegal",
		"es-PE": "Senegal",
		"es-PR": "Senegal",
		"es-PY": "Senegal",
		"es-SV": "Senegal",
		"es-US": "Senegal",
		"es-UY": "Senegal",
		"es-VE": "Senegal",
		"en-US": "Senegal",
		"fr-FR": "Sénégal",
		"fr-BE": "Sénégal",
		"fr-CA": "Sénégal",
		"fr-CH": "Sénégal",
		"fr-LU": "Sénégal",
		"fr-MC": "Sénégal",
		"it-IT": "Senegal",
		"it-CH": "Senegal",
		"it-SM": "Senegal",
		"it-VA": "Senegal",
		"de-DE": "Senegal",
		"de-AT": "Senegal",
		"de-CH": "Senegal",
		"de-BE": "Senegal",
		"de-LI": "Senegal",
		"de-LU": "Senegal"
	},
	"callingCode": "221"
} satisfies Country;
