import type { Country } from './types.js';

export const SGP = {
	"code": "SGP",
	"labels": {
		"pt-BR": "Singapura",
		"pt-PT": "Singapura",
		"qu-PE": "Singapur",
		"qu-BO": "Singapur",
		"qu-EC": "Singapur",
		"chr-US": "ᏏᏂᎦᏉᎵ",
		"hi-IN": "सिंगापुर",
		"bn-IN": "সিঙ্গাপুর",
		"bn-BD": "সিঙ্গাপুর",
		"ta-IN": "சிங்கப்பூர்",
		"ta-LK": "சிங்கப்பூர்",
		"ta-SG": "சிங்கப்பூர்",
		"ta-MY": "சிங்கப்பூர்",
		"te-IN": "సింగపూర్",
		"mr-IN": "सिंगापूर",
		"gu-IN": "સિંગાપુર",
		"kn-IN": "ಸಿಂಗಪುರ್",
		"ml-IN": "സിംഗപ്പൂർ",
		"pa-IN": "ਸਿੰਗਾਪੁਰ",
		"ur-IN": "سنگاپور",
		"ur-PK": "سنگاپور",
		"or-IN": "ସିଙ୍ଗାପୁର୍",
		"as-IN": "ছিংগাপুৰ",
		"ne-IN": "सिङ्गापुर",
		"ne-NP": "सिङ्गापुर",
		"si-LK": "සිංගප්පූරුව",
		"kok-IN": "सिंगापूर",
		"ks-IN": "سِنگاپوٗر",
		"brx-IN": "सिंंगाप’र",
		"mai-IN": "सिंगापुर",
		"dz-BT": "སིང་ག་པོར",
		"ja-JP": "シンガポール",
		"ko-KR": "싱가포르",
		"ko-KP": "싱가포르",
		"zh-CN": "新加坡",
		"zh-Hans-CN": "新加坡",
		"zh-Hant-TW": "新加坡",
		"zh-TW": "新加坡",
		"zh-HK": "新加坡",
		"zh-MO": "新加坡",
		"zh-SG": "新加坡",
		"yue-Hant-HK": "新加坡",
		"yue-Hans-CN": "新加坡",
		"mn-MN": "Сингапур",
		"ug-CN": "سىنگاپور",
		"th-TH": "สิงคโปร์",
		"lo-LA": "ສິງກະໂປ",
		"km-KH": "សិង្ហបុរី",
		"my-MM": "စင်္ကာပူ",
		"vi-VN": "Singapore",
		"id-ID": "Singapura",
		"ms-MY": "Singapura",
		"ms-SG": "Singapura",
		"ms-BN": "Singapura",
		"jv-ID": "Singapura",
		"fil-PH": "Singapore",
		"ceb-PH": "Singapore",
		"ka-GE": "სინგაპური",
		"hy-AM": "Սինգապուր",
		"az-AZ": "Sinqapur",
		"az-Cyrl-AZ": "Сингапур",
		"kk-KZ": "Сингапур",
		"ky-KG": "Сингапур",
		"uz-UZ": "Singapur",
		"tg-TJ": "Сингапур",
		"tk-TM": "Singapur",
		"fa-IR": "سنگاپور",
		"fa-AF": "سینگاپور",
		"ps-AF": "سينگاپور",
		"ps-PK": "سينگاپور",
		"he-IL": "סינגפור",
		"ar-SA": "سنغافورة",
		"ar-AE": "سنغافورة",
		"ar-QA": "سنغافورة",
		"ar-BH": "سنغافورة",
		"ar-KW": "سنغافورة",
		"ar-OM": "سنغافورة",
		"ar-YE": "سنغافورة",
		"ar-IQ": "سنغافورة",
		"ar-JO": "سنغافورة",
		"ar-LB": "سنغافورة",
		"ar-SY": "سنغافورة",
		"ar-PS": "سنغافورة",
		"en-US": "Singapore",
		"en-GB": "Singapore",
		"en-IE": "Singapore",
		"en-MT": "Singapore",
		"en-GI": "Singapore",
		"en-CY": "Singapore",
		"en-JE": "Singapore",
		"en-GG": "Singapore",
		"en-IM": "Singapore",
		"en-CA": "Singapore",
		"en-AU": "Singapore",
		"en-NZ": "Singapore",
		"en-ZA": "Singapore",
		"en-IN": "Singapore",
		"en-SG": "Singapore",
		"pt-AO": "Singapura",
		"pt-MZ": "Singapura",
		"pt-CV": "Singapura",
		"pt-GW": "Singapura",
		"pt-ST": "Singapura",
		"pt-TL": "Singapura",
		"pt-MO": "Singapura",
		"es-ES": "Singapur",
		"es-419": "Singapur",
		"es-AD": "Singapur",
		"es-GI": "Singapur",
		"es-AR": "Singapur",
		"es-BO": "Singapur",
		"es-BR": "Singapur",
		"es-BZ": "Singapur",
		"es-CL": "Singapur",
		"es-CO": "Singapur",
		"es-CR": "Singapur",
		"es-CU": "Singapur",
		"es-DO": "Singapur",
		"es-EC": "Singapur",
		"es-GT": "Singapur",
		"es-HN": "Singapur",
		"es-MX": "Singapur",
		"es-NI": "Singapur",
		"es-PA": "Singapur",
		"es-PE": "Singapur",
		"es-PR": "Singapur",
		"es-PY": "Singapur",
		"es-SV": "Singapur",
		"es-US": "Singapur",
		"es-UY": "Singapur",
		"es-VE": "Singapur",
		"fr-FR": "Singapour",
		"fr-BE": "Singapour",
		"fr-CH": "Singapour",
		"fr-LU": "Singapour",
		"fr-MC": "Singapour",
		"fr-AD": "Singapour",
		"fr-CA": "Singapour",
		"it-IT": "Singapore",
		"it-CH": "Singapore",
		"it-SM": "Singapore",
		"it-VA": "Singapore",
		"de-DE": "Singapur",
		"de-AT": "Singapur",
		"de-CH": "Singapur",
		"de-BE": "Singapur",
		"de-LI": "Singapur",
		"de-LU": "Singapur",
		"nl-NL": "Singapore",
		"nl-BE": "Singapore",
		"sv-SE": "Singapore",
		"sv-FI": "Singapore",
		"da-DK": "Singapore",
		"nb-NO": "Singapore",
		"nn-NO": "Singapore",
		"fi-FI": "Singapore",
		"is-IS": "Singapúr",
		"fo-FO": "Singapor",
		"et-EE": "Singapur",
		"lv-LV": "Singapūra",
		"lt-LT": "Singapūras",
		"pl-PL": "Singapur",
		"cs-CZ": "Singapur",
		"sk-SK": "Singapur",
		"sl-SI": "Singapur",
		"hr-HR": "Singapur",
		"bs-BA": "Singapur",
		"sr-RS": "Сингапур",
		"sr-BA": "Сингапур",
		"sr-ME": "Singapur",
		"mk-MK": "Сингапур",
		"bg-BG": "Сингапур",
		"be-BY": "Сінгапур",
		"uk-UA": "Сінгапур",
		"ru-RU": "Сингапур",
		"el-GR": "Σιγκαπούρη",
		"el-CY": "Σιγκαπούρη",
		"ro-RO": "Singapore",
		"ro-MD": "Singapore",
		"hu-HU": "Szingapúr",
		"sq-AL": "Singapor",
		"sq-XK": "Singapor",
		"mt-MT": "Singapore",
		"ga-IE": "Singeapór",
		"cy-GB": "Singapore",
		"gd-GB": "Singeapòr",
		"lb-LU": "Singapur",
		"ca-ES": "Singapur",
		"ca-AD": "Singapur",
		"ca-FR": "Singapur",
		"ca-IT": "Singapur",
		"eu-ES": "Singapur",
		"eu-FR": "Singapur",
		"gl-ES": "Singapur",
		"tr-TR": "Singapur",
		"tr-CY": "Singapur"
	},
	"callingCode": "65",
	"phoneMasks": [
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[369]|8(?:0[1-9]|[1-9])"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "#### ### ####",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"1"
			]
		},
		{
			"mask": "#### #### ###",
			"minLength": 11,
			"maxLength": 11,
			"leadingDigits": [
				"7"
			]
		}
	]
} satisfies Country;
