import type { Country } from './types.js';

export const SGS = {
	"code": "SGS",
	"labels": {
		"pt-BR": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"pt-PT": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"es-ES": "Islas Georgia del Sur y Sandwich del Sur",
		"es-419": "Islas Georgia del Sur y Sándwich del Sur",
		"es-AR": "Islas Georgia del Sur y Sándwich del Sur",
		"es-BO": "Islas Georgia del Sur y Sándwich del Sur",
		"es-BR": "Islas Georgia del Sur y Sándwich del Sur",
		"es-BZ": "Islas Georgia del Sur y Sándwich del Sur",
		"es-CL": "Islas Georgia del Sur y Sándwich del Sur",
		"es-CO": "Islas Georgia del Sur y Sándwich del Sur",
		"es-CR": "Islas Georgia del Sur y Sándwich del Sur",
		"es-CU": "Islas Georgia del Sur y Sándwich del Sur",
		"es-DO": "Islas Georgia del Sur y Sándwich del Sur",
		"es-EC": "Islas Georgia del Sur y Sándwich del Sur",
		"es-GT": "Islas Georgia del Sur y Sándwich del Sur",
		"es-HN": "Islas Georgia del Sur y Sándwich del Sur",
		"es-MX": "Islas Georgia del Sur y Sándwich del Sur",
		"es-NI": "Islas Georgia del Sur y Sándwich del Sur",
		"es-PA": "Islas Georgia del Sur y Sándwich del Sur",
		"es-PE": "Islas Georgia del Sur y Sándwich del Sur",
		"es-PR": "Islas Georgia del Sur y Sándwich del Sur",
		"es-PY": "Islas Georgia del Sur y Sándwich del Sur",
		"es-SV": "Islas Georgia del Sur y Sándwich del Sur",
		"es-US": "Islas Georgia del Sur y Sándwich del Sur",
		"es-UY": "Islas Georgia del Sur y Sándwich del Sur",
		"es-VE": "Islas Georgia del Sur y Sándwich del Sur",
		"en-US": "South Georgia & South Sandwich Islands",
		"fr-FR": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"fr-BE": "Îles Géorgie du Sud et Sandwich du Sud",
		"fr-CA": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"fr-CH": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"fr-LU": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"fr-MC": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"it-IT": "Georgia del Sud e Sandwich Australi",
		"it-CH": "Georgia del Sud e Sandwich Australi",
		"it-SM": "Georgia del Sud e Sandwich Australi",
		"it-VA": "Georgia del Sud e Sandwich Australi",
		"de-DE": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-AT": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-CH": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-BE": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-LI": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-LU": "Südgeorgien und die Südlichen Sandwichinseln"
	},
	"callingCode": "500"
} satisfies Country;
