import type { Country } from './types.js';

export const SGS = {
	"code": "SGS",
	"labels": {
		"pt-BR": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"pt-PT": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"qu-PE": "Georgia del Sur e Islas Sandwich del Sur",
		"qu-BO": "Georgia del Sur e Islas Sandwich del Sur",
		"qu-EC": "Georgia del Sur e Islas Sandwich del Sur",
		"chr-US": "ᏧᎦᏃᏮ ᏣᎠᏥᎢ ᎠᎴ ᎾᏍᎩ ᏧᎦᏃᏮ ᎠᏍᏛᎭᏟ ᏚᎦᏚᏛᎢ",
		"hi-IN": "दक्षिण जॉर्जिया और दक्षिण सैंडविच द्वीपसमूह",
		"bn-IN": "দক্ষিণ জর্জিয়া ও দক্ষিণ স্যান্ডউইচ দ্বীপপুঞ্জ",
		"bn-BD": "দক্ষিণ জর্জিয়া ও দক্ষিণ স্যান্ডউইচ দ্বীপপুঞ্জ",
		"ta-IN": "தெற்கு ஜார்ஜியா மற்றும் தெற்கு சாண்ட்விச் தீவுகள்",
		"ta-LK": "தெற்கு ஜார்ஜியா மற்றும் தெற்கு சாண்ட்விச் தீவுகள்",
		"ta-SG": "தெற்கு ஜார்ஜியா மற்றும் தெற்கு சாண்ட்விச் தீவுகள்",
		"ta-MY": "தெற்கு ஜார்ஜியா மற்றும் தெற்கு சாண்ட்விச் தீவுகள்",
		"te-IN": "దక్షిణ జార్జియా మరియు దక్షిణ శాండ్విచ్ దీవులు",
		"mr-IN": "दक्षिण जॉर्जिया आणि दक्षिण सँडविच बेटे",
		"gu-IN": "દક્ષિણ જ્યોર્જિયા અને દક્ષિણ સેન્ડવિચ આઇલેન્ડ્સ",
		"kn-IN": "ದಕ್ಷಿಣ ಜಾರ್ಜಿಯಾ ಮತ್ತು ದಕ್ಷಿಣ ಸ್ಯಾಂಡ್‍ವಿಚ್ ದ್ವೀಪಗಳು",
		"ml-IN": "ദക്ഷിണ ജോർജ്ജിയയും ദക്ഷിണ സാൻഡ്‌വിച്ച് ദ്വീപുകളും",
		"pa-IN": "ਦੱਖਣੀ ਜਾਰਜੀਆ ਅਤੇ ਦੱਖਣੀ ਸੈਂਡਵਿਚ ਟਾਪੂ",
		"ur-IN": "جنوبی جارجیا اور جنوبی سینڈوچ جزائر",
		"ur-PK": "جنوبی جارجیا اور جنوبی سینڈوچ جزائر",
		"or-IN": "ଦକ୍ଷିଣ ଜର୍ଜିଆ ଏବଂ ଦକ୍ଷିଣ ସାଣ୍ଡୱିଚ୍ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "দক্ষিণ জৰ্জিয়া আৰু দক্ষিণ চেণ্ডৱিচ দ্বীপপুঞ্জ",
		"ne-IN": "दक्षिण जर्जिया र दक्षिण स्यान्डवीच टापुहरू",
		"ne-NP": "दक्षिण जर्जिया र दक्षिण स्यान्डवीच टापुहरू",
		"si-LK": "දකුණු ජෝර්ජියාව සහ දකුණු සැන්ඩ්විච් දූපත්",
		"kok-IN": "दक्षिण जोर्जिया आनी दक्षिण सॅण्डविच आयलँड्स",
		"ks-IN": "جنوٗبی جارجِیا تہٕ جنوٗبی سینڑوٕچ جٔزیٖرٕ",
		"brx-IN": "खोला जर्जिया आरो खोला सेण्डवीच द्वीपफोर",
		"mai-IN": "दक्षिण जार्जिया आ दक्षिण सैंडविच द्वीपसमूह",
		"dz-BT": "སཱའུཐ་ཇཽར་ཇཱ་ དང་ སཱའུཐ་སེནཌ྄་ཝིཅ་གླིང་ཚོམ",
		"ja-JP": "サウスジョージア・サウスサンドウィッチ諸島",
		"ko-KR": "사우스조지아 사우스샌드위치 제도",
		"ko-KP": "사우스조지아 사우스샌드위치 제도",
		"zh-CN": "南乔治亚和南桑威奇群岛",
		"zh-Hans-CN": "南乔治亚和南桑威奇群岛",
		"zh-Hant-TW": "南喬治亞與南三明治群島",
		"zh-TW": "南喬治亞與南三明治群島",
		"zh-HK": "南佐治亞島與南桑威奇群島",
		"zh-MO": "南佐治亞島與南桑威奇群島",
		"zh-SG": "南乔治亚和南桑威奇群岛",
		"yue-Hant-HK": "南佐治亞島同南桑威奇群島",
		"yue-Hans-CN": "南佐治亚岛同南桑威奇群岛",
		"mn-MN": "Өмнөд Жоржиа ба Өмнөд Сэндвичийн арлууд",
		"ug-CN": "جەنۇبىي جورجىيە ۋە جەنۇبىي ساندۋىچ ئاراللىرى",
		"th-TH": "เกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช",
		"lo-LA": "ໝູ່ເກາະ ຈໍເຈຍຕອນໃຕ້ ແລະ ແຊນວິດຕອນໃຕ້",
		"km-KH": "កោះ​ហ្សកហ្ស៊ី​ខាងត្បូង និង សង់វិច​ខាងត្បូង",
		"my-MM": "တောင် ဂျော်ဂျီယာ နှင့် တောင် ဆင်းဒဝစ်ဂျ် ကျွန်းစုများ",
		"vi-VN": "Nam Georgia & Quần đảo Nam Sandwich",
		"id-ID": "Georgia Selatan & Kep. Sandwich Selatan",
		"ms-MY": "Kepulauan Georgia Selatan & Sandwich Selatan",
		"ms-SG": "Kepulauan Georgia Selatan & Sandwich Selatan",
		"ms-BN": "Kepulauan Georgia Selatan & Sandwich Selatan",
		"jv-ID": "Georgia Kidul lan Kapuloan Sandwich Kidul",
		"fil-PH": "South Georgia & South Sandwich Islands",
		"ceb-PH": "South Georgia & South Sandwich Islands",
		"ka-GE": "სამხრეთ ჯორჯია და სამხრეთ სენდვიჩის კუნძულები",
		"hy-AM": "Հարավային Ջորջիա և Հարավային Սենդվիչյան կղզիներ",
		"az-AZ": "Cənubi Corciya və Cənubi Sendviç adaları",
		"az-Cyrl-AZ": "Ҹәнуби Ҹорҹија вә Ҹәнуби Сендвич адалары",
		"kk-KZ": "Оңтүстік Георгия және Оңтүстік Сандвич аралдары",
		"ky-KG": "Түштүк Жоржия жана Түштүк Сэндвич аралдары",
		"uz-UZ": "Janubiy Georgiya va Janubiy Sendvich orollari",
		"tg-TJ": "Ҷорҷияи Ҷанубӣ ва Ҷазираҳои Сандвич",
		"tk-TM": "Günorta Georgiýa we Günorta Sendwiç adasy",
		"fa-IR": "جورجیای جنوبی و جزایر ساندویچ جنوبی",
		"fa-AF": "جورجیای جنوبی و جزایر ساندویچ جنوبی",
		"ps-AF": "سويلي جارجيا او سويلي سېنډوچ ټاپوګان",
		"ps-PK": "سويلي جارجيا او سويلي سېنډوچ ټاپوګان",
		"he-IL": "ג׳ורג׳יה הדרומית ואיי סנדוויץ׳ הדרומיים",
		"ar-SA": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-AE": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-QA": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-BH": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-KW": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-OM": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-YE": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-IQ": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-JO": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-LB": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-SY": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"ar-PS": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"en-US": "South Georgia & South Sandwich Islands",
		"en-GB": "South Georgia & South Sandwich Islands",
		"en-IE": "South Georgia & South Sandwich Islands",
		"en-MT": "South Georgia & South Sandwich Islands",
		"en-GI": "South Georgia & South Sandwich Islands",
		"en-CY": "South Georgia & South Sandwich Islands",
		"en-JE": "South Georgia & South Sandwich Islands",
		"en-GG": "South Georgia & South Sandwich Islands",
		"en-IM": "South Georgia & South Sandwich Islands",
		"en-CA": "South Georgia and South Sandwich Islands",
		"en-AU": "South Georgia & South Sandwich Islands",
		"en-NZ": "South Georgia & South Sandwich Islands",
		"en-ZA": "South Georgia & South Sandwich Islands",
		"en-IN": "South Georgia & South Sandwich Islands",
		"en-SG": "South Georgia & South Sandwich Islands",
		"pt-AO": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"pt-MZ": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"pt-CV": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"pt-GW": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"pt-ST": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"pt-TL": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"pt-MO": "Ilhas Geórgia do Sul e Sandwich do Sul",
		"es-ES": "Islas Georgia del Sur y Sandwich del Sur",
		"es-419": "Islas Georgia del Sur y Sándwich del Sur",
		"es-AD": "Islas Georgia del Sur y Sandwich del Sur",
		"es-GI": "Islas Georgia del Sur y Sandwich del Sur",
		"es-AR": "Islas Georgia del Sur y Sándwich del Sur",
		"es-BO": "Islas Georgia del Sur y Sándwich del Sur",
		"es-BR": "Islas Georgia del Sur y Sándwich del Sur",
		"es-BZ": "Islas Georgia del Sur y Sándwich del Sur",
		"es-CL": "Islas Georgia del Sur y Sándwich del Sur",
		"es-CO": "Islas Georgia del Sur y Sándwich del Sur",
		"es-CR": "Islas Georgia del Sur y Sándwich del Sur",
		"es-CU": "Islas Georgia del Sur y Sándwich del Sur",
		"es-DO": "Islas Georgia del Sur y Sándwich del Sur",
		"es-EC": "Islas Georgia del Sur y Sándwich del Sur",
		"es-GT": "Islas Georgia del Sur y Sándwich del Sur",
		"es-HN": "Islas Georgia del Sur y Sándwich del Sur",
		"es-MX": "Islas Georgia del Sur y Sándwich del Sur",
		"es-NI": "Islas Georgia del Sur y Sándwich del Sur",
		"es-PA": "Islas Georgia del Sur y Sándwich del Sur",
		"es-PE": "Islas Georgia del Sur y Sándwich del Sur",
		"es-PR": "Islas Georgia del Sur y Sándwich del Sur",
		"es-PY": "Islas Georgia del Sur y Sándwich del Sur",
		"es-SV": "Islas Georgia del Sur y Sándwich del Sur",
		"es-US": "Islas Georgia del Sur y Sándwich del Sur",
		"es-UY": "Islas Georgia del Sur y Sándwich del Sur",
		"es-VE": "Islas Georgia del Sur y Sándwich del Sur",
		"fr-FR": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"fr-BE": "Îles Géorgie du Sud et Sandwich du Sud",
		"fr-CH": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"fr-LU": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"fr-MC": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"fr-AD": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"fr-CA": "Géorgie du Sud-et-les Îles Sandwich du Sud",
		"it-IT": "Georgia del Sud e Sandwich Australi",
		"it-CH": "Georgia del Sud e Sandwich Australi",
		"it-SM": "Georgia del Sud e Sandwich Australi",
		"it-VA": "Georgia del Sud e Sandwich Australi",
		"de-DE": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-AT": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-CH": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-BE": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-LI": "Südgeorgien und die Südlichen Sandwichinseln",
		"de-LU": "Südgeorgien und die Südlichen Sandwichinseln",
		"nl-NL": "Zuid-Georgia en Zuidelijke Sandwicheilanden",
		"nl-BE": "Zuid-Georgia en Zuidelijke Sandwicheilanden",
		"sv-SE": "Sydgeorgien och Sydsandwichöarna",
		"sv-FI": "Sydgeorgien och Sydsandwichöarna",
		"da-DK": "South Georgia og De Sydlige Sandwichøer",
		"nb-NO": "Sør-Georgia og Sør-Sandwichøyene",
		"nn-NO": "Sør-Georgia og Sør-Sandwichøyane",
		"fi-FI": "Etelä-Georgia ja Eteläiset Sandwichinsaaret",
		"is-IS": "Suður-Georgía og Suður-Sandvíkureyjar",
		"fo-FO": "Suðurgeorgia og Suðursandwichoyggjar",
		"et-EE": "Lõuna-Georgia ja Lõuna-Sandwichi saared",
		"lv-LV": "Dienviddžordžija un Dienvidsendviču salas",
		"lt-LT": "Pietų Džordžija ir Pietų Sandvičo salos",
		"pl-PL": "Georgia Południowa i Sandwich Południowy",
		"cs-CZ": "Jižní Georgie a Jižní Sandwichovy ostrovy",
		"sk-SK": "Južná Georgia a Južné Sandwichove ostrovy",
		"sl-SI": "Južna Georgia in Južni Sandwichevi otoki",
		"hr-HR": "Južna Georgia i Otoci Južni Sandwich",
		"bs-BA": "Južna Džordžija i Južna Sendvič ostrva",
		"sr-RS": "Јужна Џорџија и Јужна Сендвичка Острва",
		"sr-BA": "Јужна Џорџија и Јужна Сендвичка острва",
		"sr-ME": "Južna Džordžija i Južna Sendvička Ostrva",
		"mk-MK": "Јужна Џорџија и Јужни Сендвички Острови",
		"bg-BG": "Южна Джорджия и Южни Сандвичеви острови",
		"be-BY": "Паўднёвая Георгія і Паўднёвыя Сандвічавы астравы",
		"uk-UA": "Південна Джорджія та Південні Сандвічеві Острови",
		"ru-RU": "Южная Георгия и Южные Сандвичевы о-ва",
		"el-GR": "Νήσοι Νότια Γεωργία και Νότιες Σάντουιτς",
		"el-CY": "Νήσοι Νότια Γεωργία και Νότιες Σάντουιτς",
		"ro-RO": "Georgia de Sud și Insulele Sandwich de Sud",
		"ro-MD": "Georgia de Sud și Insulele Sandwich de Sud",
		"hu-HU": "Déli-Georgia és Déli-Sandwich-szigetek",
		"sq-AL": "Xhorxha Jugore dhe Ishujt Senduiçë të Jugut",
		"sq-XK": "Xhorxha Jugore dhe Ishujt Senduiçë të Jugut",
		"mt-MT": "il-Georgia tan-Nofsinhar u l-Gżejjer Sandwich tan-Nofsinhar",
		"ga-IE": "An tSeoirsia Theas agus Oileáin Sandwich Theas",
		"cy-GB": "De Georgia ac Ynysoedd Sandwich y De",
		"gd-GB": "Seòirsea a Deas is na h-Eileanan Sandwich a Deas",
		"lb-LU": "Südgeorgien an déi Südlech Sandwichinselen",
		"ca-ES": "Illes Geòrgia del Sud i Sandwich del Sud",
		"ca-AD": "Illes Geòrgia del Sud i Sandwich del Sud",
		"ca-FR": "Illes Geòrgia del Sud i Sandwich del Sud",
		"ca-IT": "Illes Geòrgia del Sud i Sandwich del Sud",
		"eu-ES": "Hegoaldeko Georgia eta Hegoaldeko Sandwich uharteak",
		"eu-FR": "Hegoaldeko Georgia eta Hegoaldeko Sandwich uharteak",
		"gl-ES": "Illas Xeorxia do Sur e Sandwich do Sur",
		"tr-TR": "Güney Georgia ve Güney Sandwich Adaları",
		"tr-CY": "Güney Georgia ve Güney Sandwich Adaları"
	},
	"callingCode": "500"
} satisfies Country;
