import type { Country } from './types.js';

export const SHN = {
	"code": "SHN",
	"labels": {
		"pt-BR": "Santa Helena",
		"pt-PT": "Santa Helena",
		"qu-PE": "Santa Elena",
		"qu-BO": "Santa Elena",
		"qu-EC": "Santa Elena",
		"chr-US": "ᎤᏓᏅᏘ ᎮᎵᎾ",
		"hi-IN": "सेंट हेलेना",
		"bn-IN": "সেন্ট হেলেনা",
		"bn-BD": "সেন্ট হেলেনা",
		"ta-IN": "செயின்ட் ஹெலெனா",
		"ta-LK": "செயின்ட் ஹெலெனா",
		"ta-SG": "செயின்ட் ஹெலெனா",
		"ta-MY": "செயின்ட் ஹெலெனா",
		"te-IN": "సెయింట్ హెలెనా",
		"mr-IN": "सेंट हेलेना",
		"gu-IN": "સેંટ હેલેના",
		"kn-IN": "ಸೇಂಟ್ ಹೆಲೆನಾ",
		"ml-IN": "സെന്റ് ഹെലീന",
		"pa-IN": "ਸੇਂਟ ਹੇਲੇਨਾ",
		"ur-IN": "سینٹ ہیلینا",
		"ur-PK": "سینٹ ہیلینا",
		"or-IN": "ସେଣ୍ଟ ହେଲେନା",
		"as-IN": "ছেইণ্ট হেলেনা",
		"ne-IN": "सेन्ट हेलेना",
		"ne-NP": "सेन्ट हेलेना",
		"si-LK": "ශාන්ත හෙලේනා",
		"kok-IN": "सेंट हेलिना",
		"ks-IN": "سینٹ ہؠلِنا",
		"brx-IN": "सैन्ट हेलेना",
		"mai-IN": "सेंट हेलेना",
		"dz-BT": "སེནཊ་ ཧེ་ལི་ན",
		"ja-JP": "セントヘレナ",
		"ko-KR": "세인트헬레나",
		"ko-KP": "세인트헬레나",
		"zh-CN": "圣赫勒拿",
		"zh-Hans-CN": "圣赫勒拿",
		"zh-Hant-TW": "聖赫勒拿島",
		"zh-TW": "聖赫勒拿島",
		"zh-HK": "聖赫勒拿島",
		"zh-MO": "聖赫勒拿島",
		"zh-SG": "圣赫勒拿",
		"yue-Hant-HK": "聖赫勒拿島",
		"yue-Hans-CN": "圣赫勒拿岛",
		"mn-MN": "Сент Хелена",
		"ug-CN": "ساينىت ھېلېنا",
		"th-TH": "เซนต์เฮเลนา",
		"lo-LA": "ເຊນ ເຮເລນາ",
		"km-KH": "សង់​ហេឡេណា",
		"my-MM": "စိန့်ဟယ်လယ်နာ",
		"vi-VN": "St. Helena",
		"id-ID": "Saint Helena",
		"ms-MY": "Saint Helena",
		"ms-SG": "Saint Helena",
		"ms-BN": "Saint Helena",
		"jv-ID": "Saint Héléna",
		"fil-PH": "St. Helena",
		"ceb-PH": "St. Helena",
		"ka-GE": "წმინდა ელენეს კუნძული",
		"hy-AM": "Սուրբ Հեղինեի կղզի",
		"az-AZ": "Müqəddəs Yelena",
		"az-Cyrl-AZ": "Мүгәддәс Јелена",
		"kk-KZ": "Әулие Елена аралы",
		"ky-KG": "Ыйык Елена",
		"uz-UZ": "Muqaddas Yelena oroli",
		"tg-TJ": "Сент Елена",
		"tk-TM": "Keramatly Ýelena adasy",
		"fa-IR": "سنت هلن",
		"fa-AF": "سنت هلن",
		"ps-AF": "سینټ هیلینا",
		"ps-PK": "سینټ هیلینا",
		"he-IL": "סנט הלנה",
		"ar-SA": "سانت هيلينا",
		"ar-AE": "سانت هيلينا",
		"ar-QA": "سانت هيلينا",
		"ar-BH": "سانت هيلينا",
		"ar-KW": "سانت هيلينا",
		"ar-OM": "سانت هيلينا",
		"ar-YE": "سانت هيلينا",
		"ar-IQ": "سانت هيلينا",
		"ar-JO": "سانت هيلينا",
		"ar-LB": "سانت هيلينا",
		"ar-SY": "سانت هيلينا",
		"ar-PS": "سانت هيلينا",
		"en-US": "St. Helena",
		"en-GB": "St Helena",
		"en-IE": "St Helena",
		"en-MT": "St Helena",
		"en-GI": "St Helena",
		"en-CY": "St Helena",
		"en-JE": "St Helena",
		"en-GG": "St Helena",
		"en-IM": "St Helena",
		"en-CA": "Saint Helena",
		"en-AU": "St Helena",
		"en-NZ": "St Helena",
		"en-ZA": "St Helena",
		"en-IN": "St Helena",
		"en-SG": "St Helena",
		"pt-AO": "Santa Helena",
		"pt-MZ": "Santa Helena",
		"pt-CV": "Santa Helena",
		"pt-GW": "Santa Helena",
		"pt-ST": "Santa Helena",
		"pt-TL": "Santa Helena",
		"pt-MO": "Santa Helena",
		"es-ES": "Santa Elena",
		"es-419": "Santa Elena",
		"es-AD": "Santa Elena",
		"es-GI": "Santa Elena",
		"es-AR": "Santa Elena",
		"es-BO": "Santa Elena",
		"es-BR": "Santa Elena",
		"es-BZ": "Santa Elena",
		"es-CL": "Santa Elena",
		"es-CO": "Santa Elena",
		"es-CR": "Santa Elena",
		"es-CU": "Santa Elena",
		"es-DO": "Santa Elena",
		"es-EC": "Santa Elena",
		"es-GT": "Santa Elena",
		"es-HN": "Santa Elena",
		"es-MX": "Santa Elena",
		"es-NI": "Santa Elena",
		"es-PA": "Santa Elena",
		"es-PE": "Santa Elena",
		"es-PR": "Santa Elena",
		"es-PY": "Santa Elena",
		"es-SV": "Santa Elena",
		"es-US": "Santa Elena",
		"es-UY": "Santa Elena",
		"es-VE": "Santa Elena",
		"fr-FR": "Sainte-Hélène",
		"fr-BE": "Sainte-Hélène",
		"fr-CH": "Sainte-Hélène",
		"fr-LU": "Sainte-Hélène",
		"fr-MC": "Sainte-Hélène",
		"fr-AD": "Sainte-Hélène",
		"fr-CA": "Sainte-Hélène",
		"it-IT": "Sant’Elena",
		"it-CH": "Sant’Elena",
		"it-SM": "Sant’Elena",
		"it-VA": "Sant’Elena",
		"de-DE": "St. Helena",
		"de-AT": "St. Helena",
		"de-CH": "St. Helena",
		"de-BE": "St. Helena",
		"de-LI": "St. Helena",
		"de-LU": "St. Helena",
		"nl-NL": "Sint-Helena",
		"nl-BE": "Sint-Helena",
		"sv-SE": "S:t Helena",
		"sv-FI": "S:t Helena",
		"da-DK": "St. Helena",
		"nb-NO": "St. Helena",
		"nn-NO": "Saint Helena",
		"fi-FI": "Saint Helena",
		"is-IS": "Sankti Helena",
		"fo-FO": "St. Helena",
		"et-EE": "Saint Helena",
		"lv-LV": "Sv.Helēnas sala",
		"lt-LT": "Šv. Elenos Sala",
		"pl-PL": "Wyspa Świętej Heleny",
		"cs-CZ": "Svatá Helena",
		"sk-SK": "Svätá Helena",
		"sl-SI": "Sveta Helena",
		"hr-HR": "Sveta Helena",
		"bs-BA": "Sveta Helena",
		"sr-RS": "Света Јелена",
		"sr-BA": "Света Јелена",
		"sr-ME": "Sveta Jelena",
		"mk-MK": "Света Елена",
		"bg-BG": "Света Елена",
		"be-BY": "Востраў Святой Алены",
		"uk-UA": "Острів Святої Єлени",
		"ru-RU": "о-в Св. Елены",
		"el-GR": "Αγία Ελένη",
		"el-CY": "Αγία Ελένη",
		"ro-RO": "Sfânta Elena",
		"ro-MD": "Sfânta Elena",
		"hu-HU": "Szent Ilona",
		"sq-AL": "Shën-Elenë",
		"sq-XK": "Shën-Elenë",
		"mt-MT": "Saint Helena",
		"ga-IE": "San Héilin",
		"cy-GB": "Saint Helena",
		"gd-GB": "Eilean Naomh Eilidh",
		"lb-LU": "St. Helena",
		"ca-ES": "Santa Helena",
		"ca-AD": "Santa Helena",
		"ca-FR": "Santa Helena",
		"ca-IT": "Santa Helena",
		"eu-ES": "Santa Helena",
		"eu-FR": "Santa Helena",
		"gl-ES": "Santa Helena",
		"tr-TR": "Saint Helena",
		"tr-CY": "Saint Helena"
	},
	"callingCode": "290",
	"phoneMasks": [
		{
			"mask": "####",
			"minLength": 4,
			"maxLength": 4
		},
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		}
	]
} satisfies Country;
