import type { Country } from './types.js';

export const SHN = {
	"code": "SHN",
	"labels": {
		"pt-BR": "Santa Helena",
		"pt-PT": "Santa Helena",
		"es-ES": "Santa Elena",
		"es-419": "Santa Elena",
		"es-AR": "Santa Elena",
		"es-BO": "Santa Elena",
		"es-BR": "Santa Elena",
		"es-BZ": "Santa Elena",
		"es-CL": "Santa Elena",
		"es-CO": "Santa Elena",
		"es-CR": "Santa Elena",
		"es-CU": "Santa Elena",
		"es-DO": "Santa Elena",
		"es-EC": "Santa Elena",
		"es-GT": "Santa Elena",
		"es-HN": "Santa Elena",
		"es-MX": "Santa Elena",
		"es-NI": "Santa Elena",
		"es-PA": "Santa Elena",
		"es-PE": "Santa Elena",
		"es-PR": "Santa Elena",
		"es-PY": "Santa Elena",
		"es-SV": "Santa Elena",
		"es-US": "Santa Elena",
		"es-UY": "Santa Elena",
		"es-VE": "Santa Elena",
		"en-US": "St. Helena",
		"fr-FR": "Sainte-Hélène",
		"fr-BE": "Sainte-Hélène",
		"fr-CA": "Sainte-Hélène",
		"fr-CH": "Sainte-Hélène",
		"fr-LU": "Sainte-Hélène",
		"fr-MC": "Sainte-Hélène",
		"it-IT": "Sant’Elena",
		"it-CH": "Sant’Elena",
		"it-SM": "Sant’Elena",
		"it-VA": "Sant’Elena",
		"de-DE": "St. Helena",
		"de-AT": "St. Helena",
		"de-CH": "St. Helena",
		"de-BE": "St. Helena",
		"de-LI": "St. Helena",
		"de-LU": "St. Helena"
	},
	"callingCode": "290"
} satisfies Country;
