import type { Country } from './types.js';

export const SJM = {
	"code": "SJM",
	"labels": {
		"pt-BR": "Svalbard e Jan Mayen",
		"pt-PT": "Svalbard e Jan Mayen",
		"es-ES": "Svalbard y Jan Mayen",
		"es-419": "Svalbard y Jan Mayen",
		"es-AR": "Svalbard y Jan Mayen",
		"es-BO": "Svalbard y Jan Mayen",
		"es-BR": "Svalbard y Jan Mayen",
		"es-BZ": "Svalbard y Jan Mayen",
		"es-CL": "Svalbard y Jan Mayen",
		"es-CO": "Svalbard y Jan Mayen",
		"es-CR": "Svalbard y Jan Mayen",
		"es-CU": "Svalbard y Jan Mayen",
		"es-DO": "Svalbard y Jan Mayen",
		"es-EC": "Svalbard y Jan Mayen",
		"es-GT": "Svalbard y Jan Mayen",
		"es-HN": "Svalbard y Jan Mayen",
		"es-MX": "Svalbard y Jan Mayen",
		"es-NI": "Svalbard y Jan Mayen",
		"es-PA": "Svalbard y Jan Mayen",
		"es-PE": "Svalbard y Jan Mayen",
		"es-PR": "Svalbard y Jan Mayen",
		"es-PY": "Svalbard y Jan Mayen",
		"es-SV": "Svalbard y Jan Mayen",
		"es-US": "Svalbard y Jan Mayen",
		"es-UY": "Svalbard y Jan Mayen",
		"es-VE": "Svalbard y Jan Mayen",
		"en-US": "Svalbard & Jan Mayen",
		"fr-FR": "Svalbard et Jan Mayen",
		"fr-BE": "Svalbard et Jan Mayen",
		"fr-CA": "Svalbard et Jan Mayen",
		"fr-CH": "Svalbard et Jan Mayen",
		"fr-LU": "Svalbard et Jan Mayen",
		"fr-MC": "Svalbard et Jan Mayen",
		"it-IT": "Svalbard e Jan Mayen",
		"it-CH": "Svalbard e Jan Mayen",
		"it-SM": "Svalbard e Jan Mayen",
		"it-VA": "Svalbard e Jan Mayen",
		"de-DE": "Spitzbergen und Jan Mayen",
		"de-AT": "Svalbard und Jan Mayen",
		"de-CH": "Spitzbergen und Jan Mayen",
		"de-BE": "Spitzbergen und Jan Mayen",
		"de-LI": "Spitzbergen und Jan Mayen",
		"de-LU": "Spitzbergen und Jan Mayen"
	}
} satisfies Country;
