import type { Country } from './types.js';

export const SLB = {
	"code": "SLB",
	"labels": {
		"pt-BR": "Ilhas Salomão",
		"pt-PT": "Ilhas Salomão",
		"es-ES": "Islas Salomón",
		"es-419": "Islas Salomón",
		"es-AR": "Islas Salomón",
		"es-BO": "Islas Salomón",
		"es-BR": "Islas Salomón",
		"es-BZ": "Islas Salomón",
		"es-CL": "Islas Salomón",
		"es-CO": "Islas Salomón",
		"es-CR": "Islas Salomón",
		"es-CU": "Islas Salomón",
		"es-DO": "Islas Salomón",
		"es-EC": "Islas Salomón",
		"es-GT": "Islas Salomón",
		"es-HN": "Islas Salomón",
		"es-MX": "Islas Salomón",
		"es-NI": "Islas Salomón",
		"es-PA": "Islas Salomón",
		"es-PE": "Islas Salomón",
		"es-PR": "Islas Salomón",
		"es-PY": "Islas Salomón",
		"es-SV": "Islas Salomón",
		"es-US": "Islas Salomón",
		"es-UY": "Islas Salomón",
		"es-VE": "Islas Salomón",
		"en-US": "Solomon Islands",
		"fr-FR": "Îles Salomon",
		"fr-BE": "Îles Salomon",
		"fr-CA": "Îles Salomon",
		"fr-CH": "Îles Salomon",
		"fr-LU": "Îles Salomon",
		"fr-MC": "Îles Salomon",
		"it-IT": "Isole Salomone",
		"it-CH": "Isole Salomone",
		"it-SM": "Isole Salomone",
		"it-VA": "Isole Salomone",
		"de-DE": "Salomonen",
		"de-AT": "Salomonen",
		"de-CH": "Salomon-Inseln",
		"de-BE": "Salomonen",
		"de-LI": "Salomonen",
		"de-LU": "Salomonen"
	}
} satisfies Country;
