import type { Country } from './types.js';

export const SLB = {
	"code": "SLB",
	"labels": {
		"pt-BR": "Ilhas Salomão",
		"pt-PT": "Ilhas Salomão",
		"qu-PE": "Islas Salomón",
		"qu-BO": "Islas Salomón",
		"qu-EC": "Islas Salomón",
		"chr-US": "ᏐᎶᎹᏂ ᏚᎦᏚᏛᎢ",
		"hi-IN": "सोलोमन द्वीपसमूह",
		"bn-IN": "সলোমন দ্বীপপুঞ্জ",
		"bn-BD": "সলোমন দ্বীপপুঞ্জ",
		"ta-IN": "சாலமன் தீவுகள்",
		"ta-LK": "சாலமன் தீவுகள்",
		"ta-SG": "சாலமன் தீவுகள்",
		"ta-MY": "சாலமன் தீவுகள்",
		"te-IN": "సోలమన్ దీవులు",
		"mr-IN": "सोलोमन बेटे",
		"gu-IN": "સોલોમન આઇલેન્ડ્સ",
		"kn-IN": "ಸಾಲೊಮನ್ ದ್ವೀಪಗಳು",
		"ml-IN": "സോളമൻ ദ്വീപുകൾ",
		"pa-IN": "ਸੋਲੋਮਨ ਟਾਪੂ",
		"ur-IN": "جزائر سلیمان",
		"ur-PK": "سولومن آئلینڈز",
		"or-IN": "ସୋଲୋମନ୍‌ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "চোলোমোন দ্বীপপুঞ্জ",
		"ne-IN": "सोलोमन टापुहरू",
		"ne-NP": "सोलोमन टापुहरू",
		"si-LK": "සොලමන් දූපත්",
		"kok-IN": "सोलोमन आइलँड्स",
		"ks-IN": "سولامان جٔزیٖرٕ",
		"brx-IN": "सल’मन द्वीप",
		"mai-IN": "सोलोमन द्वीपसमूह",
		"dz-BT": "སོ་ལོ་མོན་ གླིང་ཚོམ",
		"ja-JP": "ソロモン諸島",
		"ko-KR": "솔로몬 제도",
		"ko-KP": "솔로몬 제도",
		"zh-CN": "所罗门群岛",
		"zh-Hans-CN": "所罗门群岛",
		"zh-Hant-TW": "索羅門群島",
		"zh-TW": "索羅門群島",
		"zh-HK": "所羅門群島",
		"zh-MO": "所羅門群島",
		"zh-SG": "所罗门群岛",
		"yue-Hant-HK": "索羅門群島",
		"yue-Hans-CN": "索罗门群岛",
		"mn-MN": "Соломоны арлууд",
		"ug-CN": "سولومون ئاراللىرى",
		"th-TH": "หมู่เกาะโซโลมอน",
		"lo-LA": "ຫມູ່ເກາະໂຊໂລມອນ",
		"km-KH": "កោះ​សូឡូម៉ុង",
		"my-MM": "ဆော်လမွန်ကျွန်းစု",
		"vi-VN": "Quần đảo Solomon",
		"id-ID": "Kepulauan Solomon",
		"ms-MY": "Kepulauan Solomon",
		"ms-SG": "Kepulauan Solomon",
		"ms-BN": "Kepulauan Solomon",
		"jv-ID": "Kapuloan Suleman",
		"fil-PH": "Solomon Islands",
		"ceb-PH": "Solomon Islands",
		"ka-GE": "სოლომონის კუნძულები",
		"hy-AM": "Սողոմոնյան կղզիներ",
		"az-AZ": "Solomon adaları",
		"az-Cyrl-AZ": "Соломон адалары",
		"kk-KZ": "Соломон аралдары",
		"ky-KG": "Соломон аралдары",
		"uz-UZ": "Solomon orollari",
		"tg-TJ": "Ҷазираҳои Соломон",
		"tk-TM": "Solomon adalary",
		"fa-IR": "جزایر سلیمان",
		"fa-AF": "جزایر سلیمان",
		"ps-AF": "سليمان ټاپوګان",
		"ps-PK": "سليمان ټاپوګان",
		"he-IL": "איי שלמה",
		"ar-SA": "جزر سليمان",
		"ar-AE": "جزر سليمان",
		"ar-QA": "جزر سليمان",
		"ar-BH": "جزر سليمان",
		"ar-KW": "جزر سليمان",
		"ar-OM": "جزر سليمان",
		"ar-YE": "جزر سليمان",
		"ar-IQ": "جزر سليمان",
		"ar-JO": "جزر سليمان",
		"ar-LB": "جزر سليمان",
		"ar-SY": "جزر سليمان",
		"ar-PS": "جزر سليمان",
		"en-US": "Solomon Islands",
		"en-GB": "Solomon Islands",
		"en-IE": "Solomon Islands",
		"en-MT": "Solomon Islands",
		"en-GI": "Solomon Islands",
		"en-CY": "Solomon Islands",
		"en-JE": "Solomon Islands",
		"en-GG": "Solomon Islands",
		"en-IM": "Solomon Islands",
		"en-CA": "Solomon Islands",
		"en-AU": "Solomon Islands",
		"en-NZ": "Solomon Islands",
		"en-ZA": "Solomon Islands",
		"en-IN": "Solomon Islands",
		"en-SG": "Solomon Islands",
		"pt-AO": "Ilhas Salomão",
		"pt-MZ": "Ilhas Salomão",
		"pt-CV": "Ilhas Salomão",
		"pt-GW": "Ilhas Salomão",
		"pt-ST": "Ilhas Salomão",
		"pt-TL": "Ilhas Salomão",
		"pt-MO": "Ilhas Salomão",
		"es-ES": "Islas Salomón",
		"es-419": "Islas Salomón",
		"es-AD": "Islas Salomón",
		"es-GI": "Islas Salomón",
		"es-AR": "Islas Salomón",
		"es-BO": "Islas Salomón",
		"es-BR": "Islas Salomón",
		"es-BZ": "Islas Salomón",
		"es-CL": "Islas Salomón",
		"es-CO": "Islas Salomón",
		"es-CR": "Islas Salomón",
		"es-CU": "Islas Salomón",
		"es-DO": "Islas Salomón",
		"es-EC": "Islas Salomón",
		"es-GT": "Islas Salomón",
		"es-HN": "Islas Salomón",
		"es-MX": "Islas Salomón",
		"es-NI": "Islas Salomón",
		"es-PA": "Islas Salomón",
		"es-PE": "Islas Salomón",
		"es-PR": "Islas Salomón",
		"es-PY": "Islas Salomón",
		"es-SV": "Islas Salomón",
		"es-US": "Islas Salomón",
		"es-UY": "Islas Salomón",
		"es-VE": "Islas Salomón",
		"fr-FR": "Îles Salomon",
		"fr-BE": "Îles Salomon",
		"fr-CH": "Îles Salomon",
		"fr-LU": "Îles Salomon",
		"fr-MC": "Îles Salomon",
		"fr-AD": "Îles Salomon",
		"fr-CA": "Îles Salomon",
		"it-IT": "Isole Salomone",
		"it-CH": "Isole Salomone",
		"it-SM": "Isole Salomone",
		"it-VA": "Isole Salomone",
		"de-DE": "Salomonen",
		"de-AT": "Salomonen",
		"de-CH": "Salomon-Inseln",
		"de-BE": "Salomonen",
		"de-LI": "Salomonen",
		"de-LU": "Salomonen",
		"nl-NL": "Salomonseilanden",
		"nl-BE": "Salomonseilanden",
		"sv-SE": "Salomonöarna",
		"sv-FI": "Salomonöarna",
		"da-DK": "Salomonøerne",
		"nb-NO": "Salomonøyene",
		"nn-NO": "Salomonøyane",
		"fi-FI": "Salomonsaaret",
		"is-IS": "Salómonseyjar",
		"fo-FO": "Salomonoyggjar",
		"et-EE": "Saalomoni Saared",
		"lv-LV": "Zālamana salas",
		"lt-LT": "Saliamono Salos",
		"pl-PL": "Wyspy Salomona",
		"cs-CZ": "Šalamounovy ostrovy",
		"sk-SK": "Šalamúnove ostrovy",
		"sl-SI": "Salomonovi otoki",
		"hr-HR": "Salomonovi Otoci",
		"bs-BA": "Solomonska Ostrva",
		"sr-RS": "Соломонска Острва",
		"sr-BA": "Соломонска Острва",
		"sr-ME": "Solomonska Ostrva",
		"mk-MK": "Соломонски Острови",
		"bg-BG": "Соломонови острови",
		"be-BY": "Саламонавы астравы",
		"uk-UA": "Соломонові Острови",
		"ru-RU": "Соломоновы о-ва",
		"el-GR": "Νήσοι Σολομώντος",
		"el-CY": "Νήσοι Σολομώντος",
		"ro-RO": "Insulele Solomon",
		"ro-MD": "Insulele Solomon",
		"hu-HU": "Salamon-szigetek",
		"sq-AL": "Ishujt Solomon",
		"sq-XK": "Ishujt Solomon",
		"mt-MT": "il-Gżejjer Solomon",
		"ga-IE": "Oileáin Sholaimh",
		"cy-GB": "Ynysoedd Solomon",
		"gd-GB": "Eileanan Sholaimh",
		"lb-LU": "Salomonen",
		"ca-ES": "Illes Salomó",
		"ca-AD": "Illes Salomó",
		"ca-FR": "Illes Salomó",
		"ca-IT": "Illes Salomó",
		"eu-ES": "Salomon Uharteak",
		"eu-FR": "Salomon Uharteak",
		"gl-ES": "Illas Salomón",
		"tr-TR": "Solomon Adaları",
		"tr-CY": "Solomon Adaları"
	},
	"callingCode": "677",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"6[89]|7|8[4-9]|9(?:[1-8]|9[0-8])"
			]
		}
	]
} satisfies Country;
