import type { Country } from './types.js';

export const SLE = {
	"code": "SLE",
	"labels": {
		"pt-BR": "Serra Leoa",
		"pt-PT": "Serra Leoa",
		"es-ES": "Sierra Leona",
		"es-419": "Sierra Leona",
		"es-AR": "Sierra Leona",
		"es-BO": "Sierra Leona",
		"es-BR": "Sierra Leona",
		"es-BZ": "Sierra Leona",
		"es-CL": "Sierra Leona",
		"es-CO": "Sierra Leona",
		"es-CR": "Sierra Leona",
		"es-CU": "Sierra Leona",
		"es-DO": "Sierra Leona",
		"es-EC": "Sierra Leona",
		"es-GT": "Sierra Leona",
		"es-HN": "Sierra Leona",
		"es-MX": "Sierra Leona",
		"es-NI": "Sierra Leona",
		"es-PA": "Sierra Leona",
		"es-PE": "Sierra Leona",
		"es-PR": "Sierra Leona",
		"es-PY": "Sierra Leona",
		"es-SV": "Sierra Leona",
		"es-US": "Sierra Leona",
		"es-UY": "Sierra Leona",
		"es-VE": "Sierra Leona",
		"en-US": "Sierra Leone",
		"fr-FR": "Sierra Leone",
		"fr-BE": "Sierra Leone",
		"fr-CA": "Sierra Leone",
		"fr-CH": "Sierra Leone",
		"fr-LU": "Sierra Leone",
		"fr-MC": "Sierra Leone",
		"it-IT": "Sierra Leone",
		"it-CH": "Sierra Leone",
		"it-SM": "Sierra Leone",
		"it-VA": "Sierra Leone",
		"de-DE": "Sierra Leone",
		"de-AT": "Sierra Leone",
		"de-CH": "Sierra Leone",
		"de-BE": "Sierra Leone",
		"de-LI": "Sierra Leone",
		"de-LU": "Sierra Leone"
	}
} satisfies Country;
