import type { Country } from './types.js';

export const SLV = {
	"code": "SLV",
	"labels": {
		"pt-BR": "El Salvador",
		"pt-PT": "Salvador",
		"es-ES": "El Salvador",
		"es-419": "El Salvador",
		"es-AR": "El Salvador",
		"es-BO": "El Salvador",
		"es-BR": "El Salvador",
		"es-BZ": "El Salvador",
		"es-CL": "El Salvador",
		"es-CO": "El Salvador",
		"es-CR": "El Salvador",
		"es-CU": "El Salvador",
		"es-DO": "El Salvador",
		"es-EC": "El Salvador",
		"es-GT": "El Salvador",
		"es-HN": "El Salvador",
		"es-MX": "El Salvador",
		"es-NI": "El Salvador",
		"es-PA": "El Salvador",
		"es-PE": "El Salvador",
		"es-PR": "El Salvador",
		"es-PY": "El Salvador",
		"es-SV": "El Salvador",
		"es-US": "El Salvador",
		"es-UY": "El Salvador",
		"es-VE": "El Salvador",
		"en-US": "El Salvador",
		"fr-FR": "Salvador",
		"fr-BE": "Salvador",
		"fr-CA": "Salvador",
		"fr-CH": "Salvador",
		"fr-LU": "Salvador",
		"fr-MC": "Salvador",
		"it-IT": "El Salvador",
		"it-CH": "El Salvador",
		"it-SM": "El Salvador",
		"it-VA": "El Salvador",
		"de-DE": "El Salvador",
		"de-AT": "El Salvador",
		"de-CH": "El Salvador",
		"de-BE": "El Salvador",
		"de-LI": "El Salvador",
		"de-LU": "El Salvador"
	},
	"callingCode": "503"
} satisfies Country;
