import type { Country } from './types.js';

export const SMR = {
	"code": "SMR",
	"labels": {
		"pt-BR": "San Marino",
		"pt-PT": "São Marinho",
		"qu-PE": "San Marino",
		"qu-BO": "San Marino",
		"qu-EC": "San Marino",
		"chr-US": "ᎤᏓᏅᏘ ᎹᎵᎢᏃ",
		"hi-IN": "सैन मेरीनो",
		"bn-IN": "সান মারিনো",
		"bn-BD": "সান মারিনো",
		"ta-IN": "சான் மரினோ",
		"ta-LK": "சான் மரினோ",
		"ta-SG": "சான் மரினோ",
		"ta-MY": "சான் மரினோ",
		"te-IN": "శాన్ మారినో",
		"mr-IN": "सॅन मरीनो",
		"gu-IN": "સૅન મેરિનો",
		"kn-IN": "ಸ್ಯಾನ್ ಮೆರಿನೋ",
		"ml-IN": "സാൻ മറിനോ",
		"pa-IN": "ਸੈਨ ਮਰੀਨੋ",
		"ur-IN": "سان مارینو",
		"ur-PK": "سان مارینو",
		"or-IN": "ସାନ୍ ମାରିନୋ",
		"as-IN": "চান মাৰিনো",
		"ne-IN": "सान् मारिनो",
		"ne-NP": "सान् मारिनो",
		"si-LK": "සැන් මැරිනෝ",
		"kok-IN": "सॅन मारीनो",
		"ks-IN": "سین میرِنو",
		"brx-IN": "सान मेरिन’",
		"mai-IN": "सेन मरीनो",
		"dz-BT": "སཱན་མ་རི་ནོ",
		"ja-JP": "サンマリノ",
		"ko-KR": "산마리노",
		"ko-KP": "산마리노",
		"zh-CN": "圣马力诺",
		"zh-Hans-CN": "圣马力诺",
		"zh-Hant-TW": "聖馬利諾",
		"zh-TW": "聖馬利諾",
		"zh-HK": "聖馬力諾",
		"zh-MO": "聖馬力諾",
		"zh-SG": "圣马力诺",
		"yue-Hant-HK": "聖馬利諾",
		"yue-Hans-CN": "圣马利诺",
		"mn-MN": "Сан-Марино",
		"ug-CN": "سان مارىنو",
		"th-TH": "ซานมาริโน",
		"lo-LA": "ແຊນ ມາຣິໂນ",
		"km-KH": "សាន​ម៉ារីណូ",
		"my-MM": "ဆန်မာရီနို",
		"vi-VN": "San Marino",
		"id-ID": "San Marino",
		"ms-MY": "San Marino",
		"ms-SG": "San Marino",
		"ms-BN": "San Marino",
		"jv-ID": "San Marino",
		"fil-PH": "San Marino",
		"ceb-PH": "San Marino",
		"ka-GE": "სან-მარინო",
		"hy-AM": "Սան Մարինո",
		"az-AZ": "San-Marino",
		"az-Cyrl-AZ": "Сан-Марино",
		"kk-KZ": "Сан-Марино",
		"ky-KG": "Сан Марино",
		"uz-UZ": "San-Marino",
		"tg-TJ": "Сан-Марино",
		"tk-TM": "San-Marino",
		"fa-IR": "سان‌مارینو",
		"fa-AF": "سان‌مارینو",
		"ps-AF": "سان مارینو",
		"ps-PK": "سان مارینو",
		"he-IL": "סן מרינו",
		"ar-SA": "سان مارينو",
		"ar-AE": "سان مارينو",
		"ar-QA": "سان مارينو",
		"ar-BH": "سان مارينو",
		"ar-KW": "سان مارينو",
		"ar-OM": "سان مارينو",
		"ar-YE": "سان مارينو",
		"ar-IQ": "سان مارينو",
		"ar-JO": "سان مارينو",
		"ar-LB": "سان مارينو",
		"ar-SY": "سان مارينو",
		"ar-PS": "سان مارينو",
		"en-US": "San Marino",
		"en-GB": "San Marino",
		"en-IE": "San Marino",
		"en-MT": "San Marino",
		"en-GI": "San Marino",
		"en-CY": "San Marino",
		"en-JE": "San Marino",
		"en-GG": "San Marino",
		"en-IM": "San Marino",
		"en-CA": "San Marino",
		"en-AU": "San Marino",
		"en-NZ": "San Marino",
		"en-ZA": "San Marino",
		"en-IN": "San Marino",
		"en-SG": "San Marino",
		"pt-AO": "São Marinho",
		"pt-MZ": "São Marinho",
		"pt-CV": "São Marinho",
		"pt-GW": "São Marinho",
		"pt-ST": "São Marinho",
		"pt-TL": "São Marinho",
		"pt-MO": "São Marinho",
		"es-ES": "San Marino",
		"es-419": "San Marino",
		"es-AD": "San Marino",
		"es-GI": "San Marino",
		"es-AR": "San Marino",
		"es-BO": "San Marino",
		"es-BR": "San Marino",
		"es-BZ": "San Marino",
		"es-CL": "San Marino",
		"es-CO": "San Marino",
		"es-CR": "San Marino",
		"es-CU": "San Marino",
		"es-DO": "San Marino",
		"es-EC": "San Marino",
		"es-GT": "San Marino",
		"es-HN": "San Marino",
		"es-MX": "San Marino",
		"es-NI": "San Marino",
		"es-PA": "San Marino",
		"es-PE": "San Marino",
		"es-PR": "San Marino",
		"es-PY": "San Marino",
		"es-SV": "San Marino",
		"es-US": "San Marino",
		"es-UY": "San Marino",
		"es-VE": "San Marino",
		"fr-FR": "Saint-Marin",
		"fr-BE": "Saint-Marin",
		"fr-CH": "Saint-Marin",
		"fr-LU": "Saint-Marin",
		"fr-MC": "Saint-Marin",
		"fr-AD": "Saint-Marin",
		"fr-CA": "Saint-Marin",
		"it-IT": "San Marino",
		"it-CH": "San Marino",
		"it-SM": "San Marino",
		"it-VA": "San Marino",
		"de-DE": "San Marino",
		"de-AT": "San Marino",
		"de-CH": "San Marino",
		"de-BE": "San Marino",
		"de-LI": "San Marino",
		"de-LU": "San Marino",
		"nl-NL": "San Marino",
		"nl-BE": "San Marino",
		"sv-SE": "San Marino",
		"sv-FI": "San Marino",
		"da-DK": "San Marino",
		"nb-NO": "San Marino",
		"nn-NO": "San Marino",
		"fi-FI": "San Marino",
		"is-IS": "San Marínó",
		"fo-FO": "San Marino",
		"et-EE": "San Marino",
		"lv-LV": "Sanmarīno",
		"lt-LT": "San Marinas",
		"pl-PL": "San Marino",
		"cs-CZ": "San Marino",
		"sk-SK": "San Maríno",
		"sl-SI": "San Marino",
		"hr-HR": "San Marino",
		"bs-BA": "San Marino",
		"sr-RS": "Сан Марино",
		"sr-BA": "Сан Марино",
		"sr-ME": "San Marino",
		"mk-MK": "Сан Марино",
		"bg-BG": "Сан Марино",
		"be-BY": "Сан-Марына",
		"uk-UA": "Сан-Марино",
		"ru-RU": "Сан-Марино",
		"el-GR": "Άγιος Μαρίνος",
		"el-CY": "Άγιος Μαρίνος",
		"ro-RO": "San Marino",
		"ro-MD": "San Marino",
		"hu-HU": "San Marino",
		"sq-AL": "San-Marino",
		"sq-XK": "San-Marino",
		"mt-MT": "San Marino",
		"ga-IE": "San Mairíne",
		"cy-GB": "San Marino",
		"gd-GB": "San Marino",
		"lb-LU": "San Marino",
		"ca-ES": "San Marino",
		"ca-AD": "San Marino",
		"ca-FR": "San Marino",
		"ca-IT": "San Marino",
		"eu-ES": "San Marino",
		"eu-FR": "San Marino",
		"gl-ES": "San Marino",
		"tr-TR": "San Marino",
		"tr-CY": "San Marino"
	},
	"callingCode": "378",
	"phoneMasks": [
		{
			"mask": "## ## ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[5-7]"
			]
		},
		{
			"mask": "#### ######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"0"
			]
		}
	]
} satisfies Country;
