import type { Country } from './types.js';

export const SMR = {
	"code": "SMR",
	"labels": {
		"pt-BR": "San Marino",
		"pt-PT": "São Marinho",
		"es-ES": "San Marino",
		"es-419": "San Marino",
		"es-AR": "San Marino",
		"es-BO": "San Marino",
		"es-BR": "San Marino",
		"es-BZ": "San Marino",
		"es-CL": "San Marino",
		"es-CO": "San Marino",
		"es-CR": "San Marino",
		"es-CU": "San Marino",
		"es-DO": "San Marino",
		"es-EC": "San Marino",
		"es-GT": "San Marino",
		"es-HN": "San Marino",
		"es-MX": "San Marino",
		"es-NI": "San Marino",
		"es-PA": "San Marino",
		"es-PE": "San Marino",
		"es-PR": "San Marino",
		"es-PY": "San Marino",
		"es-SV": "San Marino",
		"es-US": "San Marino",
		"es-UY": "San Marino",
		"es-VE": "San Marino",
		"en-US": "San Marino",
		"fr-FR": "Saint-Marin",
		"fr-BE": "Saint-Marin",
		"fr-CA": "Saint-Marin",
		"fr-CH": "Saint-Marin",
		"fr-LU": "Saint-Marin",
		"fr-MC": "Saint-Marin",
		"it-IT": "San Marino",
		"it-CH": "San Marino",
		"it-SM": "San Marino",
		"it-VA": "San Marino",
		"de-DE": "San Marino",
		"de-AT": "San Marino",
		"de-CH": "San Marino",
		"de-BE": "San Marino",
		"de-LI": "San Marino",
		"de-LU": "San Marino"
	},
	"callingCode": "378"
} satisfies Country;
