import type { Country } from './types.js';

export const SOM = {
	"code": "SOM",
	"labels": {
		"pt-BR": "Somália",
		"pt-PT": "Somália",
		"es-ES": "Somalia",
		"es-419": "Somalia",
		"es-AR": "Somalia",
		"es-BO": "Somalia",
		"es-BR": "Somalia",
		"es-BZ": "Somalia",
		"es-CL": "Somalia",
		"es-CO": "Somalia",
		"es-CR": "Somalia",
		"es-CU": "Somalia",
		"es-DO": "Somalia",
		"es-EC": "Somalia",
		"es-GT": "Somalia",
		"es-HN": "Somalia",
		"es-MX": "Somalia",
		"es-NI": "Somalia",
		"es-PA": "Somalia",
		"es-PE": "Somalia",
		"es-PR": "Somalia",
		"es-PY": "Somalia",
		"es-SV": "Somalia",
		"es-US": "Somalia",
		"es-UY": "Somalia",
		"es-VE": "Somalia",
		"en-US": "Somalia",
		"fr-FR": "Somalie",
		"fr-BE": "Somalie",
		"fr-CA": "Somalie",
		"fr-CH": "Somalie",
		"fr-LU": "Somalie",
		"fr-MC": "Somalie",
		"it-IT": "Somalia",
		"it-CH": "Somalia",
		"it-SM": "Somalia",
		"it-VA": "Somalia",
		"de-DE": "Somalia",
		"de-AT": "Somalia",
		"de-CH": "Somalia",
		"de-BE": "Somalia",
		"de-LI": "Somalia",
		"de-LU": "Somalia"
	}
} satisfies Country;
