import type { Country } from './types.js';

export const SPM = {
	"code": "SPM",
	"labels": {
		"pt-BR": "São Pedro e Miquelão",
		"pt-PT": "São Pedro e Miquelão",
		"qu-PE": "San Pedro y Miquelón",
		"qu-BO": "San Pedro y Miquelón",
		"qu-EC": "San Pedro y Miquelón",
		"chr-US": "ᎤᏓᏅᏘ ᏈᏰ ᎠᎴ ᎻᏇᎶᏂ",
		"hi-IN": "सेंट पिएरे और मिक्वेलान",
		"bn-IN": "সেন্ট পিয়ের ও মিকুয়েলন",
		"bn-BD": "সেন্ট পিয়ের ও মিকুয়েলন",
		"ta-IN": "செயின்ட் பியர் & மிக்வேலான்",
		"ta-LK": "செயின்ட் பியர் & மிக்வேலான்",
		"ta-SG": "செயின்ட் பியர் & மிக்வேலான்",
		"ta-MY": "செயின்ட் பியர் & மிக்வேலான்",
		"te-IN": "సెయింట్ పియెర్ మరియు మికెలాన్",
		"mr-IN": "सेंट पियरे आणि मिक्वेलोन",
		"gu-IN": "સેંટ પીએરી અને મિક્યુલોન",
		"kn-IN": "ಸೇಂಟ್ ಪಿಯರ್ ಮತ್ತು ಮಿಕ್ವೆಲನ್",
		"ml-IN": "സെന്റ് പിയറി ആൻഡ് മിക്വലൻ",
		"pa-IN": "ਸੇਂਟ ਪੀਅਰੇ ਐਂਡ ਮਿਕੇਲਨ",
		"ur-IN": "سینٹ پیئر اور میکلیئون",
		"ur-PK": "سینٹ پیئر اور میکلیئون",
		"or-IN": "ସେଣ୍ଟ ପିଏରେ ଏବଂ ମିକ୍ୱେଲନ୍‌",
		"as-IN": "ছেইণ্ট পিয়েৰে আৰু মিকিউৱেলন",
		"ne-IN": "सेन्ट पिर्रे र मिक्केलोन",
		"ne-NP": "सेन्ट पिर्रे र मिक्केलोन",
		"si-LK": "ශාන්ත පියරේ සහ මැකෝලන්",
		"kok-IN": "सँ. पायरे आनी मिकेलन",
		"ks-IN": "سینٹ پیٖری تہٕ موکیلِیَن",
		"brx-IN": "सैन्ट. पिएर आरो मिकैलन",
		"mai-IN": "सेंट पियरे आ मिक्वेलान",
		"dz-BT": "སིནཊ་པི་ཡེར་ ཨེནཌ་ མིཀོ་ལེན",
		"ja-JP": "サンピエール島・ミクロン島",
		"ko-KR": "생피에르 미클롱",
		"ko-KP": "생피에르 미클롱",
		"zh-CN": "圣皮埃尔和密克隆群岛",
		"zh-Hans-CN": "圣皮埃尔和密克隆群岛",
		"zh-Hant-TW": "聖皮埃與密克隆群島",
		"zh-TW": "聖皮埃與密克隆群島",
		"zh-HK": "聖皮埃與密克隆群島",
		"zh-MO": "聖皮埃與密克隆群島",
		"zh-SG": "圣皮埃尔和密克隆群岛",
		"yue-Hant-HK": "聖皮埃爾同密克隆群島",
		"yue-Hans-CN": "圣皮埃尔同密克隆群岛",
		"mn-MN": "Сент-Пьер ба Микело",
		"ug-CN": "ساينت پىيېر ۋە مىكېلون ئاراللىرى",
		"th-TH": "แซงปีแยร์และมีเกอลง",
		"lo-LA": "ເຊນ ປີແອ ມິເກວລອນ",
		"km-KH": "សង់ព្យែរ និង​មីគីឡុង",
		"my-MM": "စိန့်ပီအဲရ်နှင့် မီကွီလွန်",
		"vi-VN": "Saint Pierre và Miquelon",
		"id-ID": "Saint Pierre dan Miquelon",
		"ms-MY": "Saint Pierre dan Miquelon",
		"ms-SG": "Saint Pierre dan Miquelon",
		"ms-BN": "Saint Pierre dan Miquelon",
		"jv-ID": "Saint Pièr lan Mikuélon",
		"fil-PH": "St. Pierre & Miquelon",
		"ceb-PH": "St. Pierre & Miquelon",
		"ka-GE": "სენ-პიერი და მიკელონი",
		"hy-AM": "Սեն Պիեռ և Միքելոն",
		"az-AZ": "Müqəddəs Pyer və Mikelon",
		"az-Cyrl-AZ": "Мүгәддәс Пјер вә Микелон",
		"kk-KZ": "Сен-Пьер және Микелон",
		"ky-KG": "Сен-Пьер жана Микелон",
		"uz-UZ": "Sen-Pyer va Mikelon",
		"tg-TJ": "Сент-Пер ва Микелон",
		"tk-TM": "Sen-Pýer we Mikelon",
		"fa-IR": "سن پیر و میکلن",
		"fa-AF": "سن پیر و میکلن",
		"ps-AF": "سینټ پییر او میکولون",
		"ps-PK": "سینټ پییر او میکولون",
		"he-IL": "סנט פייר ומיקלון",
		"ar-SA": "سان بيير ومكويلون",
		"ar-AE": "سان بيير ومكويلون",
		"ar-QA": "سان بيير ومكويلون",
		"ar-BH": "سان بيير ومكويلون",
		"ar-KW": "سان بيير ومكويلون",
		"ar-OM": "سان بيير ومكويلون",
		"ar-YE": "سان بيير ومكويلون",
		"ar-IQ": "سان بيير ومكويلون",
		"ar-JO": "سان بيير ومكويلون",
		"ar-LB": "سان بيير ومكويلون",
		"ar-SY": "سان بيير ومكويلون",
		"ar-PS": "سان بيير ومكويلون",
		"en-US": "St. Pierre & Miquelon",
		"en-GB": "St Pierre & Miquelon",
		"en-IE": "St Pierre & Miquelon",
		"en-MT": "St Pierre & Miquelon",
		"en-GI": "St Pierre & Miquelon",
		"en-CY": "St Pierre & Miquelon",
		"en-JE": "St Pierre & Miquelon",
		"en-GG": "St Pierre & Miquelon",
		"en-IM": "St Pierre & Miquelon",
		"en-CA": "Saint-Pierre-et-Miquelon",
		"en-AU": "St Pierre & Miquelon",
		"en-NZ": "St Pierre & Miquelon",
		"en-ZA": "St Pierre & Miquelon",
		"en-IN": "St Pierre & Miquelon",
		"en-SG": "St Pierre & Miquelon",
		"pt-AO": "São Pedro e Miquelão",
		"pt-MZ": "São Pedro e Miquelão",
		"pt-CV": "São Pedro e Miquelão",
		"pt-GW": "São Pedro e Miquelão",
		"pt-ST": "São Pedro e Miquelão",
		"pt-TL": "São Pedro e Miquelão",
		"pt-MO": "São Pedro e Miquelão",
		"es-ES": "San Pedro y Miquelón",
		"es-419": "San Pedro y Miquelón",
		"es-AD": "San Pedro y Miquelón",
		"es-GI": "San Pedro y Miquelón",
		"es-AR": "San Pedro y Miquelón",
		"es-BO": "San Pedro y Miquelón",
		"es-BR": "San Pedro y Miquelón",
		"es-BZ": "San Pedro y Miquelón",
		"es-CL": "San Pedro y Miquelón",
		"es-CO": "San Pedro y Miquelón",
		"es-CR": "San Pedro y Miquelón",
		"es-CU": "San Pedro y Miquelón",
		"es-DO": "San Pedro y Miquelón",
		"es-EC": "San Pedro y Miquelón",
		"es-GT": "San Pedro y Miquelón",
		"es-HN": "San Pedro y Miquelón",
		"es-MX": "San Pedro y Miquelón",
		"es-NI": "San Pedro y Miquelón",
		"es-PA": "San Pedro y Miquelón",
		"es-PE": "San Pedro y Miquelón",
		"es-PR": "San Pedro y Miquelón",
		"es-PY": "San Pedro y Miquelón",
		"es-SV": "San Pedro y Miquelón",
		"es-US": "San Pedro y Miquelón",
		"es-UY": "San Pedro y Miquelón",
		"es-VE": "San Pedro y Miquelón",
		"fr-FR": "Saint-Pierre-et-Miquelon",
		"fr-BE": "Saint-Pierre-et-Miquelon",
		"fr-CH": "Saint-Pierre-et-Miquelon",
		"fr-LU": "Saint-Pierre-et-Miquelon",
		"fr-MC": "Saint-Pierre-et-Miquelon",
		"fr-AD": "Saint-Pierre-et-Miquelon",
		"fr-CA": "Saint-Pierre-et-Miquelon",
		"it-IT": "Saint-Pierre e Miquelon",
		"it-CH": "Saint-Pierre e Miquelon",
		"it-SM": "Saint-Pierre e Miquelon",
		"it-VA": "Saint-Pierre e Miquelon",
		"de-DE": "St. Pierre und Miquelon",
		"de-AT": "St. Pierre und Miquelon",
		"de-CH": "St. Pierre und Miquelon",
		"de-BE": "St. Pierre und Miquelon",
		"de-LI": "St. Pierre und Miquelon",
		"de-LU": "St. Pierre und Miquelon",
		"nl-NL": "Saint-Pierre en Miquelon",
		"nl-BE": "Saint-Pierre en Miquelon",
		"sv-SE": "S:t Pierre och Miquelon",
		"sv-FI": "S:t Pierre och Miquelon",
		"da-DK": "Saint Pierre og Miquelon",
		"nb-NO": "Saint-Pierre-et-Miquelon",
		"nn-NO": "Saint-Pierre-et-Miquelon",
		"fi-FI": "Saint-Pierre ja Miquelon",
		"is-IS": "Sankti Pierre og Miquelon",
		"fo-FO": "Saint Pierre & Miquelon",
		"et-EE": "Saint-Pierre ja Miquelon",
		"lv-LV": "Senpjēra un Mikelona",
		"lt-LT": "Sen Pjeras ir Mikelonas",
		"pl-PL": "Saint-Pierre i Miquelon",
		"cs-CZ": "Saint-Pierre a Miquelon",
		"sk-SK": "Saint Pierre a Miquelon",
		"sl-SI": "Saint Pierre in Miquelon",
		"hr-HR": "Sveti Petar i Mikelon",
		"bs-BA": "Sveti Petar i Mikelon",
		"sr-RS": "Сен Пјер и Микелон",
		"sr-BA": "Сен Пјер и Микелон",
		"sr-ME": "Sveti Pjer i Mikelon",
		"mk-MK": "Сент Пјер и Микелан",
		"bg-BG": "Сен Пиер и Микелон",
		"be-BY": "Сен-П’ер і Мікелон",
		"uk-UA": "Сен-Пʼєр і Мікелон",
		"ru-RU": "Сен-Пьер и Микелон",
		"el-GR": "Σεν Πιερ και Μικελόν",
		"el-CY": "Σεν Πιερ και Μικελόν",
		"ro-RO": "Saint-Pierre și Miquelon",
		"ro-MD": "Saint-Pierre și Miquelon",
		"hu-HU": "Saint-Pierre és Miquelon",
		"sq-AL": "Shën-Pier dhe Mikelon",
		"sq-XK": "Shën-Pier dhe Mikelon",
		"mt-MT": "Saint Pierre u Miquelon",
		"ga-IE": "San Pierre agus Miquelon",
		"cy-GB": "Saint-Pierre-et-Miquelon",
		"gd-GB": "Saint Pierre agus Miquelon",
		"lb-LU": "St. Pierre a Miquelon",
		"ca-ES": "Saint-Pierre-et-Miquelon",
		"ca-AD": "Saint-Pierre-et-Miquelon",
		"ca-FR": "Saint-Pierre-et-Miquelon",
		"ca-IT": "Saint-Pierre-et-Miquelon",
		"eu-ES": "Saint-Pierre eta Mikelune",
		"eu-FR": "Saint-Pierre eta Mikelune",
		"gl-ES": "Saint Pierre et Miquelon",
		"tr-TR": "Saint Pierre ve Miquelon",
		"tr-CY": "Saint Pierre ve Miquelon"
	},
	"callingCode": "508",
	"phoneMasks": [
		{
			"mask": "## ## ##",
			"minLength": 6,
			"maxLength": 6,
			"leadingDigits": [
				"[45]"
			]
		},
		{
			"mask": "### ## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"7"
			]
		}
	]
} satisfies Country;
