import type { Country } from './types.js';

export const SSD = {
	"code": "SSD",
	"labels": {
		"pt-BR": "Sudão do Sul",
		"pt-PT": "Sudão do Sul",
		"es-ES": "Sudán del Sur",
		"es-419": "Sudán del Sur",
		"es-AR": "Sudán del Sur",
		"es-BO": "Sudán del Sur",
		"es-BR": "Sudán del Sur",
		"es-BZ": "Sudán del Sur",
		"es-CL": "Sudán del Sur",
		"es-CO": "Sudán del Sur",
		"es-CR": "Sudán del Sur",
		"es-CU": "Sudán del Sur",
		"es-DO": "Sudán del Sur",
		"es-EC": "Sudán del Sur",
		"es-GT": "Sudán del Sur",
		"es-HN": "Sudán del Sur",
		"es-MX": "Sudán del Sur",
		"es-NI": "Sudán del Sur",
		"es-PA": "Sudán del Sur",
		"es-PE": "Sudán del Sur",
		"es-PR": "Sudán del Sur",
		"es-PY": "Sudán del Sur",
		"es-SV": "Sudán del Sur",
		"es-US": "Sudán del Sur",
		"es-UY": "Sudán del Sur",
		"es-VE": "Sudán del Sur",
		"en-US": "South Sudan",
		"fr-FR": "Soudan du Sud",
		"fr-BE": "Soudan du Sud",
		"fr-CA": "Soudan du Sud",
		"fr-CH": "Soudan du Sud",
		"fr-LU": "Soudan du Sud",
		"fr-MC": "Soudan du Sud",
		"it-IT": "Sud Sudan",
		"it-CH": "Sud Sudan",
		"it-SM": "Sud Sudan",
		"it-VA": "Sud Sudan",
		"de-DE": "Südsudan",
		"de-AT": "Südsudan",
		"de-CH": "Südsudan",
		"de-BE": "Südsudan",
		"de-LI": "Südsudan",
		"de-LU": "Südsudan"
	}
} satisfies Country;
