import type { Country } from './types.js';

export const SSD = {
	"code": "SSD",
	"labels": {
		"pt-BR": "Sudão do Sul",
		"pt-PT": "Sudão do Sul",
		"qu-PE": "Sudán del Sur",
		"qu-BO": "Sudán del Sur",
		"qu-EC": "Sudán del Sur",
		"chr-US": "ᏧᎦᎾᏮ ᏑᏕᏂ",
		"hi-IN": "दक्षिण सूडान",
		"bn-IN": "দক্ষিণ সুদান",
		"bn-BD": "দক্ষিণ সুদান",
		"ta-IN": "தெற்கு சூடான்",
		"ta-LK": "தெற்கு சூடான்",
		"ta-SG": "தெற்கு சூடான்",
		"ta-MY": "தெற்கு சூடான்",
		"te-IN": "దక్షిణ సూడాన్",
		"mr-IN": "दक्षिण सुदान",
		"gu-IN": "દક્ષિણ સુદાન",
		"kn-IN": "ದಕ್ಷಿಣ ಸುಡಾನ್",
		"ml-IN": "ദക്ഷിണ സുഡാൻ",
		"pa-IN": "ਦੱਖਣ ਸੁਡਾਨ",
		"ur-IN": "جنوبی سوڈان",
		"ur-PK": "جنوبی سوڈان",
		"or-IN": "ଦକ୍ଷିଣ ସୁଦାନ",
		"as-IN": "দক্ষিণ চুডান",
		"ne-IN": "दक्षिण सुडान",
		"ne-NP": "दक्षिण सुडान",
		"si-LK": "දකුණු සුඩානය",
		"kok-IN": "दक्षिण सुडान",
		"ks-IN": "جنوبی سوڈان",
		"brx-IN": "खोला सुदान",
		"mai-IN": "दक्षिण सुडान",
		"dz-BT": "སཱའུཐ་ སུ་ཌཱན",
		"ja-JP": "南スーダン",
		"ko-KR": "남수단",
		"ko-KP": "남수단",
		"zh-CN": "南苏丹",
		"zh-Hans-CN": "南苏丹",
		"zh-Hant-TW": "南蘇丹",
		"zh-TW": "南蘇丹",
		"zh-HK": "南蘇丹",
		"zh-MO": "南蘇丹",
		"zh-SG": "南苏丹",
		"yue-Hant-HK": "南蘇丹",
		"yue-Hans-CN": "南苏丹",
		"mn-MN": "Өмнөд Судан",
		"ug-CN": "جەنۇبىي سۇدان",
		"th-TH": "ซูดานใต้",
		"lo-LA": "ຊູດານໃຕ້",
		"km-KH": "ស៊ូដង់​ខាង​ត្បូង",
		"my-MM": "တောင် ဆူဒန်",
		"vi-VN": "Nam Sudan",
		"id-ID": "Sudan Selatan",
		"ms-MY": "Sudan Selatan",
		"ms-SG": "Sudan Selatan",
		"ms-BN": "Sudan Selatan",
		"jv-ID": "Sudan Kidul",
		"fil-PH": "Timog Sudan",
		"ceb-PH": "South Sudan",
		"ka-GE": "სამხრეთ სუდანი",
		"hy-AM": "Հարավային Սուդան",
		"az-AZ": "Cənubi Sudan",
		"az-Cyrl-AZ": "Ҹәнуби Судан",
		"kk-KZ": "Оңтүстік Судан",
		"ky-KG": "Түштүк Судан",
		"uz-UZ": "Janubiy Sudan",
		"tg-TJ": "Судони Ҷанубӣ",
		"tk-TM": "Günorta Sudan",
		"fa-IR": "سودان جنوبی",
		"fa-AF": "سودان جنوبی",
		"ps-AF": "سويلي سوډان",
		"ps-PK": "سويلي سوډان",
		"he-IL": "דרום סודן",
		"ar-SA": "جنوب السودان",
		"ar-AE": "جنوب السودان",
		"ar-QA": "جنوب السودان",
		"ar-BH": "جنوب السودان",
		"ar-KW": "جنوب السودان",
		"ar-OM": "جنوب السودان",
		"ar-YE": "جنوب السودان",
		"ar-IQ": "جنوب السودان",
		"ar-JO": "جنوب السودان",
		"ar-LB": "جنوب السودان",
		"ar-SY": "جنوب السودان",
		"ar-PS": "جنوب السودان",
		"en-US": "South Sudan",
		"en-GB": "South Sudan",
		"en-IE": "South Sudan",
		"en-MT": "South Sudan",
		"en-GI": "South Sudan",
		"en-CY": "South Sudan",
		"en-JE": "South Sudan",
		"en-GG": "South Sudan",
		"en-IM": "South Sudan",
		"en-CA": "South Sudan",
		"en-AU": "South Sudan",
		"en-NZ": "South Sudan",
		"en-ZA": "South Sudan",
		"en-IN": "South Sudan",
		"en-SG": "South Sudan",
		"pt-AO": "Sudão do Sul",
		"pt-MZ": "Sudão do Sul",
		"pt-CV": "Sudão do Sul",
		"pt-GW": "Sudão do Sul",
		"pt-ST": "Sudão do Sul",
		"pt-TL": "Sudão do Sul",
		"pt-MO": "Sudão do Sul",
		"es-ES": "Sudán del Sur",
		"es-419": "Sudán del Sur",
		"es-AD": "Sudán del Sur",
		"es-GI": "Sudán del Sur",
		"es-AR": "Sudán del Sur",
		"es-BO": "Sudán del Sur",
		"es-BR": "Sudán del Sur",
		"es-BZ": "Sudán del Sur",
		"es-CL": "Sudán del Sur",
		"es-CO": "Sudán del Sur",
		"es-CR": "Sudán del Sur",
		"es-CU": "Sudán del Sur",
		"es-DO": "Sudán del Sur",
		"es-EC": "Sudán del Sur",
		"es-GT": "Sudán del Sur",
		"es-HN": "Sudán del Sur",
		"es-MX": "Sudán del Sur",
		"es-NI": "Sudán del Sur",
		"es-PA": "Sudán del Sur",
		"es-PE": "Sudán del Sur",
		"es-PR": "Sudán del Sur",
		"es-PY": "Sudán del Sur",
		"es-SV": "Sudán del Sur",
		"es-US": "Sudán del Sur",
		"es-UY": "Sudán del Sur",
		"es-VE": "Sudán del Sur",
		"fr-FR": "Soudan du Sud",
		"fr-BE": "Soudan du Sud",
		"fr-CH": "Soudan du Sud",
		"fr-LU": "Soudan du Sud",
		"fr-MC": "Soudan du Sud",
		"fr-AD": "Soudan du Sud",
		"fr-CA": "Soudan du Sud",
		"it-IT": "Sud Sudan",
		"it-CH": "Sud Sudan",
		"it-SM": "Sud Sudan",
		"it-VA": "Sud Sudan",
		"de-DE": "Südsudan",
		"de-AT": "Südsudan",
		"de-CH": "Südsudan",
		"de-BE": "Südsudan",
		"de-LI": "Südsudan",
		"de-LU": "Südsudan",
		"nl-NL": "Zuid-Soedan",
		"nl-BE": "Zuid-Soedan",
		"sv-SE": "Sydsudan",
		"sv-FI": "Sydsudan",
		"da-DK": "Sydsudan",
		"nb-NO": "Sør-Sudan",
		"nn-NO": "Sør-Sudan",
		"fi-FI": "Etelä-Sudan",
		"is-IS": "Suður-Súdan",
		"fo-FO": "Suðursudan",
		"et-EE": "Lõuna-Sudaan",
		"lv-LV": "Dienvidsudāna",
		"lt-LT": "Pietų Sudanas",
		"pl-PL": "Sudan Południowy",
		"cs-CZ": "Jižní Súdán",
		"sk-SK": "Južný Sudán",
		"sl-SI": "Južni Sudan",
		"hr-HR": "Južni Sudan",
		"bs-BA": "Južni Sudan",
		"sr-RS": "Јужни Судан",
		"sr-BA": "Јужни Судан",
		"sr-ME": "Južni Sudan",
		"mk-MK": "Јужен Судан",
		"bg-BG": "Южен Судан",
		"be-BY": "Паўднёвы Судан",
		"uk-UA": "Південний Судан",
		"ru-RU": "Южный Судан",
		"el-GR": "Νότιο Σουδάν",
		"el-CY": "Νότιο Σουδάν",
		"ro-RO": "Sudanul de Sud",
		"ro-MD": "Sudanul de Sud",
		"hu-HU": "Dél-Szudán",
		"sq-AL": "Sudani i Jugut",
		"sq-XK": "Sudani i Jugut",
		"mt-MT": "is-Sudan t’Isfel",
		"ga-IE": "an tSúdáin Theas",
		"cy-GB": "De Swdan",
		"gd-GB": "Sudàn a Deas",
		"lb-LU": "Südsudan",
		"ca-ES": "Sudan del Sud",
		"ca-AD": "Sudan del Sud",
		"ca-FR": "Sudan del Sud",
		"ca-IT": "Sudan del Sud",
		"eu-ES": "Hego Sudan",
		"eu-FR": "Hego Sudan",
		"gl-ES": "Sudán do Sur",
		"tr-TR": "Güney Sudan",
		"tr-CY": "Güney Sudan"
	},
	"callingCode": "211",
	"phoneMasks": [
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[19]"
			]
		}
	]
} satisfies Country;
