import type { Country } from './types.js';

export const STP = {
	"code": "STP",
	"labels": {
		"pt-BR": "São Tomé e Príncipe",
		"pt-PT": "São Tomé e Príncipe",
		"qu-PE": "Santo Tomé y Príncipe",
		"qu-BO": "Santo Tomé y Príncipe",
		"qu-EC": "Santo Tomé y Príncipe",
		"chr-US": "ᏌᎣ ᏙᎺ ᎠᎴ ᏈᏂᏏᏇ",
		"hi-IN": "साओ टोम और प्रिंसिपे",
		"bn-IN": "সাওটোমা ও প্রিন্সিপি",
		"bn-BD": "সাওটোমা ও প্রিন্সিপি",
		"ta-IN": "சாவ் தோம் & ப்ரின்சிபி",
		"ta-LK": "சாவ் தோம் & ப்ரின்சிபி",
		"ta-SG": "சாவ் தோம் & ப்ரின்சிபி",
		"ta-MY": "சாவ் தோம் & ப்ரின்சிபி",
		"te-IN": "సావో టోమ్ మరియు ప్రిన్సిపి",
		"mr-IN": "साओ टोम आणि प्रिंसिपे",
		"gu-IN": "સાઓ ટૉમ અને પ્રિંસિપે",
		"kn-IN": "ಸಾವೋ ಟೋಮ್ ಮತ್ತು ಪ್ರಿನ್ಸಿಪಿ",
		"ml-IN": "സാവോ ടോമും പ്രിൻസിപെയും",
		"pa-IN": "ਸਾਓ ਟੋਮ ਅਤੇ ਪ੍ਰਿੰਸੀਪੇ",
		"ur-IN": "ساؤ ٹومے اور پرنسپے",
		"ur-PK": "ساؤ ٹومے اور پرنسپے",
		"or-IN": "ସାଓ ଟୋମେ ଏବଂ ପ୍ରିନସିପି",
		"as-IN": "চাও টোমে আৰু প্ৰিনচিপে",
		"ne-IN": "साओ टोमे र प्रिन्सिप",
		"ne-NP": "साओ टोमे र प्रिन्सिप",
		"si-LK": "සාඕ තෝම් සහ ප්‍රින්සිප්",
		"kok-IN": "साओ टोम आनी प्रिन्सिप",
		"ks-IN": "ساو توم تہٕ پرنسِپی",
		"brx-IN": "साऊ तमे आरो प्रिन्सिप",
		"mai-IN": "साओ टोम आ प्रिंसिप",
		"dz-BT": "སཝ་ ཊོ་མེ་ ཨེནཌ་ པྲྀན་སི་པེ",
		"ja-JP": "サントメ・プリンシペ",
		"ko-KR": "상투메 프린시페",
		"ko-KP": "상투메 프린시페",
		"zh-CN": "圣多美和普林西比",
		"zh-Hans-CN": "圣多美和普林西比",
		"zh-Hant-TW": "聖多美普林西比",
		"zh-TW": "聖多美普林西比",
		"zh-HK": "聖多美和普林西比",
		"zh-MO": "聖多美和普林西比",
		"zh-SG": "圣多美和普林西比",
		"yue-Hant-HK": "聖多美同普林西比",
		"yue-Hans-CN": "圣多美同普林西比",
		"mn-MN": "Сан-Томе ба Принсипи",
		"ug-CN": "سان تومې ۋە پرىنسىپې",
		"th-TH": "เซาตูเมและปรินซิปี",
		"lo-LA": "ເຊົາທູເມ ແລະ ພຣິນຊິບ",
		"km-KH": "សៅតូម៉េ និង ប្រាំងស៊ីប",
		"my-MM": "ဆောင်တူမေးနှင့် ပရင်စီပီ",
		"vi-VN": "São Tomé và Príncipe",
		"id-ID": "Sao Tome dan Principe",
		"ms-MY": "Sao Tome dan Principe",
		"ms-SG": "Sao Tome dan Principe",
		"ms-BN": "Sao Tome dan Principe",
		"jv-ID": "Sao Tomé lan Principé",
		"fil-PH": "São Tomé & Príncipe",
		"ceb-PH": "Sao Tome & Principe",
		"ka-GE": "სან-ტომე და პრინსიპი",
		"hy-AM": "Սան Տոմե և Փրինսիպի",
		"az-AZ": "San-Tome və Prinsipi",
		"az-Cyrl-AZ": "Сан-Томе вә Принсипи",
		"kk-KZ": "Сан-Томе және Принсипи",
		"ky-KG": "Сан-Томе жана Принсипи",
		"uz-UZ": "San-Tome va Prinsipi",
		"tg-TJ": "Сан Томе ва Принсипи",
		"tk-TM": "San-Tome we Prinsipi",
		"fa-IR": "سائوتومه و پرینسیپ",
		"fa-AF": "سائوتومه و پرینسیپ",
		"ps-AF": "ساو ټیم او پرنسیپ",
		"ps-PK": "ساو ټیم او پرنسیپ",
		"he-IL": "סאו טומה ופרינסיפה",
		"ar-SA": "ساو تومي وبرينسيبي",
		"ar-AE": "ساو تومي وبرينسيبي",
		"ar-QA": "ساو تومي وبرينسيبي",
		"ar-BH": "ساو تومي وبرينسيبي",
		"ar-KW": "ساو تومي وبرينسيبي",
		"ar-OM": "ساو تومي وبرينسيبي",
		"ar-YE": "ساو تومي وبرينسيبي",
		"ar-IQ": "ساو تومي وبرينسيبي",
		"ar-JO": "ساو تومي وبرينسيبي",
		"ar-LB": "ساو تومي وبرينسيبي",
		"ar-SY": "ساو تومي وبرينسيبي",
		"ar-PS": "ساو تومي وبرينسيبي",
		"en-US": "São Tomé & Príncipe",
		"en-GB": "São Tomé & Príncipe",
		"en-IE": "São Tomé & Príncipe",
		"en-MT": "São Tomé & Príncipe",
		"en-GI": "São Tomé & Príncipe",
		"en-CY": "São Tomé & Príncipe",
		"en-JE": "São Tomé & Príncipe",
		"en-GG": "São Tomé & Príncipe",
		"en-IM": "São Tomé & Príncipe",
		"en-CA": "São Tomé and Príncipe",
		"en-AU": "São Tomé & Príncipe",
		"en-NZ": "São Tomé & Príncipe",
		"en-ZA": "São Tomé & Príncipe",
		"en-IN": "São Tomé & Príncipe",
		"en-SG": "São Tomé & Príncipe",
		"pt-AO": "São Tomé e Príncipe",
		"pt-MZ": "São Tomé e Príncipe",
		"pt-CV": "São Tomé e Príncipe",
		"pt-GW": "São Tomé e Príncipe",
		"pt-ST": "São Tomé e Príncipe",
		"pt-TL": "São Tomé e Príncipe",
		"pt-MO": "São Tomé e Príncipe",
		"es-ES": "Santo Tomé y Príncipe",
		"es-419": "Santo Tomé y Príncipe",
		"es-AD": "Santo Tomé y Príncipe",
		"es-GI": "Santo Tomé y Príncipe",
		"es-AR": "Santo Tomé y Príncipe",
		"es-BO": "Santo Tomé y Príncipe",
		"es-BR": "Santo Tomé y Príncipe",
		"es-BZ": "Santo Tomé y Príncipe",
		"es-CL": "Santo Tomé y Príncipe",
		"es-CO": "Santo Tomé y Príncipe",
		"es-CR": "Santo Tomé y Príncipe",
		"es-CU": "Santo Tomé y Príncipe",
		"es-DO": "Santo Tomé y Príncipe",
		"es-EC": "Santo Tomé y Príncipe",
		"es-GT": "Santo Tomé y Príncipe",
		"es-HN": "Santo Tomé y Príncipe",
		"es-MX": "Santo Tomé y Príncipe",
		"es-NI": "Santo Tomé y Príncipe",
		"es-PA": "Santo Tomé y Príncipe",
		"es-PE": "Santo Tomé y Príncipe",
		"es-PR": "Santo Tomé y Príncipe",
		"es-PY": "Santo Tomé y Príncipe",
		"es-SV": "Santo Tomé y Príncipe",
		"es-US": "Santo Tomé y Príncipe",
		"es-UY": "Santo Tomé y Príncipe",
		"es-VE": "Santo Tomé y Príncipe",
		"fr-FR": "Sao Tomé-et-Principe",
		"fr-BE": "Sao Tomé-et-Principe",
		"fr-CH": "Sao Tomé-et-Principe",
		"fr-LU": "Sao Tomé-et-Principe",
		"fr-MC": "Sao Tomé-et-Principe",
		"fr-AD": "Sao Tomé-et-Principe",
		"fr-CA": "Sao Tomé-et-Principe",
		"it-IT": "São Tomé e Príncipe",
		"it-CH": "São Tomé e Príncipe",
		"it-SM": "São Tomé e Príncipe",
		"it-VA": "São Tomé e Príncipe",
		"de-DE": "São Tomé und Príncipe",
		"de-AT": "São Tomé und Príncipe",
		"de-CH": "São Tomé und Príncipe",
		"de-BE": "São Tomé und Príncipe",
		"de-LI": "São Tomé und Príncipe",
		"de-LU": "São Tomé und Príncipe",
		"nl-NL": "Sao Tomé en Principe",
		"nl-BE": "Sao Tomé en Principe",
		"sv-SE": "São Tomé och Príncipe",
		"sv-FI": "São Tomé och Príncipe",
		"da-DK": "São Tomé og Príncipe",
		"nb-NO": "São Tomé og Príncipe",
		"nn-NO": "São Tomé og Príncipe",
		"fi-FI": "São Tomé ja Príncipe",
		"is-IS": "Saó Tóme og Prinsípe",
		"fo-FO": "Sao Tome & Prinsipi",
		"et-EE": "São Tomé ja Príncipe",
		"lv-LV": "Santome un Prinsipi",
		"lt-LT": "San Tomė ir Prinsipė",
		"pl-PL": "Wyspy Świętego Tomasza i Książęca",
		"cs-CZ": "Svatý Tomáš a Princův ostrov",
		"sk-SK": "Svätý Tomáš a Princov ostrov",
		"sl-SI": "Sao Tome in Principe",
		"hr-HR": "Sveti Toma i Princip",
		"bs-BA": "Sao Tome i Principe",
		"sr-RS": "Сао Томе и Принципе",
		"sr-BA": "Сао Томе и Принципе",
		"sr-ME": "Sao Tome i Principe",
		"mk-MK": "Саун Томе и Принсип",
		"bg-BG": "Сао Томе и Принсипи",
		"be-BY": "Сан-Тамэ і Прынсіпі",
		"uk-UA": "Сан-Томе і Принсіпі",
		"ru-RU": "Сан-Томе и Принсипи",
		"el-GR": "Σάο Τομέ και Πρίνσιπε",
		"el-CY": "Σάο Τομέ και Πρίνσιπε",
		"ro-RO": "São Tomé și Príncipe",
		"ro-MD": "São Tomé și Príncipe",
		"hu-HU": "São Tomé és Príncipe",
		"sq-AL": "Sao-Tome e Principe",
		"sq-XK": "Sao-Tome e Principe",
		"mt-MT": "São Tomé u Príncipe",
		"ga-IE": "São Tomé agus Príncipe",
		"cy-GB": "São Tomé a Príncipe",
		"gd-GB": "São Tomé agus Príncipe",
		"lb-LU": "São Tomé a Príncipe",
		"ca-ES": "São Tomé i Príncipe",
		"ca-AD": "São Tomé i Príncipe",
		"ca-FR": "São Tomé i Príncipe",
		"ca-IT": "São Tomé i Príncipe",
		"eu-ES": "Sao Tome eta Principe",
		"eu-FR": "Sao Tome eta Principe",
		"gl-ES": "San Tomé e Príncipe",
		"tr-TR": "Sao Tome ve Principe",
		"tr-CY": "Sao Tome ve Principe"
	},
	"callingCode": "239",
	"phoneMasks": [
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[29]"
			]
		}
	]
} satisfies Country;
