import type { Country } from './types.js';

export const STP = {
	"code": "STP",
	"labels": {
		"pt-BR": "São Tomé e Príncipe",
		"pt-PT": "São Tomé e Príncipe",
		"es-ES": "Santo Tomé y Príncipe",
		"es-419": "Santo Tomé y Príncipe",
		"es-AR": "Santo Tomé y Príncipe",
		"es-BO": "Santo Tomé y Príncipe",
		"es-BR": "Santo Tomé y Príncipe",
		"es-BZ": "Santo Tomé y Príncipe",
		"es-CL": "Santo Tomé y Príncipe",
		"es-CO": "Santo Tomé y Príncipe",
		"es-CR": "Santo Tomé y Príncipe",
		"es-CU": "Santo Tomé y Príncipe",
		"es-DO": "Santo Tomé y Príncipe",
		"es-EC": "Santo Tomé y Príncipe",
		"es-GT": "Santo Tomé y Príncipe",
		"es-HN": "Santo Tomé y Príncipe",
		"es-MX": "Santo Tomé y Príncipe",
		"es-NI": "Santo Tomé y Príncipe",
		"es-PA": "Santo Tomé y Príncipe",
		"es-PE": "Santo Tomé y Príncipe",
		"es-PR": "Santo Tomé y Príncipe",
		"es-PY": "Santo Tomé y Príncipe",
		"es-SV": "Santo Tomé y Príncipe",
		"es-US": "Santo Tomé y Príncipe",
		"es-UY": "Santo Tomé y Príncipe",
		"es-VE": "Santo Tomé y Príncipe",
		"en-US": "São Tomé & Príncipe",
		"fr-FR": "Sao Tomé-et-Principe",
		"fr-BE": "Sao Tomé-et-Principe",
		"fr-CA": "Sao Tomé-et-Principe",
		"fr-CH": "Sao Tomé-et-Principe",
		"fr-LU": "Sao Tomé-et-Principe",
		"fr-MC": "Sao Tomé-et-Principe",
		"it-IT": "São Tomé e Príncipe",
		"it-CH": "São Tomé e Príncipe",
		"it-SM": "São Tomé e Príncipe",
		"it-VA": "São Tomé e Príncipe",
		"de-DE": "São Tomé und Príncipe",
		"de-AT": "São Tomé und Príncipe",
		"de-CH": "São Tomé und Príncipe",
		"de-BE": "São Tomé und Príncipe",
		"de-LI": "São Tomé und Príncipe",
		"de-LU": "São Tomé und Príncipe"
	},
	"callingCode": "239"
} satisfies Country;
