import type { Country } from './types.js';

export const SUR = {
	"code": "SUR",
	"labels": {
		"pt-BR": "Suriname",
		"pt-PT": "Suriname",
		"es-ES": "Surinam",
		"es-419": "Surinam",
		"es-AR": "Surinam",
		"es-BO": "Surinam",
		"es-BR": "Surinam",
		"es-BZ": "Surinam",
		"es-CL": "Surinam",
		"es-CO": "Surinam",
		"es-CR": "Surinam",
		"es-CU": "Surinam",
		"es-DO": "Surinam",
		"es-EC": "Surinam",
		"es-GT": "Surinam",
		"es-HN": "Surinam",
		"es-MX": "Surinam",
		"es-NI": "Surinam",
		"es-PA": "Surinam",
		"es-PE": "Surinam",
		"es-PR": "Surinam",
		"es-PY": "Surinam",
		"es-SV": "Surinam",
		"es-US": "Surinam",
		"es-UY": "Surinam",
		"es-VE": "Surinam",
		"en-US": "Suriname",
		"fr-FR": "Suriname",
		"fr-BE": "Suriname",
		"fr-CA": "Suriname",
		"fr-CH": "Suriname",
		"fr-LU": "Suriname",
		"fr-MC": "Suriname",
		"it-IT": "Suriname",
		"it-CH": "Suriname",
		"it-SM": "Suriname",
		"it-VA": "Suriname",
		"de-DE": "Suriname",
		"de-AT": "Suriname",
		"de-CH": "Suriname",
		"de-BE": "Suriname",
		"de-LI": "Suriname",
		"de-LU": "Suriname"
	},
	"callingCode": "597"
} satisfies Country;
