import type { Country } from './types.js';

export const SVK = {
	"code": "SVK",
	"labels": {
		"pt-BR": "Eslováquia",
		"pt-PT": "Eslováquia",
		"qu-PE": "Eslovaquia",
		"qu-BO": "Eslovaquia",
		"qu-EC": "Eslovaquia",
		"chr-US": "ᏍᎶᏩᎩᎠ",
		"hi-IN": "स्लोवाकिया",
		"bn-IN": "স্লোভাকিয়া",
		"bn-BD": "স্লোভাকিয়া",
		"ta-IN": "ஸ்லோவாகியா",
		"ta-LK": "ஸ்லோவாகியா",
		"ta-SG": "ஸ்லோவாகியா",
		"ta-MY": "ஸ்லோவாகியா",
		"te-IN": "స్లొవేకియా",
		"mr-IN": "स्लोव्हाकिया",
		"gu-IN": "સ્લોવેકિયા",
		"kn-IN": "ಸ್ಲೊವಾಕಿಯಾ",
		"ml-IN": "സ്ലോവാക്യ",
		"pa-IN": "ਸਲੋਵਾਕੀਆ",
		"ur-IN": "سلوواکیہ",
		"ur-PK": "سلوواکیہ",
		"or-IN": "ସ୍ଲୋଭାକିଆ",
		"as-IN": "শ্লোভাকিয়া",
		"ne-IN": "स्लोभाकिया",
		"ne-NP": "स्लोभाकिया",
		"si-LK": "ස්ලෝවැකියාව",
		"kok-IN": "स्लोवाकिया",
		"ks-IN": "سَلوواکِیا",
		"brx-IN": "स्लभाकिया",
		"mai-IN": "स्लोवाकिया",
		"dz-BT": "སུ་ལོ་བཱ་ཀི་ཡ",
		"ja-JP": "スロバキア",
		"ko-KR": "슬로바키아",
		"ko-KP": "슬로바키아",
		"zh-CN": "斯洛伐克",
		"zh-Hans-CN": "斯洛伐克",
		"zh-Hant-TW": "斯洛伐克",
		"zh-TW": "斯洛伐克",
		"zh-HK": "斯洛伐克",
		"zh-MO": "斯洛伐克",
		"zh-SG": "斯洛伐克",
		"yue-Hant-HK": "斯洛伐克",
		"yue-Hans-CN": "斯洛伐克",
		"mn-MN": "Словак",
		"ug-CN": "سىلوۋاكىيە",
		"th-TH": "สโลวะเกีย",
		"lo-LA": "ສະໂລວາເກຍ",
		"km-KH": "ស្លូវ៉ាគី",
		"my-MM": "ဆလိုဗက်ကီးယား",
		"vi-VN": "Slovakia",
		"id-ID": "Slovakia",
		"ms-MY": "Slovakia",
		"ms-SG": "Slovakia",
		"ms-BN": "Slovakia",
		"jv-ID": "Slowak",
		"fil-PH": "Slovakia",
		"ceb-PH": "Slovakia",
		"ka-GE": "სლოვაკეთი",
		"hy-AM": "Սլովակիա",
		"az-AZ": "Slovakiya",
		"az-Cyrl-AZ": "Словакија",
		"kk-KZ": "Словакия",
		"ky-KG": "Словакия",
		"uz-UZ": "Slovakiya",
		"tg-TJ": "Словакия",
		"tk-TM": "Slowakiýa",
		"fa-IR": "اسلواکی",
		"fa-AF": "سلواکیا",
		"ps-AF": "سلواکیا",
		"ps-PK": "سلواکیا",
		"he-IL": "סלובקיה",
		"ar-SA": "سلوفاكيا",
		"ar-AE": "سلوفاكيا",
		"ar-QA": "سلوفاكيا",
		"ar-BH": "سلوفاكيا",
		"ar-KW": "سلوفاكيا",
		"ar-OM": "سلوفاكيا",
		"ar-YE": "سلوفاكيا",
		"ar-IQ": "سلوفاكيا",
		"ar-JO": "سلوفاكيا",
		"ar-LB": "سلوفاكيا",
		"ar-SY": "سلوفاكيا",
		"ar-PS": "سلوفاكيا",
		"en-US": "Slovakia",
		"en-GB": "Slovakia",
		"en-IE": "Slovakia",
		"en-MT": "Slovakia",
		"en-GI": "Slovakia",
		"en-CY": "Slovakia",
		"en-JE": "Slovakia",
		"en-GG": "Slovakia",
		"en-IM": "Slovakia",
		"en-CA": "Slovakia",
		"en-AU": "Slovakia",
		"en-NZ": "Slovakia",
		"en-ZA": "Slovakia",
		"en-IN": "Slovakia",
		"en-SG": "Slovakia",
		"pt-AO": "Eslováquia",
		"pt-MZ": "Eslováquia",
		"pt-CV": "Eslováquia",
		"pt-GW": "Eslováquia",
		"pt-ST": "Eslováquia",
		"pt-TL": "Eslováquia",
		"pt-MO": "Eslováquia",
		"es-ES": "Eslovaquia",
		"es-419": "Eslovaquia",
		"es-AD": "Eslovaquia",
		"es-GI": "Eslovaquia",
		"es-AR": "Eslovaquia",
		"es-BO": "Eslovaquia",
		"es-BR": "Eslovaquia",
		"es-BZ": "Eslovaquia",
		"es-CL": "Eslovaquia",
		"es-CO": "Eslovaquia",
		"es-CR": "Eslovaquia",
		"es-CU": "Eslovaquia",
		"es-DO": "Eslovaquia",
		"es-EC": "Eslovaquia",
		"es-GT": "Eslovaquia",
		"es-HN": "Eslovaquia",
		"es-MX": "Eslovaquia",
		"es-NI": "Eslovaquia",
		"es-PA": "Eslovaquia",
		"es-PE": "Eslovaquia",
		"es-PR": "Eslovaquia",
		"es-PY": "Eslovaquia",
		"es-SV": "Eslovaquia",
		"es-US": "Eslovaquia",
		"es-UY": "Eslovaquia",
		"es-VE": "Eslovaquia",
		"fr-FR": "Slovaquie",
		"fr-BE": "Slovaquie",
		"fr-CH": "Slovaquie",
		"fr-LU": "Slovaquie",
		"fr-MC": "Slovaquie",
		"fr-AD": "Slovaquie",
		"fr-CA": "Slovaquie",
		"it-IT": "Slovacchia",
		"it-CH": "Slovacchia",
		"it-SM": "Slovacchia",
		"it-VA": "Slovacchia",
		"de-DE": "Slowakei",
		"de-AT": "Slowakei",
		"de-CH": "Slowakei",
		"de-BE": "Slowakei",
		"de-LI": "Slowakei",
		"de-LU": "Slowakei",
		"nl-NL": "Slowakije",
		"nl-BE": "Slowakije",
		"sv-SE": "Slovakien",
		"sv-FI": "Slovakien",
		"da-DK": "Slovakiet",
		"nb-NO": "Slovakia",
		"nn-NO": "Slovakia",
		"fi-FI": "Slovakia",
		"is-IS": "Slóvakía",
		"fo-FO": "Slovakia",
		"et-EE": "Slovakkia",
		"lv-LV": "Slovākija",
		"lt-LT": "Slovakija",
		"pl-PL": "Słowacja",
		"cs-CZ": "Slovensko",
		"sk-SK": "Slovensko",
		"sl-SI": "Slovaška",
		"hr-HR": "Slovačka",
		"bs-BA": "Slovačka",
		"sr-RS": "Словачка",
		"sr-BA": "Словачка",
		"sr-ME": "Slovačka",
		"mk-MK": "Словачка",
		"bg-BG": "Словакия",
		"be-BY": "Славакія",
		"uk-UA": "Словаччина",
		"ru-RU": "Словакия",
		"el-GR": "Σλοβακία",
		"el-CY": "Σλοβακία",
		"ro-RO": "Slovacia",
		"ro-MD": "Slovacia",
		"hu-HU": "Szlovákia",
		"sq-AL": "Sllovaki",
		"sq-XK": "Sllovaki",
		"mt-MT": "is-Slovakkja",
		"ga-IE": "an tSlóvaic",
		"cy-GB": "Slofacia",
		"gd-GB": "An t-Slòbhac",
		"lb-LU": "Slowakei",
		"ca-ES": "Eslovàquia",
		"ca-AD": "Eslovàquia",
		"ca-FR": "Eslovàquia",
		"ca-IT": "Eslovàquia",
		"eu-ES": "Eslovakia",
		"eu-FR": "Eslovakia",
		"gl-ES": "Eslovaquia",
		"tr-TR": "Slovakya",
		"tr-CY": "Slovakya"
	},
	"callingCode": "421",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "# ## ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"21"
			]
		},
		{
			"mask": "## ## ###",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[3-5][1-8]1",
				"[3-5][1-8]1[67]"
			]
		},
		{
			"mask": "#/### ### ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"2"
			]
		},
		{
			"mask": "##/### ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[3-5]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[689]"
			]
		}
	]
} satisfies Country;
