import type { Country } from './types.js';

export const SVK = {
	"code": "SVK",
	"labels": {
		"pt-BR": "Eslováquia",
		"pt-PT": "Eslováquia",
		"es-ES": "Eslovaquia",
		"es-419": "Eslovaquia",
		"es-AR": "Eslovaquia",
		"es-BO": "Eslovaquia",
		"es-BR": "Eslovaquia",
		"es-BZ": "Eslovaquia",
		"es-CL": "Eslovaquia",
		"es-CO": "Eslovaquia",
		"es-CR": "Eslovaquia",
		"es-CU": "Eslovaquia",
		"es-DO": "Eslovaquia",
		"es-EC": "Eslovaquia",
		"es-GT": "Eslovaquia",
		"es-HN": "Eslovaquia",
		"es-MX": "Eslovaquia",
		"es-NI": "Eslovaquia",
		"es-PA": "Eslovaquia",
		"es-PE": "Eslovaquia",
		"es-PR": "Eslovaquia",
		"es-PY": "Eslovaquia",
		"es-SV": "Eslovaquia",
		"es-US": "Eslovaquia",
		"es-UY": "Eslovaquia",
		"es-VE": "Eslovaquia",
		"en-US": "Slovakia",
		"fr-FR": "Slovaquie",
		"fr-BE": "Slovaquie",
		"fr-CA": "Slovaquie",
		"fr-CH": "Slovaquie",
		"fr-LU": "Slovaquie",
		"fr-MC": "Slovaquie",
		"it-IT": "Slovacchia",
		"it-CH": "Slovacchia",
		"it-SM": "Slovacchia",
		"it-VA": "Slovacchia",
		"de-DE": "Slowakei",
		"de-AT": "Slowakei",
		"de-CH": "Slowakei",
		"de-BE": "Slowakei",
		"de-LI": "Slowakei",
		"de-LU": "Slowakei"
	},
	"callingCode": "421"
} satisfies Country;
