import type { Country } from './types.js';

export const SVN = {
	"code": "SVN",
	"labels": {
		"pt-BR": "Eslovênia",
		"pt-PT": "Eslovénia",
		"es-ES": "Eslovenia",
		"es-419": "Eslovenia",
		"es-AR": "Eslovenia",
		"es-BO": "Eslovenia",
		"es-BR": "Eslovenia",
		"es-BZ": "Eslovenia",
		"es-CL": "Eslovenia",
		"es-CO": "Eslovenia",
		"es-CR": "Eslovenia",
		"es-CU": "Eslovenia",
		"es-DO": "Eslovenia",
		"es-EC": "Eslovenia",
		"es-GT": "Eslovenia",
		"es-HN": "Eslovenia",
		"es-MX": "Eslovenia",
		"es-NI": "Eslovenia",
		"es-PA": "Eslovenia",
		"es-PE": "Eslovenia",
		"es-PR": "Eslovenia",
		"es-PY": "Eslovenia",
		"es-SV": "Eslovenia",
		"es-US": "Eslovenia",
		"es-UY": "Eslovenia",
		"es-VE": "Eslovenia",
		"en-US": "Slovenia",
		"fr-FR": "Slovénie",
		"fr-BE": "Slovénie",
		"fr-CA": "Slovénie",
		"fr-CH": "Slovénie",
		"fr-LU": "Slovénie",
		"fr-MC": "Slovénie",
		"it-IT": "Slovenia",
		"it-CH": "Slovenia",
		"it-SM": "Slovenia",
		"it-VA": "Slovenia",
		"de-DE": "Slowenien",
		"de-AT": "Slowenien",
		"de-CH": "Slowenien",
		"de-BE": "Slowenien",
		"de-LI": "Slowenien",
		"de-LU": "Slowenien"
	}
} satisfies Country;
