import type { Country } from './types.js';

export const SVN = {
	"code": "SVN",
	"labels": {
		"pt-BR": "Eslovênia",
		"pt-PT": "Eslovénia",
		"qu-PE": "Eslovenia",
		"qu-BO": "Eslovenia",
		"qu-EC": "Eslovenia",
		"chr-US": "ᏍᎶᏫᏂᎠ",
		"hi-IN": "स्लोवेनिया",
		"bn-IN": "স্লোভানিয়া",
		"bn-BD": "স্লোভানিয়া",
		"ta-IN": "ஸ்லோவேனியா",
		"ta-LK": "ஸ்லோவேனியா",
		"ta-SG": "ஸ்லோவேனியா",
		"ta-MY": "ஸ்லோவேனியா",
		"te-IN": "స్లోవేనియా",
		"mr-IN": "स्लोव्हेनिया",
		"gu-IN": "સ્લોવેનિયા",
		"kn-IN": "ಸ್ಲೋವೇನಿಯಾ",
		"ml-IN": "സ്ലോവേനിയ",
		"pa-IN": "ਸਲੋਵੇਨੀਆ",
		"ur-IN": "سلووینیا",
		"ur-PK": "سلووینیا",
		"or-IN": "ସ୍ଲୋଭେନିଆ",
		"as-IN": "শ্লোভেনিয়া",
		"ne-IN": "स्लोभेनिया",
		"ne-NP": "स्लोभेनिया",
		"si-LK": "ස්ලෝවේනියාව",
		"kok-IN": "स्लोवेनिया",
		"ks-IN": "سَلووینِیا",
		"brx-IN": "स्ल’भेनिया",
		"mai-IN": "स्लोबेनिया",
		"dz-BT": "སུ་ལོ་བི་ནི་ཡ",
		"ja-JP": "スロベニア",
		"ko-KR": "슬로베니아",
		"ko-KP": "슬로베니아",
		"zh-CN": "斯洛文尼亚",
		"zh-Hans-CN": "斯洛文尼亚",
		"zh-Hant-TW": "斯洛維尼亞",
		"zh-TW": "斯洛維尼亞",
		"zh-HK": "斯洛文尼亞",
		"zh-MO": "斯洛文尼亞",
		"zh-SG": "斯洛文尼亚",
		"yue-Hant-HK": "斯洛維尼亞",
		"yue-Hans-CN": "斯洛维尼亚",
		"mn-MN": "Словени",
		"ug-CN": "سىلوۋېنىيە",
		"th-TH": "สโลวีเนีย",
		"lo-LA": "ສະໂລເວເນຍ",
		"km-KH": "ស្លូវេនី",
		"my-MM": "ဆလိုဗေးနီးယား",
		"vi-VN": "Slovenia",
		"id-ID": "Slovenia",
		"ms-MY": "Slovenia",
		"ms-SG": "Slovenia",
		"ms-BN": "Slovenia",
		"jv-ID": "Slovénia",
		"fil-PH": "Slovenia",
		"ceb-PH": "Slovenia",
		"ka-GE": "სლოვენია",
		"hy-AM": "Սլովենիա",
		"az-AZ": "Sloveniya",
		"az-Cyrl-AZ": "Словенија",
		"kk-KZ": "Словения",
		"ky-KG": "Словения",
		"uz-UZ": "Sloveniya",
		"tg-TJ": "Словения",
		"tk-TM": "Sloweniýa",
		"fa-IR": "اسلوونی",
		"fa-AF": "سلونیا",
		"ps-AF": "سلوانیا",
		"ps-PK": "سلوانیا",
		"he-IL": "סלובניה",
		"ar-SA": "سلوفينيا",
		"ar-AE": "سلوفينيا",
		"ar-QA": "سلوفينيا",
		"ar-BH": "سلوفينيا",
		"ar-KW": "سلوفينيا",
		"ar-OM": "سلوفينيا",
		"ar-YE": "سلوفينيا",
		"ar-IQ": "سلوفينيا",
		"ar-JO": "سلوفينيا",
		"ar-LB": "سلوفينيا",
		"ar-SY": "سلوفينيا",
		"ar-PS": "سلوفينيا",
		"en-US": "Slovenia",
		"en-GB": "Slovenia",
		"en-IE": "Slovenia",
		"en-MT": "Slovenia",
		"en-GI": "Slovenia",
		"en-CY": "Slovenia",
		"en-JE": "Slovenia",
		"en-GG": "Slovenia",
		"en-IM": "Slovenia",
		"en-CA": "Slovenia",
		"en-AU": "Slovenia",
		"en-NZ": "Slovenia",
		"en-ZA": "Slovenia",
		"en-IN": "Slovenia",
		"en-SG": "Slovenia",
		"pt-AO": "Eslovénia",
		"pt-MZ": "Eslovénia",
		"pt-CV": "Eslovénia",
		"pt-GW": "Eslovénia",
		"pt-ST": "Eslovénia",
		"pt-TL": "Eslovénia",
		"pt-MO": "Eslovénia",
		"es-ES": "Eslovenia",
		"es-419": "Eslovenia",
		"es-AD": "Eslovenia",
		"es-GI": "Eslovenia",
		"es-AR": "Eslovenia",
		"es-BO": "Eslovenia",
		"es-BR": "Eslovenia",
		"es-BZ": "Eslovenia",
		"es-CL": "Eslovenia",
		"es-CO": "Eslovenia",
		"es-CR": "Eslovenia",
		"es-CU": "Eslovenia",
		"es-DO": "Eslovenia",
		"es-EC": "Eslovenia",
		"es-GT": "Eslovenia",
		"es-HN": "Eslovenia",
		"es-MX": "Eslovenia",
		"es-NI": "Eslovenia",
		"es-PA": "Eslovenia",
		"es-PE": "Eslovenia",
		"es-PR": "Eslovenia",
		"es-PY": "Eslovenia",
		"es-SV": "Eslovenia",
		"es-US": "Eslovenia",
		"es-UY": "Eslovenia",
		"es-VE": "Eslovenia",
		"fr-FR": "Slovénie",
		"fr-BE": "Slovénie",
		"fr-CH": "Slovénie",
		"fr-LU": "Slovénie",
		"fr-MC": "Slovénie",
		"fr-AD": "Slovénie",
		"fr-CA": "Slovénie",
		"it-IT": "Slovenia",
		"it-CH": "Slovenia",
		"it-SM": "Slovenia",
		"it-VA": "Slovenia",
		"de-DE": "Slowenien",
		"de-AT": "Slowenien",
		"de-CH": "Slowenien",
		"de-BE": "Slowenien",
		"de-LI": "Slowenien",
		"de-LU": "Slowenien",
		"nl-NL": "Slovenië",
		"nl-BE": "Slovenië",
		"sv-SE": "Slovenien",
		"sv-FI": "Slovenien",
		"da-DK": "Slovenien",
		"nb-NO": "Slovenia",
		"nn-NO": "Slovenia",
		"fi-FI": "Slovenia",
		"is-IS": "Slóvenía",
		"fo-FO": "Slovenia",
		"et-EE": "Sloveenia",
		"lv-LV": "Slovēnija",
		"lt-LT": "Slovėnija",
		"pl-PL": "Słowenia",
		"cs-CZ": "Slovinsko",
		"sk-SK": "Slovinsko",
		"sl-SI": "Slovenija",
		"hr-HR": "Slovenija",
		"bs-BA": "Slovenija",
		"sr-RS": "Словенија",
		"sr-BA": "Словенија",
		"sr-ME": "Slovenija",
		"mk-MK": "Словенија",
		"bg-BG": "Словения",
		"be-BY": "Славенія",
		"uk-UA": "Словенія",
		"ru-RU": "Словения",
		"el-GR": "Σλοβενία",
		"el-CY": "Σλοβενία",
		"ro-RO": "Slovenia",
		"ro-MD": "Slovenia",
		"hu-HU": "Szlovénia",
		"sq-AL": "Slloveni",
		"sq-XK": "Slloveni",
		"mt-MT": "is-Slovenja",
		"ga-IE": "an tSlóivéin",
		"cy-GB": "Slofenia",
		"gd-GB": "An t-Slòbhain",
		"lb-LU": "Slowenien",
		"ca-ES": "Eslovènia",
		"ca-AD": "Eslovènia",
		"ca-FR": "Eslovènia",
		"ca-IT": "Eslovènia",
		"eu-ES": "Eslovenia",
		"eu-FR": "Eslovenia",
		"gl-ES": "Eslovenia",
		"tr-TR": "Slovenya",
		"tr-CY": "Slovenya"
	},
	"callingCode": "386",
	"phoneMasks": [
		{
			"mask": "## ###",
			"minLength": 5,
			"maxLength": 5
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "# ### ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[1-57]"
			]
		},
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[37][01]|4[0139]|51|6"
			]
		},
		{
			"mask": "## ######",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"8[09]|9"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"59|8"
			]
		}
	]
} satisfies Country;
