import type { Country } from './types.js';

export const SWE = {
	"code": "SWE",
	"labels": {
		"pt-BR": "Suécia",
		"pt-PT": "Suécia",
		"es-ES": "Suecia",
		"es-419": "Suecia",
		"es-AR": "Suecia",
		"es-BO": "Suecia",
		"es-BR": "Suecia",
		"es-BZ": "Suecia",
		"es-CL": "Suecia",
		"es-CO": "Suecia",
		"es-CR": "Suecia",
		"es-CU": "Suecia",
		"es-DO": "Suecia",
		"es-EC": "Suecia",
		"es-GT": "Suecia",
		"es-HN": "Suecia",
		"es-MX": "Suecia",
		"es-NI": "Suecia",
		"es-PA": "Suecia",
		"es-PE": "Suecia",
		"es-PR": "Suecia",
		"es-PY": "Suecia",
		"es-SV": "Suecia",
		"es-US": "Suecia",
		"es-UY": "Suecia",
		"es-VE": "Suecia",
		"en-US": "Sweden",
		"fr-FR": "Suède",
		"fr-BE": "Suède",
		"fr-CA": "Suède",
		"fr-CH": "Suède",
		"fr-LU": "Suède",
		"fr-MC": "Suède",
		"it-IT": "Svezia",
		"it-CH": "Svezia",
		"it-SM": "Svezia",
		"it-VA": "Svezia",
		"de-DE": "Schweden",
		"de-AT": "Schweden",
		"de-CH": "Schweden",
		"de-BE": "Schweden",
		"de-LI": "Schweden",
		"de-LU": "Schweden"
	}
} satisfies Country;
