import type { Country } from './types.js';

export const SWE = {
	"code": "SWE",
	"labels": {
		"pt-BR": "Suécia",
		"pt-PT": "Suécia",
		"qu-PE": "Suecia",
		"qu-BO": "Suecia",
		"qu-EC": "Suecia",
		"chr-US": "ᏍᏫᏕᏂ",
		"hi-IN": "स्वीडन",
		"bn-IN": "সুইডেন",
		"bn-BD": "সুইডেন",
		"ta-IN": "ஸ்வீடன்",
		"ta-LK": "ஸ்வீடன்",
		"ta-SG": "ஸ்வீடன்",
		"ta-MY": "ஸ்வீடன்",
		"te-IN": "స్వీడన్",
		"mr-IN": "स्वीडन",
		"gu-IN": "સ્વીડન",
		"kn-IN": "ಸ್ವೀಡನ್",
		"ml-IN": "സ്വീഡൻ",
		"pa-IN": "ਸਵੀਡਨ",
		"ur-IN": "سویڈن",
		"ur-PK": "سویڈن",
		"or-IN": "ସ୍ୱିଡେନ୍‌",
		"as-IN": "চুইডেন",
		"ne-IN": "स्विडेन",
		"ne-NP": "स्विडेन",
		"si-LK": "ස්වීඩනය",
		"kok-IN": "स्वीडन",
		"ks-IN": "سویڈن",
		"brx-IN": "स्वीडेन",
		"mai-IN": "स्वीडन",
		"dz-BT": "སུའི་ཌེན",
		"ja-JP": "スウェーデン",
		"ko-KR": "스웨덴",
		"ko-KP": "스웨덴",
		"zh-CN": "瑞典",
		"zh-Hans-CN": "瑞典",
		"zh-Hant-TW": "瑞典",
		"zh-TW": "瑞典",
		"zh-HK": "瑞典",
		"zh-MO": "瑞典",
		"zh-SG": "瑞典",
		"yue-Hant-HK": "瑞典",
		"yue-Hans-CN": "瑞典",
		"mn-MN": "Швед",
		"ug-CN": "شىۋېتسىيە",
		"th-TH": "สวีเดน",
		"lo-LA": "ສະວີເດັນ",
		"km-KH": "ស៊ុយអែត",
		"my-MM": "ဆွီဒင်",
		"vi-VN": "Thụy Điển",
		"id-ID": "Swedia",
		"ms-MY": "Sweden",
		"ms-SG": "Sweden",
		"ms-BN": "Sweden",
		"jv-ID": "Swèdhen",
		"fil-PH": "Sweden",
		"ceb-PH": "Sweden",
		"ka-GE": "შვედეთი",
		"hy-AM": "Շվեդիա",
		"az-AZ": "İsveç",
		"az-Cyrl-AZ": "Исвеч",
		"kk-KZ": "Швеция",
		"ky-KG": "Швеция",
		"uz-UZ": "Shvetsiya",
		"tg-TJ": "Шветсия",
		"tk-TM": "Şwesiýa",
		"fa-IR": "سوئد",
		"fa-AF": "سویدن",
		"ps-AF": "سویډن",
		"ps-PK": "سویډن",
		"he-IL": "שוודיה",
		"ar-SA": "السويد",
		"ar-AE": "السويد",
		"ar-QA": "السويد",
		"ar-BH": "السويد",
		"ar-KW": "السويد",
		"ar-OM": "السويد",
		"ar-YE": "السويد",
		"ar-IQ": "السويد",
		"ar-JO": "السويد",
		"ar-LB": "السويد",
		"ar-SY": "السويد",
		"ar-PS": "السويد",
		"en-US": "Sweden",
		"en-GB": "Sweden",
		"en-IE": "Sweden",
		"en-MT": "Sweden",
		"en-GI": "Sweden",
		"en-CY": "Sweden",
		"en-JE": "Sweden",
		"en-GG": "Sweden",
		"en-IM": "Sweden",
		"en-CA": "Sweden",
		"en-AU": "Sweden",
		"en-NZ": "Sweden",
		"en-ZA": "Sweden",
		"en-IN": "Sweden",
		"en-SG": "Sweden",
		"pt-AO": "Suécia",
		"pt-MZ": "Suécia",
		"pt-CV": "Suécia",
		"pt-GW": "Suécia",
		"pt-ST": "Suécia",
		"pt-TL": "Suécia",
		"pt-MO": "Suécia",
		"es-ES": "Suecia",
		"es-419": "Suecia",
		"es-AD": "Suecia",
		"es-GI": "Suecia",
		"es-AR": "Suecia",
		"es-BO": "Suecia",
		"es-BR": "Suecia",
		"es-BZ": "Suecia",
		"es-CL": "Suecia",
		"es-CO": "Suecia",
		"es-CR": "Suecia",
		"es-CU": "Suecia",
		"es-DO": "Suecia",
		"es-EC": "Suecia",
		"es-GT": "Suecia",
		"es-HN": "Suecia",
		"es-MX": "Suecia",
		"es-NI": "Suecia",
		"es-PA": "Suecia",
		"es-PE": "Suecia",
		"es-PR": "Suecia",
		"es-PY": "Suecia",
		"es-SV": "Suecia",
		"es-US": "Suecia",
		"es-UY": "Suecia",
		"es-VE": "Suecia",
		"fr-FR": "Suède",
		"fr-BE": "Suède",
		"fr-CH": "Suède",
		"fr-LU": "Suède",
		"fr-MC": "Suède",
		"fr-AD": "Suède",
		"fr-CA": "Suède",
		"it-IT": "Svezia",
		"it-CH": "Svezia",
		"it-SM": "Svezia",
		"it-VA": "Svezia",
		"de-DE": "Schweden",
		"de-AT": "Schweden",
		"de-CH": "Schweden",
		"de-BE": "Schweden",
		"de-LI": "Schweden",
		"de-LU": "Schweden",
		"nl-NL": "Zweden",
		"nl-BE": "Zweden",
		"sv-SE": "Sverige",
		"sv-FI": "Sverige",
		"da-DK": "Sverige",
		"nb-NO": "Sverige",
		"nn-NO": "Sverige",
		"fi-FI": "Ruotsi",
		"is-IS": "Svíþjóð",
		"fo-FO": "Svøríki",
		"et-EE": "Rootsi",
		"lv-LV": "Zviedrija",
		"lt-LT": "Švedija",
		"pl-PL": "Szwecja",
		"cs-CZ": "Švédsko",
		"sk-SK": "Švédsko",
		"sl-SI": "Švedska",
		"hr-HR": "Švedska",
		"bs-BA": "Švedska",
		"sr-RS": "Шведска",
		"sr-BA": "Шведска",
		"sr-ME": "Švedska",
		"mk-MK": "Шведска",
		"bg-BG": "Швеция",
		"be-BY": "Швецыя",
		"uk-UA": "Швеція",
		"ru-RU": "Швеция",
		"el-GR": "Σουηδία",
		"el-CY": "Σουηδία",
		"ro-RO": "Suedia",
		"ro-MD": "Suedia",
		"hu-HU": "Svédország",
		"sq-AL": "Suedi",
		"sq-XK": "Suedi",
		"mt-MT": "l-Iżvezja",
		"ga-IE": "an tSualainn",
		"cy-GB": "Sweden",
		"gd-GB": "An t-Suain",
		"lb-LU": "Schweden",
		"ca-ES": "Suècia",
		"ca-AD": "Suècia",
		"ca-FR": "Suècia",
		"ca-IT": "Suècia",
		"eu-ES": "Suedia",
		"eu-FR": "Suedia",
		"gl-ES": "Suecia",
		"tr-TR": "İsveç",
		"tr-CY": "İsveç"
	},
	"callingCode": "46",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "##-### ##",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"20"
			]
		},
		{
			"mask": "##-### ##",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[12][136]|3[356]|4[0246]|6[03]|90[1-9]"
			]
		},
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"9(?:00|39|44|9)"
			]
		},
		{
			"mask": "#-### ## ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "###-### ##",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"1[2457]|2(?:[247-9]|5[0138])|3[0247-9]|4[1357-9]|5[0-35-9]|6(?:[125689]|4[02-57]|7[0-2])|9(?:[125-8]|3[02-5]|4[0-3])"
			]
		},
		{
			"mask": "#-### ### ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"8"
			]
		},
		{
			"mask": "##-### ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"1[13689]|2[0136]|3[1356]|4[0246]|54|6[03]|90[1-9]"
			]
		},
		{
			"mask": "##-### ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"10|7"
			]
		},
		{
			"mask": "###-## ## ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[13-5]|2(?:[247-9]|5[0138])|6(?:[124-689]|7[0-2])|9(?:[125-8]|3[02-5]|4[0-3])"
			]
		},
		{
			"mask": "###-### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"9(?:00|39|44)"
			]
		},
		{
			"mask": "###-## ## ###",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"9"
			]
		},
		{
			"mask": "###-## ### ## ##",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"[26]"
			]
		}
	]
} satisfies Country;
