import type { Country } from './types.js';

export const SWZ = {
	"code": "SWZ",
	"labels": {
		"pt-BR": "Essuatíni",
		"pt-PT": "Essuatíni",
		"es-ES": "Esuatini",
		"es-419": "Esuatini",
		"es-AR": "Esuatini",
		"es-BO": "Esuatini",
		"es-BR": "Esuatini",
		"es-BZ": "Esuatini",
		"es-CL": "Esuatini",
		"es-CO": "Esuatini",
		"es-CR": "Esuatini",
		"es-CU": "Esuatini",
		"es-DO": "Esuatini",
		"es-EC": "Esuatini",
		"es-GT": "Esuatini",
		"es-HN": "Esuatini",
		"es-MX": "Eswatini",
		"es-NI": "Esuatini",
		"es-PA": "Esuatini",
		"es-PE": "Esuatini",
		"es-PR": "Esuatini",
		"es-PY": "Esuatini",
		"es-SV": "Esuatini",
		"es-US": "Esuatini",
		"es-UY": "Esuatini",
		"es-VE": "Esuatini",
		"en-US": "Eswatini",
		"fr-FR": "Eswatini",
		"fr-BE": "Eswatini",
		"fr-CA": "Eswatini",
		"fr-CH": "Eswatini",
		"fr-LU": "Eswatini",
		"fr-MC": "Eswatini",
		"it-IT": "Eswatini",
		"it-CH": "Eswatini",
		"it-SM": "Eswatini",
		"it-VA": "Eswatini",
		"de-DE": "Eswatini",
		"de-AT": "Eswatini",
		"de-CH": "Eswatini",
		"de-BE": "Eswatini",
		"de-LI": "Eswatini",
		"de-LU": "Eswatini"
	},
	"callingCode": "268"
} satisfies Country;
