import type { Country } from './types.js';

export const SXM = {
	"code": "SXM",
	"labels": {
		"pt-BR": "Sint Maarten",
		"pt-PT": "São Martinho (Sint Maarten)",
		"es-ES": "Sint Maarten",
		"es-419": "Sint Maarten",
		"es-AR": "Sint Maarten",
		"es-BO": "Sint Maarten",
		"es-BR": "Sint Maarten",
		"es-BZ": "Sint Maarten",
		"es-CL": "Sint Maarten",
		"es-CO": "Sint Maarten",
		"es-CR": "Sint Maarten",
		"es-CU": "Sint Maarten",
		"es-DO": "Sint Maarten",
		"es-EC": "Sint Maarten",
		"es-GT": "Sint Maarten",
		"es-HN": "Sint Maarten",
		"es-MX": "Sint Maarten",
		"es-NI": "Sint Maarten",
		"es-PA": "Sint Maarten",
		"es-PE": "Sint Maarten",
		"es-PR": "Sint Maarten",
		"es-PY": "Sint Maarten",
		"es-SV": "Sint Maarten",
		"es-US": "Sint Maarten",
		"es-UY": "Sint Maarten",
		"es-VE": "Sint Maarten",
		"en-US": "Sint Maarten",
		"fr-FR": "Saint-Martin (partie néerlandaise)",
		"fr-BE": "Saint-Martin (partie néerlandaise)",
		"fr-CA": "Saint-Martin (Pays-Bas)",
		"fr-CH": "Saint-Martin (partie néerlandaise)",
		"fr-LU": "Saint-Martin (partie néerlandaise)",
		"fr-MC": "Saint-Martin (partie néerlandaise)",
		"it-IT": "Sint Maarten",
		"it-CH": "Sint Maarten",
		"it-SM": "Sint Maarten",
		"it-VA": "Sint Maarten",
		"de-DE": "Sint Maarten",
		"de-AT": "Sint Maarten",
		"de-CH": "Sint Maarten",
		"de-BE": "Sint Maarten",
		"de-LI": "Sint Maarten",
		"de-LU": "Sint Maarten"
	},
	"callingCode": "1721"
} satisfies Country;
