import type { Country } from './types.js';

export const SXM = {
	"code": "SXM",
	"labels": {
		"pt-BR": "Sint Maarten",
		"pt-PT": "São Martinho (Sint Maarten)",
		"qu-PE": "Sint Maarten",
		"qu-BO": "Sint Maarten",
		"qu-EC": "Sint Maarten",
		"chr-US": "ᏏᏂᏘ ᎹᏘᏂ",
		"hi-IN": "सिंट मार्टिन",
		"bn-IN": "সিন্ট মার্টেন",
		"bn-BD": "সিন্ট মার্টেন",
		"ta-IN": "சின்ட் மார்டென்",
		"ta-LK": "சின்ட் மார்டென்",
		"ta-SG": "சின்ட் மார்டென்",
		"ta-MY": "சின்ட் மார்டென்",
		"te-IN": "సింట్ మార్టెన్",
		"mr-IN": "सिंट मार्टेन",
		"gu-IN": "સિંટ માર્ટેન",
		"kn-IN": "ಸಿಂಟ್ ಮಾರ್ಟೆನ್",
		"ml-IN": "സിന്റ് മാർട്ടെൻ",
		"pa-IN": "ਸਿੰਟ ਮਾਰਟੀਨ",
		"ur-IN": "سنٹ مارٹن",
		"ur-PK": "سنٹ مارٹن",
		"or-IN": "ସିଣ୍ଟ ମାର୍ଟୀନ୍‌",
		"as-IN": "চিণ্ট মাৰ্টেন",
		"ne-IN": "सिन्ट मार्टेन",
		"ne-NP": "सिन्ट मार्टेन",
		"si-LK": "ශාන්ත මාර්ටෙන්",
		"kok-IN": "सिंट मार्टेन",
		"ks-IN": "سِنٹ مارٹِن",
		"brx-IN": "सिन्त मार्तेन",
		"mai-IN": "सिंट मार्टेन",
		"dz-BT": "སིནཊ་ མཱར་ཊེན",
		"ja-JP": "シント・マールテン",
		"ko-KR": "신트마르턴",
		"ko-KP": "신트마르턴",
		"zh-CN": "荷属圣马丁",
		"zh-Hans-CN": "荷属圣马丁",
		"zh-Hant-TW": "荷屬聖馬丁",
		"zh-TW": "荷屬聖馬丁",
		"zh-HK": "荷屬聖馬丁",
		"zh-MO": "荷屬聖馬丁",
		"zh-SG": "荷属圣马丁",
		"yue-Hant-HK": "荷屬聖馬丁",
		"yue-Hans-CN": "荷属圣马丁",
		"mn-MN": "Синт Мартен",
		"ug-CN": "سىنت مارتېن",
		"th-TH": "ซินต์มาร์เทน",
		"lo-LA": "ຊິນ ມາເທັນ",
		"km-KH": "សីង​ម៉ាធីន",
		"my-MM": "စင့်မာတင်",
		"vi-VN": "Sint Maarten",
		"id-ID": "Sint Maarten",
		"ms-MY": "Sint Maarten",
		"ms-SG": "Sint Maarten",
		"ms-BN": "Sint Maarten",
		"jv-ID": "Sint Martén",
		"fil-PH": "Sint Maarten",
		"ceb-PH": "Sint Maarten",
		"ka-GE": "სინტ-მარტენი",
		"hy-AM": "Սինտ Մարտեն",
		"az-AZ": "Sint-Marten",
		"az-Cyrl-AZ": "Синт-Мартен",
		"kk-KZ": "Синт-Мартен",
		"ky-KG": "Синт-Мартен",
		"uz-UZ": "Sint-Marten",
		"tg-TJ": "Синт-Маартен",
		"tk-TM": "Sint-Marten",
		"fa-IR": "سنت مارتن",
		"fa-AF": "سنت مارتن",
		"ps-AF": "سینټ مارټین",
		"ps-PK": "سینټ مارټین",
		"he-IL": "סנט מארטן",
		"ar-SA": "سانت مارتن",
		"ar-AE": "سانت مارتن",
		"ar-QA": "سانت مارتن",
		"ar-BH": "سانت مارتن",
		"ar-KW": "سانت مارتن",
		"ar-OM": "سانت مارتن",
		"ar-YE": "سانت مارتن",
		"ar-IQ": "سانت مارتن",
		"ar-JO": "سانت مارتن",
		"ar-LB": "سانت مارتن",
		"ar-SY": "سانت مارتن",
		"ar-PS": "سانت مارتن",
		"en-US": "Sint Maarten",
		"en-GB": "Sint Maarten",
		"en-IE": "Sint Maarten",
		"en-MT": "Sint Maarten",
		"en-GI": "Sint Maarten",
		"en-CY": "Sint Maarten",
		"en-JE": "Sint Maarten",
		"en-GG": "Sint Maarten",
		"en-IM": "Sint Maarten",
		"en-CA": "Sint Maarten",
		"en-AU": "Sint Maarten",
		"en-NZ": "Sint Maarten",
		"en-ZA": "Sint Maarten",
		"en-IN": "Sint Maarten",
		"en-SG": "Sint Maarten",
		"pt-AO": "São Martinho (Sint Maarten)",
		"pt-MZ": "São Martinho (Sint Maarten)",
		"pt-CV": "São Martinho (Sint Maarten)",
		"pt-GW": "São Martinho (Sint Maarten)",
		"pt-ST": "São Martinho (Sint Maarten)",
		"pt-TL": "São Martinho (Sint Maarten)",
		"pt-MO": "São Martinho (Sint Maarten)",
		"es-ES": "Sint Maarten",
		"es-419": "Sint Maarten",
		"es-AD": "Sint Maarten",
		"es-GI": "Sint Maarten",
		"es-AR": "Sint Maarten",
		"es-BO": "Sint Maarten",
		"es-BR": "Sint Maarten",
		"es-BZ": "Sint Maarten",
		"es-CL": "Sint Maarten",
		"es-CO": "Sint Maarten",
		"es-CR": "Sint Maarten",
		"es-CU": "Sint Maarten",
		"es-DO": "Sint Maarten",
		"es-EC": "Sint Maarten",
		"es-GT": "Sint Maarten",
		"es-HN": "Sint Maarten",
		"es-MX": "Sint Maarten",
		"es-NI": "Sint Maarten",
		"es-PA": "Sint Maarten",
		"es-PE": "Sint Maarten",
		"es-PR": "Sint Maarten",
		"es-PY": "Sint Maarten",
		"es-SV": "Sint Maarten",
		"es-US": "Sint Maarten",
		"es-UY": "Sint Maarten",
		"es-VE": "Sint Maarten",
		"fr-FR": "Saint-Martin (partie néerlandaise)",
		"fr-BE": "Saint-Martin (partie néerlandaise)",
		"fr-CH": "Saint-Martin (partie néerlandaise)",
		"fr-LU": "Saint-Martin (partie néerlandaise)",
		"fr-MC": "Saint-Martin (partie néerlandaise)",
		"fr-AD": "Saint-Martin (partie néerlandaise)",
		"fr-CA": "Saint-Martin (Pays-Bas)",
		"it-IT": "Sint Maarten",
		"it-CH": "Sint Maarten",
		"it-SM": "Sint Maarten",
		"it-VA": "Sint Maarten",
		"de-DE": "Sint Maarten",
		"de-AT": "Sint Maarten",
		"de-CH": "Sint Maarten",
		"de-BE": "Sint Maarten",
		"de-LI": "Sint Maarten",
		"de-LU": "Sint Maarten",
		"nl-NL": "Sint-Maarten",
		"nl-BE": "Sint-Maarten",
		"sv-SE": "Sint Maarten",
		"sv-FI": "Sint Maarten",
		"da-DK": "Sint Maarten",
		"nb-NO": "Sint Maarten",
		"nn-NO": "Sint Maarten",
		"fi-FI": "Sint Maarten",
		"is-IS": "Sint Maarten",
		"fo-FO": "Sint Maarten",
		"et-EE": "Sint Maarten",
		"lv-LV": "Sintmārtena",
		"lt-LT": "Sint Martenas",
		"pl-PL": "Sint Maarten",
		"cs-CZ": "Svatý Martin (Nizozemsko)",
		"sk-SK": "Svätý Martin (hol.)",
		"sl-SI": "Sint Maarten",
		"hr-HR": "Sint Maarten",
		"bs-BA": "Sint Marten",
		"sr-RS": "Свети Мартин (Холандија)",
		"sr-BA": "Свети Мартин (Холандија)",
		"sr-ME": "Sveti Martin (Holandija)",
		"mk-MK": "Свети Мартин",
		"bg-BG": "Синт Мартен",
		"be-BY": "Сінт-Мартэн",
		"uk-UA": "Сінт-Мартен",
		"ru-RU": "Синт-Мартен",
		"el-GR": "Άγιος Μαρτίνος (Ολλανδικό τμήμα)",
		"el-CY": "Άγιος Μαρτίνος (Ολλανδικό τμήμα)",
		"ro-RO": "Sint-Maarten",
		"ro-MD": "Sint-Maarten",
		"hu-HU": "Sint Maarten",
		"sq-AL": "Sint-Marten",
		"sq-XK": "Sint-Marten",
		"mt-MT": "Sint Maarten",
		"ga-IE": "Sint Maarten",
		"cy-GB": "Sint Maarten",
		"gd-GB": "Sint Maarten",
		"lb-LU": "Sint Maarten",
		"ca-ES": "Sint Maarten",
		"ca-AD": "Sint Maarten",
		"ca-FR": "Sint Maarten",
		"ca-IT": "Sint Maarten",
		"eu-ES": "Sint Maarten",
		"eu-FR": "Sint Maarten",
		"gl-ES": "Sint Maarten",
		"tr-TR": "Sint Maarten",
		"tr-CY": "Sint Maarten"
	},
	"callingCode": "1721",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
