import type { Country } from './types.js';

export const SYC = {
	"code": "SYC",
	"labels": {
		"pt-BR": "Seicheles",
		"pt-PT": "Seicheles",
		"es-ES": "Seychelles",
		"es-419": "Seychelles",
		"es-AR": "Seychelles",
		"es-BO": "Seychelles",
		"es-BR": "Seychelles",
		"es-BZ": "Seychelles",
		"es-CL": "Seychelles",
		"es-CO": "Seychelles",
		"es-CR": "Seychelles",
		"es-CU": "Seychelles",
		"es-DO": "Seychelles",
		"es-EC": "Seychelles",
		"es-GT": "Seychelles",
		"es-HN": "Seychelles",
		"es-MX": "Seychelles",
		"es-NI": "Seychelles",
		"es-PA": "Seychelles",
		"es-PE": "Seychelles",
		"es-PR": "Seychelles",
		"es-PY": "Seychelles",
		"es-SV": "Seychelles",
		"es-US": "Seychelles",
		"es-UY": "Seychelles",
		"es-VE": "Seychelles",
		"en-US": "Seychelles",
		"fr-FR": "Seychelles",
		"fr-BE": "Seychelles",
		"fr-CA": "Seychelles",
		"fr-CH": "Seychelles",
		"fr-LU": "Seychelles",
		"fr-MC": "Seychelles",
		"it-IT": "Seychelles",
		"it-CH": "Seychelles",
		"it-SM": "Seychelles",
		"it-VA": "Seychelles",
		"de-DE": "Seychellen",
		"de-AT": "Seychellen",
		"de-CH": "Seychellen",
		"de-BE": "Seychellen",
		"de-LI": "Seychellen",
		"de-LU": "Seychellen"
	},
	"callingCode": "248"
} satisfies Country;
