import type { Country } from './types.js';

export const TCA = {
	"code": "TCA",
	"labels": {
		"pt-BR": "Ilhas Turcas e Caicos",
		"pt-PT": "Ilhas Turcas e Caicos",
		"es-ES": "Islas Turcas y Caicos",
		"es-419": "Islas Turcas y Caicos",
		"es-AR": "Islas Turcas y Caicos",
		"es-BO": "Islas Turcas y Caicos",
		"es-BR": "Islas Turcas y Caicos",
		"es-BZ": "Islas Turcas y Caicos",
		"es-CL": "Islas Turcas y Caicos",
		"es-CO": "Islas Turcas y Caicos",
		"es-CR": "Islas Turcas y Caicos",
		"es-CU": "Islas Turcas y Caicos",
		"es-DO": "Islas Turcas y Caicos",
		"es-EC": "Islas Turcas y Caicos",
		"es-GT": "Islas Turcas y Caicos",
		"es-HN": "Islas Turcas y Caicos",
		"es-MX": "Islas Turcas y Caicos",
		"es-NI": "Islas Turcas y Caicos",
		"es-PA": "Islas Turcas y Caicos",
		"es-PE": "Islas Turcas y Caicos",
		"es-PR": "Islas Turcas y Caicos",
		"es-PY": "Islas Turcas y Caicos",
		"es-SV": "Islas Turcas y Caicos",
		"es-US": "Islas Turcas y Caicos",
		"es-UY": "Islas Turcas y Caicos",
		"es-VE": "Islas Turcas y Caicos",
		"en-US": "Turks & Caicos Islands",
		"fr-FR": "Îles Turques-et-Caïques",
		"fr-BE": "Îles Turques-et-Caïques",
		"fr-CA": "Îles Turques-et-Caïques",
		"fr-CH": "Îles Turques-et-Caïques",
		"fr-LU": "Îles Turques-et-Caïques",
		"fr-MC": "Îles Turques-et-Caïques",
		"it-IT": "Isole Turks e Caicos",
		"it-CH": "Isole Turks e Caicos",
		"it-SM": "Isole Turks e Caicos",
		"it-VA": "Isole Turks e Caicos",
		"de-DE": "Turks- und Caicosinseln",
		"de-AT": "Turks- und Caicosinseln",
		"de-CH": "Turks- und Caicosinseln",
		"de-BE": "Turks- und Caicosinseln",
		"de-LI": "Turks- und Caicosinseln",
		"de-LU": "Turks- und Caicosinseln"
	}
} satisfies Country;
