import type { Country } from './types.js';

export const TCA = {
	"code": "TCA",
	"labels": {
		"pt-BR": "Ilhas Turcas e Caicos",
		"pt-PT": "Ilhas Turcas e Caicos",
		"qu-PE": "Islas Turcas y Caicos",
		"qu-BO": "Islas Turcas y Caicos",
		"qu-EC": "Islas Turcas y Caicos",
		"chr-US": "ᎠᏂᏛᎵᎩ ᎠᎴ ᎨᎢᎪ ᏚᎦᏚᏛᎢ",
		"hi-IN": "तुर्क और कैकोज़ द्वीपसमूह",
		"bn-IN": "তুর্কস ও কাইকোস দ্বীপপুঞ্জ",
		"bn-BD": "তুর্কস ও কাইকোস দ্বীপপুঞ্জ",
		"ta-IN": "டர்க்ஸ் & கைகோஸ் தீவுகள்",
		"ta-LK": "டர்க்ஸ் & கைகோஸ் தீவுகள்",
		"ta-SG": "டர்க்ஸ் & கைகோஸ் தீவுகள்",
		"ta-MY": "டர்க்ஸ் & கைகோஸ் தீவுகள்",
		"te-IN": "టర్క్స్ మరియు కైకోస్ దీవులు",
		"mr-IN": "टर्क्स आणि कैकोस बेटे",
		"gu-IN": "તુર્ક્સ અને કેકોઝ આઇલેન્ડ્સ",
		"kn-IN": "ಟರ್ಕ್ಸ್ ಮತ್ತು ಕೈಕೋಸ್ ದ್ವೀಪಗಳು",
		"ml-IN": "ടർക്ക്‌സും കെയ്‌ക്കോ ദ്വീപുകളും",
		"pa-IN": "ਟੁਰਕਸ ਅਤੇ ਕੈਕੋਸ ਟਾਪੂ",
		"ur-IN": "جزائر کیکس و ترکیہ",
		"ur-PK": "ٹرکس اور کیکوس جزائر",
		"or-IN": "ତୁର୍କସ୍‌ ଏବଂ କାଇକୋସ୍‌ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "টাৰ্কছ অৰু কেইক’ছ দ্বীপপুঞ্জ",
		"ne-IN": "तुर्क र काइकोस टापु",
		"ne-NP": "तुर्क र काइकोस टापु",
		"si-LK": "ටර්ක්ස් සහ කයිකොස් දූපත්",
		"kok-IN": "तुर्क्स आनी कॅकोज आयलँड्स",
		"ks-IN": "تُرکس تٕہ کیکو جزیرٕ",
		"brx-IN": "तुर्की आरो काईक’ज द्वीपफोर",
		"mai-IN": "तुर्क आ कैकोज द्वीपसमूह",
		"dz-BT": "ཏུརྐས྄་ ཨེནཌ་ ཀ་ཀོས་གླིང་ཚོམ",
		"ja-JP": "タークス・カイコス諸島",
		"ko-KR": "터크스 케이커스 제도",
		"ko-KP": "터크스 케이커스 제도",
		"zh-CN": "特克斯和凯科斯群岛",
		"zh-Hans-CN": "特克斯和凯科斯群岛",
		"zh-Hant-TW": "土克斯及開科斯群島",
		"zh-TW": "土克斯及開科斯群島",
		"zh-HK": "特克斯和凱科斯群島",
		"zh-MO": "特克斯和凱科斯群島",
		"zh-SG": "特克斯和凯科斯群岛",
		"yue-Hant-HK": "土克斯及開科斯群島",
		"yue-Hans-CN": "土克斯及开科斯群岛",
		"mn-MN": "Турк ба Кайкосын Арлууд",
		"ug-CN": "تۇركس ۋە كايكوس ئاراللىرى",
		"th-TH": "หมู่เกาะเติกส์และหมู่เกาะเคคอส",
		"lo-LA": "ໝູ່ເກາະ ເທີກ ແລະ ໄຄໂຄສ",
		"km-KH": "កោះ​ទួគ និង កៃកូស",
		"my-MM": "တခ်စ်နှင့်ကာအီကိုစ်ကျွန်းစု",
		"vi-VN": "Quần đảo Turks và Caicos",
		"id-ID": "Kepulauan Turks dan Caicos",
		"ms-MY": "Kepulauan Turks dan Caicos",
		"ms-SG": "Kepulauan Turks dan Caicos",
		"ms-BN": "Kepulauan Turks dan Caicos",
		"jv-ID": "Turks lan Kapuloan Kaikos",
		"fil-PH": "Turks & Caicos Islands",
		"ceb-PH": "Turks & Caicos Islands",
		"ka-GE": "თერქს-ქაიქოსის კუნძულები",
		"hy-AM": "Թըրքս և Կայկոս կղզիներ",
		"az-AZ": "Törks və Kaykos adaları",
		"az-Cyrl-AZ": "Төркс вә Кајкос адалары",
		"kk-KZ": "Теркс және Кайкос аралдары",
		"ky-KG": "Түркс жана Кайкос аралдары",
		"uz-UZ": "Turks va Kaykos orollari",
		"tg-TJ": "Ҷазираҳои Теркс ва Кайкос",
		"tk-TM": "Terks we Kaýkos adalary",
		"fa-IR": "جزایر تورکس و کایکوس",
		"fa-AF": "جزایر تورکس و کایکوس",
		"ps-AF": "د ترکیې او کیکاسو ټاپو",
		"ps-PK": "د ترکیے او کیکاسو ټاپو",
		"he-IL": "איי טרקס וקייקוס",
		"ar-SA": "جزر توركس وكايكوس",
		"ar-AE": "جزر توركس وكايكوس",
		"ar-QA": "جزر توركس وكايكوس",
		"ar-BH": "جزر توركس وكايكوس",
		"ar-KW": "جزر توركس وكايكوس",
		"ar-OM": "جزر توركس وكايكوس",
		"ar-YE": "جزر توركس وكايكوس",
		"ar-IQ": "جزر توركس وكايكوس",
		"ar-JO": "جزر توركس وكايكوس",
		"ar-LB": "جزر توركس وكايكوس",
		"ar-SY": "جزر توركس وكايكوس",
		"ar-PS": "جزر توركس وكايكوس",
		"en-US": "Turks & Caicos Islands",
		"en-GB": "Turks & Caicos Islands",
		"en-IE": "Turks & Caicos Islands",
		"en-MT": "Turks & Caicos Islands",
		"en-GI": "Turks & Caicos Islands",
		"en-CY": "Turks & Caicos Islands",
		"en-JE": "Turks & Caicos Islands",
		"en-GG": "Turks & Caicos Islands",
		"en-IM": "Turks & Caicos Islands",
		"en-CA": "Turks and Caicos Islands",
		"en-AU": "Turks & Caicos Islands",
		"en-NZ": "Turks & Caicos Islands",
		"en-ZA": "Turks & Caicos Islands",
		"en-IN": "Turks & Caicos Islands",
		"en-SG": "Turks & Caicos Islands",
		"pt-AO": "Ilhas Turcas e Caicos",
		"pt-MZ": "Ilhas Turcas e Caicos",
		"pt-CV": "Ilhas Turcas e Caicos",
		"pt-GW": "Ilhas Turcas e Caicos",
		"pt-ST": "Ilhas Turcas e Caicos",
		"pt-TL": "Ilhas Turcas e Caicos",
		"pt-MO": "Ilhas Turcas e Caicos",
		"es-ES": "Islas Turcas y Caicos",
		"es-419": "Islas Turcas y Caicos",
		"es-AD": "Islas Turcas y Caicos",
		"es-GI": "Islas Turcas y Caicos",
		"es-AR": "Islas Turcas y Caicos",
		"es-BO": "Islas Turcas y Caicos",
		"es-BR": "Islas Turcas y Caicos",
		"es-BZ": "Islas Turcas y Caicos",
		"es-CL": "Islas Turcas y Caicos",
		"es-CO": "Islas Turcas y Caicos",
		"es-CR": "Islas Turcas y Caicos",
		"es-CU": "Islas Turcas y Caicos",
		"es-DO": "Islas Turcas y Caicos",
		"es-EC": "Islas Turcas y Caicos",
		"es-GT": "Islas Turcas y Caicos",
		"es-HN": "Islas Turcas y Caicos",
		"es-MX": "Islas Turcas y Caicos",
		"es-NI": "Islas Turcas y Caicos",
		"es-PA": "Islas Turcas y Caicos",
		"es-PE": "Islas Turcas y Caicos",
		"es-PR": "Islas Turcas y Caicos",
		"es-PY": "Islas Turcas y Caicos",
		"es-SV": "Islas Turcas y Caicos",
		"es-US": "Islas Turcas y Caicos",
		"es-UY": "Islas Turcas y Caicos",
		"es-VE": "Islas Turcas y Caicos",
		"fr-FR": "Îles Turques-et-Caïques",
		"fr-BE": "Îles Turques-et-Caïques",
		"fr-CH": "Îles Turques-et-Caïques",
		"fr-LU": "Îles Turques-et-Caïques",
		"fr-MC": "Îles Turques-et-Caïques",
		"fr-AD": "Îles Turques-et-Caïques",
		"fr-CA": "Îles Turques-et-Caïques",
		"it-IT": "Isole Turks e Caicos",
		"it-CH": "Isole Turks e Caicos",
		"it-SM": "Isole Turks e Caicos",
		"it-VA": "Isole Turks e Caicos",
		"de-DE": "Turks- und Caicosinseln",
		"de-AT": "Turks- und Caicosinseln",
		"de-CH": "Turks- und Caicosinseln",
		"de-BE": "Turks- und Caicosinseln",
		"de-LI": "Turks- und Caicosinseln",
		"de-LU": "Turks- und Caicosinseln",
		"nl-NL": "Turks- en Caicoseilanden",
		"nl-BE": "Turks- en Caicoseilanden",
		"sv-SE": "Turks- och Caicosöarna",
		"sv-FI": "Turks- och Caicosöarna",
		"da-DK": "Turks- og Caicosøerne",
		"nb-NO": "Turks- og Caicosøyene",
		"nn-NO": "Turks- og Caicosøyane",
		"fi-FI": "Turks- ja Caicossaaret",
		"is-IS": "Turks- og Caicoseyjar",
		"fo-FO": "Turks- og Caicosoyggjar",
		"et-EE": "Turks ja Caicos",
		"lv-LV": "Tērksas un Kaikosas salas",
		"lt-LT": "Terkso ir Kaikoso Salos",
		"pl-PL": "Turks i Caicos",
		"cs-CZ": "Turks a Caicos",
		"sk-SK": "Turks a Caicos",
		"sl-SI": "Otoki Turks in Caicos",
		"hr-HR": "Otoci Turks i Caicos",
		"bs-BA": "Ostrva Turks i Kaikos",
		"sr-RS": "Острва Туркс и Каикос",
		"sr-BA": "Острва Туркс и Каикос",
		"sr-ME": "Ostrva Turks i Kaikos",
		"mk-MK": "Острови Туркс и Каикос",
		"bg-BG": "острови Търкс и Кайкос",
		"be-BY": "Астравы Цёркс і Кайкас",
		"uk-UA": "Острови Теркс і Кайкос",
		"ru-RU": "Тёркс и Кайкос",
		"el-GR": "Νήσοι Τερκς και Κάικος",
		"el-CY": "Νήσοι Τερκς και Κάικος",
		"ro-RO": "Insulele Turks și Caicos",
		"ro-MD": "Insulele Turks și Caicos",
		"hu-HU": "Turks- és Caicos-szigetek",
		"sq-AL": "Ishujt Turks dhe Kaikos",
		"sq-XK": "Ishujt Turks dhe Kaikos",
		"mt-MT": "il-Gżejjer Turks u Caicos",
		"ga-IE": "Oileáin na dTurcach agus Caicos",
		"cy-GB": "Ynysoedd Turks a Caicos",
		"gd-GB": "Na h-Eileanan Turcach is Caiceo",
		"lb-LU": "Turks- a Caicosinselen",
		"ca-ES": "Illes Turks i Caicos",
		"ca-AD": "Illes Turks i Caicos",
		"ca-FR": "Illes Turks i Caicos",
		"ca-IT": "Illes Turks i Caicos",
		"eu-ES": "Turk eta Caico uharteak",
		"eu-FR": "Turk eta Caico uharteak",
		"gl-ES": "Illas Turks e Caicos",
		"tr-TR": "Turks ve Caicos Adaları",
		"tr-CY": "Turks ve Caicos Adaları"
	},
	"callingCode": "1649",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
