import type { Country } from './types.js';

export const TGO = {
	"code": "TGO",
	"labels": {
		"pt-BR": "Togo",
		"pt-PT": "Togo",
		"es-ES": "Togo",
		"es-419": "Togo",
		"es-AR": "Togo",
		"es-BO": "Togo",
		"es-BR": "Togo",
		"es-BZ": "Togo",
		"es-CL": "Togo",
		"es-CO": "Togo",
		"es-CR": "Togo",
		"es-CU": "Togo",
		"es-DO": "Togo",
		"es-EC": "Togo",
		"es-GT": "Togo",
		"es-HN": "Togo",
		"es-MX": "Togo",
		"es-NI": "Togo",
		"es-PA": "Togo",
		"es-PE": "Togo",
		"es-PR": "Togo",
		"es-PY": "Togo",
		"es-SV": "Togo",
		"es-US": "Togo",
		"es-UY": "Togo",
		"es-VE": "Togo",
		"en-US": "Togo",
		"fr-FR": "Togo",
		"fr-BE": "Togo",
		"fr-CA": "Togo",
		"fr-CH": "Togo",
		"fr-LU": "Togo",
		"fr-MC": "Togo",
		"it-IT": "Togo",
		"it-CH": "Togo",
		"it-SM": "Togo",
		"it-VA": "Togo",
		"de-DE": "Togo",
		"de-AT": "Togo",
		"de-CH": "Togo",
		"de-BE": "Togo",
		"de-LI": "Togo",
		"de-LU": "Togo"
	}
} satisfies Country;
