import type { Country } from './types.js';

export const TJK = {
	"code": "TJK",
	"labels": {
		"pt-BR": "Tadjiquistão",
		"pt-PT": "Tajiquistão",
		"qu-PE": "Tayikistán",
		"qu-BO": "Tayikistán",
		"qu-EC": "Tayikistán",
		"chr-US": "ᏔᏥᎩᏍᏕᏂ",
		"hi-IN": "ताजिकिस्तान",
		"bn-IN": "তাজিকিস্তান",
		"bn-BD": "তাজিকিস্তান",
		"ta-IN": "தஜிகிஸ்தான்",
		"ta-LK": "தஜிகிஸ்தான்",
		"ta-SG": "தஜிகிஸ்தான்",
		"ta-MY": "தஜிகிஸ்தான்",
		"te-IN": "తజికిస్తాన్",
		"mr-IN": "ताजिकिस्तान",
		"gu-IN": "તાજીકિસ્તાન",
		"kn-IN": "ತಜಿಕಿಸ್ತಾನ್",
		"ml-IN": "താജിക്കിസ്ഥാൻ",
		"pa-IN": "ਤਾਜਿਕਿਸਤਾਨ",
		"ur-IN": "تاجکستان",
		"ur-PK": "تاجکستان",
		"or-IN": "ତାଜିକିସ୍ଥାନ୍",
		"as-IN": "তাজিকিস্তান",
		"ne-IN": "ताजिकिस्तान",
		"ne-NP": "ताजिकिस्तान",
		"si-LK": "ටජිකිස්තානය",
		"kok-IN": "तजीकिस्तान",
		"ks-IN": "تاجکِستان",
		"brx-IN": "ताजिकिस्तान",
		"mai-IN": "ताजिकिस्तान",
		"dz-BT": "ཏ་ཇིག་གི་སཏཱན",
		"ja-JP": "タジキスタン",
		"ko-KR": "타지키스탄",
		"ko-KP": "타지키스탄",
		"zh-CN": "塔吉克斯坦",
		"zh-Hans-CN": "塔吉克斯坦",
		"zh-Hant-TW": "塔吉克",
		"zh-TW": "塔吉克",
		"zh-HK": "塔吉克",
		"zh-MO": "塔吉克",
		"zh-SG": "塔吉克斯坦",
		"yue-Hant-HK": "塔吉克",
		"yue-Hans-CN": "塔吉克",
		"mn-MN": "Тажикистан",
		"ug-CN": "تاجىكىستان",
		"th-TH": "ทาจิกิสถาน",
		"lo-LA": "ທາຈິກິດສະຖານ",
		"km-KH": "តាហ្ស៊ីគីស្ថាន",
		"my-MM": "တာဂျီကစ္စတန်",
		"vi-VN": "Tajikistan",
		"id-ID": "Tajikistan",
		"ms-MY": "Tajikistan",
		"ms-SG": "Tajikistan",
		"ms-BN": "Tajikistan",
		"jv-ID": "Tajikistan",
		"fil-PH": "Tajikistan",
		"ceb-PH": "Tajikistan",
		"ka-GE": "ტაჯიკეთი",
		"hy-AM": "Տաջիկստան",
		"az-AZ": "Tacikistan",
		"az-Cyrl-AZ": "Таҹикистан",
		"kk-KZ": "Тәжікстан",
		"ky-KG": "Тажикстан",
		"uz-UZ": "Tojikiston",
		"tg-TJ": "Тоҷикистон",
		"tk-TM": "Täjigistan",
		"fa-IR": "تاجیکستان",
		"fa-AF": "تاجکستان",
		"ps-AF": "تاجکستان",
		"ps-PK": "تاجکستان",
		"he-IL": "טג׳יקיסטן",
		"ar-SA": "طاجيكستان",
		"ar-AE": "طاجيكستان",
		"ar-QA": "طاجيكستان",
		"ar-BH": "طاجيكستان",
		"ar-KW": "طاجيكستان",
		"ar-OM": "طاجيكستان",
		"ar-YE": "طاجيكستان",
		"ar-IQ": "طاجيكستان",
		"ar-JO": "طاجيكستان",
		"ar-LB": "طاجيكستان",
		"ar-SY": "طاجيكستان",
		"ar-PS": "طاجيكستان",
		"en-US": "Tajikistan",
		"en-GB": "Tajikistan",
		"en-IE": "Tajikistan",
		"en-MT": "Tajikistan",
		"en-GI": "Tajikistan",
		"en-CY": "Tajikistan",
		"en-JE": "Tajikistan",
		"en-GG": "Tajikistan",
		"en-IM": "Tajikistan",
		"en-CA": "Tajikistan",
		"en-AU": "Tajikistan",
		"en-NZ": "Tajikistan",
		"en-ZA": "Tajikistan",
		"en-IN": "Tajikistan",
		"en-SG": "Tajikistan",
		"pt-AO": "Tajiquistão",
		"pt-MZ": "Tajiquistão",
		"pt-CV": "Tajiquistão",
		"pt-GW": "Tajiquistão",
		"pt-ST": "Tajiquistão",
		"pt-TL": "Tajiquistão",
		"pt-MO": "Tajiquistão",
		"es-ES": "Tayikistán",
		"es-419": "Tayikistán",
		"es-AD": "Tayikistán",
		"es-GI": "Tayikistán",
		"es-AR": "Tayikistán",
		"es-BO": "Tayikistán",
		"es-BR": "Tayikistán",
		"es-BZ": "Tayikistán",
		"es-CL": "Tayikistán",
		"es-CO": "Tayikistán",
		"es-CR": "Tayikistán",
		"es-CU": "Tayikistán",
		"es-DO": "Tayikistán",
		"es-EC": "Tayikistán",
		"es-GT": "Tayikistán",
		"es-HN": "Tayikistán",
		"es-MX": "Tayikistán",
		"es-NI": "Tayikistán",
		"es-PA": "Tayikistán",
		"es-PE": "Tayikistán",
		"es-PR": "Tayikistán",
		"es-PY": "Tayikistán",
		"es-SV": "Tayikistán",
		"es-US": "Tayikistán",
		"es-UY": "Tayikistán",
		"es-VE": "Tayikistán",
		"fr-FR": "Tadjikistan",
		"fr-BE": "Tadjikistan",
		"fr-CH": "Tadjikistan",
		"fr-LU": "Tadjikistan",
		"fr-MC": "Tadjikistan",
		"fr-AD": "Tadjikistan",
		"fr-CA": "Tadjikistan",
		"it-IT": "Tagikistan",
		"it-CH": "Tagikistan",
		"it-SM": "Tagikistan",
		"it-VA": "Tagikistan",
		"de-DE": "Tadschikistan",
		"de-AT": "Tadschikistan",
		"de-CH": "Tadschikistan",
		"de-BE": "Tadschikistan",
		"de-LI": "Tadschikistan",
		"de-LU": "Tadschikistan",
		"nl-NL": "Tadzjikistan",
		"nl-BE": "Tadzjikistan",
		"sv-SE": "Tadzjikistan",
		"sv-FI": "Tadzjikistan",
		"da-DK": "Tadsjikistan",
		"nb-NO": "Tadsjikistan",
		"nn-NO": "Tadsjikistan",
		"fi-FI": "Tadžikistan",
		"is-IS": "Tadsíkistan",
		"fo-FO": "Tadsjikistan",
		"et-EE": "Tadžikistan",
		"lv-LV": "Tadžikistāna",
		"lt-LT": "Tadžikija",
		"pl-PL": "Tadżykistan",
		"cs-CZ": "Tádžikistán",
		"sk-SK": "Tadžikistan",
		"sl-SI": "Tadžikistan",
		"hr-HR": "Tadžikistan",
		"bs-BA": "Tadžikistan",
		"sr-RS": "Таџикистан",
		"sr-BA": "Таџикистан",
		"sr-ME": "Tadžikistan",
		"mk-MK": "Таџикистан",
		"bg-BG": "Таджикистан",
		"be-BY": "Таджыкістан",
		"uk-UA": "Таджикистан",
		"ru-RU": "Таджикистан",
		"el-GR": "Τατζικιστάν",
		"el-CY": "Τατζικιστάν",
		"ro-RO": "Tadjikistan",
		"ro-MD": "Tadjikistan",
		"hu-HU": "Tádzsikisztán",
		"sq-AL": "Taxhikistan",
		"sq-XK": "Taxhikistan",
		"mt-MT": "it-Taġikistan",
		"ga-IE": "an Táidsíceastáin",
		"cy-GB": "Tajicistan",
		"gd-GB": "Taidigeastàn",
		"lb-LU": "Tadschikistan",
		"ca-ES": "Tadjikistan",
		"ca-AD": "Tadjikistan",
		"ca-FR": "Tadjikistan",
		"ca-IT": "Tadjikistan",
		"eu-ES": "Tajikistan",
		"eu-FR": "Tajikistan",
		"gl-ES": "Taxiquistán",
		"tr-TR": "Tacikistan",
		"tr-CY": "Tacikistan"
	},
	"callingCode": "992",
	"phoneMasks": [
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[0-57-9]"
			]
		},
		{
			"mask": "### ## ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"44[02-479]|[34]7"
			]
		},
		{
			"mask": "#### # ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"3(?:[1245]|3[12])"
			]
		},
		{
			"mask": "###### # ##",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"331",
				"3317"
			]
		}
	]
} satisfies Country;
