import type { Country } from './types.js';

export const TKM = {
	"code": "TKM",
	"labels": {
		"pt-BR": "Turcomenistão",
		"pt-PT": "Turquemenistão",
		"es-ES": "Turkmenistán",
		"es-419": "Turkmenistán",
		"es-AR": "Turkmenistán",
		"es-BO": "Turkmenistán",
		"es-BR": "Turkmenistán",
		"es-BZ": "Turkmenistán",
		"es-CL": "Turkmenistán",
		"es-CO": "Turkmenistán",
		"es-CR": "Turkmenistán",
		"es-CU": "Turkmenistán",
		"es-DO": "Turkmenistán",
		"es-EC": "Turkmenistán",
		"es-GT": "Turkmenistán",
		"es-HN": "Turkmenistán",
		"es-MX": "Turkmenistán",
		"es-NI": "Turkmenistán",
		"es-PA": "Turkmenistán",
		"es-PE": "Turkmenistán",
		"es-PR": "Turkmenistán",
		"es-PY": "Turkmenistán",
		"es-SV": "Turkmenistán",
		"es-US": "Turkmenistán",
		"es-UY": "Turkmenistán",
		"es-VE": "Turkmenistán",
		"en-US": "Turkmenistan",
		"fr-FR": "Turkménistan",
		"fr-BE": "Turkménistan",
		"fr-CA": "Turkménistan",
		"fr-CH": "Turkménistan",
		"fr-LU": "Turkménistan",
		"fr-MC": "Turkménistan",
		"it-IT": "Turkmenistan",
		"it-CH": "Turkmenistan",
		"it-SM": "Turkmenistan",
		"it-VA": "Turkmenistan",
		"de-DE": "Turkmenistan",
		"de-AT": "Turkmenistan",
		"de-CH": "Turkmenistan",
		"de-BE": "Turkmenistan",
		"de-LI": "Turkmenistan",
		"de-LU": "Turkmenistan"
	},
	"callingCode": "993"
} satisfies Country;
