import type { Country } from './types.js';

export const TLS = {
	"code": "TLS",
	"labels": {
		"pt-BR": "Timor-Leste",
		"pt-PT": "Timor-Leste",
		"es-ES": "Timor-Leste",
		"es-419": "Timor Oriental",
		"es-AR": "Timor-Leste",
		"es-BO": "Timor-Leste",
		"es-BR": "Timor Oriental",
		"es-BZ": "Timor Oriental",
		"es-CL": "Timor-Leste",
		"es-CO": "Timor-Leste",
		"es-CR": "Timor-Leste",
		"es-CU": "Timor Oriental",
		"es-DO": "Timor-Leste",
		"es-EC": "Timor-Leste",
		"es-GT": "Timor-Leste",
		"es-HN": "Timor-Leste",
		"es-MX": "Timor Oriental",
		"es-NI": "Timor-Leste",
		"es-PA": "Timor-Leste",
		"es-PE": "Timor-Leste",
		"es-PR": "Timor Oriental",
		"es-PY": "Timor-Leste",
		"es-SV": "Timor Oriental",
		"es-US": "Timor Oriental",
		"es-UY": "Timor Oriental",
		"es-VE": "Timor-Leste",
		"en-US": "Timor-Leste",
		"fr-FR": "Timor oriental",
		"fr-BE": "Timor oriental",
		"fr-CA": "Timor-Leste",
		"fr-CH": "Timor oriental",
		"fr-LU": "Timor oriental",
		"fr-MC": "Timor oriental",
		"it-IT": "Timor Est",
		"it-CH": "Timor Est",
		"it-SM": "Timor Est",
		"it-VA": "Timor Est",
		"de-DE": "Timor-Leste",
		"de-AT": "Timor-Leste",
		"de-CH": "Osttimor",
		"de-BE": "Timor-Leste",
		"de-LI": "Timor-Leste",
		"de-LU": "Timor-Leste"
	}
} satisfies Country;
