import type { Country } from './types.js';

export const TUR = {
	"code": "TUR",
	"labels": {
		"pt-BR": "Turquia",
		"pt-PT": "Turquia",
		"qu-PE": "Turquía",
		"qu-BO": "Turquía",
		"qu-EC": "Turquía",
		"chr-US": "ᎬᏃ",
		"hi-IN": "तुर्किये",
		"bn-IN": "তুরস্ক",
		"bn-BD": "তুরস্ক",
		"ta-IN": "துருக்கியே",
		"ta-LK": "துருக்கியே",
		"ta-SG": "துருக்கியே",
		"ta-MY": "துருக்கியே",
		"te-IN": "తుర్కియె",
		"mr-IN": "तुर्किये",
		"gu-IN": "તુર્કિયે",
		"kn-IN": "ತುರ್ಕಿಯೆ",
		"ml-IN": "തുർക്കിയെ",
		"pa-IN": "ਤੁਰਕੀ",
		"ur-IN": "ترکیہ",
		"ur-PK": "ترکیہ",
		"or-IN": "ତୁର୍କୀ",
		"as-IN": "তুৰ্কিয়ে",
		"ne-IN": "तुर्किये",
		"ne-NP": "तुर्किये",
		"si-LK": "තුර්කිය",
		"kok-IN": "तुर्की",
		"ks-IN": "تُرکی",
		"brx-IN": "तुर्की",
		"mai-IN": "तुर्की",
		"dz-BT": "ཊཱར་ཀི",
		"ja-JP": "トルコ",
		"ko-KR": "튀르키예",
		"ko-KP": "튀르키예",
		"zh-CN": "土耳其",
		"zh-Hans-CN": "土耳其",
		"zh-Hant-TW": "土耳其",
		"zh-TW": "土耳其",
		"zh-HK": "土耳其",
		"zh-MO": "土耳其",
		"zh-SG": "土耳其",
		"yue-Hant-HK": "土耳其",
		"yue-Hans-CN": "土耳其",
		"mn-MN": "Турк",
		"ug-CN": "تۈركىيە",
		"th-TH": "ตุรกี",
		"lo-LA": "ເທີຄີ",
		"km-KH": "តួកគី",
		"my-MM": "တူရကီ",
		"vi-VN": "Thổ Nhĩ Kỳ",
		"id-ID": "Turki",
		"ms-MY": "Turkiye",
		"ms-SG": "Turkiye",
		"ms-BN": "Turkiye",
		"jv-ID": "Turki",
		"fil-PH": "Türkiye",
		"ceb-PH": "Turkiye",
		"ka-GE": "თურქეთი",
		"hy-AM": "Թուրքիա",
		"az-AZ": "Türkiyə",
		"az-Cyrl-AZ": "Түркијә",
		"kk-KZ": "Түркия",
		"ky-KG": "Түркия",
		"uz-UZ": "Turkiya",
		"tg-TJ": "Туркия",
		"tk-TM": "Türkiýe",
		"fa-IR": "ترکیه",
		"fa-AF": "ترکیه",
		"ps-AF": "ترکي",
		"ps-PK": "ترکي",
		"he-IL": "טורקיה",
		"ar-SA": "تركيا",
		"ar-AE": "تركيا",
		"ar-QA": "تركيا",
		"ar-BH": "تركيا",
		"ar-KW": "تركيا",
		"ar-OM": "تركيا",
		"ar-YE": "تركيا",
		"ar-IQ": "تركيا",
		"ar-JO": "تركيا",
		"ar-LB": "تركيا",
		"ar-SY": "تركيا",
		"ar-PS": "تركيا",
		"en-US": "Türkiye",
		"en-GB": "Türkiye",
		"en-IE": "Türkiye",
		"en-MT": "Türkiye",
		"en-GI": "Türkiye",
		"en-CY": "Türkiye",
		"en-JE": "Türkiye",
		"en-GG": "Türkiye",
		"en-IM": "Türkiye",
		"en-CA": "Türkiye",
		"en-AU": "Türkiye",
		"en-NZ": "Türkiye",
		"en-ZA": "Türkiye",
		"en-IN": "Türkiye",
		"en-SG": "Türkiye",
		"pt-AO": "Turquia",
		"pt-MZ": "Turquia",
		"pt-CV": "Turquia",
		"pt-GW": "Turquia",
		"pt-ST": "Turquia",
		"pt-TL": "Turquia",
		"pt-MO": "Turquia",
		"es-ES": "Turquía",
		"es-419": "Turquía",
		"es-AD": "Turquía",
		"es-GI": "Turquía",
		"es-AR": "Turquía",
		"es-BO": "Turquía",
		"es-BR": "Turquía",
		"es-BZ": "Turquía",
		"es-CL": "Turquía",
		"es-CO": "Turquía",
		"es-CR": "Turquía",
		"es-CU": "Turquía",
		"es-DO": "Turquía",
		"es-EC": "Turquía",
		"es-GT": "Turquía",
		"es-HN": "Turquía",
		"es-MX": "Turquía",
		"es-NI": "Turquía",
		"es-PA": "Turquía",
		"es-PE": "Turquía",
		"es-PR": "Turquía",
		"es-PY": "Turquía",
		"es-SV": "Turquía",
		"es-US": "Turquía",
		"es-UY": "Turquía",
		"es-VE": "Turquía",
		"fr-FR": "Turquie",
		"fr-BE": "Turquie",
		"fr-CH": "Turquie",
		"fr-LU": "Turquie",
		"fr-MC": "Turquie",
		"fr-AD": "Turquie",
		"fr-CA": "Turquie",
		"it-IT": "Turchia",
		"it-CH": "Turchia",
		"it-SM": "Turchia",
		"it-VA": "Turchia",
		"de-DE": "Türkei",
		"de-AT": "Türkei",
		"de-CH": "Türkei",
		"de-BE": "Türkei",
		"de-LI": "Türkei",
		"de-LU": "Türkei",
		"nl-NL": "Turkije",
		"nl-BE": "Turkije",
		"sv-SE": "Turkiet",
		"sv-FI": "Turkiet",
		"da-DK": "Tyrkiet",
		"nb-NO": "Tyrkia",
		"nn-NO": "Tyrkia",
		"fi-FI": "Turkki",
		"is-IS": "Tyrkland",
		"fo-FO": "Turkaland",
		"et-EE": "Türgi",
		"lv-LV": "Turcija",
		"lt-LT": "Turkija",
		"pl-PL": "Turcja",
		"cs-CZ": "Turecko",
		"sk-SK": "Turecko",
		"sl-SI": "Turčija",
		"hr-HR": "Turska",
		"bs-BA": "Turska",
		"sr-RS": "Турска",
		"sr-BA": "Турска",
		"sr-ME": "Turska",
		"mk-MK": "Турција",
		"bg-BG": "Турция",
		"be-BY": "Турцыя",
		"uk-UA": "Туреччина",
		"ru-RU": "Турция",
		"el-GR": "Τουρκία",
		"el-CY": "Τουρκία",
		"ro-RO": "Turcia",
		"ro-MD": "Turcia",
		"hu-HU": "Törökország",
		"sq-AL": "Turqi",
		"sq-XK": "Turqi",
		"mt-MT": "it-Turkija",
		"ga-IE": "an Tuirc",
		"cy-GB": "Twrci",
		"gd-GB": "An Tuirc",
		"lb-LU": "Tierkei",
		"ca-ES": "Turquia",
		"ca-AD": "Turquia",
		"ca-FR": "Turquia",
		"ca-IT": "Turquia",
		"eu-ES": "Turkia",
		"eu-FR": "Turkia",
		"gl-ES": "Turquía",
		"tr-TR": "Türkiye",
		"tr-CY": "Türkiye"
	},
	"callingCode": "90",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7
		},
		{
			"mask": "### ### ## ##",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"5(?:[0-59]|61)",
				"5(?:[0-59]|61[06])",
				"5(?:[0-59]|61[06]1)"
			]
		},
		{
			"mask": "### ### ## ##",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[24][1-8]|3[1-9]"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"512|8[01589]|90"
			]
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12
		},
		{
			"mask": "### ### #######",
			"minLength": 13,
			"maxLength": 13,
			"leadingDigits": [
				"80"
			]
		}
	]
} satisfies Country;
