import type { Country } from './types.js';

export const TUR = {
	"code": "TUR",
	"labels": {
		"pt-BR": "Turquia",
		"pt-PT": "Turquia",
		"es-ES": "Turquía",
		"es-419": "Turquía",
		"es-AR": "Turquía",
		"es-BO": "Turquía",
		"es-BR": "Turquía",
		"es-BZ": "Turquía",
		"es-CL": "Turquía",
		"es-CO": "Turquía",
		"es-CR": "Turquía",
		"es-CU": "Turquía",
		"es-DO": "Turquía",
		"es-EC": "Turquía",
		"es-GT": "Turquía",
		"es-HN": "Turquía",
		"es-MX": "Turquía",
		"es-NI": "Turquía",
		"es-PA": "Turquía",
		"es-PE": "Turquía",
		"es-PR": "Turquía",
		"es-PY": "Turquía",
		"es-SV": "Turquía",
		"es-US": "Turquía",
		"es-UY": "Turquía",
		"es-VE": "Turquía",
		"en-US": "Türkiye",
		"fr-FR": "Turquie",
		"fr-BE": "Turquie",
		"fr-CA": "Turquie",
		"fr-CH": "Turquie",
		"fr-LU": "Turquie",
		"fr-MC": "Turquie",
		"it-IT": "Turchia",
		"it-CH": "Turchia",
		"it-SM": "Turchia",
		"it-VA": "Turchia",
		"de-DE": "Türkei",
		"de-AT": "Türkei",
		"de-CH": "Türkei",
		"de-BE": "Türkei",
		"de-LI": "Türkei",
		"de-LU": "Türkei"
	},
	"callingCode": "90"
} satisfies Country;
