import type { Country } from './types.js';

export const TUV = {
	"code": "TUV",
	"labels": {
		"pt-BR": "Tuvalu",
		"pt-PT": "Tuvalu",
		"es-ES": "Tuvalu",
		"es-419": "Tuvalu",
		"es-AR": "Tuvalu",
		"es-BO": "Tuvalu",
		"es-BR": "Tuvalu",
		"es-BZ": "Tuvalu",
		"es-CL": "Tuvalu",
		"es-CO": "Tuvalu",
		"es-CR": "Tuvalu",
		"es-CU": "Tuvalu",
		"es-DO": "Tuvalu",
		"es-EC": "Tuvalu",
		"es-GT": "Tuvalu",
		"es-HN": "Tuvalu",
		"es-MX": "Tuvalu",
		"es-NI": "Tuvalu",
		"es-PA": "Tuvalu",
		"es-PE": "Tuvalu",
		"es-PR": "Tuvalu",
		"es-PY": "Tuvalu",
		"es-SV": "Tuvalu",
		"es-US": "Tuvalu",
		"es-UY": "Tuvalu",
		"es-VE": "Tuvalu",
		"en-US": "Tuvalu",
		"fr-FR": "Tuvalu",
		"fr-BE": "Tuvalu",
		"fr-CA": "Tuvalu",
		"fr-CH": "Tuvalu",
		"fr-LU": "Tuvalu",
		"fr-MC": "Tuvalu",
		"it-IT": "Tuvalu",
		"it-CH": "Tuvalu",
		"it-SM": "Tuvalu",
		"it-VA": "Tuvalu",
		"de-DE": "Tuvalu",
		"de-AT": "Tuvalu",
		"de-CH": "Tuvalu",
		"de-BE": "Tuvalu",
		"de-LI": "Tuvalu",
		"de-LU": "Tuvalu"
	}
} satisfies Country;
