import type { Country } from './types.js';

export const TWN = {
	"code": "TWN",
	"labels": {
		"pt-BR": "Taiwan",
		"pt-PT": "Taiwan",
		"es-ES": "Taiwán",
		"es-419": "Taiwán",
		"es-AR": "Taiwán",
		"es-BO": "Taiwán",
		"es-BR": "Taiwán",
		"es-BZ": "Taiwán",
		"es-CL": "Taiwán",
		"es-CO": "Taiwán",
		"es-CR": "Taiwán",
		"es-CU": "Taiwán",
		"es-DO": "Taiwán",
		"es-EC": "Taiwán",
		"es-GT": "Taiwán",
		"es-HN": "Taiwán",
		"es-MX": "Taiwán",
		"es-NI": "Taiwán",
		"es-PA": "Taiwán",
		"es-PE": "Taiwán",
		"es-PR": "Taiwán",
		"es-PY": "Taiwán",
		"es-SV": "Taiwán",
		"es-US": "Taiwán",
		"es-UY": "Taiwán",
		"es-VE": "Taiwán",
		"en-US": "Taiwan",
		"fr-FR": "Taïwan",
		"fr-BE": "Taïwan",
		"fr-CA": "Taïwan",
		"fr-CH": "Taïwan",
		"fr-LU": "Taïwan",
		"fr-MC": "Taïwan",
		"it-IT": "Taiwan",
		"it-CH": "Taiwan",
		"it-SM": "Taiwan",
		"it-VA": "Taiwan",
		"de-DE": "Taiwan",
		"de-AT": "Taiwan",
		"de-CH": "Taiwan",
		"de-BE": "Taiwan",
		"de-LI": "Taiwan",
		"de-LU": "Taiwan"
	},
	"callingCode": "886"
} satisfies Country;
