import type { Country } from './types.js';

export const TZA = {
	"code": "TZA",
	"labels": {
		"pt-BR": "Tanzânia",
		"pt-PT": "Tanzânia",
		"qu-PE": "Tanzania",
		"qu-BO": "Tanzania",
		"qu-EC": "Tanzania",
		"chr-US": "ᏖᏂᏏᏂᏯ",
		"hi-IN": "तंज़ानिया",
		"bn-IN": "তাঞ্জানিয়া",
		"bn-BD": "তাঞ্জানিয়া",
		"ta-IN": "தான்சானியா",
		"ta-LK": "தான்சானியா",
		"ta-SG": "தான்சானியா",
		"ta-MY": "தான்சானியா",
		"te-IN": "టాంజానియా",
		"mr-IN": "टांझानिया",
		"gu-IN": "તાંઝાનિયા",
		"kn-IN": "ತಾಂಜೇನಿಯಾ",
		"ml-IN": "ടാൻസാനിയ",
		"pa-IN": "ਤਨਜ਼ਾਨੀਆ",
		"ur-IN": "تنزانیہ",
		"ur-PK": "تنزانیہ",
		"or-IN": "ତାଞ୍ଜାନିଆ",
		"as-IN": "তাঞ্জানিয়া",
		"ne-IN": "तान्जानिया",
		"ne-NP": "तान्जानिया",
		"si-LK": "ටැන්සානියාව",
		"kok-IN": "तांझानिया",
		"ks-IN": "تَنجانِیا",
		"brx-IN": "तान्जानिया",
		"mai-IN": "तंजानिया",
		"dz-BT": "ཊཱན་ཛཱ་ནི་ཡ",
		"ja-JP": "タンザニア",
		"ko-KR": "탄자니아",
		"ko-KP": "탄자니아",
		"zh-CN": "坦桑尼亚",
		"zh-Hans-CN": "坦桑尼亚",
		"zh-Hant-TW": "坦尚尼亞",
		"zh-TW": "坦尚尼亞",
		"zh-HK": "坦桑尼亞",
		"zh-MO": "坦桑尼亞",
		"zh-SG": "坦桑尼亚",
		"yue-Hant-HK": "坦尚尼亞",
		"yue-Hans-CN": "坦尚尼亚",
		"mn-MN": "Танзани",
		"ug-CN": "تانزانىيە",
		"th-TH": "แทนซาเนีย",
		"lo-LA": "ທານຊາເນຍ",
		"km-KH": "តង់សានី",
		"my-MM": "တန်ဇန်းနီးယား",
		"vi-VN": "Tanzania",
		"id-ID": "Tanzania",
		"ms-MY": "Tanzania",
		"ms-SG": "Tanzania",
		"ms-BN": "Tanzania",
		"jv-ID": "Tansania",
		"fil-PH": "Tanzania",
		"ceb-PH": "Tanzania",
		"ka-GE": "ტანზანია",
		"hy-AM": "Տանզանիա",
		"az-AZ": "Tanzaniya",
		"az-Cyrl-AZ": "Танзанија",
		"kk-KZ": "Танзания",
		"ky-KG": "Танзания",
		"uz-UZ": "Tanzaniya",
		"tg-TJ": "Танзания",
		"tk-TM": "Tanzaniýa",
		"fa-IR": "تانزانیا",
		"fa-AF": "تانزانیا",
		"ps-AF": "تنزانیا",
		"ps-PK": "تنزانیا",
		"he-IL": "טנזניה",
		"ar-SA": "تنزانيا",
		"ar-AE": "تنزانيا",
		"ar-QA": "تنزانيا",
		"ar-BH": "تنزانيا",
		"ar-KW": "تنزانيا",
		"ar-OM": "تنزانيا",
		"ar-YE": "تنزانيا",
		"ar-IQ": "تنزانيا",
		"ar-JO": "تنزانيا",
		"ar-LB": "تنزانيا",
		"ar-SY": "تنزانيا",
		"ar-PS": "تنزانيا",
		"en-US": "Tanzania",
		"en-GB": "Tanzania",
		"en-IE": "Tanzania",
		"en-MT": "Tanzania",
		"en-GI": "Tanzania",
		"en-CY": "Tanzania",
		"en-JE": "Tanzania",
		"en-GG": "Tanzania",
		"en-IM": "Tanzania",
		"en-CA": "Tanzania",
		"en-AU": "Tanzania",
		"en-NZ": "Tanzania",
		"en-ZA": "Tanzania",
		"en-IN": "Tanzania",
		"en-SG": "Tanzania",
		"pt-AO": "Tanzânia",
		"pt-MZ": "Tanzânia",
		"pt-CV": "Tanzânia",
		"pt-GW": "Tanzânia",
		"pt-ST": "Tanzânia",
		"pt-TL": "Tanzânia",
		"pt-MO": "Tanzânia",
		"es-ES": "Tanzania",
		"es-419": "Tanzania",
		"es-AD": "Tanzania",
		"es-GI": "Tanzania",
		"es-AR": "Tanzania",
		"es-BO": "Tanzania",
		"es-BR": "Tanzania",
		"es-BZ": "Tanzania",
		"es-CL": "Tanzania",
		"es-CO": "Tanzania",
		"es-CR": "Tanzania",
		"es-CU": "Tanzania",
		"es-DO": "Tanzania",
		"es-EC": "Tanzania",
		"es-GT": "Tanzania",
		"es-HN": "Tanzania",
		"es-MX": "Tanzania",
		"es-NI": "Tanzania",
		"es-PA": "Tanzania",
		"es-PE": "Tanzania",
		"es-PR": "Tanzania",
		"es-PY": "Tanzania",
		"es-SV": "Tanzania",
		"es-US": "Tanzania",
		"es-UY": "Tanzania",
		"es-VE": "Tanzania",
		"fr-FR": "Tanzanie",
		"fr-BE": "Tanzanie",
		"fr-CH": "Tanzanie",
		"fr-LU": "Tanzanie",
		"fr-MC": "Tanzanie",
		"fr-AD": "Tanzanie",
		"fr-CA": "Tanzanie",
		"it-IT": "Tanzania",
		"it-CH": "Tanzania",
		"it-SM": "Tanzania",
		"it-VA": "Tanzania",
		"de-DE": "Tansania",
		"de-AT": "Tansania",
		"de-CH": "Tansania",
		"de-BE": "Tansania",
		"de-LI": "Tansania",
		"de-LU": "Tansania",
		"nl-NL": "Tanzania",
		"nl-BE": "Tanzania",
		"sv-SE": "Tanzania",
		"sv-FI": "Tanzania",
		"da-DK": "Tanzania",
		"nb-NO": "Tanzania",
		"nn-NO": "Tanzania",
		"fi-FI": "Tansania",
		"is-IS": "Tansanía",
		"fo-FO": "Tansania",
		"et-EE": "Tansaania",
		"lv-LV": "Tanzānija",
		"lt-LT": "Tanzanija",
		"pl-PL": "Tanzania",
		"cs-CZ": "Tanzanie",
		"sk-SK": "Tanzánia",
		"sl-SI": "Tanzanija",
		"hr-HR": "Tanzanija",
		"bs-BA": "Tanzanija",
		"sr-RS": "Танзанија",
		"sr-BA": "Танзанија",
		"sr-ME": "Tanzanija",
		"mk-MK": "Танзанија",
		"bg-BG": "Танзания",
		"be-BY": "Танзанія",
		"uk-UA": "Танзанія",
		"ru-RU": "Танзания",
		"el-GR": "Τανζανία",
		"el-CY": "Τανζανία",
		"ro-RO": "Tanzania",
		"ro-MD": "Tanzania",
		"hu-HU": "Tanzánia",
		"sq-AL": "Tanzani",
		"sq-XK": "Tanzani",
		"mt-MT": "it-Tanzanija",
		"ga-IE": "an Tansáin",
		"cy-GB": "Tanzania",
		"gd-GB": "An Tansan",
		"lb-LU": "Tansania",
		"ca-ES": "Tanzània",
		"ca-AD": "Tanzània",
		"ca-FR": "Tanzània",
		"ca-IT": "Tanzània",
		"eu-ES": "Tanzania",
		"eu-FR": "Tanzania",
		"gl-ES": "Tanzania",
		"tr-TR": "Tanzanya",
		"tr-CY": "Tanzanya"
	},
	"callingCode": "255",
	"phoneMasks": [
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[24]"
			]
		},
		{
			"mask": "## #######",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"5"
			]
		},
		{
			"mask": "### ## ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[89]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[67]"
			]
		}
	]
} satisfies Country;
