import type { Country } from './types.js';

export const TZA = {
	"code": "TZA",
	"labels": {
		"pt-BR": "Tanzânia",
		"pt-PT": "Tanzânia",
		"es-ES": "Tanzania",
		"es-419": "Tanzania",
		"es-AR": "Tanzania",
		"es-BO": "Tanzania",
		"es-BR": "Tanzania",
		"es-BZ": "Tanzania",
		"es-CL": "Tanzania",
		"es-CO": "Tanzania",
		"es-CR": "Tanzania",
		"es-CU": "Tanzania",
		"es-DO": "Tanzania",
		"es-EC": "Tanzania",
		"es-GT": "Tanzania",
		"es-HN": "Tanzania",
		"es-MX": "Tanzania",
		"es-NI": "Tanzania",
		"es-PA": "Tanzania",
		"es-PE": "Tanzania",
		"es-PR": "Tanzania",
		"es-PY": "Tanzania",
		"es-SV": "Tanzania",
		"es-US": "Tanzania",
		"es-UY": "Tanzania",
		"es-VE": "Tanzania",
		"en-US": "Tanzania",
		"fr-FR": "Tanzanie",
		"fr-BE": "Tanzanie",
		"fr-CA": "Tanzanie",
		"fr-CH": "Tanzanie",
		"fr-LU": "Tanzanie",
		"fr-MC": "Tanzanie",
		"it-IT": "Tanzania",
		"it-CH": "Tanzania",
		"it-SM": "Tanzania",
		"it-VA": "Tanzania",
		"de-DE": "Tansania",
		"de-AT": "Tansania",
		"de-CH": "Tansania",
		"de-BE": "Tansania",
		"de-LI": "Tansania",
		"de-LU": "Tansania"
	},
	"callingCode": "255"
} satisfies Country;
