import type { Country } from './types.js';

export const UGA = {
	"code": "UGA",
	"labels": {
		"pt-BR": "Uganda",
		"pt-PT": "Uganda",
		"es-ES": "Uganda",
		"es-419": "Uganda",
		"es-AR": "Uganda",
		"es-BO": "Uganda",
		"es-BR": "Uganda",
		"es-BZ": "Uganda",
		"es-CL": "Uganda",
		"es-CO": "Uganda",
		"es-CR": "Uganda",
		"es-CU": "Uganda",
		"es-DO": "Uganda",
		"es-EC": "Uganda",
		"es-GT": "Uganda",
		"es-HN": "Uganda",
		"es-MX": "Uganda",
		"es-NI": "Uganda",
		"es-PA": "Uganda",
		"es-PE": "Uganda",
		"es-PR": "Uganda",
		"es-PY": "Uganda",
		"es-SV": "Uganda",
		"es-US": "Uganda",
		"es-UY": "Uganda",
		"es-VE": "Uganda",
		"en-US": "Uganda",
		"fr-FR": "Ouganda",
		"fr-BE": "Ouganda",
		"fr-CA": "Ouganda",
		"fr-CH": "Ouganda",
		"fr-LU": "Ouganda",
		"fr-MC": "Ouganda",
		"it-IT": "Uganda",
		"it-CH": "Uganda",
		"it-SM": "Uganda",
		"it-VA": "Uganda",
		"de-DE": "Uganda",
		"de-AT": "Uganda",
		"de-CH": "Uganda",
		"de-BE": "Uganda",
		"de-LI": "Uganda",
		"de-LU": "Uganda"
	},
	"callingCode": "256"
} satisfies Country;
