import type { Country } from './types.js';

export const UKR = {
	"code": "UKR",
	"labels": {
		"pt-BR": "Ucrânia",
		"pt-PT": "Ucrânia",
		"qu-PE": "Ucrania",
		"qu-BO": "Ucrania",
		"qu-EC": "Ucrania",
		"chr-US": "ᏳᎧᎴᏂ",
		"hi-IN": "यूक्रेन",
		"bn-IN": "ইউক্রেন",
		"bn-BD": "ইউক্রেন",
		"ta-IN": "உக்ரைன்",
		"ta-LK": "உக்ரைன்",
		"ta-SG": "உக்ரைன்",
		"ta-MY": "உக்ரைன்",
		"te-IN": "ఉక్రెయిన్",
		"mr-IN": "युक्रेन",
		"gu-IN": "યુક્રેન",
		"kn-IN": "ಉಕ್ರೈನ್",
		"ml-IN": "ഉക്രെയ്‌ൻ",
		"pa-IN": "ਯੂਕਰੇਨ",
		"ur-IN": "یوکرین",
		"ur-PK": "یوکرین",
		"or-IN": "ୟୁକ୍ରେନ୍",
		"as-IN": "ইউক্ৰেইন",
		"ne-IN": "युक्रेन",
		"ne-NP": "युक्रेन",
		"si-LK": "යුක්රේනය",
		"kok-IN": "युक्रेन",
		"ks-IN": "یوٗرِکین",
		"brx-IN": "यूक्रेन",
		"mai-IN": "यूक्रेन",
		"dz-BT": "ཡུ་ཀརེན",
		"ja-JP": "ウクライナ",
		"ko-KR": "우크라이나",
		"ko-KP": "우크라이나",
		"zh-CN": "乌克兰",
		"zh-Hans-CN": "乌克兰",
		"zh-Hant-TW": "烏克蘭",
		"zh-TW": "烏克蘭",
		"zh-HK": "烏克蘭",
		"zh-MO": "烏克蘭",
		"zh-SG": "乌克兰",
		"yue-Hant-HK": "烏克蘭",
		"yue-Hans-CN": "乌克兰",
		"mn-MN": "Украин",
		"ug-CN": "ئۇكرائىنا",
		"th-TH": "ยูเครน",
		"lo-LA": "ຢູເຄຣນ",
		"km-KH": "អ៊ុយក្រែន",
		"my-MM": "ယူကရိန်း",
		"vi-VN": "Ukraina",
		"id-ID": "Ukraina",
		"ms-MY": "Ukraine",
		"ms-SG": "Ukraine",
		"ms-BN": "Ukraine",
		"jv-ID": "Ukrania",
		"fil-PH": "Ukraine",
		"ceb-PH": "Ukraine",
		"ka-GE": "უკრაინა",
		"hy-AM": "Ուկրաինա",
		"az-AZ": "Ukrayna",
		"az-Cyrl-AZ": "Украјна",
		"kk-KZ": "Украина",
		"ky-KG": "Украина",
		"uz-UZ": "Ukraina",
		"tg-TJ": "Украина",
		"tk-TM": "Ukraina",
		"fa-IR": "اوکراین",
		"fa-AF": "اوکراین",
		"ps-AF": "اوکراین",
		"ps-PK": "اوکراین",
		"he-IL": "אוקראינה",
		"ar-SA": "أوكرانيا",
		"ar-AE": "أوكرانيا",
		"ar-QA": "أوكرانيا",
		"ar-BH": "أوكرانيا",
		"ar-KW": "أوكرانيا",
		"ar-OM": "أوكرانيا",
		"ar-YE": "أوكرانيا",
		"ar-IQ": "أوكرانيا",
		"ar-JO": "أوكرانيا",
		"ar-LB": "أوكرانيا",
		"ar-SY": "أوكرانيا",
		"ar-PS": "أوكرانيا",
		"en-US": "Ukraine",
		"en-GB": "Ukraine",
		"en-IE": "Ukraine",
		"en-MT": "Ukraine",
		"en-GI": "Ukraine",
		"en-CY": "Ukraine",
		"en-JE": "Ukraine",
		"en-GG": "Ukraine",
		"en-IM": "Ukraine",
		"en-CA": "Ukraine",
		"en-AU": "Ukraine",
		"en-NZ": "Ukraine",
		"en-ZA": "Ukraine",
		"en-IN": "Ukraine",
		"en-SG": "Ukraine",
		"pt-AO": "Ucrânia",
		"pt-MZ": "Ucrânia",
		"pt-CV": "Ucrânia",
		"pt-GW": "Ucrânia",
		"pt-ST": "Ucrânia",
		"pt-TL": "Ucrânia",
		"pt-MO": "Ucrânia",
		"es-ES": "Ucrania",
		"es-419": "Ucrania",
		"es-AD": "Ucrania",
		"es-GI": "Ucrania",
		"es-AR": "Ucrania",
		"es-BO": "Ucrania",
		"es-BR": "Ucrania",
		"es-BZ": "Ucrania",
		"es-CL": "Ucrania",
		"es-CO": "Ucrania",
		"es-CR": "Ucrania",
		"es-CU": "Ucrania",
		"es-DO": "Ucrania",
		"es-EC": "Ucrania",
		"es-GT": "Ucrania",
		"es-HN": "Ucrania",
		"es-MX": "Ucrania",
		"es-NI": "Ucrania",
		"es-PA": "Ucrania",
		"es-PE": "Ucrania",
		"es-PR": "Ucrania",
		"es-PY": "Ucrania",
		"es-SV": "Ucrania",
		"es-US": "Ucrania",
		"es-UY": "Ucrania",
		"es-VE": "Ucrania",
		"fr-FR": "Ukraine",
		"fr-BE": "Ukraine",
		"fr-CH": "Ukraine",
		"fr-LU": "Ukraine",
		"fr-MC": "Ukraine",
		"fr-AD": "Ukraine",
		"fr-CA": "Ukraine",
		"it-IT": "Ucraina",
		"it-CH": "Ucraina",
		"it-SM": "Ucraina",
		"it-VA": "Ucraina",
		"de-DE": "Ukraine",
		"de-AT": "Ukraine",
		"de-CH": "Ukraine",
		"de-BE": "Ukraine",
		"de-LI": "Ukraine",
		"de-LU": "Ukraine",
		"nl-NL": "Oekraïne",
		"nl-BE": "Oekraïne",
		"sv-SE": "Ukraina",
		"sv-FI": "Ukraina",
		"da-DK": "Ukraine",
		"nb-NO": "Ukraina",
		"nn-NO": "Ukraina",
		"fi-FI": "Ukraina",
		"is-IS": "Úkraína",
		"fo-FO": "Ukraina",
		"et-EE": "Ukraina",
		"lv-LV": "Ukraina",
		"lt-LT": "Ukraina",
		"pl-PL": "Ukraina",
		"cs-CZ": "Ukrajina",
		"sk-SK": "Ukrajina",
		"sl-SI": "Ukrajina",
		"hr-HR": "Ukrajina",
		"bs-BA": "Ukrajina",
		"sr-RS": "Украјина",
		"sr-BA": "Украјина",
		"sr-ME": "Ukrajina",
		"mk-MK": "Украина",
		"bg-BG": "Украйна",
		"be-BY": "Украіна",
		"uk-UA": "Україна",
		"ru-RU": "Украина",
		"el-GR": "Ουκρανία",
		"el-CY": "Ουκρανία",
		"ro-RO": "Ucraina",
		"ro-MD": "Ucraina",
		"hu-HU": "Ukrajna",
		"sq-AL": "Ukrainë",
		"sq-XK": "Ukrainë",
		"mt-MT": "l-Ukrajna",
		"ga-IE": "an Úcráin",
		"cy-GB": "Wcráin",
		"gd-GB": "An Ucràin",
		"lb-LU": "Ukrain",
		"ca-ES": "Ucraïna",
		"ca-AD": "Ucraïna",
		"ca-FR": "Ucraïna",
		"ca-IT": "Ucraïna",
		"eu-ES": "Ukraina",
		"eu-FR": "Ukraina",
		"gl-ES": "Ucraína",
		"tr-TR": "Ukrayna",
		"tr-CY": "Ukrayna"
	},
	"callingCode": "380",
	"phoneMasks": [
		{
			"mask": "## ### ####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"[3-7]|89|9[1-9]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"6[12][29]|(?:3[1-8]|4[136-8]|5[12457]|6[49])2|(?:56|65)[24]",
				"6[12][29]|(?:35|4[1378]|5[12457]|6[49])2|(?:56|65)[24]|(?:3[1-46-8]|46)2[013-9]"
			]
		},
		{
			"mask": "#### #####",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"3[1-8]|4(?:[1367]|[45][6-9]|8[4-6])|5(?:[1-5]|6[0135689]|7[4-6])|6(?:[12][3-7]|[459])",
				"3[1-8]|4(?:[1367]|[45][6-9]|8[4-6])|5(?:[1-5]|6(?:[015689]|3[02389])|7[4-6])|6(?:[12][3-7]|[459])"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[89]"
			]
		}
	]
} satisfies Country;
