import type { Country } from './types.js';

export const UKR = {
	"code": "UKR",
	"labels": {
		"pt-BR": "Ucrânia",
		"pt-PT": "Ucrânia",
		"es-ES": "Ucrania",
		"es-419": "Ucrania",
		"es-AR": "Ucrania",
		"es-BO": "Ucrania",
		"es-BR": "Ucrania",
		"es-BZ": "Ucrania",
		"es-CL": "Ucrania",
		"es-CO": "Ucrania",
		"es-CR": "Ucrania",
		"es-CU": "Ucrania",
		"es-DO": "Ucrania",
		"es-EC": "Ucrania",
		"es-GT": "Ucrania",
		"es-HN": "Ucrania",
		"es-MX": "Ucrania",
		"es-NI": "Ucrania",
		"es-PA": "Ucrania",
		"es-PE": "Ucrania",
		"es-PR": "Ucrania",
		"es-PY": "Ucrania",
		"es-SV": "Ucrania",
		"es-US": "Ucrania",
		"es-UY": "Ucrania",
		"es-VE": "Ucrania",
		"en-US": "Ukraine",
		"fr-FR": "Ukraine",
		"fr-BE": "Ukraine",
		"fr-CA": "Ukraine",
		"fr-CH": "Ukraine",
		"fr-LU": "Ukraine",
		"fr-MC": "Ukraine",
		"it-IT": "Ucraina",
		"it-CH": "Ucraina",
		"it-SM": "Ucraina",
		"it-VA": "Ucraina",
		"de-DE": "Ukraine",
		"de-AT": "Ukraine",
		"de-CH": "Ukraine",
		"de-BE": "Ukraine",
		"de-LI": "Ukraine",
		"de-LU": "Ukraine"
	}
} satisfies Country;
