import type { Country } from './types.js';

export const UMI = {
	"code": "UMI",
	"labels": {
		"pt-BR": "Ilhas Menores Distantes dos EUA",
		"pt-PT": "Ilhas Menores Afastadas dos EUA",
		"es-ES": "Islas menores alejadas de EE. UU.",
		"es-419": "Islas Ultramarinas de EE.UU.",
		"es-AR": "Islas menores alejadas de EE. UU.",
		"es-BO": "Islas menores alejadas de EE. UU.",
		"es-BR": "Islas Ultramarinas de EE.UU.",
		"es-BZ": "Islas Ultramarinas de EE.UU.",
		"es-CL": "Islas menores alejadas de EE. UU.",
		"es-CO": "Islas menores alejadas de EE. UU.",
		"es-CR": "Islas menores alejadas de EE. UU.",
		"es-CU": "Islas Ultramarinas de EE.UU.",
		"es-DO": "Islas menores alejadas de EE. UU.",
		"es-EC": "Islas menores alejadas de EE. UU.",
		"es-GT": "Islas menores alejadas de EE. UU.",
		"es-HN": "Islas menores alejadas de EE. UU.",
		"es-MX": "Islas menores alejadas de EE. UU.",
		"es-NI": "Islas menores alejadas de EE. UU.",
		"es-PA": "Islas menores alejadas de EE. UU.",
		"es-PE": "Islas menores alejadas de EE. UU.",
		"es-PR": "Islas menores alejadas de EE. UU.",
		"es-PY": "Islas menores alejadas de EE. UU.",
		"es-SV": "Islas menores alejadas de EE. UU.",
		"es-US": "Islas menores alejadas de EE. UU.",
		"es-UY": "Islas Ultramarinas de EE.UU.",
		"es-VE": "Islas menores alejadas de EE. UU.",
		"en-US": "U.S. Outlying Islands",
		"fr-FR": "Îles mineures éloignées des États-Unis",
		"fr-BE": "Îles mineures éloignées des États-Unis",
		"fr-CA": "îles mineures éloignées des États-Unis",
		"fr-CH": "Îles mineures éloignées des États-Unis",
		"fr-LU": "Îles mineures éloignées des États-Unis",
		"fr-MC": "Îles mineures éloignées des États-Unis",
		"it-IT": "Isole Minori Esterne degli Stati Uniti",
		"it-CH": "Isole Minori Esterne degli Stati Uniti",
		"it-SM": "Isole Minori Esterne degli Stati Uniti",
		"it-VA": "Isole Minori Esterne degli Stati Uniti",
		"de-DE": "Amerikanische Überseeinseln",
		"de-AT": "Amerikanische Überseeinseln",
		"de-CH": "Amerikanische Überseeinseln",
		"de-BE": "Amerikanische Überseeinseln",
		"de-LI": "Amerikanische Überseeinseln",
		"de-LU": "Amerikanische Überseeinseln"
	},
	"callingCode": "268"
} satisfies Country;
