import type { Country } from './types.js';

export const UMI = {
	"code": "UMI",
	"labels": {
		"pt-BR": "Ilhas Menores Distantes dos EUA",
		"pt-PT": "Ilhas Menores Afastadas dos EUA",
		"qu-PE": "Islas menores alejadas de los EE.UU.",
		"qu-BO": "Islas menores alejadas de los EE.UU.",
		"qu-EC": "Islas menores alejadas de los EE.UU.",
		"chr-US": "U.S. ᎠᏍᏛ ᏚᎦᏚᏛᎢ",
		"hi-IN": "यू॰एस॰ आउटलाइंग द्वीपसमूह",
		"bn-IN": "মার্কিন যুক্তরাষ্ট্রের দূরবর্তী দ্বীপপুঞ্জ",
		"bn-BD": "যুক্তরাষ্ট্রের পার্শ্ববর্তী দ্বীপপুঞ্জ",
		"ta-IN": "யூ.எஸ். வெளிப்புறத் தீவுகள்",
		"ta-LK": "யூ.எஸ். வெளிப்புறத் தீவுகள்",
		"ta-SG": "யூ.எஸ். வெளிப்புறத் தீவுகள்",
		"ta-MY": "யூ.எஸ். வெளிப்புறத் தீவுகள்",
		"te-IN": "సంయుక్త రాజ్య అమెరికా బయట ఉన్న దీవులు",
		"mr-IN": "यू.एस. आउटलाइंग बेटे",
		"gu-IN": "યુ.એસ. આઉટલાઇનિંગ આઇલેન્ડ્સ",
		"kn-IN": "ಯುಎಸ್‌ ಔಟ್‌ಲೇಯಿಂಗ್ ದ್ವೀಪಗಳು",
		"ml-IN": "യു.എസ്. ദ്വീപസമൂഹങ്ങൾ",
		"pa-IN": "ਯੂ.ਐੱਸ. ਦੂਰ-ਦੁਰਾਡੇ ਟਾਪੂ",
		"ur-IN": "امریکی بیرونی جزائر",
		"ur-PK": "امریکہ سے باہر کے چھوٹے جزائز",
		"or-IN": "ଯୁକ୍ତରାଷ୍ଟ୍ର ଆଉଟ୍‌ଲାଇଙ୍ଗ ଦ୍ଵୀପପୁଞ୍ଜ",
		"as-IN": "ইউ. এছ. আউটলায়িং দ্বীপপুঞ্জ",
		"ne-IN": "संयुक्त राज्यका बाह्य टापुहरु",
		"ne-NP": "संयुक्त राज्यका बाह्य टापुहरु",
		"si-LK": "එක්සත් ජනපද ඈත දූපත්",
		"kok-IN": "यु. एस. मायनर आवटलायींग आयलँड्‍स",
		"ks-IN": "یوٗنایٹِڑ سِٹیٹِس ماینَر آوُٹلییِنگ جٔزیٖرٕ",
		"brx-IN": "इउ.एस नि बायजोआरि द्वीपफोर",
		"mai-IN": "यू॰एस॰ आउटलाइंग द्वीपसमूह",
		"dz-BT": "ཡུ་ཨེས་གྱི་མཐའ་མཚམས་མཚོ་གླིང་",
		"ja-JP": "合衆国領有小離島",
		"ko-KR": "미국령 해외 제도",
		"ko-KP": "미국령 해외 제도",
		"zh-CN": "美国本土外小岛屿",
		"zh-Hans-CN": "美国本土外小岛屿",
		"zh-Hant-TW": "美國本土外小島嶼",
		"zh-TW": "美國本土外小島嶼",
		"zh-HK": "美國本土外小島嶼",
		"zh-MO": "美國本土外小島嶼",
		"zh-SG": "美国本土外小岛屿",
		"yue-Hant-HK": "美國本土外小島嶼",
		"yue-Hans-CN": "美国本土外小岛屿",
		"mn-MN": "Америкийн Нэгдсэн Улсын бага арлууд",
		"ug-CN": "ئا ق ش تاشقى ئاراللىرى",
		"th-TH": "หมู่เกาะรอบนอกของสหรัฐอเมริกา",
		"lo-LA": "ໝູ່ເກາະຮອບນອກຂອງສະຫະລັດຯ",
		"km-KH": "កោះ​អៅឡាយីង​អាមេរិក",
		"my-MM": "ယူနိုက်တက်စတိတ် ကျွန်းနိုင်ငံများ",
		"vi-VN": "Các tiểu đảo xa của Hoa Kỳ",
		"id-ID": "Kepulauan Terluar AS",
		"ms-MY": "Kepulauan Terpencil A.S.",
		"ms-SG": "Kepulauan Terpencil A.S.",
		"ms-BN": "Kepulauan Terpencil A.S.",
		"jv-ID": "Kapuloan AS Paling Njaba",
		"fil-PH": "U.S. Outlying Islands",
		"ceb-PH": "U.S. Outlying Islands",
		"ka-GE": "აშშ-ის შორეული კუნძულები",
		"hy-AM": "Արտաքին կղզիներ (ԱՄՆ)",
		"az-AZ": "ABŞ-a bağlı kiçik adacıqlar",
		"az-Cyrl-AZ": "АБШ-а бағлы кичик адаҹыглар",
		"kk-KZ": "АҚШ-тың сыртқы кіші аралдары",
		"ky-KG": "АКШнын сырткы аралдары",
		"uz-UZ": "AQSH yondosh orollari",
		"tg-TJ": "Ҷазираҳои Хурди Дурдасти ИМА",
		"tk-TM": "ABŞ-nyň daşarky adalary",
		"fa-IR": "جزایر دورافتادهٔ ایالات متحده",
		"fa-AF": "جزایر دورافتادهٔ ایالات متحده",
		"ps-AF": "د متحده ایالاتو ټاپوګان",
		"ps-PK": "د متحده ایالاتو ټاپوګان",
		"he-IL": "האיים המרוחקים הקטנים של ארה״ב",
		"ar-SA": "جزر الولايات المتحدة النائية",
		"ar-AE": "جزر الولايات المتحدة النائية",
		"ar-QA": "جزر الولايات المتحدة النائية",
		"ar-BH": "جزر الولايات المتحدة النائية",
		"ar-KW": "جزر الولايات المتحدة النائية",
		"ar-OM": "جزر الولايات المتحدة النائية",
		"ar-YE": "جزر الولايات المتحدة النائية",
		"ar-IQ": "جزر الولايات المتحدة النائية",
		"ar-JO": "جزر الولايات المتحدة النائية",
		"ar-LB": "جزر الولايات المتحدة النائية",
		"ar-SY": "جزر الولايات المتحدة النائية",
		"ar-PS": "جزر الولايات المتحدة النائية",
		"en-US": "U.S. Outlying Islands",
		"en-GB": "US Outlying Islands",
		"en-IE": "US Outlying Islands",
		"en-MT": "US Outlying Islands",
		"en-GI": "US Outlying Islands",
		"en-CY": "US Outlying Islands",
		"en-JE": "US Outlying Islands",
		"en-GG": "US Outlying Islands",
		"en-IM": "US Outlying Islands",
		"en-CA": "US Outlying Islands",
		"en-AU": "US Outlying Islands",
		"en-NZ": "US Outlying Islands",
		"en-ZA": "US Outlying Islands",
		"en-IN": "US Outlying Islands",
		"en-SG": "US Outlying Islands",
		"pt-AO": "Ilhas Menores Afastadas dos EUA",
		"pt-MZ": "Ilhas Menores Afastadas dos EUA",
		"pt-CV": "Ilhas Menores Afastadas dos EUA",
		"pt-GW": "Ilhas Menores Afastadas dos EUA",
		"pt-ST": "Ilhas Menores Afastadas dos EUA",
		"pt-TL": "Ilhas Menores Afastadas dos EUA",
		"pt-MO": "Ilhas Menores Afastadas dos EUA",
		"es-ES": "Islas menores alejadas de EE. UU.",
		"es-419": "Islas Ultramarinas de EE.UU.",
		"es-AD": "Islas menores alejadas de EE. UU.",
		"es-GI": "Islas menores alejadas de EE. UU.",
		"es-AR": "Islas menores alejadas de EE. UU.",
		"es-BO": "Islas menores alejadas de EE. UU.",
		"es-BR": "Islas Ultramarinas de EE.UU.",
		"es-BZ": "Islas Ultramarinas de EE.UU.",
		"es-CL": "Islas menores alejadas de EE. UU.",
		"es-CO": "Islas menores alejadas de EE. UU.",
		"es-CR": "Islas menores alejadas de EE. UU.",
		"es-CU": "Islas Ultramarinas de EE.UU.",
		"es-DO": "Islas menores alejadas de EE. UU.",
		"es-EC": "Islas menores alejadas de EE. UU.",
		"es-GT": "Islas menores alejadas de EE. UU.",
		"es-HN": "Islas menores alejadas de EE. UU.",
		"es-MX": "Islas menores alejadas de EE. UU.",
		"es-NI": "Islas menores alejadas de EE. UU.",
		"es-PA": "Islas menores alejadas de EE. UU.",
		"es-PE": "Islas menores alejadas de EE. UU.",
		"es-PR": "Islas menores alejadas de EE. UU.",
		"es-PY": "Islas menores alejadas de EE. UU.",
		"es-SV": "Islas menores alejadas de EE. UU.",
		"es-US": "Islas menores alejadas de EE. UU.",
		"es-UY": "Islas Ultramarinas de EE.UU.",
		"es-VE": "Islas menores alejadas de EE. UU.",
		"fr-FR": "Îles mineures éloignées des États-Unis",
		"fr-BE": "Îles mineures éloignées des États-Unis",
		"fr-CH": "Îles mineures éloignées des États-Unis",
		"fr-LU": "Îles mineures éloignées des États-Unis",
		"fr-MC": "Îles mineures éloignées des États-Unis",
		"fr-AD": "Îles mineures éloignées des États-Unis",
		"fr-CA": "îles mineures éloignées des États-Unis",
		"it-IT": "Isole Minori Esterne degli Stati Uniti",
		"it-CH": "Isole Minori Esterne degli Stati Uniti",
		"it-SM": "Isole Minori Esterne degli Stati Uniti",
		"it-VA": "Isole Minori Esterne degli Stati Uniti",
		"de-DE": "Amerikanische Überseeinseln",
		"de-AT": "Amerikanische Überseeinseln",
		"de-CH": "Amerikanische Überseeinseln",
		"de-BE": "Amerikanische Überseeinseln",
		"de-LI": "Amerikanische Überseeinseln",
		"de-LU": "Amerikanische Überseeinseln",
		"nl-NL": "Kleine afgelegen eilanden van de Verenigde Staten",
		"nl-BE": "Kleine afgelegen eilanden van de Verenigde Staten",
		"sv-SE": "USA:s yttre öar",
		"sv-FI": "USA:s yttre öar",
		"da-DK": "Amerikanske oversøiske øer",
		"nb-NO": "USAs ytre øyer",
		"nn-NO": "USAs ytre småøyar",
		"fi-FI": "Yhdysvaltain erillissaaret",
		"is-IS": "Smáeyjar Bandaríkjanna",
		"fo-FO": "Sambandsríki Amerikas fjarskotnu oyggjar",
		"et-EE": "Ühendriikide hajasaared",
		"lv-LV": "ASV Mazās Aizjūras salas",
		"lt-LT": "Jungtinių Valstijų Mažosios Tolimosios Salos",
		"pl-PL": "Dalekie Wyspy Mniejsze Stanów Zjednoczonych",
		"cs-CZ": "Menší odlehlé ostrovy USA",
		"sk-SK": "Menšie odľahlé ostrovy USA",
		"sl-SI": "Stranski zunanji otoki Združenih držav",
		"hr-HR": "Mali udaljeni otoci SAD-a",
		"bs-BA": "Američka Vanjska Ostrva",
		"sr-RS": "Удаљена острва САД",
		"sr-BA": "Спољна острва САД",
		"sr-ME": "Manja udaljena ostrva SAD",
		"mk-MK": "Американски територии во Пацификот",
		"bg-BG": "Отдалечени острови на САЩ",
		"be-BY": "Малыя Аддаленыя астравы ЗША",
		"uk-UA": "Віддалені острови США",
		"ru-RU": "Внешние малые о-ва (США)",
		"el-GR": "Απομακρυσμένες Νησίδες ΗΠΑ",
		"el-CY": "Απομακρυσμένες Νησίδες ΗΠΑ",
		"ro-RO": "Insulele Îndepărtate ale S.U.A.",
		"ro-MD": "Insulele Îndepărtate ale S.U.A.",
		"hu-HU": "Az USA lakatlan külbirtokai",
		"sq-AL": "Ishujt Periferikë të SHBA-së",
		"sq-XK": "Ishujt Periferikë të SHBA-së",
		"mt-MT": "Il-Gżejjer Minuri Mbiegħda tal-Istati Uniti",
		"ga-IE": "Oileáin Imeallacha S.A.M.",
		"cy-GB": "Ynysoedd Pellennig UDA",
		"gd-GB": "Meanbh-Eileanan Iomallach nan SA",
		"lb-LU": "Amerikanesch-Ozeanien",
		"ca-ES": "Illes Menors Allunyades dels Estats Units",
		"ca-AD": "Illes Menors Allunyades dels Estats Units",
		"ca-FR": "Illes Menors Allunyades dels Estats Units",
		"ca-IT": "Illes Menors Allunyades dels Estats Units",
		"eu-ES": "Ameriketako Estatu Batuetako Kanpoaldeko Uharte Txikiak",
		"eu-FR": "Ameriketako Estatu Batuetako Kanpoaldeko Uharte Txikiak",
		"gl-ES": "Illas Menores Distantes dos Estados Unidos",
		"tr-TR": "ABD Küçük Harici Adaları",
		"tr-CY": "ABD Küçük Harici Adaları"
	},
	"callingCode": "268"
} satisfies Country;
