import type { Country } from './types.js';

export const UNK = {
	"code": "UNK",
	"labels": {
		"pt-BR": "Kosovo",
		"pt-PT": "Kosovo",
		"qu-PE": "Kosovo",
		"qu-BO": "Kosovo",
		"qu-EC": "Kosovo",
		"chr-US": "ᎪᏐᏉ",
		"hi-IN": "कोसोवो",
		"bn-IN": "কসোভো",
		"bn-BD": "কসোভো",
		"ta-IN": "கொசோவோ",
		"ta-LK": "கொசோவோ",
		"ta-SG": "கொசோவோ",
		"ta-MY": "கொசோவோ",
		"te-IN": "కొసోవో",
		"mr-IN": "कोसोव्हो",
		"gu-IN": "કોસોવો",
		"kn-IN": "ಕೊಸೊವೊ",
		"ml-IN": "കൊസോവൊ",
		"pa-IN": "ਕੋਸੋਵੋ",
		"ur-IN": "کوسووو",
		"ur-PK": "کوسووو",
		"or-IN": "କୋସୋଭୋ",
		"as-IN": "কচ’ভ’",
		"ne-IN": "कोसोभो",
		"ne-NP": "कोसोभो",
		"si-LK": "කොසෝවෝ",
		"kok-IN": "कोसोवो",
		"ks-IN": "کوسوو",
		"brx-IN": "कस’भ’",
		"mai-IN": "कोसोवो",
		"ja-JP": "コソボ",
		"ko-KR": "코소보",
		"ko-KP": "코소보",
		"zh-CN": "科索沃",
		"zh-Hans-CN": "科索沃",
		"zh-Hant-TW": "科索沃",
		"zh-TW": "科索沃",
		"zh-HK": "科索沃",
		"zh-MO": "科索沃",
		"zh-SG": "科索沃",
		"yue-Hant-HK": "科索沃",
		"yue-Hans-CN": "科索沃",
		"mn-MN": "Косово",
		"ug-CN": "كوسوۋو",
		"th-TH": "โคโซโว",
		"lo-LA": "ໂຄໂຊໂວ",
		"km-KH": "កូសូវ៉ូ",
		"my-MM": "ကိုဆိုဗို",
		"vi-VN": "Kosovo",
		"id-ID": "Kosovo",
		"ms-MY": "Kosovo",
		"ms-SG": "Kosovo",
		"ms-BN": "Kosovo",
		"jv-ID": "Kosovo",
		"fil-PH": "Kosovo",
		"ceb-PH": "Kosovo",
		"ka-GE": "კოსოვო",
		"hy-AM": "Կոսովո",
		"az-AZ": "Kosovo",
		"az-Cyrl-AZ": "Косово",
		"kk-KZ": "Косово",
		"ky-KG": "Косово",
		"uz-UZ": "Kosovo",
		"tg-TJ": "Косово",
		"tk-TM": "Kosowo",
		"fa-IR": "کوزوو",
		"fa-AF": "کوسوا",
		"ps-AF": "کوسوو",
		"ps-PK": "کوسوو",
		"he-IL": "קוסובו",
		"ar-SA": "كوسوفو",
		"ar-AE": "كوسوفو",
		"ar-QA": "كوسوفو",
		"ar-BH": "كوسوفو",
		"ar-KW": "كوسوفو",
		"ar-OM": "كوسوفو",
		"ar-YE": "كوسوفو",
		"ar-IQ": "كوسوفو",
		"ar-JO": "كوسوفو",
		"ar-LB": "كوسوفو",
		"ar-SY": "كوسوفو",
		"ar-PS": "كوسوفو",
		"en-US": "Kosovo",
		"en-GB": "Kosovo",
		"en-IE": "Kosovo",
		"en-MT": "Kosovo",
		"en-GI": "Kosovo",
		"en-CY": "Kosovo",
		"en-JE": "Kosovo",
		"en-GG": "Kosovo",
		"en-IM": "Kosovo",
		"en-CA": "Kosovo",
		"en-AU": "Kosovo",
		"en-NZ": "Kosovo",
		"en-ZA": "Kosovo",
		"en-IN": "Kosovo",
		"en-SG": "Kosovo",
		"pt-AO": "Kosovo",
		"pt-MZ": "Kosovo",
		"pt-CV": "Kosovo",
		"pt-GW": "Kosovo",
		"pt-ST": "Kosovo",
		"pt-TL": "Kosovo",
		"pt-MO": "Kosovo",
		"es-ES": "Kosovo",
		"es-419": "Kosovo",
		"es-AD": "Kosovo",
		"es-GI": "Kosovo",
		"es-AR": "Kosovo",
		"es-BO": "Kosovo",
		"es-BR": "Kosovo",
		"es-BZ": "Kosovo",
		"es-CL": "Kosovo",
		"es-CO": "Kosovo",
		"es-CR": "Kosovo",
		"es-CU": "Kosovo",
		"es-DO": "Kosovo",
		"es-EC": "Kosovo",
		"es-GT": "Kosovo",
		"es-HN": "Kosovo",
		"es-MX": "Kosovo",
		"es-NI": "Kosovo",
		"es-PA": "Kosovo",
		"es-PE": "Kosovo",
		"es-PR": "Kosovo",
		"es-PY": "Kosovo",
		"es-SV": "Kosovo",
		"es-US": "Kosovo",
		"es-UY": "Kosovo",
		"es-VE": "Kosovo",
		"fr-FR": "Kosovo",
		"fr-BE": "Kosovo",
		"fr-CH": "Kosovo",
		"fr-LU": "Kosovo",
		"fr-MC": "Kosovo",
		"fr-AD": "Kosovo",
		"fr-CA": "Kosovo",
		"it-IT": "Kosovo",
		"it-CH": "Kosovo",
		"it-SM": "Kosovo",
		"it-VA": "Kosovo",
		"de-DE": "Kosovo",
		"de-AT": "Kosovo",
		"de-CH": "Kosovo",
		"de-BE": "Kosovo",
		"de-LI": "Kosovo",
		"de-LU": "Kosovo",
		"nl-NL": "Kosovo",
		"nl-BE": "Kosovo",
		"sv-SE": "Kosovo",
		"sv-FI": "Kosovo",
		"da-DK": "Kosovo",
		"nb-NO": "Kosovo",
		"nn-NO": "Kosovo",
		"fi-FI": "Kosovo",
		"is-IS": "Kósóvó",
		"fo-FO": "Kosovo",
		"et-EE": "Kosovo",
		"lv-LV": "Kosova",
		"lt-LT": "Kosovas",
		"pl-PL": "Kosowo",
		"cs-CZ": "Kosovo",
		"sk-SK": "Kosovo",
		"sl-SI": "Kosovo",
		"hr-HR": "Kosovo",
		"bs-BA": "Kosovo",
		"sr-RS": "Косово",
		"sr-BA": "Косово",
		"sr-ME": "Kosovo",
		"mk-MK": "Косово",
		"bg-BG": "Косово",
		"be-BY": "Косава",
		"uk-UA": "Косово",
		"ru-RU": "Косово",
		"el-GR": "Κοσσυφοπέδιο",
		"el-CY": "Κοσσυφοπέδιο",
		"ro-RO": "Kosovo",
		"ro-MD": "Kosovo",
		"hu-HU": "Koszovó",
		"sq-AL": "Kosovë",
		"sq-XK": "Kosovë",
		"mt-MT": "il-Kosovo",
		"ga-IE": "an Chosaiv",
		"cy-GB": "Kosovo",
		"gd-GB": "A’ Chosobho",
		"lb-LU": "Kosovo",
		"ca-ES": "Kosovo",
		"ca-AD": "Kosovo",
		"ca-FR": "Kosovo",
		"ca-IT": "Kosovo",
		"eu-ES": "Kosovo",
		"eu-FR": "Kosovo",
		"gl-ES": "Kosovo",
		"tr-TR": "Kosova",
		"tr-CY": "Kosova"
	},
	"callingCode": "383",
	"phoneMasks": [
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[2-4]"
			]
		},
		{
			"mask": "### #####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[89]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9,
			"leadingDigits": [
				"2|39"
			]
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11
		},
		{
			"mask": "## ##########",
			"minLength": 12,
			"maxLength": 12,
			"leadingDigits": [
				"3"
			]
		}
	]
} satisfies Country;
