import type { Country } from './types.js';

export const URY = {
	"code": "URY",
	"labels": {
		"pt-BR": "Uruguai",
		"pt-PT": "Uruguai",
		"qu-PE": "Uruguay",
		"qu-BO": "Uruguay",
		"qu-EC": "Uruguay",
		"chr-US": "ᏳᎷᏇ",
		"hi-IN": "उरूग्वे",
		"bn-IN": "উরুগুয়ে",
		"bn-BD": "উরুগুয়ে",
		"ta-IN": "உருகுவே",
		"ta-LK": "உருகுவே",
		"ta-SG": "உருகுவே",
		"ta-MY": "உருகுவே",
		"te-IN": "ఉరుగ్వే",
		"mr-IN": "उरुग्वे",
		"gu-IN": "ઉરુગ્વે",
		"kn-IN": "ಉರುಗ್ವೆ",
		"ml-IN": "ഉറുഗ്വേ",
		"pa-IN": "ਉਰੂਗਵੇ",
		"ur-IN": "یوروگوئے",
		"ur-PK": "یوروگوئے",
		"or-IN": "ଉରୁଗୁଏ",
		"as-IN": "উৰুগুৱে",
		"ne-IN": "उरूग्वे",
		"ne-NP": "उरूग्वे",
		"si-LK": "උරුගුවේ",
		"kok-IN": "उरूग्वे",
		"ks-IN": "یوٗروگے",
		"brx-IN": "ऊरुगुवे",
		"mai-IN": "उरुग्वे",
		"dz-BT": "ཡུ་རུ་གུ་ཝའི",
		"ja-JP": "ウルグアイ",
		"ko-KR": "우루과이",
		"ko-KP": "우루과이",
		"zh-CN": "乌拉圭",
		"zh-Hans-CN": "乌拉圭",
		"zh-Hant-TW": "烏拉圭",
		"zh-TW": "烏拉圭",
		"zh-HK": "烏拉圭",
		"zh-MO": "烏拉圭",
		"zh-SG": "乌拉圭",
		"yue-Hant-HK": "烏拉圭",
		"yue-Hans-CN": "乌拉圭",
		"mn-MN": "Уругвай",
		"ug-CN": "ئۇرۇگۋاي",
		"th-TH": "อุรุกวัย",
		"lo-LA": "ອູຣຸກວຍ",
		"km-KH": "អ៊ុយរូហ្គាយ",
		"my-MM": "ဥရုဂွေး",
		"vi-VN": "Uruguay",
		"id-ID": "Uruguay",
		"ms-MY": "Uruguay",
		"ms-SG": "Uruguay",
		"ms-BN": "Uruguay",
		"jv-ID": "Uruguay",
		"fil-PH": "Uruguay",
		"ceb-PH": "Uruguay",
		"ka-GE": "ურუგვაი",
		"hy-AM": "Ուրուգվայ",
		"az-AZ": "Uruqvay",
		"az-Cyrl-AZ": "Уругвај",
		"kk-KZ": "Уругвай",
		"ky-KG": "Уругвай",
		"uz-UZ": "Urugvay",
		"tg-TJ": "Уругвай",
		"tk-TM": "Urugwaý",
		"fa-IR": "اروگوئه",
		"fa-AF": "یوروگوای",
		"ps-AF": "یوروګوی",
		"ps-PK": "یوروګوی",
		"he-IL": "אורוגוואי",
		"ar-SA": "أوروغواي",
		"ar-AE": "أورغواي",
		"ar-QA": "أورغواي",
		"ar-BH": "أورغواي",
		"ar-KW": "أورغواي",
		"ar-OM": "أورغواي",
		"ar-YE": "أورغواي",
		"ar-IQ": "أورغواي",
		"ar-JO": "أورغواي",
		"ar-LB": "أورغواي",
		"ar-SY": "أورغواي",
		"ar-PS": "أورغواي",
		"en-US": "Uruguay",
		"en-GB": "Uruguay",
		"en-IE": "Uruguay",
		"en-MT": "Uruguay",
		"en-GI": "Uruguay",
		"en-CY": "Uruguay",
		"en-JE": "Uruguay",
		"en-GG": "Uruguay",
		"en-IM": "Uruguay",
		"en-CA": "Uruguay",
		"en-AU": "Uruguay",
		"en-NZ": "Uruguay",
		"en-ZA": "Uruguay",
		"en-IN": "Uruguay",
		"en-SG": "Uruguay",
		"pt-AO": "Uruguai",
		"pt-MZ": "Uruguai",
		"pt-CV": "Uruguai",
		"pt-GW": "Uruguai",
		"pt-ST": "Uruguai",
		"pt-TL": "Uruguai",
		"pt-MO": "Uruguai",
		"es-ES": "Uruguay",
		"es-419": "Uruguay",
		"es-AD": "Uruguay",
		"es-GI": "Uruguay",
		"es-AR": "Uruguay",
		"es-BO": "Uruguay",
		"es-BR": "Uruguay",
		"es-BZ": "Uruguay",
		"es-CL": "Uruguay",
		"es-CO": "Uruguay",
		"es-CR": "Uruguay",
		"es-CU": "Uruguay",
		"es-DO": "Uruguay",
		"es-EC": "Uruguay",
		"es-GT": "Uruguay",
		"es-HN": "Uruguay",
		"es-MX": "Uruguay",
		"es-NI": "Uruguay",
		"es-PA": "Uruguay",
		"es-PE": "Uruguay",
		"es-PR": "Uruguay",
		"es-PY": "Uruguay",
		"es-SV": "Uruguay",
		"es-US": "Uruguay",
		"es-UY": "Uruguay",
		"es-VE": "Uruguay",
		"fr-FR": "Uruguay",
		"fr-BE": "Uruguay",
		"fr-CH": "Uruguay",
		"fr-LU": "Uruguay",
		"fr-MC": "Uruguay",
		"fr-AD": "Uruguay",
		"fr-CA": "Uruguay",
		"it-IT": "Uruguay",
		"it-CH": "Uruguay",
		"it-SM": "Uruguay",
		"it-VA": "Uruguay",
		"de-DE": "Uruguay",
		"de-AT": "Uruguay",
		"de-CH": "Uruguay",
		"de-BE": "Uruguay",
		"de-LI": "Uruguay",
		"de-LU": "Uruguay",
		"nl-NL": "Uruguay",
		"nl-BE": "Uruguay",
		"sv-SE": "Uruguay",
		"sv-FI": "Uruguay",
		"da-DK": "Uruguay",
		"nb-NO": "Uruguay",
		"nn-NO": "Uruguay",
		"fi-FI": "Uruguay",
		"is-IS": "Úrúgvæ",
		"fo-FO": "Uruguai",
		"et-EE": "Uruguay",
		"lv-LV": "Urugvaja",
		"lt-LT": "Urugvajus",
		"pl-PL": "Urugwaj",
		"cs-CZ": "Uruguay",
		"sk-SK": "Uruguaj",
		"sl-SI": "Urugvaj",
		"hr-HR": "Urugvaj",
		"bs-BA": "Urugvaj",
		"sr-RS": "Уругвај",
		"sr-BA": "Уругвај",
		"sr-ME": "Urugvaj",
		"mk-MK": "Уругвај",
		"bg-BG": "Уругвай",
		"be-BY": "Уругвай",
		"uk-UA": "Уругвай",
		"ru-RU": "Уругвай",
		"el-GR": "Ουρουγουάη",
		"el-CY": "Ουρουγουάη",
		"ro-RO": "Uruguay",
		"ro-MD": "Uruguay",
		"hu-HU": "Uruguay",
		"sq-AL": "Uruguai",
		"sq-XK": "Uruguai",
		"mt-MT": "l-Urugwaj",
		"ga-IE": "Uragua",
		"cy-GB": "Uruguay",
		"gd-GB": "Uruguaidh",
		"lb-LU": "Uruguay",
		"ca-ES": "Uruguai",
		"ca-AD": "Uruguai",
		"ca-FR": "Uruguai",
		"ca-IT": "Uruguai",
		"eu-ES": "Uruguai",
		"eu-FR": "Uruguai",
		"gl-ES": "Uruguai",
		"tr-TR": "Uruguay",
		"tr-CY": "Uruguay"
	},
	"callingCode": "598",
	"phoneMasks": [
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"0"
			]
		},
		{
			"mask": "### ####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[49]0|8"
			]
		},
		{
			"mask": "## ### ###",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"9"
			]
		},
		{
			"mask": "#### ####",
			"minLength": 8,
			"maxLength": 8,
			"leadingDigits": [
				"[124]"
			]
		},
		{
			"mask": "### ### ###",
			"minLength": 9,
			"maxLength": 9
		},
		{
			"mask": "### ### ####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"0"
			]
		},
		{
			"mask": "### #### ####",
			"minLength": 11,
			"maxLength": 11
		},
		{
			"mask": "### ### ### ###",
			"minLength": 12,
			"maxLength": 12
		},
		{
			"mask": "### ### ### ####",
			"minLength": 13,
			"maxLength": 13,
			"leadingDigits": [
				"0"
			]
		}
	]
} satisfies Country;
