import type { Country } from './types.js';

export const USA = {
	"code": "USA",
	"labels": {
		"pt-BR": "Estados Unidos",
		"pt-PT": "Estados Unidos",
		"qu-PE": "Estados Unidos",
		"qu-BO": "Estados Unidos",
		"qu-EC": "Estados Unidos",
		"chr-US": "ᏌᏊ ᎢᏳᎾᎵᏍᏔᏅ ᏍᎦᏚᎩ",
		"lkt-US": "Mílahaŋska Tȟamákȟočhe",
		"hi-IN": "संयुक्त राज्य",
		"bn-IN": "মার্কিন যুক্তরাষ্ট্র",
		"bn-BD": "মার্কিন যুক্তরাষ্ট্র",
		"ta-IN": "அமெரிக்கா",
		"ta-LK": "அமெரிக்கா",
		"ta-SG": "அமெரிக்கா",
		"ta-MY": "அமெரிக்கா",
		"te-IN": "యునైటెడ్ స్టేట్స్",
		"mr-IN": "युनायटेड स्टेट्स",
		"gu-IN": "યુનાઇટેડ સ્ટેટ્સ",
		"kn-IN": "ಯುನೈಟೆಡ್ ಸ್ಟೇಟ್ಸ್",
		"ml-IN": "അമേരിക്കൻ ഐക്യനാടുകൾ",
		"pa-IN": "ਸੰਯੁਕਤ ਰਾਜ",
		"ur-IN": "ریاست ہائے متحدہ امریکہ",
		"ur-PK": "ریاست ہائے متحدہ امریکہ",
		"or-IN": "ଯୁକ୍ତ ରାଷ୍ଟ୍ର",
		"as-IN": "মাৰ্কিন যুক্তৰাষ্ট্ৰ",
		"ne-IN": "संयुक्त राज्य",
		"ne-NP": "संयुक्त राज्य",
		"si-LK": "එක්සත් ජනපදය",
		"kok-IN": "युनायटेड स्टेट्स",
		"sd-IN": "अमेरिका",
		"ks-IN": "یوٗنایٹِڑ سِٹیٹِس",
		"doi-IN": "यूएस",
		"mni-IN": "য়ুনাইটেদ ষ্টেটস",
		"brx-IN": "जथाय हादोर आमेरिका",
		"sat-IN": "ᱭᱩᱱᱟᱭᱴᱮᱰ ᱮᱥᱴᱮᱴ",
		"mai-IN": "संयुक्त राज्य",
		"sa-IN": "संयुक्त राज्य:",
		"dz-BT": "ཡུ་ཨེས་ཨེ",
		"ja-JP": "アメリカ合衆国",
		"ko-KR": "미국",
		"ko-KP": "미국",
		"zh-CN": "美国",
		"zh-Hans-CN": "美国",
		"zh-Hant-TW": "美國",
		"zh-TW": "美國",
		"zh-HK": "美國",
		"zh-MO": "美國",
		"zh-SG": "美国",
		"yue-Hant-HK": "美國",
		"yue-Hans-CN": "美国",
		"mn-MN": "Америкийн Нэгдсэн Улс",
		"bo-CN": "ཨ་མེ་རི་ཀ།",
		"bo-IN": "ཨ་མེ་རི་ཀ།",
		"ug-CN": "ئامېرىكا قوشما ئىشتاتلىرى",
		"ii-CN": "ꂰꇩ",
		"th-TH": "สหรัฐอเมริกา",
		"lo-LA": "ສະຫະລັດ",
		"km-KH": "សហរដ្ឋអាមេរិក",
		"my-MM": "အမေရိကန် ပြည်ထောင်စု",
		"vi-VN": "Hoa Kỳ",
		"id-ID": "Amerika Serikat",
		"ms-MY": "Amerika Syarikat",
		"ms-SG": "Amerika Syarikat",
		"ms-BN": "Amerika Syarikat",
		"jv-ID": "Amérika Sarékat",
		"su-ID": "Amérika Sarikat",
		"fil-PH": "Estados Unidos",
		"ceb-PH": "Estados Unidos",
		"ka-GE": "ამერიკის შეერთებული შტატები",
		"hy-AM": "Միացյալ Նահանգներ",
		"az-AZ": "Amerika Birləşmiş Ştatları",
		"az-Cyrl-AZ": "Америка Бирләшмиш Штатлары",
		"kk-KZ": "Америка Құрама Штаттары",
		"ky-KG": "Кошмо Штаттар",
		"uz-UZ": "Amerika Qo‘shma Shtatlari",
		"tg-TJ": "Иёлоти Муттаҳида",
		"tk-TM": "Amerikanyň Birleşen Ştatlary",
		"fa-IR": "ایالات متحده",
		"fa-AF": "ایالات متحده",
		"ps-AF": "متحده آيالات",
		"ps-PK": "متحده آيالات",
		"he-IL": "ארצות הברית",
		"ar-SA": "الولايات المتحدة",
		"ar-AE": "الولايات المتحدة",
		"ar-QA": "الولايات المتحدة",
		"ar-BH": "الولايات المتحدة",
		"ar-KW": "الولايات المتحدة",
		"ar-OM": "الولايات المتحدة",
		"ar-YE": "الولايات المتحدة",
		"ar-IQ": "الولايات المتحدة",
		"ar-JO": "الولايات المتحدة",
		"ar-LB": "الولايات المتحدة",
		"ar-SY": "الولايات المتحدة",
		"ar-PS": "الولايات المتحدة",
		"en-US": "United States",
		"en-GB": "United States",
		"en-IE": "United States",
		"en-MT": "United States",
		"en-GI": "United States",
		"en-CY": "United States",
		"en-JE": "United States",
		"en-GG": "United States",
		"en-IM": "United States",
		"en-CA": "United States",
		"en-AU": "United States",
		"en-NZ": "United States",
		"en-ZA": "United States",
		"en-IN": "United States",
		"en-SG": "United States",
		"pt-AO": "Estados Unidos",
		"pt-MZ": "Estados Unidos",
		"pt-CV": "Estados Unidos",
		"pt-GW": "Estados Unidos",
		"pt-ST": "Estados Unidos",
		"pt-TL": "Estados Unidos",
		"pt-MO": "Estados Unidos",
		"es-ES": "Estados Unidos",
		"es-419": "Estados Unidos",
		"es-AD": "Estados Unidos",
		"es-GI": "Estados Unidos",
		"es-AR": "Estados Unidos",
		"es-BO": "Estados Unidos",
		"es-BR": "Estados Unidos",
		"es-BZ": "Estados Unidos",
		"es-CL": "Estados Unidos",
		"es-CO": "Estados Unidos",
		"es-CR": "Estados Unidos",
		"es-CU": "Estados Unidos",
		"es-DO": "Estados Unidos",
		"es-EC": "Estados Unidos",
		"es-GT": "Estados Unidos",
		"es-HN": "Estados Unidos",
		"es-MX": "Estados Unidos",
		"es-NI": "Estados Unidos",
		"es-PA": "Estados Unidos",
		"es-PE": "Estados Unidos",
		"es-PR": "Estados Unidos",
		"es-PY": "Estados Unidos",
		"es-SV": "Estados Unidos",
		"es-US": "Estados Unidos",
		"es-UY": "Estados Unidos",
		"es-VE": "Estados Unidos",
		"fr-FR": "États-Unis",
		"fr-BE": "États-Unis",
		"fr-CH": "États-Unis",
		"fr-LU": "États-Unis",
		"fr-MC": "États-Unis",
		"fr-AD": "États-Unis",
		"fr-CA": "États-Unis",
		"it-IT": "Stati Uniti",
		"it-CH": "Stati Uniti",
		"it-SM": "Stati Uniti",
		"it-VA": "Stati Uniti",
		"de-DE": "Vereinigte Staaten",
		"de-AT": "Vereinigte Staaten",
		"de-CH": "Vereinigte Staaten",
		"de-BE": "Vereinigte Staaten",
		"de-LI": "Vereinigte Staaten",
		"de-LU": "Vereinigte Staaten",
		"nl-NL": "Verenigde Staten",
		"nl-BE": "Verenigde Staten",
		"sv-SE": "USA",
		"sv-FI": "USA",
		"da-DK": "USA",
		"nb-NO": "USA",
		"nn-NO": "USA",
		"fi-FI": "Yhdysvallat",
		"is-IS": "Bandaríkin",
		"fo-FO": "Sambandsríki Amerika",
		"et-EE": "Ameerika Ühendriigid",
		"lv-LV": "Amerikas Savienotās Valstis",
		"lt-LT": "Jungtinės Valstijos",
		"pl-PL": "Stany Zjednoczone",
		"cs-CZ": "Spojené státy",
		"sk-SK": "Spojené štáty",
		"sl-SI": "Združene države Amerike",
		"hr-HR": "Sjedinjene Američke Države",
		"bs-BA": "Sjedinjene Države",
		"sr-RS": "Сједињене Државе",
		"sr-BA": "Сједињене Државе",
		"sr-ME": "Sjedinjene Države",
		"mk-MK": "Соединети Американски Држави",
		"bg-BG": "Съединени щати",
		"be-BY": "Злучаныя Штаты Амерыкі",
		"uk-UA": "Сполучені Штати",
		"ru-RU": "Соединенные Штаты",
		"el-GR": "Ηνωμένες Πολιτείες",
		"el-CY": "Ηνωμένες Πολιτείες",
		"ro-RO": "Statele Unite ale Americii",
		"ro-MD": "Statele Unite ale Americii",
		"hu-HU": "Egyesült Államok",
		"sq-AL": "SHBA",
		"sq-XK": "SHBA",
		"mt-MT": "l-Istati Uniti",
		"ga-IE": "Stáit Aontaithe Mheiriceá",
		"cy-GB": "Yr Unol Daleithiau",
		"gd-GB": "Na Stàitean Aonaichte",
		"lb-LU": "Vereenegt Staaten",
		"ca-ES": "Estats Units",
		"ca-AD": "Estats Units",
		"ca-FR": "Estats Units",
		"ca-IT": "Estats Units",
		"eu-ES": "Ameriketako Estatu Batuak",
		"eu-FR": "Ameriketako Estatu Batuak",
		"gl-ES": "Estados Unidos",
		"tr-TR": "Amerika Birleşik Devletleri",
		"tr-CY": "Amerika Birleşik Devletleri"
	},
	"callingCode": "1",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"310"
			]
		},
		{
			"mask": "(###) ###-####",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
