import type { Country } from './types.js';

export const VAT = {
	"code": "VAT",
	"labels": {
		"pt-BR": "Cidade do Vaticano",
		"pt-PT": "Cidade do Vaticano",
		"es-ES": "Ciudad del Vaticano",
		"es-419": "Ciudad del Vaticano",
		"es-AR": "Ciudad del Vaticano",
		"es-BO": "Ciudad del Vaticano",
		"es-BR": "Ciudad del Vaticano",
		"es-BZ": "Ciudad del Vaticano",
		"es-CL": "Ciudad del Vaticano",
		"es-CO": "Ciudad del Vaticano",
		"es-CR": "Ciudad del Vaticano",
		"es-CU": "Ciudad del Vaticano",
		"es-DO": "Ciudad del Vaticano",
		"es-EC": "Ciudad del Vaticano",
		"es-GT": "Ciudad del Vaticano",
		"es-HN": "Ciudad del Vaticano",
		"es-MX": "Ciudad del Vaticano",
		"es-NI": "Ciudad del Vaticano",
		"es-PA": "Ciudad del Vaticano",
		"es-PE": "Ciudad del Vaticano",
		"es-PR": "Ciudad del Vaticano",
		"es-PY": "Ciudad del Vaticano",
		"es-SV": "Ciudad del Vaticano",
		"es-US": "Ciudad del Vaticano",
		"es-UY": "Ciudad del Vaticano",
		"es-VE": "Ciudad del Vaticano",
		"en-US": "Vatican City",
		"fr-FR": "État de la Cité du Vatican",
		"fr-BE": "État de la Cité du Vatican",
		"fr-CA": "Cité du Vatican",
		"fr-CH": "État de la Cité du Vatican",
		"fr-LU": "État de la Cité du Vatican",
		"fr-MC": "État de la Cité du Vatican",
		"it-IT": "Città del Vaticano",
		"it-CH": "Città del Vaticano",
		"it-SM": "Città del Vaticano",
		"it-VA": "Città del Vaticano",
		"de-DE": "Vatikanstadt",
		"de-AT": "Vatikanstadt",
		"de-CH": "Vatikanstadt",
		"de-BE": "Vatikanstadt",
		"de-LI": "Vatikanstadt",
		"de-LU": "Vatikanstadt"
	},
	"callingCode": "3906698"
} satisfies Country;
