import type { Country } from './types.js';

export const VCT = {
	"code": "VCT",
	"labels": {
		"pt-BR": "São Vicente e Granadinas",
		"pt-PT": "São Vicente e Granadinas",
		"qu-PE": "San Vicente y las Granadinas",
		"qu-BO": "San Vicente y las Granadinas",
		"qu-EC": "San Vicente y las Granadinas",
		"chr-US": "ᎤᏓᏅᏘ ᏫᏂᏏᏂᏗ ᎠᎴ ᎾᏍᎩ ᏇᎾᏗᏁᏍ",
		"hi-IN": "सेंट विंसेंट और ग्रेनाडाइंस",
		"bn-IN": "সেন্ট ভিনসেন্ট ও গ্রেনাডিনস",
		"bn-BD": "সেন্ট ভিনসেন্ট ও গ্রেনাডিনস",
		"ta-IN": "செயின்ட் வின்சென்ட் & கிரெனடைன்ஸ்",
		"ta-LK": "செயின்ட் வின்சென்ட் & கிரெனடைன்ஸ்",
		"ta-SG": "செயின்ட் வின்சென்ட் & கிரெனடைன்ஸ்",
		"ta-MY": "செயின்ட் வின்சென்ட் & கிரெனடைன்ஸ்",
		"te-IN": "సెయింట్ విన్సెంట్ మరియు గ్రెనడీన్స్",
		"mr-IN": "सेंट व्हिन्सेंट आणि ग्रेनडाइन्स",
		"gu-IN": "સેંટ વિન્સેંટ અને ગ્રેનેડાઇંસ",
		"kn-IN": "ಸೇಂಟ್. ವಿನ್ಸೆಂಟ್ ಮತ್ತು ಗ್ರೆನೆಡೈನ್ಸ್",
		"ml-IN": "സെന്റ് വിൻസെന്റും ഗ്രനെഡൈൻസും",
		"pa-IN": "ਸੇਂਟ ਵਿਨਸੈਂਟ ਐਂਡ ਗ੍ਰੇਨਾਡੀਨਸ",
		"ur-IN": "سینٹ ونسنٹ اور گرینیڈائنز",
		"ur-PK": "سینٹ ونسنٹ اور گرینیڈائنز",
		"or-IN": "ସେଣ୍ଟ ଭିନସେଣ୍ଟ ଏବଂ ଗ୍ରେନାଡାଇନ୍ସ",
		"as-IN": "ছেইণ্ট ভিনচেণ্ট আৰু গ্ৰীণাডাইনছ",
		"ne-IN": "सेन्ट भिन्सेन्ट र ग्रेनाडिन्स",
		"ne-NP": "सेन्ट भिन्सेन्ट र ग्रेनाडिन्स",
		"si-LK": "ශාන්ත වින්සන්ට් සහ ග්‍රෙනඩින්ස්",
		"kok-IN": "सेंट विंसेंट ऐंड द ग्रेनेडाइंस",
		"ks-IN": "سینٹ وینسؠٹ تہٕ گریناڑاینٕز",
		"brx-IN": "सैन्ट भिन्सेन्ट आरो ग्रेनादीन्स",
		"mai-IN": "सेंट विंसेंट आ ग्रेनाडाइंस",
		"dz-BT": "སེནཊ་ཝིན་སེནཌ྄ ཨེནཌ་ གི་རེ་ན་དིནས྄",
		"ja-JP": "セントビンセント及びグレナディーン諸島",
		"ko-KR": "세인트빈센트그레나딘",
		"ko-KP": "세인트빈센트그레나딘",
		"zh-CN": "圣文森特和格林纳丁斯",
		"zh-Hans-CN": "圣文森特和格林纳丁斯",
		"zh-Hant-TW": "聖文森及格瑞那丁",
		"zh-TW": "聖文森及格瑞那丁",
		"zh-HK": "聖文森特和格林納丁斯",
		"zh-MO": "聖文森特和格林納丁斯",
		"zh-SG": "圣文森特和格林纳丁斯",
		"yue-Hant-HK": "聖文森特同格林納丁斯",
		"yue-Hans-CN": "圣文森特同格林纳丁斯",
		"mn-MN": "Сент-Винсент ба Гренадин",
		"ug-CN": "ساينت ۋىنسېنت ۋە گىرېنادىنېس",
		"th-TH": "เซนต์วินเซนต์และเกรนาดีนส์",
		"lo-LA": "ເຊນ ວິນເຊນ ແລະ ເກຣເນດິນ",
		"km-KH": "សាំង​វ៉ាំងសង់ និង ហ្គ្រេណាឌីន",
		"my-MM": "စိန့်ဗင်းဆင့်နှင့် ဂရိနေဒိုင်",
		"vi-VN": "St. Vincent và Grenadines",
		"id-ID": "Saint Vincent dan Grenadine",
		"ms-MY": "Saint Vincent dan Grenadines",
		"ms-SG": "Saint Vincent dan Grenadines",
		"ms-BN": "Saint Vincent dan Grenadines",
		"jv-ID": "Saint Vinsen lan Grénadin",
		"fil-PH": "St. Vincent & Grenadines",
		"ceb-PH": "St. Vincent & Grenadines",
		"ka-GE": "სენტ-ვინსენტი და გრენადინები",
		"hy-AM": "Սենթ Վինսենթ և Գրենադիններ",
		"az-AZ": "Sent-Vinsent və Qrenadinlər",
		"az-Cyrl-AZ": "Сент-Винсент вә Гренадинләр",
		"kk-KZ": "Сент-Винсент және Гренадин аралдары",
		"ky-KG": "Сент-Винсент жана Гренадиндер",
		"uz-UZ": "Sent-Vinsent va Grenadin",
		"tg-TJ": "Сент-Винсент ва Гренадина",
		"tk-TM": "Sent-Winsent we Grenadinler",
		"fa-IR": "سنت وینسنت و گرنادین",
		"fa-AF": "سنت وینسنت و گرنادین‌ها",
		"ps-AF": "سینټ ویسنټینټ او ګرینډینز",
		"ps-PK": "سینټ ویسنټینټ او ګرینډینز",
		"he-IL": "סנט וינסנט והגרנדינים",
		"ar-SA": "سانت فنسنت وجزر غرينادين",
		"ar-AE": "سانت فنسنت وجزر غرينادين",
		"ar-QA": "سانت فنسنت وجزر غرينادين",
		"ar-BH": "سانت فنسنت وجزر غرينادين",
		"ar-KW": "سانت فنسنت وجزر غرينادين",
		"ar-OM": "سانت فنسنت وجزر غرينادين",
		"ar-YE": "سانت فنسنت وجزر غرينادين",
		"ar-IQ": "سانت فنسنت وجزر غرينادين",
		"ar-JO": "سانت فنسنت وجزر غرينادين",
		"ar-LB": "سانت فنسنت وجزر غرينادين",
		"ar-SY": "سانت فنسنت وجزر غرينادين",
		"ar-PS": "سانت فنسنت وجزر غرينادين",
		"en-US": "St. Vincent & Grenadines",
		"en-GB": "St Vincent & the Grenadines",
		"en-IE": "St Vincent & the Grenadines",
		"en-MT": "St Vincent & the Grenadines",
		"en-GI": "St Vincent & the Grenadines",
		"en-CY": "St Vincent & the Grenadines",
		"en-JE": "St Vincent & the Grenadines",
		"en-GG": "St Vincent & the Grenadines",
		"en-IM": "St Vincent & the Grenadines",
		"en-CA": "Saint Vincent and the Grenadines",
		"en-AU": "St. Vincent & Grenadines",
		"en-NZ": "St Vincent & the Grenadines",
		"en-ZA": "St Vincent & the Grenadines",
		"en-IN": "St Vincent & the Grenadines",
		"en-SG": "St Vincent & the Grenadines",
		"pt-AO": "São Vicente e Granadinas",
		"pt-MZ": "São Vicente e Granadinas",
		"pt-CV": "São Vicente e Granadinas",
		"pt-GW": "São Vicente e Granadinas",
		"pt-ST": "São Vicente e Granadinas",
		"pt-TL": "São Vicente e Granadinas",
		"pt-MO": "São Vicente e Granadinas",
		"es-ES": "San Vicente y las Granadinas",
		"es-419": "San Vicente y las Granadinas",
		"es-AD": "San Vicente y las Granadinas",
		"es-GI": "San Vicente y las Granadinas",
		"es-AR": "San Vicente y las Granadinas",
		"es-BO": "San Vicente y las Granadinas",
		"es-BR": "San Vicente y las Granadinas",
		"es-BZ": "San Vicente y las Granadinas",
		"es-CL": "San Vicente y las Granadinas",
		"es-CO": "San Vicente y las Granadinas",
		"es-CR": "San Vicente y las Granadinas",
		"es-CU": "San Vicente y las Granadinas",
		"es-DO": "San Vicente y las Granadinas",
		"es-EC": "San Vicente y las Granadinas",
		"es-GT": "San Vicente y las Granadinas",
		"es-HN": "San Vicente y las Granadinas",
		"es-MX": "San Vicente y las Granadinas",
		"es-NI": "San Vicente y las Granadinas",
		"es-PA": "San Vicente y las Granadinas",
		"es-PE": "San Vicente y las Granadinas",
		"es-PR": "San Vicente y las Granadinas",
		"es-PY": "San Vicente y las Granadinas",
		"es-SV": "San Vicente y las Granadinas",
		"es-US": "San Vicente y las Granadinas",
		"es-UY": "San Vicente y las Granadinas",
		"es-VE": "San Vicente y las Granadinas",
		"fr-FR": "Saint-Vincent-et-les Grenadines",
		"fr-BE": "Saint-Vincent-et-les Grenadines",
		"fr-CH": "Saint-Vincent-et-les Grenadines",
		"fr-LU": "Saint-Vincent-et-les Grenadines",
		"fr-MC": "Saint-Vincent-et-les Grenadines",
		"fr-AD": "Saint-Vincent-et-les Grenadines",
		"fr-CA": "Saint-Vincent-et-les Grenadines",
		"it-IT": "Saint Vincent e Grenadine",
		"it-CH": "Saint Vincent e Grenadine",
		"it-SM": "Saint Vincent e Grenadine",
		"it-VA": "Saint Vincent e Grenadine",
		"de-DE": "St. Vincent und die Grenadinen",
		"de-AT": "St. Vincent und die Grenadinen",
		"de-CH": "St. Vincent und die Grenadinen",
		"de-BE": "St. Vincent und die Grenadinen",
		"de-LI": "St. Vincent und die Grenadinen",
		"de-LU": "St. Vincent und die Grenadinen",
		"nl-NL": "Saint Vincent en de Grenadines",
		"nl-BE": "Saint Vincent en de Grenadines",
		"sv-SE": "S:t Vincent och Grenadinerna",
		"sv-FI": "S:t Vincent och Grenadinerna",
		"da-DK": "Saint Vincent og Grenadinerne",
		"nb-NO": "St. Vincent og Grenadinene",
		"nn-NO": "St. Vincent og Grenadinane",
		"fi-FI": "Saint Vincent ja Grenadiinit",
		"is-IS": "Sankti Vinsent og Grenadíneyjar",
		"fo-FO": "St. Vinsent & Grenadinoyggjar",
		"et-EE": "Saint Vincent ja Grenadiinid",
		"lv-LV": "Sentvinsenta un Grenadīnas",
		"lt-LT": "Šventasis Vincentas ir Grenadinai",
		"pl-PL": "Saint Vincent i Grenadyny",
		"cs-CZ": "Svatý Vincenc a Grenadiny",
		"sk-SK": "Svätý Vincent a Grenadíny",
		"sl-SI": "Saint Vincent in Grenadine",
		"hr-HR": "Sveti Vincent i Grenadini",
		"bs-BA": "Sveti Vinsent i Grenadin",
		"sr-RS": "Сент Винсент и Гренадини",
		"sr-BA": "Свети Винсент и Гренадини",
		"sr-ME": "Sveti Vinsent i Grenadini",
		"mk-MK": "Сент Винсент и Гренадини",
		"bg-BG": "Сейнт Винсънт и Гренадини",
		"be-BY": "Сент-Вінсент і Грэнадзіны",
		"uk-UA": "Сент-Вінсент і Гренадіни",
		"ru-RU": "Сент-Винсент и Гренадины",
		"el-GR": "Άγιος Βικέντιος και Γρεναδίνες",
		"el-CY": "Άγιος Βικέντιος και Γρεναδίνες",
		"ro-RO": "Saint Vincent și Grenadinele",
		"ro-MD": "Saint Vincent și Grenadinele",
		"hu-HU": "Saint Vincent és a Grenadine-szigetek",
		"sq-AL": "Shën-Vincent dhe Grenadine",
		"sq-XK": "Shën-Vincent dhe Grenadine",
		"mt-MT": "Saint Vincent u l-Grenadini",
		"ga-IE": "San Uinseann agus na Greanáidíní",
		"cy-GB": "Saint Vincent a’r Grenadines",
		"gd-GB": "Naomh Bhionsant agus Eileanan Greanadach",
		"lb-LU": "St. Vincent an d’Grenadinnen",
		"ca-ES": "Saint Vincent i les Grenadines",
		"ca-AD": "Saint Vincent i les Grenadines",
		"ca-FR": "Saint Vincent i les Grenadines",
		"ca-IT": "Saint Vincent i les Grenadines",
		"eu-ES": "Saint Vincent eta Grenadinak",
		"eu-FR": "Saint Vincent eta Grenadinak",
		"gl-ES": "San Vicente e as Granadinas",
		"tr-TR": "Saint Vincent ve Grenadinler",
		"tr-CY": "Saint Vincent ve Grenadinler"
	},
	"callingCode": "1784",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
