import type { Country } from './types.js';

export const VEN = {
	"code": "VEN",
	"labels": {
		"pt-BR": "Venezuela",
		"pt-PT": "Venezuela",
		"es-ES": "Venezuela",
		"es-419": "Venezuela",
		"es-AR": "Venezuela",
		"es-BO": "Venezuela",
		"es-BR": "Venezuela",
		"es-BZ": "Venezuela",
		"es-CL": "Venezuela",
		"es-CO": "Venezuela",
		"es-CR": "Venezuela",
		"es-CU": "Venezuela",
		"es-DO": "Venezuela",
		"es-EC": "Venezuela",
		"es-GT": "Venezuela",
		"es-HN": "Venezuela",
		"es-MX": "Venezuela",
		"es-NI": "Venezuela",
		"es-PA": "Venezuela",
		"es-PE": "Venezuela",
		"es-PR": "Venezuela",
		"es-PY": "Venezuela",
		"es-SV": "Venezuela",
		"es-US": "Venezuela",
		"es-UY": "Venezuela",
		"es-VE": "Venezuela",
		"en-US": "Venezuela",
		"fr-FR": "Venezuela",
		"fr-BE": "Venezuela",
		"fr-CA": "Vénézuéla",
		"fr-CH": "Venezuela",
		"fr-LU": "Venezuela",
		"fr-MC": "Venezuela",
		"it-IT": "Venezuela",
		"it-CH": "Venezuela",
		"it-SM": "Venezuela",
		"it-VA": "Venezuela",
		"de-DE": "Venezuela",
		"de-AT": "Venezuela",
		"de-CH": "Venezuela",
		"de-BE": "Venezuela",
		"de-LI": "Venezuela",
		"de-LU": "Venezuela"
	}
} satisfies Country;
