import type { Country } from './types.js';

export const VGB = {
	"code": "VGB",
	"labels": {
		"pt-BR": "Ilhas Virgens Britânicas",
		"pt-PT": "Ilhas Virgens Britânicas",
		"es-ES": "Islas Vírgenes Británicas",
		"es-419": "Islas Vírgenes Británicas",
		"es-AR": "Islas Vírgenes Británicas",
		"es-BO": "Islas Vírgenes Británicas",
		"es-BR": "Islas Vírgenes Británicas",
		"es-BZ": "Islas Vírgenes Británicas",
		"es-CL": "Islas Vírgenes Británicas",
		"es-CO": "Islas Vírgenes Británicas",
		"es-CR": "Islas Vírgenes Británicas",
		"es-CU": "Islas Vírgenes Británicas",
		"es-DO": "Islas Vírgenes Británicas",
		"es-EC": "Islas Vírgenes Británicas",
		"es-GT": "Islas Vírgenes Británicas",
		"es-HN": "Islas Vírgenes Británicas",
		"es-MX": "Islas Vírgenes Británicas",
		"es-NI": "Islas Vírgenes Británicas",
		"es-PA": "Islas Vírgenes Británicas",
		"es-PE": "Islas Vírgenes Británicas",
		"es-PR": "Islas Vírgenes Británicas",
		"es-PY": "Islas Vírgenes Británicas",
		"es-SV": "Islas Vírgenes Británicas",
		"es-US": "Islas Vírgenes Británicas",
		"es-UY": "Islas Vírgenes Británicas",
		"es-VE": "Islas Vírgenes Británicas",
		"en-US": "British Virgin Islands",
		"fr-FR": "Îles Vierges britanniques",
		"fr-BE": "Îles Vierges britanniques",
		"fr-CA": "îles Vierges britanniques",
		"fr-CH": "Îles Vierges britanniques",
		"fr-LU": "Îles Vierges britanniques",
		"fr-MC": "Îles Vierges britanniques",
		"it-IT": "Isole Vergini Britanniche",
		"it-CH": "Isole Vergini Britanniche",
		"it-SM": "Isole Vergini Britanniche",
		"it-VA": "Isole Vergini Britanniche",
		"de-DE": "Britische Jungferninseln",
		"de-AT": "Britische Jungferninseln",
		"de-CH": "Britische Jungferninseln",
		"de-BE": "Britische Jungferninseln",
		"de-LI": "Britische Jungferninseln",
		"de-LU": "Britische Jungferninseln"
	},
	"callingCode": "1284"
} satisfies Country;
