import type { Country } from './types.js';

export const VGB = {
	"code": "VGB",
	"labels": {
		"pt-BR": "Ilhas Virgens Britânicas",
		"pt-PT": "Ilhas Virgens Britânicas",
		"qu-PE": "Islas Vírgenes Británicas",
		"qu-BO": "Islas Vírgenes Británicas",
		"qu-EC": "Islas Vírgenes Británicas",
		"chr-US": "ᏈᏗᏍ ᎠᏒᏂᎸ ᏂᎨᏒᎾ ᏚᎦᏚᏛᎢ",
		"hi-IN": "ब्रिटिश वर्जिन द्वीपसमूह",
		"bn-IN": "ব্রিটিশ ভার্জিন দ্বীপপুঞ্জ",
		"bn-BD": "ব্রিটিশ ভার্জিন দ্বীপপুঞ্জ",
		"ta-IN": "பிரிட்டீஷ் கன்னித் தீவுகள்",
		"ta-LK": "பிரிட்டீஷ் கன்னித் தீவுகள்",
		"ta-SG": "பிரிட்டீஷ் கன்னித் தீவுகள்",
		"ta-MY": "பிரிட்டீஷ் கன்னித் தீவுகள்",
		"te-IN": "బ్రిటిష్ వర్జిన్ దీవులు",
		"mr-IN": "ब्रिटिश व्हर्जिन बेटे",
		"gu-IN": "બ્રિટિશ વર્જિન આઇલેન્ડ્સ",
		"kn-IN": "ಬ್ರಿಟಿಷ್ ವರ್ಜಿನ್ ದ್ವೀಪಗಳು",
		"ml-IN": "ബ്രിട്ടീഷ് വെർജിൻ ദ്വീപുകൾ",
		"pa-IN": "ਬ੍ਰਿਟਿਸ਼ ਵਰਜਿਨ ਟਾਪੂ",
		"ur-IN": "برطانوی جزائر ورجن",
		"ur-PK": "برٹش ورجن آئلینڈز",
		"or-IN": "ବ୍ରିଟିଶ୍‌ ଭର୍ଜିନ୍ ଦ୍ୱୀପପୁଞ୍ଜ",
		"as-IN": "ব্ৰিটিছ ভাৰ্জিন দ্বীপপুঞ্জ",
		"ne-IN": "बेलायती भर्जिन टापुहरू",
		"ne-NP": "बेलायती भर्जिन टापुहरू",
		"si-LK": "බ්‍රිතාන්‍ය වර්ජින් දූපත්",
		"kok-IN": "ब्रिटिश वर्जिन आयलँड्स",
		"ks-IN": "بَرطانوی ؤرجِن جٔزیٖرٕ",
		"brx-IN": "ब्रिटिश भार्जिन द्वीपफोर",
		"mai-IN": "ब्रिटिश वर्जिन द्वीपसमूह",
		"dz-BT": "ཝརཇིན་གླིང་ཚོམ་ བྲཱི་ཊིཤ་མངའ་ཁོངས",
		"ja-JP": "英領ヴァージン諸島",
		"ko-KR": "영국령 버진아일랜드",
		"ko-KP": "영국령 버진아일랜드",
		"zh-CN": "英属维尔京群岛",
		"zh-Hans-CN": "英属维尔京群岛",
		"zh-Hant-TW": "英屬維京群島",
		"zh-TW": "英屬維京群島",
		"zh-HK": "英屬維爾京群島",
		"zh-MO": "英屬維爾京群島",
		"zh-SG": "英属维尔京群岛",
		"yue-Hant-HK": "英屬維京群島",
		"yue-Hans-CN": "英属维京群岛",
		"mn-MN": "Британийн Виржиний арлууд",
		"ug-CN": "ئەنگلىيە ۋىرگىن ئاراللىرى",
		"th-TH": "หมู่เกาะบริติชเวอร์จิน",
		"lo-LA": "ໝູ່ເກາະ ເວີຈິນຂອງອັງກິດ",
		"km-KH": "កោះ​វឺជិន​ចក្រភព​អង់គ្លេស",
		"my-MM": "ဗြိတိသျှ ဗာဂျင်း ကျွန်းစု",
		"vi-VN": "Quần đảo Virgin thuộc Anh",
		"id-ID": "Kepulauan Virgin Britania Raya",
		"ms-MY": "Kepulauan Virgin British",
		"ms-SG": "Kepulauan Virgin British",
		"ms-BN": "Kepulauan Virgin British",
		"jv-ID": "Kapuloan Virgin Britania",
		"fil-PH": "British Virgin Islands",
		"ceb-PH": "British Virgin Islands",
		"ka-GE": "ბრიტანეთის ვირჯინის კუნძულები",
		"hy-AM": "Բրիտանական Վիրջինյան կղզիներ",
		"az-AZ": "Britaniyanın Virgin adaları",
		"az-Cyrl-AZ": "Британијанын Вирҝин адалары",
		"kk-KZ": "Британдық Виргин аралдары",
		"ky-KG": "Виргин аралдары (Британия)",
		"uz-UZ": "Britaniya Virgin orollari",
		"tg-TJ": "Ҷазираҳои Виргини Британия",
		"tk-TM": "Britan Wirgin adalary",
		"fa-IR": "جزایر ویرجین بریتانیا",
		"fa-AF": "جزایر ویرجین بریتانیا",
		"ps-AF": "بریتانوی ویګور ټاپوګان",
		"ps-PK": "بریتانوی ویګور ټاپوګان",
		"he-IL": "איי הבתולה הבריטיים",
		"ar-SA": "جزر فيرجن البريطانية",
		"ar-AE": "جزر فيرجن البريطانية",
		"ar-QA": "جزر فيرجن البريطانية",
		"ar-BH": "جزر فيرجن البريطانية",
		"ar-KW": "جزر فيرجن البريطانية",
		"ar-OM": "جزر فيرجن البريطانية",
		"ar-YE": "جزر فيرجن البريطانية",
		"ar-IQ": "جزر فيرجن البريطانية",
		"ar-JO": "جزر فيرجن البريطانية",
		"ar-LB": "جزر فيرجن البريطانية",
		"ar-SY": "جزر فيرجن البريطانية",
		"ar-PS": "جزر فيرجن البريطانية",
		"en-US": "British Virgin Islands",
		"en-GB": "British Virgin Islands",
		"en-IE": "British Virgin Islands",
		"en-MT": "British Virgin Islands",
		"en-GI": "British Virgin Islands",
		"en-CY": "British Virgin Islands",
		"en-JE": "British Virgin Islands",
		"en-GG": "British Virgin Islands",
		"en-IM": "British Virgin Islands",
		"en-CA": "British Virgin Islands",
		"en-AU": "British Virgin Islands",
		"en-NZ": "British Virgin Islands",
		"en-ZA": "British Virgin Islands",
		"en-IN": "British Virgin Islands",
		"en-SG": "British Virgin Islands",
		"pt-AO": "Ilhas Virgens Britânicas",
		"pt-MZ": "Ilhas Virgens Britânicas",
		"pt-CV": "Ilhas Virgens Britânicas",
		"pt-GW": "Ilhas Virgens Britânicas",
		"pt-ST": "Ilhas Virgens Britânicas",
		"pt-TL": "Ilhas Virgens Britânicas",
		"pt-MO": "Ilhas Virgens Britânicas",
		"es-ES": "Islas Vírgenes Británicas",
		"es-419": "Islas Vírgenes Británicas",
		"es-AD": "Islas Vírgenes Británicas",
		"es-GI": "Islas Vírgenes Británicas",
		"es-AR": "Islas Vírgenes Británicas",
		"es-BO": "Islas Vírgenes Británicas",
		"es-BR": "Islas Vírgenes Británicas",
		"es-BZ": "Islas Vírgenes Británicas",
		"es-CL": "Islas Vírgenes Británicas",
		"es-CO": "Islas Vírgenes Británicas",
		"es-CR": "Islas Vírgenes Británicas",
		"es-CU": "Islas Vírgenes Británicas",
		"es-DO": "Islas Vírgenes Británicas",
		"es-EC": "Islas Vírgenes Británicas",
		"es-GT": "Islas Vírgenes Británicas",
		"es-HN": "Islas Vírgenes Británicas",
		"es-MX": "Islas Vírgenes Británicas",
		"es-NI": "Islas Vírgenes Británicas",
		"es-PA": "Islas Vírgenes Británicas",
		"es-PE": "Islas Vírgenes Británicas",
		"es-PR": "Islas Vírgenes Británicas",
		"es-PY": "Islas Vírgenes Británicas",
		"es-SV": "Islas Vírgenes Británicas",
		"es-US": "Islas Vírgenes Británicas",
		"es-UY": "Islas Vírgenes Británicas",
		"es-VE": "Islas Vírgenes Británicas",
		"fr-FR": "Îles Vierges britanniques",
		"fr-BE": "Îles Vierges britanniques",
		"fr-CH": "Îles Vierges britanniques",
		"fr-LU": "Îles Vierges britanniques",
		"fr-MC": "Îles Vierges britanniques",
		"fr-AD": "Îles Vierges britanniques",
		"fr-CA": "îles Vierges britanniques",
		"it-IT": "Isole Vergini Britanniche",
		"it-CH": "Isole Vergini Britanniche",
		"it-SM": "Isole Vergini Britanniche",
		"it-VA": "Isole Vergini Britanniche",
		"de-DE": "Britische Jungferninseln",
		"de-AT": "Britische Jungferninseln",
		"de-CH": "Britische Jungferninseln",
		"de-BE": "Britische Jungferninseln",
		"de-LI": "Britische Jungferninseln",
		"de-LU": "Britische Jungferninseln",
		"nl-NL": "Britse Maagdeneilanden",
		"nl-BE": "Britse Maagdeneilanden",
		"sv-SE": "Brittiska Jungfruöarna",
		"sv-FI": "Brittiska Jungfruöarna",
		"da-DK": "De Britiske Jomfruøer",
		"nb-NO": "De britiske jomfruøyene",
		"nn-NO": "Dei britiske Jomfruøyane",
		"fi-FI": "Brittiläiset Neitsytsaaret",
		"is-IS": "Bresku Jómfrúaeyjar",
		"fo-FO": "Stóra Bretlands Jomfrúoyggjar",
		"et-EE": "Briti Neitsisaared",
		"lv-LV": "Britu Virdžīnas",
		"lt-LT": "Didžiosios Britanijos Mergelių Salos",
		"pl-PL": "Brytyjskie Wyspy Dziewicze",
		"cs-CZ": "Britské Panenské ostrovy",
		"sk-SK": "Britské Panenské ostrovy",
		"sl-SI": "Britanski Deviški otoki",
		"hr-HR": "Britanski Djevičanski Otoci",
		"bs-BA": "Britanska Djevičanska ostrva",
		"sr-RS": "Британска Девичанска Острва",
		"sr-BA": "Британска Дјевичанска острва",
		"sr-ME": "Britanska Djevičanska Ostrva",
		"mk-MK": "Британски Девствени Острови",
		"bg-BG": "Британски Вирджински острови",
		"be-BY": "Брытанскія Віргінскія астравы",
		"uk-UA": "Британські Віргінські острови",
		"ru-RU": "Виргинские о-ва (Великобритания)",
		"el-GR": "Βρετανικές Παρθένες Νήσοι",
		"el-CY": "Βρετανικές Παρθένες Νήσοι",
		"ro-RO": "Insulele Virgine Britanice",
		"ro-MD": "Insulele Virgine Britanice",
		"hu-HU": "Brit Virgin-szigetek",
		"sq-AL": "Ishujt e Virgjër Britanikë",
		"sq-XK": "Ishujt e Virgjër Britanikë",
		"mt-MT": "il-Gżejjer Verġni Brittaniċi",
		"ga-IE": "Oileáin Bhriotanacha na Maighdean",
		"cy-GB": "Ynysoedd Gwyryf Prydain",
		"gd-GB": "Eileanan Breatannach na Maighdinn",
		"lb-LU": "Britesch Joffereninselen",
		"ca-ES": "Illes Verges Britàniques",
		"ca-AD": "Illes Verges Britàniques",
		"ca-FR": "Illes Verges Britàniques",
		"ca-IT": "Illes Verges Britàniques",
		"eu-ES": "Birjina uharte britainiarrak",
		"eu-FR": "Birjina uharte britainiarrak",
		"gl-ES": "Illas Virxes Británicas",
		"tr-TR": "Britanya Virjin Adaları",
		"tr-CY": "Britanya Virjin Adaları"
	},
	"callingCode": "1284",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
