import type { Country } from './types.js';

export const VIR = {
	"code": "VIR",
	"labels": {
		"pt-BR": "Ilhas Virgens Americanas",
		"pt-PT": "Ilhas Virgens dos EUA",
		"qu-PE": "EE.UU. Islas Vírgenes",
		"qu-BO": "EE.UU. Islas Vírgenes",
		"qu-EC": "EE.UU. Islas Vírgenes",
		"chr-US": "U.S. ᎠᏒᏂᎸ ᏂᎨᏒᎾ ᏚᎦᏚᏛᎢ",
		"hi-IN": "यू॰एस॰ वर्जिन द्वीपसमूह",
		"bn-IN": "মার্কিন যুক্তরাষ্ট্রীয় ভার্জিন দ্বীপপুঞ্জ",
		"bn-BD": "মার্কিন যুক্তরাষ্ট্রীয় ভার্জিন দ্বীপপুঞ্জ",
		"ta-IN": "யூ.எஸ். கன்னித் தீவுகள்",
		"ta-LK": "யூ.எஸ். கன்னித் தீவுகள்",
		"ta-SG": "யூ.எஸ். கன்னித் தீவுகள்",
		"ta-MY": "யூ.எஸ். கன்னித் தீவுகள்",
		"te-IN": "యు.ఎస్. వర్జిన్ దీవులు",
		"mr-IN": "यू.एस. व्हर्जिन बेटे",
		"gu-IN": "યુએસ વર્જિન આઇલેન્ડ્સ",
		"kn-IN": "ಯು.ಎಸ್. ವರ್ಜಿನ್ ದ್ವೀಪಗಳು",
		"ml-IN": "യു.എസ്. വെർജിൻ ദ്വീപുകൾ",
		"pa-IN": "ਯੂ ਐੱਸ ਵਰਜਿਨ ਟਾਪੂ",
		"ur-IN": "امریکی جزائر ورجن",
		"ur-PK": "امریکی ورجن آئلینڈز",
		"or-IN": "ଯୁକ୍ତରାଷ୍ଟ୍ର ଭର୍ଜିନ୍ ଦ୍ଵୀପପୁଞ୍ଜ",
		"as-IN": "ইউ. এছ. ভাৰ্জিন দ্বীপপুঞ্জ",
		"ne-IN": "संयुक्त राज्य भर्जिन टापुहरु",
		"ne-NP": "संयुक्त राज्य भर्जिन टापुहरु",
		"si-LK": "ඇමරිකානු වර්ජින් දූපත්",
		"kok-IN": "यु. एस. वर्जिन आयलँड्‍स",
		"ks-IN": "یوٗ ایس ؤرجِن جٔزیٖرٕ",
		"brx-IN": "इउ. एस भार्जिन द्वीपफोर",
		"mai-IN": "यू॰एस॰ वर्जिन द्वीपसमूह",
		"dz-BT": "ཝརཇིན་གླིང་ཚོམ་ ཡུ་ཨེས་ཨེ་མངའ་ཁོངས",
		"ja-JP": "米領ヴァージン諸島",
		"ko-KR": "미국령 버진아일랜드",
		"ko-KP": "미국령 버진아일랜드",
		"zh-CN": "美属维尔京群岛",
		"zh-Hans-CN": "美属维尔京群岛",
		"zh-Hant-TW": "美屬維京群島",
		"zh-TW": "美屬維京群島",
		"zh-HK": "美屬維爾京群島",
		"zh-MO": "美屬維爾京群島",
		"zh-SG": "美属维尔京群岛",
		"yue-Hant-HK": "美屬維京群島",
		"yue-Hans-CN": "美属维京群岛",
		"mn-MN": "АНУ-ын Виржиний арлууд",
		"ug-CN": "ئا ق ش ۋىرگىن ئاراللىرى",
		"th-TH": "หมู่เกาะเวอร์จินของสหรัฐอเมริกา",
		"lo-LA": "ໝູ່ເກາະ ເວີຈິນ ຂອງສະຫະລັດ",
		"km-KH": "កោះ​វឺជីន​អាមេរិក",
		"my-MM": "ယူအက်စ် ဗာဂျင်း ကျွန်းစု",
		"vi-VN": "Quần đảo Virgin thuộc Hoa Kỳ",
		"id-ID": "Kepulauan Virgin Amerika Serikat",
		"ms-MY": "Kepulauan Virgin A.S.",
		"ms-SG": "Kepulauan Virgin A.S.",
		"ms-BN": "Kepulauan Virgin A.S.",
		"jv-ID": "Kapuloan Virgin Amérika",
		"fil-PH": "U.S. Virgin Islands",
		"ceb-PH": "U.S. Virgin Islands",
		"ka-GE": "აშშ-ის ვირჯინის კუნძულები",
		"hy-AM": "ԱՄՆ Վիրջինյան կղզիներ",
		"az-AZ": "ABŞ Virgin adaları",
		"az-Cyrl-AZ": "АБШ Вирҝин адалары",
		"kk-KZ": "АҚШ-тың Виргин аралдары",
		"ky-KG": "Виргин аралдары (АКШ)",
		"uz-UZ": "AQSH Virgin orollari",
		"tg-TJ": "Ҷазираҳои Виргини ИМА",
		"tk-TM": "ABŞ-nyň Wirgin adalary",
		"fa-IR": "جزایر ویرجین ایالات متحده",
		"fa-AF": "جزایر ویرجین ایالات متحده",
		"ps-AF": "د متحده آيالاتو ورجن ټاپوګان",
		"ps-PK": "د متحده آيالاتو ورجن ټاپوګان",
		"he-IL": "איי הבתולה של ארצות הברית",
		"ar-SA": "جزر فيرجن الأمريكية",
		"ar-AE": "جزر فيرجن الأمريكية",
		"ar-QA": "جزر فيرجن الأمريكية",
		"ar-BH": "جزر فيرجن الأمريكية",
		"ar-KW": "جزر فيرجن الأمريكية",
		"ar-OM": "جزر فيرجن الأمريكية",
		"ar-YE": "جزر فيرجن الأمريكية",
		"ar-IQ": "جزر فيرجن الأمريكية",
		"ar-JO": "جزر فيرجن الأمريكية",
		"ar-LB": "جزر فيرجن الأمريكية",
		"ar-SY": "جزر فيرجن الأمريكية",
		"ar-PS": "جزر فيرجن الأمريكية",
		"en-US": "U.S. Virgin Islands",
		"en-GB": "US Virgin Islands",
		"en-IE": "US Virgin Islands",
		"en-MT": "US Virgin Islands",
		"en-GI": "US Virgin Islands",
		"en-CY": "US Virgin Islands",
		"en-JE": "US Virgin Islands",
		"en-GG": "US Virgin Islands",
		"en-IM": "US Virgin Islands",
		"en-CA": "US Virgin Islands",
		"en-AU": "US Virgin Islands",
		"en-NZ": "US Virgin Islands",
		"en-ZA": "US Virgin Islands",
		"en-IN": "US Virgin Islands",
		"en-SG": "US Virgin Islands",
		"pt-AO": "Ilhas Virgens dos EUA",
		"pt-MZ": "Ilhas Virgens dos EUA",
		"pt-CV": "Ilhas Virgens dos EUA",
		"pt-GW": "Ilhas Virgens dos EUA",
		"pt-ST": "Ilhas Virgens dos EUA",
		"pt-TL": "Ilhas Virgens dos EUA",
		"pt-MO": "Ilhas Virgens dos EUA",
		"es-ES": "Islas Vírgenes de EE. UU.",
		"es-419": "Islas Vírgenes de EE. UU.",
		"es-AD": "Islas Vírgenes de EE. UU.",
		"es-GI": "Islas Vírgenes de EE. UU.",
		"es-AR": "Islas Vírgenes de EE. UU.",
		"es-BO": "Islas Vírgenes de EE. UU.",
		"es-BR": "Islas Vírgenes de EE. UU.",
		"es-BZ": "Islas Vírgenes de EE. UU.",
		"es-CL": "Islas Vírgenes de EE. UU.",
		"es-CO": "Islas Vírgenes de EE. UU.",
		"es-CR": "Islas Vírgenes de EE. UU.",
		"es-CU": "Islas Vírgenes de EE. UU.",
		"es-DO": "Islas Vírgenes de EE. UU.",
		"es-EC": "Islas Vírgenes de EE. UU.",
		"es-GT": "Islas Vírgenes de EE. UU.",
		"es-HN": "Islas Vírgenes de EE. UU.",
		"es-MX": "Islas Vírgenes de EE. UU.",
		"es-NI": "Islas Vírgenes de EE. UU.",
		"es-PA": "Islas Vírgenes de EE. UU.",
		"es-PE": "Islas Vírgenes de EE. UU.",
		"es-PR": "Islas Vírgenes de EE. UU.",
		"es-PY": "Islas Vírgenes de EE. UU.",
		"es-SV": "Islas Vírgenes de EE. UU.",
		"es-US": "Islas Vírgenes de EE. UU.",
		"es-UY": "Islas Vírgenes de EE. UU.",
		"es-VE": "Islas Vírgenes de EE. UU.",
		"fr-FR": "Îles Vierges des États-Unis",
		"fr-BE": "Îles Vierges des États-Unis",
		"fr-CH": "Îles Vierges des États-Unis",
		"fr-LU": "Îles Vierges des États-Unis",
		"fr-MC": "Îles Vierges des États-Unis",
		"fr-AD": "Îles Vierges des États-Unis",
		"fr-CA": "îles Vierges américaines",
		"it-IT": "Isole Vergini Americane",
		"it-CH": "Isole Vergini Americane",
		"it-SM": "Isole Vergini Americane",
		"it-VA": "Isole Vergini Americane",
		"de-DE": "Amerikanische Jungferninseln",
		"de-AT": "Amerikanische Jungferninseln",
		"de-CH": "Amerikanische Jungferninseln",
		"de-BE": "Amerikanische Jungferninseln",
		"de-LI": "Amerikanische Jungferninseln",
		"de-LU": "Amerikanische Jungferninseln",
		"nl-NL": "Amerikaanse Maagdeneilanden",
		"nl-BE": "Amerikaanse Maagdeneilanden",
		"sv-SE": "Amerikanska Jungfruöarna",
		"sv-FI": "Amerikanska Jungfruöarna",
		"da-DK": "De Amerikanske Jomfruøer",
		"nb-NO": "De amerikanske jomfruøyene",
		"nn-NO": "Dei amerikanske Jomfruøyane",
		"fi-FI": "Yhdysvaltain Neitsytsaaret",
		"is-IS": "Bandarísku Jómfrúaeyjar",
		"fo-FO": "Sambandsríki Amerikas Jomfrúoyggjar",
		"et-EE": "USA Neitsisaared",
		"lv-LV": "ASV Virdžīnas",
		"lt-LT": "Jungtinių Valstijų Mergelių Salos",
		"pl-PL": "Wyspy Dziewicze Stanów Zjednoczonych",
		"cs-CZ": "Americké Panenské ostrovy",
		"sk-SK": "Americké Panenské ostrovy",
		"sl-SI": "Ameriški Deviški otoki",
		"hr-HR": "Američki Djevičanski Otoci",
		"bs-BA": "Američka Djevičanska ostrva",
		"sr-RS": "Америчка Девичанска Острва",
		"sr-BA": "Америчка Дјевичанска острва",
		"sr-ME": "Američka Djevičanska Ostrva",
		"mk-MK": "Американски Девствени Острови",
		"bg-BG": "Американски Вирджински острови",
		"be-BY": "Амерыканскія Віргінскія астравы",
		"uk-UA": "Віргінські Острови (США)",
		"ru-RU": "Виргинские о-ва (США)",
		"el-GR": "Αμερικανικές Παρθένες Νήσοι",
		"el-CY": "Αμερικανικές Παρθένες Νήσοι",
		"ro-RO": "Insulele Virgine Americane",
		"ro-MD": "Insulele Virgine Americane",
		"hu-HU": "Amerikai Virgin-szigetek",
		"sq-AL": "Ishujt e Virgjër të SHBA-së",
		"sq-XK": "Ishujt e Virgjër të SHBA-së",
		"mt-MT": "il-Gżejjer Verġni tal-Istati Uniti",
		"ga-IE": "Oileáin Mheiriceánacha na Maighdean",
		"cy-GB": "Ynysoedd Gwyryf yr Unol Daleithiau",
		"gd-GB": "Eileanan na Maighdinn aig na SA",
		"lb-LU": "Amerikanesch Joffereninselen",
		"ca-ES": "Illes Verges dels Estats Units",
		"ca-AD": "Illes Verges dels Estats Units",
		"ca-FR": "Illes Verges dels Estats Units",
		"ca-IT": "Illes Verges dels Estats Units",
		"eu-ES": "Birjina uharte amerikarrak",
		"eu-FR": "Birjina uharte amerikarrak",
		"gl-ES": "Illas Virxes Estadounidenses",
		"tr-TR": "ABD Virjin Adaları",
		"tr-CY": "ABD Virjin Adaları"
	},
	"callingCode": "1340",
	"phoneMasks": [
		{
			"mask": "###-####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"[2-9]"
			]
		}
	]
} satisfies Country;
