import type { Country } from './types.js';

export const VIR = {
	"code": "VIR",
	"labels": {
		"pt-BR": "Ilhas Virgens Americanas",
		"pt-PT": "Ilhas Virgens dos EUA",
		"es-ES": "Islas Vírgenes de EE. UU.",
		"es-419": "Islas Vírgenes de EE. UU.",
		"es-AR": "Islas Vírgenes de EE. UU.",
		"es-BO": "Islas Vírgenes de EE. UU.",
		"es-BR": "Islas Vírgenes de EE. UU.",
		"es-BZ": "Islas Vírgenes de EE. UU.",
		"es-CL": "Islas Vírgenes de EE. UU.",
		"es-CO": "Islas Vírgenes de EE. UU.",
		"es-CR": "Islas Vírgenes de EE. UU.",
		"es-CU": "Islas Vírgenes de EE. UU.",
		"es-DO": "Islas Vírgenes de EE. UU.",
		"es-EC": "Islas Vírgenes de EE. UU.",
		"es-GT": "Islas Vírgenes de EE. UU.",
		"es-HN": "Islas Vírgenes de EE. UU.",
		"es-MX": "Islas Vírgenes de EE. UU.",
		"es-NI": "Islas Vírgenes de EE. UU.",
		"es-PA": "Islas Vírgenes de EE. UU.",
		"es-PE": "Islas Vírgenes de EE. UU.",
		"es-PR": "Islas Vírgenes de EE. UU.",
		"es-PY": "Islas Vírgenes de EE. UU.",
		"es-SV": "Islas Vírgenes de EE. UU.",
		"es-US": "Islas Vírgenes de EE. UU.",
		"es-UY": "Islas Vírgenes de EE. UU.",
		"es-VE": "Islas Vírgenes de EE. UU.",
		"en-US": "U.S. Virgin Islands",
		"fr-FR": "Îles Vierges des États-Unis",
		"fr-BE": "Îles Vierges des États-Unis",
		"fr-CA": "îles Vierges américaines",
		"fr-CH": "Îles Vierges des États-Unis",
		"fr-LU": "Îles Vierges des États-Unis",
		"fr-MC": "Îles Vierges des États-Unis",
		"it-IT": "Isole Vergini Americane",
		"it-CH": "Isole Vergini Americane",
		"it-SM": "Isole Vergini Americane",
		"it-VA": "Isole Vergini Americane",
		"de-DE": "Amerikanische Jungferninseln",
		"de-AT": "Amerikanische Jungferninseln",
		"de-CH": "Amerikanische Jungferninseln",
		"de-BE": "Amerikanische Jungferninseln",
		"de-LI": "Amerikanische Jungferninseln",
		"de-LU": "Amerikanische Jungferninseln"
	}
} satisfies Country;
