import type { Country } from './types.js';

export const WLF = {
	"code": "WLF",
	"labels": {
		"pt-BR": "Wallis e Futuna",
		"pt-PT": "Wallis e Futuna",
		"es-ES": "Wallis y Futuna",
		"es-419": "Wallis y Futuna",
		"es-AR": "Wallis y Futuna",
		"es-BO": "Wallis y Futuna",
		"es-BR": "Wallis y Futuna",
		"es-BZ": "Wallis y Futuna",
		"es-CL": "Wallis y Futuna",
		"es-CO": "Wallis y Futuna",
		"es-CR": "Wallis y Futuna",
		"es-CU": "Wallis y Futuna",
		"es-DO": "Wallis y Futuna",
		"es-EC": "Wallis y Futuna",
		"es-GT": "Wallis y Futuna",
		"es-HN": "Wallis y Futuna",
		"es-MX": "Wallis y Futuna",
		"es-NI": "Wallis y Futuna",
		"es-PA": "Wallis y Futuna",
		"es-PE": "Wallis y Futuna",
		"es-PR": "Wallis y Futuna",
		"es-PY": "Wallis y Futuna",
		"es-SV": "Wallis y Futuna",
		"es-US": "Wallis y Futuna",
		"es-UY": "Wallis y Futuna",
		"es-VE": "Wallis y Futuna",
		"en-US": "Wallis & Futuna",
		"fr-FR": "Wallis-et-Futuna",
		"fr-BE": "Wallis-et-Futuna",
		"fr-CA": "Wallis-et-Futuna",
		"fr-CH": "Wallis-et-Futuna",
		"fr-LU": "Wallis-et-Futuna",
		"fr-MC": "Wallis-et-Futuna",
		"it-IT": "Wallis e Futuna",
		"it-CH": "Wallis e Futuna",
		"it-SM": "Wallis e Futuna",
		"it-VA": "Wallis e Futuna",
		"de-DE": "Wallis und Futuna",
		"de-AT": "Wallis und Futuna",
		"de-CH": "Wallis und Futuna",
		"de-BE": "Wallis und Futuna",
		"de-LI": "Wallis und Futuna",
		"de-LU": "Wallis und Futuna"
	}
} satisfies Country;
