import type { Country } from './types.js';

export const WSM = {
	"code": "WSM",
	"labels": {
		"pt-BR": "Samoa",
		"pt-PT": "Samoa",
		"qu-PE": "Samoa",
		"qu-BO": "Samoa",
		"qu-EC": "Samoa",
		"chr-US": "ᏌᎼᎠ",
		"hi-IN": "समोआ",
		"bn-IN": "সামোয়া",
		"bn-BD": "সামোয়া",
		"ta-IN": "சமோவா",
		"ta-LK": "சமோவா",
		"ta-SG": "சமோவா",
		"ta-MY": "சமோவா",
		"te-IN": "సమోవా",
		"mr-IN": "सामोआ",
		"gu-IN": "સમોઆ",
		"kn-IN": "ಸಮೋವಾ",
		"ml-IN": "സമോവ",
		"pa-IN": "ਸਾਮੋਆ",
		"ur-IN": "ساموآ",
		"ur-PK": "ساموآ",
		"or-IN": "ସାମୋଆ",
		"as-IN": "চামোৱা",
		"ne-IN": "सामोआ",
		"ne-NP": "सामोआ",
		"si-LK": "සැමෝවා",
		"kok-IN": "सामोआ",
		"ks-IN": "سامو",
		"brx-IN": "सामआ",
		"mai-IN": "समोआ",
		"dz-BT": "ས་མོ་ཨ",
		"ja-JP": "サモア",
		"ko-KR": "사모아",
		"ko-KP": "사모아",
		"zh-CN": "萨摩亚",
		"zh-Hans-CN": "萨摩亚",
		"zh-Hant-TW": "薩摩亞",
		"zh-TW": "薩摩亞",
		"zh-HK": "薩摩亞",
		"zh-MO": "薩摩亞",
		"zh-SG": "萨摩亚",
		"yue-Hant-HK": "薩摩亞",
		"yue-Hans-CN": "萨摩亚",
		"mn-MN": "Самоа",
		"ug-CN": "ساموئا",
		"th-TH": "ซามัว",
		"lo-LA": "ຊາມົວ",
		"km-KH": "សាម័រ",
		"my-MM": "ဆမိုးအား",
		"vi-VN": "Samoa",
		"id-ID": "Samoa",
		"ms-MY": "Samoa",
		"ms-SG": "Samoa",
		"ms-BN": "Samoa",
		"jv-ID": "Samoa",
		"fil-PH": "Samoa",
		"ceb-PH": "Samoa",
		"ka-GE": "სამოა",
		"hy-AM": "Սամոա",
		"az-AZ": "Samoa",
		"az-Cyrl-AZ": "Самоа",
		"kk-KZ": "Самоа",
		"ky-KG": "Самоа",
		"uz-UZ": "Samoa",
		"tg-TJ": "Самоа",
		"tk-TM": "Samoa",
		"fa-IR": "ساموآ",
		"fa-AF": "ساموآ",
		"ps-AF": "ساماوا",
		"ps-PK": "ساماوا",
		"he-IL": "סמואה",
		"ar-SA": "ساموا",
		"ar-AE": "ساموا",
		"ar-QA": "ساموا",
		"ar-BH": "ساموا",
		"ar-KW": "ساموا",
		"ar-OM": "ساموا",
		"ar-YE": "ساموا",
		"ar-IQ": "ساموا",
		"ar-JO": "ساموا",
		"ar-LB": "ساموا",
		"ar-SY": "ساموا",
		"ar-PS": "ساموا",
		"en-US": "Samoa",
		"en-GB": "Samoa",
		"en-IE": "Samoa",
		"en-MT": "Samoa",
		"en-GI": "Samoa",
		"en-CY": "Samoa",
		"en-JE": "Samoa",
		"en-GG": "Samoa",
		"en-IM": "Samoa",
		"en-CA": "Samoa",
		"en-AU": "Samoa",
		"en-NZ": "Samoa",
		"en-ZA": "Samoa",
		"en-IN": "Samoa",
		"en-SG": "Samoa",
		"pt-AO": "Samoa",
		"pt-MZ": "Samoa",
		"pt-CV": "Samoa",
		"pt-GW": "Samoa",
		"pt-ST": "Samoa",
		"pt-TL": "Samoa",
		"pt-MO": "Samoa",
		"es-ES": "Samoa",
		"es-419": "Samoa",
		"es-AD": "Samoa",
		"es-GI": "Samoa",
		"es-AR": "Samoa",
		"es-BO": "Samoa",
		"es-BR": "Samoa",
		"es-BZ": "Samoa",
		"es-CL": "Samoa",
		"es-CO": "Samoa",
		"es-CR": "Samoa",
		"es-CU": "Samoa",
		"es-DO": "Samoa",
		"es-EC": "Samoa",
		"es-GT": "Samoa",
		"es-HN": "Samoa",
		"es-MX": "Samoa",
		"es-NI": "Samoa",
		"es-PA": "Samoa",
		"es-PE": "Samoa",
		"es-PR": "Samoa",
		"es-PY": "Samoa",
		"es-SV": "Samoa",
		"es-US": "Samoa",
		"es-UY": "Samoa",
		"es-VE": "Samoa",
		"fr-FR": "Samoa",
		"fr-BE": "Samoa",
		"fr-CH": "Samoa",
		"fr-LU": "Samoa",
		"fr-MC": "Samoa",
		"fr-AD": "Samoa",
		"fr-CA": "Samoa",
		"it-IT": "Samoa",
		"it-CH": "Samoa",
		"it-SM": "Samoa",
		"it-VA": "Samoa",
		"de-DE": "Samoa",
		"de-AT": "Samoa",
		"de-CH": "Samoa",
		"de-BE": "Samoa",
		"de-LI": "Samoa",
		"de-LU": "Samoa",
		"nl-NL": "Samoa",
		"nl-BE": "Samoa",
		"sv-SE": "Samoa",
		"sv-FI": "Samoa",
		"da-DK": "Samoa",
		"nb-NO": "Samoa",
		"nn-NO": "Samoa",
		"fi-FI": "Samoa",
		"is-IS": "Samóa",
		"fo-FO": "Samoa",
		"et-EE": "Samoa",
		"lv-LV": "Samoa",
		"lt-LT": "Samoa",
		"pl-PL": "Samoa",
		"cs-CZ": "Samoa",
		"sk-SK": "Samoa",
		"sl-SI": "Samoa",
		"hr-HR": "Samoa",
		"bs-BA": "Samoa",
		"sr-RS": "Самоа",
		"sr-BA": "Самоа",
		"sr-ME": "Samoa",
		"mk-MK": "Самоа",
		"bg-BG": "Самоа",
		"be-BY": "Самоа",
		"uk-UA": "Самоа",
		"ru-RU": "Самоа",
		"el-GR": "Σαμόα",
		"el-CY": "Σαμόα",
		"ro-RO": "Samoa",
		"ro-MD": "Samoa",
		"hu-HU": "Szamoa",
		"sq-AL": "Samoa",
		"sq-XK": "Samoa",
		"mt-MT": "Samoa",
		"ga-IE": "Samó",
		"cy-GB": "Samoa",
		"gd-GB": "Samotha",
		"lb-LU": "Samoa",
		"ca-ES": "Samoa",
		"ca-AD": "Samoa",
		"ca-FR": "Samoa",
		"ca-IT": "Samoa",
		"eu-ES": "Samoa",
		"eu-FR": "Samoa",
		"gl-ES": "Samoa",
		"tr-TR": "Samoa",
		"tr-CY": "Samoa"
	},
	"callingCode": "685",
	"phoneMasks": [
		{
			"mask": "#####",
			"minLength": 5,
			"maxLength": 5,
			"leadingDigits": [
				"[2-5]|6[1-9]"
			]
		},
		{
			"mask": "### ###",
			"minLength": 6,
			"maxLength": 6
		},
		{
			"mask": "## #####",
			"minLength": 7,
			"maxLength": 7,
			"leadingDigits": [
				"7"
			]
		},
		{
			"mask": "### #######",
			"minLength": 10,
			"maxLength": 10,
			"leadingDigits": [
				"[68]"
			]
		}
	]
} satisfies Country;
