import type { Country } from './types.js';

export const YEM = {
	"code": "YEM",
	"labels": {
		"pt-BR": "Iêmen",
		"pt-PT": "Iémen",
		"es-ES": "Yemen",
		"es-419": "Yemen",
		"es-AR": "Yemen",
		"es-BO": "Yemen",
		"es-BR": "Yemen",
		"es-BZ": "Yemen",
		"es-CL": "Yemen",
		"es-CO": "Yemen",
		"es-CR": "Yemen",
		"es-CU": "Yemen",
		"es-DO": "Yemen",
		"es-EC": "Yemen",
		"es-GT": "Yemen",
		"es-HN": "Yemen",
		"es-MX": "Yemen",
		"es-NI": "Yemen",
		"es-PA": "Yemen",
		"es-PE": "Yemen",
		"es-PR": "Yemen",
		"es-PY": "Yemen",
		"es-SV": "Yemen",
		"es-US": "Yemen",
		"es-UY": "Yemen",
		"es-VE": "Yemen",
		"en-US": "Yemen",
		"fr-FR": "Yémen",
		"fr-BE": "Yémen",
		"fr-CA": "Yémen",
		"fr-CH": "Yémen",
		"fr-LU": "Yémen",
		"fr-MC": "Yémen",
		"it-IT": "Yemen",
		"it-CH": "Yemen",
		"it-SM": "Yemen",
		"it-VA": "Yemen",
		"de-DE": "Jemen",
		"de-AT": "Jemen",
		"de-CH": "Jemen",
		"de-BE": "Jemen",
		"de-LI": "Jemen",
		"de-LU": "Jemen"
	}
} satisfies Country;
