import type { Country } from './types.js';

export const ZAF = {
	"code": "ZAF",
	"labels": {
		"pt-BR": "África do Sul",
		"pt-PT": "África do Sul",
		"es-ES": "Sudáfrica",
		"es-419": "Sudáfrica",
		"es-AR": "Sudáfrica",
		"es-BO": "Sudáfrica",
		"es-BR": "Sudáfrica",
		"es-BZ": "Sudáfrica",
		"es-CL": "Sudáfrica",
		"es-CO": "Sudáfrica",
		"es-CR": "Sudáfrica",
		"es-CU": "Sudáfrica",
		"es-DO": "Sudáfrica",
		"es-EC": "Sudáfrica",
		"es-GT": "Sudáfrica",
		"es-HN": "Sudáfrica",
		"es-MX": "Sudáfrica",
		"es-NI": "Sudáfrica",
		"es-PA": "Sudáfrica",
		"es-PE": "Sudáfrica",
		"es-PR": "Sudáfrica",
		"es-PY": "Sudáfrica",
		"es-SV": "Sudáfrica",
		"es-US": "Sudáfrica",
		"es-UY": "Sudáfrica",
		"es-VE": "Sudáfrica",
		"en-US": "South Africa",
		"fr-FR": "Afrique du Sud",
		"fr-BE": "Afrique du Sud",
		"fr-CA": "Afrique du Sud",
		"fr-CH": "Afrique du Sud",
		"fr-LU": "Afrique du Sud",
		"fr-MC": "Afrique du Sud",
		"it-IT": "Sudafrica",
		"it-CH": "Sudafrica",
		"it-SM": "Sudafrica",
		"it-VA": "Sudafrica",
		"de-DE": "Südafrika",
		"de-AT": "Südafrika",
		"de-CH": "Südafrika",
		"de-BE": "Südafrika",
		"de-LI": "Südafrika",
		"de-LU": "Südafrika"
	},
	"callingCode": "27"
} satisfies Country;
