import type { Country } from './types.js';

export const ZMB = {
	"code": "ZMB",
	"labels": {
		"pt-BR": "Zâmbia",
		"pt-PT": "Zâmbia",
		"es-ES": "Zambia",
		"es-419": "Zambia",
		"es-AR": "Zambia",
		"es-BO": "Zambia",
		"es-BR": "Zambia",
		"es-BZ": "Zambia",
		"es-CL": "Zambia",
		"es-CO": "Zambia",
		"es-CR": "Zambia",
		"es-CU": "Zambia",
		"es-DO": "Zambia",
		"es-EC": "Zambia",
		"es-GT": "Zambia",
		"es-HN": "Zambia",
		"es-MX": "Zambia",
		"es-NI": "Zambia",
		"es-PA": "Zambia",
		"es-PE": "Zambia",
		"es-PR": "Zambia",
		"es-PY": "Zambia",
		"es-SV": "Zambia",
		"es-US": "Zambia",
		"es-UY": "Zambia",
		"es-VE": "Zambia",
		"en-US": "Zambia",
		"fr-FR": "Zambie",
		"fr-BE": "Zambie",
		"fr-CA": "Zambie",
		"fr-CH": "Zambie",
		"fr-LU": "Zambie",
		"fr-MC": "Zambie",
		"it-IT": "Zambia",
		"it-CH": "Zambia",
		"it-SM": "Zambia",
		"it-VA": "Zambia",
		"de-DE": "Sambia",
		"de-AT": "Sambia",
		"de-CH": "Sambia",
		"de-BE": "Sambia",
		"de-LI": "Sambia",
		"de-LU": "Sambia"
	}
} satisfies Country;
