import type { Country } from './types.js';

export const ZWE = {
	"code": "ZWE",
	"labels": {
		"pt-BR": "Zimbábue",
		"pt-PT": "Zimbabué",
		"es-ES": "Zimbabue",
		"es-419": "Zimbabue",
		"es-AR": "Zimbabue",
		"es-BO": "Zimbabue",
		"es-BR": "Zimbabue",
		"es-BZ": "Zimbabue",
		"es-CL": "Zimbabue",
		"es-CO": "Zimbabue",
		"es-CR": "Zimbabue",
		"es-CU": "Zimbabue",
		"es-DO": "Zimbabue",
		"es-EC": "Zimbabue",
		"es-GT": "Zimbabue",
		"es-HN": "Zimbabue",
		"es-MX": "Zimbabue",
		"es-NI": "Zimbabue",
		"es-PA": "Zimbabue",
		"es-PE": "Zimbabue",
		"es-PR": "Zimbabue",
		"es-PY": "Zimbabue",
		"es-SV": "Zimbabue",
		"es-US": "Zimbabue",
		"es-UY": "Zimbabue",
		"es-VE": "Zimbabue",
		"en-US": "Zimbabwe",
		"fr-FR": "Zimbabwe",
		"fr-BE": "Zimbabwe",
		"fr-CA": "Zimbabwe",
		"fr-CH": "Zimbabwe",
		"fr-LU": "Zimbabwe",
		"fr-MC": "Zimbabwe",
		"it-IT": "Zimbabwe",
		"it-CH": "Zimbabwe",
		"it-SM": "Zimbabwe",
		"it-VA": "Zimbabwe",
		"de-DE": "Simbabwe",
		"de-AT": "Simbabwe",
		"de-CH": "Zimbabwe",
		"de-BE": "Simbabwe",
		"de-LI": "Simbabwe",
		"de-LU": "Simbabwe"
	},
	"callingCode": "263"
} satisfies Country;
